/-
Copyright (c) 2026 SGAenglishpluslean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SGAenglishpluslean contributors
-/
import SGA.SGA2.ExposeII.Torsion

/-!
# SGA 2, Exposé II, (7.4)–(7.5): powers of a finite family

For a finite family `f`, the ideals generated by the `f a ^ n` are cofinal
with the powers of the ideal generated by `f`. Consequently ideal-power
torsion consists precisely of elements killed by one common power of every
generator. These are the ideal and annihilator calculations used in (7.4)
and (7.5); the comparison with a Koszul complex is separate.
-/

universe u v w

namespace SGA.SGA2.ExposeII

variable {R : Type u} [CommRing R] {ι : Type v} (f : ι → R)

/-- The ideal `(fₐⁿ)` in II.(7.4). -/
def generatorPowerIdeal (n : ℕ) : Ideal R :=
  Ideal.span (Set.range fun a => f a ^ n)

/-- Powers of the individual generators lie in the corresponding ideal power. -/
theorem generatorPowerIdeal_le_pow (n : ℕ) :
    generatorPowerIdeal f n ≤ Ideal.span (Set.range f) ^ n := by
  apply Ideal.span_le.mpr
  rintro _ ⟨a, rfl⟩
  exact Ideal.pow_mem_pow (Ideal.subset_span (Set.mem_range_self a)) n

/-- The ideals `(fₐⁿ)` form a decreasing sequence. -/
theorem generatorPowerIdeal_antitone : Antitone (generatorPowerIdeal f) := by
  intro n m hnm
  apply Ideal.span_le.mpr
  rintro _ ⟨a, rfl⟩
  change f a ^ m ∈ generatorPowerIdeal f n
  rw [← Nat.add_sub_of_le hnm, pow_add]
  exact Ideal.mul_mem_right _ _ (Ideal.subset_span (Set.mem_range_self a))

/-- The original generators lie in the radical of every generator-power ideal. -/
theorem span_le_radical_generatorPowerIdeal (n : ℕ) :
    Ideal.span (Set.range f) ≤ (generatorPowerIdeal f n).radical := by
  apply Ideal.span_le.mpr
  rintro _ ⟨a, rfl⟩
  exact ⟨n, Ideal.subset_span (Set.mem_range_self a)⟩

/-- Positive powers of the generators define the same radical. -/
theorem generatorPowerIdeal_radical (n : ℕ) (hn : n ≠ 0) :
    (generatorPowerIdeal f n).radical = (Ideal.span (Set.range f)).radical := by
  apply le_antisymm
  · exact Ideal.radical_mono
      ((generatorPowerIdeal_le_pow f n).trans (Ideal.pow_le_self hn))
  · exact Ideal.radical_le_radical_iff.mpr (span_le_radical_generatorPowerIdeal f n)

/-- II.(7.4): every generator-power ideal contains an ordinary ideal power.
Finite generation suffices; the ring need not be noetherian. -/
theorem exists_pow_le_generatorPowerIdeal [Finite ι] (n : ℕ) :
    ∃ k : ℕ, Ideal.span (Set.range f) ^ k ≤ generatorPowerIdeal f n := by
  apply Ideal.exists_pow_le_of_le_radical_of_fg
  · exact span_le_radical_generatorPowerIdeal f n
  · exact Submodule.fg_span (Set.finite_range f)

/-- The two decreasing sequences of ideals in II.(7.4) are cofinal. -/
theorem generatorPowerIdeal_cofinal [Finite ι] :
    (∀ n : ℕ, ∃ k : ℕ, generatorPowerIdeal f k ≤ Ideal.span (Set.range f) ^ n) ∧
      (∀ n : ℕ, ∃ k : ℕ, Ideal.span (Set.range f) ^ k ≤ generatorPowerIdeal f n) :=
  ⟨fun n => ⟨n, generatorPowerIdeal_le_pow f n⟩,
    exists_pow_le_generatorPowerIdeal f⟩

variable (M : Type w) [AddCommGroup M] [Module R M]

/-- An element is annihilated by `(fₐⁿ)` exactly when each `fₐⁿ` kills it. -/
theorem mem_torsionBySet_generatorPowerIdeal_iff (n : ℕ) (x : M) :
    x ∈ Submodule.torsionBySet R M (generatorPowerIdeal f n) ↔
      ∀ a, f a ^ n • x = 0 := by
  rw [generatorPowerIdeal, ← Submodule.torsionBySet_eq_torsionBySet_span]
  simp only [Submodule.mem_torsionBySet_iff, SetCoe.forall, Set.mem_range,
    forall_exists_index, forall_apply_eq_imp_iff]

/-- II.(7.5), elementwise form using the actual finite family of generators. -/
theorem mem_powerTorsion_span_iff [Finite ι] (x : M) :
    x ∈ powerTorsion (Ideal.span (Set.range f)) M ↔
      ∃ n : ℕ, ∀ a, f a ^ n • x = 0 := by
  constructor
  · intro hx
    obtain ⟨n, hn⟩ := (mem_powerTorsion_iff _ M x).mp hx
    exact ⟨n, fun a => hn _ (Ideal.pow_mem_pow
      (Ideal.subset_span (Set.mem_range_self a)) n)⟩
  · rintro ⟨n, hn⟩
    obtain ⟨k, hk⟩ := exists_pow_le_generatorPowerIdeal f n
    have hx := (mem_torsionBySet_generatorPowerIdeal_iff f M n x).mpr hn
    refine (mem_powerTorsion_iff _ M x).mpr ⟨k, fun a ha => ?_⟩
    exact (Submodule.mem_torsionBySet_iff _ _).mp hx ⟨a, hk ha⟩

/-- For a finite family, separate annihilating powers of the generators
can be replaced by a common ideal power. -/
theorem mem_powerTorsion_span_iff_forall [Finite ι] (x : M) :
    x ∈ powerTorsion (Ideal.span (Set.range f)) M ↔
      ∀ a, ∃ n : ℕ, f a ^ n • x = 0 := by
  constructor
  · intro hx a
    obtain ⟨n, hn⟩ := (mem_powerTorsion_span_iff f M x).mp hx
    exact ⟨n, hn a⟩
  · intro hx
    let J : Ideal R := (LinearMap.toSpanSingleton R M x).ker
    have hJ : Ideal.span (Set.range f) ≤ J.radical := by
      apply Ideal.span_le.mpr
      rintro _ ⟨a, rfl⟩
      obtain ⟨n, hn⟩ := hx a
      exact ⟨n, hn⟩
    obtain ⟨n, hn⟩ := Ideal.exists_pow_le_of_le_radical_of_fg hJ
      (Submodule.fg_span (Set.finite_range f))
    exact (mem_powerTorsion_iff _ M x).mpr ⟨n, fun a ha => hn ha⟩

/-- The union of the annihilators in II.(7.5) is the ideal-power torsion module. -/
theorem iSup_torsionBySet_generatorPowerIdeal [Finite ι] :
    (⨆ n : ℕ, Submodule.torsionBySet R M (generatorPowerIdeal f n)) =
      powerTorsion (Ideal.span (Set.range f)) M := by
  have hmono : Monotone fun n : ℕ =>
      Submodule.torsionBySet R M (generatorPowerIdeal f n) :=
    fun _ _ h => Submodule.torsionBySet_le_torsionBySet_of_subset
      (generatorPowerIdeal_antitone f h)
  ext x
  rw [Submodule.mem_iSup_of_directed _ hmono.directed_le, mem_powerTorsion_span_iff]
  simp only [mem_torsionBySet_generatorPowerIdeal_iff]

end SGA.SGA2.ExposeII
