/-
Copyright (c) 2026 SGAenglishpluslean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SGAenglishpluslean contributors
-/
import SGA.SGA2.ExposeII.FiniteGeneratorColimits
import SGA.SGA2.ExposeII.TorsionColimit

/-!
# SGA 2, Exposé II, (7.5): the Hom colimit for powers of generators

For a finite family `f`, the categorical colimit of `Hom_R(R/(fₐ^n), -)`
is naturally isomorphic to ideal-power torsion for the ideal generated by `f`.
The proof reindexes along the cofinality established in II.(7.4), and then
uses the evaluation-at-`1` comparison for ordinary ideal powers.

This proves the algebraic Hom/annihilator part of II.(7.5).
`KoszulCohomologyZero.lean` identifies it with degree-zero Koszul cohomology.
-/

noncomputable section

universe u v

open CategoryTheory Limits Opposite

namespace SGA.SGA2.ExposeII

variable {R : Type u} [CommRing R] {ι : Type v} (f : ι → R)

/-- The Hom diagram `Hom_R(R/(fₐ^n), -)` in II.(7.5). -/
def generatorHomDiagram : (ℕᵒᵖ)ᵒᵖ ⥤ ModuleCat.{u} R ⥤ ModuleCat.{u} R :=
  (localCohomology.ringModIdeals (generatorPowersDiagram f)).op ⋙
    linearCoyoneda R (ModuleCat.{u} R)

/-- Replacing powers of generators with ordinary ideal powers preserves
the Hom colimit, naturally in the coefficient module. -/
def generatorHomColimitIsoIdealPowers [Finite ι] :
    colimit (generatorHomDiagram f) ≅
      colimit (quotientHomDiagram (Ideal.span (Set.range f))) := by
  let I := Ideal.span (Set.range f)
  letI := idealPowersToSelfLERadical_initial_of_fg I
    (Submodule.fg_span (Set.finite_range f))
  let D := (localCohomology.ringModIdeals
      (localCohomology.selfLERadicalDiagram I)).op ⋙ linearCoyoneda R (ModuleCat.{u} R)
  exact Functor.Final.colimitIso (generatorPowersToSelfLERadical f).op D ≪≫
    (Functor.Final.colimitIso (localCohomology.idealPowersToSelfLERadical I).op D).symm

/-- II.(7.5), algebraic Hom/annihilator comparison for a finite family:
`colim_n Hom_R(R/(fₐ^n), -) ≅ Γ_I(-)` for `I = (fₐ)`. -/
def generatorHomColimitIso [Finite ι] :
    colimit (generatorHomDiagram f) ≅ powerTorsionFunctor (Ideal.span (Set.range f)) :=
  generatorHomColimitIsoIdealPowers f ≪≫ quotientHomColimitIso (Ideal.span (Set.range f))

end SGA.SGA2.ExposeII
