/-
Copyright (c) 2026 SGAenglishpluslean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SGAenglishpluslean contributors
-/
import SGA.SGA2.ExposeII.KoszulComplex
import Mathlib.RingTheory.Ideal.Span

/-!
# SGA 2, Exposé II, (7.5): zeroth Koszul homology

For the Koszul complex over the ring, the degree-zero term is the ring and
the image of its first differential is the ideal generated by the list.
Thus its zeroth homology is the quotient by that ideal.
-/

noncomputable section

universe u

open CategoryTheory Limits HomologicalComplex

namespace SGA.SGA2.ExposeII

set_option backward.isDefEq.respectTransparency false

variable {R : Type u} [CommRing R]

/-- The image of the first cofiber differential is the sum of the two
incoming images, after identifying degree zero with the target term. -/
theorem cofiber_boundary_range
    {F G : ChainComplex (ModuleCat.{u} R) ℕ} (φ : F ⟶ G)
    {N : ModuleCat.{u} R} (t : G.X 0 ⟶ N) :
    LinearMap.range (((homotopyCofiber φ).d 1 0 ≫ homotopyCofiber.sndX φ 0 ≫ t).hom) =
      LinearMap.range ((φ.f 0 ≫ t).hom) ⊔ LinearMap.range ((G.d 1 0 ≫ t).hom) := by
  let B := (homotopyCofiber φ).d 1 0 ≫ homotopyCofiber.sndX φ 0 ≫ t
  let p := φ.f 0 ≫ t
  let q := G.d 1 0 ≫ t
  have hB : B = homotopyCofiber.fstX φ 1 0 (by simp) ≫ p +
      homotopyCofiber.sndX φ 1 ≫ q := by
    dsimp [B, p, q]
    rw [← Category.assoc, homotopyCofiber.d_sndX φ 1 0 (by simp)]
    simp only [Preadditive.add_comp, Category.assoc]
  have hp : homotopyCofiber.inlX φ 0 1 (by simp) ≫ B = p := by
    rw [hB]
    simp only [Preadditive.comp_add, ← Category.assoc,
      homotopyCofiber.inlX_fstX, homotopyCofiber.inlX_sndX,
      Category.id_comp, zero_comp, add_zero]
  have hq : homotopyCofiber.inrX φ 1 ≫ B = q := by
    rw [hB]
    simp only [Preadditive.comp_add, ← Category.assoc,
      homotopyCofiber.inrX_fstX, homotopyCofiber.inrX_sndX,
      Category.id_comp, zero_comp, zero_add]
  change LinearMap.range B.hom = LinearMap.range p.hom ⊔ LinearMap.range q.hom
  apply le_antisymm
  · rintro _ ⟨x, rfl⟩
    rw [hB]
    exact Submodule.add_mem_sup ⟨_, rfl⟩ ⟨_, rfl⟩
  · apply sup_le
    · rintro _ ⟨x, rfl⟩
      exact ⟨homotopyCofiber.inlX φ 0 1 (by simp) x, ConcreteCategory.congr_hom hp x⟩
    · rintro _ ⟨x, rfl⟩
      exact ⟨homotopyCofiber.inrX φ 1 x, ConcreteCategory.congr_hom hq x⟩

/-- Degree zero of any finite Koszul complex is its coefficient module. -/
def koszulZeroIso (M : ModuleCat.{u} R) :
    (fs : List R) → (koszulComplex M fs).X 0 ≅ M
  | [] => HomologicalComplex.singleObjXSelf (ComplexShape.down ℕ) 0 M
  | f :: fs => homotopyCofiber.XIso (f • 𝟙 (koszulComplex M fs)) 0 (by simp) ≪≫
      koszulZeroIso M fs

/-- The first differential with the degree-zero term identified with the ring. -/
def koszulRingBoundary (fs : List R) :
    (koszulComplex (ModuleCat.of R R) fs).X 1 ⟶ ModuleCat.of R R :=
  (koszulComplex (ModuleCat.of R R) fs).d 1 0 ≫
    (koszulZeroIso (ModuleCat.of R R) fs).hom

/-- The ideal generated by a finite list. -/
def koszulIdeal (fs : List R) : Ideal R := Ideal.span {f | f ∈ fs}

@[simp]
theorem koszulIdeal_nil : koszulIdeal ([] : List R) = ⊥ := by
  simp [koszulIdeal]

@[simp]
theorem koszulIdeal_cons (f : R) (fs : List R) :
    koszulIdeal (f :: fs) = Ideal.span {f} ⊔ koszulIdeal fs := by
  have hs : {a | a ∈ f :: fs} = insert f {a | a ∈ fs} := by ext a; simp
  simp only [koszulIdeal, hs, Ideal.span_insert]

private theorem range_smul_iso {N : ModuleCat.{u} R} (e : N ≅ ModuleCat.of R R) (f : R) :
    LinearMap.range (f • e.hom).hom = Ideal.span {f} := by
  ext r
  rw [LinearMap.mem_range, Ideal.mem_span_singleton]
  constructor
  · rintro ⟨x, rfl⟩
    exact ⟨e.hom x, rfl⟩
  · rintro ⟨a, rfl⟩
    refine ⟨e.inv a, ?_⟩
    change f * (e.hom (e.inv a)) = f * a
    rw [← ModuleCat.comp_apply, Iso.inv_hom_id]
    rfl

/-- The boundaries in degree zero generate exactly the ideal of the list. -/
theorem koszulRingBoundary_range (fs : List R) :
    LinearMap.range (koszulRingBoundary fs).hom = koszulIdeal fs := by
  induction fs with
  | nil =>
    simp [koszulRingBoundary, koszulComplex]
  | cons f fs ih =>
    have hs : homotopyCofiber.sndX (f • 𝟙 (koszulComplex (ModuleCat.of R R) fs)) 0 =
        (homotopyCofiber.XIso (f • 𝟙 (koszulComplex (ModuleCat.of R R) fs)) 0
          (by simp)).hom := by
      exact dite_eq_right (by simp)
    change LinearMap.range (((homotopyCofiber (f • 𝟙 (koszulComplex (ModuleCat.of R R) fs))).d
      1 0 ≫ (homotopyCofiber.XIso (f • 𝟙 (koszulComplex (ModuleCat.of R R) fs))
        0 (by simp)).hom ≫
        (koszulZeroIso (ModuleCat.of R R) fs).hom).hom) = _
    rw [← hs, cofiber_boundary_range]
    simp only [HomologicalComplex.smul_f_apply, HomologicalComplex.id_f,
      Linear.smul_comp, Category.id_comp]
    rw [range_smul_iso, ← koszulRingBoundary, ih, koszulIdeal_cons]

/-- Quotienting degree zero by Koszul boundaries gives the quotient by the
ideal generated by the list. -/
def koszulOpcyclesZeroEquivQuotient (fs : List R) :
    ((koszulComplex (ModuleCat.of R R) fs).X 0 ⧸
      LinearMap.range ((koszulComplex (ModuleCat.of R R) fs).d 1 0).hom) ≃ₗ[R]
      R ⧸ koszulIdeal fs :=
  Submodule.Quotient.equiv _ _ (koszulZeroIso (ModuleCat.of R R) fs).toLinearEquiv (by
    rw [CategoryTheory.Iso.toLinearMap_toLinearEquiv, ← LinearMap.range_comp]
    exact koszulRingBoundary_range fs)

/-- II.(7.5): zeroth Koszul homology over the ring is its quotient by the
ideal generated by the list. -/
def koszulHomologyZeroIsoQuotient (fs : List R) :
    (koszulComplex (ModuleCat.of R R) fs).homology 0 ≅ ModuleCat.of R (R ⧸ koszulIdeal fs) :=
  (koszulComplex (ModuleCat.of R R) fs).homologyIsoSc' 1 0 0 (by simp) (by simp) ≪≫
    ((koszulComplex (ModuleCat.of R R) fs).sc' 1 0 0).asIsoHomologyι
      ((koszulComplex (ModuleCat.of R R) fs).shape 0 0 (by simp)) ≪≫
    ((koszulComplex (ModuleCat.of R R) fs).sc' 1 0 0).moduleCatOpcyclesIso ≪≫
    (koszulOpcyclesZeroEquivQuotient fs).toModuleIso

private theorem cofiber_zeroIso_hom {F G : ChainComplex (ModuleCat.{u} R) ℕ} (φ : F ⟶ G) :
    (homotopyCofiber.XIso φ 0 (by simp)).hom = homotopyCofiber.sndX φ 0 := by
  symm
  exact dite_eq_right (by simp)

private theorem cofiber_map_zero_snd
    {F G F' G' : ChainComplex (ModuleCat.{u} R) ℕ}
    (φ : F ⟶ G) (φ' : F' ⟶ G') (α : Arrow.mk φ ⟶ Arrow.mk φ') :
    (homotopyCofiber.mapArrowHom φ φ' chainShape_hasPredecessor α).f 0 ≫
      homotopyCofiber.sndX φ' 0 =
    homotopyCofiber.sndX φ 0 ≫ α.right.f 0 := by
  simp [homotopyCofiber.mapArrowHom, homotopyCofiber.desc_f' φ _ _ 0 (by simp)]

/-- The power transition is the identity after identifying degree zero with
the coefficient module. -/
@[reassoc]
theorem koszulTransition_zero_naturality (M : ModuleCat.{u} R) (fs : List R)
    {n m : ℕ} (hnm : n ≤ m) :
    (koszulTransition M fs hnm).f 0 ≫ (koszulZeroIso M (fs.map fun f ↦ f ^ n)).hom =
      (koszulZeroIso M (fs.map fun f ↦ f ^ m)).hom := by
  induction fs with
  | nil => exact Category.id_comp _
  | cons f fs ih =>
    change (homotopyCofiber.mapArrowHom
      (f ^ m • 𝟙 (koszulPowerComplex M fs m))
      (f ^ n • 𝟙 (koszulPowerComplex M fs n)) chainShape_hasPredecessor
      (scalarPowerArrow f hnm (koszulTransition M fs hnm))).f 0 ≫
        ((homotopyCofiber.XIso (f ^ n • 𝟙 (koszulPowerComplex M fs n)) 0
          (by simp)).hom ≫ (koszulZeroIso M (fs.map fun f ↦ f ^ n)).hom) =
      (homotopyCofiber.XIso (f ^ m • 𝟙 (koszulPowerComplex M fs m)) 0
        (by simp)).hom ≫ (koszulZeroIso M (fs.map fun f ↦ f ^ m)).hom
    rw [cofiber_zeroIso_hom, cofiber_zeroIso_hom]
    rw [← Category.assoc, cofiber_map_zero_snd, Category.assoc]
    exact congrArg (fun t ↦ homotopyCofiber.sndX
      (f ^ m • 𝟙 (koszulPowerComplex M fs m)) 0 ≫ t) ih

/-- Increasing exponents decreases the ideal generated by the list of powers. -/
theorem koszulIdeal_pow_antitone (fs : List R) {n m : ℕ} (hnm : n ≤ m) :
    koszulIdeal (fs.map fun f ↦ f ^ m) ≤ koszulIdeal (fs.map fun f ↦ f ^ n) := by
  apply Ideal.span_le.mpr
  intro a ha
  obtain ⟨f, hf, rfl⟩ := List.mem_map.mp ha
  have hx : f ^ n ∈ koszulIdeal (fs.map fun f ↦ f ^ n) :=
    Ideal.subset_span (List.mem_map.mpr ⟨f, hf, rfl⟩)
  rw [← Nat.add_sub_of_le hnm, pow_add]
  exact Ideal.mul_mem_right _ _ hx

/-- The zeroth-homology comparison sends a cycle to its residue class. -/
@[reassoc (attr := simp)]
theorem koszulHomologyZeroIsoQuotient_homologyπ (fs : List R) :
    (koszulComplex (ModuleCat.of R R) fs).homologyπ 0 ≫
      (koszulHomologyZeroIsoQuotient fs).hom =
    (koszulComplex (ModuleCat.of R R) fs).iCycles 0 ≫
      (koszulZeroIso (ModuleCat.of R R) fs).hom ≫ ModuleCat.ofHom (koszulIdeal fs).mkQ := by
  have he : ModuleCat.ofHom (LinearMap.range
      ((koszulComplex (ModuleCat.of R R) fs).d 1 0).hom).mkQ ≫
      (koszulOpcyclesZeroEquivQuotient fs).toModuleIso.hom =
    (koszulZeroIso (ModuleCat.of R R) fs).hom ≫ ModuleCat.ofHom (koszulIdeal fs).mkQ := by
    ext x
    rfl
  dsimp only [koszulHomologyZeroIsoQuotient, Iso.trans_hom]
  simp only [HomologicalComplex.π_homologyIsoSc'_hom_assoc,
    ShortComplex.asIsoHomologyι_hom, ShortComplex.homology_π_ι_assoc,
    ShortComplex.pOpcycles_comp_moduleCatOpcyclesIso_hom_assoc]
  rw [HomologicalComplex.cyclesIsoSc'_hom_iCycles_assoc]
  exact congrArg (fun t ↦ (koszulComplex (ModuleCat.of R R) fs).iCycles 0 ≫ t) he

/-- The quotient description of zeroth Koszul homology commutes with the
power transitions; its map on quotient rings is the canonical quotient map. -/
theorem koszulHomologyZeroIsoQuotient_naturality (fs : List R)
    {n m : ℕ} (hnm : n ≤ m) :
    HomologicalComplex.homologyMap (koszulTransition (ModuleCat.of R R) fs hnm) 0 ≫
      (koszulHomologyZeroIsoQuotient (fs.map fun f ↦ f ^ n)).hom =
    (koszulHomologyZeroIsoQuotient (fs.map fun f ↦ f ^ m)).hom ≫
      ModuleCat.ofHom ((koszulIdeal (fs.map fun f ↦ f ^ m)).mapQ
        (koszulIdeal (fs.map fun f ↦ f ^ n)) (LinearMap.id : R →ₗ[R] R)
          (by simpa using koszulIdeal_pow_antitone fs hnm)) := by
  apply (cancel_epi ((koszulPowerComplex (ModuleCat.of R R) fs m).homologyπ 0)).mp
  simp only [HomologicalComplex.homologyπ_naturality_assoc,
    koszulHomologyZeroIsoQuotient_homologyπ,
    koszulHomologyZeroIsoQuotient_homologyπ_assoc]
  simp only [← Category.assoc, HomologicalComplex.cyclesMap_i]
  simp only [Category.assoc, koszulTransition_zero_naturality_assoc]
  rfl

end SGA.SGA2.ExposeII
