/-
Copyright (c) 2026 SGAenglishpluslean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SGAenglishpluslean contributors
-/
import SGA.SGA2.ExposeII.HomComplexScalarChange
import SGA.SGA2.ExposeII.KoszulLocalCohomology
import SGA.SGA2.ExposeI.RightDerivedPostcomposition

/-!
# Scalar restriction for original local cohomology

The tensor comparison of the original Koszul systems gives a source-ring
linear comparison of stable Koszul cohomology. Exact scalar restriction
commutes with the actual homology objects and with their colimits. Over
noetherian rings this yields the change-of-rings isomorphism for the original
local-cohomology modules, including non-flat quotient maps.
-/

noncomputable section
universe u
open CategoryTheory Limits HomologicalComplex

namespace SGA.SGA2.ExposeII

set_option backward.isDefEq.respectTransparency false

variable {R S : Type u} [CommRing R] [CommRing S] (σ : R →+* S)

/-- The mapped generator list defines the actual image ideal. -/
theorem koszulIdeal_map (fs : List R) : koszulIdeal (fs.map σ) = (koszulIdeal fs).map σ := by
  rw [koszulIdeal, koszulIdeal, Ideal.map_span]
  congr 1
  ext x
  simp

/-- The actual direct cohomology diagrams agree after scalar restriction. -/
def koszulCohomologyDiagramScalarChangeIso (fs : List R) (M : ModuleCat.{u} S) (i : ℕ) :
    koszulCohomologyDiagram (fs.map σ) M i ⋙ ModuleCat.restrictScalars σ ≅
      koszulCohomologyDiagram fs ((ModuleCat.restrictScalars σ).obj M) i :=
  Functor.isoWhiskerLeft
    ((koszulSystem (ModuleCat.of S S) (fs.map σ)).op ⋙ homCochainBifunctor.flip.obj M)
    (ExposeI.complexHomologyMapNatIso (ModuleCat.restrictScalars σ) (ComplexShape.up ℕ) i).symm ≪≫
      Functor.isoWhiskerRight (koszulHomComplexSystemScalarChangeIso σ fs M)
        (homologyFunctor (ModuleCat R) (ComplexShape.up ℕ) i)

/-- Stable Koszul cohomology retains the actual scalar-restricted module. -/
def stableKoszulCohomologyScalarChangeIso (fs : List R) (M : ModuleCat.{u} S) (i : ℕ) :
    (ModuleCat.restrictScalars σ).obj (stableKoszulCohomology (fs.map σ) M i) ≅
      stableKoszulCohomology fs ((ModuleCat.restrictScalars σ).obj M) i :=
  preservesColimitIso (ModuleCat.restrictScalars σ) (koszulCohomologyDiagram (fs.map σ) M i) ≪≫
    HasColimit.isoOfNatIso (koszulCohomologyDiagramScalarChangeIso σ fs M i)

variable [IsNoetherianRing R] [IsNoetherianRing S]

/-- The actual local-cohomology comparison for the ideals generated by a
list and its image. No flatness or finiteness of the coefficient is required. -/
def localCohomologyScalarChangeListIso (fs : List R) (M : ModuleCat.{u} S) (i : ℕ) :
    (ModuleCat.restrictScalars σ).obj
        ((_root_.localCohomology (koszulIdeal (fs.map σ)) i).obj M) ≅
      (_root_.localCohomology (koszulIdeal fs) i).obj ((ModuleCat.restrictScalars σ).obj M) :=
  (ModuleCat.restrictScalars σ).mapIso ((localCohomologyIsoStableKoszul (fs.map σ) i).app M) ≪≫
    stableKoszulCohomologyScalarChangeIso σ fs M i ≪≫
    ((localCohomologyIsoStableKoszul fs i).app ((ModuleCat.restrictScalars σ).obj M)).symm

/-- Original local cohomology commutes with scalar restriction and image
of the support ideal along any homomorphism of noetherian commutative rings.
The coefficient module is arbitrary and the ring map need not be flat. -/
def localCohomologyScalarChangeIso (I : Ideal R) (M : ModuleCat.{u} S) (i : ℕ) :
    (ModuleCat.restrictScalars σ).obj ((_root_.localCohomology (I.map σ) i).obj M) ≅
      (_root_.localCohomology I i).obj ((ModuleCat.restrictScalars σ).obj M) := by
  classical
  let s : Finset R := (IsNoetherian.noetherian I).choose
  have hs := (IsNoetherian.noetherian I).choose_spec
  have hfs : koszulIdeal s.toList = I := by simpa [koszulIdeal] using hs
  simpa only [koszulIdeal_map, hfs] using localCohomologyScalarChangeListIso σ s.toList M i

end SGA.SGA2.ExposeII
