/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import Mathlib.RingTheory.FiniteType
import Mathlib.RingTheory.Localization.Away.Basic
import Mathlib.Tactic.LinearCombination

/-!
# Affine blowup algebras

Let `A` be a commutative ring, `I ⊆ A` an ideal and `a ∈ I`. The *affine blowup algebra*
`A[I/a]` (Stacks, Tag 052Q) is the `A`-subalgebra of the localization `A_a` generated by the
fractions `x / a`, `x ∈ I`. Its spectrum is the chart `D₊(a)` of the blow-up of `Spec A` along
`V(I)` (Stacks, Tag 0804).

We define it inside any `A`-algebra `S` in which `a` is invertible
(`Ideal.affineBlowupAlgebra I ha`, `ha : IsUnit (algebraMap A S a)`). The usual choice is
`S = A_a` (`Ideal.affineBlowup I a`); for a domain `A` and `a ≠ 0` one can also work inside the
fraction field, which is what the proof of EGA II 7.1.7 (Stacks, Tag 00PH) does with `A[𝔪/x]`.

## Main results

* `Ideal.mem_affineBlowupAlgebra_iff`: for `a ∈ I`, the elements of `A[I/a]` are the fractions
  `x / aⁿ` with `x ∈ Iⁿ` (Stacks, Tag 052Q);
* `Ideal.map_affineBlowupAlgebra_eq_span`: `I · A[I/a] = a · A[I/a]`, and `a` is a nonzerodivisor
  of `A[I/a]` (`Ideal.algebraMap_mem_nonZeroDivisors_affineBlowupAlgebra`), so `I` becomes an
  invertible ideal (an effective Cartier divisor) on the chart (Stacks, Tag 07Z3);
* `Ideal.affineBlowupAlgebra_eq_adjoin`: if `I` is generated by `s`, `A[I/a]` is generated by the
  `x / a`, `x ∈ s`; hence `A[I/a]` is of finite type over `A` when `I` is finitely generated
  (`Ideal.finiteType_affineBlowupAlgebra`);
* `Ideal.isNoetherianRing_affineBlowupAlgebra`: `A[I/a]` is noetherian when `A` is; it is a domain
  when `S` is (an instance; Stacks, Tag 052R);
* `Ideal.isLocalization_away_affineBlowupAlgebra`: `A[I/a][1/a] = A_a` (Stacks, Tag 07Z3 (3));
* `Ideal.map_affineBlowupAlgebra`, `Ideal.affineBlowupAlgebraEquivOfInjective`: compatibility with
  `A`-algebra maps `S → S'`, e.g. `A[I/a] ⊆ A_a` versus `A[I/a] ⊆ Frac A`;
* `Ideal.affineBlowup.lift`, `Ideal.affineBlowup.algHom_ext`, `Ideal.affineBlowup.uniqueAlgHom`:
  the universal property (the affine form of Stacks, Tag 0806, the universal property of blowing
  up): an `A`-algebra `B` in which `a` is a nonzerodivisor and `I B = a B` receives exactly one
  `A`-algebra map from `A[I/a]`.

## References

* [Stacks Project, Section 10.70, Tags 052P, 052Q, 07Z3, 052R](https://stacks.math.columbia.edu/tag/052P)
* [Stacks Project, Tag 0806](https://stacks.math.columbia.edu/tag/0806) (universal property of
  blowing up; here in its affine form)
* [Stacks Project, Tag 0804](https://stacks.math.columbia.edu/tag/0804) (affine charts of a blow-up)
-/

universe u v w

open Algebra

namespace Ideal

variable {A : Type u} [CommRing A] {S : Type v} [CommRing S] [Algebra A S]

section General

variable (I : Ideal A) {a : A} (ha : IsUnit (algebraMap A S a))

/-- The affine blowup algebra `A[I/a]` (Stacks, Tag 052Q), inside an `A`-algebra `S` in which `a`
is invertible: the `A`-subalgebra of `S` generated by the fractions `x / a`, `x ∈ I`. The usual
choice is `S = A_a` (`Ideal.affineBlowup`); the theory below is mostly stated for `a ∈ I`. -/
def affineBlowupAlgebra : Subalgebra A S :=
  Algebra.adjoin A ((fun x ↦ algebraMap A S x * ↑ha.unit⁻¹) '' (I : Set A))

variable {I ha}

lemma algebraMap_mul_inv_mem_affineBlowupAlgebra {x : A} (hx : x ∈ I) :
    algebraMap A S x * ↑ha.unit⁻¹ ∈ I.affineBlowupAlgebra ha :=
  Algebra.subset_adjoin ⟨x, hx, rfl⟩

lemma algebraMap_mul_inv_mul_self (x : A) :
    algebraMap A S x * ↑ha.unit⁻¹ * algebraMap A S a = algebraMap A S x := by
  rw [mul_assoc, ha.val_inv_mul, mul_one]

/-- `x / aⁿ ∈ A[I/a]` for `x ∈ Iⁿ`. -/
lemma algebraMap_mul_inv_pow_mem_affineBlowupAlgebra {n : ℕ} {x : A} (hx : x ∈ I ^ n) :
    algebraMap A S x * ↑(ha.unit⁻¹ ^ n) ∈ I.affineBlowupAlgebra ha := by
  induction n generalizing x with
  | zero => simp
  | succ n ih =>
    let f : A →ₗ[A] S :=
      LinearMap.mulRight A (↑(ha.unit⁻¹ ^ (n + 1)) : S) ∘ₗ Algebra.linearMap A S
    let N : Ideal A := (Subalgebra.toSubmodule (I.affineBlowupAlgebra ha)).comap f
    suffices I ^ (n + 1) ≤ N from this hx
    rw [pow_succ, Submodule.mul_le]
    intro y hy z hz
    change algebraMap A S (y * z) * ↑(ha.unit⁻¹ ^ (n + 1)) ∈ I.affineBlowupAlgebra ha
    have : algebraMap A S (y * z) * ↑(ha.unit⁻¹ ^ (n + 1)) =
        (algebraMap A S y * ↑(ha.unit⁻¹ ^ n)) * (algebraMap A S z * ↑ha.unit⁻¹) := by
      rw [map_mul, pow_succ, Units.val_mul]; ring
    rw [this]
    exact mul_mem (ih hy) (algebraMap_mul_inv_mem_affineBlowupAlgebra hz)

/-- Stacks, Tag 052Q: for `a ∈ I`, the elements of `A[I/a]` are the fractions `x / aⁿ` with
`x ∈ Iⁿ`. -/
theorem mem_affineBlowupAlgebra_iff (haI : a ∈ I) {y : S} :
    y ∈ I.affineBlowupAlgebra ha ↔
      ∃ n : ℕ, ∃ x ∈ I ^ n, y = algebraMap A S x * ↑(ha.unit⁻¹ ^ n) := by
  refine ⟨fun hy ↦ ?_, ?_⟩
  · induction hy using Algebra.adjoin_induction with
    | mem y hy =>
      obtain ⟨x, hx, rfl⟩ := hy
      exact ⟨1, x, by simpa using hx, by simp⟩
    | algebraMap r => exact ⟨0, r, by simp, by simp⟩
    | add y z _ _ hy hz =>
      obtain ⟨n, x, hx, rfl⟩ := hy
      obtain ⟨m, x', hx', rfl⟩ := hz
      refine ⟨n + m, x * a ^ m + x' * a ^ n, ?_, ?_⟩
      · refine add_mem ?_ ?_
        · rw [pow_add]; exact Submodule.mul_mem_mul hx (pow_mem_pow haI m)
        · rw [pow_add, mul_comm (I ^ n)]; exact Submodule.mul_mem_mul hx' (pow_mem_pow haI n)
      · have hu : algebraMap A S a * ↑ha.unit⁻¹ = 1 := ha.mul_val_inv
        have h1 : algebraMap A S a ^ m * (↑ha.unit⁻¹ : S) ^ m = 1 := by
          rw [← mul_pow, hu, one_pow]
        have h2 : algebraMap A S a ^ n * (↑ha.unit⁻¹ : S) ^ n = 1 := by
          rw [← mul_pow, hu, one_pow]
        simp only [map_add, map_mul, map_pow, pow_add, Units.val_mul, Units.val_pow_eq_pow_val]
        linear_combination (-(algebraMap A S x * (↑ha.unit⁻¹ : S) ^ n)) * h1 +
          (-(algebraMap A S x' * (↑ha.unit⁻¹ : S) ^ m)) * h2
    | mul y z _ _ hy hz =>
      obtain ⟨n, x, hx, rfl⟩ := hy
      obtain ⟨m, x', hx', rfl⟩ := hz
      refine ⟨n + m, x * x', by rw [pow_add]; exact Submodule.mul_mem_mul hx hx', ?_⟩
      simp only [map_mul, pow_add, Units.val_mul]
      ring
  · rintro ⟨n, x, hx, rfl⟩
    exact algebraMap_mul_inv_pow_mem_affineBlowupAlgebra hx

/-- `I · A[I/a] = a · A[I/a]` for `a ∈ I` (Stacks, Tag 07Z3 (2)): the ideal `I` becomes principal
on the chart, generated by `a`. -/
theorem map_affineBlowupAlgebra_eq_span (haI : a ∈ I) :
    I.map (algebraMap A (I.affineBlowupAlgebra ha)) =
      Ideal.span {algebraMap A (I.affineBlowupAlgebra ha) a} := by
  refine le_antisymm (Ideal.map_le_iff_le_comap.mpr fun x hx ↦ ?_) ?_
  · rw [Ideal.mem_comap, Ideal.mem_span_singleton']
    refine ⟨⟨_, algebraMap_mul_inv_mem_affineBlowupAlgebra hx⟩, Subtype.ext ?_⟩
    exact algebraMap_mul_inv_mul_self x
  · rw [Ideal.span_le, Set.singleton_subset_iff]
    exact Ideal.mem_map_of_mem _ haI

/-- `a` is a nonzerodivisor of `A[I/a]` (Stacks, Tag 07Z3 (1)): it is a unit of the ambient `S`. -/
theorem algebraMap_mem_nonZeroDivisors_affineBlowupAlgebra :
    algebraMap A (I.affineBlowupAlgebra ha) a ∈ nonZeroDivisors (I.affineBlowupAlgebra ha) := by
  refine mem_nonZeroDivisors_of_injective (f := (I.affineBlowupAlgebra ha).val)
    Subtype.val_injective ?_
  exact ha.mem_nonZeroDivisors

/-- If `I` is generated by `s`, then `A[I/a]` is generated by the fractions `x / a`, `x ∈ s`. -/
theorem affineBlowupAlgebra_eq_adjoin {s : Set A} (hs : Ideal.span s = I) :
    I.affineBlowupAlgebra ha =
      Algebra.adjoin A ((fun x ↦ algebraMap A S x * ↑ha.unit⁻¹) '' s) := by
  refine le_antisymm (Algebra.adjoin_le ?_) (Algebra.adjoin_mono ?_)
  · rintro _ ⟨x, hx, rfl⟩
    let f : A →ₗ[A] S := LinearMap.mulRight A (↑ha.unit⁻¹ : S) ∘ₗ Algebra.linearMap A S
    let N : Ideal A :=
      (Subalgebra.toSubmodule
        (Algebra.adjoin A ((fun x ↦ algebraMap A S x * ↑ha.unit⁻¹) '' s))).comap f
    suffices I ≤ N from this hx
    rw [← hs, Ideal.span_le]
    intro y hy
    exact Algebra.subset_adjoin ⟨y, hy, rfl⟩
  · exact Set.image_mono (hs ▸ Ideal.subset_span)

/-- `A[I/a]` is of finite type over `A` when `I` is finitely generated. -/
theorem finiteType_affineBlowupAlgebra (hI : I.FG) :
    Algebra.FiniteType A (I.affineBlowupAlgebra ha) := by
  classical
  obtain ⟨s, hs⟩ := hI
  rw [← Subalgebra.fg_iff_finiteType, affineBlowupAlgebra_eq_adjoin hs]
  exact ⟨s.image _, by rw [Finset.coe_image]⟩

/-- `A[I/a]` is a domain when the ambient `S` is (e.g. `S = A_a` for a domain `A` and `a ≠ 0`;
Stacks, Tag 052R). -/
instance [IsDomain S] : IsDomain (I.affineBlowupAlgebra ha) := inferInstance

/-- The affine blowup algebra is compatible with `A`-algebra maps `g : S → S'`. -/
theorem map_affineBlowupAlgebra {S' : Type w} [CommRing S'] [Algebra A S'] (g : S →ₐ[A] S')
    (ha' : IsUnit (algebraMap A S' a)) :
    (I.affineBlowupAlgebra ha).map g = I.affineBlowupAlgebra ha' := by
  rw [affineBlowupAlgebra, AlgHom.map_adjoin, affineBlowupAlgebra, ← Set.image_comp]
  congr 2
  ext x
  simp only [Function.comp_apply, map_mul, AlgHom.commutes]
  congr 1
  have h : g ↑ha.unit⁻¹ * algebraMap A S' a = 1 := by
    rw [← g.commutes, ← map_mul, ha.val_inv_mul, map_one]
  calc g ↑ha.unit⁻¹ = g ↑ha.unit⁻¹ * (algebraMap A S' a * ↑ha'.unit⁻¹) := by
        rw [ha'.mul_val_inv, mul_one]
    _ = ↑ha'.unit⁻¹ := by rw [← mul_assoc, h, one_mul]

/-- An injective `A`-algebra map `g : S → S'` identifies the affine blowup algebras computed in
`S` and in `S'`; e.g. `A[I/a] ⊆ A_a` with `A[I/a] ⊆ Frac A` for a domain `A` and `a ≠ 0`. -/
noncomputable def affineBlowupAlgebraEquivOfInjective {S' : Type w} [CommRing S'] [Algebra A S']
    (g : S →ₐ[A] S') (hg : Function.Injective g) (ha' : IsUnit (algebraMap A S' a)) :
    I.affineBlowupAlgebra ha ≃ₐ[A] I.affineBlowupAlgebra ha' :=
  (Subalgebra.equivMapOfInjective _ g hg).trans
    (Subalgebra.equivOfEq _ _ (map_affineBlowupAlgebra g ha'))

@[simp]
lemma coe_affineBlowupAlgebraEquivOfInjective_apply {S' : Type w} [CommRing S'] [Algebra A S']
    (g : S →ₐ[A] S') (hg : Function.Injective g) (ha' : IsUnit (algebraMap A S' a))
    (y : I.affineBlowupAlgebra ha) :
    (affineBlowupAlgebraEquivOfInjective g hg ha' y : S') = g y := rfl

/-- `A[I/a]` is noetherian when `A` is. -/
theorem isNoetherianRing_affineBlowupAlgebra [IsNoetherianRing A] :
    IsNoetherianRing (I.affineBlowupAlgebra ha) :=
  have := finiteType_affineBlowupAlgebra (ha := ha) (IsNoetherian.noetherian I)
  Algebra.FiniteType.isNoetherianRing A _

/-- `A[I/a][1/a] = S` when `S` is the localization `A_a` (Stacks, Tag 07Z3 (3)): the chart
`Spec A[I/a]` of the blow-up is an isomorphism over `D(a)`. -/
theorem isLocalization_away_affineBlowupAlgebra [IsLocalization.Away a S] :
    IsLocalization.Away (algebraMap A (I.affineBlowupAlgebra ha) a) S := by
  refine IsLocalization.Away.mk _ ?_ (fun z ↦ ?_) (fun y z h ↦ ⟨0, ?_⟩)
  · rwa [← IsScalarTower.algebraMap_apply]
  · obtain ⟨n, x, hx⟩ := IsLocalization.Away.surj a z
    refine ⟨n, algebraMap A _ x, ?_⟩
    simpa only [map_pow, ← IsScalarTower.algebraMap_apply] using hx
  · simpa using Subtype.val_injective h

end General

section Away

variable (I : Ideal A) (a : A)

/-- The affine blowup algebra `A[I/a] ⊆ A_a` (Stacks, Tag 052Q). -/
noncomputable abbrev affineBlowup : Subalgebra A (Localization.Away a) :=
  I.affineBlowupAlgebra (IsLocalization.Away.algebraMap_isUnit (S := Localization.Away a) a)

namespace affineBlowup

variable {I a} {B : Type w} [CommRing B] [Algebra A B]

/-- Two `A`-algebra maps from `A[I/a]` to an `A`-algebra in which `a` is a nonzerodivisor agree
(the uniqueness half of the affine form of Stacks, Tag 0806). -/
theorem algHom_ext (hB : algebraMap A B a ∈ nonZeroDivisors B)
    {f g : I.affineBlowup a →ₐ[A] B} : f = g := by
  set ha := IsLocalization.Away.algebraMap_isUnit (S := Localization.Away a) a
  have key : ∀ y (hy : y ∈ I.affineBlowup a), f ⟨y, hy⟩ = g ⟨y, hy⟩ := by
    intro y hy
    induction hy using Algebra.adjoin_induction with
    | mem y hy =>
      obtain ⟨x, hx, rfl⟩ := hy
      have hfg : ∀ φ : I.affineBlowup a →ₐ[A] B,
          φ ⟨_, algebraMap_mul_inv_mem_affineBlowupAlgebra (ha := ha) hx⟩ *
            algebraMap A B a = algebraMap A B x := by
        intro φ
        rw [← φ.commutes, ← φ.commutes, ← map_mul]
        congr 1
        exact Subtype.ext (algebraMap_mul_inv_mul_self x)
      have h := (hfg f).trans (hfg g).symm
      rw [← sub_eq_zero, ← sub_mul] at h
      exact sub_eq_zero.mp ((mem_nonZeroDivisors_iff.mp hB).2 _ h)
    | algebraMap r =>
      exact (f.commutes r).trans (g.commutes r).symm
    | add y z hy hz ihy ihz =>
      have := congr($ihy + $ihz)
      rwa [← map_add, ← map_add] at this
    | mul y z hy hz ihy ihz =>
      have := congr($ihy * $ihz)
      rwa [← map_mul, ← map_mul] at this
  exact AlgHom.ext fun y ↦ key y.1 y.2

variable (a B) in
/-- The `A`-algebra map `A_a → B_a` induced by `A → B` (used to construct
`Ideal.affineBlowup.lift`). -/
noncomputable def awayMap :
    Localization.Away a →ₐ[A] Localization.Away (algebraMap A B a) :=
  IsLocalization.Away.liftAlgHom (S := Localization.Away a) a
    (f := Algebra.ofId A (Localization.Away (algebraMap A B a)))
    (by
      change IsUnit (algebraMap A (Localization.Away (algebraMap A B a)) a)
      rw [IsScalarTower.algebraMap_apply A B (Localization.Away (algebraMap A B a)) a]
      exact IsLocalization.Away.algebraMap_isUnit _)

private lemma isUnit_algebraMap_away :
    IsUnit (algebraMap A (Localization.Away (algebraMap A B a)) a) := by
  rw [IsScalarTower.algebraMap_apply A B (Localization.Away (algebraMap A B a)) a]
  exact IsLocalization.Away.algebraMap_isUnit _

private lemma map_awayMap_le_range
    (hIB : I.map (algebraMap A B) = Ideal.span {algebraMap A B a}) :
    (I.affineBlowup a).map (awayMap a B) ≤
      (IsScalarTower.toAlgHom A B (Localization.Away (algebraMap A B a))).range := by
  set Bₐ := Localization.Away (algebraMap A B a)
  have hu : IsUnit (algebraMap A Bₐ a) := isUnit_algebraMap_away
  rw [map_affineBlowupAlgebra _ hu, affineBlowupAlgebra, Algebra.adjoin_le_iff]
  rintro _ ⟨x, hx, rfl⟩
  have hxB : algebraMap A B x ∈ Ideal.span {algebraMap A B a} :=
    hIB ▸ Ideal.mem_map_of_mem _ hx
  obtain ⟨b, hb⟩ := Ideal.mem_span_singleton'.mp hxB
  refine ⟨b, ?_⟩
  change algebraMap B Bₐ b = algebraMap A Bₐ x * ↑hu.unit⁻¹
  rw [IsScalarTower.algebraMap_apply A B Bₐ x, ← hb, map_mul,
    ← IsScalarTower.algebraMap_apply A B Bₐ a, mul_assoc, hu.mul_val_inv, mul_one]

/-- The universal property of the affine blowup algebra (the affine form of Stacks, Tag 0806),
existence: if `a` is a nonzerodivisor of an `A`-algebra `B` and `I B = a B`, there is an
`A`-algebra map `A[I/a] → B` (unique by `Ideal.affineBlowup.algHom_ext`). -/
noncomputable def lift (hB : algebraMap A B a ∈ nonZeroDivisors B)
    (hIB : I.map (algebraMap A B) = Ideal.span {algebraMap A B a}) : I.affineBlowup a →ₐ[A] B :=
  let Bₐ := Localization.Away (algebraMap A B a)
  have hinj : Function.Injective (IsScalarTower.toAlgHom A B Bₐ) :=
    IsLocalization.injective Bₐ (M := Submonoid.powers (algebraMap A B a))
      (Submonoid.powers_le.mpr hB)
  (AlgEquiv.ofInjective _ hinj).symm.toAlgHom.comp
    (((awayMap a B).comp (I.affineBlowup a).val).codRestrict _ fun y ↦
      map_awayMap_le_range hIB ⟨y, y.2, rfl⟩)

/-- `lift` followed by `B → B_a` is the map `A[I/a] ⊆ A_a → B_a`. -/
lemma algebraMap_lift (hB : algebraMap A B a ∈ nonZeroDivisors B)
    (hIB : I.map (algebraMap A B) = Ideal.span {algebraMap A B a}) (y : I.affineBlowup a) :
    algebraMap B (Localization.Away (algebraMap A B a)) (lift hB hIB y) = awayMap a B y := by
  set Bₐ := Localization.Away (algebraMap A B a)
  have hinj : Function.Injective (IsScalarTower.toAlgHom A B Bₐ) :=
    IsLocalization.injective Bₐ (M := Submonoid.powers (algebraMap A B a))
      (Submonoid.powers_le.mpr hB)
  have := AlgEquiv.ofInjective_apply _ hinj ((AlgEquiv.ofInjective _ hinj).symm
    (((awayMap a B).comp (I.affineBlowup a).val).codRestrict _ (fun y ↦
      map_awayMap_le_range hIB ⟨y, y.2, rfl⟩) y))
  rw [AlgEquiv.apply_symm_apply] at this
  exact this.symm

/-- The universal property of the affine blowup algebra (the affine form of Stacks, Tag 0806): if
`a` is a nonzerodivisor of the `A`-algebra `B` and `I B = a B`, there is exactly one `A`-algebra
map `A[I/a] → B`. -/
noncomputable abbrev uniqueAlgHom (hB : algebraMap A B a ∈ nonZeroDivisors B)
    (hIB : I.map (algebraMap A B) = Ideal.span {algebraMap A B a}) :
    Unique (I.affineBlowup a →ₐ[A] B) where
  default := lift hB hIB
  uniq _ := algHom_ext hB

end affineBlowup

end Away

end Ideal
