/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.Foundations.Blowup.Rees

/-!
# The blow-up of an affine scheme along a closed subscheme

Let `A` be a commutative ring and `I ⊆ A` an ideal. The blow-up of `Spec A` along `V(I)` is
`Bl_I = Proj (⊕ₙ Iⁿ)` with its structure morphism `Bl_I ⟶ Spec A` (EGA II 8.1.3; Stacks,
Tag 0804). We define it with the graded Rees algebra of `SGA.Foundations.Blowup.Rees` and prove:

* `Ideal.isProper_blowupHom`: `Bl_I ⟶ Spec A` is proper when `I` is finitely generated (a
  projective morphism; mathlib's `IsProper (Proj.toSpecZero _)`);
* `Ideal.blowupChart`: for `a ∈ I`, the open immersion `Spec A[I/a] ⟶ Bl_I` onto `D₊(a t)`
  (`Ideal.opensRange_blowupChart`), over `Spec A` (`Ideal.blowupChart_blowupHom`); these charts
  cover `Bl_I` when `a` runs through a set of generators of `I`
  (`Ideal.iSup_opensRange_blowupChart`, Stacks, Tag 0804).

On the chart `Spec A[I/a]` the inverse image of `I` is generated by the nonzerodivisor `a`
(`Ideal.map_affineBlowupAlgebra_eq_span`,
`Ideal.algebraMap_mem_nonZeroDivisors_affineBlowupAlgebra`): the exceptional divisor is an
effective Cartier divisor.

## References

* [A. Grothendieck, *EGA* II, 8.1]
* [Stacks Project, Tag 0804](https://stacks.math.columbia.edu/tag/0804)
-/

universe u

open CategoryTheory AlgebraicGeometry

namespace Ideal

variable {A : Type u} [CommRing A] (I : Ideal A)

/-- The blow-up `Bl_I = Proj (⊕ₙ Iⁿ)` of `Spec A` along `V(I)` (EGA II 8.1.3; Stacks, Tag 0804). -/
noncomputable abbrev blowup : Scheme.{u} := Proj I.reesGrading

/-- The structure morphism `Bl_I ⟶ Spec A` of the blow-up. -/
noncomputable def blowupHom : I.blowup ⟶ Spec (.of A) :=
  Proj.toSpecZero I.reesGrading ≫ Spec.map (CommRingCat.ofHom I.reesZeroEquiv.toRingHom)

/-- The blow-up of `Spec A` along `V(I)` is proper over `Spec A` when `I` is finitely generated. -/
theorem isProper_blowupHom (hI : I.FG) : IsProper I.blowupHom := by
  have := finiteType_reesAlgebra hI
  have : IsIso (CommRingCat.ofHom I.reesZeroEquiv.toRingHom) :=
    inferInstanceAs (IsIso I.reesZeroEquiv.toCommRingCatIso.hom)
  unfold blowupHom
  infer_instance

instance [IsNoetherianRing A] : IsProper I.blowupHom :=
  I.isProper_blowupHom (IsNoetherian.noetherian I)

variable {I} {a : A}

/-- The chart `Spec A[I/a] ⟶ Bl_I` of the blow-up, for `a ∈ I`: the open immersion onto
`D₊(a t)`, through the identification `(⊕ₙ Iⁿ)_{(a t)} ≅ A[I/a]` (`Ideal.reesAwayEquiv`). -/
noncomputable def blowupChart (ha : a ∈ I) : Spec (.of (I.affineBlowup a)) ⟶ I.blowup :=
  Spec.map (CommRingCat.ofHom (reesAwayEquiv ha).toRingHom) ≫
    Proj.awayι I.reesGrading (reesT ha) (reesT_mem ha) one_pos

instance (ha : a ∈ I) : IsOpenImmersion (blowupChart ha) := by
  have : IsIso (CommRingCat.ofHom (reesAwayEquiv ha).toRingHom) :=
    inferInstanceAs (IsIso (reesAwayEquiv ha).toCommRingCatIso.hom)
  unfold blowupChart
  infer_instance

lemma opensRange_blowupChart (ha : a ∈ I) :
    (blowupChart ha).opensRange = Proj.basicOpen I.reesGrading (reesT ha) := by
  have : IsIso (CommRingCat.ofHom (reesAwayEquiv ha).toRingHom) :=
    inferInstanceAs (IsIso (reesAwayEquiv ha).toCommRingCatIso.hom)
  unfold blowupChart
  rw [Scheme.Hom.opensRange_comp_of_isIso, Proj.opensRange_awayι]

/-- The chart `Spec A[I/a] ⟶ Bl_I` lies over `Spec A`: composed with `Bl_I ⟶ Spec A` it is the
morphism induced by `A → A[I/a]`. -/
lemma blowupChart_blowupHom (ha : a ∈ I) :
    blowupChart ha ≫ I.blowupHom =
      Spec.map (CommRingCat.ofHom (algebraMap A (I.affineBlowup a))) := by
  rw [blowupChart, blowupHom, Category.assoc, Proj.awayι_toSpecZero_assoc, ← Spec.map_comp,
    ← Spec.map_comp]
  congr 1
  ext x
  change (reesAwayEquiv ha (HomogeneousLocalization.fromZeroRingHom _ _
    (I.reesZeroEquiv x)) : Localization.Away a) = algebraMap A (Localization.Away a) x
  rw [coe_reesAwayEquiv]
  have h0 : (I.reesZeroEquiv x : I.ReesAlgebra) ∈ I.reesGrading (0 • 1) := by
    simpa using (I.reesZeroEquiv x).2
  have : HomogeneousLocalization.fromZeroRingHom I.reesGrading _ (I.reesZeroEquiv x) =
      HomogeneousLocalization.Away.mk _ (reesT_mem ha) 0 _ h0 := by
    ext
    rw [HomogeneousLocalization.Away.val_mk]
    rfl
  rw [this, reesAwayToAway_mk, coe_reesZeroEquiv, AlgHom.commutes, pow_zero, Units.val_one,
    mul_one, Algebra.algebraMap_self, RingHom.id_apply]

/-- The charts `Spec A[I/a]`, `a ∈ s`, cover the blow-up when `s` generates `I` (Stacks,
Tag 0804). -/
theorem iSup_opensRange_blowupChart {s : Set A} (hs : Ideal.span s = I) :
    ⨆ a : s, (blowupChart (mem_of_span_eq hs a)).opensRange = ⊤ := by
  simp_rw [opensRange_blowupChart]
  refine Proj.iSup_basicOpen_eq_top' I.reesGrading _ (fun a ↦ ⟨1, reesT_mem _⟩) ?_
  exact adjoin_reesT_eq_top hs

end Ideal
