/-
Copyright (c) 2026 SGAenglishpluslean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SGAenglishpluslean contributors
-/
import Mathlib.RingTheory.Smooth.StandardSmoothOfFree
import SGA.Foundations.Dimension.Equidimensional
import SGA.SGA1.ExposeII.FieldSmooth

/-!
# SGA 1, Exposé II, II.2.3: smoothness and equidimensionality

II.2.3 says: if `f : X ⟶ Y` is of finite type, `Y` locally noetherian and `𝒪_{f(x)}` normal, then
`f` is smooth at `x` iff it is equidimensional at `x` (`IsEquidimensionalAt`) and the fibre
`f⁻¹(f(x))` is smooth at `x`.

* Necessity, for schemes (`isEquidimensionalAt_and_asFiber_mem_smoothLocus`): near `x`, `f` is
  standard smooth of some relative dimension `n` on affine charts, and the dimension theory of
  `SGA.Foundations.Dimension` shows that the irreducible components of such a chart dominate
  components of `Y` (flatness) and that all fibres have pure dimension `n`; the fibre is smooth
  at `x` by base change.
* Sufficiency, affine form, following SGA's proof (`isEtaleAt_of_span_of_le_trdeg`,
  `isSmoothAt_of_span_of_le_trdeg`): let `S` be finitely presented over `R`, `Q` a prime of `S`
  over `p` with `R_p` a normal domain. Suppose that `Ω¹_{S/R}` is generated by `n` elements at `Q`
  (this is what the smoothness of the fibre at `x`, of dimension `n`, gives, II.5.5), and that
  there is a generization `P ⊆ Q` lying over the generic point of `Spec R_p` whose residue field
  has transcendence degree `≥ n` (this is what equidimensionality gives: the irreducible component
  through `x` dominates `Y`, and its generic fibre has dimension `n`). Then `S` is smooth over `R`
  at `Q`. As in SGA: `S` is unramified at `Q` over `R[t₁,…,tₙ]` (the `tᵢ` mapping to elements
  whose differentials generate `Ω¹`), hence also at `P`, so the image of `P` in `R[t]` is the
  generic point of the fibre ("dominant for reasons of dimension"); hence `R[t]_{Q'} → S_Q` is
  injective, and I.9.5 (ii) makes it flat, so étale.

The translation of the topological hypothesis `IsEquidimensionalAt` and of the smoothness of the
scheme-theoretic fibre into these algebraic hypotheses, hence II.2.3 for schemes, is in
`SGA.SGA1.ExposeII.EquidimensionalScheme` (`mem_smoothLocus_iff_isEquidimensionalAt`).
-/

universe u

open AlgebraicGeometry CategoryTheory IsLocalRing Algebra KaehlerDifferential MvPolynomial Cardinal
open scoped TensorProduct

namespace SGA.SGA1.ExposeII

section Scheme

variable {X Y : Scheme.{u}} (f : X ⟶ Y)

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
/-- II.2.3, necessity: a morphism locally of finite presentation which is smooth at `x`, over a
locally noetherian base, is equidimensional at `x` (no normality is needed for this direction).
Near `x`, `f` is standard smooth of some relative dimension `n` on affine charts, where
`SGA.Foundations.Dimension` gives equidimensionality. -/
theorem isEquidimensionalAt_of_mem_smoothLocus [LocallyOfFinitePresentation f]
    [IsLocallyNoetherian Y] {x : X} (hx : x ∈ f.smoothLocus) : IsEquidimensionalAt f x := by
  obtain ⟨U, hU, V, hV, hVU, hxV, H⟩ := exists_smooth_of_formallySmooth_stalk f x hx
  have := f.finitePresentation_appLE hU hV hVU
  algebraize [(f.appLE U V hVU).hom]
  have : Algebra.Smooth Γ(Y, U) Γ(X, V) := H
  have : Algebra.IsSmoothAt Γ(Y, U) (hV.primeIdealOf ⟨x, hxV⟩).asIdeal := by
    have := Algebra.smoothLocus_eq_univ (R := Γ(Y, U)) (A := Γ(X, V)) ▸
      Set.mem_univ (hV.primeIdealOf ⟨x, hxV⟩)
    exact this
  obtain ⟨r, hrx, hr⟩ := Algebra.IsSmoothAt.exists_notMem_isStandardSmooth Γ(Y, U)
    (hV.primeIdealOf ⟨x, hxV⟩).asIdeal
  obtain ⟨ι, σ, _, _, ⟨P⟩⟩ := hr.out
  have hrd : Algebra.IsStandardSmoothOfRelativeDimension P.dimension Γ(Y, U)
      (Localization.Away r) := P.isStandardSmoothOfRelativeDimension rfl
  have hxr : x ∈ X.basicOpen r := by
    rwa [← PrimeSpectrum.mem_basicOpen, IsAffineOpen.primeIdealOf,
      ← hV.fromSpec_preimage_basicOpen, Scheme.Hom.mem_preimage, ← Scheme.Hom.comp_apply,
      IsAffineOpen.isoSpec_hom, IsAffineOpen.toSpecΓ_fromSpec] at hrx
  have e : X.basicOpen r ≤ f ⁻¹ᵁ U := (X.basicOpen_le r).trans hVU
  have hstd : (f.appLE U (X.basicOpen r) e).hom.IsStandardSmoothOfRelativeDimension
      P.dimension := by
    have := hV.isLocalization_basicOpen r
    rw [← RingHom.isStandardSmoothOfRelativeDimension_algebraMap] at hrd
    convert! RingHom.isStandardSmoothOfRelativeDimension_respectsIso.1 _
      (IsLocalization.algEquiv (.powers r) _ Γ(X, X.basicOpen r)).toRingEquiv hrd
    ext
    dsimp
    simp only [IsScalarTower.algebraMap_apply Γ(Y, U) Γ(X, V) (Localization _),
      IsLocalization.map_eq]
    simp only [RingHom.algebraMap_toAlgebra, RingHomCompTriple.comp_apply,
      ← ConcreteCategory.comp_apply, Scheme.Hom.appLE_map]
  obtain ⟨h1, h2⟩ := Scheme.Hom.equidimensional_of_isStandardSmoothOfRelativeDimension_appLE f
    hU (hV.basicOpen r) e P.dimension hstd
  exact ⟨X.basicOpen r, hxr, h1, P.dimension, h2⟩

/-- II.2.3, "only if": if `f` (locally of finite presentation, over a locally noetherian base) is
smooth at `x`, then it is equidimensional at `x` and its fibre `f⁻¹(f(x))` is smooth over
`κ(f(x))` at `x`. -/
theorem isEquidimensionalAt_and_asFiber_mem_smoothLocus [LocallyOfFinitePresentation f]
    [IsLocallyNoetherian Y] {x : X} (hx : x ∈ f.smoothLocus) :
    IsEquidimensionalAt f x ∧ f.asFiber x ∈ (f.fiberToSpecResidueField (f x)).smoothLocus :=
  ⟨isEquidimensionalAt_of_mem_smoothLocus f hx, asFiber_mem_smoothLocus f hx⟩

end Scheme

section Algebra

variable {R S : Type u} [CommRing R] [CommRing S] [Algebra R S]

set_option backward.isDefEq.respectTransparency false in
/-- II.2.3, sufficiency, the key step (affine form). Let `S` be finitely presented over `R`, with
`tᵢ ↦ fᵢ` making it an `R[t₁,…,tₙ]`-algebra, `Q` a prime of `S` over `p` with `R_p` a normal
domain, such that the `dfᵢ` generate `Ω¹_{S/R}` at `Q`. Let `P ⊆ Q` be a prime of `S` whose residue
field has transcendence degree `≥ n` over a field `K` through which `R → κ(P)` factors, and lying
over the generic point of `Spec R_p` (`ker(R → K) ⊆ ker(R → R_p)`). Then `S` is étale over
`R[t₁,…,tₙ]` at `Q`: this is SGA's proof of II.2.3 (and of II.5.1 over a field). -/
theorem isEtaleAt_of_span_of_le_trdeg [FinitePresentation R S] {n : ℕ}
    [Algebra (MvPolynomial (Fin n) R) S] [IsScalarTower R (MvPolynomial (Fin n) R) S]
    (p : Ideal R) (Q : Ideal S) [p.IsPrime] [Q.IsPrime] [Q.LiesOver p]
    [IsDomain (Localization.AtPrime p)] [IsIntegrallyClosed (Localization.AtPrime p)]
    (hspan : Submodule.span (Localization.AtPrime Q) (Set.range fun i ↦
      D R (Localization.AtPrime Q) (algebraMap (MvPolynomial (Fin n) R) _ (X i))) = ⊤)
    (P : Ideal S) [P.IsPrime] (hPQ : P ≤ Q) (K : Type u) [Field K] [Algebra R K]
    [Algebra K P.ResidueField] [IsScalarTower R K P.ResidueField]
    (hK : RingHom.ker (algebraMap R K) ≤ RingHom.ker (algebraMap R (Localization.AtPrime p)))
    (htr : (n : Cardinal) ≤ trdeg K P.ResidueField) :
    IsEtaleAt (MvPolynomial (Fin n) R) Q := by
  have : IsScalarTower R (MvPolynomial (Fin n) R) (Localization.AtPrime Q) := .to₁₂₄ _ _ S _
  have : FinitePresentation (MvPolynomial (Fin n) R) S :=
    .of_restrict_scalars_finitePresentation R _ S
  -- the `dfᵢ` generate `Ω¹_{S/R}` at `Q`, so `S` is unramified over `R[t]` at `Q` (II.4.1)
  have hunr : IsUnramifiedAt (MvPolynomial (Fin n) R) Q := by
    refine formallyUnramified_of_mapBaseChange_surjective R _ _ ?_
    rw [← LinearMap.range_eq_top, _root_.eq_top_iff, ← hspan, Submodule.span_le]
    rintro _ ⟨i, rfl⟩
    exact ⟨1 ⊗ₜ D R _ (X i), by simp⟩
  -- hence also at its generization `P`
  have hpu : IsUnramifiedAt (MvPolynomial (Fin n) R) P := by
    have hQ : (⟨Q, ‹_›⟩ : PrimeSpectrum S) ∈ unramifiedLocus (MvPolynomial (Fin n) R) S := hunr
    have hsp : (⟨P, ‹_›⟩ : PrimeSpectrum S) ⤳ ⟨Q, ‹_›⟩ :=
      (PrimeSpectrum.le_iff_specializes _ _).mp hPQ
    exact hsp.mem_open isOpen_unramifiedLocus hQ
  -- the images `t̄ᵢ` of the `tᵢ` in `κ(P)`; `κ(P)` is algebraic over `K(t̄)`
  let t : Fin n → P.ResidueField := fun i ↦ algebraMap (MvPolynomial (Fin n) R) P.ResidueField (X i)
  have hT (a : MvPolynomial (Fin n) R) : algebraMap (MvPolynomial (Fin n) R) P.ResidueField a ∈
      IntermediateField.adjoin K (Set.range t) := by
    induction a using MvPolynomial.induction_on with
    | C r =>
      rw [← MvPolynomial.algebraMap_eq, ← IsScalarTower.algebraMap_apply,
        IsScalarTower.algebraMap_apply R K P.ResidueField]
      exact IntermediateField.algebraMap_mem _ _
    | add a b ha hb => rw [map_add]; exact add_mem ha hb
    | mul_X a i ha =>
      rw [map_mul]
      exact mul_mem ha (IntermediateField.subset_adjoin _ _ ⟨i, rfl⟩)
  -- `κ(P)` is finite over `κ(P')`, `P' = P ∩ R[t]`, which is generated by the `t̄ᵢ` over `K`
  let := Localization.AtPrime.algebraOfLiesOver (P.under (MvPolynomial (Fin n) R)) P
  have : Module.Finite (P.under (MvPolynomial (Fin n) R)).ResidueField P.ResidueField :=
    inferInstance
  have hF (w : (P.under (MvPolynomial (Fin n) R)).ResidueField) :
      algebraMap _ P.ResidueField w ∈ IntermediateField.adjoin K (Set.range t) := by
    obtain ⟨x, y, hy, rfl⟩ := IsFractionRing.div_surjective
      (A := MvPolynomial (Fin n) R ⧸ P.under (MvPolynomial (Fin n) R)) w
    obtain ⟨a, rfl⟩ := Ideal.Quotient.mk_surjective x
    obtain ⟨b, rfl⟩ := Ideal.Quotient.mk_surjective y
    rw [map_div₀, Ideal.algebraMap_quotient_residueField_mk,
      Ideal.algebraMap_quotient_residueField_mk,
      ← IsScalarTower.algebraMap_apply, ← IsScalarTower.algebraMap_apply]
    exact div_mem (hT a) (hT b)
  let φ : (P.under (MvPolynomial (Fin n) R)).ResidueField →+*
      IntermediateField.adjoin K (Set.range t) :=
    (algebraMap _ P.ResidueField).codRestrict _ hF
  let := φ.toAlgebra
  have : IsScalarTower (P.under (MvPolynomial (Fin n) R)).ResidueField
      (IntermediateField.adjoin K (Set.range t)) P.ResidueField := .of_algebraMap_eq fun _ ↦ rfl
  have halg : Algebra.IsAlgebraic (IntermediateField.adjoin K (Set.range t)) P.ResidueField :=
    ⟨fun z ↦ ((Algebra.IsIntegral.isIntegral (R := (P.under (MvPolynomial (Fin n) R)).ResidueField)
      z).tower_top).isAlgebraic⟩
  have : Algebra.IsAlgebraic (Algebra.adjoin K (Set.range t)) P.ResidueField :=
    IntermediateField.isAlgebraic_adjoin_iff_top.mp halg
  -- so the `t̄ᵢ` are algebraically independent over `K`
  have hind : AlgebraicIndependent K t :=
    (Algebra.IsAlgebraic.isTranscendenceBasis_of_lift_le_trdeg_of_finite K t
      (by rw [mk_fin, lift_natCast, lift_uzero]; exact htr)).1
  -- hence the kernel of `R[t] → κ(P)` dies in `R_p[t]`
  have hker (a : MvPolynomial (Fin n) R)
      (ha : algebraMap (MvPolynomial (Fin n) R) P.ResidueField a = 0) :
      MvPolynomial.map (algebraMap R (Localization.AtPrime p)) a = 0 := by
    have h1 : MvPolynomial.aeval t (MvPolynomial.map (algebraMap R K) a) = 0 := by
      rw [MvPolynomial.aeval_map_algebraMap, ← ha]
      exact (congr($(MvPolynomial.aeval_unique
        (IsScalarTower.toAlgHom R (MvPolynomial (Fin n) R) P.ResidueField)) a)).symm
    have h2 : MvPolynomial.map (algebraMap R K) a = 0 := hind (h1.trans (map_zero _).symm)
    ext m
    rw [MvPolynomial.coeff_map, MvPolynomial.coeff_zero]
    have : algebraMap R K (a.coeff m) = 0 := by
      rw [← MvPolynomial.coeff_map, h2, MvPolynomial.coeff_zero]
    exact RingHom.mem_ker.mp (hK (RingHom.mem_ker.mpr this))
  -- `R[t]_{Q'}`, `Q' = Q ∩ R[t]`, is a localization of `R_p[t]`, an integrally closed domain
  let : Algebra (MvPolynomial (Fin n) R) (MvPolynomial (Fin n) (Localization.AtPrime p)) :=
    MvPolynomial.algebraMvPolynomial
  have : IsLocalization (p.primeCompl.map (C : R →+* MvPolynomial (Fin n) R))
      (MvPolynomial (Fin n) (Localization.AtPrime p)) := MvPolynomial.isLocalization _ _
  have hQ'R : (Q.under (MvPolynomial (Fin n) R)).under R = p := by
    rw [Ideal.under_under]
    exact Ideal.LiesOver.over.symm
  have hle : p.primeCompl.map (C : R →+* MvPolynomial (Fin n) R) ≤
      (Q.under (MvPolynomial (Fin n) R)).primeCompl := by
    rintro _ ⟨r, hr, rfl⟩ h
    apply hr
    rw [← hQ'R]
    exact h
  let := IsLocalization.localizationAlgebraOfSubmonoidLe
    (MvPolynomial (Fin n) (Localization.AtPrime p))
    (Localization.AtPrime (Q.under (MvPolynomial (Fin n) R))) _ _ hle
  have := IsLocalization.localization_isScalarTower_of_submonoid_le
    (MvPolynomial (Fin n) (Localization.AtPrime p))
    (Localization.AtPrime (Q.under (MvPolynomial (Fin n) R))) _ _ hle
  have := IsLocalization.isLocalization_of_submonoid_le
    (MvPolynomial (Fin n) (Localization.AtPrime p))
    (Localization.AtPrime (Q.under (MvPolynomial (Fin n) R))) _ _ hle
  have hM : (Q.under (MvPolynomial (Fin n) R)).primeCompl.map
      (algebraMap (MvPolynomial (Fin n) R) (MvPolynomial (Fin n) (Localization.AtPrime p))) ≤
      nonZeroDivisors _ := by
    rintro _ ⟨s, hs, rfl⟩
    rw [mem_nonZeroDivisors_iff_ne_zero]
    intro h0
    apply hs
    have hp : Ideal.map (C : R →+* MvPolynomial (Fin n) R) p ≤
        Q.under (MvPolynomial (Fin n) R) := by
      rw [Ideal.map_le_iff_le_comap]
      intro r hr
      change r ∈ (Q.under (MvPolynomial (Fin n) R)).under R
      rwa [hQ'R]
    refine hp (MvPolynomial.mem_map_C_iff.mpr fun m ↦ ?_)
    have : algebraMap R (Localization.AtPrime p) (s.coeff m) = 0 := by
      rw [← MvPolynomial.coeff_map]
      exact congr(MvPolynomial.coeff m $h0)
    obtain ⟨⟨c, hc⟩, hcs⟩ := (IsLocalization.map_eq_zero_iff p.primeCompl _ _).mp this
    exact (‹p.IsPrime›.mem_or_mem (hcs ▸ p.zero_mem)).resolve_left hc
  have : IsIntegrallyClosed (MvPolynomial (Fin n) (Localization.AtPrime p)) :=
    isIntegrallyClosed_mvPolynomial _ n
  have : IsDomain (Localization.AtPrime (Q.under (MvPolynomial (Fin n) R))) :=
    IsLocalization.isDomain_of_le_nonZeroDivisors _ hM
  have : IsIntegrallyClosed (Localization.AtPrime (Q.under (MvPolynomial (Fin n) R))) :=
    isIntegrallyClosed_of_isLocalization _ _ hM
  -- `R[t]_{Q'} → S_Q` is injective: its kernel dies in `κ(P)`
  let := Localization.AtPrime.algebraOfLiesOver (Q.under (MvPolynomial (Fin n) R)) Q
  have hinjq : Function.Injective (algebraMap
      (Localization.AtPrime (Q.under (MvPolynomial (Fin n) R))) (Localization.AtPrime Q)) := by
    rw [injective_iff_map_eq_zero]
    intro z hz
    obtain ⟨a, s, rfl⟩ :=
      IsLocalization.exists_mk'_eq (Q.under (MvPolynomial (Fin n) R)).primeCompl z
    have h' : algebraMap (MvPolynomial (Fin n) R) (Localization.AtPrime Q) a = 0 := by
      rw [IsScalarTower.algebraMap_apply (MvPolynomial (Fin n) R)
        (Localization.AtPrime (Q.under (MvPolynomial (Fin n) R))) (Localization.AtPrime Q),
        ← IsLocalization.mk'_spec (Localization.AtPrime (Q.under (MvPolynomial (Fin n) R))) a s,
        RingHom.map_mul, hz, zero_mul]
    rw [IsScalarTower.algebraMap_apply _ S, IsLocalization.map_eq_zero_iff Q.primeCompl] at h'
    obtain ⟨⟨u, hu⟩, hua⟩ := h'
    have hmem : algebraMap _ S a ∈ P :=
      (‹P.IsPrime›.mem_or_mem (hua ▸ P.zero_mem)).resolve_left fun h ↦ hu (hPQ h)
    have hκ : algebraMap (MvPolynomial (Fin n) R) P.ResidueField a = 0 := by
      rw [IsScalarTower.algebraMap_apply _ S, Ideal.algebraMap_residueField_eq_zero]
      exact hmem
    have h0 : algebraMap (MvPolynomial (Fin n) R)
        (Localization.AtPrime (Q.under (MvPolynomial (Fin n) R))) a = 0 := by
      rw [IsScalarTower.algebraMap_apply _ (MvPolynomial (Fin n) (Localization.AtPrime p)) _]
      change algebraMap _ _ (MvPolynomial.map (algebraMap R (Localization.AtPrime p)) a) = 0
      rw [hker a hκ, map_zero]
    rw [IsLocalization.mk'_eq_mul_mk'_one, h0, zero_mul]
  -- I.9.5 (ii): an injective unramified local homomorphism over a normal domain is flat
  have : FormallyUnramified (Localization.AtPrime (Q.under (MvPolynomial (Fin n) R)))
      (Localization.AtPrime Q) := .localization_base (Q.under (MvPolynomial (Fin n) R)).primeCompl
  have : EssFiniteType (MvPolynomial (Fin n) R) (Localization.AtPrime Q) := .comp _ S _
  have : EssFiniteType (Localization.AtPrime (Q.under (MvPolynomial (Fin n) R)))
      (Localization.AtPrime Q) := .of_comp (MvPolynomial (Fin n) R) _ _
  have := SGA.SGA1.ExposeI.flat_of_injective_of_formallyUnramified hinjq
  have : Module.Flat (MvPolynomial (Fin n) R) (Localization.AtPrime Q) :=
    .trans _ (Localization.AtPrime (Q.under (MvPolynomial (Fin n) R))) _
  exact isEtaleAt_of_flat_of_isUnramifiedAt Q this

set_option backward.isDefEq.respectTransparency false in
/-- II.2.3, sufficiency, affine form. Let `S` be finitely presented over `R` and `Q` a prime of
`S` over `p`, with `R_p` a normal domain (`𝒪_{f(x)}` normal). Suppose that `Ω¹_{S/R}` is generated
by `n` elements at `Q` (if the fibre is smooth at `Q`, of dimension `n`, this holds by II.5.5), and
that some prime `P ⊆ Q` (a generization of `x`), lying over the generic point of `Spec R_p`, has
a residue field of transcendence degree `≥ n` over a field `K` through which `R → κ(P)` factors
(the component through `x` dominates `Y` and has generic fibre of dimension `n`, which is what
equidimensionality gives). Then `S` is smooth over `R` at `Q`. SGA's hypotheses "equidimensional
at `x`, with fibre smooth at `x`" are replaced by these algebraic consequences. -/
theorem isSmoothAt_of_span_of_le_trdeg [FinitePresentation R S] (p : Ideal R) (Q : Ideal S)
    [p.IsPrime] [Q.IsPrime] [Q.LiesOver p] [IsDomain (Localization.AtPrime p)]
    [IsIntegrallyClosed (Localization.AtPrime p)] {n : ℕ}
    (ω : Fin n → Ω[Localization.AtPrime Q⁄R])
    (hω : Submodule.span (Localization.AtPrime Q) (Set.range ω) = ⊤)
    (P : Ideal S) [P.IsPrime] (hPQ : P ≤ Q) (K : Type u) [Field K] [Algebra R K]
    [Algebra K P.ResidueField] [IsScalarTower R K P.ResidueField]
    (hK : RingHom.ker (algebraMap R K) ≤ RingHom.ker (algebraMap R (Localization.AtPrime p)))
    (htr : (n : Cardinal) ≤ trdeg K P.ResidueField) : IsSmoothAt R Q := by
  have : EssFiniteType R (Localization.AtPrime Q) := .comp R S _
  -- the `ds`, `s ∈ S`, generate `Ω¹` at `Q`
  let v : S → Ω[Localization.AtPrime Q⁄R] := fun s ↦ D R _ (algebraMap S _ s)
  have hv : Submodule.span (Localization.AtPrime Q) (Set.range v) = ⊤ := by
    have := span_range_map_derivation_of_isLocalization (R := R) (S := S)
      (T := Localization.AtPrime Q) Q.primeCompl
    rw [← this]
    congr 1
    ext x
    simp only [Set.mem_range, Function.comp_apply, KaehlerDifferential.map_D, v]
  -- a basis of `Ω¹_{S/R}(Q)` made of `dgᵢ`, `gᵢ ∈ S`; they generate `Ω¹` at `Q` (Nakayama)
  obtain ⟨κ, a, -, hsp, hli⟩ := exists_linearIndependent' (ResidueField (Localization.AtPrime Q))
    (fun s ↦ (1 : ResidueField (Localization.AtPrime Q)) ⊗ₜ[Localization.AtPrime Q] v s)
  rw [span_tmul_eq_top_of_span_eq_top v hv] at hsp
  let b := Module.Basis.mk hli hsp.ge
  have hspa : Submodule.span (Localization.AtPrime Q) (Set.range (v ∘ a)) = ⊤ :=
    span_eq_top_of_tmul_eq_basis (v ∘ a) b fun j ↦ (Module.Basis.mk_apply hli hsp.ge j).symm
  have : Finite κ := Module.Finite.finite_basis b
  have := Fintype.ofFinite κ
  let e := Finite.equivFin κ
  have hm : Nat.card κ ≤ n := by
    have h := finrank_le_of_span_eq_top (span_tmul_eq_top_of_span_eq_top ω hω)
    rwa [Module.finrank_eq_card_basis b, Fintype.card_fin, ← Nat.card_eq_fintype_card] at h
  -- `S` is étale over `R[t₁,…,tₘ]`, `tᵢ ↦ gᵢ`, at `Q`
  let g : Fin (Nat.card κ) → S := a ∘ e.symm
  algebraize [(MvPolynomial.aeval (R := R) g).toRingHom]
  have : IsScalarTower R (MvPolynomial (Fin (Nat.card κ)) R) S := .of_algHom (MvPolynomial.aeval g)
  have : IsScalarTower R (MvPolynomial (Fin (Nat.card κ)) R) (Localization.AtPrime Q) :=
    .to₁₂₄ _ _ S _
  have hf (i : Fin (Nat.card κ)) : algebraMap (MvPolynomial (Fin (Nat.card κ)) R)
      (Localization.AtPrime Q) (X i) = algebraMap S _ (g i) := by
    rw [IsScalarTower.algebraMap_apply _ S]
    congr 1
    exact aeval_X g i
  have hspan : Submodule.span (Localization.AtPrime Q) (Set.range fun i ↦
      D R (Localization.AtPrime Q)
        (algebraMap (MvPolynomial (Fin (Nat.card κ)) R) _ (X i))) = ⊤ := by
    rw [_root_.eq_top_iff, ← hspa, Submodule.span_le]
    rintro _ ⟨j, rfl⟩
    refine Submodule.subset_span ⟨e j, ?_⟩
    simp only [hf, g, Function.comp_apply, Equiv.symm_apply_apply]
    rfl
  have := isEtaleAt_of_span_of_le_trdeg p Q hspan P hPQ K hK
    (le_trans (by exact_mod_cast hm) htr)
  change FormallySmooth R (Localization.AtPrime Q)
  have : FormallyEtale (MvPolynomial (Fin (Nat.card κ)) R) (Localization.AtPrime Q) := this
  exact .comp R (MvPolynomial (Fin (Nat.card κ)) R) _

end Algebra

end SGA.SGA1.ExposeII
