/-
Copyright (c) 2026 SGAenglishpluslean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SGAenglishpluslean contributors
-/
import Mathlib.RingTheory.Smooth.StandardSmoothOfFree
import SGA.Foundations.Dimension.Scheme
import SGA.SGA1.ExposeI.Fibrewise
import SGA.SGA1.ExposeII.Equidimensional
import SGA.SGA1.ExposeII.FiberDifferentials

/-!
# SGA 1, Exposé II, II.2.3 for schemes

We deduce II.2.3 for schemes (`mem_smoothLocus_iff_isEquidimensionalAt`) from its affine form
`isSmoothAt_of_span_of_le_trdeg` (`SGA.SGA1.ExposeII.Equidimensional`). Let `x ∈ X` over `y`, with
`𝒪_y` normal, `f` equidimensional at `x` (on a neighbourhood `U`, with fibre dimension `d`), and
the fibre `X_y` smooth at `x`, of dimension `m` there. On affine charts around `x` and `y`:

* `Ω¹_{X/Y}` is generated by `m` elements at `x`: the fibre is standard smooth of relative
  dimension `m` near `x` (`exists_kaehlerSpanLE_of_mem_smoothLocus`), and the number of generators
  of `Ω¹` is the same for `X/Y` and for the fibre, by Nakayama along
  `𝒪_{X,x} → 𝒪_{X_y,x} = 𝒪_{X,x}/𝔪_y 𝒪_{X,x}` (`kaehlerSpanLE_stalkMap_iff_fiber`, using
  `SGA.SGA1.ExposeI.FiberStalk`);
* `m ≤ d`: the dimension at `x` of `f⁻¹(y) ∩ U` is `m`, and a space all of whose irreducible
  components have dimension `≤ d` has dimension `≤ d`
  (`topologicalKrullDim_le_of_forall_mem_irreducibleComponents`);
* `d ≤ trdeg_{κ(f ζ)} κ(ζ)`, `ζ` the generic point of the irreducible component of `U` through
  `x`: the irreducible component through `ζ` of the fibre `f⁻¹(f ζ) ∩ U` has dimension `d`, and
  the transcendence degree strictly decreases along strict specializations inside a fibre
  (`residueFieldTrdeg_lt_of_specializes`, `topologicalKrullDim_le_residueFieldTrdeg`);
* `f ζ` is the generic point of an irreducible component of `Y`, so of `Spec 𝒪_y`, whence
  `ζ` lies over the generic point of `Spec 𝒪_y`.
-/

universe u

open AlgebraicGeometry CategoryTheory Limits IsLocalRing KaehlerDifferential Order Topology

namespace SGA.SGA1.ExposeII


set_option backward.isDefEq.respectTransparency false in
/-- `Ω¹_{X/Y}` is generated by `n` elements at `x` iff `Ω¹_{X_y/κ(y)}` is, `x` a point of the
fibre `X_y` (Nakayama along `𝒪_{X,x} → 𝒪_{X_y,x} = 𝒪_{X,x}/𝔪_y 𝒪_{X,x}`). -/
theorem kaehlerSpanLE_stalkMap_iff_fiber {X Y : Scheme.{u}} (f : X ⟶ Y) [LocallyOfFiniteType f]
    [IsLocallyNoetherian Y] (n : ℕ) (y : Y) (z : f.fiber y) :
    KaehlerSpanLE n (f.stalkMap (f.fiberι y z)).hom ↔
      KaehlerSpanLE n ((f.fiberToSpecResidueField y).stalkMap z).hom := by
  have hP := kaehlerSpanLE_respectsIso.{u} n
  have h := SGA.SGA1.ExposeI.stalkMap_iff_stalkMap_fiberMap f (𝟙 Y) f (Category.comp_id f)
    (fun φ ↦ KaehlerSpanLE n φ) (fun _ ↦ True) hP SGA.SGA1.ExposeI.respectsIso_true
    (fun A B C _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ↦ by
      rw [kaehlerSpanLE_algebraMap, kaehlerSpanLE_algebraMap]
      refine exists_span_kaehler_iff_quotient _ ?_ n
      rw [Ideal.map_le_iff_le_comap]
      intro b hb
      rw [Ideal.mem_comap, mem_maximalIdeal, mem_nonunits_iff]
      refine fun hu ↦ ?_
      have hb' : b ∈ maximalIdeal B :=
        Ideal.map_le_iff_le_comap.mpr (maximalIdeal_comap (algebraMap A B)).ge hb
      exact (mem_maximalIdeal _).mp hb' (isUnit_of_map_unit _ _ hu))
    (fun _ ↦ trivial) (fun _ ↦ trivial) y z
  rw [h]
  have hfac := SGA.SGA1.ExposeI.fiberMap_fiberToSpecResidueField f (𝟙 Y) f (Category.comp_id f) y
  have : IsIso (Scheme.Hom.fiberToSpecResidueField (𝟙 Y) y) := by
    unfold Scheme.Hom.fiberToSpecResidueField
    infer_instance
  rw [Scheme.Hom.stalkMap_congr_hom _ _ hfac.symm z, Scheme.Hom.stalkMap_comp]
  exact ((hP.cancel_left_isIso _ _).trans (hP.cancel_left_isIso _ _)).symm



set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
/-- At a point `z` where a scheme `F` locally of finite presentation over a field `K` is smooth,
`Ω¹_{F/K}` is generated at `z` by `m = dim_z F` elements. -/
theorem exists_kaehlerSpanLE_of_mem_smoothLocus {F : Scheme.{u}} {K : CommRingCat.{u}}
    (hK : IsField K) (g : F ⟶ Spec K) [LocallyOfFinitePresentation g] {z : F}
    (hz : z ∈ g.smoothLocus) :
    ∃ m : ℕ, KaehlerSpanLE m (g.stalkMap z).hom ∧ topologicalKrullDimAt F z = m := by
  obtain ⟨U, hU, V, hV, hVU, hzV, H⟩ := exists_smooth_of_formallySmooth_stalk g z hz
  let := hK.toField
  have hU' : U = ⊤ := by
    refine eq_top_iff.mpr fun y _ ↦ ?_
    have : Subsingleton (Spec K) := inferInstanceAs (Subsingleton (PrimeSpectrum K))
    exact Subsingleton.elim (g z) y ▸ hVU hzV
  subst hU'
  have := g.finitePresentation_appLE hU hV hVU
  algebraize [(g.appLE ⊤ V hVU).hom]
  have : Algebra.Smooth Γ(Spec K, ⊤) Γ(F, V) := H
  have : Algebra.IsSmoothAt Γ(Spec K, ⊤) (hV.primeIdealOf ⟨z, hzV⟩).asIdeal := by
    have := Algebra.smoothLocus_eq_univ (R := Γ(Spec K, ⊤)) (A := Γ(F, V)) ▸
      Set.mem_univ (hV.primeIdealOf ⟨z, hzV⟩)
    exact this
  obtain ⟨r, hrz, hr⟩ := Algebra.IsSmoothAt.exists_notMem_isStandardSmooth Γ(Spec K, ⊤)
    (hV.primeIdealOf ⟨z, hzV⟩).asIdeal
  obtain ⟨ι, σ, _, _, ⟨P⟩⟩ := hr.out
  have hrd : Algebra.IsStandardSmoothOfRelativeDimension P.dimension Γ(Spec K, ⊤)
      (Localization.Away r) := P.isStandardSmoothOfRelativeDimension rfl
  have hzr : z ∈ F.basicOpen r := by
    rwa [← PrimeSpectrum.mem_basicOpen, IsAffineOpen.primeIdealOf,
      ← hV.fromSpec_preimage_basicOpen, Scheme.Hom.mem_preimage, ← Scheme.Hom.comp_apply,
      IsAffineOpen.isoSpec_hom, IsAffineOpen.toSpecΓ_fromSpec] at hrz
  have e : F.basicOpen r ≤ g ⁻¹ᵁ ⊤ := le_top
  have hstd : (g.appLE ⊤ (F.basicOpen r) e).hom.IsStandardSmoothOfRelativeDimension
      P.dimension := by
    have := hV.isLocalization_basicOpen r
    rw [← RingHom.isStandardSmoothOfRelativeDimension_algebraMap] at hrd
    convert! RingHom.isStandardSmoothOfRelativeDimension_respectsIso.1 _
      (IsLocalization.algEquiv (.powers r) _ Γ(F, F.basicOpen r)).toRingEquiv hrd
    ext
    dsimp
    simp only [IsScalarTower.algebraMap_apply Γ(Spec K, ⊤) Γ(F, V) (Localization _),
      IsLocalization.map_eq]
    simp only [RingHom.algebraMap_toAlgebra, RingHomCompTriple.comp_apply,
      ← ConcreteCategory.comp_apply, Scheme.Hom.appLE_map]
  set m := P.dimension
  have hfield : IsField Γ(Spec K, ⊤) :=
    MulEquiv.isField hK (Scheme.ΓSpecIso K).commRingCatIsoToRingEquiv.toMulEquiv
  refine ⟨m, ?_, ?_⟩
  · rw [(kaehlerSpanLE_respectsIso m).arrow_mk_iso_iff
      (IsAffineOpen.arrowStalkMapIso g ⊤ hU (F.basicOpen r) (hV.basicOpen r) e hzr)]
    let := (g.appLE ⊤ (F.basicOpen r) e).hom.toAlgebra
    have : Algebra.IsStandardSmoothOfRelativeDimension m Γ(Spec K, ⊤) Γ(F, F.basicOpen r) := hstd
    have : Algebra.IsStandardSmooth Γ(Spec K, ⊤) Γ(F, F.basicOpen r) :=
      Algebra.IsStandardSmoothOfRelativeDimension.isStandardSmooth m
    set p₀ := hU.primeIdealOf ⟨g z, e hzr⟩
    set q := (hV.basicOpen r).primeIdealOf ⟨z, hzr⟩
    have : q.asIdeal.LiesOver p₀.asIdeal :=
      ⟨congr($(IsAffineOpen.comap_primeIdealOf_appLE ⊤ hU _ (hV.basicOpen r) e hzr).1).symm⟩
    let := Localization.AtPrime.algebraOfLiesOver p₀.asIdeal q.asIdeal
    change KaehlerSpanLE m (algebraMap (Localization.AtPrime p₀.asIdeal)
      (Localization.AtPrime q.asIdeal))
    rw [kaehlerSpanLE_algebraMap]
    have : Nontrivial Γ(F, F.basicOpen r) := ⟨⟨0, 1, fun h ↦ q.2.ne_top
      ((Ideal.eq_top_iff_one _).mpr (h ▸ q.asIdeal.zero_mem))⟩⟩
    let b := Module.finBasisOfFinrankEq Γ(F, F.basicOpen r) Ω[Γ(F, F.basicOpen r)⁄Γ(Spec K, ⊤)]
      (Module.finrank_eq_of_rank_eq
        (Algebra.IsStandardSmoothOfRelativeDimension.rank_kaehlerDifferential m))
    refine exists_span_kaehler_of_square (algebraMap Γ(Spec K, ⊤) (Localization.AtPrime p₀.asIdeal))
      (algebraMap Γ(F, F.basicOpen r) (Localization.AtPrime q.asIdeal)) (fun a ↦ ?_) ?_
      ⟨b, b.span_eq⟩
    · rw [← IsScalarTower.algebraMap_apply, ← IsScalarTower.algebraMap_apply]
    · have h1 := span_range_map_derivation_of_isLocalization (R := Γ(Spec K, ⊤))
        (S := Γ(F, F.basicOpen r)) (T := Localization.AtPrime q.asIdeal) q.asIdeal.primeCompl
      have hsurj := KaehlerDifferential.map_surjective Γ(Spec K, ⊤)
        (Localization.AtPrime p₀.asIdeal) (Localization.AtPrime q.asIdeal)
      refine _root_.eq_top_iff.mpr fun w _ ↦ ?_
      obtain ⟨w, rfl⟩ := hsurj w
      have hw : w ∈ Submodule.span (Localization.AtPrime q.asIdeal)
          (Set.range (KaehlerDifferential.map Γ(Spec K, ⊤) Γ(Spec K, ⊤) Γ(F, F.basicOpen r)
            (Localization.AtPrime q.asIdeal) ∘ D Γ(Spec K, ⊤) Γ(F, F.basicOpen r))) :=
        h1 ▸ Submodule.mem_top
      have := Submodule.mem_map_of_mem (f := KaehlerDifferential.map Γ(Spec K, ⊤)
        (Localization.AtPrime p₀.asIdeal) (Localization.AtPrime q.asIdeal)
        (Localization.AtPrime q.asIdeal)) hw
      rw [Submodule.map_span, ← Set.range_comp] at this
      convert this using 3
      ext b
      simp [KaehlerDifferential.map_D]
  · let := hfield.toField
    let := (g.appLE ⊤ (F.basicOpen r) e).hom.toAlgebra
    have : Algebra.IsStandardSmoothOfRelativeDimension m Γ(Spec K, ⊤) Γ(F, F.basicOpen r) := hstd
    rw [(hV.basicOpen r).topologicalKrullDimAt_eq hzr]
    exact Algebra.IsStandardSmoothOfRelativeDimension.topologicalKrullDimAt_eq Γ(Spec K, ⊤) m _

/-- `Ω¹_{S_Q/R} = Ω¹_{S_Q/R_p}`: generators transfer. -/
lemma exists_span_kaehler_of_localization {R S : Type*} [CommRing R] [CommRing S] [Algebra R S]
    (p : Ideal R) (Q : Ideal S) [p.IsPrime] [Q.IsPrime] [Q.LiesOver p] {n : ℕ}
    (h : letI := Localization.AtPrime.algebraOfLiesOver p Q
      ∃ ω : Fin n → Ω[Localization.AtPrime Q⁄Localization.AtPrime p],
        Submodule.span (Localization.AtPrime Q) (Set.range ω) = ⊤) :
    ∃ ω : Fin n → Ω[Localization.AtPrime Q⁄R],
      Submodule.span (Localization.AtPrime Q) (Set.range ω) = ⊤ := by
  let := Localization.AtPrime.algebraOfLiesOver p Q
  obtain ⟨ω, hω⟩ := h
  have : Algebra.FormallyEtale R (Localization.AtPrime p) :=
    .of_isLocalization p.primeCompl
  have hbij : Function.Bijective (KaehlerDifferential.map R (Localization.AtPrime p)
      (Localization.AtPrime Q) (Localization.AtPrime Q)) := by
    refine ⟨?_, KaehlerDifferential.map_surjective _ _ _⟩
    rw [injective_iff_map_eq_zero]
    intro v hv
    obtain ⟨t, rfl⟩ := (KaehlerDifferential.exact_mapBaseChange_map R (Localization.AtPrime p)
      (Localization.AtPrime Q) v).mp hv
    rw [Subsingleton.elim t 0, map_zero]
  let e := LinearEquiv.ofBijective (KaehlerDifferential.map R (Localization.AtPrime p)
      (Localization.AtPrime Q) (Localization.AtPrime Q)) hbij
  refine ⟨fun i ↦ e.symm (ω i), ?_⟩
  have := congrArg (Submodule.map e.symm.toLinearMap) hω
  rw [Submodule.map_span, Submodule.map_top, LinearEquiv.range, ← Set.range_comp] at this
  exact this



/-- In an algebra of finite type over a field, the transcendence degree of the residue field
strictly decreases along a strict inclusion of primes. -/
theorem trdeg_residueField_lt_of_lt (k : Type*) {A : Type*} [Field k] [CommRing A] [Algebra k A]
    [Algebra.FiniteType k A] {P P' : PrimeSpectrum A} (h : P < P') :
    (Algebra.trdeg k P'.asIdeal.ResidueField).toENat <
      (Algebra.trdeg k P.asIdeal.ResidueField).toENat := by
  have : Nontrivial A :=
    ⟨⟨0, 1, fun h ↦ P.2.ne_top ((Ideal.eq_top_iff_one _).mpr (h ▸ P.asIdeal.zero_mem))⟩⟩
  have := Algebra.FiniteType.finiteRingKrullDim k (A := A)
  have e₁ := Algebra.FiniteType.trdeg_residueField k P.asIdeal
  have e₂ := Algebra.FiniteType.trdeg_residueField k P'.asIdeal
  rw [← PrimeSpectrum.coheight_eq_ringKrullDim_quotient] at e₁ e₂
  have e₁' : (Algebra.trdeg k P.asIdeal.ResidueField).toENat = coheight P := by exact_mod_cast e₁
  have e₂' : (Algebra.trdeg k P'.asIdeal.ResidueField).toENat = coheight P' := by exact_mod_cast e₂
  rw [e₁', e₂']
  exact coheight_strictAnti h (coheight_lt_top P')

/-- The transcendence degree of a point of a fibre can be computed in the fibre. -/
theorem residueFieldTrdeg_fiberToSpecResidueField' {X Y : Scheme.{u}} (f : X ⟶ Y) (y : Y)
    (a : f.fiber y) :
    (f.fiberToSpecResidueField y).residueFieldTrdeg a = f.residueFieldTrdeg (f.fiberι y a) := by
  have h := congrArg (fun φ : f.fiber y ⟶ Y ↦ φ.residueFieldTrdeg a) (f.fiber_fac y)
  simp only [Scheme.Hom.residueFieldTrdeg_comp] at h
  rw [Scheme.Hom.residueFieldTrdeg_eq_zero_of_surjective (f.fiberι y) _
      (Scheme.Hom.residueFieldMap_surjective _ _),
    Scheme.Hom.residueFieldTrdeg_eq_zero_of_surjective (Y.fromSpecResidueField y) _
      (Scheme.Hom.residueFieldMap_surjective _ _), add_zero, zero_add] at h
  exact h.symm

set_option backward.isDefEq.respectTransparency false in
/-- Inside a fibre of a morphism locally of finite type, the transcendence degree of the residue
field strictly decreases along a strict specialization. -/
theorem residueFieldTrdeg_lt_of_specializes {X Y : Scheme.{u}} (f : X ⟶ Y)
    [LocallyOfFiniteType f] {w w' : X} (h : w ⤳ w') (hne : w ≠ w') (hf : f w = f w') :
    (f.residueFieldTrdeg w').toENat < (f.residueFieldTrdeg w).toENat := by
  set y := f w'
  set g := f.fiberToSpecResidueField y
  set a : f.fiber y := (f.fiberHomeo y).symm ⟨w, hf⟩
  set a' : f.fiber y := (f.fiberHomeo y).symm ⟨w', rfl⟩
  have ha : f.fiberι y a = w := f.fiberι_fiberHomeo_symm y _
  have ha' : f.fiberι y a' = w' := f.fiberι_fiberHomeo_symm y _
  rw [← ha, ← ha', ← residueFieldTrdeg_fiberToSpecResidueField',
    ← residueFieldTrdeg_fiberToSpecResidueField']
  have hemb : IsEmbedding (f.fiberι y) := by
    have : (f.fiberι y : f.fiber y → X) = Subtype.val ∘ f.fiberHomeo y :=
      funext fun _ ↦ (f.fiberHomeo_apply y _).symm
    rw [this]
    exact IsEmbedding.subtypeVal.comp (f.fiberHomeo y).isEmbedding
  have hsp : a ⤳ a' := by
    rw [← hemb.isInducing.specializes_iff, ha, ha']
    exact h
  have hne' : a ≠ a' := fun e ↦ hne (by rw [← ha, ← ha', e])
  -- an affine chart of the fibre around `a'`
  obtain ⟨_, ⟨W, hW, rfl⟩, ha'W, -⟩ :=
    (f.fiber y).isBasis_affineOpens.exists_subset_of_mem_open (Set.mem_univ a') isOpen_univ
  have haW : a ∈ W := hsp.mem_open W.isOpen ha'W
  have hR : IsField (Y.residueField y) := Field.toIsField _
  have e : W ≤ g ⁻¹ᵁ ⊤ := le_top
  have hft : (g.appLE ⊤ W e).hom.FiniteType :=
    HasRingHomProperty.appLE @LocallyOfFiniteType g inferInstance ⟨⊤, isAffineOpen_top _⟩
      ⟨W, hW⟩ e
  have hΓ : IsField Γ(Spec (Y.residueField y), ⊤) :=
    MulEquiv.isField hR (Scheme.ΓSpecIso _).commRingCatIsoToRingEquiv.toMulEquiv
  let := hΓ.toField
  let := (g.appLE ⊤ W e).hom.toAlgebra
  have : Algebra.FiniteType Γ(Spec (Y.residueField y), ⊤) Γ(f.fiber y, W) := hft
  have key (b : f.fiber y) (hb : b ∈ W) : (g.residueFieldTrdeg b).toENat =
      (Algebra.trdeg Γ(Spec (Y.residueField y), ⊤)
        (hW.primeIdealOf ⟨b, hb⟩).asIdeal.ResidueField).toENat := by
    rw [hW.trdeg_residueField_primeIdealOf_eq g e hb,
      Scheme.Hom.trdeg_eq_residueFieldTrdeg g (e hb)
        (Spec.evaluation_top_bijective_of_isField hR (g b))]
  rw [key a haW, key a' ha'W]
  refine trdeg_residueField_lt_of_lt _ (lt_of_le_of_ne ?_ fun hPP ↦ hne' ?_)
  · rw [PrimeSpectrum.le_iff_specializes, ← hW.fromSpec.isOpenEmbedding.isInducing.specializes_iff,
      hW.fromSpec_primeIdealOf, hW.fromSpec_primeIdealOf]
    exact hsp
  · have := congrArg hW.fromSpec hPP
    rwa [hW.fromSpec_primeIdealOf, hW.fromSpec_primeIdealOf] at this

/-- Weak form of `residueFieldTrdeg_lt_of_specializes`. -/
theorem residueFieldTrdeg_le_of_specializes {X Y : Scheme.{u}} (f : X ⟶ Y)
    [LocallyOfFiniteType f] {w w' : X} (h : w ⤳ w') (hf : f w = f w') :
    (f.residueFieldTrdeg w').toENat ≤ (f.residueFieldTrdeg w).toENat := by
  by_cases hne : w = w'
  · rw [hne]
  · exact (residueFieldTrdeg_lt_of_specializes f h hne hf).le

set_option backward.isDefEq.respectTransparency false in
/-- Let `T ⊆ X` consist of specializations of a point `ζ`, all in the fibre of `f` through `ζ`
(`f` locally of finite type). Then `dim T ≤ trdeg_{κ(f ζ)} κ(ζ)`: the generic points of a chain
of irreducible closed subsets of `T` lie in that fibre, and their transcendence degrees strictly
decrease along the chain. -/
theorem topologicalKrullDim_le_residueFieldTrdeg {X Y : Scheme.{u}} (f : X ⟶ Y)
    [LocallyOfFiniteType f] {T : Set X} {ζ : X} (hT : T ⊆ closure {ζ})
    (hTf : ∀ w ∈ T, f w = f ζ) :
    topologicalKrullDim T ≤ ((f.residueFieldTrdeg ζ).toENat : WithBot ℕ∞) := by
  refine iSup_le fun l ↦ ?_
  let w : Fin (l.length + 1) → X := fun i ↦
    ((l i).isIrreducible.image Subtype.val continuous_subtype_val.continuousOn).genericPoint
  have hw (i) : closure {w i} = closure (Subtype.val '' (l i : Set T)) :=
    ((l i).isIrreducible.image Subtype.val
      continuous_subtype_val.continuousOn).genericPoint_closure_eq
  have hwζ (i) : ζ ⤳ w i := by
    rw [specializes_iff_mem_closure]
    have : w i ∈ closure {w i} := subset_closure rfl
    rw [hw] at this
    exact closure_minimal ((Set.image_subset_iff.mpr fun t _ ↦ hT t.2)) isClosed_closure this
  have hwf (i) : f (w i) = f ζ := by
    obtain ⟨t, ht⟩ := (l i).isIrreducible.nonempty
    have h1 : w i ⤳ t.1 := by
      rw [specializes_iff_mem_closure, hw]
      exact subset_closure ⟨t, ht, rfl⟩
    have h2 : f (w i) ⤳ f ζ := by
      have := h1.map f.continuous
      rwa [hTf t.1 t.2] at this
    exact (h2.antisymm ((hwζ i).map f.continuous)).eq
  have hlt {i j : Fin (l.length + 1)} (hij : i < j) :
      (f.residueFieldTrdeg (w i)).toENat < (f.residueFieldTrdeg (w j)).toENat := by
    have hl := l.strictMono hij
    have hsub : closure {w i} ⊆ closure {w j} := by
      rw [hw, hw]
      exact closure_mono (Set.image_mono hl.le)
    have hsp : w j ⤳ w i := specializes_iff_mem_closure.mpr (hsub (subset_closure rfl))
    refine residueFieldTrdeg_lt_of_specializes f hsp (fun heq ↦ hl.ne ?_)
      ((hwf j).trans (hwf i).symm)
    have hcl : closure (Subtype.val '' (l i : Set T)) = closure (Subtype.val '' (l j : Set T)) := by
      rw [← hw, ← hw, heq]
    ext t
    rw [← (l i).isClosed.closure_eq, ← (l j).isClosed.closure_eq,
      IsInducing.subtypeVal.closure_eq_preimage_closure_image,
      IsInducing.subtypeVal.closure_eq_preimage_closure_image, hcl]
  have hind : ∀ k (hk : k < l.length + 1), (k : ℕ∞) ≤ (f.residueFieldTrdeg (w ⟨k, hk⟩)).toENat := by
    intro k
    induction k with
    | zero => intro _; simp
    | succ k ih =>
      intro hk
      have h1 := ih (by omega)
      have h2 := hlt (i := ⟨k, by omega⟩) (j := ⟨k + 1, hk⟩) (by simp [Fin.lt_def])
      exact Order.add_one_le_of_lt (lt_of_le_of_lt h1 h2)
  have hlast := hind l.length (by omega)
  have hζ := residueFieldTrdeg_le_of_specializes f (hwζ ⟨l.length, by omega⟩) (hwf _).symm
  exact_mod_cast hlast.trans hζ

/-- A space whose irreducible components all have dimension `≤ d` has dimension `≤ d`: every
chain of irreducible closed subsets lies in one component. -/
theorem topologicalKrullDim_le_of_forall_mem_irreducibleComponents {S : Type*}
    [TopologicalSpace S] {d : WithBot ℕ∞}
    (h : ∀ C ∈ irreducibleComponents S, topologicalKrullDim C ≤ d) :
    topologicalKrullDim S ≤ d := by
  refine iSup_le fun l ↦ ?_
  obtain ⟨C, hC, hlC⟩ := exists_mem_irreducibleComponents_subset_of_isIrreducible _
    (l (Fin.last _)).isIrreducible
  have hsub (i) : (l i : Set S) ⊆ C := fun s hs ↦ hlC (l.monotone (Fin.le_last i) hs)
  let Z (i : Fin (l.length + 1)) : TopologicalSpace.IrreducibleCloseds C :=
    { carrier := Subtype.val ⁻¹' (l i : Set S)
      isIrreducible' := by
        refine ⟨?_, fun u v hu hv ⟨a, ha, hau⟩ ⟨b, hb, hbv⟩ ↦ ?_⟩
        · obtain ⟨s, hs⟩ := (l i).isIrreducible.nonempty
          exact ⟨⟨s, hsub i hs⟩, hs⟩
        · obtain ⟨u', hu', rfl⟩ := isOpen_induced_iff.mp hu
          obtain ⟨v', hv', rfl⟩ := isOpen_induced_iff.mp hv
          obtain ⟨s, hs, hsu, hsv⟩ := (l i).isIrreducible.isPreirreducible u' v' hu' hv'
            ⟨a, ha, hau⟩ ⟨b, hb, hbv⟩
          exact ⟨⟨s, hsub i hs⟩, hs, hsu, hsv⟩
      isClosed' := (l i).isClosed.preimage continuous_subtype_val }
  have hZ : StrictMono Z := by
    intro i j hij
    have hl := l.strictMono hij
    refine lt_of_le_of_ne (fun a ha ↦ hl.le ha) fun heq ↦ hl.ne ?_
    ext s
    by_cases hs : s ∈ C
    · have := congrArg (fun W : TopologicalSpace.IrreducibleCloseds C ↦ (⟨s, hs⟩ : C) ∈ W) heq
      exact iff_of_eq this
    · exact ⟨fun h ↦ absurd (hsub i h) hs, fun h ↦ absurd (hsub j h) hs⟩
  let l' : LTSeries (TopologicalSpace.IrreducibleCloseds C) :=
    ⟨l.length, Z, fun i ↦ hZ Fin.castSucc_lt_succ⟩
  exact (l'.length_le_krullDim).trans (h C hC)

/-- The generic point of an irreducible component of an open `U ⊆ X` has no proper
generization in `U`. -/
lemma eq_of_specializes_genericPoint {X : Scheme.{u}} {U : X.Opens} {Z : Set U}
    (hZ : Z ∈ irreducibleComponents U) {τ : X} (hτU : τ ∈ U)
    (hτ : τ ⤳ (hZ.1.genericPoint : U).1) : τ = (hZ.1.genericPoint : U).1 := by
  have : QuasiSober U := inferInstanceAs (QuasiSober U.toScheme)
  have : T0Space U := inferInstanceAs (T0Space U.toScheme)
  set ζ₀ := hZ.1.genericPoint
  have hζ : closure {ζ₀} = Z :=
    hZ.1.isGenericPoint_genericPoint (isClosed_of_mem_irreducibleComponents Z hZ)
  let t : type_of% ζ₀ := ⟨τ, hτU⟩
  have hτ' : t ⤳ ζ₀ := IsInducing.subtypeVal.specializes_iff.mp hτ
  have h₁ : Z ⊆ closure {t} := hζ ▸ specializes_iff_closure_subset.mp hτ'
  have h₂ : closure {t} ⊆ Z := hZ.2 isIrreducible_singleton.closure h₁
  have h₃ : ζ₀ ⤳ t := by
    rw [specializes_iff_mem_closure, hζ]
    exact h₂ (subset_closure rfl)
  exact congrArg Subtype.val (hτ'.antisymm h₃).eq

/-- A point `η` whose closure is an irreducible component has no proper generization. -/
lemma eq_of_specializes_of_mem_irreducibleComponents {Y : Scheme.{u}} {η : Y}
    (hη : closure {η} ∈ irreducibleComponents Y) {τ : Y} (hτ : τ ⤳ η) : τ = η := by
  have h₁ : closure {η} ⊆ closure {τ} := specializes_iff_closure_subset.mp hτ
  have h₂ : closure {τ} ⊆ closure {η} := hη.2 isIrreducible_singleton.closure h₁
  exact (hτ.antisymm (specializes_iff_mem_closure.mpr (h₂ (subset_closure rfl)))).eq

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
/-- On an affine open `U`, the section `a` vanishes at `y` iff `a ∈ 𝔭_y`. -/
lemma mem_primeIdealOf_of_evaluation_eq_zero {Y : Scheme.{u}} {U : Y.Opens} (hU : IsAffineOpen U)
    {y : Y} (hy : y ∈ U) {a : Γ(Y, U)} (ha : Y.evaluation U y hy a = 0) :
    a ∈ (hU.primeIdealOf ⟨y, hy⟩).asIdeal := by
  by_contra h
  have hmem : a ∉ (hU.primeIdealOf ⟨y, hy⟩).asIdeal := h
  rw [← PrimeSpectrum.mem_basicOpen, IsAffineOpen.primeIdealOf,
    ← hU.fromSpec_preimage_basicOpen, Scheme.Hom.mem_preimage, ← Scheme.Hom.comp_apply,
    IsAffineOpen.isoSpec_hom, IsAffineOpen.toSpecΓ_fromSpec] at hmem
  exact (Y.evaluation_eq_zero_iff_notMem_basicOpen y hy a).mp ha hmem

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
/-- II.2.3, "if", for schemes: let `f` be locally of finite presentation over a locally noetherian
`Y`, and `x ∈ X` with `𝒪_{f(x)}` a normal domain. If `f` is equidimensional at `x` and the fibre
`f⁻¹(f(x))` is smooth over `κ(f(x))` at `x`, then `f` is smooth at `x`. -/
theorem mem_smoothLocus_of_isEquidimensionalAt {X Y : Scheme.{u}} (f : X ⟶ Y)
    [LocallyOfFinitePresentation f] [IsLocallyNoetherian Y] {x : X}
    (hdom : IsDomain (Y.presheaf.stalk (f x)))
    (hnorm : IsIntegrallyClosed (Y.presheaf.stalk (f x)))
    (heq : IsEquidimensionalAt f x)
    (hfib : f.asFiber x ∈ (f.fiberToSpecResidueField (f x)).smoothLocus) :
    x ∈ f.smoothLocus := by
  set y := f x with hy
  -- the fibre is smooth of dimension `m` at `x`, and `Ω¹_{X/Y}` is generated by `m` elements
  obtain ⟨m, hmΩ, hmdim⟩ := exists_kaehlerSpanLE_of_mem_smoothLocus
    (Field.toIsField (Y.residueField y)) (f.fiberToSpecResidueField y) hfib
  have hΩx : KaehlerSpanLE m (f.stalkMap x).hom := by
    have := (kaehlerSpanLE_stalkMap_iff_fiber f m y (f.asFiber x)).mpr hmΩ
    rwa [(kaehlerSpanLE_respectsIso m).arrow_mk_iso_iff
      (Scheme.Hom.arrowStalkMapIsoOfEq f (f.fiberι_asFiber x))] at this
  -- the equidimensional neighbourhood and the component of `x`
  obtain ⟨U₁, hxU₁, hcomp, d, hdim⟩ := heq
  have : QuasiSober {x // x ∈ U₁} := inferInstanceAs (QuasiSober U₁.toScheme)
  have : T0Space {x // x ∈ U₁} := inferInstanceAs (T0Space U₁.toScheme)
  let x₁ : {x // x ∈ U₁} := ⟨x, hxU₁⟩
  have hZ := irreducibleComponent_mem_irreducibleComponents x₁
  have hZY := hcomp _ hZ
  set ζ₀ := hZ.1.genericPoint
  set ζ : X := ζ₀.1
  have hζ₀ : closure {ζ₀} = irreducibleComponent x₁ :=
    hZ.1.isGenericPoint_genericPoint (isClosed_of_mem_irreducibleComponents _ hZ)
  have hζx : ζ ⤳ x := by
    have : ζ₀ ⤳ x₁ := by
      rw [specializes_iff_mem_closure, hζ₀]
      exact mem_irreducibleComponent
    exact this.map continuous_subtype_val
  -- `f ζ` is the generic point of an irreducible component of `Y`
  have hZcl : Subtype.val '' irreducibleComponent x₁ ⊆ closure {ζ} := by
    rintro _ ⟨z, hz, rfl⟩
    rw [← hζ₀, ← specializes_iff_mem_closure] at hz
    exact specializes_iff_mem_closure.mp (hz.map continuous_subtype_val)
  have hcl : closure (f '' (Subtype.val '' irreducibleComponent x₁)) = closure {f ζ} := by
    refine le_antisymm ?_ (closure_mono (Set.singleton_subset_iff.mpr
      ⟨ζ, ⟨ζ₀, hζ₀ ▸ subset_closure rfl, rfl⟩, rfl⟩))
    refine closure_minimal ((Set.image_mono hZcl).trans ?_) isClosed_closure
    refine (image_closure_subset_closure_image f.continuous).trans ?_
    rw [Set.image_singleton]
  rw [hcl] at hZY
  have hfζmax : ∀ τ, τ ⤳ f ζ → τ = f ζ := fun τ hτ ↦
    eq_of_specializes_of_mem_irreducibleComponents hZY hτ
  -- `m ≤ d`: the fibre through `x` has dimension `m` at `x`
  have hmd : (m : WithBot ℕ∞) ≤ d := by
    have h1 : topologicalKrullDimAt ↥(f ⁻¹' {f x} ∩ (U₁ : Set X)) ⟨x, rfl, hxU₁⟩ = m := by
      rw [topologicalKrullDimAt_inter_of_isOpen U₁.isOpen, ← Scheme.Hom.fiberDimAt_eq]
      exact hmdim
    rw [← h1]
    refine (topologicalKrullDimAt_le_topologicalKrullDim _).trans ?_
    exact topologicalKrullDim_le_of_forall_mem_irreducibleComponents fun C hC ↦ (hdim _ C hC).le
  -- `d ≤ trdeg κ(ζ)`: the component through `ζ` of its fibre has dimension `d`
  have hdtr : (d : WithBot ℕ∞) ≤ ((f.residueFieldTrdeg ζ).toENat : WithBot ℕ∞) := by
    let ζ' : ↥(f ⁻¹' {f ζ} ∩ (U₁ : Set X)) := ⟨ζ, rfl, ζ₀.2⟩
    have hC := irreducibleComponent_mem_irreducibleComponents ζ'
    rw [← hdim (f ζ) _ hC, ← IsEmbedding.subtypeVal.topologicalKrullDim_image]
    refine topologicalKrullDim_le_residueFieldTrdeg f ?_ ?_
    · have hirr : IsIrreducible (Subtype.val '' irreducibleComponent ζ') :=
        hC.1.image _ continuous_subtype_val.continuousOn
      have hτζ : hirr.genericPoint ⤳ ζ := by
        rw [specializes_iff_mem_closure, hirr.genericPoint_closure_eq]
        exact subset_closure ⟨ζ', mem_irreducibleComponent, rfl⟩
      have hτU : hirr.genericPoint ∈ U₁ := hτζ.mem_open U₁.isOpen ζ₀.2
      have := eq_of_specializes_genericPoint hZ hτU hτζ
      rw [← hirr.genericPoint_closure_eq.symm.trans (congrArg (fun a ↦ closure {a}) this)]
      exact subset_closure
    · rintro _ ⟨s, -, rfl⟩
      exact s.2.1
  -- affine charts `U ∋ y`, `V ∋ x`, with `V` inside the equidimensional neighbourhood
  obtain ⟨_, ⟨U, hU, rfl⟩, hyU, -⟩ :=
    Y.isBasis_affineOpens.exists_subset_of_mem_open (Set.mem_univ y) isOpen_univ
  obtain ⟨_, ⟨V, hV, rfl⟩, hxV, hVsub⟩ :=
    X.isBasis_affineOpens.exists_subset_of_mem_open
      (show x ∈ (f ⁻¹ᵁ U ⊓ U₁ : X.Opens) from ⟨hyU, hxU₁⟩) (f ⁻¹ᵁ U ⊓ U₁).isOpen
  have hVU : V ≤ f ⁻¹ᵁ U := fun v hv ↦ (hVsub hv).1
  have hζV : ζ ∈ V := hζx.mem_open V.isOpen hxV
  have hfζU : f ζ ∈ U := hVU hζV
  have := f.finitePresentation_appLE hU hV hVU
  rw [Scheme.Hom.mem_smoothLocus, formallySmooth_stalkMap_iff U hU V hV hVU hxV]
  algebraize [(f.appLE U V hVU).hom]
  set p := hU.primeIdealOf ⟨f x, hVU hxV⟩
  set Q := hV.primeIdealOf ⟨x, hxV⟩
  set P := hV.primeIdealOf ⟨ζ, hζV⟩
  have : Q.asIdeal.LiesOver p.asIdeal :=
    ⟨congr($(IsAffineOpen.comap_primeIdealOf_appLE U hU V hV hVU hxV).1).symm⟩
  -- `R_p ≅ 𝒪_y` is a normal domain
  have : IsDomain (Localization.AtPrime p.asIdeal) ∧
      IsIntegrallyClosed (Localization.AtPrime p.asIdeal) := by
    let := Y.presheaf.algebra_section_stalk ⟨f x, hVU hxV⟩
    have := hU.isLocalization_stalk ⟨f x, hVU hxV⟩
    exact SGA.SGA1.ExposeI.isDomain_and_isIntegrallyClosed_of_ringEquiv
      (IsLocalization.algEquiv p.asIdeal.primeCompl (Y.presheaf.stalk (f x))
        (Localization.AtPrime p.asIdeal)).toRingEquiv ⟨hdom, hnorm⟩
  obtain ⟨_, _⟩ := this
  -- `Ω¹_{S_Q/R}` is generated by `m` elements
  obtain ⟨ω, hω⟩ : ∃ ω : Fin m → Ω[Localization.AtPrime Q.asIdeal⁄Γ(Y, U)],
      Submodule.span (Localization.AtPrime Q.asIdeal) (Set.range ω) = ⊤ := by
    have h1 := ((kaehlerSpanLE_respectsIso m).arrow_mk_iso_iff
      (IsAffineOpen.arrowStalkMapIso f U hU V hV hVU hxV)).mp hΩx
    refine exists_span_kaehler_of_localization p.asIdeal Q.asIdeal ?_
    let := Localization.AtPrime.algebraOfLiesOver p.asIdeal Q.asIdeal
    exact (kaehlerSpanLE_algebraMap m).mp h1
  -- the generization `P` of `Q`
  have hPQ : P.asIdeal ≤ Q.asIdeal := by
    change P ≤ Q
    rw [PrimeSpectrum.le_iff_specializes, ← hV.fromSpec.isOpenEmbedding.isInducing.specializes_iff,
      hV.fromSpec_primeIdealOf, hV.fromSpec_primeIdealOf]
    exact hζx
  -- the field `K = κ(f ζ)`, through which `R → κ(P) ≅ κ(ζ)` factors
  let K := Y.residueField (f ζ)
  let : Algebra Γ(Y, U) K := (Y.evaluation U (f ζ) hfζU).hom.toAlgebra
  let _ := X.presheaf.algebra_section_stalk ⟨ζ, hζV⟩
  have := hV.isLocalization_stalk ⟨ζ, hζV⟩
  let ε : Localization.AtPrime P.asIdeal ≃ₐ[Γ(X, V)] X.presheaf.stalk ζ :=
    IsLocalization.algEquiv P.asIdeal.primeCompl _ _
  let ψ : P.asIdeal.ResidueField ≃+* X.residueField ζ :=
    IsLocalRing.ResidueField.mapEquiv ε.toRingEquiv
  let : Algebra K P.asIdeal.ResidueField :=
    (ψ.symm.toRingHom.comp (f.residueFieldMap ζ).hom).toAlgebra
  have hψ (a : Γ(Y, U)) : ψ (algebraMap Γ(Y, U) P.asIdeal.ResidueField a) =
      f.residueFieldMap ζ (Y.evaluation U (f ζ) hfζU a) := by
    change ψ (IsLocalRing.residue _ (algebraMap Γ(Y, U) (Localization.AtPrime P.asIdeal) a)) = _
    rw [IsScalarTower.algebraMap_apply Γ(Y, U) Γ(X, V) (Localization.AtPrime P.asIdeal)]
    change IsLocalRing.residue _ (ε (algebraMap Γ(X, V) _ (algebraMap Γ(Y, U) Γ(X, V) a))) = _
    rw [AlgEquiv.commutes]
    change X.evaluation V ζ hζV (f.appLE U V hVU a) =
      f.residueFieldMap ζ (Y.evaluation U (f ζ) (hVU hζV) a)
    refine Eq.trans ?_ (Scheme.evaluation_naturality_apply f ζ (hVU hζV) a).symm
    rw [Scheme.Hom.appLE, CommRingCat.comp_apply]
    simp only [Scheme.evaluation, CommRingCat.comp_apply, TopCat.Presheaf.germ_res_apply]
  have : IsScalarTower Γ(Y, U) K P.asIdeal.ResidueField := .of_algebraMap_eq fun a ↦ by
    change algebraMap Γ(Y, U) P.asIdeal.ResidueField a =
      ψ.symm (f.residueFieldMap ζ (Y.evaluation U (f ζ) hfζU a))
    rw [← hψ, RingEquiv.symm_apply_apply]
  have htrK : Algebra.trdeg K P.asIdeal.ResidueField = f.residueFieldTrdeg ζ := by
    let : Algebra K (X.residueField ζ) := (f.residueFieldMap ζ).hom.toAlgebra
    let e : P.asIdeal.ResidueField ≃ₐ[K] X.residueField ζ :=
      AlgEquiv.ofRingEquiv (f := ψ) fun k ↦ by
        change ψ (ψ.symm _) = _
        rw [RingEquiv.apply_symm_apply]
        rfl
    exact e.trdeg_eq
  -- `ζ` lies over the generic point of `Spec R_p`
  have hK : RingHom.ker (algebraMap Γ(Y, U) K) ≤
      RingHom.ker (algebraMap Γ(Y, U) (Localization.AtPrime p.asIdeal)) := by
    set p₀ := hU.primeIdealOf ⟨f ζ, hfζU⟩
    have hker : RingHom.ker (algebraMap Γ(Y, U) K) ≤ p₀.asIdeal := fun a ha ↦
      mem_primeIdealOf_of_evaluation_eq_zero hU hfζU ha
    have hp₀p : p₀ ≤ p := by
      rw [PrimeSpectrum.le_iff_specializes,
        ← hU.fromSpec.isOpenEmbedding.isInducing.specializes_iff,
        hU.fromSpec_primeIdealOf, hU.fromSpec_primeIdealOf]
      exact hζx.map f.continuous
    have hmin : ∀ r : PrimeSpectrum Γ(Y, U), r ≤ p₀ → r = p₀ := by
      intro r hr
      have hsp : hU.fromSpec r ⤳ f ζ := by
        have := ((PrimeSpectrum.le_iff_specializes _ _).mp hr).map hU.fromSpec.continuous
        rwa [hU.fromSpec_primeIdealOf] at this
      apply hU.fromSpec.isOpenEmbedding.injective
      rw [hfζmax _ hsp, hU.fromSpec_primeIdealOf]
    let q₁ : PrimeSpectrum Γ(Y, U) :=
      ⟨RingHom.ker (algebraMap Γ(Y, U) (Localization.AtPrime p.asIdeal)), RingHom.ker_isPrime _⟩
    have hq₁ : q₁ ≤ p₀ := fun a ha ↦ by
      obtain ⟨⟨s, hs⟩, hsa⟩ := (IsLocalization.map_eq_zero_iff p.asIdeal.primeCompl _ a).mp ha
      exact (p₀.2.mem_or_mem (hsa ▸ p₀.asIdeal.zero_mem)).resolve_left fun h ↦ hs (hp₀p h)
    have hq₁p₀ := hmin q₁ hq₁
    intro a ha
    have := hker ha
    rw [← hq₁p₀] at this
    exact this
  have htr : (m : Cardinal) ≤ Algebra.trdeg K P.asIdeal.ResidueField := by
    rw [htrK, ← Cardinal.natCast_le_toENat]
    exact_mod_cast hmd.trans hdtr
  exact isSmoothAt_of_span_of_le_trdeg p.asIdeal Q.asIdeal ω hω P.asIdeal hPQ K hK htr


/-- **II.2.3**: let `f : X ⟶ Y` be locally of finite presentation (SGA: of finite type), `Y`
locally noetherian and `x ∈ X` with `𝒪_{f(x)}` normal (a normal domain). Then `f` is smooth at `x`
iff `f` is equidimensional at `x` and the fibre `f⁻¹(f(x))` is smooth over `κ(f(x))` at `x`. -/
theorem mem_smoothLocus_iff_isEquidimensionalAt {X Y : Scheme.{u}} (f : X ⟶ Y)
    [LocallyOfFinitePresentation f] [IsLocallyNoetherian Y] (x : X)
    (hdom : IsDomain (Y.presheaf.stalk (f x)))
    (hnorm : IsIntegrallyClosed (Y.presheaf.stalk (f x))) :
    x ∈ f.smoothLocus ↔ IsEquidimensionalAt f x ∧
      f.asFiber x ∈ (f.fiberToSpecResidueField (f x)).smoothLocus :=
  ⟨isEquidimensionalAt_and_asFiber_mem_smoothLocus f,
    fun ⟨he, hfib⟩ ↦ mem_smoothLocus_of_isEquidimensionalAt f hdom hnorm he hfib⟩

end SGA.SGA1.ExposeII
