/-
Copyright (c) 2026 SGAenglishpluslean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SGAenglishpluslean contributors
-/
import Mathlib.LinearAlgebra.TensorProduct.Quotient
import Mathlib.RingTheory.Kaehler.Basic
import Mathlib.RingTheory.LocalRing.Basic
import Mathlib.RingTheory.Nakayama
import Mathlib.RingTheory.RingHomProperties
import Mathlib.RingTheory.Unramified.Basic

/-!
# The number of generators of `Ω¹` along the fibres

For the proof of II.2.3 we need that `Ω¹_{X/Y}` is generated at `x` by as many elements as
`Ω¹_{X_y/κ(y)}`. Algebraically: for a local `B`-algebra `C` and `I ⊆ B` with `IC ⊆ 𝔪_C`, the kernel
of `Ω¹_{C/B} → Ω¹_{(C/IC)/(B/I)}` is `IC · Ω¹_{C/B}` (the conormal sequence), so by Nakayama
`Ω¹_{C/B}` is generated by `n` elements iff `Ω¹_{(C/IC)/(B/I)}` is
(`exists_span_kaehler_iff_quotient`). We record this as a property `KaehlerSpanLE n` of ring maps
which is invariant under isomorphisms, so that it can be moved between stalks and affine charts.
-/

universe u

open Algebra KaehlerDifferential TensorProduct IsLocalRing

namespace SGA.SGA1.ExposeII

/-- Generators of `Ω¹` transport along a commutative square `A → B`, `A' → B'` in which the
`D(b')`, `b'` in the image of `B`, generate `Ω¹_{B'/A'}` (e.g. `B → B'` surjective, or a
localization). -/
lemma exists_span_kaehler_of_square {A B A' B' : Type*} [CommRing A] [CommRing B]
    [CommRing A'] [CommRing B'] [Algebra A B] [Algebra A' B'] (eA : A →+* A') (eB : B →+* B')
    (h : ∀ a, eB (algebraMap A B a) = algebraMap A' B' (eA a))
    (hgen : Submodule.span B' (Set.range fun b ↦ D A' B' (eB b)) = ⊤) {n : ℕ}
    (hω : ∃ ω : Fin n → Ω[B⁄A], Submodule.span B (Set.range ω) = ⊤) :
    ∃ ω' : Fin n → Ω[B'⁄A'], Submodule.span B' (Set.range ω') = ⊤ := by
  obtain ⟨ω, hω⟩ := hω
  let : Algebra A A' := eA.toAlgebra
  let : Algebra B B' := eB.toAlgebra
  let : Algebra A B' := (eB.comp (algebraMap A B)).toAlgebra
  have : IsScalarTower A B B' := .of_algebraMap_eq fun _ ↦ rfl
  have : IsScalarTower A A' B' := .of_algebraMap_eq fun a ↦ h a
  refine ⟨fun i ↦ KaehlerDifferential.map A A' B B' (ω i), ?_⟩
  rw [_root_.eq_top_iff, ← hgen, Submodule.span_le]
  rintro _ ⟨b, rfl⟩
  have hb : D A B b ∈ Submodule.span B (Set.range ω) := hω ▸ Submodule.mem_top
  have := Submodule.mem_map_of_mem (f := KaehlerDifferential.map A A' B B') hb
  rw [Submodule.map_span, ← Set.range_comp] at this
  have hle := Submodule.span_le_restrictScalars B B' (Set.range fun i ↦
    KaehlerDifferential.map A A' B B' (ω i))
  have := hle this
  rw [KaehlerDifferential.map_D] at this
  exact this

/-- For `C` over `B` and an ideal `I ⊆ B`, the kernel of `Ω¹_{C/B} → Ω¹_{(C/IC)/(B/I)}` is
`IC · Ω¹_{C/B}`. -/
lemma ker_map_kaehler_quotient_le {B C : Type*} [CommRing B] [CommRing C] [Algebra B C]
    (I : Ideal B) (w : Ω[C⁄B])
    (hw : KaehlerDifferential.map B (B ⧸ I) C (C ⧸ I.map (algebraMap B C)) w = 0) :
    w ∈ (I.map (algebraMap B C)) • (⊤ : Submodule C Ω[C⁄B]) := by
  set J := I.map (algebraMap B C)
  -- `Ω[C₀/B] → Ω[C₀/(B/I)]` is injective, as `B → B/I` is surjective
  have hinj : Function.Injective (KaehlerDifferential.map B (B ⧸ I) (C ⧸ J) (C ⧸ J)) := by
    have : Subsingleton Ω[(B ⧸ I)⁄B] := by
      have : FormallyUnramified B (B ⧸ I) := .of_surjective (Algebra.ofId _ _)
        Ideal.Quotient.mk_surjective
      infer_instance
    rw [injective_iff_map_eq_zero]
    intro v hv
    obtain ⟨t, rfl⟩ := (KaehlerDifferential.exact_mapBaseChange_map B (B ⧸ I) (C ⧸ J) v).mp hv
    rw [Subsingleton.elim t 0, map_zero]
  -- the conormal map `J/J² → C₀ ⊗ Ω[C/B]` vanishes, as `J` comes from `B`
  have hker0 : ∀ x ∈ J, (1 : C ⧸ J) ⊗ₜ[C] D B C x = 0 := by
    intro x hx
    induction hx using Submodule.span_induction with
    | mem x hx =>
      obtain ⟨b, -, rfl⟩ := hx
      rw [Derivation.map_algebraMap, TensorProduct.tmul_zero]
    | zero => rw [map_zero, TensorProduct.tmul_zero]
    | add x y _ _ hx hy => rw [map_add, TensorProduct.tmul_add, hx, hy, add_zero]
    | smul c x hx' hx =>
      rw [smul_eq_mul, Derivation.leibniz, TensorProduct.tmul_add, TensorProduct.tmul_smul, hx,
        smul_zero, zero_add, ← TensorProduct.smul_tmul, Algebra.smul_def, mul_one]
      have hxJ : x ∈ J := hx'
      rw [Ideal.Quotient.algebraMap_eq, Ideal.Quotient.eq_zero_iff_mem.mpr hxJ,
        TensorProduct.zero_tmul]
  have hsurj : Function.Surjective (algebraMap C (C ⧸ J)) := Ideal.Quotient.mk_surjective
  have hrange := KaehlerDifferential.range_kerCotangentToTensor B C (C ⧸ J) hsurj
  have key : ∀ w' : Ω[C⁄B], KaehlerDifferential.map B (B ⧸ I) (C ⧸ J) (C ⧸ J)
      (KaehlerDifferential.map B B C (C ⧸ J) w') =
        KaehlerDifferential.map B (B ⧸ I) C (C ⧸ J) w' := by
    intro w'
    have : w' ∈ Submodule.span C (Set.range (D B C)) := by
      rw [span_range_derivation]; trivial
    induction this using Submodule.span_induction with
    | mem x hx =>
      obtain ⟨c, rfl⟩ := hx
      simp only [KaehlerDifferential.map_D]
      rfl
    | zero => simp only [map_zero]
    | add x y _ _ hx hy => simp only [map_add, hx, hy]
    | smul c x _ hx =>
      rw [LinearMap.map_smul, LinearMap.map_smul, ← hx, ← IsScalarTower.algebraMap_smul (C ⧸ J),
        LinearMap.map_smul_of_tower, IsScalarTower.algebraMap_smul]
  have hmb : KaehlerDifferential.mapBaseChange B C (C ⧸ J) ((1 : C ⧸ J) ⊗ₜ w) = 0 := by
    apply hinj
    rw [map_zero, KaehlerDifferential.mapBaseChange_tmul, one_smul, key, hw]
  have hmem : (1 : C ⧸ J) ⊗ₜ[C] w ∈ LinearMap.range (kerCotangentToTensor B C (C ⧸ J)) := by
    rw [hrange]
    exact hmb
  obtain ⟨t, ht⟩ := hmem
  obtain ⟨x, rfl⟩ := Ideal.toCotangent_surjective _ t
  rw [kerCotangentToTensor_toCotangent] at ht
  have hxJ : (x : C) ∈ J := by
    have := x.2
    rw [RingHom.mem_ker] at this
    exact Ideal.Quotient.eq_zero_iff_mem.mp this
  rw [hker0 _ hxJ] at ht
  have h1 := congrArg (TensorProduct.quotTensorEquivQuotSMul Ω[C⁄B] J) ht
  rw [map_zero, show (1 : C ⧸ J) = Ideal.Quotient.mk J 1 from rfl,
    TensorProduct.quotTensorEquivQuotSMul_mk_tmul, one_smul] at h1
  exact (Submodule.Quotient.mk_eq_zero _).mp h1.symm

/-- Nakayama along the fibre: let `C` be a local `B`-algebra with `Ω¹_{C/B}` finite and `I ⊆ B` with
`IC ⊆ 𝔪_C`. Then `Ω¹_{C/B}` is generated by `n` elements iff `Ω¹_{(C/IC)/(B/I)}` is. -/
theorem exists_span_kaehler_iff_quotient {B C : Type*} [CommRing B] [CommRing C] [Algebra B C]
    [IsLocalRing C] [Module.Finite C Ω[C⁄B]] (I : Ideal B)
    (hI : I.map (algebraMap B C) ≤ maximalIdeal C) (n : ℕ) :
    (∃ ω : Fin n → Ω[C⁄B], Submodule.span C (Set.range ω) = ⊤) ↔
      ∃ ω : Fin n → Ω[(C ⧸ I.map (algebraMap B C))⁄(B ⧸ I)],
        Submodule.span (C ⧸ I.map (algebraMap B C)) (Set.range ω) = ⊤ := by
  set J := I.map (algebraMap B C)
  have hsurj : Function.Surjective (algebraMap C (C ⧸ J)) := Ideal.Quotient.mk_surjective
  constructor
  · refine exists_span_kaehler_of_square (Ideal.Quotient.mk I) (algebraMap C (C ⧸ J))
      (fun _ ↦ rfl) ?_
    rw [_root_.eq_top_iff, ← span_range_derivation, Submodule.span_le]
    rintro _ ⟨c, rfl⟩
    obtain ⟨c, rfl⟩ := hsurj c
    exact Submodule.subset_span ⟨c, rfl⟩
  · rintro ⟨ω₀, hω₀⟩
    have hφ := KaehlerDifferential.map_surjective_of_surjective B (B ⧸ I) C (C ⧸ J) hsurj
    choose ω hω using fun i ↦ hφ (ω₀ i)
    refine ⟨ω, ?_⟩
    have hjac : J ≤ Ideal.jacobson ⊥ := by
      rw [IsLocalRing.jacobson_eq_maximalIdeal ⊥ bot_ne_top]
      exact hI
    refine _root_.eq_top_iff.mpr (Submodule.le_of_le_smul_of_le_jacobson_bot
      (Module.Finite.fg_top) hjac fun w _ ↦ ?_)
    have hw : KaehlerDifferential.map B (B ⧸ I) C (C ⧸ J) w ∈
        Submodule.span (C ⧸ J) (Set.range ω₀) := hω₀ ▸ Submodule.mem_top
    obtain ⟨c₀, hc₀⟩ := (Submodule.mem_span_range_iff_exists_fun _).mp hw
    choose c hc using fun i ↦ hsurj (c₀ i)
    have hdiff : w - ∑ i, c i • ω i ∈ J • (⊤ : Submodule C Ω[C⁄B]) := by
      apply ker_map_kaehler_quotient_le
      rw [map_sub, map_sum, ← hc₀]
      simp only [LinearMap.map_smul, ← hc, algebraMap_smul]
      refine sub_eq_zero.mpr (Finset.sum_congr rfl fun i _ ↦ ?_)
      exact congrArg _ (hω i).symm
    have hsum : ∑ i, c i • ω i ∈ Submodule.span C (Set.range ω) :=
      Submodule.sum_mem _ fun i _ ↦ Submodule.smul_mem _ _ (Submodule.subset_span ⟨i, rfl⟩)
    have : w = ∑ i, c i • ω i + (w - ∑ i, c i • ω i) := by abel
    rw [this]
    exact Submodule.add_mem_sup hsum hdiff

/-- `Ω¹` of a ring map `R → S` is generated by `n` elements as an `S`-module. -/
def KaehlerSpanLE (n : ℕ) {R S : Type*} [CommRing R] [CommRing S] (φ : R →+* S) : Prop :=
  letI := φ.toAlgebra
  ∃ ω : Fin n → Ω[S⁄R], Submodule.span S (Set.range ω) = ⊤

lemma kaehlerSpanLE_algebraMap (n : ℕ) {R S : Type*} [CommRing R] [CommRing S] [Algebra R S] :
    KaehlerSpanLE n (algebraMap R S) ↔
      ∃ ω : Fin n → Ω[S⁄R], Submodule.span S (Set.range ω) = ⊤ := by
  exact iff_of_eq (congrArg (fun A : Algebra R S ↦ letI := A
    ∃ ω : Fin n → Ω[S⁄R], Submodule.span S (Set.range ω) = ⊤) toAlgebra_algebraMap)

lemma kaehlerSpanLE_respectsIso (n : ℕ) :
    RingHom.RespectsIso (fun {R S : Type u} [CommRing R] [CommRing S] (φ : R →+* S) ↦
      KaehlerSpanLE n φ) := by
  constructor
  · intro R S T _ _ _ φ e h
    let := φ.toAlgebra
    let := (e.toRingHom.comp φ).toAlgebra
    refine exists_span_kaehler_of_square (A := R) (B := S) (A' := R) (B' := T)
      (RingHom.id R) e.toRingHom (fun _ ↦ rfl) ?_ h
    rw [_root_.eq_top_iff, ← span_range_derivation, Submodule.span_le]
    rintro _ ⟨t, rfl⟩
    obtain ⟨s, rfl⟩ := e.surjective t
    exact Submodule.subset_span ⟨s, rfl⟩
  · intro R S T _ _ _ φ e h
    let := φ.toAlgebra
    let := (φ.comp e.toRingHom).toAlgebra
    refine exists_span_kaehler_of_square (A := S) (B := T) (A' := R) (B' := T)
      e.symm.toRingHom (RingHom.id T) (fun s ↦ ?_) ?_ h
    · change φ s = φ (e (e.symm s))
      rw [RingEquiv.apply_symm_apply]
    · exact span_range_derivation R T

end SGA.SGA1.ExposeII
