/-
Copyright (c) 2026 SGAenglishpluslean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SGAenglishpluslean contributors
-/
import SGA.SGA1.ExposeII.Field
import SGA.SGA1.ExposeII.FieldEtale
import SGA.SGA1.ExposeII.RelativeDimension

/-!
# SGA 1, Exposé II, II.5.5 and its corollaries: smoothness and `Ω¹` over a field

Let `X = Spec S` be of finite type over a field `k` and `x` a point where `X` has dimension `n`.
Then `X` is smooth over `k` at `x` iff `Ω¹_{X/k}` is free of rank `n` at `x` iff it is generated by
`n` elements at `x` (II.5.5, (i) ⇔ (ii) ⇔ (ii bis), `isSmoothAt_tfae`). The proof follows SGA:
generators can be taken of the form `dfᵢ` (Nakayama), and II.5.1 applies; conversely a basis
`dfᵢ` of `Ω¹` at `x` gives an étale map to `𝔸ᵐ` (II.4.8), so `m = dim_x X` (II.1.5).

Also: II.5.2 (at a point with `κ(x)` finite separable over `k`, `f` is étale iff the `fᵢ` generate
`𝔪_x`), and II.5.7 (`X` is smooth iff `Ω¹_{X/k}` is locally free and the local rings at the
generic points are separable over `k`), and II.5.8 (`f` is étale at `x` iff `f₁,…,fₚ` generate
`𝔪_x` and the classes of the other `fⱼ` have differentials generating `Ω¹_{κ(x)/k}`), proved with
the exact sequence (5.1) `𝔪_x/𝔪_x² → Ω¹(x) → Ω¹_{κ(x)/k} → 0` and dimension counting, and
II.5.9 in full (regular with separable residue field ⇔ smooth with `𝔪/𝔪² → Ω¹(x)` injective ⇔
existence of étale coordinates adapted to `𝔪_x`).
-/

universe u

open IsLocalRing Algebra KaehlerDifferential MvPolynomial
open scoped TensorProduct

namespace SGA.SGA1.ExposeII

/-- The span of the pure tensors `1 ⊗ v i` in `κ ⊗ M` is everything if the `v i` span `M`. -/
lemma span_tmul_eq_top_of_span_eq_top {P M : Type*} [CommRing P] [IsLocalRing P]
    [AddCommGroup M] [Module P M] [Module.Finite P M] {ι : Type*} (v : ι → M)
    (hv : Submodule.span P (Set.range v) = ⊤) :
    Submodule.span (ResidueField P) (Set.range fun i ↦ (1 : ResidueField P) ⊗ₜ[P] v i) = ⊤ := by
  have := (map_tensorProduct_mk_eq_top (N := Submodule.span P (Set.range v))).mpr hv
  rw [← Submodule.span_image, ← Set.range_comp, _root_.eq_top_iff, ← SetLike.coe_subset_coe,
    Submodule.top_coe] at this
  rw [_root_.eq_top_iff]
  exact Set.Subset.trans this (Submodule.span_subset_span P _ _)

/-- II.5.5, (ii bis) ⇒ (i): let `S` be of finite type over a field `k` and `Q` a prime of `S`
(a point `x`) at which `X = Spec S` has dimension `n`. If `Ω¹_{X/k}` is generated by `n` elements
at `x`, then `X` is smooth over `k` at `x`. By Nakayama, one may take the generators of the form
`dfᵢ` with `fᵢ ∈ S`, and then II.5.1 applies. -/
theorem isSmoothAt_of_span_eq_top {k S : Type u} [Field k] [CommRing S] [Algebra k S]
    [FiniteType k S] {n : ℕ} (Q : Ideal S) [Q.IsPrime]
    (hn : topologicalKrullDimAt (PrimeSpectrum S) ⟨Q, ‹_›⟩ = n)
    (ω : Fin n → Ω[Localization.AtPrime Q⁄k])
    (hω : Submodule.span (Localization.AtPrime Q) (Set.range ω) = ⊤) : IsSmoothAt k Q := by
  have : EssFiniteType k (Localization.AtPrime Q) := .comp k S _
  -- the `ds`, `s ∈ S`, generate `Ω¹` at `x`
  let v : S → Ω[Localization.AtPrime Q⁄k] := fun s ↦ D k _ (algebraMap S _ s)
  have hv : Submodule.span (Localization.AtPrime Q) (Set.range v) = ⊤ := by
    have := span_range_map_derivation_of_isLocalization (R := k) (S := S)
      (T := Localization.AtPrime Q) Q.primeCompl
    rw [← this]
    congr 1
    ext x
    simp only [Set.mem_range, Function.comp_apply, KaehlerDifferential.map_D, v]
  -- a basis of the fibre `Ω¹_{X/k}(x)` made of `dfᵢ`
  obtain ⟨κ, a, -, hsp, hli⟩ := exists_linearIndependent' (ResidueField (Localization.AtPrime Q))
    (fun s ↦ (1 : ResidueField (Localization.AtPrime Q)) ⊗ₜ[Localization.AtPrime Q] v s)
  rw [span_tmul_eq_top_of_span_eq_top v hv] at hsp
  let b := Module.Basis.mk hli hsp.ge
  have hspa : Submodule.span (Localization.AtPrime Q) (Set.range (v ∘ a)) = ⊤ :=
    span_eq_top_of_tmul_eq_basis (v ∘ a) b fun j ↦ (Module.Basis.mk_apply hli hsp.ge j).symm
  have : Finite κ := Module.Finite.finite_basis b
  have := Fintype.ofFinite κ
  let e := Finite.equivFin κ
  have hm : Nat.card κ ≤ n := by
    have h := finrank_le_of_span_eq_top (span_tmul_eq_top_of_span_eq_top ω hω)
    rwa [Module.finrank_eq_card_basis b, Fintype.card_fin, ← Nat.card_eq_fintype_card] at h
  -- `f : X → 𝔸ⁿ` given by the `fᵢ` (and zeros)
  let f : Fin n → S := fun i ↦ if h : i.val < Nat.card κ then a (e.symm ⟨i, h⟩) else 0
  algebraize [(MvPolynomial.aeval (R := k) f).toRingHom]
  have : IsScalarTower k (MvPolynomial (Fin n) k) S := .of_algHom (MvPolynomial.aeval f)
  have : IsScalarTower k (MvPolynomial (Fin n) k) (Localization.AtPrime Q) := .to₁₂₄ _ _ S _
  have hf (i : Fin n) : algebraMap (MvPolynomial (Fin n) k) (Localization.AtPrime Q) (X i) =
      algebraMap S _ (f i) := by
    rw [IsScalarTower.algebraMap_apply _ S]
    congr 1
    exact aeval_X f i
  have hspan : Submodule.span (Localization.AtPrime Q) (Set.range fun i ↦
      D k (Localization.AtPrime Q) (algebraMap (MvPolynomial (Fin n) k) _ (X i))) = ⊤ := by
    rw [_root_.eq_top_iff, ← hspa, Submodule.span_le]
    rintro _ ⟨j, rfl⟩
    refine Submodule.subset_span ⟨Fin.castLE hm (e j), ?_⟩
    simp only [hf, f, Fin.val_castLE, (e j).isLt, ↓reduceDIte, Fin.eta, Equiv.symm_apply_apply]
    rfl
  have := isEtaleAt_of_span_eq_top Q hn hspan
  change FormallySmooth k (Localization.AtPrime Q)
  have : FormallyEtale (MvPolynomial (Fin n) k) (Localization.AtPrime Q) := this
  exact .comp k (MvPolynomial (Fin n) k) _

/-- II.5.5, (i) ⇒ (ii): if `X = Spec S` (of finite type over `k`) is smooth over `k` at `x`, where
it has dimension `n`, then `Ω¹_{X/k}` is free of rank `n` at `x`. -/
theorem nonempty_basis_kaehlerDifferential_of_isSmoothAt {k S : Type u} [Field k] [CommRing S]
    [Algebra k S] [FiniteType k S] {n : ℕ} (Q : Ideal S) [Q.IsPrime] [IsSmoothAt k Q]
    (hn : topologicalKrullDimAt (PrimeSpectrum S) ⟨Q, ‹_›⟩ = n) :
    Nonempty (Module.Basis (Fin n) (Localization.AtPrime Q) Ω[Localization.AtPrime Q⁄k]) := by
  have : EssFiniteType k (Localization.AtPrime Q) := .comp k S _
  have : IsNoetherianRing S := FiniteType.isNoetherianRing k S
  have hsm : FormallySmooth k (Localization.AtPrime Q) := ‹IsSmoothAt k Q›
  -- a basis of `Ω¹` at `x` made of `dfᵢ`, `fᵢ ∈ S`
  let v : S → Ω[Localization.AtPrime Q⁄k] := fun s ↦ D k _ (algebraMap S _ s)
  have hv : Submodule.span (Localization.AtPrime Q) (Set.range v) = ⊤ := by
    have := span_range_map_derivation_of_isLocalization (R := k) (S := S)
      (T := Localization.AtPrime Q) Q.primeCompl
    rw [← this]
    congr 1
    ext x
    simp only [Set.mem_range, Function.comp_apply, KaehlerDifferential.map_D, v]
  obtain ⟨κ, a, b, hb⟩ := Module.exists_basis_of_span_of_flat v hv
  have : Finite κ := Module.Finite.finite_basis b
  let e := Finite.equivFin κ
  set m := Nat.card κ
  -- `f = (fᵢ) : X → 𝔸ᵐ` is étale at `x` (II.4.8), so `m = dim_x X`
  algebraize [(MvPolynomial.aeval (R := k) (a ∘ e.symm)).toRingHom]
  have : IsScalarTower k (MvPolynomial (Fin m) k) S := .of_algHom (MvPolynomial.aeval _)
  have : IsScalarTower k (MvPolynomial (Fin m) k) (Localization.AtPrime Q) := .to₁₂₄ _ _ S _
  have hf (i : Fin m) : D k (Localization.AtPrime Q)
      (algebraMap (MvPolynomial (Fin m) k) (Localization.AtPrime Q) (X i)) = b (e.symm i) := by
    rw [hb, IsScalarTower.algebraMap_apply _ S]
    congr 2
    exact aeval_X _ i
  have hE : FormallyEtale (MvPolynomial (Fin m) k) (Localization.AtPrime Q) := by
    rw [formallyEtale_mvPolynomial_iff]
    simp only [hf]
    refine ⟨b.linearIndependent.comp _ e.symm.injective, ?_⟩
    rw [← b.span_eq, ← e.symm.surjective.range_comp]
    rfl
  have : IsEtaleAt (MvPolynomial (Fin m) k) Q := hE
  have : FiniteType (MvPolynomial (Fin m) k) S := .of_restrictScalars_finiteType k _ S
  have hdim := height_add_trdeg_eq_of_isEtaleAt (k := k) (Q.under (MvPolynomial (Fin m) k)) Q
  rw [FiniteType.height_add_trdeg_residueField k (Q.under (MvPolynomial (Fin m) k)),
    MvPolynomial.ringKrullDim_of_isNoetherianRing,
    ringKrullDim_eq_zero_of_field, zero_add, Nat.card_eq_fintype_card, Fintype.card_fin] at hdim
  rw [FiniteType.topologicalKrullDimAt_eq_height_add_trdeg k Q] at hn
  have hmn : m = n := by
    have h1 : (Q.height + (trdeg k Q.ResidueField).toENat : ℕ∞) = m := by exact_mod_cast hdim
    have h2 : (Q.height + (trdeg k Q.ResidueField).toENat : ℕ∞) = n := by exact_mod_cast hn
    exact_mod_cast h1.symm.trans h2
  exact ⟨(b.reindex e).reindex (finCongr hmn)⟩

/-- II.5.5, (i) ⇔ (ii) ⇔ (ii bis): let `X = Spec S` be of finite type over a field `k` and `x` a
point where `X` has dimension `n`. Then `X` is smooth over `k` at `x` iff `Ω¹_{X/k}` is free of
rank `n` at `x` iff it is generated by `n` elements at `x`. -/
theorem isSmoothAt_tfae {k S : Type u} [Field k] [CommRing S] [Algebra k S] [FiniteType k S]
    {n : ℕ} (Q : Ideal S) [Q.IsPrime]
    (hn : topologicalKrullDimAt (PrimeSpectrum S) ⟨Q, ‹_›⟩ = n) :
    List.TFAE [IsSmoothAt k Q,
      Nonempty (Module.Basis (Fin n) (Localization.AtPrime Q) Ω[Localization.AtPrime Q⁄k]),
      ∃ ω : Fin n → Ω[Localization.AtPrime Q⁄k],
        Submodule.span (Localization.AtPrime Q) (Set.range ω) = ⊤] := by
  tfae_have 1 → 2 := fun _ ↦ nonempty_basis_kaehlerDifferential_of_isSmoothAt Q hn
  tfae_have 2 → 3 := fun ⟨b⟩ ↦ ⟨b, b.span_eq⟩
  tfae_have 3 → 1 := fun ⟨ω, hω⟩ ↦ isSmoothAt_of_span_eq_top Q hn ω hω
  tfae_finish

/-- II.5.2: under the hypotheses of II.5.1 (`X = Spec S` of finite type over `k`, of dimension
`n` at `x`, `f = (fᵢ) : X → 𝔸ⁿ_k`), suppose that `κ(x)` is a finite separable extension of `k` and
that the `fᵢ` vanish at `x`. Then `f` is étale at `x` iff the `fᵢ` generate `𝔪_x`. -/
theorem isEtaleAt_iff_span_eq_maximalIdeal {k S : Type u} [Field k] [CommRing S] [Algebra k S]
    [FiniteType k S] {n : ℕ} [Algebra (MvPolynomial (Fin n) k) S]
    [IsScalarTower k (MvPolynomial (Fin n) k) S] (Q : Ideal S) [Q.IsPrime]
    (hn : topologicalKrullDimAt (PrimeSpectrum S) ⟨Q, ‹_›⟩ = n)
    [Algebra.IsSeparable k Q.ResidueField]
    (hf : ∀ i, algebraMap (MvPolynomial (Fin n) k) (Localization.AtPrime Q) (X i) ∈
      maximalIdeal (Localization.AtPrime Q)) :
    IsEtaleAt (MvPolynomial (Fin n) k) Q ↔
      Ideal.span (Set.range fun i ↦ algebraMap (MvPolynomial (Fin n) k)
        (Localization.AtPrime Q) (X i)) = maximalIdeal (Localization.AtPrime Q) := by
  have : IsScalarTower k (MvPolynomial (Fin n) k) (Localization.AtPrime Q) := .to₁₂₄ _ _ S _
  have : EssFiniteType k (Localization.AtPrime Q) := .comp k S _
  have : IsNoetherianRing S := FiniteType.isNoetherianRing k S
  have : IsNoetherianRing (Localization.AtPrime Q) :=
    IsLocalization.isNoetherianRing Q.primeCompl _ inferInstance
  have : FormallyEtale k (ResidueField (Localization.AtPrime Q)) :=
    FormallyEtale.of_isSeparable k Q.ResidueField
  set f : Fin n → Localization.AtPrime Q := fun i ↦
    algebraMap (MvPolynomial (Fin n) k) (Localization.AtPrime Q) (X i) with hfdef
  constructor
  · intro he
    have hE : FormallyEtale (MvPolynomial (Fin n) k) (Localization.AtPrime Q) := he
    have : FormallySmooth k (Localization.AtPrime Q) := .comp k (MvPolynomial (Fin n) k) _
    have hsp := ((formallyEtale_mvPolynomial_iff_residueField (R := k)
      (B := Localization.AtPrime Q) (ι := Fin n)).mp hE).2
    -- `𝔪/𝔪² → Ω¹(x)` is injective since `κ(x)` is smooth over `k` (II.4.10 (iv))
    obtain ⟨l, hl⟩ := (formallySmooth_iff_split_injection k (Localization.AtPrime Q)
      (ResidueField (Localization.AtPrime Q)) residue_surjective).mp inferInstance
    have hinj : Function.Injective (kerCotangentToTensor k (Localization.AtPrime Q)
        (ResidueField (Localization.AtPrime Q))) :=
      Function.LeftInverse.injective (g := l) fun x ↦ LinearMap.congr_fun hl x
    have hker : maximalIdeal (Localization.AtPrime Q) =
        RingHom.ker (algebraMap (Localization.AtPrime Q)
          (ResidueField (Localization.AtPrime Q))) := by
      rw [ResidueField.algebraMap_eq, ker_residue]
    let e := Ideal.Cotangent.equivOfEq _ _ hker
    let g : CotangentSpace (Localization.AtPrime Q) →ₗ[ResidueField (Localization.AtPrime Q)]
        ResidueField (Localization.AtPrime Q) ⊗[Localization.AtPrime Q]
          Ω[Localization.AtPrime Q⁄k] :=
      (kerCotangentToTensor k (Localization.AtPrime Q) (ResidueField (Localization.AtPrime Q))
        ∘ₗ e.toLinearMap).extendScalarsOfSurjective residue_surjective
    have hginj : Function.Injective g := hinj.comp e.injective
    let c : Fin n → CotangentSpace (Localization.AtPrime Q) :=
      fun i ↦ (maximalIdeal _).toCotangent ⟨f i, hf i⟩
    have hgc (i : Fin n) : g (c i) = 1 ⊗ₜ D k _ (f i) := rfl
    -- so the classes of the `fᵢ` span `𝔪/𝔪²`, and the `fᵢ` generate `𝔪`
    have hc : Submodule.span (ResidueField (Localization.AtPrime Q)) (Set.range c) = ⊤ := by
      refine eq_top_iff.mpr fun z _ ↦ ?_
      have hz : g z ∈ Submodule.map g (Submodule.span _ (Set.range c)) := by
        rw [Submodule.map_span, ← Set.range_comp]
        convert Submodule.mem_top
        convert hsp using 3
        ext i
        exact hgc i
      obtain ⟨z', hz', hzz'⟩ := hz
      rwa [hginj hzz'] at hz'
    have hc' : Submodule.span (ResidueField (Localization.AtPrime Q))
        ((maximalIdeal _).toCotangent '' Set.range fun i ↦ (⟨f i, hf i⟩ :
          maximalIdeal (Localization.AtPrime Q))) = ⊤ := by
      rw [← Set.range_comp]
      exact hc
    rw [CotangentSpace.span_image_eq_top_iff] at hc'
    exact (span_subtype_eq_top_iff _ _ rfl f hf).mp hc'
  · intro hspan
    -- the `dfᵢ(x)` generate `Ω¹(x)` (II.5.2, (iv) ⇒ (iii)), hence `Ω¹` at `x` by Nakayama
    have h1 := span_tmul_D_eq_top_of_span_eq_maximalIdeal (k := k) f hspan
    refine isEtaleAt_of_span_eq_top Q hn ?_
    rw [← map_tensorProduct_mk_eq_top, Submodule.map_span, ← Set.range_comp]
    have hsurj : Function.Surjective (algebraMap (Localization.AtPrime Q)
        (ResidueField (Localization.AtPrime Q))) := by
      rw [ResidueField.algebraMap_eq]
      exact residue_surjective
    rw [← Submodule.restrictScalars_span (Localization.AtPrime Q)
      (ResidueField (Localization.AtPrime Q)) hsurj]
    change (Submodule.span (ResidueField (Localization.AtPrime Q)) (Set.range fun i ↦
      (1 : ResidueField (Localization.AtPrime Q)) ⊗ₜ[Localization.AtPrime Q]
        D k (Localization.AtPrime Q) (f i))).restrictScalars _ = ⊤
    rw [h1, Submodule.restrictScalars_top]

/-- The localization of a ring at a minimal prime is a field as soon as it is reduced. -/
lemma isField_localization_of_isReduced {A : Type*} [CommRing A] (P : Ideal A) [P.IsPrime]
    (hP : P ∈ minimalPrimes A) [IsReduced (Localization.AtPrime P)] :
    IsField (Localization.AtPrime P) := by
  rw [IsLocalRing.isField_iff_maximalIdeal_eq, ← Localization.AtPrime.map_eq_maximalIdeal,
    ← IsLocalization.AtPrime.radical_map_of_mem_minimalPrimes (A := Localization.AtPrime P)
      (q := P) (I := ⊥) hP, Ideal.map_bot, Ideal.radical_bot_of_isReduced]

/-- The rank of `Ω¹_{S/k}` at a generic point `P` of `Spec S` with `S_P` separable over `k` is the
dimension of the component `V(P)`. -/
lemma finrank_kaehlerDifferential_localization_of_mem_minimalPrimes {k S : Type u} [Field k]
    [CommRing S] [Algebra k S] [FiniteType k S] (P : Ideal S) [P.IsPrime]
    (hP : P ∈ minimalPrimes S) [IsGeometricallyReduced k (Localization.AtPrime P)] :
    ((Module.finrank (Localization.AtPrime P) Ω[Localization.AtPrime P⁄k] : ℕ∞) : WithBot ℕ∞) =
      ringKrullDim (S ⧸ P) := by
  have : IsReduced (Localization.AtPrime P) := isReduced_of_isGeometricallyReduced k
  let := (isField_localization_of_isReduced P hP).toField
  have : EssFiniteType k (Localization.AtPrime P) := .comp k S _
  have hsep : IsSeparablyGenerated k (Localization.AtPrime P) :=
    IsGeometricallyReduced.isSeparablyGenerated
  rw [hsep.finrank_kaehlerDifferential, ← FiniteType.trdeg_residueField k P]
  -- `S_P` is its own residue field
  have : Algebra.IsIntegral (Localization.AtPrime P) P.ResidueField :=
    Algebra.isIntegral_of_surjective (by
      change Function.Surjective (algebraMap (Localization.AtPrime P)
        (ResidueField (Localization.AtPrime P)))
      rw [ResidueField.algebraMap_eq]
      exact residue_surjective)
  have h := lift_trdeg_add_eq k (Localization.AtPrime P) P.ResidueField
  rw [trdeg_eq_zero (R := Localization.AtPrime P) (A := P.ResidueField), Cardinal.lift_zero,
    add_zero, Cardinal.lift_id, Cardinal.lift_id] at h
  have hlt := trdeg_lt_aleph0 k (Localization.AtPrime P)
  rw [← h, ← Cardinal.cast_toNat_of_lt_aleph0 hlt, Cardinal.toENat_nat, Cardinal.toNat_natCast]

/-- II.5.7, affine form: an algebra `S` of finite type over a field `k` is smooth iff `Ω¹_{S/k}`
is locally free (projective) and the local rings of the generic points of the irreducible
components of `Spec S` are separable extensions of `k` (for a local artinian ring, separability
in the sense of `Algebra.IsGeometricallyReduced` forces it to be a field). As in SGA: the rank of
`Ω¹` at a generic point is the transcendence degree, i.e. the dimension of the component, so
`Ω¹` has rank `dim_x X` at every point `x`, and II.5.5 applies. -/
theorem smooth_iff_projective_and_isGeometricallyReduced {k S : Type u} [Field k] [CommRing S]
    [Algebra k S] [FiniteType k S] :
    Smooth k S ↔ Module.Projective S Ω[S⁄k] ∧ ∀ (P : Ideal S) [P.IsPrime], P ∈ minimalPrimes S →
      IsGeometricallyReduced k (Localization.AtPrime P) := by
  have : FinitePresentation k S := FinitePresentation.of_finiteType.mp inferInstance
  have : IsNoetherianRing S := FiniteType.isNoetherianRing k S
  constructor
  · intro hsm
    refine ⟨inferInstance, fun P _ hP ↦ ?_⟩
    have : IsReduced S := isReduced_of_smooth (R := k)
    let := (isField_localization_of_mem_minimalPrimes P hP).toField
    exact FormallySmooth.isGeometricallyReduced
  · rintro ⟨hproj, hgen⟩
    have : Module.Flat S Ω[S⁄k] := inferInstance
    refine ⟨smoothLocus_eq_univ_iff.mp (Set.eq_univ_iff_forall.mpr fun Q ↦ ?_), inferInstance⟩
    -- the rank of `Ω¹` at `P` is the rank of `Ω¹_{S_P/k}`
    have hrank (P : PrimeSpectrum S) : Module.rankAtStalk Ω[S⁄k] P =
        Module.finrank (Localization.AtPrime P.asIdeal) Ω[Localization.AtPrime P.asIdeal⁄k] :=
      ((IsLocalizedModule.iso P.asIdeal.primeCompl (KaehlerDifferential.map k k S
        (Localization.AtPrime P.asIdeal))).extendScalarsOfIsLocalization P.asIdeal.primeCompl
          (Localization.AtPrime P.asIdeal)).finrank_eq
    -- every component through `Q` has dimension the rank of `Ω¹` at `Q`
    have hmin (P : PrimeSpectrum S) (hP : IsMin P) (hPQ : P ≤ Q) :
        Order.coheight P = Module.rankAtStalk Ω[S⁄k] Q := by
      have hmem : P.asIdeal ∈ minimalPrimes S :=
        ⟨⟨P.2, bot_le⟩, fun J hJ hle ↦ hP (b := ⟨J, hJ.1⟩) hle⟩
      have := hgen P.asIdeal hmem
      have h1 := finrank_kaehlerDifferential_localization_of_mem_minimalPrimes (k := k)
        P.asIdeal hmem
      rw [← hrank, Module.rankAtStalk_eq_of_le_of_finite_of_flat Ω[S⁄k] hPQ,
        ← PrimeSpectrum.coheight_eq_ringKrullDim_quotient] at h1
      exact_mod_cast h1.symm
    have hdim : topologicalKrullDimAt (PrimeSpectrum S) Q = Module.rankAtStalk Ω[S⁄k] Q := by
      rw [FiniteType.topologicalKrullDimAt_eq_iSup k]
      obtain ⟨P₀, hP₀, hP₀Q⟩ := Ideal.exists_minimalPrimes_le (bot_le : ⊥ ≤ Q.asIdeal)
      have hP₀min : IsMin (⟨P₀, hP₀.1.1⟩ : PrimeSpectrum S) :=
        fun x hx ↦ hP₀.2 ⟨x.2, bot_le⟩ hx
      refine congrArg _ (le_antisymm (iSup₂_le fun P hP ↦ iSup_le fun hPQ ↦ (hmin P hP hPQ).le)
        ((hmin _ hP₀min hP₀Q).ge.trans (le_iSup₂_of_le _ hP₀min (le_iSup_of_le hP₀Q le_rfl))))
    -- `Ω¹` is free at `Q`, of rank `dim_Q X`: `S` is smooth at `Q` (II.5.5)
    have : Module.Flat (Localization.AtPrime Q.asIdeal) Ω[Localization.AtPrime Q.asIdeal⁄k] :=
      Module.Flat.of_isLocalizedModule _ Q.asIdeal.primeCompl
        (KaehlerDifferential.map k k S (Localization.AtPrime Q.asIdeal))
    have : IsNoetherianRing (Localization.AtPrime Q.asIdeal) :=
      IsLocalization.isNoetherianRing Q.asIdeal.primeCompl _ inferInstance
    have : EssFiniteType k (Localization.AtPrime Q.asIdeal) := .comp k S _
    have : Module.FinitePresentation (Localization.AtPrime Q.asIdeal)
        Ω[Localization.AtPrime Q.asIdeal⁄k] := Module.finitePresentation_of_finite _ _
    have : Module.Free (Localization.AtPrime Q.asIdeal) Ω[Localization.AtPrime Q.asIdeal⁄k] :=
      Module.free_of_flat_of_isLocalRing
    let b := Module.finBasisOfFinrankEq (Localization.AtPrime Q.asIdeal)
      Ω[Localization.AtPrime Q.asIdeal⁄k] (hrank Q).symm
    exact isSmoothAt_of_span_eq_top Q.asIdeal hdim b b.span_eq

section Linear

variable {k P : Type u} [Field k] [CommRing P] [IsLocalRing P] [Algebra k P]

/-- The exact sequence `𝔪/𝔪² → Ω¹(x) → Ω¹_{κ(x)/k} → 0` (5.1): if `f₁,…,fₚ` generate `𝔪` and the
`dfⱼ` of `κ(x)` (`j > p`) generate `Ω¹_{κ(x)/k}`, then all the `dfᵢ(x)` generate `Ω¹(x)`. -/
lemma span_tmul_D_eq_top_of_span {n p : ℕ} (f : Fin n → P)
    (h𝔪 : Ideal.span (f '' {i | i.val < p}) = maximalIdeal P)
    (hκ : Submodule.span (ResidueField P)
      ((fun j ↦ D k (ResidueField P) (residue P (f j))) '' {j | p ≤ j.val}) = ⊤) :
    Submodule.span (ResidueField P)
      (Set.range fun i ↦ (1 : ResidueField P) ⊗ₜ[P] D k P (f i)) = ⊤ := by
  set N := Submodule.span (ResidueField P)
    (Set.range fun i ↦ (1 : ResidueField P) ⊗ₜ[P] D k P (f i))
  have hsurj : Function.Surjective (algebraMap P (ResidueField P)) := by
    rw [ResidueField.algebraMap_eq]
    exact residue_surjective
  have hβ (x : P) : mapBaseChange k P (ResidueField P) ((1 : ResidueField P) ⊗ₜ D k P x) =
      D k (ResidueField P) (residue P x) := by
    rw [mapBaseChange_tmul, one_smul, KaehlerDifferential.map_D, ResidueField.algebraMap_eq]
  have hker : RingHom.ker (algebraMap P (ResidueField P)) = maximalIdeal P := by
    rw [ResidueField.algebraMap_eq, ker_residue]
  -- the image of `𝔪/𝔪²` lies in `N`
  have hα (x : P) (hx : x ∈ Ideal.span (f '' {i | i.val < p})) :
      (1 : ResidueField P) ⊗ₜ[P] D k P x ∈ N := by
    induction hx using Submodule.span_induction with
    | mem y hy =>
      obtain ⟨i, -, rfl⟩ := hy
      exact Submodule.subset_span ⟨i, rfl⟩
    | zero => simp
    | add a b _ _ ha hb => simpa [TensorProduct.tmul_add] using N.add_mem ha hb
    | smul a b hb ihb =>
      have hb' : b ∈ maximalIdeal P := h𝔪 ▸ hb
      have : (1 : ResidueField P) ⊗ₜ[P] D k P (a • b) =
          residue P a • ((1 : ResidueField P) ⊗ₜ[P] D k P b) := by
        rw [smul_eq_mul, Derivation.leibniz, TensorProduct.tmul_add, TensorProduct.tmul_smul,
          TensorProduct.tmul_smul, ← algebraMap_smul (ResidueField P) b,
          ResidueField.algebraMap_eq, (residue_eq_zero_iff b).mpr hb', zero_smul, add_zero,
          ← algebraMap_smul (ResidueField P) a, ResidueField.algebraMap_eq]
      rw [this]
      exact N.smul_mem _ ihb
  refine eq_top_iff.mpr fun v _ ↦ ?_
  have hβv : mapBaseChange k P (ResidueField P) v ∈
      Submodule.map (mapBaseChange k P (ResidueField P)) N := by
    have : Submodule.span (ResidueField P)
        ((fun j ↦ D k (ResidueField P) (residue P (f j))) '' {j | p ≤ j.val}) ≤
          Submodule.map (mapBaseChange k P (ResidueField P)) N := by
      rw [Submodule.span_le]
      rintro _ ⟨j, -, rfl⟩
      exact ⟨_, Submodule.subset_span ⟨j, rfl⟩, hβ _⟩
    exact this (hκ ▸ Submodule.mem_top)
  obtain ⟨u, hu, huv⟩ := hβv
  have hvu : v - u ∈ LinearMap.range (kerCotangentToTensor k P (ResidueField P)) := by
    rw [← (KaehlerDifferential.exact_kerCotangentToTensor_mapBaseChange k P _
      hsurj).linearMap_ker_eq, LinearMap.mem_ker]
    exact (map_sub (mapBaseChange k P (ResidueField P)) v u).trans (by rw [huv, sub_self])
  obtain ⟨c, hc⟩ := hvu
  obtain ⟨⟨x, hx⟩, rfl⟩ := Ideal.toCotangent_surjective _ c
  rw [kerCotangentToTensor_toCotangent] at hc
  have : v = u + (v - u) := by abel
  rw [this, ← hc]
  exact N.add_mem hu (hα x (h𝔪 ▸ hker ▸ hx))

/-- The converse direction of II.5.8: let `P = 𝒪_x` be local, essentially of finite type and
formally smooth over `k`, and `f₁,…,fₙ ∈ P` with `fᵢ ∈ 𝔪` for `i < p`, whose differentials form a
basis of `Ω¹(x)`. If `trdeg_k κ(x) = n - p`, then `f₁,…,fₚ` generate `𝔪` and the `dfⱼ` (`j ≥ p`)
generate `Ω¹_{κ(x)/k}`. -/
lemma span_maximalIdeal_and_span_kaehler_of_basis [IsNoetherianRing P] [EssFiniteType k P]
    [FormallySmooth k P]
    {n p : ℕ} (hpn : p ≤ n) (f : Fin n → P) (hf : ∀ i : Fin n, i.val < p → f i ∈ maximalIdeal P)
    (hli : LinearIndependent (ResidueField P) fun i ↦ (1 : ResidueField P) ⊗ₜ[P] D k P (f i))
    (hsp : Submodule.span (ResidueField P)
      (Set.range fun i ↦ (1 : ResidueField P) ⊗ₜ[P] D k P (f i)) = ⊤)
    (htr : Algebra.trdeg k (ResidueField P) = (n - p : ℕ)) :
    Ideal.span (f '' {i | i.val < p}) = maximalIdeal P ∧
      Submodule.span (ResidueField P)
        ((fun j ↦ D k (ResidueField P) (residue P (f j))) '' {j | p ≤ j.val}) = ⊤ := by
  classical
  have hsurj : Function.Surjective (algebraMap P (ResidueField P)) := by
    rw [ResidueField.algebraMap_eq]
    exact residue_surjective
  have hβ (x : P) : mapBaseChange k P (ResidueField P) ((1 : ResidueField P) ⊗ₜ D k P x) =
      D k (ResidueField P) (residue P x) := by
    rw [mapBaseChange_tmul, one_smul, KaehlerDifferential.map_D, ResidueField.algebraMap_eq]
  set β := mapBaseChange k P (ResidueField P)
  -- `Ω¹_{κ(x)/k}` is generated by the `dfⱼ`, `j ≥ p`
  have hW : Submodule.span (ResidueField P)
      ((fun j ↦ D k (ResidueField P) (residue P (f j))) '' {j | p ≤ j.val}) = ⊤ := by
    have h1 : Submodule.map β ⊤ = ⊤ := by
      rw [Submodule.map_top, LinearMap.range_eq_top]
      exact KaehlerDifferential.mapBaseChange_surjective k P _ hsurj
    rw [← hsp, Submodule.map_span, ← Set.range_comp] at h1
    rw [_root_.eq_top_iff, ← h1, Submodule.span_le]
    rintro _ ⟨i, rfl⟩
    simp only [Function.comp_apply, hβ]
    by_cases hi : i.val < p
    · rw [(residue_eq_zero_iff _).mpr (hf i hi), map_zero]
      exact zero_mem _
    · exact Submodule.subset_span ⟨i, not_lt.mp hi, rfl⟩
  refine ⟨?_, hW⟩
  -- `κ(x)` is separable over `k`, since `dim Ω¹_{κ(x)/k} ≤ n - p = trdeg_k κ(x)`
  have : EssFiniteType k (ResidueField P) := .comp k P _
  have hcard : (Finset.univ.filter fun j : Fin n ↦ p ≤ j.val).card = n - p := by
    have := Finset.card_filter_add_card_filter_not (s := Finset.univ)
      (fun j : Fin n ↦ j.val < p)
    rw [Fin.card_filter_val_lt, Finset.card_univ, Fintype.card_fin] at this
    simp only [not_lt] at this
    omega
  have hWle : Module.finrank (ResidueField P) Ω[ResidueField P⁄k] ≤ n - p := by
    have h := finrank_span_finset_le_card (R := ResidueField P)
      ((Finset.univ.filter fun j : Fin n ↦ p ≤ j.val).image
        fun j ↦ D k (ResidueField P) (residue P (f j)))
    rw [Finset.coe_image, Finset.coe_filter] at h
    simp only [Finset.mem_univ, true_and] at h
    rw [Set.finrank, hW, finrank_top] at h
    exact h.trans (Finset.card_image_le.trans hcard.le)
  have hsep : IsSeparablyGenerated k (ResidueField P) := by
    rw [isSeparablyGenerated_iff_rank_kaehlerDifferential_le, htr,
      ← Module.finrank_eq_rank]
    exact_mod_cast hWle
  have : FormallySmooth k (ResidueField P) := hsep.formallySmooth
  have hWeq : Module.finrank (ResidueField P) Ω[ResidueField P⁄k] = n - p := by
    have := hsep.finrank_kaehlerDifferential
    rw [htr] at this
    simpa using this
  -- `𝔪/𝔪² → Ω¹(x)` is injective (II.4.10 (iv)), with image `ker β` of dimension `p`
  obtain ⟨l, hl⟩ := (formallySmooth_iff_split_injection k P (ResidueField P) hsurj).mp
    inferInstance
  have hinj : Function.Injective (kerCotangentToTensor k P (ResidueField P)) :=
    Function.LeftInverse.injective (g := l) fun x ↦ LinearMap.congr_fun hl x
  have hker : maximalIdeal P = RingHom.ker (algebraMap P (ResidueField P)) := by
    rw [ResidueField.algebraMap_eq, ker_residue]
  let e := Ideal.Cotangent.equivOfEq _ _ hker
  let g : CotangentSpace P →ₗ[ResidueField P] ResidueField P ⊗[P] Ω[P⁄k] :=
    (kerCotangentToTensor k P (ResidueField P) ∘ₗ e.toLinearMap).extendScalarsOfSurjective
      residue_surjective
  have hginj : Function.Injective g := hinj.comp e.injective
  have hrange : ∀ c, g c ∈ LinearMap.ker β := fun c ↦ LinearMap.mem_ker.mpr
    ((KaehlerDifferential.exact_kerCotangentToTensor_mapBaseChange k P _
      hsurj).apply_apply_eq_zero (e c))
  let ι := {i : Fin n // i.val < p}
  let w : ι → ResidueField P ⊗[P] Ω[P⁄k] := fun i ↦ (1 : ResidueField P) ⊗ₜ D k P (f i.1)
  have hwli : LinearIndependent (ResidueField P) w := hli.comp _ Subtype.val_injective
  have hwker : Submodule.span (ResidueField P) (Set.range w) ≤ LinearMap.ker β := by
    rw [Submodule.span_le]
    rintro _ ⟨i, rfl⟩
    change β _ = 0
    rw [hβ, (residue_eq_zero_iff _).mpr (hf i.1 i.2), map_zero]
  have hVdim : Module.finrank (ResidueField P) (ResidueField P ⊗[P] Ω[P⁄k]) = n := by
    rw [Module.finrank_eq_card_basis (Module.Basis.mk hli hsp.ge), Fintype.card_fin]
  have hkerdim : Module.finrank (ResidueField P) (LinearMap.ker β) = p := by
    have := LinearMap.finrank_range_add_finrank_ker β
    rw [LinearMap.range_eq_top.mpr (KaehlerDifferential.mapBaseChange_surjective k P _ hsurj),
      finrank_top, hWeq, hVdim] at this
    omega
  have hιcard : Fintype.card ι = p := by
    rw [Fintype.card_subtype, Fin.card_filter_val_lt]
    omega
  have hspan : Submodule.span (ResidueField P) (Set.range w) = LinearMap.ker β := by
    refine Submodule.eq_of_le_of_finrank_eq hwker ?_
    have := linearIndependent_iff_card_eq_finrank_span.mp hwli
    rw [hιcard] at this
    rw [hkerdim]
    exact this.symm
  -- so the classes of `f₁,…,fₚ` span `𝔪/𝔪²`, and they generate `𝔪`
  let c : ι → CotangentSpace P := fun i ↦ (maximalIdeal P).toCotangent ⟨f i.1, hf i.1 i.2⟩
  have hgc (i : ι) : g (c i) = w i := rfl
  have hc : Submodule.span (ResidueField P) (Set.range c) = ⊤ := by
    refine eq_top_iff.mpr fun z _ ↦ ?_
    have hz : g z ∈ Submodule.map g (Submodule.span _ (Set.range c)) := by
      rw [Submodule.map_span, ← Set.range_comp]
      convert (hspan ▸ hrange z : g z ∈ Submodule.span _ (Set.range w)) using 3
      exact funext hgc
    obtain ⟨z', hz', hzz'⟩ := hz
    rwa [hginj hzz'] at hz'
  have hc' : Submodule.span (ResidueField P) ((maximalIdeal P).toCotangent ''
      Set.range fun i : ι ↦ (⟨f i.1, hf i.1 i.2⟩ : maximalIdeal P)) = ⊤ := by
    rw [← Set.range_comp]
    exact hc
  rw [CotangentSpace.span_image_eq_top_iff] at hc'
  have := (span_subtype_eq_top_iff _ _ rfl (fun i : ι ↦ f i.1) fun i ↦ hf i.1 i.2).mp hc'
  rw [← this]
  congr 1
  ext x
  simp [ι]

end Linear

/-- II.5.8: let `X = Spec S` be of finite type over a field `k`, `x` a point (a prime `Q`) where
`X` has dimension `n` and `𝒪_x` has dimension `p` (so that `trdeg_k κ(x) = n - p`), and
`f = (fᵢ) : X → 𝔸ⁿ_k` with `fᵢ(x) = 0` for `i < p`. Then `f` is étale at `x` iff `f₁,…,fₚ`
generate `𝔪_x` (a regular system of parameters) and the differentials of the classes of the
`fⱼ`, `j ≥ p`, generate `Ω¹_{κ(x)/k}` (i.e. these classes form a separating transcendence basis of
`κ(x)` over `k`, by `SGA.Foundations.Fields`). (SGA takes germs `fᵢ ∈ 𝒪_x`; we take sections over
an affine neighbourhood `Spec S` of `x`.) -/
theorem isEtaleAt_iff_span_maximalIdeal_and_span_kaehler {k S : Type u} [Field k] [CommRing S]
    [Algebra k S] [FiniteType k S] {n p : ℕ} [Algebra (MvPolynomial (Fin n) k) S]
    [IsScalarTower k (MvPolynomial (Fin n) k) S] (Q : Ideal S) [Q.IsPrime]
    (hn : topologicalKrullDimAt (PrimeSpectrum S) ⟨Q, ‹_›⟩ = n)
    (hp : ringKrullDim (Localization.AtPrime Q) = p)
    (hf : ∀ i : Fin n, i.val < p → algebraMap (MvPolynomial (Fin n) k) (Localization.AtPrime Q)
      (X i) ∈ maximalIdeal (Localization.AtPrime Q)) :
    IsEtaleAt (MvPolynomial (Fin n) k) Q ↔
      Ideal.span ((fun i ↦ algebraMap (MvPolynomial (Fin n) k) (Localization.AtPrime Q) (X i)) ''
          {i | i.val < p}) = maximalIdeal (Localization.AtPrime Q) ∧
        Submodule.span (ResidueField (Localization.AtPrime Q))
          ((fun j ↦ D k (ResidueField (Localization.AtPrime Q)) (residue _
            (algebraMap (MvPolynomial (Fin n) k) (Localization.AtPrime Q) (X j)))) ''
              {j | p ≤ j.val}) = ⊤ := by
  have : IsScalarTower k (MvPolynomial (Fin n) k) (Localization.AtPrime Q) := .to₁₂₄ _ _ S _
  have : EssFiniteType k (Localization.AtPrime Q) := .comp k S _
  have : IsNoetherianRing S := FiniteType.isNoetherianRing k S
  have : IsNoetherianRing (Localization.AtPrime Q) :=
    IsLocalization.isNoetherianRing Q.primeCompl _ inferInstance
  constructor
  · intro he
    have hE : FormallyEtale (MvPolynomial (Fin n) k) (Localization.AtPrime Q) := he
    have : FormallySmooth k (Localization.AtPrime Q) := .comp k (MvPolynomial (Fin n) k) _
    obtain ⟨hli, hsp⟩ := (formallyEtale_mvPolynomial_iff_residueField (R := k)
      (B := Localization.AtPrime Q) (ι := Fin n)).mp hE
    -- `trdeg_k κ(x) = n - p`
    have hdim := FiniteType.topologicalKrullDimAt_eq_ringKrullDim_add_trdeg k Q
    rw [hn, hp] at hdim
    have hne : (trdeg k Q.ResidueField).toENat ≠ ⊤ := by
      intro h
      rw [h] at hdim
      have h' : ((n : ℕ∞) : WithBot ℕ∞) = (((p : ℕ∞) + ⊤ : ℕ∞) : WithBot ℕ∞) := by
        rw [WithBot.coe_add]
        exact_mod_cast hdim
      rw [add_top] at h'
      exact ENat.natCast_ne_top n (WithBot.coe_inj.mp h')
    obtain ⟨m, hm⟩ := ENat.ne_top_iff_exists.mp hne
    rw [← hm] at hdim
    have hnm : n = p + m := by exact_mod_cast hdim
    have htr : trdeg k (ResidueField (Localization.AtPrime Q)) = (n - p : ℕ) := by
      have : (trdeg k Q.ResidueField).toENat = ((n - p : ℕ) : ℕ∞) := by
        rw [← hm]
        congr 1
        omega
      exact Cardinal.toENat_eq_natCast.mp this
    exact span_maximalIdeal_and_span_kaehler_of_basis (by omega) _ hf hli hsp htr
  · rintro ⟨h𝔪, hκ⟩
    have h1 := span_tmul_D_eq_top_of_span (k := k) _ h𝔪 hκ
    refine isEtaleAt_of_span_eq_top Q hn ?_
    rw [← map_tensorProduct_mk_eq_top, Submodule.map_span, ← Set.range_comp]
    have hsurj : Function.Surjective (algebraMap (Localization.AtPrime Q)
        (ResidueField (Localization.AtPrime Q))) := by
      rw [ResidueField.algebraMap_eq]
      exact residue_surjective
    rw [← Submodule.restrictScalars_span (Localization.AtPrime Q)
      (ResidueField (Localization.AtPrime Q)) hsurj]
    change (Submodule.span (ResidueField (Localization.AtPrime Q)) (Set.range fun i ↦
      (1 : ResidueField (Localization.AtPrime Q)) ⊗ₜ[Localization.AtPrime Q]
        D k (Localization.AtPrime Q)
          (algebraMap (MvPolynomial (Fin n) k) _ (X i)))).restrictScalars _ = ⊤
    rw [h1, Submodule.restrictScalars_top]

/-- The two parts of `Sum.elim g h ∘ finSumFinEquiv.symm : Fin (p + q) → S`. -/
lemma image_sumElim_finSumFinEquiv {S T : Type*} (φ : S → T) {p q : ℕ} (g : Fin p → S)
    (h : Fin q → S) :
    (fun i ↦ φ ((Sum.elim g h ∘ finSumFinEquiv.symm) i)) '' {i : Fin (p + q) | i.val < p} =
      Set.range (φ ∘ g) ∧
    (fun i ↦ φ ((Sum.elim g h ∘ finSumFinEquiv.symm) i)) '' {i : Fin (p + q) | p ≤ i.val} =
      Set.range (φ ∘ h) := by
  constructor
  · ext y
    constructor
    · rintro ⟨i, hi, rfl⟩
      induction i using Fin.addCases with
      | left a => exact ⟨a, by simp [finSumFinEquiv_symm_apply_castAdd]⟩
      | right b => exact absurd hi (by simp)
    · rintro ⟨i, rfl⟩
      exact ⟨Fin.castAdd q i, by simp, by simp [finSumFinEquiv_symm_apply_castAdd]⟩
  · ext y
    constructor
    · rintro ⟨i, hi, rfl⟩
      induction i using Fin.addCases with
      | left a => exact absurd hi (by simp)
      | right b => exact ⟨b, by simp [finSumFinEquiv_symm_apply_natAdd]⟩
    · rintro ⟨i, rfl⟩
      exact ⟨Fin.natAdd p i, by simp, by simp [finSumFinEquiv_symm_apply_natAdd]⟩

/-- II.5.9: let `X = Spec S` be of finite type over a field `k`, `x` a point (a prime `Q`) where
`X` has dimension `p + q` and `𝒪_x` has dimension `p` (so `trdeg_k κ(x) = q`). The following are
equivalent: (i) `𝒪_x` is regular and `κ(x)` is separable over `k`; (ii) `X` is smooth over `k`
at `x` and `𝔪_x/𝔪_x² → Ω¹_{X/k}(x)` is injective; (iii) there are `g₁,…,gₚ` vanishing at `x`
and `h₁,…,h_q` such that `(g, h) : X → 𝔸^{p+q}` is étale at `x`; (iv) there are `g₁,…,gₚ`
generating `𝔪_x` and `h₁,…,h_q` whose classes have differentials generating `Ω¹_{κ(x)/k}`.
(SGA takes germs at `x`; we take sections over an affine neighbourhood `Spec S`.) -/
theorem isRegularLocalRing_and_isGeometricallyReduced_tfae {k S : Type u} [Field k] [CommRing S]
    [Algebra k S] [FiniteType k S] (Q : Ideal S) [Q.IsPrime] {p q : ℕ}
    (hn : topologicalKrullDimAt (PrimeSpectrum S) ⟨Q, ‹_›⟩ = (p + q : ℕ))
    (hp : ringKrullDim (Localization.AtPrime Q) = p) :
    List.TFAE [
      IsRegularLocalRing (Localization.AtPrime Q) ∧ IsGeometricallyReduced k Q.ResidueField,
      IsSmoothAt k Q ∧ Function.Injective (kerCotangentToTensor k (Localization.AtPrime Q)
        (ResidueField (Localization.AtPrime Q))),
      ∃ (g : Fin p → S) (h : Fin q → S), (∀ i, g i ∈ Q) ∧
        letI := (MvPolynomial.aeval (R := k)
          (Sum.elim g h ∘ finSumFinEquiv.symm)).toRingHom.toAlgebra
        IsEtaleAt (MvPolynomial (Fin (p + q)) k) Q,
      ∃ (g : Fin p → S) (h : Fin q → S),
        Ideal.span (Set.range (algebraMap S (Localization.AtPrime Q) ∘ g)) =
          maximalIdeal (Localization.AtPrime Q) ∧
        Submodule.span (ResidueField (Localization.AtPrime Q)) (Set.range fun j ↦
          D k (ResidueField (Localization.AtPrime Q))
            (residue _ (algebraMap S (Localization.AtPrime Q) (h j)))) = ⊤] := by
  have : EssFiniteType k (Localization.AtPrime Q) := .comp k S _
  have : EssFiniteType k Q.ResidueField := .comp k S _
  -- `trdeg_k κ(x) = q`
  have htr : trdeg k Q.ResidueField = q := by
    have hdim := FiniteType.topologicalKrullDimAt_eq_ringKrullDim_add_trdeg k Q
    rw [hn, hp] at hdim
    have hne : (trdeg k Q.ResidueField).toENat ≠ ⊤ := by
      intro h
      rw [h] at hdim
      have h' : (((p + q : ℕ) : ℕ∞) : WithBot ℕ∞) = (((p : ℕ∞) + ⊤ : ℕ∞) : WithBot ℕ∞) := by
        rw [WithBot.coe_add]
        exact_mod_cast hdim
      rw [add_top] at h'
      exact ENat.natCast_ne_top _ (WithBot.coe_inj.mp h')
    obtain ⟨m, hm⟩ := ENat.ne_top_iff_exists.mp hne
    rw [← hm] at hdim
    have : p + q = p + m := by exact_mod_cast hdim
    exact Cardinal.toENat_eq_natCast.mp (by rw [← hm]; congr 1; omega)
  -- (iii) ⇔ (iv), by II.5.8
  have key (g : Fin p → S) (h : Fin q → S) (hg : ∀ i, g i ∈ Q) :
      (letI := (MvPolynomial.aeval (R := k)
          (Sum.elim g h ∘ finSumFinEquiv.symm)).toRingHom.toAlgebra;
        IsEtaleAt (MvPolynomial (Fin (p + q)) k) Q) ↔
      (Ideal.span (Set.range (algebraMap S (Localization.AtPrime Q) ∘ g)) =
          maximalIdeal (Localization.AtPrime Q) ∧
        Submodule.span (ResidueField (Localization.AtPrime Q)) (Set.range fun j ↦
          D k (ResidueField (Localization.AtPrime Q))
            (residue _ (algebraMap S (Localization.AtPrime Q) (h j)))) = ⊤) := by
    algebraize [(MvPolynomial.aeval (R := k) (Sum.elim g h ∘ finSumFinEquiv.symm)).toRingHom]
    have : IsScalarTower k (MvPolynomial (Fin (p + q)) k) S := .of_algHom (MvPolynomial.aeval _)
    have hX (i : Fin (p + q)) :
        algebraMap (MvPolynomial (Fin (p + q)) k) (Localization.AtPrime Q) (X i) =
          algebraMap S _ ((Sum.elim g h ∘ finSumFinEquiv.symm) i) := by
      rw [IsScalarTower.algebraMap_apply _ S]
      congr 1
      exact aeval_X _ i
    have hf (i : Fin (p + q)) (hi : i.val < p) :
        algebraMap (MvPolynomial (Fin (p + q)) k) (Localization.AtPrime Q) (X i) ∈
          maximalIdeal (Localization.AtPrime Q) := by
      rw [hX, IsLocalization.AtPrime.to_map_mem_maximal_iff _ Q]
      induction i using Fin.addCases with
      | left a => simpa [finSumFinEquiv_symm_apply_castAdd] using hg a
      | right b => exact absurd hi (by simp)
    rw [isEtaleAt_iff_span_maximalIdeal_and_span_kaehler Q hn hp hf]
    simp only [hX]
    obtain ⟨h1, -⟩ := image_sumElim_finSumFinEquiv (algebraMap S (Localization.AtPrime Q)) g h
    obtain ⟨-, h2⟩ := image_sumElim_finSumFinEquiv (fun s ↦ D k
      (ResidueField (Localization.AtPrime Q)) (residue _ (algebraMap S _ s))) g h
    rw [h1, h2]
    rfl
  have hgQ (g : Fin p → S) (hspan : Ideal.span (Set.range (algebraMap S
      (Localization.AtPrime Q) ∘ g)) = maximalIdeal (Localization.AtPrime Q)) (i : Fin p) :
      g i ∈ Q := by
    rw [← IsLocalization.AtPrime.to_map_mem_maximal_iff (Localization.AtPrime Q) Q, ← hspan]
    exact Ideal.subset_span ⟨i, rfl⟩
  have h43 : (∃ (g : Fin p → S) (h : Fin q → S),
      Ideal.span (Set.range (algebraMap S (Localization.AtPrime Q) ∘ g)) =
        maximalIdeal (Localization.AtPrime Q) ∧
      Submodule.span (ResidueField (Localization.AtPrime Q)) (Set.range fun j ↦
        D k (ResidueField (Localization.AtPrime Q))
          (residue _ (algebraMap S (Localization.AtPrime Q) (h j)))) = ⊤) →
      ∃ (g : Fin p → S) (h : Fin q → S), (∀ i, g i ∈ Q) ∧
        letI := (MvPolynomial.aeval (R := k)
          (Sum.elim g h ∘ finSumFinEquiv.symm)).toRingHom.toAlgebra
        IsEtaleAt (MvPolynomial (Fin (p + q)) k) Q := fun ⟨g, h, h1, h2⟩ ↦
    ⟨g, h, hgQ g h1, (key g h (hgQ g h1)).mpr ⟨h1, h2⟩⟩
  tfae_have 1 ↔ 2 := isRegularLocalRing_and_isGeometricallyReduced_iff k Q
  tfae_have 3 → 4 := fun ⟨g, h, hg, he⟩ ↦ ⟨g, h, (key g h hg).mp he⟩
  tfae_have 4 → 3 := h43
  tfae_have 4 → 1 := fun h4 ↦ by
    obtain ⟨g, h, h1, h2⟩ := h4
    obtain ⟨g', h', -, he⟩ := h43 ⟨g, h, h1, h2⟩
    algebraize [(MvPolynomial.aeval (R := k) (Sum.elim g' h' ∘ finSumFinEquiv.symm)).toRingHom]
    have : IsScalarTower k (MvPolynomial (Fin (p + q)) k) S := .of_algHom (MvPolynomial.aeval _)
    have : IsScalarTower k (MvPolynomial (Fin (p + q)) k) (Localization.AtPrime Q) :=
      .to₁₂₄ _ _ S _
    have hE : FormallyEtale (MvPolynomial (Fin (p + q)) k) (Localization.AtPrime Q) := he
    have : IsSmoothAt k Q := FormallySmooth.comp k (MvPolynomial (Fin (p + q)) k) _
    refine ⟨isRegularLocalRing_of_isSmoothAt k Q, ?_⟩
    have hsep : IsSeparablyGenerated k Q.ResidueField :=
      IsSeparablyGenerated.of_span_eq_top h2 (by rw [htr, Nat.card_eq_fintype_card,
        Fintype.card_fin])
    exact hsep.isGeometricallyReduced
  tfae_have 1 → 4 := fun ⟨hreg, hsep⟩ ↦ by
    -- a regular system of parameters coming from `S`
    obtain ⟨rs, hlen, hrs, -⟩ :=
      IsRegularLocalRing.exists_isRegular_ofList_eq_maximalIdeal (R := Localization.AtPrime Q)
    have hlen' : rs.length = p := by
      rw [hp] at hlen
      exact_mod_cast hlen
    let g' : Fin p → Localization.AtPrime Q := fun i ↦ rs.get (Fin.cast hlen'.symm i)
    have hg' : Ideal.span (Set.range g') = maximalIdeal (Localization.AtPrime Q) := by
      rw [← hrs]
      change _ = Ideal.span {r | r ∈ rs}
      congr 1
      ext r
      simp only [Set.mem_range, Set.mem_ofPred_eq, List.mem_iff_get, g']
      exact ⟨fun ⟨i, hi⟩ ↦ ⟨_, hi⟩, fun ⟨i, hi⟩ ↦ ⟨Fin.cast hlen' i, by simpa using hi⟩⟩
    choose a t ht using fun i ↦ IsLocalization.exists_mk'_eq Q.primeCompl (g' i)
    let u : Fin p → (Localization.AtPrime Q)ˣ :=
      fun i ↦ (IsLocalization.map_units (Localization.AtPrime Q) (t i)).unit
    have hua : (fun i ↦ (u i : Localization.AtPrime Q) * g' i) =
        algebraMap S (Localization.AtPrime Q) ∘ a := by
      funext i
      rw [Function.comp_apply, ← ht i, IsUnit.unit_spec, mul_comm, IsLocalization.mk'_spec]
    have hg : Ideal.span (Set.range (algebraMap S (Localization.AtPrime Q) ∘ a)) =
        maximalIdeal (Localization.AtPrime Q) := by
      rw [← hua, span_range_units_mul, hg']
    -- differentials of classes of elements of `S` generating `Ω¹_{κ(x)/k}`
    let v : S → Ω[ResidueField (Localization.AtPrime Q)⁄k] := fun s ↦
      D k _ (residue _ (algebraMap S (Localization.AtPrime Q) s))
    have hv : Submodule.span (ResidueField (Localization.AtPrime Q)) (Set.range v) = ⊤ := by
      have := span_range_map_derivation_of_isLocalization (R := k) (S := S ⧸ Q)
        (T := Q.ResidueField) (nonZeroDivisors (S ⧸ Q))
      rw [← this]
      congr 1
      ext ω
      simp only [Set.mem_range, Function.comp_apply, KaehlerDifferential.map_D, v]
      constructor
      · rintro ⟨s, rfl⟩
        refine ⟨Ideal.Quotient.mk Q s, ?_⟩
        rw [← Ideal.Quotient.algebraMap_eq, ← IsScalarTower.algebraMap_apply,
          IsScalarTower.algebraMap_apply S (Localization.AtPrime Q) Q.ResidueField]
        rfl
      · rintro ⟨x, rfl⟩
        obtain ⟨s, rfl⟩ := Ideal.Quotient.mk_surjective x
        refine ⟨s, ?_⟩
        rw [← Ideal.Quotient.algebraMap_eq, ← IsScalarTower.algebraMap_apply,
          IsScalarTower.algebraMap_apply S (Localization.AtPrime Q) Q.ResidueField]
        rfl
    obtain ⟨κ', b', -, hsp, hli⟩ :=
      exists_linearIndependent' (ResidueField (Localization.AtPrime Q)) v
    rw [hv] at hsp
    let B := Module.Basis.mk hli hsp.ge
    have : Finite κ' := Module.Finite.finite_basis B
    have hsg : IsSeparablyGenerated k Q.ResidueField := IsGeometricallyReduced.isSeparablyGenerated
    have hcard : Nat.card κ' = q := by
      have := hsg.finrank_kaehlerDifferential
      rw [htr, Module.finrank_eq_nat_card_basis B] at this
      simpa using this
    let e := Finite.equivFinOfCardEq hcard
    refine ⟨a, b' ∘ e.symm, hg, ?_⟩
    rw [← hsp, ← e.symm.surjective.range_comp]
    rfl
  tfae_finish

end SGA.SGA1.ExposeII
