/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import Mathlib.Topology.Algebra.Category.ProfiniteGrp.Completion
import Mathlib.Topology.Algebra.ClopenNhdofOne
import Mathlib.CategoryTheory.Galois.Prorepresentability
import Mathlib.CategoryTheory.Galois.Topology
import Mathlib.GroupTheory.Finiteness

/-!
# Topologically finitely generated profinite groups

A topological group `G` is *topologically generated* by a subset `s` if the subgroup generated by
`s` is dense. We work with finite sets of topological generators of bounded cardinality.

## Main results

* `Subgroup.exists_finset_dense_closure_iff`: "a finite set generates a dense subgroup" in its
  two usual formulations (a `Finset` whose generated subgroup is dense, a finite `Set` whose
  generated subgroup has topological closure `⊤`).
* `ProfiniteGrp.ProfiniteCompletion.dense_closure_image_etaFn`: if `s` generates `G`, its image
  topologically generates the profinite completion `Ĝ`; hence `Ĝ` is topologically finitely
  generated when `G` is finitely generated (`exists_finset_card_le_dense_closure`).
* `exists_finset_card_le_dense_closure_of_forall_openNormalSubgroup` (uniform
  criterion): a compact, totally disconnected group `G` such that every quotient `G ⧸ N` by an
  open normal subgroup is generated by `d` elements is topologically generated by `d` elements.
* `CategoryTheory.PreGaloisCategory.exists_finset_card_le_dense_closure_aut_iff`: the
  fundamental group `Aut F` of a Galois category is topologically generated by `d` elements if and
  only if the automorphism group of every Galois object is generated by `d` elements.

## References

* [L. Ribes, P. Zalesskii, *Profinite groups*, §2.5][RibesZalesskii2010]
* [SGA 1, Exposé IX, 5.2 and Exposé X, 2.9][sga1]
-/

universe u u₁ u₂ w

open Topology

namespace Subgroup

variable {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]

/-- A group is topologically generated by a finite set in the sense of a `Finset` with dense
generated subgroup if and only if some finite `Set` generates a subgroup with topological closure
`⊤`. -/
theorem exists_finset_dense_closure_iff :
    (∃ s : Finset G, Dense (closure (s : Set G) : Set G)) ↔
      ∃ S : Set G, S.Finite ∧ (closure S).topologicalClosure = ⊤ := by
  constructor
  · rintro ⟨s, hs⟩
    refine ⟨s, s.finite_toSet, ?_⟩
    rw [← SetLike.coe_set_eq, topologicalClosure_coe, coe_top, hs.closure_eq]
  · rintro ⟨S, hS, h⟩
    refine ⟨hS.toFinset, ?_⟩
    rw [hS.coe_toFinset, dense_iff_closure_eq, ← topologicalClosure_coe, h, coe_top]

end Subgroup

namespace ProfiniteGrp.ProfiniteCompletion

open CategoryTheory

variable {G : GrpCat.{u}}

/-- If `s` generates the group `G`, its image topologically generates the profinite completion
of `G`. -/
theorem dense_closure_image_etaFn {s : Set G} (hs : Subgroup.closure s = ⊤) :
    Dense (Subgroup.closure (etaFn G '' s) : Set (completion G)) := by
  have h : (Subgroup.closure (etaFn G '' s) : Set (completion G)) = Set.range (etaFn G) := by
    change (Subgroup.closure ((eta G).hom '' s) : Set (completion G)) = Set.range (eta G).hom
    rw [← MonoidHom.map_closure, hs, ← MonoidHom.range_eq_map, MonoidHom.coe_range]
  rw [h]
  exact denseRange G

/-- The profinite completion of a group generated by a finite set `s` is topologically generated
by at most `#s` elements. -/
theorem exists_finset_card_le_dense_closure (s : Finset G)
    (hs : Subgroup.closure (s : Set G) = ⊤) :
    ∃ t : Finset (completion G), t.card ≤ s.card ∧
      Dense (Subgroup.closure (t : Set (completion G)) : Set (completion G)) := by
  classical
  refine ⟨s.image (etaFn G), Finset.card_image_le, ?_⟩
  rw [Finset.coe_image]
  exact dense_closure_image_etaFn hs

/-- The profinite completion of a finitely generated group is topologically finitely
generated. -/
theorem exists_finset_dense_closure [Group.FG G] :
    ∃ t : Finset (completion G),
      Dense (Subgroup.closure (t : Set (completion G)) : Set (completion G)) := by
  obtain ⟨s, hs⟩ := (Group.fg_def).mp ‹Group.FG G›
  obtain ⟨t, -, ht⟩ := exists_finset_card_le_dense_closure s hs
  exact ⟨t, ht⟩

end ProfiniteGrp.ProfiniteCompletion

section UniformCriterion

variable {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]

/-- The `d`-tuples of elements of `G` which generate `G` modulo `N`. -/
private def generatingTuples (d : ℕ) (N : Subgroup G) : Set (Fin d → G) :=
  {x | Subgroup.closure (Set.range x) ⊔ N = ⊤}

omit [TopologicalSpace G] [IsTopologicalGroup G] in
private lemma mem_generatingTuples_of_forall {d : ℕ} {N : Subgroup G} {x y : Fin d → G}
    (hx : x ∈ generatingTuples d N) (hy : ∀ i, (y i)⁻¹ * x i ∈ N) :
    y ∈ generatingTuples d N := by
  refine eq_top_iff.mpr (hx.symm.le.trans (sup_le ?_ le_sup_right))
  rw [Subgroup.closure_le]
  rintro _ ⟨i, rfl⟩
  have : x i = y i * ((y i)⁻¹ * x i) := by group
  rw [SetLike.mem_coe, this]
  exact mul_mem (Subgroup.mem_sup_left (Subgroup.subset_closure ⟨i, rfl⟩))
    (Subgroup.mem_sup_right (hy i))

/-- The set of `y` with `y i ∈ x i * N` for all `i` is open when `N` is. -/
private lemma isOpen_setOf_forall_mem {d : ℕ} {N : Subgroup G} (hN : IsOpen (N : Set G))
    (x : Fin d → G) : IsOpen {y : Fin d → G | ∀ i, (y i)⁻¹ * x i ∈ N} := by
  rw [Set.ofPred_forall]
  refine isOpen_iInter_of_finite fun i ↦ hN.preimage ?_
  exact ((continuous_apply i).inv).mul continuous_const

private lemma isClosed_generatingTuples {d : ℕ} {N : Subgroup G} (hN : IsOpen (N : Set G)) :
    IsClosed (generatingTuples d N) := by
  rw [← isOpen_compl_iff, isOpen_iff_forall_mem_open]
  intro x hx
  refine ⟨_, fun y hy hyN ↦ hx (mem_generatingTuples_of_forall hyN fun i ↦ ?_),
    isOpen_setOf_forall_mem hN x, fun i ↦ by simp⟩
  simpa using inv_mem (hy i)

omit [TopologicalSpace G] [IsTopologicalGroup G] in
private lemma nonempty_generatingTuples {d : ℕ} {N : Subgroup G} {s : Finset G}
    (hs : s.card ≤ d) (h : Subgroup.closure (s : Set G) ⊔ N = ⊤) :
    (generatingTuples d N).Nonempty := by
  classical
  refine ⟨fun i ↦ s.toList.getD i 1, eq_top_iff.mpr (h.symm.le.trans
    (sup_le_sup_right (Subgroup.closure_mono ?_) N))⟩
  intro a ha
  obtain ⟨j, hj, rfl⟩ := List.mem_iff_getElem.mp (Finset.mem_toList.mpr ha)
  have hjd : j < d := (Finset.length_toList s ▸ hj).trans_le hs
  exact ⟨⟨j, hjd⟩, by simp [List.getElem?_eq_getElem hj]⟩

variable [CompactSpace G] [TotallyDisconnectedSpace G]

/-- **Uniform criterion for topological generation.** Let `G` be a compact, totally disconnected
group (a profinite group). If for every open normal subgroup `N` some `d` elements generate `G`
modulo `N`, then `d` elements topologically generate `G`. -/
theorem exists_finset_card_le_dense_closure_of_forall_openNormalSubgroup (d : ℕ)
    (h : ∀ N : OpenNormalSubgroup G, ∃ s : Finset G, s.card ≤ d ∧
      Subgroup.closure (s : Set G) ⊔ (N : Subgroup G) = ⊤) :
    ∃ s : Finset G, s.card ≤ d ∧ Dense (Subgroup.closure (s : Set G) : Set G) := by
  classical
  let T : OpenNormalSubgroup G → Set (Fin d → G) := fun N ↦ generatingTuples d N
  have : Nonempty (OpenNormalSubgroup G) :=
    ⟨{ toSubgroup := ⊤, isOpen' := isOpen_univ, isNormal' := inferInstance }⟩
  have hdir : Directed (· ⊇ ·) T := by
    intro N M
    refine ⟨N ⊓ M, fun x hx ↦ eq_top_iff.mpr (hx.symm.le.trans (sup_le_sup_left ?_ _)),
      fun x hx ↦ eq_top_iff.mpr (hx.symm.le.trans (sup_le_sup_left ?_ _))⟩
    · exact fun g hg ↦ (inf_le_left : N ⊓ M ≤ N) hg
    · exact fun g hg ↦ (inf_le_right : N ⊓ M ≤ M) hg
  have hne : ∀ N, (T N).Nonempty := fun N ↦
    have ⟨s, hs, hsN⟩ := h N
    nonempty_generatingTuples hs hsN
  have hcl : ∀ N, IsClosed (T N) := fun N ↦ isClosed_generatingTuples N.isOpen
  obtain ⟨x, hx⟩ := IsCompact.nonempty_iInter_of_directed_nonempty_isCompact_isClosed T hdir hne
    (fun N ↦ (hcl N).isCompact) hcl
  rw [Set.mem_iInter] at hx
  refine ⟨Finset.univ.image x, Finset.card_image_le.trans (by simp), ?_⟩
  rw [Finset.coe_image, Finset.coe_univ, Set.image_univ, dense_iff_inter_open]
  rintro U hU ⟨g, hgU⟩
  obtain ⟨N, hN⟩ := ProfiniteGrp.exist_openNormalSubgroup_sub_open_nhds_of_one
    (hU.preimage (continuous_const_mul g)) (by simpa using hgU)
  have hg : g ∈ Subgroup.closure (Set.range x) ⊔ (N : Subgroup G) := by
    rw [show Subgroup.closure (Set.range x) ⊔ (N : Subgroup G) = ⊤ from hx N]
    trivial
  obtain ⟨a, ha, n, hn, rfl⟩ := Subgroup.mem_sup_of_normal_right.mp hg
  refine ⟨a, ?_, ha⟩
  have : a * n * n⁻¹ = a := by group
  rw [← this]
  exact hN (inv_mem hn)

end UniformCriterion

namespace CategoryTheory.PreGaloisCategory

variable {C : Type u₁} [Category.{u₂} C] [GaloisCategory C] (F : C ⥤ FintypeCat.{w})
  [FiberFunctor F]

omit [GaloisCategory C] [FiberFunctor F] in
private lemma aut_smul_comm {A : C} (φ : Aut A) (σ : Aut F) (x : F.obj A) :
    φ • σ • x = σ • φ • x :=
  (mulAction_naturality F σ φ.hom x).symm

/-- For a point `a` of the fibre of `A` and a subgroup `K` of `Aut F`, the automorphisms `φ` of
`A` such that `φ • a` lies in the `K`-orbit of `a`. -/
private def autSubgroupOfAutFiber {A : C} (a : F.obj A) (K : Subgroup (Aut F)) :
    Subgroup (Aut A) where
  carrier := {φ | ∃ σ ∈ K, σ • a = φ • a}
  one_mem' := ⟨1, K.one_mem, by simp⟩
  mul_mem' := by
    rintro φ ψ ⟨σ, hσ, hσa⟩ ⟨τ, hτ, hτa⟩
    refine ⟨τ * σ, K.mul_mem hτ hσ, ?_⟩
    rw [mul_smul, mul_smul, ← hτa, aut_smul_comm, ← hσa]
  inv_mem' := by
    rintro φ ⟨σ, hσ, hσa⟩
    refine ⟨σ⁻¹, K.inv_mem hσ, ?_⟩
    rw [inv_smul_eq_iff, ← aut_smul_comm, hσa, inv_smul_smul]

/-- For a point `a` of the fibre of `A` and a subgroup `Φ` of `Aut A`, the elements `σ` of
`Aut F` such that `σ • a` lies in the `Φ`-orbit of `a`. -/
private def autFiberSubgroupOfAut {A : C} (a : F.obj A) (Φ : Subgroup (Aut A)) :
    Subgroup (Aut F) where
  carrier := {σ | ∃ φ ∈ Φ, σ • a = φ • a}
  one_mem' := ⟨1, Φ.one_mem, by simp⟩
  mul_mem' := by
    rintro σ τ ⟨φ, hφ, hσa⟩ ⟨ψ, hψ, hτa⟩
    refine ⟨ψ * φ, Φ.mul_mem hψ hφ, ?_⟩
    rw [mul_smul, mul_smul, hτa, ← aut_smul_comm, hσa]
  inv_mem' := by
    rintro σ ⟨φ, hφ, hσa⟩
    refine ⟨φ⁻¹, Φ.inv_mem hφ, ?_⟩
    rw [inv_smul_eq_iff, ← aut_smul_comm, hσa, inv_smul_smul]

/-- If the automorphism group of every Galois object is generated by `d` elements, the
fundamental group `Aut F` is topologically generated by `d` elements. -/
theorem exists_finset_card_le_dense_closure_aut_of_forall_isGalois (d : ℕ)
    (h : ∀ (A : C) [IsGalois A], ∃ t : Finset (Aut A), t.card ≤ d ∧
      Subgroup.closure (t : Set (Aut A)) = ⊤) :
    ∃ s : Finset (Aut F), s.card ≤ d ∧
      Dense (Subgroup.closure (s : Set (Aut F)) : Set (Aut F)) := by
  classical
  refine exists_finset_card_le_dense_closure_of_forall_openNormalSubgroup d
    fun N ↦ ?_
  obtain ⟨⟨A, a, hA⟩, -, hN⟩ := (nhds_one_has_basis_stabilizers F).mem_iff.mp
    (N.isOpen.mem_nhds N.one_mem)
  obtain ⟨t, ht, htop⟩ := h A
  choose σ hσ using fun φ : Aut A ↦ MulAction.exists_smul_eq (Aut F) a (φ • a)
  refine ⟨t.image σ, Finset.card_image_le.trans ht, eq_top_iff.mpr fun τ _ ↦ ?_⟩
  have hle : Subgroup.closure (t : Set (Aut A)) ≤
      autSubgroupOfAutFiber F a (Subgroup.closure (t.image σ : Set (Aut F))) := by
    rw [Subgroup.closure_le]
    intro φ hφ
    exact ⟨σ φ, Subgroup.subset_closure (Finset.mem_image_of_mem σ hφ), hσ φ⟩
  obtain ⟨φ, hφ⟩ := MulAction.exists_smul_eq (Aut A) a (τ • a)
  obtain ⟨ρ, hρ, hρa⟩ := hle (htop ▸ Subgroup.mem_top φ)
  have hstab : ρ⁻¹ * τ ∈ MulAction.stabilizer (Aut F) a := by
    rw [MulAction.mem_stabilizer_iff, mul_smul, ← hφ, ← hρa, inv_smul_smul]
  have : τ = ρ * (ρ⁻¹ * τ) := by group
  rw [this]
  exact mul_mem (Subgroup.mem_sup_left hρ) (Subgroup.mem_sup_right (hN hstab))

/-- If `Aut F` is topologically generated by `d` elements, the automorphism group of every Galois
object is generated by `d` elements (it is a continuous quotient of `Aut F`). -/
theorem exists_finset_card_le_closure_eq_top_of_dense {d : ℕ} {s : Finset (Aut F)}
    (hs : s.card ≤ d) (hd : Dense (Subgroup.closure (s : Set (Aut F)) : Set (Aut F)))
    (A : C) [IsGalois A] :
    ∃ t : Finset (Aut A), t.card ≤ d ∧ Subgroup.closure (t : Set (Aut A)) = ⊤ := by
  classical
  obtain ⟨a⟩ := nonempty_fiber_of_isConnected F A
  choose φ hφ using fun σ : Aut F ↦ MulAction.exists_smul_eq (Aut A) a (σ • a)
  refine ⟨s.image φ, Finset.card_image_le.trans hs, eq_top_iff.mpr fun ψ _ ↦ ?_⟩
  let H := autFiberSubgroupOfAut F a (Subgroup.closure (s.image φ : Set (Aut A)))
  have hstab : MulAction.stabilizer (Aut F) a ≤ H := fun σ hσ ↦
    ⟨1, one_mem _, by rw [one_smul]; exact hσ⟩
  have hclosed : IsClosed (H : Set (Aut F)) :=
    Subgroup.isClosed_of_isOpen H (Subgroup.isOpen_mono hstab (stabilizer_isOpen _ a))
  have hsH : (Subgroup.closure (s : Set (Aut F)) : Set (Aut F)) ⊆ H := by
    change Subgroup.closure (s : Set (Aut F)) ≤ H
    rw [Subgroup.closure_le]
    intro σ hσ
    exact ⟨φ σ, Subgroup.subset_closure (Finset.mem_image_of_mem φ hσ), (hφ σ).symm⟩
  have hH : ∀ τ, τ ∈ H := fun τ ↦
    (hd.closure_eq ▸ closure_minimal hsH hclosed) (Set.mem_univ τ)
  obtain ⟨τ, hτ⟩ := MulAction.exists_smul_eq (Aut F) a (ψ • a)
  obtain ⟨χ, hχ, hχa⟩ := hH τ
  have : χ = ψ := evaluation_aut_injective_of_isConnected F A a (hχa.symm.trans hτ)
  exact this ▸ hχ

/-- The fundamental group `Aut F` of a Galois category is topologically generated by `d`
elements if and only if the automorphism group of every Galois object is generated by `d`
elements. -/
theorem exists_finset_card_le_dense_closure_aut_iff (d : ℕ) :
    (∃ s : Finset (Aut F), s.card ≤ d ∧
      Dense (Subgroup.closure (s : Set (Aut F)) : Set (Aut F))) ↔
      ∀ (A : C) [IsGalois A], ∃ t : Finset (Aut A), t.card ≤ d ∧
        Subgroup.closure (t : Set (Aut A)) = ⊤ :=
  ⟨fun ⟨_, hs, hd⟩ A _ ↦ exists_finset_card_le_closure_eq_top_of_dense F hs hd A,
    exists_finset_card_le_dense_closure_aut_of_forall_isGalois F d⟩

end CategoryTheory.PreGaloisCategory
