/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import Mathlib.Algebra.Category.ModuleCat.Differentials.Presheaf

/-!
# The presheaf of relative differentials of `S ⟶ F.op ⋙ R`

Let `F : C ⥤ D` be a functor, `S` a presheaf of commutative rings on `C`, `R` a presheaf of
commutative rings on `D` and `φ : S ⟶ F.op ⋙ R`. Mathlib defines the type `M.Derivation φ` of
`φ`-derivations with values in a presheaf of `R`-modules `M`, and constructs a universal
derivation when `F` is the identity (`PresheafOfModules.DifferentialsConstruction.derivation'`).
This file constructs the universal derivation in general. The main case is a morphism of schemes
`f : X ⟶ Y`, with `F = Opens.map f.base` and `φ = f.c`: the derivations are then the
`f⁻¹ 𝒪_Y`-derivations of `𝒪_X` (Stacks Project, Tag 01UM; EGA IV 16.3).

Instead of the inverse image presheaf `F⁻¹ S`, we use its image in `R`: `imagePresheaf φ` is the
presheaf of subrings of `R` generated by the restrictions of the sections `φ(a)`. A derivation
vanishes on `φ`, i.e. is a `φ`-derivation, if and only if it vanishes on `imagePresheaf φ`
(`derivationEquiv`), so the universal derivation for the inclusion `imagePresheaf φ ⟶ R` is
universal for `φ`.

## Main definitions

* `PresheafOfModules.DifferentialsConstruction.relativeDifferentials φ`: the presheaf of
  relative differentials of `φ`.
* `PresheafOfModules.DifferentialsConstruction.derivation φ`: the universal derivation, and
  `isUniversal φ` its universal property.
-/

universe v u v₁ v₂ u₁ u₂

open CategoryTheory Opposite

namespace PresheafOfModules

variable {C : Type u₁} [Category.{v₁} C] {D : Type u₂} [Category.{v₂} D]
  {S : Cᵒᵖ ⥤ CommRingCat.{u}} {F : C ⥤ D} {R : Dᵒᵖ ⥤ CommRingCat.{u}}
  {M : PresheafOfModules.{v} (R ⋙ forget₂ _ _)} {φ : S ⟶ F.op ⋙ R}

namespace Derivation

variable (d : M.Derivation φ)

/-- The subring of sections on which a derivation vanishes. -/
def kerSubring (X : Dᵒᵖ) : Subring (R.obj X) where
  carrier := {r | d.d r = 0}
  mul_mem' {a b} (ha : d.d a = 0) (hb : d.d b = 0) := by
    change d.d (a * b) = 0
    rw [d.d_mul, ha, hb, smul_zero, smul_zero, add_zero]
  one_mem' := d.d_one X
  add_mem' {a b} (ha : d.d a = 0) (hb : d.d b = 0) := by
    change d.d (a + b) = 0
    rw [map_add, ha, hb, add_zero]
  zero_mem' := map_zero _
  neg_mem' {a} (ha : d.d a = 0) := by
    change d.d (-a) = 0
    rw [map_neg, ha, neg_zero]

@[simp]
lemma mem_kerSubring {X : Dᵒᵖ} (r : R.obj X) : r ∈ d.kerSubring X ↔ d.d r = 0 := Iff.rfl

end Derivation

namespace DifferentialsConstruction

variable (φ)

/-- The restrictions to `X` of the images under `φ` of sections of `S`. -/
def imageGenerators (X : Dᵒᵖ) : Set (R.obj X) :=
  {r | ∃ (Y : C) (g : op (F.obj Y) ⟶ X) (a : S.obj (op Y)), R.map g (φ.app (op Y) a) = r}

/-- The subring of `R.obj X` generated by the restrictions of the images under `φ` of sections
of `S`; it is the image of `(F⁻¹ S)(X) → R(X)`. -/
def imageSubring (X : Dᵒᵖ) : Subring (R.obj X) :=
  Subring.closure (imageGenerators φ X)

lemma map_mem_imageSubring {X X' : Dᵒᵖ} (h : X ⟶ X') {r : R.obj X}
    (hr : r ∈ imageSubring φ X) : R.map h r ∈ imageSubring φ X' := by
  suffices imageSubring φ X ≤ (imageSubring φ X').comap (R.map h).hom from this hr
  refine Subring.closure_le.mpr ?_
  rintro _ ⟨Y, g, a, rfl⟩
  refine Subring.subset_closure ⟨Y, g ≫ h, a, ?_⟩
  simp

/-- The presheaf of subrings `imageSubring φ` of `R`. -/
@[simps]
noncomputable def imagePresheaf : Dᵒᵖ ⥤ CommRingCat.{u} where
  obj X := CommRingCat.of (imageSubring φ X)
  map h := CommRingCat.ofHom <| (R.map h).hom.restrict _ _ fun _ hr ↦ map_mem_imageSubring φ h hr
  map_id X := by
    ext x
    change R.map (𝟙 X) x.1 = x.1
    simp
  map_comp f g := by
    ext x
    change R.map (f ≫ g) x.1 = R.map g (R.map f x.1)
    simp

/-- The inclusion of `imagePresheaf φ` in `R`. -/
@[simps]
noncomputable def imagePresheafι : imagePresheaf φ ⟶ R where
  app X := CommRingCat.ofHom (imageSubring φ X).subtype

variable {φ}

/-- A derivation vanishing on `φ` vanishes on `imagePresheaf φ`. -/
lemma Derivation.imageSubring_le_kerSubring (d : M.Derivation φ) (X : Dᵒᵖ) :
    imageSubring φ X ≤ d.kerSubring X := by
  refine Subring.closure_le.mpr ?_
  rintro _ ⟨Y, g, a, rfl⟩
  change d.d _ = 0
  rw [Derivation.d_map, d.d_app, map_zero]
  rfl

/-- The `φ`-derivations are the derivations relative to `imagePresheafι φ`. -/
@[simps]
def derivationEquiv : M.Derivation φ ≃ M.Derivation' (imagePresheafι φ) where
  toFun d :=
    { d := d.d
      d_mul := d.d_mul
      d_map := d.d_map
      d_app := fun {X} a ↦ Derivation.imageSubring_le_kerSubring d X a.2 }
  invFun d :=
    { d := d.d
      d_mul := d.d_mul
      d_map := d.d_map
      d_app := fun {Y} a ↦ d.d_app (X := op (F.obj Y.unop))
        ⟨_, Subring.subset_closure ⟨Y.unop, 𝟙 _, a, by simp⟩⟩ }

@[simp]
lemma derivationEquiv_postcomp {N : PresheafOfModules.{v} (R ⋙ forget₂ _ _)}
    (d : M.Derivation φ) (α : M ⟶ N) :
    derivationEquiv (d.postcomp α) = (derivationEquiv d).postcomp α := rfl

@[simp]
lemma derivationEquiv_symm_postcomp {N : PresheafOfModules.{v} (R ⋙ forget₂ _ _)}
    (d : M.Derivation' (imagePresheafι φ)) (α : M ⟶ N) :
    derivationEquiv.symm (d.postcomp α) = (derivationEquiv.symm d).postcomp α := rfl

/-- A derivation is universal for `φ` if and only if it is universal for `imagePresheafι φ`. -/
def universalEquiv (d : M.Derivation φ) : d.Universal ≃ (derivationEquiv d).Universal where
  toFun h :=
    { desc := fun d' ↦ h.desc (derivationEquiv.symm d')
      fac := fun d' ↦ by
        rw [← derivationEquiv_postcomp, h.fac, Equiv.apply_symm_apply]
      postcomp_injective := fun α β hαβ ↦ h.postcomp_injective α β
        (derivationEquiv.injective (by simpa using hαβ)) }
  invFun h :=
    { desc := fun d' ↦ h.desc (derivationEquiv d')
      fac := fun d' ↦ derivationEquiv.injective (by rw [derivationEquiv_postcomp, h.fac])
      postcomp_injective := fun α β hαβ ↦ h.postcomp_injective α β
        (by rw [← derivationEquiv_postcomp, ← derivationEquiv_postcomp, hαβ]) }
  left_inv _ := Subsingleton.elim _ _
  right_inv _ := Subsingleton.elim _ _

variable (φ)

/-- The presheaf of relative differentials of `φ : S ⟶ F.op ⋙ R`. -/
noncomputable def relativeDifferentials : PresheafOfModules.{u} (R ⋙ forget₂ _ _) :=
  relativeDifferentials' (imagePresheafι φ)

/-- The universal `φ`-derivation. -/
noncomputable def derivation : (relativeDifferentials φ).Derivation φ :=
  derivationEquiv.symm (derivation' (imagePresheafι φ))

/-- The derivation `derivation φ` is universal. -/
noncomputable def isUniversal : (derivation φ).Universal :=
  (universalEquiv (derivation φ)).symm (isUniversal' (imagePresheafι φ))

instance : HasDifferentials φ := ⟨_, _, ⟨isUniversal φ⟩⟩

end DifferentialsConstruction

end PresheafOfModules
