/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import Mathlib.FieldTheory.Galois.IsGaloisGroup
import Mathlib.GroupTheory.Index
import Mathlib.RingTheory.Invariant.Basic
import SGA.Foundations.Patching.Modules

/-!
# Patching of Galois algebras

Let `R` be a commutative ring and `A₁, A₂ ⊆ R` subrings with the factorization property
(`Subring.HasGLFactorization`, see `SGA.Foundations.Patching.Modules`). Let `W` be a commutative
`R`-algebra on which a group `G` acts through `σ : G →* (W ≃ₐ[R] W)`, and let `Vᵢ ⊆ W` be a
`σ`-stable `Aᵢ`-subalgebra which is an `Aᵢ`-form of `W` (the `Aᵢ`-span of an `R`-basis of `W`).
The patched algebra `GaloisPatching.patch V₁ V₂ = V₁ ∩ V₂` is then an `(A₁ ∩ A₂)`-form of `W`,
compatible with both `Vᵢ` (`GaloisPatching.exists_basis_patch`: one basis is an `(A₁ ∩ A₂)`-basis
of the patched algebra and an `Aᵢ`-basis of `Vᵢ`). If `G` acts faithfully on `W` and the
invariants of `Vᵢ` are `Aᵢ`, then `G` is a Galois group of the patched algebra over `A₁ ∩ A₂`
(`GaloisPatching.isGaloisGroup_patch`). The data need not be split: `W` is an arbitrary
`G`-algebra over `R`, for instance the base change of a non-split Galois algebra.

The split case is Galois patching (Harbater; Harbater–Hartmann, *Patching over fields*,
Israel J. Math. 176 (2010); Jarden, *Algebraic patching*, Springer 2011). Let `F₁, F₂` be
subfields of a field `F₀`, `G` a finite group generated by subgroups `H₁, H₂`, and `Eᵢ ⊆ F₀` a
finite Galois extension of `Fᵢ` with group `Hᵢ`. In `W = (G → F₀)`, on which `G` acts by right
translations (`GaloisPatching.rightTranslation`), take for `Vᵢ` the induced algebra
`Ind_{Hᵢ}^G Eᵢ` (`GaloisPatching.induced`), an `Fᵢ`-form of `W`
(`GaloisPatching.exists_basis_span_induced`). The patched algebra `GaloisPatching.patched` is a
field (`GaloisPatching.isField_patched`), `G` is a Galois group of it over `F₁ ∩ F₂`
(`GaloisPatching.isGaloisGroup_patched`), and it induces the given local data: an
`(F₁ ∩ F₂)`-basis of it is an `Fᵢ`-basis of `Ind_{Hᵢ}^G Eᵢ`
(`GaloisPatching.exists_basis_patched`), that is, `E ⊗_{F₁ ∩ F₂} Fᵢ ≅ Ind_{Hᵢ}^G Eᵢ`
compatibly with `G`. `Subfield.exists_isGaloisGroup_of_hasGLFactorization` is the existential
form ("`G` is a Galois group over `F₁ ∩ F₂`, split case").
-/

universe u v

open Matrix

namespace GaloisPatching

section General

variable {R W : Type*} [CommRing R] [CommRing W] [Algebra R W] {A₁ A₂ : Subring R}

/-- The patched algebra of an `A₁`-subalgebra `V₁` and an `A₂`-subalgebra `V₂` of `W`: their
intersection, an algebra over `A₁ ∩ A₂`. -/
def patch (V₁ : Subalgebra A₁ W) (V₂ : Subalgebra A₂ W) : Subalgebra ↥(A₁ ⊓ A₂) W where
  carrier := (V₁ : Set W) ∩ V₂
  mul_mem' h h' := ⟨V₁.mul_mem h.1 h'.1, V₂.mul_mem h.2 h'.2⟩
  add_mem' h h' := ⟨V₁.add_mem h.1 h'.1, V₂.add_mem h.2 h'.2⟩
  algebraMap_mem' c :=
    ⟨V₁.algebraMap_mem (⟨c, (Subring.mem_inf.mp c.2).1⟩ : A₁),
      V₂.algebraMap_mem (⟨c, (Subring.mem_inf.mp c.2).2⟩ : A₂)⟩

variable {V₁ : Subalgebra A₁ W} {V₂ : Subalgebra A₂ W}

lemma mem_patch_iff {v : W} : v ∈ patch V₁ V₂ ↔ v ∈ V₁ ∧ v ∈ V₂ :=
  Iff.rfl

variable {G : Type*} [Group G] (σ : G →* (W ≃ₐ[R] W))

/-- `G` acts on the patched algebra of two `σ`-stable subalgebras through `σ`. -/
@[instance_reducible]
def patchAction (hV₁ : ∀ g, ∀ v ∈ V₁, σ g v ∈ V₁) (hV₂ : ∀ g, ∀ v ∈ V₂, σ g v ∈ V₂) :
    MulSemiringAction G (patch V₁ V₂) where
  smul g v := ⟨σ g v.1, hV₁ g v.1 (mem_patch_iff.mp v.2).1, hV₂ g v.1 (mem_patch_iff.mp v.2).2⟩
  one_smul v := Subtype.ext (by change σ 1 v.1 = v.1; simp)
  mul_smul g g' v := Subtype.ext (by change σ (g * g') v.1 = σ g (σ g' v.1); simp)
  smul_zero g := Subtype.ext (map_zero (σ g))
  smul_add g v w := Subtype.ext (map_add (σ g) v.1 w.1)
  smul_one g := Subtype.ext (map_one (σ g))
  smul_mul g v w := Subtype.ext (map_mul (σ g) v.1 w.1)

variable {σ} (hV₁ : ∀ g, ∀ v ∈ V₁, σ g v ∈ V₁) (hV₂ : ∀ g, ∀ v ∈ V₂, σ g v ∈ V₂)

lemma coe_patchAction_smul (g : G) (v : patch V₁ V₂) :
    let := patchAction σ hV₁ hV₂
    ((g • v : patch V₁ V₂) : W) = σ g v :=
  rfl

lemma smulCommClass_patch :
    let := patchAction σ hV₁ hV₂
    SMulCommClass G ↥(A₁ ⊓ A₂) (patch V₁ V₂) := by
  let := patchAction σ hV₁ hV₂
  exact ⟨fun g c v ↦ Subtype.ext (map_smul (σ g) (c : R) (v : W))⟩

/-- The invariants of the patched algebra are `A₁ ∩ A₂` if those of `Vᵢ` are `Aᵢ`. -/
lemma isInvariant_patch (hinj : Function.Injective (algebraMap R W))
    (hinv₁ : ∀ v ∈ V₁, (∀ g, σ g v = v) → ∃ a ∈ A₁, algebraMap R W a = v)
    (hinv₂ : ∀ v ∈ V₂, (∀ g, σ g v = v) → ∃ a ∈ A₂, algebraMap R W a = v) :
    let := patchAction σ hV₁ hV₂
    Algebra.IsInvariant ↥(A₁ ⊓ A₂) (patch V₁ V₂) G := by
  let := patchAction σ hV₁ hV₂
  refine ⟨fun v hv ↦ ?_⟩
  have hfix : ∀ g, σ g v = v := fun g ↦ congrArg Subtype.val (hv g)
  obtain ⟨a₁, ha₁, h₁⟩ := hinv₁ v (mem_patch_iff.mp v.2).1 hfix
  obtain ⟨a₂, ha₂, h₂⟩ := hinv₂ v (mem_patch_iff.mp v.2).2 hfix
  obtain rfl : a₁ = a₂ := hinj (h₁.trans h₂.symm)
  exact ⟨⟨a₁, Subring.mem_inf.mpr ⟨ha₁, ha₂⟩⟩, Subtype.ext h₁⟩

/-- `G` acts faithfully on the patched algebra if it spans `W` and `G` acts faithfully on `W`. -/
lemma faithfulSMul_patch (hspan : Submodule.span R (patch V₁ V₂ : Set W) = ⊤)
    (hfaith : ∀ g, (∀ w, σ g w = w) → g = 1) :
    let := patchAction σ hV₁ hV₂
    FaithfulSMul G (patch V₁ V₂) := by
  let := patchAction σ hV₁ hV₂
  refine ⟨fun {g₁ g₂} h ↦ ?_⟩
  have heq : Set.EqOn (σ g₁).toLinearMap (σ g₂).toLinearMap (patch V₁ V₂ : Set W) :=
    fun v hv ↦ congrArg Subtype.val (h ⟨v, hv⟩)
  have hall : ∀ w, σ g₁ w = σ g₂ w := fun w ↦
    LinearMap.eqOn_span heq (hspan ▸ Submodule.mem_top : w ∈ Submodule.span R _)
  have := hfaith (g₂⁻¹ * g₁) fun w ↦ by
    rw [map_mul, AlgEquiv.mul_apply, hall, ← AlgEquiv.mul_apply, ← map_mul, inv_mul_cancel,
      map_one, AlgEquiv.one_apply]
  exact (inv_mul_eq_one.mp this).symm

variable {ι : Type*} [Fintype ι] [DecidableEq ι]

/-- **Patching of algebras, compatibility**: if `Vᵢ` is an `Aᵢ`-form of `W` (the `Aᵢ`-span of an
`R`-basis `bᵢ`) and `A₁, A₂` have the factorization property, one `R`-basis `b` of `W` spans `V₁`
over `A₁`, `V₂` over `A₂` and the patched algebra over `A₁ ∩ A₂`. So the patched algebra is a free
`(A₁ ∩ A₂)`-module whose base change to `Aᵢ` is `Vᵢ`. -/
theorem exists_basis_patch (h : A₁.HasGLFactorization A₂ ι) {b₁ b₂ : Module.Basis ι R W}
    (hb₁ : Subalgebra.toSubmodule V₁ = Submodule.span A₁ (Set.range b₁))
    (hb₂ : Subalgebra.toSubmodule V₂ = Submodule.span A₂ (Set.range b₂)) :
    ∃ b : Module.Basis ι R W, Subalgebra.toSubmodule V₁ = Submodule.span A₁ (Set.range b) ∧
      Subalgebra.toSubmodule V₂ = Submodule.span A₂ (Set.range b) ∧
      Subalgebra.toSubmodule (patch V₁ V₂) = Submodule.span ↥(A₁ ⊓ A₂) (Set.range b) := by
  obtain ⟨b, h₁, h₂, h₁₂⟩ := Subring.exists_basis_span_eq h b₁ b₂
  refine ⟨b, hb₁.trans h₁.symm, hb₂.trans h₂.symm, SetLike.coe_injective ?_⟩
  rw [← h₁₂, ← hb₁, ← hb₂]
  rfl

/-- **Patching of `G`-algebras**: if `Vᵢ` is a `σ`-stable `Aᵢ`-form of `W` with invariants
`Aᵢ`, `A₁, A₂` have the factorization property, `R → W` is injective and `G` acts faithfully on
`W`, then `G` is a Galois group of the patched algebra over `A₁ ∩ A₂` in the sense of mathlib's
`IsGaloisGroup`: `G` acts faithfully, `A₁ ∩ A₂`-linearly, with invariants `A₁ ∩ A₂`.

This is weaker than "Galois algebra" (Chase–Harrison–Rosenberg: for the patched algebra `E` over
`A₁ ∩ A₂`, `E` étale and `E ⊗ E ≅ ∏_G E`) in general. If `A₁ ∩ A₂` is a field, `W` has rank `|G|`
over `R` and `W` is étale over `R` (e.g. a Galois `R`-algebra), then `E` has rank `|G|`
(`exists_basis_patch`), `E ⊗ R ≅ W` is étale so `E` is étale over the field `A₁ ∩ A₂`, and Artin's
theorem on each factor shows that `E` is `G`-Galois. Without étaleness this fails: for
`R = A₁ = A₂ = ℚ`, `W = ℚ[x]/(x²)` and `G = ℤ/2` acting by `x ↦ -x`, the action is faithful with
invariants `ℚ` and `W` has rank `2`, but `W` is not étale. -/
theorem isGaloisGroup_patch (h : A₁.HasGLFactorization A₂ ι) {b₁ b₂ : Module.Basis ι R W}
    (hb₁ : Subalgebra.toSubmodule V₁ = Submodule.span A₁ (Set.range b₁))
    (hb₂ : Subalgebra.toSubmodule V₂ = Submodule.span A₂ (Set.range b₂))
    (hinj : Function.Injective (algebraMap R W))
    (hinv₁ : ∀ v ∈ V₁, (∀ g, σ g v = v) → ∃ a ∈ A₁, algebraMap R W a = v)
    (hinv₂ : ∀ v ∈ V₂, (∀ g, σ g v = v) → ∃ a ∈ A₂, algebraMap R W a = v)
    (hfaith : ∀ g, (∀ w, σ g w = w) → g = 1) :
    let := patchAction σ hV₁ hV₂
    IsGaloisGroup G ↥(A₁ ⊓ A₂) (patch V₁ V₂) := by
  let := patchAction σ hV₁ hV₂
  obtain ⟨b, -, -, hb⟩ := exists_basis_patch h hb₁ hb₂
  have hmem : ∀ j, b j ∈ patch V₁ V₂ := fun j ↦ by
    change b j ∈ Subalgebra.toSubmodule (patch V₁ V₂)
    rw [hb]
    exact Submodule.subset_span ⟨j, rfl⟩
  have hspan : Submodule.span R (patch V₁ V₂ : Set W) = ⊤ := by
    rw [eq_top_iff, ← b.span_eq]
    exact Submodule.span_mono (Set.range_subset_iff.mpr hmem)
  exact ⟨faithfulSMul_patch hV₁ hV₂ hspan hfaith, smulCommClass_patch hV₁ hV₂,
    isInvariant_patch hV₁ hV₂ hinj hinv₁ hinv₂⟩

end General

section Split

variable {F₀ : Type u} [Field F₀] {G : Type v} [Group G]

variable (F₀ G) in
/-- Right translations: `G` acts on `G → F₀` by `(g • φ) x = φ (x * g)`. -/
def rightTranslation : G →* ((G → F₀) ≃ₐ[F₀] (G → F₀)) where
  toFun g :=
    { toFun := fun φ x ↦ φ (x * g)
      invFun := fun φ x ↦ φ (x * g⁻¹)
      left_inv := fun φ ↦ funext fun x ↦ by simp
      right_inv := fun φ ↦ funext fun x ↦ by simp
      map_mul' := fun _ _ ↦ rfl
      map_add' := fun _ _ ↦ rfl
      commutes' := fun _ ↦ rfl }
  map_one' := AlgEquiv.ext fun φ ↦ funext fun x ↦ by simp
  map_mul' g g' := AlgEquiv.ext fun φ ↦ funext fun x ↦ by
    change φ (x * (g * g')) = φ (x * g * g')
    rw [mul_assoc]

lemma rightTranslation_apply (g : G) (φ : G → F₀) (x : G) :
    rightTranslation F₀ G g φ x = φ (x * g) :=
  rfl

/-- `G` acts faithfully on `G → F₀` by right translations. -/
lemma eq_one_of_rightTranslation (g : G) (hg : ∀ φ, rightTranslation F₀ G g φ = φ) : g = 1 := by
  classical
  have := congrFun (hg (Pi.single 1 1)) 1
  rw [rightTranslation_apply, one_mul, Pi.single_eq_same] at this
  by_contra hne
  rw [Pi.single_eq_of_ne hne] at this
  exact zero_ne_one this

/-- The induced algebra `Ind_H^G E` inside `G → F₀`: for a subfield `F₁ ⊆ F₀`, an intermediate
field `E` of `F₀/F₁` and an action `ρ : H → Gal(E/F₁)` of a subgroup `H ≤ G`, the functions
`φ : G → F₀` with values in `E` such that `φ (h g) = ρ(h) (φ g)` for `h ∈ H`. -/
def induced (F₁ : Subfield F₀) (E : IntermediateField F₁ F₀) (H : Subgroup G)
    (ρ : H →* (E ≃ₐ[F₁] E)) : Subalgebra F₁.toSubring (G → F₀) where
  carrier := {φ | ∀ g, ∃ e : E, φ g = e ∧ ∀ h : H, φ (h * g) = ρ h e}
  mul_mem' {φ ψ} hφ hψ g := by
    obtain ⟨e, he, he'⟩ := hφ g
    obtain ⟨e', hf, hf'⟩ := hψ g
    exact ⟨e * e', by simp [he, hf], fun h ↦ by simp [he', hf']⟩
  add_mem' {φ ψ} hφ hψ g := by
    obtain ⟨e, he, he'⟩ := hφ g
    obtain ⟨e', hf, hf'⟩ := hψ g
    exact ⟨e + e', by simp [he, hf], fun h ↦ by simp [he', hf']⟩
  algebraMap_mem' c g := ⟨algebraMap F₁ E ⟨c, c.2⟩, rfl, fun h ↦ by
    rw [AlgEquiv.commutes]
    rfl⟩

variable {F₁ : Subfield F₀} {E : IntermediateField F₁ F₀} {H : Subgroup G}
  {ρ : H →* (E ≃ₐ[F₁] E)}

lemma mem_induced_iff {φ : G → F₀} :
    φ ∈ induced F₁ E H ρ ↔ ∀ g, ∃ e : E, φ g = e ∧ ∀ h : H, φ (h * g) = ρ h e :=
  Iff.rfl

/-- The induced algebra is stable under right translations. -/
lemma comp_mul_right_mem_induced {φ : G → F₀} (hφ : φ ∈ induced F₁ E H ρ) (g₀ : G) :
    (fun x ↦ φ (x * g₀)) ∈ induced F₁ E H ρ := fun g ↦ by
  obtain ⟨e, he, he'⟩ := hφ (g * g₀)
  exact ⟨e, he, fun h ↦ by
    change φ (h * g * g₀) = _
    rw [mul_assoc, he']⟩

/-- The zero set of an element of the induced algebra is stable under left multiplication by
`H`. -/
lemma eq_zero_iff_of_mem_induced {φ : G → F₀} (hφ : φ ∈ induced F₁ E H ρ) (h : H) (g : G) :
    φ (h * g) = 0 ↔ φ g = 0 := by
  obtain ⟨e, he, he'⟩ := hφ g
  rw [he', he]
  simp

/-- The invariants of the induced algebra under right translations are the constants in `F₁`, if
`E^H = F₁`. -/
lemma exists_eq_algebraMap_of_mem_induced (hfix : ∀ e : E, (∀ h, ρ h e = e) → (e : F₀) ∈ F₁)
    {φ : G → F₀} (hφ : φ ∈ induced F₁ E H ρ) (hinv : ∀ g, rightTranslation F₀ G g φ = φ) :
    ∃ a ∈ F₁.toSubring, algebraMap F₀ (G → F₀) a = φ := by
  have hconst : ∀ g, φ g = φ 1 := fun g ↦ by
    have := congrFun (hinv g) 1
    rwa [rightTranslation_apply, one_mul] at this
  obtain ⟨e, he, he'⟩ := hφ 1
  refine ⟨φ 1, ?_, funext fun g ↦ (hconst g).symm⟩
  rw [he]
  refine hfix e fun h ↦ Subtype.ext ?_
  rw [← he' h, mul_one, hconst, he]

open Classical in
/-- The function `G → F₀` supported on the right coset `H g₀`, with `h g₀ ↦ ρ(h) e`. -/
noncomputable def cosetFun (ρ : H →* (E ≃ₐ[F₁] E)) (g₀ : G) (e : E) : G → F₀ :=
  fun g ↦ if hg : g * g₀⁻¹ ∈ H then (ρ ⟨g * g₀⁻¹, hg⟩ e : F₀) else 0

lemma cosetFun_mem_induced (g₀ : G) (e : E) : cosetFun ρ g₀ e ∈ induced F₁ E H ρ := by
  intro g
  by_cases hg : g * g₀⁻¹ ∈ H
  · refine ⟨ρ ⟨g * g₀⁻¹, hg⟩ e, by simp [cosetFun, hg], fun h ↦ ?_⟩
    have hhg : h * g * g₀⁻¹ ∈ H := by
      rw [mul_assoc]
      exact H.mul_mem h.2 hg
    simp only [cosetFun, hhg, ↓reduceDIte]
    rw [← AlgEquiv.mul_apply, ← map_mul]
    congr 3
    ext
    simp [mul_assoc]
  · refine ⟨0, by simp [cosetFun, hg], fun h ↦ ?_⟩
    have hhg : h * g * g₀⁻¹ ∉ H := fun hh ↦ hg (by
      have := H.mul_mem (H.inv_mem h.2) hh
      rwa [mul_assoc, ← mul_assoc (h : G)⁻¹, inv_mul_cancel, one_mul] at this)
    simp [cosetFun, hhg]

lemma cosetFun_add (g₀ : G) (e e' : E) :
    cosetFun ρ g₀ (e + e') = cosetFun ρ g₀ e + cosetFun ρ g₀ e' := by
  ext g
  by_cases hg : g * g₀⁻¹ ∈ H <;> simp [cosetFun, hg]

lemma cosetFun_smul (g₀ : G) (c : F₁) (e : E) :
    cosetFun ρ g₀ (c • e) = (c : F₀) • cosetFun ρ g₀ e := by
  ext g
  by_cases hg : g * g₀⁻¹ ∈ H
  · simp only [cosetFun, hg, ↓reduceDIte, map_smul, Pi.smul_apply, smul_eq_mul]
    rfl
  · simp [cosetFun, hg]

/-- An element of the induced algebra is the sum, over representatives `g₀` of the right cosets
of `H`, of the functions supported on `H g₀` with the same value at `g₀`. -/
lemma eq_sum_cosetFun [Finite G] {φ : G → F₀} (hφ : φ ∈ induced F₁ E H ρ) :
    ∃ e : Quotient (QuotientGroup.rightRel H) → E, (∀ q, φ q.out = e q) ∧
      ∃ _ : Fintype (Quotient (QuotientGroup.rightRel H)), φ = ∑ q, cosetFun ρ q.out (e q) := by
  classical
  choose e he he' using fun q : Quotient (QuotientGroup.rightRel H) ↦ hφ q.out
  refine ⟨e, he, Fintype.ofFinite _, funext fun g ↦ ?_⟩
  rw [Finset.sum_apply, Finset.sum_eq_single (Quotient.mk _ g)]
  · have hg : g * (Quotient.mk (QuotientGroup.rightRel H) g).out⁻¹ ∈ H :=
      QuotientGroup.rightRel_apply.mp (Quotient.mk_out (s := QuotientGroup.rightRel H) g)
    simp only [cosetFun, hg, ↓reduceDIte]
    rw [← he']
    congr 1
    simp
  · intro q _ hq
    have hg : g * q.out⁻¹ ∉ H := fun hg ↦ hq (by
      rw [← Quotient.out_eq q]
      exact Quotient.sound (QuotientGroup.rightRel_apply.mpr hg))
    simp [cosetFun, hg]
  · simp

/-- If `ρ` is injective, the induced algebra spans `F₀^G` over `F₀` (Dedekind's independence of
characters). -/
lemma span_induced_eq_top [Finite G] (hρ : Function.Injective ρ) :
    Submodule.span F₀ (induced F₁ E H ρ : Set (G → F₀)) = ⊤ := by
  classical
  have : Fintype G := Fintype.ofFinite G
  set S := Submodule.span F₀ (induced F₁ E H ρ : Set (G → F₀))
  -- the characters `e ↦ ρ(h) e` of `E` with values in `F₀` are linearly independent
  let ψ : H → (E →* F₀) := fun h ↦ (E.val.toRingHom.comp (ρ h).toRingHom).toMonoidHom
  have hψ : Function.Injective ψ := fun h h' hh ↦ hρ <| AlgEquiv.ext fun e ↦ by
    apply Subtype.val_injective
    exact DFunLike.congr_fun hh e
  have hli : LinearIndependent F₀ (fun h ↦ (ψ h : E → F₀)) :=
    (linearIndependent_monoidHom E F₀).comp ψ hψ
  -- the vectors `(ρ(h) e)_h` span `F₀^H`
  have hspanH : Submodule.span F₀ (Set.range fun (e : E) (h : H) ↦ (ρ h e : F₀)) = ⊤ := by
    by_contra hne
    obtain ⟨f, hf0, hf⟩ := Submodule.exists_le_ker_of_lt_top _ (lt_top_iff_ne_top.mpr hne)
    apply hf0
    let c : H → F₀ := fun h ↦ f fun j ↦ if h = j then 1 else 0
    have hc : ∀ e : E, ∑ h : H, c h * ψ h e = 0 := by
      intro e
      have hmem := hf (Submodule.subset_span ⟨e, rfl⟩)
      rw [LinearMap.mem_ker, LinearMap.pi_apply_eq_sum_univ] at hmem
      rw [← hmem]
      refine Finset.sum_congr rfl fun h _ ↦ ?_
      rw [smul_eq_mul, mul_comm]
      rfl
    have hc0 := Fintype.linearIndependent_iff.mp hli c
      (funext fun e ↦ by simpa [Finset.sum_apply] using hc e)
    refine LinearMap.ext fun v ↦ ?_
    rw [LinearMap.pi_apply_eq_sum_univ f v]
    simp only [LinearMap.zero_apply]
    exact Finset.sum_eq_zero fun h _ ↦ by rw [show f _ = c h from rfl, hc0 h, smul_zero]
  rw [eq_top_iff]
  intro v _
  rw [pi_eq_sum_univ v]
  refine Submodule.sum_mem _ fun g₀ _ ↦ Submodule.smul_mem _ _ ?_
  -- `Φ : F₀^H → F₀^G` extends by zero along `h ↦ h g₀`
  let Φ : (H → F₀) →ₗ[F₀] (G → F₀) :=
    { toFun := fun c g ↦ if hg : g * g₀⁻¹ ∈ H then c ⟨g * g₀⁻¹, hg⟩ else 0
      map_add' := fun c c' ↦ funext fun g ↦ by by_cases hg : g * g₀⁻¹ ∈ H <;> simp [hg]
      map_smul' := fun a c ↦ funext fun g ↦ by by_cases hg : g * g₀⁻¹ ∈ H <;> simp [hg] }
  have hΦ : ∀ e : E, Φ (fun h ↦ (ρ h e : F₀)) ∈ induced F₁ E H ρ := fun e ↦
    cosetFun_mem_induced g₀ e
  have hT : Submodule.span F₀ (Set.range fun (e : E) (h : H) ↦ (ρ h e : F₀)) ≤ S.comap Φ :=
    Submodule.span_le.mpr fun _ ⟨e, he⟩ ↦ he ▸ Submodule.subset_span (hΦ e)
  rw [hspanH, top_le_iff] at hT
  have := (Submodule.eq_top_iff'.mp hT) (Pi.single 1 1)
  rw [Submodule.mem_comap] at this
  convert this using 1
  ext g
  by_cases hg : g * g₀⁻¹ ∈ H
  · simp only [Φ, LinearMap.coe_mk, AddHom.coe_mk, hg, ↓reduceDIte]
    by_cases hgg : g = g₀
    · subst hgg
      simp only [mul_inv_cancel, ite_true]
      exact (Pi.single_eq_same (M := fun _ : H ↦ F₀) (1 : H) 1).symm
    · have : (⟨g * g₀⁻¹, hg⟩ : H) ≠ 1 := fun h1 ↦ hgg (by
        have := congrArg Subtype.val h1
        simpa [mul_inv_eq_one] using this)
      simp [Ne.symm hgg, this]
  · have hgg : g₀ ≠ g := fun h ↦ hg (by simp [h, H.one_mem])
    simp [Φ, hg, hgg]

/-- **The induced algebra is a form**: if `E/F₁` is a finite Galois extension with group `H`
(through `ρ`), the induced algebra `Ind_H^G E` is the `F₁`-span of an `F₀`-basis of `F₀^G`. -/
theorem exists_basis_span_induced [Finite G] [FiniteDimensional F₁ E] [IsGalois F₁ E]
    (ρ : H ≃* (E ≃ₐ[F₁] E)) :
    ∃ b : Module.Basis G F₀ (G → F₀),
      Subalgebra.toSubmodule (induced F₁ E H ρ.toMonoidHom) =
        Submodule.span F₁.toSubring (Set.range b) := by
  classical
  have : Fintype G := Fintype.ofFinite G
  have : Fintype (Quotient (QuotientGroup.rightRel H)) := Fintype.ofFinite _
  let eb := Module.finBasis F₁ E
  let ι := Quotient (QuotientGroup.rightRel H) × Fin (Module.finrank F₁ E)
  let f : ι → G → F₀ := fun qa ↦ cosetFun ρ.toMonoidHom qa.1.out (eb qa.2)
  have hfmem : ∀ qa, f qa ∈ induced F₁ E H ρ.toMonoidHom := fun qa ↦ cosetFun_mem_induced _ _
  -- every element of the induced algebra is an `F₁`-combination of the `f qa`
  have hle : (induced F₁ E H ρ.toMonoidHom : Set (G → F₀)) ⊆
      Submodule.span F₁.toSubring (Set.range f) := by
    intro φ hφ
    obtain ⟨e, -, _, rfl⟩ := eq_sum_cosetFun hφ
    refine Submodule.sum_mem _ fun q _ ↦ ?_
    rw [← eb.sum_repr (e q)]
    have hsum : ∀ s : Finset (Fin (Module.finrank F₁ E)),
        cosetFun ρ.toMonoidHom q.out (∑ a ∈ s, eb.repr (e q) a • eb a) ∈
          Submodule.span F₁.toSubring (Set.range f) := by
      intro s
      induction s using Finset.induction_on with
      | empty =>
        rw [Finset.sum_empty]
        have : cosetFun ρ.toMonoidHom q.out (0 : E) = 0 := by
          ext g
          by_cases hg : g * q.out⁻¹ ∈ H <;> simp [cosetFun, hg]
        rw [this]
        exact Submodule.zero_mem _
      | insert a s has ih =>
        rw [Finset.sum_insert has, cosetFun_add, cosetFun_smul]
        refine Submodule.add_mem _ ?_ ih
        exact Submodule.smul_mem _ (⟨_, (eb.repr (e q) a).2⟩ : F₁.toSubring)
          (Submodule.subset_span ⟨(q, a), rfl⟩)
    exact hsum Finset.univ
  -- the `f qa` span `F₀^G` over `F₀`, and there are `|G|` of them
  have htop : ⊤ ≤ Submodule.span F₀ (Set.range f) := by
    rw [← span_induced_eq_top (F₁ := F₁) (E := E) (ρ := ρ.toMonoidHom) ρ.injective]
    refine Submodule.span_le.mpr fun φ hφ ↦ ?_
    have := hle hφ
    rw [← Submodule.span_span_of_tower F₁.toSubring F₀]
    exact Submodule.subset_span this
  have hcard : Fintype.card ι = Module.finrank F₀ (G → F₀) := by
    rw [Module.finrank_fintype_fun_eq_card, Fintype.card_prod, Fintype.card_fin,
      ← IsGalois.card_aut_eq_finrank, ← Nat.card_congr ρ.toEquiv, ← Nat.card_eq_fintype_card,
      ← Nat.card_eq_fintype_card,
      Nat.card_congr (QuotientGroup.quotientRightRelEquivQuotientLeftRel H),
      ← Subgroup.index_eq_card, mul_comm, Subgroup.card_mul_index]
  let b₀ := basisOfTopLeSpanOfCardEqFinrank f htop hcard
  have hcardG : Fintype.card ι = Fintype.card G := by
    rw [hcard, Module.finrank_fintype_fun_eq_card]
  refine ⟨b₀.reindex (Fintype.equivOfCardEq hcardG), ?_⟩
  rw [Module.Basis.range_reindex, coe_basisOfTopLeSpanOfCardEqFinrank]
  refine le_antisymm (fun φ hφ ↦ hle hφ) (Submodule.span_le.mpr ?_)
  rintro _ ⟨qa, rfl⟩
  exact hfmem qa

section Patched

variable {F₁ F₂ : Subfield F₀} {E₁ : IntermediateField F₁ F₀} {E₂ : IntermediateField F₂ F₀}
  {H₁ H₂ : Subgroup G}

/-- The patched algebra of `Ind_{H₁}^G E₁` and `Ind_{H₂}^G E₂`: the functions `G → F₀` lying in
both induced algebras, an algebra over `F₁ ∩ F₂`. -/
abbrev patched (ρ₁ : H₁ →* (E₁ ≃ₐ[F₁] E₁)) (ρ₂ : H₂ →* (E₂ ≃ₐ[F₂] E₂)) :
    Subalgebra ↥(F₁.toSubring ⊓ F₂.toSubring) (G → F₀) :=
  patch (induced F₁ E₁ H₁ ρ₁) (induced F₂ E₂ H₂ ρ₂)

variable {ρ₁ : H₁ →* (E₁ ≃ₐ[F₁] E₁)} {ρ₂ : H₂ →* (E₂ ≃ₐ[F₂] E₂)}

lemma mem_patched_iff {φ : G → F₀} :
    φ ∈ patched ρ₁ ρ₂ ↔ φ ∈ induced F₁ E₁ H₁ ρ₁ ∧ φ ∈ induced F₂ E₂ H₂ ρ₂ :=
  Iff.rfl

/-- If `H₁` and `H₂` generate `G`, an element of the patched algebra vanishes nowhere unless it
is zero. -/
lemma eq_zero_or_forall_ne_zero (hH : H₁ ⊔ H₂ = ⊤) {φ : G → F₀} (hφ : φ ∈ patched ρ₁ ρ₂) :
    φ = 0 ∨ ∀ g, φ g ≠ 0 := by
  let K : Subgroup G :=
    { carrier := {x | ∀ g, φ (x * g) = 0 ↔ φ g = 0}
      one_mem' := fun g ↦ by rw [one_mul]
      mul_mem' := fun {x y} hx hy g ↦ by rw [mul_assoc, hx, hy]
      inv_mem' := fun {x} hx g ↦ by rw [← hx, mul_inv_cancel_left] }
  have h₁ : H₁ ≤ K := fun h hh g ↦
    eq_zero_iff_of_mem_induced (mem_patched_iff.mp hφ).1 ⟨h, hh⟩ g
  have h₂ : H₂ ≤ K := fun h hh g ↦
    eq_zero_iff_of_mem_induced (mem_patched_iff.mp hφ).2 ⟨h, hh⟩ g
  have hK : ∀ x, φ x = 0 ↔ φ 1 = 0 := fun x ↦ by
    have hx : x ∈ K := (hH ▸ sup_le h₁ h₂ : ⊤ ≤ K) (Subgroup.mem_top x)
    simpa using hx 1
  by_cases h1 : φ 1 = 0
  · exact Or.inl (funext fun x ↦ (hK x).mpr h1)
  · exact Or.inr fun x hx ↦ h1 ((hK x).mp hx)

/-- If `H₁` and `H₂` generate `G`, the patched algebra is a domain. -/
lemma isDomain_patched (hH : H₁ ⊔ H₂ = ⊤) : IsDomain (patched ρ₁ ρ₂) := by
  have : NoZeroDivisors (patched ρ₁ ρ₂) := ⟨fun {a b} hab ↦ by
    rcases eq_zero_or_forall_ne_zero hH a.2 with ha | ha
    · exact Or.inl (Subtype.ext ha)
    · refine Or.inr (Subtype.ext (funext fun g ↦ ?_))
      have := congrFun (congrArg Subtype.val hab) g
      exact (mul_eq_zero.mp this).resolve_left (ha g)⟩
  exact NoZeroDivisors.to_isDomain _

/-- `G` acts on the patched algebra by right translations. -/
noncomputable instance : MulSemiringAction G (patched ρ₁ ρ₂) :=
  patchAction (rightTranslation F₀ G) (fun g _ hφ ↦ comp_mul_right_mem_induced hφ g)
    (fun g _ hφ ↦ comp_mul_right_mem_induced hφ g)

lemma coe_smul_apply (g : G) (φ : patched ρ₁ ρ₂) (x : G) :
    ((g • φ : patched ρ₁ ρ₂) : G → F₀) x = (φ : G → F₀) (x * g) :=
  rfl

instance : SMulCommClass G ↥(F₁.toSubring ⊓ F₂.toSubring) (patched ρ₁ ρ₂) :=
  smulCommClass_patch _ _

/-- The invariants of the patched algebra are the constants in `F₁ ∩ F₂`, if `Eᵢ^{Hᵢ} = Fᵢ`. -/
lemma isInvariant_patched (hfix₁ : ∀ e : E₁, (∀ h, ρ₁ h e = e) → (e : F₀) ∈ F₁)
    (hfix₂ : ∀ e : E₂, (∀ h, ρ₂ h e = e) → (e : F₀) ∈ F₂) :
    Algebra.IsInvariant ↥(F₁.toSubring ⊓ F₂.toSubring) (patched ρ₁ ρ₂) G :=
  isInvariant_patch _ _ (algebraMap F₀ (G → F₀)).injective
    (fun _ hφ hinv ↦ exists_eq_algebraMap_of_mem_induced hfix₁ hφ hinv)
    (fun _ hφ hinv ↦ exists_eq_algebraMap_of_mem_induced hfix₂ hφ hinv)

/-- If moreover `H₁` and `H₂` generate `G`, the patched algebra is a field. -/
theorem isField_patched [Finite G] (hH : H₁ ⊔ H₂ = ⊤)
    (hfix₁ : ∀ e : E₁, (∀ h, ρ₁ h e = e) → (e : F₀) ∈ F₁)
    (hfix₂ : ∀ e : E₂, (∀ h, ρ₂ h e = e) → (e : F₀) ∈ F₂) :
    IsField (patched ρ₁ ρ₂) := by
  have := isDomain_patched (ρ₁ := ρ₁) (ρ₂ := ρ₂) hH
  have := isInvariant_patched hfix₁ hfix₂
  have : Algebra.IsIntegral ↥(F₁.toSubring ⊓ F₂.toSubring) (patched ρ₁ ρ₂) :=
    Algebra.IsInvariant.isIntegral _ _ G
  have : IsField ↥(F₁.toSubring ⊓ F₂.toSubring) := Field.toIsField ↥(F₁ ⊓ F₂)
  exact isField_of_isIntegral_of_isField' this

/-- An element of `E` fixed by the Galois group lies in the base field. -/
lemma mem_of_forall_eq {F : Subfield F₀} {E : IntermediateField F F₀} [FiniteDimensional F E]
    [IsGalois F E] {H : Subgroup G} (ρ : H ≃* (E ≃ₐ[F] E)) (e : E)
    (he : ∀ h, ρ.toMonoidHom h e = e) : (e : F₀) ∈ F := by
  obtain ⟨c, hc⟩ := (IsGalois.mem_range_algebraMap_iff_fixed e).mpr fun σ ↦ by
    obtain ⟨h, rfl⟩ := ρ.surjective σ
    exact he h
  rw [← hc]
  exact c.2

variable [Fintype G] [DecidableEq G] [FiniteDimensional F₁ E₁] [IsGalois F₁ E₁]
  [FiniteDimensional F₂ E₂] [IsGalois F₂ E₂]

/-- **Galois patching, compatibility with the local data** (split case): one `F₀`-basis of
`F₀^G` is an `(F₁ ∩ F₂)`-basis of the patched algebra and an `Fᵢ`-basis of `Ind_{Hᵢ}^G Eᵢ`. So
`E ⊗_{F₁ ∩ F₂} Fᵢ ≅ Ind_{Hᵢ}^G Eᵢ` for the patched algebra `E`, compatibly with the action of
`G` (both act by right translations inside `F₀^G`). -/
theorem exists_basis_patched (hfact : F₁.toSubring.HasGLFactorization F₂.toSubring G)
    (ρ₁ : H₁ ≃* (E₁ ≃ₐ[F₁] E₁)) (ρ₂ : H₂ ≃* (E₂ ≃ₐ[F₂] E₂)) :
    ∃ b : Module.Basis G F₀ (G → F₀),
      Subalgebra.toSubmodule (induced F₁ E₁ H₁ ρ₁.toMonoidHom) =
        Submodule.span F₁.toSubring (Set.range b) ∧
      Subalgebra.toSubmodule (induced F₂ E₂ H₂ ρ₂.toMonoidHom) =
        Submodule.span F₂.toSubring (Set.range b) ∧
      Subalgebra.toSubmodule (patched ρ₁.toMonoidHom ρ₂.toMonoidHom) =
        Submodule.span ↥(F₁.toSubring ⊓ F₂.toSubring) (Set.range b) := by
  obtain ⟨b₁, hb₁⟩ := exists_basis_span_induced (E := E₁) ρ₁
  obtain ⟨b₂, hb₂⟩ := exists_basis_span_induced (E := E₂) ρ₂
  exact exists_basis_patch hfact hb₁ hb₂

/-- **Galois patching** (split case): with the factorization property, `G` is a Galois group of
the patched algebra over `F₁ ∩ F₂`: it acts faithfully, and the invariants are `F₁ ∩ F₂`. -/
theorem isGaloisGroup_patched (hfact : F₁.toSubring.HasGLFactorization F₂.toSubring G)
    (ρ₁ : H₁ ≃* (E₁ ≃ₐ[F₁] E₁)) (ρ₂ : H₂ ≃* (E₂ ≃ₐ[F₂] E₂)) :
    IsGaloisGroup G ↥(F₁.toSubring ⊓ F₂.toSubring) (patched ρ₁.toMonoidHom ρ₂.toMonoidHom) := by
  obtain ⟨b₁, hb₁⟩ := exists_basis_span_induced (E := E₁) ρ₁
  obtain ⟨b₂, hb₂⟩ := exists_basis_span_induced (E := E₂) ρ₂
  exact isGaloisGroup_patch _ _ hfact hb₁ hb₂ (algebraMap F₀ (G → F₀)).injective
    (fun _ hφ hinv ↦ exists_eq_algebraMap_of_mem_induced (mem_of_forall_eq ρ₁) hφ hinv)
    (fun _ hφ hinv ↦ exists_eq_algebraMap_of_mem_induced (mem_of_forall_eq ρ₂) hφ hinv)
    eq_one_of_rightTranslation

end Patched

end Split

end GaloisPatching

namespace Subfield

open GaloisPatching

variable {F₀ : Type u} [Field F₀] {G : Type v} [Group G] [Fintype G] [DecidableEq G]

/-- **Galois patching**, split case (Harbater; Harbater–Hartmann, *Patching over fields*): let
`F₁, F₂ ⊆ F₀` be subfields with the factorization property in size `G`
(`GL_G(F₀) = GL_G(F₁) · GL_G(F₂)`), let `G` be a finite group generated by subgroups `H₁, H₂`,
and let `Eᵢ ⊆ F₀` be a finite Galois extension of `Fᵢ` with group `Hᵢ` (so the local data split
over `F₀`). Then `G` is the Galois group of a Galois field extension of `F₁ ∩ F₂`. The extension
is the patched algebra `GaloisPatching.patched`; its compatibility with the local data is
`GaloisPatching.exists_basis_patched`. -/
theorem exists_isGaloisGroup_of_hasGLFactorization {F₁ F₂ : Subfield F₀}
    (hfact : F₁.toSubring.HasGLFactorization F₂.toSubring G) {H₁ H₂ : Subgroup G}
    (hH : H₁ ⊔ H₂ = ⊤) (E₁ : IntermediateField F₁ F₀) (E₂ : IntermediateField F₂ F₀)
    [IsGalois F₁ E₁] [FiniteDimensional F₁ E₁] [IsGalois F₂ E₂] [FiniteDimensional F₂ E₂]
    (ρ₁ : H₁ ≃* (E₁ ≃ₐ[F₁] E₁)) (ρ₂ : H₂ ≃* (E₂ ≃ₐ[F₂] E₂)) :
    ∃ (E : Type (max u v)) (_ : Field E) (_ : Algebra ↥(F₁ ⊓ F₂) E)
      (_ : MulSemiringAction G E), IsGaloisGroup G ↥(F₁ ⊓ F₂) E := by
  let := (isField_patched (ρ₁ := ρ₁.toMonoidHom) (ρ₂ := ρ₂.toMonoidHom) hH
    (mem_of_forall_eq ρ₁) (mem_of_forall_eq ρ₂)).toField
  exact ⟨patched ρ₁.toMonoidHom ρ₂.toMonoidHom, inferInstance,
    (inferInstance : Algebra ↥(F₁.toSubring ⊓ F₂.toSubring) _), inferInstance,
    isGaloisGroup_patched hfact ρ₁ ρ₂⟩

end Subfield
