/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import Mathlib.RingTheory.AdjoinRoot
import SGA.Foundations.Patching.ProjectiveLineIntersection

/-!
# Patching on a nodal model: two projective lines meeting at a node

Harbater–Stevenson (*Patching and thickening problems*, J. Algebra 212 (1999), Theorem 6, a
formal-patching proof of Raynaud's Théorème 2.2.3) patch covers of two copies of the
projective line over `k` at a node whose complete local ring is `k⟦t, u, v⟧/(uv - t²)`. This
file sets up patching over fields for that configuration.

We realize the nodal model as a double cover of the configuration of
`SGA.Foundations.Patching.ProjectiveLine` (`ℙ¹_{k⟦t⟧}` with coordinate `x`, `y = 1/x`, the point
`P : y = 0` and `U = ℙ¹_k - P`): adjoin a root `u` of `T² - y T + t²`, and put `v = y - u`, so
that `uv = t²`. Over the branch field `F_℘ = k((y))((t))` the polynomial has two roots,
`T₁ ≡ y` and `T₂ ≡ 0` modulo `t` (`PatchingProjectiveLine.nodeRootOne`,
`PatchingProjectiveLine.nodeRootTwo`; `T₂ ∈ k[x]⟦t⟧` is `PatchingProjectiveLine.nodeRoot`).
So the nodal model has two branches at the node, with fields `F_℘ × F_℘`; over `U` it has two
sheets, with fields `F_U × F_U`; and the node has the field generated by `F_P` and `u`, embedded
diagonally through the two roots (`PatchingProjectiveLine.nodeSubring`: pairs
`(α + β T₁, α + β T₂)` with `α, β ∈ F_P`). Its complete local ring is
`k⟦y, t⟧[T]/(T² - y T + t²)` (`PatchingProjectiveLine.nodeRing`), which is
`k⟦t, u, v⟧/(uv - t²)` with `u = T`, `v = y - T` (this identification is only used as motivation
and is not formalized). That `F_U × F_U` and `F_O` are the fields of the sheets and of the node of
Harbater–Stevenson's nodal model is likewise the geometric meaning of the construction, not a
statement proved here.

Main results:
* `PatchingProjectiveLine.nodeHasGLFactorization`: `F_U × F_U` and the node field have the
  factorization property inside `F_℘ × F_℘`, for every size: patching problems for free modules
  and Galois algebras on the nodal model have solutions (`SGA.Foundations.Patching.Modules`,
  `SGA.Foundations.Patching.Fields`).
* `PatchingProjectiveLine.prod_inf_nodeSubring`: the intersection is `k((t))(x)[u]`, the image
  of `k((t))(x)[T]/(T² - y T + t²)` through the two roots (`PatchingProjectiveLine.nodeBase`).
  This follows from `F_U ∩ F_P = k((t))(x)` (`PatchingProjectiveLine.fieldU_inf_fieldP`). That
  `T² - y T + t²` is irreducible over `k((t))(x)`, so that `nodeBase` is the field `k((t))(u)`, is
  `PatchingProjectiveLine.isField_nodeBase` (`SGA.Foundations.Patching.ProjectiveLineNodeField`).
-/

universe u

open PowerSeries HahnSeries

namespace AdjoinRoot

variable {R : Type*} [CommRing R] (t : R) {q : Polynomial R} (hq : q.Monic)

/-- In `R[T]/(q)` with `q` monic, an element lies in `(tⁿ)` iff its coordinates in the power basis
`1, T, …` lie in `(tⁿ)`. -/
lemma mem_span_pow_iff (n : ℕ) (s : AdjoinRoot q) :
    s ∈ Ideal.span {AdjoinRoot.of q t ^ n} ↔
      ∀ i, (AdjoinRoot.powerBasis' hq).basis.repr s i ∈ Ideal.span {t ^ n} := by
  set pb := AdjoinRoot.powerBasis' hq
  constructor
  · intro hs i
    obtain ⟨c, rfl⟩ := Ideal.mem_span_singleton'.mp hs
    have : c * AdjoinRoot.of q t ^ n = t ^ n • c := by
      rw [Algebra.smul_def, mul_comm, ← map_pow]
      rfl
    rw [this, map_smul, Finsupp.smul_apply, smul_eq_mul]
    exact Ideal.mul_mem_right _ _ (Ideal.mem_span_singleton_self _)
  · intro hs
    choose c hc using fun i ↦ Ideal.mem_span_singleton'.mp (hs i)
    rw [Ideal.mem_span_singleton']
    refine ⟨∑ i, c i • pb.basis i, ?_⟩
    conv_rhs => rw [← pb.basis.sum_repr s]
    rw [Finset.sum_mul]
    refine Finset.sum_congr rfl fun i _ ↦ ?_
    rw [← hc i, smul_mul_assoc, mul_smul, ← map_pow]
    congr 1
    rw [Algebra.smul_def, mul_comm]
    rfl

/-- `R[T]/(q)` with `q` monic is `t`-adically complete if `R` is. -/
theorem isAdicComplete_span_singleton (hq : q.Monic) [IsAdicComplete (Ideal.span {t}) R] :
    IsAdicComplete (Ideal.span {AdjoinRoot.of q t}) (AdjoinRoot q) := by
  set pb := AdjoinRoot.powerBasis' hq
  have hmod : ∀ (n : ℕ) (a b : AdjoinRoot q),
      a ≡ b [SMOD ((Ideal.span {AdjoinRoot.of q t}) ^ n • ⊤ : Submodule (AdjoinRoot q) _)] ↔
        ∀ i, pb.basis.repr a i ≡ pb.basis.repr b i
          [SMOD ((Ideal.span {t}) ^ n • ⊤ : Submodule R R)] := by
    intro n a b
    simp only [SModEq.sub_mem, smul_eq_mul, Ideal.mul_top, Ideal.span_singleton_pow]
    rw [mem_span_pow_iff t hq]
    simp only [map_sub, Finsupp.sub_apply]
    exact Iff.rfl
  refine { haus' := fun s hs ↦ ?_, prec' := fun f hf ↦ ?_ }
  · rw [← pb.basis.sum_repr s]
    refine Finset.sum_eq_zero fun i _ ↦ ?_
    have : pb.basis.repr s i = 0 := IsHausdorff.haus (I := Ideal.span {t}) inferInstance _
      fun n ↦ ((hmod n s 0).mp (hs n) i).trans (by simp)
    rw [this, zero_smul]
  · choose L hL using fun i ↦ IsPrecomplete.prec (I := Ideal.span {t}) inferInstance
      (f := fun m ↦ pb.basis.repr (f m) i) fun {m n} hmn ↦ (hmod m _ _).mp (hf hmn) i
    refine ⟨pb.basis.equivFun.symm L, fun n ↦ (hmod n _ _).mpr fun i ↦ ?_⟩
    have hL' := congrFun (pb.basis.equivFun.apply_symm_apply L) i
    rw [Module.Basis.equivFun_apply] at hL'
    rw [hL']
    exact hL i n

end AdjoinRoot

namespace PatchingProjectiveLine

variable (k : Type u) [Field k]

/-- The coefficients of the root `z = ∑ zₘ tᵐ ∈ k[x]⟦t⟧` of `z = x t² + x z²` with `z ≡ 0`
modulo `t`: `z₀ = 0` and `zₘ₊₁ = [m = 1] x + x ∑_{i < m} zᵢ₊₁ zₘ₋ᵢ`. -/
noncomputable def nodeRootCoeff : ℕ → Polynomial k
  | 0 => 0
  | m + 1 => (if m = 1 then Polynomial.X else 0) +
      Polynomial.X * ∑ i : Fin m, nodeRootCoeff (i + 1) * nodeRootCoeff (m - i)
decreasing_by
  · exact Nat.succ_lt_succ i.isLt
  · omega

/-- The root `T₂ = x t² + x T₂²` of `x T² - T + x t²` in `k[x]⟦t⟧` with `T₂ ≡ 0` modulo `t`; as
`x = 1/y`, it is the root `≡ 0` of `T² - y T + t²`. -/
noncomputable def nodeRoot : PowerSeries (Polynomial k) :=
  PowerSeries.mk (nodeRootCoeff k)

lemma coeff_zero_nodeRoot : PowerSeries.coeff 0 (nodeRoot k) = 0 := by
  rw [nodeRoot, PowerSeries.coeff_mk, nodeRootCoeff]

/-- `T₂ = x t² + x T₂²` in `k[x]⟦t⟧`. -/
theorem nodeRoot_eq : PowerSeries.C Polynomial.X * nodeRoot k ^ 2 +
    PowerSeries.C Polynomial.X * PowerSeries.X ^ 2 = nodeRoot k := by
  refine PowerSeries.ext fun n ↦ ?_
  rw [map_add, PowerSeries.coeff_C_mul, PowerSeries.coeff_C_mul, PowerSeries.coeff_X_pow, pow_two,
    PowerSeries.coeff_mul, Finset.Nat.sum_antidiagonal_eq_sum_range_succ_mk]
  have hc : ∀ i, PowerSeries.coeff i (nodeRoot k) = nodeRootCoeff k i := fun i ↦
    PowerSeries.coeff_mk _ _
  have h0 : nodeRootCoeff k 0 = 0 := by rw [nodeRootCoeff.eq_1]
  simp only [hc]
  rcases n with _ | m
  · simp [h0]
  · conv_rhs => rw [nodeRootCoeff.eq_2]
    rw [Finset.sum_range_succ, Finset.sum_range_succ', Nat.sub_self, Nat.sub_zero, h0, mul_zero,
      zero_mul, add_zero, add_zero,
      Fin.sum_univ_eq_sum_range (fun i ↦ nodeRootCoeff k (i + 1) * nodeRootCoeff k (m - i)),
      add_comm]
    congr 1
    · by_cases h : m = 1
      · simp [h]
      · simp [h, show m + 1 ≠ 2 by omega]
    · congr 1
      refine Finset.sum_congr rfl fun i hi ↦ ?_
      congr 2
      omega

/-- The root `T₂ ≡ 0` (modulo `t`) of `T² - y T + t²` in `k((y))⟦t⟧`. -/
noncomputable def nodeRootTwo' : PowerSeries (LaurentSeries k) :=
  mapU k (nodeRoot k)

/-- The root `T₁ ≡ y` (modulo `t`) of `T² - y T + t²` in `k((y))⟦t⟧`. -/
noncomputable def nodeRootOne' : PowerSeries (LaurentSeries k) :=
  PowerSeries.C (single (1 : ℤ) (1 : k)) - nodeRootTwo' k

lemma mapU_C_X : mapU k (PowerSeries.C Polynomial.X) = PowerSeries.C (single (-1 : ℤ) (1 : k)) := by
  rw [mapU, PowerSeries.map_C]
  simp [invX]

/-- `T₂² - y T₂ + t² = 0` in `k((y))⟦t⟧`. -/
lemma nodeRootTwo'_sq : nodeRootTwo' k ^ 2 - PowerSeries.C (single (1 : ℤ) (1 : k)) *
    nodeRootTwo' k + PowerSeries.X ^ 2 = 0 := by
  have h := congrArg (mapU k) (nodeRoot_eq k)
  rw [map_add, map_mul, map_mul, map_pow, map_pow, mapU_C_X, mapU, PowerSeries.map_X] at h
  rw [← mapU] at h
  have hyx : PowerSeries.C (single (1 : ℤ) (1 : k)) * PowerSeries.C (single (-1 : ℤ) (1 : k)) =
      (1 : PowerSeries (LaurentSeries k)) := by
    rw [← map_mul, single_mul_single, add_neg_cancel, one_mul, single_zero_one, map_one]
  have := congrArg (PowerSeries.C (single (1 : ℤ) (1 : k)) * ·) h
  simp only [mul_add, ← mul_assoc, hyx, one_mul] at this
  rw [nodeRootTwo', ← this]
  ring

/-- `T₁² - y T₁ + t² = 0` in `k((y))⟦t⟧`. -/
lemma nodeRootOne'_sq : nodeRootOne' k ^ 2 - PowerSeries.C (single (1 : ℤ) (1 : k)) *
    nodeRootOne' k + PowerSeries.X ^ 2 = 0 := by
  rw [nodeRootOne', ← nodeRootTwo'_sq k]
  ring

lemma constantCoeff_nodeRootTwo' : PowerSeries.constantCoeff (nodeRootTwo' k) = 0 := by
  rw [nodeRootTwo', mapU, ← PowerSeries.coeff_zero_eq_constantCoeff_apply, PowerSeries.coeff_map,
    coeff_zero_nodeRoot, map_zero]

lemma constantCoeff_nodeRootOne' :
    PowerSeries.constantCoeff (nodeRootOne' k) = single (1 : ℤ) (1 : k) := by
  rw [nodeRootOne', map_sub, PowerSeries.constantCoeff_C, constantCoeff_nodeRootTwo', sub_zero]

/-- The root `T₂` in `F_℘ = k((y))((t))`. -/
noncomputable def nodeRootTwo : LaurentSeries (LaurentSeries k) :=
  toField k (nodeRootTwo' k)

/-- The root `T₁` in `F_℘ = k((y))((t))`. -/
noncomputable def nodeRootOne : LaurentSeries (LaurentSeries k) :=
  toField k (nodeRootOne' k)

/-- The element `t` of `F_℘ = k((y))((t))`. -/
noncomputable abbrev tF : LaurentSeries (LaurentSeries k) :=
  toField k PowerSeries.X

lemma yF_eq : yF k = toField k (PowerSeries.C (single (1 : ℤ) (1 : k))) :=
  rfl

lemma nodeRootTwo_sq : nodeRootTwo k ^ 2 = yF k * nodeRootTwo k - tF k ^ 2 := by
  have := congrArg (toField k) (nodeRootTwo'_sq k)
  rw [map_add, map_sub, map_mul, map_pow, map_pow, map_zero, ← yF_eq] at this
  rw [nodeRootTwo]
  linear_combination this

lemma nodeRootOne_sq : nodeRootOne k ^ 2 = yF k * nodeRootOne k - tF k ^ 2 := by
  have := congrArg (toField k) (nodeRootOne'_sq k)
  rw [map_add, map_sub, map_mul, map_pow, map_pow, map_zero, ← yF_eq] at this
  rw [nodeRootOne]
  linear_combination this

lemma nodeRootOne_add_nodeRootTwo : nodeRootOne k + nodeRootTwo k = yF k := by
  rw [nodeRootOne, nodeRootTwo, nodeRootOne', map_sub, yF_eq]
  ring

lemma nodeRootOne_mul_nodeRootTwo : nodeRootOne k * nodeRootTwo k = tF k ^ 2 := by
  have h := nodeRootTwo_sq k
  rw [← nodeRootOne_add_nodeRootTwo k] at h
  linear_combination -h

lemma nodeRootOne_sub_nodeRootTwo_ne_zero : nodeRootOne k - nodeRootTwo k ≠ 0 := by
  rw [nodeRootOne, nodeRootTwo, ← map_sub]
  intro h
  have h0 := congrArg PowerSeries.constantCoeff
    (ofPowerSeries_injective (h.trans (map_zero _).symm))
  rw [map_sub, constantCoeff_nodeRootOne', constantCoeff_nodeRootTwo', sub_zero, map_zero] at h0
  exact one_ne_zero ((single_eq_zero_iff (a := (1 : ℤ))).mp h0)

lemma tF_mem_fieldP : tF k ∈ fieldP k := by
  rw [tF, toField_X]
  exact single_one_mem_fieldP k

lemma yF_mem_fieldP : yF k ∈ fieldP k :=
  toField_C_mem_fieldP k _

lemma xF_mem_fieldU : xF k ∈ fieldU k := by
  have : xF k = toField k (mapU k (PowerSeries.C Polynomial.X)) := by
    rw [mapU_C_X]
    rfl
  rw [this]
  exact Subfield.subset_closure ⟨_, rfl⟩

lemma yF_mem_fieldU : yF k ∈ fieldU k := by
  rw [eq_inv_of_mul_eq_one_right (xF_mul_yF k)]
  exact (fieldU k).inv_mem (xF_mem_fieldU k)

lemma nodeRootTwo_mem_fieldU : nodeRootTwo k ∈ fieldU k :=
  Subfield.subset_closure ⟨nodeRoot k, rfl⟩

lemma nodeRootOne_mem_fieldU : nodeRootOne k ∈ fieldU k := by
  rw [show nodeRootOne k = yF k - nodeRootTwo k by
    rw [← nodeRootOne_add_nodeRootTwo k]; ring]
  exact (fieldU k).sub_mem (yF_mem_fieldU k) (nodeRootTwo_mem_fieldU k)

/-- The pairs `(α + β T₁, α + β T₂)` in `F_℘ × F_℘`, for `α, β` in a subfield `F` containing `y`
and `t`: the image of `F[T]/(T² - y T + t²)` under the two roots. -/
noncomputable def nodePairs (F : Subfield (LaurentSeries (LaurentSeries k)))
    (hy : yF k ∈ F) (ht : tF k ∈ F) :
    Subring (LaurentSeries (LaurentSeries k) × LaurentSeries (LaurentSeries k)) where
  carrier := {z | ∃ α ∈ F, ∃ β ∈ F, z = (α + β * nodeRootOne k, α + β * nodeRootTwo k)}
  one_mem' := ⟨1, F.one_mem, 0, F.zero_mem, Prod.ext (by simp) (by simp)⟩
  zero_mem' := ⟨0, F.zero_mem, 0, F.zero_mem, Prod.ext (by simp) (by simp)⟩
  add_mem' := by
    rintro _ _ ⟨α, hα, β, hβ, rfl⟩ ⟨α', hα', β', hβ', rfl⟩
    exact ⟨α + α', F.add_mem hα hα', β + β', F.add_mem hβ hβ',
      Prod.ext (by simp only [Prod.fst_add]; ring) (by simp only [Prod.snd_add]; ring)⟩
  neg_mem' := by
    rintro _ ⟨α, hα, β, hβ, rfl⟩
    exact ⟨-α, F.neg_mem hα, -β, F.neg_mem hβ,
      Prod.ext (by simp only [Prod.fst_neg]; ring) (by simp only [Prod.snd_neg]; ring)⟩
  mul_mem' := by
    rintro _ _ ⟨α, hα, β, hβ, rfl⟩ ⟨α', hα', β', hβ', rfl⟩
    refine ⟨α * α' - β * β' * tF k ^ 2, F.sub_mem (F.mul_mem hα hα')
      (F.mul_mem (F.mul_mem hβ hβ') (F.pow_mem ht 2)),
      α * β' + α' * β + β * β' * yF k, F.add_mem (F.add_mem (F.mul_mem hα hβ')
        (F.mul_mem hα' hβ)) (F.mul_mem (F.mul_mem hβ hβ') hy), ?_⟩
    refine Prod.ext ?_ ?_
    · simp only [Prod.fst_mul]
      linear_combination β * β' * nodeRootOne_sq k
    · simp only [Prod.snd_mul]
      linear_combination β * β' * nodeRootTwo_sq k

/-- The field of the node, `F_O = F_P[u]/(u² - y u + t²)`, inside `F_℘ × F_℘`. -/
noncomputable def nodeSubring :
    Subring (LaurentSeries (LaurentSeries k) × LaurentSeries (LaurentSeries k)) :=
  nodePairs k (fieldP k) (yF_mem_fieldP k) (tF_mem_fieldP k)

lemma tF_mem_fieldU : tF k ∈ fieldU k :=
  Subfield.subset_closure ⟨PowerSeries.X, by
    change toField k (mapU k PowerSeries.X) = _
    rw [mapU, PowerSeries.map_X]⟩

lemma yF_mem_fieldBase : yF k ∈ fieldBase k := by
  rw [← fieldU_inf_fieldP k]
  exact ⟨yF_mem_fieldU k, yF_mem_fieldP k⟩

lemma tF_mem_fieldBase : tF k ∈ fieldBase k := by
  rw [← fieldU_inf_fieldP k]
  exact ⟨tF_mem_fieldU k, tF_mem_fieldP k⟩

/-- The image of `k((t))(x)[T]/(T² - y T + t²)` in `F_℘ × F_℘` through the two roots: the
function field `k((t))(u)` of the generic fibre of the nodal model (it is a field:
`PatchingProjectiveLine.isField_nodeBase`). -/
noncomputable def nodeBase :
    Subring (LaurentSeries (LaurentSeries k) × LaurentSeries (LaurentSeries k)) :=
  nodePairs k (fieldBase k) (yF_mem_fieldBase k) (tF_mem_fieldBase k)

/-- **The intersection on the nodal model**: inside `F_℘ × F_℘`, the intersection of the fields
`F_U × F_U` of the two sheets over `U` and the field `F_O` of the node is `k((t))(x)[u]`
(`nodeBase`), the function field of the generic fibre. -/
theorem prod_inf_nodeSubring :
    (fieldU k).toSubring.prod (fieldU k).toSubring ⊓ nodeSubring k = nodeBase k := by
  ext z
  simp only [Subring.mem_inf, Subring.mem_prod]
  constructor
  · rintro ⟨⟨h₁, h₂⟩, α, hα, β, hβ, rfl⟩
    have hβU : β ∈ fieldU k := by
      have hd : β * (nodeRootOne k - nodeRootTwo k) ∈ fieldU k := by
        have := (fieldU k).sub_mem h₁ h₂
        convert this using 1
        ring
      have := (fieldU k).mul_mem hd
        ((fieldU k).inv_mem ((fieldU k).sub_mem (nodeRootOne_mem_fieldU k)
          (nodeRootTwo_mem_fieldU k)))
      rwa [mul_assoc, mul_inv_cancel₀ (nodeRootOne_sub_nodeRootTwo_ne_zero k), mul_one] at this
    have hαU : α ∈ fieldU k := by
      have := (fieldU k).sub_mem h₁ ((fieldU k).mul_mem hβU (nodeRootOne_mem_fieldU k))
      simpa using this
    refine ⟨α, ?_, β, ?_, rfl⟩
    · rw [← fieldU_inf_fieldP k]
      exact ⟨hαU, hα⟩
    · rw [← fieldU_inf_fieldP k]
      exact ⟨hβU, hβ⟩
  · rintro ⟨α, hα, β, hβ, rfl⟩
    rw [← fieldU_inf_fieldP k] at hα hβ
    exact ⟨⟨(fieldU k).add_mem hα.1 ((fieldU k).mul_mem hβ.1 (nodeRootOne_mem_fieldU k)),
      (fieldU k).add_mem hα.1 ((fieldU k).mul_mem hβ.1 (nodeRootTwo_mem_fieldU k))⟩,
      α, hα.2, β, hβ.2, rfl⟩

section Factorization

/-- An element of `nodePairs F` with both components non-zero is invertible in `nodePairs F`. -/
lemma nodePairs_exists_mul_eq_one {F : Subfield (LaurentSeries (LaurentSeries k))}
    (hy : yF k ∈ F) (ht : tF k ∈ F)
    {z : LaurentSeries (LaurentSeries k) × LaurentSeries (LaurentSeries k)}
    (hz : z ∈ nodePairs k F hy ht) (h₁ : z.1 ≠ 0) (h₂ : z.2 ≠ 0) :
    ∃ w ∈ nodePairs k F hy ht, z * w = 1 := by
  obtain ⟨α, hα, β, hβ, rfl⟩ := hz
  have hsum := nodeRootOne_add_nodeRootTwo k
  have hprod := nodeRootOne_mul_nodeRootTwo k
  set N := (α + β * nodeRootOne k) * (α + β * nodeRootTwo k) with hNdef
  have hN : N = α ^ 2 + α * β * yF k + β ^ 2 * tF k ^ 2 := by
    rw [hNdef]
    linear_combination α * β * hsum + β ^ 2 * hprod
  have hNF : N ∈ F := by
    rw [hN]
    exact F.add_mem (F.add_mem (F.pow_mem hα 2) (F.mul_mem (F.mul_mem hα hβ) hy))
      (F.mul_mem (F.pow_mem hβ 2) (F.pow_mem ht 2))
  have hN0 : N ≠ 0 := mul_ne_zero h₁ h₂
  refine ⟨((α + β * yF k) / N + (-β / N) * nodeRootOne k,
    (α + β * yF k) / N + (-β / N) * nodeRootTwo k),
    ⟨(α + β * yF k) / N, F.div_mem (F.add_mem hα (F.mul_mem hβ hy)) hNF, -β / N,
      F.div_mem (F.neg_mem hβ) hNF, rfl⟩, Prod.ext ?_ ?_⟩
  · simp only [Prod.fst_mul, Prod.fst_one]
    field_simp
    linear_combination -(α + β * nodeRootOne k) * β * hsum
  · simp only [Prod.snd_mul, Prod.snd_one]
    field_simp
    linear_combination -(α + β * nodeRootTwo k) * β * hsum

/-- A node-field element with both components non-zero is invertible in the node field. -/
lemma nodeSubring_exists_mul_eq_one
    {z : LaurentSeries (LaurentSeries k) × LaurentSeries (LaurentSeries k)}
    (hz : z ∈ nodeSubring k) (h₁ : z.1 ≠ 0) (h₂ : z.2 ≠ 0) :
    ∃ w ∈ nodeSubring k, z * w = 1 :=
  nodePairs_exists_mul_eq_one k _ _ hz h₁ h₂

omit [Field k] in
private lemma smodEq_zero_span_iff {T : Type*} [CommRing T] (c : T) (n : ℕ) (z : T) :
    z ≡ 0 [SMOD ((Ideal.span {c}) ^ n • ⊤ : Submodule T T)] ↔ ∃ d, z = c ^ n * d := by
  rw [SModEq.sub_mem, sub_zero, smul_eq_mul, Ideal.mul_top, Ideal.span_singleton_pow,
    Ideal.mem_span_singleton']
  exact ⟨fun ⟨d, hd⟩ ↦ ⟨d, by rw [← hd, mul_comm]⟩, fun ⟨d, hd⟩ ↦ ⟨d, by rw [hd, mul_comm]⟩⟩

omit [Field k] in
/-- `R × S` is `(a, b)`-adically Hausdorff if `R` is `a`-adically and `S` is `b`-adically
Hausdorff. -/
lemma isHausdorff_prod {R S : Type*} [CommRing R] [CommRing S] (a : R) (b : S)
    [IsHausdorff (Ideal.span {a}) R] [IsHausdorff (Ideal.span {b}) S] :
    IsHausdorff (Ideal.span {(a, b)}) (R × S) := by
  refine ⟨fun z hz ↦ Prod.ext ?_ ?_⟩
  · refine IsHausdorff.haus (I := Ideal.span {a}) inferInstance _ fun n ↦ ?_
    obtain ⟨d, hd⟩ := (smodEq_zero_span_iff _ n z).mp (hz n)
    exact (smodEq_zero_span_iff a n _).mpr ⟨d.1, by rw [hd, Prod.fst_mul, Prod.pow_fst]⟩
  · refine IsHausdorff.haus (I := Ideal.span {b}) inferInstance _ fun n ↦ ?_
    obtain ⟨d, hd⟩ := (smodEq_zero_span_iff _ n z).mp (hz n)
    exact (smodEq_zero_span_iff b n _).mpr ⟨d.2, by rw [hd, Prod.snd_mul, Prod.pow_snd]⟩

/-- The polynomial `T² - y T + t²` over `R̂_P = k⟦y⟧⟦t⟧`. -/
noncomputable def nodePoly : Polynomial (PowerSeries (PowerSeries k)) :=
  Polynomial.X ^ 2 + (Polynomial.C (-PowerSeries.C PowerSeries.X) * Polynomial.X +
    Polynomial.C (PowerSeries.X ^ 2))

lemma nodePoly_monic : (nodePoly k).Monic := by
  refine Polynomial.monic_X_pow_add ?_
  refine (Polynomial.degree_add_le _ _).trans_lt (max_lt ?_ ?_)
  · exact (Polynomial.degree_C_mul_X_le _).trans_lt (by decide)
  · exact Polynomial.degree_C_le.trans_lt (by decide)

/-- The complete local ring of the node, `R̂_O = k⟦y, t⟧[T]/(T² - y T + t²)` (geometrically
`k⟦t, u, v⟧/(uv - t²)` with `u = T`, `v = y - T`; not formalized). -/
noncomputable abbrev nodeRing : Type u :=
  AdjoinRoot (nodePoly k)

lemma eval₂_nodePoly (T : PowerSeries (LaurentSeries k)) :
    (nodePoly k).eval₂ (mapP k) T =
      T ^ 2 - PowerSeries.C (single (1 : ℤ) (1 : k)) * T + PowerSeries.X ^ 2 := by
  rw [nodePoly, Polynomial.eval₂_add, Polynomial.eval₂_X_pow, Polynomial.eval₂_add,
    Polynomial.eval₂_mul, Polynomial.eval₂_C, Polynomial.eval₂_X, Polynomial.eval₂_C, map_neg,
    map_pow, mapP, PowerSeries.map_C, PowerSeries.map_X, ofPowerSeries_X]
  ring

/-- The embedding of the node ring into the first branch (`u ↦ T₁ ≡ y`). -/
noncomputable def nodeMapOne : nodeRing k →+* PowerSeries (LaurentSeries k) :=
  AdjoinRoot.lift (mapP k) (nodeRootOne' k) (by rw [eval₂_nodePoly]; exact nodeRootOne'_sq k)

/-- The embedding of the node ring into the second branch (`u ↦ T₂ ≡ 0`). -/
noncomputable def nodeMapTwo : nodeRing k →+* PowerSeries (LaurentSeries k) :=
  AdjoinRoot.lift (mapP k) (nodeRootTwo' k) (by rw [eval₂_nodePoly]; exact nodeRootTwo'_sq k)

/-- The node ring lands in the node field. -/
lemma nodeMap_mem (r : nodeRing k) :
    (toField k (nodeMapOne k r), toField k (nodeMapTwo k r)) ∈ nodeSubring k := by
  let φ : nodeRing k →+* LaurentSeries (LaurentSeries k) × LaurentSeries (LaurentSeries k) :=
    ((toField k).comp (nodeMapOne k)).prod ((toField k).comp (nodeMapTwo k))
  change φ r ∈ nodeSubring k
  have hof : ∀ a, φ (AdjoinRoot.of _ a) ∈ nodeSubring k := fun a ↦
    ⟨toField k (mapP k a), Subfield.subset_closure ⟨a, rfl⟩, 0, (fieldP k).zero_mem,
      Prod.ext (by simp [φ, nodeMapOne]) (by simp [φ, nodeMapTwo])⟩
  have hroot : φ (AdjoinRoot.root _) ∈ nodeSubring k :=
    ⟨0, (fieldP k).zero_mem, 1, (fieldP k).one_mem,
      Prod.ext (by simp [φ, nodeMapOne, nodeRootOne]) (by simp [φ, nodeMapTwo, nodeRootTwo])⟩
  induction r using AdjoinRoot.induction_on with
  | ih p =>
    induction p using Polynomial.induction_on' with
    | add p q hp hq => rw [map_add, map_add]; exact (nodeSubring k).add_mem hp hq
    | monomial n a =>
      rw [← Polynomial.C_mul_X_pow_eq_monomial, map_mul, map_pow, AdjoinRoot.mk_C,
        AdjoinRoot.mk_X, map_mul, map_pow]
      exact (nodeSubring k).mul_mem (hof a) ((nodeSubring k).pow_mem hroot n)

/-- `X² ∣ T₂` in `k((y))⟦t⟧`. -/
lemma X_sq_dvd_nodeRootTwo' : (PowerSeries.X : PowerSeries (LaurentSeries k)) ^ 2 ∣
    nodeRootTwo' k := by
  rw [PowerSeries.X_pow_dvd_iff]
  intro m hm
  rw [nodeRootTwo', mapU, PowerSeries.coeff_map]
  interval_cases m
  · rw [coeff_zero_nodeRoot, map_zero]
  · rw [nodeRoot, PowerSeries.coeff_mk, nodeRootCoeff.eq_2]
    simp

/-- The weight `D = T₂ᴹ / (T₁ᴹ + T₂ᴹ)` is divisible by `t^{2M}`: the node field approximates the
idempotents `(1, 0)` and `(0, 1)` of `F_℘ × F_℘`. -/
lemma exists_nodeWeight {M : ℕ} (hM : M ≠ 0) : ∃ s : PowerSeries (LaurentSeries k),
    nodeRootTwo k ^ M = tF k ^ (2 * M) * toField k s * (nodeRootOne k ^ M + nodeRootTwo k ^ M) ∧
      nodeRootOne k ^ M + nodeRootTwo k ^ M ≠ 0 := by
  set x' : PowerSeries (LaurentSeries k) := PowerSeries.C (single (-1 : ℤ) (1 : k))
  set y' : PowerSeries (LaurentSeries k) := PowerSeries.C (single (1 : ℤ) (1 : k))
  have hxy : y' * x' = 1 := by
    rw [← map_mul, single_mul_single, add_neg_cancel, one_mul, single_zero_one, map_one]
  set w := x' * nodeRootTwo' k
  obtain ⟨w₂, hw₂⟩ := (X_sq_dvd_nodeRootTwo' k).mul_left x'
  have hT₂ : nodeRootTwo' k = y' * w := by rw [← mul_assoc, hxy, one_mul]
  have hT₁ : nodeRootOne' k = y' * (1 - w) := by
    rw [nodeRootOne', mul_sub, mul_one, ← hT₂]
  set Q := (1 - w) ^ M + w ^ M
  have hw0 : PowerSeries.constantCoeff w = 0 := by
    rw [map_mul, constantCoeff_nodeRootTwo', mul_zero]
  have hQ0 : PowerSeries.constantCoeff Q ≠ 0 := by
    simp [Q, hw0, zero_pow hM]
  have hsum : nodeRootOne' k ^ M + nodeRootTwo' k ^ M = y' ^ M * Q := by
    rw [hT₁, hT₂, mul_pow, mul_pow, ← mul_add]
  have hy'0 : y' ≠ 0 := fun h ↦ by
    have := congrArg (fun φ ↦ φ * x') h
    simp only [hxy, zero_mul] at this
    exact one_ne_zero this
  refine ⟨w₂ ^ M * Q⁻¹, ?_, ?_⟩
  · have hQQ : Q * Q⁻¹ = 1 := PowerSeries.mul_inv_cancel Q hQ0
    have key : nodeRootTwo' k ^ M = PowerSeries.X ^ (2 * M) * (w₂ ^ M * Q⁻¹) *
        (nodeRootOne' k ^ M + nodeRootTwo' k ^ M) := by
      rw [hsum, hT₂, mul_pow, show w = PowerSeries.X ^ 2 * w₂ from hw₂, mul_pow, ← pow_mul]
      linear_combination (-(PowerSeries.X ^ (2 * M) * w₂ ^ M * y' ^ M)) * hQQ
    have := congrArg (toField k) key
    simp only [map_mul, map_pow, map_add] at this
    rw [nodeRootOne, nodeRootTwo, tF, map_mul (toField k) (w₂ ^ M), map_pow]
    exact this
  · rw [nodeRootOne, nodeRootTwo, ← map_pow, ← map_pow, ← map_add, hsum]
    intro h
    have h0 := ofPowerSeries_injective (h.trans (map_zero _).symm)
    rcases mul_eq_zero.mp h0 with h' | h'
    · exact hy'0 ((pow_eq_zero_iff hM).mp h')
    · exact hQ0 (by rw [h', map_zero])

/-- `(1 - D, D)` lies in the node field, for the weight `D = T₂ᴹ / (T₁ᴹ + T₂ᴹ)`. -/
lemma nodeWeight_mem {M : ℕ} (hM : M ≠ 0) :
    (1 - nodeRootTwo k ^ M / (nodeRootOne k ^ M + nodeRootTwo k ^ M),
      nodeRootTwo k ^ M / (nodeRootOne k ^ M + nodeRootTwo k ^ M)) ∈ nodeSubring k := by
  obtain ⟨_, -, hS⟩ := exists_nodeWeight k hM
  set S := nodeRootOne k ^ M + nodeRootTwo k ^ M with hSdef
  have hτ : (nodeRootOne k, nodeRootTwo k) ∈ nodeSubring k :=
    ⟨0, (fieldP k).zero_mem, 1, (fieldP k).one_mem, Prod.ext (by simp) (by simp)⟩
  have hσ : (nodeRootTwo k, nodeRootOne k) ∈ nodeSubring k :=
    ⟨yF k, yF_mem_fieldP k, -1, (fieldP k).neg_mem (fieldP k).one_mem,
      Prod.ext (by dsimp only; rw [← nodeRootOne_add_nodeRootTwo k]; ring)
        (by dsimp only; rw [← nodeRootOne_add_nodeRootTwo k]; ring)⟩
  have hSS : (S, S) ∈ nodeSubring k := by
    have := (nodeSubring k).add_mem ((nodeSubring k).pow_mem hτ M) ((nodeSubring k).pow_mem hσ M)
    convert this using 1
    exact Prod.ext (by simp [hSdef]) (by simp [hSdef, add_comm])
  obtain ⟨w, hw, hSw⟩ := nodeSubring_exists_mul_eq_one k hSS hS hS
  have hw1 : w.1 = S⁻¹ := eq_inv_of_mul_eq_one_right (congrArg Prod.fst hSw)
  have hw2 : w.2 = S⁻¹ := eq_inv_of_mul_eq_one_right (congrArg Prod.snd hSw)
  have := (nodeSubring k).sub_mem (nodeSubring k).one_mem
    ((nodeSubring k).mul_mem ((nodeSubring k).pow_mem hσ M) hw)
  convert this using 1
  refine Prod.ext ?_ ?_
  · simp only [Prod.fst_sub, Prod.fst_one, Prod.fst_mul, Prod.pow_fst, hw1, div_eq_mul_inv]
  · simp only [Prod.snd_sub, Prod.snd_one, Prod.snd_mul, Prod.pow_snd, hw2]
    rw [eq_sub_iff_add_eq, div_eq_mul_inv, ← add_mul, add_comm, ← hSdef, mul_inv_cancel₀ hS]

/-- The map `R̂_U × R̂_U → R̂_℘ × R̂_℘` of the two sheets over `U`, with `R̂_U × R̂_U` written as
`(k[x] × k[x])⟦t⟧`. -/
noncomputable def nodeMapU : PowerSeries (Polynomial k × Polynomial k) →+*
    PowerSeries (LaurentSeries k) × PowerSeries (LaurentSeries k) :=
  ((mapU k).comp (PowerSeries.map (RingHom.fst (Polynomial k) (Polynomial k)))).prod
    ((mapU k).comp (PowerSeries.map (RingHom.snd (Polynomial k) (Polynomial k))))

/-- `R̂_℘ × R̂_℘ = (R̂_U × R̂_U) + R̂_O + t (R̂_℘ × R̂_℘)`. -/
lemma exists_eq_nodeMapU_add_nodeMap_add_mul
    (r : PowerSeries (LaurentSeries k) × PowerSeries (LaurentSeries k)) :
    ∃ a b c, r = nodeMapU k a + (nodeMapOne k).prod (nodeMapTwo k) b +
      (PowerSeries.X, PowerSeries.X) * c := by
  obtain ⟨p₂, s₂, h₂⟩ := exists_eq_invX_add_ofPowerSeries k (PowerSeries.constantCoeff r.2)
  obtain ⟨p₁, s₁, h₁⟩ := exists_eq_invX_add_ofPowerSeries k
    (PowerSeries.constantCoeff r.1 - ofPowerSeries ℤ k s₂)
  set s₁' := PowerSeries.mk fun n ↦ PowerSeries.coeff (n + 1) s₁
  have hs₁ := PowerSeries.eq_X_mul_shift_add_const s₁
  set a : PowerSeries (Polynomial k × Polynomial k) :=
    PowerSeries.C (p₁ + Polynomial.C (PowerSeries.constantCoeff s₁), p₂)
  set b : nodeRing k := AdjoinRoot.of _ (PowerSeries.C s₂) +
    AdjoinRoot.of _ (PowerSeries.C s₁') * AdjoinRoot.root _
  have hfst : PowerSeries.constantCoeff (mapU k (PowerSeries.map
      (RingHom.fst (Polynomial k) (Polynomial k)) a)) =
      invX k p₁ + HahnSeries.C (PowerSeries.constantCoeff s₁) := by
    simp only [a, PowerSeries.map_C, mapU, PowerSeries.constantCoeff_C, RingHom.coe_fst,
      map_add]
    congr 1
    simp [invX]
  have hsnd : PowerSeries.constantCoeff (mapU k (PowerSeries.map
      (RingHom.snd (Polynomial k) (Polynomial k)) a)) = invX k p₂ := by
    simp only [a, PowerSeries.map_C, mapU, PowerSeries.constantCoeff_C, RingHom.coe_snd]
  have hone : PowerSeries.constantCoeff (nodeMapOne k b) =
      ofPowerSeries ℤ k s₂ + ofPowerSeries ℤ k s₁' * single (1 : ℤ) (1 : k) := by
    simp only [b, map_add, map_mul, nodeMapOne, AdjoinRoot.lift_of, AdjoinRoot.lift_root, mapP,
      PowerSeries.map_C, PowerSeries.constantCoeff_C, constantCoeff_nodeRootOne']
  have htwo : PowerSeries.constantCoeff (nodeMapTwo k b) = ofPowerSeries ℤ k s₂ := by
    simp only [b, map_add, map_mul, nodeMapTwo, AdjoinRoot.lift_of, AdjoinRoot.lift_root, mapP,
      PowerSeries.map_C, PowerSeries.constantCoeff_C, constantCoeff_nodeRootTwo', mul_zero,
      add_zero]
  have hy : ofPowerSeries ℤ k s₁ = ofPowerSeries ℤ k s₁' * single (1 : ℤ) (1 : k) +
      HahnSeries.C (PowerSeries.constantCoeff s₁) := by
    conv_lhs => rw [hs₁]
    rw [map_add, map_mul, ofPowerSeries_X, ofPowerSeries_C, mul_comm]
  have hc₁ : PowerSeries.constantCoeff (r.1 - (mapU k (PowerSeries.map
      (RingHom.fst (Polynomial k) (Polynomial k)) a) + nodeMapOne k b)) = 0 := by
    rw [map_sub, map_add, hfst, hone]
    linear_combination h₁ + hy
  have hc₂ : PowerSeries.constantCoeff (r.2 - (mapU k (PowerSeries.map
      (RingHom.snd (Polynomial k) (Polynomial k)) a) + nodeMapTwo k b)) = 0 := by
    rw [map_sub, map_add, hsnd, htwo]
    linear_combination h₂
  obtain ⟨c₁, hc₁'⟩ := PowerSeries.X_dvd_iff.mpr hc₁
  obtain ⟨c₂, hc₂'⟩ := PowerSeries.X_dvd_iff.mpr hc₂
  refine ⟨a, b, (c₁, c₂), Prod.ext ?_ ?_⟩
  · simp only [Prod.fst_add, Prod.fst_mul, RingHom.prod_apply, RingHom.comp_apply, nodeMapU]
    linear_combination hc₁'
  · simp only [Prod.snd_add, Prod.snd_mul, RingHom.prod_apply, RingHom.comp_apply, nodeMapU]
    linear_combination hc₂'

/-- Every element of `F_℘ × F_℘` becomes integral after multiplication by a power of `t`. -/
lemma exists_mul_pow_eq_prod
    (z : LaurentSeries (LaurentSeries k) × LaurentSeries (LaurentSeries k)) :
    ∃ (a : ℕ) (r : PowerSeries (LaurentSeries k) × PowerSeries (LaurentSeries k)),
      z * (toField k).prodMap (toField k) (PowerSeries.X, PowerSeries.X) ^ a =
        (toField k).prodMap (toField k) r := by
  obtain ⟨a₁, r₁, h₁⟩ := exists_mul_pow_eq k z.1
  obtain ⟨a₂, r₂, h₂⟩ := exists_mul_pow_eq k z.2
  refine ⟨a₁ + a₂, (r₁ * PowerSeries.X ^ a₂, r₂ * PowerSeries.X ^ a₁), Prod.ext ?_ ?_⟩
  · simp only [Prod.fst_mul, Prod.pow_fst]
    change z.1 * toField k PowerSeries.X ^ (a₁ + a₂) = toField k (r₁ * PowerSeries.X ^ a₂)
    rw [pow_add, ← mul_assoc, h₁, map_mul, map_pow]
  · simp only [Prod.snd_mul, Prod.pow_snd]
    change z.2 * toField k PowerSeries.X ^ (a₁ + a₂) = toField k (r₂ * PowerSeries.X ^ a₁)
    rw [add_comm, pow_add, ← mul_assoc, h₂, map_mul, map_pow]

/-- **Weak approximation**: the node field is `t`-adically dense in `F_℘ × F_℘`. -/
lemma exists_mem_nodeSubring_sub_eq
    (z : LaurentSeries (LaurentSeries k) × LaurentSeries (LaurentSeries k)) (N : ℕ) :
    ∃ z' ∈ nodeSubring k, ∃ r : PowerSeries (LaurentSeries k) × PowerSeries (LaurentSeries k),
      z - z' = (toField k).prodMap (toField k) (PowerSeries.X, PowerSeries.X) ^ N *
        (toField k).prodMap (toField k) r := by
  obtain ⟨a₁, ha₁, r₁, h₁⟩ := exists_mem_fieldP_sub_eq k z.1 N
  obtain ⟨a₂, ha₂, r₂, h₂⟩ := exists_mem_fieldP_sub_eq k z.2 N
  obtain ⟨C, r₃, h₃⟩ := exists_mul_pow_eq k (a₁ - a₂)
  obtain ⟨s, hs, hS⟩ := exists_nodeWeight k (M := N + C + 1) (by omega)
  set D := nodeRootTwo k ^ (N + C + 1) /
    (nodeRootOne k ^ (N + C + 1) + nodeRootTwo k ^ (N + C + 1)) with hDdef
  have hD : D = toField k PowerSeries.X ^ (2 * (N + C + 1)) * toField k s := by
    rw [hDdef, div_eq_iff hS]
    exact hs
  have hr₃ : toField k (PowerSeries.X ^ (N + C + 2) * s * r₃) =
      toField k PowerSeries.X ^ (N + C + 2) * toField k s *
        ((a₁ - a₂) * toField k PowerSeries.X ^ C) := by
    rw [map_mul, map_mul, map_pow, h₃]
  have key : D * (a₁ - a₂) = toField k PowerSeries.X ^ N *
      toField k (PowerSeries.X ^ (N + C + 2) * s * r₃) := by
    rw [hr₃, hD]
    ring
  have he := nodeWeight_mem k (M := N + C + 1) (by omega)
  have hdiag : ∀ a ∈ fieldP k, ((a, a) : LaurentSeries (LaurentSeries k) ×
      LaurentSeries (LaurentSeries k)) ∈ nodeSubring k := fun a ha ↦
    ⟨a, ha, 0, (fieldP k).zero_mem, Prod.ext (by simp) (by simp)⟩
  have hmem : (1 - D, D) * (a₁, a₁) + (1 - (1 - D, D)) * (a₂, a₂) ∈ nodeSubring k :=
    (nodeSubring k).add_mem ((nodeSubring k).mul_mem he (hdiag a₁ ha₁))
      ((nodeSubring k).mul_mem ((nodeSubring k).sub_mem (nodeSubring k).one_mem he)
        (hdiag a₂ ha₂))
  refine ⟨_, hmem,
    (r₁ + PowerSeries.X ^ (N + C + 2) * s * r₃, r₂ - PowerSeries.X ^ (N + C + 2) * s * r₃),
    Prod.ext ?_ ?_⟩
  · simp only [Prod.fst_sub, Prod.fst_add, Prod.fst_mul, Prod.fst_one, Prod.pow_fst,
      RingHom.coe_prodMap, Prod.map_fst, map_add]
    linear_combination h₁ + key
  · simp only [Prod.snd_sub, Prod.snd_add, Prod.snd_mul, Prod.snd_one, Prod.pow_snd,
      RingHom.coe_prodMap, Prod.map_snd, map_sub]
    linear_combination h₂ - key


/-- **Factorization on the nodal model**: inside `F_℘ × F_℘`, the fields `F_U × F_U` of the two
sheets over `U` and the field `F_O` of the node have the factorization property in every size:
`GLₙ(F_℘ × F_℘) = GLₙ(F_U × F_U) · GLₙ(F_O)`. -/
theorem nodeHasGLFactorization (ι : Type*) [Fintype ι] [DecidableEq ι] :
    ((fieldU k).toSubring.prod (fieldU k).toSubring).HasGLFactorization (nodeSubring k) ι := by
  have : IsAdicComplete (Ideal.span {AdjoinRoot.of (nodePoly k) PowerSeries.X}) (nodeRing k) :=
    AdjoinRoot.isAdicComplete_span_singleton _ (nodePoly_monic k)
  have : IsHausdorff (Ideal.span {((PowerSeries.X, PowerSeries.X) :
      PowerSeries (LaurentSeries k) × PowerSeries (LaurentSeries k))})
      (PowerSeries (LaurentSeries k) × PowerSeries (LaurentSeries k)) :=
    isHausdorff_prod _ _
  refine Subring.hasGLFactorization_of_isAdicComplete ((toField k).prodMap (toField k))
    (R₁ := PowerSeries (Polynomial k × Polynomial k)) (f₁ := nodeMapU k)
    (f₂ := (nodeMapOne k).prod (nodeMapTwo k))
    (t₁ := PowerSeries.X) (t₂ := AdjoinRoot.of _ PowerSeries.X)
    (t := (PowerSeries.X, PowerSeries.X)) ?_ ?_ (exists_eq_nodeMapU_add_nodeMap_add_mul k) ?_
    (fun r ↦ nodeMap_mem k r) ?_ ?_ (exists_mul_pow_eq_prod k) (exists_mem_nodeSubring_sub_eq k)
  · exact Prod.ext (by simp [nodeMapU, mapU]) (by simp [nodeMapU, mapU])
  · exact Prod.ext (by simp [nodeMapOne, mapP]) (by simp [nodeMapTwo, mapP])
  · intro r
    exact Subring.mem_prod.mpr ⟨Subfield.subset_closure ⟨_, rfl⟩,
      Subfield.subset_closure ⟨_, rfl⟩⟩
  · rintro ⟨z, hz⟩ hu
    obtain ⟨hz₁, hz₂⟩ := Subring.mem_prod.mp hz
    obtain ⟨hu₁, hu₂⟩ := Prod.isUnit_iff.mp hu
    refine IsUnit.of_mul_eq_one ⟨(z.1⁻¹, z.2⁻¹), Subring.mem_prod.mpr
      ⟨(fieldU k).inv_mem hz₁, (fieldU k).inv_mem hz₂⟩⟩ (Subtype.ext (Prod.ext ?_ ?_))
    · exact mul_inv_cancel₀ hu₁.ne_zero
    · exact mul_inv_cancel₀ hu₂.ne_zero
  · rintro ⟨z, hz⟩ hu
    obtain ⟨hu₁, hu₂⟩ := Prod.isUnit_iff.mp hu
    obtain ⟨w, hw, hzw⟩ := nodeSubring_exists_mul_eq_one k hz hu₁.ne_zero hu₂.ne_zero
    exact IsUnit.of_mul_eq_one ⟨w, hw⟩ (Subtype.ext hzw)

end Factorization

end PatchingProjectiveLine
