/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import Mathlib.RingTheory.PowerSeries.WeierstrassPreparation
import SGA.Foundations.Patching.ProjectiveLine

/-!
# The intersection `F_U ∩ F_P = k((t))(x)` on `ℙ¹` over `k⟦t⟧`

With the notation of `SGA.Foundations.Patching.ProjectiveLine` (`x` a coordinate on `ℙ¹_{k⟦t⟧}`,
`y = 1/x`, `F_U = Frac k[x]⟦t⟧`, `F_P = Frac k⟦y, t⟧`, inside `F_℘ = k((y))((t))`), we show that
`F_U ∩ F_P` is the field `k((t))(x)` of rational functions, the fraction field of `k⟦t⟧[x]`
(`PatchingProjectiveLine.fieldBase`). This is the intersection half of patching over fields for
`ℙ¹` (Harbater–Hartmann, *Patching over fields*, Israel J. Math. 176 (2010)).

The proof clears denominators on both sides by polynomials:
* a non-zero element of `k⟦y, t⟧` divides a non-zero polynomial in `y` over `k⟦t⟧` (Weierstrass
  preparation, `PatchingProjectiveLine.exists_polyY_eq_mul`);
* a non-zero element of `k[x]⟦t⟧` divides a non-zero polynomial in `x` over `k⟦t⟧` (Weierstrass
  division by the reduction mod `t`, `PatchingProjectiveLine.exists_polyX_eq_mul`);
and then uses that an element of `k[x]⟦t⟧` with a pole of order `≤ L` at `y = 0` is a polynomial
in `x` of degree `≤ L` (`PatchingProjectiveLine.exists_polyX_eq_of_mapU_eq`), the formal analogue
of `H⁰(ℙ¹, 𝒪(L·∞)) = polynomials of degree ≤ L`.
-/

universe u v

open PowerSeries HahnSeries

/-- The subfield generated by the image of a ring map consists of the quotients of images. -/
lemma Subfield.mem_closure_range_iff {K R : Type*} [Field K] [CommRing R] (φ : R →+* K) {f : K} :
    f ∈ Subfield.closure (Set.range φ) ↔ ∃ a d : R, φ a / φ d = f := by
  rw [Subfield.mem_closure_iff, ← RingHom.coe_range, Subring.closure_eq]
  constructor
  · rintro ⟨_, ⟨a, rfl⟩, _, ⟨d, rfl⟩, h⟩
    exact ⟨a, d, h⟩
  · rintro ⟨a, d, h⟩
    exact ⟨_, ⟨a, rfl⟩, _, ⟨d, rfl⟩, h⟩

namespace PatchingProjectiveLine

variable (k : Type u) [Field k]

/-- `k⟦t⟧[x] → k[x]⟦t⟧`. -/
noncomputable def polyX : Polynomial (PowerSeries k) →+* PowerSeries (Polynomial k) :=
  Polynomial.eval₂RingHom (PowerSeries.map Polynomial.C) (PowerSeries.C Polynomial.X)

/-- `k⟦t⟧[y] → k⟦y⟧⟦t⟧`. -/
noncomputable def polyY : Polynomial (PowerSeries k) →+* PowerSeries (PowerSeries k) :=
  Polynomial.eval₂RingHom (PowerSeries.map PowerSeries.C) (PowerSeries.C PowerSeries.X)

/-- The field `k((t))(x)`: the fraction field of `k⟦t⟧[x]`, inside `k((y))((t))`. -/
noncomputable def fieldBase : Subfield (LaurentSeries (LaurentSeries k)) :=
  Subfield.closure (Set.range fun p ↦ toField k (mapU k (polyX k p)))

/-- The constants `k⟦t⟧ → k((y))((t))`. -/
noncomputable def constF : PowerSeries k →+* LaurentSeries (LaurentSeries k) :=
  (toField k).comp (PowerSeries.map HahnSeries.C)

/-- The element `x = y⁻¹` of `k((y))((t))`. -/
noncomputable def xF : LaurentSeries (LaurentSeries k) :=
  toField k (PowerSeries.C (single (-1 : ℤ) 1))

/-- The element `y` of `k((y))((t))`. -/
noncomputable def yF : LaurentSeries (LaurentSeries k) :=
  toField k (PowerSeries.C (single (1 : ℤ) 1))

lemma xF_mul_yF : xF k * yF k = 1 := by
  rw [xF, yF, ← map_mul, ← map_mul, single_mul_single, neg_add_cancel, one_mul, single_zero_one,
    map_one, map_one]

lemma mapU_comp_map_C : (mapU k).comp (PowerSeries.map Polynomial.C) =
    PowerSeries.map HahnSeries.C := by
  rw [mapU, ← PowerSeries.map_comp]
  congr 1
  ext a
  simp [invX]

lemma mapP_comp_map_C : (mapP k).comp (PowerSeries.map PowerSeries.C) =
    PowerSeries.map HahnSeries.C := by
  rw [mapP, ← PowerSeries.map_comp]
  congr 1
  ext a
  simp

/-- A polynomial in `x` over `k⟦t⟧`, evaluated in `k((y))((t))`. -/
lemma toField_mapU_polyX (p : Polynomial (PowerSeries k)) :
    toField k (mapU k (polyX k p)) = p.eval₂ (constF k) (xF k) := by
  rw [polyX, Polynomial.coe_eval₂RingHom, Polynomial.hom_eval₂, Polynomial.hom_eval₂,
    mapU_comp_map_C]
  congr 1
  simp [xF, mapU, invX]

/-- A polynomial in `y` over `k⟦t⟧`, evaluated in `k((y))((t))`. -/
lemma toField_mapP_polyY (p : Polynomial (PowerSeries k)) :
    toField k (mapP k (polyY k p)) = p.eval₂ (constF k) (yF k) := by
  rw [polyY, Polynomial.coe_eval₂RingHom, Polynomial.hom_eval₂, Polynomial.hom_eval₂,
    mapP_comp_map_C]
  congr 1
  simp [yF, mapP]

lemma coeff_invX_neg (p : Polynomial k) (j : ℕ) : (invX k p).coeff (-(j : ℤ)) = p.coeff j := by
  induction p using Polynomial.induction_on' with
  | add p q hp hq => rw [map_add, HahnSeries.coeff_add, hp, hq, Polynomial.coeff_add]
  | monomial n a =>
    rw [invX_monomial, HahnSeries.coeff_single, Polynomial.coeff_monomial]
    simp only [neg_inj, Nat.cast_inj]
    split_ifs <;> simp_all [eq_comm]

lemma coeff_polyX_monomial (j : ℕ) (c : PowerSeries k) (n : ℕ) :
    PowerSeries.coeff n (polyX k (Polynomial.monomial j c)) =
      Polynomial.monomial j (PowerSeries.coeff n c) := by
  rw [polyX, Polynomial.coe_eval₂RingHom, Polynomial.eval₂_monomial, ← map_pow, coeff_mul_C,
    coeff_map, Polynomial.C_mul_X_pow_eq_monomial]

/-- An element of `k[x]⟦t⟧` whose coefficients have degree `≤ L` is a polynomial in `x` over
`k⟦t⟧`. -/
lemma exists_polyX_eq_of_natDegree_le (L : ℕ) (a : PowerSeries (Polynomial k))
    (ha : ∀ n, (PowerSeries.coeff n a).natDegree ≤ L) :
    ∃ p : Polynomial (PowerSeries k), polyX k p = a := by
  refine ⟨∑ j ∈ Finset.range (L + 1),
    Polynomial.monomial j (PowerSeries.mk fun n ↦ (PowerSeries.coeff n a).coeff j), ?_⟩
  ext n : 1
  rw [map_sum, map_sum]
  simp only [coeff_polyX_monomial, coeff_mk]
  exact (Polynomial.as_sum_range' _ _ (Nat.lt_succ_of_le (ha n))).symm

/-- An element of `k[x]⟦t⟧` which, in `k((y))⟦t⟧`, is `y^{-L}` times an element of `k⟦y⟧⟦t⟧`, is
a polynomial in `x` (of degree `≤ L`) over `k⟦t⟧`: the formal analogue of
`H⁰(ℙ¹, 𝒪(L·∞)) = k[x]_{≤ L}`. -/
lemma exists_polyX_eq_of_mapU_eq (L : ℕ) {a : PowerSeries (Polynomial k)}
    {b : PowerSeries (PowerSeries k)}
    (h : mapU k a = PowerSeries.C (single (-(L : ℤ)) 1) * mapP k b) :
    ∃ p : Polynomial (PowerSeries k), polyX k p = a := by
  refine exists_polyX_eq_of_natDegree_le k L a fun n ↦
    Polynomial.natDegree_le_iff_coeff_eq_zero.mpr fun j hj ↦ ?_
  have hj : L < j := by exact_mod_cast hj
  have hn := congrArg (PowerSeries.coeff n) h
  rw [mapU, PowerSeries.coeff_map, PowerSeries.coeff_C_mul, mapP, PowerSeries.coeff_map] at hn
  have hc := congrArg (fun z ↦ HahnSeries.coeff z (-(j : ℤ))) hn
  simp only [coeff_invX_neg] at hc
  rw [hc, show (-(j : ℤ)) = ((L : ℤ) - j) + (-(L : ℤ)) by ring, coeff_single_mul_add, one_mul,
    PowerSeries.coeff_coe]
  simp [show (L : ℤ) - j < 0 by omega]

lemma coeff_coeff_polyX (p : Polynomial (PowerSeries k)) (n j : ℕ) :
    (PowerSeries.coeff n (polyX k p)).coeff j = PowerSeries.coeff n (p.coeff j) := by
  induction p using Polynomial.induction_on' with
  | add p q hp hq => simp [hp, hq]
  | monomial i c =>
    rw [coeff_polyX_monomial, Polynomial.coeff_monomial, Polynomial.coeff_monomial]
    split_ifs <;> simp

lemma polyX_injective : Function.Injective (polyX k) := by
  rw [injective_iff_map_eq_zero]
  intro p hp
  ext j n
  simpa using (coeff_coeff_polyX k p n j).symm.trans (by rw [hp]; simp)

lemma invX_injective : Function.Injective (invX k) := by
  rw [injective_iff_map_eq_zero]
  intro p hp
  ext j
  simpa [hp] using (coeff_invX_neg k p j).symm

lemma mapU_injective : Function.Injective (mapU k) :=
  PowerSeries.map_injective _ (invX_injective k)

/-- `toField ∘ mapU ∘ polyX` is injective. -/
lemma toField_mapU_polyX_injective :
    Function.Injective fun p ↦ toField k (mapU k (polyX k p)) :=
  ofPowerSeries_injective.comp ((mapU_injective k).comp (polyX_injective k))

/-- `k((t))(x) ⊆ F_U ∩ F_P`. -/
lemma fieldBase_le : fieldBase k ≤ fieldU k ⊓ fieldP k := by
  refine Subfield.closure_le.mpr ?_
  rintro _ ⟨p, rfl⟩
  refine ⟨Subfield.subset_closure ⟨_, rfl⟩, ?_⟩
  change toField k (mapU k (polyX k p)) ∈ fieldP k
  rw [toField_mapU_polyX, Polynomial.eval₂_eq_sum_range]
  refine Subfield.sum_mem _ fun j _ ↦ Subfield.mul_mem _ ?_ (Subfield.pow_mem _ ?_ _)
  · have : constF k (p.coeff j) =
        toField k (mapP k (PowerSeries.map PowerSeries.C (p.coeff j))) := by
      rw [constF, ← mapP_comp_map_C]
      rfl
    rw [this]
    exact Subfield.subset_closure ⟨_, rfl⟩
  · have : xF k = (yF k)⁻¹ := (eq_inv_of_mul_eq_one_left (xF_mul_yF k))
    rw [this]
    exact Subfield.inv_mem _ (toField_C_mem_fieldP k _)

section DivisionU

/-- The coefficients of the Weierstrass division in `k[x]⟦t⟧` by `d`, `d mod t ≠ 0`: the power
series `e = ∑ eₙ tⁿ` with `e₀ = 1` and `d · e` having coefficients of degree `≤ deg (d mod t)`. -/
noncomputable def wdivCoeff (d : PowerSeries (Polynomial k)) : ℕ → Polynomial k
  | 0 => 1
  | n + 1 => -((∑ i : Fin (n + 1), wdivCoeff d i * PowerSeries.coeff (n + 1 - i) d) /
      PowerSeries.constantCoeff d)
decreasing_by exact i.isLt

/-- The coefficients of `d · e` in positive degree are remainders modulo `d mod t`. -/
lemma coeff_mul_wdivCoeff_succ (d : PowerSeries (Polynomial k)) (n : ℕ) :
    PowerSeries.coeff (n + 1) (d * PowerSeries.mk (wdivCoeff k d)) =
      (∑ i ∈ Finset.range (n + 1), wdivCoeff k d i * PowerSeries.coeff (n + 1 - i) d) %
        PowerSeries.constantCoeff d := by
  rw [mul_comm, PowerSeries.coeff_mul, Finset.Nat.sum_antidiagonal_eq_sum_range_succ
    (fun i j ↦ PowerSeries.coeff i (PowerSeries.mk (wdivCoeff k d)) * PowerSeries.coeff j d),
    Finset.sum_range_succ]
  simp only [PowerSeries.coeff_mk, Nat.sub_self, PowerSeries.coeff_zero_eq_constantCoeff]
  rw [EuclideanDomain.mod_eq_sub_mul_div, wdivCoeff, ← Fin.sum_univ_eq_sum_range
    (fun i ↦ wdivCoeff k d i * PowerSeries.coeff (n + 1 - i) d)]
  ring

/-- A non-zero element of `k[x]⟦t⟧` divides a non-zero polynomial in `x` over `k⟦t⟧` (Weierstrass
division by the reduction modulo a power of `t`). -/
lemma exists_polyX_eq_mul (d : PowerSeries (Polynomial k)) (hd : d ≠ 0) :
    ∃ (c : Polynomial (PowerSeries k)) (e : PowerSeries (Polynomial k)), c ≠ 0 ∧
      polyX k c = d * e := by
  set d' := d.divXPowOrder
  have hd' : PowerSeries.constantCoeff d' ≠ 0 :=
    PowerSeries.constantCoeff_divXPowOrder_eq_zero_iff.not.mpr hd
  have hdd : PowerSeries.X ^ d.order.toNat * d' = d := PowerSeries.X_pow_order_mul_divXPowOrder
  set e := PowerSeries.mk (wdivCoeff k d')
  have hbound : ∀ n, (PowerSeries.coeff n (d' * e)).natDegree ≤
      (PowerSeries.constantCoeff d').natDegree := by
    rintro (_ | n)
    · simp [e, wdivCoeff]
    · rw [coeff_mul_wdivCoeff_succ]
      exact Polynomial.natDegree_le_natDegree (Polynomial.degree_mod_lt _ hd').le
  obtain ⟨c, hc⟩ := exists_polyX_eq_of_natDegree_le k _ _ hbound
  have hc0 : c ≠ 0 := by
    rintro rfl
    have h0 := congrArg (PowerSeries.coeff 0) hc
    simp [e, wdivCoeff] at h0
    exact hd' h0.symm
  refine ⟨Polynomial.C (PowerSeries.X ^ d.order.toNat) * c, e,
    mul_ne_zero (by simp) hc0, ?_⟩
  rw [map_mul, hc, polyX, Polynomial.coe_eval₂RingHom, Polynomial.eval₂_C, map_pow,
    PowerSeries.map_X, ← mul_assoc, hdd]

end DivisionU

section DivisionP

/-- Exchanging the two variables of `k⟦y⟧⟦t⟧`, giving `k⟦t⟧⟦y⟧`. -/
noncomputable def swapVars : PowerSeries (PowerSeries k) ≃+* PowerSeries (PowerSeries k) where
  toFun f := PowerSeries.mk fun i ↦ PowerSeries.mk fun j ↦
    PowerSeries.coeff i (PowerSeries.coeff j f)
  invFun f := PowerSeries.mk fun i ↦ PowerSeries.mk fun j ↦
    PowerSeries.coeff i (PowerSeries.coeff j f)
  left_inv f := by ext; simp
  right_inv f := by ext; simp
  map_mul' f g := by
    ext i j
    simp only [PowerSeries.coeff_mk, PowerSeries.coeff_mul, map_sum]
    exact Finset.sum_comm
  map_add' f g := by ext; simp

@[simp]
lemma coeff_coeff_swapVars (f : PowerSeries (PowerSeries k)) (i j : ℕ) :
    PowerSeries.coeff j (PowerSeries.coeff i (swapVars k f)) =
      PowerSeries.coeff i (PowerSeries.coeff j f) := by
  simp [swapVars]

/-- Under the exchange of variables, a polynomial in `y` over `k⟦t⟧` becomes itself. -/
lemma swapVars_polyY (p : Polynomial (PowerSeries k)) :
    swapVars k (polyY k p) = (p : PowerSeries (PowerSeries k)) := by
  rw [polyY, Polynomial.coe_eval₂RingHom, ← RingEquiv.coe_toRingHom, Polynomial.hom_eval₂,
    ← Polynomial.eval₂_C_X_eq_coe]
  congr 1
  · ext a i j
    simp only [RingHom.coe_comp, Function.comp_apply, RingEquiv.coe_toRingHom,
      coeff_coeff_swapVars, PowerSeries.coeff_map, PowerSeries.coeff_C]
    split_ifs <;> simp
  · ext i j
    simp only [RingEquiv.coe_toRingHom, coeff_coeff_swapVars, PowerSeries.coeff_C,
      PowerSeries.coeff_X]
    split_ifs <;> simp_all [PowerSeries.coeff_X]

/-- A non-zero element of `k⟦y, t⟧` divides a non-zero polynomial in `y` over `k⟦t⟧`
(Weierstrass preparation). -/
lemma exists_polyY_eq_mul (d : PowerSeries (PowerSeries k)) (hd : d ≠ 0) :
    ∃ (b : Polynomial (PowerSeries k)) (e : PowerSeries (PowerSeries k)), b ≠ 0 ∧
      polyY k b = d * e := by
  set d' := d.divXPowOrder
  have hd' : PowerSeries.constantCoeff d' ≠ 0 :=
    PowerSeries.constantCoeff_divXPowOrder_eq_zero_iff.not.mpr hd
  have hdd : PowerSeries.X ^ d.order.toNat * d' = d := PowerSeries.X_pow_order_mul_divXPowOrder
  have : IsAdicComplete (IsLocalRing.maximalIdeal (PowerSeries k)) (PowerSeries k) := by
    rw [PowerSeries.maximalIdeal_eq_span_X]
    infer_instance
  have hg : (swapVars k d').map (IsLocalRing.residue (PowerSeries k)) ≠ 0 := by
    obtain ⟨j, hj⟩ : ∃ j, PowerSeries.coeff j (PowerSeries.constantCoeff d') ≠ 0 := by
      by_contra! h
      exact hd' (PowerSeries.ext fun j ↦ by simpa using h j)
    intro h0
    have h1 := congrArg (PowerSeries.coeff j) h0
    rw [PowerSeries.coeff_map, map_zero, IsLocalRing.residue_eq_zero_iff] at h1
    apply h1
    rw [PowerSeries.isUnit_iff_constantCoeff (R := k),
      ← PowerSeries.coeff_zero_eq_constantCoeff_apply,
      coeff_coeff_swapVars, PowerSeries.coeff_zero_eq_constantCoeff_apply]
    exact isUnit_iff_ne_zero.mpr hj
  obtain ⟨b, h, H⟩ := PowerSeries.exists_isWeierstrassFactorization hg
  have hb0 : b ≠ 0 := by
    rintro rfl
    apply hd'
    have : swapVars k d' = 0 := by rw [H.eq_mul]; simp
    have h0 : d' = 0 := (swapVars k).injective (this.trans (map_zero _).symm)
    rw [h0, map_zero]
  obtain ⟨u, hu⟩ := H.isUnit
  have heq := H.eq_mul
  rw [← hu] at heq
  refine ⟨Polynomial.C (PowerSeries.X ^ d.order.toNat) * b, (swapVars k).symm ↑u⁻¹,
    mul_ne_zero (by simp) hb0, ?_⟩
  have hpb : polyY k b = d' * (swapVars k).symm ↑u⁻¹ := by
    apply (swapVars k).injective
    rw [swapVars_polyY, map_mul, RingEquiv.apply_symm_apply, heq, mul_assoc, Units.mul_inv,
      mul_one]
  rw [map_mul, hpb, polyY, Polynomial.coe_eval₂RingHom, Polynomial.eval₂_C, map_pow,
    PowerSeries.map_X, ← mul_assoc, hdd]

end DivisionP

/-- The hard inclusion `F_U ∩ F_P ⊆ k((t))(x)`, assuming that non-zero elements of `k⟦y, t⟧` and of
`k[x]⟦t⟧` divide non-zero polynomials in `y`, resp. `x`, over `k⟦t⟧`. -/
lemma inf_le_fieldBase_of
    (hP : ∀ d : PowerSeries (PowerSeries k), d ≠ 0 → ∃ (b : Polynomial (PowerSeries k))
      (e : PowerSeries (PowerSeries k)), b ≠ 0 ∧ polyY k b = d * e)
    (hU : ∀ d : PowerSeries (Polynomial k), d ≠ 0 → ∃ (c : Polynomial (PowerSeries k))
      (e : PowerSeries (Polynomial k)), c ≠ 0 ∧ polyX k c = d * e) :
    fieldU k ⊓ fieldP k ≤ fieldBase k := by
  rintro f ⟨hfU, hfP⟩
  let φU : PowerSeries (Polynomial k) →+* LaurentSeries (LaurentSeries k) :=
    (toField k).comp (mapU k)
  let φP : PowerSeries (PowerSeries k) →+* LaurentSeries (LaurentSeries k) :=
    (toField k).comp (mapP k)
  obtain ⟨a, d, rfl⟩ := (Subfield.mem_closure_range_iff φP).mp hfP
  obtain ⟨a', d', hf'⟩ := (Subfield.mem_closure_range_iff φU).mp hfU
  by_cases hd : φP d = 0
  · rw [hd, div_zero]
    exact Subfield.zero_mem _
  by_cases hd' : φU d' = 0
  · rw [hd', div_zero] at hf'
    rw [← hf']
    exact Subfield.zero_mem _
  obtain ⟨b, e, hb, hbe⟩ := hP d fun h ↦ hd (by rw [h, map_zero])
  obtain ⟨c, e', hc, hce⟩ := hU d' fun h ↦ hd' (by rw [h, map_zero])
  set F := φP a / φP d with hF
  let ψx : Polynomial (PowerSeries k) → LaurentSeries (LaurentSeries k) :=
    fun p ↦ toField k (mapU k (polyX k p))
  let ψy : Polynomial (PowerSeries k) → LaurentSeries (LaurentSeries k) :=
    fun p ↦ toField k (mapP k (polyY k p))
  have h1 : F * ψy b = φP (a * e) := by
    change F * φP (polyY k b) = _
    rw [hbe, map_mul, map_mul, hF]
    field_simp
  have h2 : F * ψx c = φU (a' * e') := by
    change F * φU (polyX k c) = _
    rw [hce, map_mul, map_mul, ← hf']
    field_simp
  -- `x = y⁻¹`: reversing polynomials
  have hxy := xF_mul_yF k
  have hrevb : ψx b.reverse * yF k ^ b.natDegree = ψy b := by
    let : Invertible (yF k) := ⟨xF k, hxy, by rw [mul_comm, hxy]⟩
    simp only [ψx, ψy, toField_mapU_polyX, toField_mapP_polyY]
    exact Polynomial.eval₂_reverse_mul_pow (constF k) (yF k) b
  have hrevc : ψy c.reverse * xF k ^ c.natDegree = ψx c := by
    let : Invertible (xF k) := ⟨yF k, by rw [mul_comm, hxy], hxy⟩
    simp only [ψx, ψy, toField_mapU_polyX, toField_mapP_polyY]
    exact Polynomial.eval₂_reverse_mul_pow (constF k) (xF k) c
  set L := b.natDegree + c.natDegree
  let A := a' * e' * polyX k b.reverse
  let B := a * e * polyY k c.reverse
  have hA : φU A = F * ψx c * ψx b.reverse := by
    simp only [A, map_mul, ← h2]
    rfl
  have hB : φP B = F * ψy b * ψy c.reverse := by
    simp only [B, map_mul, ← h1]
    rfl
  have hAB : φU A = xF k ^ L * φP B := by
    rw [hA, hB, ← hrevb, ← hrevc]
    have hpow : (xF k * yF k) ^ b.natDegree = 1 := by rw [hxy, one_pow]
    linear_combination (-(F * ψy c.reverse * ψx b.reverse * xF k ^ c.natDegree)) * hpow
  have hxL : xF k ^ L = toField k (PowerSeries.C (single (-(L : ℤ)) 1)) := by
    rw [xF, ← map_pow, ← map_pow, single_pow, one_pow]
    congr 3
    simp
  rw [hxL] at hAB
  have hAB' : mapU k A = PowerSeries.C (single (-(L : ℤ)) 1) * mapP k B := by
    change toField k (mapU k A) = toField k (PowerSeries.C _) * toField k (mapP k B) at hAB
    rw [← map_mul] at hAB
    exact ofPowerSeries_injective hAB
  obtain ⟨p, hp⟩ := exists_polyX_eq_of_mapU_eq k L hAB'
  have hc0 : ψx c ≠ 0 := fun h ↦ hc (toField_mapU_polyX_injective k (by simpa [ψx] using h))
  have hb0 : ψx b.reverse ≠ 0 := fun h ↦ hb (Polynomial.reverse_eq_zero.mp
    (toField_mapU_polyX_injective k (by simpa [ψx] using h)))
  have hFeq : F = ψx p / (ψx c * ψx b.reverse) := by
    have : ψx p = F * ψx c * ψx b.reverse := by
      rw [← hA]
      simp only [ψx, hp]
      rfl
    rw [this]
    field_simp
  rw [hFeq]
  refine Subfield.div_mem _ (Subfield.subset_closure ⟨p, rfl⟩)
    (Subfield.mul_mem _ (Subfield.subset_closure ⟨c, rfl⟩) (Subfield.subset_closure ⟨_, rfl⟩))

/-- **`F_U ∩ F_P = k((t))(x)`** on `ℙ¹` over `k⟦t⟧` (Harbater–Hartmann). -/
theorem fieldU_inf_fieldP : fieldU k ⊓ fieldP k = fieldBase k :=
  le_antisymm (inf_le_fieldBase_of k (exists_polyY_eq_mul k) (exists_polyX_eq_mul k))
    (fieldBase_le k)

/-- **Galois patching over `k((t))(x)`**, split case (Harbater; Harbater–Hartmann): a finite group
`G` generated by subgroups `H₁, H₂` is a Galois group over the rational function field
`k((t))(x)` (`fieldBase`) as soon as `H₁` is the Galois group of an extension of
`F_U = Frac k[x]⟦t⟧` and `H₂` that of an extension of `F_P = Frac k⟦y, t⟧` (`y = 1/x`), both
contained in `k((y))((t))`. -/
theorem exists_isGaloisGroup_fieldBase (G : Type v) [Group G] [Finite G]
    {H₁ H₂ : Subgroup G} (hH : H₁ ⊔ H₂ = ⊤)
    (E₁ : IntermediateField (fieldU k) (LaurentSeries (LaurentSeries k)))
    (E₂ : IntermediateField (fieldP k) (LaurentSeries (LaurentSeries k)))
    [IsGalois (fieldU k) E₁] [FiniteDimensional (fieldU k) E₁]
    [IsGalois (fieldP k) E₂] [FiniteDimensional (fieldP k) E₂]
    (ρ₁ : H₁ ≃* (E₁ ≃ₐ[fieldU k] E₁)) (ρ₂ : H₂ ≃* (E₂ ≃ₐ[fieldP k] E₂)) :
    ∃ (E : Type (max u v)) (_ : Field E) (_ : Algebra (fieldBase k) E)
      (_ : MulSemiringAction G E), IsGaloisGroup G (fieldBase k) E := by
  rw [← fieldU_inf_fieldP k]
  exact exists_isGaloisGroup k G hH E₁ E₂ ρ₁ ρ₂

end PatchingProjectiveLine
