/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import Mathlib.FieldTheory.KummerPolynomial
import Mathlib.FieldTheory.PurelyInseparable.Basic
import Mathlib.RingTheory.Kaehler.JacobiZariski
import SGA.Foundations.Fields.SeparablyGenerated

/-!
# MacLane's criterion and Cartier's criterion

Let `k` be a field of exponential characteristic `p`. For a field extension `K / k` we consider
*MacLane's condition*: every `k`-linearly independent family `(sᵢ)` of `K` stays linearly
independent after raising to the `p`-th power (equivalently, `k` and `Kᵖ` are linearly disjoint
over `kᵖ`, or `K ⊗_k k^{1/p}` is reduced). We prove:

- `LinearIndependent.pow_of_isReduced_tensorProduct`: if `L ⊗_k K` is reduced for a field `L`
  over `k` in which every element of `k` is a `p`-th power (for instance `L` perfect or
  algebraically closed), MacLane's condition holds.
- `KaehlerDifferential.exists_pow_eq_of_D_eq_zero`: in a field `k` of characteristic `p > 0`, an
  element `c` with `dc = 0` in `Ω[k⁄ℤ]` is a `p`-th power (a special case of Cartier's theorem
  on `p`-bases).
- `Algebra.FormallySmooth.linearIndependent_pow`: a formally smooth field extension satisfies
  MacLane's condition (Cartier's criterion; EGA 0_IV 21.4, Matsumura Thm 26.9). The proof uses
  the Jacobi–Zariski sequence `H₁(L_{K/k}) → K ⊗_k Ω_k → Ω_K` over `ℤ`.
- `Algebra.IsSeparablyGenerated.of_linearIndepOn_pow`: for finitely generated `K / k`,
  MacLane's condition implies that `K` is separably generated (mathlib, Stacks 030W).
- `Algebra.isReduced_tensorProduct_of_linearIndepOn_pow`: for arbitrary `K / k`, MacLane's
  condition implies that `L ⊗_k K` is reduced for every field `L` over `k`.
-/

open TensorProduct KaehlerDifferential Polynomial

section Cartier

/-- In a field `k` of characteristic `p > 0`, if `dc = 0` in `Ω[k⁄ℤ]` then `c` is a `p`-th power.

Proof: a maximal subfield `E ⊇ kᵖ` not containing `c` satisfies `k = E(c)`, a purely inseparable
extension of degree `p`; it is not separable, so `Ω[k⁄E] ≠ 0`, while `Ω[k⁄E]` is generated by the
image of `dc`. -/
theorem KaehlerDifferential.exists_pow_eq_of_D_eq_zero {k : Type*} [Field k] (p : ℕ)
    [hp : Fact p.Prime] [CharP k p] {c : k} (hc : D ℤ k c = 0) : ∃ e, e ^ p = c := by
  by_contra! hne
  let F : Subfield k := (frobenius k p).fieldRange
  let S : Set (Subfield k) := {E | F ≤ E ∧ c ∉ E}
  obtain ⟨E, -, hE⟩ := zorn_le_nonempty₀ S (fun ch hch hchain y hy ↦ ⟨sSup ch,
      ⟨(hch hy).1.trans (le_sSup hy), fun hc' ↦ by
        obtain ⟨z, hz, hcz⟩ := (Subfield.mem_sSup_of_directedOn ⟨y, hy⟩
          hchain.directedOn).mp hc'
        exact (hch hz).2 hcz⟩, fun z hz ↦ le_sSup hz⟩) F
    ⟨le_rfl, fun ⟨e, he⟩ ↦ hne e he⟩
  have hFE : F ≤ E := hE.1.1
  have hcE : c ∉ E := hE.1.2
  have hpow (y : k) : y ^ p ∈ E := hFE ⟨y, rfl⟩
  have hint (y : k) : IsIntegral E y := ⟨X ^ p - C ⟨y ^ p, hpow y⟩,
    monic_X_pow_sub_C _ hp.out.ne_zero, by simp [sub_eq_zero]; rfl⟩
  -- adjoining an element outside `E` gives an extension of degree `p`
  have hfin (y : k) (hy : y ∉ E) : Module.finrank E (IntermediateField.adjoin E {y}) = p := by
    rw [IntermediateField.adjoin.finrank (hint y)]
    have hirr : Irreducible (X ^ p - C (⟨y ^ p, hpow y⟩ : E)) := by
      refine X_pow_sub_C_irreducible_of_prime hp.out fun b hb ↦ hy ?_
      have : ((b : k) - y) ^ p = 0 := by
        rw [sub_pow_char, sub_eq_zero]; exact congrArg Subtype.val hb
      rw [← sub_eq_zero.mp (pow_eq_zero_iff hp.out.ne_zero |>.mp this)]
      exact b.2
    rw [← minpoly.eq_of_irreducible_of_monic hirr (by simp [sub_eq_zero]; rfl)
      (monic_X_pow_sub_C _ hp.out.ne_zero), natDegree_X_pow_sub_C]
  -- by maximality of `E`, every element of `k` lies in `E(c)`
  have hle (y : k) : E ≤ (IntermediateField.adjoin E {y}).toSubfield := fun x hx ↦
    (IntermediateField.adjoin E {y}).algebraMap_mem ⟨x, hx⟩
  have htop : IntermediateField.adjoin E {c} = ⊤ := by
    refine eq_top_iff.mpr fun y _ ↦ ?_
    by_cases hy : y ∈ E
    · exact (IntermediateField.adjoin E {c}).algebraMap_mem ⟨y, hy⟩
    have hcy : c ∈ IntermediateField.adjoin E {y} := by
      by_contra hcy
      exact hy (hE.2 ⟨hFE.trans (hle y), hcy⟩ (hle y)
        (IntermediateField.mem_adjoin_simple_self E y))
    have hsub : IntermediateField.adjoin E {c} ≤ IntermediateField.adjoin E {y} :=
      IntermediateField.adjoin_simple_le_iff.mpr hcy
    have : FiniteDimensional E (IntermediateField.adjoin E {y}) :=
      IntermediateField.adjoin.finiteDimensional (hint y)
    rw [IntermediateField.eq_of_le_of_finrank_eq hsub ((hfin c hcE).trans (hfin y hy).symm)]
    exact IntermediateField.mem_adjoin_simple_self E y
  -- so `k / E` is finite and purely inseparable, hence not separable
  have : FiniteDimensional E (IntermediateField.adjoin E {c}) :=
    IntermediateField.adjoin.finiteDimensional (hint c)
  have : Module.Finite E k := by
    rw [htop] at this
    exact .equiv (IntermediateField.topEquiv (F := E) (E := k)).toLinearEquiv
  have : IsPurelyInseparable E k :=
    (isPurelyInseparable_iff_pow_mem E p).mpr fun y ↦ ⟨1, ⟨y ^ p, hpow y⟩, by simp; rfl⟩
  have hsep : ¬ Algebra.IsSeparable E k := fun _ ↦ by
    obtain ⟨x, hx⟩ := IsPurelyInseparable.surjective_algebraMap_of_isSeparable E k c
    exact hcE (hx ▸ x.2)
  -- but `Ω[k⁄E]` is generated by the image of `dc`, which vanishes
  have hDc : D E k c = 0 := by
    simpa [hc] using (map_D ℤ E k k c).symm
  apply hsep
  rw [← Algebra.FormallyUnramified.iff_isSeparable]
  refine ⟨subsingleton_of_forall_eq 0 fun ω ↦ ?_⟩
  have hadj : Algebra.adjoin E {c} = ⊤ := by
    rw [← IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic (hint c).isAlgebraic, htop,
      IntermediateField.top_toSubalgebra]
  have hD (y : k) : D E k y = 0 :=
    (D E k).eqOn_adjoin (D2 := 0) (s := {c}) (by simpa using hDc)
      (hadj ▸ Algebra.mem_top : y ∈ Algebra.adjoin E {c})
  have hbot : Submodule.span k (Set.range (D E k)) = ⊥ := by
    rw [Submodule.span_eq_bot]
    rintro _ ⟨y, rfl⟩
    exact hD y
  have hω : ω ∈ Submodule.span k (Set.range (D E k)) := by
    rw [span_range_derivation]; trivial
  rwa [hbot, Submodule.mem_bot] at hω

/-- In a field `k` of characteristic `p > 0`, the kernel of `d : k → Ω[k⁄ℤ]` is `kᵖ`. -/
theorem KaehlerDifferential.D_eq_zero_iff_exists_pow_eq {k : Type*} [Field k] (p : ℕ)
    [hp : Fact p.Prime] [CharP k p] {c : k} : D ℤ k c = 0 ↔ ∃ e, e ^ p = c := by
  refine ⟨exists_pow_eq_of_D_eq_zero p, ?_⟩
  rintro ⟨e, rfl⟩
  rw [Derivation.leibniz_pow, ← Nat.cast_smul_eq_nsmul k, CharP.cast_eq_zero, zero_smul]

/-- If `v` is linearly independent and `∑ᵢ vᵢ ⊗ nᵢ = 0` with `N` flat, then all `nᵢ` vanish. -/
theorem LinearIndependent.eq_zero_of_sum_tmul_eq_zero {R M N ι : Type*} [CommRing R]
    [AddCommGroup M] [Module R M] [AddCommGroup N] [Module R N] [Module.Flat R N] [Fintype ι]
    {v : ι → M} (hv : LinearIndependent R v) {n : ι → N} (h : ∑ i, v i ⊗ₜ[R] n i = 0) (i : ι) :
    n i = 0 := by
  classical
  have hinj := Module.Flat.rTensor_preserves_injective_linearMap (M := N) _ hv
  let x : (ι →₀ R) ⊗[R] N := ∑ j, Finsupp.single j 1 ⊗ₜ n j
  have hx : x = 0 := hinj (by simpa [x, map_sum] using h)
  have := congrArg (fun y ↦ TensorProduct.finsuppScalarLeft R N ι y i) hx
  simpa [x, finsuppScalarLeft_apply_tmul_apply, Finsupp.single_apply] using this

/-- If `S` is formally smooth over `R`, then for any `R₀ → R` the map `S ⊗_R Ω[R⁄R₀] → Ω[S⁄R₀]`
is injective (Jacobi–Zariski, since `H₁(L_{S/R}) = 0`). -/
theorem Algebra.FormallySmooth.injective_mapBaseChange (R₀ R S : Type*) [CommRing R₀] [CommRing R]
    [CommRing S] [Algebra R₀ R] [Algebra R₀ S] [Algebra R S] [IsScalarTower R₀ R S]
    [Algebra.FormallySmooth R S] : Function.Injective (mapBaseChange R₀ R S) := by
  rw [← LinearMap.ker_eq_bot, (H1Cotangent.exact_δ_mapBaseChange R₀ R S).linearMap_ker_eq,
    LinearMap.range_eq_bot]
  ext x
  simp [Subsingleton.elim x 0]

/-- Cartier's criterion, the implication used here: if `K ⊗_k Ω[k⁄ℤ] → Ω[K⁄ℤ]` is injective
(e.g. `K` formally smooth over `k`), then every `k`-linearly independent finite family of `K`
stays linearly independent after raising to the `p`-th power. -/
theorem linearIndependent_pow_of_injective_mapBaseChange {k K : Type*} [Field k] [Field K]
    [Algebra k K] (p : ℕ) [hp : Fact p.Prime] [CharP k p]
    (h : Function.Injective (mapBaseChange ℤ k K)) :
    ∀ {n : ℕ} (v : Fin n → K), LinearIndependent k v → LinearIndependent k (v · ^ p) := by
  have : CharP K p := charP_of_injective_algebraMap (algebraMap k K).injective p
  have hDpow (x : K) : D ℤ K (x ^ p) = 0 := by
    rw [Derivation.leibniz_pow, ← Nat.cast_smul_eq_nsmul K, CharP.cast_eq_zero, zero_smul]
  intro n
  induction n with
  | zero => intro v _; exact linearIndependent_empty_type
  | succ n ih =>
    intro v hv
    rw [linearIndependent_finSucc] at hv ⊢
    set w := Fin.tail v
    have hw : LinearIndependent k (w · ^ p) := ih w hv.1
    refine ⟨hw, fun hmem ↦ hv.2 ?_⟩
    obtain ⟨c, hc⟩ := Submodule.mem_span_range_iff_exists_fun k |>.mp hmem
    replace hc : ∑ i, c i • w i ^ p = v 0 ^ p := hc
    -- differentiating `v₀ ^ p = ∑ cᵢ wᵢ ^ p` gives `∑ wᵢ ^ p ⊗ dcᵢ = 0`
    have hsum : ∑ i, (w i ^ p) ⊗ₜ[k] D ℤ k (c i) = 0 := by
      apply h
      have := congrArg (D ℤ K) hc
      rw [hDpow, map_sum] at this
      rw [map_zero, map_sum, ← this]
      refine Finset.sum_congr rfl fun i _ ↦ ?_
      rw [mapBaseChange_tmul, map_D, Algebra.smul_def, Derivation.leibniz, hDpow, smul_zero,
        zero_add]
    -- hence every `cᵢ` is a `p`-th power, and `v₀` is a combination of the `wᵢ`
    have hc0 (i) : D ℤ k (c i) = 0 := hw.eq_zero_of_sum_tmul_eq_zero hsum i
    choose e he using fun i ↦ exists_pow_eq_of_D_eq_zero p (hc0 i)
    refine Submodule.mem_span_range_iff_exists_fun k |>.mpr ⟨e, ?_⟩
    apply frobenius_inj K p
    simp only [frobenius_def, sum_pow_char, smul_pow, he]
    simpa using hc

end Cartier

section MacLane

variable {k K : Type*} [Field k] [Field K] [Algebra k K]

/-- MacLane's condition for an arbitrary index type follows from the case of finite families
indexed by `Fin n`. -/
theorem linearIndependent_pow_of_forall_fin (p : ℕ)
    (H : ∀ {n : ℕ} (v : Fin n → K), LinearIndependent k v → LinearIndependent k (v · ^ p))
    {ι : Type*} {v : ι → K} (hv : LinearIndependent k v) : LinearIndependent k (v · ^ p) := by
  rw [linearIndependent_iff_finset_linearIndependent] at hv ⊢
  intro s
  let e := s.equivFin
  have := (H _ ((hv s).comp e.symm e.symm.injective)).comp e e.injective
  convert this using 1
  ext x
  simp

/-- MacLane's condition stated for finite subsets (as in mathlib) implies it for arbitrary
families. -/
theorem linearIndependent_pow_of_linearIndepOn_pow (p : ℕ)
    (H : ∀ s : Finset K, LinearIndepOn k id (s : Set K) → LinearIndepOn k (· ^ p) (s : Set K))
    {ι : Type*} {v : ι → K} (hv : LinearIndependent k v) : LinearIndependent k (v · ^ p) := by
  classical
  rw [linearIndependent_iff_finset_linearIndependent]
  intro s
  have h1 : LinearIndepOn k id ((s.image v : Finset K) : Set K) := by
    rw [Finset.coe_image]; exact (hv.linearIndepOn _).id_image
  have h2 := H _ h1
  rw [Finset.coe_image] at h2
  exact h2.comp_of_image hv.injective.injOn

/-- A formally smooth field extension satisfies MacLane's condition: `k`-linearly independent
families of `K` stay linearly independent after raising to the `p`-th power, `p` the exponential
characteristic (Cartier's criterion; EGA 0_IV 21.4.2, Matsumura Thm 26.9). -/
theorem Algebra.FormallySmooth.linearIndependent_pow [Algebra.FormallySmooth k K] (p : ℕ)
    [ExpChar k p] {ι : Type*} {v : ι → K} (hv : LinearIndependent k v) :
    LinearIndependent k (v · ^ p) := by
  rcases ‹ExpChar k p› with _ | hprime
  · simpa using hv
  · have : Fact p.Prime := ⟨hprime⟩
    exact linearIndependent_pow_of_forall_fin p
      (linearIndependent_pow_of_injective_mapBaseChange p
        (Algebra.FormallySmooth.injective_mapBaseChange ℤ k K)) hv

/-- The key computation behind MacLane's criterion: let `L` be a field over `k` with `L ⊗_k K`
reduced, `(vᵢ)` a `k`-linearly independent family of `K` and `∑ gᵢ vᵢ ^ p = 0`, `p` the exponential
characteristic. If every `gᵢ` is a `p`-th power `eᵢ ^ p` in `L`, then all `gᵢ` vanish: indeed
`z = ∑ eᵢ ⊗ vᵢ` satisfies `z ^ p = 0`. -/
theorem LinearIndependent.eq_zero_of_sum_smul_pow_eq_zero {L : Type*} [Field L] [Algebra k L]
    (p : ℕ) [ExpChar k p] [IsReduced (L ⊗[k] K)] {ι : Type*} {v : ι → K}
    (hv : LinearIndependent k v) {s : Finset ι} {g : ι → k} (hg : ∑ i ∈ s, g i • v i ^ p = 0)
    {e : ι → L} (he : ∀ i ∈ s, e i ^ p = algebraMap k L (g i)) : ∀ i ∈ s, g i = 0 := by
  classical
  have : ExpChar (L ⊗[k] K) p := expChar_of_injective_algebraMap
    (show Function.Injective (algebraMap k (L ⊗[k] K)) from
      (Algebra.TensorProduct.includeLeft_injective (R := k) (S := k) (A := L) (B := K)
        (algebraMap k K).injective).comp (algebraMap k L).injective) p
  intro i hi
  -- `z = ∑ eᵢ ⊗ vᵢ` satisfies `z ^ p = 1 ⊗ ∑ gᵢ vᵢ ^ p = 0`
  set z : L ⊗[k] K := ∑ j ∈ s, e j ⊗ₜ v j
  have hz : z ^ p = 0 := by
    have : z ^ p = ∑ j ∈ s, (e j ^ p) ⊗ₜ (v j ^ p) := by
      rw [← frobenius_def, map_sum]
      simp only [frobenius_def, Algebra.TensorProduct.tmul_pow]
    rw [this, Finset.sum_congr rfl fun j hj ↦ by rw [he j hj]]
    simp_rw [Algebra.algebraMap_eq_smul_one, TensorProduct.smul_tmul,
      ← TensorProduct.tmul_sum, hg, TensorProduct.tmul_zero]
  have hz0 : z = 0 := IsReduced.eq_zero z ⟨p, hz⟩
  -- the `1 ⊗ vᵢ` are `L`-linearly independent, so all `eᵢ` vanish
  have hv' : LinearIndependent L fun j ↦ (1 : L) ⊗ₜ[k] v j :=
    Module.Flat.linearIndependent_one_tmul hv
  have := linearIndependent_iff'.mp hv' s e (by
    simpa [z, TensorProduct.smul_tmul'] using hz0) i hi
  have h0 : algebraMap k L (g i) = 0 := by
    rw [← he i hi, this, zero_pow (expChar_ne_zero k p)]
  exact (map_eq_zero_iff _ (algebraMap k L).injective).mp h0

/-- If `L ⊗_k K` is reduced, where `L` is a field over `k` in which every element of `k` is a
`p`-th power (`p` the exponential characteristic; e.g. `L` perfect, or `L = k^{1/p}`), then
`k`-linearly independent families of `K` stay linearly independent after raising to the `p`-th
power. -/
theorem LinearIndependent.pow_of_isReduced_tensorProduct {L : Type*} [Field L] [Algebra k L]
    (p : ℕ) [ExpChar k p] (hL : ∀ c : k, ∃ e : L, e ^ p = algebraMap k L c)
    [IsReduced (L ⊗[k] K)] {ι : Type*} {v : ι → K} (hv : LinearIndependent k v) :
    LinearIndependent k (v · ^ p) := by
  choose e he using hL
  rw [linearIndependent_iff']
  intro s g hg
  exact hv.eq_zero_of_sum_smul_pow_eq_zero p (L := L) hg (e := fun i ↦ e (g i)) fun i _ ↦ he _

end MacLane

namespace Algebra

variable {k K : Type*} [Field k] [Field K] [Algebra k K]

/-- MacLane's criterion (Stacks 030W, mathlib): a finitely generated extension `K / k`
satisfying MacLane's condition is separably generated. -/
theorem IsSeparablyGenerated.of_linearIndepOn_pow [EssFiniteType k K] (p : ℕ) [ExpChar k p]
    (H : ∀ s : Finset K, LinearIndepOn k _root_.id (s : Set K) →
      LinearIndepOn k (· ^ p) (s : Set K)) :
    IsSeparablyGenerated k K := by
  rcases ‹ExpChar k p› with _ | hprime
  · exact .of_charZero
  · obtain ⟨s, hs, H⟩ :=
      exists_isTranscendenceBasis_and_isSeparable_of_linearIndepOn_pow_of_essFiniteType p hprime H
    exact ⟨s, hs, H⟩

open scoped IntermediateField.algebraAdjoinAdjoin in
/-- An intermediate field generated by finitely many elements is essentially of finite type. -/
lemma essFiniteType_adjoin_finset (t : Finset K) :
    EssFiniteType k (IntermediateField.adjoin k (t : Set K)) := by
  have : FiniteType k (Algebra.adjoin k (t : Set K)) := .adjoin_of_finite t.finite_toSet
  have : EssFiniteType (Algebra.adjoin k (t : Set K)) (IntermediateField.adjoin k (t : Set K)) :=
    .of_isLocalization _ (nonZeroDivisors _)
  exact .comp _ (Algebra.adjoin k (t : Set K)) _

/-- MacLane's condition implies that `L ⊗_k K` is reduced for every field `L` over `k`, for an
arbitrary (not necessarily finitely generated) extension `K / k`: reduce to finitely generated
subextensions, which are separably generated. -/
theorem isReduced_tensorProduct_of_linearIndepOn_pow (p : ℕ) [ExpChar k p]
    (H : ∀ s : Finset K, LinearIndepOn k _root_.id (s : Set K) →
      LinearIndepOn k (· ^ p) (s : Set K))
    (L : Type*) [Field L] [Algebra k L] : IsReduced (L ⊗[k] K) := by
  refine IsReduced.tensorProduct_of_flat_of_forall_fg fun B ⟨t, ht⟩ ↦ ?_
  let K' := IntermediateField.adjoin k (t : Set K)
  have : EssFiniteType k K' := essFiniteType_adjoin_finset t
  have H' : ∀ s : Finset K', LinearIndepOn k _root_.id (s : Set K') →
      LinearIndepOn k (· ^ p) (s : Set K') := by
    intro s hs
    have := linearIndependent_pow_of_linearIndepOn_pow p H
      (hs.map' K'.val.toLinearMap (LinearMap.ker_eq_bot.mpr K'.val.injective))
    exact LinearIndependent.of_comp K'.val.toLinearMap this
  have : IsReduced (L ⊗[k] K') :=
    (IsSeparablyGenerated.of_linearIndepOn_pow p H').isReduced_tensorProduct L
  have hle : B ≤ K'.toSubalgebra := ht ▸ IntermediateField.algebra_adjoin_le_adjoin k _
  exact isReduced_of_injective (Algebra.TensorProduct.map (AlgHom.id L L)
    (Subalgebra.inclusion hle)) (Module.Flat.lTensor_preserves_injective_linearMap (M := L)
      (Subalgebra.inclusion hle).toLinearMap (Subalgebra.inclusion_injective hle))

end Algebra
