/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import Mathlib.FieldTheory.Minpoly.Field
import Mathlib.FieldTheory.PrimitiveElement
import Mathlib.RingTheory.Etale.Field
import Mathlib.RingTheory.Ideal.Quotient.Operations

/-!
# Primitive elements of finite étale algebras over an infinite field

The proof of I.7.5 uses that a finite étale algebra `L` over an infinite field `k` is generated
by one element. Write `L = ∏ Lᵢ` with `Lᵢ/k` finite separable, pick primitive elements `αᵢ`
and shift them by constants `cᵢ ∈ k` so that the minimal polynomials `Pᵢ` of the `αᵢ + cᵢ` are
pairwise distinct (only finitely many `c` are excluded at each step, and `k` is infinite).
The `Pᵢ` are then pairwise coprime, and the Chinese remainder theorem shows that
`k[t] → ∏ Lᵢ`, `t ↦ (αᵢ + cᵢ)ᵢ`, is surjective.

Over a finite field this fails (`𝔽₂ × 𝔽₂ × 𝔽₂` is not generated by one element).
-/

universe u

open Polynomial

namespace SGA.SGA1.ExposeI

variable {k : Type*} [Field k]

/-- For a nonzero polynomial `P` over `k` and `α` in a field extension `K` of `k`, only
finitely many `c ∈ k` satisfy `P(α + c) = 0`. -/
lemma finite_setOf_aeval_add_algebraMap_eq_zero {K : Type*} [Field K] [Algebra k K]
    {P : k[X]} (hP : P.Monic) (α : K) :
    {c : k | aeval (α + algebraMap k K c) P = 0}.Finite := by
  let Q : K[X] := (P.map (algebraMap k K)).comp (X + C α)
  have hQ : Q ≠ 0 :=
    ((hP.map _).comp (monic_X_add_C α) (by rw [natDegree_X_add_C]; exact one_ne_zero)).ne_zero
  refine ((finite_setOfPred_isRoot hQ).preimage
    (FaithfulSMul.algebraMap_injective k K).injOn).subset fun c hc ↦ ?_
  simp only [Set.mem_ofPred_eq, Set.mem_preimage] at hc ⊢
  change IsRoot ((P.map (algebraMap k K)).comp (X + C α)) (algebraMap k K c)
  rw [IsRoot, eval_comp, eval_add, eval_X, eval_C, eval_map_algebraMap, add_comm]
  exact hc

/-- Over an infinite field `k`, a finite product of finite separable field extensions of `k`
is generated by one element. -/
theorem exists_adjoin_pi_eq_top [Infinite k] {ι : Type*} [Finite ι] (L : ι → Type*)
    [∀ i, Field (L i)] [∀ i, Algebra k (L i)] [∀ i, FiniteDimensional k (L i)]
    [∀ i, Algebra.IsSeparable k (L i)] : ∃ ξ : Π i, L i, Algebra.adjoin k {ξ} = ⊤ := by
  classical
  have := Fintype.ofFinite ι
  -- primitive elements of the factors
  have hα (i : ι) : ∃ α : L i, Algebra.adjoin k {α} = ⊤ := by
    obtain ⟨α, hα⟩ := Field.exists_primitive_element k (L i)
    refine ⟨α, ?_⟩
    rw [← IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic
      (Algebra.IsAlgebraic.isAlgebraic α), hα, IntermediateField.top_toSubalgebra]
  choose α hα using hα
  let P (i : ι) (c : k) : k[X] := minpoly k (α i + algebraMap k (L i) c)
  have hPm (i : ι) (c : k) : (P i c).Monic := minpoly.monic (Algebra.IsIntegral.isIntegral _)
  -- shifts making the minimal polynomials pairwise distinct
  have hc : ∀ s : Finset ι, ∃ c : ι → k, ∀ i ∈ s, ∀ j ∈ s, i ≠ j → P i (c i) ≠ P j (c j) := by
    intro s
    induction s using Finset.induction_on with
    | empty => exact ⟨0, by simp⟩
    | insert a s has ih =>
      obtain ⟨c, hc⟩ := ih
      have hfin : (⋃ j ∈ s, {x : k | aeval (α a + algebraMap k (L a) x) (P j (c j)) = 0}).Finite :=
        s.finite_toSet.biUnion fun j _ ↦ finite_setOf_aeval_add_algebraMap_eq_zero (hPm j _) _
      obtain ⟨x, hx⟩ := hfin.exists_notMem
      simp only [Set.mem_iUnion, Set.mem_ofPred_eq, not_exists] at hx
      have hne (j : ι) (hj : j ∈ s) : P a x ≠ P j (c j) := fun h ↦
        hx j hj (h ▸ minpoly.aeval k _)
      have hs (l : ι) (hl : l ∈ insert a s) (hla : l ≠ a) : l ∈ s :=
        (Finset.mem_insert.mp hl).resolve_left hla
      refine ⟨Function.update c a x, fun i hi j hj hij ↦ ?_⟩
      by_cases hia : i = a <;> by_cases hja : j = a
      · exact absurd (hia.trans hja.symm) hij
      · rw [hia, Function.update_self, Function.update_of_ne hja]
        exact hne j (hs j hj hja)
      · rw [hja, Function.update_self, Function.update_of_ne hia]
        exact (hne i (hs i hi hia)).symm
      · rw [Function.update_of_ne hia, Function.update_of_ne hja]
        exact hc i (hs i hi hia) j (hs j hj hja) hij
  obtain ⟨c, hc⟩ := hc Finset.univ
  let ξ : Π i, L i := fun i ↦ α i + algebraMap k (L i) (c i)
  refine ⟨ξ, eq_top_iff.mpr fun y _ ↦ ?_⟩
  -- each `ξ i` generates `L i`
  have hξ (i : ι) : Function.Surjective (aeval (ξ i) : k[X] →ₐ[k] L i) := by
    rw [← AlgHom.range_eq_top, ← Algebra.adjoin_singleton_eq_range_aeval, eq_top_iff, ← hα i,
      Algebra.adjoin_le_iff, Set.singleton_subset_iff]
    have : α i = ξ i - algebraMap k (L i) (c i) := by simp [ξ]
    rw [this]
    exact sub_mem (Algebra.subset_adjoin rfl) (Subalgebra.algebraMap_mem _ _)
  choose g hg using fun i ↦ hξ i (y i)
  -- the minimal polynomials are pairwise coprime
  have hcop : Pairwise (Function.onFun IsCoprime fun i ↦ Ideal.span {P i (c i)}) := by
    intro i j hij
    rw [Function.onFun, Ideal.isCoprime_span_singleton_iff,
      (minpoly.irreducible (Algebra.IsIntegral.isIntegral (ξ i))).coprime_iff_not_dvd]
    intro hdvd
    exact hc i (Finset.mem_univ _) j (Finset.mem_univ _) hij
      (eq_of_monic_of_associated (hPm i _) (hPm j _)
        ((minpoly.irreducible (Algebra.IsIntegral.isIntegral (ξ i))).associated_of_dvd
          (minpoly.irreducible (Algebra.IsIntegral.isIntegral (ξ j))) hdvd))
  obtain ⟨r, hr⟩ := Ideal.exists_forall_sub_mem_ideal hcop g
  rw [Algebra.adjoin_singleton_eq_range_aeval]
  refine ⟨r, funext fun i ↦ ?_⟩
  have h1 : aeval (ξ i) (r - g i) = 0 := by
    obtain ⟨q, hq⟩ := Ideal.mem_span_singleton.mp (hr i)
    rw [hq, map_mul, minpoly.aeval, zero_mul]
  rw [map_sub, sub_eq_zero, hg] at h1
  rw [← h1]
  exact (aeval_algHom_apply (Pi.evalAlgHom k L i) ξ r).symm

/-- Over an infinite field `k`, a finite étale `k`-algebra is generated by one element. -/
theorem exists_adjoin_eq_top_of_etale [Infinite k] (A : Type u) [CommRing A] [Algebra k A]
    [Algebra.Etale k A] : ∃ ξ : A, Algebra.adjoin k {ξ} = ⊤ := by
  obtain ⟨I, _, Ai, _, _, e, hAi⟩ := (Algebra.Etale.iff_exists_algEquiv_prod k A).mp inferInstance
  have := fun i ↦ (hAi i).1
  have := fun i ↦ (hAi i).2
  obtain ⟨ξ, hξ⟩ := exists_adjoin_pi_eq_top (k := k) Ai
  refine ⟨e.symm ξ, ?_⟩
  rw [← Set.image_singleton, ← AlgEquiv.coe_toAlgHom, Algebra.adjoin_image, hξ, Algebra.map_top,
    AlgHom.range_eq_top]
  exact e.symm.surjective

end SGA.SGA1.ExposeI
