/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import Mathlib.FieldTheory.PrimitiveElement
import Mathlib.RingTheory.AdjoinRoot
import Mathlib.RingTheory.LocalRing.Module
import Mathlib.RingTheory.Adjoin.Polynomial.Basic
import Mathlib.RingTheory.Etale.Locus
import Mathlib.RingTheory.Etale.StandardEtale
import Mathlib.RingTheory.Ideal.GoingUp
import Mathlib.RingTheory.IsAdjoinRoot
import Mathlib.RingTheory.Kaehler.Polynomial
import Mathlib.RingTheory.LocalRing.Etale
import Mathlib.RingTheory.Smooth.Fiber
import Mathlib.RingTheory.Support
import Mathlib.RingTheory.Unramified.LocalStructure
import Mathlib.RingTheory.Unramified.Locus
import Mathlib.RingTheory.TensorProduct.Quotient
import SGA.SGA1.ExposeI.PrimitiveElement

/-!
# SGA 1, Exposé I, §7: local construction of unramified and étale morphisms

SGA's basic local models are the algebras `A[t]/(F)`. If `B` is generated by `u` and
`F(u) = 0`, then `F'(u)` kills `Ω¹_{B/A}`, so `B` is unramified wherever `F'(u)` is
invertible (I.7.1–I.7.2); for `B = A[t]/(F)` the different ideal is exactly `F'(u) B`,
which gives the étaleness criteria I.7.3–I.7.4 for monic `F`. A *separable*
polynomial is a monic `F` with `(F, F') = A[t]`; mathlib's `Polynomial.Separable`
(`IsCoprime F F'`) is exactly this.

I.7.5 is proved in both of SGA's alternatives: when `B` is local, in the unramified case (by
Nakayama, as in SGA) and in the étale case (after mathlib's `IsLocalRing.exists_adjoin_eq_top`);
and when the residue field `k` is infinite, where the étale `k`-algebra `k ⊗_A B` has a
primitive element (`PrimitiveElement`) whose lift generates `B` by Nakayama.

For I.7.6–I.7.8 mathlib proves the Zariski-local form: an algebra of finite type unramified
at `q` is, after inverting an element outside `q`, a quotient of a standard étale algebra
`(A[t]/(F))[1/g]`, and an étale one is standard étale; SGA's statement about the local ring
`B_q` follows by localizing. I.7.8 for schemes is in `LocalStructure`. The technical lemmas
I.7.9–I.7.10 of SGA's proof are not formalized.
-/

universe u

namespace SGA.SGA1.ExposeI

open Algebra Polynomial TensorProduct KaehlerDifferential IsLocalRing

variable {A B : Type u} [CommRing A] [CommRing B] [Algebra A B]

section Monogenic

/-- If `B` is generated over `A` by `u`, then `Ω¹_{B/A}` is generated by `du`. -/
theorem span_D_eq_top_of_adjoin_eq_top {u : B} (hu : Algebra.adjoin A {u} = ⊤) :
    Submodule.span B {D A B u} = ⊤ := by
  rw [_root_.eq_top_iff, ← span_range_derivation, Submodule.span_le]
  rintro _ ⟨b, rfl⟩
  have hb : b ∈ Algebra.adjoin A {u} := hu ▸ trivial
  rw [Algebra.adjoin_singleton_eq_range_aeval] at hb
  obtain ⟨g, rfl⟩ := hb
  rw [AlgHom.toRingHom_eq_coe, RingHom.coe_coe, Derivation.comp_aeval_eq]
  exact Submodule.smul_mem _ _ (Submodule.mem_span_singleton_self _)

/-- I.7.2, first half: if `B` is generated over `A` by `u` and `F(u) = 0`, then
`F'(u)` kills `Ω¹_{B/A}`, i.e. the different ideal contains `F'(u) B`. -/
theorem aeval_derivative_mem_annihilator {u : B} (hu : Algebra.adjoin A {u} = ⊤) {F : A[X]}
    (hF : aeval u F = 0) : aeval u (derivative F) ∈ Module.annihilator B Ω[B⁄A] := by
  rw [← Submodule.annihilator_top, ← span_D_eq_top_of_adjoin_eq_top hu,
    Submodule.mem_annihilator_span_singleton, ← Derivation.comp_aeval_eq, hF, map_zero]

/-- I.7.1: if `B` is generated over `A` by `u`, `F(u) = 0` and `F'(u) ∉ q`, then `B` is
unramified over `A` at `q`. (SGA assumes `A` noetherian and `B` finite; neither is
needed.) -/
theorem isUnramifiedAt_of_aeval_derivative_notMem {u : B} (hu : Algebra.adjoin A {u} = ⊤)
    {F : A[X]} (hF : aeval u F = 0) (q : Ideal B) [q.IsPrime]
    (hq : aeval u (derivative F) ∉ q) : Algebra.IsUnramifiedAt A q := by
  change (⟨q, ‹_›⟩ : PrimeSpectrum B) ∈ unramifiedLocus A B
  rw [unramifiedLocus_eq_compl_support, Set.mem_compl_iff, Module.notMem_support_iff']
  exact fun m ↦ ⟨_, hq, Module.mem_annihilator.mp (aeval_derivative_mem_annihilator hu hF) m⟩


/-- I.7.2, second half: if `A[t]/(F) → B`, `t ↦ u`, is an isomorphism, the different
ideal (the annihilator of `Ω¹_{B/A}`) is exactly `F'(u) B`. -/
theorem annihilator_eq_span_derivative {u : B} {F : A[X]}
    (hsurj : Function.Surjective (aeval u : A[X] →ₐ[A] B))
    (hker : RingHom.ker (aeval u : A[X] →ₐ[A] B) = Ideal.span {F}) :
    Module.annihilator B Ω[B⁄A] = Ideal.span {aeval u (derivative F)} := by
  have hu : Algebra.adjoin A {u} = ⊤ := by
    rw [Algebra.adjoin_singleton_eq_range_aeval, AlgHom.range_eq_top]; exact hsurj
  have hF : aeval u F = 0 := by
    rw [← RingHom.mem_ker]; erw [hker]; exact Ideal.mem_span_singleton_self F
  refine le_antisymm ?_ ((Ideal.span_singleton_le_iff_mem _).mpr
    (aeval_derivative_mem_annihilator hu hF))
  intro x hx
  let : Algebra A[X] B := (aeval u).toRingHom.toAlgebra
  have : IsScalarTower A A[X] B := .of_algebraMap_eq fun a ↦ by
    simp [RingHom.algebraMap_toAlgebra]
  have halg : algebraMap A[X] B = (aeval u).toRingHom := rfl
  -- `x ⊗ dt` lies in the kernel of `B ⊗ Ω_{A[t]} → Ω_B`
  have h0 : mapBaseChange A A[X] B (x ⊗ₜ D A A[X] X) = 0 := by
    rw [mapBaseChange_tmul, map_D, halg]
    simp only [AlgHom.toRingHom_eq_coe, RingHom.coe_coe, aeval_X]
    exact Module.mem_annihilator.mp hx _
  obtain ⟨c, hc⟩ := (exact_kerCotangentToTensor_mapBaseChange A A[X] B hsurj _).mp h0
  obtain ⟨y, rfl⟩ := Ideal.toCotangent_surjective _ c
  rw [kerCotangentToTensor_toCotangent] at hc
  have hy : y.1 ∈ Ideal.span {F} := by rw [← hker]; exact y.2
  obtain ⟨h, hh⟩ := Ideal.mem_span_singleton'.mp hy
  -- identify `B ⊗_{A[t]} Ω_{A[t]/A}` with `B` via the basis `dt`
  let ι : B ⊗[A[X]] Ω[A[X]⁄A] →ₗ[B] B :=
    (AlgebraTensorModule.rid A[X] B B).toLinearMap ∘ₗ
      (LinearEquiv.baseChange A[X] B _ _ (polynomialEquiv A)).toLinearMap
  have hι (b : B) (g : A[X]) : ι (b ⊗ₜ D A A[X] g) = aeval u (derivative g) * b := by
    simp [ι, polynomialEquiv_D, Algebra.smul_def, halg]
  have := congr(ι $hc)
  rw [hι, hι, ← hh, derivative_mul, map_add, map_mul, map_mul, hF, mul_zero, zero_add,
    mul_one, derivative_X, map_one, one_mul] at this
  rw [Ideal.mem_span_singleton']
  exact ⟨aeval u h, this⟩


section AdjoinRoot

variable (F : A[X])

lemma aeval_root_surjective :
    Function.Surjective (aeval (AdjoinRoot.root F) : A[X] →ₐ[A] AdjoinRoot F) := fun x ↦ by
  obtain ⟨g, rfl⟩ := AdjoinRoot.mk_surjective x
  exact ⟨g, AdjoinRoot.aeval_eq g⟩

lemma ker_aeval_root : RingHom.ker (aeval (AdjoinRoot.root F) : A[X] →ₐ[A] AdjoinRoot F) =
    Ideal.span {F} := by
  ext g
  rw [RingHom.mem_ker, AdjoinRoot.aeval_eq, AdjoinRoot.mk_eq_zero, Ideal.mem_span_singleton]

/-- I.7.2 for `B = A[t]/(F)`: the different ideal is generated by `F'(u)`. -/
theorem annihilator_kaehlerDifferential_adjoinRoot :
    Module.annihilator (AdjoinRoot F) Ω[AdjoinRoot F⁄A] =
      Ideal.span {aeval (AdjoinRoot.root F) (derivative F)} :=
  annihilator_eq_span_derivative (aeval_root_surjective F) (ker_aeval_root F)

/-- An element `G` is invertible in `A[t]/(F)` iff `F` and `G` generate the unit ideal. -/
theorem isUnit_mk_iff_isCoprime (G : A[X]) : IsUnit (AdjoinRoot.mk F G) ↔ IsCoprime F G := by
  constructor
  · rintro ⟨v, hv⟩
    obtain ⟨H, hH⟩ := AdjoinRoot.mk_surjective (v⁻¹ : (AdjoinRoot F)ˣ).1
    have : AdjoinRoot.mk F (G * H - 1) = 0 := by
      rw [map_sub, map_mul, map_one, hH, ← hv, Units.mul_inv, sub_self]
    obtain ⟨K, hK⟩ := AdjoinRoot.mk_eq_zero.mp this
    exact ⟨-K, H, by linear_combination hK⟩
  · rintro ⟨a, b, h⟩
    refine IsUnit.of_mul_eq_one (AdjoinRoot.mk F b) ?_
    rw [← map_mul, mul_comm, ← sub_eq_zero, ← map_one (AdjoinRoot.mk F), ← map_sub,
      AdjoinRoot.mk_eq_zero]
    exact ⟨-a, by linear_combination h⟩

variable {F}

/-- I.7.3: let `F` be monic and `B = A[t]/(F)`. Then `B` is étale over `A` at a prime `q`
iff `q` does not contain `F'(u)`. -/
theorem isEtaleAt_adjoinRoot_iff (hF : F.Monic) (q : Ideal (AdjoinRoot F)) [q.IsPrime] :
    Algebra.IsEtaleAt A q ↔ aeval (AdjoinRoot.root F) (derivative F) ∉ q := by
  have := hF.free_adjoinRoot
  have := hF.finite_adjoinRoot
  constructor
  · intro h
    have : (⟨q, ‹_›⟩ : PrimeSpectrum _) ∈ unramifiedLocus A (AdjoinRoot F) :=
      (inferInstance : Algebra.FormallyUnramified A (Localization.AtPrime q))
    rw [unramifiedLocus_eq_compl_support, Set.mem_compl_iff, Module.mem_support_iff_of_finite,
      annihilator_kaehlerDifferential_adjoinRoot, Ideal.span_singleton_le_iff_mem] at this
    exact this
  · intro hq
    have := isUnramifiedAt_of_aeval_derivative_notMem (hu := by
      rw [Algebra.adjoin_singleton_eq_range_aeval, AlgHom.range_eq_top]
      exact aeval_root_surjective F) (AdjoinRoot.eval₂_root F) q hq
    exact Algebra.IsEtaleAt.of_isUnramifiedAt_of_flat q

/-- I.7.4: for `F` monic, `B = A[t]/(F)` is étale over `A` iff `F'(u)` is invertible,
iff `F` and `F'` generate the unit ideal of `A[t]` (i.e. `F` is separable). The
sufficiency is `etale_adjoinRoot_of_separable`. -/
theorem isUnit_aeval_derivative_of_etale [Algebra.Etale A (AdjoinRoot F)] :
    IsUnit (aeval (AdjoinRoot.root F) (derivative F)) := by
  have : Subsingleton Ω[AdjoinRoot F⁄A] :=
    (Algebra.formallyUnramified_iff _ _).mp inferInstance
  have h := annihilator_kaehlerDifferential_adjoinRoot (A := A) F
  rw [Module.annihilator_eq_top_iff.mpr this, eq_comm, Ideal.span_singleton_eq_top] at h
  exact h

end AdjoinRoot

end Monogenic

section Separable

/-- A monic polynomial over a local ring whose reduction modulo the maximal ideal is
separable is itself separable, i.e. `F` and `F'` generate the unit ideal. -/
theorem separable_of_separable_map_residue [IsLocalRing A] {P : A[X]} (hP : P.Monic)
    (h : (P.map (residue A)).Separable) : P.Separable := by
  rw [Polynomial.Separable, ← Ideal.isCoprime_span_singleton_iff, Ideal.isCoprime_iff_sup_eq]
  by_contra hne
  obtain ⟨M, hM, hle⟩ := Ideal.exists_le_maximal _ hne
  have hPM : P ∈ M := hle (Ideal.mem_sup_left (Ideal.mem_span_singleton_self P))
  have hP'M : P.derivative ∈ M := hle (Ideal.mem_sup_right (Ideal.mem_span_singleton_self _))
  -- `M` lies over the maximal ideal of `A`, since `A[X]/(P)` is integral over `A`
  have hker : RingHom.ker (AdjoinRoot.mk P) ≤ M := fun x hx ↦ by
    rw [RingHom.mem_ker, AdjoinRoot.mk_eq_zero] at hx
    obtain ⟨c, rfl⟩ := hx
    exact M.mul_mem_right c hPM
  have hM' : (M.map (AdjoinRoot.mk P)).IsMaximal :=
    Ideal.IsMaximal.map_of_surjective_of_ker_le AdjoinRoot.mk_surjective hker
  have : Algebra.IsIntegral A (AdjoinRoot P) := AdjoinRoot.isIntegral_of_monic hP
  have hc := Ideal.isMaximal_comap_of_isIntegral_of_isMaximal (R := A) (M.map (AdjoinRoot.mk P))
  have hcomap : (M.map (AdjoinRoot.mk P)).comap (algebraMap A (AdjoinRoot P)) = M.comap C := by
    rw [AdjoinRoot.algebraMap_eq]
    change Ideal.comap ((AdjoinRoot.mk P).comp C) _ = _
    rw [← Ideal.comap_comap, Ideal.comap_map_of_surjective' _ AdjoinRoot.mk_surjective,
      sup_eq_left.mpr hker]
  rw [hcomap] at hc
  have hmA : maximalIdeal A ≤ M.comap C := (IsLocalRing.eq_maximalIdeal hc).ge
  -- so `M` contains the kernel of reduction, and its image in `k[X]` is proper
  have hker' : RingHom.ker (Polynomial.mapRingHom (residue A)) ≤ M := by
    rw [Polynomial.ker_mapRingHom, IsLocalRing.ker_residue, Ideal.map_le_iff_le_comap]
    exact hmA
  have hN : (M.map (Polynomial.mapRingHom (residue A))).IsMaximal :=
    Ideal.IsMaximal.map_of_surjective_of_ker_le
      (Polynomial.map_surjective _ residue_surjective) hker'
  apply hN.ne_top
  obtain ⟨a, b, hab⟩ := h
  rw [Ideal.eq_top_iff_one, ← hab]
  refine Ideal.add_mem _ (Ideal.mul_mem_left _ _ (Ideal.mem_map_of_mem _ hPM)) ?_
  rw [Polynomial.derivative_map]
  exact Ideal.mul_mem_left _ _ (Ideal.mem_map_of_mem (Polynomial.mapRingHom (residue A)) hP'M)


/-- The standard étale pair `(F, 1)` attached to a monic separable polynomial `F`. -/
@[simps f g]
noncomputable def standardEtalePairOfSeparable {P : A[X]} (hP : P.Monic) (hs : P.Separable) :
    StandardEtalePair A where
  f := P
  monic_f := hP
  g := 1
  cond := by
    obtain ⟨a, b, h⟩ := hs
    exact ⟨b, a, 0, by rw [pow_zero, ← h]; ring⟩

/-- `A[t]/(F)` is the standard étale algebra of the pair `(F, 1)`. -/
noncomputable def adjoinRootEquivStandardEtale {P : A[X]} (hP : P.Monic) (hs : P.Separable) :
    AdjoinRoot P ≃ₐ[A] (standardEtalePairOfSeparable hP hs).Ring := by
  have h₁ : P.eval₂ (algebraMap A (standardEtalePairOfSeparable hP hs).Ring)
      (standardEtalePairOfSeparable hP hs).X = 0 := by
    have := (StandardEtalePair.hasMap_X (P := standardEtalePairOfSeparable hP hs)).1
    rwa [standardEtalePairOfSeparable_f, aeval_def] at this
  have h₂ : (standardEtalePairOfSeparable hP hs).HasMap (AdjoinRoot.root P) :=
    ⟨by simp [AdjoinRoot.aeval_eq], by simp⟩
  refine AlgEquiv.ofAlgHom (AdjoinRoot.liftAlgHom P (Algebra.ofId A _) _ h₁)
    ((standardEtalePairOfSeparable hP hs).lift (AdjoinRoot.root P) h₂) ?_ ?_
  · apply StandardEtalePair.hom_ext
    simp only [AlgHom.coe_comp, Function.comp_apply, StandardEtalePair.lift_X, AlgHom.id_apply]
    exact AdjoinRoot.liftAlgHom_root _ _ _ _
  · apply AdjoinRoot.algHom_ext
    simp only [AlgHom.coe_comp, Function.comp_apply, AlgHom.id_apply]
    rw [AdjoinRoot.liftAlgHom_root P (Algebra.ofId A (standardEtalePairOfSeparable hP hs).Ring)
      (standardEtalePairOfSeparable hP hs).X h₁]
    exact StandardEtalePair.lift_X _ _ _

/-- I.7.4, sufficiency: if `F` is monic and `F`, `F'` generate the unit ideal of
`A[t]`, then `A[t]/(F)` is étale over `A`. -/
theorem etale_adjoinRoot_of_separable {P : A[X]} (hP : P.Monic) (hs : P.Separable) :
    Algebra.Etale A (AdjoinRoot P) :=
  Algebra.Etale.of_equiv (adjoinRootEquivStandardEtale hP hs).symm


/-- Base change of `A[t]/(F)` along `A → T` is `T[t]/(F)`. -/
noncomputable def tensorAdjoinRootEquiv (T : Type*) [CommRing T] [Algebra A T] (P : A[X]) :
    T ⊗[A] AdjoinRoot P ≃ₐ[T] AdjoinRoot (P.map (algebraMap A T)) := by
  have h₁ : (P.map (algebraMap A T)).eval₂ (algebraMap T (T ⊗[A] AdjoinRoot P))
      (1 ⊗ₜ AdjoinRoot.root P) = 0 := by
    rw [eval₂_map, ← IsScalarTower.algebraMap_eq]
    have : (1 ⊗ₜ[A] AdjoinRoot.root P : T ⊗[A] AdjoinRoot P) =
        Algebra.TensorProduct.includeRight (AdjoinRoot.root P) := rfl
    rw [this, ← aeval_def, aeval_algHom_apply, AdjoinRoot.aeval_eq, AdjoinRoot.mk_self, map_zero]
  have h₂ : P.eval₂ (algebraMap A (AdjoinRoot (P.map (algebraMap A T))))
      (AdjoinRoot.root _) = 0 := by
    rw [IsScalarTower.algebraMap_eq A T (AdjoinRoot _), ← eval₂_map, ← aeval_def,
      AdjoinRoot.aeval_eq, AdjoinRoot.mk_self]
  refine AlgEquiv.ofAlgHom (Algebra.TensorProduct.lift (Algebra.ofId T _)
      (AdjoinRoot.liftAlgHom P (Algebra.ofId A _) _ h₂) (fun _ _ ↦ .all _ _))
    (AdjoinRoot.liftAlgHom _ (Algebra.ofId T _) _ h₁) ?_ ?_
  · apply AdjoinRoot.algHom_ext
    rw [AlgHom.comp_apply, AdjoinRoot.liftAlgHom_root _ (Algebra.ofId T _) _ h₁]
    simp [AdjoinRoot.liftAlgHom_root _ (Algebra.ofId A _) _ h₂]
  · apply Algebra.TensorProduct.ext (Subsingleton.elim _ _)
    apply AdjoinRoot.algHom_ext
    simp [AdjoinRoot.liftAlgHom_root _ (Algebra.ofId A _) _ h₂,
      AdjoinRoot.liftAlgHom_root _ (Algebra.ofId T _) _ h₁]

/-- I.7.4: for `F` monic, `B = A[t]/(F)` is étale over `A` iff `F` is separable,
i.e. `F` and `F'` generate the unit ideal of `A[t]`, i.e. `F'(u)` is invertible. -/
theorem etale_adjoinRoot_iff {F : A[X]} (hF : F.Monic) :
    Algebra.Etale A (AdjoinRoot F) ↔ F.Separable := by
  refine ⟨fun _ ↦ ?_, etale_adjoinRoot_of_separable hF⟩
  have := isUnit_aeval_derivative_of_etale (F := F)
  rwa [AdjoinRoot.aeval_eq, isUnit_mk_iff_isCoprime] at this

/-- I.7.4: for `F` monic, `B = A[t]/(F)` is étale over `A` iff `F'(u)` is a unit. -/
theorem etale_adjoinRoot_iff_isUnit {F : A[X]} (hF : F.Monic) :
    Algebra.Etale A (AdjoinRoot F) ↔ IsUnit (aeval (AdjoinRoot.root F) (derivative F)) := by
  rw [etale_adjoinRoot_iff hF, AdjoinRoot.aeval_eq, isUnit_mk_iff_isCoprime]
  rfl

end Separable

section QuotientTensor

variable (I : Ideal A) {B' : Type u} [CommRing B'] [Algebra A B']

/-- `(A ⧸ I) ⊗_A B'` is the quotient `B' ⧸ I B'`. -/
noncomputable def quotientEquivQuotientTensor :
    (B' ⧸ I.map (algebraMap A B')) ≃ₐ[A] (A ⧸ I) ⊗[A] B' :=
  ((Algebra.TensorProduct.quotIdealMapEquivTensorQuot B' I).restrictScalars A).trans
    (Algebra.TensorProduct.comm A B' (A ⧸ I))

lemma quotientEquivQuotientTensor_mk (b : B') :
    quotientEquivQuotientTensor I (Ideal.Quotient.mk _ b) = 1 ⊗ₜ b := rfl

end QuotientTensor

section Local

variable [IsLocalRing A] [IsLocalRing B] [Module.Finite A B]

/-- I.7.5, étale case, when `B` is local: a finite étale local algebra `B` over a local
ring `A` is isomorphic to `A[t]/(F)` for a separable monic `F` of degree `n`, the rank of
`B` (which is also the rank of `B ⊗_A k` over the residue field `k`). -/
theorem exists_algEquiv_adjoinRoot_of_etale [Algebra.Etale A B] :
    ∃ F : A[X], F.Monic ∧ F.Separable ∧ F.natDegree = Module.finrank A B ∧
      Nonempty (AdjoinRoot F ≃ₐ[A] B) := by
  have : Module.Free A B := Module.free_of_flat_of_isLocalRing
  obtain ⟨β, hβ⟩ := IsLocalRing.exists_adjoin_eq_top (R := A) (S := B)
  let h := IsAdjoinRootMonic.mkOfAdjoinEqTop' hβ
  have hmonic : (minpoly A β).Monic := minpoly.monic (Algebra.IsIntegral.isIntegral β)
  refine ⟨minpoly A β, hmonic, ?_, h.finrank.symm, ⟨h.adjoinRootAlgEquiv⟩⟩
  have hu := isUnit_aeval_derivative_minpoly_of_adjoin_eq_top hβ
  have hroot : h.adjoinRootAlgEquiv.symm β = AdjoinRoot.root (minpoly A β) :=
    (congrArg h.adjoinRootAlgEquiv.symm (IsAdjoinRootMonic.mkOfAdjoinEqTop'_root hβ)).symm.trans
      h.adjoinRootAlgEquiv_symm_apply_root
  have hmap : h.adjoinRootAlgEquiv.symm (aeval β (derivative (minpoly A β))) =
      aeval (h.adjoinRootAlgEquiv.symm β) (derivative (minpoly A β)) :=
    (aeval_algHom_apply h.adjoinRootAlgEquiv.symm.toAlgHom β _).symm
  have := hu.map h.adjoinRootAlgEquiv.symm
  rwa [hmap, hroot, AdjoinRoot.aeval_eq, isUnit_mk_iff_isCoprime] at this

/-- I.7.5, net case, when `B` is local: a finite local unramified algebra `B` over a local
ring `A` is a quotient of `A[t]/(F)` for a separable monic `F` whose degree is the rank
of `B ⊗_A k` (here `[k(B) : k(A)]`). -/
theorem exists_surjective_adjoinRoot_of_formallyUnramified [IsLocalHom (algebraMap A B)]
    [Algebra.FormallyUnramified A B] :
    ∃ F : A[X], F.Monic ∧ F.Separable ∧
      F.natDegree = Module.finrank (ResidueField A) (ResidueField B) ∧
      ∃ φ : AdjoinRoot F →ₐ[A] B, Function.Surjective φ := by
  classical
  set k := ResidueField A
  set L := ResidueField B
  have hm := ((FormallyUnramified.iff_map_maximalIdeal_eq (R := A) (S := B)).mp inferInstance).2
  let pb := Field.powerBasisOfFiniteOfSeparable k L
  set n := pb.dim
  obtain ⟨u, hu⟩ := residue_surjective pb.gen
  -- by Nakayama, `1, u, …, u^(n-1)` generate `B` over `A`
  let N : Submodule A B := Submodule.span A (Set.range fun i : Fin n ↦ u ^ (i : ℕ))
  have hN : N = ⊤ := by
    rw [← IsLocalRing.map_mkQ_eq_top, Submodule.map_mkQ_eq_top, _root_.eq_top_iff]
    intro b _
    let c := pb.basis.repr (residue B b)
    choose a ha using fun i ↦ residue_surjective (R := A) (c i)
    have hsum : residue B (∑ i, a i • u ^ (i : ℕ)) = residue B b := by
      conv_rhs => rw [← pb.basis.sum_repr (residue B b)]
      simp only [map_sum, Algebra.smul_def, map_mul, map_pow, hu, PowerBasis.coe_basis]
      refine Finset.sum_congr rfl fun i _ ↦ ?_
      rw [← ha i]
      rfl
    have : b - ∑ i, a i • u ^ (i : ℕ) ∈ maximalIdeal A • (⊤ : Submodule A B) := by
      rw [Ideal.smul_top_eq_map, hm, Submodule.restrictScalars_mem, ← residue_eq_zero_iff,
        map_sub, hsum, sub_self]
    have hb : b = (b - ∑ i, a i • u ^ (i : ℕ)) + ∑ i, a i • u ^ (i : ℕ) := by ring
    rw [hb]
    exact Submodule.add_mem_sup this (Submodule.sum_mem _ fun i _ ↦
      Submodule.smul_mem _ _ (Submodule.subset_span ⟨i, rfl⟩))
  -- a monic `F` of degree `n` with `F(u) = 0`
  obtain ⟨c, hc⟩ := (Submodule.mem_span_range_iff_exists_fun A).mp (hN ▸ Submodule.mem_top :
    u ^ n ∈ N)
  let G : A[X] := ∑ i : Fin n, C (c i) * X ^ (i : ℕ)
  have hG : G.degree < n := by
    refine (degree_sum_le _ _).trans_lt ?_
    refine (Finset.sup_lt_iff (WithBot.bot_lt_coe n)).mpr fun i _ ↦ ?_
    exact (degree_C_mul_X_pow_le _ _).trans_lt (WithBot.coe_lt_coe.mpr i.2)
  let F : A[X] := X ^ n - G
  have hFm : F.Monic := monic_X_pow_sub hG
  have hFd : F.natDegree = n := by
    rw [natDegree_sub_eq_left_of_natDegree_lt, natDegree_X_pow]
    rw [natDegree_X_pow]
    by_cases hG0 : G = 0
    · rw [hG0, natDegree_zero]; exact pb.dim_pos
    · exact (natDegree_lt_iff_degree_lt hG0).mpr hG
  have hFu : aeval u F = 0 := by
    simp only [F, G, map_sub, map_pow, aeval_X, map_sum, map_mul, aeval_C, ← hc,
      Algebra.smul_def, sub_self]
  -- its reduction is the minimal polynomial of the generator of `L`
  have hmin : F.map (residue A) = minpoly k pb.gen := by
    refine (eq_of_monic_of_dvd_of_natDegree_le (minpoly.monic pb.isIntegral_gen) (hFm.map _)
      (minpoly.dvd _ _ ?_) ?_)
    · rw [show residue A = algebraMap A k from rfl, aeval_map_algebraMap, ← hu,
        show residue B u = IsScalarTower.toAlgHom A B L u from rfl, aeval_algHom_apply, hFu,
        map_zero]
    · rw [hFm.natDegree_map, hFd, pb.natDegree_minpoly]
  have hFs : F.Separable := separable_of_separable_map_residue hFm
    (hmin ▸ Algebra.IsSeparable.isSeparable k pb.gen)
  refine ⟨F, hFm, hFs, by rw [hFd, pb.finrank], AdjoinRoot.liftAlgHom F (Algebra.ofId A B) u
    hFu, ?_⟩
  -- the image contains the `A`-span of the `uⁱ`, which is `B`
  intro b
  have hb : b ∈ N := hN ▸ Submodule.mem_top
  induction hb using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨i, rfl⟩ := hx
    exact ⟨AdjoinRoot.root F ^ (i : ℕ), by
      rw [map_pow, AdjoinRoot.liftAlgHom_root F (Algebra.ofId A B) u hFu]⟩
  | zero => exact ⟨0, map_zero _⟩
  | add x y _ _ hx hy =>
    obtain ⟨a, rfl⟩ := hx
    obtain ⟨b, rfl⟩ := hy
    exact ⟨a + b, map_add _ _ _⟩
  | smul r x _ hx =>
    obtain ⟨a, rfl⟩ := hx
    exact ⟨r • a, map_smul _ _ _⟩

/-- I.7.5, the generator, when `B` is local and unramified over `A` and `A → B` is
injective: `B` is generated by one element (mathlib). -/
theorem exists_adjoin_eq_top_of_formallyUnramified [FaithfulSMul A B]
    [Algebra.FormallyUnramified A B] : ∃ β : B, Algebra.adjoin A {β} = ⊤ :=
  IsLocalRing.exists_adjoin_eq_top

end Local

section InfiniteResidueField

variable [IsLocalRing A]

/-- Every element of `k ⊗_A B` is of the form `1 ⊗ b`. -/
lemma exists_one_tmul_eq (ξ : ResidueField A ⊗[A] B) : ∃ b : B, 1 ⊗ₜ b = ξ := by
  obtain ⟨b, rfl⟩ := (quotientEquivQuotientTensor (maximalIdeal A) (B' := B)).surjective ξ
  obtain ⟨b, rfl⟩ := Ideal.Quotient.mk_surjective b
  exact ⟨b, rfl⟩

/-- `1 ⊗ b = 0` in `k ⊗_A B` iff `b ∈ m_A B`. -/
lemma one_tmul_eq_zero_iff (b : B) :
    (1 : ResidueField A) ⊗ₜ[A] b = 0 ↔ b ∈ (maximalIdeal A).map (algebraMap A B) := by
  have := map_eq_zero_iff (quotientEquivQuotientTensor (maximalIdeal A) (B' := B))
    (quotientEquivQuotientTensor (maximalIdeal A)).injective (x := Ideal.Quotient.mk _ b)
  rw [quotientEquivQuotientTensor_mk, Ideal.Quotient.eq_zero_iff_mem] at this
  exact this

variable [Module.Finite A B]

/-- The special fibre `k ⊗_A B` of a finite unramified algebra over a local ring is étale over
the residue field `k`. -/
instance etale_residueField_tensor [FormallyUnramified A B] :
    Algebra.Etale (ResidueField A) (ResidueField A ⊗[A] B) :=
  ⟨FormallyEtale.of_formallyUnramified_of_field _ _,
    FinitePresentation.of_finiteType.mp inferInstance⟩

/-- I.7.5, the polynomial part: let `u ∈ B` generate `k ⊗_A B` as a `k`-algebra (`k` the residue
field of `A`, `B` finite unramified). Every monic `G ∈ A[t]` of degree `n = [k ⊗_A B : k]` with
`G(u) = 0` is separable: its reduction is the minimal polynomial of the image of `u`, and
`k ⊗_A B ≅ k[t]/(Ḡ)` is étale (I.7.4). -/
theorem separable_of_aeval_eq_zero [FormallyUnramified A B] {u : B}
    (hu : Algebra.adjoin (ResidueField A) {(1 : ResidueField A) ⊗ₜ[A] u} = ⊤) {G : A[X]}
    (hG : G.Monic) (hdeg : G.natDegree = Module.finrank (ResidueField A) (ResidueField A ⊗[A] B))
    (h0 : aeval u G = 0) : G.Separable := by
  set k := ResidueField A
  set ū : k ⊗[A] B := 1 ⊗ₜ u
  let h := IsAdjoinRootMonic.mkOfAdjoinEqTop' hu
  have hmon := minpoly.monic (Algebra.IsIntegral.isIntegral (R := k) ū)
  have hsep : (minpoly k ū).Separable := by
    have : Algebra.Etale k (AdjoinRoot (minpoly k ū)) := .of_equiv h.adjoinRootAlgEquiv.symm
    exact (etale_adjoinRoot_iff hmon).mp this
  have hmap : G.map (residue A) = minpoly k ū := by
    refine eq_of_monic_of_dvd_of_natDegree_le hmon (hG.map _) (minpoly.dvd _ _ ?_) ?_
    · rw [show residue A = algebraMap A k from rfl, aeval_map_algebraMap,
        show ū = Algebra.TensorProduct.includeRight u from rfl, aeval_algHom_apply, h0, map_zero]
    · rw [hG.natDegree_map, hdeg, h.finrank]
  exact separable_of_separable_map_residue hG (hmap ▸ hsep)

/-- I.7.5, the key step: let `A` be local with residue field `k`, `B` a finite unramified
`A`-algebra and `u ∈ B` whose image generates `k ⊗_A B` over `k`, of dimension `n`. By
Nakayama, the `uⁱ` (`i < n`) generate the `A`-module `B`; hence `u` is a root of a monic `F` of
degree `n`, which is separable, and `A[t] → B`, `t ↦ u`, is surjective. -/
theorem exists_monic_separable_of_adjoin_eq_top [FormallyUnramified A B] {u : B}
    (hu : Algebra.adjoin (ResidueField A) {(1 : ResidueField A) ⊗ₜ[A] u} = ⊤) :
    ∃ F : A[X], F.Monic ∧ F.Separable ∧
      F.natDegree = Module.finrank (ResidueField A) (ResidueField A ⊗[A] B) ∧
      aeval u F = 0 ∧ Function.Surjective (aeval u : A[X] →ₐ[A] B) := by
  set k := ResidueField A
  set n := Module.finrank k (k ⊗[A] B)
  set ū : k ⊗[A] B := 1 ⊗ₜ u
  let h := IsAdjoinRootMonic.mkOfAdjoinEqTop' hu
  have hmon := minpoly.monic (Algebra.IsIntegral.isIntegral (R := k) ū)
  have hn : (minpoly k ū).natDegree = n := h.finrank.symm
  -- by Nakayama, the polynomials of degree `< n` in `u` exhaust `B`
  let N : Submodule A B := (degreeLT A n).map (aeval u).toLinearMap
  have hN : N = ⊤ := by
    rw [← IsLocalRing.map_mkQ_eq_top, Submodule.map_mkQ_eq_top, _root_.eq_top_iff]
    intro b _
    have hb : ū ^ 0 * (1 ⊗ₜ b) ∈ Algebra.adjoin k {ū} := hu ▸ Algebra.mem_top
    rw [pow_zero, one_mul, Algebra.adjoin_singleton_eq_range_aeval] at hb
    obtain ⟨p, hp⟩ := hb
    set q := p %ₘ minpoly k ū
    have hq : q.degree < n := by
      rw [← hn, ← degree_eq_natDegree hmon.ne_zero]
      exact degree_modByMonic_lt _ hmon
    obtain ⟨Q, hQ, hQd⟩ := exists_degree_eq_of_mem_lifts
      (mem_lifts_of_surjective (residue_surjective (R := A)) q)
    have hQn : Q ∈ degreeLT A n := mem_degreeLT.mpr (hQd ▸ hq)
    have hsub : b - aeval u Q ∈ maximalIdeal A • (⊤ : Submodule A B) := by
      rw [Ideal.smul_top_eq_map, Submodule.restrictScalars_mem, ← one_tmul_eq_zero_iff,
        TensorProduct.tmul_sub, sub_eq_zero]
      change (1 : k) ⊗ₜ[A] b = Algebra.TensorProduct.includeRight (aeval u Q)
      rw [← aeval_algHom_apply, ← aeval_map_algebraMap k, show algebraMap A k = residue A from rfl,
        hQ, show Algebra.TensorProduct.includeRight u = ū from rfl,
        aeval_modByMonic_eq_self_of_root (minpoly.aeval k ū)]
      exact hp.symm
    have hQN : aeval u Q ∈ N := ⟨Q, hQn, rfl⟩
    have : b = (b - aeval u Q) + aeval u Q := by ring
    rw [this]
    exact Submodule.add_mem_sup hsub hQN
  -- a monic `F` of degree `n` killing `u`
  obtain ⟨G, hG, hGu⟩ : u ^ n ∈ N := hN ▸ Submodule.mem_top
  have hGd : G.degree < n := mem_degreeLT.mp hG
  set F : A[X] := X ^ n - G
  have hFm : F.Monic := monic_X_pow_sub hGd
  have hFd : F.natDegree = n := by
    rw [natDegree_eq_of_degree_eq (degree_sub_eq_left_of_degree_lt (by rwa [degree_X_pow])),
      natDegree_X_pow]
  have hFu : aeval u F = 0 := by
    simp only [F, map_sub, map_pow, aeval_X]
    rw [← hGu]
    exact sub_self _
  refine ⟨F, hFm, separable_of_aeval_eq_zero hu hFm hFd hFu, hFd, hFu, fun b ↦ ?_⟩
  obtain ⟨Q, -, hQ⟩ : b ∈ N := hN ▸ Submodule.mem_top
  exact ⟨Q, hQ⟩

/-- I.7.5, net case, when the residue field `k` of `A` is infinite: a finite unramified
algebra `B` over the local ring `A` is a quotient of `A[t]/(F)` for a monic separable `F` of
degree `n = [k ⊗_A B : k]`. (`B` need not be local; `k ⊗_A B` is then generated by one
element.) -/
theorem exists_surjective_adjoinRoot_of_formallyUnramified_of_infinite
    [Infinite (ResidueField A)] [FormallyUnramified A B] :
    ∃ F : A[X], F.Monic ∧ F.Separable ∧
      F.natDegree = Module.finrank (ResidueField A) (ResidueField A ⊗[A] B) ∧
      ∃ φ : AdjoinRoot F →ₐ[A] B, Function.Surjective φ := by
  obtain ⟨ξ, hξ⟩ := exists_adjoin_eq_top_of_etale (k := ResidueField A) (ResidueField A ⊗[A] B)
  obtain ⟨u, rfl⟩ := exists_one_tmul_eq ξ
  obtain ⟨F, hFm, hFs, hFd, hFu, hsurj⟩ := exists_monic_separable_of_adjoin_eq_top hξ
  have hFu' : F.eval₂ ((Algebra.ofId A B : A →ₐ[A] B) : A →+* B) u = 0 := hFu
  refine ⟨F, hFm, hFs, hFd, AdjoinRoot.liftAlgHom F (Algebra.ofId A B) u hFu', fun b ↦ ?_⟩
  obtain ⟨Q, rfl⟩ := hsurj b
  exact ⟨AdjoinRoot.mk F Q, AdjoinRoot.liftAlgHom_mk F _ u hFu' Q⟩

/-- I.7.5, étale case, when the residue field `k` of `A` is infinite: a finite étale algebra
`B` over the local ring `A` is isomorphic to `A[t]/(F)` for a monic separable `F`, of degree
the rank of `B` (which is `[k ⊗_A B : k]`). -/
theorem exists_algEquiv_adjoinRoot_of_etale_of_infinite [Infinite (ResidueField A)]
    [Algebra.Etale A B] :
    ∃ F : A[X], F.Monic ∧ F.Separable ∧ F.natDegree = Module.finrank A B ∧
      Nonempty (AdjoinRoot F ≃ₐ[A] B) := by
  have : Module.Free A B := Module.free_of_flat_of_isLocalRing
  obtain ⟨F, hFm, hFs, hFd, φ, hφ⟩ :=
    exists_surjective_adjoinRoot_of_formallyUnramified_of_infinite (A := A) (B := B)
  rw [Module.finrank_baseChange] at hFd
  have := hFm.free_adjoinRoot
  have := hFm.finite_adjoinRoot
  refine ⟨F, hFm, hFs, hFd, ⟨AlgEquiv.ofBijective φ ?_⟩⟩
  refine OrzechProperty.bijective_of_surjective_of_finrank_le φ.toLinearMap hφ ?_
  rw [(AdjoinRoot.powerBasis' hFm).finrank, AdjoinRoot.powerBasis'_dim, hFd]

/-- I.7.5, when the residue field `k` of the local ring `A` is infinite: a finite `A`-algebra
`B` is unramified iff it is a quotient of `A[t]/(F)` for a monic separable `F` (which may be
taken of degree `[k ⊗_A B : k]`). -/
theorem formallyUnramified_iff_exists_surjective_adjoinRoot [Infinite (ResidueField A)] :
    FormallyUnramified A B ↔
      ∃ F : A[X], F.Monic ∧ F.Separable ∧ ∃ φ : AdjoinRoot F →ₐ[A] B, Function.Surjective φ := by
  refine ⟨fun _ ↦ ?_, fun ⟨F, hFm, hFs, φ, hφ⟩ ↦ ?_⟩
  · obtain ⟨F, hFm, hFs, -, hφ⟩ :=
      exists_surjective_adjoinRoot_of_formallyUnramified_of_infinite (A := A) (B := B)
    exact ⟨F, hFm, hFs, hφ⟩
  · have := etale_adjoinRoot_of_separable hFm hFs
    exact .of_surjective φ hφ

/-- I.7.5, étale case, when the residue field of the local ring `A` is infinite: a finite
`A`-algebra `B` is étale iff it is isomorphic to `A[t]/(F)` for a monic separable `F`. -/
theorem etale_iff_exists_algEquiv_adjoinRoot [Infinite (ResidueField A)] :
    Algebra.Etale A B ↔ ∃ F : A[X], F.Monic ∧ F.Separable ∧ Nonempty (AdjoinRoot F ≃ₐ[A] B) := by
  refine ⟨fun _ ↦ ?_, fun ⟨F, hFm, hFs, ⟨e⟩⟩ ↦ ?_⟩
  · obtain ⟨F, hFm, hFs, -, he⟩ := exists_algEquiv_adjoinRoot_of_etale_of_infinite (A := A) (B := B)
    exact ⟨F, hFm, hFs, he⟩
  · have := etale_adjoinRoot_of_separable hFm hFs
    exact .of_equiv e

end InfiniteResidueField

section ZariskiLocal

/-- I.7.4: the algebra of a standard étale pair `(A[t]/(F))[1/g]` is étale. -/
instance (P : StandardEtalePair A) : Etale A P.Ring :=
  inferInstance

/-- I.7.1–I.7.4: the derivative of the monic polynomial is invertible on the
standard étale algebra. -/
theorem isUnit_derivative (P : StandardEtalePair A) :
    IsUnit (P.f.derivative.aeval P.X) :=
  P.hasMap_X.isUnit_derivative_f

/-- I.7.6–I.7.7, Zariski-local form: an algebra of finite type unramified at `Q` is,
after inverting one element outside `Q`, a quotient of a standard étale algebra
`(A[t]/(F))[1/g]`. -/
theorem exists_standardEtale_surjection [FiniteType A B] (Q : Ideal B) [Q.IsPrime]
    [IsUnramifiedAt A Q] : ∃ f ∉ Q, HasStandardEtaleSurjectionOn (R := A) f :=
  IsUnramifiedAt.exists_hasStandardEtaleSurjectionOn (R := A) Q

/-- I.7.6, étale case, Zariski-local form: an algebra of finite presentation étale at
`Q` is, after inverting one element outside `Q`, standard étale. -/
theorem exists_isStandardEtale [FinitePresentation A B] (Q : Ideal B) [Q.IsPrime]
    [IsEtaleAt A Q] : ∃ f ∉ Q, IsStandardEtale A (Localization.Away f) :=
  IsEtaleAt.exists_isStandardEtale (R := A) Q

end ZariskiLocal

end SGA.SGA1.ExposeI
