/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import Mathlib.AlgebraicGeometry.Morphisms.FinitePresentation
import Mathlib.AlgebraicGeometry.Noetherian
import Mathlib.Topology.Constructible
import Mathlib.Topology.NoetherianSpace
import Mathlib.Topology.Sober

/-!
# SGA 1, Exposé IV, §6: constructible sets

The recollections on constructible sets opening IV.6. Mathlib's `IsConstructible` is the Boolean
algebra generated by the retrocompact open sets; in a noetherian space every set is compact, so
this is Chevalley's notion (finite unions of locally closed sets). We prove:

* IV.6.1: in a noetherian space, `Z` is constructible iff for every irreducible closed `Y`, either
  `Z ∩ Y` is not dense in `Y` or it contains a nonempty open subset of `Y`;
* IV.6.3: in a noetherian quasi-sober space, a constructible set is a neighbourhood of `x` iff it
  contains every generization of `x`;
* IV.6.4: in such a space, a set is open iff it is stable under generization and meets each
  `closure {x}`, `x ∈ U`, in a set containing a nonempty open subset of `closure {x}`.

Chevalley's theorem IV.6.2 is mathlib's `Scheme.Hom.isConstructible_image`.
-/

universe u

namespace SGA.SGA1.ExposeIV

open Topology Set TopologicalSpace

variable {X : Type*} [TopologicalSpace X]

/-- Every open subset of a noetherian space is constructible. -/
lemma isConstructible_of_isOpen [NoetherianSpace X] {U : Set X} (hU : IsOpen U) :
    IsConstructible U :=
  IsRetrocompact.isConstructible hU fun _ _ _ ↦ NoetherianSpace.isCompact _

/-- Every closed subset of a noetherian space is constructible. -/
lemma isConstructible_of_isClosed [NoetherianSpace X] {F : Set X} (hF : IsClosed F) :
    IsConstructible F := by
  rw [← compl_compl F, isConstructible_compl]
  exact isConstructible_of_isOpen hF.isOpen_compl

/-- IV.6.1: in a noetherian space, `Z` is constructible if and only if for every irreducible
closed subset `Y`, either `Z ∩ Y` is not dense in `Y`, or `Z ∩ Y` contains a nonempty open subset
of `Y`. -/
theorem isConstructible_iff_of_noetherianSpace [NoetherianSpace X] {Z : Set X} :
    IsConstructible Z ↔ ∀ Y : Set X, IsClosed Y → IsIrreducible Y →
      ¬ Y ⊆ closure (Z ∩ Y) ∨ ∃ U, IsOpen U ∧ (U ∩ Y).Nonempty ∧ U ∩ Y ⊆ Z := by
  constructor
  · intro hZ
    induction hZ using IsConstructible.empty_union_induction with
    | open_retrocompact U hU _ =>
      intro Y _ hY
      by_cases hUY : (U ∩ Y).Nonempty
      · exact Or.inr ⟨U, hU, hUY, inter_subset_left⟩
      · left
        rw [not_nonempty_iff_eq_empty.1 hUY, closure_empty, subset_empty_iff]
        exact hY.nonempty.ne_empty
    | union s _ t _ hs ht =>
      intro Y hYc hY
      rcases hs Y hYc hY with hs | ⟨U, hU, hUY, hUs⟩
      · rcases ht Y hYc hY with ht | ⟨U, hU, hUY, hUt⟩
        · left
          intro h
          rw [union_inter_distrib_right, closure_union] at h
          rcases isPreirreducible_iff_isClosed_union_isClosed.1 hY.isPreirreducible _ _
            isClosed_closure isClosed_closure h with h | h
          · exact hs h
          · exact ht h
        · exact Or.inr ⟨U, hU, hUY, hUt.trans subset_union_right⟩
      · exact Or.inr ⟨U, hU, hUY, hUs.trans subset_union_left⟩
    | compl s _ hs =>
      intro Y hYc hY
      rcases hs Y hYc hY with hs | ⟨U, hU, hUY, hUs⟩
      · refine Or.inr ⟨(closure (s ∩ Y))ᶜ, isClosed_closure.isOpen_compl, ?_, ?_⟩
        · obtain ⟨y, hyY, hy⟩ := not_subset.1 hs
          exact ⟨y, hy, hyY⟩
        · rintro y ⟨hy, hyY⟩ hys
          exact hy (subset_closure ⟨hys, hyY⟩)
      · left
        intro h
        have : closure (sᶜ ∩ Y) ⊆ Y ∩ Uᶜ :=
          closure_minimal (fun y ⟨hys, hyY⟩ ↦ ⟨hyY, fun hyU ↦ hys (hUs ⟨hyU, hyY⟩)⟩)
            (hYc.inter hU.isClosed_compl)
        obtain ⟨y, hyU, hyY⟩ := hUY
        exact (this (h hyY)).2 hyU
  · intro h
    suffices ∀ F : Closeds X, IsConstructible (Z ∩ F) by simpa using this ⊤
    intro F
    refine (wellFounded_lt (α := Closeds X)).induction
      (C := fun F : Closeds X ↦ IsConstructible (Z ∩ (F : Set X))) F fun F ih ↦ ?_
    by_cases hirr : IsIrreducible (F : Set X)
    · rcases h F F.isClosed hirr with hF | ⟨U, hU, hUF, hUZ⟩
      · -- `Z ∩ F` lies in the smaller closed set `closure (Z ∩ F)`
        let F' : Closeds X := ⟨closure (Z ∩ F), isClosed_closure⟩
        have hlt : F' < F :=
          lt_of_le_of_ne (closure_minimal inter_subset_right F.isClosed) fun h ↦
            hF (congrArg (fun G : Closeds X ↦ (G : Set X)) h).ge
        have : Z ∩ F = Z ∩ F' := by
          refine subset_antisymm (fun x hx ↦ ⟨hx.1, subset_closure hx⟩) ?_
          exact inter_subset_inter_right _ (closure_minimal inter_subset_right F.isClosed)
        rw [this]
        exact ih F' hlt
      · -- `Z ∩ F = (U ∩ F) ∪ (Z ∩ (F \ U))`
        let F' : Closeds X := ⟨F ∩ Uᶜ, F.isClosed.inter hU.isClosed_compl⟩
        have hlt : F' < F := by
          refine lt_of_le_of_ne inter_subset_left fun h ↦ ?_
          obtain ⟨x, hxU, hxF⟩ := hUF
          have : x ∈ (F' : Set X) := by rw [h]; exact hxF
          exact this.2 hxU
        have : Z ∩ F = (U ∩ F) ∪ (Z ∩ F') := by
          ext x
          constructor
          · rintro ⟨hxZ, hxF⟩
            by_cases hxU : x ∈ U
            · exact Or.inl ⟨hxU, hxF⟩
            · exact Or.inr ⟨hxZ, hxF, hxU⟩
          · rintro (⟨hxU, hxF⟩ | ⟨hxZ, hxF, -⟩)
            · exact ⟨hUZ ⟨hxU, hxF⟩, hxF⟩
            · exact ⟨hxZ, hxF⟩
        rw [this]
        exact ((isConstructible_of_isOpen hU).inter (isConstructible_of_isClosed F.isClosed)).union
          (ih F' hlt)
    · by_cases hne : (F : Set X).Nonempty
      · -- a reducible closed set is the union of two smaller closed sets
        have hpre : ¬ IsPreirreducible (F : Set X) := fun h ↦ hirr ⟨hne, h⟩
        simp only [IsPreirreducible, not_forall, not_nonempty_iff_eq_empty] at hpre
        obtain ⟨u, v, hu, hv, hFu, hFv, huv⟩ := hpre
        let F₁ : Closeds X := ⟨F ∩ uᶜ, F.isClosed.inter hu.isClosed_compl⟩
        let F₂ : Closeds X := ⟨F ∩ vᶜ, F.isClosed.inter hv.isClosed_compl⟩
        have hlt₁ : F₁ < F := by
          refine lt_of_le_of_ne inter_subset_left fun h ↦ ?_
          obtain ⟨x, hxF, hxu⟩ := hFu
          have : x ∈ (F₁ : Set X) := by rw [h]; exact hxF
          exact this.2 hxu
        have hlt₂ : F₂ < F := by
          refine lt_of_le_of_ne inter_subset_left fun h ↦ ?_
          obtain ⟨x, hxF, hxv⟩ := hFv
          have : x ∈ (F₂ : Set X) := by rw [h]; exact hxF
          exact this.2 hxv
        have : Z ∩ F = (Z ∩ F₁) ∪ (Z ∩ F₂) := by
          rw [← inter_union_distrib_left]
          congr 1
          ext x
          refine ⟨fun hx ↦ ?_, fun hx ↦ hx.elim (·.1) (·.1)⟩
          by_contra hx'
          simp only [F₁, F₂, Closeds.coe_mk, mem_union, mem_inter_iff, mem_compl_iff,
            not_or, not_and, not_not] at hx'
          have : x ∈ (F : Set X) ∩ (u ∩ v) := ⟨hx, hx'.1 hx, hx'.2 hx⟩
          rw [huv] at this
          exact this
        rw [this]
        exact (ih F₁ hlt₁).union (ih F₂ hlt₂)
      · rw [not_nonempty_iff_eq_empty.1 hne, inter_empty]
        exact IsConstructible.empty

/-- The key step of IV.6.3: in a noetherian quasi-sober space, a point in the closure of a
constructible set `C` is a specialization of a point of `C`. -/
lemma exists_specializes_of_mem_closure [NoetherianSpace X] [QuasiSober X] {C : Set X}
    (hC : IsConstructible C) {x : X} (hx : x ∈ closure C) : ∃ y ∈ C, y ⤳ x := by
  -- a minimal closed set `F` with `x ∈ closure (C ∩ F)`
  let S : Set (Closeds X) := {F | x ∈ closure (C ∩ F)}
  have hS : S.Nonempty := ⟨⊤, by simpa [S] using hx⟩
  obtain ⟨F, hF, hmin⟩ := (wellFounded_lt (α := Closeds X)).has_min S hS
  simp only [S, mem_ofPred_eq] at hF hmin
  let F' : Closeds X := ⟨closure (C ∩ F), isClosed_closure⟩
  have hF'F : F' ≤ F := closure_minimal inter_subset_right F.isClosed
  have hF' : x ∈ closure (C ∩ (F' : Set X)) :=
    closure_mono (show C ∩ (F : Set X) ⊆ C ∩ (F' : Set X) from
      fun y hy ↦ ⟨hy.1, subset_closure hy⟩) hF
  have hFeq : F' = F := by
    by_contra hne
    exact hmin F' hF' (lt_of_le_of_ne hF'F hne)
  have hxF : x ∈ (F : Set X) := hF'F hF
  -- `F` is irreducible
  have hirr : IsIrreducible (F : Set X) := by
    refine ⟨⟨x, hxF⟩, fun u v hu hv hFu hFv ↦ ?_⟩
    by_contra huv
    rw [not_nonempty_iff_eq_empty] at huv
    let F₁ : Closeds X := ⟨F ∩ uᶜ, F.isClosed.inter hu.isClosed_compl⟩
    let F₂ : Closeds X := ⟨F ∩ vᶜ, F.isClosed.inter hv.isClosed_compl⟩
    have hsplit : C ∩ (F : Set X) = (C ∩ F₁) ∪ (C ∩ F₂) := by
      rw [← inter_union_distrib_left]
      congr 1
      ext y
      refine ⟨fun hy ↦ ?_, fun hy ↦ hy.elim (·.1) (·.1)⟩
      by_contra hy'
      simp only [F₁, F₂, Closeds.coe_mk, mem_union, mem_inter_iff, mem_compl_iff,
        not_or, not_and, not_not] at hy'
      have : y ∈ (F : Set X) ∩ (u ∩ v) := ⟨hy, hy'.1 hy, hy'.2 hy⟩
      rw [huv] at this
      exact this
    rw [hsplit, closure_union] at hF
    rcases hF with h | h
    · refine hmin F₁ h (lt_of_le_of_ne inter_subset_left fun e ↦ ?_)
      obtain ⟨y, hyF, hyu⟩ := hFu
      have : y ∈ (F₁ : Set X) := by rw [e]; exact hyF
      exact this.2 hyu
    · refine hmin F₂ h (lt_of_le_of_ne inter_subset_left fun e ↦ ?_)
      obtain ⟨y, hyF, hyv⟩ := hFv
      have : y ∈ (F₂ : Set X) := by rw [e]; exact hyF
      exact this.2 hyv
  -- its generic point lies in `C`, by IV.6.1
  obtain ⟨η, hη⟩ := QuasiSober.sober hirr F.isClosed
  rcases isConstructible_iff_of_noetherianSpace.1 hC F F.isClosed hirr with h | ⟨V, hV, hVF, hVC⟩
  · exact absurd (congrArg (fun G : Closeds X ↦ (G : Set X)) hFeq.symm).le h
  · refine ⟨η, hVC ⟨(hη.mem_open_set_iff hV).2 ?_, hη.mem⟩, hη.specializes hxF⟩
    rwa [inter_comm]

/-- IV.6.3: in a noetherian space in which every irreducible closed subset has a generic point,
a constructible set `U` is a neighbourhood of `x` if and only if it contains every generization
of `x`. -/
theorem mem_nhds_iff_of_isConstructible [NoetherianSpace X] [QuasiSober X] {U : Set X}
    (hU : IsConstructible U) (x : X) : U ∈ 𝓝 x ↔ ∀ y, y ⤳ x → y ∈ U := by
  refine ⟨fun h y hy ↦ mem_of_mem_nhds (hy h), fun h ↦ ?_⟩
  by_contra hx
  rw [← mem_interior_iff_mem_nhds, ← mem_compl_iff, ← closure_compl] at hx
  obtain ⟨y, hyU, hy⟩ := exists_specializes_of_mem_closure hU.compl hx
  exact hyU (h y hy)

/-- IV.6.4: in a noetherian space in which every irreducible closed subset has a generic point,
`U` is open if and only if (a) it contains every generization of each of its points and (b) for
`x ∈ U`, `U ∩ closure {x}` contains a nonempty open subset of `closure {x}`. -/
theorem isOpen_iff_of_noetherianSpace [NoetherianSpace X] [QuasiSober X] {U : Set X} :
    IsOpen U ↔ StableUnderGeneralization U ∧
      ∀ x ∈ U, ∃ V, IsOpen V ∧ (V ∩ closure {x}).Nonempty ∧ V ∩ closure {x} ⊆ U := by
  refine ⟨fun hU ↦ ⟨hU.stableUnderGeneralization, fun x hx ↦
    ⟨U, hU, ⟨x, hx, subset_closure rfl⟩, inter_subset_left⟩⟩, fun ⟨ha, hb⟩ ↦ ?_⟩
  -- `U` is constructible by IV.6.1
  have hC : IsConstructible U := by
    refine isConstructible_iff_of_noetherianSpace.2 fun Y hYc hY ↦ ?_
    obtain ⟨η, hη⟩ := QuasiSober.sober hY hYc
    by_cases hηU : η ∈ U
    · obtain ⟨V, hV, hVne, hVU⟩ := hb η hηU
      rw [hη.def] at hVne hVU
      exact Or.inr ⟨V, hV, hVne, hVU⟩
    · left
      have hUY : U ∩ Y = ∅ := by
        rw [← not_nonempty_iff_eq_empty]
        rintro ⟨y, hyU, hyY⟩
        exact hηU (ha (hη.specializes hyY) hyU)
      rw [hUY, closure_empty, subset_empty_iff]
      exact hY.nonempty.ne_empty
  -- so it is a neighbourhood of each of its points by IV.6.3
  rw [isOpen_iff_mem_nhds]
  exact fun x hx ↦ (mem_nhds_iff_of_isConstructible hC x).2 fun y hy ↦ ha hy hx

section Chevalley

open AlgebraicGeometry

/-- IV.6.2 (Chevalley): the image of a morphism of finite type into a noetherian scheme is
constructible. -/
theorem isConstructible_range {X Y : Scheme.{u}} (f : X ⟶ Y) [IsNoetherian Y]
    [LocallyOfFiniteType f] [QuasiCompact f] : IsConstructible (Set.range f) := by
  rw [← Set.image_univ]
  exact f.isConstructible_image IsConstructible.univ

/-- IV.6.2, for subsets: the image of a constructible set under a morphism of finite type into
a noetherian scheme is constructible. -/
theorem isConstructible_image {X Y : Scheme.{u}} (f : X ⟶ Y) [IsNoetherian Y]
    [LocallyOfFiniteType f] [QuasiCompact f] {s : Set X} (hs : IsConstructible s) :
    IsConstructible (f '' s) :=
  f.isConstructible_image hs

end Chevalley

end SGA.SGA1.ExposeIV
