/-
Copyright (c) 2026 SGAenglishpluslean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SGAenglishpluslean contributors
-/
import SGA.Foundations.Analytic.Henselian
import Mathlib.Order.Filter.Germ.Basic

/-!
# Values of convergent power series near the origin

Near `0`, evaluation of convergent power series is a ring homomorphism. We record this as a ring
homomorphism `germEval : 𝕜{z} → Germ (𝓝 0) 𝕜` to germs of functions at `0`, and we introduce the
*vanishing ideal* `vanishingIdeal Z` of the germ at `0` of a set `Z ⊆ 𝕜^σ`: the convergent series
whose sums vanish on `Z` near `0`. The ideal generated by `s₁, …, sₘ` is contained in the
vanishing ideal of their common zero set (`span_le_vanishingIdeal`).

We also provide evaluation at a point of a polydisc as a ring homomorphism
(`polydisc`, `evalPolydisc`).
-/

open scoped NNReal ENNReal Topology
open Filter Finset

noncomputable section

namespace MvPowerSeries

variable {σ : Type*} {𝕜 : Type*} [NontriviallyNormedField 𝕜]

/-! ### Polydiscs -/

section Polydisc

variable (σ 𝕜) in
/-- The power series converging absolutely on the closed polydisc of polyradius `ρ`. -/
def polydisc (ρ : σ → ℝ≥0) : Subring (MvPowerSeries σ 𝕜) where
  carrier := {f | weightedNorm ρ f ≠ ⊤}
  mul_mem' {f g} hf hg := ne_top_of_le_ne_top (ENNReal.mul_ne_top hf hg) (weightedNorm_mul_le ρ f g)
  one_mem' := by simp
  add_mem' {f g} hf hg :=
    ne_top_of_le_ne_top (ENNReal.add_ne_top.mpr ⟨hf, hg⟩) (weightedNorm_add_le ρ f g)
  zero_mem' := by simp
  neg_mem' {f} hf := by simpa using hf

lemma mem_polydisc {ρ : σ → ℝ≥0} {f : MvPowerSeries σ 𝕜} :
    f ∈ polydisc σ 𝕜 ρ ↔ weightedNorm ρ f ≠ ⊤ := Iff.rfl

lemma X_mem_polydisc (ρ : σ → ℝ≥0) (i : σ) : (X i : MvPowerSeries σ 𝕜) ∈ polydisc σ 𝕜 ρ := by
  simp [mem_polydisc]

variable [CompleteSpace 𝕜]

/-- Evaluation at a point of the polydisc of polyradius `ρ`, as a ring homomorphism. -/
def evalPolydisc (ρ : σ → ℝ≥0) (z : σ → 𝕜) (hz : ∀ i, ‖z i‖₊ ≤ ρ i) :
    polydisc σ 𝕜 ρ →+* 𝕜 where
  toFun f := tsumEval f.1 z
  map_one' := tsumEval_one
  map_mul' f g := tsumEval_mul f.2 g.2 hz
  map_zero' := by simp [tsumEval]
  map_add' f g := tsumEval_add f.2 g.2 hz

@[simp] lemma evalPolydisc_apply (ρ : σ → ℝ≥0) (z : σ → 𝕜) (hz : ∀ i, ‖z i‖₊ ≤ ρ i)
    (f : polydisc σ 𝕜 ρ) : evalPolydisc ρ z hz f = tsumEval f.1 z := rfl

omit [CompleteSpace 𝕜] in
/-- Finitely many convergent power series converge on a common polydisc with constant
positive polyradius. -/
lemma exists_const_radius [Finite σ] {κ : Type*} [Finite κ] (F : κ → MvPowerSeries σ 𝕜)
    (hF : ∀ j, F j ∈ convergent σ 𝕜) :
    ∃ r : ℝ≥0, 0 < r ∧ ∀ j, weightedNorm (fun _ ↦ r) (F j) ≠ ⊤ := by
  choose r hr hFr using fun j ↦ exists_weightedNorm_const_ne_top (hF j)
  cases isEmpty_or_nonempty κ
  · exact ⟨1, one_pos, fun j ↦ isEmptyElim j⟩
  · obtain ⟨j₀, hj₀⟩ := Finite.exists_min r
    exact ⟨r j₀, hr j₀, fun j ↦ ne_top_of_le_ne_top (hFr j)
      (weightedNorm_mono (fun _ ↦ hj₀ j) (F j))⟩

omit [CompleteSpace 𝕜] in
lemma eventually_nnnorm_le_const [Finite σ] {r : ℝ≥0} (hr : 0 < r) :
    ∀ᶠ z in 𝓝 (0 : σ → 𝕜), ∀ i, ‖z i‖₊ ≤ r := by
  have := Fintype.ofFinite σ
  filter_upwards [Metric.eball_mem_nhds (0 : σ → 𝕜) (ENNReal.coe_pos.mpr hr)] with z hz
  exact nnnorm_apply_le_of_mem_eball hz

end Polydisc

/-! ### Germs of sums -/

section Germ

variable [Finite σ] [CompleteSpace 𝕜]

variable (σ 𝕜) in
/-- Near `0`, evaluation of convergent power series is a ring homomorphism: the germ at `0` of
the sum of a convergent power series. -/
def germEval : convergent σ 𝕜 →+* Germ (𝓝 (0 : σ → 𝕜)) 𝕜 where
  toFun f := Germ.coeRingHom _ (tsumEval f.1)
  map_one' := by
    rw [← map_one (Germ.coeRingHom (𝓝 (0 : σ → 𝕜)) (R := 𝕜))]
    congr 1
    funext z
    exact tsumEval_one
  map_mul' f g := by
    rw [← map_mul]
    exact Germ.coe_eq.mpr ((eventually_tsumEval_add_mul f.2 g.2).mono fun z hz ↦ hz.2)
  map_zero' := by
    rw [← map_zero (Germ.coeRingHom (𝓝 (0 : σ → 𝕜)) (R := 𝕜))]
    congr 1
    funext z
    simp [tsumEval]
  map_add' f g := by
    rw [← map_add]
    exact Germ.coe_eq.mpr ((eventually_tsumEval_add_mul f.2 g.2).mono fun z hz ↦ hz.1)

lemma germEval_apply (f : convergent σ 𝕜) :
    germEval σ 𝕜 f = Germ.coeRingHom _ (tsumEval f.1) := rfl

/-- An identity between germs of sums gives an eventual identity between the sums. -/
lemma eventually_of_germEval_eq {f : convergent σ 𝕜} {F : (σ → 𝕜) → 𝕜}
    (h : germEval σ 𝕜 f = Germ.coeRingHom _ F) : ∀ᶠ z in 𝓝 (0 : σ → 𝕜), tsumEval f.1 z = F z :=
  Germ.coe_eq.mp h

lemma eventually_tsumEval_mul_add (f g h : convergent σ 𝕜) :
    ∀ᶠ z in 𝓝 (0 : σ → 𝕜),
      tsumEval (f * g + h).1 z = tsumEval f.1 z * tsumEval g.1 z + tsumEval h.1 z := by
  have : germEval σ 𝕜 (f * g + h) =
      Germ.coeRingHom _ (tsumEval f.1 * tsumEval g.1 + tsumEval h.1) := by
    simp only [map_add, map_mul, germEval_apply]
  filter_upwards [eventually_of_germEval_eq this] with z hz
  exact hz

lemma germEval_X (i : σ) :
    germEval σ 𝕜 ⟨X i, X_mem_convergent i⟩ = Germ.coeRingHom _ (fun z ↦ z i) := by
  rw [germEval_apply]
  congr 1
  funext z
  exact tsumEval_X i

lemma germEval_C (c : 𝕜) :
    germEval σ 𝕜 (algebraMap 𝕜 _ c) = Germ.coeRingHom _ (fun _ ↦ c) := by
  rw [germEval_apply]
  congr 1
  funext z
  exact tsumEval_C c

end Germ

/-! ### Vanishing ideals -/

section Vanishing

variable [Finite σ] [CompleteSpace 𝕜]

variable (σ 𝕜) in
/-- The *vanishing ideal* of (the germ at `0` of) a set `Z ⊆ 𝕜^σ`: the convergent power series
whose sums vanish on `Z` near `0`. -/
def vanishingIdeal (Z : (σ → 𝕜) → Prop) : Ideal (convergent σ 𝕜) where
  carrier := {f | ∀ᶠ z in 𝓝 (0 : σ → 𝕜), Z z → tsumEval f.1 z = 0}
  add_mem' {f g} hf hg := by
    filter_upwards [hf, hg, eventually_tsumEval_add_mul f.2 g.2] with z h₁ h₂ h₃ hz
    change tsumEval (f.1 + g.1) z = 0
    rw [h₃.1, h₁ hz, h₂ hz, add_zero]
  zero_mem' := Eventually.of_forall fun z _ ↦ by simp [tsumEval]
  smul_mem' c {f} hf := by
    filter_upwards [hf, eventually_tsumEval_add_mul c.2 f.2] with z h₁ h₃ hz
    change tsumEval (c.1 * f.1) z = 0
    rw [h₃.2, h₁ hz, mul_zero]

lemma mem_vanishingIdeal {Z : (σ → 𝕜) → Prop} {f : convergent σ 𝕜} :
    f ∈ vanishingIdeal σ 𝕜 Z ↔ ∀ᶠ z in 𝓝 (0 : σ → 𝕜), Z z → tsumEval f.1 z = 0 := Iff.rfl

/-- The germ at `0` of the common zero set of a family of convergent power series. -/
def ZeroLocus {ι : Type*} (s : ι → convergent σ 𝕜) (z : σ → 𝕜) : Prop :=
  ∀ i, tsumEval (s i).1 z = 0

/-- The elements of the ideal generated by `s₁, …, sₘ` vanish on the common zero set of the
`sᵢ` near `0`. -/
lemma span_le_vanishingIdeal {ι : Type*} (s : ι → convergent σ 𝕜) :
    Ideal.span (Set.range s) ≤ vanishingIdeal σ 𝕜 (ZeroLocus s) := by
  rw [Ideal.span_le]
  rintro _ ⟨i, rfl⟩
  exact Eventually.of_forall fun z hz ↦ hz i

lemma eventually_zeroLocus_of_le {ι κ : Type*} [Finite κ] {s : ι → convergent σ 𝕜}
    {t : κ → convergent σ 𝕜} (h : Set.range t ⊆ Ideal.span (Set.range s)) :
    ∀ᶠ z in 𝓝 (0 : σ → 𝕜), ZeroLocus s z → ZeroLocus t z := by
  have : ∀ j, ∀ᶠ z in 𝓝 (0 : σ → 𝕜), ZeroLocus s z → tsumEval (t j).1 z = 0 := fun j ↦
    span_le_vanishingIdeal s (h ⟨j, rfl⟩)
  filter_upwards [eventually_all.mpr this] with z hz hs j
  exact hz j hs

end Vanishing

end MvPowerSeries
