/-
Copyright (c) 2026 SGAenglishpluslean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SGAenglishpluslean contributors
-/
import SGA.Foundations.Analytic.Sheaf
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.LocalRing.Basic

/-!
# Local models of analytic spaces

Let `U` be an open subset of a normed space `E` over `𝕜` and `f₁, …, f_k` functions analytic on
`U`. The *local model* defined by these data is the locally ringed space
`(Z, (𝒪_U/(f₁, …, f_k))|_Z)` where `Z = {x ∈ U | f₁(x) = ⋯ = f_k(x) = 0}`: its stalk at `x ∈ Z`
is `𝒪_{E,x}/(f₁, …, f_k)`, and its sections are the functions assigning to each point of `Z` a
class in this stalk which is locally the class of a single analytic function
([Grauert–Remmert, *Coherent analytic sheaves*, §1.1]; [SGA 1, XII.1]). Complex analytic spaces
are the locally ringed spaces locally isomorphic to local models with `E = ℂⁿ`.

## Main definitions

* `AnalyticGeometry.LocalModelData`: the data `(U, f₁, …, f_k)`.
* `LocalModelData.zeroSet`, `LocalModelData.Fiber x = 𝒪_{E,x}/(f)`.
* `LocalModelData.sheaf`: the structure sheaf of the local model.
* `LocalModelData.stalkIso`: its stalk at `x` is `𝒪_{E,x}/(f)`.
* `LocalModelData.toLocallyRingedSpace`: the local model as a locally ringed space.
* `LocalModelData.classSection`: the section defined by a function analytic on `U`.
-/

universe u

noncomputable section

open CategoryTheory Topology TopologicalSpace Opposite Filter CategoryTheory.Limits

namespace AnalyticGeometry

variable (𝕜 : Type u) [NontriviallyNormedField 𝕜] [CompleteSpace 𝕜] (E : Type u)
  [NormedAddCommGroup E] [NormedSpace 𝕜 E]

/-- The data of a local model: an open subset `U` of `E` and finitely many functions analytic on
`U`. -/
structure LocalModelData where
  /-- The ambient open set. -/
  U : Set E
  isOpen_U : IsOpen U
  /-- The number of equations. -/
  k : ℕ
  /-- The equations. -/
  f : Fin k → E → 𝕜
  analyticAt_f : ∀ i, ∀ x ∈ U, AnalyticAt 𝕜 (f i) x

namespace LocalModelData

variable {𝕜 E} (D : LocalModelData 𝕜 E)

/-- The zero set `Z = {x ∈ U | f(x) = 0}` of a local model. -/
def zeroSet : Set E := {x | x ∈ D.U ∧ ∀ i, D.f i x = 0}

omit [CompleteSpace 𝕜] in
lemma mem_U (x : D.zeroSet) : (x : E) ∈ D.U := x.2.1

omit [CompleteSpace 𝕜] in
lemma f_eq_zero (x : D.zeroSet) (i : Fin D.k) : D.f i x = 0 := x.2.2 i

/-- The ideal of the stalk `𝒪_{E,x}` generated by the germs of the equations. -/
def ideal (x : E) (hx : x ∈ D.U) :
    Ideal ((analyticPresheaf 𝕜 E).stalk x) :=
  Ideal.span (Set.range fun i ↦ germOf (D.f i) (D.analyticAt_f i x hx))

/-- The stalk `𝒪_{E,x}/(f)` of the local model at a point `x ∈ Z`. -/
abbrev Fiber (x : D.zeroSet) : Type u :=
  (analyticPresheaf 𝕜 E).stalk (x : E) ⧸ D.ideal x (D.mem_U x)

/-- The class in `𝒪_{E,x}/(f)` of a function analytic at `x`. -/
def classOf (x : D.zeroSet) (g : E → 𝕜) (hg : AnalyticAt 𝕜 g x) : D.Fiber x :=
  Ideal.Quotient.mk _ (germOf g hg)

lemma classOf_congr {x : D.zeroSet} {g h : E → 𝕜} (hg : AnalyticAt 𝕜 g x)
    (e : g =ᶠ[𝓝 (x : E)] h) : D.classOf x g hg = D.classOf x h (hg.congr e) := by
  rw [classOf, classOf, germOf_congr hg e]

lemma classOf_add {x : D.zeroSet} {g h : E → 𝕜} (hg : AnalyticAt 𝕜 g x)
    (hh : AnalyticAt 𝕜 h x) :
    D.classOf x (g + h) (hg.add hh) = D.classOf x g hg + D.classOf x h hh := by
  rw [classOf, classOf, classOf, germOf_add, map_add]

lemma classOf_mul {x : D.zeroSet} {g h : E → 𝕜} (hg : AnalyticAt 𝕜 g x)
    (hh : AnalyticAt 𝕜 h x) :
    D.classOf x (g * h) (hg.mul hh) = D.classOf x g hg * D.classOf x h hh := by
  rw [classOf, classOf, classOf, germOf_mul, map_mul]

lemma classOf_neg {x : D.zeroSet} {g : E → 𝕜} (hg : AnalyticAt 𝕜 g x) :
    D.classOf x (-g) hg.neg = -D.classOf x g hg := by
  rw [classOf, classOf, germOf_neg, map_neg]

lemma classOf_one (x : D.zeroSet) :
    D.classOf x (fun _ ↦ 1) analyticAt_const = 1 := by
  rw [classOf, germOf_one, map_one]

lemma classOf_zero (x : D.zeroSet) :
    D.classOf x (fun _ ↦ 0) analyticAt_const = 0 := by
  rw [classOf, germOf_zero, map_zero]

lemma classOf_f (x : D.zeroSet) (i : Fin D.k) :
    D.classOf x (D.f i) (D.analyticAt_f i x (D.mem_U x)) = 0 :=
  Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.subset_span ⟨i, rfl⟩)

lemma classOf_surjective (x : D.zeroSet) (t : D.Fiber x) :
    ∃ (g : E → 𝕜) (hg : AnalyticAt 𝕜 g x), D.classOf x g hg = t := by
  obtain ⟨s, rfl⟩ := Ideal.Quotient.mk_surjective t
  obtain ⟨g, hg, rfl⟩ := exists_germOf_eq s
  exact ⟨g, hg, rfl⟩

/-- If the class of `g` vanishes at `x`, then `g = ∑ hᵢ fᵢ` near `x` with `hᵢ` analytic at `x`. -/
lemma exists_eq_sum_of_classOf_eq_zero {x : D.zeroSet} {g : E → 𝕜} (hg : AnalyticAt 𝕜 g x)
    (h : D.classOf x g hg = 0) :
    ∃ (c : Fin D.k → E → 𝕜) (_ : ∀ i, AnalyticAt 𝕜 (c i) x),
      g =ᶠ[𝓝 (x : E)] fun y ↦ ∑ i, c i y * D.f i y := by
  rw [classOf, Ideal.Quotient.eq_zero_iff_mem, ideal, Ideal.mem_span_range_iff_exists_fun] at h
  obtain ⟨c, hc⟩ := h
  choose c' hc' hcc' using fun i ↦ exists_germOf_eq (c i)
  refine ⟨c', hc', ?_⟩
  have hsum : AnalyticAt 𝕜 (fun y ↦ ∑ i, c' i y * D.f i y) x := by
    refine (Finset.univ.analyticAt_sum fun i _ ↦ (hc' i).mul
      (D.analyticAt_f i x (D.mem_U x))).congr ?_
    exact Eventually.of_forall fun y ↦ by simp
  refine (germOf_eq_germOf_iff hg hsum).mp ?_
  rw [← hc, germOf_sum (g := fun i y ↦ c' i y * D.f i y) Finset.univ
    (fun i ↦ (hc' i).mul (D.analyticAt_f i x (D.mem_U x)))]
  exact Finset.sum_congr rfl fun i _ ↦ by
    rw [← hcc' i]
    exact (germOf_mul (hc' i) (D.analyticAt_f i x (D.mem_U x))).symm

/-! ### The structure sheaf -/

/-- The prelocal predicate: a section is the class of a single analytic function. -/
def isClassPredicate : TopCat.PrelocalPredicate fun x : TopCat.of D.zeroSet ↦ D.Fiber x where
  pred {W} s := ∃ (g : E → 𝕜) (hg : ∀ y : W, AnalyticAt 𝕜 g ((y : D.zeroSet) : E)),
    ∀ y : W, s y = D.classOf y g (hg y)
  res {W V} i s := by
    rintro ⟨g, hg, hs⟩
    exact ⟨g, fun y ↦ hg ⟨y.1, leOfHom i y.2⟩, fun y ↦ hs ⟨y.1, leOfHom i y.2⟩⟩

/-- The local predicate defining the structure sheaf: locally the class of an analytic
function. -/
def localPredicate : TopCat.LocalPredicate fun x : TopCat.of D.zeroSet ↦ D.Fiber x :=
  D.isClassPredicate.sheafify

/-- The sections of the structure sheaf over an open subset of `Z`. -/
def sectionsSubring (W : Opens (TopCat.of D.zeroSet)) : Subring (∀ x : W, D.Fiber x) where
  carrier := {s | D.localPredicate.pred s}
  zero_mem' := TopCat.PrelocalPredicate.sheafifyOf
    ⟨fun _ ↦ 0, fun _ ↦ analyticAt_const, fun y ↦ (D.classOf_zero y).symm⟩
  one_mem' := TopCat.PrelocalPredicate.sheafifyOf
    ⟨fun _ ↦ 1, fun _ ↦ analyticAt_const, fun y ↦ (D.classOf_one y).symm⟩
  add_mem' {s t} hs ht := by
    refine TopCat.PrelocalPredicate.sheafify_inductionOn₂' D.isClassPredicate
      D.isClassPredicate D.isClassPredicate (fun a b ↦ a + b) ?_ hs ht
    rintro U V a b ⟨g, hg, ha⟩ ⟨h, hh, hb⟩
    exact ⟨g + h, fun y ↦ (hg ⟨y, y.2.1⟩).add (hh ⟨y, y.2.2⟩), fun y ↦ by
      dsimp only
      rw [ha, hb, classOf_add]⟩
  mul_mem' {s t} hs ht := by
    refine TopCat.PrelocalPredicate.sheafify_inductionOn₂' D.isClassPredicate
      D.isClassPredicate D.isClassPredicate (fun a b ↦ a * b) ?_ hs ht
    rintro U V a b ⟨g, hg, ha⟩ ⟨h, hh, hb⟩
    exact ⟨g * h, fun y ↦ (hg ⟨y, y.2.1⟩).mul (hh ⟨y, y.2.2⟩), fun y ↦ by
      dsimp only
      rw [ha, hb, classOf_mul]⟩
  neg_mem' {s} hs := by
    refine TopCat.PrelocalPredicate.sheafify_inductionOn' D.isClassPredicate
      (fun a ↦ -a) ?_ hs
    rintro U a ⟨g, hg, ha⟩
    exact ⟨-g, fun y ↦ (hg _).neg, fun y ↦ by
      dsimp only
      rw [ha, classOf_neg]⟩

/-- The structure presheaf of the local model. -/
def presheaf : TopCat.Presheaf CommRingCat.{u} (TopCat.of D.zeroSet) where
  obj W := CommRingCat.of (D.sectionsSubring W.unop)
  map {W V} i := CommRingCat.ofHom
    { toFun s := ⟨fun x ↦ s.1 ⟨x.1, leOfHom i.unop x.2⟩, D.localPredicate.res i.unop s.1 s.2⟩
      map_one' := rfl
      map_mul' _ _ := rfl
      map_zero' := rfl
      map_add' _ _ := rfl }

@[simp] lemma presheaf_map_apply {W V : (Opens (TopCat.of D.zeroSet))ᵒᵖ} (i : W ⟶ V)
    (s : D.presheaf.obj W) (x : V.unop) :
    (D.presheaf.map i s).1 x = s.1 ⟨x.1, leOfHom i.unop x.2⟩ := rfl

/-- The structure sheaf `(𝒪_U/(f))|_Z` of the local model. -/
def sheaf : TopCat.Sheaf CommRingCat.{u} (TopCat.of D.zeroSet) where
  obj := D.presheaf
  property := by
    rw [CategoryTheory.Presheaf.isSheaf_iff_isSheaf_forget _ _
      (CategoryTheory.forget CommRingCat)]
    exact (TopCat.subsheafToTypes D.localPredicate).property

lemma isSheaf : D.presheaf.IsSheaf := D.sheaf.property

/-! ### Stalks -/

/-- Evaluation of sections at a point. -/
def evalAt (x : D.zeroSet) (W : OpenNhds (X := TopCat.of D.zeroSet) x) :
    D.presheaf.obj (op W.1) ⟶ CommRingCat.of (D.Fiber x) :=
  CommRingCat.ofHom
    { toFun s := s.1 ⟨x, W.2⟩
      map_one' := rfl
      map_mul' _ _ := rfl
      map_zero' := rfl
      map_add' _ _ := rfl }

/-- The map from the stalk of the structure sheaf at `x` to `𝒪_{E,x}/(f)`. -/
def stalkToFiber (x : D.zeroSet) :
    D.presheaf.stalk x ⟶ CommRingCat.of (D.Fiber x) :=
  colimit.desc ((OpenNhds.inclusion (X := TopCat.of D.zeroSet) x).op ⋙ D.presheaf)
    { pt := CommRingCat.of (D.Fiber x)
      ι :=
        { app W := D.evalAt x W.unop
          naturality _ _ _ := rfl } }

lemma stalkToFiber_germ (W : Opens (TopCat.of D.zeroSet)) (x : D.zeroSet) (hx : x ∈ W)
    (s : D.presheaf.obj (op W)) :
    D.stalkToFiber x (D.presheaf.germ W x hx s) = s.1 ⟨x, hx⟩ := by
  change (colimit.ι ((OpenNhds.inclusion (X := TopCat.of D.zeroSet) x).op ⋙ D.presheaf)
    (op ⟨W, hx⟩) ≫ D.stalkToFiber x) s = _
  rw [stalkToFiber, colimit.ι_desc]
  rfl

/-- The section `y ↦ [g]_y` over the part of `Z` where `g` is analytic. -/
def classSectionOn (g : E → 𝕜) (V : Opens (TopCat.of D.zeroSet))
    (hV : ∀ y ∈ V, AnalyticAt 𝕜 g ((y : D.zeroSet) : E)) : D.presheaf.obj (op V) :=
  ⟨fun y ↦ D.classOf y g (hV y y.2),
    TopCat.PrelocalPredicate.sheafifyOf (P := D.isClassPredicate) (U := V)
      (f := fun y ↦ D.classOf y g (hV y y.2)) ⟨g, fun y ↦ hV y y.2, fun _ ↦ rfl⟩⟩

/-- The global section `y ↦ [h]_y` defined by a function `h` analytic on `U`. -/
def globalSection (h : E → 𝕜) (hh : ∀ x ∈ D.U, AnalyticAt 𝕜 h x) : D.presheaf.obj (op ⊤) :=
  D.classSectionOn h ⊤ fun y _ ↦ hh _ (D.mem_U y)

@[simp] lemma globalSection_apply (h : E → 𝕜) (hh : ∀ x ∈ D.U, AnalyticAt 𝕜 h x)
    (y : (⊤ : Opens (TopCat.of D.zeroSet))) :
    (D.globalSection h hh).1 y = D.classOf y h (hh _ (D.mem_U y)) := rfl

lemma stalkToFiber_germ_globalSection (x : D.zeroSet) (h : E → 𝕜)
    (hh : ∀ x ∈ D.U, AnalyticAt 𝕜 h x) :
    D.stalkToFiber x (D.presheaf.germ ⊤ x (Set.mem_univ _) (D.globalSection h hh)) =
      D.classOf x h (hh _ (D.mem_U x)) := by
  rw [stalkToFiber_germ]
  rfl

lemma globalSection_add (h₁ h₂ : E → 𝕜) (hh₁ : ∀ x ∈ D.U, AnalyticAt 𝕜 h₁ x)
    (hh₂ : ∀ x ∈ D.U, AnalyticAt 𝕜 h₂ x) :
    D.globalSection (h₁ + h₂) (fun x hx ↦ (hh₁ x hx).add (hh₂ x hx)) =
      D.globalSection h₁ hh₁ + D.globalSection h₂ hh₂ :=
  Subtype.ext <| funext fun _ ↦ D.classOf_add _ _

lemma globalSection_mul (h₁ h₂ : E → 𝕜) (hh₁ : ∀ x ∈ D.U, AnalyticAt 𝕜 h₁ x)
    (hh₂ : ∀ x ∈ D.U, AnalyticAt 𝕜 h₂ x) :
    D.globalSection (h₁ * h₂) (fun x hx ↦ (hh₁ x hx).mul (hh₂ x hx)) =
      D.globalSection h₁ hh₁ * D.globalSection h₂ hh₂ :=
  Subtype.ext <| funext fun _ ↦ D.classOf_mul _ _

lemma globalSection_one : D.globalSection (fun _ ↦ 1) (fun _ _ ↦ analyticAt_const) = 1 :=
  Subtype.ext <| funext fun y ↦ D.classOf_one y

lemma globalSection_zero : D.globalSection (fun _ ↦ 0) (fun _ _ ↦ analyticAt_const) = 0 :=
  Subtype.ext <| funext fun y ↦ D.classOf_zero y

lemma globalSection_congr {h₁ h₂ : E → 𝕜} (hh₁ : ∀ x ∈ D.U, AnalyticAt 𝕜 h₁ x)
    (e : ∀ x ∈ D.U, h₁ x = h₂ x) :
    D.globalSection h₁ hh₁ = D.globalSection h₂ fun x hx ↦
      (hh₁ x hx).congr (Filter.eventuallyEq_of_mem (D.isOpen_U.mem_nhds hx) e) :=
  Subtype.ext <| funext fun y ↦ D.classOf_congr _
    (Filter.eventuallyEq_of_mem (D.isOpen_U.mem_nhds (D.mem_U y)) e)

lemma globalSection_f (i : Fin D.k) : D.globalSection (D.f i) (D.analyticAt_f i) = 0 :=
  Subtype.ext <| funext fun y ↦ D.classOf_f y i

lemma stalkToFiber_surjective (x : D.zeroSet) : Function.Surjective (D.stalkToFiber x) := by
  intro t
  obtain ⟨g, hg, rfl⟩ := D.classOf_surjective x t
  let V : Opens (TopCat.of D.zeroSet) :=
    ⟨Subtype.val ⁻¹' {y | AnalyticAt 𝕜 g y},
      (isOpen_analyticAt 𝕜 g).preimage continuous_subtype_val⟩
  exact ⟨D.presheaf.germ V x hg (D.classSectionOn g V fun y hy ↦ hy),
    by rw [stalkToFiber_germ]; rfl⟩

lemma stalkToFiber_injective (x : D.zeroSet) : Function.Injective (D.stalkToFiber x) := by
  rw [injective_iff_map_eq_zero]
  intro s hs
  obtain ⟨W, hxW, s, rfl⟩ := D.presheaf.exists_germ_eq s
  rw [stalkToFiber_germ] at hs
  -- `s` is locally the class of an analytic function `g`
  obtain ⟨V, hxV, iVW, g, hg, hsg⟩ := s.2 ⟨x, hxW⟩
  have hg0 : D.classOf x g (hg ⟨x, hxV⟩) = 0 := by
    rw [← hs]
    exact (hsg ⟨x, hxV⟩).symm
  obtain ⟨c, hc, hgc⟩ := D.exists_eq_sum_of_classOf_eq_zero (hg ⟨x, hxV⟩) hg0
  -- near `x`, `g = ∑ cᵢ fᵢ` with `cᵢ` analytic, so the class of `g` vanishes
  have hev : ∀ᶠ y in 𝓝 (x : E), (g =ᶠ[𝓝 y] fun y ↦ ∑ i, c i y * D.f i y) ∧
      ∀ i, AnalyticAt 𝕜 (c i) y := by
    refine hgc.eventually_nhds.and ?_
    exact Filter.eventually_all.mpr fun i ↦ (hc i).eventually_analyticAt
  obtain ⟨N, hN, hNo, hxN⟩ := mem_nhds_iff.mp hev
  let N' : Opens (TopCat.of D.zeroSet) :=
    ⟨Subtype.val ⁻¹' N, hNo.preimage continuous_subtype_val⟩
  have hxN' : x ∈ N' ⊓ V := ⟨hxN, hxV⟩
  have hle : N' ⊓ V ≤ W := inf_le_right.trans (leOfHom iVW)
  rw [← TopCat.Presheaf.germ_res_apply D.presheaf (homOfLE hle) x hxN' s]
  suffices hzero : D.presheaf.map (homOfLE hle).op s = 0 by
    rw [hzero, map_zero]
  apply Subtype.ext
  funext y
  have hyV : (y : D.zeroSet) ∈ V := y.2.2
  have hsy := hsg ⟨y, hyV⟩
  change s.1 _ = 0
  refine hsy.trans ?_
  obtain ⟨hyg, hyc⟩ := hN y.2.1
  rw [D.classOf_congr _ hyg, classOf]
  apply Ideal.Quotient.eq_zero_iff_mem.mpr
  have hsum := germOf_sum (x := ((y : D.zeroSet) : E)) (g := fun i z ↦ c i z * D.f i z)
    Finset.univ (fun i ↦ (hyc i).mul (D.analyticAt_f i _ (D.mem_U y)))
    ((hg ⟨y, hyV⟩).congr hyg)
  rw [hsum]
  refine Submodule.sum_mem _ fun i _ ↦ ?_
  rw [show germOf (fun z ↦ c i z * D.f i z) ((hyc i).mul (D.analyticAt_f i _ (D.mem_U y))) =
    germOf (c i) (hyc i) * germOf (D.f i) (D.analyticAt_f i _ (D.mem_U y)) from
    germOf_mul (hyc i) (D.analyticAt_f i _ (D.mem_U y))]
  exact Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨i, rfl⟩)

/-- The stalk of the local model at `x ∈ Z` is `𝒪_{E,x}/(f)`. -/
def stalkIso (x : D.zeroSet) :
    D.presheaf.stalk x ≃+* D.Fiber x :=
  RingEquiv.ofBijective (D.stalkToFiber x).hom
    ⟨D.stalkToFiber_injective x, D.stalkToFiber_surjective x⟩

lemma ideal_le_maximalIdeal (x : D.zeroSet) :
    D.ideal x (D.mem_U x) ≤ IsLocalRing.maximalIdeal _ := by
  rw [ideal, Ideal.span_le]
  rintro _ ⟨i, rfl⟩
  rw [SetLike.mem_coe, mem_maximalIdeal_stalk_iff, evalStalk_germOf]
  exact x.2.2 i

instance (x : D.zeroSet) : Nontrivial (D.Fiber x) :=
  Ideal.Quotient.nontrivial_iff.mpr
    (ne_top_of_le_ne_top (IsLocalRing.maximalIdeal.isMaximal _).ne_top (D.ideal_le_maximalIdeal x))

instance (x : D.zeroSet) : IsLocalRing (D.Fiber x) :=
  IsLocalRing.of_surjective' (Ideal.Quotient.mk _) Ideal.Quotient.mk_surjective

/-- Evaluation at `x` of classes in `𝒪_{E,x}/(f)`. -/
def evalFiber (x : D.zeroSet) : D.Fiber x →+* 𝕜 :=
  Ideal.Quotient.lift _ (evalStalk (x : E)) fun a ha ↦
    (mem_maximalIdeal_stalk_iff a).mp (D.ideal_le_maximalIdeal x ha)

@[simp] lemma evalFiber_classOf (x : D.zeroSet) (h : E → 𝕜) (hh : AnalyticAt 𝕜 h x) :
    D.evalFiber x (D.classOf x h hh) = h x :=
  evalStalk_germOf h hh

lemma isUnit_fiber_iff {x : D.zeroSet} (t : D.Fiber x) : IsUnit t ↔ D.evalFiber x t ≠ 0 := by
  refine ⟨fun h ↦ (h.map (D.evalFiber x)).ne_zero, fun h ↦ ?_⟩
  obtain ⟨s, rfl⟩ := Ideal.Quotient.mk_surjective t
  exact ((isUnit_stalk_iff s).mpr h).map _

lemma mem_maximalIdeal_fiber_iff {x : D.zeroSet} (t : D.Fiber x) :
    t ∈ IsLocalRing.maximalIdeal (D.Fiber x) ↔ D.evalFiber x t = 0 := by
  rw [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff, isUnit_fiber_iff, not_not]

instance isLocalRing_stalk (x : D.zeroSet) :
    IsLocalRing (D.presheaf.stalk x) :=
  (D.stalkIso x).symm.isLocalRing

/-- The local model as a locally ringed space. -/
abbrev toLocallyRingedSpace : AlgebraicGeometry.LocallyRingedSpace.{u} where
  carrier := TopCat.of D.zeroSet
  presheaf := D.presheaf
  IsSheaf := D.isSheaf
  isLocalRing x := D.isLocalRing_stalk x

end LocalModelData

end AnalyticGeometry
