/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.Foundations.Analytic.OkaRelationSheaf
import SGA.Foundations.Analytic.OkaCylinder
import SGA.Foundations.Analytic.OkaPreparation

/-!
# Oka's coherence theorem

**Oka's coherence theorem** ([Grauert–Remmert, *Coherent analytic sheaves*, 2.5];
[Demailly, *Complex analytic and differential geometry*, II.3.19]; [Gunning–Rossi, IV.C]): for
every finite matrix `A` of functions analytic near a point `x₀` of `𝕜ⁿ` (`𝕜` a complete
nontrivially normed field, e.g. `ℂ`), the sheaf of relations between the columns of `A` is of
finite type near `x₀` (`AnalyticGeometry.hasFiniteRelationsNear`).

The proof is the classical induction on `n`:

* the case of a matrix follows from the case of a row (`HasFiniteRelationsNear.of_rows`);
* for a row `f₁, …, f_p` near `x₀ ∈ 𝕜^{n+1}` with some nonzero germ, a linear change of
  coordinates (a shear) and Weierstrass preparation make the germs `fᵢ`, up to units, monic
  polynomials `Qᵢ` in the last variable with coefficients analytic in the first `n` variables
  (`MvPowerSeries.exists_simultaneous_weierstrass_preparation`);
* at every point of a cylinder `V' × 𝕜`, the relations between the `Qᵢ` are generated by the
  elementary relations and by the polynomial relations of degree at most `2μ`
  (`relationModule_eq_span_of_coefficient_generators`; this uses Weierstrass division at every
  point of the cylinder). Polynomial relations of bounded degree are the solutions of a finite
  linear system with coefficients analytic on `V'`, whose relation sheaf is of finite type by
  induction (`polynomialRow_hasFiniteRelationsNear`).

The statement in germ form, `AnalyticGeometry.OkaCoherenceStatement`, is deduced in
`SGA.Foundations.Analytic.Oka`.
-/

noncomputable section

universe u

open CategoryTheory TopologicalSpace Filter Set MvPowerSeries
open scoped Topology Polynomial

namespace MvPowerSeries

variable {τ : Type*} [Fintype τ] {𝕜 : Type*} [NontriviallyNormedField 𝕜]

/-- The shear is linear, hence analytic at every point. -/
lemma analyticAt_shear_apply (v z : Option τ → 𝕜) : AnalyticAt 𝕜 (shear v) z := by
  refine AnalyticAt.pi (f := fun o z ↦ shear v z o) fun o ↦ ?_
  cases o with
  | none => exact analyticAt_const.mul (analyticAt_apply none z)
  | some i =>
    exact (analyticAt_apply (some i) z).add (analyticAt_const.mul (analyticAt_apply none z))

/-- The inverse shear is linear, hence analytic at every point. -/
lemma analyticAt_shearInv_apply (v z : Option τ → 𝕜) : AnalyticAt 𝕜 (shearInv v) z := by
  refine AnalyticAt.pi (f := fun o z ↦ shearInv v z o) fun o ↦ ?_
  cases o with
  | none => exact (analyticAt_apply none z).div_const
  | some i =>
    exact (analyticAt_apply (some i) z).sub
      (analyticAt_const.mul (analyticAt_apply none z).div_const)

end MvPowerSeries

namespace AnalyticGeometry

/-! ### Bounded polynomial relations as a matrix kernel -/

section BoundedRelations

variable {R : Type*} [CommRing R] {ι : Type*} [Fintype ι]

/-- The coefficient matrix of the bounded relation equations: the entry in row `m` and column
`(i, l)` is the coefficient of `Xᵐ` in `Xˡ Pᵢ`. -/
def boundedRelationMatrix (P : ι → R[X]) (d μ : ℕ) :
    Fin (d + μ + 1) → ι × Fin (d + 1) → R :=
  fun m il ↦ (Polynomial.X ^ (il.2 : ℕ) * P il.1).coeff m

lemma boundedRelationEquations_apply_eq_sum (P : ι → R[X]) (d μ : ℕ)
    (a : ι → Fin (d + 1) → R) (m : Fin (d + μ + 1)) :
    Polynomial.boundedRelationEquations P d μ a m =
      ∑ il : ι × Fin (d + 1), a il.1 il.2 * boundedRelationMatrix P d μ m il := by
  classical
  rw [Polynomial.boundedRelationEquations_apply, Fintype.sum_prod_type]
  simp only [Polynomial.boundedRelationCombination, LinearMap.coe_mk, AddHom.coe_mk,
    Polynomial.finsetSum_coeff, boundedRelationMatrix]
  refine Finset.sum_congr rfl fun i _ ↦ ?_
  rw [Polynomial.ofFn_eq_sum_monomial, Finset.sum_mul, Polynomial.finsetSum_coeff]
  refine Finset.sum_congr rfl fun l _ ↦ ?_
  rw [← Polynomial.C_mul_X_pow_eq_monomial, mul_assoc, Polynomial.coeff_C_mul]

/-- Generators of the relations of the coefficient matrix generate the bounded relations. -/
lemma ker_boundedRelationEquations_eq_span (P : ι → R[X]) (d μ : ℕ) {κ : Type*} [Finite κ]
    (B : κ → ι → Fin (d + 1) → R)
    (h : matrixRelationModule (boundedRelationMatrix P d μ) =
      Submodule.span R (Set.range fun k (il : ι × Fin (d + 1)) ↦ B k il.1 il.2)) :
    (Polynomial.boundedRelationEquations P d μ).ker = Submodule.span R (Set.range B) := by
  have := Fintype.ofFinite κ
  ext a
  have key : a ∈ (Polynomial.boundedRelationEquations P d μ).ker ↔
      (fun il : ι × Fin (d + 1) ↦ a il.1 il.2) ∈
        matrixRelationModule (boundedRelationMatrix P d μ) := by
    rw [LinearMap.mem_ker, mem_matrixRelationModule, funext_iff]
    exact forall_congr' fun m ↦ by rw [boundedRelationEquations_apply_eq_sum]; rfl
  rw [key, h, Submodule.mem_span_range_iff_exists_fun, Submodule.mem_span_range_iff_exists_fun]
  constructor
  · rintro ⟨c, hc⟩
    refine ⟨c, funext fun i ↦ funext fun l ↦ ?_⟩
    have := congrFun hc (i, l)
    simpa only [Finset.sum_apply, Pi.smul_apply] using this
  · rintro ⟨c, hc⟩
    refine ⟨c, funext fun il ↦ ?_⟩
    have := congrFun (congrFun hc il.1) il.2
    simpa only [Finset.sum_apply, Pi.smul_apply] using this

omit [Fintype ι] in
lemma map_boundedRelationMatrix {S : Type*} [CommRing S] (φ : R →+* S) (P : ι → R[X])
    (d μ : ℕ) (m : Fin (d + μ + 1)) (il : ι × Fin (d + 1)) :
    φ (boundedRelationMatrix P d μ m il) =
      boundedRelationMatrix (fun i ↦ (P i).map φ) d μ m il := by
  simp only [boundedRelationMatrix, ← Polynomial.coeff_map, Polynomial.map_mul,
    Polynomial.map_pow, Polynomial.map_X]

end BoundedRelations

/-! ### Germs and the shear -/

section Shear

variable {𝕜 : Type u} [NontriviallyNormedField 𝕜] [CompleteSpace 𝕜] {τ : Type u} [Fintype τ]
  [DecidableEq τ]

omit [DecidableEq τ] in
/-- In the convergent power series of a germ at `x₀`, the shear `shearEquiv` is the composition
with the affine map `z ↦ x₀ + shear v (z - x₀)`. -/
lemma convergentStalkEquiv_shearEquiv (x₀ : Option τ → 𝕜) {v : Option τ → 𝕜}
    (hv : v none ≠ 0) {f : (Option τ → 𝕜) → 𝕜} (hf : AnalyticAt 𝕜 f x₀)
    (hf' : AnalyticAt 𝕜 (fun z ↦ f (x₀ + shear v (z - x₀))) x₀) :
    convergentStalkEquiv x₀ (shearEquiv hv ((convergentStalkEquiv x₀).symm (germOf f hf))) =
      germOf (fun z ↦ f (x₀ + shear v (z - x₀))) hf' := by
  set F := (convergentStalkEquiv x₀).symm (germOf f hf) with hFdef
  have hF : convergentStalkEquiv x₀ F = germOf f hf := by rw [hFdef, RingEquiv.apply_symm_apply]
  rw [convergentStalkEquiv_apply, convergentToStalk_apply] at hF ⊢
  have hfF : (fun y ↦ tsumEval F.1 (y - x₀)) =ᶠ[𝓝 x₀] f := (germOf_eq_germOf_iff _ _).mp hF
  rw [germOf_eq_germOf_iff]
  have hΦ : Tendsto (fun z ↦ x₀ + shear v (z - x₀)) (𝓝 x₀) (𝓝 x₀) := by
    have hc : Continuous (fun z ↦ x₀ + shear v (z - x₀)) :=
      continuous_const.add ((continuous_iff_continuousAt.mpr fun w ↦
        (analyticAt_shear_apply v w).continuousAt).comp (continuous_sub_right x₀))
    simpa [shear_zero] using hc.tendsto x₀
  have h1 := (tendsto_sub_nhds_zero x₀).eventually
    (tsumEval_substAnalytic (analyticAt_shear v) (shear_zero v) F.2)
  filter_upwards [h1, hΦ.eventually hfF] with z hz₁ hz₂
  rw [coe_shearEquiv, ← hz₁, ← hz₂, add_sub_cancel_left]

end Shear

/-! ### The polynomial step -/

section Cylinder

-- The stalks and sections of `analyticPresheaf` are `CommRingCat` objects whose carriers are
-- the subalgebras `analyticSections`; unifying the two ring structures needs this option (as in
-- `SGA.Foundations.Analytic.OkaCylinder`).
set_option backward.isDefEq.respectTransparency false

variable {𝕜 : Type u} [NontriviallyNormedField 𝕜] [CompleteSpace 𝕜]

omit [CompleteSpace 𝕜] in
lemma germ_analyticRestrict {E : Type u} [NormedAddCommGroup E] [NormedSpace 𝕜 E]
    {U V : Opens E} (h : V ≤ U) {x : E} (hx : x ∈ V) (s : analyticSections 𝕜 U) :
    (analyticPresheaf 𝕜 E).germ V x hx (analyticRestrict h s) =
      (analyticPresheaf 𝕜 E).germ U x (h hx) s :=
  (analyticPresheaf 𝕜 E).germ_res_apply (homOfLE h) x hx s

omit [CompleteSpace 𝕜] in
lemma germ_comp_analyticRestrict {E : Type u} [NormedAddCommGroup E] [NormedSpace 𝕜 E]
    {U V : Opens E} (h : V ≤ U) {x : E} (hx : x ∈ V) :
    ((analyticPresheaf 𝕜 E).germ V x hx).hom.comp (analyticRestrict (𝕜 := 𝕜) h).toRingHom =
      ((analyticPresheaf 𝕜 E).germ U x (h hx)).hom :=
  RingHom.ext fun s ↦ germ_analyticRestrict h hx s

variable {τ : Type u} [Fintype τ]

/-- **The polynomial step of Oka's induction.** Let `Q₁, …, Q_p` be polynomials in the last
variable whose coefficients are analytic on an open set `U ⊆ 𝕜^τ`, one of them monic and all of
degree at most `μ`. If the relations of their coefficient matrix (`boundedRelationMatrix`, for
relations of degree at most `2μ`) are of finite type near the base point of `x₀`, then the
relations of the `Qᵢ`, as analytic functions on the cylinder `U × 𝕜`, are of finite type near
`x₀`. (Demailly, *Complex analytic and differential geometry*, II.3.19–3.20.) -/
theorem polynomialRow_hasFiniteRelationsNear {ι : Type} [Fintype ι]
    (U : Opens (τ → 𝕜)) (Q : ι → (analyticSections 𝕜 U)[X]) (j : ι) (hQ : (Q j).Monic) (μ : ℕ)
    (hdeg : ∀ i, (Q i).natDegree ≤ μ) (x₀ : Option τ → 𝕜) (hx₀ : baseCoordinates x₀ ∈ U)
    (hbase : HasFiniteRelationsNear
      (fun m (il : ι × Fin (2 * μ + 1)) z ↦
        extendByZero (boundedRelationMatrix Q (2 * μ) μ m il).1 z)
      (baseCoordinates x₀)) :
    HasFiniteRelationsNear
      (fun (_ : Unit) i z ↦ extendByZero (analyticPolynomialSection U (Q i)).1 z) x₀ := by
  classical
  obtain ⟨V', hV', hxV', hA', n, g, hg, hgen⟩ := hbase
  let V'' : Opens (τ → 𝕜) := ⟨V' ∩ U, hV'.inter U.isOpen⟩
  have hV''U : V'' ≤ U := fun _ hy ↦ hy.2
  let ρ : analyticSections 𝕜 U →+* analyticSections 𝕜 V'' := (analyticRestrict hV''U).toRingHom
  let B : Fin n → ι → Fin (2 * μ + 1) → analyticSections 𝕜 V'' := fun k i l ↦
    ofAnalyticOnNhd (g k (i, l)) fun y hy ↦ hg k (i, l) y hy.1
  let Qr : ι → (analyticSections 𝕜 V'')[X] := fun i ↦ (Q i).map ρ
  have hB : ∀ y : V'',
      (Polynomial.boundedRelationEquations
        (fun i ↦ (Qr i).map ((analyticPresheaf 𝕜 (τ → 𝕜)).germ V'' y y.2).hom) (2 * μ) μ).ker =
      Submodule.span ((analyticPresheaf 𝕜 (τ → 𝕜)).stalk (y : τ → 𝕜))
        (Set.range (fun k i l ↦ (analyticPresheaf 𝕜 (τ → 𝕜)).germ V'' y y.2 (B k i l))) := by
    intro y
    apply ker_boundedRelationEquations_eq_span
    have hQr : (fun i ↦ (Qr i).map ((analyticPresheaf 𝕜 (τ → 𝕜)).germ V'' y y.2).hom) =
        fun i ↦ (Q i).map ((analyticPresheaf 𝕜 (τ → 𝕜)).germ U y (hV''U y.2)).hom := by
      funext i
      change ((Q i).map ρ).map _ = _
      rw [Polynomial.map_map]
      exact congrArg (fun φ ↦ (Q i).map φ) (germ_comp_analyticRestrict hV''U y.2)
    have e1 : boundedRelationMatrix
        (fun i ↦ (Q i).map ((analyticPresheaf 𝕜 (τ → 𝕜)).germ U y (hV''U y.2)).hom) (2 * μ) μ =
        fun m il ↦ germOf (extendByZero (boundedRelationMatrix Q (2 * μ) μ m il).1)
          (hA' m il y y.2.1) := by
      funext m il
      rw [← map_boundedRelationMatrix]
      exact germ_eq_germOf U _ _
    rw [hQr, e1, hgen y y.2.1]
    congr 2
    funext k il
    exact (germ_ofAnalyticOnNhd _ _ y).symm
  have hcyl := polynomialRelationGenerators_span_germs V'' Qr j (hQ.map ρ) μ
    (fun i ↦ Polynomial.natDegree_map_le.trans (hdeg i)) B hB
  -- the polynomial sections over `U` and over `V''` have the same germs
  have hgermQ (y : Option τ → 𝕜) (hy : y ∈ coordinateCylinder V'') (i : ι) :
      (analyticPresheaf 𝕜 (Option τ → 𝕜)).germ (coordinateCylinder V'') y hy
          (analyticPolynomialSection V'' (Qr i)) =
        germOf (extendByZero (analyticPolynomialSection U (Q i)).1)
          ((analyticPolynomialSection U (Q i)).2 ⟨y, hV''U hy⟩) := by
    rw [← germ_eq_germOf (coordinateCylinder U) (hV''U hy),
      analyticPolynomialSection_germ V'' ⟨y, hy⟩, analyticPolynomialSection_germ U ⟨y, hV''U hy⟩]
    congr 1
    change ((Q i).map ρ).map _ = _
    rw [Polynomial.map_map]
    exact congrArg (fun φ ↦ (Q i).map φ) (germ_comp_analyticRestrict hV''U _)
  refine HasFiniteRelationsNear.of_fintype (coordinateCylinder V'').isOpen
    (show baseCoordinates x₀ ∈ V'' from ⟨hxV', hx₀⟩)
    (fun _ i y hy ↦ (analyticPolynomialSection U (Q i)).2 ⟨y, hV''U hy⟩)
    (fun k i z ↦ extendByZero (polynomialRelationGenerators V'' Qr j μ B k i).1 z)
    (fun k i y hy ↦ (polynomialRelationGenerators V'' Qr j μ B k i).2 ⟨y, hy⟩) fun y hy ↦ ?_
  rw [HasFiniteRelationsNear.matrixRelationModule_unit]
  have h := hcyl ⟨y, hy⟩
  have e2 : (fun i ↦ (analyticPresheaf 𝕜 (Option τ → 𝕜)).germ (coordinateCylinder V'') y hy
      (analyticPolynomialSection V'' (Qr i))) = fun i ↦
        germOf (extendByZero (analyticPolynomialSection U (Q i)).1)
          ((analyticPolynomialSection U (Q i)).2 ⟨y, hV''U hy⟩) := funext (hgermQ y hy)
  rw [e2] at h
  rw [h]
  congr 2
  funext k i
  exact germ_eq_germOf _ _ _

end Cylinder

/-! ### The row case in dimension `n + 1` -/

section Row

-- see the comment in section `Cylinder`
set_option backward.isDefEq.respectTransparency false

variable {𝕜 : Type u} [NontriviallyNormedField 𝕜] [CompleteSpace 𝕜] {τ : Type u} [Fintype τ]

/-- The inverse of the recentring of stalk polynomials preserves monic polynomials. -/
lemma monic_polynomialStalkSeriesEquiv_symm (x : Option τ → 𝕜) (P : (convergent τ 𝕜)[X])
    (hP : P.Monic) : ((polynomialStalkSeriesEquiv x).symm P).Monic := by
  set Q := (polynomialStalkSeriesEquiv x).symm P
  have hQ : polynomialStalkSeriesEquiv x Q = P := RingEquiv.apply_symm_apply _ _
  have hlc : (polynomialStalkSeriesEquiv x Q).leadingCoeff =
      (convergentStalkEquiv (baseCoordinates x)).symm Q.leadingCoeff := by
    change (Polynomial.taylor _
      (Q.map (convergentStalkEquiv (baseCoordinates x)).symm.toRingHom)).leadingCoeff = _
    rw [Polynomial.leadingCoeff_taylor,
      Polynomial.leadingCoeff_map_of_injective (RingEquiv.injective _)]
    rfl
  rw [hQ, hP.leadingCoeff] at hlc
  rw [Polynomial.Monic, ← (convergentStalkEquiv (baseCoordinates x)).symm.injective.eq_iff,
    ← hlc, map_one]

/-- **Oka's induction step**: if the relations of every matrix of functions analytic on
`𝕜^τ` are of finite type, then so are the relations of every row of functions analytic on
`𝕜^{Option τ}`. -/
theorem row_hasFiniteRelationsNear_option
    (IH : ∀ (κ ι : Type) [Fintype κ] [Fintype ι] (A : κ → ι → (τ → 𝕜) → 𝕜) (y : τ → 𝕜),
      (∀ k i, AnalyticAt 𝕜 (A k i) y) → HasFiniteRelationsNear A y)
    {ι : Type} [Fintype ι] (f : ι → (Option τ → 𝕜) → 𝕜) (x₀ : Option τ → 𝕜)
    (hf : ∀ i, AnalyticAt 𝕜 (f i) x₀) :
    HasFiniteRelationsNear (fun (_ : Unit) ↦ f) x₀ := by
  classical
  by_cases hz : ∀ i, germOf (f i) (hf i) = 0
  · exact HasFiniteRelationsNear.of_eventually_eq_zero fun _ i ↦
      (germOf_eq_zero_iff (hf i)).mp (hz i)
  push Not at hz
  obtain ⟨j, hj⟩ := hz
  set e := convergentStalkEquiv x₀ with he
  let F : ι → convergent (Option τ) 𝕜 := fun i ↦ e.symm (germOf (f i) (hf i))
  obtain ⟨v, hv, u, P, hmul, -, hmonic⟩ := exists_simultaneous_weierstrass_preparation F
  have hFj : F j ≠ 0 := by
    intro h
    apply hj
    have := congrArg e h
    simpa [F] using this
  -- the shear `Φ` around `x₀` and its inverse `Ψ`
  let Φ : (Option τ → 𝕜) → (Option τ → 𝕜) := fun z ↦ x₀ + shear v (z - x₀)
  let Ψ : (Option τ → 𝕜) → (Option τ → 𝕜) := fun w ↦ x₀ + shearInv v (w - x₀)
  have hΦ (z : Option τ → 𝕜) : AnalyticAt 𝕜 Φ z :=
    analyticAt_const.add ((analyticAt_shear_apply v _).comp (analyticAt_id.sub analyticAt_const))
  have hΨ (w : Option τ → 𝕜) : AnalyticAt 𝕜 Ψ w :=
    analyticAt_const.add
      ((analyticAt_shearInv_apply v _).comp (analyticAt_id.sub analyticAt_const))
  have hΦΨ (w : Option τ → 𝕜) : Φ (Ψ w) = w := by
    simp only [Φ, Ψ, add_sub_cancel_left, shear_shearInv hv, add_sub_cancel]
  have hΨΦ (z : Option τ → 𝕜) : Ψ (Φ z) = z := by
    simp only [Φ, Ψ, add_sub_cancel_left, shearInv_shear hv, add_sub_cancel]
  have hΦ0 : Φ x₀ = x₀ := by simp only [Φ, sub_self, shear_zero, add_zero]
  have hΨ0 : Ψ x₀ = x₀ := by simp only [Ψ, sub_self, shearInv_zero, add_zero]
  let f' : ι → (Option τ → 𝕜) → 𝕜 := fun i z ↦ f i (Φ z)
  have hf' (i : ι) : AnalyticAt 𝕜 (f' i) x₀ :=
    AnalyticAt.comp (g := f i) (by rw [hΦ0]; exact hf i) (hΦ x₀)
  suffices H : HasFiniteRelationsNear (fun (_ : Unit) ↦ f') x₀ by
    have H' : HasFiniteRelationsNear (fun (_ : Unit) ↦ f') (Ψ x₀) := by rwa [hΨ0]
    have := H'.comp_analyticEquiv hΨ hΦ hΦΨ hΨΦ
    simpa only [f', hΦΨ] using this
  -- germs of the sheared functions
  have hgerm (i : ι) : e (shearEquiv hv (F i)) = germOf (f' i) (hf' i) :=
    convergentStalkEquiv_shearEquiv x₀ hv (hf i) (hf' i)
  -- the Weierstrass polynomials, as polynomials over the stalk of the base
  let Qst : ι → ((analyticPresheaf 𝕜 (τ → 𝕜)).stalk (baseCoordinates x₀))[X] :=
    fun i ↦ (polynomialStalkSeriesEquiv x₀).symm (P i)
  have hQst (i : ι) : polynomialStalkEval x₀ (Qst i) = e (polyY (P i)) := by
    rw [polynomialStalkEval_eq_series, RingEquiv.apply_symm_apply]
  -- spreading out: polynomials with analytic coefficients, and units
  obtain ⟨U₁, hx₁, Qs, hQs⟩ := exists_common_polynomial_sections (baseCoordinates x₀) Qst
  obtain ⟨U₂, hx₂, us, hus⟩ := exists_common_analytic_units x₀
    (fun i ↦ Units.map e.toRingHom.toMonoidHom (u i))
  let μ : ℕ := Finset.univ.sup fun i ↦ (Qs i).natDegree
  have hdeg (i : ι) : (Qs i).natDegree ≤ μ := Finset.le_sup (f := fun i ↦ (Qs i).natDegree)
    (Finset.mem_univ i)
  have hmon : (Qs j).Monic :=
    (hQs j).2.2.2 (monic_polynomialStalkSeriesEquiv_symm x₀ (P j) (hmonic j hFj))
  -- the induction hypothesis, for the coefficient matrix
  have hbase := IH (Fin (2 * μ + μ + 1)) (ι × Fin (2 * μ + 1))
    (fun m il z ↦ extendByZero (boundedRelationMatrix Qs (2 * μ) μ m il).1 z)
    (baseCoordinates x₀) fun m il ↦ (boundedRelationMatrix Qs (2 * μ) μ m il).2 ⟨_, hx₁⟩
  have hpoly := polynomialRow_hasFiniteRelationsNear U₁ Qs j hmon μ hdeg x₀ hx₁ hbase
  -- the sheared functions are the polynomials up to units
  let w : ι → (Option τ → 𝕜) → 𝕜 := fun i ↦ extendByZero (us i : analyticSections 𝕜 U₂).1
  have hw (i : ι) : AnalyticAt 𝕜 (w i) x₀ := (us i : analyticSections 𝕜 U₂).2 ⟨x₀, hx₂⟩
  have hw₀ (i : ι) : w i x₀ ≠ 0 := by
    have hu : IsUnit ((analyticPresheaf 𝕜 (Option τ → 𝕜)).germ U₂ x₀ hx₂
        (us i : analyticSections 𝕜 U₂)) := by
      rw [hus i]
      exact Units.isUnit _
    rw [isUnit_stalk_iff, evalStalk_germ] at hu
    simpa only [w, extendByZero_of_mem _ hx₂] using hu
  have heq (i : ι) : extendByZero (analyticPolynomialSection U₁ (Qs i)).1 =ᶠ[𝓝 x₀]
      fun z ↦ f' i z * w i z := by
    have hA : AnalyticAt 𝕜 (extendByZero (analyticPolynomialSection U₁ (Qs i)).1) x₀ :=
      (analyticPolynomialSection U₁ (Qs i)).2 ⟨x₀, hx₁⟩
    have hB : AnalyticAt 𝕜 (f' i * w i) x₀ := (hf' i).mul (hw i)
    refine (germOf_eq_germOf_iff hA hB).mp ?_
    rw [← germ_eq_germOf (coordinateCylinder U₁) hx₁, analyticPolynomialSection_germ U₁ ⟨x₀, hx₁⟩,
      (hQs i).1, hQst i, ← hmul i, map_mul, germOf_mul (hf' i) (hw i)]
    refine congrArg₂ (· * ·) ?_ ?_
    · -- `exists_simultaneous_weierstrass_preparation` uses `Fintype.ofFinite τ`
      convert hgerm i using 4
    · rw [← germ_eq_germOf U₂ hx₂, hus i]
      rfl
  have hfw : HasFiniteRelationsNear (fun (_ : Unit) i z ↦ f' i z * w i z) x₀ :=
    hpoly.of_eventuallyEq fun _ i ↦ heq i
  exact hfw.of_mul hw hw₀ fun _ i ↦ hf' i

end Row

/-! ### The induction -/

section Induction

variable {𝕜 : Type u} [NontriviallyNormedField 𝕜] [CompleteSpace 𝕜]

omit [CompleteSpace 𝕜] in
/-- Renaming the coordinates along `e : σ' ≃ σ` is analytic. -/
lemma analyticAt_comp_equiv {σ σ' : Type u} [Fintype σ] [Fintype σ'] (e : σ' ≃ σ)
    (z : σ → 𝕜) : AnalyticAt 𝕜 (fun w : σ → 𝕜 ↦ fun o ↦ w (e o)) z :=
  AnalyticAt.pi fun o ↦ analyticAt_apply (e o) z

/-- **Oka's coherence theorem** (Grauert–Remmert, *Coherent analytic sheaves*, 2.5; Demailly,
*Complex analytic and differential geometry*, II.3.19): for every finite matrix `A` of functions
on `𝕜^σ` analytic at `x₀`, the sheaf of relations between the columns of `A` is of finite type
near `x₀`: finitely many analytic relations, defined on one open neighbourhood `V` of `x₀`,
generate the module of relations between the germs at every point of `V`. -/
theorem hasFiniteRelationsNear {σ : Type u} [Fintype σ] {κ ι : Type} [Finite κ] [Fintype ι]
    (A : κ → ι → (σ → 𝕜) → 𝕜) (x₀ : σ → 𝕜) (hA : ∀ k i, AnalyticAt 𝕜 (A k i) x₀) :
    HasFiniteRelationsNear A x₀ := by
  classical
  have := Fintype.ofFinite κ
  suffices H : ∀ (n : ℕ) (σ : Type u) [Fintype σ], Fintype.card σ = n →
      ∀ (κ ι : Type) [Fintype κ] [Fintype ι] (A : κ → ι → (σ → 𝕜) → 𝕜) (x₀ : σ → 𝕜),
        (∀ k i, AnalyticAt 𝕜 (A k i) x₀) → HasFiniteRelationsNear A x₀ from
    H _ σ rfl κ ι A x₀ hA
  intro n
  induction n with
  | zero =>
    intro σ _ hσ κ ι _ _ A x₀ hA
    have : IsEmpty σ := Fintype.card_eq_zero_iff.mp hσ
    exact HasFiniteRelationsNear.of_isEmpty hA
  | succ n ih =>
    intro σ _ hσ κ ι _ _ A x₀ hA
    obtain ⟨i₀⟩ : Nonempty σ := Fintype.card_pos_iff.mp (by omega)
    let τ : Type u := {i // i ≠ i₀}
    let e : Option τ ≃ σ := Equiv.optionSubtypeNe i₀
    have hτ : Fintype.card τ = n := by
      have := Fintype.card_congr e
      rw [Fintype.card_option, hσ] at this
      omega
    -- the row case and then the matrix case on `𝕜^{Option τ}`
    have hrow (x : Option τ → 𝕜) (ι' : Type) [Fintype ι'] (f : ι' → (Option τ → 𝕜) → 𝕜)
        (hf : ∀ i, AnalyticAt 𝕜 (f i) x) : HasFiniteRelationsNear (fun (_ : Unit) ↦ f) x :=
      row_hasFiniteRelationsNear_option (fun κ ι _ _ A y hA ↦ ih τ hτ κ ι A y hA) f x hf
    -- transport along the renaming of the coordinates
    let L : (σ → 𝕜) → (Option τ → 𝕜) := fun z o ↦ z (e o)
    let L' : (Option τ → 𝕜) → (σ → 𝕜) := fun w i ↦ w (e.symm i)
    have hLL' (w : Option τ → 𝕜) : L (L' w) = w := funext fun o ↦ by simp [L, L']
    have hL'L (z : σ → 𝕜) : L' (L z) = z := funext fun i ↦ by simp [L, L']
    let B : κ → ι → (Option τ → 𝕜) → 𝕜 := fun k i w ↦ A k i (L' w)
    have hB : ∀ k i, AnalyticAt 𝕜 (B k i) (L x₀) := fun k i ↦
      AnalyticAt.comp (g := A k i) (by rw [hL'L]; exact hA k i)
        (analyticAt_comp_equiv e.symm (L x₀))
    have hBrel := HasFiniteRelationsNear.of_rows (hrow (L x₀)) κ B hB
    have := hBrel.comp_analyticEquiv (analyticAt_comp_equiv e) (analyticAt_comp_equiv e.symm)
      hL'L hLL'
    exact (congrArg (fun A' ↦ HasFiniteRelationsNear A' x₀) (funext fun k ↦ funext fun i ↦
      funext fun z ↦ congrArg (A k i) (hL'L z))).mp this

end Induction

end AnalyticGeometry
