/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.Foundations.Analytic.Sheaf
import Mathlib.LinearAlgebra.Finsupp.LinearCombination

/-!
# Analytic relations on the nonvanishing locus

For a finite family of analytic functions, a coefficient which does not vanish at a
point is invertible on one neighborhood of that point. On that neighborhood the relation
module has explicit finite generators, and the same generators work on every smaller open
subset. This is a uniform statement about analytic sections, rather than just finite
generation of a single stalk.

This is the elementary nonvanishing case in the relation-sheaf formulation of Oka's
coherence theorem (Grauert--Remmert, *Coherent Analytic Sheaves*, Chapter II). The case where
all coefficients vanish at the point requires the Weierstrass induction and is not claimed
here.
-/

noncomputable section

universe u

open TopologicalSpace Filter
open scoped Topology

namespace AnalyticGeometry

section Algebra

variable {R : Type*} [CommRing R] {ι : Type*} [Fintype ι] [DecidableEq ι]

/-- The module of relations among a finite family of coefficients. -/
def relationModule (f : ι → R) : Submodule R (ι → R) :=
  (Fintype.linearCombination R f).ker

omit [DecidableEq ι] in
@[simp]
lemma mem_relationModule (f a : ι → R) :
    a ∈ relationModule f ↔ ∑ i, a i * f i = 0 := Iff.rfl

/-- Elementary relations when `u` is the inverse of the coefficient with index `j`. -/
def relationGenerator (f : ι → R) (j : ι) (u : R) (i : ι) : ι → R :=
  Pi.single i 1 - (u * f i) • Pi.single j 1

lemma relationGenerator_mem (f : ι → R) (j : ι) (u : R) (hu : u * f j = 1) (i : ι) :
    relationGenerator f j u i ∈ relationModule f := by
  change Fintype.linearCombination R f (relationGenerator f j u i) = 0
  simp only [relationGenerator, map_sub, map_smul,
    Fintype.linearCombination_apply_single, smul_eq_mul, one_mul]
  calc
    f i - u * f i * f j = f i - f i * (u * f j) := by ring
    _ = 0 := by rw [hu, mul_one, sub_self]

/-- Every relation is the indicated linear combination of the elementary relations. -/
lemma sum_smul_relationGenerator (f : ι → R) (j : ι) (u : R) (a : ι → R)
    (ha : a ∈ relationModule f) :
    ∑ i, a i • relationGenerator f j u i = a := by
  have hsum : ∑ i, a i * (u * f i) = 0 := by
    calc
      ∑ i, a i * (u * f i) = u * ∑ i, a i * f i := by
        rw [Finset.mul_sum]
        exact Finset.sum_congr rfl fun i _ ↦ by ring
      _ = 0 := by rw [(mem_relationModule f a).mp ha, mul_zero]
  simp only [relationGenerator, smul_sub, smul_smul, Finset.sum_sub_distrib]
  rw [← Finset.sum_smul, hsum, zero_smul, sub_zero]
  ext i
  simp [Pi.single_apply, mul_ite]

/-- A unit coefficient makes the relation module finitely generated by explicit relations. -/
theorem relationModule_eq_span (f : ι → R) (j : ι) (u : R) (hu : u * f j = 1) :
    relationModule f = Submodule.span R (Set.range (relationGenerator f j u)) := by
  apply le_antisymm
  · intro a ha
    rw [Submodule.mem_span_range_iff_exists_fun]
    exact ⟨a, sum_smul_relationGenerator f j u a ha⟩
  · exact Submodule.span_le.mpr (Set.range_subset_iff.mpr (relationGenerator_mem f j u hu))

omit [Fintype ι] in
/-- The elementary generators commute with a change of coefficient ring. -/
lemma map_relationGenerator {S : Type*} [CommRing S] (φ : R →+* S)
    (f : ι → R) (j : ι) (u : R) (i l : ι) :
    φ (relationGenerator f j u i l) = relationGenerator (fun t ↦ φ (f t)) j (φ u) i l := by
  by_cases hi : i = l <;> by_cases hj : j = l <;>
    simp [relationGenerator, hi, hj]

/-- The elementary relation `fⱼeᵢ - fᵢeⱼ`, without any invertibility hypothesis. -/
def elementaryRelation (f : ι → R) (j i : ι) : ι → R :=
  f j • Pi.single i 1 - f i • Pi.single j 1

lemma elementaryRelation_mem (f : ι → R) (j i : ι) :
    elementaryRelation f j i ∈ relationModule f := by
  change Fintype.linearCombination R f (elementaryRelation f j i) = 0
  simp [elementaryRelation, mul_comm]

/-- Subtracting a combination of elementary relations preserves a relation. -/
lemma sub_sum_elementaryRelation_mem (f : ι → R) (j : ι) (a q : ι → R)
    (ha : a ∈ relationModule f) :
    a - ∑ i, q i • elementaryRelation f j i ∈ relationModule f :=
  (relationModule f).sub_mem ha ((relationModule f).sum_mem fun i _ ↦
    (relationModule f).smul_mem _ (elementaryRelation_mem f j i))

/-- Away from the distinguished coordinate, relation reduction subtracts exactly
the indicated multiple of the distinguished coefficient. -/
lemma sub_sum_elementaryRelation_apply (f : ι → R) (j : ι) (a q : ι → R)
    (l : ι) (hl : l ≠ j) :
    (a - ∑ i, q i • elementaryRelation f j i) l = a l - q l * f j := by
  simp [elementaryRelation, Pi.single_apply, hl.symm, mul_ite]

omit [DecidableEq ι] in
/-- Applying a coefficient homomorphism sends relations to relations. -/
lemma map_mem_relationModule {S : Type*} [CommRing S] (φ : R →+* S)
    (f a : ι → R) (ha : a ∈ relationModule f) :
    (fun i ↦ φ (a i)) ∈ relationModule (fun i ↦ φ (f i)) := by
  rw [mem_relationModule]
  simp only [← map_mul, ← map_sum, (mem_relationModule f a).mp ha, map_zero]

omit [Fintype ι] in
/-- Elementary relations commute with coefficient homomorphisms. -/
lemma map_elementaryRelation {S : Type*} [CommRing S] (φ : R →+* S)
    (f : ι → R) (j i l : ι) :
    φ (elementaryRelation f j i l) = elementaryRelation (fun t ↦ φ (f t)) j i l := by
  by_cases hi : i = l <;> by_cases hj : j = l <;>
    simp [elementaryRelation, hi, hj]

end Algebra

section Analytic

variable {𝕜 E : Type u} [NontriviallyNormedField 𝕜] [NormedAddCommGroup E]
  [NormedSpace 𝕜 E] {U : Opens E}

@[simp]
lemma analyticRestrict_comp_apply {V W : Opens E} (hVU : V ≤ U) (hWV : W ≤ V)
    (f : analyticSections 𝕜 U) :
    analyticRestrict hWV (analyticRestrict hVU f) = analyticRestrict (hWV.trans hVU) f := by
  apply Subtype.ext
  rfl

/-- A nowhere vanishing analytic section has an analytic reciprocal. -/
def analyticSectionInv (f : analyticSections 𝕜 U) (hf : ∀ y : U, f.1 y ≠ 0) :
    analyticSections 𝕜 U :=
  ⟨fun y ↦ (f.1 y)⁻¹, fun y ↦ ((f.2 y).inv (by
    rw [extendByZero_coe]
    exact hf y)).congr (by
      filter_upwards [U.isOpen.mem_nhds y.2] with z hz
      simp only [Pi.inv_apply, extendByZero_of_mem _ hz])⟩

@[simp]
lemma analyticSectionInv_apply (f : analyticSections 𝕜 U)
    (hf : ∀ y : U, f.1 y ≠ 0) (y : U) :
    (analyticSectionInv f hf).1 y = (f.1 y)⁻¹ := rfl

lemma analyticSectionInv_mul (f : analyticSections 𝕜 U) (hf : ∀ y : U, f.1 y ≠ 0) :
    analyticSectionInv f hf * f = 1 := by
  apply Subtype.ext
  funext y
  exact inv_mul_cancel₀ (hf y)

/-- A coefficient nonzero at a point has an analytic inverse on one neighborhood. -/
theorem exists_analytic_inverse_neighborhood (f : analyticSections 𝕜 U)
    (x : U) (hx : f.1 x ≠ 0) :
    ∃ (V : Opens E) (hVU : V ≤ U), (x : E) ∈ V ∧
      ∃ u : analyticSections 𝕜 V, u * analyticRestrict hVU f = 1 := by
  have hn : ∀ᶠ y in 𝓝 (x : E), y ∈ U ∧ extendByZero f.1 y ≠ 0 := by
    have h0 : extendByZero f.1 x ≠ 0 := by simpa using hx
    filter_upwards [U.isOpen.mem_nhds x.2, (f.2 x).continuousAt.eventually_ne h0] with y hy hne
    exact ⟨hy, hne⟩
  obtain ⟨V, hV, hVo, hxV⟩ := mem_nhds_iff.mp hn
  let W : Opens E := ⟨V, hVo⟩
  have hWU : W ≤ U := fun y hy ↦ (hV hy).1
  have hne : ∀ y : W, (analyticRestrict hWU f).1 y ≠ 0 := by
    intro y
    have h := (hV y.2).2
    rwa [extendByZero_of_mem _ (hWU y.2)] at h
  exact ⟨W, hWU, hxV, analyticSectionInv _ hne, analyticSectionInv_mul _ hne⟩

variable {ι : Type*} [Fintype ι] [DecidableEq ι]

omit [DecidableEq ι] in
/-- On the nonvanishing locus, a finite family of analytic functions admits relation
generators on one neighborhood which generate on every smaller open subset. -/
theorem exists_uniform_relation_generators_of_ne_zero
    (f : ι → analyticSections 𝕜 U) (x : U) (j : ι) (hx : (f j).1 x ≠ 0) :
    ∃ (V : Opens E) (hVU : V ≤ U), (x : E) ∈ V ∧
      ∃ q : ι → ι → analyticSections 𝕜 V,
        (∀ i, q i ∈ relationModule (fun l ↦ analyticRestrict hVU (f l))) ∧
        ∀ (W : Opens E) (hWV : W ≤ V),
          relationModule (fun l ↦ analyticRestrict (hWV.trans hVU) (f l)) =
            Submodule.span (analyticSections 𝕜 W)
              (Set.range (fun i l ↦ analyticRestrict hWV (q i l))) := by
  classical
  obtain ⟨V, hVU, hxV, u, hu⟩ := exists_analytic_inverse_neighborhood (f j) x hx
  let fV : ι → analyticSections 𝕜 V := fun l ↦ analyticRestrict hVU (f l)
  refine ⟨V, hVU, hxV, relationGenerator fV j u,
    relationGenerator_mem fV j u hu, ?_⟩
  intro W hWV
  have huW : analyticRestrict hWV u * analyticRestrict (hWV.trans hVU) (f j) = 1 := by
    have h := congrArg (analyticRestrict hWV) hu
    simpa only [map_mul, map_one, analyticRestrict_comp_apply] using h
  have hq : (fun i l ↦ analyticRestrict hWV (relationGenerator fV j u i l)) =
      relationGenerator (fun l ↦ analyticRestrict (hWV.trans hVU) (f l)) j
        (analyticRestrict hWV u) := by
    funext i l
    have h : analyticRestrict hWV (relationGenerator fV j u i l) =
        relationGenerator (fun t ↦ analyticRestrict hWV (fV t)) j
          (analyticRestrict hWV u) i l :=
      map_relationGenerator (analyticRestrict hWV).toRingHom fV j u i l
    simpa only [fV, analyticRestrict_comp_apply] using h
  rw [hq]
  exact relationModule_eq_span _ j _ huW

end Analytic

end AnalyticGeometry
