/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.Foundations.Analytic.Oka
import SGA.Foundations.Analytic.LocalModel

/-!
# Coherence of the structure sheaf of a local model

Let `D` be a local model `(Z, (𝒪_U/(f₁, …, f_k))|_Z)` with `U ⊆ 𝕜^σ` open
(`AnalyticGeometry.LocalModelData`). Its structure sheaf is coherent: the relations between
finitely many sections are, near every point of `Z`, generated by finitely many sections
([Grauert–Remmert, *Coherent analytic sheaves*, 2.5]; [SGA 1, XII.1]). Since every
section of `𝒪_D` is locally the class of a function analytic on `U`, this is the following
germ statement, proved here from Oka's theorem
(`AnalyticGeometry.LocalModelData.exists_relations_fiber`): for functions `g₁, …, g_p` analytic at
a point `x₀ ∈ Z` there are an open `V ∋ x₀` and finitely many vectors `s_j` of functions
analytic on `V` such that, at every `y ∈ Z ∩ V`, the classes of the `s_j` in the stalk
`𝒪_{D,y} = 𝒪_{E,y}/(f)` generate the module of relations between the classes of the `gᵢ`.
-/

noncomputable section

universe u

open TopologicalSpace Filter Set
open scoped Topology

namespace AnalyticGeometry

namespace LocalModelData

variable {𝕜 : Type u} [NontriviallyNormedField 𝕜] [CompleteSpace 𝕜] {σ : Type u} [Fintype σ]
  (D : LocalModelData 𝕜 (σ → 𝕜))

/-- **The structure sheaf of a local model is coherent** (germ form): the relations between the
classes in `𝒪_{D,y}` of finitely many functions analytic at `x₀ ∈ Z` are generated, at every
point `y` of `Z` near `x₀`, by the classes of finitely many vectors of functions analytic near
`x₀`. -/
theorem exists_relations_fiber {p : ℕ} {g : Fin p → (σ → 𝕜) → 𝕜} (x₀ : D.zeroSet)
    (hg : ∀ i, AnalyticAt 𝕜 (g i) x₀) :
    ∃ V : Set (σ → 𝕜), IsOpen V ∧ (x₀ : σ → 𝕜) ∈ V ∧
      ∃ (hgV : ∀ i, ∀ y ∈ V, AnalyticAt 𝕜 (g i) y) (m : ℕ) (s : Fin m → Fin p → (σ → 𝕜) → 𝕜)
        (hs : ∀ j i, ∀ y ∈ V, AnalyticAt 𝕜 (s j i) y),
        ∀ (y : D.zeroSet) (hy : (y : σ → 𝕜) ∈ V),
          relationModule (fun i ↦ D.classOf y (g i) (hgV i y hy)) =
            Submodule.span (D.Fiber y) (Set.range fun j i ↦ D.classOf y (s j i) (hs j i y hy)) := by
  obtain ⟨V, hV, hxV, hgV, hfV, m, s, hs, hrel, hgen⟩ :=
    exists_relations_mod_ideal_of_analyticAt (f := g) (g := D.f) hg
      fun l ↦ D.analyticAt_f l x₀ (D.mem_U x₀)
  refine ⟨V, hV, hxV, hgV, m, s, hs, fun y hy ↦ ?_⟩
  have hI : D.ideal y (D.mem_U y) = Ideal.span (Set.range fun l ↦ germOf (D.f l) (hfV l y hy)) :=
    rfl
  apply le_antisymm
  · intro a ha
    choose a' ha' using fun i ↦ Ideal.Quotient.mk_surjective (a i)
    have hmem : ∑ i, a' i * germOf (g i) (hgV i y hy) ∈ D.ideal y (D.mem_U y) := by
      rw [← Ideal.Quotient.eq_zero_iff_mem, map_sum]
      simpa only [map_mul, ha', classOf] using (mem_relationModule _ a).mp ha
    rw [hI] at hmem
    obtain ⟨c, hc⟩ := (Submodule.mem_span_range_iff_exists_fun _).mp (hgen y hy a' hmem)
    rw [Submodule.mem_span_range_iff_exists_fun]
    refine ⟨fun j ↦ Ideal.Quotient.mk _ (c j), funext fun i ↦ ?_⟩
    have := congrArg (Ideal.Quotient.mk (D.ideal y (D.mem_U y))) (congrFun hc i)
    simp only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul, map_sum, map_mul, ha'] at this
    simpa only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul, classOf] using this
  · rw [Submodule.span_le]
    rintro _ ⟨j, rfl⟩
    rw [SetLike.mem_coe, mem_relationModule]
    have h := hrel j y hy
    rw [← hI, ← Ideal.Quotient.eq_zero_iff_mem, map_sum] at h
    simpa only [map_mul, classOf] using h

end LocalModelData

end AnalyticGeometry
