/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.Foundations.Analytic.Completion
import SGA.Foundations.Analytic.Stalk
import SGA.Foundations.Analytic.OkaRelationSheaf
import SGA.Foundations.CommAlg.RegularLocalRing

/-!
# The ring of convergent power series is regular; syzygies

The ring `𝕜{X_σ}` of convergent power series in finitely many variables is a regular local ring
of dimension `#σ` (`MvPowerSeries.isRegularLocalRing_convergent`,
`MvPowerSeries.ringKrullDim_convergent`): its maximal ideal is generated by the variables, and the
kernels of the substitutions `Xᵢ ↦ 0` (`i ∈ S`) give a chain of primes of length `#σ`
([Grauert–Remmert, *Analytische Stellenalgebren*]). Hence so is every stalk of the sheaf of
analytic functions on `𝕜^σ` (`AnalyticGeometry.isRegularLocalRing_stalk`), and every module over
it has projective dimension at most `#σ` (Serre's theorem,
`AnalyticGeometry.hasProjectiveDimensionLE_stalk`): **Hilbert's syzygy theorem for `𝒪_{𝕜ⁿ,x}`**.

For the construction of finite free resolutions we record the syzygy step in terms of relation
modules: if the vectors `G_m ∈ R^ι` generate a module of projective dimension `≤ d + 1`, their
module of relations `matrixRelationModule Gᵀ` has projective dimension `≤ d`
(`AnalyticGeometry.hasProjectiveDimensionLE_relations`); a finitely generated module of projective
dimension `0` over a local ring has a basis, whose vectors have no relations
(`AnalyticGeometry.exists_basis_of_hasProjectiveDimensionLE_zero`).
-/

noncomputable section

universe u

open CategoryTheory IsLocalRing

namespace MvPowerSeries

variable {σ : Type*} [Fintype σ] {𝕜 : Type*} [NontriviallyNormedField 𝕜] [CompleteSpace 𝕜]

/-- The variable `Xᵢ` as a convergent power series. -/
abbrev convergentX (i : σ) : convergent σ 𝕜 :=
  ⟨X i, X_mem_convergent i⟩

omit [Fintype σ] in
/-- The maximal ideal of `𝕜{X}` is generated by the variables. -/
theorem maximalIdeal_convergent_eq_span [Finite σ] :
    maximalIdeal (convergent σ 𝕜) = Ideal.span (Set.range (convergentX (𝕜 := 𝕜))) := by
  classical
  have := Fintype.ofFinite σ
  apply le_antisymm
  · intro f hf
    let _ : LinearOrder σ := LinearOrder.lift' (Fintype.equivFin σ) (Fintype.equivFin σ).injective
    have hc : constantCoeff f.1 = 0 := mem_maximalIdeal_convergent_iff.mp hf
    have hsum : f = ∑ i, convergentX i * ⟨divX i f.1, divX_mem_convergent i f.2⟩ := by
      apply Subtype.ext
      simp only [AddSubmonoidClass.coe_finsetSum, MulMemClass.coe_mul]
      exact (sum_X_mul_divX hc).symm
    rw [hsum]
    exact Ideal.sum_mem _ fun i _ ↦ Ideal.mul_mem_right _ _ (Ideal.subset_span ⟨i, rfl⟩)
  · rw [Ideal.span_le]
    rintro _ ⟨i, rfl⟩
    exact X_mem_maximalIdeal_convergent i

omit [Fintype σ] [CompleteSpace 𝕜] in
lemma analyticAt_zeroVarsMap (S : Set σ) [DecidablePred (· ∈ S)] [Fintype σ] :
    AnalyticAt 𝕜 (fun (z : σ → 𝕜) i ↦ if i ∈ S then (0 : 𝕜) else z i) 0 := by
  refine AnalyticAt.pi fun i ↦ ?_
  by_cases hi : i ∈ S
  · simpa [hi] using (analyticAt_const (v := (0 : 𝕜)) (x := (0 : σ → 𝕜)))
  · simpa [hi] using analyticAt_apply (𝕜 := 𝕜) i (0 : σ → 𝕜)

open Classical in
/-- The substitution `Xᵢ ↦ 0` for `i ∈ S`. -/
def zeroVars (S : Set σ) : convergent σ 𝕜 →ₐ[𝕜] convergent σ 𝕜 :=
  substAnalyticHom (analyticAt_zeroVarsMap S) (by funext i; simp)

open Classical in
lemma zeroVars_X (S : Set σ) (j : σ) :
    zeroVars (𝕜 := 𝕜) S (convergentX j) = if j ∈ S then 0 else convergentX j := by
  apply Subtype.ext
  rw [zeroVars, substAnalyticHom_apply, substAnalytic_X]
  by_cases hj : j ∈ S
  · simp only [hj, ite_true]
    exact (taylorSeries_const 0).trans (map_zero _)
  · simp only [hj, ite_false]
    exact taylorSeries_coord j

open Classical in
lemma zeroVars_zeroVars {S T : Set σ} (hST : S ⊆ T) (f : convergent σ 𝕜) :
    zeroVars T (zeroVars S f) = zeroVars T f := by
  apply Subtype.ext
  simp only [zeroVars, substAnalyticHom_apply]
  rw [substAnalytic_substAnalytic (analyticAt_zeroVarsMap S) (by funext i; simp)
    (analyticAt_zeroVarsMap T) (by funext i; simp) f.2]
  congr 1
  funext z i
  by_cases hi : i ∈ T
  · by_cases hiS : i ∈ S <;> simp [hi, hiS]
  · simp [hi, show i ∉ S from fun h ↦ hi (hST h)]

omit [Fintype σ] [CompleteSpace 𝕜] in
lemma convergentX_ne_zero (i : σ) : convergentX (𝕜 := 𝕜) i ≠ 0 := by
  intro h
  have := congrArg (fun f : convergent σ 𝕜 ↦ coeff (Finsupp.single i 1) f.1) h
  simp at this

instance isDomain_convergent : IsDomain (convergent σ 𝕜) :=
  haveI : IsDomain (MvPowerSeries σ 𝕜) := NoZeroDivisors.to_isDomain _
  Subalgebra.isDomain _

omit [CompleteSpace 𝕜] in
private lemma ncard_range_convergentX_le :
    (Set.range (convergentX (σ := σ) (𝕜 := 𝕜))).ncard ≤ Fintype.card σ := by
  rw [← Set.image_univ, ← Nat.card_eq_fintype_card, ← Set.ncard_univ]
  exact Set.ncard_image_le Set.finite_univ

/-- `𝕜{X_σ}` has Krull dimension at least `#σ`: the kernels of the substitutions `Xᵢ ↦ 0` for
`i` in an increasing chain of sets of variables form a chain of primes of length `#σ`. -/
theorem card_le_ringKrullDim_convergent :
    (Fintype.card σ : WithBot ℕ∞) ≤ ringKrullDim (convergent σ 𝕜) := by
  classical
  let e := Fintype.equivFin σ
  let S : Fin (Fintype.card σ + 1) → Set σ := fun k ↦ {i | (e i : ℕ) < k}
  let P : Fin (Fintype.card σ + 1) → PrimeSpectrum (convergent σ 𝕜) := fun k ↦
    ⟨RingHom.ker (zeroVars (𝕜 := 𝕜) (S k)).toRingHom, RingHom.ker_isPrime _⟩
  have hmono : StrictMono P := by
    refine Fin.strictMono_iff_lt_succ.mpr fun k ↦ ?_
    have hS : S k.castSucc ⊆ S k.succ := fun i hi ↦ by
      simp only [S, Set.mem_ofPred_eq, Fin.val_castSucc, Fin.val_succ] at hi ⊢
      omega
    refine lt_of_le_of_ne (fun f hf ↦ ?_) fun h ↦ ?_
    · change zeroVars _ f = 0 at hf
      change zeroVars _ f = 0
      rw [← zeroVars_zeroVars hS, hf, map_zero]
    · -- the variable `X_{e⁻¹ k}` separates the two primes
      have hmem : convergentX (e.symm k) ∈ (P k.succ).asIdeal := by
        change zeroVars _ _ = 0
        rw [zeroVars_X, ite_eq_left (by simp [S])]
      rw [← h] at hmem
      change zeroVars _ _ = 0 at hmem
      rw [zeroVars_X, ite_eq_right (by simp [S])] at hmem
      exact convergentX_ne_zero _ hmem
  exact Order.le_krullDim_iff.mpr ⟨LTSeries.mk _ P hmono, rfl⟩

omit [Fintype σ] in
/-- **`𝕜{X_σ}` is a regular local ring** (of dimension `#σ`). -/
instance isRegularLocalRing_convergent [Finite σ] : IsRegularLocalRing (convergent σ 𝕜) := by
  have := Fintype.ofFinite σ
  apply IsRegularLocalRing.of_spanFinrank_maximalIdeal_le
  rw [maximalIdeal_convergent_eq_span]
  refine le_trans ?_ card_le_ringKrullDim_convergent
  have h := Submodule.spanFinrank_span_le_ncard_of_finite (R := convergent σ 𝕜)
    (Set.finite_range (convergentX (σ := σ) (𝕜 := 𝕜)))
  have h' := ncard_range_convergentX_le (σ := σ) (𝕜 := 𝕜)
  exact_mod_cast h.trans h'

/-- `𝕜{X_σ}` has Krull dimension `#σ`. -/
theorem ringKrullDim_convergent :
    ringKrullDim (convergent σ 𝕜) = Fintype.card σ := by
  refine le_antisymm ?_ card_le_ringKrullDim_convergent
  refine (ringKrullDim_le_spanFinrank_maximalIdeal (R := convergent σ 𝕜)).trans ?_
  rw [maximalIdeal_convergent_eq_span]
  have h := Submodule.spanFinrank_span_le_ncard_of_finite (R := convergent σ 𝕜)
    (Set.finite_range (convergentX (σ := σ) (𝕜 := 𝕜)))
  have h' := ncard_range_convergentX_le (σ := σ) (𝕜 := 𝕜)
  exact_mod_cast h.trans h'

end MvPowerSeries

namespace AnalyticGeometry

section Stalk

variable {𝕜 : Type u} [NontriviallyNormedField 𝕜] [CompleteSpace 𝕜] {σ : Type u} [Fintype σ]

/-- The stalks of the sheaf of analytic functions on `𝕜^σ` are regular local rings. -/
instance isRegularLocalRing_stalk (x : σ → 𝕜) :
    IsRegularLocalRing ((analyticPresheaf 𝕜 (σ → 𝕜)).stalk x) :=
  IsRegularLocalRing.of_ringEquiv (convergentStalkEquiv x)

/-- The stalks of the sheaf of analytic functions on `𝕜^σ` have dimension `#σ`. -/
theorem ringKrullDim_stalk (x : σ → 𝕜) :
    ringKrullDim ((analyticPresheaf 𝕜 (σ → 𝕜)).stalk x) = Fintype.card σ := by
  rw [← ringKrullDim_eq_of_ringEquiv (convergentStalkEquiv x),
    MvPowerSeries.ringKrullDim_convergent]

/-- **Hilbert's syzygy theorem for `𝒪_{𝕜^σ, x}`**: every module over the stalk has projective
dimension at most `#σ`. -/
theorem hasProjectiveDimensionLE_stalk (x : σ → 𝕜)
    (M : ModuleCat.{u} ((analyticPresheaf 𝕜 (σ → 𝕜)).stalk x)) :
    HasProjectiveDimensionLE M (Fintype.card σ) :=
  IsRegularLocalRing.hasProjectiveDimensionLE (ringKrullDim_stalk x) M

end Stalk

/-! ### The syzygy step -/

section SyzygyStep

variable {R : Type u} [CommRing R] {ι μ : Type} [Fintype ι] [Fintype μ]

omit [Fintype ι] in
lemma ker_linearCombination_eq_matrixRelationModule (G : μ → ι → R) :
    LinearMap.ker (Fintype.linearCombination R G) =
      matrixRelationModule (fun i m ↦ G m i) := by
  ext c
  simp only [LinearMap.mem_ker, mem_matrixRelationModule, Fintype.linearCombination_apply,
    funext_iff, Finset.sum_apply, Pi.smul_apply, smul_eq_mul, Pi.zero_apply]

omit [Fintype ι] in
/-- **The syzygy step**: if the vectors `G_m ∈ R^ι` span a module of projective dimension
`≤ d + 1`, their module of relations has projective dimension `≤ d`. -/
theorem hasProjectiveDimensionLE_relations (G : μ → ι → R) (d : ℕ)
    (h : HasProjectiveDimensionLE (ModuleCat.of R (Submodule.span R (Set.range G))) (d + 1)) :
    HasProjectiveDimensionLE (ModuleCat.of R (matrixRelationModule (fun i m ↦ G m i))) d := by
  let f := (Fintype.linearCombination R G).rangeRestrict
  have hS := LinearMap.shortExact_shortComplexKer (LinearMap.surjective_rangeRestrict
    (Fintype.linearCombination R G))
  have hproj : Projective (ModuleCat.of R (μ → R)) :=
    ModuleCat.projective_of_free (Pi.basisFun R μ)
  have h₃ : HasProjectiveDimensionLT (ModuleCat.of R (LinearMap.range
      (Fintype.linearCombination R G))) (d + 2) := by
    rw [Fintype.range_linearCombination]
    exact h
  have h₁ := (hS.hasProjectiveDimensionLT_X₃_iff d hproj).mp h₃
  have hker : LinearMap.ker f = matrixRelationModule (fun i m ↦ G m i) := by
    rw [LinearMap.ker_rangeRestrict, ker_linearCombination_eq_matrixRelationModule]
  exact hasProjectiveDimensionLT_of_iso (LinearEquiv.ofEq _ _ hker).toModuleIso (d + 1)

omit [Fintype ι] in
/-- A finitely generated module of projective dimension `0` over a local ring is free: the
vectors of a basis span it and have no relations. -/
theorem exists_basis_of_hasProjectiveDimensionLE_zero [IsLocalRing R]
    (N : Submodule R (ι → R)) [Module.Finite R N]
    (h : HasProjectiveDimensionLE (ModuleCat.of R N) 0) :
    ∃ (r : ℕ) (b : Fin r → ι → R), N = Submodule.span R (Set.range b) ∧
      matrixRelationModule (fun i j ↦ b j i) = ⊥ := by
  have hP : Projective (ModuleCat.of R N) := (projective_iff_hasProjectiveDimensionLE_zero _).mpr h
  have : Module.Projective R N := (IsProjective.iff_projective N).mpr hP
  have : Module.Free R N := Module.free_of_flat_of_isLocalRing
  let B := Module.finBasis R N
  refine ⟨_, fun j ↦ (B j : ι → R), ?_, ?_⟩
  · calc N = Submodule.map N.subtype ⊤ := (Submodule.map_subtype_top N).symm
      _ = Submodule.map N.subtype (Submodule.span R (Set.range B)) := by rw [B.span_eq]
      _ = Submodule.span R (Set.range fun j ↦ (B j : ι → R)) := by
        rw [Submodule.map_span, ← Set.range_comp]
        rfl
  · rw [eq_bot_iff]
    intro c hc
    rw [← ker_linearCombination_eq_matrixRelationModule, LinearMap.mem_ker] at hc
    have hli : LinearIndependent R (fun j ↦ (B j : ι → R)) :=
      B.linearIndependent.map' N.subtype (Submodule.ker_subtype N)
    have := (Fintype.linearIndependent_iff.mp hli) c
    rw [Fintype.linearCombination_apply] at hc
    exact (Submodule.mem_bot R).mpr (funext fun j ↦ this hc j)

end SyzygyStep

end AnalyticGeometry
