/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import Mathlib.LinearAlgebra.TensorProduct.Tower
import Mathlib.RingTheory.Flat.Basic
import Mathlib.RingTheory.Localization.AtPrime.Basic
import Mathlib.RingTheory.TensorProduct.Basic
import SGA.Foundations.CommAlg.DominatingDVR

/-!
# Points with values in local domains dominating a given one: reduction to DVRs

Let `A₀` be a ring and `B` an `A₀`-algebra. For a local domain `D` over `A₀`, say that `B` has a
*dominating point over `D`* (`Algebra.HasDominatingPoint A₀ B D`) if there are a local domain `E`,
an injective local homomorphism `D → E` and a homomorphism `B → E` agreeing on `A₀`.
Geometrically: `Spec E → Spec D` maps the generic point to the generic point and the closed point
to the closed point, and lifts to `Spec B`; so the specialization in `Spec D` lifts to
`Spec B ×_{Spec A₀} Spec D`.

The main result, `Algebra.exists_hasDominatingPoint_of_forall_isDiscreteValuationRing`, says that
for `A₀` noetherian and a finite family `(Bᵢ)`, if every discrete valuation ring `R` over `A₀` has a
dominating point in some `Bᵢ`, then so does every local domain `D` over `A₀`. This is the algebraic
heart of the sufficiency in SGA 1 IX.2.6 (valuative criterion for universally submersive
morphisms of finite type over a locally noetherian base); compare Rydh, *Submersions and effective
descent of étale morphisms*, §2.

## Proof

Let `K` be the fraction field of `D`. The obstruction to a dominating point is an identity
`1 = ∑ dⱼ cⱼ ⊗ bⱼ` in `K ⊗_{A₀} B` with `cⱼ ∈ 𝔪_D` (`Algebra.obstructionSpan`):

* if there is no such identity, a dominating point is constructed from a prime of the
  `D`-subalgebra of `K ⊗ B` generated by `B` that contains `𝔪_D`, and a prime of its localization
  avoiding `D ∖ 0` (`Algebra.hasDominatingPoint_of_one_not_mem`);
* the identity maps along injective local homomorphisms of local domains
  (`Algebra.one_mem_obstructionSpan_of_injective`) and is incompatible with a point of `B` with
  values in `D` itself, hence with a dominating point (`Algebra.one_not_mem_of_hasDominatingPoint`);
* an identity over `D` involves finitely many elements of `D`; it already holds over the
  localization `D₂` of the `A₀`-subalgebra they generate, a noetherian local domain, because
  `Frac D₂ ⊗ B → K ⊗ B` is injective. Then it holds over a DVR dominating `D₂`
  (`IsLocalRing.exists_injective_isLocalHom_isDiscreteValuationRing`, EGA II 7.1.7), which has a
  dominating point: contradiction.
-/

universe u

open TensorProduct IsLocalRing

namespace Algebra

section Defs

variable (A₀ B : Type*) [CommRing A₀] [CommRing B] [Algebra A₀ B]

/-- `B` has a point with values in a local domain dominating `D`: a local domain `E` (in the
universe of `D`), an injective local homomorphism `ρ : D → E` and a ring homomorphism `β : B → E`
agreeing on `A₀`. -/
def HasDominatingPoint (D : Type u) [CommRing D] [Algebra A₀ D] : Prop :=
  ∃ (E : Type u) (_ : CommRing E) (_ : IsDomain E) (_ : IsLocalRing E) (ρ : D →+* E)
    (β : B →+* E), Function.Injective ρ ∧ IsLocalHom ρ ∧
      β.comp (algebraMap A₀ B) = ρ.comp (algebraMap A₀ D)

variable {A₀ B} in
/-- The `D`-submodule of `K ⊗[A₀] B` spanned by the `c ⊗ b` with `c ∈ 𝔪_D`. The identity
`1 ∈ obstructionSpan D K` is the obstruction to a dominating point over `D`. -/
def obstructionSpan (D K : Type*) [CommRing D] [IsLocalRing D] [Algebra A₀ D] [Field K]
    [Algebra A₀ K] [Algebra D K] [IsScalarTower A₀ D K] : Submodule D (K ⊗[A₀] B) :=
  Submodule.span D {x | ∃ c ∈ maximalIdeal D, ∃ b : B, x = algebraMap D K c ⊗ₜ b}

end Defs

variable {A₀ B : Type*} [CommRing A₀] [CommRing B] [Algebra A₀ B]

section Map

variable {D D' K K' : Type*} [CommRing D] [Algebra A₀ D] [CommRing D']
  [Algebra A₀ D'] [Field K] [Algebra A₀ K] [Algebra D K] [IsScalarTower A₀ D K]
  [IsFractionRing D K] [Field K'] [Algebra A₀ K'] [Algebra D' K'] [IsScalarTower A₀ D' K']
  [IsFractionRing D' K']

/-- The map of fraction fields induced by an injective homomorphism of domains over `A₀`. -/
noncomputable def fractionMap (ρ : D →+* D') (hρ : Function.Injective ρ)
    (hcomp : ρ.comp (algebraMap A₀ D) = algebraMap A₀ D') : K →ₐ[A₀] K' where
  __ := IsFractionRing.lift (A := D) (K := K) (g := (algebraMap D' K').comp ρ)
    ((IsFractionRing.injective D' K').comp hρ)
  commutes' a := by
    simp only [RingHom.toMonoidHom_eq_coe, OneHom.toFun_eq_coe, MonoidHom.toOneHom_coe,
      MonoidHom.coe_coe, IsScalarTower.algebraMap_apply A₀ D K, IsFractionRing.lift_algebraMap,
      RingHom.coe_comp, Function.comp_apply, IsScalarTower.algebraMap_apply A₀ D' K',
      ← RingHom.comp_apply ρ, hcomp]

lemma fractionMap_algebraMap (ρ : D →+* D') (hρ : Function.Injective ρ)
    (hcomp : ρ.comp (algebraMap A₀ D) = algebraMap A₀ D') (d : D) :
    fractionMap (K := K) (K' := K') ρ hρ hcomp (algebraMap D K d) = algebraMap D' K' (ρ d) := by
  simp only [fractionMap, AlgHom.coe_mk, IsFractionRing.lift_algebraMap, RingHom.coe_comp,
    Function.comp_apply]

variable (B) in
/-- The map `K ⊗[A₀] B → K' ⊗[A₀] B` induced by `ρ : D → D'`. -/
noncomputable abbrev tensorFractionMap (ρ : D →+* D') (hρ : Function.Injective ρ)
    (hcomp : ρ.comp (algebraMap A₀ D) = algebraMap A₀ D') : K ⊗[A₀] B →ₐ[A₀] K' ⊗[A₀] B :=
  TensorProduct.map (fractionMap ρ hρ hcomp) (AlgHom.id A₀ B)

lemma tensorFractionMap_tmul (ρ : D →+* D') (hρ : Function.Injective ρ)
    (hcomp : ρ.comp (algebraMap A₀ D) = algebraMap A₀ D') (d : D) (b : B) :
    tensorFractionMap B (K := K) (K' := K') ρ hρ hcomp (algebraMap D K d ⊗ₜ b) =
      algebraMap D' K' (ρ d) ⊗ₜ b := by
  simp [fractionMap_algebraMap]

lemma tensorFractionMap_smul (ρ : D →+* D') (hρ : Function.Injective ρ)
    (hcomp : ρ.comp (algebraMap A₀ D) = algebraMap A₀ D') (d : D) (x : K ⊗[A₀] B) :
    tensorFractionMap B (K := K) (K' := K') ρ hρ hcomp (d • x) =
      ρ d • tensorFractionMap B (K := K) (K' := K') ρ hρ hcomp x := by
  rw [Algebra.smul_def, Algebra.smul_def, map_mul]
  congr 1
  rw [Algebra.TensorProduct.algebraMap_apply, Algebra.TensorProduct.algebraMap_apply,
    tensorFractionMap_tmul]

/-- The obstruction maps along injective local homomorphisms of local domains over `A₀`. -/
theorem one_mem_obstructionSpan_of_injective [IsLocalRing D] [IsLocalRing D'] (ρ : D →+* D')
    (hρ : Function.Injective ρ) [IsLocalHom ρ]
    (hcomp : ρ.comp (algebraMap A₀ D) = algebraMap A₀ D')
    (h : (1 : K ⊗[A₀] B) ∈ obstructionSpan D K) :
    (1 : K' ⊗[A₀] B) ∈ obstructionSpan D' K' := by
  have key : ∀ x ∈ obstructionSpan (B := B) D K,
      tensorFractionMap B (K := K) (K' := K') ρ hρ hcomp x ∈ obstructionSpan (B := B) D' K' := by
    intro x hx
    induction hx using Submodule.span_induction with
    | mem y hy =>
      obtain ⟨c, hc, b, rfl⟩ := hy
      rw [tensorFractionMap_tmul]
      refine Submodule.subset_span ⟨ρ c, ?_, b, rfl⟩
      exact (mem_maximalIdeal _).mpr fun hu ↦ (mem_maximalIdeal c).mp hc (isUnit_of_map_unit ρ c hu)
    | zero => simp
    | add y z _ _ hy hz => rw [map_add]; exact add_mem hy hz
    | smul d y _ hy => rw [tensorFractionMap_smul]; exact Submodule.smul_mem _ _ hy
  simpa using key 1 h

end Map

/-- If `B` has a point with values in a local domain `E` over `A₀`, the obstruction over `E`
fails. -/
theorem one_not_mem_obstructionSpan_of_algHom {E K : Type*} [CommRing E] [IsDomain E]
    [IsLocalRing E] [Algebra A₀ E] [Field K] [Algebra A₀ K] [Algebra E K] [IsScalarTower A₀ E K]
    [IsFractionRing E K] (β : B →ₐ[A₀] E) :
    (1 : K ⊗[A₀] B) ∉ obstructionSpan E K := by
  intro h
  let Ψ : K ⊗[A₀] B →ₐ[A₀] K :=
    Algebra.TensorProduct.lift (AlgHom.id A₀ K) ((IsScalarTower.toAlgHom A₀ E K).comp β)
      fun _ _ ↦ Commute.all _ _
  have key : ∀ x ∈ obstructionSpan (B := B) E K,
      ∃ y ∈ maximalIdeal E, Ψ x = algebraMap E K y := by
    intro x hx
    induction hx using Submodule.span_induction with
    | mem z hz =>
      obtain ⟨c, hc, b, rfl⟩ := hz
      refine ⟨c * β b, Ideal.mul_mem_right _ _ hc, ?_⟩
      simp [Ψ]
    | zero => exact ⟨0, zero_mem _, by simp⟩
    | add y z _ _ hy hz =>
      obtain ⟨y₁, hy₁, e₁⟩ := hy
      obtain ⟨z₁, hz₁, e₂⟩ := hz
      exact ⟨y₁ + z₁, add_mem hy₁ hz₁, by rw [map_add, e₁, e₂, map_add]⟩
    | smul d y _ hy =>
      obtain ⟨y₁, hy₁, e₁⟩ := hy
      refine ⟨d * y₁, Ideal.mul_mem_left _ _ hy₁, ?_⟩
      rw [Algebra.smul_def, map_mul, e₁, Algebra.TensorProduct.algebraMap_apply, map_mul]
      simp [Ψ]
  obtain ⟨y, hy, e⟩ := key 1 h
  rw [map_one, ← map_one (algebraMap E K)] at e
  have := IsFractionRing.injective E K e
  exact (mem_maximalIdeal y).mp hy (this ▸ isUnit_one)

/-- A dominating point over `D` rules out the obstruction over `D`. -/
theorem one_not_mem_of_hasDominatingPoint {D : Type u} [CommRing D] [IsDomain D] [IsLocalRing D]
    [Algebra A₀ D] {K : Type*} [Field K] [Algebra A₀ K] [Algebra D K] [IsScalarTower A₀ D K]
    [IsFractionRing D K] (h : HasDominatingPoint A₀ B D) :
    (1 : K ⊗[A₀] B) ∉ obstructionSpan D K := by
  obtain ⟨E, _, _, _, ρ, β, hρ, hloc, hβ⟩ := h
  let : Algebra A₀ E := (ρ.comp (algebraMap A₀ D)).toAlgebra
  have hcomp : ρ.comp (algebraMap A₀ D) = algebraMap A₀ E := rfl
  let β' : B →ₐ[A₀] E := { β with commutes' := fun a ↦ congrArg (· a) hβ }
  intro hD
  exact one_not_mem_obstructionSpan_of_algHom (K := FractionRing E) β'
    (one_mem_obstructionSpan_of_injective (K' := FractionRing E) ρ hρ hcomp hD)

/-- A dominating point from a local ring `L` receiving `D` injectively and locally: take the
quotient of `L` by a prime ideal avoiding the image of `D ∖ 0`. -/
theorem hasDominatingPoint_of_isLocalRing {A₀ B D L : Type u} [CommRing A₀] [CommRing B]
    [Algebra A₀ B] [CommRing D] [IsDomain D] [IsLocalRing D] [Algebra A₀ D] [CommRing L]
    [IsLocalRing L] (ρL : D →+* L) (βL : B →+* L)
    (hcomp : βL.comp (algebraMap A₀ B) = ρL.comp (algebraMap A₀ D))
    (hloc : ∀ d ∈ maximalIdeal D, ρL d ∈ maximalIdeal L) (hinj : Function.Injective ρL) :
    HasDominatingPoint A₀ B D := by
  let M : Submonoid L := Submonoid.map ρL (nonZeroDivisors D)
  have hM : Disjoint ((⊥ : Ideal L) : Set L) (M : Set L) := by
    rw [Set.disjoint_left]
    rintro _ h0 ⟨d, hd, rfl⟩
    exact nonZeroDivisors.ne_zero hd (hinj (by rw [map_zero]; exact h0))
  obtain ⟨P, hP, -, hPM⟩ := Ideal.exists_le_prime_disjoint ⊥ M hM
  have hPtop : P ≠ ⊤ := hP.ne_top
  have : IsLocalRing (L ⧸ P) :=
    IsLocalRing.of_surjective' (Ideal.Quotient.mk P) Ideal.Quotient.mk_surjective
  refine ⟨L ⧸ P, inferInstance, inferInstance, inferInstance, (Ideal.Quotient.mk P).comp ρL,
    (Ideal.Quotient.mk P).comp βL, ?_, ?_, ?_⟩
  · rw [injective_iff_map_eq_zero]
    intro d hd
    by_contra hd0
    have hmem : ρL d ∈ P := Ideal.Quotient.eq_zero_iff_mem.mp hd
    exact Set.disjoint_left.mp hPM hmem ⟨d, mem_nonZeroDivisors_of_ne_zero hd0, rfl⟩
  · refine ⟨fun d hu ↦ ?_⟩
    by_contra hd
    have hdL : ρL d ∈ maximalIdeal L := hloc d ((mem_maximalIdeal d).mpr hd)
    obtain ⟨v, hv⟩ := isUnit_iff_exists_inv.mp hu
    obtain ⟨w, rfl⟩ := Ideal.Quotient.mk_surjective v
    have h1 : ρL d * w - 1 ∈ P := by
      rw [← Ideal.Quotient.eq_zero_iff_mem, map_sub, map_mul, map_one]
      exact sub_eq_zero.mpr hv
    have h2 : ρL d * w - 1 ∈ maximalIdeal L := le_maximalIdeal hPtop h1
    have h3 : ρL d * w ∈ maximalIdeal L := Ideal.mul_mem_right _ _ hdL
    have : (1 : L) ∈ maximalIdeal L := by simpa using sub_mem h3 h2
    exact (maximalIdeal.isMaximal L).ne_top ((Ideal.eq_top_iff_one _).mpr this)
  · rw [RingHom.comp_assoc, hcomp, ← RingHom.comp_assoc]

/-- If the obstruction fails over `D`, then `B` has a dominating point over `D`. -/
theorem hasDominatingPoint_of_one_not_mem {A₀ B : Type u} [CommRing A₀] [CommRing B]
    [Algebra A₀ B] (D K : Type u) [CommRing D] [IsDomain D] [IsLocalRing D] [Algebra A₀ D]
    [Field K] [Algebra A₀ K] [Algebra D K] [IsScalarTower A₀ D K] [IsFractionRing D K]
    (h : (1 : K ⊗[A₀] B) ∉ obstructionSpan D K) : HasDominatingPoint A₀ B D := by
  classical
  let T := K ⊗[A₀] B
  let iB : B →ₐ[A₀] T := Algebra.TensorProduct.includeRight
  let E' : Subalgebra D T := Algebra.adjoin D (Set.range iB)
  have hmulN : ∀ e ∈ E', ∀ n ∈ obstructionSpan (B := B) D K,
      e * n ∈ obstructionSpan (B := B) D K := by
    intro e he
    induction he using Algebra.adjoin_induction with
    | mem x hx =>
      obtain ⟨b, rfl⟩ := hx
      intro n hn
      induction hn using Submodule.span_induction with
      | mem y hy =>
        obtain ⟨c, hc, b', rfl⟩ := hy
        refine Submodule.subset_span ⟨c, hc, b * b', ?_⟩
        change (1 ⊗ₜ b) * _ = _
        rw [Algebra.TensorProduct.tmul_mul_tmul, one_mul]
      | zero => simp
      | add y z _ _ hy hz => rw [mul_add]; exact add_mem hy hz
      | smul d y _ hy => rw [mul_smul_comm]; exact Submodule.smul_mem _ d hy
    | algebraMap d =>
      intro n hn
      rw [← Algebra.smul_def]
      exact Submodule.smul_mem _ d hn
    | add x y _ _ hx hy =>
      intro n hn
      rw [add_mul]
      exact add_mem (hx n hn) (hy n hn)
    | mul x y _ _ hx hy =>
      intro n hn
      rw [mul_assoc]
      exact hx _ (hy n hn)
  let J : Ideal E' :=
    { carrier := {e | (e : T) ∈ obstructionSpan (B := B) D K}
      add_mem' := by
        intro x y hx hy
        change ((x + y : E') : T) ∈ obstructionSpan (B := B) D K
        rw [AddMemClass.coe_add]
        exact add_mem hx hy
      zero_mem' := by
        change ((0 : E') : T) ∈ obstructionSpan (B := B) D K
        rw [ZeroMemClass.coe_zero]
        exact zero_mem _
      smul_mem' := fun c x hx ↦ hmulN c c.2 x hx }
  have hJ : Ideal.map (algebraMap D E') (maximalIdeal D) ≤ J := by
    rw [Ideal.map_le_iff_le_comap]
    intro c hc
    change ((algebraMap D E' c : E') : T) ∈ obstructionSpan (B := B) D K
    refine Submodule.subset_span ⟨c, hc, 1, ?_⟩
    rw [Subalgebra.coe_algebraMap, Algebra.TensorProduct.algebraMap_apply]
  have hne : Ideal.map (algebraMap D E') (maximalIdeal D) ≠ ⊤ := by
    intro htop
    apply h
    have : ((1 : E') : T) ∈ obstructionSpan (B := B) D K := hJ (htop ▸ Submodule.mem_top)
    simpa using this
  obtain ⟨Q, hQmax, hQ⟩ := Ideal.exists_le_maximal _ hne
  let L := Localization.AtPrime Q
  let ρL : D →+* L := (algebraMap E' L).comp (algebraMap D E')
  let β' : B →+* E' := iB.toRingHom.codRestrict E' fun b ↦ Algebra.subset_adjoin ⟨b, rfl⟩
  refine hasDominatingPoint_of_isLocalRing ρL ((algebraMap E' L).comp β') ?_ ?_ ?_
  · ext a
    simp only [RingHom.coe_comp, Function.comp_apply, ρL]
    congr 1
    apply Subtype.ext
    simp only [β', RingHom.codRestrict_apply, AlgHom.toRingHom_eq_coe, RingHom.coe_coe,
      AlgHom.commutes, Subalgebra.coe_algebraMap, ← IsScalarTower.algebraMap_apply]
  · intro d hd
    exact (IsLocalization.AtPrime.to_map_mem_maximal_iff L Q _).mpr
      (hQ (Ideal.mem_map_of_mem _ hd))
  · rw [injective_iff_map_eq_zero]
    intro d h0
    by_contra hd
    obtain ⟨⟨s, hs⟩, hsd⟩ := (IsLocalization.map_eq_zero_iff Q.primeCompl L _).mp h0
    have hsT : (s : T) * algebraMap D T d = 0 := congrArg Subtype.val hsd
    have hu : IsUnit (algebraMap D T d) := by
      rw [IsScalarTower.algebraMap_apply D K T]
      exact (IsUnit.mk0 _ (IsFractionRing.to_map_ne_zero_of_mem_nonZeroDivisors
        (mem_nonZeroDivisors_of_ne_zero hd))).map _
    have : (s : T) = 0 := by simpa [hu.mul_left_eq_zero] using hsT
    exact hs (by rw [show s = 0 from Subtype.ext this]; exact Q.zero_mem)

/-- `K₂ ⊗[A₀] B → K ⊗[A₀] B` is injective for a homomorphism of fields `K₂ → K` over `A₀`. -/
theorem injective_tensorProduct_map_of_field {K₂ K : Type*} [Field K₂] [Field K] [Algebra A₀ K₂]
    [Algebra A₀ K] (κ : K₂ →ₐ[A₀] K) :
    Function.Injective (TensorProduct.map κ (AlgHom.id A₀ B)) := by
  let : Algebra K₂ K := κ.toRingHom.toAlgebra
  have : IsScalarTower A₀ K₂ K := IsScalarTower.of_algebraMap_eq fun a ↦ (κ.commutes a).symm
  let e := Algebra.TensorProduct.cancelBaseChange A₀ K₂ K K B
  have hinc : Function.Injective
      (Algebra.TensorProduct.includeRight : K₂ ⊗[A₀] B →ₐ[K₂] K ⊗[K₂] (K₂ ⊗[A₀] B)) :=
    Algebra.TensorProduct.includeRight_injective (algebraMap K₂ K).injective
  have heq : ⇑(TensorProduct.map κ (AlgHom.id A₀ B)) = e ∘ Algebra.TensorProduct.includeRight := by
    ext x
    induction x using TensorProduct.induction_on with
    | zero => simp
    | tmul k b =>
      simp [e, Algebra.TensorProduct.cancelBaseChange_tmul, Algebra.smul_def]
      rfl
    | add x y hx hy => simp only [map_add, Function.comp_apply] at hx hy ⊢; rw [hx, hy]
  rw [heq]
  exact e.injective.comp hinc

/-- **Dominating points can be tested on discrete valuation rings.** Let `A₀` be a noetherian
ring and `(Bᵢ)` a finite family of `A₀`-algebras. If for every discrete valuation ring `R` over
`A₀` some `Bᵢ` has a dominating point over `R`, then for every local domain `D` over `A₀` some
`Bᵢ` has a dominating point over `D`. (All rings in one universe `u`.) -/
theorem exists_hasDominatingPoint_of_forall_isDiscreteValuationRing {A₀ : Type u} [CommRing A₀]
    [IsNoetherianRing A₀] {ι : Type*} [Finite ι] (B : ι → Type u) [∀ i, CommRing (B i)]
    [∀ i, Algebra A₀ (B i)]
    (H : ∀ (R : Type u) [CommRing R] [IsDomain R] [IsDiscreteValuationRing R] [Algebra A₀ R],
      ∃ i, HasDominatingPoint A₀ (B i) R)
    (D : Type u) [CommRing D] [IsDomain D] [IsLocalRing D] [Algebra A₀ D] :
    ∃ i, HasDominatingPoint A₀ (B i) D := by
  classical
  by_contra hD
  push Not at hD
  let K := FractionRing D
  have hobs : ∀ i, (1 : K ⊗[A₀] B i) ∈ obstructionSpan D K := fun i ↦ by
    by_contra h
    exact hD i (hasDominatingPoint_of_one_not_mem D K h)
  -- Finite witnesses of the obstructions.
  have hw : ∀ i, ∃ (n : ℕ) (f : Fin n → D) (c : Fin n → D) (b : Fin n → B i),
      (∀ j, c j ∈ maximalIdeal D) ∧ ∑ j, f j • (algebraMap D K (c j) ⊗ₜ[A₀] b j) = 1 := by
    intro i
    obtain ⟨n, f, g, hfg⟩ := Submodule.mem_span_set'.mp (hobs i)
    choose c hc b hb using fun j ↦ (g j).2
    exact ⟨n, f, c, b, hc, by rw [← hfg]; exact Finset.sum_congr rfl fun j _ ↦ by rw [hb j]⟩
  choose n f c b hc hsum using hw
  -- The noetherian local domain `D₂` generated by these elements.
  let Ss : Set D := ⋃ i, (Set.range (f i) ∪ Set.range (c i))
  have hSs : Ss.Finite := Set.finite_iUnion fun i ↦ (Set.finite_range _).union (Set.finite_range _)
  let D₁ : Subalgebra A₀ D := Algebra.adjoin A₀ Ss
  have : Algebra.FiniteType A₀ D₁ :=
    (Subalgebra.fg_iff_finiteType D₁).mp ⟨hSs.toFinset, by simp [D₁]⟩
  have : IsNoetherianRing D₁ := Algebra.FiniteType.isNoetherianRing A₀ D₁
  let 𝔭 : Ideal D₁ := (maximalIdeal D).comap D₁.val.toRingHom
  have : 𝔭.IsPrime := Ideal.comap_isPrime _ _
  let D₂ := Localization.AtPrime 𝔭
  have : IsNoetherianRing D₂ := IsLocalization.isNoetherianRing 𝔭.primeCompl D₂ inferInstance
  have : IsDomain D₂ := IsLocalization.isDomain_localization 𝔭.primeCompl_le_nonZeroDivisors
  have hunits : ∀ s : 𝔭.primeCompl, IsUnit (D₁.val.toRingHom (s : D₁)) := fun s ↦ by
    by_contra hs
    exact s.2 ((mem_maximalIdeal _).mpr hs)
  let ρ₂ : D₂ →+* D := IsLocalization.lift (M := 𝔭.primeCompl) hunits
  have hρ₂a : ∀ x : D₁, ρ₂ (algebraMap D₁ D₂ x) = x := fun x ↦ IsLocalization.lift_eq hunits x
  have hinj₁ : Function.Injective (algebraMap D₁ D₂) :=
    IsLocalization.injective D₂ 𝔭.primeCompl_le_nonZeroDivisors
  have hρ₂ : Function.Injective ρ₂ := by
    rw [IsLocalization.lift_injective_iff]
    intro x y
    exact ⟨fun h ↦ by rw [hinj₁ h], fun h ↦ congrArg _ (Subtype.ext h)⟩
  have : IsLocalHom ρ₂ := ⟨fun x hx ↦ by
    obtain ⟨a, s, rfl⟩ := IsLocalization.exists_mk'_eq 𝔭.primeCompl x
    have hspec := IsLocalization.mk'_spec D₂ a s
    have hs : IsUnit (ρ₂ (algebraMap D₁ D₂ s)) := by rw [hρ₂a]; exact hunits s
    have ha : IsUnit (ρ₂ (algebraMap D₁ D₂ a)) := by
      rw [← hspec, map_mul]; exact hx.mul hs
    rw [hρ₂a] at ha
    have ha' : a ∈ 𝔭.primeCompl := fun h ↦ (mem_maximalIdeal _).mp h ha
    have hau : IsUnit (algebraMap D₁ D₂ a) := IsLocalization.map_units D₂ ⟨a, ha'⟩
    rw [← hspec] at hau
    exact isUnit_of_mul_isUnit_left hau⟩
  have hcomp₂ : ρ₂.comp (algebraMap A₀ D₂) = algebraMap A₀ D := by
    ext a
    simp only [RingHom.coe_comp, Function.comp_apply]
    rw [IsScalarTower.algebraMap_apply A₀ D₁ D₂, hρ₂a]
    rfl
  -- The obstructions already hold over `D₂`.
  let K₂ := FractionRing D₂
  have hobs₂ : ∀ i, (1 : K₂ ⊗[A₀] B i) ∈ obstructionSpan D₂ K₂ := by
    intro i
    have hf : ∀ j, f i j ∈ D₁ := fun j ↦
      Algebra.subset_adjoin (Set.mem_iUnion.mpr ⟨i, Or.inl ⟨j, rfl⟩⟩)
    have hcD : ∀ j, c i j ∈ D₁ := fun j ↦
      Algebra.subset_adjoin (Set.mem_iUnion.mpr ⟨i, Or.inr ⟨j, rfl⟩⟩)
    let f₂ : Fin (n i) → D₂ := fun j ↦ algebraMap D₁ D₂ ⟨f i j, hf j⟩
    let c₂ : Fin (n i) → D₂ := fun j ↦ algebraMap D₁ D₂ ⟨c i j, hcD j⟩
    have hc₂ : ∀ j, c₂ j ∈ maximalIdeal D₂ := fun j ↦
      (IsLocalization.AtPrime.to_map_mem_maximal_iff D₂ 𝔭 _).mpr (hc i j)
    let x := ∑ j, f₂ j • (algebraMap D₂ K₂ (c₂ j) ⊗ₜ[A₀] b i j)
    have hx : x ∈ obstructionSpan D₂ K₂ := Submodule.sum_mem _ fun j _ ↦
      Submodule.smul_mem _ _ (Submodule.subset_span ⟨c₂ j, hc₂ j, b i j, rfl⟩)
    have hΦ : tensorFractionMap (B i) (K := K₂) (K' := K) ρ₂ hρ₂ hcomp₂ x = 1 := by
      simp only [x, map_sum, tensorFractionMap_smul, tensorFractionMap_tmul, f₂, c₂, hρ₂a]
      exact hsum i
    have h1 : x = 1 := injective_tensorProduct_map_of_field (B := B i)
      (fractionMap (K := K₂) (K' := K) ρ₂ hρ₂ hcomp₂) (hΦ.trans (map_one _).symm)
    rwa [h1] at hx
  -- A DVR dominating `D₂` has the obstructions too: contradiction.
  obtain ⟨R, _, _, _, φR, hφR, hlocR⟩ :=
    IsLocalRing.exists_injective_isLocalHom_isDiscreteValuationRing D₂
  let : Algebra A₀ R := (φR.comp (algebraMap A₀ D₂)).toAlgebra
  obtain ⟨i, hi⟩ := H R
  exact one_not_mem_of_hasDominatingPoint (K := FractionRing R) hi
    (one_mem_obstructionSpan_of_injective (K := K₂) (K' := FractionRing R) φR hφR rfl (hobs₂ i))

end Algebra
