/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.Foundations.CommAlg.FlatResidueExtensionRealize
import Mathlib.RingTheory.AlgebraicIndependent.Defs
import Mathlib.RingTheory.Flat.Localization
import Mathlib.RingTheory.Localization.AtPrime.Basic
import Mathlib.RingTheory.Polynomial.Basic
import Mathlib.FieldTheory.IntermediateField.Adjoin.Algebra

/-!
# Realizing a purely transcendental residue field extension

EGA 0_III 10.3.1, transcendental step (Bourbaki, *Algèbre commutative* IX, Appendice): let `A`
be a local ring with residue field `k`, `φ : k → K` a field extension and `x : ι → K` a family
algebraically independent over `k`. Then `k(x) ⊆ K` is realized over `(A, φ)`
(`IsLocalRing.realizes_adjoin_of_algebraicIndependent`) by `C = A[X_i]_{𝔪 A[X_i]}`, the
localization of the polynomial ring at the prime `𝔪_A A[X]` (the kernel of `A[X] → k[X]`). `C` is
flat over `A`, local with maximal ideal `𝔪_A C`, and its residue field is `k(X) ≅ k(x)`.
-/

universe u

open IsLocalRing MvPolynomial

namespace IsLocalRing

variable {K : Type u} [Field K]

/-- The subfield `k(x)` of `K` generated by an algebraically independent family `x` over `φ(k)`
is realized over `(A, φ)`, by `A[X]_{𝔪 A[X]}`. -/
theorem realizes_adjoin_of_algebraicIndependent (A : Type u) [CommRing A] [IsLocalRing A]
    (φ : ResidueField A →+* K) {ι : Type u} (x : ι → K)
    (hx : letI := φ.toAlgebra; AlgebraicIndependent (ResidueField A) x) :
    Realizes A φ (letI := φ.toAlgebra;
      (IntermediateField.adjoin (ResidueField A) (Set.range x)).toSubfield) := by
  let _ : Algebra (ResidueField A) K := φ.toAlgebra
  -- The prime `P = 𝔪 A[X]` and `C = A[X]_P`.
  let P : Ideal (MvPolynomial ι A) := RingHom.ker (MvPolynomial.map (residue A))
  have hP : P = (maximalIdeal A).map (C : A →+* MvPolynomial ι A) :=
    (MvPolynomial.ker_map (residue A)).trans (by rw [ker_residue])
  have : P.IsPrime := RingHom.ker_isPrime _
  let Cl := Localization.AtPrime P
  -- The evaluation `A[X] → K`, `a ↦ φ(ā)`, `X_i ↦ x_i`; its kernel is `P`.
  let ev : MvPolynomial ι A →+* K :=
    (MvPolynomial.aeval x : MvPolynomial ι (ResidueField A) →ₐ[ResidueField A] K).toRingHom.comp
      (MvPolynomial.map (residue A))
  have hev : ∀ g, ev g = 0 ↔ g ∈ P := by
    intro g
    rw [RingHom.mem_ker]
    constructor
    · intro h
      exact (injective_iff_map_eq_zero _).mp hx _ h
    · intro h
      simp only [ev, RingHom.comp_apply, h, map_zero]
  have hunit : ∀ s : P.primeCompl, IsUnit (ev s) := fun s ↦
    isUnit_iff_ne_zero.mpr fun h ↦ s.2 ((hev s).mp h)
  let f : Cl →+* K := IsLocalization.lift hunit
  have hf : ∀ g, f (algebraMap _ Cl g) = ev g := IsLocalization.lift_eq hunit
  have hmax : P.map (algebraMap _ Cl) = maximalIdeal Cl :=
    IsLocalization.AtPrime.map_eq_maximalIdeal P Cl
  have hfm : ∀ c ∈ maximalIdeal Cl, f c = 0 := by
    rw [← hmax]
    intro c hc
    have hle : P.map (algebraMap _ Cl) ≤ RingHom.ker f := by
      rw [Ideal.map_le_iff_le_comap]
      intro g hg
      rw [Ideal.mem_comap, RingHom.mem_ker, hf]
      exact (hev g).mpr hg
    exact hle hc
  have : IsLocalHom f := ⟨fun c hc ↦ by
    by_contra hnu
    exact hc.ne_zero (hfm c ((mem_maximalIdeal c).mpr hnu))⟩
  let ιC : ResidueField Cl →+* K := ResidueField.lift f
  have hιC : ∀ c, ιC (residue Cl c) = f c := fun c ↦ ResidueField.lift_residue_apply f c
  have hAC : algebraMap A Cl = (algebraMap (MvPolynomial ι A) Cl).comp C :=
    IsScalarTower.algebraMap_eq A (MvPolynomial ι A) Cl
  refine ⟨Cl, inferInstance, inferInstance, inferInstance, inferInstance, ?_, ιC, fun a ↦ ?_, ?_⟩
  · rw [hAC, ← Ideal.map_map, ← hP, hmax]
  · rw [hιC, hAC, RingHom.comp_apply, hf]
    simp only [ev, RingHom.comp_apply, map_C, AlgHom.toRingHom_eq_coe, RingHom.coe_coe, aeval_C]
    rfl
  · -- the image is `k(x)`
    have hmem : ∀ g, ev g ∈ IntermediateField.adjoin (ResidueField A) (Set.range x) := by
      intro g
      apply IntermediateField.algebra_adjoin_le_adjoin
      rw [Algebra.adjoin_range_eq_range_aeval]
      exact ⟨MvPolynomial.map (residue A) g, rfl⟩
    apply le_antisymm
    · rintro _ ⟨z, rfl⟩
      obtain ⟨c, rfl⟩ := residue_surjective z
      obtain ⟨⟨g, t⟩, rfl⟩ := IsLocalization.mk'_surjective P.primeCompl c
      have ht0 : ev t ≠ 0 := (hunit t).ne_zero
      have hval : f (IsLocalization.mk' Cl g t) = ev g * (ev t)⁻¹ := by
        rw [IsLocalization.lift_mk'_spec, mul_comm (ev g), ← mul_assoc, mul_inv_cancel₀ ht0,
          one_mul]
      rw [hιC, hval]
      exact IntermediateField.mul_mem _ (hmem g) (IntermediateField.inv_mem _ (hmem t))
    · let F : IntermediateField (ResidueField A) K :=
        ιC.fieldRange.toIntermediateField fun z ↦ by
          obtain ⟨a, rfl⟩ := residue_surjective z
          refine ⟨residue Cl (algebraMap A Cl a), ?_⟩
          rw [hιC, hAC, RingHom.comp_apply, hf]
          simp only [ev, RingHom.comp_apply, map_C, AlgHom.toRingHom_eq_coe, RingHom.coe_coe,
            aeval_C]
      have hle : IntermediateField.adjoin (ResidueField A) (Set.range x) ≤ F := by
        rw [IntermediateField.adjoin_le_iff]
        rintro _ ⟨i, rfl⟩
        refine ⟨residue Cl (algebraMap (MvPolynomial ι A) Cl (X i)), ?_⟩
        rw [hιC, hf]
        simp [ev]
      exact fun y hy ↦ hle hy

end IsLocalRing
