/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.Foundations.CommAlg.FlatResidueExtensionRealize
import SGA.Foundations.StrictHenselization

/-!
# Realizing a separable algebraic residue field extension

EGA 0_III 10.3.1, separable algebraic step (EGA IV 18.8; Stacks 0BSK): let `A` be a local ring
and `φ : k → K` a field extension of its residue field. The separable closure of `k` in `K` is
realized over `(A, φ)` (`IsLocalRing.realizes_separableClosure`) by the strict henselization
`StrictHenselization A K` of `A` with respect to `K`: it is local, flat over `A`, its maximal
ideal is generated by that of `A`, and its residue field embeds into `K` with image the
separable closure of `k` (`SGA.Foundations.Henselization`, `SGA.Foundations.StrictHenselization`).
-/

universe u

open IsLocalRing

namespace IsLocalRing

variable {K : Type u} [Field K]

/-- The separable closure of `φ(k)` in `K` is realized over `(A, φ)`, by the strict henselization
of `A` with respect to `K`. -/
theorem realizes_separableClosure (A : Type u) [CommRing A] [IsLocalRing A]
    (φ : ResidueField A →+* K) :
    Realizes A φ (letI := φ.toAlgebra; (separableClosure (ResidueField A) K).toSubfield) := by
  let _ : Algebra (ResidueField A) K := φ.toAlgebra
  let _ : Algebra A K := (φ.comp (residue A)).toAlgebra
  have : IsScalarTower A (ResidueField A) K := IsScalarTower.of_algebraMap_eq fun _ ↦ rfl
  have : IsLocalHom (algebraMap A K) := isLocalHom_algebraMap_of_isScalarTower
  refine ⟨StrictHenselization A K, inferInstance, inferInstance, inferInstance, inferInstance,
    StrictHenselization.map_maximalIdeal,
    (StrictHenselization.residueFieldHom (R := A) (K := K)).toRingHom, fun a ↦ ?_, ?_⟩
  · rw [AlgHom.toRingHom_eq_coe, RingHom.coe_coe, StrictHenselization.residueFieldHom_residue,
      AlgHom.commutes]
    rfl
  · ext y
    rw [RingHom.mem_fieldRange, IntermediateField.mem_toSubfield]
    constructor
    · rintro ⟨z, rfl⟩
      obtain ⟨w, rfl⟩ := residue_surjective z
      rw [AlgHom.toRingHom_eq_coe, RingHom.coe_coe, StrictHenselization.residueFieldHom_residue]
      exact StrictHenselization.pointHom_mem_separableClosure A K w
    · intro hy
      obtain ⟨w, hw⟩ := StrictHenselization.exists_pointHom_eq A K (mem_separableClosure_iff.mp hy)
      exact ⟨residue _ w, by
        rw [AlgHom.toRingHom_eq_coe, RingHom.coe_coe, StrictHenselization.residueFieldHom_residue,
          hw]⟩

end IsLocalRing
