/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import Mathlib.RingTheory.DiscreteValuationRing.TFAE
import Mathlib.RingTheory.Ideal.MinimalPrime.Noetherian
import Mathlib.RingTheory.Nakayama
import Mathlib.RingTheory.RegularLocalRing.Defs
import SGA.Foundations.CommAlg.Depth
import SGA.SGA2.ExposeIII.RegularLocalRegularSequence
import SGA.SGA2.ExposeV.GlobalProjectiveDimension
import SGA.SGA2.ExposeV.HomologicalRegularityCriterion

/-!
# Regular local rings

Basic properties of regular local rings (mathlib's `IsRegularLocalRing`: a noetherian local ring
whose maximal ideal is generated by `dim R` elements) that mathlib does not have yet.

## Main results

* `IsRegularLocalRing.isDomain`: a regular local ring is a domain (Stacks 00NP).
* `IsRegularLocalRing.quotient_span_range`: the quotient by part of a regular system of
  parameters is regular, of the expected dimension (Stacks 00NR).
* `IsRegularLocalRing.isRegular_of_span_eq_maximalIdeal`: a regular system of parameters is a
  regular sequence, hence `IsRegularLocalRing.depth_eq_ringKrullDim`: a regular local ring is
  Cohen–Macaulay (Stacks 00NQ).
* `IsRegularLocalRing.hasProjectiveDimensionLE` and
  `isRegularLocalRing_iff_exists_hasProjectiveDimensionLE`: Serre's theorem, a noetherian local
  ring is regular iff it has finite global dimension, which then equals its dimension
  (Stacks 00OB, 065U).
* `IsRegularLocalRing.localization_atPrime` / `IsRegularLocalRing.isRegularRing`: localizations
  of a regular local ring at primes are regular (Stacks 00OE).
* `IsRegularLocalRing.isDiscreteValuationRing`: a regular local ring of dimension one is a
  discrete valuation ring.

The homological results (Serre's theorem and its consequence for localizations) are proved in
this repository's formalization of SGA 2, Exposés IV–V; they are re-exported here.
-/

universe u

open IsLocalRing RingTheory.Sequence CategoryTheory

namespace IsLocalRing

variable {A : Type u} [CommRing A] [IsLocalRing A] [IsNoetherianRing A]

/-- An element `x ∈ m \ m²` of a noetherian local ring is part of a minimal system of generators
of `m`. -/
theorem exists_span_insert_eq_maximalIdeal {x : A} (hx : x ∈ maximalIdeal A)
    (hx2 : x ∉ maximalIdeal A ^ 2) :
    ∃ (k : ℕ) (y : Fin k → A), k + 1 = (maximalIdeal A).spanFinrank ∧
      maximalIdeal A = Ideal.span (insert x (Set.range y)) := by
  let x' : maximalIdeal A := ⟨x, hx⟩
  let v := (maximalIdeal A).toCotangent x'
  have hv : v ≠ 0 := by rwa [Ne, Ideal.toCotangent_eq_zero]
  let W := Submodule.span (ResidueField A) {v}
  let b := Module.finBasis (ResidueField A) (CotangentSpace A ⧸ W)
  have hsurj :
      Function.Surjective fun z : maximalIdeal A ↦ W.mkQ ((maximalIdeal A).toCotangent z) :=
    W.mkQ_surjective.comp ((maximalIdeal A).toCotangent_surjective)
  choose y hy using fun j ↦ hsurj (b j)
  refine ⟨_, fun j ↦ (y j : A), ?_, ?_⟩
  · rw [spanFinrank_maximalIdeal_eq_finrank_cotangentSpace,
      ← Submodule.finrank_quotient_add_finrank W, finrank_span_singleton hv]
  · let S := Submodule.span (ResidueField A)
      ((maximalIdeal A).toCotangent '' insert x' (Set.range y))
    have hW : W ≤ S := Submodule.span_le.mpr (Set.singleton_subset_iff.mpr
      (Submodule.subset_span ⟨x', Set.mem_insert _ _, rfl⟩))
    have hS : S.map W.mkQ = ⊤ := by
      rw [eq_top_iff, ← b.span_eq, Submodule.span_le]
      rintro _ ⟨j, rfl⟩
      exact ⟨_, Submodule.subset_span ⟨y j, Set.mem_insert_of_mem _ ⟨j, rfl⟩, rfl⟩, hy j⟩
    rw [Submodule.map_mkQ_eq_top, sup_eq_right.mpr hW,
      CotangentSpace.span_image_eq_top_iff] at hS
    have := congrArg (Submodule.map (maximalIdeal A).subtype) hS
    rw [Submodule.map_span, Submodule.map_top, Submodule.range_subtype] at this
    refine this.symm.trans ?_
    rw [Set.image_insert_eq, ← Set.range_comp]
    rfl

/-- In a noetherian local ring of positive dimension there is `x ∈ m \ m²` outside all minimal
primes (prime avoidance). -/
theorem exists_mem_maximalIdeal_notMem_sq_notMem_minimalPrimes (h : 0 < ringKrullDim A) :
    ∃ x ∈ maximalIdeal A, x ∉ maximalIdeal A ^ 2 ∧ ∀ P ∈ minimalPrimes A, x ∉ P := by
  by_contra! H
  let s : Set (Ideal A) := insert (maximalIdeal A ^ 2) (minimalPrimes A)
  have hs : s.Finite := (minimalPrimes.finite_of_isNoetherianRing A).insert _
  have hp : ∀ I ∈ s, I ≠ maximalIdeal A ^ 2 → I ≠ maximalIdeal A ^ 2 → (id I).IsPrime :=
    fun I hI h _ ↦ ((Set.mem_insert_iff.mp hI).resolve_left h).1.1
  have hsub : (maximalIdeal A : Set A) ⊆ ⋃ I ∈ s, ((id I : Ideal A) : Set A) := by
    intro x hx
    by_cases hx2 : x ∈ maximalIdeal A ^ 2
    · exact Set.mem_biUnion (Set.mem_insert _ _) hx2
    · obtain ⟨P, hP, hxP⟩ := H x hx hx2
      exact Set.mem_biUnion (Set.mem_insert_of_mem _ hP) hxP
  obtain ⟨I, hI, hle⟩ := (Ideal.subset_union_prime_finite hs _ _ hp).mp hsub
  rcases Set.mem_insert_iff.mp hI with rfl | hI
  · change maximalIdeal A ≤ maximalIdeal A ^ 2 at hle
    have : IsIdempotentElem (maximalIdeal A) := by
      rw [IsIdempotentElem, ← pow_two]
      exact le_antisymm (Ideal.pow_le_self two_ne_zero) hle
    have := (Ideal.cotangent_subsingleton_iff _).mpr this
    have hfield : IsField A := subsingleton_cotangentSpace_iff.mp this
    rw [ringKrullDim_eq_zero_of_isField hfield] at h
    exact lt_irrefl _ h
  · change maximalIdeal A ≤ I at hle
    have hIm : I = maximalIdeal A := ((maximalIdeal.isMaximal A).eq_of_le hI.1.1.ne_top hle).symm
    subst hIm
    have h0 := Ideal.height_eq_zero_iff.mpr hI
    rw [← maximalIdeal_height_eq_ringKrullDim, h0] at h
    exact lt_irrefl _ h

omit [IsNoetherianRing A] in
theorem maximalIdeal_le_ringJacobson : maximalIdeal A ≤ Ring.jacobson A := by
  rw [Ring.jacobson_eq_sInf_isMaximal]
  exact le_sInf fun I hI ↦ (eq_maximalIdeal hI).ge

end IsLocalRing

namespace IsRegularLocalRing

section Domain

private theorem ncard_range_le {A β : Type*} [Finite β] (h : β → A) :
    (Set.range h).ncard ≤ Nat.card β := by
  rw [← Set.image_univ, ← Set.ncard_univ]
  exact Set.ncard_image_le (Set.toFinite _)

/-- Induction step: a regular local ring whose maximal ideal needs `d` generators is a domain. -/
private theorem isDomain_of_spanFinrank_eq (d : ℕ) :
    ∀ (B : Type u) [CommRing B] [IsRegularLocalRing B], (maximalIdeal B).spanFinrank = d →
      IsDomain B := by
  induction d with
  | zero =>
    intro B _ _ hd
    have hbot : maximalIdeal B = ⊥ :=
      (Submodule.spanFinrank_eq_zero_iff_eq_bot (maximalIdeal B).fg_of_isNoetherianRing).mp hd
    let := (isField_iff_maximalIdeal_eq.mpr hbot).toField
    infer_instance
  | succ d ih =>
    intro B _ _ hd
    have hdim : ringKrullDim B = (d + 1 : ℕ) := by
      rw [← IsRegularLocalRing.spanFinrank_maximalIdeal, hd]
    obtain ⟨x, hxm, hx2, hxP⟩ := exists_mem_maximalIdeal_notMem_sq_notMem_minimalPrimes
      (A := B) (by rw [hdim]; exact_mod_cast Nat.succ_pos d)
    obtain ⟨k, y, hk, hmax⟩ := exists_span_insert_eq_maximalIdeal hxm hx2
    obtain rfl : k = d := by omega
    set I := Ideal.span {x}
    have hIm : I ≤ maximalIdeal B := (Ideal.span_le).mpr (Set.singleton_subset_iff.mpr hxm)
    have : Nontrivial (B ⧸ I) :=
      Ideal.Quotient.nontrivial_iff.mpr (ne_top_of_le_ne_top (maximalIdeal.isMaximal B).ne_top hIm)
    have : IsLocalRing (B ⧸ I) :=
      IsLocalRing.of_surjective' (Ideal.Quotient.mk I) Ideal.Quotient.mk_surjective
    have hmaxB : maximalIdeal (B ⧸ I) = Ideal.span (Set.range (Ideal.Quotient.mk I ∘ y)) := by
      rw [← map_maximalIdeal_of_surjective (Ideal.Quotient.mk I) Ideal.Quotient.mk_surjective,
        hmax, Ideal.map_span, Set.image_insert_eq,
        Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.mem_span_singleton_self x),
        Ideal.span_insert_zero, ← Set.range_comp]
    have hspan : (maximalIdeal (B ⧸ I)).spanFinrank ≤ k := by
      rw [hmaxB]
      refine (Submodule.spanFinrank_span_le_ncard_of_finite (Set.finite_range _)).trans ?_
      simpa using ncard_range_le (Ideal.Quotient.mk I ∘ y)
    have hI1 : I.spanFinrank ≤ 1 := by
      simpa using Submodule.spanFinrank_span_le_ncard_of_finite (R := B) (Set.finite_singleton x)
    have h1 := ringKrullDim_le_ringKrullDim_quotient_add_spanFinrank I
      (hIm.trans maximalIdeal_le_ringJacobson)
    have hdimB : (k : WithBot ℕ∞) ≤ ringKrullDim (B ⧸ I) := by
      obtain ⟨e, he⟩ : ∃ e : ℕ∞, ringKrullDim (B ⧸ I) = e :=
        (WithBot.ne_bot_iff_exists.mp (ne_bot_of_le_ne_bot WithBot.coe_ne_bot
          ringKrullDim_nonneg_of_nontrivial)).imp fun _ h ↦ h.symm
      rw [hdim, he] at h1
      rw [he]
      have h2 : ((k + 1 : ℕ) : WithBot ℕ∞) ≤ (e : WithBot ℕ∞) + 1 :=
        h1.trans (by gcongr; exact_mod_cast hI1)
      have h3 : ((k : ℕ∞) + 1 : ℕ∞) ≤ e + 1 := by exact_mod_cast h2
      exact_mod_cast (ENat.add_le_add_iff_right ENat.one_ne_top).mp h3
    have : IsRegularLocalRing (B ⧸ I) :=
      IsRegularLocalRing.of_spanFinrank_maximalIdeal_le (B ⧸ I)
        (le_trans (by exact_mod_cast hspan) hdimB)
    have hdom : IsDomain (B ⧸ I) := ih (B ⧸ I) (le_antisymm hspan (by
      have := (ringKrullDim_le_spanFinrank_maximalIdeal (B ⧸ I))
      exact_mod_cast hdimB.trans this))
    have hIprime : I.IsPrime := (Ideal.Quotient.isDomain_iff_prime I).mp hdom
    obtain ⟨P, hP, hPI⟩ := Ideal.exists_minimalPrimes_le (bot_le : ⊥ ≤ I)
    have hPsmul : P ≤ maximalIdeal B • P := by
      intro p hp
      obtain ⟨a, rfl⟩ := Ideal.mem_span_singleton'.mp (hPI hp)
      have ha : a ∈ P := (hP.1.1.mem_or_mem hp).resolve_right (hxP P hP)
      rw [mul_comm]
      exact Submodule.smul_mem_smul hxm ha
    have hP0 : P = ⊥ := Submodule.eq_bot_of_le_smul_of_le_jacobson_bot _ _
      (IsNoetherian.noetherian P) hPsmul (maximalIdeal_le_jacobson _)
    have : (⊥ : Ideal B).IsPrime := hP0 ▸ hP.1.1
    exact IsDomain.of_bot_isPrime B

/-- A regular local ring is a domain (Stacks 00NP, Matsumura, *Commutative Ring Theory*,
Th. 14.3).

The proof is by induction on the number `d` of generators of the maximal ideal `m`. If `d > 0`,
prime avoidance gives `x ∈ m` outside `m²` and outside every minimal prime; `x` is part of a
minimal system of generators of `m`, so `A/(x)` is regular of dimension `d - 1`, hence a domain
by induction. A minimal prime `P ⊆ (x)` then satisfies `P = xP`, so `P = 0` by Nakayama. -/
@[stacks 00NP]
instance isDomain (A : Type u) [CommRing A] [IsRegularLocalRing A] : IsDomain A :=
  isDomain_of_spanFinrank_eq _ A rfl

end Domain

variable {R : Type u} [CommRing R] [IsRegularLocalRing R]

/-- The dimension of a regular local ring is the number of generators of its maximal ideal. -/
theorem ringKrullDim_eq_spanFinrank :
    ringKrullDim R = (maximalIdeal R).spanFinrank :=
  IsRegularLocalRing.spanFinrank_maximalIdeal.symm

section Quotient

/-- The quotient of a regular local ring by part of a regular system of parameters is regular, of
the expected dimension (Stacks 00NR): if `m` is generated by the `xᵢ` and the `yⱼ`, with
`#ι + #κ = dim R` elements in all, then `R/(xᵢ)` is regular of dimension `#κ`. -/
@[stacks 00NR]
theorem quotient_span_range {ι κ : Type*} [Finite ι] [Finite κ] (x : ι → R) (y : κ → R)
    (hmax : maximalIdeal R = Ideal.span (Set.range x ∪ Set.range y))
    (hdim : ((Nat.card ι + Nat.card κ : ℕ) : WithBot ℕ∞) = ringKrullDim R) :
    ∃ (_ : IsLocalRing (R ⧸ Ideal.span (Set.range x))),
      IsRegularLocalRing (R ⧸ Ideal.span (Set.range x)) ∧
      ringKrullDim (R ⧸ Ideal.span (Set.range x)) = Nat.card κ := by
  set I := Ideal.span (Set.range x)
  have hIm : I ≤ maximalIdeal R := hmax ▸ Ideal.span_mono Set.subset_union_left
  have : Nontrivial (R ⧸ I) :=
    Ideal.Quotient.nontrivial_iff.mpr (ne_top_of_le_ne_top (maximalIdeal.isMaximal R).ne_top hIm)
  have : IsLocalRing (R ⧸ I) :=
    IsLocalRing.of_surjective' (Ideal.Quotient.mk I) Ideal.Quotient.mk_surjective
  have hmaxI : maximalIdeal (R ⧸ I) = Ideal.span (Set.range (Ideal.Quotient.mk I ∘ y)) := by
    rw [← map_maximalIdeal_of_surjective (Ideal.Quotient.mk I) Ideal.Quotient.mk_surjective,
      hmax, Ideal.span_union, Ideal.map_sup, Ideal.map_span, Ideal.map_span,
      show Ideal.span (Ideal.Quotient.mk I '' Set.range x) = ⊥ by
        rw [Ideal.span_eq_bot]
        rintro _ ⟨_, ⟨i, rfl⟩, rfl⟩
        exact Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.subset_span ⟨i, rfl⟩),
      bot_sup_eq, ← Set.range_comp]
  have hspan : (maximalIdeal (R ⧸ I)).spanFinrank ≤ Nat.card κ := by
    rw [hmaxI]
    refine (Submodule.spanFinrank_span_le_ncard_of_finite (Set.finite_range _)).trans ?_
    rw [← Set.image_univ, ← Set.ncard_univ]
    exact Set.ncard_image_le (Set.toFinite _)
  have hI : I.spanFinrank ≤ Nat.card ι := by
    refine (Submodule.spanFinrank_span_le_ncard_of_finite (Set.finite_range _)).trans ?_
    rw [← Set.image_univ, ← Set.ncard_univ]
    exact Set.ncard_image_le (Set.toFinite _)
  have h1 := ringKrullDim_le_ringKrullDim_quotient_add_spanFinrank I
    (hIm.trans maximalIdeal_le_ringJacobson)
  obtain ⟨e, he⟩ : ∃ e : ℕ∞, ringKrullDim (R ⧸ I) = e :=
    (WithBot.ne_bot_iff_exists.mp (ne_bot_of_le_ne_bot WithBot.coe_ne_bot
      ringKrullDim_nonneg_of_nontrivial)).imp fun _ h ↦ h.symm
  have hdimI : (Nat.card κ : WithBot ℕ∞) ≤ ringKrullDim (R ⧸ I) := by
    rw [← hdim, he] at h1
    rw [he]
    have h2 : ((Nat.card ι + Nat.card κ : ℕ) : WithBot ℕ∞) ≤ (e : WithBot ℕ∞) + Nat.card ι :=
      h1.trans (by gcongr)
    have h3 : ((Nat.card κ : ℕ∞) + Nat.card ι : ℕ∞) ≤ e + Nat.card ι := by
      rw [add_comm]; exact_mod_cast h2
    exact_mod_cast (ENat.add_le_add_iff_right (ENat.natCast_ne_top _)).mp h3
  have hle := ringKrullDim_le_spanFinrank_maximalIdeal (R ⧸ I)
  refine ⟨this, IsRegularLocalRing.of_spanFinrank_maximalIdeal_le _
    ((Nat.cast_le.mpr hspan).trans hdimI), le_antisymm ?_ hdimI⟩
  exact hle.trans (by exact_mod_cast hspan)

/-- The quotient of a regular local ring by an element of `m \ m²` is regular of dimension
`dim R - 1`, and the element is a nonzerodivisor (Stacks 00NR). -/
theorem quotient_span_singleton {x : R} (hx : x ∈ maximalIdeal R)
    (hx2 : x ∉ maximalIdeal R ^ 2) :
    IsSMulRegular R x ∧ IsRegularLocalRing (R ⧸ Ideal.span {x}) ∧
      ringKrullDim (R ⧸ Ideal.span {x}) + 1 = ringKrullDim R :=
  SGA.SGA2.ExposeIII.regularLocal_parameter_quotient x hx hx2

end Quotient

section CohenMacaulay

/-- A regular system of parameters, i.e. a list of `dim R` generators of the maximal ideal, is a
regular sequence (Stacks 00NQ). -/
theorem isRegular_of_span_eq_maximalIdeal {rs : List R} (hnodup : rs.Nodup)
    (hspan : Ideal.ofList rs = maximalIdeal R) (hlen : (rs.length : WithBot ℕ∞) = ringKrullDim R) :
    IsRegular R rs :=
  SGA.SGA2.ExposeIII.regularLocal_isRegular_of_minimal_generating_list rs hnodup hspan hlen

/-- A regular local ring has a regular sequence of length `dim R` generating its maximal ideal. -/
theorem exists_isRegular_ofList_eq_maximalIdeal :
    ∃ rs : List R, (rs.length : WithBot ℕ∞) = ringKrullDim R ∧
      Ideal.ofList rs = maximalIdeal R ∧ IsRegular R rs := by
  obtain ⟨rs, hlen, hspan, hreg⟩ := SGA.SGA2.ExposeIII.regularLocal_exists_regular_parameters
    (R := R) _ ringKrullDim_eq_spanFinrank
  exact ⟨rs, hlen ▸ ringKrullDim_eq_spanFinrank.symm, hspan, hreg⟩

/-- A regular local ring is Cohen–Macaulay: its depth is its dimension (Stacks 00NQ). -/
@[stacks 00NQ]
theorem depth_eq_ringKrullDim : ((maximalIdeal R).depth R : WithBot ℕ∞) = ringKrullDim R := by
  refine le_antisymm depth_le_ringKrullDim ?_
  obtain ⟨rs, hlen, hspan, hreg⟩ := exists_isRegular_ofList_eq_maximalIdeal (R := R)
  rw [← hlen]
  have hmem : ∀ r ∈ rs, r ∈ maximalIdeal R := fun r hr ↦ hspan ▸ Ideal.subset_span hr
  exact_mod_cast Ideal.length_le_depth hmem hreg.1

end CohenMacaulay

section Homological

/-- Serre: every module over a regular local ring has projective dimension at most `dim R`
(Stacks 00OB, 065U). -/
@[stacks 00OB]
theorem hasProjectiveDimensionLE {n : ℕ} (hn : ringKrullDim R = n) (M : ModuleCat.{u} R) :
    HasProjectiveDimensionLE M n :=
  SGA.SGA2.ExposeV.regularLocal_hasProjectiveDimensionLE n hn M

/-- Serre: the residue field of a regular local ring has projective dimension exactly `dim R`. -/
theorem projectiveDimension_residueField {n : ℕ} (hn : ringKrullDim R = n) :
    projectiveDimension (ModuleCat.of R (ResidueField R)) = n :=
  SGA.SGA2.ExposeIV.regularLocal_residueField_projectiveDimension n hn

end Homological

end IsRegularLocalRing

section Serre

variable {R : Type u} [CommRing R] [IsLocalRing R] [IsNoetherianRing R]

/-- Serre's theorem: a noetherian local ring is regular iff its residue field has finite
projective dimension (Stacks 00OB). -/
@[stacks 00OB]
theorem isRegularLocalRing_iff_projectiveDimension_residueField_ne_top :
    IsRegularLocalRing R ↔ projectiveDimension (ModuleCat.of R (ResidueField R)) ≠ ⊤ :=
  SGA.SGA2.ExposeV.isRegularLocalRing_iff_residueField_projectiveDimension_ne_top

/-- Serre's theorem: a noetherian local ring is regular iff it has finite global dimension
(Stacks 00OB, 065U). -/
@[stacks 065U]
theorem isRegularLocalRing_iff_exists_hasProjectiveDimensionLE :
    IsRegularLocalRing R ↔ ∃ n : ℕ, ∀ M : ModuleCat.{u} R, HasProjectiveDimensionLE M n := by
  refine ⟨fun h ↦ ⟨_, IsRegularLocalRing.hasProjectiveDimensionLE
    IsRegularLocalRing.ringKrullDim_eq_spanFinrank⟩, fun ⟨n, hn⟩ ↦ ?_⟩
  have := hn (ModuleCat.of R (ResidueField R))
  exact SGA.SGA2.ExposeV.isRegularLocalRing_of_residueField_bound n

end Serre

namespace IsRegularLocalRing

variable {R : Type u} [CommRing R] [IsRegularLocalRing R]

/-- The localization of a regular local ring at a prime is regular (Stacks 00OE). -/
@[stacks 00OE]
instance localization_atPrime (p : Ideal R) [p.IsPrime] :
    IsRegularLocalRing (Localization.AtPrime p) :=
  SGA.SGA2.ExposeV.regularLocal_atPrime_isRegularLocalRing p

/-- A regular local ring is a regular ring (Stacks 00OE). -/
instance isRegularRing : IsRegularRing R :=
  ⟨fun p _ ↦ localization_atPrime p⟩

/-- Any localization of a regular local ring at a prime is regular (Stacks 00OE). -/
theorem of_isLocalization_atPrime (p : Ideal R) [p.IsPrime] (S : Type*) [CommRing S]
    [Algebra R S] [IsLocalization.AtPrime S p] : IsRegularLocalRing S :=
  of_ringEquiv (IsLocalization.algEquiv p.primeCompl (Localization.AtPrime p) S).toRingEquiv

/-- A regular local ring of dimension at most one is a principal ideal ring. -/
theorem isPrincipalIdealRing_of_ringKrullDim_le_one (h : ringKrullDim R ≤ 1) :
    IsPrincipalIdealRing R := by
  refine ((tfae_of_isNoetherianRing_of_isLocalRing_of_isDomain R).out 1 6).mpr ?_
  have := (iff_finrank_cotangentSpace R).mp inferInstance
  rw [← this] at h
  exact_mod_cast h

/-- A regular local ring of dimension one is a discrete valuation ring. -/
theorem isDiscreteValuationRing (h : ringKrullDim R = 1) : IsDiscreteValuationRing R := by
  rw [← IsLocalRing.finrank_CotangentSpace_eq_one_iff]
  have := (iff_finrank_cotangentSpace R).mp inferInstance
  rw [h] at this
  exact_mod_cast this

/-- A regular local ring of dimension at most one is integrally closed. -/
theorem isIntegrallyClosed_of_ringKrullDim_le_one (h : ringKrullDim R ≤ 1) :
    IsIntegrallyClosed R :=
  have := isPrincipalIdealRing_of_ringKrullDim_le_one h
  inferInstance

end IsRegularLocalRing
