/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.Foundations.Topology.SemilocallySimplyConnected
import Mathlib.Topology.Homotopy.Lifting
import Mathlib.Analysis.Convex.Contractible
import Mathlib.Topology.Algebra.Module.LocallyConvex
import Mathlib.Analysis.LocallyConvex.Basic
import Mathlib.Analysis.Normed.Module.Convex
import Mathlib.Topology.LocallyConstant.Basic

/-!
# The covering space associated with a functor on the fundamental groupoid

Let `X` be a locally path-connected, semilocally simply connected space and
`L : FundamentalGroupoid X ⥤ Type v` a functor (a "local system of sets"). The *total space*
`FundamentalGroupoid.TotalSpace L` is the set of pairs `⟨x, s⟩` with `x : X` and `s ∈ L x`,
topologized by the *sheets* `sheet L U x s = {⟨γ 1, L γ s⟩ | γ a path in U starting at x}` for
open `U ⊆ X`. We show:

* the projection `TotalSpace.proj L` to `X` is a covering map (`TotalSpace.isCoveringMap_proj`),
  evenly covered over every open, path-connected, relatively simply connected set;
* its monodromy is `L`: the lift of a path `γ` starting at `⟨x, s⟩` ends at `⟨γ 1, L γ s⟩`
  (`TotalSpace.monodromy_mk`, `TotalSpace.monodromyFunctorIso`);
* a natural transformation `L ⟶ L'` induces a continuous map of total spaces over `X`
  (`TotalSpace.map`).

This is the construction of the covering space associated with a set with an action of the
fundamental group (or groupoid), used in the classification of coverings.

## References

* [A. Hatcher, *Algebraic Topology*, §1.3][hatcher02]
-/

noncomputable section

open CategoryTheory Topology Set Filter

universe u v w

/-! ### The unit interval is contractible and locally path-connected

It is then simply connected by mathlib's instance `SimplyConnectedSpace.ofContractible`. -/

namespace unitInterval

instance : ContractibleSpace I :=
  (convex_Icc (0 : ℝ) 1).contractibleSpace ⟨0, by simp⟩

instance : LocallyPathConnectedSpace I :=
  (Topology.IsQuotientMap.of_inverse continuous_subtype_val continuous_projIcc
    (Set.projIcc_val zero_le_one)).locallyPathConnectedSpace

/-- The path `u ↦ u * t` from `0` to `t` in the unit interval. -/
def segPath (t : I) : Path (0 : I) t where
  toFun u := u * t
  continuous_toFun := by fun_prop
  source' := zero_mul t
  target' := one_mul t

end unitInterval

namespace FundamentalGroupoid

variable {X : Type u} [TopologicalSpace X]

variable (L : FundamentalGroupoid X ⥤ Type v)

/-- The total space of the covering associated with a functor `L` on the fundamental groupoid of
`X`: the pairs `⟨x, s⟩` with `x : X` and `s ∈ L x`. -/
@[ext]
structure TotalSpace : Type (max u v) where
  /-- The point `⟨x, s⟩` of the total space. -/
  mk ::
  /-- The projection from the total space to `X`. -/
  proj : X
  /-- The element of the fibre `L (proj e)`. -/
  snd : L.obj ⟨proj⟩

namespace TotalSpace

variable {L}

variable (L) in
/-- The sheet of `U` through `⟨x, s⟩`: the points `⟨γ 1, L γ s⟩` for the paths `γ` in `U`
starting at `x`. -/
def sheet (U : Set X) (x : X) (s : L.obj ⟨x⟩) : Set (TotalSpace L) :=
  {e | ∃ γ : Path x e.proj, range γ ⊆ U ∧ e.snd = L.map (fromPath (.mk γ)) s}

/-- The topology on the total space, generated by the sheets over open sets. -/
instance : TopologicalSpace (TotalSpace L) :=
  .generateFrom {S | ∃ (U : Set X) (x : X) (s : L.obj ⟨x⟩), IsOpen U ∧ S = sheet L U x s}

variable {U V : Set X} {x : X} {s : L.obj ⟨x⟩}

lemma mk_mem_sheet (hx : x ∈ U) : mk x s ∈ sheet L U x s :=
  ⟨Path.refl x, by rintro _ ⟨t, rfl⟩; exact hx, by
    change s = L.map (fromPath (.mk (Path.refl x))) s
    rw [fromPath_mk_refl, L.map_id]
    rfl⟩

lemma proj_mem_of_mem_sheet {e : TotalSpace L} (he : e ∈ sheet L U x s) : proj e ∈ U := by
  obtain ⟨γ, hγ, -⟩ := he
  exact hγ ⟨1, γ.target⟩

lemma sheet_mono (hUV : U ⊆ V) : sheet L U x s ⊆ sheet L V x s :=
  fun _ ⟨γ, hγ, he⟩ ↦ ⟨γ, hγ.trans hUV, he⟩

lemma sheet_subset_sheet (hVU : V ⊆ U) {e : TotalSpace L} (he : e ∈ sheet L U x s) :
    sheet L V e.proj e.snd ⊆ sheet L U x s := by
  obtain ⟨γ, hγ, he⟩ := he
  rintro e' ⟨β, hβ, he'⟩
  refine ⟨γ.trans β, ?_, ?_⟩
  · rw [Path.trans_range]
    exact union_subset hγ (hβ.trans hVU)
  · rw [he', he, fromPath_mk_trans, Functor.map_comp_apply]

lemma isOpen_sheet (hU : IsOpen U) : IsOpen (sheet L U x s) :=
  .basic _ ⟨U, x, s, hU, rfl⟩

variable (L) in
lemma isTopologicalBasis :
    TopologicalSpace.IsTopologicalBasis
      {S | ∃ (U : Set X) (x : X) (s : L.obj ⟨x⟩), IsOpen U ∧ S = sheet L U x s} where
  exists_subset_inter := by
    rintro _ ⟨U₁, x₁, s₁, hU₁, rfl⟩ _ ⟨U₂, x₂, s₂, hU₂, rfl⟩ e ⟨he₁, he₂⟩
    refine ⟨sheet L (U₁ ∩ U₂) e.proj e.snd, ⟨_, _, _, hU₁.inter hU₂, rfl⟩,
      mk_mem_sheet ⟨proj_mem_of_mem_sheet he₁, proj_mem_of_mem_sheet he₂⟩,
      subset_inter (sheet_subset_sheet inter_subset_left he₁)
        (sheet_subset_sheet inter_subset_right he₂)⟩
  sUnion_eq := eq_univ_of_forall fun e ↦
    ⟨_, ⟨univ, e.proj, e.snd, isOpen_univ, rfl⟩, mk_mem_sheet (mem_univ _)⟩
  eq_generateFrom := rfl

/-- The sheets through `e` over open neighbourhoods of `proj e` form a basis of neighbourhoods
of `e`. -/
lemma hasBasis_nhds (e : TotalSpace L) :
    (𝓝 e).HasBasis (fun U : Set X ↦ IsOpen U ∧ e.proj ∈ U) (fun U ↦ sheet L U e.proj e.snd) := by
  refine (isTopologicalBasis L).nhds_hasBasis.to_hasBasis ?_ ?_
  · rintro _ ⟨⟨U, x, s, hU, rfl⟩, he⟩
    exact ⟨U, ⟨hU, proj_mem_of_mem_sheet he⟩, sheet_subset_sheet subset_rfl he⟩
  · rintro U ⟨hU, he⟩
    exact ⟨_, ⟨⟨U, e.proj, e.snd, hU, rfl⟩, mk_mem_sheet he⟩, subset_rfl⟩

/-- In a locally path-connected, semilocally simply connected space, the sheets through `e` over
open, path-connected, relatively simply connected neighbourhoods of `proj e` form a basis of
neighbourhoods of `e`. -/
lemma hasBasis_nhds' [LocallyPathConnectedSpace X] [SemilocallySimplyConnectedSpace X]
    (e : TotalSpace L) :
    (𝓝 e).HasBasis
      (fun U : Set X ↦ IsOpen U ∧ e.proj ∈ U ∧ IsPathConnected U ∧ IsRelSimplyConnected U)
      (fun U ↦ sheet L U e.proj e.snd) := by
  refine (hasBasis_nhds e).to_hasBasis (fun U ⟨hU, he⟩ ↦ ?_) fun U hU ↦ ⟨U, ⟨hU.1, hU.2.1⟩,
    subset_rfl⟩
  obtain ⟨V, hVU, hV⟩ := exists_isRelSimplyConnected_subset (hU.mem_nhds he)
  exact ⟨V, hV, sheet_mono hVU⟩

lemma continuous_proj : Continuous (proj (L := L)) := by
  refine continuous_def.mpr fun W hW ↦ isOpen_iff_mem_nhds.mpr fun e he ↦ ?_
  exact (hasBasis_nhds e).mem_of_superset ⟨hW, he⟩ fun e' he' ↦ proj_mem_of_mem_sheet he'

/-! ### Local trivializations -/

section Trivialization

variable {V : Set X} (hV : IsPathConnected V) (hVs : IsRelSimplyConnected V)

/-- The homotopy class of a path from `y` to `z` in a path-connected, relatively simply
connected set `V`; it does not depend on the path (`transportIn_eq`). -/
noncomputable def transportIn {y z : X} (hy : y ∈ V) (hz : z ∈ V) :
    FundamentalGroupoid.mk y ⟶ FundamentalGroupoid.mk z :=
  fromPath (.mk (hV.joinedIn y hy z hz).somePath)

include hVs

lemma transportIn_eq {y z : X} (hy : y ∈ V) (hz : z ∈ V) {γ : Path y z} (hγ : range γ ⊆ V) :
    transportIn hV hy hz = fromPath (.mk γ) :=
  hVs.mk_eq (range_subset_iff.mpr (hV.joinedIn y hy z hz).somePath_mem) hγ

lemma transportIn_comp {y z w : X} (hy : y ∈ V) (hz : z ∈ V) (hw : w ∈ V) :
    transportIn hV hy hz ≫ transportIn hV hz hw = transportIn hV hy hw := by
  have h := range_subset_iff.mpr (hV.joinedIn y hy z hz).somePath_mem
  have h' := range_subset_iff.mpr (hV.joinedIn z hz w hw).somePath_mem
  rw [transportIn_eq hV hVs hy hw
    (γ := (hV.joinedIn y hy z hz).somePath.trans (hV.joinedIn z hz w hw).somePath)
    (by rw [Path.trans_range]; exact union_subset h h')]
  rfl

lemma transportIn_self {y : X} (hy : y ∈ V) : transportIn hV hy hy = 𝟙 _ := by
  rw [transportIn_eq hV hVs hy hy (γ := Path.refl y) (by simpa using hy)]
  rfl

lemma mem_sheet_iff_transportIn {y : X} (hy : y ∈ V) (t : L.obj ⟨y⟩) {e : TotalSpace L}
    (he : e.proj ∈ V) : e ∈ sheet L V y t ↔ e.snd = L.map (transportIn hV hy he) t := by
  constructor
  · rintro ⟨γ, hγ, he'⟩
    rw [he', transportIn_eq hV hVs hy he hγ]
  · intro he'
    exact ⟨_, range_subset_iff.mpr (hV.joinedIn y hy e.proj he).somePath_mem, he'⟩

variable (hVo : IsOpen V)
include hV hVo

/-- The function `e ↦ L (transport from proj e to x) e` on `proj ⁻¹' V` is locally constant. -/
lemma isLocallyConstant_transport {x : X} (hx : x ∈ V) :
    IsLocallyConstant fun e : proj (L := L) ⁻¹' V ↦ L.map (transportIn hV e.2 hx) e.1.snd := by
  refine (IsLocallyConstant.iff_eventually_eq _).mpr fun e ↦ ?_
  have hS : sheet L V e.1.proj e.1.snd ∈ 𝓝 e.1 :=
    (isOpen_sheet hVo).mem_nhds (mk_mem_sheet e.2)
  filter_upwards [continuous_subtype_val.continuousAt.preimage_mem_nhds hS]
    with e' (he' : e'.1 ∈ sheet L V e.1.proj e.1.snd)
  obtain ⟨β, hβ, he'⟩ := he'
  change L.map (transportIn hV e'.2 hx) e'.1.snd = L.map (transportIn hV e.2 hx) e.1.snd
  rw [he', ← Functor.map_comp_apply, ← transportIn_eq hV hVs e.2 e'.2 hβ,
    transportIn_comp hV hVs]


variable [LocallyPathConnectedSpace X]

/-- The section `y ↦ ⟨y, L (transport from x to y) s⟩` over `V` is continuous. -/
lemma continuous_section {x : X} (hx : x ∈ V) (s : L.obj ⟨x⟩) :
    Continuous fun y : V ↦ mk (L := L) y.1 (L.map (transportIn hV hx y.2) s) := by
  refine continuous_iff_continuousAt.mpr fun y ↦ ?_
  refine ((hasBasis_nhds _).tendsto_right_iff).mpr fun U ⟨hU, hyU⟩ ↦ ?_
  have hW : IsOpen (pathComponentIn (U ∩ V) y.1) := (hU.inter hVo).pathComponentIn _
  have hyW : y.1 ∈ pathComponentIn (U ∩ V) y.1 := mem_pathComponentIn_self ⟨hyU, y.2⟩
  filter_upwards [continuous_subtype_val.continuousAt.preimage_mem_nhds (hW.mem_nhds hyW)]
    with z (hz : JoinedIn (U ∩ V) y.1 z.1)
  refine ⟨hz.somePath, range_subset_iff.mpr fun t ↦ (hz.somePath_mem t).1, ?_⟩
  change L.map (transportIn hV hx z.2) s =
    L.map (fromPath (.mk hz.somePath)) (L.map (transportIn hV hx y.2) s)
  rw [← Functor.map_comp_apply, ← transportIn_eq hV hVs y.2 z.2
    (range_subset_iff.mpr fun t ↦ (hz.somePath_mem t).2), transportIn_comp hV hVs]

/-- The total space is evenly covered over an open, path-connected, relatively simply connected
set `V`, with fibre `L x` for any `x ∈ V`. -/
lemma isEvenlyCovered {x : X} (hx : x ∈ V) :
    letI : TopologicalSpace (L.obj ⟨x⟩) := ⊥
    IsEvenlyCovered (proj (L := L)) x (L.obj ⟨x⟩) := by
  let _ : TopologicalSpace (L.obj ⟨x⟩) := ⊥
  have : DiscreteTopology (L.obj ⟨x⟩) := ⟨rfl⟩
  refine ⟨this, V, hx, hVo, continuous_proj.isOpen_preimage V hVo, ?_⟩
  refine ⟨
    { toFun e := (⟨e.1.proj, e.2⟩, L.map (transportIn hV e.2 hx) e.1.snd)
      invFun p := ⟨mk p.1.1 (L.map (transportIn hV hx p.1.2) p.2), p.1.2⟩
      left_inv e := by
        obtain ⟨⟨y, t⟩, hy⟩ := e
        refine Subtype.ext (TotalSpace.ext rfl (heq_of_eq ?_))
        change L.map (transportIn hV hx hy) (L.map (transportIn hV hy hx) t) = t
        rw [← Functor.map_comp_apply, transportIn_comp hV hVs, transportIn_self hV hVs,
          L.map_id]
        rfl
      right_inv p := by
        obtain ⟨⟨y, hy⟩, t⟩ := p
        refine Prod.ext rfl ?_
        change L.map (transportIn hV hy hx) (L.map (transportIn hV hx hy) t) = t
        rw [← Functor.map_comp_apply, transportIn_comp hV hVs, transportIn_self hV hVs,
          L.map_id]
        rfl
      continuous_toFun :=
        ((continuous_proj.comp continuous_subtype_val).subtype_mk _).prodMk
          (isLocallyConstant_transport hV hVs hVo hx).continuous
      continuous_invFun := by
        refine Continuous.subtype_mk (continuous_prod_of_discrete_right.mpr fun t ↦ ?_) _
        exact continuous_section hV hVs hVo hx t }, fun e ↦ rfl⟩

end Trivialization

variable (L) in
/-- The projection from the total space of a functor on the fundamental groupoid of a locally
path-connected, semilocally simply connected space is a covering map. -/
theorem isCoveringMap_proj [LocallyPathConnectedSpace X] [SemilocallySimplyConnectedSpace X] :
    IsCoveringMap (proj (L := L)) := fun x ↦ by
  obtain ⟨V, -, hVo, hx, hV, hVs⟩ := exists_isRelSimplyConnected_subset (univ_mem : univ ∈ 𝓝 x)
  let _ : TopologicalSpace (L.obj ⟨x⟩) := ⊥
  exact (isEvenlyCovered hV hVs hVo hx).to_isEvenlyCovered_preimage

/-! ### Fibres and monodromy -/

variable (L) in
/-- The fibre of the total space over `x` is `L x`. -/
def fiberEquiv (x : X) : L.obj ⟨x⟩ ≃ proj (L := L) ⁻¹' {x} where
  toFun s := ⟨mk x s, rfl⟩
  invFun e := cast (congrArg (fun y ↦ L.obj ⟨y⟩) e.2) e.1.snd
  left_inv _ := rfl
  right_inv := by
    rintro ⟨⟨y, t⟩, rfl⟩
    rfl

@[simp]
lemma fiberEquiv_apply (x : X) (s : L.obj ⟨x⟩) : (fiberEquiv L x s : TotalSpace L) = mk x s :=
  rfl

variable [LocallyPathConnectedSpace X] [SemilocallySimplyConnectedSpace X]

open unitInterval in
/-- The monodromy of the total space: the lift of a path `γ` from `x` to `y` starting at
`⟨x, s⟩` ends at `⟨y, L γ s⟩`. -/
theorem monodromy_mk {x y : X} (γ : Path x y) (s : L.obj ⟨x⟩) :
    (isCoveringMap_proj L).monodromy (.mk γ) (fiberEquiv L x s) =
      fiberEquiv L y (L.map (fromPath (.mk γ)) s) := by
  obtain ⟨⟨f, hf⟩, rfl, rfl⟩ := γ
  let Γ (t : I) : TotalSpace L := mk (f t) (L.map (fromPath (.mk ((segPath t).map hf))) s)
  have hΓ : Continuous Γ := continuous_iff_continuousAt.mpr fun t₀ ↦ by
    refine ((hasBasis_nhds _).tendsto_right_iff).mpr fun U ⟨hU, ht₀U⟩ ↦ ?_
    have hW : f ⁻¹' U ∈ 𝓝 t₀ := hf.continuousAt.preimage_mem_nhds (hU.mem_nhds ht₀U)
    filter_upwards [pathComponentIn_mem_nhds hW] with t (ht : JoinedIn (f ⁻¹' U) t₀ t)
    refine ⟨ht.somePath.map hf, ?_, ?_⟩
    · rintro _ ⟨u, rfl⟩
      exact ht.somePath_mem u
    · change L.map (fromPath (.mk ((segPath t).map hf))) s =
        L.map (fromPath (.mk (ht.somePath.map hf)))
          (L.map (fromPath (.mk ((segPath t₀).map hf))) s)
      rw [← Functor.map_comp_apply, ← fromPath_mk_trans, ← Path.map_trans]
      congr 3
      exact Path.Homotopic.Quotient.eq.mpr
        ((SimplyConnectedSpace.paths_homotopic _ _).map ⟨f, hf⟩)
  have hΓ0 : Γ 0 = mk (f 0) s := by
    have : (segPath 0).map hf = Path.refl (f 0) := by
      ext u
      simp [segPath]
    change mk (f 0) (L.map (fromPath (.mk ((segPath 0).map hf))) s) = mk (f 0) s
    rw [this, fromPath_mk_refl, L.map_id]
    rfl
  have hΓ1 : (segPath 1).map hf = ⟨⟨f, hf⟩, rfl, rfl⟩ := by
    ext u
    simp [segPath]
  have hlift := ((isCoveringMap_proj L).eq_liftPath_iff' (Γ := ⟨Γ, hΓ⟩)
    (γ := ⟨f, hf⟩) (e := mk (f 0) s) rfl).mpr ⟨rfl, hΓ0⟩
  refine Subtype.ext ?_
  change (isCoveringMap_proj L).liftPath ⟨f, hf⟩ (mk (f 0) s) rfl 1 = _
  rw [← hlift]
  change mk (f 1) (L.map (fromPath (.mk ((segPath 1).map hf))) s) = _
  rw [hΓ1]
  rfl

/-- The monodromy functor of the total space is `L`. -/
def monodromyFunctorIso (L : FundamentalGroupoid X ⥤ Type u) :
    L ≅ (isCoveringMap_proj L).monodromyFunctor :=
  NatIso.ofComponents (fun x ↦ (fiberEquiv L x.as).toIso) fun {x y} γ ↦ by
    obtain ⟨x⟩ := x
    obtain ⟨y⟩ := y
    obtain ⟨γ⟩ := γ
    ext s
    exact (monodromy_mk γ s).symm

/-! ### Functoriality -/

variable {L' : FundamentalGroupoid X ⥤ Type v}

/-- The map of total spaces induced by a natural transformation. -/
def map (α : L ⟶ L') (e : TotalSpace L) : TotalSpace L' :=
  mk e.proj (α.app _ e.snd)

omit [LocallyPathConnectedSpace X] [SemilocallySimplyConnectedSpace X] in
@[simp] lemma proj_map (α : L ⟶ L') (e : TotalSpace L) : proj (map α e) = proj e := rfl

omit [LocallyPathConnectedSpace X] [SemilocallySimplyConnectedSpace X] in
lemma continuous_map (α : L ⟶ L') : Continuous (map α) := by
  refine continuous_iff_continuousAt.mpr fun e ↦
    ((hasBasis_nhds e).tendsto_iff (hasBasis_nhds _)).mpr fun U hU ↦
      ⟨U, hU, fun e' ⟨β, hβ, he'⟩ ↦ ⟨β, hβ, ?_⟩⟩
  change α.app _ e'.snd = L'.map _ (α.app _ e.snd)
  rw [he', NatTrans.naturality_apply]
  rfl

end TotalSpace

end FundamentalGroupoid

/-! ### Every covering is the total space of its monodromy functor -/

namespace IsCoveringMap

open FundamentalGroupoid

variable {E : Type w} {X : Type u} [TopologicalSpace E] [TopologicalSpace X] {p : E → X}
  (cov : IsCoveringMap p)
include cov

/-- The monodromy along a path in the target of a local inverse `φ` of `p` is given by `φ.symm`. -/
lemma monodromy_mk_eq_symm {φ : OpenPartialHomeomorph E X} (hφ : p = φ) {x y : X}
    (γ : Path x y) (hγ : range γ ⊆ φ.target) (e : p ⁻¹' {x}) (he : e.1 ∈ φ.source) :
    (cov.monodromy (.mk γ) e : E) = φ.symm y := by
  have hx : p e.1 = x := e.2
  have hc : Continuous fun t ↦ φ.symm (γ t) :=
    φ.continuousOn_symm.comp_continuous γ.continuous fun t ↦ hγ ⟨t, rfl⟩
  have hlift := (cov.eq_liftPath_iff' (Γ := ⟨_, hc⟩) (γ := γ.toContinuousMap) (e := e.1)
    (by rw [hx]; exact γ.source)).mpr
      ⟨funext fun t ↦ by simp [hφ, φ.right_inv (hγ ⟨t, rfl⟩)], by
        change φ.symm (γ 0) = e.1
        rw [γ.source, ← φ.left_inv he, ← hφ, hx]⟩
  change cov.liftPath γ.toContinuousMap e.1 _ 1 = _
  rw [← hlift]
  change φ.symm (γ 1) = _
  rw [γ.target]

/-- The monodromy commutes with maps of coverings. -/
lemma apply_monodromy {E' : Type*} [TopologicalSpace E'] {p' : E' → X} (cov' : IsCoveringMap p')
    (f : C(E, E')) (hf : ∀ e, p' (f e) = p e) {x y : X} (γ : Path.Homotopic.Quotient x y)
    (e : p ⁻¹' {x}) :
    f (cov.monodromy γ e) = (cov'.monodromy γ ⟨f e, (hf e).trans e.2⟩ : E') := by
  obtain ⟨γ⟩ := γ
  have hx : p e.1 = x := e.2
  have hlift := (cov'.eq_liftPath_iff' (Γ := f.comp (cov.liftPath γ.toContinuousMap e.1
    (by rw [hx]; exact γ.source))) (γ := γ.toContinuousMap) (e := f e.1)
    (by rw [hf, hx]; exact γ.source)).mpr
      ⟨funext fun t ↦ by
        simp only [Function.comp_apply, ContinuousMap.comp_apply, hf]
        exact congrFun (cov.liftPath_lifts _ _ _) t, by
        simp only [ContinuousMap.comp_apply, liftPath_zero]⟩
  change f (cov.liftPath γ.toContinuousMap e.1 _ 1) = cov'.liftPath γ.toContinuousMap (f e.1) _ 1
  rw [← hlift]
  rfl

variable [LocallyPathConnectedSpace X]

/-- A covering space `E` of a locally path-connected, semilocally simply connected space is
homeomorphic, over `X`, to the total space of its monodromy functor. -/
def homeomorphTotalSpace : E ≃ₜ TotalSpace cov.monodromyFunctor where
  toFun e := .mk (p e) ⟨e, rfl⟩
  invFun e := e.snd.1
  left_inv _ := rfl
  right_inv := by
    rintro ⟨y, ⟨e, he⟩⟩
    obtain rfl : p e = y := he
    rfl
  continuous_toFun := by
    refine continuous_iff_continuousAt.mpr fun e ↦
      ((TotalSpace.hasBasis_nhds _).tendsto_right_iff).mpr fun U ⟨hU, heU⟩ ↦ ?_
    obtain ⟨φ, heφ, hφ⟩ := cov.isLocalHomeomorph e
    have hpe : p e ∈ φ.target := hφ ▸ φ.map_source heφ
    have hW : IsOpen (pathComponentIn (U ∩ φ.target) (p e)) :=
      (hU.inter φ.open_target).pathComponentIn _
    have hO : φ.source ∩ p ⁻¹' pathComponentIn (U ∩ φ.target) (p e) ∈ 𝓝 e :=
      (φ.open_source.inter (hW.preimage cov.continuous)).mem_nhds
        ⟨heφ, mem_pathComponentIn_self ⟨heU, hpe⟩⟩
    filter_upwards [hO] with e' ⟨he'φ, (he' : JoinedIn (U ∩ φ.target) (p e) (p e'))⟩
    refine ⟨he'.somePath, range_subset_iff.mpr fun t ↦ (he'.somePath_mem t).1, ?_⟩
    refine Subtype.ext ?_
    change e' = (cov.monodromy (.mk he'.somePath) ⟨e, rfl⟩ : E)
    rw [cov.monodromy_mk_eq_symm hφ _ (range_subset_iff.mpr fun t ↦ (he'.somePath_mem t).2)
      _ heφ, hφ, φ.left_inv he'φ]
  continuous_invFun := by
    refine continuous_iff_continuousAt.mpr fun e ↦ ?_
    obtain ⟨y, ⟨e₀, he₀⟩⟩ := e
    change Tendsto _ _ (𝓝 e₀)
    refine (nhds_basis_opens e₀).tendsto_right_iff.mpr fun N ⟨he₀N, hN⟩ ↦ ?_
    obtain ⟨φ, he₀φ, hφ⟩ := cov.isLocalHomeomorph e₀
    have hU : IsOpen (φ '' (φ.source ∩ N)) := φ.isOpen_image_source_inter hN
    have hyU : y ∈ φ '' (φ.source ∩ N) := ⟨e₀, ⟨he₀φ, he₀N⟩, hφ ▸ he₀⟩
    filter_upwards [(TotalSpace.hasBasis_nhds _).mem_of_mem ⟨hU, hyU⟩]
    rintro ⟨y', e'⟩ ⟨β, hβ, he'⟩
    have hβ' : range β ⊆ φ.target := hβ.trans (by
      rintro _ ⟨e'', he'', rfl⟩
      exact φ.map_source he''.1)
    change e'.1 ∈ N
    rw [show e' = cov.monodromy (.mk β) ⟨e₀, he₀⟩ from he',
      cov.monodromy_mk_eq_symm hφ β hβ' _ he₀φ]
    obtain ⟨e'', he'', hy'⟩ := hβ ⟨1, β.target⟩
    rw [← hy', φ.left_inv he''.1]
    exact he''.2

@[simp]
lemma proj_homeomorphTotalSpace (e : E) : (cov.homeomorphTotalSpace e).proj = p e :=
  rfl

end IsCoveringMap

end
