/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import Mathlib.Analysis.Convex.Contractible
import SGA.Foundations.Topology.SurfaceLoopAround
import SGA.Foundations.Topology.VanKampenPushout

/-!
# Filling in a puncture

Let `Z` be a T1 space and `q ∈ Z` a point with a disc chart `φ : W ≃ₜ D(0, r)` (`W` open,
`φ q = 0`), such that `Z ∖ {q}` is path-connected. Then the inclusion `Z ∖ {q} → Z` induces a
surjection on `π₁` whose kernel is the normal subgroup generated by a loop around `q`: a
homomorphism `f : π₁(Z ∖ {q}, x) → G` factors (uniquely) through `π₁(Z, x)` as soon as it kills one
loop around `q`. Here a loop around `q` is a loop around `0` in the chart coordinate
(`FundamentalGroup.IsLoopAround` for `Complex.chartCoord φ`, conjugate to a small circle in the
chart).

* `Complex.chartCoord φ`: the chart as a function `Z → ℂ`, with the junk value `0` outside `W`;
* `FundamentalGroup.IsLoopAround.isConj`: two loops around `s` at the same base point are
  conjugate, when the coordinate has a continuous inverse over a punctured convex neighbourhood
  of `s`;
* `FundamentalGroup.map_fundamentalGroupMulEquivOfPath`: base point changes commute with maps;
* `FundamentalGroup.IsLoopAround.exists_radius_lt`, `FundamentalGroup.IsLoopAround.congr`: loops
  around `s` can be represented by arbitrarily small circles, so they only depend on the
  coordinate near `s`;
* `FundamentalGroup.surjective_mapSubtypeVal_compl_singleton`,
  `FundamentalGroup.existsUnique_hom_compl_singleton`: the statement above for `Z ∖ {q}` as a
  subspace;
* `FundamentalGroup.surjective_map_of_range_eq_compl_singleton`,
  `FundamentalGroup.existsUnique_hom_of_range_eq_compl_singleton`: the same for an open embedding
  `ι : Z' → Z` onto `Z ∖ {q}`.

The proof is the Seifert–van Kampen theorem for `Z = (Z ∖ {q}) ∪ W`: `W` is simply connected and
`π₁(W ∖ {q}) ≅ ℤ` is generated by a loop around `q`.

## References

* [A. Hatcher, *Algebraic Topology*, §1.2 (Proposition 1.26)][hatcher02]
-/

open Set Topology CategoryTheory Metric

noncomputable section

namespace Complex

variable {Z : Type*} [TopologicalSpace Z] {W : Set Z} {r : ℝ}

open Classical in
/-- A chart `φ : W ≃ₜ D(0, r)` of a space `Z`, as a function on all of `Z`, with the junk value
`0` outside `W` (a value that loops around the centre of the chart never see, since they live where
the coordinate is a nonzero number). -/
def chartCoord (φ : W ≃ₜ ball (0 : ℂ) r) (y : Z) : ℂ :=
  if h : y ∈ W then (φ ⟨y, h⟩ : ℂ) else 0

lemma chartCoord_of_mem (φ : W ≃ₜ ball (0 : ℂ) r) {y : Z} (hy : y ∈ W) :
    chartCoord φ y = φ ⟨y, hy⟩ := by
  simp [chartCoord, hy]

lemma chartCoord_of_notMem (φ : W ≃ₜ ball (0 : ℂ) r) {y : Z} (hy : y ∉ W) :
    chartCoord φ y = 0 := by
  simp [chartCoord, hy]

lemma chartCoord_mem_ball (φ : W ≃ₜ ball (0 : ℂ) r) (hr : 0 < r) (y : Z) :
    chartCoord φ y ∈ ball (0 : ℂ) r := by
  by_cases hy : y ∈ W
  · rw [chartCoord_of_mem φ hy]
    exact (φ _).2
  · rw [chartCoord_of_notMem φ hy]
    exact mem_ball_self hr

lemma mem_of_chartCoord_ne_zero (φ : W ≃ₜ ball (0 : ℂ) r) {y : Z} (hy : chartCoord φ y ≠ 0) :
    y ∈ W := by
  by_contra h
  exact hy (chartCoord_of_notMem φ h)

end Complex

namespace FundamentalGroup

open FundamentalGroupoid

/-- The class of a path, as an arrow of the fundamental groupoid. -/
local notation "⌈" γ "⌉" => FundamentalGroupoid.fromPath (Path.Homotopic.Quotient.mk γ)

section Naturality

variable {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y]

/-- **Base point changes commute with induced maps**: for `f : X → Y` and a path `p` from `x₀` to
`x₁`, transporting along `p` and then mapping by `f` is mapping by `f` and then transporting along
`f ∘ p`. -/
lemma map_fundamentalGroupMulEquivOfPath (f : C(X, Y)) {x₀ x₁ : X} (p : Path x₀ x₁)
    (α : FundamentalGroup X x₀) :
    map f x₁ (fundamentalGroupMulEquivOfPath p α) =
      fundamentalGroupMulEquivOfPath (p.map f.continuous) (map f x₀ α) := by
  change (FundamentalGroupoid.map f).map (Groupoid.inv ⌈p⌉ ≫ α ≫ ⌈p⌉) =
    Groupoid.inv ⌈p.map f.continuous⌉ ≫ (FundamentalGroupoid.map f).map α ≫ ⌈p.map f.continuous⌉
  rw [Groupoid.inv_eq_inv, Groupoid.inv_eq_inv, Functor.map_comp, Functor.map_comp,
    Functor.map_inv]
  rfl

end Naturality

section IsConj

variable {Y : Type*} [TopologicalSpace Y] {j : Y → ℂ} {C : Set ℂ} {s : ℂ}

/-- **Two loops around `s` at the same base point are conjugate**, provided the coordinate
`j : Y → ℂ` takes its values in a convex open set `C ∋ s` and has a continuous inverse
`ψ : C ∖ {s} → Y` over `C ∖ {s}` (`ψ (j y) = y` whenever `j y ≠ s`). Both loops are then images
under `ψ` of circles around `s`, which are conjugate in `π₁(C ∖ {s})` by a radial segment. -/
theorem IsLoopAround.isConj (hCc : Convex ℝ C) (hCo : IsOpen C) (hs : s ∈ C)
    (hjC : ∀ y, j y ∈ C) (ψ : C(↥(C \ {s}), Y))
    (hψ : ∀ (y : Y) (hy : j y ∈ C \ {s}), ψ ⟨j y, hy⟩ = y) {y : Y}
    {σ σ' : FundamentalGroup Y y} (h : IsLoopAround j s σ) (h' : IsLoopAround j s σ') :
    IsConj σ σ' := by
  obtain ⟨r₁, hr₁, κ₁, hκ₁, δ₁, rfl⟩ := h
  obtain ⟨r₂, hr₂, κ₂, hκ₂, δ₂, rfl⟩ := h'
  -- the closed punctured discs of the two loops lie in `C ∖ {s}`
  have hdisc (r : ℝ) (κ : C(↥(closedBall s r \ {s}), Y)) (hκ : ∀ z, j (κ z) = z) :
      closedBall s r \ {s} ⊆ C \ {s} := fun z hz ↦ by
    have := hjC (κ ⟨z, hz⟩)
    rw [hκ] at this
    exact ⟨this, hz.2⟩
  have hd₁ : closedBall s r₁ \ {s} ⊆ C \ {s} := hdisc r₁ κ₁ hκ₁
  have hd₂ : closedBall s r₂ \ {s} ⊆ C \ {s} := hdisc r₂ κ₂ hκ₂
  -- the inclusions of the punctured discs into `C ∖ {s}`
  obtain ⟨ι₁, hι₁⟩ : ∃ ι : C(↥(closedBall s r₁ \ {s}), ↥(C \ {s})), ∀ z, (ι z : ℂ) = z :=
    ⟨⟨fun z ↦ ⟨z, hd₁ z.2⟩, by fun_prop⟩, fun _ ↦ rfl⟩
  obtain ⟨ι₂, hι₂⟩ : ∃ ι : C(↥(closedBall s r₂ \ {s}), ↥(C \ {s})), ∀ z, (ι z : ℂ) = z :=
    ⟨⟨fun z ↦ ⟨z, hd₂ z.2⟩, by fun_prop⟩, fun _ ↦ rfl⟩
  -- the sections are `ψ` composed with the inclusions
  have hκψ (r : ℝ) (κ : C(↥(closedBall s r \ {s}), Y)) (hκ : ∀ z, j (κ z) = z)
      (ι : C(↥(closedBall s r \ {s}), ↥(C \ {s}))) (hι : ∀ z, (ι z : ℂ) = z) :
      κ = ψ.comp ι := by
    ext z
    have h1 : j (κ z) ∈ C \ {s} := by rw [hκ]; exact hdisc r κ hκ z.2
    calc κ z = ψ ⟨j (κ z), h1⟩ := (hψ _ h1).symm
      _ = ψ (ι z) := congrArg ψ (Subtype.ext ((hκ z).trans (hι z).symm))
  have e₁ := hκψ r₁ κ₁ hκ₁ ι₁ hι₁
  have e₂ := hκψ r₂ κ₂ hκ₂ ι₂ hι₂
  subst e₁ e₂
  let p₁ : ↥(closedBall s r₁ \ {s}) := ⟨s + r₁, Complex.add_ofReal_mem_closedBall_diff hr₁⟩
  let p₂ : ↥(closedBall s r₂ \ {s}) := ⟨s + r₂, Complex.add_ofReal_mem_closedBall_diff hr₂⟩
  let c₁ := (Complex.circlePath s r₁).codRestrict (Complex.range_circlePath_subset hr₁)
  let c₂ := (Complex.circlePath s r₂).codRestrict (Complex.range_circlePath_subset hr₂)
  -- the radial segment from `s + r₁` to `s + r₂`, in `C ∖ {s}`
  have hseg (t : unitInterval) : s + (((1 - (t : ℝ)) * r₁ + (t : ℝ) * r₂ : ℝ) : ℂ) ∈ C \ {s} := by
    have hpos : 0 < (1 - (t : ℝ)) * r₁ + (t : ℝ) * r₂ := by
      have h0 : 0 ≤ (1 - (t : ℝ)) := by linarith [t.2.2]
      rcases eq_or_lt_of_le t.2.1 with ht | ht
      · rw [← ht]; simpa using hr₁
      · have : 0 ≤ (1 - (t : ℝ)) * r₁ := mul_nonneg h0 hr₁.le
        nlinarith
    refine ⟨?_, ?_⟩
    · have h1 : s + (r₁ : ℂ) ∈ C := (hd₁ p₁.2).1
      have h2 : s + (r₂ : ℂ) ∈ C := (hd₂ p₂.2).1
      have := hCc h1 h2 (by linarith [t.2.2] : (0 : ℝ) ≤ 1 - t) t.2.1 (by ring)
      convert this using 1
      simp only [Complex.real_smul]
      push_cast
      ring
    · intro h
      have : (((1 - (t : ℝ)) * r₁ + (t : ℝ) * r₂ : ℝ) : ℂ) = 0 := by
        simpa using congrArg (· - s) (mem_singleton_iff.mp h)
      exact hpos.ne' (by exact_mod_cast this)
  let ε : Path (ι₁ p₁) (ι₂ p₂) :=
    { toFun t := ⟨_, hseg t⟩
      continuous_toFun := by fun_prop
      source' := by ext; simp [hι₁, p₁]
      target' := by ext; simp [hι₂, p₂] }
  -- in `C ∖ {s}`, the circle of radius `r₁` and the conjugate of the circle of radius `r₂` are
  -- two loops around `s` at `s + r₁`, hence equal
  have l₁ : IsLoopAround (Subtype.val : ↥(C \ {s}) → ℂ) s
      (Path.Homotopic.Quotient.mk (((Path.refl (ι₁ p₁)).trans (c₁.map ι₁.continuous)).trans
        (Path.refl (ι₁ p₁)).symm) : FundamentalGroup _ (ι₁ p₁)) :=
    ⟨r₁, hr₁, ι₁, hι₁, Path.refl _, rfl⟩
  have l₂ : IsLoopAround (Subtype.val : ↥(C \ {s}) → ℂ) s
      (Path.Homotopic.Quotient.mk ((ε.trans (c₂.map ι₂.continuous)).trans ε.symm) :
        FundamentalGroup _ (ι₁ p₁)) :=
    ⟨r₂, hr₂, ι₂, hι₂, ε, rfl⟩
  have heq := IsLoopAround.eq hCc hCo hs IsEmbedding.subtypeVal Subtype.range_coe l₁ l₂
  -- push to `Y` by `ψ`
  have hmap := congrArg (FundamentalGroupoid.map ψ).map heq
  change ⌈(((Path.refl (ι₁ p₁)).trans (c₁.map ι₁.continuous)).trans
        (Path.refl (ι₁ p₁)).symm).map ψ.continuous⌉ =
    ⌈((ε.trans (c₂.map ι₂.continuous)).trans ε.symm).map ψ.continuous⌉ at hmap
  have hmap' : ⌈c₁.map (ψ.comp ι₁).continuous⌉ = ⌈ε.map ψ.continuous⌉ ≫
      ⌈c₂.map (ψ.comp ι₂).continuous⌉ ≫ inv ⌈ε.map ψ.continuous⌉ := by
    rw [Path.map_trans, Path.map_trans, Path.map_trans, Path.map_trans, ← Path.map_symm,
      ← Path.map_symm, Path.map_map, Path.map_map] at hmap
    have hrefl (a : ↥(C \ {s})) : (Path.refl a).map ψ.continuous = Path.refl (ψ a) := rfl
    simp only [hrefl, fromPath_mk_trans, fromPath_mk_symm, fromPath_mk_refl] at hmap
    simp only [FundamentalGroupoid.fromPath] at hmap
    simp only [Category.id_comp, IsIso.inv_id, Category.assoc] at hmap
    erw [Category.comp_id] at hmap
    exact hmap
  rw [isConj_iff]
  refine ⟨⌈δ₁⌉ ≫ ⌈ε.map ψ.continuous⌉ ≫ inv ⌈δ₂⌉, ?_⟩
  change Groupoid.inv (⌈δ₁⌉ ≫ ⌈ε.map ψ.continuous⌉ ≫ inv ⌈δ₂⌉) ≫
    ⌈(δ₁.trans (c₁.map (ψ.comp ι₁).continuous)).trans δ₁.symm⌉ ≫
      (⌈δ₁⌉ ≫ ⌈ε.map ψ.continuous⌉ ≫ inv ⌈δ₂⌉) =
    ⌈(δ₂.trans (c₂.map (ψ.comp ι₂).continuous)).trans δ₂.symm⌉
  rw [Groupoid.inv_eq_inv]
  simp only [fromPath_mk_trans, fromPath_mk_symm, hmap', Category.assoc, IsIso.inv_comp,
    IsIso.inv_inv, IsIso.inv_hom_id_assoc]

end IsConj


section Shrinking

variable {Y : Type*} [TopologicalSpace Y] {j j' : Y → ℂ} {s : ℂ}

/-- The radial clamp `D(s, 2r) ∖ {s} → D̄(s, r) ∖ {s}`. -/
private def clamp (s : ℂ) {r : ℝ} (hr : 0 < r) :
    C(↥(ball s (2 * r) \ {s}), ↥(closedBall s r \ {s})) where
  toFun z := ⟨s + ((min ‖(z : ℂ) - s‖ r / ‖(z : ℂ) - s‖ : ℝ) : ℂ) * ((z : ℂ) - s), by
    have hz : (z : ℂ) - s ≠ 0 := sub_ne_zero.mpr z.2.2
    have hn : 0 < ‖(z : ℂ) - s‖ := norm_pos_iff.mpr hz
    refine ⟨?_, ?_⟩
    · rw [mem_closedBall, dist_eq_norm, add_sub_cancel_left, norm_mul, Complex.norm_real,
        Real.norm_eq_abs, abs_of_nonneg (div_nonneg (le_min hn.le hr.le) hn.le),
        div_mul_cancel₀ _ hn.ne']
      exact min_le_right _ _
    · intro h
      have h' : ((min ‖(z : ℂ) - s‖ r / ‖(z : ℂ) - s‖ : ℝ) : ℂ) * ((z : ℂ) - s) = 0 := by
        simpa using congrArg (· - s) (mem_singleton_iff.mp h)
      rcases mul_eq_zero.mp h' with h1 | h1
      · have : min ‖(z : ℂ) - s‖ r / ‖(z : ℂ) - s‖ = 0 := by exact_mod_cast h1
        rw [div_eq_zero_iff] at this
        rcases this with h2 | h2
        · exact (lt_min hn hr).ne' h2
        · exact hn.ne' h2
      · exact hz h1⟩
  continuous_toFun := by
    refine Continuous.subtype_mk ?_ _
    have hn : ∀ z : ↥(ball s (2 * r) \ {s}), ‖(z : ℂ) - s‖ ≠ 0 := fun z ↦
      norm_ne_zero_iff.mpr (sub_ne_zero.mpr z.2.2)
    fun_prop (disch := exact hn _)

private lemma clamp_of_mem {r : ℝ} (hr : 0 < r) (z : ↥(ball s (2 * r) \ {s}))
    (hz : ‖(z : ℂ) - s‖ ≤ r) : (clamp s hr z : ℂ) = z := by
  have hn : 0 < ‖(z : ℂ) - s‖ := norm_pos_iff.mpr (sub_ne_zero.mpr z.2.2)
  change s + ((min ‖(z : ℂ) - s‖ r / ‖(z : ℂ) - s‖ : ℝ) : ℂ) * ((z : ℂ) - s) = z
  rw [min_eq_left hz, div_self hn.ne']
  simp


/-- A loop around `s` has representatives with arbitrarily small circles. -/
theorem IsLoopAround.exists_radius_lt {y : Y} {σ : FundamentalGroup Y y}
    (h : IsLoopAround j s σ) {ρ : ℝ} (hρ : 0 < ρ) :
    ∃ (r : ℝ) (hr : 0 < r) (_ : r < ρ) (κ : C(↥(closedBall s r \ {s}), Y)) (_ : ∀ z, j (κ z) = z)
      (δ : Path y (κ ⟨s + r, Complex.add_ofReal_mem_closedBall_diff hr⟩)),
      σ = Path.Homotopic.Quotient.mk
        ((δ.trans (((Complex.circlePath s r).codRestrict (Complex.range_circlePath_subset hr)).map
          κ.continuous)).trans δ.symm) := by
  obtain ⟨r, hr, κ, hκ, δ, rfl⟩ := h
  set r' := min (r / 2) (ρ / 2) with hr'_def
  have hr' : 0 < r' := lt_min (half_pos hr) (half_pos hρ)
  have hr'r : r' ≤ r := (min_le_left _ _).trans (half_le_self hr.le)
  have hr'ρ : r' < ρ := (min_le_right _ _).trans_lt (half_lt_self hρ)
  have hsub (t : ℝ) (ht : 0 < t) (htr : t ≤ r) : closedBall s t \ {s} ⊆ ball s (2 * r) \ {s} :=
    fun z hz ↦ ⟨by
      rw [mem_ball]
      exact (mem_closedBall.mp hz.1).trans_lt (by linarith), hz.2⟩
  let incl : C(↥(closedBall s r \ {s}), ↥(ball s (2 * r) \ {s})) :=
    ⟨fun z ↦ ⟨z, hsub r hr le_rfl z.2⟩, by fun_prop⟩
  let incl' : C(↥(closedBall s r' \ {s}), ↥(ball s (2 * r) \ {s})) :=
    ⟨fun z ↦ ⟨z, hsub r' hr' hr'r z.2⟩, by fun_prop⟩
  obtain ⟨K, hK⟩ : ∃ K : C(↥(ball s (2 * r) \ {s}), Y), ∀ z, K (incl z) = κ z :=
    ⟨κ.comp (clamp s hr), fun z ↦ by
      change κ (clamp s hr (incl z)) = κ z
      congr 1
      exact Subtype.ext (clamp_of_mem hr _ (by
        have := mem_closedBall.mp z.2.1
        rwa [dist_eq_norm] at this))⟩
  have hκK : κ = K.comp incl := by
    ext z
    exact (hK z).symm
  subst hκK
  let p : ↥(closedBall s r \ {s}) := ⟨s + r, Complex.add_ofReal_mem_closedBall_diff hr⟩
  let p' : ↥(closedBall s r' \ {s}) := ⟨s + r', Complex.add_ofReal_mem_closedBall_diff hr'⟩
  let c := (Complex.circlePath s r).codRestrict (Complex.range_circlePath_subset hr)
  let c' := (Complex.circlePath s r').codRestrict (Complex.range_circlePath_subset hr')
  -- the radial segment from `s + r` to `s + r'`
  have hseg (t : unitInterval) :
      s + (((1 - (t : ℝ)) * r + (t : ℝ) * r' : ℝ) : ℂ) ∈ ball s (2 * r) \ {s} := by
    have h0 : 0 ≤ (1 - (t : ℝ)) := by linarith [t.2.2]
    have hpos : 0 < (1 - (t : ℝ)) * r + (t : ℝ) * r' := by
      rcases eq_or_lt_of_le t.2.1 with ht | ht
      · rw [← ht]; simpa using hr
      · have : 0 ≤ (1 - (t : ℝ)) * r := mul_nonneg h0 hr.le
        nlinarith
    have hle : (1 - (t : ℝ)) * r + (t : ℝ) * r' ≤ r := by nlinarith [t.2.1, t.2.2]
    refine ⟨?_, ?_⟩
    · rw [mem_ball, dist_eq_norm, add_sub_cancel_left, Complex.norm_real, Real.norm_eq_abs,
        abs_of_pos hpos]
      linarith
    · intro h
      have : (((1 - (t : ℝ)) * r + (t : ℝ) * r' : ℝ) : ℂ) = 0 := by
        simpa using congrArg (· - s) (mem_singleton_iff.mp h)
      exact hpos.ne' (by exact_mod_cast this)
  let ε : Path (incl p) (incl' p') :=
    { toFun t := ⟨_, hseg t⟩
      continuous_toFun := by fun_prop
      source' := by ext; simp [incl, p]
      target' := by ext; simp [incl', p'] }
  have l₁ : IsLoopAround (Subtype.val : ↥(ball s (2 * r) \ {s}) → ℂ) s
      (Path.Homotopic.Quotient.mk (((Path.refl (incl p)).trans (c.map incl.continuous)).trans
        (Path.refl (incl p)).symm) : FundamentalGroup _ (incl p)) :=
    ⟨r, hr, incl, fun _ ↦ rfl, Path.refl _, rfl⟩
  have l₂ : IsLoopAround (Subtype.val : ↥(ball s (2 * r) \ {s}) → ℂ) s
      (Path.Homotopic.Quotient.mk ((ε.trans (c'.map incl'.continuous)).trans ε.symm) :
        FundamentalGroup _ (incl p)) :=
    ⟨r', hr', incl', fun _ ↦ rfl, ε, rfl⟩
  have hs2 : s ∈ ball s (2 * r) := mem_ball_self (by linarith)
  have heq := IsLoopAround.eq (convex_ball s (2 * r)) isOpen_ball hs2 IsEmbedding.subtypeVal
    Subtype.range_coe l₁ l₂
  have hmap := congrArg (FundamentalGroupoid.map K).map heq
  change ⌈(((Path.refl (incl p)).trans (c.map incl.continuous)).trans
        (Path.refl (incl p)).symm).map K.continuous⌉ =
    ⌈((ε.trans (c'.map incl'.continuous)).trans ε.symm).map K.continuous⌉ at hmap
  have hmap' : ⌈c.map (K.comp incl).continuous⌉ = ⌈ε.map K.continuous⌉ ≫
      ⌈c'.map (K.comp incl').continuous⌉ ≫ inv ⌈ε.map K.continuous⌉ := by
    rw [Path.map_trans, Path.map_trans, Path.map_trans, Path.map_trans, ← Path.map_symm,
      ← Path.map_symm, Path.map_map, Path.map_map] at hmap
    have hrefl (a : ↥(ball s (2 * r) \ {s})) : (Path.refl a).map K.continuous = Path.refl (K a) :=
      rfl
    simp only [hrefl, fromPath_mk_trans, fromPath_mk_symm, fromPath_mk_refl] at hmap
    simp only [FundamentalGroupoid.fromPath] at hmap
    simp only [Category.id_comp, IsIso.inv_id, Category.assoc] at hmap
    erw [Category.comp_id] at hmap
    exact hmap
  refine ⟨r', hr', hr'ρ, K.comp incl', fun z ↦ ?_, δ.trans (ε.map K.continuous), ?_⟩
  · exact hκ ⟨z, mem_closedBall.mpr ((mem_closedBall.mp z.2.1).trans hr'r), z.2.2⟩
  · change ⌈(δ.trans (c.map (K.comp incl).continuous)).trans δ.symm⌉ =
      ⌈((δ.trans (ε.map K.continuous)).trans (c'.map (K.comp incl').continuous)).trans
        (δ.trans (ε.map K.continuous)).symm⌉
    rw [Path.trans_symm]
    simp only [fromPath_mk_trans, fromPath_mk_symm, hmap', Category.assoc]


/-- **Loops around `s` only depend on the coordinate near `s`**: if `j'` agrees with `j` at the
points where `j` lies in a punctured disc `D(s, ρ) ∖ {s}`, then every loop around `s` for `j` is a
loop around `s` for `j'`. -/
theorem IsLoopAround.congr {ρ : ℝ} (hρ : 0 < ρ) (hjj' : ∀ y, j y ∈ ball s ρ \ {s} → j' y = j y)
    {y : Y} {σ : FundamentalGroup Y y} (h : IsLoopAround j s σ) : IsLoopAround j' s σ := by
  obtain ⟨r, hr, hrρ, κ, hκ, δ, rfl⟩ := h.exists_radius_lt hρ
  refine ⟨r, hr, κ, fun z ↦ ?_, δ, rfl⟩
  rw [hjj' _ (by
    rw [hκ]
    exact ⟨mem_ball.mpr ((mem_closedBall.mp z.2.1).trans_lt hrρ), z.2.2⟩), hκ]


end Shrinking

section Filling

variable {Z : Type} [TopologicalSpace Z] {q : Z} {W : Set Z} {r : ℝ}

open Complex

/-- The radius of a nonempty chart is positive. -/
private lemma pos_of_chart (hqW : q ∈ W) (φ : W ≃ₜ ball (0 : ℂ) r) : 0 < r :=
  pos_of_mem_ball (φ ⟨q, hqW⟩).2

/-- The chart coordinate on `(Z ∖ {q}) ∩ W`, an open embedding onto `D(0, r) ∖ {0}`. -/
private def interCoord (φ : W ≃ₜ ball (0 : ℂ) r) (y : ↥(({q}ᶜ : Set Z) ∩ W)) : ℂ :=
  φ ⟨y, y.2.2⟩

private lemma interCoord_eq (φ : W ≃ₜ ball (0 : ℂ) r) (y : ↥(({q}ᶜ : Set Z) ∩ W)) :
    interCoord φ y = chartCoord φ (y : Z) :=
  (chartCoord_of_mem φ y.2.2).symm

private lemma isOpenEmbedding_interCoord (hqW : q ∈ W)
    (φ : W ≃ₜ ball (0 : ℂ) r) (hφ : (φ ⟨q, hqW⟩ : ℂ) = 0) :
    IsOpenEmbedding (interCoord (q := q) φ) ∧
      range (interCoord (q := q) φ) = ball (0 : ℂ) r \ {0} := by
  have hrange : range (interCoord (q := q) φ) = ball (0 : ℂ) r \ {0} := by
    ext z
    constructor
    · rintro ⟨y, rfl⟩
      refine ⟨(φ _).2, fun h ↦ y.2.1 ?_⟩
      have : φ ⟨y, y.2.2⟩ = φ ⟨q, hqW⟩ := Subtype.ext (by rw [hφ]; exact h)
      exact congrArg Subtype.val (φ.injective this)
    · rintro ⟨hz, hz0⟩
      refine ⟨⟨φ.symm ⟨z, hz⟩, fun h ↦ hz0 ?_, (φ.symm ⟨z, hz⟩).2⟩, ?_⟩
      · have h2 := congrArg (fun w ↦ (φ w : ℂ))
          (Subtype.ext h : φ.symm ⟨z, hz⟩ = ⟨q, hqW⟩)
        simp only [Homeomorph.apply_symm_apply] at h2
        exact h2.trans hφ
      · simp [interCoord]
  have hemb : IsEmbedding (interCoord (q := q) φ) := by
    have h1 : IsEmbedding (fun y : ↥(({q}ᶜ : Set Z) ∩ W) ↦ (⟨y, y.2.2⟩ : W)) :=
      IsEmbedding.inclusion inter_subset_right
    exact IsEmbedding.subtypeVal.comp (φ.isEmbedding.comp h1)
  refine ⟨⟨hemb, ?_⟩, hrange⟩
  rw [hrange]
  exact isOpen_ball.sdiff isClosed_singleton

/-- `(Z ∖ {q}) ∩ W` is path-connected (it is a punctured disc). -/
private lemma isPathConnected_inter (hqW : q ∈ W)
    (φ : W ≃ₜ ball (0 : ℂ) r) (hφ : (φ ⟨q, hqW⟩ : ℂ) = 0) :
    IsPathConnected (({q}ᶜ : Set Z) ∩ W) := by
  obtain ⟨h, hr⟩ := isOpenEmbedding_interCoord hqW φ hφ
  rw [isPathConnected_iff_pathConnectedSpace]
  exact pathConnectedSpace_of_range_eq_diff_singleton (convex_ball 0 r) isOpen_ball
    (mem_ball_self (pos_of_chart hqW φ)) h.isEmbedding hr

/-- The chart domain is simply connected. -/
private lemma simplyConnectedSpace_chart (hqW : q ∈ W) (φ : W ≃ₜ ball (0 : ℂ) r) :
    SimplyConnectedSpace W := by
  have : ContractibleSpace (ball (0 : ℂ) r) :=
    (convex_ball 0 r).contractibleSpace (nonempty_ball.mpr (pos_of_chart hqW φ))
  exact φ.toHomotopyEquiv.simplyConnectedSpace

/-- The inverse of the chart over `D(0, r) ∖ {0}`, with values in `Z ∖ {q}`. -/
private def chartInv (hqW : q ∈ W) (φ : W ≃ₜ ball (0 : ℂ) r) (hφ : (φ ⟨q, hqW⟩ : ℂ) = 0) :
    C(↥(ball (0 : ℂ) r \ {0}), ({q}ᶜ : Set Z)) where
  toFun z := ⟨φ.symm ⟨z, z.2.1⟩, fun h ↦ z.2.2 (by
    have h2 := congrArg (fun w ↦ (φ w : ℂ))
      (Subtype.ext h : φ.symm ⟨z, z.2.1⟩ = ⟨q, hqW⟩)
    simp only [Homeomorph.apply_symm_apply] at h2
    exact h2.trans hφ)⟩
  continuous_toFun := by fun_prop

private lemma chartCoord_chartInv (hqW : q ∈ W) (φ : W ≃ₜ ball (0 : ℂ) r)
    (hφ : (φ ⟨q, hqW⟩ : ℂ) = 0) (z : ↥(ball (0 : ℂ) r \ {0})) :
    chartCoord φ (chartInv hqW φ hφ z : Z) = z := by
  change chartCoord φ (φ.symm ⟨z, z.2.1⟩ : Z) = z
  rw [chartCoord_of_mem φ (φ.symm ⟨z, z.2.1⟩).2]
  simp

/-- Two loops around `q` (in the chart coordinate) at the same base point of `Z ∖ {q}` are
conjugate. -/
theorem isConj_of_isLoopAround_chartCoord (hqW : q ∈ W) (φ : W ≃ₜ ball (0 : ℂ) r)
    (hφ : (φ ⟨q, hqW⟩ : ℂ) = 0) {y : ({q}ᶜ : Set Z)} {σ σ' : FundamentalGroup ({q}ᶜ : Set Z) y}
    (h : IsLoopAround (fun y : ({q}ᶜ : Set Z) ↦ chartCoord φ y) 0 σ)
    (h' : IsLoopAround (fun y : ({q}ᶜ : Set Z) ↦ chartCoord φ y) 0 σ') : IsConj σ σ' := by
  refine IsLoopAround.isConj (convex_ball 0 r) isOpen_ball (mem_ball_self (pos_of_chart hqW φ))
    (fun y ↦ chartCoord_mem_ball φ (pos_of_chart hqW φ) _) (chartInv hqW φ hφ) (fun y hy ↦ ?_) h h'
  have hyW : (y : Z) ∈ W := mem_of_chartCoord_ne_zero φ hy.2
  ext
  change (φ.symm ⟨chartCoord φ y, hy.1⟩ : Z) = y
  have : (⟨chartCoord φ y, hy.1⟩ : ball (0 : ℂ) r) = φ ⟨y, hyW⟩ :=
    Subtype.ext (chartCoord_of_mem φ hyW)
  rw [this, φ.symm_apply_apply]

/-- A point of `(Z ∖ {q}) ∩ W`. -/
private lemma exists_mem_inter (hqW : q ∈ W) (φ : W ≃ₜ ball (0 : ℂ) r)
    (hφ : (φ ⟨q, hqW⟩ : ℂ) = 0) : ∃ x₁, x₁ ∈ ({q}ᶜ : Set Z) ∩ W := by
  have hr := pos_of_chart hqW φ
  have hz : ((r / 2 : ℝ) : ℂ) ∈ ball (0 : ℂ) r \ {0} := by
    refine ⟨?_, ?_⟩
    · rw [mem_ball_zero_iff, Complex.norm_real, Real.norm_eq_abs, abs_of_pos (half_pos hr)]
      exact half_lt_self hr
    · simpa using hr.ne'
  exact ⟨chartInv hqW φ hφ ⟨_, hz⟩, (chartInv hqW φ hφ ⟨_, hz⟩).2,
    (φ.symm ⟨_, hz.1⟩).2⟩

/-- **Filling in a puncture: surjectivity.** If `q` has a disc chart `φ : W ≃ₜ D(0, r)` and
`Z ∖ {q}` is path-connected, then `π₁(Z ∖ {q}, x) → π₁(Z, x)` is surjective. -/
theorem surjective_mapSubtypeVal_compl_singleton [T1Space Z] (hW : IsOpen W) (hqW : q ∈ W)
    (φ : W ≃ₜ ball (0 : ℂ) r) (hφ : (φ ⟨q, hqW⟩ : ℂ) = 0)
    (hZ : IsPathConnected ({q}ᶜ : Set Z)) {x : Z} (hx : x ∈ ({q}ᶜ : Set Z)) :
    Function.Surjective (mapSubtypeVal hx) := by
  have hU : IsOpen ({q}ᶜ : Set Z) := isClosed_singleton.isOpen_compl
  have hUV : ({q}ᶜ : Set Z) ∪ W = univ := by
    ext y
    by_cases hy : y = q
    · simp [hy, hqW]
    · simp [hy]
  have : SimplyConnectedSpace W := simplyConnectedSpace_chart hqW φ
  obtain ⟨x₁, hx₁U, hx₁V⟩ := exists_mem_inter hqW φ hφ
  have htop := range_map_subtypeVal_sup_eq_top hU hW hUV hZ
    (isPathConnected_iff_pathConnectedSpace.mpr inferInstance) (isPathConnected_inter hqW φ hφ)
    hx₁U hx₁V
  have hbot : (mapSubtypeVal hx₁V).range = ⊥ := by
    rw [MonoidHom.range_eq_bot_iff]
    ext α
    rw [Subsingleton.elim α 1, map_one]
    rfl
  rw [hbot, sup_bot_eq] at htop
  -- transport from `x₁` to `x`
  obtain ⟨γ, hγ⟩ := hZ.joinedIn x hx x₁ hx₁U
  let γU : Path (⟨x, hx⟩ : ({q}ᶜ : Set Z)) ⟨x₁, hx₁U⟩ :=
    γ.codRestrict (by rintro _ ⟨t, rfl⟩; exact hγ t)
  intro α
  have hmem : fundamentalGroupMulEquivOfPath (γU.map continuous_subtype_val) α ∈
      (mapSubtypeVal hx₁U).range := htop ▸ Subgroup.mem_top _
  obtain ⟨β, hβ⟩ := hmem
  refine ⟨(fundamentalGroupMulEquivOfPath γU).symm β, ?_⟩
  apply (fundamentalGroupMulEquivOfPath (γU.map continuous_subtype_val)).injective
  rw [← hβ]
  simp only [mapSubtypeVal]
  rw [← map_fundamentalGroupMulEquivOfPath ⟨Subtype.val, continuous_subtype_val⟩ γU,
    MulEquiv.apply_symm_apply]

/-- **Filling in a puncture.** Let `Z` be a T1 space, `q ∈ Z` a point with a disc chart
`φ : W ≃ₜ D(0, r)` (`W` open, `φ q = 0`), and suppose `Z ∖ {q}` is path-connected. Let `σ` be a
loop around `q` at `x ∈ Z ∖ {q}` (a loop around `0` in the chart coordinate,
`FundamentalGroup.IsLoopAround`). Then every homomorphism `f : π₁(Z ∖ {q}, x) → G` with
`f σ = 1` factors uniquely through `π₁(Z ∖ {q}, x) → π₁(Z, x)`. Together with
`surjective_mapSubtypeVal_compl_singleton`: `π₁(Z, x) = π₁(Z ∖ {q}, x) / ⟨⟨σ⟩⟩`. -/
theorem existsUnique_hom_compl_singleton [T1Space Z] (hW : IsOpen W) (hqW : q ∈ W)
    (φ : W ≃ₜ ball (0 : ℂ) r) (hφ : (φ ⟨q, hqW⟩ : ℂ) = 0)
    (hZ : IsPathConnected ({q}ᶜ : Set Z)) {x : Z} (hx : x ∈ ({q}ᶜ : Set Z))
    {σ : FundamentalGroup ({q}ᶜ : Set Z) ⟨x, hx⟩}
    (hσ : IsLoopAround (fun y : ({q}ᶜ : Set Z) ↦ chartCoord φ y) 0 σ)
    {G : Type*} [Group G] (f : FundamentalGroup ({q}ᶜ : Set Z) ⟨x, hx⟩ →* G) (hf : f σ = 1) :
    ∃! f' : FundamentalGroup Z x →* G, f'.comp (mapSubtypeVal hx) = f := by
  have hsurj := surjective_mapSubtypeVal_compl_singleton hW hqW φ hφ hZ hx
  refine existsUnique_of_exists_of_unique ?_ fun f₁ f₂ h₁ h₂ ↦ ?_
  swap
  · ext α
    obtain ⟨β, rfl⟩ := hsurj α
    rw [← MonoidHom.comp_apply, h₁, ← MonoidHom.comp_apply, h₂]
  have hU : IsOpen ({q}ᶜ : Set Z) := isClosed_singleton.isOpen_compl
  have hUV : ({q}ᶜ : Set Z) ∪ W = univ := by
    ext y
    by_cases hy : y = q
    · simp [hy, hqW]
    · simp [hy]
  have : SimplyConnectedSpace W := simplyConnectedSpace_chart hqW φ
  obtain ⟨x₁, hx₁U, hx₁V⟩ := exists_mem_inter hqW φ hφ
  obtain ⟨γ, hγ⟩ := hZ.joinedIn x hx x₁ hx₁U
  let γU : Path (⟨x, hx⟩ : ({q}ᶜ : Set Z)) ⟨x₁, hx₁U⟩ :=
    γ.codRestrict (by rintro _ ⟨t, rfl⟩; exact hγ t)
  -- the homomorphism at the base point `x₁`
  let f₁ : FundamentalGroup ({q}ᶜ : Set Z) ⟨x₁, hx₁U⟩ →* G :=
    f.comp (fundamentalGroupMulEquivOfPath γU).symm.toMonoidHom
  have hσ₁ : IsLoopAround (fun y : ({q}ᶜ : Set Z) ↦ chartCoord φ y) 0
      (fundamentalGroupMulEquivOfPath γU σ) := hσ.conj γU
  have hf₁ : f₁ (fundamentalGroupMulEquivOfPath γU σ) = 1 := by
    simp [f₁, hf]
  -- it kills `π₁((Z ∖ {q}) ∩ W)`, which is generated by a loop around `q`
  obtain ⟨hemb, hrange⟩ := isOpenEmbedding_interCoord hqW φ hφ
  obtain ⟨b, hb⟩ := Complex.exists_freeGroupBasis_fundamentalGroup_of_isOpenEmbedding
    (S := {0}) (convex_ball 0 r) isOpen_ball
    (by
      intro z hz
      rw [Finset.coe_singleton, mem_singleton_iff] at hz
      subst hz
      exact mem_ball_self (pos_of_chart hqW φ)) hemb (by simpa using hrange)
    (⟨x₁, hx₁U, hx₁V⟩ : ↥(({q}ᶜ : Set Z) ∩ W))
  have hcompat : f₁.comp (map (ContinuousMap.inclusion inter_subset_left) ⟨x₁, hx₁U, hx₁V⟩) =
      (1 : FundamentalGroup W ⟨x₁, hx₁V⟩ →* G).comp
        (map (ContinuousMap.inclusion inter_subset_right) ⟨x₁, hx₁U, hx₁V⟩) := by
    refine b.ext_hom _ _ fun i ↦ ?_
    have hi : i = ⟨0, Finset.mem_singleton_self 0⟩ := Subtype.ext (Finset.mem_singleton.mp i.2)
    subst hi
    let L : FundamentalGroup ({q}ᶜ : Set Z) ⟨x₁, hx₁U⟩ :=
      map (ContinuousMap.inclusion inter_subset_left) ⟨x₁, hx₁U, hx₁V⟩
        (b ⟨0, Finset.mem_singleton_self 0⟩)
    change f₁ L = 1
    have hloop : IsLoopAround (fun y : ({q}ᶜ : Set Z) ↦ chartCoord φ y) 0 L :=
      (hb ⟨0, Finset.mem_singleton_self 0⟩).map (ContinuousMap.inclusion inter_subset_left)
        fun y ↦ (interCoord_eq φ y).symm
    obtain ⟨c, hc⟩ := isConj_iff.mp
      (isConj_of_isLoopAround_chartCoord hqW φ hφ hloop hσ₁)
    have h2 := congrArg f₁ hc
    rw [hf₁, map_mul, map_mul, map_inv, mul_inv_eq_one, mul_eq_left] at h2
    exact h2
  obtain ⟨g, ⟨hgU, -⟩, -⟩ := existsUnique_hom_of_union hU hW hUV hZ
    (isPathConnected_iff_pathConnectedSpace.mpr inferInstance) (isPathConnected_inter hqW φ hφ)
    hx₁U hx₁V f₁ 1 hcompat
  refine ⟨g.comp (fundamentalGroupMulEquivOfPath (γU.map continuous_subtype_val)).toMonoidHom, ?_⟩
  ext α
  change g (fundamentalGroupMulEquivOfPath (γU.map continuous_subtype_val)
    (map ⟨Subtype.val, continuous_subtype_val⟩ _ α)) = f α
  rw [← map_fundamentalGroupMulEquivOfPath ⟨Subtype.val, continuous_subtype_val⟩ γU]
  change (g.comp (mapSubtypeVal hx₁U)) _ = _
  rw [hgU]
  simp [f₁]

end Filling



section Trivial

variable {Z Z' : Type} [TopologicalSpace Z] [TopologicalSpace Z'] {W : Set Z} {r : ℝ}

open Complex

/-- **A loop around a point with a disc chart dies once the point is filled in**: if
`φ : W ≃ₜ D(0, r)` is a chart of `Z` and `σ ∈ π₁(Z', x)` is a loop around `0` in the coordinate
`chartCoord φ ∘ ι` (for `ι : Z' → Z` continuous), then `ι` maps `σ` to `1`: the small circle lies in
the simply connected `W`. -/
theorem map_eq_one_of_isLoopAround_chartCoord (φ : W ≃ₜ ball (0 : ℂ) r) (ι : C(Z', Z)) {x : Z'}
    {σ : FundamentalGroup Z' x} (hσ : IsLoopAround (fun y ↦ chartCoord φ (ι y)) 0 σ) :
    map ι x σ = 1 := by
  obtain ⟨ρ, hρ, κ, hκ, δ, rfl⟩ := hσ
  set c := ((Complex.circlePath 0 ρ).codRestrict (Complex.range_circlePath_subset hρ)).map
    κ.continuous
  have hW (t : unitInterval) : ι (c t) ∈ W := by
    refine mem_of_chartCoord_ne_zero φ ?_
    have h := hκ (((Complex.circlePath 0 ρ).codRestrict (Complex.range_circlePath_subset hρ)) t)
    simp only at h
    change chartCoord φ (ι (κ _)) ≠ 0
    rw [h]
    exact (((Complex.circlePath 0 ρ).codRestrict (Complex.range_circlePath_subset hρ)) t).2.2
  have : Nonempty W := ⟨⟨_, hW 0⟩⟩
  have hr : 0 < r := pos_of_mem_ball (φ (Classical.arbitrary W)).2
  have : ContractibleSpace (ball (0 : ℂ) r) :=
    (convex_ball 0 r).contractibleSpace (nonempty_ball.mpr hr)
  have : SimplyConnectedSpace W := φ.toHomotopyEquiv.simplyConnectedSpace
  let cW := (c.map ι.continuous).codRestrict (by rintro _ ⟨t, rfl⟩; exact hW t)
  have h1 : ⌈c.map ι.continuous⌉ = 𝟙 _ := by
    change (FundamentalGroupoid.map ⟨Subtype.val, continuous_subtype_val⟩).map ⌈cW⌉ = _
    have : ⌈cW⌉ = 𝟙 _ := Subsingleton.elim (α := Path.Homotopic.Quotient _ _) _ _
    rw [this, CategoryTheory.Functor.map_id]
    rfl
  change (FundamentalGroupoid.map ι).map ((⌈δ⌉ ≫ ⌈c⌉) ≫ Groupoid.inv ⌈δ⌉) = 𝟙 _
  rw [Groupoid.inv_eq_inv, CategoryTheory.Functor.map_comp, CategoryTheory.Functor.map_comp,
    CategoryTheory.Functor.map_inv]
  change (⌈δ.map ι.continuous⌉ ≫ ⌈c.map ι.continuous⌉) ≫ inv ⌈δ.map ι.continuous⌉ = 𝟙 _
  rw [h1, Category.comp_id, IsIso.hom_inv_id]

/-- **Filling in a puncture keeps path-connectedness**: if `ι : Z' → Z` is a continuous map onto
`Z ∖ {q}` with `Z'` path-connected and `q` has a disc chart, then `Z` is path-connected. -/
theorem pathConnectedSpace_of_range_eq_compl_singleton {q : Z} (ι : C(Z', Z))
    (hιr : range ι = {q}ᶜ) (hqW : q ∈ W) (φ : W ≃ₜ ball (0 : ℂ) r)
    (hφ : (φ ⟨q, hqW⟩ : ℂ) = 0) [PathConnectedSpace Z'] : PathConnectedSpace Z := by
  have h1 : IsPathConnected (range ι) := isPathConnected_range ι.continuous
  have hr : 0 < r := pos_of_mem_ball (φ ⟨q, hqW⟩).2
  have : PathConnectedSpace (ball (0 : ℂ) r) :=
    isPathConnected_iff_pathConnectedSpace.mp ((convex_ball 0 r).isPathConnected
      (nonempty_ball.mpr hr))
  have : PathConnectedSpace W := φ.symm.surjective.pathConnectedSpace φ.symm.continuous
  have h2 : IsPathConnected W := isPathConnected_iff_pathConnectedSpace.mpr this
  obtain ⟨x₁, hx₁U, hx₁V⟩ := exists_mem_inter hqW φ hφ
  have h3 := h1.union h2 ⟨x₁, hιr ▸ hx₁U, hx₁V⟩
  have hU : range ι ∪ W = univ := by
    rw [hιr]
    ext y
    by_cases hy : y = q
    · simp [hy, hqW]
    · simp [hy]
  rw [hU] at h3
  exact pathConnectedSpace_iff_univ.mpr h3

end Trivial

section Embedding

variable {Z Z' : Type} [TopologicalSpace Z] [TopologicalSpace Z'] [T1Space Z] {q : Z}
  {W : Set Z} {r : ℝ} {ι : Z' → Z}

open Complex

/-- `Z' ≅ Z ∖ {q}` through an embedding `ι` onto `Z ∖ {q}`. -/
private def complHomeomorph (hι : IsEmbedding ι) (hιr : range ι = {q}ᶜ) :
    Z' ≃ₜ ({q}ᶜ : Set Z) :=
  hι.toHomeomorph.trans (Homeomorph.setCongr hιr)

omit [T1Space Z] in
private lemma map_eq_comp (hι : IsEmbedding ι) (hιr : range ι = {q}ᶜ) (x : Z') :
    map ⟨ι, hι.continuous⟩ x = (mapSubtypeVal (complHomeomorph hι hιr x).2).comp
      (mapHomeomorph (complHomeomorph hι hιr) x).toMonoidHom := by
  ext α
  induction α using Path.Homotopic.Quotient.ind with | mk γ => ?_
  rfl

/-- **Filling in a puncture: surjectivity**, for an embedding `ι : Z' → Z` onto `Z ∖ {q}` (see
`surjective_mapSubtypeVal_compl_singleton`). -/
theorem surjective_map_of_range_eq_compl_singleton (hι : IsEmbedding ι)
    (hιr : range ι = {q}ᶜ) (hW : IsOpen W) (hqW : q ∈ W) (φ : W ≃ₜ ball (0 : ℂ) r)
    (hφ : (φ ⟨q, hqW⟩ : ℂ) = 0) [PathConnectedSpace Z'] (x : Z') :
    Function.Surjective (map ⟨ι, hι.continuous⟩ x) := by
  set e := complHomeomorph hι hιr
  have hZ : IsPathConnected ({q}ᶜ : Set Z) :=
    isPathConnected_iff_pathConnectedSpace.mpr (e.surjective.pathConnectedSpace e.continuous)
  have h := (surjective_mapSubtypeVal_compl_singleton hW hqW φ hφ hZ (e x).2).comp
    (mapHomeomorph e x).surjective
  intro β
  obtain ⟨α, hα⟩ := h β
  exact ⟨α, (DFunLike.congr_fun (map_eq_comp hι hιr x) α).trans hα⟩

/-- **Filling in a puncture**, for an embedding `ι : Z' → Z` onto `Z ∖ {q}`, `Z` a T1 space and
`Z'` path-connected (see `existsUnique_hom_compl_singleton`): if `q` has a disc chart
`φ : W ≃ₜ D(0, r)` (`W` open, `φ q = 0`) and `σ ∈ π₁(Z', x)` is a loop around `q` (a loop around
`0` in the coordinate `chartCoord φ ∘ ι`), then every homomorphism `f : π₁(Z', x) → G` with
`f σ = 1` factors uniquely through `π₁(Z', x) → π₁(Z, ι x)`. -/
theorem existsUnique_hom_of_range_eq_compl_singleton (hι : IsEmbedding ι)
    (hιr : range ι = {q}ᶜ) (hW : IsOpen W) (hqW : q ∈ W) (φ : W ≃ₜ ball (0 : ℂ) r)
    (hφ : (φ ⟨q, hqW⟩ : ℂ) = 0) [PathConnectedSpace Z'] (x : Z') {σ : FundamentalGroup Z' x}
    (hσ : IsLoopAround (fun y ↦ chartCoord φ (ι y)) 0 σ) {G : Type*} [Group G]
    (f : FundamentalGroup Z' x →* G) (hf : f σ = 1) :
    ∃! f' : FundamentalGroup Z (ι x) →* G, f'.comp (map ⟨ι, hι.continuous⟩ x) = f := by
  set e := complHomeomorph hι hιr
  have hZ : IsPathConnected ({q}ᶜ : Set Z) :=
    isPathConnected_iff_pathConnectedSpace.mpr (e.surjective.pathConnectedSpace e.continuous)
  have hσ₀ : IsLoopAround (fun y : ({q}ᶜ : Set Z) ↦ chartCoord φ y) 0
      (mapHomeomorph e x σ) :=
    hσ.map ⟨e, e.continuous⟩ fun y ↦ rfl
  obtain ⟨f', hf', huniq⟩ := existsUnique_hom_compl_singleton hW hqW φ hφ hZ (e x).2 hσ₀
    (f.comp (mapHomeomorph e x).symm.toMonoidHom) (by
      simp only [MonoidHom.comp_apply, MulEquiv.coe_toMonoidHom, MulEquiv.symm_apply_apply, hf])
  refine ⟨f', ?_, fun f'' hf'' ↦ huniq f'' ?_⟩
  · ext α
    have h1 := DFunLike.congr_fun hf' (mapHomeomorph e x α)
    simp only [MonoidHom.comp_apply, MulEquiv.coe_toMonoidHom, MulEquiv.symm_apply_apply] at h1
    exact (congrArg f' (DFunLike.congr_fun (map_eq_comp hι hιr x) α)).trans h1
  · ext β
    have h1 := DFunLike.congr_fun hf'' ((mapHomeomorph e x).symm β)
    have h2 : map ⟨ι, hι.continuous⟩ x ((mapHomeomorph e x).symm β) =
        mapSubtypeVal (e x).2 β := by
      refine (DFunLike.congr_fun (map_eq_comp hι hιr x) _).trans ?_
      change mapSubtypeVal (e x).2 (mapHomeomorph e x ((mapHomeomorph e x).symm β)) = _
      rw [MulEquiv.apply_symm_apply]
    simp only [MonoidHom.comp_apply, MulEquiv.coe_toMonoidHom] at h1 ⊢
    exact (congrArg f'' h2).symm.trans h1

end Embedding

end FundamentalGroup
