/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import Mathlib.GroupTheory.FreeGroup.IsFreeGroup
import SGA.Foundations.Topology.PuncturedDisc
import SGA.Foundations.Topology.VanKampenPushout

/-!
# The fundamental group of the plane minus finitely many points

Let `C ⊆ ℂ` be open and convex (e.g. `ℂ` or a disc) and `S ⊆ C` finite. Then `π₁(C ∖ S, x)` is
free, with a basis `(σ_s)_{s ∈ S}` in which `σ_s` is a loop around `s`: conjugate, by a path, to a
small circle around `s` (`Complex.exists_freeGroupBasis_fundamentalGroup_diff`). This is the
genus `0` case of the presentation of the fundamental group of a compact Riemann surface minus
`n` points, the topological input of SGA 1 XIII.2.12 in characteristic `0` for the projective
line (`ℂ ∖ S = ℙ¹(ℂ) ∖ (S ∪ {∞})`); no classification of surfaces is needed. Not done here: that
for a suitable order of the basis, `(∏ σ_s)⁻¹` is a loop around `∞` (which would give the
presentation `⟨σ₁, …, σ_n | σ₁ ⋯ σ_n = 1⟩` with every generator a loop around a puncture).

The statement is made for any space `X` with an open embedding `j : X → ℂ` onto `C ∖ S`, and loops
around `s` are taken relative to `j` (`FundamentalGroup.IsLoopAround`), so that it is stable under
restriction to open subsets.

## Proof

Induction on the number of points. For no point, `C` is convex, hence simply connected. For one
point `s`, `exp⁻¹(C - s)` is simply connected (it deformation retracts onto a half-plane), so
`Complex.fundamentalGroupMulEquivInt` gives `π₁(C ∖ {s}) ≅ ℤ`, generated by a circle around `s`.
For two points or more, a line with points of `S` on both sides and none in a strip around it cuts
`C` into two convex open pieces with fewer points that meet in a convex strip; van Kampen
(`FundamentalGroup.existsUnique_hom_of_union`) glues the free bases.

## References

* [A. Hatcher, *Algebraic Topology*, §1.2][hatcher02]
* [SGA 1, Exposé XIII, 2.12][grothendieck1971]
-/

open Set Topology CategoryTheory Metric Real

namespace Complex

/-- The circle of center `s` and radius `r`, run once counterclockwise from `s + r`. -/
noncomputable def circlePath (s : ℂ) (r : ℝ) : Path (s + r) (s + r) where
  toFun t := s + r * Complex.exp (2 * π * Complex.I * (t : ℝ))
  continuous_toFun := by fun_prop
  source' := by simp
  target' := by simp

lemma circlePath_apply (s : ℂ) (r : ℝ) (t : unitInterval) :
    circlePath s r t = s + r * Complex.exp (2 * π * Complex.I * (t : ℝ)) :=
  rfl

lemma add_ofReal_mem_closedBall_diff {s : ℂ} {r : ℝ} (hr : 0 < r) :
    s + r ∈ closedBall s r \ {s} :=
  ⟨by simp [dist_eq_norm, abs_of_pos hr], by simpa using hr.ne'⟩

lemma range_circlePath_subset {s : ℂ} {r : ℝ} (hr : 0 < r) :
    range (circlePath s r) ⊆ closedBall s r \ {s} := by
  rintro _ ⟨t, rfl⟩
  have hn : ‖Complex.exp (2 * π * Complex.I * ((t : ℝ) : ℂ))‖ = 1 := by
    rw [Complex.norm_exp]
    simp
  refine ⟨?_, ?_⟩
  · rw [mem_closedBall, circlePath_apply, dist_eq_norm, add_sub_cancel_left, norm_mul, hn,
      mul_one, Complex.norm_real, Real.norm_of_nonneg hr.le]
  · rw [mem_singleton_iff, circlePath_apply, add_eq_left]
    exact mul_ne_zero (by exact_mod_cast hr.ne') (Complex.exp_ne_zero _)

end Complex

namespace FundamentalGroup

variable {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y]

/-- A homeomorphism induces an isomorphism of fundamental groups. -/
noncomputable def mapHomeomorph (e : X ≃ₜ Y) (x : X) :
    FundamentalGroup X x ≃* FundamentalGroup Y (e x) where
  toFun := map ⟨e, e.continuous⟩ x
  invFun := mapOfEq ⟨e.symm, e.symm.continuous⟩ (e.symm_apply_apply x)
  left_inv γ := by
    induction γ using Path.Homotopic.Quotient.ind with | mk γ => ?_
    rw [mapOfEq_apply]
    refine congrArg Path.Homotopic.Quotient.mk (Path.ext (funext fun t ↦ ?_))
    exact e.symm_apply_apply (γ t)
  right_inv γ := by
    induction γ using Path.Homotopic.Quotient.ind with | mk γ => ?_
    change map ⟨e, e.continuous⟩ x (mapOfEq ⟨e.symm, e.symm.continuous⟩ _ _) = _
    rw [mapOfEq_apply]
    refine congrArg Path.Homotopic.Quotient.mk (Path.ext (funext fun t ↦ ?_))
    exact e.apply_symm_apply (γ t)
  map_mul' := map_mul _

@[simp] lemma mapHomeomorph_apply (e : X ≃ₜ Y) (x : X) (γ : FundamentalGroup X x) :
    mapHomeomorph e x γ = map ⟨e, e.continuous⟩ x γ :=
  rfl

variable (j : X → ℂ)

/-- `σ ∈ π₁(X, x)` is a *loop around `s`* (relative to `j : X → ℂ`): it is conjugate, by a path
`δ`, to a small circle around `s`, namely the image of the circle of center `s` and radius `r`
under a continuous section `κ` of `j` over the punctured closed disc `D̄(s, r) ∖ {s}`. If `j` is an
embedding with image `C ∖ S` and `s ∈ S`, the closed disc meets `S` in `s` only. -/
def IsLoopAround (s : ℂ) {x : X} (σ : FundamentalGroup X x) : Prop :=
  ∃ (r : ℝ) (hr : 0 < r) (κ : C(↥(closedBall s r \ {s}), X)) (_ : ∀ z, j (κ z) = z)
    (δ : Path x (κ ⟨s + r, Complex.add_ofReal_mem_closedBall_diff hr⟩)),
    σ = Path.Homotopic.Quotient.mk
      ((δ.trans (((Complex.circlePath s r).codRestrict (Complex.range_circlePath_subset hr)).map
        κ.continuous)).trans δ.symm)

variable {j}

/-- Loops around `s` are mapped to loops around `s` by maps compatible with the maps to `ℂ`. -/
lemma IsLoopAround.map {j' : Y → ℂ} (f : C(X, Y)) (hf : ∀ x, j' (f x) = j x) {s : ℂ} {x : X}
    {σ : FundamentalGroup X x} (h : IsLoopAround j s σ) : IsLoopAround j' s (map f x σ) := by
  obtain ⟨r, hr, κ, hκ, δ, rfl⟩ := h
  refine ⟨r, hr, f.comp κ, fun z ↦ (hf _).trans (hκ z), δ.map f.continuous, ?_⟩
  change Path.Homotopic.Quotient.mk (((δ.trans _).trans δ.symm).map f.continuous) = _
  rw [Path.map_trans, Path.map_trans, Path.map_symm]
  rfl

/-- Loops around `s` are transported to loops around `s` by changes of base point. -/
lemma IsLoopAround.conj {s : ℂ} {x x' : X} (p : Path x x') {σ : FundamentalGroup X x}
    (h : IsLoopAround j s σ) : IsLoopAround j s (fundamentalGroupMulEquivOfPath p σ) := by
  obtain ⟨r, hr, κ, hκ, δ, rfl⟩ := h
  refine ⟨r, hr, κ, hκ, p.symm.trans δ, ?_⟩
  set c := ((Complex.circlePath s r).codRestrict
    (Complex.range_circlePath_subset hr)).map κ.continuous
  change FundamentalGroupoid.fromPath (Path.Homotopic.Quotient.mk p.symm) ≫
      FundamentalGroupoid.fromPath (Path.Homotopic.Quotient.mk ((δ.trans c).trans δ.symm)) ≫
        FundamentalGroupoid.fromPath (Path.Homotopic.Quotient.mk p) =
    FundamentalGroupoid.fromPath
      (Path.Homotopic.Quotient.mk (((p.symm.trans δ).trans c).trans (p.symm.trans δ).symm))
  rw [Path.trans_symm, Path.symm_symm]
  simp only [FundamentalGroupoid.fromPath_mk_trans, Category.assoc]


/-- A family `σ` in a group `G` with the universal property of a free basis (for groups in
`Type`) is preserved by isomorphisms. -/
private lemma existsUnique_lift_mulEquiv {G G' ι : Type*} [Group G] [Group G'] (ψ : G ≃* G')
    {σ : ι → G} (h : ∀ {H : Type} [Group H] (g : ι → H), ∃! φ : G →* H, ∀ i, φ (σ i) = g i)
    {H : Type} [Group H] (g : ι → H) : ∃! φ : G' →* H, ∀ i, φ (ψ (σ i)) = g i := by
  obtain ⟨φ, hφ, huniq⟩ := h g
  refine ⟨φ.comp ψ.symm.toMonoidHom, fun i ↦ by simpa using hφ i, fun φ' hφ' ↦ ?_⟩
  have := huniq (φ'.comp ψ.toMonoidHom) hφ'
  ext a
  simpa using DFunLike.congr_fun this (ψ.symm a)

end FundamentalGroup

namespace Complex

open FundamentalGroup

section Induction

/-- The property proved by induction on the number of points: `X` is path-connected and at every
base point `π₁(X, x)` is free on loops around the points of `S` (relative to `j`). -/
private def Good (S : Finset ℂ) (X : Type) [TopologicalSpace X] (j : X → ℂ) : Prop :=
  PathConnectedSpace X ∧ ∀ x : X, ∃ σ : S → FundamentalGroup X x,
    (∀ s : S, IsLoopAround j (s : ℂ) (σ s)) ∧
    ∀ {H : Type} [Group H] (g : S → H), ∃! φ : FundamentalGroup X x →* H, ∀ s, φ (σ s) = g s

variable {S : Finset ℂ} {X : Type} [TopologicalSpace X] {j : X → ℂ}

/-- It is enough to check `Good` at one base point. -/
private lemma good_of_exists (hX : PathConnectedSpace X) (x₀ : X)
    (h : ∃ σ : S → FundamentalGroup X x₀, (∀ s : S, IsLoopAround j (s : ℂ) (σ s)) ∧
      ∀ {H : Type} [Group H] (g : S → H), ∃! φ : FundamentalGroup X x₀ →* H,
        ∀ s, φ (σ s) = g s) :
    Good S X j := by
  refine ⟨hX, fun x ↦ ?_⟩
  obtain ⟨σ, hσ, hfree⟩ := h
  let p : Path x₀ x := PathConnectedSpace.somePath x₀ x
  exact ⟨fun s ↦ fundamentalGroupMulEquivOfPath p (σ s), fun s ↦ (hσ s).conj p,
    fun g ↦ existsUnique_lift_mulEquiv (fundamentalGroupMulEquivOfPath p) hfree g⟩

/-- `Good` is transported along homeomorphisms compatible with the maps to `ℂ`. -/
private lemma good_of_homeomorph {X' : Type} [TopologicalSpace X'] {j' : X' → ℂ} (e : X' ≃ₜ X)
    (he : ∀ x, j (e x) = j' x) (h : Good S X' j') : Good S X j := by
  obtain ⟨hX', hσ⟩ := h
  have : PathConnectedSpace X := e.surjective.pathConnectedSpace e.continuous
  obtain ⟨y₀⟩ := hX'.nonempty
  refine good_of_exists this (e y₀) ?_
  obtain ⟨σ, hσl, hfree⟩ := hσ y₀
  exact ⟨fun s ↦ mapHomeomorph e y₀ (σ s), fun s ↦ (hσl s).map ⟨e, e.continuous⟩ he,
    fun g ↦ existsUnique_lift_mulEquiv (mapHomeomorph e y₀) hfree g⟩

/-- No point: `X ≅ C` is simply connected. -/
private lemma good_empty {C : Set ℂ} (hCc : Convex ℝ C) (hj : IsOpenEmbedding j)
    (hjr : range j = C) [Nonempty X] : Good ∅ X j := by
  obtain ⟨x₀⟩ := ‹Nonempty X›
  have hCne : C.Nonempty := ⟨j x₀, hjr ▸ mem_range_self x₀⟩
  have : ContractibleSpace C := hCc.contractibleSpace hCne
  let e : X ≃ₜ C := hj.isEmbedding.toHomeomorph.trans (Homeomorph.setCongr hjr)
  have : SimplyConnectedSpace X := e.toHomotopyEquiv.simplyConnectedSpace
  refine good_of_exists inferInstance x₀ ⟨fun t ↦ (Finset.notMem_empty _ t.2).elim,
    fun t ↦ (Finset.notMem_empty _ t.2).elim, fun g ↦ ⟨1, fun t ↦ (Finset.notMem_empty _ t.2).elim,
      fun φ _ ↦ ?_⟩⟩
  ext γ
  rw [Subsingleton.elim γ 1, map_one, map_one]

end Induction

/-- For `C ⊆ ℂ` convex and open and `s ∈ C`, the set `{w | s + exp w ∈ C}` (that is,
`exp⁻¹(C - s)`) is simply connected: it deformation retracts onto a left half-plane. -/
lemma isSimplyConnected_setOf_add_exp_mem {C : Set ℂ} (hCc : Convex ℝ C) (hCo : IsOpen C)
    {s : ℂ} (hs : s ∈ C) : IsSimplyConnected {w : ℂ | s + exp w ∈ C} := by
  obtain ⟨r₀, hr₀, hball⟩ := Metric.isOpen_iff.mp hCo s hs
  set R := {w : ℂ | s + exp w ∈ C}
  set c₀ := Real.log r₀ - 1
  set Q := {w : ℂ | w.re < Real.log r₀}
  have hQR : Q ⊆ R := fun w hw ↦ hball (by
    rw [mem_ball, dist_eq_norm, add_sub_cancel_left, norm_exp]
    exact (Real.lt_log_iff_exp_lt hr₀).mp hw)
  have hshift (w : ℂ) (hw : w ∈ R) (u : ℝ) (hu : 0 ≤ u) : w - u ∈ R := by
    have ha : 0 ≤ 1 - Real.exp (-u) := sub_nonneg.mpr (Real.exp_le_one_iff.mpr (by linarith))
    have h := hCc hs hw ha (Real.exp_pos _).le (by ring)
    have heq : s + exp (w - u) = (1 - Real.exp (-u)) • s + Real.exp (-u) • (s + exp w) := by
      rw [Complex.real_smul, Complex.real_smul, sub_eq_add_neg w, exp_add, ← Complex.ofReal_neg,
        ← Complex.ofReal_exp]
      push_cast
      ring
    change s + exp (w - u) ∈ C
    rw [heq]
    exact h
  let m : ℂ → ℝ := fun w ↦ max 0 (w.re - c₀)
  have hm : Continuous m := by fun_prop
  have hm0 (w : ℂ) : 0 ≤ m w := le_max_left _ _
  have hmQ (w : ℂ) : (w - m w).re < Real.log r₀ := by
    have : w.re - c₀ ≤ m w := le_max_right _ _
    simp only [Complex.sub_re, Complex.ofReal_re]
    linarith
  have hQ : Convex ℝ Q := convex_halfSpace_lt (f := Complex.re) ⟨fun _ _ ↦ rfl, fun _ _ ↦ by simp⟩ _
  have : ContractibleSpace Q := hQ.contractibleSpace ⟨c₀, by simp [Q, c₀]⟩
  have hu (t : unitInterval) (w : ℂ) : 0 ≤ (1 - (t : ℝ)) * m w :=
    mul_nonneg (sub_nonneg.mpr t.2.2) (hm0 w)
  let e : ContinuousMap.HomotopyEquiv R Q :=
    { toFun := ⟨fun w ↦ ⟨w - m w, hmQ w⟩, by fun_prop⟩
      invFun := ⟨fun w ↦ ⟨w, hQR w.2⟩, by fun_prop⟩
      left_inv := ⟨{ toFun := fun p ↦ ⟨p.2 - ((1 - (p.1 : ℝ)) * m p.2 : ℝ),
                      hshift _ p.2.2 _ (hu p.1 p.2)⟩
                     continuous_toFun := by fun_prop
                     map_zero_left := fun w ↦ by ext; simp
                     map_one_left := fun w ↦ by ext; simp }⟩
      right_inv := ⟨{ toFun := fun p ↦ ⟨p.2 - ((1 - (p.1 : ℝ)) * m p.2 : ℝ), by
                        have h := p.2.2
                        simp only [Q, mem_ofPred_eq, Complex.sub_re, Complex.ofReal_re] at h ⊢
                        linarith [hu p.1 p.2]⟩
                      continuous_toFun := by fun_prop
                      map_zero_left := fun w ↦ by ext; simp
                      map_one_left := fun w ↦ by ext; simp }⟩ }
  exact e.simplyConnectedSpace

section Induction

variable {S : Finset ℂ} {X : Type} [TopologicalSpace X] {j : X → ℂ}

/-- One point: `π₁(C ∖ {s}) ≅ ℤ`, generated by a circle around `s`
(`Complex.fundamentalGroupMulEquivInt`). -/
private lemma good_singleton {C : Set ℂ} (hCc : Convex ℝ C) (hCo : IsOpen C) {s : ℂ}
    (hs : s ∈ C) (hj : IsOpenEmbedding j) (hjr : range j = C \ {s}) : Good {s} X j := by
  obtain ⟨r₀, hr₀, hball⟩ := Metric.isOpen_iff.mp hCo s hs
  let B : Set ℂ := {z | z ≠ 0 ∧ s + z ∈ C}
  have hB0 : (0 : ℂ) ∉ B := fun h ↦ h.1 rfl
  have hBexp : exp ⁻¹' B = {w | s + exp w ∈ C} := by
    ext w
    simp [B, exp_ne_zero]
  have hS : IsSimplyConnected (exp ⁻¹' B) :=
    hBexp ▸ isSimplyConnected_setOf_add_exp_mem hCc hCo hs
  have : SimplyConnectedSpace (expPreimage B) := hS.simplyConnectedSpace
  -- `X ≅ B` by `x ↦ j x - s`
  let τ : ↥B ≃ₜ ↥(C \ {s}) :=
    { toFun z := ⟨s + z, z.2.2, by simpa using z.2.1⟩
      invFun w := ⟨w - s, sub_ne_zero.mpr w.2.2, by simpa using w.2.1⟩
      left_inv z := Subtype.ext (add_sub_cancel_left _ _)
      right_inv w := Subtype.ext (add_sub_cancel _ _)
      continuous_toFun := by fun_prop
      continuous_invFun := by fun_prop }
  let E : X ≃ₜ ↥(C \ {s}) := hj.isEmbedding.toHomeomorph.trans (Homeomorph.setCongr hjr)
  have hE (x : X) : (E x : ℂ) = j x := rfl
  let e : ↥B ≃ₜ X := τ.trans E.symm
  have he (z : B) : j (e z) = s + z := by
    rw [← hE]
    change ((E (E.symm (τ z))) : ℂ) = _
    rw [E.apply_symm_apply]
    rfl
  refine good_of_homeomorph e he ?_
  have hPC : PathConnectedSpace B :=
    (isAddQuotientCoveringMap_expRestrict hB0).surjective.pathConnectedSpace continuous_expRestrict
  -- the base point `b = r₁` and the circle of radius `r₁`
  set r₁ := r₀ / 2
  have hr₁ : 0 < r₁ := half_pos hr₀
  have hdisc : closedBall s r₁ ⊆ C := (closedBall_subset_ball (half_lt_self hr₀)).trans hball
  let κ : C(↥(closedBall s r₁ \ {s}), B) :=
    ⟨fun z ↦ ⟨z - s, sub_ne_zero.mpr z.2.2, by rw [add_sub_cancel]; exact hdisc z.2.1⟩,
      by fun_prop⟩
  have hκ (z : ↥(closedBall s r₁ \ {s})) : s + (κ z : ℂ) = z := add_sub_cancel _ _
  let b : B := κ ⟨s + r₁, add_ofReal_mem_closedBall_diff hr₁⟩
  have hb : (b : ℂ) = r₁ := add_sub_cancel_left _ _
  refine good_of_exists hPC b ⟨fun _ ↦ generatorLoop hB0 b, fun t ↦ ?_,
    fun {H : Type} [Group H] g ↦ ?_⟩
  · -- the generator is a loop around `s`
    have ht : (t : ℂ) = s := Finset.mem_singleton.mp t.2
    rw [ht]
    refine ⟨r₁, hr₁, κ, hκ, Path.refl b, ?_⟩
    set c := ((circlePath s r₁).codRestrict (range_circlePath_subset hr₁)).map κ.continuous
    have hc : Path.Homotopic.Quotient.mk (((Path.refl b).trans c).trans (Path.refl b).symm) =
        Path.Homotopic.Quotient.mk c := by
      change FundamentalGroupoid.fromPath _ = FundamentalGroupoid.fromPath _
      rw [Path.refl_symm, FundamentalGroupoid.fromPath_mk_trans,
        FundamentalGroupoid.fromPath_mk_trans, FundamentalGroupoid.fromPath_mk_refl,
        Category.id_comp, Category.comp_id]
    rw [hc]
    -- the straight path from `log b` to `log b + 2πi` in `exp⁻¹(B)`
    have hmem (t : unitInterval) :
        log (b : ℂ) + 2 * π * I * (t : ℝ) ∈ expPreimage B := by
      rw [mem_expPreimage, exp_add, exp_log (by rw [hb]; exact_mod_cast hr₁.ne')]
      have := (κ (⟨circlePath s r₁ t, range_circlePath_subset hr₁ ⟨t, rfl⟩⟩)).2
      convert this using 1
      change _ = circlePath s r₁ t - s
      rw [circlePath_apply, add_sub_cancel_left, hb]
    let lp : Path (logLift hB0 b) (logLiftAdd hB0 b) :=
      { toFun t := ⟨log (b : ℂ) + 2 * π * I * (t : ℝ), hmem t⟩
        continuous_toFun := by fun_prop
        source' := by ext; simp
        target' := by ext; simp }
    have hlp : Path.Homotopic.Quotient.mk ((PathConnectedSpace.somePath (logLift hB0 b)
        (logLiftAdd hB0 b)).map continuous_expRestrict) =
        Path.Homotopic.Quotient.mk (lp.map continuous_expRestrict) :=
      Path.Homotopic.Quotient.eq.mpr
        ((SimplyConnectedSpace.paths_homotopic _ lp).map ⟨_, continuous_expRestrict⟩)
    change Path.Homotopic.Quotient.mk (((PathConnectedSpace.somePath (logLift hB0 b)
      (logLiftAdd hB0 b)).map continuous_expRestrict).cast _ _) = _
    rw [Path.Homotopic.Quotient.mk_cast, hlp, ← Path.Homotopic.Quotient.mk_cast]
    refine congrArg Path.Homotopic.Quotient.mk (Path.ext (funext fun t ↦ Subtype.ext ?_))
    change exp (log (b : ℂ) + 2 * π * I * (t : ℝ)) = circlePath s r₁ t - s
    rw [circlePath_apply, add_sub_cancel_left, exp_add,
      exp_log (by rw [hb]; exact_mod_cast hr₁.ne'), hb]
  · -- freeness
    let φ₀ := fundamentalGroupMulEquivInt hB0 b
    let g₀ := g ⟨s, Finset.mem_singleton_self s⟩
    have hgt (t : ↥({s} : Finset ℂ)) : g t = g₀ :=
      congrArg g (Subtype.ext (Finset.mem_singleton.mp t.2))
    have hφ₀ : φ₀ (Multiplicative.ofAdd 1) = generatorLoop hB0 b := by
      rw [fundamentalGroupMulEquivInt_apply, toAdd_ofAdd, zpow_one]
    refine ⟨(zpowersHom H g₀).comp φ₀.symm.toMonoidHom, fun t ↦ ?_, fun φ hφ ↦ ?_⟩
    · rw [hgt, MonoidHom.comp_apply, MulEquiv.coe_toMonoidHom, ← hφ₀, MulEquiv.symm_apply_apply,
        zpowersHom_apply, toAdd_ofAdd, zpow_one]
    · ext γ
      obtain ⟨k, rfl⟩ := φ₀.surjective γ
      rw [MonoidHom.comp_apply, MulEquiv.coe_toMonoidHom, MulEquiv.symm_apply_apply,
        zpowersHom_apply, fundamentalGroupMulEquivInt_apply, map_zpow,
        hφ ⟨s, Finset.mem_singleton_self s⟩]


/-- The induction, on the number of points. -/
private theorem good (n : ℕ) : ∀ (S : Finset ℂ), S.card = n → ∀ (C : Set ℂ), Convex ℝ C →
    IsOpen C → (S : Set ℂ) ⊆ C → ∀ (X : Type) [TopologicalSpace X] (j : X → ℂ),
    IsOpenEmbedding j → range j = C \ S → Nonempty X → Good S X j := by
  induction n using Nat.strong_induction_on with
  | _ n ih =>
  intro S hSn C hCc hCo hSC X _ j hj hjr hX
  rcases Nat.lt_or_ge n 2 with hn | hn
  · interval_cases n
    · rw [Finset.card_eq_zero] at hSn
      subst hSn
      exact good_empty hCc hj (by simpa using hjr)
    · obtain ⟨s, rfl⟩ := Finset.card_eq_one.mp hSn
      exact good_singleton hCc hCo (hSC (by simp)) hj (by simpa using hjr)
  -- two points or more: a real linear form separating two of them
  obtain ⟨s₁, hs₁, s₂, hs₂, hne⟩ := Finset.one_lt_card.mp (by omega : 1 < S.card)
  obtain ⟨v, hv⟩ : ∃ v : ℂ →L[ℝ] ℝ, v s₁ ≠ v s₂ := by
    by_cases hre : s₁.re = s₂.re
    · exact ⟨Complex.imCLM, fun h ↦ hne (Complex.ext hre h)⟩
    · exact ⟨Complex.reCLM, hre⟩
  -- the smallest value `m` of `v` on `S` and the next one `v₂`
  have hVne : (S.image v).Nonempty := Finset.image_nonempty.mpr ⟨s₁, hs₁⟩
  set m := (S.image v).min' hVne
  have hmle (z : ℂ) (hz : z ∈ S) : m ≤ v z := Finset.min'_le _ _ (Finset.mem_image_of_mem _ hz)
  have hT : ((S.image v).filter (m < ·)).Nonempty := by
    rcases lt_or_gt_of_ne hv with h | h
    · exact ⟨v s₂, Finset.mem_filter.mpr ⟨Finset.mem_image_of_mem _ hs₂,
        (hmle s₁ hs₁).trans_lt h⟩⟩
    · exact ⟨v s₁, Finset.mem_filter.mpr ⟨Finset.mem_image_of_mem _ hs₁,
        (hmle s₂ hs₂).trans_lt h⟩⟩
  set v₂ := ((S.image v).filter (m < ·)).min' hT
  have hmv₂ : m < v₂ := (Finset.mem_filter.mp (Finset.min'_mem _ hT)).2
  have hgap (z : ℂ) (hz : z ∈ S) : v z ≤ m ∨ v₂ ≤ v z := by
    by_cases h : m < v z
    · exact Or.inr (Finset.min'_le _ _
        (Finset.mem_filter.mpr ⟨Finset.mem_image_of_mem _ hz, h⟩))
    · exact Or.inl (not_lt.mp h)
  obtain ⟨p, hpS, hpv⟩ : ∃ p ∈ S, v p = m := by
    simpa using Finset.min'_mem _ hVne
  obtain ⟨q, hqS, hqv⟩ : ∃ q ∈ S, v q = v₂ := by
    simpa using (Finset.mem_filter.mp (Finset.min'_mem _ hT)).1
  set a' := (2 * m + v₂) / 3
  set a := (m + 2 * v₂) / 3
  have ha'a : a' < a := by simp only [a', a]; linarith
  have hma' : m < a' := by simp only [a']; linarith
  have hav₂ : a < v₂ := by simp only [a]; linarith
  have hmid₁ : a' < (m + v₂) / 2 := by simp only [a']; linarith
  have hmid₂ : (m + v₂) / 2 < a := by simp only [a]; linarith
  -- the pieces
  set SU := S.filter (fun z ↦ v z < a)
  set SV := S.filter (fun z ↦ a' < v z)
  have hcardU : SU.card < n := by
    rw [← hSn]
    refine Finset.card_lt_card ⟨Finset.filter_subset _ _, fun h ↦ ?_⟩
    have := (Finset.mem_filter.mp (h hqS)).2
    linarith
  have hcardV : SV.card < n := by
    rw [← hSn]
    refine Finset.card_lt_card ⟨Finset.filter_subset _ _, fun h ↦ ?_⟩
    have := (Finset.mem_filter.mp (h hpS)).2
    linarith
  have hlin : IsLinearMap ℝ v := v.toLinearMap.isLinear
  have hCUc : Convex ℝ (C ∩ {z | v z < a}) := hCc.inter (convex_halfSpace_lt hlin a)
  have hCVc : Convex ℝ (C ∩ {z | a' < v z}) := hCc.inter (convex_halfSpace_gt hlin a')
  have hCUo : IsOpen (C ∩ {z | v z < a}) := hCo.inter (isOpen_lt v.continuous continuous_const)
  have hCVo : IsOpen (C ∩ {z | a' < v z}) := hCo.inter (isOpen_lt continuous_const v.continuous)
  -- the base point, on the segment `[p, q]`
  set z₀ : ℂ := (1 / 2 : ℝ) • p + (1 / 2 : ℝ) • q
  have hz₀C : z₀ ∈ C := hCc (hSC hpS) (hSC hqS) (by norm_num) (by norm_num) (by norm_num)
  have hvz₀ : v z₀ = (m + v₂) / 2 := by
    simp only [z₀, map_add, map_smul, hpv, hqv, smul_eq_mul]
    ring
  have hz₀S : z₀ ∉ S := fun h ↦ by
    rcases hgap z₀ h with h' | h' <;> rw [hvz₀] at h' <;> linarith
  obtain ⟨x₀, hx₀⟩ : z₀ ∈ range j := hjr ▸ ⟨hz₀C, hz₀S⟩
  -- the open cover of `X`
  set U : Set X := j ⁻¹' {z | v z < a}
  set V : Set X := j ⁻¹' {z | a' < v z}
  have hUo : IsOpen U := (isOpen_lt v.continuous continuous_const).preimage hj.continuous
  have hVo : IsOpen V := (isOpen_lt continuous_const v.continuous).preimage hj.continuous
  have hUV : U ∪ V = univ := eq_univ_of_forall fun x ↦ by
    by_cases h : v (j x) < a
    · exact Or.inl h
    · exact Or.inr (show a' < v (j x) by linarith [not_lt.mp h])
  have hx₀U : x₀ ∈ U := show v (j x₀) < a by rw [hx₀, hvz₀]; exact hmid₂
  have hx₀V : x₀ ∈ V := show a' < v (j x₀) by rw [hx₀, hvz₀]; exact hmid₁
  have hrangeU : range (j ∘ (Subtype.val : U → X)) = (C ∩ {z | v z < a}) \ SU := by
    rw [range_comp, Subtype.range_coe, image_preimage_eq_inter_range, hjr]
    ext z
    simp only [SU, Finset.coe_filter, mem_inter_iff, mem_sdiff, mem_ofPred_eq]
    tauto
  have hrangeV : range (j ∘ (Subtype.val : V → X)) = (C ∩ {z | a' < v z}) \ SV := by
    rw [range_comp, Subtype.range_coe, image_preimage_eq_inter_range, hjr]
    ext z
    simp only [SV, Finset.coe_filter, mem_inter_iff, mem_sdiff, mem_ofPred_eq]
    tauto
  have hSUC : (SU : Set ℂ) ⊆ C ∩ {z | v z < a} := fun z hz ↦ by
    rw [Finset.coe_filter] at hz
    exact ⟨hSC hz.1, hz.2⟩
  have hSVC : (SV : Set ℂ) ⊆ C ∩ {z | a' < v z} := fun z hz ↦ by
    rw [Finset.coe_filter] at hz
    exact ⟨hSC hz.1, hz.2⟩
  obtain ⟨hPU, hσU⟩ := ih _ hcardU SU rfl _ hCUc hCUo hSUC U (j ∘ Subtype.val)
    (hj.comp hUo.isOpenEmbedding_subtypeVal) hrangeU ⟨⟨x₀, hx₀U⟩⟩
  obtain ⟨hPV, hσV⟩ := ih _ hcardV SV rfl _ hCVc hCVo hSVC V (j ∘ Subtype.val)
    (hj.comp hVo.isOpenEmbedding_subtypeVal) hrangeV ⟨⟨x₀, hx₀V⟩⟩
  have hUc : IsPathConnected U := isPathConnected_iff_pathConnectedSpace.mpr hPU
  have hVc : IsPathConnected V := isPathConnected_iff_pathConnectedSpace.mpr hPV
  -- the intersection is a convex strip
  have hUVeq : U ∩ V = j ⁻¹' (C ∩ {z | a' < v z ∧ v z < a}) := by
    ext x
    have hxC : j x ∈ C := (hjr ▸ mem_range_self x : j x ∈ C \ S).1
    simp only [U, V, mem_inter_iff, mem_preimage, mem_ofPred_eq]
    tauto
  have hstrip : C ∩ {z | a' < v z ∧ v z < a} ⊆ range j := fun z hz ↦ by
    rw [hjr]
    refine ⟨hz.1, fun hzS ↦ ?_⟩
    rcases hgap z hzS with h | h <;> linarith [hz.2.1, hz.2.2]
  have hstripc : Convex ℝ (C ∩ {z | a' < v z ∧ v z < a}) := by
    have : {z : ℂ | a' < v z ∧ v z < a} = {z | a' < v z} ∩ {z | v z < a} := rfl
    rw [this]
    exact hCc.inter ((convex_halfSpace_gt hlin a').inter (convex_halfSpace_lt hlin a))
  have hz₀strip : z₀ ∈ C ∩ {z | a' < v z ∧ v z < a} :=
    ⟨hz₀C, by rw [hvz₀]; exact hmid₁, by rw [hvz₀]; exact hmid₂⟩
  have : ContractibleSpace ↥(C ∩ {z | a' < v z ∧ v z < a}) :=
    hstripc.contractibleSpace ⟨z₀, hz₀strip⟩
  let eUV : ↥(U ∩ V) ≃ₜ ↥(C ∩ {z | a' < v z ∧ v z < a}) :=
    (Homeomorph.setCongr hUVeq).trans (hj.isEmbedding.homeomorphOfSubsetRange hstrip)
  have : SimplyConnectedSpace ↥(U ∩ V) := eUV.toHomotopyEquiv.simplyConnectedSpace
  have hUVc : IsPathConnected (U ∩ V) := isPathConnected_iff_pathConnectedSpace.mpr inferInstance
  have hXc : PathConnectedSpace X := by
    rw [pathConnectedSpace_iff_univ, ← hUV]
    exact hUc.union hVc ⟨x₀, hx₀U, hx₀V⟩
  -- the basis
  obtain ⟨σU, hσUl, hfreeU⟩ := hσU ⟨x₀, hx₀U⟩
  obtain ⟨σV, hσVl, hfreeV⟩ := hσV ⟨x₀, hx₀V⟩
  have hmemU (t : S) (h : v t < a) : (t : ℂ) ∈ SU := Finset.mem_filter.mpr ⟨t.2, h⟩
  have hmemV (t : S) (h : ¬ v t < a) : (t : ℂ) ∈ SV :=
    Finset.mem_filter.mpr ⟨t.2, by linarith [not_lt.mp h]⟩
  let σ : S → FundamentalGroup X x₀ := fun t ↦
    if h : v t < a then mapSubtypeVal hx₀U (σU ⟨t, hmemU t h⟩)
    else mapSubtypeVal hx₀V (σV ⟨t, hmemV t h⟩)
  have hσU' (t : SU) : σ ⟨t, (Finset.mem_filter.mp t.2).1⟩ = mapSubtypeVal hx₀U (σU t) := by
    simp only [σ, dite_eq_left (Finset.mem_filter.mp t.2).2]
  have hσV' (t : SV) (h : ¬ v t < a) :
      σ ⟨t, (Finset.mem_filter.mp t.2).1⟩ = mapSubtypeVal hx₀V (σV t) := by
    simp only [σ, dite_eq_right h]
  refine good_of_exists hXc x₀ ⟨σ, fun t ↦ ?_, fun {H : Type} [Group H] g ↦ ?_⟩
  · by_cases h : v t < a
    · simp only [σ, dite_eq_left h]
      exact (hσUl ⟨t, hmemU t h⟩).map ⟨Subtype.val, continuous_subtype_val⟩ fun _ ↦ rfl
    · simp only [σ, dite_eq_right h]
      exact (hσVl ⟨t, hmemV t h⟩).map ⟨Subtype.val, continuous_subtype_val⟩ fun _ ↦ rfl
  · obtain ⟨φU, hφU, huU⟩ := hfreeU fun t ↦ g ⟨t, (Finset.mem_filter.mp t.2).1⟩
    obtain ⟨φV, hφV, huV⟩ := hfreeV fun t ↦ g ⟨t, (Finset.mem_filter.mp t.2).1⟩
    obtain ⟨φ, hφ, huniq⟩ := existsUnique_hom_of_union hUo hVo hUV hUc hVc hUVc hx₀U hx₀V φU φV
      (MonoidHom.ext fun γ ↦ by rw [Subsingleton.elim γ 1, map_one, map_one])
    refine ⟨φ, fun t ↦ ?_, fun φ' hφ' ↦ huniq φ' ⟨?_, ?_⟩⟩
    · by_cases h : v t < a
      · simp only [σ, dite_eq_left h]
        rw [← MonoidHom.comp_apply, hφ.1, hφU]
      · simp only [σ, dite_eq_right h]
        rw [← MonoidHom.comp_apply, hφ.2, hφV]
    · refine huU _ fun t ↦ ?_
      rw [MonoidHom.comp_apply, ← hσU' t, hφ']
    · refine huV _ fun t ↦ ?_
      have h : ¬ v t < a := fun h ↦ by
        have := (Finset.mem_filter.mp t.2).2
        rcases hgap t (Finset.mem_filter.mp t.2).1 with h' | h' <;> linarith
      rw [MonoidHom.comp_apply, ← hσV' t h, hφ']

end Induction


variable {C : Set ℂ} {S : Finset ℂ} {X : Type} [TopologicalSpace X] {j : X → ℂ}

/-- A space with an open embedding into `ℂ` onto `C ∖ S` (`C` convex and open, `S ⊆ C` finite)
is path-connected as soon as it is nonempty. -/
theorem pathConnectedSpace_of_isOpenEmbedding_of_range_eq_diff (hCc : Convex ℝ C) (hCo : IsOpen C)
    (hSC : (S : Set ℂ) ⊆ C) (hj : IsOpenEmbedding j) (hjr : range j = C \ S) [Nonempty X] :
    PathConnectedSpace X :=
  (good S.card S rfl C hCc hCo hSC X j hj hjr inferInstance).1

/-- **The fundamental group of a convex open subset of `ℂ` minus finitely many points is free on
loops around the points.** Let `C ⊆ ℂ` be convex and open, `S ⊆ C` finite, and `j : X → ℂ` an
open embedding onto `C ∖ S` (e.g. the inclusion of `C ∖ S`, see
`exists_freeGroupBasis_fundamentalGroup_diff`). Then `π₁(X, x)` has a free basis indexed by `S`
whose element at `s` is a loop around `s`: conjugate to a small circle around `s`
(`FundamentalGroup.IsLoopAround`). -/
theorem exists_freeGroupBasis_fundamentalGroup_of_isOpenEmbedding (hCc : Convex ℝ C)
    (hCo : IsOpen C) (hSC : (S : Set ℂ) ⊆ C) (hj : IsOpenEmbedding j) (hjr : range j = C \ S)
    (x : X) :
    ∃ b : FreeGroupBasis S (FundamentalGroup X x), ∀ s : S, IsLoopAround j (s : ℂ) (b s) := by
  obtain ⟨σ, hσ, hfree⟩ := (good S.card S rfl C hCc hCo hSC X j hj hjr ⟨x⟩).2 x
  refine ⟨FreeGroupBasis.ofUniqueLift S σ hfree, fun s ↦ ?_⟩
  have h : (FreeGroupBasis.ofUniqueLift S σ hfree) s = σ s := by
    change (FreeGroupBasis.ofUniqueLift S σ hfree).repr.symm (FreeGroup.of s) = σ s
    simp [FreeGroupBasis.ofUniqueLift, FreeGroupBasis.ofLift]
  rw [h]
  exact hσ s

/-- **`π₁(C ∖ S)` is free on loops around the points of `S`** (`C ⊆ ℂ` convex and open, e.g. `ℂ`
or a disc, and `S ⊆ C` finite): the genus `0` case of the presentation of the fundamental group of
a punctured compact Riemann surface. -/
theorem exists_freeGroupBasis_fundamentalGroup_diff (hCc : Convex ℝ C) (hCo : IsOpen C)
    (hSC : (S : Set ℂ) ⊆ C) (x : (C \ S : Set ℂ)) :
    ∃ b : FreeGroupBasis S (FundamentalGroup (C \ S : Set ℂ) x),
      ∀ s : S, IsLoopAround Subtype.val (s : ℂ) (b s) :=
  exists_freeGroupBasis_fundamentalGroup_of_isOpenEmbedding hCc hCo hSC
    (hCo.sdiff S.finite_toSet.isClosed).isOpenEmbedding_subtypeVal Subtype.range_coe x

end Complex
