/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.Foundations.Topology.SurfaceSchreierTree

/-!
# The Schreier basis of a stabilizer

Let `F` be free on `σ₀, …, σₙ`, acting transitively on a finite set `Φ`, `φ₀ ∈ Φ`, and let
`(rest, T, t)` be a spanning tree with a Schreier transversal (`Ribbon.Schreier.TreeInv`). Then
the labels `t ψ⁻¹ σᵢ t (σᵢ⁻¹ • ψ)` of the edges off the tree form a free basis of the stabilizer
`H` of `φ₀` (`Ribbon.Schreier.isFreeList_nonTree`, `Ribbon.Schreier.spanOf_nonTree`).

Generation: every `g ∈ F` satisfies `t (g • ψ)⁻¹ g t ψ ∈ ⟨labels⟩` for all `ψ`, by induction on
`g`. Freeness: for labels `f` in any group `X`, trivial on the tree, `F` acts on `Φ × X` by
`σᵢ • (ψ, y) = (σᵢ • ψ, f (σᵢ • ψ, i) y)`, and `h ↦` (the `X`-coordinate of `h • (φ₀, 1)`) is a
homomorphism `H → X` sending each label to its value (`Ribbon.Schreier.exists_hom_stabilizer`).

## References

* [W. Magnus, A. Karrass, D. Solitar, *Combinatorial Group Theory*, §2.3 (Reidemeister–Schreier)
  ][magnus1966]
-/

open Function Nielsen

/- Membership in lists of edges and darts is decided with the `BEq` instance coming from
`DecidableEq`, as in `Ribbon.IsRibbon.contract_tree`. -/
attribute [local instance 2000] instBEqOfDecidableEq

namespace Ribbon.Schreier

variable {F : Type*} [Group F] {Φ : Type*} [MulAction F Φ] {n : ℕ} (σ : Fin (n + 1) → F)

lemma mem_closure_of_bijective (hfree : Bijective (FreeGroup.lift σ)) (g : F) :
    g ∈ Subgroup.closure (Set.range σ) := by
  obtain ⟨w, rfl⟩ := hfree.2 g
  induction w using FreeGroup.induction_on with
  | one => simp
  | of i => simpa using Subgroup.subset_closure (Set.mem_range_self i)
  | inv_of i hi =>
    rw [map_inv]
    exact Subgroup.inv_mem _ hi
  | mul x y hx hy =>
    rw [map_mul]
    exact Subgroup.mul_mem _ hx hy

variable {σ} {φ₀ : Φ} {t : Φ → F}

lemma edgeLabel_mem_stabilizer (ht : ∀ ψ, t ψ • φ₀ = ψ) (e : Φ × Fin (n + 1)) :
    edgeLabel σ t e ∈ MulAction.stabilizer F φ₀ := by
  rw [MulAction.mem_stabilizer_iff, edgeLabel, mul_smul, mul_smul, ht, smul_inv_smul,
    inv_smul_eq_iff, ht]

/-- **Generation**: the stabilizer of `φ₀` is generated by the Schreier labels. -/
lemma stabilizer_le_closure (hgen : ∀ g : F, g ∈ Subgroup.closure (Set.range σ))
    (ht0 : t φ₀ = 1) :
    MulAction.stabilizer F φ₀ ≤ Subgroup.closure (Set.range (edgeLabel σ t)) := by
  set K := Subgroup.closure (Set.range (edgeLabel σ t))
  have key : ∀ g : F, ∀ ψ, (t (g • ψ))⁻¹ * g * t ψ ∈ K := by
    intro g
    induction hgen g using Subgroup.closure_induction'' with
    | mem x hx =>
      obtain ⟨i, rfl⟩ := hx
      intro ψ
      have : edgeLabel σ t (σ i • ψ, i) = (t (σ i • ψ))⁻¹ * σ i * t ψ := by
        simp [edgeLabel]
      rw [← this]
      exact Subgroup.subset_closure (Set.mem_range_self _)
    | inv_mem x hx =>
      obtain ⟨i, rfl⟩ := hx
      intro ψ
      have : (edgeLabel σ t (ψ, i))⁻¹ = (t ((σ i)⁻¹ • ψ))⁻¹ * (σ i)⁻¹ * t ψ := by
        simp [edgeLabel, mul_assoc]
      rw [← this]
      exact Subgroup.inv_mem _ (Subgroup.subset_closure (Set.mem_range_self _))
    | one => intro ψ; simp
    | mul x y _ _ hx hy =>
      intro ψ
      have := Subgroup.mul_mem K (hx (y • ψ)) (hy ψ)
      rwa [← mul_smul, show (t ((x * y) • ψ))⁻¹ * x * t (y • ψ) * ((t (y • ψ))⁻¹ * y * t ψ) =
        (t ((x * y) • ψ))⁻¹ * (x * y) * t ψ by group] at this
  intro h hh
  have := key h φ₀
  rwa [MulAction.mem_stabilizer_iff.mp hh, ht0, inv_one, one_mul, mul_one] at this

section Lift

variable {X : Type*} [Group X] (f : Φ × Fin (n + 1) → X)

/-- The action of the generator `σᵢ` on `Φ × X`: `(ψ, y) ↦ (σᵢ • ψ, f (σᵢ • ψ, i) y)`. -/
def genPerm (i : Fin (n + 1)) : Equiv.Perm (Φ × X) where
  toFun p := (σ i • p.1, f (σ i • p.1, i) * p.2)
  invFun p := ((σ i)⁻¹ • p.1, (f (p.1, i))⁻¹ * p.2)
  left_inv p := by simp
  right_inv p := by simp

variable (hfree : Bijective (FreeGroup.lift σ))

/-- The action of `F` on `Φ × X` defined by the generators. -/
noncomputable def theta : F →* Equiv.Perm (Φ × X) :=
  (FreeGroup.lift (genPerm (σ := σ) f)).comp
    (MulEquiv.ofBijective (FreeGroup.lift σ) hfree).symm.toMonoidHom

lemma theta_gen (i : Fin (n + 1)) : theta f hfree (σ i) = genPerm (σ := σ) f i := by
  have : (MulEquiv.ofBijective (FreeGroup.lift σ) hfree).symm (σ i) = FreeGroup.of i := by
    rw [MulEquiv.symm_apply_eq]
    simp
  simp [theta, this]

/-- The first coordinate of the action is the action on `Φ`, and the action commutes with right
multiplication on `X`. -/
lemma theta_apply (g : F) : ∀ (ψ : Φ) (y y' : X),
    (theta f hfree g (ψ, y * y')).1 = g • ψ ∧
      (theta f hfree g (ψ, y * y')).2 = (theta f hfree g (ψ, y)).2 * y' := by
  induction mem_closure_of_bijective σ hfree g using Subgroup.closure_induction'' with
  | mem x hx =>
    obtain ⟨i, rfl⟩ := hx
    intro ψ y y'
    simp [theta_gen, genPerm, mul_assoc]
  | inv_mem x hx =>
    obtain ⟨i, rfl⟩ := hx
    intro ψ y y'
    rw [map_inv, theta_gen]
    simp [genPerm, Equiv.Perm.inv_def, mul_assoc]
  | one => intro ψ y y'; simp
  | mul a b _ _ ha hb =>
    intro ψ y y'
    rw [map_mul, Equiv.Perm.mul_apply, Equiv.Perm.mul_apply, mul_smul]
    obtain ⟨hb1, hb2⟩ := hb ψ y y'
    have hb1' : (theta f hfree b (ψ, y)).1 = b • ψ := by simpa using (hb ψ y 1).1
    have e1 : theta f hfree b (ψ, y * y') =
        ((theta f hfree b (ψ, y)).1, (theta f hfree b (ψ, y)).2 * y') := by
      rw [← hb2, hb1', ← hb1]
    have e2 : theta f hfree b (ψ, y) = (b • ψ, (theta f hfree b (ψ, y)).2) := by
      rw [← hb1']
    rw [e1, e2]
    exact ha (b • ψ) _ y'

lemma theta_fst (g : F) (p : Φ × X) : (theta f hfree g p).1 = g • p.1 := by
  simpa using (theta_apply f hfree g p.1 p.2 1).1

lemma theta_snd_mul (g : F) (ψ : Φ) (y y' : X) :
    (theta f hfree g (ψ, y * y')).2 = (theta f hfree g (ψ, y)).2 * y' :=
  (theta_apply f hfree g ψ y y').2

lemma theta_eq (g : F) (ψ : Φ) (y : X) :
    theta f hfree g (ψ, y) = (g • ψ, (theta f hfree g (ψ, 1)).2 * y) := by
  ext
  · rw [theta_fst]
  · rw [← theta_snd_mul, one_mul]

/-- The homomorphism `H → X` from the action on `Φ × X`: the `X`-coordinate of `h • (φ₀, 1)`. -/
noncomputable def stabHom (φ₀ : Φ) : MulAction.stabilizer F φ₀ →* X where
  toFun h := (theta f hfree h (φ₀, 1)).2
  map_one' := by simp
  map_mul' h h' := by
    change (theta f hfree ((h : F) * h') (φ₀, 1)).2 =
      (theta f hfree h (φ₀, 1)).2 * (theta f hfree h' (φ₀, 1)).2
    rw [map_mul, Equiv.Perm.mul_apply]
    have e : theta f hfree h' (φ₀, 1) = (φ₀, (theta f hfree h' (φ₀, 1)).2) := by
      ext
      · rw [theta_fst]
        exact h'.2
      · rfl
    conv_lhs => rw [e, theta_eq]

lemma stabHom_apply (φ₀ : Φ) (h : MulAction.stabilizer F φ₀) :
    stabHom f hfree φ₀ h = (theta f hfree h (φ₀, 1)).2 := rfl

variable {f hfree}

/-- Along an edge with label `1` in `F` and in `X`, the `X`-coordinates of the transversal agree. -/
lemma coc_eq_of_edge (ht : ∀ ψ, t ψ • φ₀ = ψ) {e : Φ × Fin (n + 1)} (he : edgeLabel σ t e = 1)
    (hf : f e = 1) :
    (theta f hfree (t e.1) (φ₀, 1)).2 = (theta f hfree (t ((σ e.2)⁻¹ • e.1)) (φ₀, 1)).2 := by
  obtain ⟨ψ, i⟩ := e
  simp only [edgeLabel] at he
  have he' : t ψ = σ i * t ((σ i)⁻¹ • ψ) := by
    rw [mul_assoc, inv_mul_eq_one] at he
    exact he
  rw [he', map_mul, Equiv.Perm.mul_apply, theta_eq f hfree _ φ₀ 1, ht, mul_one, theta_gen]
  simp [genPerm, hf]

/-- On a spanning tree with labels `1` in `F` and `X`, the transversal acts trivially on the
`X`-coordinate. -/
lemma coc_eq_one (ht : ∀ ψ, t ψ • φ₀ = ψ) (ht0 : t φ₀ = 1) :
    ∀ {A rest : List Φ} {T : List (Dart Φ n)}, TreeCond σ A rest T →
    (∀ ψ ∈ A, (theta f hfree (t ψ) (φ₀, 1)).2 = 1) →
    (∀ d ∈ T, edgeLabel σ t d.1 = 1 ∧ f d.1 = 1) →
    ∀ ψ ∈ rest, (theta f hfree (t ψ) (φ₀, 1)).2 = 1
  | _, [], [], _, _, _, ψ, hψ => by simp at hψ
  | A, ψ' :: rest, d :: T, h, hA, hT, ψ, hψ => by
    obtain ⟨h₁, h₂, h₃⟩ := h
    have hd : (theta f hfree (t ψ') (φ₀, 1)).2 = 1 := by
      obtain ⟨⟨ψ₀, i⟩, b⟩ := d
      have key := coc_eq_of_edge (f := f) (hfree := hfree) ht
        (hT _ (List.mem_cons_self ..)).1 (hT _ (List.mem_cons_self ..)).2
      cases b
      · simp only [vtx_false, flip, Bool.not_false, vtx_true] at h₁ h₂
        rw [← h₁, ← key]
        exact hA _ h₂
      · simp only [vtx_true, flip, Bool.not_true, vtx_false] at h₁ h₂
        rw [← h₁, key]
        exact hA _ h₂
    rcases List.mem_cons.mp hψ with rfl | hψ
    · exact hd
    · refine coc_eq_one ht ht0 h₃ (fun ψ'' hψ'' ↦ ?_)
        (fun d' hd' ↦ hT d' (List.mem_cons_of_mem _ hd')) ψ hψ
      rcases List.mem_append.mp hψ'' with hψ'' | hψ''
      · exact hA _ hψ''
      · rw [List.mem_singleton.mp hψ'']
        exact hd
  | _, [], _ :: _, h, _, _, _, _ => h.elim
  | _, _ :: _, [], h, _, _, _, _ => h.elim

/-- **The homomorphism to `X` sends each Schreier label to its value**, when the labels in `X`
are `1` on the tree. -/
lemma stabHom_edgeLabel {rest : List Φ} {T : List (Dart Φ n)} (h : TreeInv σ φ₀ rest T t)
    (hall : ∀ ψ, ψ ∈ φ₀ :: rest) (ht : ∀ ψ, t ψ • φ₀ = ψ) (hf : ∀ d ∈ T, f d.1 = 1)
    (e : Φ × Fin (n + 1)) :
    stabHom f hfree φ₀ ⟨edgeLabel σ t e, edgeLabel_mem_stabilizer ht e⟩ = f e := by
  obtain ⟨-, hT, ht0, -, -, hlab⟩ := h
  have hc : ∀ ψ, (theta f hfree (t ψ) (φ₀, 1)).2 = 1 := by
    intro ψ
    rcases List.mem_cons.mp (hall ψ) with rfl | hψ
    · rw [ht0, map_one]
      rfl
    · exact coc_eq_one ht ht0 hT (fun ψ' hψ' ↦ by
        rw [List.mem_singleton.mp hψ', ht0, map_one]; rfl)
        (fun d hd ↦ ⟨(hlab d hd).1, hf d hd⟩) ψ hψ
  obtain ⟨ψ, i⟩ := e
  rw [stabHom_apply]
  simp only [edgeLabel, map_mul, map_inv, Equiv.Perm.mul_apply]
  rw [theta_eq f hfree _ φ₀ 1, hc, mul_one, ht, theta_gen]
  simp only [genPerm, Equiv.coe_fn_mk, smul_inv_smul, mul_one]
  have e : theta f hfree (t ψ) (φ₀, f (ψ, i)) = (ψ, f (ψ, i)) := by
    rw [theta_eq, hc, one_mul, ht]
  rw [show (theta f hfree (t ψ))⁻¹ (ψ, f (ψ, i)) = (φ₀, f (ψ, i)) from
    Equiv.Perm.inv_eq_iff_eq.mpr e.symm]

end Lift

/-- The edges off the tree, for a list `Φl` of the points. -/
def nonTree [DecidableEq Φ] (Φl : List Φ) (T : List (Dart Φ n)) : List (Φ × Fin (n + 1)) :=
  (Φl ×ˢ List.finRange (n + 1)).filter fun e ↦ e ∉ T.map Prod.fst

/-- **Schreier's theorem with an explicit basis**: the labels of the edges off a spanning tree
form a free basis of the stabilizer of `φ₀`. -/
theorem isFreeList_nonTree [DecidableEq Φ] (hfree : Bijective (FreeGroup.lift σ))
    {rest : List Φ} {T : List (Dart Φ n)} (h : TreeInv σ φ₀ rest T t)
    (hall : ∀ ψ, ψ ∈ φ₀ :: rest) (ht : ∀ ψ, t ψ • φ₀ = ψ) :
    IsFreeList ((nonTree (φ₀ :: rest) T).map (edgeLabel σ t)) ∧
      spanOf ((nonTree (φ₀ :: rest) T).map (edgeLabel σ t)) = MulAction.stabilizer F φ₀ := by
  classical
  set N := nonTree (φ₀ :: rest) T
  set x := edgeLabel σ t
  have hN : N.Nodup := (h.1.product (List.nodup_finRange _)).filter _
  -- the homomorphism to the free group on the edges
  let f : Φ × Fin (n + 1) → FreeGroup (Φ × Fin (n + 1)) :=
    fun e ↦ if e ∈ T.map Prod.fst then 1 else FreeGroup.of e
  have hf : ∀ d ∈ T, f d.1 = 1 := fun d hd ↦ ite_eq_left (List.mem_map_of_mem hd)
  have hlam : ∀ e ∈ N, stabHom f hfree φ₀ ⟨x e, edgeLabel_mem_stabilizer ht e⟩ = FreeGroup.of e :=
    fun e he ↦ by
      rw [stabHom_edgeLabel h hall ht hf]
      exact ite_eq_right (by simpa using (List.mem_filter.mp he).2)
  have hxinj : ∀ e ∈ N, ∀ e' ∈ N, x e = x e' → e = e' := fun e he e' he' hee' ↦ by
    have := hlam e he
    rw [show (⟨x e, _⟩ : MulAction.stabilizer F φ₀) = ⟨x e', edgeLabel_mem_stabilizer ht e'⟩ from
      Subtype.ext hee', hlam e' he'] at this
    exact FreeGroup.of_injective this.symm
  have hbase : (N.map x).Nodup := hN.map_on hxinj
  refine ⟨⟨hbase, ?_⟩, ?_⟩
  · -- injectivity of the map from the free group
    have hmem : ∀ a : {a | a ∈ N.map x}, ∃ e ∈ N, x e = a := fun a ↦ List.mem_map.mp a.2
    choose ε hεN hε using hmem
    let L' : FreeGroup {a | a ∈ N.map x} →* MulAction.stabilizer F φ₀ :=
      FreeGroup.lift fun a ↦ ⟨a, by rw [← hε a]; exact edgeLabel_mem_stabilizer ht _⟩
    have hcomp : (stabHom f hfree φ₀).comp L' = FreeGroup.map ε := by
      refine FreeGroup.ext_hom _ _ fun a ↦ ?_
      simp only [MonoidHom.comp_apply, L', FreeGroup.lift_apply_of, FreeGroup.map.of]
      rw [← hlam (ε a) (hεN a)]
      congr 1
      exact Subtype.ext (hε a).symm
    have hεinj : Injective ε := fun a b hab ↦ Subtype.ext (by rw [← hε a, ← hε b, hab])
    have hL'inj : Injective L' := by
      intro u v huv
      have := congrArg (stabHom f hfree φ₀) huv
      rw [← MonoidHom.comp_apply, hcomp, ← MonoidHom.comp_apply, hcomp] at this
      exact FreeGroup.map_injective hεinj this
    have : FreeGroup.lift ((↑) : {a | a ∈ N.map x} → F) =
        (MulAction.stabilizer F φ₀).subtype.comp L' :=
      FreeGroup.ext_hom _ _ fun a ↦ by simp [L']
    rw [this, MonoidHom.coe_comp]
    exact Subtype.val_injective.comp hL'inj
  · apply le_antisymm
    · rw [spanOf_le]
      intro a ha
      obtain ⟨e, -, rfl⟩ := List.mem_map.mp ha
      exact edgeLabel_mem_stabilizer ht e
    · refine (stabilizer_le_closure (mem_closure_of_bijective σ hfree) h.2.2.1).trans ?_
      rw [Subgroup.closure_le]
      rintro _ ⟨e, rfl⟩
      by_cases he : e ∈ T.map Prod.fst
      · obtain ⟨d, hd, rfl⟩ := List.mem_map.mp he
        rw [(h.2.2.2.2.2 d hd).1]
        exact Subgroup.one_mem _
      · refine mem_spanOf (List.mem_map_of_mem (List.mem_filter.mpr ⟨?_, by simpa using he⟩))
        exact List.mem_product.mpr ⟨hall _, List.mem_finRange _⟩

end Ribbon.Schreier
