/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import Mathlib.GroupTheory.PresentedGroup
import Mathlib.Topology.Compactification.OnePoint.Basic
import SGA.Foundations.Topology.SurfaceGenusZeroOrdered

/-!
# The fundamental group of the projective line minus finitely many points

Let `T ⊆ ℙ¹(ℂ) = OnePoint ℂ` be finite with `n ≥ 1` points. Then `π₁(ℙ¹(ℂ) ∖ T)` is generated by
loops `σ₁, …, σₙ` around the points of `T`, in a suitable order, subject to the single relation
`σ₁ ⋯ σₙ = 1`: the homomorphism from the presented group `⟨x₁, …, xₙ | x₁ ⋯ xₙ⟩` sending `xᵢ` to
`σᵢ` is bijective. Here `σ` is a *loop around `t ∈ ℙ¹(ℂ)`* if it is a loop around `0` in the
standard coordinate at `t` (`z - a` at a finite point `a`, `1 / z` at `∞`;
`Complex.IsLoopAroundAt`).

* `FreeGroup.prodRelator n`: the relator `x₁ ⋯ xₙ`; `Fin.snocProdInv b`: the family `b` followed
  by the inverse of its product;
* `FreeGroupBasis.bijective_toGroup_snoc`: if `b₁, …, b_{n-1}` is a free basis of `G`, then
  `b₁, …, b_{n-1}, (b₁ ⋯ b_{n-1})⁻¹` presents `G` with the single relation `x₁ ⋯ xₙ = 1`;
* `Complex.exists_presentation_of_isOpenEmbedding`: the presentation for `ℂ ∖ S` with the loop
  around `∞` (from `Complex.exists_ordered_freeGroupBasis_of_isOpenEmbedding`);
* `Complex.exists_presentation_fundamentalGroup_compl_of_infty_mem`: the presentation for
  `ℙ¹(ℂ) ∖ T` when `∞ ∈ T`.

The case `∞ ∉ T` is not done here (planned: van Kampen with `ℙ¹(ℂ) ∖ (T ∪ {∞})` and a disc
around `∞`, which kills the loop around `∞`).

This is the topological input of SGA 1 XIII.2.12 for `(g, n) = (0, n)` in characteristic `0`.

## References

* [A. Hatcher, *Algebraic Topology*, §1.2][hatcher02]
* [SGA 1, Exposé XIII, 2.12][grothendieck1971]
-/

open Set Topology CategoryTheory OnePoint

noncomputable section

namespace FreeGroup

/-- The relator `x₁ x₂ ⋯ xₙ` of the free group on `n` letters. -/
def prodRelator (n : ℕ) : FreeGroup (Fin n) := (List.ofFn fun i ↦ FreeGroup.of i).prod

lemma lift_prodRelator {G : Type*} [Group G] {n : ℕ} (σ : Fin n → G) :
    FreeGroup.lift σ (prodRelator n) = (List.ofFn σ).prod := by
  rw [prodRelator, map_list_prod, List.map_ofFn]
  congr 1
  exact List.ofFn_inj.mpr (funext fun i ↦ FreeGroup.lift_apply_of)

end FreeGroup

namespace Fin

variable {G : Type*} [Group G] {n : ℕ}

/-- `b₁, …, bₙ, (b₁ ⋯ bₙ)⁻¹`: the family `b` followed by the inverse of its product, so that the
product of all `n + 1` terms is `1` (`Fin.prod_ofFn_snocProdInv`). -/
def snocProdInv (b : Fin n → G) : Fin (n + 1) → G := Fin.snoc b ((List.ofFn b).prod)⁻¹

@[simp] lemma snocProdInv_castSucc (b : Fin n → G) (i : Fin n) :
    snocProdInv b i.castSucc = b i := by
  simp [snocProdInv]

@[simp] lemma snocProdInv_last (b : Fin n → G) :
    snocProdInv b (Fin.last n) = ((List.ofFn b).prod)⁻¹ := by
  simp [snocProdInv]

lemma prod_ofFn_snocProdInv (b : Fin n → G) : (List.ofFn (snocProdInv b)).prod = 1 := by
  rw [List.ofFn_succ', List.concat_eq_append, List.prod_append, List.prod_singleton,
    snocProdInv_last]
  simp only [snocProdInv_castSucc]
  exact mul_inv_cancel _

end Fin

namespace FreeGroupBasis

@[deprecated FreeGroup.prodRelator (since := "2026-10-04")]
alias prodRelator := FreeGroup.prodRelator

@[deprecated FreeGroup.lift_prodRelator (since := "2026-10-04")]
alias lift_prodRelator := FreeGroup.lift_prodRelator

variable {G : Type*} [Group G] {n : ℕ} (b : FreeGroupBasis (Fin n) G)

/-- `b₁, …, bₙ, (b₁ ⋯ bₙ)⁻¹` for a free basis `b` (`Fin.snocProdInv`). -/
abbrev snocInv : Fin (n + 1) → G := Fin.snocProdInv b

lemma snocInv_castSucc (i : Fin n) : b.snocInv i.castSucc = b i :=
  Fin.snocProdInv_castSucc _ i

lemma snocInv_last : b.snocInv (Fin.last n) = ((List.ofFn b).prod)⁻¹ :=
  Fin.snocProdInv_last _

lemma prod_ofFn_snocInv : (List.ofFn b.snocInv).prod = 1 :=
  Fin.prod_ofFn_snocProdInv _

lemma lift_snocInv_eq_one : ∀ r ∈ ({FreeGroup.prodRelator (n + 1)} : Set (FreeGroup (Fin (n + 1)))),
    FreeGroup.lift b.snocInv r = 1 := by
  rintro r rfl
  rw [FreeGroup.lift_prodRelator, prod_ofFn_snocInv]

/-- **A free basis plus the inverse of its product presents the group with one relation**: if
`b₁, …, bₙ` is a free basis of `G`, then `⟨x₁, …, x_{n+1} | x₁ ⋯ x_{n+1}⟩ → G`,
`xᵢ ↦ bᵢ` (`i ≤ n`), `x_{n+1} ↦ (b₁ ⋯ bₙ)⁻¹`, is bijective. -/
theorem bijective_toGroup_snoc :
    Function.Bijective (PresentedGroup.toGroup b.lift_snocInv_eq_one) := by
  set φ := PresentedGroup.toGroup b.lift_snocInv_eq_one
  let ψ : G →* PresentedGroup ({FreeGroup.prodRelator (n + 1)} : Set (FreeGroup (Fin (n + 1)))) :=
    b.lift fun i ↦ PresentedGroup.of i.castSucc
  have hψ (i : Fin n) : ψ (b i) = PresentedGroup.of i.castSucc :=
    congrFun (b.lift.symm_apply_apply fun i ↦ PresentedGroup.of i.castSucc) i
  have h1 : φ.comp ψ = MonoidHom.id G := b.ext_hom _ _ fun i ↦ by
    rw [MonoidHom.comp_apply, hψ, PresentedGroup.toGroup.of, snocInv_castSucc,
      MonoidHom.id_apply]
  have h2 : ψ.comp φ = MonoidHom.id _ := PresentedGroup.ext fun x ↦ by
    rw [MonoidHom.comp_apply, PresentedGroup.toGroup.of, MonoidHom.id_apply]
    induction x using Fin.lastCases with
    | cast i => rw [snocInv_castSucc, hψ]
    | last =>
      rw [snocInv_last, map_inv, map_list_prod, List.map_ofFn]
      -- the relation gives `x_{n+1} = (x₁ ⋯ xₙ)⁻¹`
      have hrel : (List.ofFn fun i : Fin (n + 1) ↦ (PresentedGroup.of i :
          PresentedGroup ({FreeGroup.prodRelator (n + 1)} : Set (FreeGroup (Fin (n + 1)))))).prod =
            1 := by
        have := PresentedGroup.one_of_mem (rels := {FreeGroup.prodRelator (n + 1)})
          (Set.mem_singleton (FreeGroup.prodRelator (n + 1)))
        rw [FreeGroup.prodRelator, map_list_prod, List.map_ofFn] at this
        exact this
      rw [List.ofFn_succ', List.concat_eq_append, List.prod_append, List.prod_singleton] at hrel
      rw [eq_inv_of_mul_eq_one_right hrel]
      congr 2
      exact List.ofFn_inj.mpr (funext fun i ↦ by simp [hψ])
  exact ⟨fun a a' h ↦ by
      have := congrArg ψ h
      rwa [← MonoidHom.comp_apply, ← MonoidHom.comp_apply, h2] at this,
    fun g ↦ ⟨ψ g, by rw [← MonoidHom.comp_apply, h1, MonoidHom.id_apply]⟩⟩

end FreeGroupBasis

namespace FundamentalGroup

variable {X : Type*} [TopologicalSpace X] {j : X → ℂ}

/-- Loops around `a` are loops around `0` in the translated coordinate `j - a`. -/
lemma IsLoopAround.sub {a : ℂ} {x : X} {σ : FundamentalGroup X x} (h : IsLoopAround j a σ) :
    IsLoopAround (fun y ↦ j y - a) 0 σ := by
  obtain ⟨r, hr, κ, hκ, δ, rfl⟩ := h
  have hmem (w : ↥(Metric.closedBall (0 : ℂ) r \ {0})) :
      a + (w : ℂ) ∈ Metric.closedBall a r \ {a} := by
    obtain ⟨h1, h2⟩ := w.2
    refine ⟨?_, ?_⟩
    · rw [Metric.mem_closedBall, dist_eq_norm, add_sub_cancel_left]
      simpa using h1
    · simpa using h2
  let κ' : C(↥(Metric.closedBall (0 : ℂ) r \ {0}), X) :=
    κ.comp ⟨fun w ↦ ⟨a + w, hmem w⟩, by fun_prop⟩
  have hκ' (w : ↥(Metric.closedBall (0 : ℂ) r \ {0})) : j (κ' w) - a = w := by
    change j (κ ⟨a + w, hmem w⟩) - a = w
    rw [hκ]
    ring
  have hpt : κ' ⟨0 + r, Complex.add_ofReal_mem_closedBall_diff hr⟩ =
      κ ⟨a + r, Complex.add_ofReal_mem_closedBall_diff hr⟩ := by
    change κ ⟨a + (0 + r), _⟩ = _
    congr 2
    ring
  set c := ((Complex.circlePath a r).codRestrict (Complex.range_circlePath_subset hr)).map
    κ.continuous
  set c' := ((Complex.circlePath 0 r).codRestrict (Complex.range_circlePath_subset hr)).map
    κ'.continuous
  have hc (t : unitInterval) : c t = c' t := by
    change κ ⟨Complex.circlePath a r t, _⟩ = κ ⟨a + Complex.circlePath 0 r t, _⟩
    congr 2
    rw [Complex.circlePath_apply, Complex.circlePath_apply]
    ring
  have hp : ((δ.cast rfl hpt).trans c').trans (δ.cast rfl hpt).symm =
      (δ.trans c).trans δ.symm := by
    refine Path.ext (funext fun t ↦ ?_)
    rw [Path.trans_apply, Path.trans_apply]
    split_ifs with h1
    · rw [Path.trans_apply, Path.trans_apply]
      split_ifs with h2
      · rfl
      · exact (hc _).symm
    · rfl
  exact ⟨r, hr, κ', hκ', δ.cast rfl hpt, by rw [hp]⟩

end FundamentalGroup

namespace Complex

open FundamentalGroup

/-- **`π₁(ℂ ∖ S)` as `π₁` of the projective line minus `|S| + 1` points**: for `j : X → ℂ` an open
embedding onto `ℂ ∖ S`, there are an enumeration `e` of `S` and loops `σ₀, …, σ_{n-1}, σₙ`
(`n = |S|`), `σᵢ` around `e i` and `σₙ` around `∞` (around `0` in the coordinate `1 / j`), such that
`⟨x₀, …, xₙ | x₀ ⋯ xₙ⟩ → π₁(X, x)`, `xᵢ ↦ σᵢ`, is well defined and bijective. -/
theorem exists_presentation_of_isOpenEmbedding {S : Finset ℂ} {X : Type} [TopologicalSpace X]
    {j : X → ℂ} (hj : IsOpenEmbedding j) (hjr : range j = (↑S : Set ℂ)ᶜ) (x : X) :
    ∃ (e : Fin S.card ≃ S) (σ : Fin (S.card + 1) → FundamentalGroup X x),
      (∀ i : Fin S.card, IsLoopAround j (e i : ℂ) (σ i.castSucc)) ∧
      IsLoopAround (fun z ↦ (j z)⁻¹) 0 (σ (Fin.last _)) ∧
      ∃ h : ∀ r ∈ ({FreeGroup.prodRelator (S.card + 1)} : Set (FreeGroup (Fin _))),
        FreeGroup.lift σ r = 1, Function.Bijective (PresentedGroup.toGroup h) := by
  obtain ⟨e, b, hb, hinf⟩ := exists_ordered_freeGroupBasis_of_isOpenEmbedding hj hjr x
  refine ⟨e, b.snocInv, fun i ↦ by simpa using hb i, by simpa using hinf,
    b.lift_snocInv_eq_one, b.bijective_toGroup_snoc⟩

/-- The standard coordinate of `ℙ¹(ℂ) = OnePoint ℂ` centred at `t`: `z ↦ z - a` if `t = a` is
finite, `z ↦ 1 / z` if `t = ∞`. At the pole of the coordinate (`∞`, resp. `0`) the value is the
junk value `0`; loops around `t` only use points where the coordinate is a nonzero number. -/
def sphereCoord (t : OnePoint ℂ) (z : OnePoint ℂ) : ℂ :=
  OnePoint.elim t (OnePoint.elim z 0 fun w ↦ w⁻¹) fun a ↦ OnePoint.elim z 0 fun w ↦ w - a

@[simp] lemma sphereCoord_infty_coe (w : ℂ) : sphereCoord ∞ w = w⁻¹ := rfl

@[simp] lemma sphereCoord_coe_coe (a w : ℂ) : sphereCoord a w = w - a := rfl

/-- `σ ∈ π₁(X, x)` is a *loop around `t ∈ ℙ¹(ℂ)`* (relative to `j : X → ℙ¹(ℂ)`): a loop around `0`
in the standard coordinate at `t` (`FundamentalGroup.IsLoopAround`, conjugate to a small circle
run counterclockwise in that coordinate). -/
def IsLoopAroundAt {X : Type*} [TopologicalSpace X] (j : X → OnePoint ℂ) (t : OnePoint ℂ)
    {x : X} (σ : FundamentalGroup X x) : Prop :=
  IsLoopAround (fun y ↦ sphereCoord t (j y)) 0 σ

/-- The finite points of `T ⊆ ℙ¹(ℂ)`. -/
abbrev finitePart (T : Finset (OnePoint ℂ)) : Finset ℂ :=
  T.preimage (↑) OnePoint.coe_injective.injOn

lemma mem_finitePart {T : Finset (OnePoint ℂ)} {a : ℂ} : a ∈ finitePart T ↔ (a : OnePoint ℂ) ∈ T :=
  Finset.mem_preimage

/-- **The affine coordinate of `ℙ¹(ℂ) ∖ T` for `∞ ∈ T`**: `ℙ¹(ℂ) ∖ T → ℂ` is an open embedding
onto `ℂ ∖ S`, `S` the finite points of `T`. -/
lemma exists_coord_of_infty_mem (T : Finset (OnePoint ℂ)) (hT : (∞ : OnePoint ℂ) ∈ T) :
    ∃ j : ((↑T : Set (OnePoint ℂ))ᶜ : Set (OnePoint ℂ)) → ℂ, IsOpenEmbedding j ∧
      range j = (↑(finitePart T) : Set ℂ)ᶜ ∧
        ∀ y : ((↑T : Set (OnePoint ℂ))ᶜ : Set (OnePoint ℂ)), (y : OnePoint ℂ) = (j y : ℂ) := by
  classical
  set S : Finset ℂ := finitePart T
  have hST (a : ℂ) : a ∈ S ↔ (a : OnePoint ℂ) ∈ T := Finset.mem_preimage
  -- `ℙ¹(ℂ) ∖ T ≅ ℂ ∖ S`
  have hsub : ((↑T : Set (OnePoint ℂ))ᶜ) ⊆ range ((↑) : ℂ → OnePoint ℂ) := by
    intro z hz
    induction z using OnePoint.rec with
    | infty => exact absurd hT hz
    | coe a => exact mem_range_self a
  have hpre : ((↑) : ℂ → OnePoint ℂ) ⁻¹' ((↑T : Set (OnePoint ℂ))ᶜ) = (↑S : Set ℂ)ᶜ := by
    ext a
    simp [hST]
  let Φ : ((↑S : Set ℂ)ᶜ : Set ℂ) ≃ₜ ((↑T : Set (OnePoint ℂ))ᶜ : Set (OnePoint ℂ)) :=
    (Homeomorph.setCongr hpre.symm).trans
      (OnePoint.isOpenEmbedding_coe.isEmbedding.homeomorphOfSubsetRange hsub)
  have hΦ (z : ((↑S : Set ℂ)ᶜ : Set ℂ)) : ((Φ z : OnePoint ℂ)) = ((z : ℂ) : OnePoint ℂ) := rfl
  set j : ((↑T : Set (OnePoint ℂ))ᶜ : Set (OnePoint ℂ)) → ℂ := fun y ↦ (Φ.symm y : ℂ)
  have hjy (y : ((↑T : Set (OnePoint ℂ))ᶜ : Set (OnePoint ℂ))) : (y : OnePoint ℂ) = (j y : ℂ) := by
    have := hΦ (Φ.symm y)
    rw [Φ.apply_symm_apply] at this
    exact this
  have hj : IsOpenEmbedding j :=
    (S.finite_toSet.isClosed.isOpen_compl.isOpenEmbedding_subtypeVal).comp
      Φ.symm.isOpenEmbedding
  have hjr : range j = (↑S : Set ℂ)ᶜ := by
    change range (Subtype.val ∘ Φ.symm) = _
    rw [range_comp, Φ.symm.range_coe, image_univ, Subtype.range_coe]
  exact ⟨j, hj, hjr, hjy⟩

/-- **`π₁` of `ℙ¹(ℂ)` minus `n ≥ 1` points, one of them `∞`.** For `T ⊆ ℙ¹(ℂ)` finite with
`∞ ∈ T`, at every base point `x` of `ℙ¹(ℂ) ∖ T` there are an enumeration `e : Fin m ≃ T` and loops
`σ₁, …, σ_m` (`σᵢ` around `e i`) such that `⟨x₁, …, x_m | x₁ ⋯ x_m⟩ → π₁(ℙ¹(ℂ) ∖ T, x)`,
`xᵢ ↦ σᵢ`, is well defined and bijective. The order of the points is not arbitrary: it is the
one produced by the proof (`exists_ordered_freeGroupBasis_of_isOpenEmbedding`). -/
theorem exists_presentation_fundamentalGroup_compl_of_infty_mem (T : Finset (OnePoint ℂ))
    (hT : (∞ : OnePoint ℂ) ∈ T) (x : ((↑T : Set (OnePoint ℂ))ᶜ : Set (OnePoint ℂ))) :
    ∃ (m : ℕ) (e : Fin m ≃ T) (σ : Fin m → FundamentalGroup ((↑T : Set (OnePoint ℂ))ᶜ : Set _) x),
      (∀ i, IsLoopAroundAt Subtype.val (e i : OnePoint ℂ) (σ i)) ∧
      ∃ h : ∀ r ∈ ({FreeGroup.prodRelator m} : Set (FreeGroup (Fin m))),
        FreeGroup.lift σ r = 1, Function.Bijective (PresentedGroup.toGroup h) := by
  classical
  set S : Finset ℂ := finitePart T
  have hST (a : ℂ) : a ∈ S ↔ (a : OnePoint ℂ) ∈ T := Finset.mem_preimage
  obtain ⟨j, hj, hjr, hjy⟩ := exists_coord_of_infty_mem T hT
  obtain ⟨e, σ, hσ, hinf, h, hbij⟩ := exists_presentation_of_isOpenEmbedding hj hjr x
  -- the enumeration of `T`: the points of `S`, then `∞`
  let f : Fin (S.card + 1) → T := Fin.lastCases ⟨∞, hT⟩
    fun i ↦ ⟨((e i : ℂ) : OnePoint ℂ), (hST _).mp (e i).2⟩
  have hf : Function.Bijective f := by
    refine ⟨fun a b hab ↦ ?_, fun t ↦ ?_⟩
    · induction a using Fin.lastCases with
      | last =>
        induction b using Fin.lastCases with
        | last => rfl
        | cast b =>
          simp only [f, Fin.lastCases_last, Fin.lastCases_castSucc, Subtype.mk.injEq] at hab
          exact absurd hab.symm (OnePoint.coe_ne_infty _)
      | cast a =>
        induction b using Fin.lastCases with
        | last =>
          simp only [f, Fin.lastCases_last, Fin.lastCases_castSucc, Subtype.mk.injEq] at hab
          exact absurd hab (OnePoint.coe_ne_infty _)
        | cast b =>
          simp only [f, Fin.lastCases_castSucc, Subtype.mk.injEq] at hab
          rw [e.injective (Subtype.ext (OnePoint.coe_injective hab))]
    · obtain ⟨t, ht⟩ := t
      induction t using OnePoint.rec with
      | infty => exact ⟨Fin.last _, by simp [f]⟩
      | coe a =>
        obtain ⟨i, hi⟩ := e.surjective ⟨a, (hST a).mpr ht⟩
        exact ⟨i.castSucc, by simp [f, hi]⟩
  refine ⟨S.card + 1, Equiv.ofBijective f hf, σ, fun i ↦ ?_, h, hbij⟩
  induction i using Fin.lastCases with
  | last =>
    simp only [Equiv.ofBijective_apply, f, Fin.lastCases_last]
    unfold IsLoopAroundAt
    convert hinf using 2 with y
    rw [hjy y]
    rfl
  | cast i =>
    simp only [Equiv.ofBijective_apply, f, Fin.lastCases_castSucc]
    unfold IsLoopAroundAt
    convert (hσ i).sub using 2 with y
    rw [hjy y]
    rfl

end Complex
