/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.Foundations.Topology.SurfaceSchreierWord

/-!
# Spanning trees of the Schreier graph and Schreier transversals

Let `F` act transitively on a finite set `Φ`, generated by `σ₀, …, σₙ`, and let `φ₀ ∈ Φ`. There is
an ordering `φ₀, ψ₁, …, ψ_{d-1}` of `Φ`, a spanning tree of the Schreier graph (one edge from each
`ψₖ` to an earlier point, `Ribbon.Schreier.TreeCond`) and a transversal `t : Φ → F`
(`t ψ • φ₀ = ψ`, `t φ₀ = 1`) for which the edges of the tree have label `1`
(`Ribbon.Schreier.exists_tree`).

## References

* [W. Magnus, A. Karrass, D. Solitar, *Combinatorial Group Theory*, §2.3][magnus1966]
-/

open Function

namespace Ribbon.Schreier

variable {F : Type*} [Group F] {Φ : Type*} [MulAction F Φ] {n : ℕ} (σ : Fin (n + 1) → F)

/-- The spanning-tree condition on the level of vertices: the `k`-th dart of `T` lies at the
`k`-th point of `rest` and its partner at a point of `A` or at an earlier point of `rest`. -/
def TreeCond : List Φ → List Φ → List (Dart Φ n) → Prop
  | _, [], [] => True
  | A, ψ :: rest, d :: T => vtx σ d = ψ ∧ vtx σ (flip d) ∈ A ∧ TreeCond (A ++ [ψ]) rest T
  | _, _, _ => False

lemma TreeCond.length_eq : ∀ {A rest : List Φ} {T : List (Dart Φ n)}, TreeCond σ A rest T →
    T.length = rest.length
  | _, [], [], _ => rfl
  | _, _ :: _, _ :: _, h => by simp [h.2.2.length_eq]
  | _, [], _ :: _, h => h.elim
  | _, _ :: _, [], h => h.elim

lemma TreeCond.append : ∀ {A rest : List Φ} {T : List (Dart Φ n)} {ψ : Φ} {d : Dart Φ n},
    TreeCond σ A rest T → vtx σ d = ψ → vtx σ (flip d) ∈ A ++ rest →
    TreeCond σ A (rest ++ [ψ]) (T ++ [d])
  | _, [], [], _, _, _, h1, h2 => ⟨h1, by simpa using h2, trivial⟩
  | A, ψ' :: rest, d' :: T, _, _, h, h1, h2 => by
    obtain ⟨h₁, h₂, h₃⟩ := h
    exact ⟨h₁, h₂, h₃.append h1 (by simpa using h2)⟩
  | _, [], _ :: _, _, _, h, _, _ => h.elim
  | _, _ :: _, [], _, _, h, _, _ => h.elim

lemma TreeCond.mem : ∀ {A rest : List Φ} {T : List (Dart Φ n)}, TreeCond σ A rest T →
    ∀ d ∈ T, vtx σ d ∈ rest ∧ vtx σ (flip d) ∈ A ++ rest
  | _, [], [], _, d, hd => by simp at hd
  | A, ψ :: rest, d' :: T, h, d, hd => by
    obtain ⟨h₁, h₂, h₃⟩ := h
    rcases List.mem_cons.mp hd with rfl | hd
    · exact ⟨h₁ ▸ List.mem_cons_self .., List.mem_append_left _ h₂⟩
    · obtain ⟨h4, h5⟩ := h₃.mem d hd
      exact ⟨List.mem_cons_of_mem _ h4, by simpa using h5⟩
  | _, [], _ :: _, h, _, _ => h.elim
  | _, _ :: _, [], h, _, _ => h.elim

/-- The rotation at `ψ`, as a list. -/
noncomputable def rotList [Finite Φ] (ψ : Φ) : List (Dart Φ n) := cyc (rot σ) ((ψ, 0), true)

lemma mem_rotList [Finite Φ] {ψ : Φ} {d : Dart Φ n} : d ∈ rotList σ ψ ↔ vtx σ d = ψ := by
  rw [rotList, mem_cyc, sameCycle_rot_iff]

lemma two_le_length_rotList [Finite Φ] (ψ : Φ) : 2 ≤ (rotList σ ψ).length := by
  rw [rotList, length_cyc]
  have h0 := minimalPeriod_perm_pos (rot σ) ((ψ, 0), true)
  have h1 : minimalPeriod (rot σ) ((ψ, 0), true) ≠ 1 := by
    intro h
    have := iterate_minimalPeriod (f := rot σ) (x := ((ψ, 0), true))
    rw [h, iterate_one] at this
    simp at this
  omega

/-- The vertex-level spanning-tree condition gives tree darts for the rotations. -/
lemma TreeCond.isTreeDarts [Finite Φ] : ∀ {A rest : List Φ} {T : List (Dart Φ n)}
    {AR : List (Dart Φ n)}, TreeCond σ A rest T → (∀ d, vtx σ d ∈ A → d ∈ AR) →
    IsTreeDarts AR T (rest.map (rotList σ))
  | _, [], [], _, _, _ => trivial
  | A, ψ :: rest, d :: T, AR, h, hA => by
    obtain ⟨h₁, h₂, h₃⟩ := h
    refine ⟨(mem_rotList σ).mpr h₁, hA _ h₂, h₃.isTreeDarts fun d' hd' ↦ ?_⟩
    rcases List.mem_append.mp hd' with hd' | hd'
    · exact List.mem_append_left _ (hA d' hd')
    · exact List.mem_append_right _ ((mem_rotList σ).mpr (List.mem_singleton.mp hd'))
  | _, [], _ :: _, _, h, _ => h.elim
  | _, _ :: _, [], _, h, _ => h.elim

/-- A finite set `S` that is stable under the generators `σᵢ` and their inverses is stable under
the group they generate. -/
lemma smul_mem_of_closure {S : List Φ} (hS : ∀ ψ ∈ S, ∀ i, σ i • ψ ∈ S ∧ (σ i)⁻¹ • ψ ∈ S)
    {g : F} (hg : g ∈ Subgroup.closure (Set.range σ)) : ∀ ψ ∈ S, g • ψ ∈ S := by
  induction hg using Subgroup.closure_induction'' with
  | mem x hx =>
    obtain ⟨i, rfl⟩ := hx
    exact fun ψ hψ ↦ (hS ψ hψ i).1
  | inv_mem x hx =>
    obtain ⟨i, rfl⟩ := hx
    exact fun ψ hψ ↦ (hS ψ hψ i).2
  | one => exact fun ψ hψ ↦ by rwa [one_smul]
  | mul x y _ _ hx hy => exact fun ψ hψ ↦ by rw [mul_smul]; exact hx _ (hy ψ hψ)

/-- The invariant of the construction of the spanning tree. -/
def TreeInv (φ₀ : Φ) (rest : List Φ) (T : List (Dart Φ n)) (t : Φ → F) : Prop :=
  (φ₀ :: rest).Nodup ∧ TreeCond σ [φ₀] rest T ∧ t φ₀ = 1 ∧
    (∀ ψ ∈ φ₀ :: rest, t ψ • φ₀ = ψ) ∧ (T.map Prod.fst).Nodup ∧
    ∀ d ∈ T, edgeLabel σ t d.1 = 1 ∧ d.1.1 ∈ φ₀ :: rest ∧ (σ d.1.2)⁻¹ • d.1.1 ∈ φ₀ :: rest

/-- One step of the construction: attach a new point to the tree. -/
lemma TreeInv.step {φ₀ : Φ} {rest : List Φ} {T : List (Dart Φ n)} {t : Φ → F}
    (h : TreeInv σ φ₀ rest T t) {ψ w : Φ} (hψ : ψ ∈ φ₀ :: rest) (hw : w ∉ φ₀ :: rest)
    {i : Fin (n + 1)} (hiw : (σ i)⁻¹ • ψ = w ∨ σ i • ψ = w) :
    ∃ T' t', TreeInv σ φ₀ (rest ++ [w]) T' t' := by
  classical
  obtain ⟨hnd, hT, ht0, htψ, hTn, hlab⟩ := h
  have hupd : ∀ ψ' ∈ φ₀ :: rest, ∀ g, update t w g ψ' = t ψ' := fun ψ' hψ' g ↦
    update_of_ne (fun h' : ψ' = w ↦ hw (h' ▸ hψ')) _ _
  have hnd' : (φ₀ :: (rest ++ [w])).Nodup := by
    rw [← List.cons_append, List.nodup_append]
    refine ⟨hnd, List.nodup_singleton w, fun a ha b hb hab ↦ hw ?_⟩
    rw [List.mem_singleton.mp hb] at hab
    exact hab ▸ ha
  have hmem' : ∀ ψ' ∈ φ₀ :: rest, ψ' ∈ φ₀ :: (rest ++ [w]) := fun ψ' hψ' ↦ by
    rcases List.mem_cons.mp hψ' with rfl | h'
    · exact List.mem_cons_self ..
    · exact List.mem_cons_of_mem _ (List.mem_append_left _ h')
  have hwmem : w ∈ φ₀ :: (rest ++ [w]) := by simp
  rcases hiw with hiw | hiw
  · -- the edge `(ψ, i)` from `ψ` to `w = σᵢ⁻¹ • ψ`; tree dart `((ψ, i), false)` at `w`
    refine ⟨T ++ [((ψ, i), false)], update t w ((σ i)⁻¹ * t ψ), hnd', ?_, ?_, ?_, ?_, ?_⟩
    · exact hT.append σ (by simpa using hiw) (by simpa [flip] using hψ)
    · rw [hupd φ₀ (List.mem_cons_self ..), ht0]
    · intro ψ' hψ'
      rcases List.mem_cons.mp hψ' with rfl | hψ'
      · rw [hupd _ (List.mem_cons_self ..), htψ _ (List.mem_cons_self ..)]
      rcases List.mem_append.mp hψ' with hψ' | hψ'
      · rw [hupd _ (List.mem_cons_of_mem _ hψ'), htψ _ (List.mem_cons_of_mem _ hψ')]
      · rw [List.mem_singleton.mp hψ', update_self, mul_smul, htψ _ hψ, hiw]
    · rw [List.map_append, List.nodup_append]
      refine ⟨hTn, List.nodup_singleton _, fun a ha b hb hab ↦ ?_⟩
      rw [List.mem_singleton.mp hb] at hab
      obtain ⟨d, hd, rfl⟩ := List.mem_map.mp ha
      have := (hlab d hd).2.2
      rw [hab] at this
      exact hw (hiw ▸ this)
    · intro d hd
      rcases List.mem_append.mp hd with hd | hd
      · obtain ⟨h1, h2, h3⟩ := hlab d hd
        refine ⟨?_, hmem' _ h2, hmem' _ h3⟩
        rw [edgeLabel, hupd _ h2, hupd _ h3]
        exact h1
      · rw [List.mem_singleton.mp hd]
        refine ⟨?_, hmem' _ hψ, by rw [hiw]; exact hwmem⟩
        simp only [edgeLabel]
        rw [hupd _ hψ, hiw, update_self]
        group
  · -- the edge `(w, i)` from `w = σᵢ • ψ` to `ψ`; tree dart `((w, i), true)` at `w`
    have hψ' : (σ i)⁻¹ • w = ψ := by rw [← hiw, inv_smul_smul]
    refine ⟨T ++ [((w, i), true)], update t w (σ i * t ψ), hnd', ?_, ?_, ?_, ?_, ?_⟩
    · exact hT.append σ rfl (by simpa [flip, hψ'] using hψ)
    · rw [hupd φ₀ (List.mem_cons_self ..), ht0]
    · intro ψ' hψ''
      rcases List.mem_cons.mp hψ'' with rfl | hψ''
      · rw [hupd _ (List.mem_cons_self ..), htψ _ (List.mem_cons_self ..)]
      rcases List.mem_append.mp hψ'' with hψ'' | hψ''
      · rw [hupd _ (List.mem_cons_of_mem _ hψ''), htψ _ (List.mem_cons_of_mem _ hψ'')]
      · rw [List.mem_singleton.mp hψ'', update_self, mul_smul, htψ _ hψ, hiw]
    · rw [List.map_append, List.nodup_append]
      refine ⟨hTn, List.nodup_singleton _, fun a ha b hb hab ↦ ?_⟩
      rw [List.mem_singleton.mp hb] at hab
      obtain ⟨d, hd, rfl⟩ := List.mem_map.mp ha
      have := (hlab d hd).2.1
      rw [hab] at this
      exact hw this
    · intro d hd
      rcases List.mem_append.mp hd with hd | hd
      · obtain ⟨h1, h2, h3⟩ := hlab d hd
        refine ⟨?_, hmem' _ h2, hmem' _ h3⟩
        rw [edgeLabel, hupd _ h2, hupd _ h3]
        exact h1
      · rw [List.mem_singleton.mp hd]
        refine ⟨?_, hwmem, by rw [hψ']; exact hmem' _ hψ⟩
        simp only [edgeLabel]
        rw [hψ', update_self, hupd _ hψ]
        group

/-- **Existence of a spanning tree with a Schreier transversal.** If the `σᵢ` generate `F` and `F`
acts transitively on the finite set `Φ`, there are an ordering `φ₀ :: rest` of `Φ`, tree darts
`T` (`Ribbon.Schreier.TreeCond`) on distinct edges, and a transversal `t` (`t ψ • φ₀ = ψ`,
`t φ₀ = 1`) for which the tree edges have label `1`. -/
theorem exists_tree [Finite Φ] (hgen : ∀ g : F, g ∈ Subgroup.closure (Set.range σ)) (φ₀ : Φ)
    (htrans : ∀ ψ : Φ, ∃ g : F, g • φ₀ = ψ) :
    ∃ (rest : List Φ) (T : List (Dart Φ n)) (t : Φ → F), TreeInv σ φ₀ rest T t ∧
      ∀ ψ, ψ ∈ φ₀ :: rest := by
  have key : ∀ k : ℕ, ∀ rest T t, Nat.card Φ - rest.length = k → TreeInv σ φ₀ rest T t →
      ∃ (rest' : List Φ) (T' : List (Dart Φ n)) (t' : Φ → F), TreeInv σ φ₀ rest' T' t' ∧
        ∀ ψ, ψ ∈ φ₀ :: rest' := by
    intro k
    induction k using Nat.strong_induction_on with
    | _ k ih =>
    intro rest T t hk h
    by_cases hall : ∀ ψ, ψ ∈ φ₀ :: rest
    · exact ⟨rest, T, t, h, hall⟩
    -- some generator leads out of the current set
    have hout : ∃ ψ ∈ φ₀ :: rest, ∃ i : Fin (n + 1), ∃ w ∉ φ₀ :: rest,
        (σ i)⁻¹ • ψ = w ∨ σ i • ψ = w := by
      by_contra hno
      apply hall
      intro ψ'
      obtain ⟨g, rfl⟩ := htrans ψ'
      refine smul_mem_of_closure σ (fun ψ hψ i ↦ ⟨?_, ?_⟩) (hgen g) φ₀ (List.mem_cons_self ..)
      · by_contra hc
        exact hno ⟨ψ, hψ, i, _, hc, Or.inr rfl⟩
      · by_contra hc
        exact hno ⟨ψ, hψ, i, _, hc, Or.inl rfl⟩
    obtain ⟨ψ, hψ, i, w, hw, hiw⟩ := hout
    obtain ⟨T', t', h'⟩ := h.step σ hψ hw hiw
    have hlen : (φ₀ :: (rest ++ [w])).length ≤ Nat.card Φ := by
      have := Fintype.ofFinite Φ
      rw [Nat.card_eq_fintype_card]
      exact h'.1.length_le_card
    refine ih (Nat.card Φ - (rest ++ [w]).length) ?_ _ _ _ rfl h'
    rw [← hk]
    simp only [List.length_append, List.length_cons] at hlen ⊢
    omega
  exact key _ [] [] (fun _ ↦ 1) rfl
    ⟨List.nodup_singleton _, trivial, by simp, fun ψ hψ ↦ by simp [List.mem_singleton.mp hψ],
      List.nodup_nil, fun d hd ↦ by simp at hd⟩

end Ribbon.Schreier
