/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.Foundations.Topology.SurfaceLoopAround

/-!
# The fundamental group of the plane minus finitely many points: ordered generators

Let `S ⊆ ℂ` be finite with `n` elements. We show (`Complex.exists_ordered_freeGroupBasis`) that
there are an enumeration `s₀, …, s_{n-1}` of `S` and a free basis `σ₀, …, σ_{n-1}` of
`π₁(ℂ ∖ S, x)` such that `σᵢ` is a loop around `sᵢ` and `(σ₀ ⋯ σ_{n-1})⁻¹` is a loop around `∞`
(a loop around `0` in the coordinate `1/z`). Equivalently (`ℂ ∖ S = ℙ¹(ℂ) ∖ (S ∪ {∞})`),
`π₁(ℙ¹(ℂ) ∖ (S ∪ {∞}))` is generated by loops `σ₀, …, σ_{n-1}, σ_∞` around the `n + 1` punctures
with the single relation `σ₀ ⋯ σ_{n-1} σ_∞ = 1`; this presentation is
`Complex.exists_presentation_of_isOpenEmbedding`
(in `SGA.Foundations.Topology.SurfacePresentation`).
This is the topological input of SGA 1 XIII.2.12 for the projective line in characteristic `0`.

## Proof

Choose a real linear form `v = re + ε im` injective on `S`, number the points so that `v` increases,
and cut the plane by the lines `v = xᵢ` (`x₀ < v(s₀) < x₁ < ⋯ < v(s_{n-1}) < xₙ`). Let `Rᵢ` be the
parallelogram `xᵢ ≤ v ≤ xᵢ₊₁`, `-(R + 1) ≤ im ≤ R + 1` (it contains `sᵢ` and no other point), and
`σᵢ` the loop that runs along the bottom edge of the big parallelogram `R₀ ∪ ⋯ ∪ R_{n-1}` from its
corner `p` to the corner of `Rᵢ`, around `∂Rᵢ` counterclockwise, and back. Then:

* `σᵢ` is a loop around `sᵢ`: `∂Rᵢ` winds once around `sᵢ` (`Complex.exists_log_quadPath`), so
  it is conjugate to a small circle (`Path.WindsOnceAround.isLoopAround`);
* the `σᵢ` form a free basis: induction on the half-planes `v < xₖ + η` with van Kampen
  (`FundamentalGroup.existsUnique_hom_of_union`), adding one strip at a time; the strips meet in
  thin convex strips without points;
* `σ₀ ⋯ σ_{n-1} = ∂(R₀ ∪ ⋯ ∪ R_{n-1})`: the vertical edges between consecutive parallelograms
  cancel (an identity in the fundamental groupoid), and the bottom and top edges merge (they lie
  in convex sets without points). The big parallelogram lies outside a disc containing `S`, and
  winds once around `0`; in the coordinate `1/z` its reverse winds once around `0`, so it is a
  loop around `∞`.

## References

* [A. Hatcher, *Algebraic Topology*, §1.2][hatcher02]
* [SGA 1, Exposé XIII, 2.12][grothendieck1971]
-/

open Set Topology CategoryTheory Metric Real

noncomputable section

namespace Complex

namespace OrderedPunctures

/-- The real linear form `v_ε z = re z + ε im z`. -/
def shearRe (ε : ℝ) (z : ℂ) : ℝ := z.re + ε * z.im

/-- The point with `v_ε = x` and imaginary part `y`. -/
def shearPt (ε x y : ℝ) : ℂ := ⟨x - ε * y, y⟩

@[simp] lemma shearRe_shearPt (ε x y : ℝ) : shearRe ε (shearPt ε x y) = x := by
  simp [shearRe, shearPt]

@[simp] lemma im_shearPt (ε x y : ℝ) : (shearPt ε x y).im = y := rfl

lemma shearRe_isLinearMap (ε : ℝ) : IsLinearMap ℝ (shearRe ε) :=
  ⟨fun a b ↦ by simp [shearRe]; ring, fun c a ↦ by simp [shearRe]; ring⟩

lemma continuous_shearRe (ε : ℝ) : Continuous (shearRe ε) := by
  unfold shearRe
  fun_prop

/-- The geometric data of the proof: a linear form `v = re + ε im` injective on `S`, an
enumeration `e` of `S` along which `v` increases, cut values `xᵢ` separating the points, a margin
`η`, and a radius `R` with `S ⊆ D(0, R)`; the outer cut values are far enough that the big
parallelogram lies outside `D(0, R)`. -/
private structure StripData (S : Finset ℂ) where
  ε : ℝ
  e : Fin S.card ≃ S
  x : ℕ → ℝ
  η : ℝ
  R : ℝ
  η_pos : 0 < η
  R_pos : 0 < R
  norm_lt : ∀ s ∈ S, ‖s‖ < R
  x_mono : Monotone x
  x_lt : ∀ i : Fin S.card, x i < shearRe ε (e i)
  lt_x : ∀ i : Fin S.card, shearRe ε (e i) < x (i + 1)
  gap : ∀ i ≤ S.card, ∀ s ∈ S, η < |x i - shearRe ε s|
  x_zero : x 0 < -(R + |ε| * (R + 1))
  x_card : R + |ε| * (R + 1) < x S.card

/-- A finite set of positive reals has a positive strict lower bound. -/
private lemma exists_pos_lt_of_finset (T : Finset ℝ) (hT : ∀ t ∈ T, 0 < t) :
    ∃ η > 0, ∀ t ∈ T, η < t := by
  rcases T.eq_empty_or_nonempty with rfl | hne
  · exact ⟨1, one_pos, by simp⟩
  · refine ⟨T.min' hne / 2, half_pos (hT _ (T.min'_mem hne)), fun t ht ↦ ?_⟩
    have h1 := T.min'_le t ht
    have h2 := hT _ (T.min'_mem hne)
    linarith

private theorem exists_stripData (S : Finset ℂ) (hS : S.Nonempty) : Nonempty (StripData S) := by
  classical
  -- a linear form injective on `S`
  obtain ⟨ε, hε⟩ : ∃ ε : ℝ, ε ∉ (S ×ˢ S).image (fun p ↦ (p.2.re - p.1.re) / (p.1.im - p.2.im)) :=
    Infinite.exists_notMem_finset _
  have hinj : Set.InjOn (shearRe ε) S := by
    intro a ha b hb hab
    by_contra hne
    simp only [shearRe] at hab
    by_cases him : a.im = b.im
    · exact hne (Complex.ext (by rw [him] at hab; linarith) him)
    · refine hε (Finset.mem_image.mpr ⟨(a, b), Finset.mem_product.mpr ⟨ha, hb⟩, ?_⟩)
      have : a.im - b.im ≠ 0 := sub_ne_zero.mpr him
      field_simp
      linarith
  -- the enumeration along `v`
  set T := S.image (shearRe ε)
  have hT : T.card = S.card := Finset.card_image_of_injOn hinj
  let f : S ≃ T := Equiv.ofBijective (fun s ↦ ⟨shearRe ε s, Finset.mem_image_of_mem _ s.2⟩)
    ⟨fun a b h ↦ Subtype.ext (hinj a.2 b.2 (congrArg Subtype.val h)), fun t ↦ by
      obtain ⟨s, hs, hst⟩ := Finset.mem_image.mp t.2
      exact ⟨⟨s, hs⟩, Subtype.ext hst⟩⟩
  let o := T.orderIsoOfFin hT
  let e : Fin S.card ≃ S := o.toEquiv.trans f.symm
  have he (i : Fin S.card) : shearRe ε (e i) = o i := by
    have := congrArg Subtype.val (f.apply_symm_apply (o i))
    exact this
  have hmono : StrictMono fun i : Fin S.card ↦ shearRe ε (e i) := by
    intro a b hab
    change shearRe ε (e a) < shearRe ε (e b)
    rw [he, he]
    exact o.strictMono hab
  -- the radius
  set R : ℝ := 1 + ∑ s ∈ S, ‖s‖
  have hR : 0 < R := by positivity
  have hSR (s : ℂ) (hs : s ∈ S) : ‖s‖ < R := by
    have := Finset.single_le_sum (f := fun s ↦ ‖s‖) (fun _ _ ↦ norm_nonneg _) hs
    simp only [R]
    linarith
  set M : ℝ := R + |ε| * (R + 1) + 1
  have hMpos : 0 < M := by positivity
  have hvM (s : ℂ) (hs : s ∈ S) : |shearRe ε s| < M := by
    have h1 := hSR s hs
    have hre := Complex.abs_re_le_norm s
    have him := Complex.abs_im_le_norm s
    calc |shearRe ε s| ≤ |s.re| + |ε| * |s.im| := by
          unfold shearRe
          calc |s.re + ε * s.im| ≤ |s.re| + |ε * s.im| := abs_add_le _ _
            _ = |s.re| + |ε| * |s.im| := by rw [abs_mul]
      _ ≤ ‖s‖ + |ε| * ‖s‖ := by gcongr
      _ < M := by
          simp only [M]
          nlinarith [abs_nonneg ε, norm_nonneg s]
  have hn : 0 < S.card := Finset.card_pos.mpr hS
  -- the cut values: `-M`, the midpoints of consecutive values of `v`, then `M`
  let w : ℕ → ℝ := fun i ↦ if h : i < S.card then shearRe ε (e ⟨i, h⟩) else M
  have hw (i : Fin S.card) : w i = shearRe ε (e i) := by simp [w, i.2]
  have hwM (i : ℕ) : -M < w i ∧ w i ≤ M := by
    by_cases h : i < S.card
    · have := hvM _ (e ⟨i, h⟩).2
      simp only [w, h, ↓reduceDIte]
      constructor <;> linarith [abs_lt.mp this]
    · simp only [w, h, ↓reduceDIte]
      constructor <;> linarith
  have hwmono : Monotone w := by
    intro a b hab
    by_cases hb : b < S.card
    · have ha : a < S.card := lt_of_le_of_lt hab hb
      simp only [w, ha, hb, ↓reduceDIte]
      exact hmono.monotone (Fin.mk_le_mk.mpr hab)
    · simp only [w, hb, ↓reduceDIte]
      exact (hwM a).2
  have hwlt (a b : ℕ) (hab : a < b) (hb : b < S.card) : w a < w b := by
    have ha : a < S.card := hab.trans hb
    simp only [w, ha, hb, ↓reduceDIte]
    exact hmono (Fin.mk_lt_mk.mpr hab)
  let x : ℕ → ℝ := fun i ↦ if i = 0 then -M else if i < S.card then (w (i - 1) + w i) / 2 else M
  have hxge (i : ℕ) : -M ≤ x i := by
    simp only [x]
    split_ifs
    · exact le_rfl
    · linarith [hwM (i - 1), hwM i]
    · linarith
  have hx_mono : Monotone x := by
    intro a b hab
    rcases Nat.eq_zero_or_pos a with rfl | ha
    · simpa [x] using hxge b
    · have hb : b ≠ 0 := by omega
      simp only [x, show a ≠ 0 by omega, hb, ↓reduceIte]
      split_ifs with h1 h2 h2
      · linarith [hwmono (show a - 1 ≤ b - 1 by omega), hwmono hab]
      · linarith [hwM (a - 1), hwM a]
      · omega
      · exact le_rfl
  have hx_lt (i : Fin S.card) : x i < shearRe ε (e i) := by
    rw [← hw]
    simp only [x]
    split_ifs with h0 h1
    · exact (hwM i).1
    · linarith [hwlt (i - 1) i (by omega) i.2]
    · exact absurd i.2 h1
  have hlt_x (i : Fin S.card) : shearRe ε (e i) < x (i + 1) := by
    rw [← hw]
    simp only [x, Nat.succ_ne_zero, ↓reduceIte]
    split_ifs with h1
    · rw [Nat.add_sub_cancel]
      linarith [hwlt i (i + 1) (by omega) h1]
    · have := hvM _ (e i).2
      rw [hw]
      linarith [abs_lt.mp this]
  -- `x i ≠ v s` for `i ≤ n` and `s ∈ S`
  have hxv (i : ℕ) (hi : i ≤ S.card) (s : ℂ) (hs : s ∈ S) : x i ≠ shearRe ε s := by
    obtain ⟨k, hk⟩ := e.surjective ⟨s, hs⟩
    have hks : shearRe ε s = w k := by rw [hw, hk]
    rw [hks]
    intro heq
    by_cases hki : (k : ℕ) < i
    · have h1 := hlt_x k
      have h2 : x (k + 1) ≤ x i := hx_mono (by omega)
      rw [← hw] at h1
      linarith
    · have h1 := hx_lt k
      have h2 : x i ≤ x k := hx_mono (by omega)
      rw [← hw] at h1
      linarith
  obtain ⟨η, hη, hηlt⟩ := exists_pos_lt_of_finset
    (((Finset.range (S.card + 1)) ×ˢ S).image (fun p ↦ |x p.1 - shearRe ε p.2|)) (by
      intro t ht
      obtain ⟨⟨i, s⟩, hp, rfl⟩ := Finset.mem_image.mp ht
      obtain ⟨hi, hs⟩ := Finset.mem_product.mp hp
      exact abs_pos.mpr (sub_ne_zero.mpr (hxv i (by simpa [Nat.lt_succ_iff] using hi) s hs)))
  refine ⟨⟨ε, e, x, η, R, hη, hR, hSR, hx_mono, hx_lt, hlt_x, fun i hi s hs ↦ hηlt _ ?_, ?_, ?_⟩⟩
  · exact Finset.mem_image.mpr ⟨(i, s), Finset.mem_product.mpr
      ⟨Finset.mem_range.mpr (Nat.lt_succ_of_le hi), hs⟩, rfl⟩
  · simp only [x, ↓reduceIte, M]
    linarith
  · simp only [x, hn.ne', lt_irrefl, ↓reduceIte, M]
    linarith

/-- `(w / u).im > 0` iff `w` is strictly counterclockwise from `u`. -/
lemma im_div_pos_iff {u w : ℂ} (hu : u ≠ 0) :
    0 < (w / u).im ↔ 0 < w.im * u.re - w.re * u.im := by
  have hn : 0 < normSq u := normSq_pos.mpr hu
  rw [div_im, ← sub_div]
  exact div_pos_iff_of_pos_right hn

lemma shearPt_sub_ne_zero {ε x y : ℝ} {s : ℂ} (h : x ≠ shearRe ε s) : shearPt ε x y - s ≠ 0 := by
  intro h0
  apply h
  have := congrArg (shearRe ε) (sub_eq_zero.mp h0)
  rwa [shearRe_shearPt] at this

/-- The cross product of two vertices of a sheared parallelogram, seen from `s`. -/
lemma im_div_shearPt_pos_iff {ε x₁ y₁ x₂ y₂ : ℝ} {s : ℂ} (h : x₁ ≠ shearRe ε s) :
    0 < ((shearPt ε x₂ y₂ - s) / (shearPt ε x₁ y₁ - s)).im ↔
      0 < (x₁ - shearRe ε s) * (y₂ - s.im) - (x₂ - shearRe ε s) * (y₁ - s.im) := by
  rw [im_div_pos_iff (shearPt_sub_ne_zero h)]
  simp only [shearPt, shearRe, sub_re, sub_im]
  constructor <;> intro hh <;> linarith

/-- A sheared parallelogram `a ≤ v ≤ b`, `c ≤ im ≤ d` around `s` is run counterclockwise. -/
lemma exists_log_shearQuad {ε a b c d : ℝ} {s : ℂ} (ha : a < shearRe ε s) (hb : shearRe ε s < b)
    (hc : c < s.im) (hd : s.im < d) :
    ∃ Λ : C(unitInterval, ℂ), (∀ t, s + exp (Λ t) =
      quadPath (shearPt ε a c) (shearPt ε b c) (shearPt ε b d) (shearPt ε a d) t) ∧
      Λ 1 = Λ 0 + 2 * π * I := by
  refine exists_log_quadPath ?_ ?_ ?_ ?_
  · rw [im_div_shearPt_pos_iff ha.ne]
    nlinarith
  · rw [im_div_shearPt_pos_iff hb.ne']
    nlinarith
  · rw [im_div_shearPt_pos_iff hb.ne']
    nlinarith
  · rw [im_div_shearPt_pos_iff ha.ne]
    nlinarith

section FreeFamily

/-- `σ` has the universal property of a free basis, for groups in `Type`. -/
private def IsFreeFamily {G ι : Type} [Group G] (σ : ι → G) : Prop :=
  ∀ (H : Type) [Group H] (g : ι → H), ∃! φ : G →* H, ∀ i, φ (σ i) = g i

private lemma IsFreeFamily.mulEquiv {G G' ι : Type} [Group G] [Group G'] {σ : ι → G}
    (h : IsFreeFamily σ) (e : G ≃* G') : IsFreeFamily fun i ↦ e (σ i) := by
  intro H _ g
  obtain ⟨φ, hφ, huniq⟩ := h H g
  refine ⟨φ.comp e.symm.toMonoidHom, fun i ↦ by simpa using hφ i, fun φ' hφ' ↦ ?_⟩
  have := huniq (φ'.comp e.toMonoidHom) hφ'
  ext a
  simpa using DFunLike.congr_fun this (e.symm a)

private lemma IsFreeFamily.comp_equiv {G ι ι' : Type} [Group G] {σ : ι → G} (h : IsFreeFamily σ)
    (e : ι' ≃ ι) : IsFreeFamily (σ ∘ e) := by
  intro H _ g
  obtain ⟨φ, hφ, huniq⟩ := h H (g ∘ e.symm)
  refine ⟨φ, fun i ↦ by simpa using hφ (e i), fun φ' hφ' ↦ huniq φ' fun i ↦ ?_⟩
  simpa using hφ' (e.symm i)

private lemma isFreeFamily_of_isEmpty {G ι : Type} [Group G] [Subsingleton G] [IsEmpty ι]
    (σ : ι → G) : IsFreeFamily σ := fun _ _ _ ↦
  ⟨1, fun i ↦ isEmptyElim i, fun φ _ ↦ MonoidHom.ext fun a ↦ by
    rw [Subsingleton.elim a 1, map_one, map_one]⟩

/-- Free families in the two pieces of an open cover with simply connected intersection give a
free family of the whole space, the second one transported along a path in the first piece. -/
private lemma isFreeFamily_glue {Y : Type} [TopologicalSpace Y] {U V : Set Y} (hU : IsOpen U)
    (hV : IsOpen V) (hUV : U ∪ V = univ) (hUc : IsPathConnected U) (hVc : IsPathConnected V)
    (hUVc : IsPathConnected (U ∩ V)) (hUVs : SimplyConnectedSpace ↥(U ∩ V)) {y y' : Y}
    (hyU : y ∈ U) (hy'U : y' ∈ U) (hy'V : y' ∈ V) (β : Path y y') (hβ : range β ⊆ U)
    {ι κ : Type} {σU : ι → FundamentalGroup U ⟨y, hyU⟩} (hσU : IsFreeFamily σU)
    {σV : κ → FundamentalGroup V ⟨y', hy'V⟩} (hσV : IsFreeFamily σV) :
    IsFreeFamily (Sum.elim (fun i ↦ FundamentalGroup.mapSubtypeVal hyU (σU i))
      (fun i ↦ FundamentalGroup.fundamentalGroupMulEquivOfPath β.symm
        (FundamentalGroup.mapSubtypeVal hy'V (σV i)))) := by
  -- transport the family of `U` to `y'`
  let βU : Path (⟨y, hyU⟩ : U) ⟨y', hy'U⟩ := β.codRestrict hβ
  have hσU' := IsFreeFamily.mulEquiv hσU (FundamentalGroup.fundamentalGroupMulEquivOfPath βU)
  -- van Kampen at `y'`
  have hfree : IsFreeFamily (Sum.elim
      (fun i ↦ FundamentalGroup.mapSubtypeVal hy'U
        (FundamentalGroup.fundamentalGroupMulEquivOfPath βU (σU i)))
      (fun i ↦ FundamentalGroup.mapSubtypeVal hy'V (σV i))) := by
    intro H _ g
    obtain ⟨φU, hφU, huU⟩ := hσU' H (g ∘ Sum.inl)
    obtain ⟨φV, hφV, huV⟩ := hσV H (g ∘ Sum.inr)
    obtain ⟨φ, hφ, huniq⟩ := FundamentalGroup.existsUnique_hom_of_union hU hV hUV hUc hVc hUVc
      hy'U hy'V φU φV (MonoidHom.ext fun a ↦ by
        rw [Subsingleton.elim a 1, map_one, map_one])
    refine ⟨φ, fun i ↦ ?_, fun φ' hφ' ↦ huniq φ' ⟨?_, ?_⟩⟩
    · rcases i with i | i
      · simp only [Sum.elim_inl]
        rw [← MonoidHom.comp_apply, hφ.1]
        exact hφU i
      · simp only [Sum.elim_inr]
        rw [← MonoidHom.comp_apply, hφ.2]
        exact hφV i
    · exact huU _ fun i ↦ by simpa using hφ' (Sum.inl i)
    · exact huV _ fun i ↦ by simpa using hφ' (Sum.inr i)
  have h2 := IsFreeFamily.mulEquiv hfree (FundamentalGroup.fundamentalGroupMulEquivOfPath β.symm)
  convert h2 using 1
  funext i
  rcases i with i | i
  · simp only [Sum.elim_inl]
    induction σU i using Path.Homotopic.Quotient.ind with | mk γ => ?_
    change Path.Homotopic.Quotient.mk (γ.map continuous_subtype_val) =
      Path.Homotopic.Quotient.mk (β.symm.symm.trans
        (((βU.symm.trans (γ.trans βU)).map continuous_subtype_val).trans β.symm))
    have hβU : βU.map continuous_subtype_val = β := Path.ext rfl
    rw [Path.map_trans, Path.map_trans, ← Path.map_symm, hβU, Path.symm_symm]
    change FundamentalGroupoid.fromPath (Path.Homotopic.Quotient.mk _) =
      FundamentalGroupoid.fromPath (Path.Homotopic.Quotient.mk _)
    simp only [FundamentalGroupoid.fromPath_mk_trans, FundamentalGroupoid.fromPath_mk_symm,
      Category.assoc, IsIso.hom_inv_id_assoc, IsIso.hom_inv_id, Category.comp_id]
  · rfl

end FreeFamily

/-- The concatenation of two paths with values in `T` has values in `T` (`Path.trans_range`). -/
private lemma trans_apply_mem {X : Type*} [TopologicalSpace X] {T : Set X} {a b c : X}
    {p : Path a b} {q : Path b c} (hp : ∀ t, p t ∈ T) (hq : ∀ t, q t ∈ T) (t : unitInterval) :
    (p.trans q) t ∈ T := by
  have h : (p.trans q) t ∈ range p ∪ range q := Path.trans_range p q ▸ mem_range_self t
  rcases h with ⟨s, hs⟩ | ⟨s, hs⟩
  · exact hs ▸ hp s
  · exact hs ▸ hq s

namespace StripData

variable {S : Finset ℂ} (D : StripData S)

/-- The half-plane `v < xₖ + η`. -/
private def half (k : ℕ) : Set ℂ := {z | shearRe D.ε z < D.x k + D.η}

/-- The strip `xᵢ - η < v < xᵢ₊₁ + η` (it contains `sᵢ` and no other point of `S`). -/
private def strip (i : ℕ) : Set ℂ :=
  {z | D.x i - D.η < shearRe D.ε z ∧ shearRe D.ε z < D.x (i + 1) + D.η}

/-- The thin strip `xᵢ - η < v < xᵢ + η` (no point of `S`). -/
private def thin (i : ℕ) : Set ℂ := {z | D.x i - D.η < shearRe D.ε z ∧ shearRe D.ε z < D.x i + D.η}

/-- The half-plane `v > xₙ - η` (no point of `S`). -/
private def right : Set ℂ := {z | D.x S.card - D.η < shearRe D.ε z}

/-- The half-plane `im < -R` (no point of `S`). -/
private def low : Set ℂ := {z | z.im < -D.R}

/-- The half-plane `im > R` (no point of `S`). -/
private def high : Set ℂ := {z | D.R < z.im}

/-- The bottom corner `v = xᵢ`, `im = -(R + 1)`. -/
private def corner (i : ℕ) : ℂ := shearPt D.ε (D.x i) (-(D.R + 1))

/-- The top corner `v = xᵢ`, `im = R + 1`. -/
private def top (i : ℕ) : ℂ := shearPt D.ε (D.x i) (D.R + 1)

/-- The bottom edge from `corner 0` to `corner i`. -/
private def bot (i : ℕ) : Path (D.corner 0) (D.corner i) := segmentPath _ _

/-- The boundary of the `i`-th parallelogram, from its bottom left corner. -/
private def quad (i : ℕ) : Path (D.corner i) (D.corner i) :=
  quadPath (D.corner i) (D.corner (i + 1)) (D.top (i + 1)) (D.top i)

/-- The `i`-th standard loop: along the bottom, around the `i`-th parallelogram, and back. -/
private def loop (i : ℕ) : Path (D.corner 0) (D.corner 0) :=
  ((D.bot i).trans (D.quad i)).trans (D.bot i).symm

/-- The boundary of the big parallelogram. -/
private def big : Path (D.corner 0) (D.corner 0) :=
  quadPath (D.corner 0) (D.corner S.card) (D.top S.card) (D.top 0)

private lemma convex_half (k : ℕ) : Convex ℝ (D.half k) :=
  convex_halfSpace_lt (shearRe_isLinearMap D.ε) _

private lemma convex_strip (i : ℕ) : Convex ℝ (D.strip i) :=
  (convex_halfSpace_gt (shearRe_isLinearMap D.ε) _).inter
    (convex_halfSpace_lt (shearRe_isLinearMap D.ε) _)

private lemma convex_thin (i : ℕ) : Convex ℝ (D.thin i) :=
  (convex_halfSpace_gt (shearRe_isLinearMap D.ε) _).inter
    (convex_halfSpace_lt (shearRe_isLinearMap D.ε) _)

private lemma convex_right : Convex ℝ D.right := convex_halfSpace_gt (shearRe_isLinearMap D.ε) _

private lemma convex_low : Convex ℝ D.low :=
  convex_halfSpace_lt (f := Complex.im) ⟨fun _ _ ↦ rfl, fun _ _ ↦ by simp⟩ _

private lemma convex_high : Convex ℝ D.high :=
  convex_halfSpace_gt (f := Complex.im) ⟨fun _ _ ↦ rfl, fun _ _ ↦ by simp⟩ _

private lemma isOpen_half (k : ℕ) : IsOpen (D.half k) :=
  isOpen_lt (continuous_shearRe _) continuous_const

private lemma isOpen_strip (i : ℕ) : IsOpen (D.strip i) :=
  (isOpen_lt continuous_const (continuous_shearRe _)).inter
    (isOpen_lt (continuous_shearRe _) continuous_const)

private lemma isOpen_thin (i : ℕ) : IsOpen (D.thin i) :=
  (isOpen_lt continuous_const (continuous_shearRe _)).inter
    (isOpen_lt (continuous_shearRe _) continuous_const)

private lemma isOpen_right : IsOpen D.right := isOpen_lt continuous_const (continuous_shearRe _)

private lemma im_lt (s : ℂ) (hs : s ∈ S) : -D.R < s.im ∧ s.im < D.R := by
  have h := (Complex.abs_im_le_norm s).trans_lt (D.norm_lt s hs)
  exact abs_lt.mp h

private lemma notMem_low {s : ℂ} (hs : s ∈ S) : s ∉ D.low := fun h ↦ by
  have := (D.im_lt s hs).1
  exact absurd h (not_lt.mpr this.le)

private lemma notMem_high {s : ℂ} (hs : s ∈ S) : s ∉ D.high := fun h ↦ by
  have := (D.im_lt s hs).2
  exact absurd h (not_lt.mpr this.le)

private lemma notMem_thin {i : ℕ} (hi : i ≤ S.card) {s : ℂ} (hs : s ∈ S) : s ∉ D.thin i := by
  intro h
  obtain ⟨h1, h2⟩ := h
  have hg := D.gap i hi s hs
  have : |D.x i - shearRe D.ε s| < D.η := abs_sub_lt_iff.mpr ⟨by linarith, by linarith⟩
  linarith

/-- The region `‖z‖ > R` (no point of `S`). -/
private def far : Set ℂ := {z | D.R < ‖z‖}

/-- The vertical edge `v = xₖ`, `|im| ≤ R + 1`. -/
private def vline (k : ℕ) : Set ℂ :=
  {z | shearRe D.ε z = D.x k ∧ -(D.R + 1) ≤ z.im ∧ z.im ≤ D.R + 1}

private lemma convex_vline (k : ℕ) : Convex ℝ (D.vline k) :=
  (convex_hyperplane (shearRe_isLinearMap D.ε) _).inter
    ((convex_halfSpace_ge (f := Complex.im) ⟨fun _ _ ↦ rfl, fun _ _ ↦ by simp⟩ _).inter
      (convex_halfSpace_le (f := Complex.im) ⟨fun _ _ ↦ rfl, fun _ _ ↦ by simp⟩ _))

private lemma notMem_far {s : ℂ} (hs : s ∈ S) : s ∉ D.far := fun h ↦
  absurd h (not_lt.mpr (D.norm_lt s hs).le)

private lemma low_subset_far : D.low ⊆ D.far := fun z hz ↦ by
  have h1 : D.R < |z.im| := by
    rw [abs_of_neg (by linarith [D.R_pos, show z.im < -D.R from hz])]
    linarith [show z.im < -D.R from hz]
  exact h1.trans_le (Complex.abs_im_le_norm z)

private lemma high_subset_far : D.high ⊆ D.far := fun z hz ↦ by
  have h1 : D.R < |z.im| := by
    rw [abs_of_pos (by linarith [D.R_pos, show D.R < z.im from hz])]
    exact hz
  exact h1.trans_le (Complex.abs_im_le_norm z)

private lemma vline_subset_far_aux {k : ℕ} (hk : D.R + |D.ε| * (D.R + 1) < |D.x k|) :
    D.vline k ⊆ D.far := fun z hz ↦ by
  obtain ⟨hv, h1, h2⟩ := hz
  have hre : z.re = D.x k - D.ε * z.im := by
    simp only [shearRe] at hv
    linarith
  have him : |z.im| ≤ D.R + 1 := abs_le.mpr ⟨h1, h2⟩
  have hεim : |D.ε * z.im| ≤ |D.ε| * (D.R + 1) := by
    rw [abs_mul]
    exact mul_le_mul_of_nonneg_left him (abs_nonneg _)
  have : D.R < |z.re| := by
    rw [hre]
    have := abs_sub_abs_le_abs_sub (D.x k) (D.ε * z.im)
    linarith
  exact this.trans_le (Complex.abs_re_le_norm z)

private lemma εR_nonneg : 0 ≤ |D.ε| * (D.R + 1) :=
  mul_nonneg (abs_nonneg _) (by linarith [D.R_pos])

private lemma vline_zero_subset_far : D.vline 0 ⊆ D.far := by
  have h0 := D.x_zero
  have h1 := D.εR_nonneg
  have h2 := D.R_pos
  refine D.vline_subset_far_aux ?_
  rw [abs_of_neg (a := D.x 0) (by linarith)]
  linarith

private lemma vline_card_subset_far : D.vline S.card ⊆ D.far := by
  have h0 := D.x_card
  have h1 := D.εR_nonneg
  have h2 := D.R_pos
  refine D.vline_subset_far_aux ?_
  rw [abs_of_pos (a := D.x S.card) (by linarith)]
  exact h0

@[simp] lemma shearRe_corner (i : ℕ) : shearRe D.ε (D.corner i) = D.x i := shearRe_shearPt ..
@[simp] lemma shearRe_top (i : ℕ) : shearRe D.ε (D.top i) = D.x i := shearRe_shearPt ..
@[simp] lemma im_corner (i : ℕ) : (D.corner i).im = -(D.R + 1) := rfl
@[simp] lemma im_top (i : ℕ) : (D.top i).im = D.R + 1 := rfl

private lemma corner_mem_low (i : ℕ) : D.corner i ∈ D.low := show -(D.R + 1) < -D.R by linarith
private lemma top_mem_high (i : ℕ) : D.top i ∈ D.high := show D.R < D.R + 1 by linarith
private lemma corner_mem_vline (i : ℕ) : D.corner i ∈ D.vline i :=
  ⟨by simp, by simp, by simp; linarith [D.R_pos]⟩
private lemma top_mem_vline (i : ℕ) : D.top i ∈ D.vline i :=
  ⟨by simp, by simp; linarith [D.R_pos], by simp⟩
private lemma corner_mem_thin (i : ℕ) : D.corner i ∈ D.thin i :=
  ⟨by simp [D.η_pos], by simp [D.η_pos]⟩
private lemma top_mem_thin (i : ℕ) : D.top i ∈ D.thin i := ⟨by simp [D.η_pos], by simp [D.η_pos]⟩

private lemma mem_half_of_le {z : ℂ} {i k : ℕ} (hz : shearRe D.ε z = D.x i) (hik : i ≤ k) :
    z ∈ D.half k := by
  change shearRe D.ε z < D.x k + D.η
  rw [hz]
  linarith [D.x_mono hik, D.η_pos]

private lemma mem_strip_left {z : ℂ} {i : ℕ} (hz : shearRe D.ε z = D.x i) : z ∈ D.strip i := by
  refine ⟨?_, ?_⟩ <;> rw [hz] <;> linarith [D.x_mono (Nat.le_succ i), D.η_pos]

private lemma mem_strip_right {z : ℂ} {i : ℕ} (hz : shearRe D.ε z = D.x (i + 1)) :
    z ∈ D.strip i := by
  refine ⟨?_, ?_⟩ <;> rw [hz] <;> linarith [D.x_mono (Nat.le_succ i), D.η_pos]

private lemma mem_thin_of {z : ℂ} {i : ℕ} (hz : shearRe D.ε z = D.x i) : z ∈ D.thin i := by
  refine ⟨?_, ?_⟩ <;> rw [hz] <;> linarith [D.η_pos]

/-- The strip `i` contains exactly one point of `S`, namely `sᵢ`. -/
private lemma mem_strip_iff {i : Fin S.card} {s : ℂ} (hs : s ∈ S) : s ∈ D.strip i ↔ s = D.e i := by
  constructor
  · rintro ⟨h1, h2⟩
    obtain ⟨k, hk⟩ := D.e.surjective ⟨s, hs⟩
    have hks : s = D.e k := by rw [hk]
    rw [hks] at h1 h2 ⊢
    rcases lt_trichotomy k i with hki | rfl | hki
    · exfalso
      have h3 := D.lt_x k
      have h4 : D.x (k + 1) ≤ D.x i := D.x_mono (by omega)
      have h5 := D.gap i i.2.le _ (D.e k).2
      rw [abs_of_pos (by linarith)] at h5
      linarith
    · rfl
    · exfalso
      have h3 := D.x_lt k
      have h4 : D.x (i + 1) ≤ D.x k := D.x_mono (by omega)
      have h5 := D.gap (i + 1) (by omega) _ (D.e k).2
      rw [abs_of_neg (by linarith)] at h5
      linarith
  · rintro rfl
    exact ⟨by linarith [D.x_lt i, D.η_pos], by linarith [D.lt_x i, D.η_pos]⟩

private lemma notMem_half_zero {s : ℂ} (hs : s ∈ S) : s ∉ D.half 0 := fun h ↦ by
  obtain ⟨k, hk⟩ := D.e.surjective ⟨s, hs⟩
  have hks : s = D.e k := by rw [hk]
  have h3 := D.x_lt k
  have h4 : D.x 0 ≤ D.x k := D.x_mono (Nat.zero_le _)
  have h5 := D.gap 0 (Nat.zero_le _) s hs
  rw [hks] at h h5
  rw [abs_of_neg (by linarith)] at h5
  change shearRe D.ε (D.e k) < D.x 0 + D.η at h
  linarith

private lemma notMem_right {s : ℂ} (hs : s ∈ S) : s ∉ D.right := fun h ↦ by
  obtain ⟨k, hk⟩ := D.e.surjective ⟨s, hs⟩
  have hks : s = D.e k := by rw [hk]
  have h3 := D.lt_x k
  have h4 : D.x (k + 1) ≤ D.x S.card := D.x_mono (by omega)
  have h5 := D.gap S.card le_rfl s hs
  rw [hks] at h h5
  rw [abs_of_pos (by linarith)] at h5
  change D.x S.card - D.η < shearRe D.ε (D.e k) at h
  linarith

private lemma half_mono {k l : ℕ} (hkl : k ≤ l) : D.half k ⊆ D.half l := fun z hz ↦ by
  change shearRe D.ε z < D.x l + D.η
  linarith [D.x_mono hkl, show shearRe D.ε z < D.x k + D.η from hz]

private lemma strip_subset_half (i : ℕ) : D.strip i ⊆ D.half (i + 1) := fun _ hz ↦ hz.2

private lemma thin_subset_half (i : ℕ) : D.thin i ⊆ D.half i := fun _ hz ↦ hz.2

private lemma half_succ_eq (k : ℕ) : D.half (k + 1) = D.half k ∪ D.strip k := by
  ext z
  simp only [half, strip, mem_ofPred_eq, mem_union]
  constructor
  · intro h
    by_cases h' : shearRe D.ε z < D.x k + D.η
    · exact Or.inl h'
    · exact Or.inr ⟨by linarith [not_lt.mp h', D.η_pos], h⟩
  · rintro (h | h)
    · linarith [D.x_mono (Nat.le_succ k)]
    · exact h.2

private lemma half_inter_strip (k : ℕ) : D.half k ∩ D.strip k = D.thin k := by
  ext z
  simp only [half, strip, thin, mem_ofPred_eq, mem_inter_iff]
  constructor
  · rintro ⟨h1, h2, _⟩
    exact ⟨h2, h1⟩
  · rintro ⟨h1, h2⟩
    exact ⟨h2, h1, by linarith [D.x_mono (Nat.le_succ k)]⟩

private lemma half_union_right : D.half S.card ∪ D.right = univ := by
  ext z
  simp only [half, right, mem_ofPred_eq, mem_union, mem_univ, iff_true]
  by_contra h
  push Not at h
  linarith [D.η_pos]

private lemma half_inter_right : D.half S.card ∩ D.right = D.thin S.card := by
  ext z
  simp only [half, right, thin, mem_ofPred_eq, mem_inter_iff]
  tauto

private lemma quadPath_mem {T : Set ℂ} {v₀ v₁ v₂ v₃ : ℂ} {K₀ K₁ K₂ K₃ : Set ℂ} (h₀ : Convex ℝ K₀)
    (h₁ : Convex ℝ K₁) (h₂ : Convex ℝ K₂) (h₃ : Convex ℝ K₃) (hK₀ : K₀ ⊆ T) (hK₁ : K₁ ⊆ T)
    (hK₂ : K₂ ⊆ T) (hK₃ : K₃ ⊆ T) (a₀ : v₀ ∈ K₀) (a₁ : v₁ ∈ K₀) (b₁ : v₁ ∈ K₁) (b₂ : v₂ ∈ K₁)
    (c₂ : v₂ ∈ K₂) (c₃ : v₃ ∈ K₂) (d₃ : v₃ ∈ K₃) (d₀ : v₀ ∈ K₃) (t : unitInterval) :
    quadPath v₀ v₁ v₂ v₃ t ∈ T :=
  trans_apply_mem (trans_apply_mem (trans_apply_mem (fun t ↦ hK₀ (segmentPath_mem h₀ a₀ a₁ t))
    (fun t ↦ hK₁ (segmentPath_mem h₁ b₁ b₂ t))) (fun t ↦ hK₂ (segmentPath_mem h₂ c₂ c₃ t)))
    (fun t ↦ hK₃ (segmentPath_mem h₃ d₃ d₀ t)) t

/-- The boundary of the `i`-th parallelogram lies in the `i`-th strip and misses `S`. -/
private lemma quad_mem {i : ℕ} (hi : i < S.card) (t : unitInterval) : D.quad i t ∈ D.strip i \ S :=
  quadPath_mem (T := D.strip i \ S) ((D.convex_low).inter (D.convex_strip i))
    ((D.convex_thin (i + 1)).inter (D.convex_strip i)) ((D.convex_high).inter (D.convex_strip i))
    ((D.convex_thin i).inter (D.convex_strip i))
    (fun z hz ↦ ⟨hz.2, fun h ↦ D.notMem_low h hz.1⟩)
    (fun z hz ↦ ⟨hz.2, fun h ↦ D.notMem_thin (by omega) h hz.1⟩)
    (fun z hz ↦ ⟨hz.2, fun h ↦ D.notMem_high h hz.1⟩)
    (fun z hz ↦ ⟨hz.2, fun h ↦ D.notMem_thin hi.le h hz.1⟩)
    ⟨D.corner_mem_low i, D.mem_strip_left (D.shearRe_corner i)⟩
    ⟨D.corner_mem_low _, D.mem_strip_right (D.shearRe_corner _)⟩
    ⟨D.mem_thin_of (D.shearRe_corner _), D.mem_strip_right (D.shearRe_corner _)⟩
    ⟨D.mem_thin_of (D.shearRe_top _), D.mem_strip_right (D.shearRe_top _)⟩
    ⟨D.top_mem_high _, D.mem_strip_right (D.shearRe_top _)⟩
    ⟨D.top_mem_high i, D.mem_strip_left (D.shearRe_top i)⟩
    ⟨D.mem_thin_of (D.shearRe_top i), D.mem_strip_left (D.shearRe_top i)⟩
    ⟨D.mem_thin_of (D.shearRe_corner i), D.mem_strip_left (D.shearRe_corner i)⟩ t

/-- The big parallelogram lies outside `D(0, R)`. -/
private lemma big_mem (t : unitInterval) : D.big t ∈ D.far :=
  quadPath_mem D.convex_low (D.convex_vline _) D.convex_high (D.convex_vline 0) D.low_subset_far
    D.vline_card_subset_far D.high_subset_far D.vline_zero_subset_far (D.corner_mem_low 0)
    (D.corner_mem_low _) (D.corner_mem_vline _) (D.top_mem_vline _) (D.top_mem_high _)
    (D.top_mem_high 0) (D.top_mem_vline 0) (D.corner_mem_vline 0) t

/-- The bottom edge from `corner 0` to `corner i` lies below `S` and in the half-plane `k`. -/
private lemma bot_mem {i k : ℕ} (hik : i ≤ k) (t : unitInterval) : D.bot i t ∈ D.low ∩ D.half k :=
  segmentPath_mem ((D.convex_low).inter (D.convex_half k))
    ⟨D.corner_mem_low 0, D.mem_half_of_le (D.shearRe_corner 0) (Nat.zero_le _)⟩
    ⟨D.corner_mem_low i, D.mem_half_of_le (D.shearRe_corner i) hik⟩ t

private lemma corner_notMem (i : ℕ) : D.corner i ∉ S := fun h ↦ D.notMem_low h (D.corner_mem_low i)

private lemma top_notMem (i : ℕ) : D.top i ∉ S := fun h ↦ D.notMem_high h (D.top_mem_high i)

private lemma low_notMem : ∀ z ∈ D.low, z ∉ S := fun _ hz hs ↦ D.notMem_low hs hz

private lemma high_notMem : ∀ z ∈ D.high, z ∉ S := fun _ hz hs ↦ D.notMem_high hs hz

private lemma thin_notMem {i : ℕ} (hi : i ≤ S.card) : ∀ z ∈ D.thin i, z ∉ S :=
  fun _ hz hs ↦ D.notMem_thin hi hs hz

private lemma loop_mem {i k : ℕ} (hik : i < k) (hk : k ≤ S.card) (t : unitInterval) :
    D.loop i t ∈ D.half k \ S := by
  have hb (t : unitInterval) : D.bot i t ∈ D.half k \ S :=
    ⟨(D.bot_mem hik.le t).2, fun h ↦ D.notMem_low h (D.bot_mem hik.le t).1⟩
  have hq (t : unitInterval) : D.quad i t ∈ D.half k \ S := by
    obtain ⟨h1, h2⟩ := D.quad_mem (i := i) (by omega) t
    exact ⟨D.half_mono hik (D.strip_subset_half i h1), h2⟩
  have hb' (t : unitInterval) : (D.bot i).symm t ∈ D.half k \ S := hb _
  exact trans_apply_mem (trans_apply_mem hb hq) hb' t

end StripData

section Induction

/-- `σ` is the class of a loop `γ` in `Y` whose image under `j` is the loop `c` of `ℂ`. -/
private def IsClassOf {Y : Type} [TopologicalSpace Y] (j : Y → ℂ) {y : Y} {a : ℂ}
    (c : Path a a) (σ : FundamentalGroup Y y) : Prop :=
  ∃ γ : Path y y, (∀ t, j (γ t) = c t) ∧ σ = Path.Homotopic.Quotient.mk γ

private lemma range_comp_preimage {Y : Type} [TopologicalSpace Y] (j : Y → ℂ) (A : Set ℂ) :
    range (j ∘ (Subtype.val : j ⁻¹' A → Y)) = range j ∩ A := by
  rw [range_comp, Subtype.range_coe, image_preimage_eq_inter_range, inter_comm]

/-- The preimage of a convex subset of the range of an embedding is simply connected. -/
private lemma simplyConnectedSpace_preimage {Y : Type} [TopologicalSpace Y] {j : Y → ℂ}
    (hj : IsEmbedding j) {K : Set ℂ} (hK : Convex ℝ K) (hKne : K.Nonempty) (hKj : K ⊆ range j) :
    SimplyConnectedSpace (j ⁻¹' K) := by
  have : ContractibleSpace K := hK.contractibleSpace hKne
  exact (hj.homeomorphOfSubsetRange hKj).toHomotopyEquiv.simplyConnectedSpace

private lemma subsingleton_fundamentalGroup {Y : Type} [TopologicalSpace Y]
    [SimplyConnectedSpace Y] (y : Y) : Subsingleton (FundamentalGroup Y y) :=
  ⟨fun a b ↦ Subsingleton.elim (α := Path.Homotopic.Quotient y y) a b⟩

variable {S : Finset ℂ} (D : StripData S)

/-- The boundary of the `i`-th parallelogram, seen in a space over `strip i ∖ {sᵢ}`, is a loop
around `sᵢ`. -/
private lemma isLoopAround_quad {Y : Type} [TopologicalSpace Y] {j : Y → ℂ} (hj : IsEmbedding j)
    (i : Fin S.card) (hjr : range j = D.strip i \ {(D.e i : ℂ)}) {y : Y} (γ : Path y y)
    (hγ : ∀ t, j (γ t) = D.quad i t) :
    FundamentalGroup.IsLoopAround j (D.e i : ℂ) (Path.Homotopic.Quotient.mk γ) := by
  obtain ⟨Λ, hΛ, hΛ'⟩ := exists_log_shearQuad (ε := D.ε) (D.x_lt i) (D.lt_x i)
    (c := -(D.R + 1)) (d := D.R + 1) (by linarith [(D.im_lt _ (D.e i).2).1])
    (by linarith [(D.im_lt _ (D.e i).2).2])
  have hw : γ.WindsOnceAround j (D.e i : ℂ) := ⟨Λ, fun t ↦ (hΛ t).trans (hγ t).symm, hΛ'⟩
  exact hw.isLoopAround (D.convex_strip i) (D.isOpen_strip i)
    ((D.mem_strip_iff (D.e i).2).mpr rfl) hj hjr

/-- **Freeness, by induction on the half-planes.** In a space `Y` over `half k ∖ S`, the classes of
the `k` standard loops based over `corner 0` form a free family. -/
private theorem isFreeFamily_half (k : ℕ) : k ≤ S.card → ∀ (Y : Type) [TopologicalSpace Y]
    (j : Y → ℂ), IsOpenEmbedding j → range j = D.half k \ S → ∀ (y : Y), j y = D.corner 0 →
    ∀ (ρ : Fin k → FundamentalGroup Y y), (∀ i : Fin k, IsClassOf j (D.loop i) (ρ i)) →
      IsFreeFamily ρ := by
  induction k with
  | zero =>
    intro _ Y _ j hj hjr y hy ρ _
    have hr : D.half 0 ⊆ range j := fun z hz ↦ by
      rw [hjr]
      exact ⟨hz, fun hs ↦ D.notMem_half_zero hs hz⟩
    have := simplyConnectedSpace_preimage hj.isEmbedding (D.convex_half 0)
      ⟨_, D.mem_half_of_le (D.shearRe_corner 0) le_rfl⟩ hr
    have hpre : j ⁻¹' D.half 0 = univ := eq_univ_of_forall fun y' ↦
      (hjr ▸ mem_range_self y' : j y' ∈ D.half 0 \ S).1
    have : SimplyConnectedSpace Y :=
      ((Homeomorph.setCongr hpre).trans
        (Homeomorph.Set.univ Y)).symm.toHomotopyEquiv.simplyConnectedSpace
    have := subsingleton_fundamentalGroup y
    exact isFreeFamily_of_isEmpty ρ
  | succ k ih =>
    intro hk Y _ j hj hjr y hy ρ hρ
    classical
    have hkS : k < S.card := hk
    have hmemj {z : ℂ} : z ∈ range j ↔ z ∈ D.half (k + 1) \ S := by rw [hjr]
    set U : Set Y := j ⁻¹' D.half k
    set V : Set Y := j ⁻¹' D.strip k
    have hUo : IsOpen U := (D.isOpen_half k).preimage hj.continuous
    have hVo : IsOpen V := (D.isOpen_strip k).preimage hj.continuous
    have hUV : U ∪ V = univ := by
      rw [← preimage_union, ← D.half_succ_eq]
      exact eq_univ_of_forall fun y' ↦ (hmemj.mp (mem_range_self y')).1
    have hUr : range (j ∘ (Subtype.val : U → Y)) = D.half k \ S := by
      rw [range_comp_preimage, hjr]
      ext z
      constructor
      · rintro ⟨⟨_, h2⟩, h3⟩
        exact ⟨h3, h2⟩
      · rintro ⟨h1, h2⟩
        exact ⟨⟨D.half_mono (Nat.le_succ k) h1, h2⟩, h1⟩
    have hVr : range (j ∘ (Subtype.val : V → Y)) = D.strip k \ {(D.e ⟨k, hkS⟩ : ℂ)} := by
      rw [range_comp_preimage, hjr]
      ext z
      constructor
      · rintro ⟨⟨_, h2⟩, h3⟩
        exact ⟨h3, fun h ↦ h2 (by rw [mem_singleton_iff.mp h]; exact (D.e _).2)⟩
      · rintro ⟨h1, h2⟩
        refine ⟨⟨D.strip_subset_half k h1, fun hs ↦ h2 ?_⟩, h1⟩
        exact (D.mem_strip_iff (i := ⟨k, hkS⟩) hs).mp h1
    have hUVeq : U ∩ V = j ⁻¹' D.thin k := by
      rw [← preimage_inter, D.half_inter_strip]
    have hthin : D.thin k ⊆ range j := fun z hz ↦ hmemj.mpr
      ⟨D.half_mono (Nat.le_succ k) (D.thin_subset_half k hz), fun hs ↦ D.notMem_thin hkS.le hs hz⟩
    have hthin_ne : (D.thin k).Nonempty := ⟨_, D.corner_mem_thin k⟩
    have hUVs : SimplyConnectedSpace ↥(U ∩ V) := by
      have := simplyConnectedSpace_preimage hj.isEmbedding (D.convex_thin k) hthin_ne hthin
      exact (Homeomorph.setCongr hUVeq).toHomotopyEquiv.simplyConnectedSpace
    have hUVc : IsPathConnected (U ∩ V) := by
      rw [isPathConnected_iff_pathConnectedSpace]
      have : Nonempty ↥(U ∩ V) := by
        obtain ⟨z, hz⟩ := hthin_ne
        obtain ⟨y', hy'⟩ := hthin hz
        exact ⟨⟨y', hUVeq ▸ (show j y' ∈ D.thin k from hy' ▸ hz)⟩⟩
      infer_instance
    -- base points
    have hyU : y ∈ U := show j y ∈ D.half k by
      rw [hy]
      exact D.mem_half_of_le (D.shearRe_corner 0) (Nat.zero_le _)
    have hck : D.corner k ∈ range j := hmemj.mpr
      ⟨D.mem_half_of_le (D.shearRe_corner k) (Nat.le_succ k),
        fun hs ↦ D.notMem_low hs (D.corner_mem_low k)⟩
    set y' : Y := hj.isEmbedding.toHomeomorph.symm ⟨D.corner k, hck⟩
    have hy' : j y' = D.corner k :=
      congrArg Subtype.val (hj.isEmbedding.toHomeomorph.apply_symm_apply ⟨D.corner k, hck⟩)
    have hy'U : y' ∈ U := show j y' ∈ D.half k by
      rw [hy']
      exact D.mem_half_of_le (D.shearRe_corner k) le_rfl
    have hy'V : y' ∈ V := show j y' ∈ D.strip k by
      rw [hy']
      exact D.mem_strip_left (D.shearRe_corner k)
    -- path-connectedness of the pieces
    have hUc : IsPathConnected U := by
      rw [isPathConnected_iff_pathConnectedSpace]
      have : Nonempty U := ⟨⟨y, hyU⟩⟩
      refine Complex.pathConnectedSpace_of_isOpenEmbedding_of_range_eq_diff (C := D.half k)
        (S := S.filter (· ∈ D.half k)) (D.convex_half k) (D.isOpen_half k) (fun z hz ↦ ?_)
        (hj.comp hUo.isOpenEmbedding_subtypeVal) ?_
      · rw [Finset.coe_filter] at hz
        exact hz.2
      · rw [hUr, Finset.coe_filter]
        ext z
        simp only [mem_sdiff, mem_ofPred_eq, Finset.mem_coe, not_and]
        tauto
    have hVc : IsPathConnected V := by
      rw [isPathConnected_iff_pathConnectedSpace]
      exact FundamentalGroup.pathConnectedSpace_of_range_eq_diff_singleton (D.convex_strip k)
        (D.isOpen_strip k) ((D.mem_strip_iff (D.e ⟨k, hkS⟩).2).mpr rfl)
        (hj.comp hVo.isOpenEmbedding_subtypeVal).isEmbedding hVr
    -- the bottom path
    have hbot (t : unitInterval) : D.bot k t ∈ range j := hmemj.mpr
      ⟨(D.bot_mem (Nat.le_succ k) t).2, fun hs ↦ D.notMem_low hs (D.bot_mem (Nat.le_succ k) t).1⟩
    set β : Path y y' := hj.isEmbedding.liftPath (D.bot k) hbot hy hy'
    have hβU : range β ⊆ U := by
      rintro _ ⟨t, rfl⟩
      change j (β t) ∈ D.half k
      rw [hj.isEmbedding.apply_liftPath]
      exact (D.bot_mem le_rfl t).2
    -- the family of `U`, from the induction hypothesis
    choose γ hγ hργ using hρ
    have hγU (i : Fin k) : range (γ (Fin.castSucc i)) ⊆ U := by
      rintro _ ⟨t, rfl⟩
      change j (γ _ t) ∈ D.half k
      rw [hγ]
      exact (D.loop_mem (i := i) i.2 hkS.le t).1
    let σU : Fin k → FundamentalGroup U ⟨y, hyU⟩ := fun i ↦
      Path.Homotopic.Quotient.mk ((γ (Fin.castSucc i)).codRestrict (hγU i))
    have hσU : IsFreeFamily σU := ih hkS.le U (j ∘ Subtype.val)
      (hj.comp hUo.isOpenEmbedding_subtypeVal) hUr ⟨y, hyU⟩ hy σU
      (fun i ↦ ⟨(γ (Fin.castSucc i)).codRestrict (hγU i), fun t ↦ hγ (Fin.castSucc i) t, rfl⟩)
    -- the generator of `V`
    have hVemb : IsEmbedding (j ∘ (Subtype.val : V → Y)) :=
      (hj.comp hVo.isOpenEmbedding_subtypeVal).isEmbedding
    have hquad (t : unitInterval) : D.quad k t ∈ range (j ∘ (Subtype.val : V → Y)) := by
      rw [hVr]
      obtain ⟨h1, h2⟩ := D.quad_mem hkS t
      exact ⟨h1, fun h ↦ h2 (by rw [mem_singleton_iff.mp h]; exact (D.e _).2)⟩
    set qV : Path (⟨y', hy'V⟩ : V) ⟨y', hy'V⟩ := hVemb.liftPath (D.quad k) hquad hy' hy'
    have hqV : FundamentalGroup.IsLoopAround (j ∘ Subtype.val) (D.e ⟨k, hkS⟩ : ℂ)
        (Path.Homotopic.Quotient.mk qV) :=
      isLoopAround_quad D hVemb ⟨k, hkS⟩ hVr qV (fun t ↦ hVemb.apply_liftPath _ _ _ _ t)
    let σV : Fin 1 → FundamentalGroup V ⟨y', hy'V⟩ := fun _ ↦ Path.Homotopic.Quotient.mk qV
    have hσV : IsFreeFamily σV := by
      intro H _ g
      obtain ⟨φ, hφ, hu⟩ := hqV.existsUnique_hom (D.convex_strip k) (D.isOpen_strip k)
        ((D.mem_strip_iff (D.e ⟨k, hkS⟩).2).mpr rfl) (hj.comp hVo.isOpenEmbedding_subtypeVal)
        hVr (g 0)
      exact ⟨φ, fun i ↦ by rw [Subsingleton.elim i 0]; exact hφ, fun φ' h ↦ hu φ' (h 0)⟩
    have hglue := isFreeFamily_glue hUo hVo hUV hUc hVc hUVc hUVs hyU hy'U hy'V β hβU hσU hσV
    have hfin := IsFreeFamily.comp_equiv hglue finSumFinEquiv.symm
    convert hfin using 1
    funext i
    induction i using Fin.lastCases with
    | last =>
      rw [Function.comp_apply, finSumFinEquiv_symm_last, Sum.elim_inr, hργ]
      have hγk : γ (Fin.last k) = (β.trans (qV.map continuous_subtype_val)).trans β.symm :=
        hj.isEmbedding.path_ext fun t ↦ by
          rw [hγ]
          refine Path.trans_apply_compat (f := id) (g := j)
            (Path.trans_apply_compat (f := id) (g := j) (fun t ↦ ?_) (fun t ↦ ?_)) (fun t ↦ ?_) t
          · exact (hj.isEmbedding.apply_liftPath _ _ _ _ t).symm
          · exact (hVemb.apply_liftPath _ _ _ _ t).symm
          · change D.bot k (unitInterval.symm t) = j (β (unitInterval.symm t))
            exact (hj.isEmbedding.apply_liftPath _ _ _ _ _).symm
      rw [hγk]
      change FundamentalGroupoid.fromPath (Path.Homotopic.Quotient.mk _) =
        FundamentalGroupoid.fromPath (Path.Homotopic.Quotient.mk _)
      simp only [FundamentalGroupoid.fromPath_mk_trans, FundamentalGroupoid.fromPath_mk_symm,
        Category.assoc, IsIso.inv_inv]
    | cast i =>
      rw [Function.comp_apply, finSumFinEquiv_symm_apply_castSucc, Sum.elim_inl, hργ]
      rfl

end Induction

section Final

variable {S : Finset ℂ} (D : StripData S) {X : Type} [TopologicalSpace X] {j : X → ℂ}
  (hj : IsOpenEmbedding j) (hjr : range j = (↑S : Set ℂ)ᶜ)

omit [TopologicalSpace X] in
include hjr in
private lemma mem_range_iff {z : ℂ} : z ∈ range j ↔ z ∉ S := by rw [hjr]; rfl

/-- The point of `X` over `z ∉ S`. -/
private def pt (z : ℂ) (hz : z ∉ S) : X :=
  hj.isEmbedding.toHomeomorph.symm ⟨z, (mem_range_iff hjr).mpr hz⟩

private lemma j_pt (z : ℂ) (hz : z ∉ S) : j (pt hj hjr z hz) = z :=
  congrArg Subtype.val (hj.isEmbedding.toHomeomorph.apply_symm_apply _)

/-- A path of `ℂ ∖ S`, lifted to `X`. -/
private def lift {a b : ℂ} (c : Path a b) (hc : ∀ t, c t ∉ S) (ha : a ∉ S) (hb : b ∉ S) :
    Path (pt hj hjr a ha) (pt hj hjr b hb) :=
  hj.isEmbedding.liftPath c (fun t ↦ (mem_range_iff hjr).mpr (hc t)) (j_pt hj hjr a ha)
    (j_pt hj hjr b hb)

private lemma j_lift {a b : ℂ} (c : Path a b) (hc : ∀ t, c t ∉ S) (ha : a ∉ S) (hb : b ∉ S)
    (t : unitInterval) : j (lift hj hjr c hc ha hb t) = c t :=
  hj.isEmbedding.apply_liftPath _ _ _ _ t

private lemma lift_trans {a b c : ℂ} (p : Path a b) (q : Path b c) (hp : ∀ t, p t ∉ S)
    (hq : ∀ t, q t ∉ S) (hpq : ∀ t, (p.trans q) t ∉ S) (ha : a ∉ S) (hb : b ∉ S) (hc : c ∉ S) :
    lift hj hjr (p.trans q) hpq ha hc = (lift hj hjr p hp ha hb).trans (lift hj hjr q hq hb hc) :=
  hj.isEmbedding.liftPath_trans _ _ _ _ _ _ _ _

private lemma lift_symm {a b : ℂ} (p : Path a b) (hp : ∀ t, p t ∉ S) (hp' : ∀ t, p.symm t ∉ S)
    (ha : a ∉ S) (hb : b ∉ S) :
    lift hj hjr p.symm hp' hb ha = (lift hj hjr p hp ha hb).symm :=
  hj.isEmbedding.liftPath_symm _ _ _ _ _

/-- The class of a lift only depends on the path up to homotopy in a convex set missing `S`. -/
private lemma fromPath_lift_eq {K : Set ℂ} (hK : Convex ℝ K) (hKS : ∀ z ∈ K, z ∉ S) {a b : ℂ}
    (p q : Path a b) (hp : ∀ t, p t ∈ K) (hq : ∀ t, q t ∈ K) (ha : a ∉ S) (hb : b ∉ S) :
    FundamentalGroupoid.fromPath (Path.Homotopic.Quotient.mk
      (lift hj hjr p (fun t ↦ hKS _ (hp t)) ha hb)) =
    FundamentalGroupoid.fromPath (Path.Homotopic.Quotient.mk
      (lift hj hjr q (fun t ↦ hKS _ (hq t)) ha hb)) :=
  congrArg _ (Path.Homotopic.Quotient.eq.mpr (hj.isEmbedding.liftPath_homotopic_of_convex hK
    (fun z hz ↦ (mem_range_iff hjr).mpr (hKS z hz)) p q hp hq _ _))

/-- The class of the lift of a constant segment is the identity. -/
private lemma fromPath_lift_segment_self {K : Set ℂ} (hK : Convex ℝ K) (hKS : ∀ z ∈ K, z ∉ S)
    {a : ℂ} (haK : a ∈ K) (ha : a ∉ S) :
    FundamentalGroupoid.fromPath (Path.Homotopic.Quotient.mk
      (lift hj hjr (segmentPath a a) (fun t ↦ hKS _ (segmentPath_mem hK haK haK t)) ha ha)) =
      𝟙 _ := by
  have h := fromPath_lift_eq hj hjr hK hKS (segmentPath a a) (Path.refl a)
    (segmentPath_mem hK haK haK) (fun _ ↦ haK) ha ha
  rw [h]
  have : lift hj hjr (Path.refl a) (fun t ↦ hKS _ haK) ha ha = Path.refl _ :=
    hj.isEmbedding.path_ext fun t ↦ by rw [j_lift hj hjr]; exact (j_pt hj hjr a ha).symm
  rw [this]
  rfl

end Final

section Product

variable {S : Finset ℂ} (D : StripData S) {X : Type} [TopologicalSpace X] {j : X → ℂ}
  (hj : IsOpenEmbedding j) (hjr : range j = (↑S : Set ℂ)ᶜ)

open FundamentalGroupoid

local notation "⌈" γ "⌉" => fromPath (Path.Homotopic.Quotient.mk γ)

/-- The point over `corner i`. -/
private abbrev yC (i : ℕ) : X := pt hj hjr (D.corner i) (D.corner_notMem i)
/-- The point over `top i`. -/
private abbrev yT (i : ℕ) : X := pt hj hjr (D.top i) (D.top_notMem i)

/-- Bottom edge from `corner 0` to `corner i`. -/
private def arrB (i : ℕ) : FundamentalGroupoid.mk (yC D hj hjr 0) ⟶ .mk (yC D hj hjr i) :=
  ⌈lift hj hjr (segmentPath (D.corner 0) (D.corner i)) (fun t ↦ D.low_notMem _
    (segmentPath_mem D.convex_low (D.corner_mem_low 0) (D.corner_mem_low i) t)) _ _⌉

/-- Bottom edge from `corner i` to `corner (i + 1)`. -/
private def arrb (i : ℕ) : FundamentalGroupoid.mk (yC D hj hjr i) ⟶ .mk (yC D hj hjr (i + 1)) :=
  ⌈lift hj hjr (segmentPath (D.corner i) (D.corner (i + 1))) (fun t ↦ D.low_notMem _
    (segmentPath_mem D.convex_low (D.corner_mem_low i) (D.corner_mem_low (i + 1)) t)) _ _⌉

/-- Vertical edge up from `corner i` to `top i`. -/
private def arru (i : ℕ) (hi : i ≤ S.card) :
    FundamentalGroupoid.mk (yC D hj hjr i) ⟶ .mk (yT D hj hjr i) :=
  ⌈lift hj hjr (segmentPath (D.corner i) (D.top i)) (fun t ↦ D.thin_notMem hi _
    (segmentPath_mem (D.convex_thin i) (D.corner_mem_thin i) (D.top_mem_thin i) t)) _ _⌉

/-- Vertical edge down from `top i` to `corner i`. -/
private def arrd (i : ℕ) (hi : i ≤ S.card) :
    FundamentalGroupoid.mk (yT D hj hjr i) ⟶ .mk (yC D hj hjr i) :=
  ⌈lift hj hjr (segmentPath (D.top i) (D.corner i)) (fun t ↦ D.thin_notMem hi _
    (segmentPath_mem (D.convex_thin i) (D.top_mem_thin i) (D.corner_mem_thin i) t)) _ _⌉

/-- Top edge from `top (i + 1)` to `top i`. -/
private def arrt (i : ℕ) : FundamentalGroupoid.mk (yT D hj hjr (i + 1)) ⟶ .mk (yT D hj hjr i) :=
  ⌈lift hj hjr (segmentPath (D.top (i + 1)) (D.top i)) (fun t ↦ D.high_notMem _
    (segmentPath_mem D.convex_high (D.top_mem_high (i + 1)) (D.top_mem_high i) t)) _ _⌉

/-- Top edge from `top i` to `top 0`. -/
private def arrT (i : ℕ) : FundamentalGroupoid.mk (yT D hj hjr i) ⟶ .mk (yT D hj hjr 0) :=
  ⌈lift hj hjr (segmentPath (D.top i) (D.top 0)) (fun t ↦ D.high_notMem _
    (segmentPath_mem D.convex_high (D.top_mem_high i) (D.top_mem_high 0) t)) _ _⌉

private lemma arrB_comp_arrb (i : ℕ) :
    arrB D hj hjr i ≫ arrb D hj hjr i = arrB D hj hjr (i + 1) := by
  have hp := trans_apply_mem
    (segmentPath_mem D.convex_low (D.corner_mem_low 0) (D.corner_mem_low i))
    (segmentPath_mem D.convex_low (D.corner_mem_low i) (D.corner_mem_low (i + 1)))
  unfold arrB arrb
  rw [← fromPath_mk_trans, ← lift_trans hj hjr _ _ _ _ (fun t ↦ D.low_notMem _ (hp t))]
  exact fromPath_lift_eq hj hjr D.convex_low D.low_notMem _ _ hp
    (segmentPath_mem D.convex_low (D.corner_mem_low 0) (D.corner_mem_low (i + 1))) _ _

private lemma arrt_comp_arrT (i : ℕ) :
    arrt D hj hjr i ≫ arrT D hj hjr i = arrT D hj hjr (i + 1) := by
  have hp := trans_apply_mem
    (segmentPath_mem D.convex_high (D.top_mem_high (i + 1)) (D.top_mem_high i))
    (segmentPath_mem D.convex_high (D.top_mem_high i) (D.top_mem_high 0))
  unfold arrt arrT
  rw [← fromPath_mk_trans, ← lift_trans hj hjr _ _ _ _ (fun t ↦ D.high_notMem _ (hp t))]
  exact fromPath_lift_eq hj hjr D.convex_high D.high_notMem _ _ hp
    (segmentPath_mem D.convex_high (D.top_mem_high (i + 1)) (D.top_mem_high 0)) _ _

private lemma arrB_zero : arrB D hj hjr 0 = 𝟙 _ :=
  fromPath_lift_segment_self hj hjr D.convex_low D.low_notMem (D.corner_mem_low 0) _

private lemma arrT_zero : arrT D hj hjr 0 = 𝟙 _ :=
  fromPath_lift_segment_self hj hjr D.convex_high D.high_notMem (D.top_mem_high 0) _

private lemma arru_comp_arrd (i : ℕ) (hi : i ≤ S.card) :
    arru D hj hjr i hi ≫ arrd D hj hjr i hi = 𝟙 _ := by
  have hp := trans_apply_mem
    (segmentPath_mem (D.convex_thin i) (D.corner_mem_thin i) (D.top_mem_thin i))
    (segmentPath_mem (D.convex_thin i) (D.top_mem_thin i) (D.corner_mem_thin i))
  unfold arru arrd
  rw [← fromPath_mk_trans, ← lift_trans hj hjr _ _ _ _ (fun t ↦ D.thin_notMem hi _ (hp t))]
  rw [fromPath_lift_eq hj hjr (D.convex_thin i) (D.thin_notMem hi) _ (segmentPath _ _) hp
    (segmentPath_mem (D.convex_thin i) (D.corner_mem_thin i) (D.corner_mem_thin i)) _ _]
  exact fromPath_lift_segment_self hj hjr (D.convex_thin i) (D.thin_notMem hi)
    (D.corner_mem_thin i) _

private lemma arrd_comp_arru (i : ℕ) (hi : i ≤ S.card) :
    arrd D hj hjr i hi ≫ arru D hj hjr i hi = 𝟙 _ := by
  have hp := trans_apply_mem
    (segmentPath_mem (D.convex_thin i) (D.top_mem_thin i) (D.corner_mem_thin i))
    (segmentPath_mem (D.convex_thin i) (D.corner_mem_thin i) (D.top_mem_thin i))
  unfold arru arrd
  rw [← fromPath_mk_trans, ← lift_trans hj hjr _ _ _ _ (fun t ↦ D.thin_notMem hi _ (hp t))]
  rw [fromPath_lift_eq hj hjr (D.convex_thin i) (D.thin_notMem hi) _ (segmentPath _ _) hp
    (segmentPath_mem (D.convex_thin i) (D.top_mem_thin i) (D.top_mem_thin i)) _ _]
  exact fromPath_lift_segment_self hj hjr (D.convex_thin i) (D.thin_notMem hi)
    (D.top_mem_thin i) _

/-- The `i`-th standard loop, in `π₁(X, x₀)` with `x₀` over `corner 0`. -/
private def rho (i : ℕ) (hi : i < S.card) : FundamentalGroup X (yC D hj hjr 0) :=
  Path.Homotopic.Quotient.mk (lift hj hjr (D.loop i) (fun t ↦ (D.loop_mem hi le_rfl t).2)
    (D.corner_notMem 0) (D.corner_notMem 0))

private lemma bot_notMem {i : ℕ} (t : unitInterval) : D.bot i t ∉ S :=
  D.low_notMem _ (segmentPath_mem D.convex_low (D.corner_mem_low 0) (D.corner_mem_low i) t)

private lemma rho_eq (i : ℕ) (hi : i < S.card) :
    (rho D hj hjr i hi : FundamentalGroupoid.mk (yC D hj hjr 0) ⟶ _) =
      arrB D hj hjr i ≫ (arrb D hj hjr i ≫ arru D hj hjr (i + 1) hi ≫ arrt D hj hjr i ≫
        arrd D hj hjr i hi.le) ≫ inv (arrB D hj hjr i) := by
  have h₁ := segmentPath_mem D.convex_low (D.corner_mem_low i) (D.corner_mem_low (i + 1))
  have h₂ := segmentPath_mem (D.convex_thin (i + 1)) (D.corner_mem_thin (i + 1))
    (D.top_mem_thin (i + 1))
  have h₃ := segmentPath_mem D.convex_high (D.top_mem_high (i + 1)) (D.top_mem_high i)
  have h₄ := segmentPath_mem (D.convex_thin i) (D.top_mem_thin i) (D.corner_mem_thin i)
  have e : lift hj hjr (D.loop i) (fun t ↦ (D.loop_mem hi le_rfl t).2) (D.corner_notMem 0)
      (D.corner_notMem 0) =
      ((lift hj hjr (D.bot i) (bot_notMem D) (D.corner_notMem 0) (D.corner_notMem i)).trans
        ((((lift hj hjr _ (fun t ↦ D.low_notMem _ (h₁ t)) (D.corner_notMem i)
          (D.corner_notMem (i + 1))).trans
          (lift hj hjr _ (fun t ↦ D.thin_notMem hi _ (h₂ t)) (D.corner_notMem (i + 1))
            (D.top_notMem (i + 1)))).trans
          (lift hj hjr _ (fun t ↦ D.high_notMem _ (h₃ t)) (D.top_notMem (i + 1))
            (D.top_notMem i))).trans
          (lift hj hjr _ (fun t ↦ D.thin_notMem hi.le _ (h₄ t)) (D.top_notMem i)
            (D.corner_notMem i)))).trans
        (lift hj hjr (D.bot i) (bot_notMem D) (D.corner_notMem 0) (D.corner_notMem i)).symm := by
    refine hj.isEmbedding.path_ext fun t ↦ ?_
    rw [j_lift hj hjr]
    refine Path.trans_apply_compat (f := id) (g := j) (Path.trans_apply_compat (f := id) (g := j)
      (fun t ↦ (j_lift ..).symm) (Path.trans_apply_compat (f := id) (g := j)
        (Path.trans_apply_compat (f := id) (g := j) (Path.trans_apply_compat (f := id) (g := j)
          (fun t ↦ (j_lift ..).symm) (fun t ↦ (j_lift ..).symm)) (fun t ↦ (j_lift ..).symm))
        (fun t ↦ (j_lift ..).symm))) (fun t ↦ ?_) t
    change D.bot i (unitInterval.symm t) = j (lift hj hjr (D.bot i) (bot_notMem D)
      (D.corner_notMem 0) (D.corner_notMem i) (unitInterval.symm t))
    exact (j_lift ..).symm
  change ⌈lift hj hjr (D.loop i) (fun t ↦ (D.loop_mem hi le_rfl t).2) (D.corner_notMem 0)
    (D.corner_notMem 0)⌉ = _
  rw [e]
  simp only [fromPath_mk_trans, fromPath_mk_symm, Category.assoc]
  rfl

/-- **The product of the standard loops is the boundary of the big parallelogram**, by induction
on the number of factors: `σ₀ ⋯ σ_{k-1}` runs along the bottom to `corner k`, up, along the top
back to `top 0`, and down. -/
private lemma prod_rho (k : ℕ) (hk : k ≤ S.card) :
    ((List.ofFn fun i : Fin k ↦ rho D hj hjr i (lt_of_lt_of_le i.2 hk)).prod :
      FundamentalGroupoid.mk (yC D hj hjr 0) ⟶ _) =
      arrB D hj hjr k ≫ arru D hj hjr k hk ≫ arrT D hj hjr k ≫ arrd D hj hjr 0 (Nat.zero_le _) := by
  induction k with
  | zero =>
    rw [List.ofFn_zero, List.prod_nil, arrB_zero, arrT_zero, Category.id_comp, Category.id_comp,
      arru_comp_arrd]
    rfl
  | succ k ih =>
    rw [List.ofFn_succ', List.concat_eq_append, List.prod_append, List.prod_singleton]
    change (rho D hj hjr k _ : _ ⟶ _) ≫ (List.ofFn fun i : Fin k ↦ rho D hj hjr i _).prod = _
    rw [ih (Nat.le_of_succ_le hk), rho_eq]
    simp only [Category.assoc, IsIso.inv_hom_id_assoc]
    rw [reassoc_of% arrd_comp_arru, ← reassoc_of% arrt_comp_arrT, ← reassoc_of% arrB_comp_arrb]

/-- The boundary of the big parallelogram, lifted to `X`. -/
private def bigLift : Path (yC D hj hjr 0) (yC D hj hjr 0) :=
  lift hj hjr D.big (fun t ↦ fun hs ↦ D.notMem_far hs (D.big_mem t)) (D.corner_notMem 0)
    (D.corner_notMem 0)

private lemma prod_rho_eq_big :
    ((List.ofFn fun i : Fin S.card ↦ rho D hj hjr i i.2).prod : FundamentalGroup X _) =
      Path.Homotopic.Quotient.mk (bigLift D hj hjr) := by
  have h₂ := segmentPath_mem (D.convex_thin S.card) (D.corner_mem_thin S.card)
    (D.top_mem_thin S.card)
  have h₄ := segmentPath_mem (D.convex_thin 0) (D.top_mem_thin 0) (D.corner_mem_thin 0)
  have e : bigLift D hj hjr =
      (((lift hj hjr (D.bot S.card) (bot_notMem D) (D.corner_notMem 0)
        (D.corner_notMem S.card)).trans
        (lift hj hjr _ (fun t ↦ D.thin_notMem le_rfl _ (h₂ t)) (D.corner_notMem S.card)
          (D.top_notMem _))).trans
        (lift hj hjr _ (fun t ↦ D.high_notMem _ (segmentPath_mem D.convex_high
          (D.top_mem_high S.card) (D.top_mem_high 0) t)) (D.top_notMem S.card)
          (D.top_notMem 0))).trans
        (lift hj hjr _ (fun t ↦ D.thin_notMem (Nat.zero_le _) _ (h₄ t)) (D.top_notMem 0)
          (D.corner_notMem 0)) := by
    refine hj.isEmbedding.path_ext fun t ↦ ?_
    rw [bigLift, j_lift hj hjr]
    exact Path.trans_apply_compat (f := id) (g := j) (Path.trans_apply_compat (f := id) (g := j)
      (Path.trans_apply_compat (f := id) (g := j) (fun t ↦ (j_lift ..).symm)
        (fun t ↦ (j_lift ..).symm)) (fun t ↦ (j_lift ..).symm)) (fun t ↦ (j_lift ..).symm) t
  have := prod_rho D hj hjr S.card le_rfl
  change (_ : FundamentalGroupoid.mk (yC D hj hjr 0) ⟶ _) = ⌈bigLift D hj hjr⌉
  rw [this, e]
  simp only [fromPath_mk_trans, Category.assoc]
  rfl

/-- **Freeness in `X`**: glue the half-plane `half n` and the empty half-plane `right`. -/
private lemma isFreeFamily_rho : IsFreeFamily fun i : Fin S.card ↦ rho D hj hjr i i.2 := by
  classical
  have hmemj {z : ℂ} : z ∈ range j ↔ z ∉ S := mem_range_iff hjr
  set U : Set X := j ⁻¹' D.half S.card
  set V : Set X := j ⁻¹' D.right
  have hUo : IsOpen U := (D.isOpen_half _).preimage hj.continuous
  have hVo : IsOpen V := (D.isOpen_right).preimage hj.continuous
  have hUV : U ∪ V = univ := by rw [← preimage_union, D.half_union_right, preimage_univ]
  have hUr : range (j ∘ (Subtype.val : U → X)) = D.half S.card \ S := by
    rw [range_comp_preimage, hjr]
    ext z
    simp only [mem_inter_iff, mem_compl_iff, Finset.mem_coe, mem_sdiff]
    tauto
  have hVr : range (j ∘ (Subtype.val : V → X)) = D.right := by
    rw [range_comp_preimage, hjr]
    ext z
    simp only [mem_inter_iff, mem_compl_iff, Finset.mem_coe]
    exact ⟨fun h ↦ h.2, fun h ↦ ⟨fun hs ↦ D.notMem_right hs h, h⟩⟩
  have hUVeq : U ∩ V = j ⁻¹' D.thin S.card := by rw [← preimage_inter, D.half_inter_right]
  have hthin : D.thin S.card ⊆ range j := fun z hz ↦ hmemj.mpr (D.thin_notMem le_rfl z hz)
  have hUVs : SimplyConnectedSpace ↥(U ∩ V) := by
    have := simplyConnectedSpace_preimage hj.isEmbedding (D.convex_thin _)
      ⟨_, D.corner_mem_thin S.card⟩ hthin
    exact (Homeomorph.setCongr hUVeq).toHomotopyEquiv.simplyConnectedSpace
  have hy'thin : j (yC D hj hjr S.card) ∈ D.thin S.card := by
    rw [j_pt hj hjr]
    exact D.corner_mem_thin _
  have hy'UV : yC D hj hjr S.card ∈ U ∩ V := hUVeq ▸ hy'thin
  have hUVc : IsPathConnected (U ∩ V) := by
    rw [isPathConnected_iff_pathConnectedSpace]
    have : Nonempty ↥(U ∩ V) := ⟨⟨_, hy'UV⟩⟩
    infer_instance
  have hyU : yC D hj hjr 0 ∈ U := show j _ ∈ D.half S.card by
    rw [j_pt hj hjr]
    exact D.mem_half_of_le (D.shearRe_corner 0) (Nat.zero_le _)
  have hUc : IsPathConnected U := by
    rw [isPathConnected_iff_pathConnectedSpace]
    have : Nonempty U := ⟨⟨_, hyU⟩⟩
    refine Complex.pathConnectedSpace_of_isOpenEmbedding_of_range_eq_diff (C := D.half S.card)
      (S := S.filter (· ∈ D.half S.card)) (D.convex_half _) (D.isOpen_half _) (fun z hz ↦ ?_)
      (hj.comp hUo.isOpenEmbedding_subtypeVal) ?_
    · rw [Finset.coe_filter] at hz
      exact hz.2
    · rw [hUr, Finset.coe_filter]
      ext z
      simp only [mem_sdiff, mem_ofPred_eq, Finset.mem_coe, not_and]
      tauto
  have hVs : SimplyConnectedSpace V := by
    have := simplyConnectedSpace_preimage hj.isEmbedding D.convex_right
      ⟨_, show D.corner S.card ∈ D.right from (D.corner_mem_thin S.card).1⟩
      (fun z hz ↦ hmemj.mpr fun hs ↦ D.notMem_right hs hz)
    exact this
  have hVc : IsPathConnected V := by
    rw [isPathConnected_iff_pathConnectedSpace]
    have : Nonempty V := ⟨⟨_, hy'UV.2⟩⟩
    infer_instance
  -- the bottom path
  set β : Path (yC D hj hjr 0) (yC D hj hjr S.card) :=
    lift hj hjr (D.bot S.card) (bot_notMem D) (D.corner_notMem 0)
      (D.corner_notMem S.card)
  have hβU : range β ⊆ U := by
    rintro _ ⟨t, rfl⟩
    change j (β t) ∈ D.half S.card
    rw [j_lift hj hjr]
    exact (D.bot_mem le_rfl t).2
  -- the family of `U`
  have hloopU (i : Fin S.card) : range (lift hj hjr (D.loop i)
      (fun t ↦ (D.loop_mem i.2 le_rfl t).2) (D.corner_notMem 0) (D.corner_notMem 0)) ⊆ U := by
    rintro _ ⟨t, rfl⟩
    change j _ ∈ D.half S.card
    rw [j_lift hj hjr]
    exact (D.loop_mem i.2 le_rfl t).1
  let σU : Fin S.card → FundamentalGroup U ⟨_, hyU⟩ := fun i ↦
    Path.Homotopic.Quotient.mk ((lift hj hjr (D.loop i) (fun t ↦ (D.loop_mem i.2 le_rfl t).2)
      (D.corner_notMem 0) (D.corner_notMem 0)).codRestrict (hloopU i))
  have hσU : IsFreeFamily σU := isFreeFamily_half D S.card le_rfl U (j ∘ Subtype.val)
    (hj.comp hUo.isOpenEmbedding_subtypeVal) hUr ⟨_, hyU⟩
    (j_pt hj hjr (D.corner 0) (D.corner_notMem 0)) σU
    (fun i ↦ ⟨(lift hj hjr (D.loop i) (fun t ↦ (D.loop_mem i.2 le_rfl t).2)
      (D.corner_notMem 0) (D.corner_notMem 0)).codRestrict (hloopU i),
      fun t ↦ j_lift hj hjr _ _ _ _ t, rfl⟩)
  have := subsingleton_fundamentalGroup (⟨_, hy'UV.2⟩ : V)
  have hσV : IsFreeFamily (Fin.elim0 : Fin 0 → FundamentalGroup V ⟨_, hy'UV.2⟩) :=
    isFreeFamily_of_isEmpty _
  have hglue := isFreeFamily_glue hUo hVo hUV hUc hVc hUVc hUVs hyU hy'UV.1 hy'UV.2 β hβU hσU hσV
  have hfin := IsFreeFamily.comp_equiv hglue (Equiv.sumEmpty (Fin S.card) (Fin 0)).symm
  convert hfin using 1
  funext i
  simp only [Function.comp_apply, Equiv.sumEmpty_symm_apply, Sum.elim_inl]
  rfl

/-- The standard loops are loops around the points. -/
private lemma isLoopAround_rho (i : Fin S.card) :
    FundamentalGroup.IsLoopAround j (D.e i : ℂ) (rho D hj hjr i i.2) := by
  have hmemj {z : ℂ} : z ∈ range j ↔ z ∉ S := mem_range_iff hjr
  set W : Set X := j ⁻¹' D.strip i
  have hWo : IsOpen W := (D.isOpen_strip i).preimage hj.continuous
  have hWemb : IsEmbedding (j ∘ (Subtype.val : W → X)) :=
    (hj.comp hWo.isOpenEmbedding_subtypeVal).isEmbedding
  have hWr : range (j ∘ (Subtype.val : W → X)) = D.strip i \ {(D.e i : ℂ)} := by
    rw [range_comp_preimage, hjr]
    ext z
    simp only [mem_inter_iff, mem_compl_iff, Finset.mem_coe, mem_sdiff, mem_singleton_iff]
    constructor
    · rintro ⟨h1, h2⟩
      exact ⟨h2, fun h ↦ h1 (h ▸ (D.e i).2)⟩
    · rintro ⟨h1, h2⟩
      exact ⟨fun hs ↦ h2 ((D.mem_strip_iff hs).mp h1), h1⟩
  have hyW : yC D hj hjr i ∈ W := show j _ ∈ D.strip i by
    rw [j_pt hj hjr]
    exact D.mem_strip_left (D.shearRe_corner i)
  have hquad (t : unitInterval) : D.quad i t ∈ range (j ∘ (Subtype.val : W → X)) := by
    rw [hWr]
    obtain ⟨h1, h2⟩ := D.quad_mem i.2 t
    exact ⟨h1, fun h ↦ h2 (by rw [mem_singleton_iff.mp h]; exact (D.e i).2)⟩
  set qW : Path (⟨_, hyW⟩ : W) ⟨_, hyW⟩ :=
    hWemb.liftPath (D.quad i) hquad (j_pt hj hjr (D.corner i) (D.corner_notMem i))
      (j_pt hj hjr (D.corner i) (D.corner_notMem i))
  have h1 := (isLoopAround_quad D hWemb i hWr qW
    (fun t ↦ hWemb.apply_liftPath _ _ _ _ t)).map ⟨Subtype.val, continuous_subtype_val⟩
    (j' := j) (fun _ ↦ rfl)
  set β : Path (yC D hj hjr 0) (yC D hj hjr i) :=
    lift hj hjr (D.bot i) (bot_notMem D) (D.corner_notMem 0) (D.corner_notMem i)
  have h2 := h1.conj β.symm
  convert h2 using 1
  have e : lift hj hjr (D.loop i) (fun t ↦ (D.loop_mem i.2 le_rfl t).2) (D.corner_notMem 0)
      (D.corner_notMem 0) = (β.trans (qW.map continuous_subtype_val)).trans β.symm := by
    refine hj.isEmbedding.path_ext fun t ↦ ?_
    rw [j_lift hj hjr]
    refine Path.trans_apply_compat (f := id) (g := j) (Path.trans_apply_compat (f := id) (g := j)
      (fun t ↦ (j_lift ..).symm) (fun t ↦ (hWemb.apply_liftPath _ _ _ _ t).symm)) (fun t ↦ ?_) t
    change D.bot i (unitInterval.symm t) = j (β (unitInterval.symm t))
    exact (j_lift ..).symm
  change Path.Homotopic.Quotient.mk (lift hj hjr (D.loop i) _ _ _) =
    Path.Homotopic.Quotient.mk (β.symm.symm.trans ((qW.map continuous_subtype_val).trans β.symm))
  rw [e, Path.symm_symm]
  change fromPath (Path.Homotopic.Quotient.mk _) = fromPath (Path.Homotopic.Quotient.mk _)
  simp only [fromPath_mk_trans, Category.assoc]

/-- The reverse of the big parallelogram is a loop around `∞`, i.e. around `0` in the coordinate
`1 / z`. -/
private lemma isLoopAround_inv_bigLift :
    FundamentalGroup.IsLoopAround (fun x ↦ (j x)⁻¹) 0
      (Path.Homotopic.Quotient.mk (bigLift D hj hjr).symm) := by
  have hR := D.R_pos
  set A : Set X := j ⁻¹' D.far
  have hjA (a : A) : D.R < ‖j a‖ := a.2
  have hjA0 (a : A) : j a ≠ 0 := fun h ↦ by
    have := hjA a
    rw [h, norm_zero] at this
    linarith
  -- `A ≅ D(0, 1/R) ∖ {0}` by `a ↦ (j a)⁻¹`
  let Φ : A ≃ₜ ↥(ball (0 : ℂ) D.R⁻¹ \ {0}) :=
    { toFun a := ⟨(j a)⁻¹, by
        rw [mem_ball, dist_zero_right, norm_inv]
        exact inv_strictAnti₀ hR (hjA a), inv_ne_zero (hjA0 a)⟩
      invFun w := ⟨pt hj hjr ((w : ℂ)⁻¹) (fun hs ↦ D.notMem_far hs (by
          have h1 : ‖(w : ℂ)‖ < D.R⁻¹ := by simpa using w.2.1
          have h0 : (w : ℂ) ≠ 0 := w.2.2
          change D.R < ‖(w : ℂ)⁻¹‖
          rw [norm_inv]
          exact lt_inv_of_lt_inv₀ (norm_pos_iff.mpr h0) h1)), by
          change D.R < ‖j _‖
          rw [j_pt hj hjr, norm_inv]
          have h1 : ‖(w : ℂ)‖ < D.R⁻¹ := by simpa using w.2.1
          exact lt_inv_of_lt_inv₀ (norm_pos_iff.mpr w.2.2) h1⟩
      left_inv a := Subtype.ext (hj.injective (by rw [j_pt hj hjr, inv_inv]))
      right_inv w := Subtype.ext (by
        dsimp only
        rw [j_pt hj hjr, inv_inv])
      continuous_toFun := by
        refine Continuous.subtype_mk ?_ _
        exact (hj.continuous.comp continuous_subtype_val).inv₀ hjA0
      continuous_invFun := by
        refine Continuous.subtype_mk ?_ _
        refine hj.isEmbedding.toHomeomorph.symm.continuous.comp (Continuous.subtype_mk ?_ _)
        exact continuous_subtype_val.inv₀ fun w ↦ w.2.2 }
  have hAemb : IsEmbedding (fun a : A ↦ (j a)⁻¹) :=
    IsEmbedding.subtypeVal.comp Φ.isEmbedding
  have hAr : range (fun a : A ↦ (j a)⁻¹) = ball (0 : ℂ) D.R⁻¹ \ {0} := by
    have : (fun a : A ↦ (j a)⁻¹) = Subtype.val ∘ Φ := rfl
    rw [this, range_comp, Φ.range_coe, image_univ, Subtype.range_coe]
  -- the loop in `A`
  have hbigA : range (bigLift D hj hjr).symm ⊆ A := by
    rintro _ ⟨t, rfl⟩
    change D.R < ‖j (bigLift D hj hjr (unitInterval.symm t))‖
    rw [bigLift, j_lift hj hjr]
    exact D.big_mem _
  set γA := (bigLift D hj hjr).symm.codRestrict hbigA
  obtain ⟨Λ, hΛ, hΛ'⟩ := exists_log_shearQuad (ε := D.ε) (s := 0) (a := D.x 0)
    (b := D.x S.card) (c := -(D.R + 1)) (d := D.R + 1)
    (by simp only [shearRe, zero_re, zero_im, mul_zero, add_zero]
        linarith [D.x_zero, D.εR_nonneg])
    (by simp only [shearRe, zero_re, zero_im, mul_zero, add_zero]
        linarith [D.x_card, D.εR_nonneg])
    (by simp; linarith) (by simp; linarith)
  have hw : γA.WindsOnceAround (fun a : A ↦ (j a)⁻¹) 0 := by
    refine ⟨⟨fun t ↦ -Λ (unitInterval.symm t), by fun_prop⟩, fun t ↦ ?_, ?_⟩
    · change 0 + Complex.exp (-Λ (unitInterval.symm t)) =
        (j (bigLift D hj hjr (unitInterval.symm t)))⁻¹
      have := hΛ (unitInterval.symm t)
      rw [zero_add] at this
      rw [Complex.exp_neg, bigLift, j_lift hj hjr, zero_add, this]
      rfl
    · change -Λ (unitInterval.symm 1) = -Λ (unitInterval.symm 0) + 2 * Real.pi * I
      rw [unitInterval.symm_one, unitInterval.symm_zero, hΛ']
      ring
  have h1 := hw.isLoopAround (convex_ball 0 _) isOpen_ball
    (mem_ball_self (inv_pos.mpr hR)) hAemb hAr
  exact h1.map (j' := fun x : X ↦ (j x)⁻¹) ⟨Subtype.val, continuous_subtype_val⟩ (fun _ ↦ rfl)

end Product

end OrderedPunctures

open OrderedPunctures FundamentalGroup

/-- **`π₁(ℂ ∖ S)` with ordered loops around the punctures and the loop around `∞`.** Let
`S ⊆ ℂ` be finite with `n` elements and `j : X → ℂ` an open embedding onto `ℂ ∖ S` (for instance
the inclusion, `Complex.exists_ordered_freeGroupBasis`). Then at every base point `x` there are an
enumeration `e : Fin n ≃ S` of the punctures and a free basis `σ₀, …, σ_{n-1}` of `π₁(X, x)` such
that `σᵢ` is a loop around `e i` (`FundamentalGroup.IsLoopAround`: conjugate to a small circle
around `e i`, run counterclockwise) and `(σ₀ ⋯ σ_{n-1})⁻¹` is a loop around `∞`, that is a loop
around `0` in the coordinate `1 / j`. In other words `π₁(ℙ¹(ℂ) ∖ (S ∪ {∞}))` is generated by loops
`σ₀, …, σ_{n-1}, σ_∞` around the `n + 1` punctures, subject to `σ₀ ⋯ σ_{n-1} σ_∞ = 1` only; this
is SGA 1 XIII.2.12's presentation in genus `0`, on the topological side. -/
theorem exists_ordered_freeGroupBasis_of_isOpenEmbedding {S : Finset ℂ} {X : Type}
    [TopologicalSpace X] {j : X → ℂ} (hj : IsOpenEmbedding j) (hjr : range j = (↑S : Set ℂ)ᶜ)
    (x : X) :
    ∃ (e : Fin S.card ≃ S) (b : FreeGroupBasis (Fin S.card) (FundamentalGroup X x)),
      (∀ i, IsLoopAround j (e i : ℂ) (b i)) ∧
        IsLoopAround (fun z ↦ (j z)⁻¹) 0 ((List.ofFn b).prod)⁻¹ := by
  have hjr' : range j = univ \ (↑S : Set ℂ) := by rw [hjr, compl_eq_univ_sdiff]
  have : Nonempty X := ⟨x⟩
  have hX : PathConnectedSpace X := pathConnectedSpace_of_isOpenEmbedding_of_range_eq_diff
    convex_univ isOpen_univ (subset_univ _) hj hjr'
  rcases S.eq_empty_or_nonempty with rfl | hS
  · -- no puncture: `X ≅ ℂ` is simply connected
    have hu : range j = univ := by rw [hjr]; simp
    have : ContractibleSpace (univ : Set ℂ) := convex_univ.contractibleSpace univ_nonempty
    have : SimplyConnectedSpace X :=
      (hj.isEmbedding.toHomeomorph.trans
        (Homeomorph.setCongr hu)).toHomotopyEquiv.simplyConnectedSpace
    have := subsingleton_fundamentalGroup x
    have : IsEmpty (Fin (∅ : Finset ℂ).card) := ⟨fun i ↦ by simpa using i.2⟩
    have : IsEmpty (∅ : Finset ℂ) := ⟨fun s ↦ Finset.notMem_empty _ s.2⟩
    refine ⟨Equiv.equivOfIsEmpty _ _, FreeGroupBasis.ofUniqueLift _ isEmptyElim
      (fun {H} _ g ↦ isFreeFamily_of_isEmpty _ H g), fun i ↦ isEmptyElim i, ?_⟩
    -- a loop around `∞`, which is trivial like everything in `π₁(X, x)`
    have hmem (w : ↥(closedBall (0 : ℂ) 1 \ {0})) : (w : ℂ)⁻¹ ∈ range j := by rw [hu]; trivial
    let κ : C(↥(closedBall (0 : ℂ) 1 \ {0}), X) :=
      ⟨fun w ↦ hj.isEmbedding.toHomeomorph.symm ⟨(w : ℂ)⁻¹, hmem w⟩, by
        refine hj.isEmbedding.toHomeomorph.symm.continuous.comp (Continuous.subtype_mk ?_ _)
        exact continuous_subtype_val.inv₀ fun w ↦ w.2.2⟩
    have hκ (w : ↥(closedBall (0 : ℂ) 1 \ {0})) : (j (κ w))⁻¹ = w := by
      have := congrArg Subtype.val (hj.isEmbedding.toHomeomorph.apply_symm_apply ⟨_, hmem w⟩)
      change (j (hj.isEmbedding.toHomeomorph.symm ⟨_, hmem w⟩))⁻¹ = _
      rw [show j (hj.isEmbedding.toHomeomorph.symm ⟨_, hmem w⟩) = (w : ℂ)⁻¹ from this, inv_inv]
    exact ⟨1, one_pos, κ, hκ, PathConnectedSpace.somePath _ _, Subsingleton.elim _ _⟩
  · obtain ⟨D⟩ := exists_stripData S hS
    let p := PathConnectedSpace.somePath (yC D hj hjr 0) x
    let ψ := fundamentalGroupMulEquivOfPath p
    let b₀ : FreeGroupBasis (Fin S.card) (FundamentalGroup X (yC D hj hjr 0)) :=
      FreeGroupBasis.ofUniqueLift (Fin S.card) (fun i ↦ rho D hj hjr i i.2)
        (fun {H} _ g ↦ isFreeFamily_rho D hj hjr H g)
    have hb₀ (i : Fin S.card) : b₀ i = rho D hj hjr i i.2 := by
      change (FreeGroupBasis.ofUniqueLift _ _ _).repr.symm (FreeGroup.of i) = _
      simp [FreeGroupBasis.ofUniqueLift, FreeGroupBasis.ofLift]
    refine ⟨D.e, b₀.map ψ, fun i ↦ ?_, ?_⟩
    · rw [FreeGroupBasis.map_apply, hb₀]
      exact (isLoopAround_rho D hj hjr i).conj p
    · have hprod : (List.ofFn (b₀.map ψ)).prod =
          ψ (List.ofFn fun i : Fin S.card ↦ rho D hj hjr i i.2).prod := by
        rw [map_list_prod, List.map_ofFn]
        congr 1
        exact List.ofFn_inj.mpr (funext fun i ↦ by
          simp only [Function.comp_apply, FreeGroupBasis.map_apply, hb₀])
      rw [hprod, prod_rho_eq_big, ← map_inv]
      exact (isLoopAround_inv_bigLift D hj hjr).conj p

/-- **`π₁(ℂ ∖ S)` with ordered loops around the punctures and the loop around `∞`**: the case of
the inclusion of `ℂ ∖ S` in `exists_ordered_freeGroupBasis_of_isOpenEmbedding`. -/
theorem exists_ordered_freeGroupBasis (S : Finset ℂ) (x : ((↑S : Set ℂ)ᶜ : Set ℂ)) :
    ∃ (e : Fin S.card ≃ S) (b : FreeGroupBasis (Fin S.card)
      (FundamentalGroup ((↑S : Set ℂ)ᶜ : Set ℂ) x)),
      (∀ i, IsLoopAround Subtype.val (e i : ℂ) (b i)) ∧
        IsLoopAround (fun z : ((↑S : Set ℂ)ᶜ : Set ℂ) ↦ (z : ℂ)⁻¹) 0 ((List.ofFn b).prod)⁻¹ :=
  exists_ordered_freeGroupBasis_of_isOpenEmbedding
    (S.finite_toSet.isClosed.isOpen_compl.isOpenEmbedding_subtypeVal) Subtype.range_coe x

end Complex
