/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.Foundations.Topology.FundamentalGroupFG

/-!
# The Seifert–van Kampen theorem: generation

Let `X` be covered by open sets `W i`, all containing the base point `x`, such that every
`W i ∩ W j` is path-connected (in particular every `W i` is). Then `π₁(X, x)` is generated by the
images of the groups `π₁(W i, x)` (`FundamentalGroup.iSup_range_map_subtypeVal_eq_top`); for two
open sets `U ∪ V = X` with `U`, `V`, `U ∩ V` path-connected, `π₁(X, x)` is generated by the images
of `π₁(U, x)` and `π₁(V, x)` (`FundamentalGroup.range_map_subtypeVal_sup_eq_top`).

This is the surjectivity half of the Seifert–van Kampen theorem. The description of the kernel
(`π₁(X) = π₁(U) *_{π₁(U ∩ V)} π₁(V)`) is in `Foundations/Topology/VanKampenPushout.lean`
(`FundamentalGroup.existsUnique_hom_of_union`, `FundamentalGroup.pushoutIMulEquiv`) and, in
Hatcher's form with path-connected triple intersections, in
`Foundations/Topology/VanKampenTriple.lean`
(`FundamentalGroup.existsUnique_hom_of_isOpen_cover_of_isPathConnected_inter`,
`FundamentalGroup.vanKampenMulEquiv`). The proof here is `FundamentalGroup.eq_top_of_isOpen_cover`,
the same edge-path argument that proves finite generation of `π₁` of compact spaces.

## References

* [A. Hatcher, *Algebraic Topology*, Theorem 1.20][hatcher02]
-/

open Set Topology CategoryTheory

variable {X : Type*} [TopologicalSpace X]

namespace FundamentalGroup

open FundamentalGroupoid

/-- The class of a path, as an arrow of the fundamental groupoid. -/
local notation "⌈" γ "⌉" => FundamentalGroupoid.fromPath (Path.Homotopic.Quotient.mk γ)

/-- The homomorphism `π₁(U, x) → π₁(X, x)` induced by the inclusion of a subset `U ∋ x`. -/
noncomputable abbrev mapSubtypeVal {U : Set X} {x : X} (hx : x ∈ U) :
    FundamentalGroup U ⟨x, hx⟩ →* FundamentalGroup X x :=
  FundamentalGroup.map ⟨Subtype.val, continuous_subtype_val⟩ ⟨x, hx⟩

/-- A loop at `x` with values in `U` lies in the image of `π₁(U, x) → π₁(X, x)`. -/
theorem fromPath_mem_range_mapSubtypeVal {U : Set X} {x : X} (hx : x ∈ U) (γ : Path x x)
    (hγ : range γ ⊆ U) : fromArrow ⌈γ⌉ ∈ (mapSubtypeVal hx).range :=
  ⟨fromArrow ⌈γ.codRestrict hγ⌉, rfl⟩

/-- **Seifert–van Kampen, generation.** Let `X` be covered by open sets `W i`, all containing `x`,
such that every `W i ∩ W j` is path-connected. Then `π₁(X, x)` is generated by the images of the
`π₁(W i, x)`. -/
theorem iSup_range_map_subtypeVal_eq_top {ι : Type*} (W : ι → Set X) (hWo : ∀ i, IsOpen (W i))
    (hcov : ∀ y, ∃ i, y ∈ W i) {x : X} (hx : ∀ i, x ∈ W i)
    (hWW : ∀ i j, IsPathConnected (W i ∩ W j)) :
    ⨆ i, (mapSubtypeVal (hx i)).range = ⊤ := by
  classical
  set H := ⨆ i, (mapSubtypeVal (hx i)).range
  have hH : ∀ i (γ : Path x x), range γ ⊆ W i → fromArrow ⌈γ⌉ ∈ H := fun i γ hγ ↦
    le_iSup (fun i ↦ (mapSubtypeVal (hx i)).range) i (fromPath_mem_range_mapSubtypeVal _ γ hγ)
  have hWc : ∀ i, IsPathConnected (W i) := fun i ↦ by simpa using hWW i i
  -- standard paths from `x` to `y ∈ W i` inside `W i`
  let ρ : ∀ i (y : X), y ∈ W i → Path x y := fun i y hy ↦ ((hWc i).joinedIn _ (hx i) _ hy).somePath
  have hρ : ∀ i y (hy : y ∈ W i), range (ρ i y hy) ⊆ W i := fun i y hy ↦
    range_subset_iff.mpr ((hWc i).joinedIn _ (hx i) _ hy).somePath_mem
  let s : ι → ∀ y : X, mk x ⟶ mk y := fun i y ↦
    if hy : y ∈ W i then ⌈ρ i y hy⌉ else ⌈ρ _ y (hcov y).choose_spec⌉
  refine eq_top_of_isOpen_cover W hWo hcov H s ?_ ?_ ?_
  · intro i y z σ hσ
    have hy : y ∈ W i := hσ ⟨0, σ.source⟩
    have hz : z ∈ W i := hσ ⟨1, σ.target⟩
    simp only [s, hy, hz, ↓reduceDIte]
    have := hH i (((ρ i y hy).trans σ).trans (ρ i z hz).symm) (by
      simp only [Path.trans_range, Path.symm_range]
      exact union_subset (union_subset (hρ i y hy) hσ) (hρ i z hz))
    rwa [fromPath_mk_trans, fromPath_mk_trans, fromPath_mk_symm, Category.assoc] at this
  · intro i j y hi hj
    simp only [s, hi, hj, ↓reduceDIte]
    obtain ⟨τ, hτ⟩ := (hWW i j).joinedIn _ ⟨hx i, hx j⟩ _ ⟨hi, hj⟩
    have hτ' : range τ ⊆ W i ∩ W j := range_subset_iff.mpr hτ
    have h₁ := hH i ((ρ i y hi).trans τ.symm) (by
      simp only [Path.trans_range, Path.symm_range]
      exact union_subset (hρ i y hi) (hτ'.trans inter_subset_left))
    have h₂ := hH j (τ.trans (ρ j y hj).symm) (by
      simp only [Path.trans_range, Path.symm_range]
      exact union_subset (hτ'.trans inter_subset_right) (hρ j y hj))
    have := H.mul_mem h₂ h₁
    rw [fromPath_mk_trans, fromPath_mk_trans, fromPath_mk_symm, fromPath_mk_symm] at this
    convert this using 1
    change _ = fromArrow ((⌈ρ i y hi⌉ ≫ inv ⌈τ⌉) ≫ ⌈τ⌉ ≫ inv ⌈ρ j y hj⌉)
    simp
  · intro i hi
    simp only [s, hi, ↓reduceDIte]
    exact hH i _ (hρ i x hi)

/-- **Seifert–van Kampen, generation, for two open sets.** If `X = U ∪ V` with `U`, `V` open and
`U`, `V`, `U ∩ V` path-connected, and `x ∈ U ∩ V`, then `π₁(X, x)` is generated by the images of
`π₁(U, x)` and `π₁(V, x)`. -/
theorem range_map_subtypeVal_sup_eq_top {U V : Set X} (hU : IsOpen U) (hV : IsOpen V)
    (hUV : U ∪ V = univ) (hUc : IsPathConnected U) (hVc : IsPathConnected V)
    (hUVc : IsPathConnected (U ∩ V)) {x : X} (hxU : x ∈ U) (hxV : x ∈ V) :
    (mapSubtypeVal hxU).range ⊔ (mapSubtypeVal hxV).range = ⊤ := by
  let W : Bool → Set X := fun b ↦ cond b U V
  have h := iSup_range_map_subtypeVal_eq_top W (fun b ↦ by cases b <;> assumption)
    (fun y ↦ by
      have : y ∈ U ∪ V := hUV ▸ mem_univ y
      rcases this with h | h
      · exact ⟨true, h⟩
      · exact ⟨false, h⟩)
    (x := x) (fun b ↦ by cases b <;> assumption)
    (fun i j ↦ by cases i <;> cases j <;> simp [W, inter_comm, *])
  rw [← h, iSup_bool_eq]
  rfl

end FundamentalGroup
