/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import Mathlib.GroupTheory.PushoutI
import SGA.Foundations.Topology.CoveringOfFunctor
import SGA.Foundations.Topology.PathConnectedHelpersBasic
import SGA.Foundations.Topology.VanKampen

/-!
# The Seifert–van Kampen theorem

Let `X` be covered by open sets `W i`.

* **Groupoid form** (R. Brown's theorem, restricted to functors to groups): functors
  `F i : π(W i) ⥤ G` to a group `G` (a one-object category) that agree on paths in the overlaps
  `W i ∩ W j` glue to a unique functor `π(X) ⥤ G`
  (`FundamentalGroupoid.existsUnique_functor_of_isOpen_cover`; in terms of restrictions of
  functors, `FundamentalGroupoid.existsUnique_functor_comp_eq_of_isOpen_cover`). No connectedness
  hypothesis is needed. Brown's theorem allows any groupoid as target; only groups are treated
  here.
* **Group form**: if the `W i` are path-connected and all pairwise intersections `W i ∩ W j`
  (`i ≠ j`) lie in one path-connected set `A ⊆ ⋂ W i` containing the base point `x`, then
  homomorphisms `π₁(W i, x) →* G` that agree on `π₁(A, x)` extend uniquely to `π₁(X, x)`
  (`FundamentalGroup.existsUnique_hom_of_isOpen_cover`), i.e. `π₁(X, x)` is the amalgamated
  product `*_{π₁(A, x)} π₁(W i, x)` (`FundamentalGroup.pushoutIMulEquiv`, with mathlib's
  `Monoid.PushoutI`).
* **Two open sets**: `X = U ∪ V` with `U`, `V`, `U ∩ V` path-connected:
  `π₁(X, x) = π₁(U, x) *_{π₁(U ∩ V, x)} π₁(V, x)` as a universal property
  (`FundamentalGroup.existsUnique_hom_of_union`).

The generation half (`π₁(X, x)` is generated by the images of the `π₁(W i, x)`) is
`FundamentalGroup.iSup_range_map_subtypeVal_eq_top` in `Foundations/Topology/VanKampen.lean`; it
gives the uniqueness part here.

For more than two sets the group form asks for a common intersection `A`, which is stronger than
Hatcher's hypothesis (path-connected triple intersections); it covers two open sets and wedges
glued along a neighbourhood of the base point. Hatcher's form is in
`Foundations/Topology/VanKampenTriple.lean`
(`FundamentalGroup.existsUnique_hom_of_isOpen_cover_of_isPathConnected_inter`, with the
presentation `FundamentalGroup.vanKampenMulEquiv`).

## Proof

The glued functor is evaluated on a path `γ` by *developing* `γ`
(`FundamentalGroupoid.VanKampen.IsDevelopment`): a function `D : [0, 1] → G` with `D 0 = 1` such
that near every `t`, for some `i` with `γ` near `t` in `W i`, `D s = F i (γ|[t, s]) * D t`.
Developments are unique and exist, by connectedness of `[0, 1]` (the argument of
`FundamentalGroup.eq_top_of_isOpen_cover`). Homotopy invariance holds because the value is locally
constant in the homotopy parameter: a Lebesgue number on `{s₀} × [0, 1]` and the relation of
`F i` on the four sides of a small square (`FundamentalGroupoid.VanKampen.localValue_square`).
Every local homotopy needed lives in a square `I × I` or an interval, which is simply connected,
so no explicit subdivision of `[0, 1]` is used.

## References

* [A. Hatcher, *Algebraic Topology*, Theorem 1.20][hatcher02]
* R. Brown, *Topology and Groupoids*, §6.7 (the groupoid form)
-/

open Set Topology Filter CategoryTheory
open scoped unitInterval

universe u v w

namespace FundamentalGroupoid

open unitInterval

/-- `1 / 2` as a point of the unit interval. -/
private noncomputable def half : I :=
  ⟨1 / 2, by norm_num, by norm_num⟩

variable {X : Type u} [TopologicalSpace X]

/-- The class of a path, as an arrow of the fundamental groupoid. -/
local notation "⌈" γ "⌉" => FundamentalGroupoid.fromPath (Path.Homotopic.Quotient.mk γ)

/-! ### Functors to a group, evaluated on paths -/

section SingleObj

variable {Y : Type*} [TopologicalSpace Y] {G : Type v} [Group G]

/-- A functor to a group takes the same value on a path and on its casts. -/
lemma map_fromPath_cast (F : FundamentalGroupoid Y ⥤ SingleObj G) {y z y' z' : Y}
    (p : Path y z) (hy : y' = y) (hz : z' = z) :
    (F.map ⌈p.cast hy hz⌉ : G) = F.map ⌈p⌉ := by
  subst hy hz
  rfl

end SingleObj

/-! ### Developments of paths -/

section Development

namespace VanKampen

variable {G : Type v} [Group G] {ι : Type w} {W : ι → Set X}
  (F : ∀ i, FundamentalGroupoid (W i) ⥤ SingleObj G)

open scoped Classical in
/-- The value of the local functor `F i` on a path of `X` with values in `W i` (and `1` on the
other paths). -/
noncomputable def localValue (i : ι) {y z : X} (p : Path y z) : G :=
  if h : range p ⊆ W i then F i |>.map ⌈p.codRestrict h⌉ else 1

/-- The local functors are *compatible* if they agree on paths in the overlaps. -/
def LocalCompatible : Prop :=
  ∀ i j {y z : X} (p : Path y z), range p ⊆ W i → range p ⊆ W j →
    localValue F i p = localValue F j p

variable {F}

lemma localValue_of_subset {i : ι} {y z : X} (p : Path y z) (h : range p ⊆ W i) :
    localValue F i p = (F i).map ⌈p.codRestrict h⌉ := by
  simp [localValue, h]

/-- `localValue` only depends on the underlying function of the path. -/
lemma localValue_congr (i : ι) {y z y' z' : X} {p : Path y z} {p' : Path y' z'}
    (h : ∀ t, p t = p' t) : localValue F i p = localValue F i p' := by
  obtain rfl : y = y' := by rw [← p.source, ← p'.source, h]
  obtain rfl : z = z' := by rw [← p.target, ← p'.target, h]
  obtain rfl : p = p' := Path.ext (funext h)
  rfl

lemma localValue_trans {i : ι} {y z w : X} (p : Path y z) (τ : Path z w) (hp : range p ⊆ W i)
    (hτ : range τ ⊆ W i) : localValue F i (p.trans τ) = localValue F i τ * localValue F i p := by
  have h : range (p.trans τ) ⊆ W i := by rw [Path.trans_range]; exact union_subset hp hτ
  rw [localValue_of_subset _ h, localValue_of_subset _ hp, localValue_of_subset _ hτ,
    Path.codRestrict_trans _ _ h hp hτ, ← SingleObj.comp_as_mul, ← Functor.map_comp]
  rfl

lemma localValue_refl (i : ι) (y : X) : localValue F i (Path.refl y) = 1 := by
  by_cases h : range (Path.refl y) ⊆ W i
  · rw [localValue_of_subset _ h, Path.codRestrict_refl]
    exact (F i).map_id _
  · exact dite_eq_right h

lemma localValue_eq_one_of_forall_eq (i : ι) {y z : X} (p : Path y z) (h : ∀ t, p t = y) :
    localValue F i p = 1 :=
  (localValue_congr i (p' := Path.refl y) h).trans (localValue_refl i y)

/-- The local functor `F i` takes the same value on the images of two paths with the same
endpoints in a simply connected space `Y`, under a map `g : Y → W i`. -/
lemma localValue_map_eq {i : ι} {Y : Type*} [TopologicalSpace Y] [SimplyConnectedSpace Y]
    (g : C(Y, X)) (hg : range g ⊆ W i) {a b : Y} (α β : Path a b) :
    localValue F i (α.map g.continuous) = localValue F i (β.map g.continuous) := by
  have hα : range (α.map g.continuous) ⊆ W i := by rintro _ ⟨t, rfl⟩; exact hg ⟨α t, rfl⟩
  have hβ : range (β.map g.continuous) ⊆ W i := by rintro _ ⟨t, rfl⟩; exact hg ⟨β t, rfl⟩
  rw [localValue_of_subset _ hα, localValue_of_subset _ hβ]
  let g' : C(Y, W i) := ⟨fun y ↦ ⟨g y, hg ⟨y, rfl⟩⟩, by fun_prop⟩
  have e : ∀ γ : Path a b, ∀ h : range (γ.map g.continuous) ⊆ W i,
      (γ.map g.continuous).codRestrict h = γ.map g'.continuous := fun _ _ ↦ rfl
  rw [e, e, Path.Homotopic.Quotient.mk_map, Path.Homotopic.Quotient.mk_map,
    (Path.Homotopic.Quotient.eq).mpr (SimplyConnectedSpace.paths_homotopic α β)]

/-- The clamp `u ↦ max a (min b u)` of the unit interval onto `[a, b]`. -/
private def clamp (a b : I) : C(I, I) :=
  ⟨fun u ↦ max a (min b u), by fun_prop⟩

private lemma clamp_of_mem {a b u : I} (h : u ∈ Icc a b) : clamp a b u = u := by
  simp [clamp, min_eq_right h.2, max_eq_right h.1]

private lemma range_clamp_subset {a b : I} (hab : a ≤ b) : range (clamp a b) ⊆ Icc a b := by
  rintro _ ⟨u, rfl⟩
  exact ⟨le_max_left _ _, max_le hab (min_le_left _ _)⟩

/-- **The cocycle relation.** If `γ` maps the intervals between `t₀` and `t₁` and between `t₀` and
`t₂` into `W i`, then the values of `F i` on the subpaths compose. -/
lemma localValue_subpath_trans {i : ι} {y z : X} (γ : Path y z) {t₀ t₁ t₂ : I}
    (h₁ : γ '' uIcc t₀ t₁ ⊆ W i) (h₂ : γ '' uIcc t₀ t₂ ⊆ W i) :
    localValue F i (γ.subpath t₀ t₂) =
      localValue F i (γ.subpath t₁ t₂) * localValue F i (γ.subpath t₀ t₁) := by
  set a := (t₀ ⊓ t₁) ⊓ (t₀ ⊓ t₂)
  set b := (t₀ ⊔ t₁) ⊔ (t₀ ⊔ t₂)
  have hab : a ≤ b := inf_le_left.trans (inf_le_left.trans (le_sup_left.trans le_sup_left))
  have hK : Icc a b ⊆ uIcc t₀ t₁ ∪ uIcc t₀ t₂ := by
    rw [uIcc, uIcc, Icc_union_Icc' (inf_le_left.trans le_sup_left)
      (inf_le_left.trans le_sup_left)]
  have hsub : ∀ {u v : I}, u ∈ Icc a b → v ∈ Icc a b → uIcc u v ⊆ Icc a b := fun hu hv ↦
    uIcc_subset_Icc hu hv
  have ht₀ : t₀ ∈ Icc a b :=
    ⟨inf_le_left.trans inf_le_left, le_sup_left.trans le_sup_left⟩
  have ht₁ : t₁ ∈ Icc a b :=
    ⟨inf_le_left.trans inf_le_right, le_sup_right.trans le_sup_left⟩
  have ht₂ : t₂ ∈ Icc a b :=
    ⟨inf_le_right.trans inf_le_right, le_sup_right.trans le_sup_right⟩
  let g : C(I, X) := γ.toContinuousMap.comp (clamp a b)
  have hg : range g ⊆ W i := by
    rintro _ ⟨u, rfl⟩
    have := hK (range_clamp_subset hab ⟨u, rfl⟩)
    rcases this with h | h
    · exact h₁ ⟨_, h, rfl⟩
    · exact h₂ ⟨_, h, rfl⟩
  have key : ∀ {u v : I}, u ∈ Icc a b → v ∈ Icc a b →
      ∀ s, (Path.id.subpath u v).map g.continuous s = γ.subpath u v s := by
    intro u v hu hv s
    change γ (clamp a b _) = γ _
    rw [clamp_of_mem (hsub hu hv _)]
    · rfl
    · rw [← Path.range_subpathAux u v]
      exact ⟨s, rfl⟩
  have hr : ∀ {u v : I}, u ∈ Icc a b → v ∈ Icc a b →
      range ((Path.id.subpath u v).map g.continuous) ⊆ W i := by
    rintro u v - - _ ⟨t, rfl⟩
    exact hg ⟨_, rfl⟩
  calc localValue F i (γ.subpath t₀ t₂)
      = localValue F i ((Path.id.subpath t₀ t₂).map g.continuous) :=
        localValue_congr i fun s ↦ (key ht₀ ht₂ s).symm
    _ = localValue F i (((Path.id.subpath t₀ t₁).trans (Path.id.subpath t₁ t₂)).map g.continuous) :=
        localValue_map_eq g hg _ _
    _ = localValue F i (((Path.id.subpath t₀ t₁).map g.continuous).trans
          ((Path.id.subpath t₁ t₂).map g.continuous)) := by rw [Path.map_trans]
    _ = localValue F i ((Path.id.subpath t₁ t₂).map g.continuous) *
          localValue F i ((Path.id.subpath t₀ t₁).map g.continuous) :=
        localValue_trans _ _ (hr ht₀ ht₁) (hr ht₁ ht₂)
    _ = _ := by
        rw [localValue_congr i (key ht₁ ht₂), localValue_congr i (key ht₀ ht₁)]

/-- The square relation: for a map `φ` from the square `I × I` into `W i`, the values of `F i` on
the four edges (given as paths with the same values) satisfy `top · left = right · bottom`. -/
lemma localValue_square {i : ι} (φ : C(I × I, X)) (hφ : range φ ⊆ W i)
    {a b c d a' b' c' d' : X} (pb : Path a b) (pt : Path c d) (pl : Path a' c') (pr : Path b' d')
    (hb : ∀ u, pb u = φ (u, 0)) (ht : ∀ u, pt u = φ (u, 1)) (hl : ∀ v, pl v = φ (0, v))
    (hr : ∀ v, pr v = φ (1, v)) :
    localValue F i pt * localValue F i pl = localValue F i pr * localValue F i pb := by
  let L : Path ((0 : I), (0 : I)) (0, 1) := (Path.refl 0).prod Path.id
  let T : Path ((0 : I), (1 : I)) (1, 1) := Path.id.prod (Path.refl 1)
  let B : Path ((0 : I), (0 : I)) (1, 0) := Path.id.prod (Path.refl 0)
  let R : Path ((1 : I), (0 : I)) (1, 1) := (Path.refl 1).prod Path.id
  have hr' : ∀ {p q : I × I} (γ : Path p q), range (γ.map φ.continuous) ⊆ W i := by
    rintro p q γ _ ⟨t, rfl⟩
    exact hφ ⟨_, rfl⟩
  have h := localValue_map_eq (F := F) φ hφ (L.trans T) (B.trans R)
  rw [Path.map_trans, Path.map_trans, localValue_trans _ _ (hr' _) (hr' _),
    localValue_trans _ _ (hr' _) (hr' _)] at h
  have e₁ : localValue F i (T.map φ.continuous) = localValue F i pt :=
    localValue_congr i fun u ↦ (ht u).symm
  have e₂ : localValue F i (L.map φ.continuous) = localValue F i pl :=
    localValue_congr i fun u ↦ (hl u).symm
  have e₃ : localValue F i (R.map φ.continuous) = localValue F i pr :=
    localValue_congr i fun u ↦ (hr u).symm
  have e₄ : localValue F i (B.map φ.continuous) = localValue F i pb :=
    localValue_congr i fun u ↦ (hb u).symm
  rwa [e₁, e₂, e₃, e₄] at h

variable (F) in
/-- `D` is a *development* of the path `γ` along the local functors `F i`: `D 0 = 1`, and near
every `t` there is an `i` such that `γ` maps the interval between `t` and `s` into `W i` and
`D s = F i (γ|[t, s]) * D t`. Think of `D t` as the value of the glued functor on `γ|[0, t]`. -/
def IsDevelopment {y z : X} (γ : Path y z) (D : I → G) : Prop :=
  D 0 = 1 ∧ ∀ t, ∃ i, ∀ᶠ s in 𝓝 t,
    γ '' uIcc t s ⊆ W i ∧ D s = localValue F i (γ.subpath t s) * D t

/-- Developments are unique. -/
lemma IsDevelopment.eq (hF : LocalCompatible F) {y z : X} {γ : Path y z} {D D' : I → G}
    (hD : IsDevelopment F γ D) (hD' : IsDevelopment F γ D') : D = D' := by
  have hlc : IsLocallyConstant (fun t ↦ D t = D' t) := by
    rw [IsLocallyConstant.iff_eventually_eq]
    intro t
    obtain ⟨i, hi⟩ := hD.2 t
    obtain ⟨j, hj⟩ := hD'.2 t
    filter_upwards [hi, hj] with s ⟨hsi, hs⟩ ⟨hsj, hs'⟩
    have hc : localValue F i (γ.subpath t s) = localValue F j (γ.subpath t s) :=
      hF i j _ (by rwa [Path.range_subpath]) (by rwa [Path.range_subpath])
    rw [hs, hs', hc, mul_right_inj]
  funext t
  have h := hlc.apply_eq_of_preconnectedSpace t 0
  simp only [hD.1, hD'.1] at h
  exact of_eq_true h

private lemma image_uIcc_subset_of {y z : X} (γ : Path y z) {τ a s : I} {U : Set X}
    (ha : γ '' uIcc τ a ⊆ U) (hs : γ '' uIcc τ s ⊆ U) : γ '' uIcc a s ⊆ U := by
  refine (image_mono (uIcc_subset_uIcc_union_uIcc (b := τ))).trans ?_
  rw [image_union, uIcc_comm a τ]
  exact union_subset ha hs

/-- Every path has a development. -/
lemma exists_isDevelopment (hWo : ∀ i, IsOpen (W i)) (hcov : ∀ y, ∃ i, y ∈ W i)
    (hF : LocalCompatible F) {y z : X} (γ : Path y z) : ∃ D, IsDevelopment F γ D := by
  let L : (I → G) → I → Prop := fun D t ↦ ∃ i, ∀ᶠ s in 𝓝 t,
    γ '' uIcc t s ⊆ W i ∧ D s = localValue F i (γ.subpath t s) * D t
  let T : Set I := {τ | ∃ D : I → G, D 0 = 1 ∧ ∀ t ≤ τ, L D t}
  have h0 : (0 : I) ∈ T := by
    obtain ⟨i, hi⟩ := hcov (γ 0)
    refine ⟨fun s ↦ localValue F i (γ.subpath 0 s), by simp [localValue_refl], fun t ht ↦ ?_⟩
    obtain rfl : t = 0 := le_antisymm ht nonneg'
    refine ⟨i, ?_⟩
    filter_upwards [γ.eventually_image_uIcc_subset (hWo _) hi] with s hs
    exact ⟨hs, by simp [localValue_refl]⟩
  have hopen : IsOpen T := by
    rw [isOpen_iff_mem_nhds]
    rintro τ ⟨D, hD0, hD⟩
    obtain ⟨i, hi⟩ := hD τ le_rfl
    have hev : ∀ᶠ t in 𝓝 τ, L D t := by
      filter_upwards [hi, hi.eventually_nhds] with t ⟨ht, hDt⟩ hs
      refine ⟨i, ?_⟩
      filter_upwards [hs] with s ⟨hs, hDs⟩
      refine ⟨image_uIcc_subset_of γ ht hs, ?_⟩
      rw [hDs, hDt, localValue_subpath_trans γ ht hs, mul_assoc]
    filter_upwards [eventually_uIcc_subset hev] with τ' hτ'
    refine ⟨D, hD0, fun t ht ↦ ?_⟩
    rcases le_total t τ with h | h
    · exact hD t h
    · exact hτ' (mem_uIcc_of_le h ht)
  have hclosed : IsClosed T := by
    refine isClosed_of_closure_subset fun τ hτ ↦ ?_
    obtain ⟨i, hi⟩ := hcov (γ τ)
    have hP := (γ.eventually_image_uIcc_subset (hWo _) hi).eventually_nhds
    obtain ⟨τ', hτ', hτ'T⟩ := mem_closure_iff_nhds.mp hτ _ (eventually_uIcc_subset hP)
    obtain ⟨D, hD0, hD⟩ := hτ'T
    rcases le_total τ τ' with hle | hlt
    · exact ⟨D, hD0, fun t ht ↦ hD t (ht.trans hle)⟩
    have hP' : ∀ t ∈ uIcc τ τ', γ '' uIcc τ t ⊆ W i := fun t ht ↦ (hτ' ht).self_of_nhds
    have hτ'i : γ '' uIcc τ τ' ⊆ W i := hP' τ' right_mem_uIcc
    classical
    let D' : I → G := fun s ↦ if τ' ≤ s then localValue F i (γ.subpath τ' s) * D τ' else D s
    have hD'τ' : D' τ' = D τ' := by simp [D', localValue_refl]
    refine ⟨D', ?_, fun t ht ↦ ?_⟩
    · by_cases h : τ' ≤ 0
      · obtain rfl : τ' = 0 := le_antisymm h nonneg'
        rw [hD'τ', hD0]
      · simp [D', h, hD0]
    rcases lt_trichotomy t τ' with h | h | h
    · obtain ⟨j, hj⟩ := hD t h.le
      refine ⟨j, ?_⟩
      filter_upwards [hj, Iio_mem_nhds h] with s hs hs'
      have e1 : D' s = D s := ite_eq_right (not_le.mpr hs')
      have e2 : D' t = D t := ite_eq_right (not_le.mpr h)
      rwa [e1, e2]
    · subst h
      obtain ⟨j, hj⟩ := hD t le_rfl
      refine ⟨i, ?_⟩
      filter_upwards [hj, hτ' right_mem_uIcc] with s ⟨hsj, hs⟩ hsi
      have hts : γ '' uIcc t s ⊆ W i := image_uIcc_subset_of γ hτ'i hsi
      refine ⟨hts, ?_⟩
      rw [hD'τ']
      by_cases hs' : t ≤ s
      · exact ite_eq_left hs'
      · rw [show D' s = D s from ite_eq_right hs', hs,
          hF j i _ (by rwa [Path.range_subpath]) (by rwa [Path.range_subpath])]
    · have htu : t ∈ uIcc τ τ' := mem_uIcc_of_ge h.le ht
      have ht' : γ '' uIcc τ t ⊆ W i := hP' t htu
      refine ⟨i, ?_⟩
      filter_upwards [hτ' htu, Ioi_mem_nhds h] with s hsi hs'
      refine ⟨image_uIcc_subset_of γ ht' hsi, ?_⟩
      have e1 : D' s = localValue F i (γ.subpath τ' s) * D τ' := ite_eq_left hs'.le
      have e2 : D' t = localValue F i (γ.subpath τ' t) * D τ' := ite_eq_left h.le
      rw [e1, e2, localValue_subpath_trans γ (image_uIcc_subset_of γ hτ'i ht')
        (image_uIcc_subset_of γ hτ'i hsi), mul_assoc]
  have hT : T = univ := IsClopen.eq_univ ⟨hclosed, hopen⟩ ⟨0, h0⟩
  obtain ⟨D, hD0, hD⟩ : (1 : I) ∈ T := hT ▸ mem_univ _
  exact ⟨D, hD0, fun t ↦ hD t le_one'⟩

variable (F) in
open scoped Classical in
/-- The value of the glued functor on a path: `D 1` for the development `D` of the path. -/
noncomputable def develop {y z : X} (γ : Path y z) : G :=
  if h : ∃ D, IsDevelopment F γ D then h.choose 1 else 1

lemma IsDevelopment.develop_eq (hF : LocalCompatible F) {y z : X} {γ : Path y z} {D : I → G}
    (hD : IsDevelopment F γ D) : develop F γ = D 1 := by
  have h : ∃ D, IsDevelopment F γ D := ⟨D, hD⟩
  rw [develop, dite_eq_left h]
  exact congrFun (h.choose_spec.eq hF hD) 1

/-- `develop` only depends on the underlying function of the path. -/
lemma develop_congr {y z y' z' : X} {p : Path y z} {p' : Path y' z'} (h : ∀ t, p t = p' t) :
    develop F p = develop F p' := by
  obtain rfl : y = y' := by rw [← p.source, ← p'.source, h]
  obtain rfl : z = z' := by rw [← p.target, ← p'.target, h]
  obtain rfl : p = p' := Path.ext (funext h)
  rfl

private lemma convexComb_convexComb (t₀ t₁ u u' s : I) :
    Icc.convexComb t₀ t₁ (Icc.convexComb u u' s) =
      Icc.convexComb (Icc.convexComb t₀ t₁ u) (Icc.convexComb t₀ t₁ u') s := by
  ext
  simp only [Icc.coe_convexComb]
  ring

/-- A development of `γ` restricts to developments of the subpaths of `γ`. -/
lemma IsDevelopment.subpath {y z : X} {γ : Path y z} {D : I → G} (hD : IsDevelopment F γ D)
    (t₀ t₁ : I) :
    IsDevelopment F (γ.subpath t₀ t₁) (fun u ↦ D (Icc.convexComb t₀ t₁ u) * (D t₀)⁻¹) := by
  refine ⟨by simp, fun u ↦ ?_⟩
  obtain ⟨i, hi⟩ := hD.2 (Icc.convexComb t₀ t₁ u)
  refine ⟨i, ?_⟩
  have hc : Continuous (Icc.convexComb t₀ t₁) := (Path.id.subpath t₀ t₁).continuous
  filter_upwards [hc.continuousAt.eventually hi] with u' ⟨h₁, h₂⟩
  have e : ∀ s, (γ.subpath t₀ t₁).subpath u u' s =
      γ.subpath (Icc.convexComb t₀ t₁ u) (Icc.convexComb t₀ t₁ u') s := fun s ↦
    congrArg γ (convexComb_convexComb t₀ t₁ u u' s)
  refine ⟨?_, ?_⟩
  · rw [← Path.range_subpath, show ⇑((γ.subpath t₀ t₁).subpath u u') = ⇑(γ.subpath
      (Icc.convexComb t₀ t₁ u) (Icc.convexComb t₀ t₁ u')) from funext e, Path.range_subpath]
    exact h₁
  · rw [h₂, localValue_congr i e, mul_assoc]

lemma IsDevelopment.develop_subpath (hF : LocalCompatible F) {y z : X} {γ : Path y z}
    {D : I → G} (hD : IsDevelopment F γ D) (t₀ t₁ : I) :
    develop F (γ.subpath t₀ t₁) = D t₁ * (D t₀)⁻¹ := by
  rw [(hD.subpath t₀ t₁).develop_eq hF, Icc.convexComb_one]

/-- On a path with values in `W i`, the glued value is the value of `F i`. -/
lemma develop_eq_localValue (hF : LocalCompatible F) {i : ι} {y z : X} (p : Path y z)
    (h : range p ⊆ W i) : develop F p = localValue F i p := by
  have hD : IsDevelopment F p (fun t ↦ localValue F i (p.subpath 0 t)) := by
    refine ⟨by simp [localValue_refl], fun t ↦ ⟨i, Eventually.of_forall fun s ↦ ⟨?_, ?_⟩⟩⟩
    · exact (image_subset_range _ _).trans h
    · exact localValue_subpath_trans p ((image_subset_range _ _).trans h)
        ((image_subset_range _ _).trans h)
  rw [hD.develop_eq hF]
  exact localValue_congr i fun s ↦ by simp [Path.subpath]

lemma develop_refl (hcov : ∀ y, ∃ i, y ∈ W i) (hF : LocalCompatible F) (y : X) :
    develop F (Path.refl y) = 1 := by
  obtain ⟨i, hi⟩ := hcov y
  rw [develop_eq_localValue hF _ (by rintro _ ⟨t, rfl⟩; exact hi), localValue_refl]

/-- The glued values are multiplicative (in the order of `SingleObj`). -/
lemma develop_trans (hWo : ∀ i, IsOpen (W i)) (hcov : ∀ y, ∃ i, y ∈ W i)
    (hF : LocalCompatible F) {y z w : X} (γ : Path y z) (δ : Path z w) :
    develop F (γ.trans δ) = develop F δ * develop F γ := by
  obtain ⟨E, hE⟩ := exists_isDevelopment hWo hcov hF (γ.trans δ)
  have h₁ : develop F γ = E half := by
    rw [develop_congr (p' := (γ.trans δ).subpath 0 half), hE.develop_subpath hF, hE.1, inv_one,
      mul_one]
    intro s
    simp only [Path.subpath, Path.coe_mk', ContinuousMap.coe_mk, Function.comp_apply,
      Path.trans_apply]
    rw [dite_eq_left]
    · congr 1
      ext
      simp [half]
      ring
    · simp [half]
      linarith [s.2.2]
  have h₂ : develop F δ = E 1 * (E half)⁻¹ := by
    rw [develop_congr (p' := (γ.trans δ).subpath half 1), hE.develop_subpath hF]
    intro s
    simp only [Path.subpath, Path.coe_mk', ContinuousMap.coe_mk, Function.comp_apply,
      Path.trans_apply]
    split_ifs with h
    · have hs : (s : ℝ) = 0 := by
        simp [half] at h
        linarith [s.2.1]
      have : s = 0 := Subtype.ext hs
      subst this
      rw [δ.source]
      refine γ.target.symm.trans ?_
      congr 1
      ext
      simp [half]
    · congr 1
      ext
      simp [half]
      ring
  rw [hE.develop_eq hF, h₁, h₂, inv_mul_cancel_right]

/-- **Homotopy invariance** of the glued values. -/
lemma develop_eq_of_homotopy (hWo : ∀ i, IsOpen (W i)) (hcov : ∀ y, ∃ i, y ∈ W i)
    (hF : LocalCompatible F) {y z : X} {γ₀ γ₁ : Path y z} (H : γ₀.Homotopy γ₁) :
    develop F γ₀ = develop F γ₁ := by
  have hlc : IsLocallyConstant (fun s ↦ develop F (H.eval s)) := by
    rw [IsLocallyConstant.iff_eventually_eq]
    intro s₀
    obtain ⟨ε, hε, hball⟩ := lebesgue_number_lemma_of_metric
      (isCompact_singleton.prod isCompact_univ : IsCompact ({s₀} ×ˢ univ : Set (I × I)))
      (c := fun i ↦ H ⁻¹' W i) (fun i ↦ (hWo i).preimage H.continuous)
      (fun p _ ↦ mem_iUnion.mpr (hcov (H p)))
    choose c hc using fun t : I ↦ hball (s₀, t) ⟨rfl, mem_univ t⟩
    -- `hmem`: points of the box around `(s₀, t)` go to `W (c t)`
    have hmem : ∀ {t s' t' : I}, s' ∈ Metric.ball s₀ ε → t' ∈ Metric.ball t ε →
        H (s', t') ∈ W (c t) := fun hs' ht' ↦
      hc _ (by rw [← ball_prod_same]; exact ⟨hs', ht'⟩)
    filter_upwards [Metric.ball_mem_nhds s₀ hε] with s hs
    obtain ⟨D₀, hD₀⟩ := exists_isDevelopment hWo hcov hF (H.eval s₀)
    let vert : ∀ t : I, Path (H (s₀, t)) (H (s, t)) := fun t ↦
      (Path.id.subpath s₀ s).map (f := fun u ↦ H (u, t)) (by fun_prop)
    have hv : ∀ t u, vert t u = H (Icc.convexComb s₀ s u, t) := fun _ _ ↦ rfl
    have hvmem : ∀ u : I, Icc.convexComb s₀ s u ∈ Metric.ball s₀ ε := fun u ↦
      uIcc_subset_ball hs (by rw [← Path.range_subpathAux]; exact ⟨u, rfl⟩)
    let D : I → G := fun t ↦ localValue F (c t) (vert t) * D₀ t
    have hD : IsDevelopment F (H.eval s) D := by
      refine ⟨?_, fun t ↦ ?_⟩
      · simp only [D, hD₀.1, mul_one]
        exact localValue_eq_one_of_forall_eq _ _ fun u ↦ by simp [hv]
      obtain ⟨j, hj⟩ := hD₀.2 t
      refine ⟨c t, ?_⟩
      filter_upwards [hj, Metric.ball_mem_nhds t hε] with t' ⟨hj₁, hj₂⟩ ht'
      have htt' : ∀ v, Icc.convexComb t t' v ∈ Metric.ball t ε := fun v ↦
        uIcc_subset_ball ht' (by rw [← Path.range_subpathAux]; exact ⟨v, rfl⟩)
      refine ⟨?_, ?_⟩
      · rintro _ ⟨v, hv', rfl⟩
        exact hmem hs (uIcc_subset_ball ht' hv')
      -- the square
      let φ : C(I × I, X) := ⟨fun q ↦ H (Icc.convexComb s₀ s q.1, Icc.convexComb t t' q.2), by
        have h₁ : Continuous (Icc.convexComb s₀ s) := (Path.id.subpath s₀ s).continuous
        have h₂ : Continuous (Icc.convexComb t t') := (Path.id.subpath t t').continuous
        fun_prop⟩
      have hφ : range φ ⊆ W (c t) := by
        rintro _ ⟨q, rfl⟩
        exact hmem (hvmem q.1) (htt' q.2)
      have hsq := localValue_square (F := F) φ hφ (vert t) (vert t') ((H.eval s₀).subpath t t')
        ((H.eval s).subpath t t') (fun u ↦ by rw [hv]; simp [φ]) (fun u ↦ by rw [hv]; simp [φ])
        (fun v ↦ by simp [φ, Path.subpath]) (fun v ↦ by simp [φ, Path.subpath])
      have hc₁ : localValue F (c t') (vert t') = localValue F (c t) (vert t') := by
        refine hF _ _ _ ?_ ?_
        · rintro _ ⟨u, rfl⟩
          exact hmem (hvmem u) (Metric.mem_ball_self hε)
        · rintro _ ⟨u, rfl⟩
          exact hmem (hvmem u) ht'
      have hc₂ : localValue F j ((H.eval s₀).subpath t t') =
          localValue F (c t) ((H.eval s₀).subpath t t') := by
        refine hF _ _ _ (by rwa [Path.range_subpath]) ?_
        rintro _ ⟨v, rfl⟩
        exact hmem (Metric.mem_ball_self hε) (htt' v)
      simp only [D]
      rw [hj₂, hc₁, ← mul_assoc, hc₂, hsq, mul_assoc]
    rw [hD.develop_eq hF, hD₀.develop_eq hF]
    simp only [D]
    rw [localValue_eq_one_of_forall_eq _ _ fun u ↦ by simp [hv], one_mul]
  have := hlc.apply_eq_of_preconnectedSpace 0 1
  simpa using this

variable (F) in
/-- The functor on `π(X)` glued from the local functors `F i`. -/
noncomputable def glue (hWo : ∀ i, IsOpen (W i)) (hcov : ∀ y, ∃ i, y ∈ W i)
    (hF : LocalCompatible F) : FundamentalGroupoid X ⥤ SingleObj G where
  obj _ := SingleObj.star G
  map {a b} p := Quotient.liftOn p (fun γ ↦ (develop F γ : G))
    (fun _ _ h ↦ develop_eq_of_homotopy hWo hcov hF h.some)
  map_id a := develop_refl hcov hF a.as
  map_comp := by
    rintro a b c ⟨γ⟩ ⟨δ⟩
    exact (develop_trans hWo hcov hF γ δ).trans (SingleObj.comp_as_mul _ _ _).symm

lemma glue_map (hWo : ∀ i, IsOpen (W i)) (hcov : ∀ y, ∃ i, y ∈ W i) (hF : LocalCompatible F)
    {y z : X} (γ : Path y z) : ((glue F hWo hcov hF).map ⌈γ⌉ : G) = develop F γ :=
  rfl

/-- If a functor `F'` on `π(X)` agrees with the local functors on paths in each `W i`, then
`t ↦ F'(γ|[0, t])` is a development of `γ`. -/
lemma isDevelopment_map_subpath (hWo : ∀ i, IsOpen (W i)) (hcov : ∀ y, ∃ i, y ∈ W i)
    (F' : FundamentalGroupoid X ⥤ SingleObj G)
    (hF' : ∀ i {y z : X} (p : Path y z), range p ⊆ W i → (F'.map ⌈p⌉ : G) = localValue F i p)
    {y z : X} (γ : Path y z) : IsDevelopment F γ (fun t ↦ (F'.map ⌈γ.subpath 0 t⌉ : G)) := by
  refine ⟨?_, fun t ↦ ?_⟩
  · simp only [Path.subpath_self, fromPath_mk_refl]
    exact F'.map_id _
  obtain ⟨i, hi⟩ := hcov (γ t)
  refine ⟨i, ?_⟩
  filter_upwards [γ.eventually_image_uIcc_subset (hWo _) hi] with s hs
  refine ⟨hs, ?_⟩
  have e : ⌈γ.subpath 0 s⌉ = ⌈γ.subpath 0 t⌉ ≫ ⌈γ.subpath t s⌉ :=
    (Path.Homotopic.Quotient.eq.mpr ⟨Path.Homotopy.subpathTransSubpath γ 0 t s⟩).symm
  rw [e, F'.map_comp, SingleObj.comp_as_mul, hF' i _ (by rwa [Path.range_subpath])]

/-- A functor on `π(X)` agreeing with the local functors on paths in each `W i` takes the glued
values. -/
lemma map_eq_develop (hWo : ∀ i, IsOpen (W i)) (hcov : ∀ y, ∃ i, y ∈ W i)
    (hF : LocalCompatible F) (F' : FundamentalGroupoid X ⥤ SingleObj G)
    (hF' : ∀ i {y z : X} (p : Path y z), range p ⊆ W i → (F'.map ⌈p⌉ : G) = localValue F i p)
    {y z : X} (γ : Path y z) : (F'.map ⌈γ⌉ : G) = develop F γ := by
  rw [(isDevelopment_map_subpath hWo hcov F' hF' γ).develop_eq hF, Path.subpath_zero_one,
    map_fromPath_cast]

end VanKampen

end Development

/-! ### Seifert–van Kampen for fundamental groupoids -/

section Groupoid

open VanKampen

variable {G : Type v} [Group G]

lemma _root_.CategoryTheory.SingleObj.eqToHom_eq_one {a b : SingleObj G} (h : a = b) :
    (eqToHom h : G) = 1 := by
  subst h
  rfl

/-- Two functors to a group `G` (a one-object category) are equal as soon as they agree on all
arrows. -/
lemma _root_.CategoryTheory.SingleObj.functor_ext_of_map_eq {C : Type*} [Category C]
    {F₁ F₂ : C ⥤ SingleObj G} (h : ∀ {a b : C} (f : a ⟶ b), (F₁.map f : G) = F₂.map f) :
    F₁ = F₂ :=
  CategoryTheory.Functor.ext (fun _ ↦ rfl) fun _ _ f ↦ by
    simp only [eqToHom_refl, SingleObj.comp_as_mul, SingleObj.id_as_one, one_mul, mul_one]
    exact h f

variable {ι : Type w} {W : ι → Set X}

/-- **Seifert–van Kampen for fundamental groupoids, path form.** Let `W i` be an open cover of `X`
and `F i : π(W i) ⥤ G` functors to a group (as a one-object category) which agree on paths in the
overlaps `W i ∩ W j`. Then there is a unique functor `π(X) ⥤ G` that agrees with `F i` on paths in
`W i`, for every `i`. -/
theorem existsUnique_functor_of_isOpen_cover (hWo : ∀ i, IsOpen (W i))
    (hcov : ∀ y, ∃ i, y ∈ W i) (F : ∀ i, FundamentalGroupoid (W i) ⥤ SingleObj G)
    (hF : ∀ i j {y z : X} (p : Path y z) (hi : range p ⊆ W i) (hj : range p ⊆ W j),
      ((F i).map ⌈p.codRestrict hi⌉ : G) = (F j).map ⌈p.codRestrict hj⌉) :
    ∃! F' : FundamentalGroupoid X ⥤ SingleObj G, ∀ i {y z : X} (p : Path y z)
      (h : range p ⊆ W i), (F'.map ⌈p⌉ : G) = (F i).map ⌈p.codRestrict h⌉ := by
  have hF₀ : LocalCompatible F := fun i j y z p hi hj ↦ by
    rw [localValue_of_subset p hi, localValue_of_subset p hj, hF i j p hi hj]
  refine ⟨glue F hWo hcov hF₀, fun i y z p h ↦ ?_, fun F' hF' ↦ ?_⟩
  · rw [glue_map, develop_eq_localValue hF₀ p h, localValue_of_subset p h]
  · have hF'' : ∀ i {y z : X} (p : Path y z), range p ⊆ W i →
        (F'.map ⌈p⌉ : G) = localValue F i p := fun i y z p h ↦ by
      rw [hF' i p h, localValue_of_subset p h]
    refine SingleObj.functor_ext_of_map_eq fun {a b} f ↦ ?_
    induction f using Path.Homotopic.Quotient.ind with | mk γ => ?_
    exact map_eq_develop hWo hcov hF₀ F' hF'' γ

/-- **Seifert–van Kampen for fundamental groupoids.** Let `W i` be an open cover of `X` and
`F i : π(W i) ⥤ G` functors to a group (as a one-object category) whose restrictions to
`π(W i ∩ W j)` agree. Then there is a unique functor `F' : π(X) ⥤ G` whose restriction to each
`π(W i)` is `F i`: the fundamental groupoid of `X` is the colimit of the `π(W i)` for functors to
groups. -/
theorem existsUnique_functor_comp_eq_of_isOpen_cover (hWo : ∀ i, IsOpen (W i))
    (hcov : ∀ y, ∃ i, y ∈ W i) (F : ∀ i, FundamentalGroupoid (W i) ⥤ SingleObj G)
    (hF : ∀ i j, map (ContinuousMap.inclusion inter_subset_left) ⋙ F i =
      map (ContinuousMap.inclusion inter_subset_right) ⋙ F j) :
    ∃! F' : FundamentalGroupoid X ⥤ SingleObj G,
      ∀ i, map ⟨Subtype.val, continuous_subtype_val⟩ ⋙ F' = F i := by
  have hF₁ : ∀ i j {y z : X} (p : Path y z) (hi : range p ⊆ W i) (hj : range p ⊆ W j),
      ((F i).map ⌈p.codRestrict hi⌉ : G) = (F j).map ⌈p.codRestrict hj⌉ := by
    intro i j y z p hi hj
    have h := Functor.congr_hom (hF i j) ⌈p.codRestrict (subset_inter hi hj)⌉
    simp only [SingleObj.comp_as_mul, SingleObj.eqToHom_eq_one, one_mul, mul_one] at h
    exact h
  have key : ∀ F' : FundamentalGroupoid X ⥤ SingleObj G,
      (∀ i, map ⟨Subtype.val, continuous_subtype_val⟩ ⋙ F' = F i) ↔
        ∀ i {y z : X} (p : Path y z) (h : range p ⊆ W i),
          (F'.map ⌈p⌉ : G) = (F i).map ⌈p.codRestrict h⌉ := by
    intro F'
    constructor
    · intro h i y z p hp
      have := Functor.congr_hom (h i) ⌈p.codRestrict hp⌉
      simp only [SingleObj.comp_as_mul, SingleObj.eqToHom_eq_one, one_mul, mul_one] at this
      exact this
    · intro h i
      refine SingleObj.functor_ext_of_map_eq fun {a b} f ↦ ?_
      induction f using Path.Homotopic.Quotient.ind with | mk γ => ?_
      exact h i (γ.map continuous_subtype_val) (Path.range_map_subtypeVal_subset γ)
  obtain ⟨F', hF', huniq⟩ := existsUnique_functor_of_isOpen_cover hWo hcov F hF₁
  exact ⟨F', (key F').mpr hF', fun F'' h ↦ huniq F'' ((key F'').mp h)⟩

end Groupoid

end FundamentalGroupoid

/-! ### Seifert–van Kampen for fundamental groups -/

namespace FundamentalGroup

open FundamentalGroupoid

variable {X : Type u} [TopologicalSpace X]

/-- The class of a path, as an arrow of the fundamental groupoid. -/
local notation "⌈" γ "⌉" => FundamentalGroupoid.fromPath (Path.Homotopic.Quotient.mk γ)

section Based

variable {ι : Type w} {W : ι → Set X} {A : Set X} {x : X}

/-- Standard paths for a cover whose pairwise intersections lie in `A`: a path from `x` to `y`
inside `A` if `y ∈ A`, inside the unique `W i` containing `y` otherwise, and constant at `x`. -/
private lemma exists_standardPath (hcov : ∀ y, ∃ i, y ∈ W i) (hAW : ∀ i, A ⊆ W i)
    (hWW : ∀ i j, i ≠ j → W i ∩ W j ⊆ A) (hWc : ∀ i, IsPathConnected (W i))
    (hAc : IsPathConnected A) (hx : x ∈ A) :
    ∃ ρ : ∀ y, Path x y, ρ x = Path.refl x ∧
      ∀ y, (y ∈ A → range (ρ y) ⊆ A) ∧ ∀ i, y ∈ W i → range (ρ y) ⊆ W i := by
  have h : ∀ y, ∃ r : Path x y, (y ∈ A → range r ⊆ A) ∧ ∀ i, y ∈ W i → range r ⊆ W i := by
    intro y
    by_cases hy : y ∈ A
    · obtain ⟨r, hr⟩ := hAc.joinedIn x hx y hy
      exact ⟨r, fun _ ↦ range_subset_iff.mpr hr, fun i _ ↦ (range_subset_iff.mpr hr).trans (hAW i)⟩
    · obtain ⟨i, hi⟩ := hcov y
      obtain ⟨r, hr⟩ := (hWc i).joinedIn x (hAW i hx) y hi
      refine ⟨r, fun h ↦ absurd h hy, fun j hj ↦ ?_⟩
      by_cases hij : i = j
      · subst hij
        exact range_subset_iff.mpr hr
      · exact absurd (hWW i j hij ⟨hi, hj⟩) hy
  choose r hr using h
  classical
  have hrefl : range (Path.refl x) ⊆ A := by
    rintro _ ⟨t, rfl⟩
    exact hx
  refine ⟨fun y ↦ if h : y = x then (Path.refl x).cast rfl h else r y, by simp, fun y ↦ ?_⟩
  by_cases h : y = x
  · subst h
    simp only [dite_true]
    exact ⟨fun _ ↦ hrefl, fun i _ ↦ hrefl.trans (hAW i)⟩
  · simp only [h, dite_false]
    exact hr y

variable {G : Type v} [Group G]

/-- The functor `π(W) ⥤ G` given by a homomorphism `f : π₁(W, x) →* G` and paths `ρ y` from `x`
to every `y ∈ W` inside `W`: a path `p` from `y` to `z` goes to `f (ρ y · p · (ρ z)⁻¹)`. -/
private noncomputable def localFunctor {U : Set X} (ρ : ∀ y, Path x y)
    (hρ : ∀ y, y ∈ U → range (ρ y) ⊆ U) (hx : x ∈ U) (f : FundamentalGroup U ⟨x, hx⟩ →* G) :
    FundamentalGroupoid U ⥤ SingleObj G where
  obj _ := SingleObj.star G
  map {a b} p := f (⌈(ρ a.as).codRestrict (hρ _ a.as.2)⌉ ≫ p ≫
    ⌈((ρ b.as).codRestrict (hρ _ b.as.2)).symm⌉)
  map_id a := by
    simp only [Category.id_comp, fromPath_mk_symm, IsIso.hom_inv_id]
    exact f.map_one
  map_comp {a b c} p q := by
    rw [SingleObj.comp_as_mul, ← map_mul, End.mul_def]
    congr 1
    simp only [Category.assoc, fromPath_mk_symm, IsIso.inv_hom_id_assoc]

private lemma localFunctor_map_eq {U : Set X} (ρ : ∀ y, Path x y)
    (hρ : ∀ y, y ∈ U → range (ρ y) ⊆ U) (hx : x ∈ U) (f : FundamentalGroup U ⟨x, hx⟩ →* G)
    {a b : FundamentalGroupoid U} (p : a ⟶ b) :
    ((localFunctor ρ hρ hx f).map p : G) = f (⌈(ρ a.as).codRestrict (hρ _ a.as.2)⌉ ≫ p ≫
      ⌈((ρ b.as).codRestrict (hρ _ b.as.2)).symm⌉) :=
  rfl

private lemma localFunctor_map {U : Set X} (ρ : ∀ y, Path x y)
    (hρ : ∀ y, y ∈ U → range (ρ y) ⊆ U) (hx : x ∈ U) (f : FundamentalGroup U ⟨x, hx⟩ →* G)
    {y z : X} (p : Path y z) (h : range p ⊆ U) :
    ((localFunctor ρ hρ hx f).map ⌈p.codRestrict h⌉ : G) =
      f ⌈(((ρ y).trans p).trans (ρ z).symm).codRestrict (by
        simp only [Path.trans_range, Path.symm_range]
        exact union_subset (union_subset (hρ y (h ⟨0, p.source⟩)) h)
          (hρ z (h ⟨1, p.target⟩)))⌉ := by
  have hy : y ∈ U := h ⟨0, p.source⟩
  have hz : z ∈ U := h ⟨1, p.target⟩
  have h₁ : range ((ρ y).trans p) ⊆ U := by
    rw [Path.trans_range]; exact union_subset (hρ y hy) h
  have h₂ : range (ρ z).symm ⊆ U := by rw [Path.symm_range]; exact hρ z hz
  rw [localFunctor_map_eq, Path.codRestrict_trans _ _ _ h₁ h₂,
    Path.codRestrict_trans _ _ h₁ (hρ y hy) h, Path.codRestrict_symm _ h₂ (hρ z hz),
    fromPath_mk_trans, fromPath_mk_trans, Category.assoc]

private lemma localFunctor_map_self {U : Set X} (ρ : ∀ y, Path x y)
    (hρ : ∀ y, y ∈ U → range (ρ y) ⊆ U) (hx : x ∈ U) (f : FundamentalGroup U ⟨x, hx⟩ →* G)
    (hρx : ρ x = Path.refl x) (a : FundamentalGroup U ⟨x, hx⟩) :
    ((localFunctor ρ hρ hx f).map a : G) = f a := by
  have e : ∀ (r : Path x x) (hr : range r ⊆ U), r = Path.refl x →
      ⌈r.codRestrict hr⌉ = 𝟙 (FundamentalGroupoid.mk (⟨x, hx⟩ : U)) := by
    rintro r hr rfl
    rfl
  rw [localFunctor_map_eq]
  dsimp only
  rw [fromPath_mk_symm, e _ _ hρx, IsIso.inv_id, Category.id_comp, Category.comp_id]

/-- **Seifert–van Kampen** (universal property). Let `X` be covered by open path-connected sets
`W i` whose pairwise intersections `W i ∩ W j` (`i ≠ j`) all lie in a path-connected set
`A ⊆ ⋂ W i` (so they equal `A`), and let `x ∈ A`. Then homomorphisms `f i : π₁(W i, x) →* G`
which agree on `π₁(A, x)` extend uniquely to a homomorphism `π₁(X, x) →* G`. With two open sets,
`A = U ∩ V`; with more, this covers wedges glued along a common neighbourhood of the base point. -/
theorem existsUnique_hom_of_isOpen_cover (hWo : ∀ i, IsOpen (W i)) (hcov : ∀ y, ∃ i, y ∈ W i)
    (hAW : ∀ i, A ⊆ W i) (hWW : ∀ i j, i ≠ j → W i ∩ W j ⊆ A)
    (hWc : ∀ i, IsPathConnected (W i)) (hAc : IsPathConnected A) (hx : x ∈ A)
    (f : ∀ i, FundamentalGroup (W i) ⟨x, hAW i hx⟩ →* G)
    (hf : ∀ i j, (f i).comp (map (ContinuousMap.inclusion (hAW i)) ⟨x, hx⟩) =
      (f j).comp (map (ContinuousMap.inclusion (hAW j)) ⟨x, hx⟩)) :
    ∃! g : FundamentalGroup X x →* G, ∀ i, g.comp (mapSubtypeVal (hAW i hx)) = f i := by
  obtain ⟨ρ, hρx, hρ⟩ := exists_standardPath hcov hAW hWW hWc hAc hx
  let F : ∀ i, FundamentalGroupoid (W i) ⥤ SingleObj G := fun i ↦
    localFunctor ρ (fun y hy ↦ (hρ y).2 i hy) (hAW i hx) (f i)
  have hF : ∀ i j {y z : X} (p : Path y z) (hi : range p ⊆ W i) (hj : range p ⊆ W j),
      ((F i).map ⌈p.codRestrict hi⌉ : G) = (F j).map ⌈p.codRestrict hj⌉ := by
    intro i j y z p hi hj
    by_cases hij : i = j
    · subst hij
      rfl
    have hpA : range p ⊆ A := subset_inter hi hj |>.trans (hWW i j hij)
    have hyA : y ∈ A := hpA ⟨0, p.source⟩
    have hzA : z ∈ A := hpA ⟨1, p.target⟩
    have hℓ : range (((ρ y).trans p).trans (ρ z).symm) ⊆ A := by
      simp only [Path.trans_range, Path.symm_range]
      exact union_subset (union_subset ((hρ y).1 hyA) hpA) ((hρ z).1 hzA)
    have := DFunLike.congr_fun (hf i j) ⌈(((ρ y).trans p).trans (ρ z).symm).codRestrict hℓ⌉
    refine (localFunctor_map ρ (fun y hy ↦ (hρ y).2 i hy) (hAW i hx) (f i) p hi).trans
      (Eq.trans ?_ (localFunctor_map ρ (fun y hy ↦ (hρ y).2 j hy) (hAW j hx) (f j) p hj).symm)
    exact this
  obtain ⟨F', hF', -⟩ := FundamentalGroupoid.existsUnique_functor_of_isOpen_cover hWo hcov F hF
  let g : FundamentalGroup X x →* G :=
    { toFun a := (F'.map a : G)
      map_one' := F'.map_id _
      map_mul' a b := by
        rw [End.mul_def, F'.map_comp, SingleObj.comp_as_mul] }
  have hgen : ⨆ i, (mapSubtypeVal (hAW i hx)).range = ⊤ := by
    refine iSup_range_map_subtypeVal_eq_top W hWo hcov _ fun i j ↦ ?_
    by_cases hij : i = j
    · subst hij
      rw [inter_self]
      exact hWc i
    · rwa [(hWW i j hij).antisymm (subset_inter (hAW i) (hAW j))]
  have hres : ∀ i (b : FundamentalGroup (W i) ⟨x, hAW i hx⟩),
      g (mapSubtypeVal (hAW i hx) b) = f i b := by
    intro i b
    induction b using Path.Homotopic.Quotient.ind with | mk ℓ => ?_
    have h₁ : g (mapSubtypeVal (hAW i hx) ⌈ℓ⌉) = (F'.map ⌈ℓ.map continuous_subtype_val⌉ : G) :=
      rfl
    rw [h₁, hF' i _ (Path.range_map_subtypeVal_subset ℓ), Path.codRestrict_map_subtypeVal]
    exact localFunctor_map_self ρ _ (hAW i hx) (f i) hρx ⌈ℓ⌉
  refine ⟨g, fun i ↦ MonoidHom.ext (hres i), fun g' hg' ↦ ?_⟩
  refine MonoidHom.ext fun a ↦ ?_
  have hle : ⨆ i, (mapSubtypeVal (hAW i hx)).range ≤ g'.eqLocus g := by
    refine iSup_le fun i ↦ ?_
    rintro _ ⟨b, rfl⟩
    exact (DFunLike.congr_fun (hg' i) b).trans (hres i b).symm
  rw [hgen] at hle
  exact hle (Subgroup.mem_top a)

/-- The inclusions `π₁(A, x) → π₁(W i, x)`, the data of the amalgamated product. -/
noncomputable abbrev mapInclusion (hAW : ∀ i, A ⊆ W i) (hx : x ∈ A) (i : ι) :
    FundamentalGroup A ⟨x, hx⟩ →* FundamentalGroup (W i) ⟨x, hAW i hx⟩ :=
  map (ContinuousMap.inclusion (hAW i)) ⟨x, hx⟩

lemma mapSubtypeVal_comp_mapInclusion (hAW : ∀ i, A ⊆ W i) (hx : x ∈ A) (i : ι) :
    (mapSubtypeVal (hAW i hx)).comp (mapInclusion hAW hx i) = mapSubtypeVal hx := by
  ext a
  induction a using Path.Homotopic.Quotient.ind with | mk ℓ => ?_
  rfl

/-- The homomorphism `π₁(X, x) → *_{π₁(A, x)} π₁(W i, x)` given by the universal property. -/
private noncomputable def pushoutIInv (hWo : ∀ i, IsOpen (W i)) (hcov : ∀ y, ∃ i, y ∈ W i)
    (hAW : ∀ i, A ⊆ W i) (hWW : ∀ i j, i ≠ j → W i ∩ W j ⊆ A)
    (hWc : ∀ i, IsPathConnected (W i)) (hAc : IsPathConnected A) (hx : x ∈ A) :
    FundamentalGroup X x →* Monoid.PushoutI (mapInclusion hAW hx) :=
  (existsUnique_hom_of_isOpen_cover hWo hcov hAW hWW hWc hAc hx
    (fun i ↦ Monoid.PushoutI.of (φ := mapInclusion hAW hx) i)
    (fun i j ↦ (Monoid.PushoutI.of_comp_eq_base i).trans
      (Monoid.PushoutI.of_comp_eq_base j).symm)).exists.choose

private lemma pushoutIInv_comp (hWo : ∀ i, IsOpen (W i)) (hcov : ∀ y, ∃ i, y ∈ W i)
    (hAW : ∀ i, A ⊆ W i) (hWW : ∀ i j, i ≠ j → W i ∩ W j ⊆ A)
    (hWc : ∀ i, IsPathConnected (W i)) (hAc : IsPathConnected A) (hx : x ∈ A) (i : ι) :
    (pushoutIInv hWo hcov hAW hWW hWc hAc hx).comp (mapSubtypeVal (hAW i hx)) =
      Monoid.PushoutI.of (φ := mapInclusion hAW hx) i :=
  (existsUnique_hom_of_isOpen_cover hWo hcov hAW hWW hWc hAc hx
    (fun i ↦ Monoid.PushoutI.of (φ := mapInclusion hAW hx) i)
    (fun i j ↦ (Monoid.PushoutI.of_comp_eq_base i).trans
      (Monoid.PushoutI.of_comp_eq_base j).symm)).exists.choose_spec i

/-- **Seifert–van Kampen.** Let `X` be covered by open path-connected sets `W i` whose pairwise
intersections `W i ∩ W j` (`i ≠ j`) all lie in a path-connected set `A ⊆ ⋂ W i`, and let `x ∈ A`.
Then `π₁(X, x)` is the amalgamated product of the groups `π₁(W i, x)` over `π₁(A, x)`. The
isomorphism is induced by the inclusions `W i → X` (`FundamentalGroup.pushoutIMulEquiv_of`). -/
noncomputable def pushoutIMulEquiv (hWo : ∀ i, IsOpen (W i)) (hcov : ∀ y, ∃ i, y ∈ W i)
    (hAW : ∀ i, A ⊆ W i) (hWW : ∀ i j, i ≠ j → W i ∩ W j ⊆ A)
    (hWc : ∀ i, IsPathConnected (W i)) (hAc : IsPathConnected A) (hx : x ∈ A) :
    Monoid.PushoutI (mapInclusion hAW hx) ≃* FundamentalGroup X x :=
  MonoidHom.toMulEquiv
    (Monoid.PushoutI.lift (fun i ↦ mapSubtypeVal (hAW i hx)) (mapSubtypeVal hx)
      (mapSubtypeVal_comp_mapInclusion hAW hx))
    (pushoutIInv hWo hcov hAW hWW hWc hAc hx)
    (by
      have : Nonempty ι := ⟨(hcov x).choose⟩
      refine Monoid.PushoutI.hom_ext_nonempty fun i ↦ MonoidHom.ext fun g ↦ ?_
      have h := DFunLike.congr_fun (pushoutIInv_comp hWo hcov hAW hWW hWc hAc hx i) g
      simp only [MonoidHom.comp_apply, Monoid.PushoutI.lift_of, MonoidHom.id_apply] at h ⊢
      exact h)
    (by
      refine (existsUnique_hom_of_isOpen_cover hWo hcov hAW hWW hWc hAc hx
        (fun i ↦ mapSubtypeVal (hAW i hx))
        (fun i j ↦ (mapSubtypeVal_comp_mapInclusion hAW hx i).trans
          (mapSubtypeVal_comp_mapInclusion hAW hx j).symm)).unique (fun i ↦ ?_)
        (fun i ↦ MonoidHom.id_comp _)
      rw [MonoidHom.comp_assoc, pushoutIInv_comp]
      ext g
      exact Monoid.PushoutI.lift_of (φ := mapInclusion hAW hx) (i := i)
        (fun i ↦ mapSubtypeVal (hAW i hx)) (mapSubtypeVal hx)
        (mapSubtypeVal_comp_mapInclusion hAW hx) g)

@[simp]
lemma pushoutIMulEquiv_of (hWo : ∀ i, IsOpen (W i)) (hcov : ∀ y, ∃ i, y ∈ W i)
    (hAW : ∀ i, A ⊆ W i) (hWW : ∀ i j, i ≠ j → W i ∩ W j ⊆ A)
    (hWc : ∀ i, IsPathConnected (W i)) (hAc : IsPathConnected A) (hx : x ∈ A) (i : ι)
    (g : FundamentalGroup (W i) ⟨x, hAW i hx⟩) :
    pushoutIMulEquiv hWo hcov hAW hWW hWc hAc hx (Monoid.PushoutI.of i g) =
      mapSubtypeVal (hAW i hx) g :=
  Monoid.PushoutI.lift_of (φ := mapInclusion hAW hx) (i := i)
    (fun i ↦ mapSubtypeVal (hAW i hx)) (mapSubtypeVal hx)
    (mapSubtypeVal_comp_mapInclusion hAW hx) g

end Based

/-- **Seifert–van Kampen for two open sets** (universal property). Let `X = U ∪ V` with `U`, `V`
open and `U`, `V`, `U ∩ V` path-connected, and `x ∈ U ∩ V`. Then homomorphisms
`fU : π₁(U, x) →* G` and `fV : π₁(V, x) →* G` which agree on `π₁(U ∩ V, x)` extend uniquely to a
homomorphism `π₁(X, x) →* G`: `π₁(X, x) = π₁(U, x) *_{π₁(U ∩ V, x)} π₁(V, x)`. -/
theorem existsUnique_hom_of_union {G : Type v} [Group G] {U V : Set X} (hU : IsOpen U)
    (hV : IsOpen V) (hUV : U ∪ V = univ) (hUc : IsPathConnected U) (hVc : IsPathConnected V)
    (hUVc : IsPathConnected (U ∩ V)) {x : X} (hxU : x ∈ U) (hxV : x ∈ V)
    (fU : FundamentalGroup U ⟨x, hxU⟩ →* G) (fV : FundamentalGroup V ⟨x, hxV⟩ →* G)
    (h : fU.comp (map (ContinuousMap.inclusion inter_subset_left) ⟨x, hxU, hxV⟩) =
      fV.comp (map (ContinuousMap.inclusion inter_subset_right) ⟨x, hxU, hxV⟩)) :
    ∃! g : FundamentalGroup X x →* G,
      g.comp (mapSubtypeVal hxU) = fU ∧ g.comp (mapSubtypeVal hxV) = fV := by
  let W : Bool → Set X := fun b ↦ cond b U V
  have hAW : ∀ b, U ∩ V ⊆ W b := fun b ↦ by
    cases b
    exacts [inter_subset_right, inter_subset_left]
  have hx : x ∈ U ∩ V := ⟨hxU, hxV⟩
  let f : ∀ b, FundamentalGroup (W b) ⟨x, hAW b hx⟩ →* G := fun b ↦
    Bool.rec (motive := fun b ↦ FundamentalGroup (W b) ⟨x, hAW b hx⟩ →* G) fV fU b
  obtain ⟨g, hg, huniq⟩ := existsUnique_hom_of_isOpen_cover (W := W) (A := U ∩ V)
    (fun b ↦ by cases b <;> assumption)
    (fun y ↦ by
      rcases (hUV ▸ mem_univ y : y ∈ U ∪ V) with hy | hy
      exacts [⟨true, hy⟩, ⟨false, hy⟩])
    hAW
    (fun i j hij ↦ by
      cases i <;> cases j
      · exact absurd rfl hij
      · exact (inter_comm V U).subset
      · exact subset_rfl
      · exact absurd rfl hij)
    (fun b ↦ by cases b <;> assumption) hUVc hx f
    (fun i j ↦ by
      cases i <;> cases j
      exacts [rfl, h.symm, h, rfl])
  refine ⟨g, ⟨hg true, hg false⟩, fun g' hg' ↦ huniq g' fun b ↦ ?_⟩
  cases b
  exacts [hg'.2, hg'.1]

end FundamentalGroup
