/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import Mathlib.Algebra.Polynomial.Laurent
import Mathlib.GroupTheory.SpecificGroups.Alternating
import SGA.SGA1.ExposeI.StandardEtale
import SGA.SGA1.ExposeXIII.AffineLinePGroups

/-!
# XIII.2.13: `S₃` and `A₄` are quotients of `π₁(𝔸¹)` in characteristics `2` and `3`

Abhyankar's conjecture for the affine line (XIII.2.13, `AbhyankarAffineLineStatement`) predicts
that every finite group generated by its Sylow `p`-subgroups is the Galois group of a connected
étale covering of `𝔸¹_k`, `k` algebraically closed of characteristic `p`. Besides the `p`-groups
(`SGA.SGA1.ExposeXIII.AffineLinePGroups`), we realize the first groups that are not `p`-groups.

Abhyankar's covering `y ↦ yᵖ + y⁻¹` from `𝔾_m` to `𝔸¹` is `k[T][Y]/(Yᵖ⁺¹ - TY + 1)`
(`AbhyankarCover.cover`): it is finite étale of degree `p + 1` because `Y f' - f = -1`
(`AbhyankarCover.poly_separable`), and connected because it embeds in `k[Y, Y⁻¹]`
(`AbhyankarCover.injective_toLaurent`). Its monodromy group (`AbhyankarCover.monodromy`, the
image of `π₁` in the permutations of a fibre) is transitive on `p + 1` points, and it is generated
by its Sylow `p`-subgroups by the necessary condition of XIII.2.13
(`AbhyankarCover.sylowSup_monodromy_eq_top`). For `p = 2` this forces `S₃`, for `p = 3` it
forces `A₄` (`AbhyankarCover.eq_top_of_card_eq_three`,
`AbhyankarCover.eq_alternatingGroup_of_card_eq_four`), giving
`exists_surjective_of_mulEquiv_perm_fin_three` and
`exists_surjective_of_mulEquiv_alternatingGroup_fin_four`. Both are `PSL₂(𝔽_p)`; that the
monodromy group is `PSL₂(𝔽_p)` for every `p` (Abhyankar) is not formalized.

By Serre's theorem (`SerrePKernel.affineLinePExtension`), every extension of `S₃` (`p = 2`) or
`A₄` (`p = 3`) by a `p`-group is then a quotient of `π₁(𝔸¹_k)` as well.
-/
universe u

namespace SGA.SGA1.ExposeXIII

open Polynomial

namespace AbhyankarCover

variable (k : Type u) [Field k] (p : ℕ)

/-- Abhyankar's polynomial `Yᵖ⁺¹ - T Y + 1` over `k[T]`. -/
noncomputable def poly : k[X][X] := X ^ (p + 1) - C X * X + 1

lemma poly_monic [hp : Fact p.Prime] : (poly k p).Monic := by
  unfold poly
  monicity!
  exact hp.out.ne_zero

lemma poly_natDegree [hp : Fact p.Prime] : (poly k p).natDegree = p + 1 := by
  unfold poly
  compute_degree!
  simp [hp.out.ne_zero]

/-- `Y f' - f = -1` in characteristic `p`, so `f` is separable. -/
lemma poly_separable [CharP k p] : (poly k p).Separable := by
  refine ⟨1, -X, ?_⟩
  have hp0 : ((p : ℕ) : k[X]) = 0 := by
    rw [← map_natCast (algebraMap k k[X]), CharP.cast_eq_zero, map_zero]
  unfold poly
  rw [derivative_add, derivative_sub, derivative_X_pow, derivative_mul, derivative_C,
    derivative_X, derivative_one, Nat.cast_add, hp0, Nat.add_sub_cancel, zero_add,
    Nat.cast_one, C_1]
  ring


lemma root_mul_eq_one :
    AdjoinRoot.root (poly k p) * (AdjoinRoot.of _ X - AdjoinRoot.root (poly k p) ^ p) = 1 := by
  have h : Polynomial.eval₂ (AdjoinRoot.of (poly k p)) (AdjoinRoot.root (poly k p))
      (X ^ (p + 1) - C X * X + 1) = 0 := AdjoinRoot.eval₂_root (poly k p)
  rw [eval₂_add, eval₂_sub, eval₂_mul, eval₂_X_pow, eval₂_C, eval₂_X, eval₂_one] at h
  linear_combination -h

/-- The root `Y` of Abhyankar's polynomial is a unit, with inverse `T - Yᵖ`. -/
noncomputable def rootUnit : (AdjoinRoot (poly k p))ˣ :=
  ⟨AdjoinRoot.root _, AdjoinRoot.of _ X - AdjoinRoot.root _ ^ p, root_mul_eq_one k p,
    by rw [mul_comm, root_mul_eq_one]⟩

open LaurentPolynomial in
/-- `k[T][Y]/(Yᵖ⁺¹ - TY + 1) → k[Y, Y⁻¹]`, `T ↦ Yᵖ + Y⁻¹`, `Y ↦ Y`. -/
noncomputable def toLaurent : AdjoinRoot (poly k p) →+* k[T;T⁻¹] :=
  AdjoinRoot.lift (Polynomial.eval₂RingHom LaurentPolynomial.C (T p + T (-1))) (T 1) (by
    have h₁ : (T 1 : k[T;T⁻¹]) ^ (p + 1) = T p * T 1 := by
      rw [T_pow, ← T_add]
      congr 1
      push_cast
      ring
    have h₂ : (T (-1) : k[T;T⁻¹]) * T 1 = 1 := by
      rw [← T_add, neg_add_cancel, T_zero]
    unfold poly
    rw [Polynomial.eval₂_add, Polynomial.eval₂_sub, Polynomial.eval₂_mul,
      Polynomial.eval₂_X_pow, Polynomial.eval₂_C, Polynomial.eval₂_X, Polynomial.eval₂_one,
      coe_eval₂RingHom, Polynomial.eval₂_X, h₁]
    linear_combination -h₂)

open LaurentPolynomial in
lemma injective_toLaurent : Function.Injective (toLaurent k p) := by
  let ψ : k[T;T⁻¹] →+* AdjoinRoot (poly k p) :=
    LaurentPolynomial.eval₂ (algebraMap k _) (rootUnit k p)
  have hψT : ψ (T p + T (-1)) = AdjoinRoot.of _ X := by
    rw [map_add, show (T (-1) : k[T;T⁻¹]) = T (-((1 : ℕ) : ℤ)) by simp,
      LaurentPolynomial.eval₂_T_n, LaurentPolynomial.eval₂_T_neg_n, pow_one]
    change AdjoinRoot.root _ ^ p + (AdjoinRoot.of _ X - AdjoinRoot.root _ ^ p) = _
    ring
  have hleft : ψ.comp (toLaurent k p) = RingHom.id _ := by
    refine AdjoinRoot.ringHom_ext (Polynomial.ringHom_ext (fun a ↦ ?_) ?_) ?_
    · simp only [RingHom.comp_apply, toLaurent, AdjoinRoot.lift_of, coe_eval₂RingHom,
        Polynomial.eval₂_C, RingHom.id_apply]
      rw [LaurentPolynomial.eval₂_C]
      rfl
    · simp only [RingHom.comp_apply, toLaurent, AdjoinRoot.lift_of, coe_eval₂RingHom,
        Polynomial.eval₂_X, RingHom.id_apply]
      exact hψT
    · simp only [RingHom.comp_apply, toLaurent, AdjoinRoot.lift_root, RingHom.id_apply]
      rw [show (T 1 : k[T;T⁻¹]) = T ((1 : ℕ) : ℤ) by simp, LaurentPolynomial.eval₂_T_n, pow_one]
      rfl
  exact Function.LeftInverse.injective (g := ψ) fun y ↦ RingHom.congr_fun hleft y

instance isDomain [Fact p.Prime] : IsDomain (AdjoinRoot (poly k p)) :=
  (injective_toLaurent k p).isDomain (toLaurent k p)

/-! ### Group theory and monodromy (helpers, namespaced to avoid clashes) -/

section GroupTheory

open Equiv

variable {p : ℕ} [hp : Fact p.Prime]

/-- A nontrivial finite group generated by its Sylow `p`-subgroups has order divisible by
`p`. -/
lemma dvd_card_of_sylowSup_eq_top {M : Type*} [Group M] [Finite M] [Nontrivial M]
    (h : sylowSup p M = ⊤) : p ∣ Nat.card M := by
  by_contra hnd
  have hbot : ∀ P : Sylow p M, (P : Subgroup M) = ⊥ := fun P ↦ by
    rw [← Subgroup.card_eq_one, P.card_eq_multiplicity,
      Nat.factorization_eq_zero_of_not_dvd hnd, pow_zero]
  have : sylowSup p M = ⊥ := by
    unfold sylowSup
    simp [hbot]
  exact bot_ne_top (this.symm.trans h)

omit hp in
/-- A group of permutations generated by its Sylow `p`-subgroups, `p` odd, consists of even
permutations. -/
lemma le_alternatingGroup_of_sylowSup_eq_top {α : Type*} [Fintype α] [DecidableEq α]
    (M : Subgroup (Perm α)) (hodd : Odd p) (h : sylowSup p M = ⊤) :
    M ≤ alternatingGroup α := by
  have hle : sylowSup p M ≤ (Perm.sign.comp M.subtype).ker := by
    refine iSup_le fun P x hx ↦ ?_
    obtain ⟨n, hn⟩ := P.isPGroup' ⟨x, hx⟩
    have hx' : x ^ p ^ n = 1 := congrArg Subtype.val hn
    rw [MonoidHom.mem_ker, MonoidHom.comp_apply]
    have hs : Perm.sign (M.subtype x) ^ p ^ n = 1 := by
      rw [← map_pow, ← map_pow, hx', map_one, map_one]
    rcases Int.units_eq_one_or (Perm.sign (M.subtype x)) with h1 | h1
    · exact h1
    · rw [h1, (hodd.pow).neg_one_pow] at hs
      exact absurd hs (by decide)
  intro g hg
  have := hle (h ▸ Subgroup.mem_top (⟨g, hg⟩ : M))
  exact Equiv.Perm.mem_alternatingGroup.mpr this

/-- If a group of permutations of `α` is transitive, `|α|` divides its order. -/
lemma card_dvd_of_isPretransitive {α : Type*} [Finite α] [Nonempty α] (M : Subgroup (Perm α))
    [MulAction.IsPretransitive M α] : Nat.card α ∣ Nat.card M := by
  obtain ⟨a⟩ := ‹Nonempty α›
  rw [← MulAction.index_stabilizer_of_transitive M a]
  exact Subgroup.index_dvd_card _

lemma nontrivial_of_isPretransitive {α : Type*} {a b : α} (hab : a ≠ b) (M : Subgroup (Perm α))
    [MulAction.IsPretransitive M α] : Nontrivial M := by
  obtain ⟨m, hm⟩ := MulAction.exists_smul_eq M a b
  refine ⟨⟨m, 1, fun h ↦ hab ?_⟩⟩
  rw [h, one_smul] at hm
  exact hm

/-- XIII.2.13 for `p = 2`, group theory: a transitive group of permutations of three letters
generated by its Sylow `2`-subgroups is the full symmetric group. -/
lemma eq_top_of_card_eq_three {α : Type*} [Finite α] (hα : Nat.card α = 3)
    (M : Subgroup (Perm α)) [MulAction.IsPretransitive M α] (h : sylowSup 2 M = ⊤) :
    M = ⊤ := by
  have : Nontrivial α := Finite.one_lt_card_iff_nontrivial.mp (by omega)
  obtain ⟨a, b, hab⟩ := exists_pair_ne α
  have := nontrivial_of_isPretransitive hab M
  have h3 : 3 ∣ Nat.card M := hα ▸ card_dvd_of_isPretransitive M
  have h2 : 2 ∣ Nat.card M := dvd_card_of_sylowSup_eq_top h
  have hle : Nat.card M ∣ 6 := by
    have := Subgroup.card_subgroup_dvd_card M
    rwa [Nat.card_perm, hα] at this
  refine Subgroup.eq_top_of_card_eq M ?_
  rw [Nat.card_perm, hα]
  have h6 : 6 ∣ Nat.card M := Nat.Coprime.mul_dvd_of_dvd_of_dvd (by norm_num) h2 h3
  exact Nat.dvd_antisymm hle h6

/-- XIII.2.13 for `p = 3`, group theory: a transitive group of permutations of four letters
generated by its Sylow `3`-subgroups is the alternating group. -/
lemma eq_alternatingGroup_of_card_eq_four {α : Type*} [Fintype α] [DecidableEq α]
    (hα : Nat.card α = 4) (M : Subgroup (Perm α)) [MulAction.IsPretransitive M α]
    (h : sylowSup 3 M = ⊤) : M = alternatingGroup α := by
  have : Nontrivial α := Finite.one_lt_card_iff_nontrivial.mp (by omega)
  obtain ⟨a, b, hab⟩ := exists_pair_ne α
  have := nontrivial_of_isPretransitive hab M
  have h4 : 4 ∣ Nat.card M := hα ▸ card_dvd_of_isPretransitive M
  have h3 : 3 ∣ Nat.card M := dvd_card_of_sylowSup_eq_top h
  have hle := le_alternatingGroup_of_sylowSup_eq_top M (by decide) h
  have hA : Nat.card (alternatingGroup α) = 12 := by
    rw [nat_card_alternatingGroup, hα]
    rfl
  refine Subgroup.eq_of_le_of_card_ge hle ?_
  rw [hA]
  have h12 : 12 ∣ Nat.card M := Nat.Coprime.mul_dvd_of_dvd_of_dvd (by norm_num) h3 h4
  exact Nat.le_of_dvd Nat.card_pos h12

end GroupTheory

section Monodromy

open CategoryTheory PreGaloisCategory CommAlgCat
open scoped FintypeCatDiscrete

variable {R : Type u} [CommRing R] [ConnectedSpace (PrimeSpectrum R)] (Ω : Type u) [Field Ω]
  [IsSepClosed Ω] [Algebra R Ω]

/-- The monodromy representation of `π₁(Spec R)` on the fibre of an étale covering `X`; its image
is the Galois group of the Galois closure of `X`. -/
noncomputable abbrev monodromy (X : (FiniteEtale.{u} R)ᵒᵖ) :
    Aut (ExposeV.fiberFunctor R Ω) →* Equiv.Perm ((ExposeV.fiberFunctor R Ω).obj X) :=
  MulAction.toPermHom _ _

omit [ConnectedSpace (PrimeSpectrum R)] [IsSepClosed Ω] in
lemma isOpen_setOf_monodromy_eq (X : (FiniteEtale.{u} R)ᵒᵖ)
    (g : Equiv.Perm ((ExposeV.fiberFunctor R Ω).obj X)) :
    IsOpen {σ | monodromy Ω X σ = g} := by
  have : {σ | monodromy Ω X σ = g} =
      ⋂ a, (fun σ : Aut (ExposeV.fiberFunctor R Ω) ↦ σ • a) ⁻¹' {g a} := by
    ext σ
    simp only [Set.mem_iInter, Set.mem_preimage, Set.mem_singleton_iff]
    exact Equiv.ext_iff
  rw [this]
  exact isOpen_iInter_of_finite fun a ↦
    (continuous_id.smul continuous_const).isOpen_preimage _ (isOpen_discrete _)

omit [ConnectedSpace (PrimeSpectrum R)] [IsSepClosed Ω] in
/-- `π₁(Spec R)` maps continuously onto every group isomorphic to the monodromy group of a
covering. -/
lemma exists_surjective_of_monodromy (X : (FiniteEtale.{u} R)ᵒᵖ) {G : Type*} [Group G]
    [TopologicalSpace G] [DiscreteTopology G] (e : (monodromy Ω X).range ≃* G) :
    ∃ φ : ContinuousMonoidHom (Aut (ExposeV.fiberFunctor R Ω)) G, Function.Surjective φ := by
  refine ⟨⟨e.toMonoidHom.comp (monodromy Ω X).rangeRestrict, ?_⟩,
    e.surjective.comp (MonoidHom.rangeRestrict_surjective _)⟩
  rw [continuous_discrete_rng]
  intro g
  convert isOpen_setOf_monodromy_eq Ω X (e.symm g : Equiv.Perm _) using 1
  ext σ
  change e ((monodromy Ω X).rangeRestrict σ) = g ↔ monodromy Ω X σ = (e.symm g : Equiv.Perm _)
  rw [← e.eq_symm_apply, Subtype.ext_iff]
  rfl

/-- The monodromy group of a connected covering acts transitively on the fibre. -/
instance isPretransitive_monodromy (X : (FiniteEtale.{u} R)ᵒᵖ) [IsConnected X] :
    MulAction.IsPretransitive (monodromy Ω X).range ((ExposeV.fiberFunctor R Ω).obj X) :=
  ⟨fun a b ↦ by
    obtain ⟨σ, hσ⟩ := MulAction.exists_smul_eq (Aut (ExposeV.fiberFunctor R Ω)) a b
    exact ⟨⟨monodromy Ω X σ, σ, rfl⟩, hσ⟩⟩

/-- XIII.2.13, necessity, for monodromy groups: over `𝔸¹_k`, `k` algebraically closed of
characteristic `p`, the monodromy group of every covering is generated by its Sylow
`p`-subgroups. -/
lemma sylowSup_monodromy_eq_top (k : Type u) [Field k] [IsAlgClosed k] (p : ℕ) [Fact p.Prime]
    [CharP k p] [Algebra k[X] Ω] (X : (FiniteEtale.{u} k[X])ᵒᵖ) :
    sylowSup p (monodromy Ω X).range = ⊤ := by
  let : TopologicalSpace (monodromy Ω X).range := ⊥
  have : DiscreteTopology (monodromy Ω X).range := ⟨rfl⟩
  obtain ⟨φ, hφ⟩ := exists_surjective_of_monodromy Ω X (MulEquiv.refl _)
  exact sylowSup_eq_top_of_surjective (proLKernel_aut_fiberFunctor_eq_top k Ω p) _ φ hφ

end Monodromy

end AbhyankarCover

section Examples

open CategoryTheory PreGaloisCategory CommAlgCat AlgebraicGeometry AffineLinePGroups

namespace AbhyankarCover

variable (k : Type u) [Field k] (p : ℕ) [hp : Fact p.Prime] [CharP k p]

/-- Abhyankar's covering `𝔾_m → 𝔸¹`, `y ↦ yᵖ + y⁻¹`, i.e. `k[T][Y]/(Yᵖ⁺¹ - TY + 1)`, as a
connected finite étale covering of `𝔸¹_k` of degree `p + 1`. -/
noncomputable def cover : (FiniteEtale.{u} k[X])ᵒᵖ :=
  have := ExposeI.etale_adjoinRoot_of_separable (poly_monic k p) (poly_separable k p)
  have : Module.Finite k[X] (AdjoinRoot (poly k p)) :=
    (AdjoinRoot.powerBasis' (poly_monic k p)).finite
  Opposite.op (FiniteEtale.of k[X] (AdjoinRoot (poly k p)))

instance isConnected_cover : IsConnected (cover k p) :=
  (ExposeV.isConnected_op_iff_connectedSpace k[X] _).mpr
    (inferInstanceAs (ConnectedSpace (PrimeSpectrum (AdjoinRoot (poly k p)))))

lemma card_fiber_cover (Ω : Type u) [Field Ω] [IsSepClosed Ω] [Algebra k[X] Ω] :
    Nat.card ((ExposeV.fiberFunctor k[X] Ω).obj (cover k p)) = p + 1 := by
  have : Module.Free k[X] (AdjoinRoot (poly k p)) :=
    .of_basis (AdjoinRoot.powerBasis' (poly_monic k p)).basis
  rw [ExposeV.card_fiber_eq_rankAtStalk k[X] Ω _ (Classical.arbitrary _)]
  change Module.rankAtStalk (R := k[X]) (AdjoinRoot (poly k p)) _ = _
  rw [Module.rankAtStalk_eq_finrank_of_free,
    (AdjoinRoot.powerBasis' (poly_monic k p)).finrank, AdjoinRoot.powerBasis'_dim,
    poly_natDegree]
  rfl

end AbhyankarCover

open AbhyankarCover

variable (k : Type u) [Field k] [IsAlgClosed k] (Ω : Type u) [Field Ω] [IsSepClosed Ω]
  (x : Spec (.of Ω) ⟶ Spec (.of k[X]))

/-- XIII.2.13 (Abhyankar's conjecture for `𝔸¹`), the case `G ≅ S₃` in characteristic `2`:
`S₃ = PSL₂(𝔽₂)` is the Galois group of a connected étale covering of `𝔸¹_k`, namely the Galois
closure of Abhyankar's covering `y ↦ y² + y⁻¹` of degree `3`. -/
theorem exists_surjective_of_mulEquiv_perm_fin_three [CharP k 2] (G : Type*) [Group G]
    [TopologicalSpace G] [DiscreteTopology G] (e : G ≃* Equiv.Perm (Fin 3)) :
    ∃ φ : ContinuousMonoidHom (FundamentalGroup x) G, Function.Surjective φ := by
  classical
  let := ExposeV.algebraOfPoint (CommRingCat.of k[X]) Ω x
  refine exists_surjective_of_continuousMulEquiv (fundamentalGroupSpecContinuousMulEquiv k[X] Ω x)
    ?_
  have hcard := card_fiber_cover k 2 Ω
  have : Finite ((ExposeV.fiberFunctor k[X] Ω).obj (cover k 2)) :=
    Nat.finite_of_card_ne_zero (by rw [hcard]; norm_num)
  have := Fintype.ofFinite ((ExposeV.fiberFunctor k[X] Ω).obj (cover k 2))
  have hM := eq_top_of_card_eq_three hcard (monodromy Ω (cover k 2)).range
    (sylowSup_monodromy_eq_top Ω k 2 (cover k 2))
  let eα := Finite.equivFinOfCardEq hcard
  exact exists_surjective_of_monodromy Ω (cover k 2)
    ((MulEquiv.subgroupCongr hM).trans (Subgroup.topEquiv.trans (eα.permCongrHom.trans e.symm)))

/-- XIII.2.13 (Abhyankar's conjecture for `𝔸¹`), the case `G ≅ A₄` in characteristic `3`:
`A₄ = PSL₂(𝔽₃)` is the Galois group of a connected étale covering of `𝔸¹_k`, namely the Galois
closure of Abhyankar's covering `y ↦ y³ + y⁻¹` of degree `4`. -/
theorem exists_surjective_of_mulEquiv_alternatingGroup_fin_four [CharP k 3] (G : Type*)
    [Group G] [TopologicalSpace G] [DiscreteTopology G]
    (e : G ≃* alternatingGroup (Fin 4)) :
    ∃ φ : ContinuousMonoidHom (FundamentalGroup x) G, Function.Surjective φ := by
  classical
  let := ExposeV.algebraOfPoint (CommRingCat.of k[X]) Ω x
  refine exists_surjective_of_continuousMulEquiv (fundamentalGroupSpecContinuousMulEquiv k[X] Ω x)
    ?_
  have hcard := card_fiber_cover k 3 Ω
  have : Finite ((ExposeV.fiberFunctor k[X] Ω).obj (cover k 3)) :=
    Nat.finite_of_card_ne_zero (by rw [hcard]; norm_num)
  have := Fintype.ofFinite ((ExposeV.fiberFunctor k[X] Ω).obj (cover k 3))
  have hM := eq_alternatingGroup_of_card_eq_four hcard (monodromy Ω (cover k 3)).range
    (sylowSup_monodromy_eq_top Ω k 3 (cover k 3))
  let eα := Finite.equivFinOfCardEq hcard
  exact exists_surjective_of_monodromy Ω (cover k 3)
    ((MulEquiv.subgroupCongr hM).trans ((Equiv.altCongrHom eα).trans e.symm))

end Examples

end SGA.SGA1.ExposeXIII
