/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import Mathlib.AlgebraicGeometry.Morphisms.Flat
import Mathlib.RingTheory.AdicCompletion.Algebra
import Mathlib.RingTheory.DiscreteValuationRing.Basic
import Mathlib.RingTheory.MvPowerSeries.Basic
import Mathlib.RingTheory.PowerSeries.Basic
import SGA.SGA1.ExposeXIII.AffineLinePGroups

/-!
# XIII.2.13: Raynaud's proof of Abhyankar's conjecture for the affine line, by cases

Remark XIII.2.13 recalls Raynaud's theorem (Invent. Math. 116 (1994), 425–462): over an
algebraically closed field `k` of characteristic `p`, a finite group is a continuous quotient of
`π₁(𝔸¹_k)` iff it is generated by its Sylow `p`-subgroups (`AbhyankarAffineLineStatement`).
Raynaud argues by induction on `|G|`, with three cases, recorded here as statements:

* `AffineLinePExtensionStatement`: Serre's theorem for `p`-group kernels (if `G/N` is realized
  and `N` is a normal `p`-subgroup, `G` is realized). It is proved in
  `SGA.SGA1.ExposeXIII.SerrePKernel` (`SerrePKernel.affineLinePExtension`), so XIII.2.13 reduces
  to the two cases below (`SerrePKernel.abhyankarAffineLine_of_patching_of_caseB`).
* `AffineLinePatchingStatement` (case A): `G` is realized when it is generated by realized
  subgroups `Q` with `Q ∩ S` a Sylow subgroup of `Q`, for a fixed Sylow `p`-subgroup `S`.
* `AffineLineCaseBStatement` (case B): `G` without non-trivial normal `p`-subgroups and with
  `G(S) ≠ G` (`raynaudSubgroup`). Raynaud's proof uses XIII.2.12 in characteristic `0` (hence
  Riemann's existence theorem), the semistable reduction theorem
  (`SemistableReductionStatement`, stated here) and an analysis of the tails of the stable
  reduction of a `G`-covering of `ℙ¹` in mixed characteristic.

`abhyankarAffineLine_of_cases` proves that the three statements imply
`AbhyankarAffineLineStatement` (Raynaud's induction).
-/
universe u

namespace SGA.SGA1.ExposeXIII

open CategoryTheory AlgebraicGeometry Polynomial

section GroupTheory

variable (p : ℕ) [hp : Fact p.Prime] {G : Type*} [Group G] [Finite G]

/-- Raynaud's subgroup `G(S)` of a finite group `G`, for a Sylow `p`-subgroup `S`: the subgroup
generated by the proper subgroups `Q` of `G` which are generated by their Sylow `p`-subgroups and
such that `Q ∩ S` is a Sylow `p`-subgroup of `Q` (its order is the `p`-part of `|Q|`). -/
def raynaudSubgroup (S : Sylow p G) : Subgroup G :=
  ⨆ (Q : Subgroup G) (_ : Q ≠ ⊤ ∧ sylowSup p Q = ⊤ ∧
    Nat.card ↥(Q ⊓ (S : Subgroup G)) = p ^ (Nat.card Q).factorization p), Q

/-- A quotient of a group generated by its Sylow `p`-subgroups is generated by its Sylow
`p`-subgroups. -/
lemma sylowSup_eq_top_of_surjective_hom {H : Type*} [Group H] (f : G →* H)
    (hf : Function.Surjective f) (hG : sylowSup p G = ⊤) : sylowSup p H = ⊤ := by
  have : Finite H := Finite.of_surjective f hf
  rw [eq_top_iff, ← Subgroup.map_top_of_surjective f hf, ← hG, sylowSup, Subgroup.map_iSup]
  exact iSup_le fun P ↦ le_iSup (fun Q : Sylow p H ↦ (Q : Subgroup H)) (P.mapSurjective hf)

end GroupTheory

section Statements

variable (p : ℕ) [Fact p.Prime]

/-- Serre's theorem (C. R. Acad. Sci. Paris 311 (1990), 341–346), the case of a `p`-group
kernel, for the affine line (the first step of Raynaud's proof of XIII.2.13):
over an algebraically closed field `k` of characteristic `p`, if `H` is a continuous quotient of
`π₁(𝔸¹_k)` and `G → H` is onto with kernel a `p`-group, then `G` is a continuous quotient of
`π₁(𝔸¹_k)`. Proved in `SGA.SGA1.ExposeXIII.SerrePKernel` (`SerrePKernel.affineLinePExtension`). -/
def AffineLinePExtensionStatement : Prop :=
  ∀ (k : Type u) [Field k] [IsAlgClosed k] [CharP k p] (Ω : Type u) [Field Ω] [IsSepClosed Ω]
    (x : Spec (.of Ω) ⟶ Spec (.of k[X])) (G H : Type u) [Group G] [Finite G]
    [TopologicalSpace G] [DiscreteTopology G] [Group H] [Finite H] [TopologicalSpace H]
    [DiscreteTopology H] (π : G →* H), Function.Surjective π → IsPGroup p π.ker →
    (∃ ψ : ContinuousMonoidHom (FundamentalGroup x) H, Function.Surjective ψ) →
    ∃ φ : ContinuousMonoidHom (FundamentalGroup x) G, Function.Surjective φ

/-- Raynaud's patching step ("case A" of the proof of XIII.2.13; Raynaud, Invent. Math. 116
(1994), §2, by rigid patching; Harbater's formal patching gives the same; statement only): let
`k` be algebraically closed of characteristic `p`, `G` a finite group, `S` a Sylow `p`-subgroup
of `G` and `𝒬` a set of subgroups generating `G` such that for each `Q ∈ 𝒬`, `Q ∩ S` is a Sylow
`p`-subgroup of `Q` and `Q` is a continuous quotient of `π₁(𝔸¹_k)`. Then `G` is a continuous
quotient of `π₁(𝔸¹_k)`. (The condition on `Q ∩ S` lets one choose the `Q`-coverings with
inertia at `∞` inside `S` and patch them at `∞`.) -/
def AffineLinePatchingStatement : Prop :=
  ∀ (k : Type u) [Field k] [IsAlgClosed k] [CharP k p] (Ω : Type u) [Field Ω] [IsSepClosed Ω]
    (x : Spec (.of Ω) ⟶ Spec (.of k[X])) (G : Type u) [Group G] [Finite G]
    [TopologicalSpace G] [DiscreteTopology G] (S : Sylow p G) (𝒬 : Set (Subgroup G)),
    sSup 𝒬 = ⊤ →
    (∀ Q ∈ 𝒬, Nat.card ↥(Q ⊓ (S : Subgroup G)) = p ^ (Nat.card Q).factorization p) →
    (∀ Q ∈ 𝒬, ∃ ψ : ContinuousMonoidHom (FundamentalGroup x) Q, Function.Surjective ψ) →
    ∃ φ : ContinuousMonoidHom (FundamentalGroup x) G, Function.Surjective φ

/-- The remaining case of Raynaud's proof of XIII.2.13 ("case B", statement only): over an
algebraically closed field `k` of characteristic `p`, a finite group `G` generated by its Sylow
`p`-subgroups, without non-trivial normal `p`-subgroups, and with `G(S) ≠ G`
(`raynaudSubgroup`) for a Sylow `p`-subgroup `S`, is a continuous quotient of `π₁(𝔸¹_k)`.

Raynaud proves it by degeneration from characteristic `0`: a `G`-covering of `ℙ¹` over the
algebraic closure of `Frac W(k)`, branched at points with inertia `p`-groups, exists by XIII.2.12
in characteristic `0` (`TameCurveFundamentalGroupStatement`, from Riemann's existence theorem
XII.5.1, `CurveRiemannExistenceStatement`); one takes its stable reduction
(`SemistableReductionStatement`) and shows, using `O_p(G) = 1` and `G(S) ≠ G`, that a tail of the
special fibre gives a `G`-covering of `𝔸¹_k`. The last step is not stated here. -/
def AffineLineCaseBStatement : Prop :=
  ∀ (k : Type u) [Field k] [IsAlgClosed k] [CharP k p] (Ω : Type u) [Field Ω] [IsSepClosed Ω]
    (x : Spec (.of Ω) ⟶ Spec (.of k[X])) (G : Type u) [Group G] [Finite G]
    [TopologicalSpace G] [DiscreteTopology G] (S : Sylow p G), sylowSup p G = ⊤ →
    (∀ N : Subgroup G, N.Normal → IsPGroup p N → N = ⊥) → raynaudSubgroup p S ≠ ⊤ →
    ∃ φ : ContinuousMonoidHom (FundamentalGroup x) G, Function.Surjective φ

end Statements

section SemistableReduction

open CategoryTheory.Limits

/-- A scheme `Y` (a curve over an algebraically closed field `k`) is a semistable curve if the
completed local ring at each closed point is `k⟦t⟧` (a smooth point) or `k⟦u, v⟧/(uv)` (an
ordinary double point).

Two deviations from the usual definition, both harmless here. The isomorphisms are ring
isomorphisms (`≃+*`), not `k`-algebra isomorphisms; for a perfect `k` (here `k` is algebraically
closed) and a complete local `k`-algebra with residue field `k`, Cohen's structure theorem lets one
replace such a ring isomorphism by a `k`-algebra isomorphism. And the definition does not itself
require `Y` to be a proper curve over `k` (finite type, dimension `1`): in
`SemistableReductionStatement` this comes from the context (`Y` is the special fibre of a proper
flat family of curves). -/
def IsSemistableCurve (k : Type u) [Field k] (Y : Scheme.{u}) : Prop :=
  ∀ y : Y, IsClosed ({y} : Set Y) →
    Nonempty (AdicCompletion (IsLocalRing.maximalIdeal (Y.presheaf.stalk y))
      (Y.presheaf.stalk y) ≃+* PowerSeries k) ∨
    Nonempty (AdicCompletion (IsLocalRing.maximalIdeal (Y.presheaf.stalk y))
      (Y.presheaf.stalk y) ≃+*
        (MvPowerSeries (Fin 2) k ⧸
          Ideal.span {(MvPowerSeries.X 0 * MvPowerSeries.X 1 : MvPowerSeries (Fin 2) k)}))

/-- The semistable reduction theorem for curves (statement only; used in case B of Raynaud's
proof of XIII.2.13, see `AffineLineCaseBStatement`): let `R` be a complete discrete valuation
ring with algebraically closed residue field and fraction field `K`, and `X` a smooth proper
geometrically connected curve over `K`. There are a finite extension `R ⊂ R'` of discrete
valuation rings, with fraction field `K'` finite over `K`, and a proper flat `R'`-scheme `𝒳` whose
generic fibre is `X ⊗_K K'` (over `K'`) and whose special fibre is a semistable curve
(`IsSemistableCurve`).

The statement is for all genera. Deligne–Mumford (Publ. IHÉS 36 (1969), Cor. 2.7, from the
stable reduction theorem 2.4) treat genus `≥ 2`; genus `0` and `1` hold by other arguments
(genus `0`: after a finite extension `X` has a rational point, so `X ≅ ℙ¹` has the smooth model
`ℙ¹_{R'}`; genus `1`: potentially good or multiplicative reduction of elliptic curves, via the
Tate curve). -/
def SemistableReductionStatement : Prop :=
  ∀ (R : Type u) [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]
    [IsAdicComplete (IsLocalRing.maximalIdeal R) R]
    [IsAlgClosed (IsLocalRing.ResidueField R)] (K : Type u) [Field K] [Algebra R K]
    [IsFractionRing R K] (X : Scheme.{u}) (f : X ⟶ Spec (.of K)) [IsProper f]
    [SmoothOfRelativeDimension 1 f] [GeometricallyConnected f],
    ∃ (R' : Type u) (_ : CommRing R') (_ : IsDomain R') (_ : IsDiscreteValuationRing R')
      (_ : Algebra R R') (_ : Module.Finite R R') (_ : FaithfulSMul R R')
      (K' : Type u) (_ : Field K') (_ : Algebra R' K') (_ : IsFractionRing R' K')
      (_ : Algebra K K') (_ : FiniteDimensional K K') (_ : Algebra R K')
      (_ : IsScalarTower R K K') (_ : IsScalarTower R R' K')
      (𝒳 : Scheme.{u}) (g : 𝒳 ⟶ Spec (.of R')) (_ : IsProper g) (_ : Flat g),
      (∃ e : pullback g (Spec.map (CommRingCat.ofHom (algebraMap R' K'))) ≅
          pullback f (Spec.map (CommRingCat.ofHom (algebraMap K K'))),
        e.hom ≫ pullback.snd _ _ = pullback.snd _ _) ∧
      IsSemistableCurve (IsLocalRing.ResidueField R')
        (pullback g (Spec.map (CommRingCat.ofHom (IsLocalRing.residue R'))))

end SemistableReduction

section Reduction

variable (p : ℕ) [Fact p.Prime]

/-- XIII.2.13 (Abhyankar's conjecture for the affine line, Raynaud's theorem), reduced to the
three cases of Raynaud's proof: Serre's theorem for `p`-group kernels
(`AffineLinePExtensionStatement`), patching (`AffineLinePatchingStatement`) and the degeneration
case (`AffineLineCaseBStatement`). The proof is Raynaud's induction on `|G|`: if `G` has a
non-trivial normal `p`-subgroup `N`, realize `G/N` and apply Serre's theorem; if `G(S) = G`, the
proper quasi-`p` subgroups `Q` with `Q ∩ S` Sylow in `Q` are realized and generate `G`; otherwise
`G` is in case B. -/
theorem abhyankarAffineLine_of_cases (h₁ : AffineLinePExtensionStatement.{u} p)
    (h₂ : AffineLinePatchingStatement.{u} p) (h₃ : AffineLineCaseBStatement.{u} p) :
    AbhyankarAffineLineStatement.{u} p := by
  intro k _ _ _ Ω _ _ x G _ _ _ _
  refine ⟨fun ⟨φ, hφ⟩ ↦ sylowSup_eq_top_of_affineLine p k Ω x G φ hφ, fun hG ↦ ?_⟩
  suffices h : ∀ n (G : Type u) [Group G] [Finite G] [TopologicalSpace G] [DiscreteTopology G],
      Nat.card G = n → sylowSup p G = ⊤ →
      ∃ φ : ContinuousMonoidHom (FundamentalGroup x) G, Function.Surjective φ from
    h _ G rfl hG
  intro n
  induction n using Nat.strong_induction_on with
  | _ n ih =>
  intro G _ _ _ _ hn hG
  by_cases hN : ∃ N : Subgroup G, N.Normal ∧ IsPGroup p N ∧ N ≠ ⊥
  · -- Serre's theorem
    obtain ⟨N, hNn, hNp, hNbot⟩ := hN
    let : TopologicalSpace (G ⧸ N) := ⊥
    have : DiscreteTopology (G ⧸ N) := ⟨rfl⟩
    have hlt : Nat.card (G ⧸ N) < n := by
      rw [← hn, Subgroup.card_eq_card_quotient_mul_card_subgroup N]
      have : 0 < Nat.card (G ⧸ N) := Nat.card_pos
      have : 1 < Nat.card N := by
        have := (Subgroup.nontrivial_iff_ne_bot N).mpr hNbot
        exact Finite.one_lt_card
      nlinarith
    have hQ := ih _ hlt (G ⧸ N) rfl
      (sylowSup_eq_top_of_surjective_hom p (QuotientGroup.mk' N) (QuotientGroup.mk'_surjective N)
        hG)
    exact h₁ k Ω x G (G ⧸ N) (QuotientGroup.mk' N) (QuotientGroup.mk'_surjective N)
      (by rw [QuotientGroup.ker_mk']; exact hNp) hQ
  push Not at hN
  obtain ⟨S⟩ := Sylow.nonempty (p := p) (G := G)
  by_cases hS : raynaudSubgroup p S = ⊤
  · -- patching
    let 𝒬 : Set (Subgroup G) := {Q | Q ≠ ⊤ ∧ sylowSup p Q = ⊤ ∧
      Nat.card ↥(Q ⊓ (S : Subgroup G)) = p ^ (Nat.card Q).factorization p}
    refine h₂ k Ω x G S 𝒬 ?_ (fun Q hQ ↦ hQ.2.2) (fun Q hQ ↦ ?_)
    · rw [sSup_eq_iSup]
      exact hS
    · have hlt : Nat.card Q < n := by
        have := Subgroup.card_lt_of_lt (lt_top_iff_ne_top.mpr hQ.1)
        rwa [Subgroup.card_top, hn] at this
      exact ih _ hlt Q rfl hQ.2.1
  · -- case B
    exact h₃ k Ω x G S hG (fun N hNn hNp ↦ hN N hNn hNp) hS

end Reduction

end SGA.SGA1.ExposeXIII
