/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.Foundations.Patching.ProjectiveLine
import SGA.SGA1.ExposeXIII.AbhyankarAffineLine
import SGA.SGA1.ExposeXIII.AffineLinePGroupsPrincipal

/-!
# XIII.2.13, case A: decomposition of Raynaud's patching step

Case A of Raynaud's proof of XIII.2.13 (`AffineLinePatchingStatement`) is proved here from four
statements, following Harbater–Stevenson (*Patching and thickening problems*, J. Algebra 212
(1999), 272–304, Theorem 6 and its corollary):

* `AbhyankarLemmaAtInfinityStatement` (Abhyankar's lemma at `∞`): a subgroup `H` of `G` which is
  realized over `𝔸¹_k` is realized with inertia at `∞` in any given Sylow `p`-subgroup of `H` (pull
  back along `x ↦ xᵐ`, `p ∤ m`, to kill the tame part of the inertia; the pullback stays
  connected because `H` is generated by its Sylow `p`-subgroups);
* `NodalPatchingStatement` (Harbater–Stevenson's Theorem 6, by formal patching on a nodal curve
  over `k⟦t⟧`): if `G₁` and `G₂` are realized over `𝔸¹_k` with inertia at `∞` in a `p`-subgroup
  `P ≤ G₁ ⊔ G₂`, then `G₁ ⊔ G₂` is realized over `𝔸¹_K`, with inertia at `∞` in `P`, for some
  algebraically closed extension `K` of `k` (an algebraic closure of `k((t))`);
* `AffineLineBaseChangeStatement`: realizations with inertia in `P` survive the base change to an
  algebraically closed extension;
* `AffineLineSpecializationStatement`: a group realized over `𝔸¹_K`, `K ⊇ k` algebraically closed,
  is realized over `𝔸¹_k` (spreading out and specialization to a `k`-point of the parameter space
  where the fibre stays connected, EGA IV 9.7.7).

The realizations are continuous homomorphisms `φ : π₁(𝔸¹_k, a) → G` with image `H`
(`IsRealizedWithInertiaAtInfty`), with `π₁` the automorphism group of the fibre functor of finite
étale `k[X]`-algebras (V.7). The inertia at `∞` is read through the local homomorphisms
`π₁(Spec k((y)), a') → π₁(𝔸¹_k, a)` induced by `k[X] → k((y))`, `X ↦ y⁻¹`
(`PatchingProjectiveLine.invX`), composed with any class of paths `a' ⇝ a`: the condition is that
their images are conjugate by an element of `H` into `P`.

The assembly (`affineLinePatching_of_statements`) is an induction over the finitely many subgroups
of the generating family: with a Sylow `p`-subgroup `S` of `G`, each `Q` is realized with inertia
in `Q ∩ S` (Abhyankar), and the subgroups `H` generated by finite subfamilies are realized, over
larger and larger algebraically closed fields, with inertia in `H ∩ S`; finally specialization
brings `G` back to `k`.

The node lemma, the main ingredient of `NodalPatchingStatement`, is
`AffineLinePGroups.exists_continuousMonoidHom_conj_nodePunctured`
(`SGA.SGA1.ExposeXIII.AbhyankarAffineLineNode`).
-/

universe u

open CategoryTheory PreGaloisCategory Polynomial AlgebraicGeometry

namespace SGA.SGA1.ExposeXIII

open AffineLinePGroups

section Realization

variable (k : Type u) [Field k] {G : Type u} [Group G] [TopologicalSpace G]

/-- The subgroup `H` of `G` is realized over `𝔸¹_k` with inertia at `∞` in `P`: for some geometric
point `k[X] → Ω` there is a continuous homomorphism `φ : π₁(𝔸¹_k, Ω) → G` with image `H` (a
connected `H`-Galois étale covering of `𝔸¹_k`) such that, for every geometric point
`k((y)) → Ω'` of the punctured disc at `∞` (`X ↦ y⁻¹`) and every class of paths `γ` from its image
in `𝔸¹_k` to `Ω`, the image of the local homomorphism `π₁(k((y)), Ω') → π₁(𝔸¹_k, Ω) → G` is
conjugate by an element of `H` into `P`. With `P = ⊤` this only says that `H` is a quotient of
`π₁(𝔸¹_k)`. -/
def IsRealizedWithInertiaAtInfty (H P : Subgroup G) : Prop :=
  ∃ (Ω : Type u) (_ : Field Ω) (_ : IsSepClosed Ω) (_ : Algebra k[X] Ω)
    (φ : ContinuousMonoidHom (Aut (ExposeV.fiberFunctor k[X] Ω)) G),
    φ.toMonoidHom.range = H ∧
      ∀ (Ω' : Type u) [Field Ω'] [IsSepClosed Ω'] [Algebra (LaurentSeries k) Ω']
        [Algebra k[X] Ω']
        (h : algebraMap k[X] Ω' =
          (algebraMap (LaurentSeries k) Ω').comp (PatchingProjectiveLine.invX k))
        (γ : 𝟭 _ ⋙ ExposeV.fiberFunctor k[X] Ω' ≅ ExposeV.fiberFunctor k[X] Ω),
        ∃ g ∈ H, ∀ σ, g * φ (ExposeV.autMap (𝟭 _) γ
          (fundamentalGroupMapOfRingHom (PatchingProjectiveLine.invX k) Ω' h σ)) * g⁻¹ ∈ P

variable {k}

lemma IsRealizedWithInertiaAtInfty.mono {H P P' : Subgroup G}
    (h : IsRealizedWithInertiaAtInfty k H P) (hP : P ≤ P') :
    IsRealizedWithInertiaAtInfty k H P' := by
  obtain ⟨Ω, _, _, _, φ, hφ, hloc⟩ := h
  refine ⟨Ω, inferInstance, inferInstance, inferInstance, φ, hφ, fun Ω' _ _ _ _ h γ ↦ ?_⟩
  obtain ⟨g, hg, hg'⟩ := hloc Ω' h γ
  exact ⟨g, hg, fun σ ↦ hP (hg' σ)⟩

variable (k) in
/-- The trivial subgroup is realized, with inertia in any `P`. -/
lemma isRealizedWithInertiaAtInfty_bot (P : Subgroup G) :
    IsRealizedWithInertiaAtInfty k ⊥ P := by
  let : Algebra k[X] (AlgebraicClosure k) :=
    (Polynomial.aeval (0 : AlgebraicClosure k)).toRingHom.toAlgebra
  refine ⟨AlgebraicClosure k, inferInstance, inferInstance, inferInstance, 1, ?_,
    fun Ω' _ _ _ _ h γ ↦ ⟨1, Subgroup.one_mem _, fun σ ↦ ?_⟩⟩
  · ext g
    simp [eq_comm]
  · simp

/-- A continuous surjection from the scheme-theoretic `π₁(𝔸¹_k, x)` onto a subgroup `Q` realizes
`Q`. -/
lemma isRealizedWithInertiaAtInfty_top_of_surjective {Ω : Type u} [Field Ω]
    [IsSepClosed Ω] (x : Spec (.of Ω) ⟶ Spec (.of k[X])) (Q : Subgroup G)
    (ψ : ContinuousMonoidHom (FundamentalGroup x) Q) (hψ : Function.Surjective ψ) :
    IsRealizedWithInertiaAtInfty k Q ⊤ := by
  let := ExposeV.algebraOfPoint (CommRingCat.of k[X]) Ω x
  let e := fundamentalGroupSpecContinuousMulEquiv k[X] Ω x
  let φ : ContinuousMonoidHom (Aut (ExposeV.fiberFunctor k[X] Ω)) G :=
    (⟨Q.subtype, continuous_subtype_val⟩ : ContinuousMonoidHom Q G).comp
      (ψ.comp (ContinuousMonoidHom.toContinuousMonoidHom e))
  refine ⟨Ω, inferInstance, inferInstance, inferInstance, φ, ?_,
    fun Ω' _ _ _ _ h γ ↦ ⟨1, Q.one_mem, fun σ ↦ Subgroup.mem_top _⟩⟩
  ext g
  constructor
  · rintro ⟨σ, rfl⟩
    exact (ψ (e σ)).2
  · intro hg
    obtain ⟨τ, hτ⟩ := hψ ⟨g, hg⟩
    refine ⟨e.symm τ, ?_⟩
    change ((ψ (e (e.symm τ)) : Q) : G) = g
    rw [e.apply_symm_apply, hτ]

/-- A realization of the whole group gives a continuous surjection from the scheme-theoretic
`π₁(𝔸¹_k, x)` at every geometric point `x` (V.7: the fibre functors at two geometric points are
isomorphic). -/
lemma exists_surjective_of_isRealizedWithInertiaAtInfty_top
    (h : IsRealizedWithInertiaAtInfty k (⊤ : Subgroup G) ⊤) (Ω : Type u) [Field Ω]
    [IsSepClosed Ω] (x : Spec (.of Ω) ⟶ Spec (.of k[X])) :
    ∃ φ : ContinuousMonoidHom (FundamentalGroup x) G, Function.Surjective φ := by
  obtain ⟨Ω₀, _, _, _, φ₀, hφ₀, -⟩ := h
  let := ExposeV.algebraOfPoint (CommRingCat.of k[X]) Ω x
  obtain ⟨γ⟩ := ExposeV.nonempty_iso_of_fiberFunctor (ExposeV.fiberFunctor k[X] Ω₀)
    (ExposeV.fiberFunctor k[X] Ω)
  refine exists_surjective_of_continuousMulEquiv
    ((ExposeV.conjAutContinuousMulEquiv γ).trans (fundamentalGroupSpecContinuousMulEquiv k[X] Ω x))
    ⟨φ₀, fun g ↦ ?_⟩
  have : g ∈ φ₀.toMonoidHom.range := hφ₀ ▸ Subgroup.mem_top g
  obtain ⟨σ, hσ⟩ := this
  exact ⟨σ, hσ⟩

end Realization

section Statements

variable (p : ℕ)

/-- Abhyankar's lemma at `∞` (statement only), as used in Raynaud's case A: over an algebraically
closed field `k` of characteristic `p`, a subgroup `H` of `G` realized over `𝔸¹_k` is realized with
inertia at `∞` in any given Sylow `p`-subgroup `S` of `H`. The proof pulls the covering back along
`𝔸¹ → 𝔸¹`, `x ↦ xᵐ` (`m` the order of the tame quotient of the inertia, prime to `p`): the
pullback is connected since `H` is generated by its Sylow `p`-subgroups, and its inertia at `∞`
is the wild part of the original one, a `p`-group (structure of inertia groups,
`Ideal.exists_isPGroup_isCyclic_quotient_inertia`; Kummer theory over `k((y))`). -/
def AbhyankarLemmaAtInfinityStatement : Prop :=
  ∀ (k : Type u) [Field k] [IsAlgClosed k] [CharP k p] (G : Type u) [Group G] [Finite G]
    [TopologicalSpace G] [DiscreteTopology G] (H S : Subgroup G), IsPGroup p S → S ≤ H →
    Nat.card S = p ^ (Nat.card H).factorization p →
    IsRealizedWithInertiaAtInfty k H ⊤ → IsRealizedWithInertiaAtInfty k H S

/-- Harbater–Stevenson's Theorem 6 (*Patching and thickening problems*, J. Algebra 212 (1999)),
over an algebraically closed extension (statement only): over an algebraically closed field `k` of
characteristic `p`, if `G₁` and `G₂` are realized over `𝔸¹_k` with inertia at `∞` in a
`p`-subgroup `P ≤ G₁ ⊔ G₂`, then `G₁ ⊔ G₂` is realized over `𝔸¹_K` with inertia at `∞` in `P`, for
some algebraically closed field `K` containing `k`. Harbater–Stevenson patch the two coverings on
the two components of a nodal curve over `k⟦t⟧`, with a `P`-covering of the punctured node
(`AffineLinePGroups.exists_continuousMonoidHom_conj_nodePunctured`) in between; this gives the
covering over `k((t))`, and `K` is an algebraic closure of `k((t))`.

This is a weak form of Harbater–Stevenson's theorem: the inertia at `∞` is only required to be
contained in a conjugate of `P`, while Harbater–Stevenson also get a totally ramified point over
`∞` with inertia exactly `P` (not needed for case A). -/
def NodalPatchingStatement : Prop :=
  ∀ (k : Type u) [Field k] [IsAlgClosed k] [CharP k p] (G : Type u) [Group G] [Finite G]
    [TopologicalSpace G] [DiscreteTopology G] (G₁ G₂ P : Subgroup G), IsPGroup p P →
    P ≤ G₁ ⊔ G₂ → IsRealizedWithInertiaAtInfty k G₁ P → IsRealizedWithInertiaAtInfty k G₂ P →
    ∃ (K : Type u) (_ : Field K) (_ : IsAlgClosed K) (_ : Algebra k K),
      IsRealizedWithInertiaAtInfty K (G₁ ⊔ G₂) P

/-- Base change of realizations (statement only): if `k ⊆ K` are algebraically closed fields, a
realization over `𝔸¹_k` with inertia at `∞` in `P` gives one over `𝔸¹_K` with inertia at `∞` in
`P` (a connected covering of `𝔸¹_k` stays connected over `K`, and the local homomorphisms at `∞`
are compatible with `k((y)) → K((y))`). -/
def AffineLineBaseChangeStatement : Prop :=
  ∀ (k K : Type u) [Field k] [IsAlgClosed k] [Field K] [IsAlgClosed K] [Algebra k K]
    (G : Type u) [Group G] [Finite G] [TopologicalSpace G] [DiscreteTopology G]
    (H P : Subgroup G), IsRealizedWithInertiaAtInfty k H P → IsRealizedWithInertiaAtInfty K H P

/-- Specialization (statement only): if `k ⊆ K` are algebraically closed fields, a finite group
realized over `𝔸¹_K` is realized over `𝔸¹_k`. The covering is defined over a finitely generated
`k`-subalgebra `A ⊆ K` (EGA IV 8); its fibres over the `k`-points of a dense open subset of
`Spec A` are connected Galois coverings with the same group (EGA IV 9.7.7, or Chevalley's theorem
applied to the sections of the quotients by proper subgroups). -/
def AffineLineSpecializationStatement : Prop :=
  ∀ (k K : Type u) [Field k] [IsAlgClosed k] [Field K] [IsAlgClosed K] [Algebra k K]
    (G : Type u) [Group G] [Finite G] [TopologicalSpace G] [DiscreteTopology G] (H : Subgroup G),
    IsRealizedWithInertiaAtInfty K H ⊤ → IsRealizedWithInertiaAtInfty k H ⊤

/-- **Case A of Raynaud's proof of XIII.2.13, reduced to four statements**:
`AffineLinePatchingStatement` follows from Abhyankar's lemma at `∞`
(`AbhyankarLemmaAtInfinityStatement`), Harbater–Stevenson's nodal patching
(`NodalPatchingStatement`), base change (`AffineLineBaseChangeStatement`) and specialization
(`AffineLineSpecializationStatement`). With a Sylow `p`-subgroup `S`, each `Q ∈ 𝒬` is realized with
inertia in `Q ∩ S`; the subgroups generated by finite subfamilies `T ⊆ 𝒬` are realized with
inertia in their intersection with `S`, over algebraically closed extensions of `k`, by induction
on `T`; and the realization of `G = ⊔ 𝒬` is specialized back to `k`. -/
theorem affineLinePatching_of_statements (h₁ : AbhyankarLemmaAtInfinityStatement.{u} p)
    (h₂ : NodalPatchingStatement.{u} p) (h₃ : AffineLineBaseChangeStatement.{u})
    (h₄ : AffineLineSpecializationStatement.{u}) : AffineLinePatchingStatement.{u} p := by
  intro k _ _ _ Ω _ _ x G _ _ _ _ S 𝒬 hsup hsyl hreal
  classical
  have hQ : ∀ Q ∈ 𝒬, IsRealizedWithInertiaAtInfty k Q (Q ⊓ (S : Subgroup G)) := by
    intro Q hQ
    obtain ⟨ψ, hψ⟩ := hreal Q hQ
    exact h₁ k G Q _ (S.isPGroup'.to_le inf_le_right) inf_le_left (hsyl Q hQ)
      (isRealizedWithInertiaAtInfty_top_of_surjective x Q ψ hψ)
  have key : ∀ T : Finset (Subgroup G), (↑T : Set (Subgroup G)) ⊆ 𝒬 →
      ∃ (K : Type u) (_ : Field K) (_ : IsAlgClosed K) (_ : Algebra k K),
        IsRealizedWithInertiaAtInfty K (T.sup id) (T.sup id ⊓ (S : Subgroup G)) := by
    intro T
    induction T using Finset.induction_on with
    | empty =>
      intro _
      exact ⟨k, inferInstance, inferInstance, inferInstance,
        isRealizedWithInertiaAtInfty_bot k _⟩
    | insert Q T hQT ih =>
      intro hT
      obtain ⟨K, _, _, _, hK⟩ := ih ((Finset.coe_subset.mpr (Finset.subset_insert Q T)).trans hT)
      have : CharP K p := charP_of_injective_algebraMap (algebraMap k K).injective p
      have hQ' := h₃ k K G Q _ (hQ Q (hT (Finset.mem_insert_self Q T)))
      have hP : IsPGroup p ↥((T.sup id ⊔ Q) ⊓ (S : Subgroup G)) :=
        S.isPGroup'.to_le inf_le_right
      obtain ⟨K', _, _, _, hK'⟩ := h₂ K G (T.sup id) Q ((T.sup id ⊔ Q) ⊓ S) hP inf_le_left
        (hK.mono (inf_le_inf_right _ le_sup_left)) (hQ'.mono (inf_le_inf_right _ le_sup_right))
      let : Algebra k K' := ((algebraMap K K').comp (algebraMap k K)).toAlgebra
      refine ⟨K', inferInstance, inferInstance, this, ?_⟩
      rw [Finset.sup_insert, id, sup_comm]
      exact hK'
  have h𝒬 : 𝒬.Finite := Set.toFinite 𝒬
  obtain ⟨K, _, _, _, hK⟩ := key h𝒬.toFinset (by simp)
  have htop : h𝒬.toFinset.sup id = ⊤ := by
    rw [Finset.sup_id_eq_sSup, Set.Finite.coe_toFinset, hsup]
  rw [htop] at hK
  exact exists_surjective_of_isRealizedWithInertiaAtInfty_top (h₄ k K G ⊤ (hK.mono le_top)) Ω x

end Statements

end SGA.SGA1.ExposeXIII
