/-
Copyright (c) 2026 SGAenglishpluslean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SGAenglishpluslean contributors
-/
import Mathlib.Algebra.CharP.Lemmas
import Mathlib.Algebra.Polynomial.Degree.Lemmas
import Mathlib.FieldTheory.Perfect
import Mathlib.GroupTheory.Sylow

/-!
# SGA 1, Exposé XIII, Remark 2.13 (M. Raynaud, 2003): the affine line in characteristic `p`

Remark XIII.2.13 describes `Hom_cont(π₁(𝔸¹_k), ℤ/pℤ) ≅ k[T]/℘(k[T])`, `℘(a) = aᵖ - a`, by
Artin–Schreier theory, and observes that the polynomials `∑ aᵢ Tⁱ` with `aᵢ = 0` for `p ∣ i`
map bijectively onto `k[T]/℘(k[T])` when `k` is algebraically closed. Hence this group is
infinite (so `π₁(𝔸¹)` is not topologically of finite type), and for an extension `k → k'` of
algebraically closed fields the map `k[T]/℘ → k'[T]/℘` is not surjective (so
`π₁(𝔸¹_{k'}) → π₁(𝔸¹_k)` is not injective). The remark then states Abhyankar's conjecture
(Raynaud, Harbater): a finite group `G` is a Galois group of a connected étale covering of
`𝔸¹_k` iff `G^{(p')} = 1`, i.e. iff `G` is generated by its Sylow `p`-subgroups; every finite
simple group of order divisible by `p` qualifies.

We prove the Artin–Schreier computations on `k[T]` (for `k` perfect with `℘` surjective on
`k`, e.g. algebraically closed) and the group theory of `G^{(p')}`. The identification with
`π₁` (Artin–Schreier theory, XI.6.9) and Abhyankar's conjecture are not formalized.
-/

namespace SGA.SGA1.ExposeXIII

open Polynomial

section ArtinSchreier

variable (k : Type*) [Field k] (p : ℕ) [hp : Fact p.Prime] [CharP k p]

/-- The Artin–Schreier map `℘(f) = fᵖ - f` on `k[T]`, an additive homomorphism. -/
noncomputable def artinSchreierPoly : k[X] →+ k[X] :=
  (frobenius k[X] p).toAddMonoidHom - AddMonoidHom.id k[X]

variable {k p}

lemma artinSchreierPoly_apply (f : k[X]) : artinSchreierPoly k p f = f ^ p - f :=
  rfl

variable (k p)

/-- The polynomials `∑ aᵢ Tⁱ` with `aᵢ = 0` whenever `p ∣ i` (the set `E` of XIII.2.13). -/
def primeToPPolys : AddSubgroup k[X] where
  carrier := {f | ∀ i, p ∣ i → f.coeff i = 0}
  add_mem' hf hg i hi := by rw [coeff_add, hf i hi, hg i hi, add_zero]
  zero_mem' _ _ := coeff_zero _
  neg_mem' hf i hi := by rw [coeff_neg, hf i hi, neg_zero]

variable {k p}

omit hp [CharP k p] in
lemma mem_primeToPPolys_iff {f : k[X]} : f ∈ primeToPPolys k p ↔ ∀ i, p ∣ i → f.coeff i = 0 :=
  Iff.rfl

/-- XIII.2.13: a polynomial of `E` of the form `bᵖ - b` is zero. -/
theorem eq_zero_of_mem_primeToPPolys_of_mem_range {e : k[X]} (he : e ∈ primeToPPolys k p)
    (hr : e ∈ (artinSchreierPoly k p).range) : e = 0 := by
  obtain ⟨b, rfl⟩ := hr
  rw [mem_primeToPPolys_iff, artinSchreierPoly_apply] at he
  rw [artinSchreierPoly_apply]
  by_cases hb : b.natDegree = 0
  · rw [eq_C_of_natDegree_eq_zero hb] at he ⊢
    have h0 := he 0 (dvd_zero p)
    rw [← C_pow, ← C_sub, coeff_C_zero] at h0
    rw [← C_pow, ← C_sub, h0, C_0]
  · exfalso
    have hd : 0 < b.natDegree := Nat.pos_of_ne_zero hb
    have hlt : b.natDegree < p * b.natDegree :=
      lt_mul_left hd hp.out.one_lt
    have hc := he (p * b.natDegree) (dvd_mul_right p _)
    rw [coeff_sub, coeff_pow_of_natDegree_le le_rfl, coeff_eq_zero_of_natDegree_lt hlt,
      sub_zero] at hc
    have hlc : b.leadingCoeff = 0 := pow_eq_zero_iff hp.out.ne_zero |>.mp hc
    rw [leadingCoeff_eq_zero] at hlc
    simp [hlc] at hb

/-- XIII.2.13: over a perfect field on which `℘` is surjective (e.g. an algebraically closed
field), every polynomial is congruent modulo `℘(k[T])` to an element of `E`. -/
theorem primeToPPolys_sup_range_eq_top [PerfectRing k p] (hAS : ∀ a : k, ∃ b, b ^ p - b = a) :
    primeToPPolys k p ⊔ (artinSchreierPoly k p).range = ⊤ := by
  rw [eq_top_iff]
  rintro f -
  induction f using Polynomial.induction_on' with
  | add f g hf hg => exact add_mem hf hg
  | monomial n a =>
    induction n using Nat.strong_induction_on generalizing a with
    | _ n ih =>
    by_cases hn : p ∣ n
    · obtain ⟨j, rfl⟩ := hn
      rcases Nat.eq_zero_or_pos j with rfl | hj
      · obtain ⟨b, hb⟩ := hAS a
        refine AddSubgroup.mem_sup_right ⟨C b, ?_⟩
        rw [artinSchreierPoly_apply, mul_zero, ← C_pow, ← C_sub, hb, monomial_zero_left]
      · obtain ⟨c, hc⟩ := surjective_frobenius k p a
        have heq : monomial (p * j) a = artinSchreierPoly k p (monomial j c) + monomial j c := by
          rw [artinSchreierPoly_apply, monomial_pow, sub_add_cancel, mul_comm, ← hc]
          rfl
        rw [heq]
        exact add_mem (AddSubgroup.mem_sup_right ⟨_, rfl⟩)
          (ih j (lt_mul_left hj hp.out.one_lt) c)
    · refine AddSubgroup.mem_sup_left fun i hi ↦ ?_
      rw [coeff_monomial, ite_eq_right_iff]
      rintro rfl
      exact absurd hi hn

/-- XIII.2.13: over any field of characteristic `p`, `E → k[T]/℘(k[T])` is injective. -/
theorem injective_mk_primeToPPolys :
    Function.Injective fun e : primeToPPolys k p ↦
      (QuotientAddGroup.mk (e : k[X]) : k[X] ⧸ (artinSchreierPoly k p).range) := by
  intro e₁ e₂ h
  have hmem := (QuotientAddGroup.eq).mp h
  have h0 := eq_zero_of_mem_primeToPPolys_of_mem_range
    (add_mem (neg_mem e₁.2) e₂.2) hmem
  rw [neg_add_eq_zero] at h0
  exact Subtype.ext h0

/-- XIII.2.13: over an algebraically closed field (more generally a perfect field on which `℘`
is surjective), `E → k[T]/℘(k[T])` is bijective. -/
theorem bijective_mk_primeToPPolys [PerfectRing k p] (hAS : ∀ a : k, ∃ b, b ^ p - b = a) :
    Function.Bijective fun e : primeToPPolys k p ↦
      (QuotientAddGroup.mk (e : k[X]) : k[X] ⧸ (artinSchreierPoly k p).range) := by
  refine ⟨injective_mk_primeToPPolys, fun q ↦ ?_⟩
  obtain ⟨f, rfl⟩ := QuotientAddGroup.mk_surjective q
  have hf : f ∈ primeToPPolys k p ⊔ (artinSchreierPoly k p).range := by
    rw [primeToPPolys_sup_range_eq_top hAS]
    trivial
  obtain ⟨e, he, r, hr, rfl⟩ := AddSubgroup.mem_sup.mp hf
  refine ⟨⟨e, he⟩, (QuotientAddGroup.eq).mpr ?_⟩
  simpa using hr

omit [CharP k p] in
lemma X_pow_mem_primeToPPolys (n : ℕ) : (X ^ (p * n + 1) : k[X]) ∈ primeToPPolys k p := by
  intro i hi
  rw [coeff_X_pow, ite_eq_right_iff]
  rintro rfl
  exfalso
  exact hp.out.one_lt.ne' (Nat.eq_one_of_dvd_one ((Nat.dvd_add_right (dvd_mul_right p n)).mp hi))

omit [CharP k p] in
variable (k p) in
/-- The polynomials without monomials of degree divisible by `p` form an infinite set. -/
theorem infinite_primeToPPolys : Infinite (primeToPPolys k p) := by
  have hinj : Function.Injective fun n : ℕ ↦
      (⟨X ^ (p * n + 1), X_pow_mem_primeToPPolys n⟩ : primeToPPolys k p) := by
    intro m n h
    have := congrArg (fun e : primeToPPolys k p ↦ (e : k[X]).natDegree) h
    simp only [natDegree_X_pow] at this
    exact Nat.eq_of_mul_eq_mul_left hp.out.pos (Nat.add_right_cancel this)
  exact Infinite.of_injective _ hinj

/-- XIII.2.13: `k[T]/℘(k[T])` (that is, `Hom(π₁(𝔸¹_k), ℤ/pℤ)`) is infinite; hence `π₁(𝔸¹_k)` is
not topologically of finite type. -/
theorem infinite_quotient_artinSchreierPoly :
    Infinite (k[X] ⧸ (artinSchreierPoly k p).range) := by
  have := infinite_primeToPPolys k p
  exact Infinite.of_injective _ injective_mk_primeToPPolys

variable (k' : Type*) [Field k'] [Algebra k k'] [CharP k' p]

lemma map_artinSchreierPoly (f : k[X]) :
    (artinSchreierPoly k p f).map (algebraMap k k') =
      artinSchreierPoly k' p (f.map (algebraMap k k')) := by
  simp [artinSchreierPoly_apply, Polynomial.map_sub, Polynomial.map_pow]

/-- The map `k[T]/℘(k[T]) → k'[T]/℘(k'[T])` induced by an extension `k → k'`. -/
noncomputable def artinSchreierBaseChange :
    k[X] ⧸ (artinSchreierPoly k p).range →+ k'[X] ⧸ (artinSchreierPoly k' p).range :=
  QuotientAddGroup.map _ _ (mapRingHom (algebraMap k k')).toAddMonoidHom (by
    rintro _ ⟨f, rfl⟩
    exact ⟨f.map (algebraMap k k'), (map_artinSchreierPoly k' f).symm⟩)

/-- XIII.2.13: for an extension `k → k'` of algebraically closed fields (more generally with `k`
perfect and `℘` surjective on `k`) which is not surjective, `k[T]/℘ → k'[T]/℘` is not
surjective: the map `π₁(𝔸¹_{k'}) → π₁(𝔸¹_k)` is surjective but not bijective. -/
theorem not_surjective_artinSchreierBaseChange [PerfectRing k p]
    (hAS : ∀ a : k, ∃ b, b ^ p - b = a) (hk : ¬ Function.Surjective (algebraMap k k')) :
    ¬ Function.Surjective (artinSchreierBaseChange (k := k) (p := p) k') := by
  intro hs
  obtain ⟨c, hc⟩ : ∃ c : k', ∀ a : k, algebraMap k k' a ≠ c := by
    by_contra h
    push Not at h
    exact hk h
  obtain ⟨q, hq⟩ := hs (QuotientAddGroup.mk (C c * X))
  obtain ⟨⟨e, he⟩, rfl⟩ := (bijective_mk_primeToPPolys (k := k) (p := p) hAS).2 q
  have hmem : e.map (algebraMap k k') ∈ primeToPPolys k' p := fun i hi ↦ by
    rw [coeff_map, he i hi, map_zero]
  have hmem' : (C c * X : k'[X]) ∈ primeToPPolys k' p := fun i hi ↦ by
    rw [coeff_C_mul_X, ite_eq_right_iff]
    rintro rfl
    exfalso
    exact hp.out.one_lt.ne' (Nat.eq_one_of_dvd_one hi)
  have heq := injective_mk_primeToPPolys (k := k') (p := p)
    (a₁ := ⟨_, hmem⟩) (a₂ := ⟨_, hmem'⟩) hq
  have := congrArg (fun f : k'[X] ↦ f.coeff 1) (congrArg Subtype.val heq)
  simp only [coeff_map, coeff_C_mul_X, ite_true] at this
  exact hc _ this

end ArtinSchreier

section PrimeToP

variable (p : ℕ) [hp : Fact p.Prime] (G : Type*) [Group G] [Finite G]

/-- The kernel of the largest quotient `G^{(p')}` of `G` of order prime to `p`
(XIII.2.13). -/
def primeToPKernel : Subgroup G :=
  ⨅ (N : Subgroup G) (_ : N.Normal ∧ N.index.Coprime p), N

instance : (primeToPKernel p G).Normal :=
  Subgroup.normal_iInf_normal fun _ ↦ Subgroup.normal_iInf_normal fun h ↦ h.1

/-- XIII.2.13: `G^{(p')}`, the largest quotient of `G` of order prime to `p`. -/
abbrev PrimeToPQuotient := G ⧸ primeToPKernel p G

/-- The subgroup generated by the Sylow `p`-subgroups of `G`. -/
def sylowSup : Subgroup G := ⨆ P : Sylow p G, (P : Subgroup G)

instance : (sylowSup p G).Normal := by
  constructor
  intro n hn g
  have hle : (sylowSup p G).map (MulAut.conj g).toMonoidHom ≤ sylowSup p G := by
    rw [sylowSup, Subgroup.map_iSup]
    refine iSup_le fun P ↦ ?_
    have : (P : Subgroup G).map (MulAut.conj g).toMonoidHom =
        ((g • P : Sylow p G) : Subgroup G) := rfl
    rw [this]
    exact le_iSup (fun P : Sylow p G ↦ (P : Subgroup G)) (g • P)
  exact hle ⟨n, hn, rfl⟩

variable {p G}

lemma le_of_isPGroup_of_coprime {P : Subgroup G} (hP : IsPGroup p P) {N : Subgroup G} [N.Normal]
    (hN : N.index.Coprime p) : P ≤ N := by
  have hmap : IsPGroup p (P.map (QuotientGroup.mk' N)) := hP.map _
  obtain ⟨n, hn⟩ := (IsPGroup.iff_card).mp hmap
  have hdvd : Nat.card (P.map (QuotientGroup.mk' N)) ∣ N.index := by
    rw [Subgroup.index_eq_card]
    exact Subgroup.card_subgroup_dvd_card _
  have hcop : (p ^ n).Coprime p := Nat.Coprime.coprime_dvd_left (hn ▸ hdvd) hN
  have hn0 : n = 0 := by
    by_contra h
    exact hp.out.one_lt.ne' (Nat.Coprime.eq_one_of_dvd hcop.symm (dvd_pow_self p h))
  rw [hn0, pow_zero, Subgroup.card_eq_one] at hn
  rw [← QuotientGroup.ker_mk' N, ← Subgroup.map_eq_bot_iff]
  exact hn

variable (p G)

/-- XIII.2.13: the kernel of `G → G^{(p')}` is the subgroup generated by the Sylow
`p`-subgroups. -/
theorem primeToPKernel_eq_sylowSup : primeToPKernel p G = sylowSup p G := by
  apply le_antisymm
  · refine iInf₂_le (sylowSup p G) ⟨inferInstance, ?_⟩
    obtain ⟨P⟩ := Sylow.nonempty (p := p) (G := G)
    have hle : (P : Subgroup G) ≤ sylowSup p G := le_iSup (fun P : Sylow p G ↦ (P : Subgroup G)) P
    have hndvd : ¬ p ∣ (sylowSup p G).index :=
      fun h ↦ P.not_dvd_index (h.trans (Subgroup.index_dvd_of_le hle))
    exact (Nat.Coprime.symm ((Nat.Prime.coprime_iff_not_dvd hp.out).mpr hndvd))
  · refine le_iInf₂ fun N hN ↦ ?_
    have := hN.1
    exact iSup_le fun P : Sylow p G ↦ le_of_isPGroup_of_coprime P.isPGroup' hN.2

/-- XIII.2.13: `G^{(p')} = 1` iff `G` is generated by its Sylow `p`-subgroups. -/
theorem subsingleton_primeToPQuotient_iff :
    Subsingleton (PrimeToPQuotient p G) ↔ sylowSup p G = ⊤ := by
  rw [← primeToPKernel_eq_sylowSup, ← Subgroup.index_eq_one, Subgroup.index_eq_card,
    Nat.card_eq_one_iff_unique]
  exact ⟨fun h ↦ ⟨h, ⟨1⟩⟩, fun h ↦ h.1⟩

/-- XIII.2.13: a finite simple group of order divisible by `p` is generated by its Sylow
`p`-subgroups, so `G^{(p')} = 1`. -/
theorem sylowSup_eq_top_of_isSimpleGroup [IsSimpleGroup G] (h : p ∣ Nat.card G) :
    sylowSup p G = ⊤ := by
  rcases IsSimpleGroup.eq_bot_or_eq_top_of_normal (sylowSup p G) inferInstance with hb | ht
  · obtain ⟨P⟩ := Sylow.nonempty (p := p) (G := G)
    have hle : (P : Subgroup G) ≤ sylowSup p G := le_iSup (fun P : Sylow p G ↦ (P : Subgroup G)) P
    exact absurd (le_bot_iff.mp (hb ▸ hle)) (P.ne_bot_of_dvd_card h)
  · exact ht

end PrimeToP

end SGA.SGA1.ExposeXIII
