/-
Copyright (c) 2026 SGAenglishpluslean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SGAenglishpluslean contributors
-/
import Mathlib.GroupTheory.FinitelyPresentedGroup
import Mathlib.GroupTheory.SemidirectProduct

/-!
# SGA 1, Exposé XIII, 4.7–4.8: amalgamated sums and coinvariants

In XIII.4.7, `π₁(U) → π₁(S)` is surjective with kernel `K`, and `π'₁(X_U)` is a semidirect
product of `π₁(U)` by `A = π₁^L(X_s̄)`. The amalgamated sum `π₁(S) ∐_{π₁(U)} π'₁(X_U)` is the
quotient of `π'₁(X_U)` by the invariant subgroup generated by the image of `K`, and this quotient
is the semidirect product of `π₁(S) = π₁(U)/K` by the coinvariants `A_K` (4.7.3). XIII.4.8 then
presents `A_K` by generators and relations.

We prove these facts for abstract groups: `surjective_of_exact_rows` (the diagram chase of 4.7
showing that `φ` is onto), `isPushout_quotient` (4.7.1), `semidirectQuotientEquiv` (4.7.3),
`coinvariantKernel_closure_eq` and `coinvariantsEquivPresentation` (4.8), and
`isFinitelyPresented_coinvariants` (the "in particular" of 4.8). SGA works with profinite groups
and closed invariant subgroups; the algebra is the same, but the closures are not treated here.
-/

namespace SGA.SGA1.ExposeXIII

open Subgroup

section Coinvariants

variable {A : Type*} [Group A]

/-- The normal subgroup of `A` generated by the `σ a * a⁻¹`, `σ ∈ Γ`: the kernel of `A → A_Γ`. -/
def coinvariantKernel (Γ : Set (MulAut A)) : Subgroup A :=
  normalClosure {y | ∃ σ ∈ Γ, ∃ a, y = σ a * a⁻¹}

instance (Γ : Set (MulAut A)) : (coinvariantKernel Γ).Normal :=
  normalClosure_normal

/-- The coinvariants `A_Γ` of a group of automorphisms (XIII.4.7). -/
abbrev Coinvariants (Γ : Set (MulAut A)) := A ⧸ coinvariantKernel Γ

lemma smul_mul_inv_mem_coinvariantKernel {Γ : Set (MulAut A)} {σ : MulAut A} (hσ : σ ∈ Γ)
    (a : A) : σ a * a⁻¹ ∈ coinvariantKernel Γ :=
  subset_normalClosure ⟨σ, hσ, a, rfl⟩

/-- XIII.4.8, key step: if `A` is generated by `X` and `Γ` is generated by `S`, the coinvariants
under `Γ` are the quotient by the relations `s(x) x⁻¹`, `s ∈ S`, `x ∈ X`. -/
theorem coinvariantKernel_closure_eq (S : Set (MulAut A)) (X : Set A) (hX : closure X = ⊤) :
    coinvariantKernel (closure S : Set (MulAut A)) =
      normalClosure {y | ∃ s ∈ S, ∃ x ∈ X, y = s x * x⁻¹} := by
  set M := normalClosure {y | ∃ s ∈ S, ∃ x ∈ X, y = s x * x⁻¹}
  refine le_antisymm (normalClosure_le_normal ?_) (normalClosure_mono ?_)
  · -- first for the generators `s ∈ S`, by induction on `a`
    have hS : ∀ s ∈ S, ∀ a : A, s a * a⁻¹ ∈ M := by
      intro s hs a
      have ha : a ∈ closure X := hX ▸ mem_top a
      induction ha using closure_induction with
      | mem x hx => exact subset_normalClosure ⟨s, hs, x, hx, rfl⟩
      | one => simp
      | mul b c _ _ hb hc =>
        have : s (b * c) * (b * c)⁻¹ = (s b * b⁻¹) * (b * (s c * c⁻¹) * b⁻¹) := by
          simp only [map_mul, mul_inv_rev]
          group
        rw [this]
        exact M.mul_mem hb (normalClosure_normal.conj_mem _ hc b)
      | inv b _ hb =>
        have : s b⁻¹ * b⁻¹⁻¹ = (s b)⁻¹ * (s b * b⁻¹)⁻¹ * (s b)⁻¹⁻¹ := by
          simp only [map_inv]
          group
        rw [this]
        exact normalClosure_normal.conj_mem _ (M.inv_mem hb) _
    -- then by induction on `σ ∈ closure S`
    rintro _ ⟨σ, hσ, a, rfl⟩
    induction hσ using closure_induction generalizing a with
    | mem s hs => exact hS s hs a
    | one => simp
    | mul τ ρ _ _ hτ hρ =>
      have : (τ * ρ) a * a⁻¹ = (τ (ρ a) * (ρ a)⁻¹) * (ρ a * a⁻¹) := by
        simp only [MulAut.mul_apply]
        group
      rw [this]
      exact M.mul_mem (hτ _) (hρ a)
    | inv τ _ hτ =>
      have : τ⁻¹ a * a⁻¹ = (τ (τ⁻¹ a) * (τ⁻¹ a)⁻¹)⁻¹ := by
        simp only [MulAut.apply_inv_self]
        group
      rw [this]
      exact M.inv_mem (hτ _)
  · rintro _ ⟨s, hs, x, -, rfl⟩
    exact ⟨s, subset_closure hs, x, rfl⟩

/-- XIII.4.8: if `A = F ⧸ ⟨⟨R⟩⟩` and `Γ` is generated by `S`, then `A_Γ` is the quotient of `F`
by the invariant subgroup generated by `R` and by elements `z` lifting the `s(x) x⁻¹`, where
`x` runs through the images of a generating set `X` of `F`. -/
theorem coinvariantsEquivPresentation {F : Type*} [Group F] (π : F →* A)
    (hπ : Function.Surjective π) (R : Set F) (hR : π.ker = normalClosure R) (X : Set F)
    (hX : closure X = ⊤) (S : Set (MulAut A)) (Z : Set F)
    (hZ : π '' Z = {y | ∃ s ∈ S, ∃ x ∈ π '' X, y = s x * x⁻¹}) :
    Nonempty (Coinvariants (closure S : Set (MulAut A)) ≃* F ⧸ normalClosure (R ∪ Z)) := by
  have hX' : closure (π '' X) = ⊤ := by
    rw [← MonoidHom.map_closure, hX, ← MonoidHom.range_eq_map, MonoidHom.range_eq_top.mpr hπ]
  let q : F →* Coinvariants (closure S : Set (MulAut A)) := (QuotientGroup.mk' _).comp π
  have hq : Function.Surjective q := (QuotientGroup.mk'_surjective _).comp hπ
  have hker : q.ker = normalClosure (R ∪ Z) := by
    rw [← MonoidHom.comap_ker, QuotientGroup.ker_mk', coinvariantKernel_closure_eq S _ hX', ← hZ,
      ← map_normalClosure Z π hπ, comap_map_eq, hR, normalClosure_union, sup_comm]
  exact ⟨((QuotientGroup.quotientKerEquivOfSurjective q hq).symm.trans
    (QuotientGroup.quotientMulEquivOfEq hker))⟩

/-- XIII.4.8, "in particular" (for abstract groups): if `A` is finitely presented and `Γ` is
finitely generated, then `A_Γ` is finitely presented. -/
theorem isFinitelyPresented_coinvariants [hA : Group.IsFinitelyPresented A] (S : Set (MulAut A))
    (hS : S.Finite) : Group.IsFinitelyPresented (Coinvariants (closure S : Set (MulAut A))) := by
  obtain ⟨n, φ, hφ, -⟩ := hA.out
  have hXfin : (Set.range (φ ∘ FreeGroup.of)).Finite := Set.finite_range _
  have hX : closure (Set.range (φ ∘ FreeGroup.of)) = ⊤ := by
    rw [Set.range_comp, ← MonoidHom.map_closure, FreeGroup.closure_range_of,
      ← MonoidHom.range_eq_map, MonoidHom.range_eq_top.mpr hφ]
  refine Group.IsFinitelyPresented.quotient _ ⟨_, ?_, (coinvariantKernel_closure_eq S _ hX).symm⟩
  have : {y | ∃ s ∈ S, ∃ x ∈ Set.range (φ ∘ FreeGroup.of), y = s x * x⁻¹} =
      (fun p : MulAut A × A ↦ p.1 p.2 * p.2⁻¹) '' (S ×ˢ Set.range (φ ∘ FreeGroup.of)) := by
    ext y
    constructor
    · rintro ⟨s, hs, x, hx, rfl⟩
      exact ⟨(s, x), ⟨hs, hx⟩, rfl⟩
    · rintro ⟨⟨s, x⟩, ⟨hs, hx⟩, rfl⟩
      exact ⟨s, hs, x, hx, rfl⟩
  rw [this]
  exact (hS.prod hXfin).image _

end Coinvariants

section Pushout

variable {B C : Type*} [Group B] [Group C] (ι : C →* B) (K : Subgroup C) [K.Normal]

/-- The invariant subgroup of `B` generated by the image of `K`. -/
abbrev imageNormalClosure : Subgroup B := normalClosure (ι '' K)

/-- The morphism `C ⧸ K → B ⧸ ⟨⟨ι(K)⟩⟩`. -/
def pushoutInl : C ⧸ K →* B ⧸ imageNormalClosure ι K :=
  QuotientGroup.map _ _ ι fun k hk ↦ subset_normalClosure ⟨k, hk, rfl⟩

@[simp]
lemma pushoutInl_mk (c : C) :
    pushoutInl ι K (c : C ⧸ K) = ((ι c : B) : B ⧸ imageNormalClosure ι K) :=
  rfl

/-- XIII.4.7.1: `B ⧸ ⟨⟨ι(K)⟩⟩` is the amalgamated sum of `C ⧸ K` and `B` over `C`, i.e. it has
the universal property of the pushout of `C → C ⧸ K` and `ι : C → B` in the category of
groups. -/
theorem isPushout_quotient {T : Type*} [Group T] (f₁ : C ⧸ K →* T) (f₂ : B →* T)
    (h : f₂.comp ι = f₁.comp (QuotientGroup.mk' K)) :
    ∃! g : B ⧸ imageNormalClosure ι K →* T,
      g.comp (QuotientGroup.mk' _) = f₂ ∧ g.comp (pushoutInl ι K) = f₁ := by
  have hle : imageNormalClosure ι K ≤ f₂.ker := normalClosure_le_normal (by
    rintro _ ⟨k, hk, rfl⟩
    rw [SetLike.mem_coe, MonoidHom.mem_ker, ← MonoidHom.comp_apply, h, MonoidHom.comp_apply,
      QuotientGroup.mk'_apply, (QuotientGroup.eq_one_iff k).mpr hk, map_one])
  refine ⟨QuotientGroup.lift _ f₂ hle, ⟨?_, ?_⟩, fun g ⟨hg, _⟩ ↦ ?_⟩
  · ext b
    rfl
  · ext c
    change f₂ (ι c) = f₁ c
    rw [← MonoidHom.comp_apply, h]
    rfl
  · ext b
    exact DFunLike.congr_fun hg b

end Pushout

section Semidirect

variable {A C : Type*} [Group A] [Group C] (φ : C →* MulAut A) (K : Subgroup C) [K.Normal]

/-- The group of automorphisms of `A` through which `K` acts. -/
abbrev actingGroup : Set (MulAut A) := φ '' K

lemma map_coinvariantKernel_le (c : C) :
    (coinvariantKernel (actingGroup φ K)).map (φ c).toMonoidHom ≤
      coinvariantKernel (actingGroup φ K) := by
  rw [coinvariantKernel, map_normalClosure _ _ (φ c).surjective]
  apply normalClosure_mono
  rintro _ ⟨_, ⟨_, ⟨k, hk, rfl⟩, a, rfl⟩, rfl⟩
  refine ⟨φ (c * k * c⁻¹), ⟨_, Subgroup.Normal.conj_mem inferInstance k hk c, rfl⟩, φ c a, ?_⟩
  simp [map_mul, MulAut.mul_apply]

lemma map_coinvariantKernel_eq (c : C) :
    (coinvariantKernel (actingGroup φ K)).map (φ c).toMonoidHom =
      coinvariantKernel (actingGroup φ K) := by
  refine le_antisymm (map_coinvariantKernel_le φ K c) ?_
  have h := map_mono (f := (φ c).toMonoidHom) (map_coinvariantKernel_le φ K c⁻¹)
  rw [map_map] at h
  have hid : (φ c).toMonoidHom.comp (φ c⁻¹).toMonoidHom = MonoidHom.id A := by
    ext a
    change φ c (φ c⁻¹ a) = a
    rw [← MulAut.mul_apply, ← map_mul, mul_inv_cancel, map_one, MulAut.one_apply]
  rwa [hid, map_id] at h

/-- The action of `C` on the coinvariants `A_K`. -/
noncomputable def coinvariantsAction : C →* MulAut (Coinvariants (actingGroup φ K)) where
  toFun c := QuotientGroup.congr _ _ (φ c) (map_coinvariantKernel_eq φ K c)
  map_one' := by
    ext x
    induction x using QuotientGroup.induction_on with
    | H a =>
      change ((φ 1 a : A) : Coinvariants (actingGroup φ K)) = a
      rw [map_one, MulAut.one_apply]
  map_mul' c d := by
    ext x
    induction x using QuotientGroup.induction_on with
    | H a =>
      change ((φ (c * d) a : A) : Coinvariants (actingGroup φ K)) = ((φ c (φ d a) : A) : _)
      rw [map_mul, MulAut.mul_apply]

lemma coinvariantsAction_mk (c : C) (a : A) :
    coinvariantsAction φ K c (a : Coinvariants (actingGroup φ K)) = (φ c a : A) :=
  rfl

lemma le_ker_coinvariantsAction : K ≤ (coinvariantsAction φ K).ker := by
  intro k hk
  rw [MonoidHom.mem_ker]
  ext x
  induction x using QuotientGroup.induction_on with
  | H a =>
    rw [coinvariantsAction_mk, MulAut.one_apply, QuotientGroup.eq_iff_div_mem, div_eq_mul_inv]
    exact smul_mul_inv_mem_coinvariantKernel (Γ := actingGroup φ K) (σ := φ k) ⟨k, hk, rfl⟩ a

/-- The action of `C ⧸ K` on the coinvariants `A_K`. -/
noncomputable def quotientCoinvariantsAction : C ⧸ K →* MulAut (Coinvariants (actingGroup φ K)) :=
  QuotientGroup.lift K (coinvariantsAction φ K) (le_ker_coinvariantsAction φ K)

/-- The image of `K` under `inr` normally generates the kernel of the comparison map. -/
abbrev inrNormalClosure : Subgroup (A ⋊[φ] C) :=
  imageNormalClosure (SemidirectProduct.inr : C →* A ⋊[φ] C) K

/-- The comparison map `(A ⋊ C) ⧸ ⟨⟨K⟩⟩ → A_K ⋊ (C ⧸ K)`. -/
noncomputable def semidirectQuotientToCoinvariants :
    (A ⋊[φ] C) ⧸ inrNormalClosure φ K →*
      Coinvariants (actingGroup φ K) ⋊[quotientCoinvariantsAction φ K] (C ⧸ K) :=
  QuotientGroup.lift _ (SemidirectProduct.map (QuotientGroup.mk' _) (QuotientGroup.mk' K)
    (fun c ↦ by
      ext a
      rfl))
    (normalClosure_le_normal (by
      rintro _ ⟨k, hk, rfl⟩
      rw [SetLike.mem_coe, MonoidHom.mem_ker, SemidirectProduct.map_inr, QuotientGroup.mk'_apply,
        (QuotientGroup.eq_one_iff k).mpr hk, map_one]))

omit [K.Normal] in
lemma inl_mem_of_mem_coinvariantKernel {a : A} (ha : a ∈ coinvariantKernel (actingGroup φ K)) :
    SemidirectProduct.inl a ∈ inrNormalClosure φ K := by
  have hle : coinvariantKernel (actingGroup φ K) ≤
      (inrNormalClosure φ K).comap SemidirectProduct.inl := by
    refine normalClosure_le_normal ?_
    rintro _ ⟨_, ⟨k, hk, rfl⟩, a, rfl⟩
    have hk' : SemidirectProduct.inr k ∈ inrNormalClosure φ K := subset_normalClosure ⟨k, hk, rfl⟩
    have := (inrNormalClosure φ K).mul_mem hk'
      (normalClosure_normal.conj_mem _ (inv_mem hk') (SemidirectProduct.inl a))
    rw [SetLike.mem_coe, mem_comap]
    simp only [map_mul, map_inv, SemidirectProduct.inl_aut]
    convert this using 1
    group
  exact hle ha

/-- The comparison map `A_K ⋊ (C ⧸ K) → (A ⋊ C) ⧸ ⟨⟨K⟩⟩`. -/
noncomputable def coinvariantsToSemidirectQuotient :
    Coinvariants (actingGroup φ K) ⋊[quotientCoinvariantsAction φ K] (C ⧸ K) →*
      (A ⋊[φ] C) ⧸ inrNormalClosure φ K :=
  SemidirectProduct.lift
    (QuotientGroup.lift _ ((QuotientGroup.mk' _).comp SemidirectProduct.inl) fun a ha ↦ by
      rw [MonoidHom.mem_ker, MonoidHom.comp_apply, QuotientGroup.mk'_apply,
        QuotientGroup.eq_one_iff]
      exact inl_mem_of_mem_coinvariantKernel φ K ha)
    (pushoutInl SemidirectProduct.inr K)
    (fun c ↦ by
      induction c using QuotientGroup.induction_on with
      | H c =>
        ext a
        change ((SemidirectProduct.inl (φ c a) : A ⋊[φ] C) : _ ⧸ inrNormalClosure φ K) =
          (SemidirectProduct.inr c * SemidirectProduct.inl a * (SemidirectProduct.inr c)⁻¹ :
            A ⋊[φ] C)
        rw [SemidirectProduct.inl_aut, map_inv])

/-- XIII.4.7.3: the quotient of `A ⋊ C` by the invariant subgroup generated by `K ⊴ C` is the
semidirect product of `C ⧸ K` by the coinvariants `A_K`. -/
noncomputable def semidirectQuotientEquiv :
    (A ⋊[φ] C) ⧸ inrNormalClosure φ K ≃*
      Coinvariants (actingGroup φ K) ⋊[quotientCoinvariantsAction φ K] (C ⧸ K) :=
  MonoidHom.toMulEquiv (semidirectQuotientToCoinvariants φ K) (coinvariantsToSemidirectQuotient φ K)
    (by
      apply QuotientGroup.monoidHom_ext
      refine MonoidHom.ext fun b ↦ ?_
      change ((SemidirectProduct.inl b.left * SemidirectProduct.inr b.right : A ⋊[φ] C) :
        _ ⧸ inrNormalClosure φ K) = (b : _ ⧸ _)
      rw [SemidirectProduct.inl_left_mul_inr_right])
    (by
      refine MonoidHom.ext fun ⟨l, r⟩ ↦ ?_
      induction l using QuotientGroup.induction_on with | H a =>
      induction r using QuotientGroup.induction_on with | H c =>
      change semidirectQuotientToCoinvariants φ K
        ((SemidirectProduct.inl a * SemidirectProduct.inr c : A ⋊[φ] C) : _ ⧸ _) = _
      refine SemidirectProduct.ext ?_ ?_
      · change ((a * φ 1 1 : A) : Coinvariants (actingGroup φ K)) = a
        rw [map_one, mul_one]
      · change ((1 * c : C) : C ⧸ K) = c
        rw [one_mul])

end Semidirect

section DiagramChase

/-- XIII.4.7, diagram (4.7.0): given a commutative diagram with exact rows
`A → B₁ → C₁ → 1` and `A → B₂ → C₂ → 1` which is the identity on `A`, if `C₁ → C₂` is surjective
then so is `B₁ → B₂`. (In SGA: `π₁(U) → π₁(S)` onto implies `π'₁(X_U) → π'₁(X)` onto, so the
morphism `φ` of (4.7.1) is an epimorphism.) -/
theorem surjective_of_exact_rows {A B₁ C₁ B₂ C₂ : Type*} [Group A] [Group B₁] [Group C₁]
    [Group B₂] [Group C₂] (i₁ : A →* B₁) (p₁ : B₁ →* C₁) (i₂ : A →* B₂) (p₂ : B₂ →* C₂)
    (β : B₁ →* B₂) (γ : C₁ →* C₂) (hβ : β.comp i₁ = i₂) (hγ : p₂.comp β = γ.comp p₁)
    (hp₁ : Function.Surjective p₁) (hex₂ : i₂.range = p₂.ker) (hγs : Function.Surjective γ) :
    Function.Surjective β := by
  intro b₂
  obtain ⟨c₁, hc₁⟩ := hγs (p₂ b₂)
  obtain ⟨b₁, rfl⟩ := hp₁ c₁
  have hker : (β b₁)⁻¹ * b₂ ∈ p₂.ker := by
    rw [MonoidHom.mem_ker, map_mul, map_inv, ← MonoidHom.comp_apply, hγ, MonoidHom.comp_apply,
      hc₁, inv_mul_cancel]
  rw [← hex₂] at hker
  obtain ⟨a, ha⟩ := hker
  refine ⟨b₁ * i₁ a, ?_⟩
  rw [map_mul, ← MonoidHom.comp_apply, hβ, ha, mul_inv_cancel_left]

end DiagramChase

end SGA.SGA1.ExposeXIII
