/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.SGA1.ExposeXII.GAGAFiberSeparating
import SGA.SGA1.ExposeXIII.CurveFundamentalGroupCompletion

/-!
# SGA 1, XIII.2.12 in genus `0` over `ℂ`: the group structure

For `S ⊂ ℂ` finite with `m` elements, `X = Spec ℂ[t][1/∏_{a ∈ S} (t - a)]` is `ℙ¹_ℂ` minus the
`m + 1` points `S ∪ {∞}`, and its étale fundamental group is the profinite completion of the free
group on `S` (xii4, xii51: `PuncturedPlane.etaleFundamentalGroup_mulEquiv_completion_freeGroup`,
from the Riemann existence theorem for `ℂ ∖ S` and cx-top's free basis of `π₁(ℂ ∖ S)`). Hence
(`PuncturedPlane.exists_isProLSurfaceGroup`), at every geometric point `ξ` of `X` (with values in
any separably closed field), `π₁(X, ξ)` has elements `σ₁, …, σ_{m+1}` presenting it as the
profinite group generated by `m + 1` elements with product `1`, for every set of primes `L`:
the group structure in XIII.2.12 for `(g, n) = (0, m + 1)` over `ℂ`.

This is not the full XIII.2.12 in genus `0`: the condition that `σⱼ` generates an inertia group
at the `j`-th removed point is not proved here. It needs the comparison of inertia groups with
loops around the punctures and, at `∞`, the order of cx-top's free basis (the product of the loops
around the points of `S` is a loop around `∞`).
-/

universe u

open CategoryTheory AlgebraicGeometry

namespace SGA.SGA1.ExposeXIII

namespace PuncturedPlane

open ExposeXII ExposeXII.PuncturedPlane

instance (S : Finset ℂ) : IsDomain (coordRing S) :=
  IsLocalization.isDomain_localization (M := Submonoid.powers (punctures S))
    (powers_le_nonZeroDivisors_of_noZeroDivisors
      (Finset.prod_ne_zero_iff.mpr fun a _ ↦ Polynomial.X_sub_C_ne_zero a))

/-- XIII.2.12 for `(g, n) = (0, |S| + 1)` over `ℂ`, group structure only: for `S ⊂ ℂ` finite and
any geometric point `ξ` of `X = Spec ℂ[t][1/∏_{a ∈ S} (t - a)]` (`ℙ¹_ℂ` minus `S ∪ {∞}`), there
are `σ₁, …, σ_{|S|+1} ∈ π₁(X, ξ)` presenting the maximal pro-`L` quotient of `π₁(X, ξ)` as the
pro-`L` group generated by `|S| + 1` elements with product `1` (`IsProLSurfaceGroup` in genus `0`),
for every set of primes `L`. The inertia condition of XIII.2.12 on the `σⱼ` is not part of this
statement. -/
theorem exists_isProLSurfaceGroup (S : Finset ℂ) (L : Set ℕ) (Ω : Type) [Field Ω]
    [IsSepClosed Ω] (ξ : Spec (.of Ω) ⟶ Spec (.of (coordRing S))) :
    ∃ σ : Fin (S.card + 1) → ExposeV.etaleFundamentalGroup Ω ξ,
      IsProLSurfaceGroup.{0} L (Fin.elim0 : Fin 0 → ExposeV.etaleFundamentalGroup Ω ξ)
        Fin.elim0 σ := by
  obtain ⟨z, hz⟩ := S.exists_notMem
  let x := (schemeHomeomorph S).symm ⟨z, hz⟩
  obtain ⟨e⟩ := etaleFundamentalGroup_mulEquiv_completion_freeGroup S x
  obtain ⟨γ⟩ := ExposeV.etalePaths.nonempty ℂ Ω x.1 ξ
  let ψ := e.symm.trans (ExposeV.etaleFundamentalGroup.continuousMulEquivOfPath ℂ Ω γ)
  let b : Fin S.card → ProfiniteGrp.ProfiniteCompletion.completion (GrpCat.of (FreeGroup S)) :=
    fun i ↦ ProfiniteGrp.ProfiniteCompletion.etaFn _ (FreeGroup.of (S.equivFin.symm i))
  refine ⟨genusZeroGenerators (⇑ψ ∘ b), isProLSurfaceGroup_of_bijective_comp L
    (fun G _ _ _ hG ↦ ?_)⟩
  have := hG.1
  exact bijective_comp_map L ψ (fun G _ _ _ hG ↦ have := hG.1;
    bijective_comp_etaFn_freeGroup S.equivFin.symm G) G hG

end PuncturedPlane

end SGA.SGA1.ExposeXIII
