/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import Mathlib.Topology.Algebra.Category.ProfiniteGrp.Completion
import SGA.SGA1.ExposeXIII.CurveFundamentalGroup

/-!
# SGA 1, XIII.2.12: presentations of profinite completions (group theory)

In characteristic `0`, XIII.2.12 comes from the topological fundamental group: `π₁(U)` is the
profinite completion of `π₁^top(U(ℂ))`, a group with the presentation
`⟨xᵢ, yᵢ, σⱼ | ∏ᵢ [xᵢ, yᵢ] ∏ⱼ σⱼ⟩`. This file passes from the discrete presentation to the
pro-`L` statement `IsProLSurfaceGroup`:

* `IsProLSurfaceGroup.map`: `IsProLSurfaceGroup` is transported along isomorphisms of topological
  groups;
* `isProLSurfaceGroup_of_denseRange`: if `ι : π → Γ` has dense image, every homomorphism from
  `π` to a finite `L`-group extends to a continuous homomorphism on `Γ`, and `xᵢ, yᵢ, σⱼ` generate
  `π`, satisfy (*) and map to any family of a finite `L`-group satisfying (*), then their images
  satisfy `IsProLSurfaceGroup L`;
* `isProLSurfaceGroup_etaFn`: the case of the profinite completion of `π`, for every `L`;
* genus `0`: `FreeGroup.genusZeroGenerators b` (`σⱼ = bⱼ` for `j < m`, `σ_{m+1} = (b₁ ⋯ b_m)⁻¹`)
  satisfies the relation `σ₁ ⋯ σ_{m+1} = 1` and presents the free group on `b`
  (`isProLSurfaceGroup_completion_freeGroup`: the profinite completion of the free group of rank
  `m` is the profinite group generated by `m + 1` elements with product `1`), and more generally
  `isProLSurfaceGroup_of_bijective_comp`: if `Γ^L` is the free pro-`L` group on `b`, then
  `genusZeroGenerators b` presents it.
-/

universe u w

open CategoryTheory

namespace SGA.SGA1.ExposeXIII

section Transport

variable {L : Set ℕ} {Γ Γ' : Type*} [Group Γ] [TopologicalSpace Γ] [Group Γ'] [TopologicalSpace Γ']
  {g n : ℕ}

/-- `IsProLSurfaceGroup` is transported along isomorphisms of topological groups. -/
theorem IsProLSurfaceGroup.map {x y : Fin g → Γ} {σ : Fin n → Γ}
    (h : IsProLSurfaceGroup.{w} L x y σ) (ψ : Γ ≃ₜ* Γ') :
    IsProLSurfaceGroup.{w} L (ψ ∘ x) (ψ ∘ y) (ψ ∘ σ) := by
  refine ⟨?_, fun G _ _ _ hG ↦ ⟨fun φ₁ φ₂ hx hy hσ ↦ ?_, fun x' y' σ' hrel ↦ ?_⟩⟩
  · rw [← map_surfaceWord]
    exact proLKernel_le_comap L (ψ : Γ →* Γ') ψ.continuous h.1
  · have := (h.2 G hG).1 (φ₁.comp (ψ : Γ →ₜ* Γ')) (φ₂.comp (ψ : Γ →ₜ* Γ')) hx hy hσ
    ext γ'
    have h' := congrArg (fun φ : ContinuousMonoidHom Γ G ↦ φ (ψ.symm γ')) this
    simpa using h'
  · obtain ⟨φ, hφx, hφy, hφσ⟩ := (h.2 G hG).2 x' y' σ' hrel
    refine ⟨φ.comp (ψ.symm : Γ' →ₜ* Γ), ?_, ?_, ?_⟩ <;> ext i
    · simpa using congrFun hφx i
    · simpa using congrFun hφy i
    · simpa using congrFun hφσ i

end Transport

section DenseRange

variable (L : Set ℕ) {π Γ : Type*} [Group π] [Group Γ] [TopologicalSpace Γ] {g n : ℕ}

/-- XIII.2.12, from a discrete presentation to the pro-`L` one: let `ι : π → Γ` be a homomorphism
with dense image such that every homomorphism from `π` to a finite `L`-group (with values in
`Type w`) extends to a continuous homomorphism on `Γ`. If `xᵢ, yᵢ, σⱼ ∈ π` generate `π`, satisfy
the relation (*) and can be sent to any family of a finite `L`-group satisfying (*), then their
images present `Γ^L` (`IsProLSurfaceGroup L`). E.g. `Γ` the profinite completion of `π`
(`isProLSurfaceGroup_etaFn`). -/
theorem isProLSurfaceGroup_of_denseRange (ι : π →* Γ) (hι : DenseRange ι)
    (hext : ∀ (G : Type w) [Group G] [TopologicalSpace G] [DiscreteTopology G], IsLGroup L G →
      ∀ f : π →* G, ∃ φ : ContinuousMonoidHom Γ G, ∀ a, φ (ι a) = f a)
    (x y : Fin g → π) (σ : Fin n → π) (hrel : surfaceWord x y σ = 1)
    (hgen : Subgroup.closure (Set.range x ∪ Set.range y ∪ Set.range σ) = ⊤)
    (hpres : ∀ (G : Type w) [Group G], IsLGroup L G →
      ∀ (x' y' : Fin g → G) (σ' : Fin n → G), surfaceWord x' y' σ' = 1 →
        ∃ f : π →* G, ⇑f ∘ x = x' ∧ ⇑f ∘ y = y' ∧ ⇑f ∘ σ = σ') :
    IsProLSurfaceGroup.{w} L (ι ∘ x) (ι ∘ y) (ι ∘ σ) := by
  refine ⟨?_, fun G _ _ _ hG ↦ ⟨fun φ₁ φ₂ hx hy hσ ↦ ?_, fun x' y' σ' hrel' ↦ ?_⟩⟩
  · rw [← map_surfaceWord, hrel, map_one]
    exact one_mem _
  · -- `φ₁ ∘ ι` and `φ₂ ∘ ι` agree on the generators of `π`, so everywhere, and `ι` is dense
    have hcomp : (φ₁ : Γ →* G).comp ι = (φ₂ : Γ →* G).comp ι := by
      refine MonoidHom.eq_of_eqOn_dense hgen ?_
      rintro _ ((⟨i, rfl⟩ | ⟨i, rfl⟩) | ⟨j, rfl⟩)
      · exact congrFun hx i
      · exact congrFun hy i
      · exact congrFun hσ j
    have hG2 : T2Space G := DiscreteTopology.toT2Space
    ext γ
    refine congrFun (hι.equalizer φ₁.continuous φ₂.continuous (funext fun a ↦ ?_)) γ
    exact DFunLike.congr_fun hcomp a
  · obtain ⟨f, hfx, hfy, hfσ⟩ := hpres G hG x' y' σ' hrel'
    obtain ⟨φ, hφ⟩ := hext G hG f
    refine ⟨φ, ?_, ?_, ?_⟩ <;> ext i
    · exact (hφ _).trans (congrFun hfx i)
    · exact (hφ _).trans (congrFun hfy i)
    · exact (hφ _).trans (congrFun hfσ i)

end DenseRange

section Completion

open ProfiniteGrp ProfiniteGrp.ProfiniteCompletion

variable (L : Set ℕ) {π : Type u} [Group π] {g n : ℕ}

/-- The canonical map of a group to its profinite completion, as a monoid homomorphism. -/
noncomputable abbrev etaHom (π : Type u) [Group π] :
    π →* completion (GrpCat.of π) :=
  (eta (GrpCat.of π)).hom

lemma etaHom_apply (a : π) : etaHom π a = etaFn (GrpCat.of π) a := rfl

/-- Every homomorphism from `π` to a finite discrete group extends to a continuous homomorphism on
the profinite completion of `π`. -/
lemma exists_continuousMonoidHom_etaFn (G : Type u) [Group G] [TopologicalSpace G]
    [DiscreteTopology G] [Finite G] (f : π →* G) :
    ∃ φ : ContinuousMonoidHom (completion (GrpCat.of π)) G,
      ∀ a, φ (etaFn (GrpCat.of π) a) = f a := by
  have : IsTopologicalGroup G := {}
  let F : GrpCat.of π ⟶ GrpCat.of (ProfiniteGrp.of G) := GrpCat.ofHom f
  refine ⟨(lift F).hom, fun a ↦ ?_⟩
  have h := lift_eta F
  exact congrArg (fun φ ↦ (GrpCat.Hom.hom φ) a) h

/-- XIII.2.12 in characteristic `0`, group theory: if `xᵢ, yᵢ, σⱼ` generate `π` and present it by
the single relation (*) (at least towards finite `L`-groups), their images in the profinite
completion of `π` present its maximal pro-`L` quotient (`IsProLSurfaceGroup L`). -/
theorem isProLSurfaceGroup_etaFn (x y : Fin g → π) (σ : Fin n → π)
    (hrel : surfaceWord x y σ = 1)
    (hgen : Subgroup.closure (Set.range x ∪ Set.range y ∪ Set.range σ) = ⊤)
    (hpres : ∀ (G : Type u) [Group G], IsLGroup L G →
      ∀ (x' y' : Fin g → G) (σ' : Fin n → G), surfaceWord x' y' σ' = 1 →
        ∃ f : π →* G, ⇑f ∘ x = x' ∧ ⇑f ∘ y = y' ∧ ⇑f ∘ σ = σ') :
    IsProLSurfaceGroup.{u} L (etaFn (GrpCat.of π) ∘ x) (etaFn (GrpCat.of π) ∘ y)
      (etaFn (GrpCat.of π) ∘ σ) :=
  isProLSurfaceGroup_of_denseRange L (etaHom π) (denseRange (GrpCat.of π))
    (fun G _ _ _ hG f ↦ have := hG.1; exists_continuousMonoidHom_etaFn G f) x y σ hrel hgen hpres

end Completion

section GenusZero

variable {G : Type*} [Group G] {m : ℕ}

/-- The generators of the genus-`0` presentation attached to `b₁, …, b_m`:
`σⱼ = bⱼ` for `j ≤ m` and `σ_{m+1} = (b₁ ⋯ b_m)⁻¹`, so that `σ₁ ⋯ σ_{m+1} = 1`. -/
def genusZeroGenerators (b : Fin m → G) : Fin (m + 1) → G :=
  Fin.lastCases ((List.ofFn b).prod)⁻¹ b

@[simp] lemma genusZeroGenerators_castSucc (b : Fin m → G) (j : Fin m) :
    genusZeroGenerators b j.castSucc = b j := by
  simp [genusZeroGenerators]

@[simp] lemma genusZeroGenerators_last (b : Fin m → G) :
    genusZeroGenerators b (Fin.last m) = ((List.ofFn b).prod)⁻¹ := by
  simp [genusZeroGenerators]

lemma genusZeroGenerators_comp_castSucc (b : Fin m → G) :
    genusZeroGenerators b ∘ Fin.castSucc = b :=
  funext fun j ↦ genusZeroGenerators_castSucc b j

/-- `σ₁ ⋯ σ_{m+1} = 1` for `σ = genusZeroGenerators b`. -/
lemma prod_ofFn_genusZeroGenerators (b : Fin m → G) :
    (List.ofFn (genusZeroGenerators b)).prod = 1 := by
  rw [List.ofFn_succ', List.prod_concat]
  simp

lemma surfaceWord_genusZeroGenerators (x y : Fin 0 → G) (b : Fin m → G) :
    surfaceWord x y (genusZeroGenerators b) = 1 := by
  rw [surfaceWord_genus_zero, prod_ofFn_genusZeroGenerators]

/-- A family `σ'` with `σ'₁ ⋯ σ'_{m+1} = 1` is `genusZeroGenerators` of its first `m` terms. -/
lemma eq_genusZeroGenerators {σ' : Fin (m + 1) → G} (h : (List.ofFn σ').prod = 1) :
    σ' = genusZeroGenerators (σ' ∘ Fin.castSucc) := by
  funext j
  refine Fin.lastCases ?_ (fun j ↦ ?_) j
  · rw [genusZeroGenerators_last]
    rw [List.ofFn_succ', List.prod_concat] at h
    exact (inv_eq_of_mul_eq_one_right h).symm
  · rw [genusZeroGenerators_castSucc]
    rfl

lemma map_genusZeroGenerators {H : Type*} [Group H] {F : Type*} [FunLike F G H]
    [MonoidHomClass F G H] (f : F) (b : Fin m → G) :
    ⇑f ∘ genusZeroGenerators b = genusZeroGenerators (⇑f ∘ b) := by
  funext j
  refine Fin.lastCases ?_ (fun j ↦ ?_) j
  · simp [map_list_prod, List.map_ofFn]
  · simp

end GenusZero

section FreeProL

variable (L : Set ℕ) {Γ Γ' : Type*} [Group Γ] [TopologicalSpace Γ] [Group Γ'] [TopologicalSpace Γ']
  {m : ℕ}

/-- XIII.2.12 for genus `0`, group theory: if `Γ^L` is the free pro-`L` group on `b₁, …, b_m`
(every family of `m` elements of a finite `L`-group is the image of `b` under exactly one
continuous homomorphism), then `σⱼ = bⱼ` (`j ≤ m`) and `σ_{m+1} = (b₁ ⋯ b_m)⁻¹`
(`genusZeroGenerators b`) present `Γ^L` as the pro-`L` group generated by `m + 1` elements with
product `1` (`IsProLSurfaceGroup L` in genus `0`). -/
theorem isProLSurfaceGroup_of_bijective_comp {b : Fin m → Γ}
    (hb : ∀ (G : Type w) [Group G] [TopologicalSpace G] [DiscreteTopology G], IsLGroup L G →
      Function.Bijective fun φ : ContinuousMonoidHom Γ G ↦ ⇑φ ∘ b) :
    IsProLSurfaceGroup.{w} L (Fin.elim0 : Fin 0 → Γ) Fin.elim0 (genusZeroGenerators b) := by
  refine ⟨?_, fun G _ _ _ hG ↦ ⟨fun φ ψ _ _ h ↦ (hb G hG).1 ?_, fun x' y' σ' h ↦ ?_⟩⟩
  · rw [surfaceWord_genusZeroGenerators]
    exact one_mem _
  · change ⇑φ ∘ b = ⇑ψ ∘ b
    rw [← genusZeroGenerators_comp_castSucc b, ← Function.comp_assoc, ← Function.comp_assoc, h]
  · rw [surfaceWord_genus_zero] at h
    obtain ⟨φ, hφ⟩ := (hb G hG).2 (σ' ∘ Fin.castSucc)
    change ⇑φ ∘ b = σ' ∘ Fin.castSucc at hφ
    refine ⟨φ, funext fun i ↦ i.elim0, funext fun i ↦ i.elim0, ?_⟩
    rw [map_genusZeroGenerators, hφ, ← eq_genusZeroGenerators h]

/-- Bijectivity of `φ ↦ φ ∘ b` on the continuous homomorphisms to finite `L`-groups is transported
along isomorphisms of topological groups. -/
lemma bijective_comp_map (ψ : Γ ≃ₜ* Γ') {b : Fin m → Γ}
    (hb : ∀ (G : Type w) [Group G] [TopologicalSpace G] [DiscreteTopology G], IsLGroup L G →
      Function.Bijective fun φ : ContinuousMonoidHom Γ G ↦ ⇑φ ∘ b)
    (G : Type w) [Group G] [TopologicalSpace G] [DiscreteTopology G] (hG : IsLGroup L G) :
    Function.Bijective fun φ : ContinuousMonoidHom Γ' G ↦ ⇑φ ∘ (⇑ψ ∘ b) := by
  let Φ : ContinuousMonoidHom Γ' G ≃ ContinuousMonoidHom Γ G :=
    { toFun φ := φ.comp (ψ : Γ →ₜ* Γ')
      invFun φ := φ.comp (ψ.symm : Γ' →ₜ* Γ)
      left_inv φ := by ext; simp
      right_inv φ := by ext; simp }
  have : (fun φ : ContinuousMonoidHom Γ' G ↦ ⇑φ ∘ (⇑ψ ∘ b)) =
      (fun φ : ContinuousMonoidHom Γ G ↦ ⇑φ ∘ b) ∘ Φ := by
    ext φ
    rfl
  rw [this]
  exact (hb G hG).comp Φ.bijective

open ProfiniteGrp ProfiniteGrp.ProfiniteCompletion in
/-- The profinite completion of the free group on `α ≃ Fin m` is the free profinite group on the
images of the generators: continuous homomorphisms to a finite discrete group `G` correspond to
families of `m` elements of `G`. -/
theorem bijective_comp_etaFn_freeGroup {α : Type u} (e : Fin m ≃ α) (G : Type u) [Group G]
    [TopologicalSpace G] [DiscreteTopology G] [Finite G] :
    Function.Bijective fun φ : ContinuousMonoidHom (completion (GrpCat.of (FreeGroup α))) G ↦
      ⇑φ ∘ fun i ↦ etaFn (GrpCat.of (FreeGroup α)) (FreeGroup.of (e i)) := by
  refine ⟨fun φ₁ φ₂ h ↦ ?_, fun b ↦ ?_⟩
  · have hcomp : (φ₁ : _ →* G).comp (etaHom (FreeGroup α)) =
        (φ₂ : _ →* G).comp (etaHom (FreeGroup α)) := by
      refine FreeGroup.ext_hom _ _ fun a ↦ ?_
      obtain ⟨i, rfl⟩ := e.surjective a
      exact congrFun h i
    have hG2 : T2Space G := DiscreteTopology.toT2Space
    ext γ
    refine congrFun ((denseRange (GrpCat.of (FreeGroup α))).equalizer φ₁.continuous
      φ₂.continuous (funext fun a ↦ ?_)) γ
    exact DFunLike.congr_fun hcomp a
  · obtain ⟨φ, hφ⟩ := exists_continuousMonoidHom_etaFn G (FreeGroup.lift (b ∘ e.symm))
    refine ⟨φ, funext fun i ↦ ?_⟩
    simp only [Function.comp_apply]
    rw [hφ, FreeGroup.lift_apply_of]
    simp


end FreeProL

end SGA.SGA1.ExposeXIII
