/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.Foundations.Cohomology.EulerCharacteristic
import SGA.SGA1.ExposeXIII.CurveFundamentalGroup

/-!
# SGA 1, Exposé XIII, 2.12: the tame fundamental group of a curve minus `n` points

Let `X` be a proper smooth connected curve of genus `g` over a separably closed field `k` of
characteristic `p ≥ 0` and `U = X - {a₁, …, a_n}`. XIII.2.12 says that `π₁^tame(U)` is generated by
`2g + n` elements `xᵢ, yᵢ, σⱼ`, `σⱼ` generating an inertia group at `aⱼ`, with the relation
`∏ᵢ [xᵢ, yᵢ] ∏ⱼ σⱼ = 1`, and that every finite group of order prime to `p` generated by elements
satisfying this relation is a quotient of `π₁^tame(U)` in the corresponding way; in other words
`π₁^{p'}(U)` is the pro-`p'` group generated by the `xᵢ, yᵢ, σⱼ` bound by this relation. SGA
proves it by Riemann's existence theorem in characteristic `0` and by lifting to characteristic
`0` (III.7.4) and tame specialization (XIII.2.8–2.11) in characteristic `p`.

* `TameCurveFundamentalGroupStatement`: XIII.2.12 as stated (statement only);
* `TameCurvePrimeToPStatement`: its "in other words" form, the presentation of `π₁^{p'}(U)` with
  the inertia generators (statement only);
* `PrimeToPCoveringsTameStatement`: the part of XIII.2.3 b) relating the two, an étale covering
  of `U` trivialized by a Galois covering of degree prime to `p` is tamely ramified, in the form
  `tameKernel ≤ proLKernel p'` (proved as `primeToPCoveringsTameStatement` in
  `SGA.SGA1.ExposeXIII.CurveFundamentalGroupTame`);
* `tameCurvePrimeToPStatement_of_tameCurveFundamentalGroupStatement`: XIII.2.12 implies its
  "in other words" form, given `PrimeToPCoveringsTameStatement`;
* `exists_finset_card_le_closure_eq_top_of_isProLSurfaceGroup`: if `n ≥ 1`, every finite continuous
  quotient of `π₁(U)` of order prime to `p` is generated by `2g + n - 1` elements (the use of
  XIII.2.12 in XIII.2.13).

The genus is `Scheme.Hom.genus f = dim_k H¹(X, 𝒪_X)`
(`SGA.Foundations.Cohomology.EulerCharacteristic`).
The case `g = 0`, `n = 1` of the prime-to-`p` part is `affineLinePrimeToPTrivialStatement`
(for `X = ℙ¹`, `U = 𝔸¹`, in the form `π₁^{p'}(𝔸¹_k) = 1`).
-/

universe u

open CategoryTheory Limits AlgebraicGeometry

namespace SGA.SGA1.ExposeXIII

/-- XIII.2.12 (statement only; SGA's proof needs Riemann's existence theorem XII.5.1 and, in
characteristic `p`, the lifting III.7.4 and tame specialization XIII.2.8–2.11). Let `X` be a proper
smooth connected curve over a separably closed field `k` of characteristic `p ≥ 0`, of genus `g`
(`Scheme.Hom.genus f = dim_k H¹(X, 𝒪_X)`), `a₁, …, a_n` distinct closed points and
`U = X - {a₁, …, a_n}`. Then there are `xᵢ, yᵢ, σⱼ ∈ π₁(U, ξ)` (`1 ≤ i ≤ g`, `1 ≤ j ≤ n`) whose
images in `π₁^tame(U, ξ) = π₁(U, ξ) / tameKernel` (XIII.2.1.3)

* satisfy the relation (*) `∏ᵢ [xᵢ, yᵢ] ∏ⱼ σⱼ = 1` (`surfaceWord`);
* generate `π₁^tame(U, ξ)` topologically;
* `σⱼ` generates an inertia group at `aⱼ`: for some geometric point `āⱼ` over `aⱼ` and some
  inertia subgroup `H` of `π₁(U, ξ)` at `āⱼ` (`IsInertiaSubgroupAt`), the images of `H` and of
  the closed subgroup generated by `σⱼ` in `π₁^tame(U, ξ)` agree. This is written
  `closure (H · tameKernel) = closure (σⱼ^ℤ · tameKernel)`; since `π₁(U, ξ)` is compact and `H` is
  closed, `H · tameKernel` is already closed;

and for every finite group `G` of order prime to `p` generated by elements `x'ᵢ, y'ᵢ, σ'ⱼ`
satisfying (*), there is a continuous homomorphism `π₁^tame(U, ξ) → G` (a continuous
homomorphism `π₁(U, ξ) → G` vanishing on `tameKernel`, i.e. an étale covering of `U` with group
`G` tamely ramified along `X - U`) sending `xᵢ, yᵢ, σⱼ` to `x'ᵢ, y'ᵢ, σ'ⱼ`. -/
def TameCurveFundamentalGroupStatement : Prop :=
  ∀ (k : Type u) [Field k] [IsSepClosed k] (X : Scheme.{u}) (f : X ⟶ Spec (.of k)) [IsProper f]
    [SmoothOfRelativeDimension 1 f] [ConnectedSpace X] (g n : ℕ), f.genus = g →
    ∀ (a : Fin n → X), Function.Injective a → (∀ j, IsClosed {a j}) →
    ∀ (U : X.Opens), (U : Set X) = (Set.range a)ᶜ →
    ∀ (Ω : Type u) [Field Ω] [IsSepClosed Ω] (ξ : Spec (.of Ω) ⟶ (U : Scheme.{u})),
    ∃ (x y : Fin g → ExposeV.etaleFundamentalGroup Ω ξ)
      (σ : Fin n → ExposeV.etaleFundamentalGroup Ω ξ),
      surfaceWord x y σ ∈ tameKernel f U ξ ∧
      Dense ((Subgroup.closure (Set.range x ∪ Set.range y ∪ Set.range σ) ⊔ tameKernel f U ξ :
        Subgroup (ExposeV.etaleFundamentalGroup Ω ξ)) : Set (ExposeV.etaleFundamentalGroup Ω ξ)) ∧
      (∀ j, ∃ (Ω₀ : Type u) (_ : Field Ω₀) (_ : IsSepClosed Ω₀) (xb : Spec (.of Ω₀) ⟶ X)
        (H : Subgroup (ExposeV.etaleFundamentalGroup Ω ξ)),
        xb.imagePoint = a j ∧ IsInertiaSubgroupAt U xb ξ H ∧
        (H ⊔ tameKernel f U ξ).topologicalClosure =
          (Subgroup.zpowers (σ j) ⊔ tameKernel f U ξ).topologicalClosure) ∧
      ∀ (G : Type u) [Group G] [TopologicalSpace G] [DiscreteTopology G],
        IsLGroup (primesDifferentFrom (ringChar k)) G →
        ∀ (x' y' : Fin g → G) (σ' : Fin n → G), surfaceWord x' y' σ' = 1 →
          Subgroup.closure (Set.range x' ∪ Set.range y' ∪ Set.range σ') = ⊤ →
          ∃ φ : ContinuousMonoidHom (ExposeV.etaleFundamentalGroup Ω ξ) G,
            tameKernel f U ξ ≤ (φ : ExposeV.etaleFundamentalGroup Ω ξ →* G).ker ∧
            ⇑φ ∘ x = x' ∧ ⇑φ ∘ y = y' ∧ ⇑φ ∘ σ = σ'

/-- XIII.2.12, "in other words" (statement only): with the notation of
`TameCurveFundamentalGroupStatement`, `π₁^{p'}(U, ξ)` (`p'` the primes different from the
characteristic `p` of `k`; all primes if `p = 0`) is the pro-`p'` group generated by elements
`xᵢ, yᵢ, σⱼ` bound by the single relation (*) (`IsProLSurfaceGroup`), and the image of `σⱼ`
generates the image in `π₁^{p'}(U, ξ)` of an inertia group at `aⱼ` (SGA's condition on the `σⱼ`,
read in `π₁^{p'}`). For `p = 0` this says that `π₁(U, ξ)` is the profinite completion of the
surface group. -/
def TameCurvePrimeToPStatement : Prop :=
  ∀ (k : Type u) [Field k] [IsSepClosed k] (X : Scheme.{u}) (f : X ⟶ Spec (.of k)) [IsProper f]
    [SmoothOfRelativeDimension 1 f] [ConnectedSpace X] (g n : ℕ), f.genus = g →
    ∀ (a : Fin n → X), Function.Injective a → (∀ j, IsClosed {a j}) →
    ∀ (U : X.Opens), (U : Set X) = (Set.range a)ᶜ →
    ∀ (Ω : Type u) [Field Ω] [IsSepClosed Ω] (ξ : Spec (.of Ω) ⟶ (U : Scheme.{u})),
    ∃ (x y : Fin g → ExposeV.etaleFundamentalGroup Ω ξ)
      (σ : Fin n → ExposeV.etaleFundamentalGroup Ω ξ),
      IsProLSurfaceGroup.{u} (primesDifferentFrom (ringChar k)) x y σ ∧
      ∀ j, ∃ (Ω₀ : Type u) (_ : Field Ω₀) (_ : IsSepClosed Ω₀) (xb : Spec (.of Ω₀) ⟶ X)
        (H : Subgroup (ExposeV.etaleFundamentalGroup Ω ξ)),
        xb.imagePoint = a j ∧ IsInertiaSubgroupAt U xb ξ H ∧
        (H ⊔ proLKernel (primesDifferentFrom (ringChar k))
          (ExposeV.etaleFundamentalGroup Ω ξ)).topologicalClosure =
          (Subgroup.zpowers (σ j) ⊔ proLKernel (primesDifferentFrom (ringChar k))
            (ExposeV.etaleFundamentalGroup Ω ξ)).topologicalClosure

/-- XIII.2.12, "in other words", the conclusion for given data: for a curve over `k`, the points
`a`, the open `U = X - {aⱼ}` and a geometric point `ξ` of `U`, some `xᵢ, yᵢ, σⱼ ∈ π₁(U, ξ)`
present `π₁^{p'}(U, ξ)` (`IsProLSurfaceGroup`) with `σⱼ` generating the image of an inertia group
at `aⱼ`. `TameCurvePrimeToPStatement` is this conclusion for all data satisfying its hypotheses
(`tameCurvePrimeToPStatement_iff`); it is the predicate to prove for a given curve. -/
def TameCurvePrimeToPConclusion (k : Type u) [Field k] (X : Scheme.{u}) (g n : ℕ) (a : Fin n → X)
    (U : X.Opens) (Ω : Type u) [Field Ω] [IsSepClosed Ω] (ξ : Spec (.of Ω) ⟶ (U : Scheme.{u})) :
    Prop :=
  ∃ (x y : Fin g → ExposeV.etaleFundamentalGroup Ω ξ)
    (σ : Fin n → ExposeV.etaleFundamentalGroup Ω ξ),
    IsProLSurfaceGroup.{u} (primesDifferentFrom (ringChar k)) x y σ ∧
    ∀ j, ∃ (Ω₀ : Type u) (_ : Field Ω₀) (_ : IsSepClosed Ω₀) (xb : Spec (.of Ω₀) ⟶ X)
      (H : Subgroup (ExposeV.etaleFundamentalGroup Ω ξ)),
      xb.imagePoint = a j ∧ IsInertiaSubgroupAt U xb ξ H ∧
      (H ⊔ proLKernel (primesDifferentFrom (ringChar k))
        (ExposeV.etaleFundamentalGroup Ω ξ)).topologicalClosure =
        (Subgroup.zpowers (σ j) ⊔ proLKernel (primesDifferentFrom (ringChar k))
          (ExposeV.etaleFundamentalGroup Ω ξ)).topologicalClosure

/-- `TameCurvePrimeToPStatement` is `TameCurvePrimeToPConclusion` for all data satisfying its
hypotheses. -/
theorem tameCurvePrimeToPStatement_iff :
    TameCurvePrimeToPStatement.{u} ↔
      ∀ (k : Type u) [Field k] [IsSepClosed k] (X : Scheme.{u}) (f : X ⟶ Spec (.of k))
        [IsProper f] [SmoothOfRelativeDimension 1 f] [ConnectedSpace X] (g n : ℕ), f.genus = g →
        ∀ (a : Fin n → X), Function.Injective a → (∀ j, IsClosed {a j}) →
        ∀ (U : X.Opens), (U : Set X) = (Set.range a)ᶜ →
        ∀ (Ω : Type u) [Field Ω] [IsSepClosed Ω] (ξ : Spec (.of Ω) ⟶ (U : Scheme.{u})),
          TameCurvePrimeToPConclusion k X g n a U Ω ξ :=
  Iff.rfl

/-- XIII.2.3 b), for the Galois coverings with constant group used in XIII.2.12 (statement; proved
as `primeToPCoveringsTameStatement` in `SGA.SGA1.ExposeXIII.CurveFundamentalGroupTame`):
with the notation of `TameCurveFundamentalGroupStatement`, an étale covering of `U` which is a
torsor under a constant group of order prime to `p` is tamely ramified along `X - U`. In terms of
fundamental groups: the kernel of `π₁(U) → π₁^tame(U)` is contained in the kernel of
`π₁(U) → π₁^{p'}(U)`. -/
def PrimeToPCoveringsTameStatement : Prop :=
  ∀ (k : Type u) [Field k] [IsSepClosed k] (X : Scheme.{u}) (f : X ⟶ Spec (.of k)) [IsProper f]
    [SmoothOfRelativeDimension 1 f] [ConnectedSpace X] (U : X.Opens) (_ : Set.Finite (U : Set X)ᶜ)
    (Ω : Type u) [Field Ω] [IsSepClosed Ω] (ξ : Spec (.of Ω) ⟶ (U : Scheme.{u})),
    tameKernel f U ξ ≤
      proLKernel (primesDifferentFrom (ringChar k)) (ExposeV.etaleFundamentalGroup Ω ξ)

section GroupTheory

variable {L : Set ℕ} {Γ : Type*} [Group Γ] [TopologicalSpace Γ]
  {g n : ℕ}

/-- If the `xᵢ, yᵢ, σⱼ` present `Γ^L` (`IsProLSurfaceGroup`), the images of the `xᵢ, yᵢ, σⱼ`
under a continuous surjection onto a finite `L`-group generate it. -/
lemma IsProLSurfaceGroup.closure_eq_top {x y : Fin g → Γ} {σ : Fin n → Γ}
    (h : IsProLSurfaceGroup.{u} L x y σ) {G : Type u} [Group G] [TopologicalSpace G]
    [DiscreteTopology G] (hG : IsLGroup L G) (φ : ContinuousMonoidHom Γ G)
    (hφ : Function.Surjective φ) :
    Subgroup.closure (Set.range (φ ∘ x) ∪ Set.range (φ ∘ y) ∪ Set.range (φ ∘ σ)) = ⊤ := by
  set G' := Subgroup.closure (Set.range (φ ∘ x) ∪ Set.range (φ ∘ y) ∪ Set.range (φ ∘ σ))
  have hx : ∀ i, (φ ∘ x) i ∈ G' := fun i ↦ Subgroup.subset_closure (Or.inl (Or.inl ⟨i, rfl⟩))
  have hy : ∀ i, (φ ∘ y) i ∈ G' := fun i ↦ Subgroup.subset_closure (Or.inl (Or.inr ⟨i, rfl⟩))
  have hσ : ∀ j, (φ ∘ σ) j ∈ G' := fun j ↦ Subgroup.subset_closure (Or.inr ⟨j, rfl⟩)
  let x' : Fin g → G' := fun i ↦ ⟨_, hx i⟩
  let y' : Fin g → G' := fun i ↦ ⟨_, hy i⟩
  let σ' : Fin n → G' := fun j ↦ ⟨_, hσ j⟩
  have hrel : surfaceWord x' y' σ' = 1 := by
    apply Subtype.ext
    rw [← Subgroup.coe_subtype, map_surfaceWord]
    change surfaceWord (φ ∘ x) (φ ∘ y) (φ ∘ σ) = 1
    rw [← map_surfaceWord]
    have h1 := proLKernel_le_ker hG φ.toMonoidHom φ.continuous h.1
    exact h1
  obtain ⟨ψ, hψx, hψy, hψσ⟩ :=
    (h.2 G' (hG.of_injective G'.subtype G'.subtype_injective)).2 x' y' σ' hrel
  let ψ' : ContinuousMonoidHom Γ G :=
    ⟨G'.subtype.comp ψ.toMonoidHom, continuous_subtype_val.comp ψ.continuous⟩
  have heq : ψ' = φ := (h.2 G hG).1 ψ' φ
    (funext fun i ↦ congrArg Subtype.val (congrFun hψx i))
    (funext fun i ↦ congrArg Subtype.val (congrFun hψy i))
    (funext fun j ↦ congrArg Subtype.val (congrFun hψσ j))
  refine eq_top_iff.mpr fun z _ ↦ ?_
  obtain ⟨γ, rfl⟩ := hφ z
  rw [← heq]
  exact (ψ γ).2

/-- XIII.2.12 ⇒ XIII.2.13 (necessary condition): if the `xᵢ, yᵢ, σⱼ` present `Γ^L` with `n ≥ 1`
(at least one point removed), every finite continuous quotient `G` of `Γ` which is an `L`-group is
generated by `2g + n - 1` elements: `σ_n` is a word in the other generators by (*). -/
theorem exists_finset_card_le_closure_eq_top_of_isProLSurfaceGroup {x y : Fin g → Γ}
    {σ : Fin n → Γ} (h : IsProLSurfaceGroup.{u} L x y σ) (hn : 1 ≤ n) {G : Type u} [Group G]
    [TopologicalSpace G] [DiscreteTopology G] (hG : IsLGroup L G) (φ : ContinuousMonoidHom Γ G)
    (hφ : Function.Surjective φ) :
    ∃ s : Finset G, s.card ≤ 2 * g + n - 1 ∧ Subgroup.closure (s : Set G) = ⊤ := by
  classical
  obtain ⟨m, rfl⟩ : ∃ m, n = m + 1 := ⟨n - 1, by omega⟩
  have hgen := h.closure_eq_top hG φ hφ
  have hrel : surfaceWord (φ ∘ x) (φ ∘ y) (φ ∘ σ) = 1 := by
    rw [← map_surfaceWord]
    exact proLKernel_le_ker hG φ.toMonoidHom φ.continuous h.1
  let s : Finset G := Finset.univ.image (φ ∘ x) ∪ Finset.univ.image (φ ∘ y) ∪
    Finset.univ.image (fun j : Fin m ↦ φ (σ (Fin.castSucc j)))
  refine ⟨s, ?_, ?_⟩
  · refine (Finset.card_union_le _ _).trans ?_
    refine (add_le_add (Finset.card_union_le _ _) Finset.card_image_le).trans ?_
    refine (add_le_add (add_le_add Finset.card_image_le Finset.card_image_le) le_rfl).trans ?_
    simp only [Finset.card_univ, Fintype.card_fin]
    omega
  · -- the last generator `σ_n` lies in the subgroup generated by the others, by (*)
    rw [eq_top_iff, ← hgen, Subgroup.closure_le]
    have hs : ∀ z ∈ (s : Set G), z ∈ Subgroup.closure (s : Set G) :=
      fun z hz ↦ Subgroup.subset_closure hz
    have hlast : φ (σ (Fin.last m)) ∈ Subgroup.closure (s : Set G) := by
      have hw : surfaceWord (φ ∘ x) (φ ∘ y) (φ ∘ σ) =
          (List.ofFn fun i ↦ φ (x i) * φ (y i) * (φ (x i))⁻¹ * (φ (y i))⁻¹).prod *
            (List.ofFn fun j : Fin m ↦ φ (σ (Fin.castSucc j))).prod * φ (σ (Fin.last m)) := by
        simp only [surfaceWord, Function.comp_apply, List.ofFn_succ', List.prod_concat,
          mul_assoc]
      rw [hw] at hrel
      have hA : (List.ofFn fun i ↦ φ (x i) * φ (y i) * (φ (x i))⁻¹ * (φ (y i))⁻¹).prod ∈
          Subgroup.closure (s : Set G) := by
        refine (Subgroup.closure (s : Set G)).list_prod_mem fun z hz ↦ ?_
        obtain ⟨i, rfl⟩ := List.mem_ofFn.mp hz
        have hxi : φ (x i) ∈ Subgroup.closure (s : Set G) :=
          hs _ (by simp [s])
        have hyi : φ (y i) ∈ Subgroup.closure (s : Set G) :=
          hs _ (by simp [s])
        exact Subgroup.mul_mem _ (Subgroup.mul_mem _ (Subgroup.mul_mem _ hxi hyi)
          (Subgroup.inv_mem _ hxi)) (Subgroup.inv_mem _ hyi)
      have hB : (List.ofFn fun j : Fin m ↦ φ (σ (Fin.castSucc j))).prod ∈
          Subgroup.closure (s : Set G) := by
        refine (Subgroup.closure (s : Set G)).list_prod_mem fun z hz ↦ ?_
        obtain ⟨j, rfl⟩ := List.mem_ofFn.mp hz
        exact hs _ (by simp [s])
      have : φ (σ (Fin.last m)) = ((List.ofFn fun i ↦ φ (x i) * φ (y i) * (φ (x i))⁻¹ *
          (φ (y i))⁻¹).prod * (List.ofFn fun j : Fin m ↦ φ (σ (Fin.castSucc j))).prod)⁻¹ :=
        eq_inv_of_mul_eq_one_right (by rw [mul_assoc]; rwa [mul_assoc] at hrel)
      rw [this]
      exact Subgroup.inv_mem _ (Subgroup.mul_mem _ hA hB)
    rintro z ((⟨i, rfl⟩ | ⟨i, rfl⟩) | ⟨j, rfl⟩)
    · exact hs _ (by simp [s])
    · exact hs _ (by simp [s])
    · obtain ⟨j, rfl⟩ | rfl := Fin.eq_castSucc_or_eq_last j
      · exact hs _ (by simp [s])
      · exact hlast

omit [TopologicalSpace Γ] in
/-- The closure of `closure A ⊔ B` is the closure of `A ⊔ B`. -/
lemma topologicalClosure_topologicalClosure_sup {G : Type*} [Group G] [TopologicalSpace G]
    [IsTopologicalGroup G] (A B : Subgroup G) :
    (A.topologicalClosure ⊔ B).topologicalClosure = (A ⊔ B).topologicalClosure := by
  refine le_antisymm (Subgroup.topologicalClosure_minimal _ (sup_le ?_ ?_)
    (Subgroup.isClosed_topologicalClosure _)) (Subgroup.topologicalClosure_mono
      (sup_le_sup_right A.le_topologicalClosure B))
  · exact Subgroup.topologicalClosure_mono le_sup_left
  · exact le_sup_right.trans (Subgroup.le_topologicalClosure _)

omit [TopologicalSpace Γ] in
/-- If `closure (H ⊔ K) = closure (A ⊔ K)` and `K ≤ K'`, then `closure (H ⊔ K') = closure (A ⊔ K')`
(passing from `π₁^tame` to a quotient of it). -/
lemma topologicalClosure_sup_eq_of_le {G : Type*} [Group G] [TopologicalSpace G]
    [IsTopologicalGroup G] {H A K K' : Subgroup G} (h : (H ⊔ K).topologicalClosure =
      (A ⊔ K).topologicalClosure) (hK : K ≤ K') :
    (H ⊔ K').topologicalClosure = (A ⊔ K').topologicalClosure := by
  have e₁ : H ⊔ K' = H ⊔ K ⊔ K' := by rw [sup_assoc, sup_eq_right.mpr hK]
  have e₂ : A ⊔ K' = A ⊔ K ⊔ K' := by rw [sup_assoc, sup_eq_right.mpr hK]
  rw [e₁, e₂, ← topologicalClosure_topologicalClosure_sup (H ⊔ K),
    ← topologicalClosure_topologicalClosure_sup (A ⊔ K), h]

end GroupTheory

/-- XIII.2.12 implies its "in other words" form `TameCurvePrimeToPStatement`, given that the
Galois coverings of `U` of degree prime to `p` are tamely ramified, i.e. that the kernel of
`π₁(U) → π₁^tame(U)` lies in that of `π₁(U) → π₁^{p'}(U)` (`PrimeToPCoveringsTameStatement`,
XIII.2.3 b); a non-Galois covering of degree prime to `p` need not be tame): the presentation of
`π₁^tame(U)` passes to its quotient `π₁^{p'}(U)`. -/
theorem tameCurvePrimeToPStatement_of_tameCurveFundamentalGroupStatement
    (h : TameCurveFundamentalGroupStatement.{u}) (hA : PrimeToPCoveringsTameStatement.{u}) :
    TameCurvePrimeToPStatement.{u} := by
  intro k _ _ X f _ _ _ g n hg a ha hac U hU Ω _ _ ξ
  obtain ⟨x, y, σ, h1, h2, h3, h4⟩ := h k X f g n hg a ha hac U hU Ω ξ
  have hKK' := hA k X f U (by rw [hU, compl_compl]; exact Set.finite_range a) Ω ξ
  refine ⟨x, y, σ, ⟨hKK' h1, fun G _ _ _ hG ↦ ⟨fun φ ψ hx hy hσ ↦ ?_, fun x' y' σ' hrel ↦ ?_⟩⟩,
    fun j ↦ ?_⟩
  · -- uniqueness: `φ` and `ψ` agree on a closed subgroup containing a dense subgroup
    have hker (χ : ContinuousMonoidHom (ExposeV.etaleFundamentalGroup Ω ξ) G) :
        tameKernel f U ξ ≤ (χ : ExposeV.etaleFundamentalGroup Ω ξ →* G).ker :=
      hKK'.trans (proLKernel_le_ker hG _ χ.continuous)
    let E := (φ : ExposeV.etaleFundamentalGroup Ω ξ →* G).eqLocus ψ
    have hE : Subgroup.closure (Set.range x ∪ Set.range y ∪ Set.range σ) ⊔ tameKernel f U ξ ≤
        E := by
      refine sup_le ((Subgroup.closure_le E).mpr ?_) fun γ hγ ↦ ?_
      · rintro _ ((⟨i, rfl⟩ | ⟨i, rfl⟩) | ⟨j, rfl⟩)
        · exact congrFun hx i
        · exact congrFun hy i
        · exact congrFun hσ j
      · have h₁ : φ γ = 1 := (MonoidHom.mem_ker).mp (hker φ hγ)
        have h₂ : ψ γ = 1 := (MonoidHom.mem_ker).mp (hker ψ hγ)
        change φ γ = ψ γ
        rw [h₁, h₂]
    have hEc : IsClosed (E : Set (ExposeV.etaleFundamentalGroup Ω ξ)) :=
      isClosed_eq φ.continuous ψ.continuous
    ext γ
    have hγ : γ ∈ closure ((Subgroup.closure (Set.range x ∪ Set.range y ∪ Set.range σ) ⊔
        tameKernel f U ξ : Subgroup _) : Set (ExposeV.etaleFundamentalGroup Ω ξ)) := by
      rw [h2.closure_eq]
      trivial
    have : γ ∈ closure (E : Set (ExposeV.etaleFundamentalGroup Ω ξ)) := closure_mono hE hγ
    rw [hEc.closure_eq] at this
    exact this
  · -- existence: apply XIII.2.12 to the subgroup generated by the `x'ᵢ, y'ᵢ, σ'ⱼ`
    set S := Set.range x' ∪ Set.range y' ∪ Set.range σ'
    let G' := Subgroup.closure S
    have hx : ∀ i, x' i ∈ G' := fun i ↦ Subgroup.subset_closure (Or.inl (Or.inl ⟨i, rfl⟩))
    have hy : ∀ i, y' i ∈ G' := fun i ↦ Subgroup.subset_closure (Or.inl (Or.inr ⟨i, rfl⟩))
    have hσ : ∀ j, σ' j ∈ G' := fun j ↦ Subgroup.subset_closure (Or.inr ⟨j, rfl⟩)
    let x'' : Fin g → G' := fun i ↦ ⟨_, hx i⟩
    let y'' : Fin g → G' := fun i ↦ ⟨_, hy i⟩
    let σ'' : Fin n → G' := fun j ↦ ⟨_, hσ j⟩
    have hrel' : surfaceWord x'' y'' σ'' = 1 := by
      apply Subtype.ext
      rw [← Subgroup.coe_subtype, map_surfaceWord]
      exact hrel
    have hgen' : Subgroup.closure (Set.range x'' ∪ Set.range y'' ∪ Set.range σ'') = ⊤ := by
      have : Set.range x'' ∪ Set.range y'' ∪ Set.range σ'' = ((↑) : G' → G) ⁻¹' S := by
        ext z
        simp only [Set.mem_union, Set.mem_range, Set.mem_preimage, S, x'', y'', σ'']
        constructor
        · rintro ((⟨i, rfl⟩ | ⟨i, rfl⟩) | ⟨j, rfl⟩)
          · exact Or.inl (Or.inl ⟨i, rfl⟩)
          · exact Or.inl (Or.inr ⟨i, rfl⟩)
          · exact Or.inr ⟨j, rfl⟩
        · rintro ((⟨i, hi⟩ | ⟨i, hi⟩) | ⟨j, hj⟩)
          · exact Or.inl (Or.inl ⟨i, Subtype.ext hi⟩)
          · exact Or.inl (Or.inr ⟨i, Subtype.ext hi⟩)
          · exact Or.inr ⟨j, Subtype.ext hj⟩
      rw [this]
      exact Subgroup.closure_closure_coe_preimage
    obtain ⟨φ, -, hφx, hφy, hφσ⟩ :=
      h4 G' (hG.of_injective G'.subtype G'.subtype_injective) x'' y'' σ'' hrel' hgen'
    refine ⟨⟨G'.subtype.comp φ.toMonoidHom, continuous_subtype_val.comp φ.continuous⟩, ?_, ?_, ?_⟩
    · exact funext fun i ↦ congrArg Subtype.val (congrFun hφx i)
    · exact funext fun i ↦ congrArg Subtype.val (congrFun hφy i)
    · exact funext fun j ↦ congrArg Subtype.val (congrFun hφσ j)
  · obtain ⟨Ω₀, _, _, xb, H, hxb, hH, hHσ⟩ := h3 j
    exact ⟨Ω₀, _, _, xb, H, hxb, hH, topologicalClosure_sup_eq_of_le hHσ hKK'⟩

end SGA.SGA1.ExposeXIII
