/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.Foundations.StrictLocalization
import SGA.SGA1.ExposeV.FundamentalGroupBasePoint
import SGA.SGA1.ExposeXIII.NormalCrossings
import SGA.SGA1.ExposeXIII.SchemeFundamentalGroup

/-!
# SGA 1, Exposé XIII, 2.12: the notions in the fundamental group of a curve

XIII.2.12 describes the tame fundamental group of a smooth proper connected curve `X` of genus
`g` over a separably closed field, minus `n` closed points `a₁, …, a_n`: it is generated by
`2g + n` elements `xᵢ, yᵢ, σⱼ` with the single relation
`∏ᵢ [xᵢ, yᵢ] · ∏ⱼ σⱼ = 1` (`surfaceWord`), `σⱼ` generating an inertia group at `aⱼ`. This file
defines the notions the statement is made of:

* `surfaceWord x y σ`, the word `∏ᵢ xᵢ yᵢ xᵢ⁻¹ yᵢ⁻¹ · ∏ⱼ σⱼ` of XIII.2.12 (*);
* `IsProLSurfaceGroup L x y σ`: the elements `xᵢ, yᵢ, σⱼ` of a topological group `Γ` present the
  maximal pro-`L` quotient `Γ^L` (XIII.2.10.0) as the pro-`L` completion of
  `⟨xᵢ, yᵢ, σⱼ | (*)⟩`, through its universal property on finite `L`-groups (the "in other words"
  of XIII.2.12);
* `IsInertiaSubgroupAt U x̄ ξ H`: `H` is an inertia subgroup of `π₁(U, ξ)` at the geometric point
  `x̄` of `X` (as in the proof of XIII.2.11): the image of `π₁(U ×_X X̃)`, `X̃` the strict
  localization of `X` at `x̄`, transported to the base point `ξ` along a path (V.7);
* `tameKernel p U ξ`: the kernel of `π₁(U, ξ) → π₁^tame(U, ξ)` (XIII.2.1.3), the intersection of
  the stabilizers of the points of the fibres of the étale coverings of `U` tamely ramified along
  `X - U` relative to `p : X ⟶ S` (XIII.2.1.1, `IsTamelyRamifiedCovering`).
-/

universe u w

open CategoryTheory Limits AlgebraicGeometry

namespace SGA.SGA1.ExposeXIII

section SurfaceWord

variable {G H : Type*} [Group G] [Group H] {g n : ℕ}

/-- The word `∏ᵢ [xᵢ, yᵢ] · ∏ⱼ σⱼ = ∏ᵢ xᵢ yᵢ xᵢ⁻¹ yᵢ⁻¹ · ∏ⱼ σⱼ` of the relation XIII.2.12 (*),
the products taken in increasing order of the indices. -/
def surfaceWord (x y : Fin g → G) (σ : Fin n → G) : G :=
  (List.ofFn fun i ↦ x i * y i * (x i)⁻¹ * (y i)⁻¹).prod * (List.ofFn σ).prod

lemma map_surfaceWord {F : Type*} [FunLike F G H] [MonoidHomClass F G H] (φ : F)
    (x y : Fin g → G) (σ : Fin n → G) :
    φ (surfaceWord x y σ) = surfaceWord (φ ∘ x) (φ ∘ y) (φ ∘ σ) := by
  simp [surfaceWord, map_mul, map_list_prod, List.map_ofFn, Function.comp_def]

/-- In genus `0` the relation (*) is `σ₁ ⋯ σ_n = 1`. -/
lemma surfaceWord_genus_zero (x y : Fin 0 → G) (σ : Fin n → G) :
    surfaceWord x y σ = (List.ofFn σ).prod := by
  simp [surfaceWord]

/-- Without points removed the relation (*) is `∏ᵢ [xᵢ, yᵢ] = 1`. -/
lemma surfaceWord_zero_points (x y : Fin g → G) (σ : Fin 0 → G) :
    surfaceWord x y σ = (List.ofFn fun i ↦ x i * y i * (x i)⁻¹ * (y i)⁻¹).prod := by
  simp [surfaceWord]

end SurfaceWord

section ProLSurfaceGroup

variable (L : Set ℕ) {Γ : Type*} [Group Γ] [TopologicalSpace Γ] {g n : ℕ}

/-- XIII.2.12, "in other words": the elements `xᵢ, yᵢ, σⱼ` of the topological group `Γ` present
its maximal pro-`L` quotient `Γ^L = Γ / proLKernel L Γ` (XIII.2.10.0) as the pro-`L` group
generated by `xᵢ, yᵢ, σⱼ` bound by the single relation (*), i.e. as the pro-`L` completion of
`⟨xᵢ, yᵢ, σⱼ | ∏ᵢ [xᵢ, yᵢ] ∏ⱼ σⱼ⟩`. This is stated through the universal property on finite
`L`-groups `G` (with values in `Type w`): the relation holds in `Γ^L`; a continuous homomorphism
`Γ → G` is determined by the images of the `xᵢ, yᵢ, σⱼ` (they generate `Γ^L` topologically); and
every family `x'ᵢ, y'ᵢ, σ'ⱼ` of `G` satisfying (*) is the image of `xᵢ, yᵢ, σⱼ` under some
continuous homomorphism. -/
def IsProLSurfaceGroup (x y : Fin g → Γ) (σ : Fin n → Γ) : Prop :=
  surfaceWord x y σ ∈ proLKernel L Γ ∧
    ∀ (G : Type w) [Group G] [TopologicalSpace G] [DiscreteTopology G], IsLGroup L G →
      (∀ φ ψ : ContinuousMonoidHom Γ G,
        ⇑φ ∘ x = ⇑ψ ∘ x → ⇑φ ∘ y = ⇑ψ ∘ y → ⇑φ ∘ σ = ⇑ψ ∘ σ → φ = ψ) ∧
      ∀ (x' y' : Fin g → G) (σ' : Fin n → G), surfaceWord x' y' σ' = 1 →
        ∃ φ : ContinuousMonoidHom Γ G, ⇑φ ∘ x = x' ∧ ⇑φ ∘ y = y' ∧ ⇑φ ∘ σ = σ'

end ProLSurfaceGroup

section Inertia

variable {X : Scheme.{u}}

/-- XIII.2.11 (proof), XIII.2.12: `H` is an *inertia subgroup* of `π₁(U, ξ)` at the geometric
point `x̄ : Spec Ω₀ ⟶ X` (`Ω₀` separably closed): with `X̃ = Spec 𝒪^{sh}_{X,x̄}` the strict
localization of `X` at `x̄` (`Scheme.Hom.fromSpecStrictLocalization`), `H` is the image of
`π₁(U ×_X X̃, η) → π₁(U, η)` for some geometric point `η` of `U ×_X X̃`, transported to the base
point `ξ` along a path from `η` to `ξ` (V.7,
`ExposeV.etaleFundamentalGroup.continuousMulEquivOfPath`).
In SGA the inertia groups at `x̄` are defined up to conjugation by this choice. SGA takes the
inertia group in `π₁^tame(U)` to be the image of `π₁^tame(U ×_X X̃)`; here `H` is the image of
`π₁(U ×_X X̃)` in `π₁(U)`, read modulo `tameKernel` in `TameCurveFundamentalGroupStatement`
(or modulo `proLKernel` in `TameCurvePrimeToPStatement`). The two agree: `π₁(U ×_X X̃) →
π₁^tame(U ×_X X̃)` is onto, and tamely ramified coverings of `U` pull back to tamely ramified
coverings of `U ×_X X̃`. -/
def IsInertiaSubgroupAt (U : X.Opens) {Ω₀ : Type u} [Field Ω₀] [IsSepClosed Ω₀]
    (xb : Spec (.of Ω₀) ⟶ X) {Ω : Type u} [Field Ω] [IsSepClosed Ω]
    (ξ : Spec (.of Ω) ⟶ (U : Scheme.{u}))
    (H : Subgroup (ExposeV.etaleFundamentalGroup Ω ξ)) : Prop :=
  ∃ (Ω' : Type u) (_ : Field Ω') (_ : IsSepClosed Ω')
    (η : Spec (.of Ω') ⟶ pullback U.ι xb.fromSpecStrictLocalization)
    (γ : ExposeV.etalePaths Ω' Ω (η ≫ pullback.fst U.ι xb.fromSpecStrictLocalization) ξ),
    H = (ExposeV.etaleFundamentalGroup.map Ω' (pullback.fst U.ι xb.fromSpecStrictLocalization)
      η).range.map (ExposeV.etaleFundamentalGroup.continuousMulEquivOfPath Ω' Ω γ).toMonoidHom

end Inertia

section Tame

variable {X S : Scheme.{u}}

/-- XIII.2.1.3: the kernel of `π₁(U, ξ) → π₁^tame(U, ξ)`, where `π₁^tame(U)` classifies the
étale coverings of `U` tamely ramified along `X - U` relative to `p : X ⟶ S` (XIII.2.1.1,
`IsTamelyRamifiedCovering`): the intersection of the stabilizers of the points of the fibres at
`ξ` of these coverings. -/
noncomputable def tameKernel (p : X ⟶ S) (U : X.Opens) {Ω : Type u} [Field Ω] [IsSepClosed Ω]
    (ξ : Spec (.of Ω) ⟶ (U : Scheme.{u})) :
    Subgroup (ExposeV.etaleFundamentalGroup Ω ξ) :=
  ⨅ (E : ExposeV.FEt (U : Scheme.{u}))
    (_ : haveI : Etale E.hom := E.prop.2
      IsTamelyRamifiedCovering p ((U : Set X)ᶜ) U (Scheme.Etale.mk E.hom)),
    ⨅ (s : ((ExposeV.FEt.fiber Ω ξ).obj E : Type u)), MulAction.stabilizer _ s

lemma tameKernel_le_stabilizer (p : X ⟶ S) (U : X.Opens) {Ω : Type u} [Field Ω]
    [IsSepClosed Ω] (ξ : Spec (.of Ω) ⟶ (U : Scheme.{u})) (E : ExposeV.FEt (U : Scheme.{u}))
    (hE : haveI : Etale E.hom := E.prop.2
      IsTamelyRamifiedCovering p ((U : Set X)ᶜ) U (Scheme.Etale.mk E.hom))
    (s : ((ExposeV.FEt.fiber Ω ξ).obj E : Type u)) :
    tameKernel p U ξ ≤ MulAction.stabilizer _ s :=
  (iInf_le_of_le E (iInf_le_of_le hE (iInf_le _ s)))

end Tame

end SGA.SGA1.ExposeXIII
