/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.SGA1.ExposeXIII.AbhyankarPurity

/-!
# SGA 1, XIII.4.6 in characteristic `0`: Abhyankar's lemma at a boundary point of a curve

The curve case of the resolution-free route to XIII.4.6 in characteristic `0`
(`AffineLineOpenInvarianceStatement`) extends an étale covering of an open subset of a smooth
curve, pulled back to a Kummer covering, across the missing points: by purity
(`SGA.SGA1.ExposeX.finite_etale_fromNormalization_of_isRegularScheme`) it suffices that the
normalization be étale over the local rings at those points, and this is Abhyankar's lemma
(XIII.5.2 in dimension one, `etale_integralClosure_of_dvd`). This file proves the local
statement in the form needed there, for a residue field of characteristic `0` (so that all
extensions are tamely ramified) and an *abstract* normalization `S'` of the base discrete
valuation ring in the function field `K'` of the curve:

* `dvd_ramificationIdx_of_pow_eq`: if `K'` contains an `N`-th root of `π u` (`π` a uniformizer of
  the discrete valuation ring `R`, `u` a unit), every prime of the normalization of `R` in `K'`
  over the maximal ideal has ramification index divisible by `N`;
* `ramificationIdx_le_finrank_of_isDiscreteValuationRing`: ramification indices are at most the
  degree;
* `etale_integralClosure_of_pow_eq` (XIII.5.2, dimension one, residue characteristic `0`): with
  `K'` as above, `B` a finite étale `K`-algebra of degree at most `d` and `1, …, d ∣ N`, the
  normalization of `S'` in any `K'`-algebra generated by the image of `B` is finite étale over
  `S'`;
* `isEtaleAt_integralClosure_of_pow_eq_mul`: the same on an affine chart `Spec S` of the curve,
  finite over `𝔸¹ = Spec k[X]` (`k` algebraically closed of characteristic `0`), at the
  height-one primes over the zeros of a polynomial `g₀`: this is the hypothesis of the purity
  theorem on that chart. The roots `y` of `X - b` (up to a unit) are given in the function field.
-/

universe u

open IsLocalRing Polynomial
open scoped TensorProduct

namespace SGA.SGA1.ExposeXIII

variable (R : Type*) [CommRing R] [IsDomain R] [IsDiscreteValuationRing R] {K : Type*} [Field K]
  [Algebra R K] [IsFractionRing R K]

/-- Ramification in a Kummer extension: let `R` be a discrete valuation ring with fraction field
`K`, `π` a uniformizer, `u` a unit and `K'` a finite separable extension of `K` containing `y`
with `y ^ N = π u`. Then `N` divides the ramification index of every prime of the normalization of
`R` in `K'` over the maximal ideal (`π = y ^ N u⁻¹` in it). -/
theorem dvd_ramificationIdx_of_pow_eq {K' : Type*} [Field K'] [Algebra K K'] [Algebra R K']
    [IsScalarTower R K K'] [FiniteDimensional K K'] [Algebra.IsSeparable K K']
    {π : R} (hπ : Irreducible π) {N : ℕ} (u : Rˣ) (y : K')
    (hy : y ^ N = algebraMap R K' (π * u))
    (Q' : Ideal (integralClosure R K')) [Q'.IsPrime] [Q'.LiesOver (maximalIdeal R)] :
    N ∣ Q'.ramificationIdx R := by
  classical
  have := integralClosure.isDedekindDomain' R K K'
  have hinj : Function.Injective (algebraMap R K') := by
    rw [IsScalarTower.algebraMap_eq R K K']
    exact (algebraMap K K').injective.comp (IsFractionRing.injective R K)
  have hN : N ≠ 0 := by
    rintro rfl
    rw [pow_zero, ← map_one (algebraMap R K')] at hy
    exact hπ.not_isUnit (isUnit_of_mul_isUnit_left ((hinj hy) ▸ isUnit_one))
  have hyi : IsIntegral R y := by
    refine ⟨X ^ N - C (π * u), monic_X_pow_sub_C _ hN, ?_⟩
    rw [eval₂_sub, eval₂_X_pow, eval₂_C, hy, sub_self]
  set y' : integralClosure R K' := ⟨y, hyi⟩
  have hy' : algebraMap R (integralClosure R K') π =
      y' ^ N * algebraMap R (integralClosure R K') (↑u⁻¹ : R) := by
    apply Subtype.ext
    change algebraMap R K' π = y ^ N * algebraMap R K' (↑u⁻¹ : R)
    rw [hy, ← map_mul, mul_assoc, Units.mul_inv, mul_one]
  have hmax : maximalIdeal R = Ideal.span {π} :=
    (IsDiscreteValuationRing.irreducible_iff_uniformizer π).mp hπ
  have hmap : (maximalIdeal R).map (algebraMap R (integralClosure R K')) =
      Ideal.span {y'} ^ N := by
    rw [hmax, Ideal.map_span, Set.image_singleton, hy', Ideal.span_singleton_pow,
      Ideal.span_singleton_mul_right_unit ((u⁻¹).isUnit.map _)]
  have hy0 : y' ≠ 0 := by
    intro h0
    have : y = 0 := congrArg Subtype.val h0
    rw [this, zero_pow hN, ← map_zero (algebraMap R K')] at hy
    exact (mul_ne_zero hπ.ne_zero u.ne_zero) (hinj hy).symm
  have hp0 : (maximalIdeal R).map (algebraMap R (integralClosure R K')) ≠ ⊥ := by
    rw [hmap]
    exact pow_ne_zero _ (by simpa using hy0)
  rw [Ideal.IsDedekindDomain.ramificationIdx_eq_normalizedFactors_count (maximalIdeal R) Q' hp0,
    hmap, UniqueFactorizationMonoid.normalizedFactors_pow, Multiset.count_nsmul]
  exact dvd_mul_right _ _

/-- The ramification index of a prime of the normalization of a discrete valuation ring `R` in a
finite separable extension `L` of its fraction field is at most `[L : K]` (`∑ e f = [L : K]`). -/
theorem ramificationIdx_le_finrank_of_isDiscreteValuationRing (L : Type*) [Field L] [Algebra K L]
    [Algebra R L] [IsScalarTower R K L] [FiniteDimensional K L] [Algebra.IsSeparable K L]
    (Q : Ideal (integralClosure R L)) [Q.IsPrime] [Q.LiesOver (maximalIdeal R)] :
    Q.ramificationIdx R ≤ Module.finrank K L := by
  classical
  have := integralClosure.finite R K L
  have := integralClosure.flat R K L
  have := integralClosure.isDedekindDomain' R K L
  have h := Ideal.sum_ramification_inertia_eq_finrank (maximalIdeal R) (integralClosure R L)
  have : Module.IsTorsionFree R L := by
    rw [Module.isTorsionFree_iff_algebraMap_injective, IsScalarTower.algebraMap_eq R K L]
    exact (algebraMap K L).injective.comp (IsFractionRing.injective R K)
  rw [IsIntegralClosure.rank R K L (integralClosure R L)] at h
  rw [← h]
  have hQ : Q ∈ (maximalIdeal R).primesOver (integralClosure R L) := ⟨inferInstance, inferInstance⟩
  calc Q.ramificationIdx R ≤ Q.ramificationIdx R * Q.inertiaDeg R :=
        Nat.le_mul_of_pos_right _ (Ideal.inertiaDeg_pos Q R)
    _ ≤ _ := Finset.single_le_sum (s := Finset.univ)
        (f := fun q : (maximalIdeal R).primesOver (integralClosure R L) ↦
          q.1.ramificationIdx R * q.1.inertiaDeg R) (fun _ _ ↦ Nat.zero_le _)
        (Finset.mem_univ ⟨Q, hQ⟩)

/-- XIII.5.2 in dimension one, residue characteristic `0`, for an abstract normalization: let `R`
be a discrete valuation ring with fraction field `K` and residue field of characteristic `0`,
`π` a uniformizer, `u` a unit, `K'` a finite separable extension of `K` containing an `N`-th root
`y` of `π u`, and `S'` the normalization of `R` in `K'` (`IsIntegralClosure S' R K'`). Let `B` be
a finite étale `K`-algebra such that every `m` with `0 < m ≤ [B : K]` divides `N`, and `C'` a
`K'`-algebra (and `S'`-algebra) generated over `K'` by the image of a ring map `β : B → C'` over
`K → K'`. Then the normalization of `S'` in `C'` is finite étale over `S'`.

Each factor `F` of `C'` is a composite of `K'` and a factor `L` of `B`; the ramification indices
of `L` are at most `[B : K]`, hence divide `N`, which divides those of `K'`
(`dvd_ramificationIdx_of_pow_eq`), so `etale_integralClosure_of_dvd` applies (tameness is
automatic in residue characteristic `0`). -/
theorem etale_integralClosure_of_pow_eq (hR : ringChar (ResidueField R) = 0)
    {K' : Type*} [Field K'] [Algebra K K'] [Algebra R K'] [IsScalarTower R K K']
    [FiniteDimensional K K'] [Algebra.IsSeparable K K']
    {π : R} (hπ : Irreducible π) (N : ℕ) (u : Rˣ) (y : K')
    (hy : y ^ N = algebraMap R K' (π * u))
    (S' : Type*) [CommRing S'] [Algebra R S'] [Algebra S' K'] [IsScalarTower R S' K']
    [IsIntegralClosure S' R K']
    (B : Type*) [CommRing B] [Algebra K B] [Module.Finite K B] [Algebra.Etale K B]
    (hB : ∀ m, 0 < m → m ≤ Module.finrank K B → m ∣ N)
    (C' : Type*) [CommRing C'] [Algebra K' C'] [Algebra S' C'] [IsScalarTower S' K' C']
    (β : B →+* C') (hβ : ∀ a : K, β (algebraMap K B a) = algebraMap K' C' (algebraMap K K' a))
    (hgen : ∀ c : C', c ∈ Algebra.adjoin K' (Set.range β)) :
    Module.Finite S' (integralClosure S' C') ∧ Algebra.Etale S' (integralClosure S' C') := by
  classical
  -- the structures over `K` and `R`
  let : Algebra K C' := ((algebraMap K' C').comp (algebraMap K K')).toAlgebra
  let : Algebra R C' := ((algebraMap K' C').comp (algebraMap R K')).toAlgebra
  have : IsScalarTower K K' C' := .of_algebraMap_eq fun _ ↦ rfl
  have : IsScalarTower R K' C' := .of_algebraMap_eq fun _ ↦ rfl
  have : IsScalarTower R K C' := .of_algebraMap_eq fun r ↦
    congrArg (algebraMap K' C') (IsScalarTower.algebraMap_apply R K K' r)
  let : Algebra R B := ((algebraMap K B).comp (algebraMap R K)).toAlgebra
  have : IsScalarTower R K B := .of_algebraMap_eq fun _ ↦ rfl
  let βK : B →ₐ[K] C' := { β with commutes' := hβ }
  -- `C'` is a quotient of `K' ⊗_K B`, hence finite étale over `K'`
  have : Algebra.FormallyEtale K K' := Algebra.FormallyEtale.of_isSeparable K K'
  have : Algebra.FinitePresentation K K' :=
    Algebra.FinitePresentation.of_finiteType.mp inferInstance
  have : Algebra.Etale K K' := ⟨inferInstance, inferInstance⟩
  have : Algebra.Etale K' (K' ⊗[K] B) := inferInstance
  have : Module.Finite K' (K' ⊗[K] B) := inferInstance
  let Λ : K' ⊗[K] B →ₐ[K'] C' :=
    Algebra.TensorProduct.lift (Algebra.ofId K' C') βK fun _ _ ↦ Commute.all _ _
  have hΛ : Function.Surjective Λ := by
    intro c
    induction hgen c using Algebra.adjoin_induction with
    | mem x hx =>
      obtain ⟨b, rfl⟩ := hx
      exact ⟨1 ⊗ₜ b, by simp [Λ, βK]⟩
    | algebraMap a => exact ⟨a ⊗ₜ 1, by simp [Λ]⟩
    | add x y _ _ hx hy =>
      obtain ⟨x', rfl⟩ := hx
      obtain ⟨y', rfl⟩ := hy
      exact ⟨x' + y', map_add _ _ _⟩
    | mul x y _ _ hx hy =>
      obtain ⟨x', rfl⟩ := hx
      obtain ⟨y', rfl⟩ := hy
      exact ⟨x' * y', map_mul _ _ _⟩
  have : Algebra.FormallyUnramified K' C' := Algebra.FormallyUnramified.of_surjective Λ hΛ
  have : Module.Finite K' C' := Module.Finite.of_surjective Λ.toLinearMap hΛ
  have : Algebra.FormallyUnramified K C' := Algebra.FormallyUnramified.comp K K' C'
  have : Module.Finite K C' := Module.Finite.trans K' C'
  have : IsArtinianRing C' := IsArtinianRing.of_finite K' C'
  have : IsReduced C' := Algebra.FormallyUnramified.isReduced_of_field K' C'
  have : IsArtinianRing B := IsArtinianRing.of_finite K B
  -- `S'` is the normalization of `R` in `K'`
  have := integralClosure.isDedekindDomain' R K K'
  let σ : S' ≃ₐ[R] integralClosure R K' :=
    IsIntegralClosure.equiv R S' K' (integralClosure R K')
  have hσ (s : S') : ((σ s : integralClosure R K') : K') = algebraMap S' K' s :=
    IsIntegralClosure.algebraMap_equiv R S' K' (integralClosure R K') s
  have : Algebra.IsIntegral R S' := IsIntegralClosure.isIntegral_algebra R K'
  have : IsScalarTower R S' C' := .of_algebraMap_eq fun r ↦ by
    rw [IsScalarTower.algebraMap_apply S' K' C', ← IsScalarTower.algebraMap_apply R S' K']
    rfl
  -- each factor `F` of `C'` is a composite of `K'` and a factor `L` of `B`
  have key (M : MaximalSpectrum C') :
      Module.Finite S' (integralClosure S' (C' ⧸ M.asIdeal)) ∧
        Algebra.FormallyEtale S' (integralClosure S' (C' ⧸ M.asIdeal)) := by
    let := Ideal.Quotient.field M.asIdeal
    let M' : Ideal B := M.asIdeal.comap βK
    have : M'.IsPrime := Ideal.comap_isPrime _ _
    have : M'.IsMaximal := IsArtinianRing.isMaximal_of_isPrime M'
    let := Ideal.Quotient.field M'
    have : Module.Finite K (C' ⧸ M.asIdeal) := Module.Finite.of_surjective
      (Ideal.Quotient.mkₐ K M.asIdeal).toLinearMap Ideal.Quotient.mk_surjective
    have : Algebra.FormallyUnramified K (C' ⧸ M.asIdeal) :=
      Algebra.FormallyUnramified.comp K C' _
    have : Algebra.IsSeparable K (C' ⧸ M.asIdeal) := Algebra.FormallyUnramified.isSeparable K _
    have : Module.Finite K (B ⧸ M') := Module.Finite.of_surjective
      (Ideal.Quotient.mkₐ K M').toLinearMap Ideal.Quotient.mk_surjective
    have : Algebra.FormallyUnramified K (B ⧸ M') := Algebra.FormallyUnramified.comp K B _
    have : Algebra.IsSeparable K (B ⧸ M') := Algebra.FormallyUnramified.isSeparable K _
    let g : (B ⧸ M') →ₐ[K] (C' ⧸ M.asIdeal) := Ideal.quotientMapₐ M.asIdeal βK fun _ h ↦ h
    have hgenF : Algebra.adjoin K (Set.range g ∪
        Set.range (algebraMap K' (C' ⧸ M.asIdeal))) = ⊤ := by
      refine eq_top_iff.mpr ?_
      rintro x -
      obtain ⟨c, rfl⟩ := Ideal.Quotient.mk_surjective x
      obtain ⟨z, rfl⟩ := hΛ c
      induction z using TensorProduct.induction_on with
      | zero => rw [map_zero, map_zero]; exact Subalgebra.zero_mem _
      | tmul a b =>
        have : Λ (a ⊗ₜ b) = algebraMap K' C' a * βK b :=
          Algebra.TensorProduct.lift_tmul _ _ _ _ _
        rw [this, map_mul]
        exact Subalgebra.mul_mem _ (Algebra.subset_adjoin (Or.inr ⟨a, rfl⟩))
          (Algebra.subset_adjoin (Or.inl ⟨Ideal.Quotient.mk M' b, rfl⟩))
      | add x y hx hy => rw [map_add, map_add]; exact Subalgebra.add_mem _ hx hy
    have hdvd : ∀ (Q : Ideal (integralClosure R (B ⧸ M'))) (Q' : Ideal (integralClosure R K')),
        Q.IsPrime → Q.LiesOver (maximalIdeal R) → Q'.IsPrime →
        Q'.LiesOver (maximalIdeal R) → Q.ramificationIdx R ∣ Q'.ramificationIdx R := by
      intro Q Q' _ _ _ _
      have := integralClosure.finite R K (B ⧸ M')
      refine (hB _ (Ideal.ramificationIdx_pos Q R) ?_).trans
        (dvd_ramificationIdx_of_pow_eq R (K := K) hπ u y hy Q')
      exact (ramificationIdx_le_finrank_of_isDiscreteValuationRing R (K := K) (B ⧸ M') Q).trans
        (LinearMap.finrank_le_finrank_of_surjective (f := (Ideal.Quotient.mkₐ K M').toLinearMap)
          Ideal.Quotient.mk_surjective)
    let := integralClosure.algebraOfTower R K' (C' ⧸ M.asIdeal)
    obtain ⟨h1, h2⟩ := etale_integralClosure_of_dvd R (K' := K') (F := C' ⧸ M.asIdeal) g hgenF
      (isTameExtension_of_ringChar_eq_zero R hR _) (isTameExtension_of_ringChar_eq_zero R hR _)
      hdvd
    -- the normalizations of `R` and of `S'` in `F` agree
    let : Algebra S' (integralClosure R (C' ⧸ M.asIdeal)) :=
      (((IsScalarTower.toAlgHom R K' (C' ⧸ M.asIdeal)).mapIntegralClosure).comp
        σ.toAlgHom).toRingHom.toAlgebra
    obtain ⟨h1', h2'⟩ := finite_and_formallyEtale_of_ringEquiv
      (I := integralClosure R K') (W := integralClosure R (C' ⧸ M.asIdeal))
      σ.toRingEquiv (fun _ ↦ rfl)
      h1 inferInstance
    let Z : integralClosure S' (C' ⧸ M.asIdeal) ≃ₐ[S'] integralClosure R (C' ⧸ M.asIdeal) :=
      { toFun x := ⟨x.1, isIntegral_trans (A := S') _ x.2⟩
        invFun z := ⟨z.1, z.2.tower_top⟩
        left_inv _ := rfl
        right_inv _ := rfl
        map_mul' _ _ := rfl
        map_add' _ _ := rfl
        commutes' s := Subtype.ext (by
          change algebraMap S' (C' ⧸ M.asIdeal) s =
            algebraMap K' (C' ⧸ M.asIdeal) ((σ s : integralClosure R K') : K')
          rw [hσ, IsScalarTower.algebraMap_apply S' K' (C' ⧸ M.asIdeal)]) }
    exact ⟨Module.Finite.equiv Z.symm.toLinearEquiv, Algebra.FormallyEtale.of_equiv Z.symm⟩
  have : ∀ M : MaximalSpectrum C', Module.Finite S' (integralClosure S' (C' ⧸ M.asIdeal)) :=
    fun M ↦ (key M).1
  -- the normalization of `S'` in `C'` is the product of the normalizations in the factors
  let Φ := ((IsArtinianRing.equivPi C').restrictScalars S').mapIntegralClosure.trans
    (integralClosure.piAlgEquiv S' (fun M : MaximalSpectrum C' ↦ C' ⧸ M.asIdeal))
  have : Algebra.FormallyEtale S'
      (Π M : MaximalSpectrum C', integralClosure S' (C' ⧸ M.asIdeal)) :=
    (Algebra.FormallyEtale.pi_iff _).mpr fun M ↦ (key M).2
  have : Module.Finite S' (integralClosure S' C') := Module.Finite.equiv Φ.symm.toLinearEquiv
  have : Algebra.FormallyEtale S' (integralClosure S' C') := Algebra.FormallyEtale.of_equiv Φ.symm
  have : IsNoetherianRing S' := IsIntegralClosure.isNoetherianRing R K K' S'
  have : Algebra.FinitePresentation S' (integralClosure S' C') :=
    Algebra.FinitePresentation.of_finiteType.mp inferInstance
  exact ⟨inferInstance, ⟨inferInstance, inferInstance⟩⟩

section Chart

variable {k : Type*} [Field k]

open nonZeroDivisors in
/-- XIII.5.2 in dimension one on an affine chart of a curve over an algebraically closed field `k`
of characteristic `0` (the local hypothesis of the purity theorem
`SGA.SGA1.ExposeX.finite_etale_fromNormalization_of_isRegularScheme`). Let `S` be a normal domain,
finite over `k[X]`, `g₀ ∈ k[X]`, and `D` an `S`-algebra in which `g₀` is a unit. Suppose `D` is
generated over `S` by the image of `ι : W₀ → D`, where `W₀` is a finite étale algebra over
`P₀ = k[X][1/g₀]` (compatibly with `k[X] → S`), every `m` with `0 < m ≤ rank W₀` divides `N`, and
for every root `b` of `g₀` the function field `L` of `S` contains `y` with `y^N u = X - b` for some
`u ∈ k[X]` with `u(b) ≠ 0`. Then the normalization of `S` in `D` is étale over `S` at every prime
`q` lying over a height-one prime of `S` containing `g₀`.

With `p = (X - b)` the prime of `k[X]` below `q`, `R = k[X]_p` is a discrete valuation ring with
uniformizer `π = X - b`, `S_p` is the normalization of `R` in `L`, and over `D_p` this is
`etale_integralClosure_of_pow_eq` for `B = k(X) ⊗_{P₀} W₀`; then localize back
(`isEtaleAt_integralClosure_of_isLocalization`). -/
theorem isEtaleAt_integralClosure_of_pow_eq_mul [IsAlgClosed k] [CharZero k]
    {S : Type*} [CommRing S] [IsDomain S] [IsIntegrallyClosed S] [Algebra k[X] S]
    [Module.Finite k[X] S] {D : Type*} [CommRing D] [Algebra S D]
    (g₀ : k[X]) (hg₀ : IsUnit (algebraMap S D (algebraMap k[X] S g₀)))
    (P₀ : Type*) [CommRing P₀] [Algebra k[X] P₀] [IsLocalization.Away g₀ P₀]
    (W₀ : Type*) [CommRing W₀] [Algebra P₀ W₀] [Module.Finite P₀ W₀] [Algebra.Etale P₀ W₀]
    (ι : W₀ →+* D)
    (hι : ∀ a : k[X], ι (algebraMap P₀ W₀ (algebraMap k[X] P₀ a)) =
      algebraMap S D (algebraMap k[X] S a))
    (hgen : ∀ c : D, c ∈ Algebra.adjoin S (Set.range ι))
    (N : ℕ) (hN : ∀ m, 0 < m → m ≤ Module.finrank P₀ W₀ → m ∣ N)
    (L : Type*) [Field L] [Algebra S L] [IsFractionRing S L]
    (hy : ∀ b : k, g₀.IsRoot b → ∃ (y : L) (u : k[X]), ¬ u.IsRoot b ∧
      y ^ N * algebraMap S L (algebraMap k[X] S u) = algebraMap S L (algebraMap k[X] S (X - C b)))
    (q : Ideal (integralClosure S D)) [q.IsPrime]
    (hq : algebraMap k[X] S g₀ ∈ q.comap (algebraMap S (integralClosure S D)))
    (hq1 : (q.comap (algebraMap S (integralClosure S D))).height = 1) :
    Algebra.IsEtaleAt S q := by
  classical
  set P := q.comap (algebraMap S (integralClosure S D)) with hPdef
  have hP : P.IsPrime := Ideal.comap_isPrime _ _
  set p := P.comap (algebraMap k[X] S) with hpdef
  have hp : p.IsPrime := Ideal.comap_isPrime _ _
  have hg₀p : g₀ ∈ p := hq
  have hPne : P ≠ ⊥ := by
    intro h
    rw [h, Ideal.height_bot] at hq1
    exact zero_ne_one hq1
  -- `k[X] → S` is injective: otherwise its kernel is maximal and `⊥ < P` lie over it
  have : Algebra.IsIntegral k[X] S := inferInstance
  have hinj : Function.Injective (algebraMap k[X] S) := by
    rw [injective_iff_map_eq_zero]
    intro a ha
    by_contra ha0
    have hlt := Ideal.IsIntegral.comap_lt_comap (R := k[X]) (A := S) (I := ⊥) (J := P)
      (bot_lt_iff_ne_bot.mpr hPne)
    have hker : a ∈ (⊥ : Ideal S).comap (algebraMap k[X] S) := by simpa using ha
    have hmax : ((⊥ : Ideal S).comap (algebraMap k[X] S)).IsMaximal :=
      (Ideal.comap_isPrime _ _).isMaximal (fun h ↦ ha0 (by rw [h] at hker; simpa using hker))
    exact hlt.ne (hmax.eq_of_le hp.ne_top hlt.le)
  have : FaithfulSMul k[X] S := (faithfulSMul_iff_algebraMap_injective _ _).mpr hinj
  -- `g₀ ≠ 0`, and a root `b` of `g₀` with `X - b ∈ p`
  have hg₀0 : g₀ ≠ 0 := by
    rintro rfl
    have h01 : (0 : D) = 1 := by simpa using hg₀
    have : Subsingleton D := subsingleton_of_zero_eq_one h01
    have h1 : (1 : integralClosure S D) ∈ q := by
      rw [show (1 : integralClosure S D) = 0 from Subsingleton.elim _ _]
      exact q.zero_mem
    exact (Ideal.IsPrime.ne_top ‹_›) ((Ideal.eq_top_iff_one _).mpr h1)
  obtain ⟨b, hb, hbp⟩ : ∃ b, g₀.IsRoot b ∧ X - C b ∈ p := by
    have hsplit :=
      C_leadingCoeff_mul_prod_multiset_X_sub_C (IsAlgClosed.card_roots_eq_natDegree (p := g₀))
    rw [← hsplit] at hg₀p
    rcases hp.mem_or_mem hg₀p with h | h
    · exact absurd (Ideal.eq_top_of_isUnit_mem _ h
        (isUnit_C.mpr (leadingCoeff_ne_zero.mpr hg₀0).isUnit)) hp.ne_top
    · obtain ⟨_, hmem, hx⟩ := (hp.multiset_prod_mem_iff_exists_mem _).mp h
      obtain ⟨b, hbr, rfl⟩ := Multiset.mem_map.mp hmem
      exact ⟨b, (mem_roots hg₀0).mp hbr, hx⟩
  obtain ⟨y, u, hu, hyu⟩ := hy b hb
  have hpeq : p = Ideal.span {X - C b} := by
    have hmax : (Ideal.span {X - C b} : Ideal k[X]).IsMaximal :=
      PrincipalIdealRing.isMaximal_of_irreducible (irreducible_X_sub_C b)
    exact (hmax.eq_of_le hp.ne_top ((Ideal.span_singleton_le_iff_mem _).mpr hbp)).symm
  have hp0 : p ≠ ⊥ := by
    rw [hpeq, ne_eq, Ideal.span_singleton_eq_bot]
    exact X_sub_C_ne_zero b
  -- the discrete valuation ring `R = k[X]_p` with uniformizer `π = X - b`
  let R := Localization.AtPrime p
  have : IsDiscreteValuationRing R :=
    IsLocalization.AtPrime.isDiscreteValuationRing_of_dedekind_domain k[X] hp0 R
  set π : R := algebraMap k[X] R (X - C b) with hπdef
  have hπ : Irreducible π := by
    rw [IsDiscreteValuationRing.irreducible_iff_uniformizer,
      ← IsLocalization.AtPrime.map_eq_maximalIdeal p R,
      show Ideal.map (algebraMap k[X] R) p = Ideal.map (algebraMap k[X] R) (Ideal.span {X - C b})
        from congrArg _ hpeq, Ideal.map_span, Set.image_singleton]
  have huR : IsUnit (algebraMap k[X] R u) := by
    refine (IsLocalization.AtPrime.isUnit_to_map_iff R p u).mpr ?_
    change u ∉ p
    rw [hpeq, Ideal.mem_span_singleton, dvd_iff_isRoot]
    exact hu
  have hR0 : ringChar (IsLocalRing.ResidueField R) = 0 := by
    have : CharZero (IsLocalRing.ResidueField R) :=
      charZero_of_injective_algebraMap (algebraMap k (IsLocalRing.ResidueField R)).injective
    exact ringChar.eq_zero
  -- the semilocal ring `S' = S_p`, normal, finite over `R`
  let NS := Algebra.algebraMapSubmonoid S p.primeCompl
  have hNS : NS ≤ S⁰ := by
    rintro _ ⟨a, ha, rfl⟩
    exact mem_nonZeroDivisors_of_ne_zero fun h ↦ ha (by
      rw [hinj (h.trans (map_zero _).symm)]; exact p.zero_mem)
  let S' := Localization NS
  have : IsDomain S' := IsLocalization.isDomain_localization hNS
  have : IsIntegrallyClosed S' := isIntegrallyClosed_of_isLocalization S' NS hNS
  have : Module.Finite R S' := inferInstance
  have : Algebra.IsIntegral R S' := inferInstance
  have : FaithfulSMul R S' := by
    rw [faithfulSMul_iff_algebraMap_injective]
    refine IsLocalization.map_injective_of_injective' (M := p.primeCompl) (Rₘ := R) S
      (f := algebraMap k[X] S) S' (N := NS) (Submonoid.le_comap_map _) ?_ hinj
    rintro ⟨a, ha, h0⟩
    exact ha (by rw [hinj (h0.trans (map_zero _).symm)]; exact p.zero_mem)
  -- the fraction fields `K = k(X)` (of `k[X]` and `R`) and `K'` (of `S` and `S'`)
  let K := FractionRing k[X]
  let K' := FractionRing S
  let : Algebra K K' := FractionRing.liftAlgebra k[X] K'
  have : IsScalarTower k[X] K K' := FractionRing.isScalarTower_liftAlgebra k[X] K'
  have : Module.Finite K K' := Module.Finite.of_isLocalization k[X] S k[X]⁰
  have : CharZero K := charZero_of_injective_algebraMap (algebraMap k K).injective
  have : Algebra.IsSeparable K K' := Algebra.IsAlgebraic.isSeparable_of_perfectField
  have hle : p.primeCompl ≤ k[X]⁰ := p.primeCompl_le_nonZeroDivisors
  let : Algebra R K := IsLocalization.localizationAlgebraOfSubmonoidLe R K p.primeCompl k[X]⁰ hle
  have : IsScalarTower k[X] R K :=
    IsLocalization.localization_isScalarTower_of_submonoid_le R K p.primeCompl k[X]⁰ hle
  have : IsFractionRing R K :=
    IsFractionRing.isFractionRing_of_isDomain_of_isLocalization p.primeCompl R K
  have hNS' : NS ≤ S⁰.comap (RingHom.id S) := hNS
  let : Algebra S' K' := (IsLocalization.map (M := NS) (T := S⁰) K' (RingHom.id S) hNS' :
    S' →+* K').toAlgebra
  have : IsScalarTower S S' K' := .of_algebraMap_eq fun a ↦ by
    change _ = IsLocalization.map (M := NS) (T := S⁰) K' (RingHom.id S) hNS' (algebraMap S S' a)
    rw [IsLocalization.map_eq]
    rfl
  have : IsFractionRing S' K' := IsFractionRing.isFractionRing_of_isLocalization NS S' K' hNS
  let : Algebra R K' := ((algebraMap S' K').comp (algebraMap R S')).toAlgebra
  have : IsScalarTower R S' K' := .of_algebraMap_eq fun _ ↦ rfl
  have : IsScalarTower R K K' := .of_algebraMap_eq fun r ↦ by
    have : (algebraMap R K').comp (algebraMap k[X] R) =
        ((algebraMap K K').comp (algebraMap R K)).comp (algebraMap k[X] R) := by
      refine RingHom.ext fun a ↦ ?_
      change algebraMap R K' (algebraMap k[X] R a) =
        algebraMap K K' (algebraMap R K (algebraMap k[X] R a))
      rw [← IsScalarTower.algebraMap_apply k[X] R K, ← IsScalarTower.algebraMap_apply k[X] K K',
        IsScalarTower.algebraMap_apply R S' K', ← IsScalarTower.algebraMap_apply k[X] R S',
        IsScalarTower.algebraMap_apply k[X] S S', ← IsScalarTower.algebraMap_apply S S' K',
        ← IsScalarTower.algebraMap_apply k[X] S K']
    exact congrArg (· r) (IsLocalization.ringHom_ext p.primeCompl this)
  have : IsIntegralClosure S' R K' := IsIntegralClosure.of_isIntegrallyClosed S' R K'
  let e : L ≃ₐ[S] K' := IsLocalization.algEquiv S⁰ L K'
  have hcomp (a : k[X]) : algebraMap R K' (algebraMap k[X] R a) =
      algebraMap S K' (algebraMap k[X] S a) := by
    rw [IsScalarTower.algebraMap_apply R S' K', IsScalarTower.algebraMap_apply S S' K',
      ← IsScalarTower.algebraMap_apply k[X] R S', ← IsScalarTower.algebraMap_apply k[X] S S']
  have hy' : (e y) ^ N = algebraMap R K' (π * ↑(huR.unit⁻¹)) := by
    have h1 := congrArg e hyu
    rw [map_mul, map_pow, AlgEquiv.commutes, AlgEquiv.commutes, ← hcomp, ← hcomp] at h1
    rw [map_mul, ← h1, mul_assoc, ← map_mul, IsUnit.mul_val_inv, map_one, mul_one]
  -- the localized covering `D' = D_p`: an `S'`-algebra in which `π` is a unit
  let D' := Localization (Algebra.algebraMapSubmonoid D NS)
  let : Algebra R D' := ((algebraMap S' D').comp (algebraMap R S')).toAlgebra
  have : IsScalarTower R S' D' := .of_algebraMap_eq fun _ ↦ rfl
  have hRD (a : k[X]) : algebraMap R D' (algebraMap k[X] R a) =
      algebraMap D D' (algebraMap S D (algebraMap k[X] S a)) := by
    rw [IsScalarTower.algebraMap_apply R S' D', ← IsScalarTower.algebraMap_apply k[X] R S',
      IsScalarTower.algebraMap_apply k[X] S S', ← IsScalarTower.algebraMap_apply S S' D',
      IsScalarTower.algebraMap_apply S D D']
  have hπD : IsUnit (algebraMap R D' π) := by
    rw [hπdef, hRD]
    refine IsUnit.map _ (isUnit_of_dvd_unit (map_dvd _ (map_dvd _ ?_)) hg₀)
    exact dvd_iff_isRoot.mpr hb
  have hunits : ∀ s : S'⁰, IsUnit (algebraMap S' D' s) := by
    rintro ⟨s, hs⟩
    obtain ⟨r, hr0, hsr⟩ :=
      (Algebra.IsIntegral.isIntegral (R := R) s).isAlgebraic.exists_nonzero_dvd hs
    obtain ⟨m, v, rfl⟩ := IsDiscreteValuationRing.eq_unit_mul_pow_irreducible hr0 hπ
    refine isUnit_of_dvd_unit (map_dvd (algebraMap S' D') hsr) ?_
    rw [← IsScalarTower.algebraMap_apply, map_mul, map_pow]
    exact (v.isUnit.map _).mul (hπD.pow m)
  let : Algebra K' D' := (IsLocalization.lift (M := S'⁰) (S := K') hunits).toAlgebra
  have : IsScalarTower S' K' D' :=
    .of_algebraMap_eq fun s ↦ (IsLocalization.lift_eq (M := S'⁰) (S := K') hunits s).symm
  -- the generic algebra `B = K ⊗_{P₀} W₀` of the covering and its map `β` to `D'`
  have hg₀K : IsUnit (algebraMap k[X] K g₀) :=
    (map_ne_zero_iff _ (IsFractionRing.injective k[X] K)).mpr hg₀0 |>.isUnit
  let : Algebra P₀ K := (IsLocalization.Away.lift g₀ hg₀K).toAlgebra
  have : IsScalarTower k[X] P₀ K :=
    .of_algebraMap_eq fun a ↦ (IsLocalization.Away.lift_eq g₀ hg₀K a).symm
  have : IsDomain P₀ := IsLocalization.isDomain_of_le_nonZeroDivisors (M := Submonoid.powers g₀)
    P₀ (powers_le_nonZeroDivisors_of_noZeroDivisors hg₀0)
  have : IsFractionRing P₀ K := IsFractionRing.isFractionRing_of_isDomain_of_isLocalization
    (Submonoid.powers g₀) P₀ K
  let B := K ⊗[P₀] W₀
  have hrank : Module.finrank K B = Module.finrank P₀ W₀ := by
    rw [IsLocalization.finrank_eq K P₀⁰ le_rfl,
      IsLocalizedModule.finrank_eq P₀⁰ (TensorProduct.mk P₀ K W₀ 1) le_rfl]
  let : Algebra P₀ D' :=
    ((algebraMap K' D').comp ((algebraMap K K').comp (algebraMap P₀ K))).toAlgebra
  have hP₀D (a : k[X]) : algebraMap P₀ D' (algebraMap k[X] P₀ a) =
      algebraMap D D' (algebraMap S D (algebraMap k[X] S a)) := by
    change algebraMap K' D' (algebraMap K K' (algebraMap P₀ K (algebraMap k[X] P₀ a))) = _
    rw [← IsScalarTower.algebraMap_apply k[X] P₀ K, ← IsScalarTower.algebraMap_apply k[X] K K',
      IsScalarTower.algebraMap_apply k[X] S K', IsScalarTower.algebraMap_apply S S' K',
      ← IsScalarTower.algebraMap_apply S' K' D', ← IsScalarTower.algebraMap_apply S S' D',
      IsScalarTower.algebraMap_apply S D D']
  let f₁ : K →ₐ[P₀] D' :=
    { (algebraMap K' D').comp (algebraMap K K') with commutes' := fun _ ↦ rfl }
  let f₂ : W₀ →ₐ[P₀] D' :=
    { (algebraMap D D').comp ι with
      commutes' := fun a ↦ by
        change algebraMap D D' (ι (algebraMap P₀ W₀ a)) = algebraMap P₀ D' a
        have : ((algebraMap D D').comp ι).comp (algebraMap P₀ W₀) = algebraMap P₀ D' :=
          IsLocalization.ringHom_ext (Submonoid.powers g₀) (RingHom.ext fun a ↦ by
            simp only [RingHom.comp_apply]
            rw [hι, hP₀D])
        exact congrArg (· a) this }
  obtain ⟨β, hβ, hβ₁⟩ : ∃ β : B →+* D',
      (∀ a : K, β (algebraMap K B a) = algebraMap K' D' (algebraMap K K' a)) ∧
      ∀ w : W₀, β ((1 : K) ⊗ₜ[P₀] w) = algebraMap D D' (ι w) := by
    refine ⟨(Algebra.TensorProduct.lift f₁ f₂ fun _ _ ↦ Commute.all _ _).toRingHom,
      fun a ↦ ?_, fun w ↦ ?_⟩
    · change Algebra.TensorProduct.lift f₁ f₂ _ (a ⊗ₜ 1) = _
      rw [Algebra.TensorProduct.lift_tmul, map_one, mul_one]
      rfl
    · change Algebra.TensorProduct.lift f₁ f₂ _ ((1 : K) ⊗ₜ[P₀] w) = _
      rw [Algebra.TensorProduct.lift_tmul, map_one, one_mul]
      rfl
  -- `D'` is generated over `K'` by the image of `B`
  have : IsScalarTower S K' D' := .of_algebraMap_eq fun s ↦ by
    rw [IsScalarTower.algebraMap_apply S S' K', ← IsScalarTower.algebraMap_apply S' K' D',
      ← IsScalarTower.algebraMap_apply S S' D']
  have hgen' (c : D') : c ∈ Algebra.adjoin K' (Set.range β) := by
    have hD (x : D) : algebraMap D D' x ∈ Algebra.adjoin K' (Set.range β) := by
      induction hgen x using Algebra.adjoin_induction with
      | mem x hx =>
        obtain ⟨w, rfl⟩ := hx
        rw [← hβ₁ w]
        exact Algebra.subset_adjoin ⟨_, rfl⟩
      | algebraMap a =>
        rw [← IsScalarTower.algebraMap_apply S D D', IsScalarTower.algebraMap_apply S K' D']
        exact Subalgebra.algebraMap_mem _ _
      | add x y _ _ hx hy => rw [map_add]; exact Subalgebra.add_mem _ hx hy
      | mul x y _ _ hx hy => rw [map_mul]; exact Subalgebra.mul_mem _ hx hy
    obtain ⟨⟨x, ⟨_, s, hs, rfl⟩⟩, rfl⟩ := IsLocalization.mk'_surjective
      (Algebra.algebraMapSubmonoid D NS) c
    dsimp only
    rw [IsLocalization.mk'_eq_mul_mk'_one]
    refine Subalgebra.mul_mem _ (hD x) ?_
    have hs0 : algebraMap S K' s ≠ 0 :=
      (map_ne_zero_iff _ (IsFractionRing.injective S K')).mpr (nonZeroDivisors.ne_zero (hNS hs))
    have : IsLocalization.mk' D' (1 : D) (⟨algebraMap S D s, ⟨s, hs, rfl⟩⟩ :
        Algebra.algebraMapSubmonoid D NS) = algebraMap K' D' (algebraMap S K' s)⁻¹ := by
      rw [IsLocalization.mk'_eq_iff_eq_mul, map_one]
      change 1 = _ * algebraMap D D' (algebraMap S D s)
      rw [← IsScalarTower.algebraMap_apply S D D', IsScalarTower.algebraMap_apply S K' D',
        ← map_mul, inv_mul_cancel₀ hs0, map_one]
    rw [this]
    exact Subalgebra.algebraMap_mem _ _
  -- Abhyankar over `R` (`etale_integralClosure_of_pow_eq`), then back to `S` by localization
  obtain ⟨-, hDet⟩ := etale_integralClosure_of_pow_eq R (K := K) hR0 hπ N huR.unit⁻¹ (e y) hy'
    S' B (fun m hm hle ↦ hN m hm (hle.trans_eq hrank)) D' β hβ hgen'
  refine isEtaleAt_integralClosure_of_isLocalization (S' := S') (C' := D') NS q ?_
  rintro _ ⟨a, ha, rfl⟩ haq
  exact ha haq

end Chart

end SGA.SGA1.ExposeXIII

