/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import Mathlib.GroupTheory.SpecificGroups.Cyclic
import SGA.SGA1.ExposeI.GeometricPoints
import SGA.SGA1.ExposeXIII.MultiplicativeGroup

/-!
# Inertia subgroups and pro-`L` quotients (tools for XIII.2.12)

Tools to show that an inertia subgroup `H` of `π₁(U)` (`IsInertiaSubgroupAt`) generates the
maximal pro-`L` quotient `π₁^L(U)`, as XIII.2.12 asserts for `𝔾_m = ℙ¹ - {0, ∞}` at `0`:

* group theory: `topologicalClosure_sup_proLKernel_eq_top` (in a compact group, if `H N = Γ` for
  every open normal subgroup `N` of `L`-index, then `H` is dense in `Γ` modulo
  `proLKernel L Γ`); if `φ ↦ φ σ` is bijective on the continuous homomorphisms to finite
  `L`-groups (`Γ^L` procyclic, generated by `σ`), then `σ` generates every finite `L`-quotient
  (`zpowers_mk_eq_top_of_bijective`) and the open normal subgroups of `L`-index are determined by
  their index (`le_of_bijective_eval`);
* Galois categories (V.7): if the pullback of an étale covering `E` of `S` along `f : T ⟶ S` is
  connected, the image of `π₁(T)` acts transitively on the fibres of `E`
  (`exists_map_smul_eq_of_isConnected_pullback`); transitivity is transported along paths
  (`exists_smul_eq_of_path`); so an inertia subgroup at `x̄` acts transitively on the fibres of
  every covering of `U` that stays connected over `U ×_X Spec 𝒪^{sh}_{X,x̄}`
  (`exists_mem_smul_eq_of_isInertiaSubgroupAt`, `sup_stabilizer_eq_top_of_isInertiaSubgroupAt`);
* the criterion `topologicalClosure_sup_proLKernel_eq_top_of_isInertiaSubgroupAt`: if `π₁^L(U)` is
  procyclic and every finite quotient of `π₁^L(U)` comes from a Galois covering that stays
  connected over `U ×_X Spec 𝒪^{sh}_{X,x̄}`, every inertia subgroup at `x̄` maps onto `π₁^L(U)`;
* existence: over an integral `X`, inertia subgroups at any geometric point exist for every nonempty
  open `U` (`exists_isInertiaSubgroupAt`), as `U ×_X Spec 𝒪^{sh}_{X,x̄}` contains a point over the
  generic point (`nonempty_pullback_fromSpecStrictLocalization`).

The group-theoretic statements are about `proLKernel` and `IsLGroup`
(`SGA.SGA1.ExposeXIII.ProLQuotient`) and stay next to them.
-/

universe u w

open CategoryTheory Limits AlgebraicGeometry

namespace SGA.SGA1.ExposeXIII

section Closure

variable {L : Set ℕ} {Γ : Type*} [Group Γ] [TopologicalSpace Γ] [IsTopologicalGroup Γ]

/-- In a compact group, a subgroup `H` with `H N = Γ` for every open normal subgroup `N` of
`L`-index is dense modulo the kernel of the maximal pro-`L` quotient. -/
theorem topologicalClosure_sup_proLKernel_eq_top [CompactSpace Γ] (H : Subgroup Γ)
    (h : ∀ N : Subgroup Γ, N.Normal → IsOpen (N : Set Γ) → IsLIndex L N → H ⊔ N = ⊤) :
    (H ⊔ proLKernel L Γ).topologicalClosure = ⊤ := by
  classical
  set C := (H ⊔ proLKernel L Γ).topologicalClosure
  refine eq_top_iff.mpr fun γ _ ↦ ?_
  let ι := {N : Subgroup Γ // N.Normal ∧ IsOpen (N : Set Γ) ∧ IsLIndex L N}
  let t : ι → Set Γ := fun N ↦ {c | γ⁻¹ * c ∈ N.1} ∩ C
  let top : ι := ⟨⊤, inferInstance, isOpen_univ, by
    refine ⟨by rw [Subgroup.index_top]; exact one_ne_zero, fun p hp hdvd ↦ ?_⟩
    rw [Subgroup.index_top] at hdvd
    exact absurd (Nat.le_of_dvd one_pos hdvd) (by have := hp.two_le; omega)⟩
  have : Nonempty ι := ⟨top⟩
  have hdir : Directed (· ⊇ ·) t := by
    rintro ⟨N, hN, hNo, hNL⟩ ⟨N', hN', hN'o, hN'L⟩
    refine ⟨⟨N ⊓ N', Subgroup.normal_inf_normal N N', hNo.inter hN'o, hNL.inf hN'L⟩, ?_, ?_⟩
    · exact Set.inter_subset_inter_left _ fun c hc ↦ (Subgroup.mem_inf.mp hc).1
    · exact Set.inter_subset_inter_left _ fun c hc ↦ (Subgroup.mem_inf.mp hc).2
  have hne : ∀ N : ι, (t N).Nonempty := by
    rintro ⟨N, hN, hNo, hNL⟩
    have hγ : γ ∈ H ⊔ N := (h N hN hNo hNL).symm ▸ Subgroup.mem_top γ
    obtain ⟨y, hy, z, hz, rfl⟩ := (mem_sup_normal_iff H N).mp hγ
    refine ⟨y, ?_, Subgroup.le_topologicalClosure _ (Subgroup.mem_sup_left hy)⟩
    change (y * z)⁻¹ * y ∈ N
    simpa [mul_assoc] using N.inv_mem hz
  have hcl : ∀ N : ι, IsClosed (t N) := by
    rintro ⟨N, hN, hNo, hNL⟩
    refine IsClosed.inter ?_ (Subgroup.isClosed_topologicalClosure _)
    exact (Subgroup.isClosed_of_isOpen N hNo).preimage (continuous_const.mul continuous_id)
  obtain ⟨c, hc⟩ := IsCompact.nonempty_iInter_of_directed_nonempty_isCompact_isClosed t hdir hne
    (fun N ↦ (hcl N).isCompact) hcl
  rw [Set.mem_iInter] at hc
  have hcC : c ∈ C := (hc top).2
  have hk : γ⁻¹ * c ∈ proLKernel L Γ :=
    mem_proLKernel.mpr fun N hN ho hL ↦ (hc ⟨N, hN, ho, hL⟩).1
  have : γ = c * (γ⁻¹ * c)⁻¹ := by group
  rw [this]
  exact C.mul_mem hcC (C.inv_mem (Subgroup.le_topologicalClosure _ (Subgroup.mem_sup_right hk)))

end Closure

section ProCyclic

variable {L : Set ℕ} {Γ : Type*} [Group Γ] [TopologicalSpace Γ] {σ : Γ}

/-- Bijectivity of `φ ↦ φ σ` on the continuous homomorphisms to the finite `L`-groups of one
universe gives it for the finite `L`-groups of any universe (through `Shrink`). -/
theorem bijective_eval_of_small
    (hσ : ∀ (G : Type u) [Group G] [TopologicalSpace G] [DiscreteTopology G], IsLGroup L G →
      Function.Bijective fun φ : ContinuousMonoidHom Γ G ↦ φ σ)
    (G : Type w) [Group G] [TopologicalSpace G] [DiscreteTopology G] (hG : IsLGroup L G) :
    Function.Bijective fun φ : ContinuousMonoidHom Γ G ↦ φ σ := by
  have := hG.1
  let G' := Shrink.{u} G
  let : TopologicalSpace G' := ⊥
  have : DiscreteTopology G' := ⟨rfl⟩
  let e : G' ≃* G := Shrink.mulEquiv
  have hG' : IsLGroup L G' := hG.of_injective e.toMonoidHom e.injective
  let Φ : ContinuousMonoidHom Γ G ≃ ContinuousMonoidHom Γ G' :=
    { toFun φ := ⟨e.symm.toMonoidHom.comp φ.toMonoidHom,
        (continuous_of_discreteTopology (f := ⇑e.symm)).comp φ.continuous⟩
      invFun φ := ⟨e.toMonoidHom.comp φ.toMonoidHom,
        (continuous_of_discreteTopology (f := ⇑e)).comp φ.continuous⟩
      left_inv φ := ContinuousMonoidHom.ext fun x ↦ e.apply_symm_apply (φ x)
      right_inv φ := ContinuousMonoidHom.ext fun x ↦ e.symm_apply_apply (φ x) }
  have : (fun φ : ContinuousMonoidHom Γ G ↦ φ σ) =
      e ∘ (fun φ : ContinuousMonoidHom Γ G' ↦ φ σ) ∘ Φ := by
    ext φ
    exact (e.apply_symm_apply (φ σ)).symm
  rw [this]
  exact e.bijective.comp ((hσ G' hG').comp Φ.bijective)

variable [IsTopologicalGroup Γ]

/-- If `φ ↦ φ σ` is bijective on the continuous homomorphisms to finite `L`-groups, the image of
`σ` generates `Γ ⧸ N` for every open normal subgroup `N` of `L`-index. -/
theorem zpowers_mk_eq_top_of_bijective
    (hσ : ∀ (G : Type u) [Group G] [TopologicalSpace G] [DiscreteTopology G], IsLGroup L G →
      Function.Bijective fun φ : ContinuousMonoidHom Γ G ↦ φ σ)
    (N : Subgroup Γ) [N.Normal] (ho : IsOpen (N : Set Γ)) (hL : IsLIndex L N) :
    Subgroup.zpowers (σ : Γ ⧸ N) = ⊤ := by
  have := QuotientGroup.discreteTopology ho
  have hQ : IsLGroup L (Γ ⧸ N) := (isLGroup_quotient_iff N).mpr hL
  set C := Subgroup.zpowers (σ : Γ ⧸ N)
  have hC : IsLGroup L C := hQ.of_injective C.subtype C.subtype_injective
  obtain ⟨ψ, hψ⟩ := (bijective_eval_of_small hσ C hC).2 ⟨(σ : Γ ⧸ N), Subgroup.mem_zpowers _⟩
  let q : ContinuousMonoidHom Γ (Γ ⧸ N) := ⟨QuotientGroup.mk' N, QuotientGroup.continuous_mk⟩
  let ψ' : ContinuousMonoidHom Γ (Γ ⧸ N) :=
    ⟨C.subtype.comp ψ.toMonoidHom, continuous_subtype_val.comp ψ.continuous⟩
  have heq : ψ' = q := (bijective_eval_of_small hσ (Γ ⧸ N) hQ).1 (by
    change ((ψ σ : C) : Γ ⧸ N) = (σ : Γ ⧸ N)
    rw [show ψ σ = ⟨(σ : Γ ⧸ N), Subgroup.mem_zpowers _⟩ from hψ])
  refine eq_top_iff.mpr fun x _ ↦ ?_
  obtain ⟨γ, rfl⟩ := QuotientGroup.mk_surjective x
  have : ((ψ γ : C) : Γ ⧸ N) = (γ : Γ ⧸ N) :=
    congrArg (fun f : ContinuousMonoidHom Γ (Γ ⧸ N) ↦ f γ) heq
  exact this ▸ (ψ γ).2

/-- If `φ ↦ φ σ` is bijective on the continuous homomorphisms to finite `L`-groups, an open normal
subgroup `M` of `L`-index is contained in every open normal subgroup `N` of `L`-index with
`[Γ : N] ∣ [Γ : M]` (`Γ^L` is procyclic, generated by `σ`). -/
theorem le_of_bijective_eval
    (hσ : ∀ (G : Type u) [Group G] [TopologicalSpace G] [DiscreteTopology G], IsLGroup L G →
      Function.Bijective fun φ : ContinuousMonoidHom Γ G ↦ φ σ)
    {M N : Subgroup Γ} [M.Normal] [N.Normal] (hMo : IsOpen (M : Set Γ)) (hML : IsLIndex L M)
    (hNo : IsOpen (N : Set Γ)) (hNL : IsLIndex L N) (hdvd : N.index ∣ M.index) : M ≤ N := by
  have := QuotientGroup.discreteTopology hMo
  have := QuotientGroup.discreteTopology hNo
  have hgen := zpowers_mk_eq_top_of_bijective hσ M hMo hML
  have hgen' : ∀ x : Γ ⧸ M, x ∈ Subgroup.zpowers (σ : Γ ⧸ M) := fun x ↦ hgen ▸ Subgroup.mem_top x
  have : N.FiniteIndex := ⟨hNL.1⟩
  have hord : orderOf (σ : Γ ⧸ N) ∣ orderOf (σ : Γ ⧸ M) := by
    rw [orderOf_eq_card_of_forall_mem_zpowers hgen', ← Subgroup.index_eq_card]
    exact (orderOf_dvd_natCard _).trans (by rw [← Subgroup.index_eq_card]; exact hdvd)
  let χ := monoidHomOfForallMemZpowers hgen' hord
  let f₁ : ContinuousMonoidHom Γ (Γ ⧸ N) := ⟨χ.comp (QuotientGroup.mk' M),
    (continuous_of_discreteTopology (f := ⇑χ)).comp QuotientGroup.continuous_mk⟩
  let f₂ : ContinuousMonoidHom Γ (Γ ⧸ N) := ⟨QuotientGroup.mk' N, QuotientGroup.continuous_mk⟩
  have heq : f₁ = f₂ := (bijective_eval_of_small hσ (Γ ⧸ N) ((isLGroup_quotient_iff N).mpr hNL)).1
    (monoidHomOfForallMemZpowers_apply_gen hgen' hord)
  intro m hm
  have : f₂ m = 1 := by
    rw [← heq]
    change χ (m : Γ ⧸ M) = 1
    rw [(QuotientGroup.eq_one_iff m).mpr hm, map_one]
  exact (QuotientGroup.eq_one_iff m).mp this

/-- If `φ ↦ φ σ` is bijective on the continuous homomorphisms to finite `L`-groups, `σ` generates a
dense subgroup of the compact group `Γ` modulo `proLKernel L Γ` (it generates `Γ^L`). -/
theorem topologicalClosure_zpowers_sup_proLKernel_eq_top [CompactSpace Γ]
    (hσ : ∀ (G : Type u) [Group G] [TopologicalSpace G] [DiscreteTopology G], IsLGroup L G →
      Function.Bijective fun φ : ContinuousMonoidHom Γ G ↦ φ σ) :
    (Subgroup.zpowers σ ⊔ proLKernel L Γ).topologicalClosure = ⊤ :=
  topologicalClosure_sup_proLKernel_eq_top _ fun N _ ho hL ↦ by
    have hgen := zpowers_mk_eq_top_of_bijective hσ N ho hL
    refine eq_top_iff.mpr fun g _ ↦ ?_
    have hg : (g : Γ ⧸ N) ∈ Subgroup.zpowers (σ : Γ ⧸ N) := hgen ▸ Subgroup.mem_top _
    obtain ⟨j, hj⟩ := Subgroup.mem_zpowers_iff.mp hg
    rw [← QuotientGroup.mk_zpow, QuotientGroup.eq] at hj
    have : g = σ ^ j * ((σ ^ j)⁻¹ * g) := by group
    rw [this]
    exact Subgroup.mul_mem _ (Subgroup.mem_sup_left (Subgroup.zpow_mem_zpowers σ j))
      (Subgroup.mem_sup_right hj)

end ProCyclic

section Transitivity

open PreGaloisCategory ExposeV

variable {S T : Scheme.{u}} (Ω : Type u) [Field Ω]

/-- If the pullback of an étale covering `E` of `S` along `f : T ⟶ S` (`T` connected) is
connected, the image of `π₁(T, t) → π₁(S, f t)` acts transitively on the fibre of `E`. -/
theorem exists_map_smul_eq_of_isConnected_pullback [IsSepClosed Ω] [ConnectedSpace T]
    (f : T ⟶ S)
    (t : Spec (.of Ω) ⟶ T) (E : FEt S) [IsConnected ((FEt.pullback f).obj E)]
    (x y : (FEt.fiber Ω (t ≫ f)).obj E) :
    ∃ τ : etaleFundamentalGroup Ω t, etaleFundamentalGroup.map Ω f t τ • x = y := by
  let e := FEt.pullbackFiberIso Ω f t
  obtain ⟨x', rfl⟩ : ∃ x' : (FEt.fiber Ω t).obj ((FEt.pullback f).obj E), e.hom.app E x' = x :=
    ⟨e.inv.app E x, FintypeCat.inv_hom_id_apply (e.app E) x⟩
  obtain ⟨y', rfl⟩ : ∃ y' : (FEt.fiber Ω t).obj ((FEt.pullback f).obj E), e.hom.app E y' = y :=
    ⟨e.inv.app E y, FintypeCat.inv_hom_id_apply (e.app E) y⟩
  obtain ⟨τ, hτ⟩ := MulAction.exists_smul_eq (etaleFundamentalGroup Ω t) x' y'
  refine ⟨τ, ?_⟩
  change (autMap (FEt.pullback f) e τ).hom.app E (e.hom.app E x') = _
  rw [autMap_hom_app, FintypeCat.comp_apply, FintypeCat.comp_apply]
  have hx : e.inv.app E (e.hom.app E x') = x' := FintypeCat.hom_inv_id_apply (e.app E) x'
  simp only [hx]
  exact congrArg _ hτ

private lemma conjAut_hom_app_hom_app {C : Type*} [Category C] {F F' : C ⥤ FintypeCat.{w}}
    (φ : F ≅ F') (σ : Aut F) {X : C} (x : F.obj X) :
    (φ.conjAut σ).hom.app X (φ.hom.app X x) = φ.hom.app X (σ.hom.app X x) := by
  rw [Iso.conjAut_apply]
  change φ.hom.app X (σ.hom.app X (φ.inv.app X (φ.hom.app X x))) = _
  have hx : φ.inv.app X (φ.hom.app X x) = x := FintypeCat.hom_inv_id_apply (φ.app X) x
  rw [hx]

variable {Ω} in
/-- Transport of a transitive action along a path `γ` (V.7): if `K ≤ π₁(S, s)` acts transitively
on the fibre at `s` of `E`, its image in `π₁(S, s')` acts transitively on the fibre at `s'`. -/
theorem exists_smul_eq_of_path {Ω' : Type u} [Field Ω']
    {s : Spec (.of Ω') ⟶ S} {s' : Spec (.of Ω) ⟶ S} (γ : etalePaths Ω' Ω s s')
    (K : Subgroup (etaleFundamentalGroup Ω' s)) (E : FEt S)
    (h : ∀ x y : (FEt.fiber Ω' s).obj E, ∃ k ∈ K, k • x = y)
    (x y : (FEt.fiber Ω s').obj E) :
    ∃ k ∈ K.map (etaleFundamentalGroup.continuousMulEquivOfPath Ω' Ω γ).toMonoidHom, k • x = y := by
  obtain ⟨x', rfl⟩ : ∃ x', γ.hom.app E x' = x :=
    ⟨γ.inv.app E x, FintypeCat.inv_hom_id_apply (γ.app E) x⟩
  obtain ⟨y', rfl⟩ : ∃ y', γ.hom.app E y' = y :=
    ⟨γ.inv.app E y, FintypeCat.inv_hom_id_apply (γ.app E) y⟩
  obtain ⟨k, hk, hky⟩ := h x' y'
  refine ⟨_, ⟨k, hk, rfl⟩, ?_⟩
  change (γ.conjAut k).hom.app E (γ.hom.app E x') = _
  rw [conjAut_hom_app_hom_app]
  exact congrArg _ hky

end Transitivity


section Inertia

open PreGaloisCategory ExposeV

/-- A subgroup `H` acting transitively on `α` satisfies `H ⊔ Stab(x) = G`. -/
private lemma sup_stabilizer_eq_top_of_forall_exists_smul_eq {G α : Type*} [Group G]
    [MulAction G α] (H : Subgroup G) (x : α) (h : ∀ y : α, ∃ k ∈ H, k • x = y) :
    H ⊔ MulAction.stabilizer G x = ⊤ := by
  refine eq_top_iff.mpr fun g _ ↦ ?_
  obtain ⟨k, hk, hkx⟩ := h (g • x)
  have hs : k⁻¹ * g ∈ MulAction.stabilizer G x := by
    rw [MulAction.mem_stabilizer_iff, mul_smul, ← hkx, inv_smul_smul]
  have : g = k * (k⁻¹ * g) := by group
  rw [this]
  exact Subgroup.mul_mem _ (Subgroup.mem_sup_left hk) (Subgroup.mem_sup_right hs)

variable {X : Scheme.{u}} {U : X.Opens} {Ω₀ : Type u} [Field Ω₀] [IsSepClosed Ω₀]
  {xb : Spec (.of Ω₀) ⟶ X} {Ω : Type u} [Field Ω] [IsSepClosed Ω]
  {ξ : Spec (.of Ω) ⟶ (U : Scheme.{u})} {H : Subgroup (etaleFundamentalGroup Ω ξ)}

/-- An inertia subgroup `H` of `π₁(U, ξ)` at `x̄` acts transitively on the fibre at `ξ` of every
étale covering `E` of `U` whose pullback to `U ×_X Spec 𝒪^{sh}_{X,x̄}` is connected. -/
theorem exists_mem_smul_eq_of_isInertiaSubgroupAt (hH : IsInertiaSubgroupAt U xb ξ H)
    [ConnectedSpace ↥(pullback U.ι xb.fromSpecStrictLocalization)] (E : FEt (U : Scheme.{u}))
    [IsConnected ((FEt.pullback (pullback.fst U.ι xb.fromSpecStrictLocalization)).obj E)]
    (x y : (FEt.fiber Ω ξ).obj E) : ∃ k ∈ H, k • x = y := by
  obtain ⟨Ω', _, _, η, γ, rfl⟩ := hH
  exact exists_smul_eq_of_path γ _ E (fun x y ↦ by
    obtain ⟨τ, hτ⟩ := exists_map_smul_eq_of_isConnected_pullback Ω' _ η E x y
    exact ⟨_, ⟨τ, rfl⟩, hτ⟩) x y

/-- If the pullback of the étale covering `E` of `U` to `U ×_X Spec 𝒪^{sh}_{X,x̄}` is connected,
then `H ⊔ Stab(y) = π₁(U, ξ)` for every inertia subgroup `H` at `x̄` and every point `y` of the
fibre of `E` at `ξ`. -/
theorem sup_stabilizer_eq_top_of_isInertiaSubgroupAt (hH : IsInertiaSubgroupAt U xb ξ H)
    [ConnectedSpace ↥(pullback U.ι xb.fromSpecStrictLocalization)] (E : FEt (U : Scheme.{u}))
    [IsConnected ((FEt.pullback (pullback.fst U.ι xb.fromSpecStrictLocalization)).obj E)]
    (y : (FEt.fiber Ω ξ).obj E) : H ⊔ MulAction.stabilizer _ y = ⊤ :=
  sup_stabilizer_eq_top_of_forall_exists_smul_eq H y
    (exists_mem_smul_eq_of_isInertiaSubgroupAt hH E y)

/-- Criterion for an inertia subgroup to generate `π₁^L(U)`: if `π₁^L(U, ξ)` is procyclic,
generated by `σ` (`φ ↦ φ σ` bijective on continuous homomorphisms to finite `L`-groups), and for
every `L`-number `m` some Galois covering of `U` of degree `m` stays connected over
`U ×_X Spec 𝒪^{sh}_{X,x̄}`, then every inertia subgroup `H` at `x̄` is dense in `π₁(U, ξ)` modulo
`proLKernel L`. -/
theorem topologicalClosure_sup_proLKernel_eq_top_of_isInertiaSubgroupAt {L : Set ℕ}
    [ConnectedSpace (U : Scheme.{u})] (hH : IsInertiaSubgroupAt U xb ξ H)
    [ConnectedSpace ↥(pullback U.ι xb.fromSpecStrictLocalization)]
    {σ : etaleFundamentalGroup Ω ξ}
    (hσ : ∀ (G : Type u) [Group G] [TopologicalSpace G] [DiscreteTopology G], IsLGroup L G →
      Function.Bijective fun φ : ContinuousMonoidHom (etaleFundamentalGroup Ω ξ) G ↦ φ σ)
    (hE : ∀ m : ℕ, m ≠ 0 → (∀ ℓ : ℕ, ℓ.Prime → ℓ ∣ m → ℓ ∈ L) → ∃ E : FEt (U : Scheme.{u}),
      IsGalois E ∧ Nat.card ((FEt.fiber Ω ξ).obj E) = m ∧
      IsConnected ((FEt.pullback (pullback.fst U.ι xb.fromSpecStrictLocalization)).obj E)) :
    (H ⊔ proLKernel L (etaleFundamentalGroup Ω ξ)).topologicalClosure = ⊤ :=
  topologicalClosure_sup_proLKernel_eq_top H fun N _ ho hL ↦ by
    obtain ⟨E, _, hcard, _⟩ := hE N.index hL.1 hL.2
    obtain ⟨y⟩ := nonempty_fiber_of_isConnected (FEt.fiber Ω ξ) E
    obtain ⟨-, h₂, h₃⟩ := stabilizer_normal_isOpen_index (FEt.fiber Ω ξ) E y
    rw [hcard] at h₃
    have hML : IsLIndex L (MulAction.stabilizer (etaleFundamentalGroup Ω ξ) y) := by
      rw [IsLIndex, h₃]
      exact hL
    have := stabilizer_normal_of_isGalois (FEt.fiber Ω ξ) E y
    have hMN := le_of_bijective_eval hσ h₂ hML ho hL (by rw [h₃])
    rw [eq_top_iff, ← sup_stabilizer_eq_top_of_isInertiaSubgroupAt hH E y]
    exact sup_le_sup_left hMN H

end Inertia

section Existence

open ExposeV

/-- Over an integral scheme `X`, for a nonempty open `U` and any geometric point `x̄` of `X`,
`U ×_X Spec 𝒪^{sh}_{X,x̄}` is nonempty: the generic point of `X` lies in `U`, and it lifts to
`Spec 𝒪^{sh}_{X,x̄}` since `𝒪_{X,x} → 𝒪^{sh}_{X,x̄}` is faithfully flat. -/
theorem nonempty_pullback_fromSpecStrictLocalization {X : Scheme.{u}} [IsIntegral X] (U : X.Opens)
    (hU : (U : Set X).Nonempty) {Ω₀ : Type u} [Field Ω₀] (xb : Spec (.of Ω₀) ⟶ X) :
    Nonempty ↥(pullback U.ι xb.fromSpecStrictLocalization) := by
  obtain ⟨w, hw⟩ := PrimeSpectrum.comap_surjective_of_faithfullyFlat
    (A := X.presheaf.stalk xb.imagePoint) (B := xb.strictLocalization) ⟨⊥, Ideal.isPrime_bot⟩
  have hfw : xb.fromSpecStrictLocalization w = genericPoint X := by
    have : Spec.map xb.toStrictLocalization w = ⟨⊥, Ideal.isPrime_bot⟩ := hw
    change X.fromSpecStalk xb.imagePoint (Spec.map xb.toStrictLocalization w) = _
    rw [this]
    exact ExposeI.fromSpecStalk_bot _
  have hmem : genericPoint X ∈ U :=
    ((genericPoint_spec X).mem_open_set_iff U.isOpen).mpr (by simpa using hU)
  have : w ∈ Set.range (pullback.snd U.ι xb.fromSpecStrictLocalization) := by
    rw [IsOpenImmersion.range_pullbackSnd, Scheme.Opens.opensRange_ι]
    change xb.fromSpecStrictLocalization w ∈ U
    rw [hfw]
    exact hmem
  obtain ⟨z, -⟩ := this
  exact ⟨z⟩

/-- Over an integral scheme `X`, inertia subgroups of `π₁(U, ξ)` at any geometric point `x̄` of `X`
exist, for every nonempty open `U` (which is connected). -/
theorem exists_isInertiaSubgroupAt {X : Scheme.{u}} [IsIntegral X] (U : X.Opens)
    (hU : (U : Set X).Nonempty) {Ω₀ : Type u} [Field Ω₀] [IsSepClosed Ω₀]
    (xb : Spec (.of Ω₀) ⟶ X) {Ω : Type u} [Field Ω] [IsSepClosed Ω]
    (ξ : Spec (.of Ω) ⟶ (U : Scheme.{u})) :
    ∃ H, IsInertiaSubgroupAt U xb ξ H := by
  have : Nonempty U := hU.to_subtype
  have : IsIntegral (U : Scheme.{u}) := isIntegral_of_isOpenImmersion U.ι
  obtain ⟨z⟩ := nonempty_pullback_fromSpecStrictLocalization U hU xb
  let η := geometricPointAt _ z
  obtain ⟨γ⟩ := etalePaths.nonempty _ Ω
    (η ≫ pullback.fst U.ι xb.fromSpecStrictLocalization) ξ
  exact ⟨_, _, inferInstance, inferInstance, η, γ, rfl⟩

/-- The image of the geometric point at `x` (`ExposeV.geometricPointAt`) is `x`. -/
lemma imagePoint_geometricPointAt {S : Scheme.{u}} (x : S) :
    (geometricPointAt S x).imagePoint = x := by
  have : geometricPointAt S x = (Scheme.SpecToEquivOfField _ S).symm
      ⟨x, CommRingCat.ofHom
        (algebraMap (S.residueField x) (AlgebraicClosure (S.residueField x)))⟩ := rfl
  rw [Scheme.Hom.imagePoint, this, Equiv.apply_symm_apply]

end Existence

end SGA.SGA1.ExposeXIII
