/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.Foundations.SchemeConnectedSpace
import SGA.SGA1.ExposeXI.MultiplicativeGroupCovering
import SGA.SGA1.ExposeXIII.AffineLinePGroups
import SGA.SGA1.ExposeXIII.CurveFundamentalGroup

/-!
# SGA 1, XIII.2.12 for `g = 0`, `n = 2`: `π₁^{p'}(𝔾_m) = Ẑ^{(p')}`

For `k` algebraically closed of characteristic `p ≥ 0`, the maximal prime-to-`p` quotient of
`π₁(𝔾_{m,k})` is the pro-`p'` completion of `ℤ` (`multiplicativeGroupPrimeToPStatement`). This is
the "in other words" part of XIII.2.12 for `X = ℙ¹`, `U = ℙ¹ - {0, ∞}`, without SGA's condition
that the generator generate an inertia group at `0`, and for `k` algebraically closed (SGA's
XIII.2.12 has `k` separably closed; its proof reduces to the algebraic closure). SGA derives it
from Riemann's existence theorem; here it is algebraic:

* `exists_bijective_eval_of_isCyclic` (group theory): a compact group whose finite quotients of
  `L`-order are cyclic, and which has such quotients of every `L`-order, has an element `σ` with
  `Hom_cont(Γ, G) ≃ G`, `φ ↦ φ σ`, for every finite `L`-group `G`;
* `isCyclic_quotient_of_isCyclic_aut` (Galois categories): `π₁ ⧸ N` is cyclic when the Galois
  covering attached to `N` (V.5.11, `ExposeV.exists_isGalois_stabilizer_eq`) has cyclic
  automorphism group;
* the connected Galois coverings of `𝔾_m` of degree prime to `p` have cyclic group
  (`SGA.SGA1.ExposeXI.MultiplicativeGroupCovering.isCyclic_algEquiv_of_laurent`, by Abhyankar's
  lemma and the case `g = 0`, `n = 1`), and the Kummer coverings `z ↦ z^m`
  (`kummerFiniteEtale`, `SGA.SGA1.ExposeXI.MultiplicativeGroupCoveringKummer`) give quotients of
  every order `m` prime to `p` (`exists_bijective_eval_aut_fiberFunctor_laurent`,
  `multiplicativeGroupPrimeToPStatement_of_isCyclic`).

For a scheme `S ≅ Spec k[T, T⁻¹]` (e.g. `ℙ¹ - {0, ∞}`): `exists_bijective_eval_of_iso` transports
the result (`bijective_eval_map`), and `kummerCovering m hm e` is the Kummer covering `z^m = T` of
`S`, Galois with fibres of `m` points (`isGalois_kummerCovering`, `card_fiber_kummerCovering`).
`isProLSurfaceGroup_of_bijective_eval` is the passage to the form `σ₁ = σ`, `σ₂ = σ⁻¹`,
`σ₁ σ₂ = 1` of the general statement.
-/

universe u w

open CategoryTheory AlgebraicGeometry
open scoped LaurentPolynomial

namespace SGA.SGA1.ExposeXIII

section ProCyclic

variable {L : Set ℕ} {Γ : Type*} [Group Γ] [TopologicalSpace Γ] [IsTopologicalGroup Γ]

omit [TopologicalSpace Γ] [IsTopologicalGroup Γ] in
/-- The kernel of a homomorphism to a finite `L`-group has `L`-index. -/
lemma isLIndex_ker {G : Type*} [Group G] (hG : IsLGroup L G) (φ : Γ →* G) :
    IsLIndex L φ.ker :=
  (isLGroup_quotient_iff φ.ker).mp
    (hG.of_injective (QuotientGroup.kerLift φ) (QuotientGroup.kerLift_injective φ))

/-- The elements of `Γ` whose image generates `Γ ⧸ N`. -/
private def generatorsMod (N : Subgroup Γ) [N.Normal] : Set Γ :=
  (QuotientGroup.mk : Γ → Γ ⧸ N) ⁻¹' {c | Subgroup.zpowers c = ⊤}

private lemma isClosed_generatorsMod (N : Subgroup Γ) [N.Normal] (ho : IsOpen (N : Set Γ)) :
    IsClosed (generatorsMod N) := by
  have := QuotientGroup.discreteTopology ho
  exact (isClosed_discrete _).preimage QuotientGroup.continuous_mk

omit [TopologicalSpace Γ] [IsTopologicalGroup Γ] in
private lemma exists_zpow_of_mem_generatorsMod {N : Subgroup Γ} [N.Normal] {σ : Γ}
    (hσ : σ ∈ generatorsMod N) (γ : Γ) : ∃ j : ℤ, γ⁻¹ * σ ^ j ∈ N := by
  simp only [generatorsMod, Set.mem_preimage, Set.mem_ofPred_eq] at hσ
  have hγ : (γ : Γ ⧸ N) ∈ Subgroup.zpowers (σ : Γ ⧸ N) := hσ ▸ Subgroup.mem_top _
  obtain ⟨j, hj⟩ := hγ
  refine ⟨j, QuotientGroup.eq.mp ?_⟩
  rw [QuotientGroup.mk_zpow]
  exact hj.symm

omit [TopologicalSpace Γ] [IsTopologicalGroup Γ] in
private lemma generatorsMod_anti {N N' : Subgroup Γ} [N.Normal] [N'.Normal] (h : N' ≤ N) :
    generatorsMod N' ⊆ generatorsMod N := by
  intro σ hσ
  simp only [generatorsMod, Set.mem_preimage, Set.mem_ofPred_eq]
  rw [eq_top_iff]
  rintro c -
  obtain ⟨γ, rfl⟩ := QuotientGroup.mk_surjective c
  obtain ⟨j, hj⟩ := exists_zpow_of_mem_generatorsMod hσ γ
  refine ⟨j, ?_⟩
  change (σ : Γ ⧸ N) ^ j = γ
  rw [← QuotientGroup.mk_zpow]
  exact (QuotientGroup.eq.mpr (h hj)).symm

/-- A compact topological group `Γ` such that every quotient by an open normal subgroup of
`L`-index is cyclic, and which has open normal subgroups of every `L`-index, is "pro-`L`-cyclic":
some `σ ∈ Γ` gives, for every finite `L`-group `G`, a bijection `φ ↦ φ σ` from the continuous
homomorphisms `Γ → G` onto `G`. That is, `Γ^L` is the pro-`L` completion of `ℤ`, topologically
generated by `σ`. -/
theorem exists_bijective_eval_of_isCyclic [CompactSpace Γ]
    (hcyc : ∀ (N : Subgroup Γ) [N.Normal], IsOpen (N : Set Γ) → IsLIndex L N → IsCyclic (Γ ⧸ N))
    (hex : ∀ m : ℕ, m ≠ 0 → (∀ p : ℕ, p.Prime → p ∣ m → p ∈ L) →
      ∃ N : Subgroup Γ, N.Normal ∧ IsOpen (N : Set Γ) ∧ N.index = m) :
    ∃ σ : Γ, ∀ (G : Type w) [Group G] [TopologicalSpace G] [DiscreteTopology G], IsLGroup L G →
      Function.Bijective fun φ : ContinuousMonoidHom Γ G ↦ φ σ := by
  classical
  -- the open normal subgroups of `L`-index
  let ι := {N : Subgroup Γ // N.Normal ∧ IsOpen (N : Set Γ) ∧ IsLIndex L N}
  let t : ι → Set Γ := fun N ↦ @generatorsMod Γ _ N.1 N.2.1
  have hι : Nonempty ι := ⟨⟨⊤, inferInstance, isOpen_univ, by
    refine ⟨by rw [Subgroup.index_top]; exact one_ne_zero, fun p hp hdvd ↦ ?_⟩
    rw [Subgroup.index_top] at hdvd
    exact absurd (Nat.le_of_dvd one_pos hdvd) (by have := hp.two_le; omega)⟩⟩
  have hdir : Directed (· ⊇ ·) t := by
    intro x y
    obtain ⟨N, hN, hNo, hNL⟩ := x
    obtain ⟨N', hN', hN'o, hN'L⟩ := y
    refine ⟨⟨N ⊓ N', Subgroup.normal_inf_normal N N', hNo.inter hN'o, hNL.inf hN'L⟩, ?_, ?_⟩
    · exact @generatorsMod_anti Γ _ N (N ⊓ N') hN (Subgroup.normal_inf_normal N N') inf_le_left
    · exact @generatorsMod_anti Γ _ N' (N ⊓ N') hN' (Subgroup.normal_inf_normal N N')
        inf_le_right
  have hne : ∀ N : ι, (t N).Nonempty := by
    intro x
    obtain ⟨N, hN, hNo, hNL⟩ := x
    obtain ⟨c, hc⟩ := (hcyc N hNo hNL).exists_generator
    obtain ⟨σ, rfl⟩ := QuotientGroup.mk_surjective c
    refine ⟨σ, ?_⟩
    change Subgroup.zpowers _ = ⊤
    exact eq_top_iff.mpr fun q _ ↦ hc q
  obtain ⟨σ, hσ⟩ := IsCompact.nonempty_iInter_of_directed_nonempty_isCompact_isClosed t hdir hne
    (fun N ↦ (@isClosed_generatorsMod Γ _ _ _ N.1 N.2.1 N.2.2.1).isCompact)
    (fun N ↦ @isClosed_generatorsMod Γ _ _ _ N.1 N.2.1 N.2.2.1)
  rw [Set.mem_iInter] at hσ
  refine ⟨σ, fun G _ _ _ hG ↦ ⟨fun φ ψ hφψ ↦ ?_, fun g ↦ ?_⟩⟩
  · -- injectivity: `φ` and `ψ` agree modulo the kernel of `(φ, ψ)`
    have := hG.1
    let χ : Γ →* G × G := (φ : Γ →* G).prod ψ
    have hχo : IsOpen (χ.ker : Set Γ) := by
      have hc : Continuous χ := (φ.continuous.prodMk ψ.continuous)
      exact (isOpen_discrete ({1} : Set (G × G))).preimage hc
    have hσχ := hσ ⟨χ.ker, χ.normal_ker, hχo, isLIndex_ker (hG.prod hG) χ⟩
    ext γ
    obtain ⟨j, hj⟩ := exists_zpow_of_mem_generatorsMod hσχ γ
    have h1 : φ (γ⁻¹ * σ ^ j) = 1 := congrArg Prod.fst ((MonoidHom.mem_ker).mp hj)
    have h2 : ψ (γ⁻¹ * σ ^ j) = 1 := congrArg Prod.snd ((MonoidHom.mem_ker).mp hj)
    simp only [map_mul, map_inv, map_zpow] at h1 h2
    have e1 : φ γ = φ σ ^ j := (inv_mul_eq_one.mp h1)
    have e2 : ψ γ = ψ σ ^ j := (inv_mul_eq_one.mp h2)
    change φ σ = ψ σ at hφψ
    rw [e1, e2, hφψ]
  · -- surjectivity: use an open normal subgroup of index the order of `g`
    have := hG.1
    have hm0 : orderOf g ≠ 0 := (orderOf_pos g).ne'
    have hmL : ∀ p : ℕ, p.Prime → p ∣ orderOf g → p ∈ L :=
      fun p hp hdvd ↦ hG.2 p hp (hdvd.trans (orderOf_dvd_natCard g))
    obtain ⟨N, hN, hNo, hNi⟩ := hex (orderOf g) hm0 hmL
    have hNL : IsLIndex L N := ⟨hNi ▸ hm0, fun p hp hdvd ↦ hmL p hp (hNi ▸ hdvd)⟩
    have hσN : σ ∈ generatorsMod N := hσ ⟨N, hN, hNo, hNL⟩
    have : N.FiniteIndex := ⟨by rw [hNi]; exact hm0⟩
    have hgen : ∀ q : Γ ⧸ N, q ∈ Subgroup.zpowers (σ : Γ ⧸ N) := fun q ↦ by
      have h : Subgroup.zpowers (σ : Γ ⧸ N) = ⊤ := hσN
      exact h ▸ Subgroup.mem_top q
    have hord : orderOf (σ : Γ ⧸ N) = orderOf g := by
      rw [orderOf_eq_card_of_forall_mem_zpowers hgen, ← Subgroup.index_eq_card, hNi]
    let φ' := monoidHomOfForallMemZpowers hgen (g' := g) hord.symm.dvd
    have := QuotientGroup.discreteTopology hNo
    exact ⟨⟨φ'.comp (QuotientGroup.mk' N),
      (continuous_of_discreteTopology (f := ⇑φ')).comp QuotientGroup.continuous_mk⟩,
      monoidHomOfForallMemZpowers_apply_gen hgen hord.symm.dvd⟩

omit [IsTopologicalGroup Γ] in
/-- Bijectivity of `φ ↦ φ σ` on the continuous homomorphisms to finite `L`-groups is transported
along isomorphisms of topological groups. -/
lemma bijective_eval_map {Γ' : Type*} [Group Γ'] [TopologicalSpace Γ'] (ψ : Γ ≃ₜ* Γ') {σ : Γ}
    (hσ : ∀ (G : Type w) [Group G] [TopologicalSpace G] [DiscreteTopology G], IsLGroup L G →
      Function.Bijective fun φ : ContinuousMonoidHom Γ G ↦ φ σ)
    (G : Type w) [Group G] [TopologicalSpace G] [DiscreteTopology G] (hG : IsLGroup L G) :
    Function.Bijective fun φ : ContinuousMonoidHom Γ' G ↦ φ (ψ σ) := by
  let Φ : ContinuousMonoidHom Γ' G ≃ ContinuousMonoidHom Γ G :=
    { toFun φ := φ.comp (ψ : Γ →ₜ* Γ')
      invFun φ := φ.comp (ψ.symm : Γ' →ₜ* Γ)
      left_inv φ := by ext; simp
      right_inv φ := by ext; simp }
  have : (fun φ : ContinuousMonoidHom Γ' G ↦ φ (ψ σ)) =
      (fun φ : ContinuousMonoidHom Γ G ↦ φ σ) ∘ Φ := by
    ext φ
    rfl
  rw [this]
  exact (hσ G hG).comp Φ.bijective

omit [IsTopologicalGroup Γ] in
/-- XIII.2.12 for `g = 0`, `n = 2`, group theory: if `φ ↦ φ σ` is bijective on the continuous
homomorphisms to finite `L`-groups (`Γ^L` is the pro-`L` completion of `ℤ`, generated by `σ`), then
`σ₁ = σ`, `σ₂ = σ⁻¹` present `Γ^L` as the pro-`L` group generated by `σ₁, σ₂` with the relation
`σ₁ σ₂ = 1` (`IsProLSurfaceGroup`). -/
theorem isProLSurfaceGroup_of_bijective_eval {σ : Γ}
    (hσ : ∀ (G : Type w) [Group G] [TopologicalSpace G] [DiscreteTopology G], IsLGroup L G →
      Function.Bijective fun φ : ContinuousMonoidHom Γ G ↦ φ σ) :
    IsProLSurfaceGroup.{w} L (Fin.elim0 : Fin 0 → Γ) Fin.elim0 ![σ, σ⁻¹] := by
  refine ⟨?_, fun G _ _ _ hG ↦ ⟨fun φ ψ _ _ h ↦ (hσ G hG).1 ?_, fun x' y' σ' h ↦ ?_⟩⟩
  · rw [surfaceWord_genus_zero]
    simp only [List.ofFn_succ, List.ofFn_zero, Matrix.cons_val_zero, Matrix.cons_val_succ,
      List.prod_cons, List.prod_nil, mul_one, mul_inv_cancel]
    exact one_mem _
  · exact congrFun h 0
  · obtain ⟨φ, hφ⟩ := (hσ G hG).2 (σ' 0)
    change φ σ = σ' 0 at hφ
    refine ⟨φ, funext fun i ↦ i.elim0, funext fun i ↦ i.elim0, funext fun j ↦ ?_⟩
    rw [surfaceWord_genus_zero] at h
    simp only [List.ofFn_succ, List.ofFn_zero, List.prod_cons, List.prod_nil, mul_one] at h
    fin_cases j
    · exact hφ
    · change φ σ⁻¹ = σ' 1
      rw [map_inv, hφ]
      exact inv_eq_of_mul_eq_one_right h

end ProCyclic

section GaloisCategory

open PreGaloisCategory

variable {C : Type*} [Category* C] [GaloisCategory C] (F : C ⥤ FintypeCat.{w}) [FiberFunctor F]

/-- A connected object with at least as many automorphisms as points in its fibre is Galois. -/
lemma isGalois_of_card_fiber_le (X : C) [IsConnected X]
    (h : Nat.card (F.obj X) ≤ Nat.card (Aut X)) : IsGalois X := by
  obtain ⟨x⟩ := nonempty_fiber_of_isConnected F X
  have hinj := evaluation_aut_injective_of_isConnected F X x
  have : Finite (Aut X) := Finite.of_injective _ hinj
  have hbij : Function.Bijective (fun f : Aut X ↦ F.map f.hom x) :=
    (Function.Injective.bijective_of_nat_card_le hinj h)
  rw [isGalois_iff_pretransitive F X]
  refine ⟨fun y z ↦ ?_⟩
  obtain ⟨f, rfl⟩ := hbij.2 y
  obtain ⟨g, rfl⟩ := hbij.2 z
  refine ⟨g * f⁻¹, ?_⟩
  have key (f g : X ≅ X) : F.map (f.inv ≫ g.hom) (F.map f.hom x) = F.map g.hom x := by
    rw [F.map_comp, FintypeCat.comp_apply, ← FintypeCat.comp_apply (F.map f.hom), ← F.map_comp,
      Iso.hom_inv_id, F.map_id, FintypeCat.id_apply]
  exact key f g

variable {F} in
/-- For a Galois object `X` with commutative automorphism group and a point `x` of its fibre,
`σ ↦ (the automorphism of X sending x to σ x)` is a homomorphism `Aut F →* Aut X` with kernel the
stabilizer of `x`. -/
noncomputable def autHomOfComm (X : C) [IsGalois X] (x : F.obj X)
    (hc : ∀ a b : Aut X, a * b = b * a) : Aut F →* Aut X where
  toFun σ := (evaluationEquivOfIsGalois F X x).symm (σ • x)
  map_one' := by
    apply evaluation_aut_injective_of_isConnected F X x
    beta_reduce
    rw [evaluationEquivOfIsGalois_symm_fiber, one_smul]
    change x = F.map (𝟙 X) x
    rw [F.map_id, FintypeCat.id_apply]
  map_mul' σ τ := by
    rw [hc]
    apply evaluation_aut_injective_of_isConnected F X x
    beta_reduce
    rw [evaluationEquivOfIsGalois_symm_fiber]
    have key (a b : X ≅ X) (ha : F.map a.hom x = σ • x) (hb : F.map b.hom x = τ • x) :
        (σ * τ) • x = F.map (a.hom ≫ b.hom) x := by
      rw [F.map_comp, FintypeCat.comp_apply, ha, ← mulAction_naturality, hb, mul_smul]
    exact key _ _ (evaluationEquivOfIsGalois_symm_fiber F X x (σ • x))
      (evaluationEquivOfIsGalois_symm_fiber F X x (τ • x))

lemma autHomOfComm_apply_fiber (X : C) [IsGalois X] (x : F.obj X)
    (hc : ∀ a b : Aut X, a * b = b * a) (σ : Aut F) :
    F.map ((autHomOfComm X x hc) σ).hom x = σ • x :=
  evaluationEquivOfIsGalois_symm_fiber F X x (σ • x)

lemma ker_autHomOfComm (X : C) [IsGalois X] (x : F.obj X)
    (hc : ∀ a b : Aut X, a * b = b * a) :
    (autHomOfComm X x hc).ker = MulAction.stabilizer (Aut F) x := by
  ext σ
  rw [MonoidHom.mem_ker, MulAction.mem_stabilizer_iff, ← autHomOfComm_apply_fiber F X x hc σ]
  constructor
  · intro h
    rw [h]
    change F.map (𝟙 X) x = x
    rw [F.map_id, FintypeCat.id_apply]
  · intro h
    apply evaluation_aut_injective_of_isConnected F X x
    change _ = F.map (𝟙 X) x
    rw [F.map_id, FintypeCat.id_apply]
    exact h

/-- If `N` is the stabilizer of the points of the fibre of a Galois object `X` whose automorphism
group is cyclic, then `Aut F ⧸ N` is cyclic. -/
theorem isCyclic_quotient_of_isCyclic_aut (N : Subgroup (Aut F)) [N.Normal] (X : C) [IsGalois X]
    [IsCyclic (Aut X)] (x : F.obj X) (hx : MulAction.stabilizer (Aut F) x = N) :
    IsCyclic (Aut F ⧸ N) := by
  have hc : ∀ a b : Aut X, a * b = b * a := fun a b ↦ IsCyclic.commGroup.mul_comm a b
  let ρ := autHomOfComm X x hc
  have hker : ρ.ker = N := (ker_autHomOfComm F X x hc).trans hx
  have e : Aut F ⧸ N ≃* ρ.range :=
    (QuotientGroup.quotientMulEquivOfEq hker.symm).trans (QuotientGroup.quotientKerEquivRange ρ)
  have : IsCyclic ρ.range := Subgroup.isCyclic ρ.range
  exact isCyclic_of_surjective e.symm.toMonoidHom e.symm.surjective

/-- The stabilizer of a point of the fibre of a connected Galois object `Y` is an open normal
subgroup of index `#F(Y)`. -/
theorem stabilizer_normal_isOpen_index (Y : C) [IsGalois Y] (y : F.obj Y) :
    (MulAction.stabilizer (Aut F) y).Normal ∧ IsOpen (MulAction.stabilizer (Aut F) y : Set (Aut F))
      ∧ (MulAction.stabilizer (Aut F) y).index = Nat.card (F.obj Y) :=
  ⟨stabilizer_normal_of_isGalois F Y y, stabilizer_isOpen (Aut F) y,
    MulAction.index_stabilizer_of_transitive (Aut F) y⟩

end GaloisCategory

section MultiplicativeGroup

open PreGaloisCategory Module

/-- XIII.2.12 for `g = 0`, `n = 2`, group structure (statement): `π₁^{p'}(𝔾_{m,k})` is the
pro-`p'` completion of `ℤ`. For `k` algebraically closed of characteristic `p` and every geometric
point `ξ` of `𝔾_{m,k} = Spec k[T, T⁻¹]`, some `σ ∈ π₁(𝔾_m, ξ)` gives, for every finite group `G`
of order prime to `p`, a bijection `φ ↦ φ σ` from the continuous homomorphisms `π₁(𝔾_m, ξ) → G`
onto `G`. This is the "in other words" part of XIII.2.12 for `X = ℙ¹`, `U = ℙ¹ - {0, ∞}` (where
`σ₁ = σ`, `σ₂ = σ⁻¹`), with three deviations: it is stated on the model `Spec k[T, T⁻¹]` of
`ℙ¹ - {0, ∞}`; `k` is algebraically closed (SGA: separably closed); and SGA's condition that `σ`
generate an inertia group at `0` is not included. For `p = 0` it says that `π₁(𝔾_m)` is `Ẑ`. -/
def MultiplicativeGroupPrimeToPStatement (p : ℕ) : Prop :=
  ∀ (k : Type u) [Field k] [IsAlgClosed k] [CharP k p] (Ω : Type u) [Field Ω] [IsSepClosed Ω]
    (ξ : Spec (.of Ω) ⟶ Spec (.of k[T;T⁻¹])),
    ∃ σ : ExposeV.etaleFundamentalGroup Ω ξ,
      ∀ (G : Type u) [Group G] [TopologicalSpace G] [DiscreteTopology G],
        IsLGroup (primesDifferentFrom p) G →
        Function.Bijective fun φ : ContinuousMonoidHom (ExposeV.etaleFundamentalGroup Ω ξ) G ↦ φ σ

/-- In characteristic `p`, an integer with all its prime factors different from `p` is nonzero
in `k`. -/
lemma natCast_ne_zero_of_primesDifferentFrom {k : Type*} [Field k] {p : ℕ} [CharP k p] {m : ℕ}
    (hm : m ≠ 0) (hL : ∀ ℓ : ℕ, ℓ.Prime → ℓ ∣ m → ℓ ∈ primesDifferentFrom p) : (m : k) ≠ 0 := by
  intro h
  rw [CharP.cast_eq_zero_iff k p] at h
  rcases CharP.char_is_prime_or_zero k p with hp | rfl
  · exact (hL p hp h).2 rfl
  · exact hm (Nat.eq_zero_of_zero_dvd h)

section Kummer

variable (k : Type u) [Field k] (m : ℕ) [NeZero m] (hm : (m : k) ≠ 0)

/-- The Kummer algebra `k[T, T⁻¹][z]/(z^m - T)`, as a finite étale `k[T, T⁻¹]`-algebra (`m`
invertible in `k`). -/
noncomputable def kummerFiniteEtale : CommAlgCat.FiniteEtale.{u} k[T;T⁻¹] :=
  haveI := ExposeXI.etale_kummer (k := k) hm
  CommAlgCat.FiniteEtale.of k[T;T⁻¹] (ExposeXI.KummerAlgebra k[T;T⁻¹] m (LaurentPolynomial.T 1))

lemma isConnected_kummerFiniteEtale : IsConnected (Opposite.op (kummerFiniteEtale k m hm)) :=
  (ExposeV.isConnected_op_iff_connectedSpace k[T;T⁻¹] _).mpr
    (inferInstanceAs (ConnectedSpace (PrimeSpectrum
      (ExposeXI.KummerAlgebra k[T;T⁻¹] m (LaurentPolynomial.T 1)))))

/-- The fibres of the Kummer covering of degree `m` have `m` points. -/
lemma card_fiberFunctor_kummerFiniteEtale (Ω : Type u) [Field Ω] [IsSepClosed Ω]
    [Algebra k[T;T⁻¹] Ω] :
    Nat.card ((ExposeV.fiberFunctor k[T;T⁻¹] Ω).obj (Opposite.op (kummerFiniteEtale k m hm))) =
      m := by
  have h := ExposeV.card_fiber_eq_rankAtStalk k[T;T⁻¹] Ω (kummerFiniteEtale k m hm)
    (Classical.arbitrary _)
  rw [Module.rankAtStalk_eq_finrank_of_free] at h
  have := ExposeXI.etale_kummer (k := k) hm
  exact h.trans ExposeXI.Kummer.finrank_eq

/-- The Kummer covering of degree `m` has at least `m` automorphisms (`z ↦ ζ z`, `ζ ∈ μ_m(k)`). -/
lemma le_card_aut_kummerFiniteEtale [IsSepClosed k] :
    m ≤ Nat.card (Aut (Opposite.op (kummerFiniteEtale k m hm))) := by
  rw [Nat.card_congr (autOpEquivAlgEquiv (kummerFiniteEtale k m hm))]
  exact ExposeXI.card_le_card_algEquiv_kummer hm

variable {k} {S : Scheme.{u}} (e : S ≅ Spec (.of k[T;T⁻¹]))

/-- The Kummer covering `z ↦ z^m = T` of a scheme `S` identified with `𝔾_m = Spec k[T, T⁻¹]` by
`e`. -/
noncomputable def kummerCovering : ExposeV.FEt S :=
  (ExposeV.FEt.pullback e.hom).obj
    ((ExposeV.specFunctor (.of k[T;T⁻¹])).obj (Opposite.op (kummerFiniteEtale k m hm)))

lemma isConnected_kummerCovering : IsConnected (kummerCovering m hm e) := by
  have : ConnectedSpace ↥((ExposeV.specFunctor (.of k[T;T⁻¹])).obj
      (Opposite.op (kummerFiniteEtale k m hm))).left :=
    inferInstanceAs (ConnectedSpace (PrimeSpectrum
      (ExposeXI.KummerAlgebra k[T;T⁻¹] m (LaurentPolynomial.T 1))))
  have : ConnectedSpace ↥((𝟭 Scheme).obj ((ExposeV.specFunctor (.of k[T;T⁻¹])).obj
      (Opposite.op (kummerFiniteEtale k m hm))).left) := this
  have hi : IsIso (Limits.pullback.fst ((ExposeV.specFunctor (.of k[T;T⁻¹])).obj
      (Opposite.op (kummerFiniteEtale k m hm))).hom e.hom) :=
    Limits.pullback_fst_iso_of_right_iso _ _
  have : ConnectedSpace ↥(kummerCovering m hm e).left :=
    Scheme.connectedSpace_of_iso (@asIso _ _ _ _ (Limits.pullback.fst _ e.hom) hi)
  exact ExposeV.FEt.isConnected_of_connectedSpace _

/-- The fibres of the Kummer covering of degree `m` of `S ≅ 𝔾_m` have `m` points. -/
lemma card_fiber_kummerCovering (Ω : Type u) [Field Ω] [IsSepClosed Ω] (ξ : Spec (.of Ω) ⟶ S) :
    Nat.card ((ExposeV.FEt.fiber Ω ξ).obj (kummerCovering m hm e)) = m := by
  let := ExposeV.algebraOfPoint (CommRingCat.of k[T;T⁻¹]) Ω (ξ ≫ e.hom)
  let K := (ExposeV.specFunctor (.of k[T;T⁻¹])).obj (Opposite.op (kummerFiniteEtale k m hm))
  let e₁ := (ExposeV.FEt.pullbackFiberIso Ω e.hom ξ).app K
  let e₂ := (ExposeV.FEt.fiberSpecIso (CommRingCat.of k[T;T⁻¹]) Ω (ξ ≫ e.hom)).app K
  let e₃ := (ExposeV.fiberFunctor k[T;T⁻¹] Ω).mapIso
    ((ExposeV.specEquivalence (CommRingCat.of k[T;T⁻¹])).unitIso.app
      (Opposite.op (kummerFiniteEtale k m hm))).symm
  have h : Nat.card ((ExposeV.FEt.fiber Ω ξ).obj (kummerCovering m hm e)) =
      Nat.card ((ExposeV.fiberFunctor k[T;T⁻¹] Ω).obj (Opposite.op (kummerFiniteEtale k m hm))) :=
    Nat.card_congr (FintypeCat.equivEquivIso.symm (e₁ ≪≫ e₂ ≪≫ e₃))
  rw [h, card_fiberFunctor_kummerFiniteEtale]

/-- The Kummer covering of degree `m` of `S ≅ 𝔾_m` has at least `m` automorphisms. -/
lemma le_card_aut_kummerCovering [IsSepClosed k] : m ≤ Nat.card (Aut (kummerCovering m hm e)) := by
  have hff := Functor.FullyFaithful.ofFullyFaithful (ExposeV.FEt.pullback e.hom)
  have h : Nat.card (Aut (kummerCovering m hm e)) =
      Nat.card (Aut (Opposite.op (kummerFiniteEtale k m hm))) :=
    (Nat.card_congr
      ((ExposeV.specFunctorFullyFaithful (.of k[T;T⁻¹])).isoEquiv.trans hff.isoEquiv)).symm
  rw [h]
  exact le_card_aut_kummerFiniteEtale k m hm

/-- The Kummer covering of degree `m` of `S ≅ 𝔾_m` is Galois. -/
lemma isGalois_kummerCovering [IsSepClosed k] [ConnectedSpace S] (Ω : Type u) [Field Ω]
    [IsSepClosed Ω] (ξ : Spec (.of Ω) ⟶ S) :
    PreGaloisCategory.IsGalois (kummerCovering m hm e) := by
  have := isConnected_kummerCovering m hm e
  exact isGalois_of_card_fiber_le (ExposeV.FEt.fiber Ω ξ) _
    (by rw [card_fiber_kummerCovering]; exact le_card_aut_kummerCovering m hm e)

end Kummer

/-- The `π₁`-level argument for XIII.2.12 with `g = 0`, `n = 2`, over `Aut` of the fibre functor
of finite étale `k[T, T⁻¹]`-algebras: if every connected Galois covering of `𝔾_{m,k}` of degree
prime to `p` has cyclic group, then `π₁^{p'}` is the pro-`p'` completion of `ℤ`. The Kummer
coverings `z ↦ z^m` give the quotients of order `m`. -/
theorem exists_bijective_eval_aut_fiberFunctor_laurent (p : ℕ) (k : Type u) [Field k]
    [IsAlgClosed k] [CharP k p] (Ω : Type u) [Field Ω] [IsSepClosed Ω] [Algebra k[T;T⁻¹] Ω]
    (hcyc : ∀ (A : Type u) [CommRing A] [IsDomain A] [Algebra k[T;T⁻¹] A]
      [Algebra.Etale k[T;T⁻¹] A] [Module.Finite k[T;T⁻¹] A] [Finite (A ≃ₐ[k[T;T⁻¹]] A)],
      finrank k[T;T⁻¹] A ≤ Nat.card (A ≃ₐ[k[T;T⁻¹]] A) → (finrank k[T;T⁻¹] A : k) ≠ 0 →
      IsCyclic (A ≃ₐ[k[T;T⁻¹]] A)) :
    ∃ σ : Aut (ExposeV.fiberFunctor k[T;T⁻¹] Ω),
      ∀ (G : Type u) [Group G] [TopologicalSpace G] [DiscreteTopology G],
        IsLGroup (primesDifferentFrom p) G →
        Function.Bijective fun φ : ContinuousMonoidHom (Aut (ExposeV.fiberFunctor k[T;T⁻¹] Ω)) G ↦
          φ σ := by
  let F := ExposeV.fiberFunctor k[T;T⁻¹] Ω
  refine exists_bijective_eval_of_isCyclic (fun N _ ho hNL ↦ ?_) (fun m hm hmL ↦ ?_)
  · -- the Galois covering attached to `N` has cyclic group
    obtain ⟨X, x, hg, hx⟩ := ExposeV.exists_isGalois_stabilizer_eq F ⟨N, ho⟩ inferInstance
    replace hx : MulAction.stabilizer (Aut F) x = N := hx
    let A := X.unop
    have : ConnectedSpace (PrimeSpectrum A.obj) :=
      (ExposeV.isConnected_op_iff_connectedSpace k[T;T⁻¹] A).mp inferInstance
    have : IsDomain A.obj := isDomain_of_etale_of_connectedSpace (R := k[T;T⁻¹])
    have hcard : Nat.card (F.obj X) = N.index := by
      rw [← hx, MulAction.index_stabilizer_of_transitive]
    have hAut : Nat.card (A.obj ≃ₐ[k[T;T⁻¹]] A.obj) = N.index := by
      rw [← Nat.card_congr (autOpEquivAlgEquiv A),
        Nat.card_congr (evaluationEquivOfIsGalois F X x), hcard]
    have : Finite (A.obj ≃ₐ[k[T;T⁻¹]] A.obj) := Nat.finite_of_card_ne_zero (hAut ▸ hNL.1)
    have hrank : finrank k[T;T⁻¹] A.obj = N.index := by
      have h := ExposeV.card_fiber_eq_rankAtStalk k[T;T⁻¹] Ω A (Classical.arbitrary _)
      rw [Module.rankAtStalk_eq_finrank_of_free] at h
      exact h.symm.trans hcard
    have hcycA := hcyc A.obj (by rw [hrank, hAut]) (by
      rw [hrank]; exact natCast_ne_zero_of_primesDifferentFrom hNL.1 hNL.2)
    -- `Aut X` is the opposite of the cyclic group `Aut_{k[T, T⁻¹]}(A)`
    have : IsCyclic (Aut X)ᵐᵒᵖ :=
      isCyclic_of_surjective (AffineLinePGroups.autOpMulEquivAlgEquiv A).symm.toMonoidHom
        (AffineLinePGroups.autOpMulEquivAlgEquiv A).symm.surjective
    have : IsCyclic (Aut X) :=
      isCyclic_of_surjective (MulEquiv.inv' (Aut X)).symm.toMonoidHom
        (MulEquiv.inv' (Aut X)).symm.surjective
    exact isCyclic_quotient_of_isCyclic_aut F N X x hx
  · -- the Kummer covering of degree `m`
    have hmk : (m : k) ≠ 0 := natCast_ne_zero_of_primesDifferentFrom hm hmL
    have : NeZero m := ⟨hm⟩
    let Y := Opposite.op (kummerFiniteEtale k m hmk)
    have := isConnected_kummerFiniteEtale k m hmk
    have hcardY : Nat.card (F.obj Y) = m := card_fiberFunctor_kummerFiniteEtale k m hmk Ω
    have : IsGalois Y :=
      isGalois_of_card_fiber_le F Y (hcardY ▸ le_card_aut_kummerFiniteEtale k m hmk)
    obtain ⟨y⟩ := nonempty_fiber_of_isConnected F Y
    obtain ⟨h1, h2, h3⟩ := stabilizer_normal_isOpen_index F Y y
    exact ⟨_, h1, h2, h3.trans hcardY⟩

/-- XIII.2.12 for `g = 0`, `n = 2` (group structure), reduced to algebra: if every connected
Galois covering of `𝔾_{m,k}` of degree prime to the characteristic has cyclic group, then
`MultiplicativeGroupPrimeToPStatement` holds. -/
theorem multiplicativeGroupPrimeToPStatement_of_isCyclic (p : ℕ)
    (hcyc : ∀ (k : Type u) [Field k] [IsAlgClosed k] [CharP k p] (A : Type u) [CommRing A]
      [IsDomain A] [Algebra k[T;T⁻¹] A] [Algebra.Etale k[T;T⁻¹] A] [Module.Finite k[T;T⁻¹] A]
      [Finite (A ≃ₐ[k[T;T⁻¹]] A)],
      finrank k[T;T⁻¹] A ≤ Nat.card (A ≃ₐ[k[T;T⁻¹]] A) → (finrank k[T;T⁻¹] A : k) ≠ 0 →
      IsCyclic (A ≃ₐ[k[T;T⁻¹]] A)) :
    MultiplicativeGroupPrimeToPStatement.{u} p := by
  intro k _ _ _ Ω _ _ ξ
  let := ExposeV.algebraOfPoint (CommRingCat.of k[T;T⁻¹]) Ω ξ
  let ψ := fundamentalGroupSpecContinuousMulEquiv k[T;T⁻¹] Ω ξ
  obtain ⟨σ, hσ⟩ := exists_bijective_eval_aut_fiberFunctor_laurent p k Ω (hcyc k)
  -- transport along `ψ : Aut F ≃ₜ* π₁(𝔾_m, ξ)`
  exact ⟨ψ σ, bijective_eval_map ψ hσ⟩

/-- XIII.2.12 for `g = 0`, `n = 2` (group structure): `π₁^{p'}(𝔾_{m,k})` is the pro-`p'` completion
of `ℤ`, for `k` algebraically closed of characteristic `p`. Proved algebraically: every connected
Galois covering of `𝔾_m` of degree prime to `p` is a Kummer covering
(`ExposeXI.MultiplicativeGroupCovering.isCyclic_algEquiv_of_laurent`, by Abhyankar's lemma and
the case of `𝔸¹`), and the Kummer coverings give quotients of every order prime to `p`. -/
theorem multiplicativeGroupPrimeToPStatement (p : ℕ) :
    MultiplicativeGroupPrimeToPStatement.{u} p :=
  multiplicativeGroupPrimeToPStatement_of_isCyclic p fun _ _ _ _ _ _ _ _ _ _ _ hG hp ↦
    ExposeXI.MultiplicativeGroupCovering.isCyclic_algEquiv_of_laurent hG hp

/-- XIII.2.12 for `g = 0`, `n = 2` (group structure), transported to a scheme `S` isomorphic to
`𝔾_m = Spec k[T, T⁻¹]` (e.g. `ℙ¹ - {0, ∞}` or `D(t) ⊆ 𝔸¹`): `π₁^{p'}(S, ξ)` is the pro-`p'`
completion of `ℤ`. -/
theorem exists_bijective_eval_of_iso (p : ℕ) (k : Type u) [Field k] [IsAlgClosed k] [CharP k p]
    {S : Scheme.{u}} (e : S ≅ Spec (.of k[T;T⁻¹])) (Ω : Type u) [Field Ω] [IsSepClosed Ω]
    (ξ : Spec (.of Ω) ⟶ S) :
    ∃ σ : ExposeV.etaleFundamentalGroup Ω ξ,
      ∀ (G : Type u) [Group G] [TopologicalSpace G] [DiscreteTopology G],
        IsLGroup (primesDifferentFrom p) G →
        Function.Bijective fun φ : ContinuousMonoidHom (ExposeV.etaleFundamentalGroup Ω ξ) G ↦
          φ σ := by
  have : ConnectedSpace S := Scheme.connectedSpace_of_iso e
  let ψ := ExposeV.autContinuousMulEquiv (ExposeV.FEt.pullback e.hom)
    (ExposeV.FEt.pullbackFiberIso Ω e.hom ξ)
  obtain ⟨σ₀, hσ₀⟩ := multiplicativeGroupPrimeToPStatement p k Ω (ξ ≫ e.hom)
  exact ⟨ψ.symm σ₀, bijective_eval_map ψ.symm hσ₀⟩

/-- XIII.2.12 for `g = 0`, `n = 2`, in the form of the general statement (group structure, on the
model `𝔾_m = Spec k[T, T⁻¹]` of `ℙ¹ - {0, ∞}`): `σ₁ = σ`, `σ₂ = σ⁻¹` present `π₁^{p'}(𝔾_m)` as the
pro-`p'` group generated by `σ₁, σ₂` with the relation `σ₁ σ₂ = 1` (`IsProLSurfaceGroup`). The
inertia condition of XIII.2.12 is not included. -/
theorem exists_isProLSurfaceGroup_multiplicativeGroup (p : ℕ) (k : Type u) [Field k]
    [IsAlgClosed k] [CharP k p] (Ω : Type u) [Field Ω] [IsSepClosed Ω]
    (ξ : Spec (.of Ω) ⟶ Spec (.of k[T;T⁻¹])) :
    ∃ σ : Fin 2 → ExposeV.etaleFundamentalGroup Ω ξ,
      IsProLSurfaceGroup.{u} (primesDifferentFrom p) (Fin.elim0 : Fin 0 → _) Fin.elim0 σ := by
  obtain ⟨σ, hσ⟩ := multiplicativeGroupPrimeToPStatement p k Ω ξ
  exact ⟨_, isProLSurfaceGroup_of_bijective_eval hσ⟩

end MultiplicativeGroup

end SGA.SGA1.ExposeXIII
