/-
Copyright (c) 2026 SGAenglishpluslean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SGAenglishpluslean contributors
-/
import Mathlib.FieldTheory.IsAlgClosed.AlgebraicClosure
import Mathlib.RingTheory.DiscreteValuationRing.TFAE
import Mathlib.RingTheory.Ideal.GoingUp
import Mathlib.RingTheory.Ideal.HasGoingUp
import Mathlib.RingTheory.Polynomial.Eisenstein.Basic
import Mathlib.RingTheory.Polynomial.GaussLemma
import Mathlib.RingTheory.Polynomial.UniqueFactorization
import Mathlib.RingTheory.RegularLocalRing.Defs
import SGA.SGA1.ExposeXIII.KummerCoverings
import SGA.SGA1.ExposeXIII.RegularLocalRing
import SGA.SGA1.ExposeXIII.TameRamification

/-!
# SGA 1, Exposé XIII, XIII.5.1: adjoining roots of parameters

Proposition XIII.5.1: let `X = Spec A` be a regular local scheme and `f₁, …, f_r` part of a
regular system of parameters, `D = Σ div fᵢ`, `U = X - Supp D`, and
`X' = X[T₁, …, T_r]/(T₁^{n₁} - f₁, …, T_r^{n_r} - f_r)`. Then `X'` is regular, `U' = U ×_X X'`
is the complement of `Σ div Tᵢ`, and if the `nᵢ` are prime to the residue characteristic, `U'` is
a connected étale covering of `U`, tamely ramified along `D`.

For the ring `A' = A[Tᵢ]/(Tᵢ^{nᵢ} - fᵢ)` (`KummerAlgebra n f`), with all `nᵢ > 0`, we prove:

* `A'` is integral over `A` and `Spec A' → Spec A` is surjective, so `dim A ≤ dim A'`;
* `A'` is local with maximal ideal `m_A A' + (T₁, …, T_r)`, generated by the `Tᵢ` and the
  complementary parameters of `A`; it is a regular local ring of the same dimension as `A`, and the
  `Tᵢ` are part of a regular system of parameters (`isRegularLocalRing`,
  `isPartOfRegularSystemOfParameters_T`);
* `A'` is a domain (`RegularLocalRing`), so `U' = X' - V(∏ Tᵢ)` is connected;
* a prime of `A'` contains `∏ fᵢ` iff it contains `∏ Tᵢ` (`U'` is the complement of `Σ div Tᵢ`);
* `U' = Spec (A_f ⊗_A A')` is étale over `U = Spec A_f` when the `nᵢ` are invertible in `A`.

Tame ramification along `D` is proved in the one-dimensional case: when `A` is a discrete
valuation ring with uniformizer `π`, `R' = R[T]/(Tⁿ - π)` is a discrete valuation ring with
uniformizer `T`, ramification index `n` and trivial residue extension, tamely ramified over `R`
when `n` is prime to the residue characteristic, and its generic fibre `K[T]/(Tⁿ - π)` is a
field, étale over `K`. In higher dimension it would need the local rings of `X'` at the generic
points of the `V(Tᵢ)` (normality of regular rings), which is not formalized.
-/

open IsLocalRing
open scoped TensorProduct

namespace SGA.SGA1.ExposeXIII

/-- XIII.5.1: the family `f` is part of a regular system of parameters of the local ring `A`:
together with a family `g` it generates the maximal ideal, with `dim A` elements in all. -/
def IsPartOfRegularSystemOfParameters {A : Type*} [CommRing A] [IsLocalRing A] {ι : Type*}
    (f : ι → A) : Prop :=
  ∃ (k : ℕ) (g : Fin k → A), maximalIdeal A = Ideal.span (Set.range f ∪ Set.range g) ∧
    ((Nat.card ι + k : ℕ) : WithBot ℕ∞) = ringKrullDim A

/-- The members of a regular system of parameters are nonzero. -/
theorem IsPartOfRegularSystemOfParameters.ne_zero {A : Type*} [CommRing A] [IsRegularLocalRing A]
    {ι : Type*} [Finite ι] {f : ι → A} (hf : IsPartOfRegularSystemOfParameters f) (i : ι) :
    f i ≠ 0 := by
  obtain ⟨k, g, hmax, hdim⟩ := hf
  intro h0
  set S := Set.range f ∪ Set.range g
  have hfin : S.Finite := (Set.finite_range f).union (Set.finite_range g)
  have h1 : (maximalIdeal A).spanFinrank ≤ (S \ {0}).ncard := by
    rw [hmax, ← Ideal.span_sdiff_singleton_zero]
    exact Submodule.spanFinrank_span_le_ncard_of_finite hfin.sdiff
  have h2 : (S \ {0}).ncard < S.ncard := Set.ncard_sdiff_singleton_lt_of_mem (Or.inl ⟨i, h0⟩) hfin
  have h3 : S.ncard ≤ Nat.card ι + k := by
    refine (Set.ncard_union_le _ _).trans (Nat.add_le_add ?_ ?_)
    · rw [← Set.image_univ, ← Set.ncard_univ]
      exact Set.ncard_image_le (Set.toFinite _)
    · have := Set.ncard_image_le (f := g) (s := Set.univ) (Set.toFinite _)
      rwa [Set.image_univ, Set.ncard_univ, Nat.card_fin] at this
  have h4 : ((maximalIdeal A).spanFinrank : WithBot ℕ∞) = ((Nat.card ι + k : ℕ) : WithBot ℕ∞) := by
    rw [IsRegularLocalRing.spanFinrank_maximalIdeal, hdim]
  have h5 : (maximalIdeal A).spanFinrank = Nat.card ι + k := by exact_mod_cast h4
  omega

namespace KummerAlgebra

open MvPolynomial

variable {A : Type*} [CommRing A] {ι : Type*} (n : ι → ℕ) (f : ι → A)

/-- `A[Tᵢ]/(Tᵢ^{nᵢ} - fᵢ)` is generated by the `Tᵢ`. -/
theorem adjoin_range_T : Algebra.adjoin A (Set.range (T n f)) = ⊤ := by
  have : Set.range (T n f) = Ideal.Quotient.mkₐ A _ '' Set.range X := by
    rw [← Set.range_comp]; rfl
  rw [this, ← AlgHom.map_adjoin, MvPolynomial.adjoin_range_X, Algebra.map_top,
    AlgHom.range_eq_top]
  exact Ideal.Quotient.mkₐ_surjective A _

variable {n} in
/-- `X' → X` is finite: `A[Tᵢ]/(Tᵢ^{nᵢ} - fᵢ)` is integral over `A`. -/
theorem isIntegral (hn : ∀ i, 0 < n i) : Algebra.IsIntegral A (KummerAlgebra n f) := by
  have : Algebra.adjoin A (Set.range (T n f)) ≤ integralClosure A (KummerAlgebra n f) := by
    rw [Algebra.adjoin_le_iff]
    rintro _ ⟨i, rfl⟩
    refine ⟨Polynomial.X ^ n i - Polynomial.C (f i), Polynomial.monic_X_pow_sub_C _ (hn i).ne', ?_⟩
    simp [Polynomial.eval₂_sub, T_pow]
  rw [adjoin_range_T, top_le_iff] at this
  exact ⟨fun x ↦ (this ▸ Algebra.mem_top : x ∈ integralClosure A _)⟩

variable {n} in
/-- `X' → X` is surjective: every prime of `A` is under a prime of `A[Tᵢ]/(Tᵢ^{nᵢ} - fᵢ)`
(send `Tᵢ` to an `nᵢ`-th root of `fᵢ` in an algebraic closure of the residue field). -/
theorem exists_liesOver (hn : ∀ i, 0 < n i) (p : Ideal A) [p.IsPrime] :
    ∃ P : Ideal (KummerAlgebra n f), P.IsPrime ∧ P.LiesOver p := by
  let K := AlgebraicClosure p.ResidueField
  choose x hx using fun i ↦ IsAlgClosed.exists_pow_nat_eq (algebraMap A K (f i)) (hn i)
  let φ := lift (n := n) (f := f) x hx
  refine ⟨RingHom.ker φ, RingHom.ker_isPrime _, ⟨?_⟩⟩
  ext a
  rw [Ideal.under, Ideal.mem_comap, RingHom.mem_ker, AlgHom.commutes,
    IsScalarTower.algebraMap_apply A p.ResidueField K,
    map_eq_zero_iff (algebraMap p.ResidueField K) (FaithfulSMul.algebraMap_injective _ _),
    Ideal.algebraMap_residueField_eq_zero]

variable {n} in
/-- `dim A ≤ dim A[Tᵢ]/(Tᵢ^{nᵢ} - fᵢ)`, by going up and lying over. -/
theorem ringKrullDim_le (hn : ∀ i, 0 < n i) :
    ringKrullDim A ≤ ringKrullDim (KummerAlgebra n f) := by
  have := isIntegral f hn
  refine iSup_le fun l ↦ ?_
  obtain ⟨P, hP, hlo⟩ := exists_liesOver f hn l.head.asIdeal
  obtain ⟨L, hL, -, -⟩ := Ideal.exists_ltSeries_of_hasGoingUp l P
  rw [← hL]
  exact Order.LTSeries.length_le_krullDim L

/-- Every element of `A[Tᵢ]/(Tᵢ^{nᵢ} - fᵢ)` is congruent to an element of `A` modulo the `Tᵢ`. -/
theorem exists_sub_mem_span_T (x : KummerAlgebra n f) :
    ∃ a : A, x - algebraMap A _ a ∈ Ideal.span (Set.range (T n f)) := by
  obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective x
  induction p using MvPolynomial.induction_on with
  | C a =>
    refine ⟨a, ?_⟩
    rw [← Ideal.Quotient.mk_algebraMap, MvPolynomial.algebraMap_eq, sub_self]
    exact zero_mem _
  | add p q hp hq =>
    obtain ⟨a, ha⟩ := hp
    obtain ⟨b, hb⟩ := hq
    refine ⟨a + b, ?_⟩
    convert add_mem ha hb using 1
    rw [map_add, map_add]
    ring
  | mul_X p i _ =>
    refine ⟨0, ?_⟩
    rw [map_zero, sub_zero, map_mul]
    exact Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨i, rfl⟩)

variable {n f} in
/-- XIII.5.1: when the `fᵢ` lie in the maximal ideal `m` of the local ring `A`, the only maximal
ideal of `A[Tᵢ]/(Tᵢ^{nᵢ} - fᵢ)` is `m A' + (T₁, …, T_r)`. -/
theorem eq_of_isMaximal [IsLocalRing A] (hn : ∀ i, 0 < n i) (hf : ∀ i, f i ∈ maximalIdeal A)
    (M : Ideal (KummerAlgebra n f)) [M.IsMaximal] :
    M = (maximalIdeal A).map (algebraMap A _) ⊔ Ideal.span (Set.range (T n f)) := by
  have := isIntegral f hn
  have hc : M.comap (algebraMap A _) = maximalIdeal A :=
    IsLocalRing.eq_maximalIdeal (Ideal.isMaximal_comap_of_isIntegral_of_isMaximal M)
  have hT : ∀ i, T n f i ∈ M := fun i ↦ (‹M.IsMaximal›.isPrime).mem_of_pow_mem (n i) (by
    rw [T_pow, ← Ideal.mem_comap, hc]
    exact hf i)
  have hspan : Ideal.span (Set.range (T n f)) ≤ M :=
    Ideal.span_le.mpr (Set.range_subset_iff.mpr hT)
  refine le_antisymm (fun x hx ↦ ?_) (sup_le (Ideal.map_le_iff_le_comap.mpr hc.ge) hspan)
  obtain ⟨a, ha⟩ := exists_sub_mem_span_T n f x
  have hma : a ∈ maximalIdeal A := by
    rw [← hc, Ideal.mem_comap]
    simpa using M.sub_mem hx (hspan ha)
  rw [← add_sub_cancel (algebraMap A _ a) x]
  exact add_mem (Ideal.mem_sup_left (Ideal.mem_map_of_mem _ hma)) (Ideal.mem_sup_right ha)

variable {n f} in
/-- XIII.5.1: `X'` is local. -/
theorem isLocalRing [IsLocalRing A] (hn : ∀ i, 0 < n i) (hf : ∀ i, f i ∈ maximalIdeal A) :
    IsLocalRing (KummerAlgebra n f) := by
  obtain ⟨P, hP, -⟩ := exists_liesOver f hn (maximalIdeal A)
  have : Nontrivial (KummerAlgebra n f) :=
    ⟨0, 1, fun h ↦ hP.ne_top ((Ideal.eq_top_iff_one _).mpr (h ▸ P.zero_mem))⟩
  obtain ⟨M, hM⟩ := Ideal.exists_maximal (KummerAlgebra n f)
  refine IsLocalRing.of_unique_max_ideal ⟨M, hM, fun M' hM' ↦ ?_⟩
  rw [eq_of_isMaximal hn hf M, eq_of_isMaximal hn hf M']

variable {n} in
/-- If `m = (f, g)`, then `m A' + (T) = (T, g)` in `A' = A[Tᵢ]/(Tᵢ^{nᵢ} - fᵢ)`. -/
theorem map_sup_span_T (hn : ∀ i, 0 < n i) {k : ℕ} (g : Fin k → A) :
    (Ideal.span (Set.range f ∪ Set.range g)).map (algebraMap A (KummerAlgebra n f)) ⊔
        Ideal.span (Set.range (T n f)) =
      Ideal.span (Set.range (T n f) ∪ Set.range (algebraMap A _ ∘ g)) := by
  rw [Ideal.map_span, Set.image_union, ← Set.range_comp, ← Set.range_comp, Ideal.span_union,
    Ideal.span_union]
  refine le_antisymm (sup_le (sup_le ?_ le_sup_right) le_sup_left) (sup_le le_sup_right ?_)
  · refine (Ideal.span_le.mpr (Set.range_subset_iff.mpr fun i ↦ ?_)).trans le_sup_left
    rw [Function.comp_apply, ← T_pow]
    have hi : T n f i ∈ Ideal.span (Set.range (T n f)) := Ideal.subset_span ⟨i, rfl⟩
    exact Ideal.pow_mem_of_mem _ hi _ (hn i)
  · exact le_sup_of_le_left le_sup_right

omit [CommRing A] in
private theorem ncard_range_le {β : Type*} [Finite β] (h : β → A) :
    (Set.range h).ncard ≤ Nat.card β := by
  rw [← Set.image_univ, ← Set.ncard_univ]
  exact Set.ncard_image_le (Set.toFinite _)

variable {f} in
theorem mem_maximalIdeal_of_eq_span [IsLocalRing A] {k : ℕ} {g : Fin k → A}
    (hmax : maximalIdeal A = Ideal.span (Set.range f ∪ Set.range g)) (i : ι) :
    f i ∈ maximalIdeal A := by
  rw [hmax]
  exact Ideal.subset_span (Or.inl ⟨i, rfl⟩)

variable {n f} in
/-- XIII.5.1: the maximal ideal of `X'` is generated by the `Tᵢ` and the parameters `g` of `A`
complementary to the `fᵢ`. -/
theorem maximalIdeal_eq [IsLocalRing A] [IsLocalRing (KummerAlgebra n f)] (hn : ∀ i, 0 < n i)
    {k : ℕ} {g : Fin k → A} (hmax : maximalIdeal A = Ideal.span (Set.range f ∪ Set.range g)) :
    maximalIdeal (KummerAlgebra n f) =
      Ideal.span (Set.range (T n f) ∪ Set.range (algebraMap A _ ∘ g)) := by
  rw [eq_of_isMaximal hn (mem_maximalIdeal_of_eq_span hmax) (maximalIdeal _), hmax]
  exact map_sup_span_T f hn g

variable {n f} in
/-- The maximal ideal of `X'` has at most `r + k` generators. -/
theorem spanFinrank_maximalIdeal_le [IsLocalRing A] [IsLocalRing (KummerAlgebra n f)] [Finite ι]
    (hn : ∀ i, 0 < n i) {k : ℕ} {g : Fin k → A}
    (hmax : maximalIdeal A = Ideal.span (Set.range f ∪ Set.range g)) :
    (maximalIdeal (KummerAlgebra n f)).spanFinrank ≤ Nat.card ι + k := by
  rw [maximalIdeal_eq hn hmax]
  have h1 := Submodule.spanFinrank_span_le_ncard_of_finite (R := KummerAlgebra n f)
    ((Set.finite_range (T n f)).union (Set.finite_range (algebraMap A _ ∘ g)))
  have h2 := Set.ncard_union_le (Set.range (T n f)) (Set.range (algebraMap A _ ∘ g))
  have h3 := ncard_range_le (T n f)
  have h4 := ncard_range_le (algebraMap A (KummerAlgebra n f) ∘ g)
  rw [Nat.card_eq_fintype_card, Fintype.card_fin] at h4
  exact h1.trans (h2.trans (Nat.add_le_add h3 h4))

variable {n f} in
/-- XIII.5.1: if `A` is a regular local ring and the `fᵢ` are part of a regular system of
parameters, then `X' = X[Tᵢ]/(Tᵢ^{nᵢ} - fᵢ)` is regular (all `nᵢ > 0`). -/
theorem isRegularLocalRing [IsRegularLocalRing A] [Finite ι] (hn : ∀ i, 0 < n i)
    (hf : IsPartOfRegularSystemOfParameters f) : IsRegularLocalRing (KummerAlgebra n f) := by
  obtain ⟨k, g, hmax, hdim⟩ := hf
  let := isLocalRing hn (mem_maximalIdeal_of_eq_span hmax)
  apply IsRegularLocalRing.of_spanFinrank_maximalIdeal_le
  calc ((maximalIdeal (KummerAlgebra n f)).spanFinrank : WithBot ℕ∞)
      ≤ ((Nat.card ι + k : ℕ) : WithBot ℕ∞) := by
        exact_mod_cast spanFinrank_maximalIdeal_le hn hmax
    _ = ringKrullDim A := hdim
    _ ≤ ringKrullDim (KummerAlgebra n f) := ringKrullDim_le f hn

variable {n f} in
/-- XIII.5.1: `X'` has the same dimension as `X`. -/
theorem ringKrullDim_eq [IsRegularLocalRing A] [Finite ι] (hn : ∀ i, 0 < n i)
    (hf : IsPartOfRegularSystemOfParameters f) :
    ringKrullDim (KummerAlgebra n f) = ringKrullDim A := by
  obtain ⟨k, g, hmax, hdim⟩ := hf
  let := isLocalRing hn (mem_maximalIdeal_of_eq_span hmax)
  refine le_antisymm ?_ (ringKrullDim_le f hn)
  calc ringKrullDim (KummerAlgebra n f)
      ≤ (maximalIdeal (KummerAlgebra n f)).spanFinrank :=
        ringKrullDim_le_spanFinrank_maximalIdeal _
    _ ≤ ((Nat.card ι + k : ℕ) : WithBot ℕ∞) := by
        exact_mod_cast spanFinrank_maximalIdeal_le hn hmax
    _ = ringKrullDim A := hdim

variable {n f} in
/-- XIII.5.1: the `Tᵢ` are part of a regular system of parameters of `X'`, so that `Σ div Tᵢ` is
a divisor with normal crossings on `X'`. -/
theorem isPartOfRegularSystemOfParameters_T [IsRegularLocalRing A] [Finite ι]
    (hn : ∀ i, 0 < n i) (hf : IsPartOfRegularSystemOfParameters f)
    [IsLocalRing (KummerAlgebra n f)] : IsPartOfRegularSystemOfParameters (T n f) := by
  have hdim' := ringKrullDim_eq hn hf
  obtain ⟨k, g, hmax, hdim⟩ := hf
  exact ⟨k, algebraMap A _ ∘ g, maximalIdeal_eq hn hmax, hdim.trans hdim'.symm⟩

variable {n f} in
/-- XIII.5.1: `X'` is integral (a regular local ring is a domain). -/
theorem isDomain [IsRegularLocalRing A] [Finite ι] (hn : ∀ i, 0 < n i)
    (hf : IsPartOfRegularSystemOfParameters f) : IsDomain (KummerAlgebra n f) :=
  have := isRegularLocalRing hn hf
  isDomain_of_isRegularLocalRing _

variable {n} in
/-- `A → A[Tᵢ]/(Tᵢ^{nᵢ} - fᵢ)` is injective when `A` is a domain. -/
theorem injective_algebraMap [IsDomain A] (hn : ∀ i, 0 < n i) :
    Function.Injective (algebraMap A (KummerAlgebra n f)) := by
  obtain ⟨P, hP, hlo⟩ := exists_liesOver f hn ⊥
  refine (injective_iff_map_eq_zero _).mpr fun a ha ↦ ?_
  have : a ∈ P.under A := by rw [Ideal.under, Ideal.mem_comap, ha]; exact P.zero_mem
  rwa [← hlo.over, Ideal.mem_bot] at this

variable {n f} in
/-- XIII.5.1: `U' = X' - V(∏ Tᵢ)` is connected: its ring `A'[1/∏ Tᵢ]` is a domain. -/
theorem isDomain_away [IsRegularLocalRing A] [Fintype ι] (hn : ∀ i, 0 < n i)
    (hf : IsPartOfRegularSystemOfParameters f) :
    IsDomain (Localization.Away (∏ i, T n f i)) := by
  have := isDomain hn hf
  have := isDomain_of_isRegularLocalRing A
  have hT : ∀ i, T n f i ≠ 0 := fun i h ↦ by
    have := T_pow n f i
    rw [h, zero_pow (hn i).ne', eq_comm] at this
    exact hf.ne_zero i ((map_eq_zero_iff _ (injective_algebraMap f hn)).mp this)
  exact IsLocalization.isDomain_localization (powers_le_nonZeroDivisors_of_noZeroDivisors
    (Finset.prod_ne_zero_iff.mpr fun i _ ↦ hT i))

variable {n f} in
/-- XIII.5.1: `U' = U ×_X X'` is the complement in `X'` of `Σ div Tᵢ`: a prime of `X'` contains
`∏ fᵢ` if and only if it contains `∏ Tᵢ`. -/
theorem algebraMap_prod_mem_iff [Fintype ι] (hn : ∀ i, 0 < n i) (P : Ideal (KummerAlgebra n f))
    [P.IsPrime] : algebraMap A _ (∏ i, f i) ∈ P ↔ ∏ i, T n f i ∈ P := by
  simp_rw [map_prod, ← T_pow, Ideal.IsPrime.prod_mem_iff]
  exact exists_congr fun i ↦ and_congr_right fun _ ↦
    ⟨fun h ↦ ‹P.IsPrime›.mem_of_pow_mem _ h, fun h ↦ Ideal.pow_mem_of_mem _ h _ (hn i)⟩

variable {n} in
/-- XIII.5.1: if the `nᵢ` are invertible in `A` (for `A` local: prime to the residue
characteristic), `U' = U ×_X X'` is étale over `U = Spec A[1/∏ fᵢ]`. -/
theorem etale_away [Fintype ι] (hn : ∀ i, IsUnit (n i : A)) :
    Algebra.Etale (Localization.Away (∏ i, f i))
      (Localization.Away (∏ i, f i) ⊗[A] KummerAlgebra n f) := by
  let B := Localization.Away (∏ i, f i)
  have hf : ∀ i, IsUnit (algebraMap A B (f i)) := fun i ↦
    isUnit_of_dvd_unit (map_dvd _ (Finset.dvd_prod_of_mem f (Finset.mem_univ i)))
      (IsLocalization.Away.algebraMap_isUnit _)
  have := etale (B := B) (n := n) (fun i ↦ by simpa using (hn i).map (algebraMap A B)) hf
  exact Algebra.Etale.of_equiv (baseChangeEquiv n f B).symm

end KummerAlgebra

section DiscreteValuationRing

open Polynomial

section Ring

variable {R : Type*} [CommRing R] (π : R) (n : ℕ)

/-- In `R[T]/(Tⁿ - π)`, `Tⁿ = π`. -/
theorem root_X_pow_sub_C_pow : AdjoinRoot.root (X ^ n - C π) ^ n = algebraMap R _ π := by
  have := AdjoinRoot.eval₂_root (X ^ n - C π)
  simpa [eval₂_sub, sub_eq_zero] using this

/-- Every element of `R[T]/(Tⁿ - π)` is `a + T y` with `a ∈ R`. -/
theorem exists_eq_algebraMap_add_root_mul (x : AdjoinRoot (X ^ n - C π)) :
    ∃ a : R, ∃ y, x = algebraMap R _ a + AdjoinRoot.root _ * y := by
  induction x using AdjoinRoot.induction_on with
  | ih p =>
    refine ⟨p.coeff 0, AdjoinRoot.mk _ p.divX, ?_⟩
    have h := congrArg (AdjoinRoot.mk (X ^ n - C π)) (X_mul_divX_add p)
    rw [← h, map_add, map_mul, AdjoinRoot.mk_X, AdjoinRoot.mk_C, add_comm,
      AdjoinRoot.algebraMap_eq]

variable [hn : NeZero n]

instance : Module.Free R (AdjoinRoot (X ^ n - C π)) :=
  (monic_X_pow_sub_C π hn.out).free_adjoinRoot

instance : Module.Finite R (AdjoinRoot (X ^ n - C π)) :=
  (monic_X_pow_sub_C π hn.out).finite_adjoinRoot

variable [Nontrivial R]

/-- `X' → X` is finite and flat of degree `n`. -/
theorem finrank_adjoinRoot_X_pow_sub_C : Module.finrank R (AdjoinRoot (X ^ n - C π)) = n := by
  rw [(AdjoinRoot.powerBasis' (monic_X_pow_sub_C π hn.out)).finrank]
  simp [AdjoinRoot.powerBasis']

/-- `R → R[T]/(Tⁿ - π)` is injective. -/
theorem injective_algebraMap_adjoinRoot :
    Function.Injective (algebraMap R (AdjoinRoot (X ^ n - C π))) :=
  AdjoinRoot.of.injective_of_monic_of_degree_pos (monic_X_pow_sub_C π hn.out)
    (by rw [degree_X_pow_sub_C (Nat.pos_of_ne_zero hn.out)]
        exact_mod_cast Nat.pos_of_ne_zero hn.out)

end Ring

variable {R : Type*} [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]
  (π : R) [hπ : Fact (Irreducible π)] (n : ℕ) [hn : NeZero n]

/-- For a uniformizer `π` of a discrete valuation ring, `Tⁿ - π` is Eisenstein. -/
theorem isEisensteinAt_X_pow_sub_C : (X ^ n - C π).IsEisensteinAt (maximalIdeal R) := by
  have hn := Nat.pos_of_ne_zero hn.out
  have hdeg : (X ^ n - C π).natDegree = n := natDegree_X_pow_sub_C
  refine (monic_X_pow_sub_C π hn.ne').isEisensteinAt_of_mem_of_notMem
    (maximalIdeal.isMaximal R).ne_top ?_ ?_
  · intro i hi
    rw [hdeg] at hi
    rcases eq_or_ne i 0 with rfl | h0
    · simpa [coeff_X_pow, hn.ne] using hπ.out.not_isUnit
    · simp [coeff_X_pow, coeff_C, h0, hi.ne]
  · have : (X ^ n - C π).coeff 0 = -π := by simp [coeff_X_pow, hn.ne]
    rw [this, neg_mem_iff, hπ.out.maximalIdeal_eq, Ideal.span_singleton_pow,
      Ideal.mem_span_singleton]
    rintro ⟨c, hc⟩
    apply hπ.out.not_isUnit
    refine .of_mul_eq_one c (mul_left_cancel₀ hπ.out.ne_zero ?_)
    rw [mul_one, ← mul_assoc, ← sq]
    exact hc.symm

/-- For a uniformizer `π` of a discrete valuation ring, `Tⁿ - π` is irreducible. -/
theorem irreducible_X_pow_sub_C_of_irreducible : Irreducible (X ^ n - C π) :=
  (isEisensteinAt_X_pow_sub_C π n).irreducible (maximalIdeal.isMaximal R).isPrime
    (monic_X_pow_sub_C π hn.out).isPrimitive
    (by rw [natDegree_X_pow_sub_C]; exact Nat.pos_of_ne_zero hn.out)

/-- XIII.5.1 for a discrete valuation ring: `X'` is integral, in particular connected. -/
instance : IsDomain (AdjoinRoot (X ^ n - C π)) :=
  AdjoinRoot.isDomain_of_prime (irreducible_X_pow_sub_C_of_irreducible π n).prime

/-- The only maximal ideal of `R[T]/(Tⁿ - π)` is `(T)`. -/
theorem eq_span_root_of_isMaximal (M : Ideal (AdjoinRoot (X ^ n - C π))) [M.IsMaximal] :
    M = Ideal.span {AdjoinRoot.root _} := by
  have hc : M.comap (algebraMap R _) = maximalIdeal R :=
    IsLocalRing.eq_maximalIdeal (Ideal.isMaximal_comap_of_isIntegral_of_isMaximal M)
  have hπM : algebraMap R _ π ∈ M := by
    rw [← Ideal.mem_comap, hc, hπ.out.maximalIdeal_eq]
    exact Ideal.mem_span_singleton_self π
  have hroot : AdjoinRoot.root _ ∈ M :=
    (‹M.IsMaximal›.isPrime).mem_of_pow_mem n (root_X_pow_sub_C_pow π n ▸ hπM)
  refine le_antisymm (fun x hx ↦ ?_) ((Ideal.span_le).mpr (Set.singleton_subset_iff.mpr hroot))
  obtain ⟨a, y, rfl⟩ := exists_eq_algebraMap_add_root_mul π n x
  have ha : a ∈ maximalIdeal R := by
    rw [← hc, Ideal.mem_comap]
    have := M.sub_mem hx (M.mul_mem_right y hroot)
    rwa [add_sub_cancel_right] at this
  rw [hπ.out.maximalIdeal_eq, Ideal.mem_span_singleton] at ha
  obtain ⟨b, rfl⟩ := ha
  obtain ⟨k, rfl⟩ : ∃ k, n = k + 1 := ⟨n - 1, (Nat.succ_pred_eq_of_ne_zero hn.out).symm⟩
  rw [Ideal.mem_span_singleton]
  refine ⟨AdjoinRoot.root _ ^ k * algebraMap R _ b + y, ?_⟩
  rw [map_mul, ← root_X_pow_sub_C_pow]
  ring

/-- `R[T]/(Tⁿ - π)` is local. -/
instance : IsLocalRing (AdjoinRoot (X ^ n - C π)) := by
  obtain ⟨M, hM⟩ := Ideal.exists_maximal (AdjoinRoot (X ^ n - C π))
  refine IsLocalRing.of_unique_max_ideal ⟨Ideal.span {AdjoinRoot.root _}, ?_, fun M hM ↦ ?_⟩
  · rw [← eq_span_root_of_isMaximal π n M]; exact hM
  · exact eq_span_root_of_isMaximal π n M

/-- XIII.5.1 for a discrete valuation ring: the maximal ideal of `X'` is generated by `T`. -/
theorem maximalIdeal_adjoinRoot_X_pow_sub_C :
    maximalIdeal (AdjoinRoot (X ^ n - C π)) = Ideal.span {AdjoinRoot.root _} :=
  eq_span_root_of_isMaximal π n _

/-- `T ≠ 0` in `R[T]/(Tⁿ - π)`. -/
theorem root_X_pow_sub_C_ne_zero_of_irreducible : AdjoinRoot.root (X ^ n - C π) ≠ 0 := by
  intro h
  have := root_X_pow_sub_C_pow π n
  rw [h, zero_pow hn.out, eq_comm] at this
  exact hπ.out.ne_zero ((map_eq_zero_iff _ (injective_algebraMap_adjoinRoot π n)).mp this)

/-- XIII.5.1 for a discrete valuation ring: `X' = Spec R[T]/(Tⁿ - π)` is regular, i.e.
`R[T]/(Tⁿ - π)` is a discrete valuation ring. -/
instance : IsDiscreteValuationRing (AdjoinRoot (X ^ n - C π)) := by
  have hmax := maximalIdeal_adjoinRoot_X_pow_sub_C π n
  have hnf : ¬ IsField (AdjoinRoot (X ^ n - C π)) := by
    rw [IsLocalRing.isField_iff_maximalIdeal_eq, hmax, Ideal.span_singleton_eq_bot]
    exact root_X_pow_sub_C_ne_zero_of_irreducible π n
  have hp : (maximalIdeal (AdjoinRoot (X ^ n - C π))).IsPrincipal := ⟨_, hmax⟩
  exact ((IsDiscreteValuationRing.TFAE _ hnf).out 1 5).mpr hp

/-- XIII.5.1 for a discrete valuation ring: `T` is a uniformizer of `R[T]/(Tⁿ - π)`. -/
theorem irreducible_root_X_pow_sub_C : Irreducible (AdjoinRoot.root (X ^ n - C π)) :=
  (IsDiscreteValuationRing.irreducible_iff_uniformizer _).mpr
    (maximalIdeal_adjoinRoot_X_pow_sub_C π n)

instance : (maximalIdeal (AdjoinRoot (X ^ n - C π))).LiesOver (maximalIdeal R) :=
  ⟨(IsLocalRing.eq_maximalIdeal (Ideal.isMaximal_comap_of_isIntegral_of_isMaximal _)).symm⟩

/-- `R[T]/(Tⁿ - π)` has ramification index `n` over `R`. -/
theorem ramificationIdx_adjoinRoot_X_pow_sub_C :
    (maximalIdeal (AdjoinRoot (X ^ n - C π))).ramificationIdx R = n := by
  have : Module.IsTorsionFree R (AdjoinRoot (X ^ n - C π)) :=
    Module.isTorsionFree_iff_algebraMap_injective.mpr (injective_algebraMap_adjoinRoot π n)
  rw [← Ideal.ramificationIdx'_eq_ramificationIdx (maximalIdeal R) _
    (IsDiscreteValuationRing.not_a_field R)]
  have hmap : (maximalIdeal R).map (algebraMap R (AdjoinRoot (X ^ n - C π))) =
      maximalIdeal (AdjoinRoot (X ^ n - C π)) ^ n := by
    rw [hπ.out.maximalIdeal_eq, Ideal.map_span, Set.image_singleton, ← root_X_pow_sub_C_pow,
      maximalIdeal_adjoinRoot_X_pow_sub_C, Ideal.span_singleton_pow]
  refine Ideal.ramificationIdx'_spec hmap.le fun h ↦ ?_
  rw [hmap, maximalIdeal_adjoinRoot_X_pow_sub_C, Ideal.span_singleton_pow,
    Ideal.span_singleton_pow, Ideal.span_singleton_le_span_singleton,
    pow_dvd_pow_iff (root_X_pow_sub_C_ne_zero_of_irreducible π n)
      (irreducible_root_X_pow_sub_C π n).not_isUnit] at h
  omega

/-- The residue extension of `R[T]/(Tⁿ - π)` over `R` is trivial. -/
theorem algebraMap_quotient_surjective (q : Ideal (AdjoinRoot (X ^ n - C π))) [q.IsMaximal] :
    Function.Surjective (algebraMap (R ⧸ q.under R) (AdjoinRoot (X ^ n - C π) ⧸ q)) := by
  intro w
  obtain ⟨x, rfl⟩ := Ideal.Quotient.mk_surjective w
  obtain ⟨a, y, rfl⟩ := exists_eq_algebraMap_add_root_mul π n x
  have hroot : AdjoinRoot.root (X ^ n - C π) ∈ q := by
    rw [eq_span_root_of_isMaximal π n q]; exact Ideal.mem_span_singleton_self _
  refine ⟨Ideal.Quotient.mk _ a, ?_⟩
  rw [Ideal.Quotient.algebraMap_mk_of_liesOver, map_add, map_mul,
    Ideal.Quotient.eq_zero_iff_mem.mpr hroot, zero_mul, add_zero]

/-- `R[T]/(Tⁿ - π)` has inertia degree `1` over `R`. -/
theorem inertiaDeg_adjoinRoot_X_pow_sub_C :
    (maximalIdeal (AdjoinRoot (X ^ n - C π))).inertiaDeg R = 1 := by
  set q := maximalIdeal (AdjoinRoot (X ^ n - C π))
  rw [Ideal.inertiaDeg_eq_of_isMaximal (q.under R) q]
  let := Ideal.Quotient.field (q.under R)
  refine (finrank_eq_one_iff_of_nonzero' (1 : AdjoinRoot (X ^ n - C π) ⧸ q) one_ne_zero).mpr
    fun w ↦ ?_
  obtain ⟨c, rfl⟩ := algebraMap_quotient_surjective π n q w
  exact ⟨c, by rw [Algebra.smul_def, mul_one]⟩

/-- The residue extension of `R[T]/(Tⁿ - π)` over `R` is separable (it is trivial). -/
theorem isSeparable_quotient (q : Ideal (AdjoinRoot (X ^ n - C π))) [q.IsMaximal] :
    letI := Ideal.Quotient.field (q.under R)
    letI := Ideal.Quotient.field q
    Algebra.IsSeparable (R ⧸ q.under R) (AdjoinRoot (X ^ n - C π) ⧸ q) := by
  let := Ideal.Quotient.field (q.under R)
  let := Ideal.Quotient.field q
  let e := AlgEquiv.ofBijective (Algebra.ofId (R ⧸ q.under R) (AdjoinRoot (X ^ n - C π) ⧸ q))
    ⟨(algebraMap (R ⧸ q.under R) (AdjoinRoot (X ^ n - C π) ⧸ q)).injective,
      algebraMap_quotient_surjective π n q⟩
  exact Algebra.IsSeparable.of_algHom _ _ e.symm.toAlgHom

/-- XIII.5.1 for a discrete valuation ring: `R[T]/(Tⁿ - π)` is tamely ramified over `R` when `n`
is prime to the residue characteristic. -/
theorem isTamelyRamifiedOver_adjoinRoot_X_pow_sub_C (hp : (n : R) ∉ maximalIdeal R) :
    IsTamelyRamifiedOver R (AdjoinRoot (X ^ n - C π)) := by
  intro q _ _
  have : q.IsMaximal := Ideal.IsMaximal.of_liesOver_isMaximal q (maximalIdeal R)
  obtain rfl : q = maximalIdeal _ := IsLocalRing.eq_maximalIdeal this
  let := Localization.AtPrime.algebraOfLiesOver ((maximalIdeal (AdjoinRoot (X ^ n - C π))).under R)
    (maximalIdeal (AdjoinRoot (X ^ n - C π)))
  refine ⟨?_, ?_⟩
  · rwa [ramificationIdx_adjoinRoot_X_pow_sub_C,
      ← Ideal.over_def (maximalIdeal (AdjoinRoot (X ^ n - C π))) (maximalIdeal R)]
  · have := isSeparable_quotient π n (maximalIdeal (AdjoinRoot (X ^ n - C π)))
    infer_instance

section Generic

variable (K : Type*) [Field K] [Algebra R K] [IsFractionRing R K]

/-- XIII.5.1 for a discrete valuation ring: `U' = Spec K[T]/(Tⁿ - π)` is connected, as
`Tⁿ - π` is irreducible over `K` (Eisenstein and Gauss). -/
theorem irreducible_X_pow_sub_C_algebraMap : Irreducible (X ^ n - C (algebraMap R K π)) := by
  have h := ((monic_X_pow_sub_C π hn.out).irreducible_iff_irreducible_map_fraction_map
    (K := K)).mp (irreducible_X_pow_sub_C_of_irreducible π n)
  simpa [Polynomial.map_sub, Polynomial.map_pow] using h

omit hn in
/-- XIII.5.1 for a discrete valuation ring: the restriction `U' = Spec K[T]/(Tⁿ - π)` of
`R[T]/(Tⁿ - π)` to `U = Spec K` is a connected (it is a field) étale covering of `U` when `n` is
prime to the residue characteristic. -/
theorem etale_adjoinRoot_X_pow_sub_C_algebraMap (hp : (n : R) ∉ maximalIdeal R) :
    Algebra.Etale K (AdjoinRoot (X ^ n - C (algebraMap R K π))) := by
  have hu : IsUnit (n : R) := by rwa [← IsLocalRing.notMem_maximalIdeal]
  have hπ0 : algebraMap R K π ≠ 0 :=
    (map_ne_zero_iff _ (IsFractionRing.injective R K)).mpr hπ.out.ne_zero
  have := etale_adjoinRoot_X_pow_sub_C (R := K) (n := n) (by simpa using hu.map (algebraMap R K))
    (Units.mk0 _ hπ0)
  exact this

end Generic


end DiscreteValuationRing

end SGA.SGA1.ExposeXIII
