/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.Foundations.Projective.PlaneModelCurve
import SGA.Foundations.Projective.PlaneModelField
import SGA.Foundations.Dimension.StalkKrullDim
import SGA.SGA1.ExposeIX.PinchingCurveNormalization
import SGA.SGA1.ExposeIX.DescentFiniteGeneration
import SGA.SGA1.ExposeX.PurityBirational
import SGA.SGA1.ExposeXI.RationalVarieties
import SGA.SGA1.ExposeXI.UnirationalCovers

/-!
# SGA 1, Exposé X, 2.9 for curves, from plane curves

Let `k` be algebraically closed and `Z` an integral proper `k`-scheme of dimension `1`. Its
function field `K = K(Z)` is `k(x, y)` for a plane model `(x, y)`
(`Field.exists_planeModel_of_trdeg_eq_one`), and `D = planeCurve k x y`, the plane curve through
`(1 : x : y)`, is an integral proper curve with function field `K`
(`SGA.Foundations.Projective.PlaneModelCurve`). This file shows that **`π₁(Z)` is topologically
finitely generated as soon as `π₁(D)` is** (`isTopologicallyFG_of_planeCurve`), so that X.2.9 for
curves reduces to plane curves (`isTopologicallyFG_of_forall_planeCurve`). No normality of `Z` is
needed. The argument:

* the normalization `ν : D' ⟶ D` of `D` is finite (E. Noether) and an isomorphism off finitely
  many closed points, so `π₁(D')` is topologically finitely generated by the consequence of IX.5.4
  for normalizations of curves
  (`SGA.SGA1.ExposeIX.isTopologicallyFG_etaleFundamentalGroup_normalization_of_isTopologicallyFG`);
* the local rings of `D'` are valuation rings (normal of dimension `≤ 1`), so the isomorphism
  `K(Z) ≅ K(D) ≅ K(D')` extends to a morphism `h : D' ⟶ Z` over `k` (valuative criterion,
  `CurvePlaneModel.exists_hom_of_valuationRing`); `h` is proper and surjective;
* IX.5.2 (`SGA.SGA1.ExposeIX.isTopologicallyFG_etaleFundamentalGroup_of_family`) along `h` gives
  `π₁(Z)`.

In dimension `0` there is nothing to prove (`isTopologicallyFG_of_topologicalKrullDim_le_zero`:
the scheme is a rational point with trivial `π₁`), so the input `hC` of SGA's induction
(`SGA.SGA1.ExposeX.isTopologicallyFG_of_curve_of_hyperplane_of_isFinite`, for integral proper
schemes of dimension `≤ 1`) follows from the plane-curve case
(`isTopologicallyFG_of_forall_planeCurve_of_le_one`).

This is the first step of this formalization's planned route to the curve case of X.2.9 in
characteristic `p` (plane model, lift of the plane curve to characteristic `0`, pinching); SGA
instead lifts the smooth curve by III.7.4. The other steps are not formalized yet.
-/

universe u

open CategoryTheory CategoryTheory.Limits AlgebraicGeometry

namespace SGA.SGA1.ExposeX

namespace CurvePlaneModel

/-- The generic point `Spec K(X) ⟶ X` of an integral scheme is dominant. -/
lemma isDominant_fromSpecStalk_genericPoint {X : Scheme.{u}} [IsIntegral X] :
    IsDominant (X.fromSpecStalk (genericPoint X)) := by
  refine ⟨dense_iff_closure_eq.mpr (Set.eq_univ_of_univ_subset ?_)⟩
  rw [← genericPoint_closure X]
  exact closure_mono (Set.singleton_subset_iff.mpr ⟨_, Scheme.fromSpecStalk_closedPoint⟩)

variable {X Y S : Scheme.{u}} [IsIntegral X] (sX : X ⟶ S) (sY : Y ⟶ S) [LocallyOfFiniteType sY]
  [UniversallyClosed sY] [Y.IsSeparated] [S.IsSeparated]

/-- **Extension of morphisms from the generic point**: let `X` be an integral scheme whose local
rings are valuation rings (e.g. a normal curve), and `Y` universally closed, separated and locally
of finite type over a separated `S`. Every `S`-morphism `Spec K(X) ⟶ Y` extends to an `S`-morphism
`X ⟶ Y` (valuative criterion, `ExposeX.mem_domain_of_valuationRing`). -/
theorem exists_hom_of_valuationRing (hval : ∀ x : X, ValuationRing (X.presheaf.stalk x))
    (φ : Spec X.functionField ⟶ Y) (h : φ ≫ sY = X.fromSpecStalk (genericPoint X) ≫ sX) :
    ∃ g : X ⟶ Y, X.fromSpecStalk (genericPoint X) ≫ g = φ ∧ g ≫ sY = sX := by
  let ψ := Scheme.PartialMap.ofFromSpecStalk sX sY φ h
  have hψ := Scheme.PartialMap.ofFromSpecStalk_comp sX sY φ h
  let P := ψ.toRationalMap.toPartialMap
  have hdom : P.domain = ⊤ := eq_top_iff.mpr fun x _ ↦
    mem_domain_of_valuationRing sX sY ψ hψ x
  let e : X ⟶ P.domain := X.topIso.inv ≫ (X.isoOfEq hdom.symm).hom
  have he : e ≫ P.domain.ι = 𝟙 X := by simp [e]
  have hmem : genericPoint X ∈ P.domain := hdom ▸ trivial
  have h1 : X.fromSpecStalk (genericPoint X) ≫ e = P.domain.fromSpecStalkOfMem _ hmem := by
    rw [← cancel_mono P.domain.ι, Category.assoc, he, Category.comp_id,
      Scheme.Opens.fromSpecStalkOfMem_ι]
  have h2 : P.fromFunctionField = φ := by
    rw [← Scheme.RationalMap.fromFunctionField_toRationalMap,
      Scheme.RationalMap.toRationalMap_toPartialMap,
      Scheme.RationalMap.fromFunctionField_toRationalMap]
    exact Scheme.PartialMap.fromSpecStalkOfMem_ofFromSpecStalk sX sY φ h
  have hη : X.fromSpecStalk (genericPoint X) ≫ e ≫ P.hom = φ := by
    rw [reassoc_of% h1]
    exact h2
  refine ⟨e ≫ P.hom, hη, ?_⟩
  have := isDominant_fromSpecStalk_genericPoint (X := X)
  refine ext_of_isDominant (X.fromSpecStalk (genericPoint X)) ?_
  rw [Category.assoc, reassoc_of% hη, h]

end CurvePlaneModel

open CurvePlaneModel PlaneCurve

variable {k : Type u} [Field k] [IsAlgClosed k] {Z : Scheme.{u}} [IsIntegral Z]
  (sZ : Z ⟶ Spec (.of k)) [IsProper sZ]

/-- **X.2.9 for curves, from plane curves**: let `k` be algebraically closed, `Z` an integral
proper `k`-scheme of dimension `≤ 1`, and `x, y ∈ K(Z)` with `K(Z) = k(x, y)` (the `k`-algebra
structure of `K(Z)` being the one given by `sZ`). If `π₁` of the plane curve `planeCurve k x y`
is topologically finitely generated (at some geometric point), so is `π₁(Z)`, at every geometric
point. -/
theorem isTopologicallyFG_of_planeCurve [Algebra k Z.functionField]
    (hk : algebraMap k Z.functionField = ExposeXI.functionFieldMap sZ) (x y : Z.functionField)
    (hxy : IntermediateField.adjoin k {x, y} = ⊤) (hZ : topologicalKrullDim Z ≤ 1)
    {Ω₀ : Type u} [Field Ω₀] [IsSepClosed Ω₀] (s₀ : Spec (.of Ω₀) ⟶ planeCurve k x y)
    (h : ExposeXIII.IsTopologicallyFG (ExposeV.etaleFundamentalGroup Ω₀ s₀))
    (Ω : Type u) [Field Ω] [IsSepClosed Ω] (s : Spec (.of Ω) ⟶ Z) :
    ExposeXIII.IsTopologicallyFG (ExposeV.etaleFundamentalGroup Ω s) := by
  let D := planeCurve k x y
  let τ := toSpec k x y
  have : LocallyOfFiniteType τ := inferInstance
  have : CompactSpace D := QuasiCompact.compactSpace_of_compactSpace τ
  have : Z.IsSeparated := ⟨by rw [← terminal.comp_from sZ]; infer_instance⟩
  -- `dim D = dim Z ≤ 1`
  have hdimZ := topologicalKrullDim_eq_trdeg_functionField sZ hk
  have hD : topologicalKrullDim D ≤ 1 := by
    rw [topologicalKrullDim_eq k x y hxy, ← hdimZ]
    exact hZ
  -- the normalization `ν : D' ⟶ D`
  let η := D.fromSpecStalk (genericPoint D)
  let D' := η.normalization
  let ν := η.fromNormalization
  have : IsFinite ν := isFinite_fromNormalization_fromSpecStalk_genericPoint τ
  have hν : ν (genericPoint D') = genericPoint D :=
    ExposeXI.genericPoint_eq_of_surjective ν ν.surjective
  -- `π₁(D')` is topologically finitely generated (pinching for the normalization)
  have hD' := ExposeIX.isTopologicallyFG_etaleFundamentalGroup_normalization_of_isTopologicallyFG
    τ hD s₀ h
  -- the local rings of `D'` are valuation rings
  have : LocallyOfFiniteType (ν ≫ τ) := inferInstance
  have : IsLocallyNoetherian D' := LocallyOfFiniteType.isLocallyNoetherian (ν ≫ τ)
  have hdimD' : topologicalKrullDim D' ≤ 1 :=
    (Scheme.Hom.topologicalKrullDim_le_of_locallyQuasiFinite ν).trans hD
  have hval (d : D') : ValuationRing (D'.presheaf.stalk d) := by
    have := isIntegrallyClosed_stalk_normalization_fromSpecStalk_genericPoint (X := D) d
    have := IsPrincipalIdealRing.of_isIntegrallyClosed_of_ringKrullDim_le_one
      ((AlgebraicGeometry.ringKrullDim_stalk_le_topologicalKrullDim d).trans hdimD')
    infer_instance
  -- `K(Z) ≅ K(D) → K(D')`
  let ψ := PlaneCurve.functionFieldHom k x y
  have hψ := bijective_functionFieldHom k x y hxy
  let ψe : D.functionField ≅ Z.functionField :=
    (RingEquiv.ofBijective ψ.hom hψ).toCommRingCatIso
  let β := ExposeXI.functionFieldHom ν hν
  let γ : Z.functionField ⟶ D'.functionField := ψe.inv ≫ β
  let φ : Spec D'.functionField ⟶ Z := Spec.map γ ≫ Z.fromSpecStalk (genericPoint Z)
  have hψk : CommRingCat.ofHom (ExposeXI.functionFieldMap τ) ≫ ψe.hom =
      CommRingCat.ofHom (ExposeXI.functionFieldMap sZ) := by
    rw [← hk]
    exact functionFieldHom_comp k x y
  have hφ : φ ≫ sZ = D'.fromSpecStalk (genericPoint D') ≫ ν ≫ τ := by
    rw [ExposeXI.fromSpecStalk_comp_eq_SpecMap (ν ≫ τ), ExposeXI.functionFieldMap_comp τ ν hν,
      Category.assoc, ExposeXI.fromSpecStalk_comp_eq_SpecMap sZ, ← Spec.map_comp, ← hψk]
    congr 1
    ext t
    change β (ψe.inv (ψe.hom _)) = _
    rw [Iso.hom_inv_id_apply]
    rfl
  -- the morphism `h : D' ⟶ Z`
  obtain ⟨g, hg₁, hg₂⟩ := exists_hom_of_valuationRing (ν ≫ τ) sZ hval φ hφ
  have : IsProper (g ≫ sZ) := by rw [hg₂]; infer_instance
  have : IsProper g := IsProper.of_comp g sZ
  have hgen : g (genericPoint D') = genericPoint Z := by
    have h1 : D'.fromSpecStalk (genericPoint D') (IsLocalRing.closedPoint D'.functionField) =
        genericPoint D' := Scheme.fromSpecStalk_closedPoint
    have h2 (q : Spec Z.functionField) : Z.fromSpecStalk (genericPoint Z) q = genericPoint Z := by
      rw [Subsingleton.elim q (IsLocalRing.closedPoint Z.functionField)]
      exact Scheme.fromSpecStalk_closedPoint
    rw [← h1]
    exact (congrArg (fun f : Spec D'.functionField ⟶ Z ↦
      f (IsLocalRing.closedPoint D'.functionField)) hg₁).trans (h2 _)
  have hsurj : Function.Surjective g := by
    have hc : IsClosed (Set.range g) := g.isClosedMap.isClosed_range
    have : Set.range g = Set.univ := by
      refine Set.eq_univ_of_univ_subset ?_
      rw [← genericPoint_closure Z]
      exact hc.closure_subset_iff.mpr (Set.singleton_subset_iff.mpr ⟨_, hgen⟩)
    exact Set.range_eq_univ.mp this
  -- IX.5.2 along `g`
  have : IsNoetherian Z :=
    { toIsLocallyNoetherian := LocallyOfFiniteType.isLocallyNoetherian sZ,
      toCompactSpace := QuasiCompact.compactSpace_of_compactSpace sZ }
  obtain ⟨w⟩ : Nonempty D' := inferInstance
  refine ExposeIX.isTopologicallyFG_etaleFundamentalGroup_of_family (ι := Unit) (fun _ ↦ g)
    (fun z ↦ ⟨(), hsurj z⟩) (fun _ ↦ ⟨_, _, inferInstance, ExposeV.geometricPointAt _ w,
      hD' _ (ExposeV.geometricPointAt _ w)⟩) Ω s

include sZ in
/-- **X.2.9 for curves reduces to plane curves**: let `k` be algebraically closed. Assume that for
every finitely generated extension `K ⊇ k` of transcendence degree `1` (in universe `u`) and every
plane model of `K` (elements `x, y ∈ K` with `x` transcendental over `k`, `K = k(x, y)`, and the
relations between `x` and `y` generated by a monic irreducible `f ∈ k[s][t]` of positive degree in
`t`), `π₁` of the plane curve `planeCurve k x y` is topologically finitely generated at some
geometric point. Then `π₁(Z)` is topologically finitely generated, at every geometric point, for
every integral proper `k`-scheme `Z` of dimension `1`. -/
theorem isTopologicallyFG_of_forall_planeCurve
    (hP : ∀ (K : Type u) [Field K] [Algebra k K] [Algebra.EssFiniteType k K] (x y : K),
      Algebra.trdeg k K = 1 → Transcendental k x → IntermediateField.adjoin k {x, y} = ⊤ →
      (∃ f : Polynomial (Polynomial k), f.Monic ∧ Irreducible f ∧ 0 < f.natDegree ∧
        RingHom.ker (Polynomial.eval₂RingHom (Polynomial.aeval x).toRingHom y) =
          Ideal.span {f}) →
      ∃ (Ω₀ : Type u) (_ : Field Ω₀) (_ : IsSepClosed Ω₀) (s₀ : Spec (.of Ω₀) ⟶ planeCurve k x y),
        ExposeXIII.IsTopologicallyFG (ExposeV.etaleFundamentalGroup Ω₀ s₀))
    (hZ : topologicalKrullDim Z = 1) (Ω : Type u) [Field Ω] [IsSepClosed Ω]
    (s : Spec (.of Ω) ⟶ Z) :
    ExposeXIII.IsTopologicallyFG (ExposeV.etaleFundamentalGroup Ω s) := by
  let _ : Algebra k Z.functionField := (ExposeXI.functionFieldMap sZ).toAlgebra
  have : Algebra.EssFiniteType k Z.functionField := ExposeXI.essFiniteType_functionFieldMap sZ
  have htr : Algebra.trdeg k Z.functionField = 1 := by
    have e := topologicalKrullDim_eq_trdeg_functionField sZ rfl
    rw [hZ] at e
    have e' : Cardinal.toENat (Algebra.trdeg k Z.functionField) = 1 := by exact_mod_cast e.symm
    exact Cardinal.toENat_eq_one.mp e'
  obtain ⟨x, y, hx, hxy, hf⟩ := Field.exists_planeModel_of_trdeg_eq_one k Z.functionField htr
  obtain ⟨Ω₀, _, _, s₀, h⟩ := hP Z.functionField x y htr hx hxy hf
  exact isTopologicallyFG_of_planeCurve sZ rfl x y hxy hZ.le s₀ h Ω s

include sZ in
/-- **X.2.9 in dimension `0`**: an integral proper scheme of dimension `≤ 0` over an algebraically
closed field is a point with a rational point, and its fundamental group is trivial, hence
topologically finitely generated (`ExposeIX.Pinching.subsingleton_etaleFundamentalGroup`). -/
theorem isTopologicallyFG_of_topologicalKrullDim_le_zero (hZ : topologicalKrullDim Z ≤ 0)
    (Ω : Type u) [Field Ω] [IsSepClosed Ω] (s : Spec (.of Ω) ⟶ Z) :
    ExposeXIII.IsTopologicallyFG (ExposeV.etaleFundamentalGroup Ω s) := by
  -- `Z` is a point: every point is the generic point
  have hpt (z : Z) : z = genericPoint Z := by
    by_contra hne
    have hsp : genericPoint Z ⤳ z := genericPoint_specializes z
    let c₀ : TopologicalSpace.IrreducibleCloseds Z :=
      ⟨closure {z}, isIrreducible_singleton.closure, isClosed_closure⟩
    let c₁ : TopologicalSpace.IrreducibleCloseds Z :=
      ⟨closure {genericPoint Z}, isIrreducible_singleton.closure, isClosed_closure⟩
    have hlt : c₀ < c₁ := by
      refine lt_of_le_of_ne (fun w hw ↦ ?_) fun h ↦ hne ?_
      · exact closure_minimal (Set.singleton_subset_iff.mpr hsp.mem_closure) isClosed_closure hw
      · have h' : closure {z} = closure ({genericPoint Z} : Set Z) := congrArg (·.1) h
        exact ((specializes_iff_closure_subset.mpr h'.ge).antisymm hsp).eq
    let p : LTSeries (TopologicalSpace.IrreducibleCloseds Z) :=
      (RelSeries.singleton _ c₀).snoc c₁ hlt
    have hp : p.length = 1 := rfl
    have h1 : ((p.length : ℕ) : WithBot ℕ∞) ≤ topologicalKrullDim Z :=
      Order.LTSeries.length_le_krullDim p
    rw [hp] at h1
    exact absurd (h1.trans hZ) (by decide)
  have : Subsingleton Z := ⟨fun a b ↦ (hpt a).trans (hpt b).symm⟩
  -- a `k`-point
  have hc : IsClosed ({genericPoint Z} : Set Z) := by
    rw [Set.eq_univ_of_forall (fun z ↦ hpt z ▸ rfl : ∀ z, z ∈ ({genericPoint Z} : Set Z))]
    exact isClosed_univ
  let t := pointOfClosedPoint sZ (genericPoint Z) hc
  have ht : t ≫ sZ = 𝟙 _ := pointOfClosedPoint_comp sZ _ _
  have := ExposeIX.Pinching.subsingleton_etaleFundamentalGroup sZ t ht
  have hfg : ExposeXIII.IsTopologicallyFG (ExposeV.etaleFundamentalGroup k t) :=
    ⟨∅, fun g ↦ by rw [Subsingleton.elim g 1]; exact subset_closure (one_mem _)⟩
  exact (isTopologicallyFG_etaleFundamentalGroup_iff k Ω t s).mp hfg

/-- `topologicalKrullDim Z ≤ 1` splits into `≤ 0` and `= 1`. -/
private lemma le_zero_or_eq_one_of_le_one {d : WithBot ℕ∞} (h : d ≤ 1) : d ≤ 0 ∨ d = 1 := by
  induction d using WithBot.recBotCoe with
  | bot => exact Or.inl bot_le
  | coe n =>
    induction n using ENat.recTopCoe with
    | top => exact absurd h (by decide)
    | coe m =>
      have hm : m ≤ 1 := by exact_mod_cast h
      rcases Nat.le_one_iff_eq_zero_or_eq_one.mp hm with rfl | rfl
      · exact Or.inl le_rfl
      · exact Or.inr rfl

include sZ in
/-- **The curve case of X.2.9 (input `hC`) from plane curves**: under the hypothesis of
`isTopologicallyFG_of_forall_planeCurve` on plane curves, `π₁(Z)` is topologically finitely
generated for every integral proper `Z` of dimension `≤ 1` over the algebraically closed `k`. -/
theorem isTopologicallyFG_of_forall_planeCurve_of_le_one
    (hP : ∀ (K : Type u) [Field K] [Algebra k K] [Algebra.EssFiniteType k K] (x y : K),
      Algebra.trdeg k K = 1 → Transcendental k x → IntermediateField.adjoin k {x, y} = ⊤ →
      (∃ f : Polynomial (Polynomial k), f.Monic ∧ Irreducible f ∧ 0 < f.natDegree ∧
        RingHom.ker (Polynomial.eval₂RingHom (Polynomial.aeval x).toRingHom y) =
          Ideal.span {f}) →
      ∃ (Ω₀ : Type u) (_ : Field Ω₀) (_ : IsSepClosed Ω₀) (s₀ : Spec (.of Ω₀) ⟶ planeCurve k x y),
        ExposeXIII.IsTopologicallyFG (ExposeV.etaleFundamentalGroup Ω₀ s₀))
    (hZ : topologicalKrullDim Z ≤ 1) (Ω : Type u) [Field Ω] [IsSepClosed Ω]
    (s : Spec (.of Ω) ⟶ Z) :
    ExposeXIII.IsTopologicallyFG (ExposeV.etaleFundamentalGroup Ω s) := by
  rcases le_zero_or_eq_one_of_le_one hZ with h0 | h1
  · exact isTopologicallyFG_of_topologicalKrullDim_le_zero sZ h0 Ω s
  · exact isTopologicallyFG_of_forall_planeCurve sZ hP h1 Ω s

end SGA.SGA1.ExposeX
