/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import Mathlib.RingTheory.DedekindDomain.Dvr
import Mathlib.RingTheory.DedekindDomain.IntegralClosure
import Mathlib.RingTheory.Etale.Locus
import Mathlib.RingTheory.Smooth.Fiber
import Mathlib.RingTheory.Unramified.Field
import Mathlib.RingTheory.Unramified.LocalRing
import Mathlib.RingTheory.Unramified.Locus

/-!
# Unramifiedness descends along unramified extensions of discrete valuation rings

Let `B → B'` be a local homomorphism from a discrete valuation ring to a local ring with
`𝔪_B B' = 𝔪_{B'}` and `κ(B')/κ(B)` separable (in the application `B'` is the local ring of
`X ×_V R` at the generic point of its closed fibre, `R` the completed strict henselization of a
discrete valuation ring `V`, and `B` that of `X`). Let `L` be a finite separable extension of
`K = Frac B` and `L'` an `L`-algebra which is a `B'`-algebra compatibly. If the integral closure of
`B'` in `L'` is unramified over `B'` at a prime `Q'` lying over the prime `Q` of the integral
closure `C` of `B` in `L`, then `C` is unramified over `B` at `Q`
(`isUnramifiedAt_integralClosure_of_isUnramifiedAt`). Hence `C` is étale over `B` as soon as
every nonzero prime of `C` lies under such a `Q'` (`etale_integralClosure_of_forall_exists`).

The argument is Serre's (*Local fields*, I §4): a uniformizer `π` of `B` stays one in `C'_{Q'}`,
hence (`Irreducible.of_map`) in the discrete valuation ring `C_Q`, so `e(Q/B) = 1`; and
`κ(Q) ⊆ κ(Q')` is separable over `κ(B)` because `κ(Q')/κ(B')` and `κ(B')/κ(B)` are.

This is used in the proof of the second part of SGA 1 XIII.4.4 over a regular base: a covering of
the generic fibre whose inverse image over the completed strict henselization `R` of the local ring
at a codimension-one point extends over `R` already extends over the local ring itself. No
excellence is needed (the map `B → B'` need not be regular).
-/

open IsLocalRing

namespace SGA.SGA1.ExposeX

/-- In a local ring whose maximal ideal is generated by a nonzero element `x`, `x` is
irreducible. This is mathlib's `IsDiscreteValuationRing.irreducible_of_span_eq_maximalIdeal`
without its `[IsDomain D]` assumption, which is needed for localizations `Localization.AtPrime Q'`
that need not be domains. -/
theorem irreducible_of_maximalIdeal_eq_span {D : Type*} [CommRing D] [IsLocalRing D] {x : D}
    (hx : maximalIdeal D = Ideal.span {x}) (h0 : x ≠ 0) : Irreducible x := by
  have hxm : x ∈ maximalIdeal D := hx ▸ Ideal.mem_span_singleton_self x
  refine ⟨fun hu ↦ (maximalIdeal.isMaximal D).ne_top (Ideal.eq_top_of_isUnit_mem _ hxm hu),
    fun a b hab ↦ ?_⟩
  by_contra! h
  obtain ⟨ha, hb⟩ := h
  have ha' : a ∈ Ideal.span {x} := hx ▸ (mem_maximalIdeal a).mpr ha
  have hb' : b ∈ Ideal.span {x} := hx ▸ (mem_maximalIdeal b).mpr hb
  obtain ⟨a', rfl⟩ := Ideal.mem_span_singleton'.mp ha'
  obtain ⟨b', rfl⟩ := Ideal.mem_span_singleton'.mp hb'
  have hu : IsUnit (1 - a' * b' * x) := by
    refine (isUnit_or_isUnit_one_sub_self (a' * b' * x)).resolve_left fun hu ↦ ?_
    exact (mem_maximalIdeal _).mp (Ideal.mul_mem_left _ _ hxm) hu
  apply h0
  have : x * (1 - a' * b' * x) = 0 := by
    rw [mul_sub, mul_one, sub_eq_zero]
    calc x = a' * x * (b' * x) := hab
      _ = x * (a' * b' * x) := by ring
  exact (hu.mul_left_eq_zero).mp this

/-- The localization of `S` at a prime `q` lying over the maximal ideal of a local ring `R` is a
local `R`-algebra. -/
lemma isLocalHom_algebraMap_localization {R S : Type*} [CommRing R] [IsLocalRing R] [CommRing S]
    [Algebra R S] (q : Ideal S) [q.IsPrime] (h : q.comap (algebraMap R S) = maximalIdeal R) :
    IsLocalHom (algebraMap R (Localization.AtPrime q)) := by
  refine ⟨fun r hr ↦ ?_⟩
  rw [IsScalarTower.algebraMap_apply R S,
    IsLocalization.AtPrime.isUnit_to_map_iff (Localization.AtPrime q) q] at hr
  by_contra hnu
  exact hr (show r ∈ q.comap (algebraMap R S) from h ▸ (mem_maximalIdeal r).mpr hnu)

variable {B : Type*} [CommRing B] [IsDomain B] [IsDiscreteValuationRing B]
  (K : Type*) [Field K] [Algebra B K] [IsFractionRing B K]
  (L : Type*) [Field L] [Algebra K L] [Algebra B L] [IsScalarTower B K L] [FiniteDimensional K L]
  [Algebra.IsSeparable K L]
  {B' : Type*} [CommRing B'] [IsLocalRing B'] [Algebra B B'] [IsLocalHom (algebraMap B B')]
  (L' : Type*) [CommRing L'] [Algebra B' L'] [Algebra L L'] [Algebra B L'] [IsScalarTower B L L']
  [IsScalarTower B B' L']

/-- The map from the integral closure of `B` in `L` to that of `B'` in `L'`. -/
noncomputable def integralClosureMap : integralClosure B L →ₐ[B] integralClosure B' L' where
  toFun x := ⟨algebraMap L L' x, (x.2.map (IsScalarTower.toAlgHom B L L')).tower_top⟩
  map_one' := Subtype.ext (map_one _)
  map_mul' _ _ := Subtype.ext (map_mul _ _ _)
  map_zero' := Subtype.ext (map_zero _)
  map_add' _ _ := Subtype.ext (map_add _ _ _)
  commutes' b := Subtype.ext <| by
    change algebraMap L L' (algebraMap B L b) = algebraMap B L' b
    rw [← IsScalarTower.algebraMap_apply]

variable {K L L'}

omit [IsDomain B] [IsDiscreteValuationRing B] [IsLocalRing B'] [IsLocalHom (algebraMap B B')] in
lemma integralClosureMap_algebraMap (b : B) :
    integralClosureMap L L' (algebraMap B (integralClosure B L) b) =
      algebraMap B (integralClosure B' L') b :=
  (integralClosureMap L L').commutes b

variable (K) in
include K in
/-- A nonzero prime of the integral closure of `B` in `L` lies over the maximal ideal of `B`. -/
lemma comap_eq_maximalIdeal_of_ne_bot (Q : Ideal (integralClosure B L)) [Q.IsPrime]
    (hQ : Q ≠ ⊥) : Q.comap (algebraMap B (integralClosure B L)) = maximalIdeal B := by
  have : IsDedekindDomain (integralClosure B L) := integralClosure.isDedekindDomain B K L
  have hne : Q.comap (algebraMap B (integralClosure B L)) ≠ ⊥ :=
    Ideal.comap_ne_bot_of_integral_mem (x := (Submodule.ne_bot_iff Q).mp hQ |>.choose)
      ((Submodule.ne_bot_iff Q).mp hQ).choose_spec.2 ((Submodule.ne_bot_iff Q).mp hQ).choose_spec.1
      (Algebra.IsIntegral.isIntegral _)
  exact IsLocalRing.eq_maximalIdeal (Ideal.IsPrime.isMaximal inferInstance hne)

variable (K) in
include K in
/-- **Unramifiedness descends along `B → B'`.** Let `B` be a discrete valuation ring, `B → B'` a
local homomorphism to a local ring with `𝔪_B B' = 𝔪_{B'}` and `κ(B')/κ(B)` separable, `L` a finite
separable extension of `K = Frac B` and `L'` an `L`-algebra compatible with `B'`, with the integral
closure `C'` of `B'` in `L'` of finite type over `B'`. If `C'` is unramified over `B'` at a prime
`Q'` lying over the nonzero prime `Q` of the integral closure `C` of `B` in `L`, then `C` is
unramified over `B` at `Q`. -/
theorem isUnramifiedAt_integralClosure_of_isUnramifiedAt
    (hm : (maximalIdeal B).map (algebraMap B B') = maximalIdeal B')
    [Algebra.IsSeparable (ResidueField B) (ResidueField B')]
    [Algebra.FiniteType B' (integralClosure B' L')]
    (Q : Ideal (integralClosure B L)) [Q.IsPrime] (hQ : Q ≠ ⊥)
    (Q' : Ideal (integralClosure B' L')) [Q'.IsPrime]
    (hQQ' : Q'.comap (integralClosureMap (B := B) (B' := B') L L').toRingHom = Q)
    [Algebra.IsUnramifiedAt B' Q'] :
    Algebra.IsUnramifiedAt B Q := by
  have : IsDedekindDomain (integralClosure B L) := integralClosure.isDedekindDomain B K L
  have : Module.Finite B (integralClosure B L) := IsIntegralClosure.finite B K L _
  have : IsDiscreteValuationRing (Localization.AtPrime Q) :=
    IsLocalization.AtPrime.isDiscreteValuationRing_of_dedekind_domain _ hQ _
  let φ : integralClosure B L →+* integralClosure B' L' := (integralClosureMap L L').toRingHom
  let ψ : Localization.AtPrime Q →+* Localization.AtPrime Q' :=
    Localization.localRingHom Q Q' φ hQQ'.symm
  have hψ (c : integralClosure B L) :
      ψ (algebraMap _ (Localization.AtPrime Q) c) = algebraMap _ (Localization.AtPrime Q') (φ c) :=
    Localization.localRingHom_to_map Q Q' φ hQQ'.symm c
  have hQB := comap_eq_maximalIdeal_of_ne_bot K Q hQ
  -- `Q'` lies over the maximal ideal of `B'`
  have hQ'B : Q'.comap (algebraMap B' (integralClosure B' L')) = maximalIdeal B' := by
    refine le_antisymm (IsLocalRing.le_maximalIdeal (Ideal.IsPrime.ne_top inferInstance)) ?_
    rw [← hm, Ideal.map_le_iff_le_comap, Ideal.comap_comap,
      ← IsScalarTower.algebraMap_eq, ← hQB, ← hQQ', Ideal.comap_comap]
    refine le_of_eq (congrArg (Ideal.comap · Q') ?_)
    ext b
    exact congrArg Subtype.val (integralClosureMap_algebraMap (B' := B') (L := L) (L' := L') b)
  have := isLocalHom_algebraMap_localization Q hQB
  have := isLocalHom_algebraMap_localization Q' hQ'B
  have : IsLocalHom (algebraMap B (Localization.AtPrime Q')) := by
    rw [IsScalarTower.algebraMap_eq B B' (Localization.AtPrime Q')]
    infer_instance
  have : Algebra.EssFiniteType B (Localization.AtPrime Q) :=
    .comp B (integralClosure B L) _
  have : Algebra.EssFiniteType B' (Localization.AtPrime Q') :=
    .comp B' (integralClosure B' L') _
  have hD' : (maximalIdeal B').map (algebraMap B' (Localization.AtPrime Q')) =
      maximalIdeal (Localization.AtPrime Q') :=
    Algebra.FormallyUnramified.map_maximalIdeal
  -- a uniformizer `π` of `B`
  obtain ⟨π, hπ⟩ := IsDiscreteValuationRing.exists_irreducible B
  have hπm : maximalIdeal B = Ideal.span {π} :=
    (IsDiscreteValuationRing.irreducible_iff_uniformizer π).mp hπ
  have hψπ (b : B) : ψ (algebraMap B (Localization.AtPrime Q) b) =
      algebraMap B (Localization.AtPrime Q') b := by
    rw [IsScalarTower.algebraMap_apply B (integralClosure B L) (Localization.AtPrime Q), hψ,
      IsScalarTower.algebraMap_apply B (integralClosure B' L') (Localization.AtPrime Q')]
    exact congrArg _ (integralClosureMap_algebraMap b)
  -- `π` generates the maximal ideal of `C'_{Q'}` and is nonzero there
  have hspan' : maximalIdeal (Localization.AtPrime Q') =
      Ideal.span {algebraMap B (Localization.AtPrime Q') π} := by
    rw [← hD', ← hm, Ideal.map_map, ← IsScalarTower.algebraMap_eq, hπm, Ideal.map_span,
      Set.image_singleton]
  have hπL : IsUnit (algebraMap B L' π) := by
    rw [IsScalarTower.algebraMap_apply B L L']
    refine IsUnit.map _ (isUnit_iff_ne_zero.mpr ?_)
    rw [IsScalarTower.algebraMap_apply B K L]
    refine (map_ne_zero_iff _ (algebraMap K L).injective).mpr ?_
    exact (map_ne_zero_iff _ (IsFractionRing.injective B K)).mpr hπ.ne_zero
  have hπ0 : algebraMap B (Localization.AtPrime Q') π ≠ 0 := by
    rw [IsScalarTower.algebraMap_apply B (integralClosure B' L') (Localization.AtPrime Q'),
      Ne, IsLocalization.map_eq_zero_iff Q'.primeCompl]
    rintro ⟨⟨m, hm'⟩, hm0⟩
    have : (m : L') * algebraMap B L' π = 0 := by
      have := congrArg Subtype.val hm0
      simpa [← IsScalarTower.algebraMap_apply] using this
    have hm0' : (m : L') = 0 := (hπL.mul_left_eq_zero).mp this
    exact hm' (show m ∈ Q' from (Subtype.ext hm0' : m = 0) ▸ Q'.zero_mem)
  have hirr' := irreducible_of_maximalIdeal_eq_span hspan' hπ0
  have hirr : Irreducible (algebraMap B (Localization.AtPrime Q) π) :=
    Irreducible.of_map (f := ψ) (by rwa [hψπ])
  have hmap : (maximalIdeal B).map (algebraMap B (Localization.AtPrime Q)) =
      maximalIdeal (Localization.AtPrime Q) := by
    rw [(IsDiscreteValuationRing.irreducible_iff_uniformizer _).mp hirr, hπm, Ideal.map_span,
      Set.image_singleton]
  -- the residue field extension is separable
  let e : Localization.AtPrime Q →ₐ[B] Localization.AtPrime Q' :=
    { ψ with commutes' := hψπ }
  have : IsLocalHom e := ⟨fun x hx ↦ (inferInstance : IsLocalHom ψ).map_nonunit x hx⟩
  have : Algebra.IsSeparable (ResidueField B) (ResidueField (Localization.AtPrime Q')) :=
    Algebra.IsSeparable.trans (ResidueField B) (ResidueField B') _
  have : Algebra.IsSeparable (ResidueField B) (ResidueField (Localization.AtPrime Q)) :=
    Algebra.IsSeparable.of_algHom _ _ (IsLocalRing.ResidueField.mapAlgHom' e)
  exact Algebra.FormallyUnramified.of_map_maximalIdeal hmap

omit [IsDiscreteValuationRing B] in
variable (K) in
include K in
/-- The integral closure of `B` in `L` is unramified at the zero ideal (its fraction field is the
separable extension `L` of `K`). -/
lemma isUnramifiedAt_integralClosure_bot :
    Algebra.IsUnramifiedAt B (⊥ : Ideal (integralClosure B L)) := by
  have : IsFractionRing (integralClosure B L)
      (Localization.AtPrime (⊥ : Ideal (integralClosure B L))) := by
    simpa [Ideal.primeCompl_bot] using
      Localization.isLocalization (M := (⊥ : Ideal (integralClosure B L)).primeCompl)
  have : IsFractionRing (integralClosure B L) L :=
    integralClosure.isFractionRing_of_finite_extension K L
  let e : L ≃ₐ[integralClosure B L] Localization.AtPrime (⊥ : Ideal (integralClosure B L)) :=
    IsLocalization.algEquiv (nonZeroDivisors (integralClosure B L)) L _
  have : Algebra.FormallyUnramified B K := .of_isLocalization (nonZeroDivisors B)
  have : Algebra.FormallyUnramified K L := .of_isSeparable K L
  have : Algebra.FormallyUnramified B L := .comp B K L
  exact Algebra.FormallyUnramified.of_equiv (e.restrictScalars B)

variable (K) in
include K in
/-- **Étaleness descends along `B → B'`.** With the hypotheses of
`isUnramifiedAt_integralClosure_of_isUnramifiedAt`, if every nonzero prime `Q` of the integral
closure `C` of `B` in `L` lies under a prime of the integral closure of `B'` in `L'` at which the
latter is unramified over `B'`, then `C` is étale over `B`. -/
theorem etale_integralClosure_of_forall_exists
    (hm : (maximalIdeal B).map (algebraMap B B') = maximalIdeal B')
    [Algebra.IsSeparable (ResidueField B) (ResidueField B')]
    [Algebra.FiniteType B' (integralClosure B' L')]
    (h : ∀ (Q : Ideal (integralClosure B L)) [Q.IsPrime], Q ≠ ⊥ →
      ∃ (Q' : Ideal (integralClosure B' L')) (_ : Q'.IsPrime),
        Q'.comap (integralClosureMap (B := B) (B' := B') L L').toRingHom = Q ∧
          Algebra.IsUnramifiedAt B' Q') :
    Algebra.Etale B (integralClosure B L) := by
  have : IsDedekindDomain (integralClosure B L) := integralClosure.isDedekindDomain B K L
  have : Module.Finite B (integralClosure B L) := IsIntegralClosure.finite B K L _
  have : Module.IsTorsionFree B L := by
    rw [Module.isTorsionFree_iff_algebraMap_injective, IsScalarTower.algebraMap_eq B K L]
    exact (algebraMap K L).injective.comp (IsFractionRing.injective B K)
  have : Module.IsTorsionFree B (integralClosure B L) := IsIntegralClosure.isTorsionFree B L
  have : Algebra.FinitePresentation B (integralClosure B L) :=
    Algebra.FinitePresentation.of_finiteType.mp inferInstance
  have : Algebra.FormallyUnramified B (integralClosure B L) := by
    rw [Algebra.formallyUnramified_iff_forall]
    intro q
    by_cases hq : q.asIdeal = ⊥
    · have : q = ⟨⊥, Ideal.isPrime_bot⟩ := PrimeSpectrum.ext hq
      subst this
      exact isUnramifiedAt_integralClosure_bot K
    · obtain ⟨Q', _, hQQ', _⟩ := h q.asIdeal hq
      exact isUnramifiedAt_integralClosure_of_isUnramifiedAt K hm q.asIdeal hq Q' hQQ'
  exact Algebra.Etale.of_formallyUnramified_of_flat

end SGA.SGA1.ExposeX
