/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.Foundations.Ample
import SGA.Foundations.Analytic.AnalyticSpace
import SGA.Foundations.Analytic.Analytification
import SGA.Foundations.Analytic.CompactPerturbation
import SGA.Foundations.Analytic.Completion
import SGA.Foundations.Analytic.ConvergentPowerSeries
import SGA.Foundations.Analytic.Cousin
import SGA.Foundations.Analytic.Dolbeault
import SGA.Foundations.Analytic.DolbeaultDisc
import SGA.Foundations.Analytic.Flatness
import SGA.Foundations.Analytic.GermEval
import SGA.Foundations.Analytic.GluingLocalization
import SGA.Foundations.Analytic.Hadamard
import SGA.Foundations.Analytic.Henselian
import SGA.Foundations.Analytic.JetComparison
import SGA.Foundations.Analytic.LocalModel
import SGA.Foundations.Analytic.LocalModelHom
import SGA.Foundations.Analytic.LyingOver
import SGA.Foundations.Analytic.Modules
import SGA.Foundations.Analytic.Montel
import SGA.Foundations.Analytic.Morphisms
import SGA.Foundations.Analytic.Noetherian
import SGA.Foundations.Analytic.Nullstellensatz
import SGA.Foundations.Analytic.OpenSubspace
import SGA.Foundations.Analytic.PowerSeriesExpansion
import SGA.Foundations.Analytic.Presentation
import SGA.Foundations.Analytic.PrincipalOpen
import SGA.Foundations.Analytic.RiemannSurfaceCech
import SGA.Foundations.Analytic.RiemannSurfaceCompactification
import SGA.Foundations.Analytic.RiemannSurfaceDisc
import SGA.Foundations.Analytic.RiemannSurfaceMeromorphic
import SGA.Foundations.Analytic.RiemannSurfacePunctures
import SGA.Foundations.Analytic.RiemannSurfaceRefinement
import SGA.Foundations.Analytic.SectionMorphism
import SGA.Foundations.Analytic.Sheaf
import SGA.Foundations.Analytic.Stalk
import SGA.Foundations.Analytic.Statements
import SGA.Foundations.Analytic.Substitution
import SGA.Foundations.Analytic.UniversalProperty
import SGA.Foundations.Analytic.WeierstrassDivision
import SGA.Foundations.Cohomology.AdicSheafSystem
import SGA.Foundations.Cohomology.AffineHom
import SGA.Foundations.Cohomology.AffineOpenVanishing
import SGA.Foundations.Cohomology.AffineVanishing
import SGA.Foundations.Cohomology.AlgebraAlgebraization
import SGA.Foundations.Cohomology.ArtinRees
import SGA.Foundations.Cohomology.ArtinReesHom
import SGA.Foundations.Cohomology.BaseChangeAlgebra
import SGA.Foundations.Cohomology.BaseChangeCover
import SGA.Foundations.Cohomology.BaseChangeLocal
import SGA.Foundations.Cohomology.BaseChangeSections
import SGA.Foundations.Cohomology.Basic
import SGA.Foundations.Cohomology.Cartan
import SGA.Foundations.Cohomology.Cech
import SGA.Foundations.Cohomology.CechComparison
import SGA.Foundations.Cohomology.CechFinite
import SGA.Foundations.Cohomology.CechLocalization
import SGA.Foundations.Cohomology.CechMonomial
import SGA.Foundations.Cohomology.CechTransport
import SGA.Foundations.Cohomology.CechVanishing
import SGA.Foundations.Cohomology.ClosedFibre
import SGA.Foundations.Cohomology.ClosedImmersionSections
import SGA.Foundations.Cohomology.Coherent
import SGA.Foundations.Cohomology.CohomologicalDimension
import SGA.Foundations.Cohomology.CohomologyLemmas
import SGA.Foundations.Cohomology.Devissage
import SGA.Foundations.Cohomology.EulerCharacteristic
import SGA.Foundations.Cohomology.EulerCharacteristicBaseChange
import SGA.Foundations.Cohomology.EulerCharacteristicBasic
import SGA.Foundations.Cohomology.EulerCharacteristicClopen
import SGA.Foundations.Cohomology.EulerCharacteristicDevissage
import SGA.Foundations.Cohomology.EulerCharacteristicFiniteEtale
import SGA.Foundations.Cohomology.EulerCharacteristicFiniteEtaleProof
import SGA.Foundations.Cohomology.EulerCharacteristicGeneric
import SGA.Foundations.Cohomology.EulerCharacteristicPullback
import SGA.Foundations.Cohomology.ExistenceFullyFaithful
import SGA.Foundations.Cohomology.ExistenceLocallyFree
import SGA.Foundations.Cohomology.Extension
import SGA.Foundations.Cohomology.FiniteEtaleAlgebraization
import SGA.Foundations.Cohomology.FiniteEtaleEquivalence
import SGA.Foundations.Cohomology.FiniteEtaleExistence
import SGA.Foundations.Cohomology.FiniteHomAlgebraization
import SGA.Foundations.Cohomology.FlatBaseChange
import SGA.Foundations.Cohomology.FormalFunctions
import SGA.Foundations.Cohomology.FormalPullback
import SGA.Foundations.Cohomology.GeometricConnectedness
import SGA.Foundations.Cohomology.Godement
import SGA.Foundations.Cohomology.GradedSheaf
import SGA.Foundations.Cohomology.HProjective
import SGA.Foundations.Cohomology.Helpers
import SGA.Foundations.Cohomology.HomTwist
import SGA.Foundations.Cohomology.IdealPowers
import SGA.Foundations.Cohomology.InvertibleSheaf
import SGA.Foundations.Cohomology.Leray
import SGA.Foundations.Cohomology.LerayNaturality
import SGA.Foundations.Cohomology.LerayTransfer
import SGA.Foundations.Cohomology.LocallyFreeAlgebraization
import SGA.Foundations.Cohomology.LongExactSequence
import SGA.Foundations.Cohomology.Modules
import SGA.Foundations.Cohomology.ProIsoAlgebraization
import SGA.Foundations.Cohomology.ProjectiveMorphism
import SGA.Foundations.Cohomology.ProjectiveSpace
import SGA.Foundations.Cohomology.ProjectiveSpaceTwist
import SGA.Foundations.Cohomology.ProperFiniteness
import SGA.Foundations.Cohomology.ProperProjectivity
import SGA.Foundations.Cohomology.Pushforward
import SGA.Foundations.Cohomology.PushforwardLeray
import SGA.Foundations.Cohomology.PushforwardProjective
import SGA.Foundations.Cohomology.QuasiCoherentAbelian
import SGA.Foundations.Cohomology.QuasiCoherentBiproduct
import SGA.Foundations.Cohomology.QuasiCoherentKernel
import SGA.Foundations.Cohomology.QuasiCoherentLocal
import SGA.Foundations.Cohomology.ReesBound
import SGA.Foundations.Cohomology.ReesCohomology
import SGA.Foundations.Cohomology.ReesMaps
import SGA.Foundations.Cohomology.ReesSheaf
import SGA.Foundations.Cohomology.RelativeArtinRees
import SGA.Foundations.Cohomology.RelativeSerre
import SGA.Foundations.Cohomology.RelativeSpec
import SGA.Foundations.Cohomology.RelativeSpecEtale
import SGA.Foundations.Cohomology.RelativeSpecFunctoriality
import SGA.Foundations.Cohomology.RelativeSpecUniversal
import SGA.Foundations.Cohomology.SeparatingSections
import SGA.Foundations.Cohomology.Serre
import SGA.Foundations.Cohomology.SerreFiniteness
import SGA.Foundations.Cohomology.SheafHomCoherent
import SGA.Foundations.Cohomology.Statements
import SGA.Foundations.Cohomology.SteinAlgebraization
import SGA.Foundations.Cohomology.SteinEtale
import SGA.Foundations.Cohomology.SteinFactorization
import SGA.Foundations.Cohomology.Thickening
import SGA.Foundations.Cohomology.ThickeningReduction
import SGA.Foundations.Cohomology.TrivialIdempotents
import SGA.Foundations.Cohomology.Twist
import SGA.Foundations.Cohomology.TwistBaseChange
import SGA.Foundations.Cohomology.TwistGeneration
import SGA.Foundations.Cohomology.TwistProjection
import SGA.Foundations.Cohomology.UniformVanishing
import SGA.Foundations.Cohomology.ZariskiConnectedness
import SGA.Foundations.CommAlg.AuslanderBuchsbaum
import SGA.Foundations.CommAlg.BasicOpenHartogs
import SGA.Foundations.CommAlg.Depth
import SGA.Foundations.CommAlg.Discriminant
import SGA.Foundations.CommAlg.Factorial
import SGA.Foundations.CommAlg.FlatDepth
import SGA.Foundations.CommAlg.NoetherFiniteness
import SGA.Foundations.CommAlg.Normal
import SGA.Foundations.CommAlg.PairSections
import SGA.Foundations.CommAlg.PuncturedSpectrum
import SGA.Foundations.CommAlg.Purity
import SGA.Foundations.CommAlg.PurityCompletion
import SGA.Foundations.CommAlg.PurityHull
import SGA.Foundations.CommAlg.PurityInduction
import SGA.Foundations.CommAlg.PurityLift
import SGA.Foundations.CommAlg.PurityQuasiFinite
import SGA.Foundations.CommAlg.PurityScheme
import SGA.Foundations.CommAlg.PurityStalk
import SGA.Foundations.CommAlg.RegularLocalRing
import SGA.Foundations.CommAlg.RegularPair
import SGA.Foundations.CompleteLocalQuasiFinite
import SGA.Foundations.CompletionDimension
import SGA.Foundations.Desingularization
import SGA.Foundations.Differentials.Affine
import SGA.Foundations.Differentials.AffineOpens
import SGA.Foundations.Differentials.BaseChange
import SGA.Foundations.Differentials.BaseChangeAffine
import SGA.Foundations.Differentials.Basic
import SGA.Foundations.Differentials.DerivationOn
import SGA.Foundations.Differentials.Exact
import SGA.Foundations.Differentials.Localization
import SGA.Foundations.Differentials.Presheaf
import SGA.Foundations.Differentials.QuasiCoherent
import SGA.Foundations.Differentials.Restrict
import SGA.Foundations.Differentials.Sections
import SGA.Foundations.Differentials.SheafHom
import SGA.Foundations.Differentials.Smooth
import SGA.Foundations.Differentials.Tangent
import SGA.Foundations.Differentials.Tilde
import SGA.Foundations.Differentials.Unramified
import SGA.Foundations.Dimension.Equidimensional
import SGA.Foundations.Dimension.FiberDimension
import SGA.Foundations.Dimension.FiniteType
import SGA.Foundations.Dimension.FlatFiber
import SGA.Foundations.Dimension.FlatLocal
import SGA.Foundations.Dimension.FlatScheme
import SGA.Foundations.Dimension.Integral
import SGA.Foundations.Dimension.LocalDimension
import SGA.Foundations.Dimension.QuasiFinite
import SGA.Foundations.Dimension.Scheme
import SGA.Foundations.Dimension.Semicontinuity
import SGA.Foundations.Dimension.Smooth
import SGA.Foundations.Dimension.StalkKrullDim
import SGA.Foundations.Etale.BaseChange
import SGA.Foundations.Etale.ChangeOfGroup
import SGA.Foundations.Etale.ConstantScheme
import SGA.Foundations.Etale.Functoriality
import SGA.Foundations.Etale.GabberDescent
import SGA.Foundations.Etale.GabberFiniteCover
import SGA.Foundations.Etale.GabberHenselian
import SGA.Foundations.Etale.GabberProper
import SGA.Foundations.Etale.GabberZariski
import SGA.Foundations.Etale.GroupObjectTorsor
import SGA.Foundations.Etale.HigherDirectImage
import SGA.Foundations.Etale.LocalAcyclicity
import SGA.Foundations.Etale.LocalAcyclicityBaseChange
import SGA.Foundations.Etale.LocalAcyclicityComparison
import SGA.Foundations.Etale.LocalAcyclicityConstant
import SGA.Foundations.Etale.LocalAcyclicityHenselian
import SGA.Foundations.Etale.LocalAcyclicityStrictLocalization
import SGA.Foundations.Etale.LocallyConstant
import SGA.Foundations.Etale.NonabelianExact
import SGA.Foundations.Etale.Picard
import SGA.Foundations.Etale.Points
import SGA.Foundations.Etale.ProperBaseChangeClopen
import SGA.Foundations.Etale.ProperBaseChangeClosure
import SGA.Foundations.Etale.Representable
import SGA.Foundations.Etale.RepresentableGluing
import SGA.Foundations.Etale.Restriction
import SGA.Foundations.Etale.StructureSheaf
import SGA.Foundations.Etale.Torsor
import SGA.Foundations.Etale.TorsorCech
import SGA.Foundations.Etale.TorsorDescent
import SGA.Foundations.Etale.TorsorEtale
import SGA.Foundations.Etale.TorsorPresheaf
import SGA.Foundations.Etale.TorsorProduct
import SGA.Foundations.Etale.TorsorPullback
import SGA.Foundations.Etale.TorsorPushforward
import SGA.Foundations.Etale.TorsorStack
import SGA.Foundations.Etale.TorsorTwist
import SGA.Foundations.EtaleSpreadingOut
import SGA.Foundations.EtaleStalk
import SGA.Foundations.EtaleStalkBaseChange
import SGA.Foundations.EtaleStalkProper
import SGA.Foundations.EtaleStalkProperLimit
import SGA.Foundations.EtaleStalkProperRepresentable
import SGA.Foundations.EtaleStalkPullback
import SGA.Foundations.EtaleStalkPushforward
import SGA.Foundations.EtaleStalkStructureSheaf
import SGA.Foundations.EtaleStalkTorsor
import SGA.Foundations.Fields.ComplexEmbedding
import SGA.Foundations.Fields.Differentials
import SGA.Foundations.Fields.GeometricallyConnected
import SGA.Foundations.Fields.GeometricallyIntegral
import SGA.Foundations.Fields.GeometricallyReduced
import SGA.Foundations.Fields.GeometricallyReducedScheme
import SGA.Foundations.Fields.MacLane
import SGA.Foundations.Fields.Separable
import SGA.Foundations.Fields.SeparablyGenerated
import SGA.Foundations.Formal.AdicInverseLimit
import SGA.Foundations.Formal.AdicRing
import SGA.Foundations.Formal.AdicSystem
import SGA.Foundations.Formal.Completion
import SGA.Foundations.Formal.CompletionLocal
import SGA.Foundations.Formal.CompletionNoetherian
import SGA.Foundations.Formal.EtaleCovering
import SGA.Foundations.Formal.EtaleLift
import SGA.Foundations.Formal.FiniteEtale
import SGA.Foundations.Formal.FiniteEtaleSpec
import SGA.Foundations.Formal.FormalColimit
import SGA.Foundations.Formal.FormalScheme
import SGA.Foundations.Formal.NoetherianOfComplete
import SGA.Foundations.Formal.OpenImmersion
import SGA.Foundations.Formal.Spf
import SGA.Foundations.Formal.SpfBasicOpen
import SGA.Foundations.Formal.SpfCompletion
import SGA.Foundations.Formal.SpfInverseLimit
import SGA.Foundations.Formal.SpfMorphisms
import SGA.Foundations.Formal.TowerLimit
import SGA.Foundations.GroupScheme.LocalEndomorphism
import SGA.Foundations.GroupScheme.MulNCotangent
import SGA.Foundations.GroupScheme.Points
import SGA.Foundations.HenselianDegree
import SGA.Foundations.HenselianFinite
import SGA.Foundations.HenselianFiniteEtale
import SGA.Foundations.HenselianFiniteLocal
import SGA.Foundations.HenselianLifting
import SGA.Foundations.HenselianQuasiFinite
import SGA.Foundations.Henselization
import SGA.Foundations.HenselizationNoetherian
import SGA.Foundations.Limits.BaseChange
import SGA.Foundations.Limits.EtaleSections
import SGA.Foundations.Limits.EtaleSectionsAlong
import SGA.Foundations.Limits.EtaleSectionsGluing
import SGA.Foundations.Limits.FiniteEtale
import SGA.Foundations.Limits.GeometricFiberCard
import SGA.Foundations.Limits.GeometricFiberCardIso
import SGA.Foundations.Limits.IntegralApproximation
import SGA.Foundations.Limits.SpecFibre
import SGA.Foundations.NoetherianApproximation
import SGA.Foundations.NormalizationFinite
import SGA.Foundations.Patching.Factorization
import SGA.Foundations.Patching.Fields
import SGA.Foundations.Patching.Modules
import SGA.Foundations.Patching.ProjectiveLine
import SGA.Foundations.Patching.ProjectiveLineIntersection
import SGA.Foundations.Patching.ProjectiveLineNode
import SGA.Foundations.Patching.ProjectiveLineNodeField
import SGA.Foundations.Patching.ProjectiveLineNodeTwist
import SGA.Foundations.Pro.Basic
import SGA.Foundations.Pro.ContAction
import SGA.Foundations.Pro.Equivalence
import SGA.Foundations.Pro.Representable
import SGA.Foundations.Pro.TopologicallyFG
import SGA.Foundations.Projective.AmpleDescent
import SGA.Foundations.Projective.AmpleFinite
import SGA.Foundations.Projective.AmpleLocal
import SGA.Foundations.Projective.AmpleProj
import SGA.Foundations.Projective.Chow
import SGA.Foundations.Projective.Dehomogenization
import SGA.Foundations.Projective.GradedQuotient
import SGA.Foundations.Projective.LineBundle
import SGA.Foundations.Projective.LineBundleIso
import SGA.Foundations.Projective.Morphisms
import SGA.Foundations.Projective.Norm
import SGA.Foundations.Projective.NormLineBundle
import SGA.Foundations.Projective.PlaneModel
import SGA.Foundations.Projective.PlaneModelField
import SGA.Foundations.Projective.ProjBaseChange
import SGA.Foundations.Projective.ProjectiveSpace
import SGA.Foundations.Projective.ProjectiveSpaceHom
import SGA.Foundations.Projective.ProjectiveSpaceSpec
import SGA.Foundations.Projective.QuasiProjective
import SGA.Foundations.Projective.RelativeProj
import SGA.Foundations.Projective.SectionExtension
import SGA.Foundations.Projective.SectionRing
import SGA.Foundations.Projective.SectionRingMaps
import SGA.Foundations.Projective.SectionsBaseChange
import SGA.Foundations.Projective.Segre
import SGA.Foundations.Projective.ToProj
import SGA.Foundations.Projective.TwistingSheaf
import SGA.Foundations.QuasiAffine
import SGA.Foundations.QuasiCoherent.Cokernel
import SGA.Foundations.QuasiCoherent.Descent
import SGA.Foundations.QuasiCoherent.DescentChart
import SGA.Foundations.QuasiCoherent.DescentEffective
import SGA.Foundations.QuasiCoherent.DescentLocalIso
import SGA.Foundations.QuasiCoherent.DescentLocalizing
import SGA.Foundations.QuasiCoherent.DescentQuotient
import SGA.Foundations.QuasiCoherent.DescentSections
import SGA.Foundations.QuasiCoherent.Glue
import SGA.Foundations.QuasiCoherent.Local
import SGA.Foundations.QuasiCoherent.Pullback
import SGA.Foundations.QuasiCoherent.SchemeTheoreticImage
import SGA.Foundations.QuasiCoherent.Sections
import SGA.Foundations.QuasiCoherent.SpecSections
import SGA.Foundations.QuasiCoherent.Stalk
import SGA.Foundations.QuasiCoherent.StalkModule
import SGA.Foundations.QuasiCoherent.Tilde
import SGA.Foundations.Ramification.BaseLocalization
import SGA.Foundations.Ramification.Henselian
import SGA.Foundations.Ramification.Inertia
import SGA.Foundations.Ramification.IntegralClosure
import SGA.Foundations.Ramification.Pi
import SGA.Foundations.Ramification.Tame
import SGA.Foundations.Ramification.TameInertia
import SGA.Foundations.Ramification.Transport
import SGA.Foundations.SchemeConnectedSpace
import SGA.Foundations.Semialgebraic.Basic
import SGA.Foundations.Semialgebraic.Choice
import SGA.Foundations.Semialgebraic.Closure
import SGA.Foundations.Semialgebraic.Definable
import SGA.Foundations.Semialgebraic.GradientRetraction
import SGA.Foundations.Semialgebraic.Hormander
import SGA.Foundations.Semialgebraic.Line
import SGA.Foundations.Semialgebraic.LocalContractibility
import SGA.Foundations.Semialgebraic.Lojasiewicz
import SGA.Foundations.Semialgebraic.Monotonicity
import SGA.Foundations.Semialgebraic.OneVariable
import SGA.Foundations.Semialgebraic.OrderIso
import SGA.Foundations.Semialgebraic.ParametricHormander
import SGA.Foundations.Semialgebraic.PolynomialCalculus
import SGA.Foundations.Semialgebraic.PseudoDivision
import SGA.Foundations.Semialgebraic.SignDiagram
import SGA.Foundations.Semialgebraic.TarskiSeidenberg
import SGA.Foundations.Smooth.GenericSmoothness
import SGA.Foundations.Smooth.GeometricallyReduced
import SGA.Foundations.SpecStalkLimit
import SGA.Foundations.StrictHenselization
import SGA.Foundations.StrictLocalization
import SGA.Foundations.StrictLocalizationFunctorial
import SGA.Foundations.StrictLocalizationFunctorialFlat
import SGA.Foundations.StrictLocalizationLift
import SGA.Foundations.StrictLocalizationLimit
import SGA.Foundations.StrictlyHenselianFinite
import SGA.Foundations.StrictlyHenselianFiniteScheme
import SGA.Foundations.StrictlyHenselianLift
import SGA.Foundations.Topology.ContractibleNhds
import SGA.Foundations.Topology.ContractibleNhdsLocal
import SGA.Foundations.Topology.CoveringGalois
import SGA.Foundations.Topology.CoveringMapOn
import SGA.Foundations.Topology.CoveringOfFunctor
import SGA.Foundations.Topology.CoveringProd
import SGA.Foundations.Topology.FiniteCovering
import SGA.Foundations.Topology.FiniteCoveringMonodromy
import SGA.Foundations.Topology.FundamentalGroupFG
import SGA.Foundations.Topology.FundamentalGroupFGConvex
import SGA.Foundations.Topology.FundamentalGroupProd
import SGA.Foundations.Topology.GaloisCategoryEquivalence
import SGA.Foundations.Topology.LocallyContractible
import SGA.Foundations.Topology.PathConnectedHelpers
import SGA.Foundations.Topology.PathConnectedHelpersBasic
import SGA.Foundations.Topology.ProfiniteCompletionGalois
import SGA.Foundations.Topology.PuncturedDisc
import SGA.Foundations.Topology.PuncturedDiscConnected
import SGA.Foundations.Topology.PuncturedDiscProduct
import SGA.Foundations.Topology.SemilocallySimplyConnected
import SGA.Foundations.Topology.SurfaceGenusZero
import SGA.Foundations.Topology.VanKampen
import SGA.Foundations.Topology.VanKampenPushout
import SGA.Foundations.Topology.VanKampenTriple
import SGA.Foundations.WeilRestriction

import SGA.Foundations.Analytic.CoherentCartanLemma
import SGA.Foundations.Analytic.CoherentClosure
import SGA.Foundations.Analytic.CoherentCohomology
import SGA.Foundations.Analytic.CoherentFree
import SGA.Foundations.Analytic.CoherentGenerators
import SGA.Foundations.Analytic.CoherentKernel
import SGA.Foundations.Analytic.CoherentRestrict
import SGA.Foundations.Analytic.CoherentSheaf
import SGA.Foundations.Analytic.CoherentStatements
import SGA.Foundations.Analytic.DolbeaultBound
import SGA.Foundations.Analytic.DolbeaultFormSheaf
import SGA.Foundations.Analytic.DolbeaultForms
import SGA.Foundations.Analytic.DolbeaultGlobal
import SGA.Foundations.Analytic.DolbeaultHolomorphic
import SGA.Foundations.Analytic.DolbeaultLocal
import SGA.Foundations.Analytic.DolbeaultOffSupport
import SGA.Foundations.Analytic.DolbeaultParam
import SGA.Foundations.Analytic.DolbeaultPartial
import SGA.Foundations.Analytic.Hartogs
import SGA.Foundations.Analytic.HartogsLaurent
import SGA.Foundations.Analytic.ModulesCohomology
import SGA.Foundations.Analytic.ModulesExactness
import SGA.Foundations.Analytic.ModulesHom
import SGA.Foundations.Analytic.ModulesHomExact
import SGA.Foundations.Analytic.ModulesHomFree
import SGA.Foundations.Analytic.ModulesHomLocal
import SGA.Foundations.Analytic.ModulesHomPresentation
import SGA.Foundations.Analytic.ModulesHomPullback
import SGA.Foundations.Analytic.ModulesHomRestriction
import SGA.Foundations.Analytic.ModulesHomStalk
import SGA.Foundations.Analytic.ModulesStalk
import SGA.Foundations.Analytic.ModulesStalkFree
import SGA.Foundations.Analytic.Oka
import SGA.Foundations.Analytic.OkaAnalyticPolynomial
import SGA.Foundations.Analytic.OkaCylinder
import SGA.Foundations.Analytic.OkaFactorization
import SGA.Foundations.Analytic.OkaInduction
import SGA.Foundations.Analytic.OkaPolynomial
import SGA.Foundations.Analytic.OkaPreparation
import SGA.Foundations.Analytic.OkaReduction
import SGA.Foundations.Analytic.OkaRelationSheaf
import SGA.Foundations.Analytic.OkaRelations
import SGA.Foundations.Analytic.OkaSpreading
import SGA.Foundations.Analytic.OkaStalkPolynomial
import SGA.Foundations.Analytic.OkaWeierstrass
import SGA.Foundations.Analytic.Osgood
import SGA.Foundations.Analytic.OsgoodWeierstrass
import SGA.Foundations.Analytic.RungeBox
import SGA.Foundations.Analytic.RungeLaurent
import SGA.Foundations.Analytic.RungeLaurentProjector
import SGA.Foundations.Analytic.RungeLaurentSplitting
import SGA.Foundations.Analytic.RungeParam
import SGA.Foundations.Analytic.RungeProduct
import SGA.Foundations.Analytic.RungeRect
import SGA.Foundations.Analytic.RungeScheme
import SGA.Foundations.Analytic.StructureSheafCoherent
import SGA.Foundations.Analytic.Syzygy
import SGA.Foundations.Analytic.SyzygyResolution
import SGA.Foundations.Analytic.TheoremB
import SGA.Foundations.ArithmeticSurface.Model
import SGA.Foundations.ArithmeticSurface.ModelStatements
import SGA.Foundations.ArithmeticSurface.Statements
import SGA.Foundations.Blowup.AffineAlgebra
import SGA.Foundations.Blowup.Proj
import SGA.Foundations.Blowup.Quadratic
import SGA.Foundations.Blowup.Rees
import SGA.Foundations.Cohomology.ExtChase
import SGA.Foundations.Cohomology.FormalAlgebraization
import SGA.Foundations.Cohomology.RestrictOpen
import SGA.Foundations.CommAlg.DominatingDVR
import SGA.Foundations.CommAlg.DominatingDVRGeneral
import SGA.Foundations.CommAlg.DominatingDVRLift
import SGA.Foundations.CommAlg.FlatResidueExtension
import SGA.Foundations.CommAlg.FlatResidueExtensionColimit
import SGA.Foundations.CommAlg.FlatResidueExtensionCompletion
import SGA.Foundations.CommAlg.FlatResidueExtensionFree
import SGA.Foundations.CommAlg.FlatResidueExtensionGeneral
import SGA.Foundations.CommAlg.FlatResidueExtensionInseparable
import SGA.Foundations.CommAlg.FlatResidueExtensionPBasis
import SGA.Foundations.CommAlg.FlatResidueExtensionRealize
import SGA.Foundations.CommAlg.FlatResidueExtensionSeparable
import SGA.Foundations.CommAlg.FlatResidueExtensionTranscendental
import SGA.Foundations.CommAlg.KrullAkizuki
import SGA.Foundations.CommAlg.KrullAkizukiFinite
import SGA.Foundations.CommAlg.QuasiSection
import SGA.Foundations.Constructible
import SGA.Foundations.ConstructibleNoetherian
import SGA.Foundations.Formal.AmpleLift
import SGA.Foundations.Formal.AmpleLiftProj
import SGA.Foundations.Hodge.AlternatingSmooth
import SGA.Foundations.Hodge.Dbar
import SGA.Foundations.Hodge.DbarHodgeStatement
import SGA.Foundations.Hodge.DetForm
import SGA.Foundations.Hodge.DolbeaultCohomology
import SGA.Foundations.Hodge.DolbeaultIsomorphism
import SGA.Foundations.Hodge.ExteriorAlgebraAux
import SGA.Foundations.Hodge.ExteriorAlgebraPairs
import SGA.Foundations.Hodge.FormSpan
import SGA.Foundations.Hodge.FormType
import SGA.Foundations.Hodge.FormTypeLinear
import SGA.Foundations.Hodge.HermitianFrame
import SGA.Foundations.Hodge.HodgeSymmetryReduction
import SGA.Foundations.Hodge.Integration
import SGA.Foundations.Hodge.Kahler
import SGA.Foundations.Hodge.KahlerFlat
import SGA.Foundations.Hodge.KahlerHolomorphic
import SGA.Foundations.Hodge.KahlerPositivity
import SGA.Foundations.Hodge.KahlerPower
import SGA.Foundations.Hodge.ManifoldForms
import SGA.Foundations.Hodge.ManifoldWedge
import SGA.Foundations.Hodge.Statements
import SGA.Foundations.Hodge.UnitaryCoordinates
import SGA.Foundations.Hodge.Wedge
import SGA.Foundations.Hodge.WedgeDeriv
import SGA.Foundations.Limits.FibreProperties
import SGA.Foundations.Limits.FibrePropertiesBertiniNoether
import SGA.Foundations.Limits.FibrePropertiesConnected
import SGA.Foundations.Limits.FibrePropertiesConstructible
import SGA.Foundations.Limits.FibrePropertiesDescent
import SGA.Foundations.Limits.FibrePropertiesLimit
import SGA.Foundations.Limits.PropertiesLimit
import SGA.Foundations.Limits.PropertiesLimitClosedImmersion
import SGA.Foundations.Limits.PropertiesLimitEtale
import SGA.Foundations.Limits.PropertiesLimitFinite
import SGA.Foundations.Limits.PropertiesLimitLocal
import SGA.Foundations.Limits.PropertiesLimitProper
import SGA.Foundations.Limits.PropertiesLimitSeparated
import SGA.Foundations.Limits.PropertiesLimitSubfield
import SGA.Foundations.Limits.PropertiesLimitSurjective
import SGA.Foundations.Limits.SpreadingOut
import SGA.Foundations.Limits.SpreadingOutAffine
import SGA.Foundations.Limits.SpreadingOutGluing
import SGA.Foundations.Limits.SpreadingOutNoetherian
import SGA.Foundations.Limits.SpreadingOutSubfield
import SGA.Foundations.NormalizationFiniteDimension
import SGA.Foundations.Patching.LaurentSeriesMap
import SGA.Foundations.Picard.Basic
import SGA.Foundations.Picard.CechProduct
import SGA.Foundations.Picard.Cube
import SGA.Foundations.Picard.FormalSections
import SGA.Foundations.Picard.IntegralSubscheme
import SGA.Foundations.Picard.KunnethAlgebra
import SGA.Foundations.Picard.KunnethCech
import SGA.Foundations.Picard.PoleDivisor
import SGA.Foundations.Picard.ProductSections
import SGA.Foundations.Picard.Seesaw
import SGA.Foundations.Projective.AmpleAffine
import SGA.Foundations.Projective.BertiniConnected
import SGA.Foundations.Projective.BertiniCovers
import SGA.Foundations.Projective.BertiniDimension
import SGA.Foundations.Projective.BertiniField
import SGA.Foundations.Projective.BertiniFieldLemma
import SGA.Foundations.Projective.CurveProjective
import SGA.Foundations.Projective.CurveProjectiveChart
import SGA.Foundations.Projective.PlaneModelCurve
import SGA.Foundations.Projective.PlaneModelEquation
import SGA.Foundations.Projective.PlaneModelFamily
import SGA.Foundations.Projective.PlaneModelHypersurface
import SGA.Foundations.Projective.PlaneModelLift
import SGA.Foundations.Projective.PlaneModelLiftFamily
import SGA.Foundations.Semistable.Components
import SGA.Foundations.Semistable.CurveStatements
import SGA.Foundations.Semistable.IntegerMatrix
import SGA.Foundations.Semistable.LinearAlgebra
import SGA.Foundations.Semistable.NumericalType
import SGA.Foundations.Semistable.NumericalTypeBound
import SGA.Foundations.Semistable.SmoothCurve
import SGA.Foundations.Semistable.Statements
import SGA.Foundations.Topology.FibreBundle
import SGA.Foundations.Topology.FiniteCoveringBaseChange
import SGA.Foundations.Topology.SurfaceBranchedCovering
import SGA.Foundations.Topology.SurfaceContract
import SGA.Foundations.Topology.SurfaceCovering
import SGA.Foundations.Topology.SurfaceFilling
import SGA.Foundations.Topology.SurfaceGenusZeroOrdered
import SGA.Foundations.Topology.SurfaceLoopAround
import SGA.Foundations.Topology.SurfaceNielsen
import SGA.Foundations.Topology.SurfaceOneVertex
import SGA.Foundations.Topology.SurfacePresentation
import SGA.Foundations.Topology.SurfaceRibbon
import SGA.Foundations.Topology.SurfaceRibbonPerm
import SGA.Foundations.Topology.SurfaceSchreier
import SGA.Foundations.Topology.SurfaceSchreierBasis
import SGA.Foundations.Topology.SurfaceSchreierFree
import SGA.Foundations.Topology.SurfaceSchreierTree
import SGA.Foundations.Topology.SurfaceSchreierWord
import SGA.Foundations.Topology.SurfaceSphere
/-!
# Foundations for the SGA formalization

Prerequisites of SGA 1 that mathlib does not have, written in mathlib style (mathlib namespaces
and naming, references to EGA and the Stacks Project in the module docstrings). None of them
restates a mathlib result.

* `QuasiAffine`, `Ample`, `Projective`: quasi-affine, ample and quasi-projective morphisms,
  relative `Proj`, Segre embeddings, Chow's lemma, norms of line bundles (EGA II);
* `CommAlg`, `Dimension`, `CompletionDimension`, `Fields`: regular local rings,
  Auslander–Buchsbaum, factoriality, Zariski–Nagata purity, dimension theory of schemes,
  separability of field extensions (EGA 0_IV, EGA IV 4–7);
* `Henselization`, `StrictHenselization`, `HenselizationNoetherian`, `HenselianLifting`,
  `HenselianFiniteEtale`, `StrictLocalization`, `StrictLocalizationLift`, `EtaleStalk`,
  `EtaleStalkStructureSheaf`, `EtaleStalkPushforward`, `SpecStalkLimit`: henselian rings,
  (strict) henselization, strict localization and étale stalks (EGA IV 18, Stacks 04GE, 04HX);
* `Differentials`: the sheaf `Ω_{X/Y}` and its properties (EGA IV 16–17);
* `QuasiCoherent`, `Cohomology`: quasi-coherent sheaves, Čech and derived cohomology of
  quasi-coherent sheaves, Serre vanishing, the finiteness, formal-function, connectedness and
  base-change theorems for proper morphisms and the Grothendieck existence theorem (EGA III);
* `Formal`: adic completion, formal schemes and `Spf` (EGA I 10);
* `Etale`: étale sheaves, torsors, non-abelian `H¹`, the stack of torsors, `Pic`, and locally
  constant sheaves versus finite étale coverings (SGA 4 VII–IX);
* `Pro`: pro-objects and pro-representable functors (SGA 4 I 8);
* `Limits`, `NoetherianApproximation`, `EtaleSpreadingOut`, `WeilRestriction`: limits of schemes
  and noetherian approximation (EGA IV 8, 17.7);
* `Ramification`, `CompleteLocalQuasiFinite`: ramification and tame inertia of valuations,
  quasi-finite algebras over complete local rings;
* `Topology`: topological coverings form a Galois category; finite generation of `π₁` of compact
  semilocally simply connected spaces, van Kampen, the punctured disc and its products;
* `Semialgebraic`: semialgebraic sets, Tarski–Seidenberg, monotonicity, the Łojasiewicz
  inequality and a gradient retraction (local contractibility of real algebraic sets);
* `Analytic`: convergent power series, the Weierstrass theorems, Rückert's Nullstellensatz,
  complex analytic spaces and analytification (Grauert–Remmert); sheaves of modules on analytic
  spaces, Cousin I and Dolbeault on discs, Montel, compact Riemann surfaces and their
  meromorphic functions (Forster);
* `Cohomology` also: Euler characteristics of coherent sheaves on proper schemes over a field and
  their multiplicativity in finite étale coverings (Stacks 0BEJ);
* `Etale` also: Gabber's theorem over a noetherian henselian base and proper base change in
  degree 0 over a locally noetherian base (Stacks 0A3S, 09Z0); local acyclicity and asphericity
  (SGA 4 XV); `Limits/EtaleSections`: étale sheaves on cofiltered limits (SGA 4 VII 5.7, VIII 5.2);
* `GroupScheme`: points and local endomorphisms of group schemes, multiplication by `n` on the
  cotangent space;
* `Patching`: Harbater–Hartmann field patching and patching of Galois algebras over `k⟦t⟧`;
* `Desingularization`, `NormalizationFinite`, `Smooth`, `StrictLocalizationFunctorial`: finiteness
  of normalization (E. Noether), resolution of curves, smooth morphisms are geometrically reduced,
  functoriality of strict localizations.
* Wave 2 (2026-10-04): Oka coherence and Theorem B for `𝒪` on `Δ × ℂᵃ × (ℂ*)ᵇ`
  (`Analytic.okaCoherence`, `Analytic.polydiscProductVanishing`); EGA II 7.1.7 and EGA 0_III 10.3.1
  (`CommAlg.dominatingDVRStatement`, `CommAlg.flatResidueExtensionStatement`); EGA IV 8.8.2 and
  8.10.5 for proper morphisms (`Limits.spreadingOutStatement`, `Limits.properLimitStatement`);
  `(p, q)`-forms and `∂̄` (`Hodge`, symmetry still open); numerical types toward semistable
  reduction (`Semistable`, `Blowup`). `docs` and `Foundations/README.md` record what is proved.
-/
