/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import Mathlib.RingTheory.Flat.EquationalCriterion
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.Noetherian.Basic
import Mathlib.Algebra.Polynomial.Identities
import Mathlib.Algebra.Polynomial.Div
import Mathlib.FieldTheory.IsAlgClosed.AlgebraicClosure
import Mathlib.FieldTheory.Minpoly.Field
import Mathlib.FieldTheory.Perfect
import Mathlib.RingTheory.Unramified.Basic
import Mathlib.RingTheory.Nakayama

/-!
# Kernels of maps of flat modules modulo powers of an ideal

This file contains the commutative algebra behind cohomology and base change in degree `0` for
the structure sheaf (EGA III 7.7, 7.8; Mumford, *Abelian varieties* §5): for a map `d : C₀ → C₁`
of flat modules over a noetherian ring `A` with maximal ideal `m` (in the application, the Čech
differential of a finite affine cover of a flat scheme over `A`), a family `b` of elements of
`C₀` with `d (b i) ∈ mⁿ C₁` which is a basis of `ker (d ⊗ A/m)` is a basis of `ker (d ⊗ A/mⁿ)`.

* `Module.Flat.mem_smul_top_of_mul_mem`: in a flat module, `t x ∈ J M` implies `x ∈ (J : t) M`
  (equational criterion of flatness, Stacks 00HK).
* `CohomologyAux.SpansModulo`, `CohomologyAux.IndepModulo`: `b` generates, resp. is linearly
  independent in, `ker (d ⊗ A/J)`, stated inside `C₀` and `C₁`.
* `CohomologyAux.spansModulo_pow_and_indepModulo_pow`: passage from `m` to `mⁿ`, by induction
  along `J ⊂ J + (t)` with `m t ⊆ J` (`spansModulo_and_indepModulo_of_sup_span`).
* `CohomologyAux.exists_eval_mem_pow`, `CohomologyAux.sub_mem_pow_of_eval_mem_pow`: Newton's
  method, existence and uniqueness of approximate roots of a polynomial modulo `Iⁿ` lifting a
  simple root modulo `I` (Hensel's lemma for the pair `(R, I)` modulo `Iⁿ`), and
  `CohomologyAux.exists_compatible_seq`, the same on the equalizer of two algebra maps.
* `CohomologyAux.separable_minpoly_of_isReduced`: integral elements of a geometrically reduced
  algebra over a field have separable minimal polynomials (EGA IV 4.6.1).
* `CohomologyAux.formallyUnramified_of_forall_exists_aeval`: a finite algebra over a local ring
  generated by simple roots modulo the maximal ideal is unramified.
-/

universe u v w

open Polynomial TensorProduct

namespace Module.Flat

variable {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M] [Module.Flat R M]

/-- **Colon ideals and flat modules** (Stacks 00HK): in a flat `R`-module `M`, if `t x ∈ J M`
and every `a` with `t a ∈ J` lies in `K`, then `x ∈ K M`. -/
theorem mem_smul_top_of_mul_mem {J K : Ideal R} {t : R} (hK : ∀ a, t * a ∈ J → a ∈ K) {x : M}
    (h : t • x ∈ J • (⊤ : Submodule R M)) : x ∈ K • (⊤ : Submodule R M) := by
  classical
  rw [← Submodule.span_univ, ← Set.range_id, Submodule.mem_ideal_smul_span_iff_exists_sum] at h
  obtain ⟨c, hcJ, hc⟩ := h
  let ι := Option c.support
  let f : ι → R := fun o ↦ o.elim t fun i ↦ -c i
  let z : ι → M := fun o ↦ o.elim x fun i ↦ (i : M)
  have hrel : ∑ o, f o • z o = 0 := by
    rw [Fintype.sum_option]
    simp only [f, z, Option.elim, neg_smul, Finset.sum_neg_distrib]
    have hc' : ∑ i : c.support, c i • (i : M) = t • x := by
      rw [Finset.sum_coe_sort c.support (fun i ↦ c i • i)]
      exact hc
    rw [hc', add_neg_cancel]
  obtain ⟨κ, a, w, hz, ha⟩ := Module.Flat.isTrivialRelation_of_sum_smul_eq_zero hrel
  have hx : x = ∑ j, a none j • w j := hz none
  rw [hx]
  refine Submodule.sum_mem _ fun j _ ↦ Submodule.smul_mem_smul (hK _ ?_) trivial
  have h0 := ha j
  rw [Fintype.sum_option] at h0
  have : t * a none j = ∑ i : c.support, c i * a (some i) j := by
    simp only [f, Option.elim, neg_mul, Finset.sum_neg_distrib] at h0
    linear_combination h0
  rw [this]
  exact J.sum_mem fun i _ ↦ J.mul_mem_right _ (hcJ i)

end Module.Flat

namespace AlgebraicGeometry.CohomologyAux

section Kernel

variable {R : Type u} [CommRing R] {C₀ : Type v} {C₁ : Type w} [AddCommGroup C₀] [Module R C₀]
  [AddCommGroup C₁] [Module R C₁] (d : C₀ →ₗ[R] C₁) {ι : Type*} [Fintype ι] (b : ι → C₀)

/-- `b` generates `ker (d ⊗ R/J)` modulo `J C₀`: every `c` with `d c ∈ J C₁` is congruent to an
`R`-linear combination of the `b i` modulo `J C₀`. -/
def SpansModulo (J : Ideal R) : Prop :=
  ∀ c : C₀, d c ∈ J • (⊤ : Submodule R C₁) →
    ∃ a : ι → R, c - ∑ i, a i • b i ∈ J • (⊤ : Submodule R C₀)

/-- `b` is linearly independent modulo `J`: `∑ aᵢ bᵢ ∈ J C₀` implies `aᵢ ∈ J`. -/
def IndepModulo (J : Ideal R) : Prop :=
  ∀ a : ι → R, ∑ i, a i • b i ∈ J • (⊤ : Submodule R C₀) → ∀ i, a i ∈ J

variable {d b}

lemma smul_mem_smul_top_of_mul_mem {J K : Ideal R} {t : R} (hK : ∀ a ∈ K, a * t ∈ J) {x : C₀}
    (hx : x ∈ K • (⊤ : Submodule R C₀)) : t • x ∈ J • (⊤ : Submodule R C₀) := by
  refine Submodule.smul_induction_on hx (fun a ha y _ ↦ ?_) fun y z hy hz ↦ ?_
  · rw [smul_smul, mul_comm]
    exact Submodule.smul_mem_smul (hK a ha) trivial
  · rw [smul_add]
    exact add_mem hy hz

lemma map_mem_smul_top {J : Ideal R} {x : C₀} (hx : x ∈ J • (⊤ : Submodule R C₀)) :
    d x ∈ J • (⊤ : Submodule R C₁) := by
  have : d x ∈ (J • (⊤ : Submodule R C₀)).map d := Submodule.mem_map_of_mem hx
  rw [Submodule.map_smul''] at this
  exact Submodule.smul_mono le_rfl le_top this

variable [Module.Flat R C₀] [Module.Flat R C₁] (m : Ideal R) [m.IsMaximal]

/-- If `t ∉ J` and `m t ⊆ J` for a maximal ideal `m`, then `(J : t) = m`. -/
lemma mem_of_mul_mem {J : Ideal R} {t : R} (hmt : ∀ a ∈ m, a * t ∈ J) (htJ : t ∉ J) {a : R}
    (ha : t * a ∈ J) : a ∈ m := by
  by_contra ham
  obtain ⟨a', c, hc, hac⟩ := Ideal.IsMaximal.exists_inv ‹_› ham
  apply htJ
  have : t = t * a * a' + c * t := by linear_combination (-t) * hac
  rw [this]
  exact J.add_mem (J.mul_mem_right _ ha) (hmt c hc)

/-- **The inductive step**: from `J + (t)` to `J`, when `m t ⊆ J`. -/
theorem spansModulo_and_indepModulo_of_sup_span {J : Ideal R} {t : R}
    (hmt : ∀ a ∈ m, a * t ∈ J) (hb : ∀ i, d (b i) ∈ J • (⊤ : Submodule R C₁))
    (hs : SpansModulo d b m) (hi : IndepModulo b m)
    (hs' : SpansModulo d b (J ⊔ Ideal.span {t})) (hi' : IndepModulo b (J ⊔ Ideal.span {t})) :
    SpansModulo d b J ∧ IndepModulo b J := by
  by_cases htJ : t ∈ J
  · have : J ⊔ Ideal.span {t} = J := sup_eq_left.mpr ((Ideal.span_singleton_le_iff_mem J).mpr htJ)
    rw [this] at hs' hi'
    exact ⟨hs', hi'⟩
  have hcol := fun {a : R} (ha : t * a ∈ J) ↦ mem_of_mul_mem m hmt htJ ha
  have hle : J ≤ J ⊔ Ideal.span {t} := le_sup_left
  have hdecomp : ∀ x : C₀, x ∈ (J ⊔ Ideal.span {t}) • (⊤ : Submodule R C₀) →
      ∃ j e, j ∈ J • (⊤ : Submodule R C₀) ∧ x = j + t • e := by
    intro x hx
    rw [Submodule.sup_smul, Submodule.mem_sup] at hx
    obtain ⟨j, hj, e', he', rfl⟩ := hx
    rw [Submodule.ideal_span_singleton_smul, Submodule.mem_smul_pointwise_iff_exists] at he'
    obtain ⟨e, -, rfl⟩ := he'
    exact ⟨j, e, hj, rfl⟩
  constructor
  · intro c hc
    obtain ⟨a, ha⟩ := hs' c (Submodule.smul_mono_left hle hc)
    obtain ⟨j, e, hj, he⟩ := hdecomp _ ha
    -- `t d(e) ∈ J C₁`
    have hde : t • d e ∈ J • (⊤ : Submodule R C₁) := by
      have h1 : d (c - ∑ i, a i • b i - j) ∈ J • (⊤ : Submodule R C₁) := by
        simp only [map_sub, map_sum, map_smul]
        refine sub_mem (sub_mem hc (Submodule.sum_mem _ fun i _ ↦ ?_)) (map_mem_smul_top hj)
        exact Submodule.smul_of_tower_mem _ _ (hb i)
      rw [he, add_sub_cancel_left, map_smul] at h1
      exact h1
    obtain ⟨α, hα⟩ := hs e (Module.Flat.mem_smul_top_of_mul_mem (fun _ h ↦ hcol h) hde)
    refine ⟨fun i ↦ a i + t * α i, ?_⟩
    have : c - ∑ i, (a i + t * α i) • b i = j + t • (e - ∑ i, α i • b i) := by
      have he' : c - ∑ i, a i • b i - j = t • e := by rw [he]; abel
      simp only [add_smul, Finset.sum_add_distrib, smul_sub, Finset.smul_sum, mul_smul]
      rw [← he']
      abel
    rw [this]
    exact add_mem hj (smul_mem_smul_top_of_mul_mem hmt hα)
  · intro a ha i
    have hai : ∀ i, a i ∈ J ⊔ Ideal.span {t} := hi' a (Submodule.smul_mono_left hle ha)
    choose j hj α hα hja using fun i ↦ Submodule.mem_sup.mp (hai i)
    choose β hβ using fun i ↦ Ideal.mem_span_singleton'.mp (hα i)
    have ha' : ∀ i, a i = j i + β i * t := fun i ↦ by rw [← hja, ← hβ]
    have hsum : ∑ i, a i • b i = ∑ i, j i • b i + t • ∑ i, β i • b i := by
      simp only [ha', add_smul, Finset.sum_add_distrib, Finset.smul_sum, smul_smul, mul_comm t]
    have htβ : t • ∑ i, β i • b i ∈ J • (⊤ : Submodule R C₀) := by
      have h1 : ∑ i, j i • b i ∈ J • (⊤ : Submodule R C₀) :=
        Submodule.sum_mem _ fun i _ ↦ Submodule.smul_mem_smul (hj i) trivial
      have h2 := sub_mem ha h1
      rwa [hsum, add_sub_cancel_left] at h2
    have hβm := hi β (Module.Flat.mem_smul_top_of_mul_mem (fun _ h ↦ hcol h) htβ) i
    rw [ha']
    exact J.add_mem (hj i) (hmt _ hβm)

/-- Iterating `spansModulo_and_indepModulo_of_sup_span`: from `J + (F)` to `J` for a finite set
`F` with `m F ⊆ J`. -/
theorem spansModulo_and_indepModulo_of_sup_span_finset {J : Ideal R} (F : Finset R)
    (hF : ∀ t ∈ F, ∀ a ∈ m, a * t ∈ J) (hb : ∀ i, d (b i) ∈ J • (⊤ : Submodule R C₁))
    (hs : SpansModulo d b m) (hi : IndepModulo b m)
    (hs' : SpansModulo d b (J ⊔ Ideal.span F)) (hi' : IndepModulo b (J ⊔ Ideal.span F)) :
    SpansModulo d b J ∧ IndepModulo b J := by
  classical
  induction F using Finset.induction_on with
  | empty => simpa using And.intro hs' hi'
  | insert t F _ ih =>
    have hJ : J ≤ J ⊔ Ideal.span (F : Set R) := le_sup_left
    have e : J ⊔ Ideal.span ((insert t F : Finset R) : Set R) =
        J ⊔ Ideal.span (F : Set R) ⊔ Ideal.span {t} := by
      rw [Finset.coe_insert, Ideal.span_insert, sup_comm (Ideal.span {t}), sup_assoc]
    rw [e] at hs' hi'
    have h := spansModulo_and_indepModulo_of_sup_span m
      (fun a ha ↦ hJ (hF t (Finset.mem_insert_self t F) a ha))
      (fun i ↦ Submodule.smul_mono_left hJ (hb i)) hs hi hs' hi'
    exact ih (fun t' ht' ↦ hF t' (Finset.mem_insert_of_mem ht')) h.1 h.2

/-- **From `m` to `mⁿ⁺¹`** (EGA III 7.7, degree `0`): over a noetherian ring, if `b` is a basis of
`ker (d ⊗ R/m)` in the sense of `SpansModulo`, `IndepModulo`, and `d (b i) ∈ mⁿ⁺¹ C₁`, then `b` is
a basis of `ker (d ⊗ R/mⁿ⁺¹)`. -/
theorem spansModulo_pow_and_indepModulo_pow [IsNoetherianRing R] (hs : SpansModulo d b m)
    (hi : IndepModulo b m) {n : ℕ} (hb : ∀ i, d (b i) ∈ (m ^ (n + 1)) • (⊤ : Submodule R C₁)) :
    SpansModulo d b (m ^ (n + 1)) ∧ IndepModulo b (m ^ (n + 1)) := by
  suffices ∀ k ≤ n, SpansModulo d b (m ^ (k + 1)) ∧ IndepModulo b (m ^ (k + 1)) from this n le_rfl
  intro k
  induction k with
  | zero => intro _; simpa using And.intro hs hi
  | succ k ih =>
    intro hk
    obtain ⟨F, hF'⟩ := (IsNoetherian.noetherian (m ^ (k + 1)) : (m ^ (k + 1)).FG)
    have hF : Ideal.span (F : Set R) = m ^ (k + 1) := hF'
    have hle : m ^ (k + 1 + 1) ≤ m ^ (k + 1) := Ideal.pow_le_pow_right (Nat.le_succ _)
    have e : m ^ (k + 1 + 1) ⊔ Ideal.span (F : Set R) = m ^ (k + 1) := by
      rw [hF, sup_eq_right.mpr hle]
    have ih' := ih (Nat.le_of_succ_le hk)
    rw [← e] at ih'
    refine spansModulo_and_indepModulo_of_sup_span_finset m F (fun t ht a ha ↦ ?_)
      (fun i ↦ Submodule.smul_mono_left (Ideal.pow_le_pow_right (by omega)) (hb i)) hs hi
      ih'.1 ih'.2
    have ht' : t ∈ m ^ (k + 1) := hF ▸ Ideal.subset_span ht
    rw [pow_succ' m (k + 1)]
    exact Ideal.mul_mem_mul ha ht'

end Kernel

section Newton

variable {R : Type*} [CommRing R] (I : Ideal R) (P : R[X])

lemma mul_derivative_sub_one_mem {r r' u : R} (hr : r' - r ∈ I)
    (hu : u * P.derivative.eval r - 1 ∈ I) : u * P.derivative.eval r' - 1 ∈ I := by
  obtain ⟨c, hc⟩ := sub_dvd_eval_sub r' r P.derivative
  have : u * P.derivative.eval r' - 1 = (u * P.derivative.eval r - 1) + u * ((r' - r) * c) := by
    rw [← hc]; ring
  rw [this]
  exact I.add_mem hu (I.mul_mem_left _ (I.mul_mem_right _ hr))

lemma mul_mem_pow_succ {k : ℕ} (hk : 0 < k) {x y : R} (hx : x ∈ I ^ k) (hy : y ∈ I ^ k) :
    x * y ∈ I ^ (k + 1) := by
  have : I ^ k * I ^ k ≤ I ^ (k + 1) := by
    rw [← pow_add]; exact Ideal.pow_le_pow_right (by omega)
  exact this (Ideal.mul_mem_mul hx hy)

/-- **Newton's method** (Hensel's lemma modulo `Iⁿ⁺¹`): if `P(r) ∈ I` and `P'(r)` is invertible
modulo `I`, there is `r' ≡ r (mod I)` with `P(r') ∈ Iⁿ⁺¹`. -/
theorem exists_eval_mem_pow {r u : R} (hr : P.eval r ∈ I)
    (hu : u * P.derivative.eval r - 1 ∈ I) (n : ℕ) :
    ∃ r', r' - r ∈ I ∧ P.eval r' ∈ I ^ (n + 1) := by
  induction n with
  | zero => exact ⟨r, by simp, by simpa using hr⟩
  | succ n ih =>
    obtain ⟨r', hr', hP⟩ := ih
    have hu' := mul_derivative_sub_one_mem I P hr' hu
    refine ⟨r' + -(u * P.eval r'), ?_, ?_⟩
    · have : r' + -(u * P.eval r') - r = (r' - r) - u * P.eval r' := by ring
      rw [this]
      exact I.sub_mem hr' (I.mul_mem_left _ (Ideal.pow_le_self (Nat.succ_ne_zero n) hP))
    · obtain ⟨q, hq⟩ := P.binomExpansion r' (-(u * P.eval r'))
      rw [hq]
      have : P.eval r' + P.derivative.eval r' * -(u * P.eval r') + q * (-(u * P.eval r')) ^ 2 =
          P.eval r' * (-(u * P.derivative.eval r' - 1)) +
            (q * u ^ 2) * (P.eval r' * P.eval r') := by
        ring
      rw [this]
      refine Ideal.add_mem _ ?_ (Ideal.mul_mem_left _ _ (mul_mem_pow_succ I (by omega) hP hP))
      rw [pow_succ]
      exact Ideal.mul_mem_mul hP (I.neg_mem hu')

/-- **Uniqueness in Newton's method**: two approximate roots `s, t ≡ r (mod I)` of `P` modulo `Iⁿ`,
with `P'(r)` invertible modulo `I`, are congruent modulo `Iⁿ`. -/
theorem sub_mem_pow_of_eval_mem_pow {r s t u : R} (hs : s - r ∈ I) (ht : t - r ∈ I)
    (hu : u * P.derivative.eval r - 1 ∈ I) {n : ℕ} (hPs : P.eval s ∈ I ^ n)
    (hPt : P.eval t ∈ I ^ n) : t - s ∈ I ^ n := by
  have hu' := mul_derivative_sub_one_mem I P hs hu
  have hh : t - s ∈ I := by
    have := I.sub_mem ht hs
    rwa [sub_sub_sub_cancel_right] at this
  suffices ∀ k ≤ n, t - s ∈ I ^ k from this n le_rfl
  intro k hk
  induction k with
  | zero => simp
  | succ k ih =>
    rcases Nat.eq_zero_or_pos k with rfl | hk0
    · simpa using hh
    have ih := ih (by omega)
    obtain ⟨q, hq⟩ := P.binomExpansion s (t - s)
    rw [show s + (t - s) = t by ring] at hq
    have h1 : P.derivative.eval s * (t - s) ∈ I ^ (k + 1) := by
      have : P.derivative.eval s * (t - s) = P.eval t - P.eval s - q * (t - s) ^ 2 := by
        rw [hq]; ring
      rw [this, sq]
      exact Ideal.sub_mem _ (Ideal.sub_mem _ (Ideal.pow_le_pow_right hk hPt)
        (Ideal.pow_le_pow_right hk hPs)) (Ideal.mul_mem_left _ _ (mul_mem_pow_succ I hk0 ih ih))
    have : t - s =
        u * (P.derivative.eval s * (t - s)) - (u * P.derivative.eval s - 1) * (t - s) := by
      ring
    rw [this, pow_succ']
    exact Ideal.sub_mem _ (Ideal.mul_mem_left _ _ (pow_succ' I k ▸ h1)) (Ideal.mul_mem_mul hu' ih)

end Newton

section Equalizer

variable {R : Type*} [CommRing R] {C₀ C₁ : Type*} [CommRing C₀] [CommRing C₁] [Algebra R C₀]
  [Algebra R C₁] (α β : C₀ →ₐ[R] C₁) (m : Ideal R)

lemma mem_map_algebraMap_pow {J : Ideal R} {k : ℕ} {x : C₀}
    (hx : x ∈ J.map (algebraMap R C₀) ^ k) : α x ∈ J.map (algebraMap R C₁) ^ k := by
  have := Ideal.mem_map_of_mem (α : C₀ →+* C₁) hx
  rwa [Ideal.map_pow, Ideal.map_map, AlgHom.comp_algebraMap] at this

lemma mem_map_algebraMap {J : Ideal R} {x : C₀} (hx : x ∈ J.map (algebraMap R C₀)) :
    α x ∈ J.map (algebraMap R C₁) := by
  simpa using mem_map_algebraMap_pow α (k := 1) (by simpa using hx)

/-- **Approximate roots on an equalizer.** Let `α, β : C₀ → C₁` be `R`-algebra maps, `c ∈ C₀` with
`α c ≡ β c (mod m)`, and `P` a polynomial over `R` with `P(c) ≡ 0` and `P'(c)` invertible modulo
`m`. Then for every `n` there is `c' ≡ c (mod m)` with `P(c') ≡ 0` and `α c' ≡ β c'` modulo
`mⁿ⁺¹`. -/
theorem exists_aeval_mem_pow_and_sub_mem_pow (P : R[X]) {c u : C₀}
    (hc : aeval c P ∈ m.map (algebraMap R C₀))
    (hu : u * aeval c (derivative P) - 1 ∈ m.map (algebraMap R C₀))
    (hαβ : α c - β c ∈ m.map (algebraMap R C₁)) (n : ℕ) :
    ∃ c', c' - c ∈ m.map (algebraMap R C₀) ∧ aeval c' P ∈ m.map (algebraMap R C₀) ^ (n + 1) ∧
      α c' - β c' ∈ m.map (algebraMap R C₁) ^ (n + 1) := by
  set I₀ := m.map (algebraMap R C₀)
  set I₁ := m.map (algebraMap R C₁)
  have hev₀ : ∀ x : C₀, aeval x P = (P.map (algebraMap R C₀)).eval x := fun x ↦
    (eval_map_algebraMap P x).symm
  have hev₁ : ∀ x : C₁, aeval x P = (P.map (algebraMap R C₁)).eval x := fun x ↦
    (eval_map_algebraMap P x).symm
  have hd₀ : ∀ x : C₀, aeval x (derivative P) = (P.map (algebraMap R C₀)).derivative.eval x :=
    fun x ↦ by rw [derivative_map, eval_map_algebraMap]
  have hd₁ : ∀ x : C₁, aeval x (derivative P) = (P.map (algebraMap R C₁)).derivative.eval x :=
    fun x ↦ by rw [derivative_map, eval_map_algebraMap]
  have hαI : ∀ x ∈ I₀, α x ∈ I₁ := fun x hx ↦ mem_map_algebraMap α hx
  have hβI : ∀ x ∈ I₀, β x ∈ I₁ := fun x hx ↦ mem_map_algebraMap β hx
  have hαIn : ∀ x ∈ I₀ ^ (n + 1), α x ∈ I₁ ^ (n + 1) := fun x hx ↦ mem_map_algebraMap_pow α hx
  have hβIn : ∀ x ∈ I₀ ^ (n + 1), β x ∈ I₁ ^ (n + 1) := fun x hx ↦ mem_map_algebraMap_pow β hx
  rw [hev₀] at hc
  rw [hd₀] at hu
  obtain ⟨c', hc', hP⟩ := exists_eval_mem_pow I₀ _ hc hu n
  refine ⟨c', hc', (hev₀ c').symm ▸ hP, ?_⟩
  have hPα : (P.map (algebraMap R C₁)).eval (α c') ∈ I₁ ^ (n + 1) := by
    rw [← hev₁, aeval_algHom_apply, hev₀]; exact hαIn _ hP
  have hPβ : (P.map (algebraMap R C₁)).eval (β c') ∈ I₁ ^ (n + 1) := by
    rw [← hev₁, aeval_algHom_apply, hev₀]; exact hβIn _ hP
  have hsα : α c' - α c ∈ I₁ := by rw [← map_sub]; exact hαI _ hc'
  have hsβ : β c' - α c ∈ I₁ := by
    have : β c' - α c = β (c' - c) - (α c - β c) := by rw [map_sub]; ring
    rw [this]; exact I₁.sub_mem (hβI _ hc') hαβ
  have hu₁ : α u * (P.map (algebraMap R C₁)).derivative.eval (α c) - 1 ∈ I₁ := by
    rw [← hd₁, aeval_algHom_apply, ← map_mul, ← map_one α, ← map_sub, hd₀]
    exact hαI _ hu
  have := sub_mem_pow_of_eval_mem_pow I₁ _ hsα hsβ hu₁ hPα hPβ
  rw [← neg_sub]
  exact (I₁ ^ (n + 1)).neg_mem this

/-- A compatible system of approximate roots `cₙ` as in `exists_aeval_mem_pow_and_sub_mem_pow`:
`cₙ₊₁ ≡ cₙ (mod mⁿ⁺¹)`. -/
theorem exists_compatible_seq (P : R[X]) {c u : C₀}
    (hc : aeval c P ∈ m.map (algebraMap R C₀))
    (hu : u * aeval c (derivative P) - 1 ∈ m.map (algebraMap R C₀))
    (hαβ : α c - β c ∈ m.map (algebraMap R C₁)) :
    ∃ c' : ℕ → C₀, (∀ n, c' n - c ∈ m.map (algebraMap R C₀)) ∧
      (∀ n, α (c' n) - β (c' n) ∈ m.map (algebraMap R C₁) ^ (n + 1)) ∧
      ∀ n, c' (n + 1) - c' n ∈ m.map (algebraMap R C₀) ^ (n + 1) := by
  choose c' h₁ h₂ h₃ using exists_aeval_mem_pow_and_sub_mem_pow α β m P hc hu hαβ
  refine ⟨c', h₁, h₃, fun n ↦ ?_⟩
  have hd₀ : u * (P.map (algebraMap R C₀)).derivative.eval c - 1 ∈ m.map (algebraMap R C₀) := by
    rw [derivative_map, eval_map_algebraMap]; exact hu
  refine sub_mem_pow_of_eval_mem_pow _ _ (h₁ n) (h₁ (n + 1)) hd₀ ?_ ?_
  · rw [eval_map_algebraMap]; exact h₂ n
  · rw [eval_map_algebraMap]
    exact Ideal.pow_le_pow_right (Nat.le_succ _) (h₂ (n + 1))

end Equalizer

section Separable

variable {k D : Type*} [Field k] [CommRing D] [Algebra k D]

/-- **Integral elements of a geometrically reduced algebra are separable** (EGA IV 4.6.1): if
`k̄ ⊗_k D` is reduced, the minimal polynomial over `k` of an integral element of `D` is
separable. (Otherwise `μ = q² h` over `k̄` with `q` not a unit, and `g = q h` has `g(1 ⊗ x)² = 0`,
so `g(1 ⊗ x) = 0` with `deg g < deg μ`, contradicting the linear independence of the
`1 ⊗ xⁱ`, `i < deg μ`.) -/
theorem separable_minpoly_of_isReduced (hD : IsReduced (AlgebraicClosure k ⊗[k] D)) {x : D}
    (hx : IsIntegral k x) : (minpoly k x).Separable := by
  set K := AlgebraicClosure k
  set μ := minpoly k x
  set y : K ⊗[k] D := 1 ⊗ₜ x
  by_contra hsep
  have hμ0 : μ ≠ 0 := minpoly.ne_zero hx
  have hμ0' : μ.map (algebraMap k K) ≠ 0 :=
    (Polynomial.map_ne_zero_iff (algebraMap k K).injective).mpr hμ0
  have hsep' : ¬ Squarefree (μ.map (algebraMap k K)) := by
    rw [← PerfectField.separable_iff_squarefree, separable_map]
    exact hsep
  obtain ⟨q, ⟨h, hh⟩, hqu⟩ : ∃ q, q * q ∣ μ.map (algebraMap k K) ∧ ¬ IsUnit q := by
    simpa [Squarefree] using hsep'
  set g := q * h
  have hμg : μ.map (algebraMap k K) = q * g := by rw [hh]; ring
  have hq0 : q ≠ 0 := by rintro rfl; simp [hμg] at hμ0'
  have hg0 : g ≠ 0 := by rintro hg; simp [hμg, hg] at hμ0'
  -- `g(y) = 0`
  have hμy : aeval y (μ.map (algebraMap k K)) = 0 := by
    rw [aeval_map_algebraMap]
    change aeval (Algebra.TensorProduct.includeRight x) μ = 0
    rw [aeval_algHom_apply, minpoly.aeval, map_zero]
  have hgy : aeval y g = 0 := by
    have : aeval y g ^ 2 = aeval y (μ.map (algebraMap k K)) * aeval y h := by
      rw [← map_pow, ← map_mul, hh]; congr 1; ring
    rw [hμy, zero_mul] at this
    exact IsReduced.eq_zero _ ⟨2, this⟩
  -- `deg g < deg μ`
  have hdeg : g.natDegree < μ.natDegree := by
    have hq : 0 < q.natDegree := by
      rw [Polynomial.natDegree_pos_iff_degree_pos]
      refine lt_of_le_of_ne (Polynomial.zero_le_degree_iff.mpr hq0) fun h ↦ hqu ?_
      exact Polynomial.isUnit_iff_degree_eq_zero.mpr h.symm
    have := Polynomial.natDegree_mul hq0 hg0
    rw [← hμg, Polynomial.natDegree_map] at this
    omega
  -- linear independence of the `1 ⊗ xⁱ`
  have hli := Module.Flat.linearIndependent_one_tmul (S := K) (linearIndependent_pow (K := k) x)
  rw [Fintype.linearIndependent_iff] at hli
  have hsum : ∑ i : Fin μ.natDegree, g.coeff i • ((1 : K) ⊗ₜ[k] (x ^ (i : ℕ))) = 0 := by
    rw [← hgy, aeval_eq_sum_range' hdeg, Finset.sum_range]
    refine Finset.sum_congr rfl fun i _ ↦ ?_
    rw [Algebra.TensorProduct.tmul_pow, one_pow]
  apply hg0
  ext i
  rw [Polynomial.coeff_zero]
  by_cases hi : i < μ.natDegree
  · exact hli _ hsum ⟨i, hi⟩
  · exact Polynomial.coeff_eq_zero_of_natDegree_lt (by omega)

/-- For `x` integral and separable over `k`, `P = minpoly k x` has `P(x) = 0` and `P'(x)`
invertible, with an explicit inverse `Q(x)`. -/
theorem exists_aeval_eq_zero_and_mul_derivative_eq_one {x : D}
    (hx : (minpoly k x).Separable) :
    ∃ P Q : k[X], aeval x P = 0 ∧ aeval x Q * aeval x (derivative P) = 1 := by
  obtain ⟨a, b, hab⟩ := hx
  refine ⟨minpoly k x, b, minpoly.aeval k x, ?_⟩
  have := congrArg (aeval x) hab
  rwa [map_add, map_mul, map_mul, minpoly.aeval, mul_zero, zero_add, map_one] at this

end Separable

section Unramified

variable {R B : Type*} [CommRing R] [CommRing B] [Algebra R B]

open KaehlerDifferential in
lemma D_mem_smul_top {I : Ideal R} {x : B} (hx : x ∈ I.map (algebraMap R B)) :
    D R B x ∈ I.map (algebraMap R B) • (⊤ : Submodule B Ω[B⁄R]) := by
  induction hx using Submodule.span_induction with
  | mem y hy =>
    obtain ⟨r, -, rfl⟩ := hy
    rw [Derivation.map_algebraMap]
    exact zero_mem _
  | zero => rw [map_zero]; exact zero_mem _
  | add y z _ _ hy hz => rw [map_add]; exact add_mem hy hz
  | smul c y hy ih =>
    rw [smul_eq_mul, Derivation.leibniz]
    exact add_mem (Submodule.smul_of_tower_mem _ c ih) (Submodule.smul_mem_smul hy trivial)

/-- **An unramifiedness criterion** (EGA IV 17.4.1, special case): let `R` be local and `B` a
finite `R`-algebra such that every `y ∈ B` is a root modulo `m B` of a polynomial `P` over `R`
with `P'(y)` invertible modulo `m B`. Then `B` is formally unramified over `R`: `D(y) ∈ m Ω`
for all `y`, so `Ω_{B/R} = m Ω_{B/R}` and Nakayama applies. -/
theorem formallyUnramified_of_forall_exists_aeval [IsLocalRing R] [Module.Finite R B]
    (h : ∀ y : B, ∃ (P : R[X]) (v : B),
      aeval y P ∈ (IsLocalRing.maximalIdeal R).map (algebraMap R B) ∧
        v * aeval y (derivative P) - 1 ∈ (IsLocalRing.maximalIdeal R).map (algebraMap R B)) :
    Algebra.FormallyUnramified R B := by
  set m := IsLocalRing.maximalIdeal R
  set N : Submodule B Ω[B⁄R] := m.map (algebraMap R B) • ⊤
  have hD : ∀ y : B, KaehlerDifferential.D R B y ∈ N := by
    intro y
    obtain ⟨P, v, hP, hv⟩ := h y
    have h1 := D_mem_smul_top hP
    rw [Derivation.map_aeval] at h1
    have : KaehlerDifferential.D R B y =
        v • (aeval y (derivative P) • KaehlerDifferential.D R B y) -
          (v * aeval y (derivative P) - 1) • KaehlerDifferential.D R B y := by
      rw [smul_smul, sub_smul, one_smul, sub_sub_cancel]
    rw [this]
    exact sub_mem (Submodule.smul_of_tower_mem _ v h1) (Submodule.smul_mem_smul hv trivial)
  have hN : N = ⊤ := by
    rw [eq_top_iff, ← KaehlerDifferential.span_range_derivation, Submodule.span_le]
    rintro _ ⟨y, rfl⟩
    exact hD y
  have : Module.Finite R Ω[B⁄R] := Module.Finite.trans B _
  have hle : (⊤ : Submodule R Ω[B⁄R]) ≤ m • ⊤ := by
    intro ω _
    have hω : ω ∈ N.restrictScalars R := by rw [hN]; trivial
    rwa [Ideal.smul_restrictScalars, Submodule.restrictScalars_top] at hω
  have := Submodule.eq_bot_of_le_smul_of_le_jacobson_bot m ⊤ Module.Finite.fg_top hle
    (IsLocalRing.maximalIdeal_le_jacobson _)
  exact ⟨subsingleton_of_forall_eq 0 fun ω ↦ by
    simpa using (show ω ∈ (⊥ : Submodule R Ω[B⁄R]) from this ▸ trivial)⟩

end Unramified

end AlgebraicGeometry.CohomologyAux
