/-
Copyright (c) 2026 SGAenglishpluslean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SGAenglishpluslean contributors
-/
import SGA.Foundations.Cohomology.BaseChangeAlgebra
import Mathlib.RingTheory.Smooth.Fiber
import Mathlib.RingTheory.Filtration
import Mathlib.RingTheory.Ideal.Over
import Mathlib.RingTheory.FinitePresentation
import Mathlib.RingTheory.TensorProduct.Quotient

/-!
# The local theorem: `f_* 𝒪_X` is finite étale for geometrically reduced fibres

This is the algebraic core of EGA III 7.8.6–7.8.10 (i) in degree `0` (Stacks, the étaleness of
the Stein factorization of a proper flat morphism with geometrically reduced fibres). Let `A` be a
noetherian local ring with maximal ideal `m` and residue field `k`, and consider

* the ring `B = Γ(X, 𝒪_X)`, finite over `A`;
* the Čech rings `C₀ = ∏ᵢ Γ(Uᵢ, 𝒪_X)`, `C₁ = ∏ᵢⱼ Γ(Uᵢ ∩ Uⱼ, 𝒪_X)` of a finite affine cover, flat
  over `A`, with the restriction `σ : B → C₀` and the two restrictions `α, β : C₀ → C₁`.

`CohomologyAux.BaseChangeData` records what the geometry provides: `α σ = β σ`; the elements of
`H⁰(X_k, 𝒪) = ker (α - β ⊗ k)` are integral over `k` (properness); `C₀ ⊗ k` is geometrically
reduced (geometrically reduced fibre); compatible families of sections over the thickenings
`X ⊗ A/mⁿ⁺¹` come from `B` (theorem on formal functions, EGA III 4.1.5), and the topology on `B`
induced by `C₀` is the `m`-adic one (Artin–Rees, EGA III 4.1.7).

From this, `BaseChangeData.etale`: `B` is a finite étale `A`-algebra; also `B` is free
(`BaseChangeData.free`) and its formation commutes with passage to the closed fibre,
`B ∩ m C₀ = m B` (`BaseChangeData.mem_map_of_mem`). The proof: every element of
`H⁰(X_k, 𝒪)` is a simple root of a polynomial, so lifts by Newton's method to all thickenings
(`exists_compatible_seq`), hence to `B`; a family of `B` lifting a basis of `H⁰(X_k, 𝒪)` is then a
basis of each `H⁰(X ⊗ A/mⁿ⁺¹, 𝒪)` (`spansModulo_pow_and_indepModulo_pow`, flatness), hence of `B`
(Krull and Nakayama); finally `Ω_{B/A} = 0` since `B` is generated by simple roots modulo `m`
(`formallyUnramified_of_forall_exists_aeval`).
-/

universe u v w

open Polynomial IsLocalRing TensorProduct

namespace AlgebraicGeometry.CohomologyAux

attribute [local instance] Ideal.Quotient.field

section Local

variable {A : Type u} [CommRing A] [IsLocalRing A] [IsNoetherianRing A]
  {B : Type v} [CommRing B] [Algebra A B]
  {C₀ C₁ : Type w} [CommRing C₀] [CommRing C₁] [Algebra A C₀] [Algebra A C₁]
  (σ : B →ₐ[A] C₀) (α β : C₀ →ₐ[A] C₁)

/-- The data of the local base change theorem in degree `0` (see the module docstring): `σ` is the
restriction `Γ(X, 𝒪_X) → ∏ Γ(Uᵢ, 𝒪_X)` and `α, β` are the two restrictions to the intersections
`Uᵢ ∩ Uⱼ` of a finite affine cover of a scheme proper and flat over `Spec A`. -/
structure BaseChangeData : Prop where
  /-- Global sections agree on intersections. -/
  comp_eq : ∀ y, α (σ y) = β (σ y)
  /-- Sections of the closed fibre are integral over `k` (properness). -/
  exists_monic : ∀ c : C₀, α c - β c ∈ (maximalIdeal A).map (algebraMap A C₁) →
    ∃ P : A[X], P.Monic ∧ aeval c P ∈ (maximalIdeal A).map (algebraMap A C₀)
  /-- The closed fibre is geometrically reduced: `C₀ ⊗_A k̄` is reduced. -/
  isReduced : IsReduced (AlgebraicClosure (A ⧸ maximalIdeal A) ⊗[A] C₀)
  /-- Compatible families of sections of the thickenings come from `B` (formal functions). -/
  exists_lift : ∀ c : ℕ → C₀,
    (∀ n, α (c n) - β (c n) ∈ (maximalIdeal A).map (algebraMap A C₁) ^ (n + 1)) →
    (∀ n, c (n + 1) - c n ∈ (maximalIdeal A).map (algebraMap A C₀) ^ (n + 1)) →
    ∃ y, σ y - c 0 ∈ (maximalIdeal A).map (algebraMap A C₀)
  /-- The topology on `B` induced by `C₀` is the `m`-adic one (Artin–Rees). -/
  artinRees : ∃ N, ∀ y, σ y ∈ (maximalIdeal A).map (algebraMap A C₀) ^ N →
    y ∈ (maximalIdeal A).map (algebraMap A B)

/-- The Čech differential `α - β : C₀ → C₁`. -/
abbrev dMap (α β : C₀ →ₐ[A] C₁) : C₀ →ₗ[A] C₁ := α.toLinearMap - β.toLinearMap

omit [IsLocalRing A] [IsNoetherianRing A] in
lemma mem_smul_top_iff {M : Type*} [CommRing M] [Algebra A M] {J : Ideal A} {x : M} :
    x ∈ J • (⊤ : Submodule A M) ↔ x ∈ J.map (algebraMap A M) := by
  rw [Ideal.smul_top_eq_map]; rfl

namespace BaseChangeData

variable {σ α β} (H : BaseChangeData σ α β)

local notation "m" => maximalIdeal A
local notation "k" => A ⧸ maximalIdeal A
local notation "I₀" => Ideal.map (algebraMap A C₀) (maximalIdeal A)
local notation "I₁" => Ideal.map (algebraMap A C₁) (maximalIdeal A)

omit [IsNoetherianRing A] in
lemma mk_aeval (c : C₀) (R : A[X]) :
    Ideal.Quotient.mk I₀ (aeval c R) =
      aeval (Ideal.Quotient.mk I₀ c) (R.map (Ideal.Quotient.mk m)) := by
  have e : R.map (Ideal.Quotient.mk m) = R.map (algebraMap A k) := rfl
  rw [e, aeval_map_algebraMap]
  exact (aeval_algHom_apply (Ideal.Quotient.mkₐ A _) c R).symm

include H in
omit [IsNoetherianRing A] in
lemma isReduced_tensor_quotient :
    IsReduced (AlgebraicClosure k ⊗[k] (C₀ ⧸ I₀)) := by
  have := H.isReduced
  let e₁ := Algebra.TensorProduct.quotIdealMapEquivQuotTensor C₀ (maximalIdeal A)
  let e : AlgebraicClosure k ⊗[k] (C₀ ⧸ I₀) ≃ₐ[AlgebraicClosure k]
      AlgebraicClosure k ⊗[A] C₀ :=
    (Algebra.TensorProduct.congr AlgEquiv.refl e₁).trans
      (Algebra.TensorProduct.cancelBaseChange A k _ _ C₀)
  exact isReduced_of_injective e.toRingHom e.injective

include H in
omit [IsNoetherianRing A] in
/-- An element of `C₀` integral modulo `m` is a simple root modulo `m` of a polynomial over `A`:
the minimal polynomial over `k` is separable (geometric reducedness), lifted to `A`. -/
lemma exists_poly {c : C₀} (hc : IsIntegral k (Ideal.Quotient.mk I₀ c)) :
    ∃ P Q : A[X], aeval c P ∈ I₀ ∧ aeval c Q * aeval c (derivative P) - 1 ∈ I₀ := by
  have hsep := separable_minpoly_of_isReduced H.isReduced_tensor_quotient hc
  obtain ⟨P₀, Q₀, hP₀, hQ₀⟩ := exists_aeval_eq_zero_and_mul_derivative_eq_one hsep
  obtain ⟨P, rfl⟩ := Polynomial.map_surjective (Ideal.Quotient.mk m)
    Ideal.Quotient.mk_surjective P₀
  obtain ⟨Q, rfl⟩ := Polynomial.map_surjective (Ideal.Quotient.mk m)
    Ideal.Quotient.mk_surjective Q₀
  refine ⟨P, Q, ?_, ?_⟩
  · rw [← Ideal.Quotient.eq_zero_iff_mem, mk_aeval, hP₀]
  · rw [← Ideal.Quotient.eq_zero_iff_mem, map_sub, map_mul, mk_aeval, mk_aeval, map_one,
      ← derivative_map, hQ₀, sub_self]

omit [IsNoetherianRing A] in
lemma isIntegral_of_monic {c : C₀} {P : A[X]} (hP : P.Monic) (hc : aeval c P ∈ I₀) :
    IsIntegral k (Ideal.Quotient.mk I₀ c) := by
  refine ⟨P.map (Ideal.Quotient.mk m), hP.map _, ?_⟩
  rw [← aeval_def, ← mk_aeval, Ideal.Quotient.eq_zero_iff_mem]
  exact hc

include H in
omit [IsNoetherianRing A] in
/-- **Sections of the closed fibre lift to `B`** (EGA III 7.8.6): every `c ∈ C₀` which is a
section over the closed fibre is congruent modulo `m` to a global section. -/
theorem exists_sub_mem {c : C₀} (hc : α c - β c ∈ I₁) : ∃ y, σ y - c ∈ I₀ := by
  obtain ⟨P₁, hP₁m, hP₁⟩ := H.exists_monic c hc
  obtain ⟨P, Q, hP, hQ⟩ := H.exists_poly (isIntegral_of_monic hP₁m hP₁)
  obtain ⟨c', h₁, h₂, h₃⟩ := exists_compatible_seq α β m P hP hQ hc
  obtain ⟨y, hy⟩ := H.exists_lift c' h₂ h₃
  refine ⟨y, ?_⟩
  have := Ideal.add_mem _ hy (h₁ 0)
  rwa [sub_add_sub_cancel] at this

include H in
omit [IsNoetherianRing A] in
/-- **A basis of the sections of the closed fibre coming from `B`**: there are `b₁, …, b_r ∈ B`
whose images in `H⁰(X_k, 𝒪) ⊆ C₀ ⊗ k` form a `k`-basis (in the sense of `SpansModulo`,
`IndepModulo`). -/
theorem exists_family [Module.Finite A B] : ∃ (r : ℕ) (b : Fin r → B),
    SpansModulo (dMap α β) (fun i ↦ σ (b i)) m ∧ IndepModulo (fun i ↦ σ (b i)) m := by
  classical
  obtain ⟨s, g, hg⟩ := Module.Finite.exists_fin (R := A) (M := B)
  set π : C₀ →ₐ[A] (C₀ ⧸ I₀) := Ideal.Quotient.mkₐ A I₀
  let L : B →ₗ[A] C₀ ⧸ I₀ := (π.comp σ).toLinearMap
  let v : Fin s → C₀ ⧸ I₀ := fun j ↦ L (g j)
  obtain ⟨t, hts, hspan, hli⟩ := exists_linearIndependent k (Set.range v)
  have ht : t.Finite := (Set.finite_range v).subset hts
  let _ := ht.fintype
  let e := Fintype.equivFin t
  let w : Fin (Fintype.card t) → C₀ ⧸ I₀ := fun i ↦ (e.symm i : C₀ ⧸ I₀)
  have hrw : Set.range w = t := by
    ext x
    refine ⟨?_, fun hx ↦ ⟨e ⟨x, hx⟩, by simp [w]⟩⟩
    rintro ⟨i, rfl⟩
    exact (e.symm i).2
  have hliw : LinearIndependent k w := hli.comp _ e.symm.injective
  choose j hj using fun i ↦ hts (e.symm i).2
  have hLb : ∀ i, L (g (j i)) = w i := hj
  -- the `k`-module structure on `C₀ ⊗ k`
  have hsmul : ∀ (a : A) (x : C₀ ⧸ I₀), Ideal.Quotient.mk m a • x = a • x := fun a x ↦
    algebraMap_smul k a x
  have hL : ∀ (a : Fin (Fintype.card t) → A),
      π (∑ i, a i • σ (g (j i))) = ∑ i, Ideal.Quotient.mk m (a i) • w i := by
    intro a
    simp only [map_sum, map_smul, hsmul]
    exact Finset.sum_congr rfl fun i _ ↦ by rw [← hLb i]; rfl
  refine ⟨Fintype.card t, fun i ↦ g (j i), ?_, ?_⟩
  · intro c hc
    rw [mem_smul_top_iff] at hc
    obtain ⟨y, hy⟩ := H.exists_sub_mem (by simpa using hc)
    have h1 : L y ∈ Submodule.span k (Set.range w) := by
      rw [hrw, hspan]
      have hy' : L y ∈ Submodule.span A (Set.range v) := by
        have : L y ∈ (Submodule.span A (Set.range g)).map L :=
          Submodule.mem_map_of_mem (by rw [hg]; trivial)
        rwa [Submodule.map_span, ← Set.range_comp] at this
      exact Submodule.span_le_restrictScalars A k _ hy'
    obtain ⟨l, hl⟩ := (Submodule.mem_span_range_iff_exists_fun k).mp h1
    choose a ha using fun i ↦ Ideal.Quotient.mk_surjective (l i)
    refine ⟨a, ?_⟩
    rw [mem_smul_top_iff, ← Ideal.Quotient.eq_zero_iff_mem]
    change π (c - ∑ i, a i • σ (g (j i))) = 0
    rw [map_sub, hL]
    simp only [ha, hl]
    rw [sub_eq_zero]
    change π c = π (σ y)
    exact (Ideal.Quotient.eq.mpr hy).symm
  · intro a ha i
    rw [mem_smul_top_iff, ← Ideal.Quotient.eq_zero_iff_mem] at ha
    change π (∑ i, a i • σ (g (j i))) = 0 at ha
    rw [hL] at ha
    rw [← Ideal.Quotient.eq_zero_iff_mem]
    exact Fintype.linearIndependent_iff.mp hliw _ ha i

include H in
/-- **`B` is free, with a basis lifting a basis of the sections of the closed fibre** (EGA III
7.8.6, 7.8.7 in degree `0`). -/
theorem exists_basis [Module.Finite A B] [Module.Flat A C₀] [Module.Flat A C₁] :
    ∃ (r : ℕ) (b : Fin r → B),
    Function.Bijective (Fintype.linearCombination A b) ∧
      IndepModulo (fun i ↦ σ (b i)) m := by
  obtain ⟨r, b, hs, hi⟩ := H.exists_family
  have hd : ∀ i, dMap α β (σ (b i)) = 0 := fun i ↦ by simp [dMap, H.comp_eq]
  have hpow : ∀ n, SpansModulo (dMap α β) (fun i ↦ σ (b i)) (m ^ (n + 1)) ∧
      IndepModulo (fun i ↦ σ (b i)) (m ^ (n + 1)) := fun n ↦
    spansModulo_pow_and_indepModulo_pow m hs hi fun i ↦ by rw [hd i]; exact zero_mem _
  have hσφ : ∀ a, σ (Fintype.linearCombination A b a) = ∑ i, a i • σ (b i) := by
    intro a; simp [Fintype.linearCombination_apply, map_sum, map_smul]
  refine ⟨r, b, ⟨?_, ?_⟩, hi⟩
  · rw [← LinearMap.ker_eq_bot, eq_bot_iff]
    intro a ha
    rw [LinearMap.mem_ker] at ha
    rw [Submodule.mem_bot]
    funext i
    have hmem : ∀ n, a i ∈ m ^ n := by
      intro n
      cases n with
      | zero => simp
      | succ n =>
        exact (hpow n).2 a (by rw [← hσφ, ha, map_zero]; exact zero_mem _) i
    have h := Ideal.iInf_pow_eq_bot_of_isLocalRing m (maximalIdeal.isMaximal A).ne_top
    have : a i ∈ ⨅ n, m ^ n := Submodule.mem_iInf _ |>.mpr hmem
    rw [h] at this
    simpa using this
  · obtain ⟨N, hN⟩ := H.artinRees
    rw [← LinearMap.range_eq_top, eq_top_iff]
    refine Submodule.le_of_le_smul_of_le_jacobson_bot Module.Finite.fg_top
      (maximalIdeal_le_jacobson _) ?_
    intro y _
    obtain ⟨a, ha⟩ := (hpow N).1 (σ y) (by
      have : dMap α β (σ y) = 0 := by simp [dMap, H.comp_eq]
      rw [this]; exact zero_mem _)
    have hmem : y - Fintype.linearCombination A b a ∈ m • (⊤ : Submodule A B) := by
      rw [mem_smul_top_iff]
      apply hN
      rw [map_sub, hσφ]
      rw [mem_smul_top_iff, Ideal.map_pow] at ha
      exact Ideal.pow_le_pow_right (Nat.le_succ N) ha
    exact Submodule.mem_sup.mpr ⟨_, LinearMap.mem_range_self _ a, _, hmem, by abel⟩

include H in
/-- `B` is a free `A`-module. -/
theorem free [Module.Finite A B] [Module.Flat A C₀] [Module.Flat A C₁] : Module.Free A B := by
  obtain ⟨r, b, hb, -⟩ := H.exists_basis
  exact Module.Free.of_equiv (LinearEquiv.ofBijective _ hb)

include H in
/-- **Base change to the closed fibre** (EGA III 7.7.5 (ii) in degree `0`): `B ∩ m C₀ = m B`, i.e.
`B ⊗ k → H⁰(X_k, 𝒪)` is injective. -/
theorem mem_map_of_mem [Module.Finite A B] [Module.Flat A C₀] [Module.Flat A C₁] {y : B}
    (hy : σ y ∈ I₀) : y ∈ (maximalIdeal A).map (algebraMap A B) := by
  obtain ⟨r, b, hb, hi⟩ := H.exists_basis
  obtain ⟨a, rfl⟩ := hb.2 y
  have hσφ : σ (Fintype.linearCombination A b a) = ∑ i, a i • σ (b i) := by
    simp [Fintype.linearCombination_apply, map_sum, map_smul]
  have ha := hi a (by rw [mem_smul_top_iff, ← hσφ]; exact hy)
  rw [← mem_smul_top_iff, Fintype.linearCombination_apply]
  exact Submodule.sum_mem _ fun i _ ↦ Submodule.smul_mem_smul (ha i) trivial

include H in
/-- `B` is formally unramified over `A`. -/
theorem formallyUnramified [Module.Finite A B] [Module.Flat A C₀] [Module.Flat A C₁] :
    Algebra.FormallyUnramified A B := by
  refine formallyUnramified_of_forall_exists_aeval fun y ↦ ?_
  obtain ⟨P₁, hP₁m, hP₁⟩ := Algebra.IsIntegral.isIntegral (R := A) y
  have h₀ : aeval (σ y) P₁ = 0 := by rw [aeval_algHom_apply, aeval_def, hP₁, map_zero]
  have h₁ : aeval (σ y) P₁ ∈ I₀ := by rw [h₀]; exact zero_mem _
  obtain ⟨P, Q, hP, hQ⟩ := H.exists_poly (isIntegral_of_monic hP₁m h₁)
  refine ⟨P, aeval y Q, H.mem_map_of_mem (y := aeval y P) (by rwa [← aeval_algHom_apply]),
    H.mem_map_of_mem (y := aeval y Q * aeval y (derivative P) - 1) ?_⟩
  rwa [map_sub, map_mul, map_one, ← aeval_algHom_apply, ← aeval_algHom_apply]

include H in
/-- **The local theorem** (EGA III 7.8.10 (i), local form): `B` is a finite étale `A`-algebra. -/
theorem etale [Module.Finite A B] [Module.Flat A C₀] [Module.Flat A C₁] :
    Algebra.Etale A B := by
  have := H.free
  have := H.formallyUnramified
  have : Algebra.FinitePresentation A B :=
    Algebra.FinitePresentation.of_finiteType.mp inferInstance
  exact Algebra.Etale.of_formallyUnramified_of_flat

end BaseChangeData

end Local

end AlgebraicGeometry.CohomologyAux
