/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import Mathlib.CategoryTheory.Sites.SheafCohomology.Basic
import Mathlib.CategoryTheory.Adjunction.Additive
import Mathlib.CategoryTheory.Adjunction.Whiskering
import Mathlib.AlgebraicGeometry.Modules.Sheaf
import Mathlib.Topology.Sheaves.Abelian
import Mathlib.CategoryTheory.Abelian.GrothendieckCategory.HasExt

/-!
# Cohomology of abelian sheaves and of `𝒪_X`-modules

This file fixes the framework used for the cohomology of (quasi-coherent) sheaves on schemes
(EGA 0_III §12, EGA III §1; Stacks Project, Chapter 20; Hartshorne III.2).

## The framework

We use mathlib's derived-functor (`Ext`) definition of sheaf cohomology on a site `(C, J)`:
* `CategoryTheory.Sheaf.H F n = Extⁿ(ℤ, F)`, the cohomology of an abelian sheaf `F`, and
* `CategoryTheory.Sheaf.H' F n U = Extⁿ(ℤ_U, F)`, the cohomology of `F` over an object `U`,
  where `ℤ_U` is the free abelian sheaf generated by `U` (the sheafification of `ℤ[yoneda U]`).

For a topological space (or a scheme) `X` the site is `Opens.grothendieckTopology X`, and
`F.H' n U` is `Hⁿ(U, F)` for an open `U`, computed in the category of abelian sheaves on the whole
of `X` (it agrees with `Hⁿ(U, F|_U)` since `ℤ_U` is the extension by zero of `ℤ`; this comparison
is not needed here). Working with `H'` has two advantages: long exact sequences in the coefficient
sheaf come directly from `Ext`, and `Hⁿ(U, I) = 0` for injective `I` is immediate. Global
cohomology is `H'` over `⊤` (`CategoryTheory.Sheaf.H'.addEquivH`).

For an `𝒪_X`-module `M` we take the cohomology of its underlying abelian sheaf `M.toAbSheaf`
(the derived functors of `Γ` on `𝒪_X`-modules agree with these, Hartshorne III.2.6; here this
is the definition). A global section
`r ∈ Γ(X, 𝒪_X)` acts on `M` by the endomorphism `M.smulHom r` (`M.smulEnd r` as an `𝒪_X`-module
map), hence on `Hⁿ(U, M)`: this is the `Γ(X, 𝒪_X)`-module structure of
`SGA.Foundations.Cohomology.Modules` (for `X` over `Spec A` it gives the `A`-module structure of
EGA III 1.4).

## Main definitions and results of this file

* `CategoryTheory.Sheaf.H'.equiv₀ : F.H' 0 U ≃+ F(U)` and its naturality
  `CategoryTheory.Sheaf.H'.equiv₀_naturality`; `CategoryTheory.Sheaf.H'.map` and
  `CategoryTheory.Sheaf.H'.endRingHom : End F →+* End (Hⁿ(U, F))`.
* `CategoryTheory.Sheaf.H'.addEquivH : F.H' n T ≃+ F.H n` for a terminal object `T`.
* `AlgebraicGeometry.Scheme.Modules.toAbSheaf`, `smulHom`, `smulRingHom`, `smulEnd`.

## Overview of `SGA/Foundations/Cohomology`

Stage I:
* `Cech`: Čech complexes of presheaves for families of opens; `Godement`: Godement sheaves and
  Čech acyclicity of injective sheaves;
* `Cartan`: Cartan's criterion (Stacks Tag 01EW); `Leray`, `CechComparison`: Leray's acyclicity
  theorem (Stacks Tag 01ET), in vanishing form and as an isomorphism of abelian groups;
* `CechLocalization`, `AffineVanishing`, `AffineOpenVanishing`: exactness of Čech complexes of
  quasi-coherent modules for standard covers (Stacks Tag 01X9) and Serre's vanishing theorem
  `Hⁿ(V, F) = 0` for `n > 0`, `V` an affine open of any scheme, `F` quasi-coherent (Stacks
  Tag 01XB; EGA III 1.3.1), and the `Γ(X, 𝒪_X)`-linear comparison of Čech cohomology of
  quasi-coherent modules with cohomology (Stacks Tag 01XD; EGA III 1.4.1);
* `Modules`: cohomology of `𝒪_X`-modules as `Γ(X, 𝒪_X)`-modules;
* `Statements`: what remains, as `Prop`s.

Stage II:
* `LongExactSequence`: `M ↦ M.toAbSheaf` is exact, and the long exact cohomology sequence of a
  short exact sequence of `𝒪_X`-modules, `Γ(X, 𝒪_X)`-linearly;
* `CechVanishing`, `CohomologicalDimension`: the Čech complex of `n` opens is exact in degrees
  `≥ n` (Stacks Tag 01FM), hence `Hᵖ(X, F) = 0` for `p ≥ n` when `X` is covered by `n` affines
  with affine intersections and `F` is quasi-coherent;
* `InvertibleSheaf`: the `𝒪_X`-modules `L^{⊗n}` of a line bundle given by a cocycle, locally free
  of rank one;
* `CechMonomial`, `ProjectiveSpace`, `ProjectiveSpaceTwist`: the cohomology of `𝒪(d)` on
  `ℙʳ_A = Proj A[x₀, …, x_r]` by Čech cochains and Laurent monomials (Stacks Tag 01XT):
  `Γ(ℙʳ_A, 𝒪) = A`, `Γ(ℙʳ_A, 𝒪(n)) = A[x]ₙ`, and `Hᵖ(ℙʳ_A, 𝒪(d)) = 0` except for `p = 0`, and
  `p = r` with `d ≤ -r - 1`.

Stage III:
* `Helpers`, `CohomologyLemmas`: restriction lemmas; additivity and biproducts for `Hⁿ`;
* `Twist`: the twists `M ⊗ L^{⊗n}` of arbitrary modules, `(M(a))(b) ≅ M(a + b)`, `M(0) ≅ M`, and
  twisting as an (exact, additive) equivalence of categories; `HomTwist`:
  `Hom(L^{⊗-n}, F) ≅ Γ(F ⊗ L^{⊗n})`;
* `QuasiCoherentLocal`, `QuasiCoherentKernel`: sections of quasi-coherent modules over basic opens
  (EGA I 1.4.1), epimorphisms detected on affine covers, quasi-coherence of kernels of
  epimorphisms between quasi-coherent modules;
* `Extension`: extension of sections `xᵢⁿ s` (EGA I 9.3.1) and global generation of `F(n)`;
* `Serre`: Serre's vanishing theorem `Hᵖ(ℙʳ_A, F(n)) = 0` for `p > 0`, `n ≫ 0` (EGA III 2.2.1);
* `CechFinite`, `SerreFiniteness`: finiteness of `Hᵖ(ℙʳ_A, 𝒪(d))` and Serre's finiteness theorem
  on `ℙʳ_A` over a noetherian ring;
* `Coherent`: sections of coherent modules over affines are finitely generated, the class of
  Serre's theorems is the class of coherent modules, coherence of kernels, finiteness over `A`;
* `Pushforward`: direct images along affine morphisms are quasi-coherent and have the same
  cohomology (EGA III 1.3.3); `ProjectiveMorphism`, `HProjective`: finiteness of cohomology of
  coherent modules for closed subschemes of `ℙʳ_A` and for H-projective morphisms over an affine
  noetherian base (`AlgebraicGeometry.properFiniteness_of_isHProjective`);
* `QuasiCoherentAbelian`: kernels, cokernels and images of quasi-coherent (coherent) modules,
  and `CohomologyAux.FiniteCohomology` with its "two out of three" property;
* `PushforwardLeray`, `LerayTransfer`: Leray's theorem for direct images with acyclic inverse
  images, and transfer of finiteness of cohomology along direct images;
* `CechTransport`, `TwistBaseChange`, `RelativeSerre`: restriction of twists to open
  subschemes, and relative Serre vanishing on `ℙ(σ; S)` over a locally noetherian `S`;
* `TwistProjection`: the projection formula for twists, coherence of twists, multiplication by
  sections of `L^{⊗m}`;
* `ClosedImmersionSections`: `Γ(i^* M, i⁻¹ U) = Γ(M, U) / I(U) Γ(M, U)` for closed immersions
  (EGA I 4.1.2);
* `PushforwardProjective`: coherence of direct images along H-projective morphisms;
* `Devissage`: the dévissage of EGA III 3.1.2 (noetherian induction on the support, filtration by
  powers of the ideal of an integral closed subscheme);
* `ProperFiniteness`: `AlgebraicGeometry.properFinitenessStatement`, the finiteness theorem for
  proper morphisms (EGA III 3.2.1), by dévissage and Chow's lemma.

Stage III, formal functions and connectedness:
* `BaseChangeSections`: sections of pullbacks along base changes by `Spec A → Spec A[t]` and
  affine morphisms (`Γ(g^* M, g⁻¹ V) ≅ Γ(M, V)[t]`); `QuasiCoherentBiproduct`: finite biproducts
  of quasi-coherent modules;
* `IdealPowers`: the subsheaves `Iⁿ M ⊆ M` for an ideal `I` of the base ring, their sections over
  affines, and `0 → Iⁿ⁺¹ M → M → M / Iⁿ⁺¹ M → 0`;
* `ReesSheaf`, `ReesMaps`, `ReesCohomology`: the Rees module `⊕ Iⁿ M tⁿ` on `X ×_A B`, `B` the Rees
  algebra (EGA III 3.3.1), its sections, the projections to the `Iⁿ M`, its coherence, and the fact
  that cohomology classes have bounded support in `n`;
* `ReesBound`: the algebraic bound for finite modules over the Rees algebra; `LerayNaturality`:
  naturality of Leray's comparison for direct images;
* `ArtinRees`: Artin–Rees statements for `Hᵖ(X, Iⁿ M)` (EGA III 4.1.5, proof), from the
  finiteness of `⊕ₙ Hᵖ(X, Iⁿ M)` over the Rees algebra;
* `FormalFunctions`: `AlgebraicGeometry.formalFunctionsStatement` (EGA III 4.1.5);
* `SeparatingSections`: idempotents of `Γ(X, 𝒪_X / Iⁿ⁺¹)` lift to global functions;
* `ZariskiConnectedness`: `AlgebraicGeometry.zariskiConnectednessStatement` (EGA III 4.3.1);
* `SteinFactorization`: `AlgebraicGeometry.steinFactorizationStatement` (EGA III 4.3.3), with
  `Y'` the relative normalization of `Y` in `X`; finiteness of `Γ(f⁻¹ U, F)` for proper `f` and
  `U` affine (EGA III 3.2.1 in degree `0`);
* `FlatBaseChange`: flat base change for `f_* 𝒪_X` (EGA III 1.4.15 in degree `0`), so that
  `𝒪_Y ≅ f_* 𝒪_X` is stable under flat base change;
* `TrivialIdempotents`, `GeometricConnectedness`: the fibres of a proper `f` with
  `𝒪_Y ≅ f_* 𝒪_X` over a locally noetherian base are geometrically connected
  (`CohomologyAux.geometricallyConnected_of_isIso_app`; EGA III 4.3.4);
* `Thickening`: towards Grothendieck's existence theorem, the ideal of the thickening
  `X_n = X ×_A A / I^{n+1}` and `ι_* ι^* M ≅ M / I^{n+1} M` for `ι : X_n ⟶ X`.

Stage III, Grothendieck's existence theorem:
* `ClosedFibre`: over an `I`-adically complete noetherian base,
  `Hᵖ(X, M) = lim Hᵖ(X, M / I^{n+1} M)` (EGA III 4.1.7), idempotents and clopen subsets lift from
  `f⁻¹ V(I)`, and the closed fibre of a connected proper scheme over a complete local ring is
  connected (the `π₀` part of SGA 1 IX.1.10, X.2.1: `AlgebraicGeometry.connectedSpace_closedFibre`,
  `AlgebraicGeometry.existsUnique_isClopen_preimage_closedFibre`);
* `SheafHomCoherent`: `ℋom(M, N)` over affine opens and its coherence for `M`, `N` coherent
  (`CohomologyAux.isCoherent_sheafHom`; EGA I 9.1.1);
* `ArtinReesHom`: Artin–Rees for `Hom(M, N)` and `Hom(M, N / Jⁿ N)`;
* `ExistenceFullyFaithful`: the full faithfulness in Grothendieck's existence theorem
  (EGA III 5.1.4), `AlgebraicGeometry.grothendieckExistence_fullyFaithful`, with
  `Hom(F|_{X_n}, G|_{X_n}) ≅ Hom(F, G / I^{n+1} G)` (`CohomologyAux.homPullbackThickeningEquiv`).

## Roadmap

The `Prop`s are in `SGA.Foundations.Cohomology.Statements`. Done: Serre's theorems on projective
space (EGA III 2.2.1; Hartshorne III.5.2), `AlgebraicGeometry.ProperFinitenessStatement`
(EGA III 3.2.1; Stacks Tag 02O5), `AlgebraicGeometry.FormalFunctionsStatement` (EGA III 4.1.5;
Stacks Tag 02OC), `AlgebraicGeometry.ZariskiConnectednessStatement` and
`AlgebraicGeometry.SteinFactorizationStatement` (EGA III 4.3.1, 4.3.3; Stacks Tag 03H0), proved as
`AlgebraicGeometry.properFinitenessStatement`, `formalFunctionsStatement`,
`zariskiConnectednessStatement` and `steinFactorizationStatement`; also the geometric form of
Zariski's theorem (EGA III 4.3.4), `CohomologyAux.geometricallyConnected_of_isIso_app`, and the
fully faithful half of `AlgebraicGeometry.GrothendieckExistenceStatement` (EGA III 5.1.4),
`AlgebraicGeometry.grothendieckExistence_fullyFaithful`. Remaining: the essential surjectivity in
Grothendieck's existence theorem (Stacks Tag 088C).
-/

universe w v u

open CategoryTheory Limits Opposite Abelian TopologicalSpace

namespace CategoryTheory

variable {C : Type u} [Category.{v} C] {J : GrothendieckTopology C}
  [HasSheafify J AddCommGrpCat.{v}]

namespace Sheaf

/-- Morphisms from the free abelian presheaf on `yoneda.obj U` are sections over `U`. -/
noncomputable def freeYonedaHomAddEquiv (P : Cᵒᵖ ⥤ AddCommGrpCat.{v}) (U : C) :
    (yoneda.obj U ⋙ AddCommGrpCat.free ⟶ P) ≃+ P.obj (op U) :=
  AddEquiv.mk' (((AddCommGrpCat.adj.whiskerRight Cᵒᵖ).homEquiv _ _).trans yonedaEquiv)
    fun _ _ ↦ rfl

lemma freeYonedaHomAddEquiv_apply (P : Cᵒᵖ ⥤ AddCommGrpCat.{v}) (U : C)
    (φ : yoneda.obj U ⋙ AddCommGrpCat.free ⟶ P) :
    freeYonedaHomAddEquiv P U φ = φ.app (op U) (FreeAbelianGroup.of (𝟙 U)) :=
  rfl

/-- Morphisms from the free abelian sheaf `ℤ_U` generated by `U` are sections over `U`. -/
noncomputable def freeYonedaSheafHomAddEquiv (F : Sheaf J AddCommGrpCat.{v}) (U : C) :
    ((presheafToSheaf J _).obj (yoneda.obj U ⋙ AddCommGrpCat.free) ⟶ F) ≃+ F.obj.obj (op U) :=
  ((sheafificationAdjunction J AddCommGrpCat.{v}).homAddEquiv _ _).trans
    (freeYonedaHomAddEquiv F.obj U)

lemma freeYonedaSheafHomAddEquiv_comp {F G : Sheaf J AddCommGrpCat.{v}} (U : C)
    (φ : (presheafToSheaf J _).obj (yoneda.obj U ⋙ AddCommGrpCat.free) ⟶ F) (f : F ⟶ G) :
    freeYonedaSheafHomAddEquiv G U (φ ≫ f) =
      f.hom.app (op U) (freeYonedaSheafHomAddEquiv F U φ) := by
  simp only [freeYonedaSheafHomAddEquiv, AddEquiv.trans_apply, Adjunction.homAddEquiv_apply,
    freeYonedaHomAddEquiv_apply, Adjunction.homEquiv_naturality_right]
  rfl

variable [HasExt.{w} (Sheaf J AddCommGrpCat.{v})]

/-- `H⁰(U, F) ≅ F(U)`: degree-zero cohomology over `U` is the group of sections over `U`. -/
noncomputable def H'.equiv₀ (F : Sheaf J AddCommGrpCat.{v}) (U : C) :
    F.H' 0 U ≃+ F.obj.obj (op U) :=
  Ext.addEquiv₀.trans (freeYonedaSheafHomAddEquiv F U)

/-- The map `Hⁿ(U, F) → Hⁿ(U, G)` induced by a morphism of sheaves. -/
noncomputable def H'.map {F G : Sheaf J AddCommGrpCat.{v}} (f : F ⟶ G) (n : ℕ) (U : C) :
    F.H' n U ⟶ G.H' n U :=
  ((cohomologyPresheafFunctor J n).map f).app (op U)

lemma H'.map_apply {F G : Sheaf J AddCommGrpCat.{v}} (f : F ⟶ G) {n : ℕ} {U : C}
    (x : F.H' n U) : H'.map f n U x = x.comp (Ext.mk₀ f) (add_zero n) :=
  rfl

@[simp]
lemma H'.map_id_apply {F : Sheaf J AddCommGrpCat.{v}} {n : ℕ} {U : C} (x : F.H' n U) :
    H'.map (𝟙 F) n U x = x :=
  Ext.comp_mk₀_id (X := (presheafToSheaf J _).obj (yoneda.obj U ⋙ AddCommGrpCat.free)) x

lemma H'.map_comp_apply {F G K : Sheaf J AddCommGrpCat.{v}} (f : F ⟶ G) (g : G ⟶ K) {n : ℕ}
    {U : C} (x : F.H' n U) : H'.map (f ≫ g) n U x = H'.map g n U (H'.map f n U x) := by
  simp only [H'.map_apply, ← Ext.mk₀_comp_mk₀]
  exact (Ext.comp_assoc_of_third_deg_zero _ _ _ _).symm

@[simp]
lemma H'.map_add_apply {F G : Sheaf J AddCommGrpCat.{v}} (f g : F ⟶ G) {n : ℕ} {U : C}
    (x : F.H' n U) : H'.map (f + g) n U x = H'.map f n U x + H'.map g n U x := by
  simp only [H'.map_apply, Ext.mk₀_add]
  exact Ext.comp_add (X := (presheafToSheaf J _).obj (yoneda.obj U ⋙ AddCommGrpCat.free)) x _ _ _

@[simp]
lemma H'.map_zero_apply {F G : Sheaf J AddCommGrpCat.{v}} {n : ℕ} {U : C} (x : F.H' n U) :
    H'.map (0 : F ⟶ G) n U x = 0 := by
  simp only [H'.map_apply, Ext.mk₀_zero]
  exact Ext.comp_zero (X := (presheafToSheaf J _).obj (yoneda.obj U ⋙ AddCommGrpCat.free)) x _ _ _
    _

lemma H'.equiv₀_naturality {F G : Sheaf J AddCommGrpCat.{v}} (f : F ⟶ G) {U : C}
    (x : F.H' 0 U) : H'.equiv₀ G U (H'.map f 0 U x) = f.hom.app (op U) (H'.equiv₀ F U x) := by
  have : Ext.addEquiv₀ (x.comp (Ext.mk₀ f) (add_zero 0)) = Ext.addEquiv₀ x ≫ f := by
    delta Ext.addEquiv₀
    apply (Ext.mk₀_bijective _ G).injective
    simp only [AddEquiv.coe_mk, Ext.mk₀_homEquiv₀_apply, ← Ext.mk₀_comp_mk₀]
    exact congrArg (fun y ↦ Ext.comp y (Ext.mk₀ f) (add_zero 0))
      (Ext.mk₀_homEquiv₀_apply (X := (presheafToSheaf J _).obj (yoneda.obj U ⋙ AddCommGrpCat.free))
        (Y := F) x).symm
  change freeYonedaSheafHomAddEquiv G U (Ext.addEquiv₀ (x.comp (Ext.mk₀ f) (add_zero 0))) =
    f.hom.app (op U) (freeYonedaSheafHomAddEquiv F U (Ext.addEquiv₀ x))
  rw [this]
  exact freeYonedaSheafHomAddEquiv_comp U _ f

lemma H'.equiv₀_symm_naturality {F G : Sheaf J AddCommGrpCat.{v}} (f : F ⟶ G) {U : C}
    (s : F.obj.obj (op U)) :
    H'.map f 0 U ((H'.equiv₀ F U).symm s) = (H'.equiv₀ G U).symm (f.hom.app (op U) s) := by
  apply (H'.equiv₀ G U).injective
  rw [H'.equiv₀_naturality, AddEquiv.apply_symm_apply, AddEquiv.apply_symm_apply]

/-- If `f : F ⟶ G` is surjective on sections over `U`, it is surjective on `H⁰(U, -)`. -/
lemma H'.map_zero_surjective {F G : Sheaf J AddCommGrpCat.{v}} (f : F ⟶ G) {U : C}
    (hf : Function.Surjective (f.hom.app (op U))) : Function.Surjective (H'.map f 0 U) := by
  intro y
  obtain ⟨s, hs⟩ := hf (H'.equiv₀ G U y)
  refine ⟨(H'.equiv₀ F U).symm s, ?_⟩
  rw [H'.equiv₀_symm_naturality, hs, AddEquiv.symm_apply_apply]

/-- Cohomology over any object with coefficients in an injective sheaf vanishes in positive
degrees. -/
instance H'.subsingleton_of_injective (I : Sheaf J AddCommGrpCat.{v}) [Injective I] {n : ℕ}
    (U : C) : Subsingleton (I.H' (n + 1) U) :=
  subsingleton_of_forall_eq 0 fun x ↦ Ext.eq_zero_of_injective x

/-- Endomorphisms of an abelian sheaf act on its cohomology over `U`: the ring homomorphism
`End F → End (Hⁿ(U, F))`. (In `End F`, `f * g = g ≫ f`.) -/
noncomputable def H'.endRingHom (F : Sheaf J AddCommGrpCat.{v}) (n : ℕ) (U : C) :
    End F →+* AddMonoid.End (F.H' n U) where
  toFun f := (H'.map f n U).hom
  map_one' := AddMonoidHom.ext fun x ↦ H'.map_id_apply x
  map_mul' f g := AddMonoidHom.ext fun x ↦ H'.map_comp_apply g f x
  map_zero' := AddMonoidHom.ext fun x ↦ H'.map_zero_apply x
  map_add' f g := AddMonoidHom.ext fun x ↦ H'.map_add_apply f g x

omit [HasSheafify J AddCommGrpCat.{v}] in
lemma ext_mk₀_hom_comp_mk₀_inv_comp {D : Type*} [Category* D]
    [Abelian D] [HasExt.{w} D] {X Y Z : D} (e : X ≅ Y) {n : ℕ} (x : Ext X Z n) :
    (Ext.mk₀ e.hom).comp ((Ext.mk₀ e.inv).comp x (zero_add n)) (zero_add n) = x := by
  rw [Ext.mk₀_comp_mk₀_assoc, e.hom_inv_id, Ext.mk₀_id_comp]

section Terminal

variable {T : C} (hT : IsTerminal T)

/-- For a terminal object `T`, the free abelian presheaf on `yoneda.obj T` is the constant
presheaf `ℤ`. -/
noncomputable def freeYonedaTerminalIso :
    yoneda.obj T ⋙ AddCommGrpCat.free ≅ (Functor.const Cᵒᵖ).obj (AddCommGrpCat.of (ULift ℤ)) :=
  NatIso.ofComponents
    (fun V ↦ (letI : Unique (V.unop ⟶ T) := ⟨⟨hT.from _⟩, fun _ ↦ hT.hom_ext _ _⟩
      (FreeAbelianGroup.uniqueEquiv (V.unop ⟶ T)).trans AddEquiv.ulift.symm).toAddCommGrpIso)
    fun _ ↦ AddCommGrpCat.hom_ext (FreeAbelianGroup.lift_ext _ _ fun _ ↦ rfl)

/-- For a terminal object `T`, `ℤ_T` is the constant sheaf `ℤ`. -/
noncomputable def freeYonedaSheafTerminalIso :
    (presheafToSheaf J _).obj (yoneda.obj T ⋙ AddCommGrpCat.free) ≅
      (constantSheaf J AddCommGrpCat.{v}).obj (AddCommGrpCat.of (ULift ℤ)) :=
  (presheafToSheaf J _).mapIso (freeYonedaTerminalIso hT)

/-- For a terminal object `T`, cohomology over `T` is global cohomology:
`Hⁿ(T, F) = Hⁿ(F)`. -/
noncomputable def H'.addEquivH (F : Sheaf J AddCommGrpCat.{v}) (n : ℕ) : F.H' n T ≃+ F.H n where
  toFun x := (Ext.mk₀ (freeYonedaSheafTerminalIso hT).inv).comp x (zero_add n)
  invFun y := (Ext.mk₀ (freeYonedaSheafTerminalIso hT).hom).comp y (zero_add n)
  left_inv x := ext_mk₀_hom_comp_mk₀_inv_comp (freeYonedaSheafTerminalIso hT) x
  right_inv y := ext_mk₀_hom_comp_mk₀_inv_comp (freeYonedaSheafTerminalIso hT).symm y
  map_add' x y := Ext.comp_add _ x y _

/-- `H'.addEquivH` is natural in the sheaf. -/
lemma H'.addEquivH_naturality {F G : Sheaf J AddCommGrpCat.{v}} (f : F ⟶ G) {n : ℕ}
    (x : F.H' n T) : H'.addEquivH hT G n (H'.map f n T x) = H.map f n (H'.addEquivH hT F n x) :=
  (Ext.comp_assoc _ x _ (zero_add n) (add_zero n) (by lia)).symm

end Terminal

end Sheaf

end CategoryTheory


namespace AlgebraicGeometry.Scheme.Modules

open CategoryTheory.Sheaf

variable {X : Scheme.{u}}

/-- The underlying abelian sheaf of an `𝒪_X`-module. -/
noncomputable abbrev toAbSheaf (M : X.Modules) :
    Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u} :=
  (SheafOfModules.toSheaf X.ringCatSheaf).obj M

/-- The morphism of underlying abelian sheaves of a morphism of `𝒪_X`-modules. -/
noncomputable abbrev Hom.toAbSheaf {M N : X.Modules} (φ : M ⟶ N) : M.toAbSheaf ⟶ N.toAbSheaf :=
  (SheafOfModules.toSheaf X.ringCatSheaf).map φ

/-- Multiplication by a global section `r` of `𝒪_X`, as an endomorphism of the underlying abelian
sheaf of an `𝒪_X`-module. -/
noncomputable def smulHom (M : X.Modules) (r : Γ(X, ⊤)) : M.toAbSheaf ⟶ M.toAbSheaf :=
  ObjectProperty.homMk
    { app V := AddCommGrpCat.ofHom (show Γ(M, V.unop) →+ Γ(M, V.unop) from
        DistribSMul.toAddMonoidHom _ (X.presheaf.map (homOfLE (le_top : V.unop ≤ ⊤)).op r))
      naturality V W f := AddCommGrpCat.ext fun (s : Γ(M, V.unop)) ↦ by
        change (X.presheaf.map (homOfLE (le_top : W.unop ≤ ⊤)).op r) •
            M.presheaf.map f.unop.op s =
          M.presheaf.map f.unop.op ((X.presheaf.map (homOfLE (le_top : V.unop ≤ ⊤)).op r) • s)
        rw [map_smul, ← ConcreteCategory.comp_apply, ← X.presheaf.map_comp]
        rfl }

lemma smulHom_app_apply (M : X.Modules) (r : Γ(X, ⊤)) {V : X.Opens} (s : Γ(M, V)) :
    (M.smulHom r).hom.app (op V) s = X.presheaf.map (homOfLE (le_top : V ≤ ⊤)).op r • s :=
  rfl

lemma toAbSheaf_hom_ext {M N : X.Modules} {f g : M.toAbSheaf ⟶ N.toAbSheaf}
    (h : ∀ (V : X.Opens) (s : Γ(M, V)), f.hom.app (op V) s = g.hom.app (op V) s) : f = g :=
  CategoryTheory.Sheaf.hom_ext (NatTrans.ext (funext fun V ↦ AddCommGrpCat.ext fun s ↦ h V.unop s))

@[simp]
lemma smulHom_one (M : X.Modules) : M.smulHom 1 = 𝟙 _ :=
  toAbSheaf_hom_ext fun V s ↦ by simp [smulHom_app_apply]; rfl

lemma smulHom_mul (M : X.Modules) (r s : Γ(X, ⊤)) :
    M.smulHom (r * s) = M.smulHom s ≫ M.smulHom r :=
  toAbSheaf_hom_ext fun V t ↦ by simp [smulHom_app_apply, mul_smul]; rfl

lemma smulHom_add (M : X.Modules) (r s : Γ(X, ⊤)) :
    M.smulHom (r + s) = M.smulHom r + M.smulHom s :=
  toAbSheaf_hom_ext fun V t ↦ by simp [smulHom_app_apply, add_smul]; rfl

@[simp]
lemma smulHom_zero (M : X.Modules) : M.smulHom 0 = 0 :=
  toAbSheaf_hom_ext fun V t ↦ by simp [smulHom_app_apply]; rfl

/-- Morphisms of `𝒪_X`-modules commute with multiplication by global sections. -/
@[reassoc]
lemma Hom.toAbSheaf_smulHom {M N : X.Modules} (φ : M ⟶ N) (r : Γ(X, ⊤)) :
    Hom.toAbSheaf φ ≫ N.smulHom r = M.smulHom r ≫ Hom.toAbSheaf φ :=
  toAbSheaf_hom_ext fun V t ↦ by
    change X.presheaf.map (homOfLE (le_top : V ≤ ⊤)).op r • φ.app V t =
      φ.app V (X.presheaf.map (homOfLE (le_top : V ≤ ⊤)).op r • t)
    rw [Hom.app_smul]

/-- The action of `Γ(X, 𝒪_X)` on the underlying abelian sheaf of an `𝒪_X`-module. -/
noncomputable def smulRingHom (M : X.Modules) : Γ(X, ⊤) →+* End M.toAbSheaf where
  toFun := M.smulHom
  map_one' := M.smulHom_one
  map_mul' := M.smulHom_mul
  map_zero' := M.smulHom_zero
  map_add' := M.smulHom_add

/-- Multiplication by a global section `r` of `𝒪_X`, as an endomorphism of `𝒪_X`-modules. -/
noncomputable def smulEnd (M : X.Modules) (r : Γ(X, ⊤)) : M ⟶ M :=
  ⟨PresheafOfModules.homMk (M.smulHom r).hom fun V s m ↦ by
    let r' : Γ(X, V.unop) := X.presheaf.map (homOfLE (le_top : V.unop ≤ ⊤)).op r
    let s' : Γ(X, V.unop) := s
    let m' : Γ(M, V.unop) := m
    change r' • s' • m' = s' • r' • m'
    rw [smul_smul, smul_smul, mul_comm]⟩

lemma toAbSheaf_smulEnd (M : X.Modules) (r : Γ(X, ⊤)) :
    Hom.toAbSheaf (M.smulEnd r) = M.smulHom r := rfl

end AlgebraicGeometry.Scheme.Modules
