/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.Foundations.Cohomology.CechComparison
import SGA.Foundations.Cohomology.LongExactSequence
import Mathlib.Algebra.Homology.DerivedCategory.Ext.Map
import Mathlib.Topology.Sheaves.Functors

/-!
# Pulling back cohomology classes, and Leray's theorem

Let `f : X ⟶ Y` be a continuous map, `F` an abelian sheaf on `Y`, `G` an abelian sheaf on `X` and
`g : f⁻¹ F ⟶ G`. For opens `W ⊆ Y` and `W' ⊆ f⁻¹(W)` there is a canonical map
`Hᵖ(W, F) → Hᵖ(W', G)` (`TopCat.Sheaf.cohomologyPullbackMap`): apply the exact functor `f⁻¹` to
`Extᵖ(ℤ_W, F)`, then compose with `ℤ_{W'} → f⁻¹ ℤ_W` and with `g` (EGA 0_III 12.1.3.1; Godement,
*Théorie des faisceaux*, II.4.17). In degree `0` it is `F(W) → G(f⁻¹ W) → G(W')`, through the
adjoint `F ⟶ f_* G` of `g` (`H'.equiv₀_cohomologyPullbackMap`); it is natural in `(F, G, g)`
(`cohomologyPullbackMap_naturality`) and compatible with connecting maps
(`cohomologyPullbackMap_H'δ`).

The main result is that these maps are computed by Čech cochains: for a finite family of opens
`U` of `Y` such that `F` is Leray-acyclic for `U` and `G` for `f⁻¹ U`, Leray's isomorphisms
`Ȟᵖ(U, F) ≅ Hᵖ(⋃ Uᵢ, F)` and `Ȟᵖ(f⁻¹ U, G) ≅ Hᵖ(⋃ f⁻¹ Uᵢ, G)` (`TopCat.Sheaf.cechHomologyIso`)
identify `cohomologyPullbackMap g` with the map of Čech complexes `c ↦ (g♭(c_x))_x`
(`TopCat.Sheaf.cechHomologyIso_cohomologyPullbackMap`). The proof is by dimension shifting, as for
the naturality of Leray's isomorphisms in `SGA.Foundations.Cohomology.CechComparison`.

This is how the comparison maps of GAGA, `Hᵖ(X, F) → Hᵖ(X^an, F^an)`, are computed (SGA 1 XII.4;
Serre, GAGA, no. 12).

## Main definitions and results

* `TopCat.Sheaf.freeYonedaPullback`: the morphism `ℤ_{W'} → f⁻¹ ℤ_W`.
* `TopCat.Sheaf.cohomologyPullbackMap`: the map `Hᵖ(W, F) → Hᵖ(W', G)`, with
  `cohomologyPullbackMap_naturality`, `cohomologyPullbackMap_H'δ` and its degree-`0` description
  `H'_equiv₀_cohomologyPullbackMap`.
* `TopCat.Sheaf.globalCohomologyPullbackMap`: the same map on global cohomology `Extᵖ(ℤ, -)`
  (through `ℤ_X → f⁻¹ ℤ_Y`, `constZToPullback`), with `addEquivH_cohomologyPullbackMap`,
  `globalCohomologyPullbackMap_naturality`, `globalCohomologyPullbackMap_comp_extClass`.
* `TopCat.Presheaf.cechPullbackCochainMap`, `TopCat.Presheaf.cechPullbackComplexMap`: the map of
  Čech complexes `Č(U, P) → Č(f⁻¹ U, Q)` induced by `P ⟶ f_* Q`.
* `TopCat.Sheaf.cechHomologyIso_cohomologyPullbackMap`: compatibility with Leray's isomorphisms.
* `TopCat.Sheaf.bijective_globalCohomologyPullbackMap_iff`: for a finite open cover, the map on
  global cohomology is bijective iff the map of Čech cohomology is.
-/

universe u

open CategoryTheory Limits TopologicalSpace Opposite Abelian TopCat.Presheaf

namespace TopCat.Sheaf

variable {X Y : TopCat.{u}} (f : X ⟶ Y)

/-! ### The inverse image functor on abelian sheaves is exact -/

section Exact

/-- The inverse image `f⁻¹` of abelian sheaves (mathlib's `TopCat.Sheaf.pullback`, with source and
target written as `CategoryTheory.Sheaf`, so that the instances of abelian sheaves apply). -/
noncomputable abbrev abPullback :
    CategoryTheory.Sheaf (Opens.grothendieckTopology Y) AddCommGrpCat.{u} ⥤
      CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u} :=
  TopCat.Sheaf.pullback AddCommGrpCat.{u} f

/-- The direct image `f_*` of abelian sheaves. -/
noncomputable abbrev abPushforward :
    CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u} ⥤
      CategoryTheory.Sheaf (Opens.grothendieckTopology Y) AddCommGrpCat.{u} :=
  TopCat.Sheaf.pushforward AddCommGrpCat.{u} f

/-- The adjunction `f⁻¹ ⊣ f_*` for abelian sheaves. -/
noncomputable abbrev abAdjunction : abPullback f ⊣ abPushforward f :=
  TopCat.Sheaf.pullbackPushforwardAdjunction AddCommGrpCat.{u} f

instance : PreservesFiniteLimits (abPullback f) :=
  Functor.sheafPullbackConstruction.preservesFiniteLimits _ _ _ _

instance : PreservesFiniteColimits (abPullback f) :=
  have : PreservesColimitsOfSize.{0, 0} (abPullback f) :=
    (abAdjunction f).leftAdjoint_preservesColimits
  PreservesColimitsOfSize.preservesFiniteColimits _

instance : (abPullback f).Additive :=
  have := preservesBinaryBiproducts_of_preservesBinaryCoproducts (abPullback f)
  Functor.additive_of_preservesBinaryBiproducts _

end Exact

/-! ### The map on cohomology -/

section Map

/-- The free abelian sheaf `ℤ_W` generated by an open `W`. -/
noncomputable abbrev freeYoneda {Z : TopCat.{u}} (W : Opens Z) :
    CategoryTheory.Sheaf (Opens.grothendieckTopology Z) AddCommGrpCat.{u} :=
  (presheafToSheaf _ _).obj (yoneda.obj W ⋙ AddCommGrpCat.free)

/-- The canonical section of `ℤ_W` over `W` (the class of the identity of `W`). -/
noncomputable def freeYonedaSection {Z : TopCat.{u}} (W : Opens Z) :
    (freeYoneda W).obj.obj (op W) :=
  CategoryTheory.Sheaf.freeYonedaSheafHomAddEquiv (freeYoneda W) W (𝟙 _)

variable {f}

/-- The morphism `ℤ_{W'} → f⁻¹ ℤ_W` for `W' ⊆ f⁻¹(W)`: it corresponds to the image of the
canonical section of `ℤ_W` under `ℤ_W(W) → (f⁻¹ ℤ_W)(f⁻¹ W) → (f⁻¹ ℤ_W)(W')`. -/
noncomputable def freeYonedaPullback {W : Opens Y} {W' : Opens X}
    (h : W' ≤ (Opens.map f).obj W) :
    freeYoneda W' ⟶ (abPullback f).obj (freeYoneda W) :=
  (CategoryTheory.Sheaf.freeYonedaSheafHomAddEquiv _ W').symm
    (((abPullback f).obj (freeYoneda W)).obj.map (homOfLE h).op
      (((abAdjunction f).unit.app
        (freeYoneda W)).hom.app (op W) (freeYonedaSection W)))

variable {F : CategoryTheory.Sheaf (Opens.grothendieckTopology Y) AddCommGrpCat.{u}}
  {G : CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}}

/-- The canonical map `Hᵖ(W, F) → Hᵖ(W', G)` attached to `g : f⁻¹ F ⟶ G`, for `W' ⊆ f⁻¹(W)`:
apply `f⁻¹` to `Extᵖ(ℤ_W, F)`, then compose with `ℤ_{W'} → f⁻¹ ℤ_W` and `g`
(EGA 0_III 12.1.3.1). -/
noncomputable def cohomologyPullbackMap
    (g : (abPullback f).obj F ⟶ G) {W : Opens Y} {W' : Opens X}
    (h : W' ≤ (Opens.map f).obj W) (p : ℕ) : F.H' p W ⟶ G.H' p W' :=
  AddCommGrpCat.ofHom
    { toFun := fun x ↦ (Ext.mk₀ (freeYonedaPullback h)).comp
        ((Ext.mapExactFunctor (abPullback f)
          (show Ext (freeYoneda W) F p from x)).comp (Ext.mk₀ g) (add_zero p)) (zero_add p)
      map_zero' := by simp
      map_add' := fun x y ↦ by simp [Ext.comp_add] }

lemma cohomologyPullbackMap_apply
    (g : (abPullback f).obj F ⟶ G) {W : Opens Y} {W' : Opens X}
    (h : W' ≤ (Opens.map f).obj W) {p : ℕ} (x : F.H' p W) :
    cohomologyPullbackMap g h p x = (Ext.mk₀ (freeYonedaPullback h)).comp
        ((Ext.mapExactFunctor (abPullback f)
          (show Ext (freeYoneda W) F p from x)).comp (Ext.mk₀ g) (add_zero p)) (zero_add p) :=
  rfl

lemma H'_equiv₀_mk₀ {Z : TopCat.{u}}
    {K : CategoryTheory.Sheaf (Opens.grothendieckTopology Z) AddCommGrpCat.{u}} {W : Opens Z}
    (a : freeYoneda W ⟶ K) :
    CategoryTheory.Sheaf.H'.equiv₀ K W (Ext.mk₀ a) = a.hom.app (op W) (freeYonedaSection W) := by
  change CategoryTheory.Sheaf.freeYonedaSheafHomAddEquiv K W (Ext.addEquiv₀ (Ext.mk₀ a)) = _
  rw [← Ext.addEquiv₀_symm_apply, AddEquiv.apply_symm_apply, ← Category.id_comp a,
    CategoryTheory.Sheaf.freeYonedaSheafHomAddEquiv_comp, Category.id_comp]
  rfl

lemma freeYonedaPullback_app {W : Opens Y} {W' : Opens X} (h : W' ≤ (Opens.map f).obj W) :
    (freeYonedaPullback h).hom.app (op W') (freeYonedaSection W') =
      ((abPullback f).obj (freeYoneda W)).obj.map (homOfLE h).op
        (((abAdjunction f).unit.app (freeYoneda W)).hom.app (op W) (freeYonedaSection W)) := by
  have := CategoryTheory.Sheaf.freeYonedaSheafHomAddEquiv_comp W' (𝟙 _) (freeYonedaPullback h)
  rw [Category.id_comp] at this
  rw [freeYonedaSection, ← this, freeYonedaPullback, AddEquiv.apply_symm_apply]

/-- In degree `0`, `cohomologyPullbackMap g` is `F(W) → G(f⁻¹ W) → G(W')`, where the first map is
the adjoint `F ⟶ f_* G` of `g`. -/
lemma H'_equiv₀_cohomologyPullbackMap (g : (abPullback f).obj F ⟶ G) {W : Opens Y}
    {W' : Opens X} (h : W' ≤ (Opens.map f).obj W) (x : F.H' 0 W) :
    CategoryTheory.Sheaf.H'.equiv₀ G W' (cohomologyPullbackMap g h 0 x) =
      G.obj.map (homOfLE h).op (((abAdjunction f).homEquiv _ _ g).hom.app (op W)
        (CategoryTheory.Sheaf.H'.equiv₀ F W x)) := by
  obtain ⟨a, rfl⟩ := (Ext.mk₀_bijective (freeYoneda W) F).2 x
  change CategoryTheory.Sheaf.H'.equiv₀ G W' ((Ext.mk₀ (freeYonedaPullback h)).comp
    ((Ext.mapExactFunctor (abPullback f) (Ext.mk₀ a)).comp (Ext.mk₀ g) (add_zero 0))
      (zero_add 0)) = _
  rw [Ext.mapExactFunctor_mk₀, Ext.mk₀_comp_mk₀, Ext.mk₀_comp_mk₀, H'_equiv₀_mk₀, H'_equiv₀_mk₀]
  simp only [ObjectProperty.FullSubcategory.comp_hom, NatTrans.comp_app,
    ConcreteCategory.comp_apply, freeYonedaPullback_app]
  -- naturality of `f⁻¹ a` and of `g` with respect to `W' ≤ f⁻¹ W`
  have e1 := NatTrans.naturality_apply ((abPullback f).map a).hom (homOfLE h).op
    (((abAdjunction f).unit.app (freeYoneda W)).hom.app (op W) (freeYonedaSection W))
  have e2 := NatTrans.naturality_apply g.hom (homOfLE h).op
    (((abPullback f).map a).hom.app (op ((Opens.map f).obj W))
      (((abAdjunction f).unit.app (freeYoneda W)).hom.app (op W) (freeYonedaSection W)))
  -- naturality of the unit
  have e3 := congrArg (fun φ ↦ φ.hom.app (op W) (freeYonedaSection W))
    ((abAdjunction f).unit.naturality a)
  simp only [Functor.id_map, ObjectProperty.FullSubcategory.comp_hom, NatTrans.comp_app,
    ConcreteCategory.comp_apply] at e3
  erw [e1, e2]
  erw [Adjunction.homEquiv_unit]
  simp only [ObjectProperty.FullSubcategory.comp_hom, NatTrans.comp_app,
    ConcreteCategory.comp_apply]
  erw [← e3]
  rfl

/-- `cohomologyPullbackMap` is natural in `(F, G, g)`. -/
lemma cohomologyPullbackMap_naturality
    {F' : CategoryTheory.Sheaf (Opens.grothendieckTopology Y) AddCommGrpCat.{u}}
    {G' : CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}}
    (φ : F ⟶ F') (ψ : G ⟶ G') (g : (abPullback f).obj F ⟶ G) (g' : (abPullback f).obj F' ⟶ G')
    (hcomm : (abPullback f).map φ ≫ g' = g ≫ ψ) {W : Opens Y} {W' : Opens X}
    (h : W' ≤ (Opens.map f).obj W) {p : ℕ} (x : F.H' p W) :
    cohomologyPullbackMap g' h p (CategoryTheory.Sheaf.H'.map φ p W x) =
      CategoryTheory.Sheaf.H'.map ψ p W' (cohomologyPullbackMap g h p x) := by
  have key (y : Ext (freeYoneda W) F p) :
      (Ext.mk₀ (freeYonedaPullback h)).comp
        ((Ext.mapExactFunctor (abPullback f) (y.comp (Ext.mk₀ φ) (add_zero p))).comp
          (Ext.mk₀ g') (add_zero p)) (zero_add p) =
      ((Ext.mk₀ (freeYonedaPullback h)).comp
        ((Ext.mapExactFunctor (abPullback f) y).comp (Ext.mk₀ g) (add_zero p))
          (zero_add p)).comp (Ext.mk₀ ψ) (add_zero p) := by
    rw [Ext.mapExactFunctor_comp, Ext.mapExactFunctor_mk₀, Ext.comp_assoc_of_third_deg_zero,
      Ext.comp_assoc_of_third_deg_zero, Ext.comp_assoc_of_third_deg_zero, Ext.mk₀_comp_mk₀,
      Ext.mk₀_comp_mk₀, hcomm]
  exact key x

/-- `AlgebraicGeometry.Scheme.Modules.comp_extClass_naturality` (stated for any abelian category),
precomposed with a class `m` of degree `0`. -/
private lemma ext_comp_extClass_naturality {C : Type*} [Category* C] [Abelian C] [HasExt.{u} C]
    {S₁ S₂ : ShortComplex C} (h₁ : S₁.ShortExact) (h₂ : S₂.ShortExact) (α : S₁ ⟶ S₂)
    {A A' : C} {p : ℕ} (m : Ext A' A 0) (z : Ext A S₁.X₃ p) :
    m.comp ((z.comp h₁.extClass rfl).comp (Ext.mk₀ α.τ₁) (add_zero (p + 1))) (zero_add (p + 1)) =
      (m.comp (z.comp (Ext.mk₀ α.τ₃) (add_zero p)) (zero_add p)).comp h₂.extClass rfl := by
  rw [← AlgebraicGeometry.Scheme.Modules.comp_extClass_naturality h₁ h₂ α z,
    Ext.comp_assoc m _ h₂.extClass (zero_add p) rfl (by omega)]

/-- `cohomologyPullbackMap` commutes with the connecting maps of short exact sequences: for short
exact sequences `S` on `Y` and `S'` on `X` and a morphism `α : f⁻¹ S ⟶ S'`. -/
lemma cohomologyPullbackMap_H'δ
    {S : ShortComplex (CategoryTheory.Sheaf (Opens.grothendieckTopology Y) AddCommGrpCat.{u})}
    {S' : ShortComplex (CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u})}
    (hS : S.ShortExact) (hS' : S'.ShortExact) (α : S.map (abPullback f) ⟶ S')
    {W : Opens Y} {W' : Opens X} (h : W' ≤ (Opens.map f).obj W) (p : ℕ) (x : S.X₃.H' p W) :
    cohomologyPullbackMap α.τ₁ h (p + 1) (H'δ hS W p x) =
      H'δ hS' W' p (cohomologyPullbackMap α.τ₃ h p x) := by
  have key (y : Ext (freeYoneda W) S.X₃ p) :
      (Ext.mk₀ (freeYonedaPullback h)).comp
        ((Ext.mapExactFunctor (abPullback f) (y.comp hS.extClass rfl)).comp
          (Ext.mk₀ α.τ₁) (add_zero (p + 1))) (zero_add (p + 1)) =
      ((Ext.mk₀ (freeYonedaPullback h)).comp
        ((Ext.mapExactFunctor (abPullback f) y).comp (Ext.mk₀ α.τ₃) (add_zero p))
          (zero_add p)).comp hS'.extClass rfl := by
    have hS₁ := hS.map_of_exact (abPullback f)
    have e₁ : Ext.mapExactFunctor (abPullback f) (y.comp hS.extClass rfl) =
        (Ext.mapExactFunctor (abPullback f) y).comp hS₁.extClass rfl := by
      rw [Ext.mapExactFunctor_comp, Ext.mapExactFunctor_extClass]
      rfl
    rw [e₁]
    exact ext_comp_extClass_naturality hS₁ hS' α _ _
  exact key x

/-- `cohomologyPullbackMap` commutes with connecting maps (morphism form). -/
lemma H'δ_comp_cohomologyPullbackMap
    {S : ShortComplex (CategoryTheory.Sheaf (Opens.grothendieckTopology Y) AddCommGrpCat.{u})}
    {S' : ShortComplex (CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u})}
    (hS : S.ShortExact) (hS' : S'.ShortExact) (α : S.map (abPullback f) ⟶ S')
    {W : Opens Y} {W' : Opens X} (h : W' ≤ (Opens.map f).obj W) (p : ℕ) :
    H'δ hS W p ≫ cohomologyPullbackMap α.τ₁ h (p + 1) =
      cohomologyPullbackMap α.τ₃ h p ≫ H'δ hS' W' p := by
  ext x
  exact cohomologyPullbackMap_H'δ hS hS' α h p x

end Map

end TopCat.Sheaf

/-! ### Global cohomology -/

namespace TopCat.Sheaf

section Global

variable {X Y : TopCat.{u}} (f : X ⟶ Y)

/-- The constant sheaf `ℤ` (as `ULift ℤ`) on a topological space. -/
noncomputable abbrev constZ (Z : TopCat.{u}) :
    CategoryTheory.Sheaf (Opens.grothendieckTopology Z) AddCommGrpCat.{u} :=
  (constantSheaf (Opens.grothendieckTopology Z) AddCommGrpCat.{u}).obj (AddCommGrpCat.of (ULift ℤ))

/-- The adjunction between the constant sheaf functor and global sections. -/
noncomputable abbrev constAdj (Z : TopCat.{u}) :=
  constantSheafAdj (Opens.grothendieckTopology Z) AddCommGrpCat.{u}
    (isTerminalTop (α := Opens Z))

/-- The canonical morphism `ℤ_X → f⁻¹ ℤ_Y`: the image of the section `1` of `ℤ_Y`. -/
noncomputable def constZToPullback : constZ X ⟶ (abPullback f).obj (constZ Y) :=
  ((constAdj X).homEquiv _ _).symm
    ((constAdj Y).unit.app (AddCommGrpCat.of (ULift ℤ)) ≫
      ((sheafSections _ _).obj (op ⊤)).map ((abAdjunction f).unit.app (constZ Y)))

variable {F : CategoryTheory.Sheaf (Opens.grothendieckTopology Y) AddCommGrpCat.{u}}
  {G : CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}}

variable {f} in
/-- The canonical map `Hᵖ(Y, F) → Hᵖ(X, G)` on global cohomology (`Extᵖ(ℤ, -)`) attached to
`g : f⁻¹ F ⟶ G`: apply `f⁻¹`, then compose with `ℤ_X → f⁻¹ ℤ_Y` and `g`. Over the terminal open
it is `cohomologyPullbackMap` (`addEquivH_cohomologyPullbackMap`). -/
noncomputable def globalCohomologyPullbackMap (g : (abPullback f).obj F ⟶ G) (p : ℕ) :
    F.H p →+ G.H p :=
  ((Ext.mk₀ (constZToPullback f)).precomp _ (zero_add p)).comp
    (((Ext.mk₀ g).postcomp _ (add_zero p)).comp ((abPullback f).mapExtAddHom _ _ p))

/-- Additive maps out of `ULift ℤ` are determined by the image of `1`. -/
private lemma hom_ext_ulift_int {A : AddCommGrpCat.{u}} {φ ψ : AddCommGrpCat.of (ULift ℤ) ⟶ A}
    (h : φ (ULift.up 1) = ψ (ULift.up 1)) : φ = ψ := by
  ext ⟨k⟩
  have e : (ULift.up k : ULift ℤ) = k • ULift.up 1 := by
    apply ULift.ext
    simp
  rw [e, map_zsmul, map_zsmul, h]

/-- Under `ℤ_⊤ ≅ ℤ`, the section `1` of the constant sheaf is the canonical section of `ℤ_⊤`. -/
lemma freeYonedaSheafTerminalIso_inv_unit (Z : TopCat.{u}) :
    (CategoryTheory.Sheaf.freeYonedaSheafTerminalIso (isTerminalTop (α := Opens Z))).inv.hom.app
        (op ⊤) ((constAdj Z).unit.app (AddCommGrpCat.of (ULift ℤ)) (ULift.up 1)) =
      freeYonedaSection (⊤ : Opens Z) := by
  rw [constAdj, constantSheafAdj, Adjunction.comp_unit_app]
  change (CategoryTheory.Sheaf.freeYonedaSheafTerminalIso _).inv.hom.app (op ⊤)
    ((toSheafify (Opens.grothendieckTopology Z) ((Functor.const _).obj
      (AddCommGrpCat.of (ULift ℤ)))).app (op ⊤) (ULift.up 1)) = _
  have e1 := congrArg (fun φ ↦ φ.app (op ⊤) (ULift.up 1)) (toSheafify_naturality
    (Opens.grothendieckTopology Z)
    (CategoryTheory.Sheaf.freeYonedaTerminalIso (isTerminalTop (α := Opens Z))).inv)
  simp only [NatTrans.comp_app, ConcreteCategory.comp_apply] at e1
  have e2 : (CategoryTheory.Sheaf.freeYonedaTerminalIso (isTerminalTop (α := Opens Z))).inv.app
      (op ⊤) (ULift.up 1) = FreeAbelianGroup.of (𝟙 (⊤ : Opens Z)) := by
    change (FreeAbelianGroup.uniqueEquiv ((⊤ : Opens Z) ⟶ ⊤)).symm 1 = _
    change (1 : ℤ) • FreeAbelianGroup.of (default : (⊤ : Opens Z) ⟶ ⊤) = _
    rw [one_smul]
    rfl
  rw [e2] at e1
  change (sheafifyMap _ (CategoryTheory.Sheaf.freeYonedaTerminalIso
    (isTerminalTop (α := Opens Z))).inv).app (op ⊤) _ = _
  rw [← e1]
  rw [freeYonedaSection, CategoryTheory.Sheaf.freeYonedaSheafHomAddEquiv, AddEquiv.trans_apply,
    CategoryTheory.Sheaf.freeYonedaHomAddEquiv_apply, Adjunction.homAddEquiv_apply,
    Adjunction.homEquiv_id]

lemma top_le_map_top : (⊤ : Opens X) ≤ (Opens.map f).obj ⊤ := (Opens.map_top f).ge

lemma freeYonedaSheafTerminalIso_inv_comp_freeYonedaPullback :
    (CategoryTheory.Sheaf.freeYonedaSheafTerminalIso (isTerminalTop (α := Opens X))).inv ≫
        freeYonedaPullback (top_le_map_top f) =
      constZToPullback f ≫ (abPullback f).map
        (CategoryTheory.Sheaf.freeYonedaSheafTerminalIso (isTerminalTop (α := Opens Y))).inv := by
  apply ((constAdj X).homEquiv _ _).injective
  rw [Adjunction.homEquiv_unit, Adjunction.homEquiv_unit]
  apply hom_ext_ulift_int
  simp only [ConcreteCategory.comp_apply]
  change (freeYonedaPullback (top_le_map_top f)).hom.app (op ⊤)
      ((CategoryTheory.Sheaf.freeYonedaSheafTerminalIso _).inv.hom.app (op ⊤)
        ((constAdj X).unit.app _ (ULift.up 1))) =
    ((abPullback f).map (CategoryTheory.Sheaf.freeYonedaSheafTerminalIso _).inv).hom.app (op ⊤)
      ((constZToPullback f).hom.app (op ⊤) ((constAdj X).unit.app _ (ULift.up 1)))
  rw [freeYonedaSheafTerminalIso_inv_unit, freeYonedaPullback_app]
  have e1 : (constZToPullback f).hom.app (op ⊤) ((constAdj X).unit.app _ (ULift.up 1)) =
      ((abAdjunction f).unit.app (constZ Y)).hom.app (op ⊤)
        ((constAdj Y).unit.app _ (ULift.up 1)) := by
    have := congrArg (fun φ ↦ φ (ULift.up 1))
      (((constAdj X).homEquiv _ _).apply_symm_apply
        ((constAdj Y).unit.app (AddCommGrpCat.of (ULift ℤ)) ≫
          ((sheafSections _ _).obj (op ⊤)).map ((abAdjunction f).unit.app (constZ Y))))
    rw [Adjunction.homEquiv_unit] at this
    exact this
  rw [e1]
  have e2 := congrArg (fun φ ↦ φ.hom.app (op ⊤) ((constAdj Y).unit.app _ (ULift.up 1)))
    ((abAdjunction f).unit.naturality
      (CategoryTheory.Sheaf.freeYonedaSheafTerminalIso (isTerminalTop (α := Opens Y))).inv)
  simp only [Functor.id_map, ObjectProperty.FullSubcategory.comp_hom, NatTrans.comp_app,
    ConcreteCategory.comp_apply] at e2
  erw [← e2, freeYonedaSheafTerminalIso_inv_unit]
  rw [show (homOfLE (top_le_map_top f)).op = 𝟙 (op ((Opens.map f).obj ⊤)) from rfl]
  erw [CategoryTheory.Functor.map_id]
  rfl

/-- Over the terminal open, `cohomologyPullbackMap` is `globalCohomologyPullbackMap`, through
`Hᵖ(⊤, -) ≃ Hᵖ(-)` (`CategoryTheory.Sheaf.H'.addEquivH`). -/
theorem addEquivH_cohomologyPullbackMap (g : (abPullback f).obj F ⟶ G) (p : ℕ)
    (x : F.H' p ⊤) :
    CategoryTheory.Sheaf.H'.addEquivH (isTerminalTop (α := Opens X)) G p
        (cohomologyPullbackMap g (top_le_map_top f) p x) =
      globalCohomologyPullbackMap g p
        (CategoryTheory.Sheaf.H'.addEquivH (isTerminalTop (α := Opens Y)) F p x) := by
  have key (y : Ext (freeYoneda (⊤ : Opens Y)) F p) :
      (Ext.mk₀ (CategoryTheory.Sheaf.freeYonedaSheafTerminalIso
          (isTerminalTop (α := Opens X))).inv).comp ((Ext.mk₀ (freeYonedaPullback
            (top_le_map_top f))).comp ((Ext.mapExactFunctor (abPullback f) y).comp
              (Ext.mk₀ g) (add_zero p)) (zero_add p)) (zero_add p) =
        (Ext.mk₀ (constZToPullback f)).comp ((Ext.mapExactFunctor (abPullback f)
          ((Ext.mk₀ (CategoryTheory.Sheaf.freeYonedaSheafTerminalIso
            (isTerminalTop (α := Opens Y))).inv).comp y (zero_add p))).comp (Ext.mk₀ g)
              (add_zero p)) (zero_add p) := by
    rw [Ext.mk₀_comp_mk₀_assoc, freeYonedaSheafTerminalIso_inv_comp_freeYonedaPullback,
      Ext.mapExactFunctor_comp, Ext.mapExactFunctor_mk₀,
      Ext.comp_assoc _ _ (Ext.mk₀ g) (zero_add p) (add_zero p) (by omega), Ext.mk₀_comp_mk₀_assoc]
  exact key x

lemma globalCohomologyPullbackMap_apply (g : (abPullback f).obj F ⟶ G) {p : ℕ} (x : F.H p) :
    globalCohomologyPullbackMap g p x = (Ext.mk₀ (constZToPullback f)).comp
      ((Ext.mapExactFunctor (abPullback f) x).comp (Ext.mk₀ g) (add_zero p)) (zero_add p) :=
  rfl

/-- `globalCohomologyPullbackMap` is natural in `(F, G, g)`. -/
lemma globalCohomologyPullbackMap_naturality
    {F' : CategoryTheory.Sheaf (Opens.grothendieckTopology Y) AddCommGrpCat.{u}}
    {G' : CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}}
    (φ : F ⟶ F') (ψ : G ⟶ G') (g : (abPullback f).obj F ⟶ G) (g' : (abPullback f).obj F' ⟶ G')
    (hcomm : (abPullback f).map φ ≫ g' = g ≫ ψ) {p : ℕ} (x : F.H p) :
    globalCohomologyPullbackMap g' p (CategoryTheory.Sheaf.H.map φ p x) =
      CategoryTheory.Sheaf.H.map ψ p (globalCohomologyPullbackMap g p x) := by
  rw [globalCohomologyPullbackMap_apply, globalCohomologyPullbackMap_apply,
    CategoryTheory.Sheaf.H.map_apply, CategoryTheory.Sheaf.H.map_apply,
    Ext.mapExactFunctor_comp, Ext.mapExactFunctor_mk₀, Ext.comp_assoc_of_third_deg_zero,
    Ext.comp_assoc_of_third_deg_zero, Ext.comp_assoc_of_third_deg_zero, Ext.mk₀_comp_mk₀,
    Ext.mk₀_comp_mk₀, hcomm]

/-- `globalCohomologyPullbackMap` commutes with the connecting maps of short exact sequences: for
short exact sequences `S` on `Y` and `S'` on `X` and a morphism `α : f⁻¹ S ⟶ S'`. -/
lemma globalCohomologyPullbackMap_comp_extClass
    {S : ShortComplex (CategoryTheory.Sheaf (Opens.grothendieckTopology Y) AddCommGrpCat.{u})}
    {S' : ShortComplex (CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u})}
    (hS : S.ShortExact) (hS' : S'.ShortExact) (α : S.map (abPullback f) ⟶ S') (p : ℕ)
    (x : S.X₃.H p) :
    globalCohomologyPullbackMap α.τ₁ (p + 1) (x.comp hS.extClass rfl) =
      (globalCohomologyPullbackMap α.τ₃ p x).comp hS'.extClass rfl := by
  have hS₁ := hS.map_of_exact (abPullback f)
  have e₁ : Ext.mapExactFunctor (abPullback f) (x.comp hS.extClass rfl) =
      (Ext.mapExactFunctor (abPullback f) x).comp hS₁.extClass rfl := by
    rw [Ext.mapExactFunctor_comp, Ext.mapExactFunctor_extClass]
    rfl
  change (Ext.mk₀ (constZToPullback f)).comp
      ((Ext.mapExactFunctor (abPullback f) (x.comp hS.extClass rfl)).comp
        (Ext.mk₀ α.τ₁) (add_zero (p + 1))) (zero_add (p + 1)) =
    ((Ext.mk₀ (constZToPullback f)).comp
      ((Ext.mapExactFunctor (abPullback f) x).comp (Ext.mk₀ α.τ₃) (add_zero p))
        (zero_add p)).comp hS'.extClass rfl
  rw [e₁]
  exact ext_comp_extClass_naturality hS₁ hS' α _ _

end Global

end TopCat.Sheaf

/-! ### Čech cochains -/

namespace TopCat.Presheaf

section Pullback

variable {X Y : TopCat.{u}} (f : X ⟶ Y) {ι : Type*} (U : ι → Opens Y)

/-- The finite intersections of the family `f⁻¹ U` are the inverse images of those of `U`. -/
lemma cechOpen_map {α : Type*} [Finite α] (x : α → ι) :
    cechOpen (fun i ↦ (Opens.map f).obj (U i)) x = (Opens.map f).obj (cechOpen U x) := by
  apply SetLike.coe_injective
  simp only [cechOpen, Opens.coe_iInf, Opens.map_coe, Set.preimage_iInter]

variable {P P' : TopCat.Presheaf AddCommGrpCat.{u} Y} {Q Q' : TopCat.Presheaf AddCommGrpCat.{u} X}

/-- The map of Čech cochains `Č(U, P) → Č(f⁻¹ U, Q)` induced by `φ : P ⟶ f_* Q`:
`c ↦ (φ(c_x)|_{(f⁻¹ U)_x})_x`. -/
noncomputable def cechPullbackCochainMap (φ : P ⟶ (Presheaf.pushforward _ f).obj Q) (n : ℕ) :
    CechCochain U P n →+ CechCochain (fun i ↦ (Opens.map f).obj (U i)) Q n :=
  AddMonoidHom.pi fun x ↦ (Q.map (homOfLE (cechOpen_map f U x).le).op).hom.comp
    ((φ.app (op (cechOpen U x))).hom.comp
      (Pi.evalAddMonoidHom (fun x : Fin (n + 1) → ι ↦ P.obj (op (cechOpen U x))) x))

lemma cechPullbackCochainMap_apply (φ : P ⟶ (Presheaf.pushforward _ f).obj Q) {n : ℕ}
    (c : CechCochain U P n) (x : Fin (n + 1) → ι) :
    cechPullbackCochainMap f U φ n c x =
      Q.map (homOfLE (cechOpen_map f U x).le).op (φ.app (op (cechOpen U x)) (c x)) :=
  rfl

lemma cechPullbackCochainMap_cechMap (φ : P ⟶ (Presheaf.pushforward _ f).obj Q) {m n : ℕ}
    (θ : Fin (m + 1) → Fin (n + 1)) (c : CechCochain U P m) :
    cechPullbackCochainMap f U φ n (cechMap U P θ c) =
      cechMap _ Q θ (cechPullbackCochainMap f U φ m c) := by
  funext y
  simp only [cechPullbackCochainMap_apply, cechMap_apply]
  erw [NatTrans.naturality_apply φ]
  rw [map_map_apply]
  erw [map_map_apply]
  rfl

/-- The map of Čech cochains induced by `φ : P ⟶ f_* Q` commutes with the Čech differentials. -/
lemma cechD_cechPullbackCochainMap (φ : P ⟶ (Presheaf.pushforward _ f).obj Q) {n : ℕ}
    (c : CechCochain U P n) :
    cechD _ Q n (cechPullbackCochainMap f U φ n c) =
      cechPullbackCochainMap f U φ (n + 1) (cechD U P n c) := by
  simp only [cechD, AddMonoidHom.finsetSum_apply, map_sum, AddMonoidHom.smul_apply, map_zsmul,
    cechPullbackCochainMap_cechMap]

end Pullback

section PullbackComplex

variable {X Y : TopCat.{u}} (f : X ⟶ Y) {n : ℕ} (U : Fin n → Opens Y)
  {P P' : TopCat.Presheaf AddCommGrpCat.{u} Y} {Q Q' : TopCat.Presheaf AddCommGrpCat.{u} X}

/-- The morphism of cosimplicial Čech objects induced by `φ : P ⟶ f_* Q`. -/
@[simps]
noncomputable def cechPullbackCosimplicialMap (φ : P ⟶ (Presheaf.pushforward _ f).obj Q) :
    cechCosimplicialObject U P ⟶ cechCosimplicialObject (fun i ↦ (Opens.map f).obj (U i)) Q where
  app Δ := AddCommGrpCat.ofHom (cechPullbackCochainMap f U φ Δ.len)
  naturality _ _ θ := AddCommGrpCat.ext fun c ↦
    cechPullbackCochainMap_cechMap f U φ θ.toOrderHom c

/-- The morphism of Čech complexes `Č(U, P) → Č(f⁻¹ U, Q)` induced by `φ : P ⟶ f_* Q`. -/
noncomputable def cechPullbackComplexMap (φ : P ⟶ (Presheaf.pushforward _ f).obj Q) :
    cechComplex U P ⟶ cechComplex (fun i ↦ (Opens.map f).obj (U i)) Q :=
  (AlgebraicTopology.alternatingCofaceMapComplex _).map (cechPullbackCosimplicialMap f U φ)

lemma cechPullbackComplexMap_f_apply (φ : P ⟶ (Presheaf.pushforward _ f).obj Q) (m : ℕ)
    (c : CechCochain U P m) :
    (cechPullbackComplexMap f U φ).f m c = cechPullbackCochainMap f U φ m c :=
  rfl

lemma cechComplexMap_comp_cechPullbackComplexMap (χ : P' ⟶ P)
    (φ : P ⟶ (Presheaf.pushforward _ f).obj Q) :
    cechComplexMap U χ ≫ cechPullbackComplexMap f U φ = cechPullbackComplexMap f U (χ ≫ φ) := by
  ext m : 1
  exact AddCommGrpCat.ext fun c ↦ rfl

lemma cechPullbackComplexMap_comp_cechComplexMap (φ : P ⟶ (Presheaf.pushforward _ f).obj Q)
    (ψ : Q ⟶ Q') :
    cechPullbackComplexMap f U φ ≫ cechComplexMap _ ψ =
      cechPullbackComplexMap f U (φ ≫ (Presheaf.pushforward _ f).map ψ) := by
  ext m : 1
  refine AddCommGrpCat.ext fun c ↦ funext fun x ↦ ?_
  change ψ.app _ (Q.map _ (φ.app _ (c x))) = Q'.map _ (ψ.app _ (φ.app _ (c x)))
  exact NatTrans.naturality_apply ψ _ _

lemma cechPullbackCochainMap_cechAugmentation (φ : P ⟶ (Presheaf.pushforward _ f).obj Q)
    (s : P.obj (op (⨆ i, U i))) :
    cechPullbackCochainMap f U φ 0 (cechAugmentation U P s) =
      cechAugmentation _ Q (Q.map (homOfLE (iSup_le fun i ↦
        ((Opens.map f).map (homOfLE (le_iSup U i))).le)).op (φ.app _ s)) := by
  funext x
  simp only [cechPullbackCochainMap_apply, cechAugmentation_apply]
  erw [NatTrans.naturality_apply φ]
  erw [map_map_apply, map_map_apply]
  rfl

lemma cechH0Map_cechPullbackComplexMap (φ : P ⟶ (Presheaf.pushforward _ f).obj Q) :
    cechH0Map U P ≫ HomologicalComplex.homologyMap (cechPullbackComplexMap f U φ) 0 =
      (φ.app _ ≫ Q.map (homOfLE (iSup_le fun i ↦
        ((Opens.map f).map (homOfLE (le_iSup U i))).le)).op) ≫ cechH0Map _ Q := by
  rw [cechH0Map, cechH0Map, Category.assoc, HomologicalComplex.homologyπ_naturality,
    HomologicalComplex.liftCycles_comp_cyclesMap_assoc, HomologicalComplex.comp_liftCycles_assoc]
  congr 2
  exact AddCommGrpCat.ext fun s ↦ cechPullbackCochainMap_cechAugmentation f U φ s

end PullbackComplex

end TopCat.Presheaf

/-! ### Compatibility with Leray's isomorphisms -/

namespace TopCat.Sheaf

variable {X Y : TopCat.{u}} (f : X ⟶ Y) {n : ℕ} (U : Fin n → Opens Y)

lemma iSup_map_le : ⨆ i, (Opens.map f).obj (U i) ≤ (Opens.map f).obj (⨆ i, U i) :=
  iSup_le fun i ↦ ((Opens.map f).map (homOfLE (le_iSup U i))).le

variable {f}

/-- The morphism of presheaves `F ⟶ f_* G` adjoint to `g : f⁻¹ F ⟶ G`. -/
noncomputable abbrev pullbackAdjoint
    {F : CategoryTheory.Sheaf (Opens.grothendieckTopology Y) AddCommGrpCat.{u}}
    {G : CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}}
    (g : (abPullback f).obj F ⟶ G) : F.obj ⟶ (Presheaf.pushforward _ f).obj G.obj :=
  ((abAdjunction f).homEquiv _ _ g).hom

lemma cechH0Iso_hom_cechH0Map_apply {Z : TopCat.{u}} {m : ℕ} (V : Fin m → Opens Z)
    (K : CategoryTheory.Sheaf (Opens.grothendieckTopology Z) AddCommGrpCat.{u})
    (s : K.obj.obj (op (⨆ i, V i))) :
    (cechH0Iso V K).hom (cechH0Map V K.obj s) =
      (CategoryTheory.Sheaf.H'.equiv₀ K (⨆ i, V i)).symm s := by
  change (CategoryTheory.Sheaf.H'.equiv₀ K _).symm
    ((asIso (cechH0Map V K.obj)).inv ((asIso (cechH0Map V K.obj)).hom s)) = _
  rw [Iso.hom_inv_id_apply]

/-- Degree `0` of `cechHomologyIso_cohomologyPullbackMap`. -/
lemma cechH0Iso_cohomologyPullbackMap
    {F : CategoryTheory.Sheaf (Opens.grothendieckTopology Y) AddCommGrpCat.{u}}
    {G : CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}}
    (g : (abPullback f).obj F ⟶ G) :
    HomologicalComplex.homologyMap (cechPullbackComplexMap f U (pullbackAdjoint g)) 0 ≫
        (cechH0Iso _ G).hom =
      (cechH0Iso U F).hom ≫ cohomologyPullbackMap g (iSup_map_le f U) 0 := by
  rw [← cancel_epi (cechH0Map U F.obj), ← Category.assoc, cechH0Map_cechPullbackComplexMap]
  ext s
  change (cechH0Iso _ G).hom (cechH0Map _ G.obj _) =
    cohomologyPullbackMap g (iSup_map_le f U) 0 ((cechH0Iso U F).hom (cechH0Map U F.obj s))
  rw [cechH0Iso_hom_cechH0Map_apply, cechH0Iso_hom_cechH0Map_apply]
  apply (CategoryTheory.Sheaf.H'.equiv₀ G _).injective
  rw [AddEquiv.apply_symm_apply, H'_equiv₀_cohomologyPullbackMap, AddEquiv.apply_symm_apply]
  rfl

section Leray

variable {F F' : CategoryTheory.Sheaf (Opens.grothendieckTopology Y) AddCommGrpCat.{u}}
  {G G' : CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}}

lemma comp_pullbackAdjoint (a : F' ⟶ F) (g : (abPullback f).obj F ⟶ G) :
    a.hom ≫ pullbackAdjoint g = pullbackAdjoint ((abPullback f).map a ≫ g) := by
  rw [pullbackAdjoint, pullbackAdjoint, Adjunction.homEquiv_naturality_left]
  rfl

lemma pullbackAdjoint_comp (g : (abPullback f).obj F ⟶ G) (b : G ⟶ G') :
    pullbackAdjoint g ≫ (Presheaf.pushforward _ f).map b.hom = pullbackAdjoint (g ≫ b) := by
  rw [pullbackAdjoint, pullbackAdjoint, Adjunction.homEquiv_naturality_right]
  rfl

variable (f) in
lemma injSeq_map_shortExact (F : CategoryTheory.Sheaf (Opens.grothendieckTopology Y)
    AddCommGrpCat.{u}) : ((injSeq F).map (abPullback f)).ShortExact :=
  (injSeq_shortExact F).map_of_exact (abPullback f)

instance (F : CategoryTheory.Sheaf (Opens.grothendieckTopology Y) AddCommGrpCat.{u}) :
    Mono ((abPullback f).map (injSeq F).f) :=
  (injSeq_map_shortExact f F).mono_f

instance (F : CategoryTheory.Sheaf (Opens.grothendieckTopology Y) AddCommGrpCat.{u}) :
    Epi ((injSeq F).map (abPullback f)).g :=
  (injSeq_map_shortExact f F).epi_g

variable (f) in
/-- The extension `f⁻¹ I(F) ⟶ I(G)` of `g : f⁻¹ F ⟶ G` (`I(G)` is injective). -/
noncomputable def injPullbackMap (g : (abPullback f).obj F ⟶ G) :
    (abPullback f).obj (injSeq F).X₂ ⟶ (injSeq G).X₂ :=
  Injective.factorThru (g ≫ (injSeq G).f) ((abPullback f).map (injSeq F).f)

lemma map_f_injPullbackMap (g : (abPullback f).obj F ⟶ G) :
    (abPullback f).map (injSeq F).f ≫ injPullbackMap f g = g ≫ (injSeq G).f :=
  Injective.comp_factorThru _ _

lemma map_f_injPullbackMap_g (g : (abPullback f).obj F ⟶ G) :
    (abPullback f).map (injSeq F).f ≫ injPullbackMap f g ≫ (injSeq G).g = 0 := by
  rw [← Category.assoc, map_f_injPullbackMap, Category.assoc, (injSeq G).zero, comp_zero]

variable (f) in
/-- The morphism `f⁻¹(0 → F → I(F) → Q(F) → 0) ⟶ (0 → G → I(G) → Q(G) → 0)` extending
`g : f⁻¹ F ⟶ G` (`I(G)` is injective and `f⁻¹` is exact). -/
noncomputable def injSeqPullbackMap (g : (abPullback f).obj F ⟶ G) :
    (injSeq F).map (abPullback f) ⟶ injSeq G where
  τ₁ := g
  τ₂ := injPullbackMap f g
  τ₃ := (injSeq_map_shortExact f F).exact.desc (injPullbackMap f g ≫ (injSeq G).g)
    (map_f_injPullbackMap_g g)
  comm₁₂ := (map_f_injPullbackMap g).symm
  comm₂₃ := ((injSeq_map_shortExact f F).exact.g_desc _ _).symm

@[simp]
lemma injSeqPullbackMap_τ₁ (g : (abPullback f).obj F ⟶ G) : (injSeqPullbackMap f g).τ₁ = g :=
  rfl

variable {U} in
/-- The morphism of short complexes of Čech complexes `Č(U, S₁) ⟶ Č(f⁻¹ U, S₂)` induced by a
morphism `α : f⁻¹ S₁ ⟶ S₂`. -/
noncomputable def cechShortComplexPullbackMap
    {S₁ : ShortComplex (CategoryTheory.Sheaf (Opens.grothendieckTopology Y) AddCommGrpCat.{u})}
    {S₂ : ShortComplex (CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u})}
    (α : S₁.map (abPullback f) ⟶ S₂) :
    cechShortComplex U (S := S₁) ⟶
      cechShortComplex (fun i ↦ (Opens.map f).obj (U i)) (S := S₂) where
  τ₁ := cechPullbackComplexMap f U (pullbackAdjoint α.τ₁)
  τ₂ := cechPullbackComplexMap f U (pullbackAdjoint α.τ₂)
  τ₃ := cechPullbackComplexMap f U (pullbackAdjoint α.τ₃)
  comm₁₂ := by
    have e : S₁.f.hom ≫ pullbackAdjoint α.τ₂ =
        pullbackAdjoint α.τ₁ ≫ (Presheaf.pushforward _ f).map S₂.f.hom := by
      rw [comp_pullbackAdjoint (f := f) S₁.f α.τ₂, pullbackAdjoint_comp (f := f) α.τ₁ S₂.f]
      exact congrArg pullbackAdjoint α.comm₁₂.symm
    change _ ≫ cechComplexMap _ S₂.f.hom = cechComplexMap U S₁.f.hom ≫ _
    rw [cechComplexMap_comp_cechPullbackComplexMap, cechPullbackComplexMap_comp_cechComplexMap, e]
  comm₂₃ := by
    have e : S₁.g.hom ≫ pullbackAdjoint α.τ₃ =
        pullbackAdjoint α.τ₂ ≫ (Presheaf.pushforward _ f).map S₂.g.hom := by
      rw [comp_pullbackAdjoint (f := f) S₁.g α.τ₃, pullbackAdjoint_comp (f := f) α.τ₂ S₂.g]
      exact congrArg pullbackAdjoint α.comm₂₃.symm
    change _ ≫ cechComplexMap _ S₂.g.hom = cechComplexMap U S₁.g.hom ≫ _
    rw [cechComplexMap_comp_cechPullbackComplexMap, cechPullbackComplexMap_comp_cechComplexMap, e]

variable (f) in
/-- The component `f⁻¹ Q(F) ⟶ Q(G)` of `injSeqPullbackMap f g`. -/
noncomputable abbrev injSeqPullbackMap₃ (g : (abPullback f).obj F ⟶ G) :
    (abPullback f).obj (injSeq F).X₃ ⟶ (injSeq G).X₃ :=
  (injSeqPullbackMap f g).τ₃

lemma H'δ_injSeq_comp_cohomologyPullbackMap (g : (abPullback f).obj F ⟶ G) {W : Opens Y}
    {W' : Opens X} (h : W' ≤ (Opens.map f).obj W) (p : ℕ) :
    H'δ (injSeq_shortExact F) W p ≫ cohomologyPullbackMap g h (p + 1) =
      cohomologyPullbackMap (injSeqPullbackMap₃ f g) h p ≫ H'δ (injSeq_shortExact G) W' p :=
  H'δ_comp_cohomologyPullbackMap _ _ (injSeqPullbackMap f g) h p

private lemma cechHomologyIso_succ_succ {Z : TopCat.{u}} {m : ℕ} {V : Fin m → Opens Z} (p : ℕ)
    (K : CategoryTheory.Sheaf (Opens.grothendieckTopology Z) AddCommGrpCat.{u})
    (hK : IsLerayAcyclic V K) :
    cechHomologyIso (p + 2) K hK =
      (hK.shortExact_cechShortComplex.δIso (p + 1) (p + 2) (complexShape_up_rel_succ (p + 1))
        (isZero_homology_injSeq V K p) (isZero_homology_injSeq V K (p + 1))).symm ≪≫
        cechHomologyIso (p + 1) (injSeq K).X₃ hK.injSeqX₃ ≪≫ H'δIso K (⨆ i, V i) p :=
  rfl

/-- **Leray's isomorphisms are compatible with pullback.** Let `f : X ⟶ Y` be continuous, `U` a
finite family of opens of `Y`, `F` an abelian sheaf on `Y` which is Leray-acyclic for `U`, `G` an
abelian sheaf on `X` which is Leray-acyclic for `f⁻¹ U`, and `g : f⁻¹ F ⟶ G`. Then, through
Leray's isomorphisms `Ȟᵖ(U, F) ≅ Hᵖ(⋃ Uᵢ, F)` and `Ȟᵖ(f⁻¹ U, G) ≅ Hᵖ(⋃ f⁻¹ Uᵢ, G)`, the map
`cohomologyPullbackMap g` is the map of Čech cohomology induced by the adjoint `F ⟶ f_* G` of
`g`. -/
theorem cechHomologyIso_cohomologyPullbackMap :
    ∀ (p : ℕ) {F : CategoryTheory.Sheaf (Opens.grothendieckTopology Y) AddCommGrpCat.{u}}
      {G : CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}}
      (hF : IsLerayAcyclic U F) (hG : IsLerayAcyclic (fun i ↦ (Opens.map f).obj (U i)) G)
      (g : (abPullback f).obj F ⟶ G),
      HomologicalComplex.homologyMap (cechPullbackComplexMap f U (pullbackAdjoint g)) p ≫
          (cechHomologyIso p G hG).hom =
        (cechHomologyIso p F hF).hom ≫ cohomologyPullbackMap g (iSup_map_le f U) p
  | 0, F, G, hF, hG, g => cechH0Iso_cohomologyPullbackMap U g
  | 1, F, G, hF, hG, g => by
    have := hF.shortExact_cechShortComplex.epi_δ 0 1 (complexShape_up_rel_succ 0)
      (isZero_homology_injSeq U F 0)
    rw [← cancel_epi (hF.shortExact_cechShortComplex.δ 0 1 (complexShape_up_rel_succ 0))]
    have hδ := HomologicalComplex.HomologySequence.δ_naturality
      (cechShortComplexPullbackMap (U := U) (injSeqPullbackMap f g))
      hF.shortExact_cechShortComplex hG.shortExact_cechShortComplex 0 1
      (complexShape_up_rel_succ 0)
    rw [← Category.assoc, show cechPullbackComplexMap f U (pullbackAdjoint g) =
      (cechShortComplexPullbackMap (U := U) (injSeqPullbackMap f g)).τ₁ from rfl, hδ,
      Category.assoc, cechHomologyIso_one_comp hG, ← Category.assoc,
      show (cechShortComplexPullbackMap (U := U) (injSeqPullbackMap f g)).τ₃ =
        cechPullbackComplexMap f U (pullbackAdjoint (injSeqPullbackMap₃ f g)) from rfl,
      cechH0Iso_cohomologyPullbackMap, Category.assoc,
      ← H'δ_injSeq_comp_cohomologyPullbackMap, ← Category.assoc]
    rw [← cechHomologyIso_one_comp hF, Category.assoc]
  | p + 2, F, G, hF, hG, g => by
    have ih := cechHomologyIso_cohomologyPullbackMap (p + 1) hF.injSeqX₃ hG.injSeqX₃
      (injSeqPullbackMap₃ f g)
    have hδ := HomologicalComplex.HomologySequence.δ_naturality
      (cechShortComplexPullbackMap (U := U) (injSeqPullbackMap f g))
      hF.shortExact_cechShortComplex hG.shortExact_cechShortComplex (p + 1) (p + 2)
      (complexShape_up_rel_succ (p + 1))
    rw [cechHomologyIso_succ_succ, cechHomologyIso_succ_succ]
    simp only [Iso.trans_hom, Iso.symm_hom, Category.assoc, H'δIso_hom]
    have h1 : HomologicalComplex.homologyMap (cechPullbackComplexMap f U (pullbackAdjoint g))
          (p + 2) ≫
        (hG.shortExact_cechShortComplex.δIso (p + 1) (p + 2) (complexShape_up_rel_succ (p + 1))
          (isZero_homology_injSeq _ G p) (isZero_homology_injSeq _ G (p + 1))).inv =
        (hF.shortExact_cechShortComplex.δIso (p + 1) (p + 2) (complexShape_up_rel_succ (p + 1))
          (isZero_homology_injSeq U F p) (isZero_homology_injSeq U F (p + 1))).inv ≫
          HomologicalComplex.homologyMap (cechPullbackComplexMap f U
            (pullbackAdjoint (injSeqPullbackMap₃ f g))) (p + 1) := by
      rw [Iso.comp_inv_eq, Category.assoc, Iso.eq_inv_comp]
      exact hδ
    rw [← Category.assoc, h1, Category.assoc, ← Category.assoc
      (HomologicalComplex.homologyMap (cechPullbackComplexMap f U
        (pullbackAdjoint (injSeqPullbackMap₃ f g))) (p + 1)), ih, Category.assoc,
      ← H'δ_injSeq_comp_cohomologyPullbackMap]

end Leray

/-- `cohomologyPullbackMap` only depends on the opens up to equality. -/
lemma bijective_cohomologyPullbackMap_congr {F : CategoryTheory.Sheaf
      (Opens.grothendieckTopology Y) AddCommGrpCat.{u}}
    {G : CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}}
    (g : (abPullback f).obj F ⟶ G) {W₁ W₂ : Opens Y} {W₁' W₂' : Opens X} (e : W₁ = W₂)
    (e' : W₁' = W₂') (h₁ : W₁' ≤ (Opens.map f).obj W₁) (h₂ : W₂' ≤ (Opens.map f).obj W₂)
    (p : ℕ) :
    Function.Bijective (cohomologyPullbackMap g h₁ p) ↔
      Function.Bijective (cohomologyPullbackMap g h₂ p) := by
  subst e e'
  rfl

variable (f) in
lemma iSup_map_eq_top {U : Fin n → Opens Y} (hU : ⨆ i, U i = ⊤) :
    ⨆ i, (Opens.map f).obj (U i) = ⊤ := by
  apply SetLike.coe_injective
  have := congrArg (fun V : Opens Y ↦ f ⁻¹' (V : Set Y)) hU
  simp only [Opens.coe_iSup, Set.preimage_iUnion, Opens.coe_top, Set.preimage_univ] at this
  simpa only [Opens.coe_iSup, Opens.map_coe, Opens.coe_top] using this

/-- **Comparison of global cohomology through Čech complexes.** For a finite open cover `U` of `Y`
(`⨆ Uᵢ = ⊤`), `F` Leray-acyclic for `U` and `G` Leray-acyclic for `f⁻¹ U`, the map
`Hᵖ(Y, F) → Hᵖ(X, G)` induced by `g : f⁻¹ F ⟶ G` is bijective if and only if the map of Čech
cohomology `Ȟᵖ(U, F) → Ȟᵖ(f⁻¹ U, G)` is. -/
theorem bijective_globalCohomologyPullbackMap_iff (hU : ⨆ i, U i = ⊤)
    {F : CategoryTheory.Sheaf (Opens.grothendieckTopology Y) AddCommGrpCat.{u}}
    {G : CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}}
    (hF : IsLerayAcyclic U F) (hG : IsLerayAcyclic (fun i ↦ (Opens.map f).obj (U i)) G)
    (g : (abPullback f).obj F ⟶ G) (p : ℕ) :
    Function.Bijective (globalCohomologyPullbackMap g p) ↔
      Function.Bijective
        (HomologicalComplex.homologyMap (cechPullbackComplexMap f U (pullbackAdjoint g)) p) := by
  have e₁ : Function.Bijective (globalCohomologyPullbackMap g p) ↔
      Function.Bijective (cohomologyPullbackMap g (top_le_map_top f) p) := by
    have h : ⇑(globalCohomologyPullbackMap g p) =
        (CategoryTheory.Sheaf.H'.addEquivH (isTerminalTop (α := Opens X)) G p) ∘
          (cohomologyPullbackMap g (top_le_map_top f) p) ∘
            (CategoryTheory.Sheaf.H'.addEquivH (isTerminalTop (α := Opens Y)) F p).symm := by
      funext y
      simp only [Function.comp_apply, addEquivH_cohomologyPullbackMap, AddEquiv.apply_symm_apply]
    rw [h, (AddEquiv.bijective _).of_comp_iff', Function.Bijective.of_comp_iff _
      (AddEquiv.bijective (CategoryTheory.Sheaf.H'.addEquivH (isTerminalTop (α := Opens Y))
        F p).symm)]
  rw [e₁, bijective_cohomologyPullbackMap_congr g hU.symm (iSup_map_eq_top f hU).symm
    (top_le_map_top f) (iSup_map_le f U)]
  have h := cechHomologyIso_cohomologyPullbackMap U p hF hG g
  rw [← ConcreteCategory.bijective_of_isIso (cechHomologyIso p G hG).hom |>.of_comp_iff',
    ← ConcreteCategory.coe_comp, h, ConcreteCategory.coe_comp,
    Function.Bijective.of_comp_iff _ (ConcreteCategory.bijective_of_isIso _)]

end TopCat.Sheaf
