/-
Copyright (c) 2026 SGAenglishpluslean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SGAenglishpluslean contributors
-/
import SGA.Foundations.Cohomology.Modules
import SGA.Foundations.Cohomology.QuasiCoherentLocal

/-!
# Functoriality of the cohomology of `𝒪_X`-modules

The maps `Hⁿ(U, M) → Hⁿ(U, N)` induced by morphisms of `𝒪_X`-modules are additive in the morphism
and functorial; isomorphic modules have isomorphic cohomology, and the cohomology of a finite
biproduct is generated by the images of the cohomology of the summands. In particular it vanishes,
or is a finitely generated `Γ(X, 𝒪_X)`-module, as soon as this holds for each summand.
-/

universe u

open CategoryTheory Limits Opposite TopologicalSpace

namespace AlgebraicGeometry.Scheme.Modules

variable {X : Scheme.{u}} {M N K : X.Modules} {n : ℕ} {U : X.Opens}

lemma Hom.toAbSheaf_add (φ ψ : M ⟶ N) :
    Hom.toAbSheaf (φ + ψ) = Hom.toAbSheaf φ + Hom.toAbSheaf ψ :=
  (SheafOfModules.toSheaf X.ringCatSheaf).map_add

lemma H'.map_add (φ ψ : M ⟶ N) : H'.map (φ + ψ) n U = H'.map φ n U + H'.map ψ n U := by
  ext x
  change Sheaf.H'.map (Hom.toAbSheaf (φ + ψ)) n U x = _
  rw [Hom.toAbSheaf_add, Sheaf.H'.map_add_apply]
  rfl

lemma H'.map_zero : H'.map (0 : M ⟶ N) n U = 0 := by
  ext x
  change Sheaf.H'.map (Hom.toAbSheaf (0 : M ⟶ N)) n U x = 0
  rw [show Hom.toAbSheaf (0 : M ⟶ N) = 0 from (SheafOfModules.toSheaf X.ringCatSheaf).map_zero _ _,
    Sheaf.H'.map_zero_apply]

lemma H'.map_sum {J : Type*} (s : Finset J) (φ : J → (M ⟶ N)) :
    H'.map (∑ j ∈ s, φ j) n U = ∑ j ∈ s, H'.map (φ j) n U := by
  classical
  induction s using Finset.induction_on with
  | empty => simp [H'.map_zero]
  | insert a s ha ih => rw [Finset.sum_insert ha, Finset.sum_insert ha, H'.map_add, ih]

lemma H'.map_id : H'.map (𝟙 M) n U = LinearMap.id := by
  ext x
  change Sheaf.H'.map (Hom.toAbSheaf (𝟙 M)) n U x = x
  rw [show Hom.toAbSheaf (𝟙 M) = 𝟙 _ from (SheafOfModules.toSheaf X.ringCatSheaf).map_id _]
  exact Sheaf.H'.map_id_apply x

lemma H'.map_comp (φ : M ⟶ N) (ψ : N ⟶ K) :
    H'.map (φ ≫ ψ) n U = H'.map ψ n U ∘ₗ H'.map φ n U :=
  LinearMap.ext fun x ↦ H'.map_comp_apply φ ψ x

/-- Isomorphic modules have isomorphic cohomology. -/
noncomputable def H'.mapIso (e : M ≅ N) (n : ℕ) (U : X.Opens) :
    M.H' n U ≃ₗ[Γ(X, ⊤)] N.H' n U :=
  LinearEquiv.ofLinearMap (H'.map e.hom n U) (H'.map e.inv n U)
    (by rw [← H'.map_comp, e.inv_hom_id, H'.map_id])
    (by rw [← H'.map_comp, e.hom_inv_id, H'.map_id])

lemma subsingleton_H'_of_iso (e : M ≅ N) [Subsingleton (M.H' n U)] :
    Subsingleton (N.H' n U) :=
  (H'.mapIso e n U).symm.injective.subsingleton

lemma finite_H'_of_iso (e : M ≅ N) [Module.Finite Γ(X, ⊤) (M.H' n U)] :
    Module.Finite Γ(X, ⊤) (N.H' n U) :=
  Module.Finite.equiv (H'.mapIso e n U)

section Biproduct

variable {J : Type} [Finite J] (G : J → X.Modules)

/-- A class in the cohomology of a finite biproduct is the sum of the images of its
components. -/
lemma H'_biproduct_eq_sum [Fintype J] (x : (⨁ G).H' n U) :
    x = ∑ j, H'.map (biproduct.ι G j) n U (H'.map (biproduct.π G j) n U x) := by
  have h := congrArg (fun φ : ⨁ G ⟶ ⨁ G ↦ H'.map φ n U x) (biproduct.total (f := G))
  simp only [H'.map_id, H'.map_sum, LinearMap.id_apply] at h
  rw [LinearMap.sum_apply] at h
  exact h.symm.trans (Finset.sum_congr rfl fun j _ ↦ H'.map_comp_apply _ _ x)

lemma subsingleton_H'_biproduct (h : ∀ j, Subsingleton ((G j).H' n U)) :
    Subsingleton ((⨁ G).H' n U) := by
  have := Fintype.ofFinite J
  refine ⟨fun x y ↦ ?_⟩
  rw [H'_biproduct_eq_sum G x, H'_biproduct_eq_sum G y]
  exact Finset.sum_congr rfl fun j _ ↦ congrArg _ (Subsingleton.elim _ _)

lemma finite_H'_biproduct (h : ∀ j, Module.Finite Γ(X, ⊤) ((G j).H' n U)) :
    Module.Finite Γ(X, ⊤) ((⨁ G).H' n U) := by
  have := Fintype.ofFinite J
  let f : (∀ j, (G j).H' n U) →ₗ[Γ(X, ⊤)] (⨁ G).H' n U :=
    ∑ j, H'.map (biproduct.ι G j) n U ∘ₗ LinearMap.proj j
  refine Module.Finite.of_surjective f fun x ↦ ⟨fun j ↦ H'.map (biproduct.π G j) n U x, ?_⟩
  conv_rhs => rw [H'_biproduct_eq_sum G x]
  simp [f, LinearMap.sum_apply]

end Biproduct

end AlgebraicGeometry.Scheme.Modules
