/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.Foundations.Cohomology.ProjectiveSpaceTwist
import SGA.Foundations.Cohomology.Twist
import SGA.Foundations.Cohomology.QuasiCoherentLocal

/-!
# Extension of sections and global generation on projective space

Let `X = Proj A[xᵢ : i ∈ σ]` (`σ` finite, non-empty) and `F` a quasi-coherent `𝒪_X`-module. For a
section `s` of `F` over `D₊(xᵢ)`, the section `xᵢⁿ s` of `F(n)` over `D₊(xᵢ)` extends to a global
section of `F(n)` for all `n ≫ 0` (EGA I 9.3.1; Hartshorne II.5.14, Lemma II.5.3.2 of
EGA II 2.7.9). Consequently, if the sections of `F` over each `D₊(xᵢ)` are finitely generated,
`F(n)` is generated by finitely many global sections for `n ≫ 0` (Serre; EGA III 2.2.1 (i) in the
case of projective space, Hartshorne II.5.17).

In terms of the twist `F(n) = (twistingBundle σ A).twist F n`, whose sections over `V` are families
`tⱼ ∈ Γ(V ∩ D₊(xⱼ), F)` with `tⱼ = (xₖ/xⱼ)ⁿ tₖ`, the statement is: there is a global section `t` of
`F(n)` whose `i`-th component is `s`.
-/

universe v u

open CategoryTheory TopologicalSpace Opposite MvPolynomial

namespace AlgebraicGeometry.projectiveSpace

attribute [local instance] MvPolynomial.gradedAlgebra

variable {σ : Type v} {A : Type u} [CommRing A] [Fintype σ] [DecidableEq σ] [Nonempty σ]

section Setup

variable (σ A) in
/-- The open `⊤ ∩ D₊(xⱼ)` over which the `j`-th component of a global section of a twist lives. -/
noncomputable abbrev topStd (j : σ) : (Proj (homogeneousSubmodule σ A)).Opens :=
  ⊤ ⊓ stdCover σ A j

variable (σ A) in
/-- The open `⊤ ∩ (D₊(xⱼ) ∩ D₊(xₖ))`. -/
noncomputable abbrev topStd₂ (j k : σ) : (Proj (homogeneousSubmodule σ A)).Opens :=
  ⊤ ⊓ (stdCover σ A j ⊓ stdCover σ A k)

omit [Fintype σ] [DecidableEq σ] [Nonempty σ] in
lemma isAffineOpen_topStd (j : σ) : IsAffineOpen (topStd σ A j) := by
  change IsAffineOpen (⊤ ⊓ stdCover σ A j)
  rw [top_inf_stdCover]
  exact Proj.isAffineOpen_basicOpen _ _ (prodX_mem _) (Finset.singleton_nonempty j).card_pos

omit [Fintype σ] [DecidableEq σ] [Nonempty σ] in
lemma isAffineOpen_topStd₂ (j k : σ) : IsAffineOpen (topStd₂ σ A j k) := by
  classical
  change IsAffineOpen (⊤ ⊓ (stdCover σ A j ⊓ stdCover σ A k))
  rw [top_inf_stdCover_inf]
  exact Proj.isAffineOpen_basicOpen _ _ (prodX_mem _) (Finset.insert_nonempty j {k}).card_pos

variable (A) in
/-- The section `xᵢ / xⱼ` of `𝒪` over `⊤ ∩ D₊(xⱼ)`. -/
noncomputable def ratio (i j : σ) : Γ(Proj (homogeneousSubmodule σ A), topStd σ A j) :=
  Proj.fracSection _ (X_mem i) (X_mem j) _ inf_le_right

omit [Fintype σ] [DecidableEq σ] [Nonempty σ] in
lemma basicOpen_ratio (i j : σ) :
    (Proj (homogeneousSubmodule σ A)).basicOpen (ratio A i j) =
      topStd σ A j ⊓ Proj.basicOpen _ (X i) :=
  Proj.basicOpen_fracSection _ _ _ _

omit [Fintype σ] [DecidableEq σ] [Nonempty σ] in
lemma ratio_self (j : σ) : ratio A j j = 1 :=
  Proj.fracSection_self _ _ _

omit [Fintype σ] [DecidableEq σ] [Nonempty σ] in
lemma basicOpen_ratio_le (i j : σ) :
    (Proj (homogeneousSubmodule σ A)).basicOpen (ratio A i j) ≤ topStd σ A i := by
  rw [basicOpen_ratio]
  exact le_inf le_top inf_le_right

omit [Fintype σ] [DecidableEq σ] [Nonempty σ] in
/-- The transition function of `𝒪(n)`, `n ≥ 0`, on `D₊(xⱼ) ∩ D₊(xₖ)` is `(xₖ/xⱼ)ⁿ`. -/
lemma transStd_natCast (n : ℕ) (j k : σ) :
    transStd σ A n j k =
      Proj.fracSection _ (X_mem k) (X_mem j) (stdCover σ A j ⊓ stdCover σ A k) inf_le_left ^ n := by
  rw [transStd, Scheme.LineBundle.trans, zpow_natCast, Units.val_pow_eq_pow_val]
  rfl

omit [Fintype σ] [DecidableEq σ] [Nonempty σ] in
/-- On `D₊(xⱼ) ∩ D₊(xₖ)`, `xᵢ/xⱼ = (xₖ/xⱼ)(xᵢ/xₖ)`. -/
lemma map_ratio_eq (i j k : σ) :
    (Proj _).presheaf.map (homOfLE (le_inf le_top (inf_le_right.trans inf_le_left) :
        topStd₂ σ A j k ≤ topStd σ A j)).op (ratio A i j) =
      (Proj _).presheaf.map (homOfLE (inf_le_right :
          topStd₂ σ A j k ≤ stdCover σ A j ⊓ stdCover σ A k)).op
          (Proj.fracSection _ (X_mem k) (X_mem j) (stdCover σ A j ⊓ stdCover σ A k)
            inf_le_left) *
        (Proj _).presheaf.map (homOfLE (le_inf le_top (inf_le_right.trans inf_le_right) :
          topStd₂ σ A j k ≤ topStd σ A k)).op (ratio A i k) := by
  simp only [ratio, Proj.map_fracSection]
  rw [Proj.fracSection_mul]
  exact Proj.fracSection_eq _ _ _ _ _ _ _ (by ring)

end Setup

section Extension

variable (F : (Proj (homogeneousSubmodule σ A)).Modules)

omit [Fintype σ] [DecidableEq σ] [Nonempty σ] in
/-- **Extension of sections** (EGA I 9.3.1; Hartshorne II.5.14): for `F` quasi-coherent on
`Proj A[xᵢ]` and a section `s` of `F` over `D₊(xᵢ)`, for all `n ≫ 0` there is a global section of
`F(n)` whose `i`-th component is `s` (that is, which is `xᵢⁿ s` on `D₊(xᵢ)`). -/
theorem exists_twist_section_eq [Finite σ] [F.IsQuasicoherent] (i : σ) (s : Γ(F, topStd σ A i)) :
    ∃ n₀ : ℕ, ∀ n ≥ n₀, ∃ t : (twistingBundle σ A).twistAddSubgroup F n ⊤,
      t.1 (idx σ A i) = s := by
  classical
  have := Fintype.ofFinite σ
  let X := Proj (homogeneousSubmodule σ A)
  -- Step 1: on each `D₊(xⱼ)`, `(xᵢ/xⱼ)^k s` extends.
  have hstep1 (j : σ) := CohomologyAux.exists_pow_smul_eq_map F (isAffineOpen_topStd j)
    (ratio A i j) (F.presheaf.map (homOfLE (basicOpen_ratio_le i j)).op s)
  choose m k hm using hstep1
  let K := Finset.univ.sup k
  obtain ⟨t0, ht0def⟩ : ∃ t0 : ∀ j, Γ(F, topStd σ A j),
      ∀ j, t0 j = ratio A i j ^ (K - k j) • m j := ⟨_, fun _ ↦ rfl⟩
  have ht0 (j : σ) : F.presheaf.map (homOfLE (X.basicOpen_le (ratio A i j))).op (t0 j) =
      X.presheaf.map (homOfLE (X.basicOpen_le (ratio A i j))).op (ratio A i j ^ K) •
        F.presheaf.map (homOfLE (basicOpen_ratio_le i j)).op s := by
    rw [ht0def, Scheme.Modules.map_smul, ← hm j, smul_smul, ← map_mul, ← pow_add,
      Nat.sub_add_cancel (Finset.le_sup (f := k) (Finset.mem_univ j))]
  -- Step 2: the defect of `t0` on the double intersections vanishes on `D₊(xᵢ)`.
  let hj (j l : σ) : topStd₂ σ A j l ≤ topStd σ A j :=
    le_inf le_top (inf_le_right.trans inf_le_left)
  let hl (j l : σ) : topStd₂ σ A j l ≤ topStd σ A l :=
    le_inf le_top (inf_le_right.trans inf_le_right)
  let hjl (j l : σ) : topStd₂ σ A j l ≤ stdCover σ A j ⊓ stdCover σ A l := inf_le_right
  let c (j l : σ) : Γ(X, topStd₂ σ A j l) := X.presheaf.map (homOfLE (hj j l)).op (ratio A i j)
  let δ (j l : σ) : Γ(F, topStd₂ σ A j l) :=
    F.presheaf.map (homOfLE (hj j l)).op (t0 j) -
      X.presheaf.map (homOfLE (hjl j l)).op (transStd σ A K j l) •
        F.presheaf.map (homOfLE (hl j l)).op (t0 l)
  have hδ (j l : σ) : ∃ N : ℕ, c j l ^ N • δ j l = 0 := by
    refine CohomologyAux.exists_pow_smul_eq_zero F (isAffineOpen_topStd₂ j l) (c j l) (δ j l) ?_
    have hB : X.basicOpen (c j l) = topStd₂ σ A j l ⊓ X.basicOpen (ratio A i j) :=
      Scheme.basicOpen_res _ _ _
    have hBj : X.basicOpen (c j l) ≤ X.basicOpen (ratio A i j) := hB.le.trans inf_le_right
    have hBl : X.basicOpen (c j l) ≤ X.basicOpen (ratio A i l) := by
      rw [hB, basicOpen_ratio, basicOpen_ratio]
      exact le_inf ((inf_le_left.trans (hl j l))) (inf_le_right.trans inf_le_right)
    have e1 : F.presheaf.map (homOfLE (X.basicOpen_le (c j l))).op
        (F.presheaf.map (homOfLE (hj j l)).op (t0 j)) =
        X.presheaf.map (homOfLE (hBj.trans (X.basicOpen_le _))).op (ratio A i j ^ K) •
          F.presheaf.map (homOfLE (hBj.trans (basicOpen_ratio_le i j))).op s := by
      rw [TopCat.Presheaf.map_map_apply,
        ← TopCat.Presheaf.map_map_apply F.presheaf (X.basicOpen_le (ratio A i j)) hBj, ht0,
        Scheme.Modules.map_smul, CohomologyAux.presheaf_map_map, TopCat.Presheaf.map_map_apply]
    have e2 : F.presheaf.map (homOfLE (X.basicOpen_le (c j l))).op
        (F.presheaf.map (homOfLE (hl j l)).op (t0 l)) =
        X.presheaf.map (homOfLE (hBl.trans (X.basicOpen_le _))).op (ratio A i l ^ K) •
          F.presheaf.map (homOfLE (hBj.trans (basicOpen_ratio_le i j))).op s := by
      rw [TopCat.Presheaf.map_map_apply,
        ← TopCat.Presheaf.map_map_apply F.presheaf (X.basicOpen_le (ratio A i l)) hBl, ht0,
        Scheme.Modules.map_smul, CohomologyAux.presheaf_map_map, TopCat.Presheaf.map_map_apply]
    have e3 : X.presheaf.map (homOfLE ((X.basicOpen_le (c j l)).trans (hjl j l))).op
        (transStd σ A K j l) *
        X.presheaf.map (homOfLE (hBl.trans (X.basicOpen_le _))).op (ratio A i l ^ K) =
        X.presheaf.map (homOfLE (hBj.trans (X.basicOpen_le _))).op (ratio A i j ^ K) := by
      have := congrArg (fun r ↦ X.presheaf.map (homOfLE (X.basicOpen_le (c j l))).op (r ^ K))
        (map_ratio_eq (A := A) i j l)
      simp only [mul_pow, map_mul, map_pow] at this
      rw [transStd_natCast, map_pow, map_pow, map_pow]
      exact this.symm
    change F.presheaf.map _ (F.presheaf.map _ (t0 j) -
      X.presheaf.map _ (transStd σ A K j l) • F.presheaf.map _ (t0 l)) = 0
    rw [map_sub, Scheme.Modules.map_smul, e1, e2, smul_smul, CohomologyAux.presheaf_map_map, e3,
      sub_self]
  choose N hN using hδ
  let Nmax := (Finset.univ : Finset (σ × σ)).sup fun p ↦ N p.1 p.2
  refine ⟨K + Nmax, fun n hn ↦ ?_⟩
  obtain ⟨N', rfl⟩ : ∃ N', n = K + N' := ⟨n - K, by omega⟩
  have hN' (j l : σ) : N j l ≤ N' :=
    (Finset.le_sup (f := fun p : σ × σ ↦ N p.1 p.2) (Finset.mem_univ (j, l))).trans (by omega)
  obtain ⟨t, htdef⟩ : ∃ t : ∀ j, Γ(F, topStd σ A j), ∀ j, t j = ratio A i j ^ N' • t0 j :=
    ⟨_, fun _ ↦ rfl⟩
  refine ⟨⟨fun j ↦ t j.down, fun j l ↦ ?_⟩, ?_⟩
  · obtain ⟨j, rfl⟩ := idx_surjective (A := A) j
    obtain ⟨l, rfl⟩ := idx_surjective (A := A) l
    change F.presheaf.map (homOfLE (hj j l)).op (t j) =
      X.presheaf.map (homOfLE (hjl j l)).op (transStd σ A ((K + N' : ℕ) : ℤ) j l) •
        F.presheaf.map (homOfLE (hl j l)).op (t l)
    have hv := map_ratio_eq (A := A) i j l
    rw [← sub_eq_zero]
    have key : F.presheaf.map (homOfLE (hj j l)).op (t j) -
        X.presheaf.map (homOfLE (hjl j l)).op (transStd σ A ((K + N' : ℕ) : ℤ) j l) •
          F.presheaf.map (homOfLE (hl j l)).op (t l) = c j l ^ N' • δ j l := by
      simp only [htdef, δ, c, Scheme.Modules.map_smul, smul_sub, smul_smul, map_pow]
      rw [transStd_natCast, transStd_natCast, pow_add, map_mul, map_pow, map_pow, mul_assoc,
        ← mul_pow, ← hv]
      congr 2
      ring
    rw [key, ← Nat.sub_add_cancel (hN' j l), pow_add, mul_smul, hN j l, smul_zero]
  · change t i = s
    rw [htdef]
    have e : ratio A i i = 1 := ratio_self i
    have hmi := hm i
    have hk : ratio A i i ^ k i = 1 := by rw [e, one_pow]
    rw [hk, map_one, one_smul] at hmi
    have hB : X.basicOpen (ratio A i i) = topStd σ A i := by
      rw [basicOpen_ratio]
      exact inf_eq_left.mpr (inf_le_right)
    have hs : m i = s := CohomologyAux.modules_map_injective_of_eq F hB (hmi.symm.trans rfl)
    rw [ht0def, e, one_pow, one_pow, one_smul, one_smul, hs]

omit [Fintype σ] [DecidableEq σ] [Nonempty σ] in
/-- The `i`-th trivialization of the restriction to `D₊(xᵢ)` of a global section of a twist is its
`i`-th component. -/
lemma twistToModule_restrict_top {n : ℤ} (i : σ)
    (t : (twistingBundle σ A).twistAddSubgroup F n ⊤) :
    (twistingBundle σ A).twistToModule (idx σ A i) (inf_le_right : topStd σ A i ≤ stdCover σ A i)
      ((twistingBundle σ A).twistResHom F n le_top t) = t.1 (idx σ A i) := by
  change F.presheaf.map _ (F.presheaf.map _ (t.1 (idx σ A i))) = _
  rw [TopCat.Presheaf.map_map_apply]
  exact CohomologyAux.modules_map_self F _ _

omit [Fintype σ] [DecidableEq σ] [Nonempty σ] in
/-- **Global generation** (Hartshorne II.5.17; EGA III 2.2.1 for projective space): if the
sections of a quasi-coherent `F` over each `D₊(xᵢ)` are finitely generated, then for `n ≫ 0`
finitely many global sections of `F(n)` generate its sections over each `D₊(xᵢ)`. -/
theorem exists_generating_twist_sections [Finite σ] [F.IsQuasicoherent]
    (hF : ∀ i, Module.Finite Γ(Proj (homogeneousSubmodule σ A), topStd σ A i)
      Γ(F, topStd σ A i)) :
    ∃ n₀ : ℕ, ∀ n ≥ n₀, ∃ (J : Type (max u v)) (_ : Fintype J)
      (g : J → Γ((twistingBundle σ A).twist F n, ⊤)), ∀ i,
        Submodule.span Γ(Proj (homogeneousSubmodule σ A), topStd σ A i)
          (Set.range fun j ↦ ((twistingBundle σ A).twist F n).presheaf.map
            (homOfLE le_top : topStd σ A i ⟶ ⊤).op (g j)) = ⊤ := by
  classical
  have := Fintype.ofFinite σ
  choose S hS using fun i ↦ (hF i).fg_top
  have hext (i : σ) (s : Γ(F, topStd σ A i)) := exists_twist_section_eq F i s
  choose n₀ hn₀ using hext
  let N : ℕ := Finset.univ.sup fun i ↦ (S i).sup fun s ↦ n₀ i s
  refine ⟨N, fun n hn ↦ ?_⟩
  have hle (i : σ) (s : Γ(F, topStd σ A i)) (hs : s ∈ S i) : n₀ i s ≤ n :=
    ((Finset.le_sup (f := fun s ↦ n₀ i s) hs).trans
      (Finset.le_sup (f := fun i ↦ (S i).sup fun s ↦ n₀ i s) (Finset.mem_univ i))).trans hn
  let J := Σ i : σ, (S i : Set Γ(F, topStd σ A i))
  have hJ (p : J) := hn₀ p.1 p.2.1 n (hle p.1 p.2.1 p.2.2)
  choose t ht using hJ
  refine ⟨ULift.{max u v} J, inferInstance, fun p ↦ t p.down, fun i ↦ ?_⟩
  let L := twistingBundle σ A
  let e := L.twistEquiv (M := F) (n := n) (idx σ A i) (inf_le_right : topStd σ A i ≤ L.U _)
  rw [eq_top_iff]
  rintro m' -
  have hsub : (S i : Set Γ(F, topStd σ A i)) ⊆ e '' Set.range fun p : ULift.{max u v} J ↦
      (L.twist F n).presheaf.map (homOfLE le_top : topStd σ A i ⟶ ⊤).op (t p.down) := by
    intro s hs
    refine ⟨_, ⟨ULift.up ⟨i, s, hs⟩, rfl⟩, ?_⟩
    change L.twistToModule (idx σ A i) (inf_le_right : topStd σ A i ≤ stdCover σ A i)
      (L.twistResHom F n le_top (t ⟨i, s, hs⟩)) = s
    rw [twistToModule_restrict_top, ht]
  have hm0 : e m' ∈ Submodule.span Γ(Proj (homogeneousSubmodule σ A), topStd σ A i)
      (S i : Set Γ(F, topStd σ A i)) := by
    rw [hS i]
    exact Submodule.mem_top
  have hm := Submodule.span_mono hsub hm0
  have key : ∀ x ∈ Submodule.span Γ(Proj (homogeneousSubmodule σ A), topStd σ A i)
      (e '' Set.range fun p : ULift.{max u v} J ↦ (L.twist F n).presheaf.map
        (homOfLE le_top : topStd σ A i ⟶ ⊤).op (t p.down)),
      e.symm x ∈ Submodule.span Γ(Proj (homogeneousSubmodule σ A), topStd σ A i)
        (Set.range fun p : ULift.{max u v} J ↦ (L.twist F n).presheaf.map
          (homOfLE le_top : topStd σ A i ⟶ ⊤).op (t p.down)) := by
    intro x hx
    induction hx using Submodule.span_induction with
    | mem x hx =>
      obtain ⟨y, hy, rfl⟩ := hx
      rw [e.symm_apply_apply]
      exact Submodule.subset_span hy
    | zero => rw [map_zero]; exact zero_mem _
    | add x y _ _ hx hy => rw [map_add]; exact add_mem hx hy
    | smul r x _ hx => rw [LinearEquiv.map_smul]; exact Submodule.smul_mem _ r hx
  have := key _ hm
  have e2 : e.symm (e m') = m' := e.symm_apply_apply m'
  exact e2 ▸ this

end Extension

end AlgebraicGeometry.projectiveSpace
