/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.Foundations.Cohomology.RelativeArtinRees

/-!
# Base change of formal étale coverings and flat base change of kernels and images

* `thickeningMap`, `formalPullback`: the pullback `(Yₙ ×_{Xₙ} X'ₙ)ₙ` of an étale covering of the
  formal completion of `X` along a morphism `X' ⟶ X` over `Spec A`, and the compatibility of its
  transitions with those of `(Yₙ)` (`formalPullback_transition_fst`);
* `mem_map_ker_of_isPushout`, `mem_map_inf_ker_of_isPushout`: in a pushout square of rings with
  one side flat, kernels are generated by the kernels on the other side (flat base change preserves
  kernels);
* `range_subset_of_isPushout`: images of transition maps between pushouts are controlled by the
  images on one side.
-/

universe u

open CategoryTheory Limits TopologicalSpace Opposite TensorProduct

noncomputable section

namespace AlgebraicGeometry.CohomologyAux

section FlatKernel

variable {R S : Type u} [CommRing R] [CommRing S] [Algebra R S] [Module.Flat R S]

/-- For `S` flat over `R` and `φ : R → T` linear, an element `y ∈ S` with `φ 1 ⊗ y = 0` in
`T ⊗_R S` lies in `(ker φ) S`. -/
lemma mem_smul_top_of_tmul_eq_zero {T : Type u} [AddCommGroup T] [Module R T] (φ : R →ₗ[R] T)
    {y : S} (hy : φ 1 ⊗ₜ[R] y = 0) :
    y ∈ ((LinearMap.ker φ : Submodule R R) • ⊤ : Submodule R S) := by
  have hex := Module.Flat.rTensor_exact S (LinearMap.exact_subtype_ker_map φ)
  have h1 : φ.rTensor S (1 ⊗ₜ y) = 0 := by simpa using hy
  obtain ⟨z, hz⟩ := (hex _).mp h1
  have hy' : y = TensorProduct.lid R S ((LinearMap.ker φ).subtype.rTensor S z) := by
    rw [hz, TensorProduct.lid_tmul, one_smul]
  have key : ∀ w : LinearMap.ker φ ⊗[R] S,
      TensorProduct.lid R S ((LinearMap.ker φ).subtype.rTensor S w) ∈
        ((LinearMap.ker φ : Submodule R R) • ⊤ : Submodule R S) := by
    intro w
    induction w using TensorProduct.induction_on with
    | zero => simp
    | tmul k s =>
      rw [LinearMap.rTensor_tmul, TensorProduct.lid_tmul]
      exact Submodule.smul_mem_smul k.2 Submodule.mem_top
    | add a b ha hb =>
      rw [map_add, map_add]
      exact Submodule.add_mem _ ha hb
  rw [hy']
  exact key z

end FlatKernel

section Pushout

set_option backward.isDefEq.respectTransparency false in
/-- **Kernels under flat base change** (ring form): in a pushout square of commutative rings
`R → A`, `R → B`, `A → X`, `B → X` with `B` flat over `R`, the kernel of `B → X` is generated by
the kernel of `R → A`. -/
lemma mem_map_ker_of_isPushout {R A B X : CommRingCat.{u}} {f : R ⟶ A} {g : R ⟶ B}
    {a : A ⟶ X} {b : B ⟶ X} (H : IsPushout f g a b) (hg : g.hom.Flat) {y : B}
    (hy : b y = 0) : y ∈ (RingHom.ker f.hom).map g.hom := by
  algebraize [f.hom, g.hom]
  let e := (CommRingCat.isPushout_tensorProduct R A B).isoIsPushout A B H
  have he : b = CommRingCat.ofHom (S := A ⊗[R] B) Algebra.TensorProduct.includeRight.toRingHom ≫
      e.hom := ((CommRingCat.isPushout_tensorProduct R A B).inr_isoIsPushout_hom A B H).symm
  have h1 : (1 : A) ⊗ₜ[R] (y : B) = 0 := by
    have h2 : e.hom ((1 : A) ⊗ₜ[R] (y : B)) = 0 := by
      rw [← hy, he]
      rfl
    have h3 := congrArg e.inv h2
    rwa [← CommRingCat.comp_apply, Iso.hom_inv_id, CommRingCat.id_apply, map_zero] at h3
  have h4 := mem_smul_top_of_tmul_eq_zero (S := B) (Algebra.linearMap R A)
    (y := y) (by simpa using h1)
  rw [Ideal.smul_top_eq_map] at h4
  have hker : (LinearMap.ker (Algebra.linearMap R A) : Submodule R R) = RingHom.ker f.hom := by
    ext r
    simp [RingHom.algebraMap_toAlgebra]
  rw [hker] at h4
  exact h4

set_option backward.isDefEq.respectTransparency false in
/-- The product form of `mem_map_ker_of_isPushout`: for two pushout squares with the same flat
`R → B`, an element of `B` vanishing in both pushouts lies in the ideal generated by the
intersection of the kernels. -/
lemma mem_map_inf_ker_of_isPushout {R A₁ A₂ B X₁ X₂ : CommRingCat.{u}} {f₁ : R ⟶ A₁}
    {f₂ : R ⟶ A₂} {g : R ⟶ B} {a₁ : A₁ ⟶ X₁} {b₁ : B ⟶ X₁} {a₂ : A₂ ⟶ X₂} {b₂ : B ⟶ X₂}
    (H₁ : IsPushout f₁ g a₁ b₁) (H₂ : IsPushout f₂ g a₂ b₂) (hg : g.hom.Flat) {y : B}
    (hy₁ : b₁ y = 0) (hy₂ : b₂ y = 0) :
    y ∈ (RingHom.ker f₁.hom ⊓ RingHom.ker f₂.hom).map g.hom := by
  algebraize [f₁.hom, f₂.hom, g.hom]
  have h₁ : (1 : A₁) ⊗ₜ[R] (y : B) = 0 := by
    let e := (CommRingCat.isPushout_tensorProduct R A₁ B).isoIsPushout A₁ B H₁
    have he : b₁ = CommRingCat.ofHom (S := A₁ ⊗[R] B)
        Algebra.TensorProduct.includeRight.toRingHom ≫ e.hom :=
      ((CommRingCat.isPushout_tensorProduct R A₁ B).inr_isoIsPushout_hom A₁ B H₁).symm
    have h2 : e.hom ((1 : A₁) ⊗ₜ[R] (y : B)) = 0 := by
      rw [← hy₁, he]
      rfl
    have h3 := congrArg e.inv h2
    rwa [← CommRingCat.comp_apply, Iso.hom_inv_id, CommRingCat.id_apply, map_zero] at h3
  have h₂ : (1 : A₂) ⊗ₜ[R] (y : B) = 0 := by
    let e := (CommRingCat.isPushout_tensorProduct R A₂ B).isoIsPushout A₂ B H₂
    have he : b₂ = CommRingCat.ofHom (S := A₂ ⊗[R] B)
        Algebra.TensorProduct.includeRight.toRingHom ≫ e.hom :=
      ((CommRingCat.isPushout_tensorProduct R A₂ B).inr_isoIsPushout_hom A₂ B H₂).symm
    have h2 : e.hom ((1 : A₂) ⊗ₜ[R] (y : B)) = 0 := by
      rw [← hy₂, he]
      rfl
    have h3 := congrArg e.inv h2
    rwa [← CommRingCat.comp_apply, Iso.hom_inv_id, CommRingCat.id_apply, map_zero] at h3
  let φ : R →ₗ[R] A₁ × A₂ := (Algebra.linearMap R A₁).prod (Algebra.linearMap R A₂)
  have hφ : φ 1 ⊗ₜ[R] (y : B) = 0 := by
    apply (TensorProduct.prodLeft R R A₁ A₂ B).injective
    rw [map_zero, TensorProduct.prodLeft_tmul]
    simp [φ, h₁, h₂]
  have h4 := mem_smul_top_of_tmul_eq_zero (S := B) φ hφ
  rw [Ideal.smul_top_eq_map] at h4
  have hker : (LinearMap.ker φ : Submodule R R) = RingHom.ker f₁.hom ⊓ RingHom.ker f₂.hom := by
    ext r
    simp [φ, RingHom.algebraMap_toAlgebra]
  rw [hker] at h4
  exact h4

/-- **Images under base change**: given a pushout square `R' → A'`, `R' → B'`, `A' → X'`,
`B' → X'`, a commutative square `R → A`, `R → B`, `A → X`, `B → X` and a map `X' → X` compatible
with `A' → A` and `B' → B`, if the image of `A' → A` lies in that of `R → A`, then the image of
`X' → X` lies in that of `B → X`. -/
lemma range_subset_of_isPushout {R' A' B' X' R A B X : CommRingCat.{u}} {f' : R' ⟶ A'}
    {g' : R' ⟶ B'} {a' : A' ⟶ X'} {b' : B' ⟶ X'} (H' : IsPushout f' g' a' b') {f : R ⟶ A}
    {g : R ⟶ B} {a : A ⟶ X} {b : B ⟶ X} (hsq : f ≫ a = g ≫ b) (φ : X' ⟶ X) (τ : A' ⟶ A)
    (σ : B' ⟶ B) (hτ : a' ≫ φ = τ ≫ a) (hσ : b' ≫ φ = σ ≫ b)
    (hrange : Set.range τ ⊆ Set.range f) : Set.range φ ⊆ Set.range b := by
  have hcl := CommRingCat.closure_range_union_range_eq_top_of_isPushout H'
  have hle : (Subring.closure (Set.range a' ∪ Set.range b')).map φ.hom ≤ b.hom.range := by
    rw [RingHom.map_closure]
    refine Subring.closure_le.mpr ?_
    rintro _ ⟨z, (⟨t, rfl⟩ | ⟨s, rfl⟩), rfl⟩
    · obtain ⟨r, hr⟩ := hrange ⟨t, rfl⟩
      refine ⟨g r, ?_⟩
      change (g ≫ b) r = (a' ≫ φ) t
      rw [← hsq, hτ, CommRingCat.comp_apply, CommRingCat.comp_apply, ← hr]
    · refine ⟨σ s, ?_⟩
      change (σ ≫ b) s = (b' ≫ φ) s
      rw [hσ]
  rintro _ ⟨x, rfl⟩
  have hx : x ∈ Subring.closure (Set.range a' ∪ Set.range b') := by
    rw [hcl]
    trivial
  exact hle ⟨x, hx, rfl⟩

end Pushout


open Scheme (FiniteEtale FormalFiniteEtale)

section FormalPullback

variable {A : CommRingCat.{u}} (I : Ideal A) {X X' : Scheme.{u}} (f : X ⟶ Spec A) (p : X' ⟶ X)

/-- The morphism of thickenings `X'_n ⟶ X_n` induced by `p : X' ⟶ X` over `Spec A`. -/
def thickeningMap (n : ℕ) : thickening (p ≫ f) I n ⟶ thickening f I n :=
  pullback.map _ _ _ _ p (𝟙 _) (𝟙 _) (by simp) (by simp)

@[reassoc (attr := simp)]
lemma thickeningMap_ι (n : ℕ) :
    thickeningMap I f p n ≫ thickening.ι f I n = thickening.ι (p ≫ f) I n ≫ p :=
  pullback.lift_fst _ _ _

set_option backward.isDefEq.respectTransparency false in
lemma thickeningMap_transition (n : ℕ) :
    thickening.transition (p ≫ f) I n ≫ thickeningMap I f p (n + 1) =
      thickeningMap I f p n ≫ thickening.transition f I n := by
  apply pullback.hom_ext <;> simp only [thickeningMap, thickening.transition, pullback.map,
    Category.assoc, pullback.lift_fst, pullback.lift_snd, pullback.lift_fst_assoc,
    pullback.lift_snd_assoc, Category.comp_id]

lemma thickeningDiagram_map_thickeningMap (n : ℕ) :
    (thickeningDiagram I (p ≫ f)).map (homOfLE n.le_succ) ≫ thickeningMap I f p (n + 1) =
      thickeningMap I f p n ≫ (thickeningDiagram I f).map (homOfLE n.le_succ) := by
  rw [thickeningDiagram_map, thickeningDiagram_map]
  exact thickeningMap_transition I f p n

end FormalPullback

section TowerPullback

/-- The comparison isomorphism `(Y₁ ×_{S₁} T₁) ×_{T₁} T₀ ≅ Y₀ ×_{S₀} T₀` for a commutative square
`a ≫ b = c ≫ d` and `Y₁ ×_{S₁} S₀ ≅ Y₀`. -/
def pullbackSquareIso {S₀ S₁ T₀ T₁ : Scheme.{u}} (a : T₀ ⟶ T₁) (b : T₁ ⟶ S₁) (c : T₀ ⟶ S₀)
    (d : S₀ ⟶ S₁) (h : a ≫ b = c ≫ d) (Y₁ : S₁.FiniteEtale) (Y₀ : S₀.FiniteEtale)
    (φ : (FiniteEtale.pullback d).obj Y₁ ≅ Y₀) :
    (FiniteEtale.pullback a).obj ((FiniteEtale.pullback b).obj Y₁) ≅
      (FiniteEtale.pullback c).obj Y₀ :=
  ((MorphismProperty.Over.pullbackComp (P := Scheme.finiteEtaleHom.{u}) (Q := ⊤) a b).app
      Y₁).symm ≪≫
    (MorphismProperty.Over.pullbackComp (P := Scheme.finiteEtaleHom.{u}) (Q := ⊤) c d _ h).app
      Y₁ ≪≫ (FiniteEtale.pullback c).mapIso φ

set_option backward.isDefEq.respectTransparency false in
set_option backward.defeqAttrib.useBackward true in
lemma pullbackSquareIso_inv_left_fst {S₀ S₁ T₀ T₁ : Scheme.{u}} (a : T₀ ⟶ T₁) (b : T₁ ⟶ S₁)
    (c : T₀ ⟶ S₀) (d : S₀ ⟶ S₁) (h : a ≫ b = c ≫ d) (Y₁ : S₁.FiniteEtale)
    (Y₀ : S₀.FiniteEtale) (φ : (FiniteEtale.pullback d).obj Y₁ ≅ Y₀) :
    (pullbackSquareIso a b c d h Y₁ Y₀ φ).inv.left ≫ pullback.fst _ a ≫
        pullback.fst Y₁.hom b =
      pullback.fst Y₀.hom c ≫ φ.inv.left ≫ pullback.fst Y₁.hom d := by
  simp [pullbackSquareIso]

end TowerPullback

section FormalPullback

variable {A : CommRingCat.{u}} (I : Ideal A) {X X' : Scheme.{u}} (f : X ⟶ Spec A) (p : X' ⟶ X)

/-- **The pullback of an étale covering of the formal completion** along `p : X' ⟶ X` over
`Spec A`: `(Yₙ ×_{Xₙ} X'ₙ)ₙ`. -/
def formalPullback (𝒴 : FormalFiniteEtale (thickeningDiagram I f)) :
    FormalFiniteEtale (thickeningDiagram I (p ≫ f)) where
  obj n := (FiniteEtale.pullback (thickeningMap I f p n)).obj (𝒴.obj n)
  iso n := pullbackSquareIso _ _ _ _ (thickeningDiagram_map_thickeningMap I f p n)
    (𝒴.obj (n + 1)) (𝒴.obj n) (𝒴.iso n)

lemma formalPullback_transition_fst (𝒴 : FormalFiniteEtale (thickeningDiagram I f)) (n : ℕ) :
    (formalPullback I f p 𝒴).transition n ≫
        pullback.fst (𝒴.obj (n + 1)).hom (thickeningMap I f p (n + 1)) =
      pullback.fst (𝒴.obj n).hom (thickeningMap I f p n) ≫ 𝒴.transition n := by
  have h := pullbackSquareIso_inv_left_fst _ _ _ _ (thickeningDiagram_map_thickeningMap I f p n)
    (𝒴.obj (n + 1)) (𝒴.obj n) (𝒴.iso n)
  exact (Category.assoc _ _ _).trans h

end FormalPullback

end AlgebraicGeometry.CohomologyAux
