/-
Copyright (c) 2026 SGAenglishpluslean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SGAenglishpluslean contributors
-/
import Mathlib.RingTheory.ReesAlgebra
import Mathlib.RingTheory.Noetherian.Basic
import Mathlib.RingTheory.Finiteness.Defs
import Mathlib.LinearAlgebra.Finsupp.LinearCombination

/-!
# A bound for finite modules over the Rees algebra

The algebraic core of the theorem on formal functions (EGA III 4.1.5; EGA 0_III 13.7.7): let `H`
be a finitely generated module over the Rees algebra `B = ⊕ Iᵏ tᵏ ⊆ A[t]` of a noetherian ring,
equipped with "coefficient maps" `πₘ : H → Gₘ` for which every element has bounded support and
multiplication by `a tᵏ` shifts coefficients. Then the coefficients in degree `n + c` of any
submodule are generated by elements of `Iⁿ` times coefficients in degrees `≤ c`
(`CohomologyAux.exists_rees_bound`). In the application `H = ⊕ₘ H^q(X, Iᵐ M)` and this yields the
Artin–Rees type statements for the filtrations of `H^q(X, M)` and of the kernels
`ker(H^q(X, Iᵐ M) → H^q(X, M))`.
-/

universe w

open Polynomial

namespace AlgebraicGeometry.CohomologyAux

variable {A : Type*} [CommRing A] (I : Ideal A)

/-- Every element of the Rees algebra is the sum of its monomials `a tᵏ`, `a ∈ Iᵏ`. -/
lemma reesAlgebra_eq_sum_monomial (b : reesAlgebra I) :
    b = ∑ k ∈ (b : A[X]).support, (⟨monomial k ((b : A[X]).coeff k),
      reesAlgebra.monomial_mem.mpr ((mem_reesAlgebra_iff I _).mp b.2 k)⟩ : reesAlgebra I) := by
  apply Subtype.ext
  rw [AddSubmonoidClass.coe_finsetSum]
  exact (b : A[X]).as_sum_support

variable {H : Type*} [AddCommGroup H] [Module (reesAlgebra I) H]
  {G : ℕ → Type*} [∀ m, AddCommGroup (G m)]

/-- **The Artin–Rees type bound for a finite module over the Rees algebra** (EGA III 4.1.5, proof;
EGA 0_III 13.7.7). Let `H` be a finitely generated module over the Rees algebra `B = ⊕ Iᵏ tᵏ`
(noetherian), with additive "coefficient maps" `πₘ : H → Gₘ` such that every element has bounded
support, and such that multiplication by `a tᵏ` shifts coefficients by `k` via maps
`μ_a : Gⱼ → Gⱼ₊ₖ`. Then for every subset `S ⊆ H` there is `c` such that for all `n`, the
coefficient of degree `n + c` of any element of the submodule spanned by `S` is a sum of terms
`μ_a(π_j g)` with `g ∈ S`, `j ≤ c` and `a ∈ Iᵏ`, `k ≥ n`: precisely, it is killed by every family
of additive maps `Φₘ` killing all those terms. -/
theorem exists_rees_bound [IsNoetherianRing (reesAlgebra I)] [Module.Finite (reesAlgebra I) H]
    (π : ∀ m, H →+ G m) (μ : ∀ (j : ℕ) {k : ℕ} {a : A}, a ∈ I ^ k → G j →+ G (j + k))
    (hsupp : ∀ g, ∃ N, ∀ m, N < m → π m g = 0)
    (hmul : ∀ {k : ℕ} {a : A} (ha : a ∈ I ^ k) (b : reesAlgebra I), (b : A[X]) = monomial k a →
      ∀ j g, π (j + k) (b • g) = μ j ha (π j g))
    (hlt : ∀ {k : ℕ} {a : A} (b : reesAlgebra I), (b : A[X]) = monomial k a →
      ∀ m, m < k → ∀ g, π m (b • g) = 0)
    (S : Set H) :
    ∃ c, ∀ (n : ℕ) {T : Type w} [AddCommGroup T] (Φ : ∀ m, G m →+ T),
      (∀ (j k : ℕ) (a : A) (ha : a ∈ I ^ k), j + k = n + c → n ≤ k → ∀ g ∈ S,
        Φ (j + k) (μ j ha (π j g)) = 0) →
      ∀ s ∈ Submodule.span (reesAlgebra I) S, Φ (n + c) (π (n + c) s) = 0 := by
  classical
  have : IsNoetherian (reesAlgebra I) H := isNoetherian_of_isNoetherianRing_of_finite _ _
  obtain ⟨t, hts, hspan⟩ :=
    (Submodule.fg_span_iff_fg_span_finset_subset S).mp
      (IsNoetherian.noetherian (R := reesAlgebra I) (Submodule.span (reesAlgebra I) S))
  choose N hN using hsupp
  refine ⟨t.sup N, fun n T _ Φ hΦ s hs ↦ ?_⟩
  rw [hspan] at hs
  obtain ⟨v, -, rfl⟩ := Submodule.mem_span_finset.mp hs
  rw [map_sum, map_sum]
  refine Finset.sum_eq_zero fun g hg ↦ ?_
  rw [reesAlgebra_eq_sum_monomial I (v g), Finset.sum_smul, map_sum, map_sum]
  refine Finset.sum_eq_zero fun k _ ↦ ?_
  have ha : ((v g : A[X]).coeff k) ∈ I ^ k := (mem_reesAlgebra_iff I _).mp (v g).2 k
  generalize hm : n + t.sup N = m
  by_cases hkm : m < k
  · rw [hlt _ rfl m hkm, map_zero]
  · obtain ⟨j, rfl⟩ : ∃ j, m = j + k := ⟨m - k, by omega⟩
    rw [hmul ha _ rfl j g]
    by_cases hj : N g < j
    · rw [hN g j hj, map_zero, map_zero]
    · have := Finset.le_sup (f := N) hg
      exact hΦ j k _ ha hm.symm (by omega) g (hts hg)

end AlgebraicGeometry.CohomologyAux
