/-
Copyright (c) 2026 SGAenglishpluslean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SGAenglishpluslean contributors
-/
import SGA.Foundations.Cohomology.RelativeSpecUniversal
import SGA.Foundations.Cohomology.Thickening

/-!
# Functoriality of the direct image algebra and affine base change

For a morphism `h : Z ⟶ Z'` of `X`-schemes (`h ≫ g' = g`):

* `pushforwardUnitMap h hg : g'_* 𝒪_{Z'} ⟶ g_* 𝒪_Z`, the algebra morphism given on sections by
  `h.appLE` (`pushforwardUnitMap_app`, `pushforwardUnitMap_pfMul`, `pushforwardUnitMap_one`,
  `pushforwardUnitMap_comp`, `pushforwardUnitMap_id`);
* `comp_toRelativeSpec`: naturality of `toRelativeSpec`,
  `h ≫ toRelativeSpec ψ = toRelativeSpec (ψ ≫ h^♯)`;
* `isIso_of_bijective_appLE`: a morphism of affine `X`-schemes which is bijective on the rings of
  sections over inverse images of affine opens is an isomorphism (EGA II 1.2.7);
* `toRelativeSpec_appLE`: on sections over `p⁻¹ U`, `U` affine, `toRelativeSpec φ` is `φ`.

Affine base change (EGA I 3.2.2):

* `ker_inl_of_isPushout_surjective`: in a pushout of rings along a surjection `A → C`, the map
  `B → P` is surjective with kernel `ker(A → C) B`;
* `app_surjective_ker_of_isPullback`: for `P = Y ×_X X'` and `X' ⟶ X` surjective on sections over
  an affine `U` (e.g. a closed immersion), `Γ(Y, p⁻¹ U) → Γ(P, j⁻¹ p⁻¹ U)` is surjective with
  kernel generated by the ideal of `X'` in `U`;
* `mem_smul_top_pushforwardUnit_iff`: `J • Γ(g_* 𝒪_Z, U)` is the ideal generated by `J`.
-/

universe u

open CategoryTheory Limits TopologicalSpace Opposite

noncomputable section

namespace AlgebraicGeometry.CohomologyAux

open Scheme.Modules

section PushforwardUnitMap

variable {X Z Z' : Scheme.{u}} {g : Z ⟶ X} {g' : Z' ⟶ X} (h : Z ⟶ Z') (hg : h ≫ g' = g)

include hg in
lemma preimage_le_preimage_of_comp_eq (U : X.Opens) : g ⁻¹ᵁ U ≤ h ⁻¹ᵁ (g' ⁻¹ᵁ U) := by
  subst hg
  exact le_of_eq (Scheme.Hom.comp_preimage _ _ _)

include hg in
lemma appLE_app_of_comp_eq (U : X.Opens) (r : Γ(X, U)) :
    h.appLE (g' ⁻¹ᵁ U) (g ⁻¹ᵁ U) (preimage_le_preimage_of_comp_eq h hg U) (g'.app U r) =
      g.app U r := by
  subst hg
  rw [Scheme.Hom.app_eq_appLE, Scheme.Hom.app_eq_appLE, ← CommRingCat.comp_apply,
    Scheme.Hom.appLE_comp_appLE]

/-- The algebra morphism `g'_* 𝒪_{Z'} ⟶ g_* 𝒪_Z` of a morphism `h : Z ⟶ Z'` of `X`-schemes. -/
def pushforwardUnitMap : pushforwardUnit g' ⟶ pushforwardUnit g :=
  ⟨_root_.PresheafOfModules.homMk
    { app U := AddCommGrpCat.ofHom (h.appLE (g' ⁻¹ᵁ U.unop) (g ⁻¹ᵁ U.unop)
        (preimage_le_preimage_of_comp_eq h hg U.unop)).hom.toAddMonoidHom
      naturality U V i := by
        ext (x : Γ(Z', g' ⁻¹ᵁ U.unop))
        change h.appLE (g' ⁻¹ᵁ V.unop) (g ⁻¹ᵁ V.unop) _
            (Z'.presheaf.map (homOfLE (g'.preimage_mono i.unop.le)).op x) =
          Z.presheaf.map (homOfLE (g.preimage_mono i.unop.le)).op (h.appLE _ _ _ x)
        rw [appLE_presheaf_map_apply', presheaf_map_appLE_apply'] }
    fun U (r : Γ(X, U.unop)) (x : Γ(Z', g' ⁻¹ᵁ U.unop)) ↦ by
      change h.appLE (g' ⁻¹ᵁ U.unop) (g ⁻¹ᵁ U.unop) _ (g'.app U.unop r * x) =
        g.app U.unop r * h.appLE (g' ⁻¹ᵁ U.unop) (g ⁻¹ᵁ U.unop) _ x
      rw [map_mul, appLE_app_of_comp_eq h hg]⟩

lemma pushforwardUnitMap_app (U : X.Opens) (x : Γ(pushforwardUnit g', U)) :
    pushforwardUnitEquiv g ((pushforwardUnitMap h hg).app U x) =
      h.appLE (g' ⁻¹ᵁ U) (g ⁻¹ᵁ U) (preimage_le_preimage_of_comp_eq h hg U)
        (pushforwardUnitEquiv g' x) :=
  rfl

lemma pushforwardUnitMap_pfMul (U : X.Opens) (x y : Γ(pushforwardUnit g', U)) :
    (pushforwardUnitMap h hg).app U (pfMul g' x y) =
      pfMul g ((pushforwardUnitMap h hg).app U x) ((pushforwardUnitMap h hg).app U y) :=
  (h.appLE (g' ⁻¹ᵁ U) (g ⁻¹ᵁ U) _).hom.map_mul _ _

lemma pushforwardUnitMap_one :
    (pushforwardUnitMap h hg).app ⊤ ((pushforwardUnitEquiv g').symm 1) =
      (pushforwardUnitEquiv g).symm 1 :=
  (h.appLE (g' ⁻¹ᵁ ⊤) (g ⁻¹ᵁ ⊤) _).hom.map_one

lemma pushforwardUnitMap_comp {Z'' : Scheme.{u}} {g'' : Z'' ⟶ X} (h' : Z' ⟶ Z'')
    (hg' : h' ≫ g'' = g') :
    pushforwardUnitMap (h ≫ h') (by rw [Category.assoc, hg', hg]) =
      pushforwardUnitMap h' hg' ≫ pushforwardUnitMap h hg := by
  refine Scheme.Modules.hom_ext _ _ fun U ↦ ?_
  ext (x : Γ(Z'', g'' ⁻¹ᵁ U))
  change (h ≫ h').appLE (g'' ⁻¹ᵁ U) (g ⁻¹ᵁ U) _ x =
    h.appLE (g' ⁻¹ᵁ U) (g ⁻¹ᵁ U) _ (h'.appLE (g'' ⁻¹ᵁ U) (g' ⁻¹ᵁ U) _ x)
  rw [← CommRingCat.comp_apply, Scheme.Hom.appLE_comp_appLE]

lemma pushforwardUnitMap_id :
    pushforwardUnitMap (𝟙 Z) (Category.id_comp g) = 𝟙 (pushforwardUnit g) := by
  refine Scheme.Modules.hom_ext _ _ fun U ↦ ?_
  ext (x : Γ(Z, g ⁻¹ᵁ U))
  change (𝟙 Z : Z ⟶ Z).appLE (g ⁻¹ᵁ U) (g ⁻¹ᵁ U) _ x = x
  change (Z.presheaf.map (𝟙 (op (g ⁻¹ᵁ U)))) x = x
  rw [CategoryTheory.Functor.map_id]
  rfl

end PushforwardUnitMap

section Naturality

variable {X Z Z' : Scheme.{u}} {g : Z ⟶ X} {g' : Z' ⟶ X} (h : Z ⟶ Z') (hg : h ≫ g' = g)
  {B : X.Modules} [B.IsQuasicoherent] (algB : ModuleAlgebra B) (ψ : B ⟶ pushforwardUnit g')
  (hmul : ∀ (U : X.Opens) (x y : Γ(B, U)),
    ψ.app U (mulApp algB.mul U x y) = pfMul g' (ψ.app U x) (ψ.app U y))
  (hone : ψ.app ⊤ algB.one = (pushforwardUnitEquiv g').symm 1)

omit [B.IsQuasicoherent] in
include hmul in
lemma comp_pushforwardUnitMap_hmul (U : X.Opens) (x y : Γ(B, U)) :
    (ψ ≫ pushforwardUnitMap h hg).app U (mulApp algB.mul U x y) =
      pfMul g ((ψ ≫ pushforwardUnitMap h hg).app U x) ((ψ ≫ pushforwardUnitMap h hg).app U y) := by
  rw [Scheme.Modules.Hom.comp_app_apply, hmul, pushforwardUnitMap_pfMul]
  rfl

omit [B.IsQuasicoherent] in
include hone in
lemma comp_pushforwardUnitMap_hone :
    (ψ ≫ pushforwardUnitMap h hg).app ⊤ algB.one = (pushforwardUnitEquiv g).symm 1 := by
  rw [Scheme.Modules.Hom.comp_app_apply, hone, pushforwardUnitMap_one]

set_option backward.isDefEq.respectTransparency false in
/-- **Naturality of `toRelativeSpec`**: for an `X`-morphism `h : Z ⟶ Z'` and an algebra morphism
`ψ : B ⟶ g'_* 𝒪_{Z'}`, `h ≫ toRelativeSpec ψ = toRelativeSpec (ψ ≫ h^♯)`. -/
theorem comp_toRelativeSpec :
    h ≫ toRelativeSpec algB ψ hmul hone = toRelativeSpec algB (ψ ≫ pushforwardUnitMap h hg)
      (comp_pushforwardUnitMap_hmul h hg algB ψ hmul)
      (comp_pushforwardUnitMap_hone h hg algB ψ hone) := by
  refine Scheme.Cover.hom_ext (Z.openCoverOfIsOpenCover _
    (.comap (iSup_affineOpens_eq_top X) g.base.1)) _ _ fun U ↦ ?_
  change (g ⁻¹ᵁ U.1).ι ≫ h ≫ _ = (g ⁻¹ᵁ U.1).ι ≫ _
  rw [ι_toRelativeSpec, ← Category.assoc,
    ← h.resLE_comp_ι (preimage_le_preimage_of_comp_eq h hg U.1), Category.assoc, ι_toRelativeSpec,
    ← Scheme.Opens.toSpecΓ_SpecMap_appLE_assoc, ← Spec.map_comp_assoc]
  rfl

end Naturality

section AffineIso

variable {X Z Z' : Scheme.{u}} {g : Z ⟶ X} {g' : Z' ⟶ X} (h : Z ⟶ Z') (hg : h ≫ g' = g)

set_option backward.isDefEq.respectTransparency false in
include hg in
/-- A morphism of affine `X`-schemes inducing bijections on the rings of sections over the inverse
images of affine opens of `X` is an isomorphism. -/
theorem isIso_of_bijective_appLE [IsAffineHom g] [IsAffineHom g']
    (hbij : ∀ U : X.AffineZariskiSite, Function.Bijective
      (h.appLE (g' ⁻¹ᵁ U.1) (g ⁻¹ᵁ U.1) (preimage_le_preimage_of_comp_eq h hg U.1))) : IsIso h := by
  have h₁ := isIso_toRelativeSpec_pushforwardAlgebra g'
  have h₂ := comp_toRelativeSpec h hg (pushforwardAlgebra g') (𝟙 _) (pushforwardAlgebra_hmul g')
    rfl
  have h₃ : IsIso (toRelativeSpec (pushforwardAlgebra g') (𝟙 _ ≫ pushforwardUnitMap h hg)
      (comp_pushforwardUnitMap_hmul h hg _ _ (pushforwardAlgebra_hmul g'))
      (comp_pushforwardUnitMap_hone h hg _ _ rfl)) :=
    isIso_toRelativeSpec _ _ _ _ fun U ↦ hbij U
  rw [← h₂] at h₃
  exact IsIso.of_isIso_comp_right h
    (toRelativeSpec (pushforwardAlgebra g') (𝟙 _) (pushforwardAlgebra_hmul g') rfl)

end AffineIso

section BaseChange

/-- In a pushout square of commutative rings `A → B`, `A → C` with `A → C` surjective, `B → P` is
surjective with kernel generated by the kernel of `A → C`. -/
lemma ker_inl_of_isPushout_surjective {A B C P : CommRingCat.{u}} {f : A ⟶ B} {q : A ⟶ C}
    {inl : B ⟶ P} {inr : C ⟶ P} (h : IsPushout f q inl inr) (hq : Function.Surjective q) :
    RingHom.ker inl.hom = (RingHom.ker q.hom).map f.hom ∧ Function.Surjective inl := by
  let e : C ≅ CommRingCat.of (A ⧸ RingHom.ker q.hom) :=
    (RingHom.quotientKerEquivOfSurjective hq).symm.toCommRingCatIso
  have h' : IsPushout f (CommRingCat.ofHom (Ideal.Quotient.mk (RingHom.ker q.hom))) inl
      (e.inv ≫ inr) := by
    refine h.of_iso (Iso.refl _) (Iso.refl _) e (Iso.refl _) ?_ ?_ ?_ ?_
    · simp
    · ext a
      change (RingHom.quotientKerEquivOfSurjective hq).symm (q a) = Ideal.Quotient.mk _ a
      rw [RingEquiv.symm_apply_eq]
      rfl
    · simp
    · simp
  exact ker_inl_of_isPushout_quotient _ h'

set_option backward.isDefEq.respectTransparency false in
/-- **Affine base change along a closed immersion**: for a pullback square `P = Y ×_X X'` with
`i : X' ⟶ X` surjective on sections over the affine open `U` and `p⁻¹ U` affine, the map
`Γ(Y, p⁻¹ U) → Γ(P, j⁻¹ p⁻¹ U)` is surjective with kernel generated by the kernel of `i`. -/
theorem app_surjective_ker_of_isPullback {P Y X' X : Scheme.{u}} {j : P ⟶ Y} {s : P ⟶ X'}
    {p : Y ⟶ X} {i : X' ⟶ X} (H : IsPullback j s p i) {U : X.Opens} (hU : IsAffineOpen U)
    (hpU : IsAffineOpen (p ⁻¹ᵁ U)) (hiU : IsAffineOpen (i ⁻¹ᵁ U))
    (hi : Function.Surjective (i.app U)) :
    Function.Surjective (j.app (p ⁻¹ᵁ U)) ∧
      RingHom.ker (j.app (p ⁻¹ᵁ U)).hom = (RingHom.ker (i.app U).hom).map (p.app U).hom := by
  have hUY : j ⁻¹ᵁ p ⁻¹ᵁ U = j ⁻¹ᵁ p ⁻¹ᵁ U ⊓ s ⁻¹ᵁ i ⁻¹ᵁ U := by
    refine (inf_eq_left.mpr ?_).symm
    rw [← Scheme.Hom.comp_preimage, ← Scheme.Hom.comp_preimage, H.w]
  have hiso := isIso_pushoutSection_of_isAffineOpen H (US := U) (UT := i ⁻¹ᵁ U) (UX := p ⁻¹ᵁ U)
    le_rfl le_rfl hUY hU hiU hpU
  rw [isIso_pushoutSection_iff] at hiso
  have hi' : Function.Surjective (i.appLE U (i ⁻¹ᵁ U) le_rfl) := by
    rwa [← Scheme.Hom.app_eq_appLE]
  obtain ⟨hker, hsurj⟩ := ker_inl_of_isPushout_surjective hiso hi'
  rw [Scheme.Hom.app_eq_appLE, Scheme.Hom.app_eq_appLE, Scheme.Hom.app_eq_appLE]
  exact ⟨hsurj, hker⟩

end BaseChange

section SmulTop

variable {X Z : Scheme.{u}} (g : Z ⟶ X)

/-- `J • Γ(g_* 𝒪_Z, U)` is the ideal of `Γ(Z, g⁻¹ U)` generated by `J`. -/
lemma mem_smul_top_pushforwardUnit_iff {U : X.Opens} (J : Ideal Γ(X, U))
    (x : Γ(pushforwardUnit g, U)) :
    x ∈ (J • ⊤ : Submodule Γ(X, U) Γ(pushforwardUnit g, U)) ↔
      pushforwardUnitEquiv g x ∈ J.map (g.app U).hom := by
  constructor
  · intro hx
    refine Submodule.smul_induction_on
      (p := fun z ↦ pushforwardUnitEquiv g z ∈ J.map (g.app U).hom) hx ?_ ?_
    · intro r hr m _
      rw [pushforwardUnit_smul]
      exact Ideal.mul_mem_right _ _ (Ideal.mem_map_of_mem _ hr)
    · intro y z hy hz
      exact add_mem hy hz
  · intro hx
    have key : ∀ y ∈ J.map (g.app U).hom, ∀ t : Γ(Z, g ⁻¹ᵁ U),
        (pushforwardUnitEquiv g).symm (t * y) ∈
          (J • ⊤ : Submodule Γ(X, U) Γ(pushforwardUnit g, U)) := by
      intro y hy
      induction hy using Submodule.span_induction with
      | mem y hy =>
        obtain ⟨r, hr, rfl⟩ := hy
        intro t
        have : (pushforwardUnitEquiv g).symm (t * (g.app U).hom r) =
            r • (pushforwardUnitEquiv g).symm t := by
          change t * (g.app U).hom r = (g.app U).hom r * t
          exact mul_comm _ _
        rw [this]
        exact Submodule.smul_mem_smul hr Submodule.mem_top
      | zero => intro t; rw [mul_zero]; exact zero_mem _
      | add y z _ _ hy hz =>
        intro t
        rw [mul_add]
        exact add_mem (hy t) (hz t)
      | smul a y _ hy =>
        intro t
        rw [smul_eq_mul, ← mul_assoc]
        exact hy (t * a)
    have := key _ hx 1
    rwa [one_mul] at this

end SmulTop

lemma appLE_eq_of_eq {X Y : Scheme.{u}} {h h' : X ⟶ Y} (H : h = h') (U : Y.Opens)
    (V : X.Opens) (e : V ≤ h ⁻¹ᵁ U) (e' : V ≤ h' ⁻¹ᵁ U) : h.appLE U V e = h'.appLE U V e' := by
  subst H
  rfl

lemma appLE_comp_appLE_top {X Y Z : Scheme.{u}} (f : X ⟶ Y) (g : Y ⟶ Z) (V : Y.Opens)
    (e₁ : V ≤ g ⁻¹ᵁ ⊤) (e₂ : ⊤ ≤ f ⁻¹ᵁ V) :
    g.appLE ⊤ V e₁ ≫ f.appLE V ⊤ e₂ = g.appTop ≫ f.appTop := by
  rw [Scheme.Hom.appLE_comp_appLE, ← Scheme.Hom.comp_appTop, Scheme.Hom.appTop,
    Scheme.Hom.app_eq_appLE]
  rfl

section ToRelativeSpecApp

variable {X Z : Scheme.{u}} {g : Z ⟶ X} {B : X.Modules} [B.IsQuasicoherent]
  (algB : ModuleAlgebra B) (φ : B ⟶ pushforwardUnit g)
  (hmul : ∀ (U : X.Opens) (x y : Γ(B, U)),
    φ.app U (mulApp algB.mul U x y) = pfMul g (φ.app U x) (φ.app U y))
  (hone : φ.app ⊤ algB.one = (pushforwardUnitEquiv g).symm 1)

set_option backward.isDefEq.respectTransparency false in
/-- The morphism `toRelativeSpec φ` on sections over the inverse image of an affine open `U` is
`φ` (via `Γ(Spec_X B, p⁻¹ U) ≅ Γ(B, U)`). -/
theorem toRelativeSpec_appLE (U : X.AffineZariskiSite) :
    (algB.sectionsIso U).inv ≫ (toRelativeSpec algB φ hmul hone).appLE
      (algB.relativeSpecHom ⁻¹ᵁ U.toOpens) (g ⁻¹ᵁ U.toOpens)
      (by rw [← Scheme.Hom.comp_preimage, toRelativeSpec_relativeSpecHom]) =
      CommRingCat.ofHom (algHomApp algB φ hmul hone U.toOpens) := by
  let R := CommRingCat.of (algB.Sections U.toOpens)
  obtain ⟨c, hc'⟩ : ∃ c : Spec R ⟶ algB.relativeSpec, c = algB.relativeSpecCover.f U := ⟨_, rfl⟩
  have : IsOpenImmersion c := hc' ▸ inferInstance
  have hc : c ''ᵁ ⊤ = algB.relativeSpecHom ⁻¹ᵁ U.toOpens := by
    subst hc'
    rw [Scheme.Hom.image_top_eq_opensRange, algB.relativeSpecHom_preimage U]
  have hσ : (algB.sectionsIso U).inv = (Scheme.ΓSpecIso R).inv ≫ (c.appIso ⊤).inv ≫
      algB.relativeSpec.presheaf.map (eqToHom hc.symm).op := by
    subst hc'
    rfl
  have hWt : g ⁻¹ᵁ U.toOpens ≤ toRelativeSpec algB φ hmul hone ⁻¹ᵁ (c ''ᵁ ⊤) := by
    rw [hc, ← Scheme.Hom.comp_preimage, toRelativeSpec_relativeSpecHom]
  have E : (g ⁻¹ᵁ U.toOpens).ι ≫ toRelativeSpec algB φ hmul hone =
      (g ⁻¹ᵁ U.toOpens).toSpecΓ ≫ Spec.map (CommRingCat.ofHom
      (algHomApp algB φ hmul hone U.toOpens)) ≫ c := by
    rw [hc']
    exact ι_toRelativeSpec algB φ hmul hone U
  have e₂ : (⊤ : (g ⁻¹ᵁ U.toOpens : Scheme).Opens) ≤ (g ⁻¹ᵁ U.toOpens).ι ⁻¹ᵁ (g ⁻¹ᵁ U.toOpens) :=
    fun x _ ↦ x.2
  have EA := appLE_eq_of_eq E (c ''ᵁ ⊤) ⊤
    (fun x _ ↦ hWt x.2) (fun x _ ↦ by simp)
  rw [← Scheme.Hom.appLE_comp_appLE (U := c ''ᵁ ⊤) (V := g ⁻¹ᵁ U.toOpens) (W := ⊤) (e₁ := hWt)
    (e₂ := e₂), Scheme.Hom.comp_appLE, Scheme.Hom.comp_app] at EA
  have hι : (g ⁻¹ᵁ U.toOpens).ι.appLE (g ⁻¹ᵁ U.toOpens) ⊤ e₂ = (g ⁻¹ᵁ U.toOpens).topIso.inv := by
    rw [Scheme.Opens.ι_appLE]
    rfl
  rw [hι] at EA
  rw [← cancel_mono (g ⁻¹ᵁ U.toOpens).topIso.inv, hσ]
  simp only [Category.assoc]
  rw [Scheme.Hom.map_appLE_assoc, EA]
  simp only [Category.assoc, Scheme.Hom.appIso_inv_app_assoc]
  simp only [Scheme.Hom.app_eq_appLE, Scheme.Hom.map_appLE_assoc]
  refine (congrArg ((Scheme.ΓSpecIso R).inv ≫ ·)
    (appLE_comp_appLE_top _ _ _ le_top _)).trans ?_
  rw [← Category.assoc, ← Scheme.ΓSpecIso_inv_naturality, Category.assoc,
    Scheme.Opens.toSpecΓ_appTop, Iso.inv_hom_id_assoc]

end ToRelativeSpecApp

end AlgebraicGeometry.CohomologyAux
