/-
Copyright (c) 2026 SGAenglishpluslean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SGAenglishpluslean contributors
-/
import SGA.Foundations.Cohomology.Extension
import SGA.Foundations.Cohomology.CohomologyLemmas
import SGA.Foundations.Cohomology.QuasiCoherentKernel
import SGA.Foundations.Cohomology.CohomologicalDimension

/-!
# Serre's vanishing theorem on projective space

Let `A` be a noetherian ring and `X = ℙʳ_A = Proj A[x₀, …, x_r]`. We consider the quasi-coherent
`𝒪_X`-modules `F` whose sections over each standard affine `D₊(xᵢ)` are finitely generated
(`projectiveSpace.IsStdFinite`; these are the coherent modules). We prove:

* the class is stable under twists, isomorphisms and kernels of epimorphisms
  (`IsStdFinite.twist`, `IsStdFinite.of_iso`, `IsStdFinite.of_shortExact`);
* every such `F` is a quotient of some `𝒪(-m)^k` (`projectiveSpace.exists_epi_twist`;
  EGA III 2.2.1 (i), Hartshorne II.5.18);
* **Serre's vanishing theorem** (EGA III 2.2.1 (ii); Hartshorne III.5.2 (b); FAC §66): there is
  `n₀` with `Hᵖ(X, F(n)) = 0` for all `p > 0` and `n ≥ n₀`
  (`projectiveSpace.exists_H_twist_subsingleton`).

The proof is Serre's descending induction on `p`: `Hᵖ = 0` for `p > r` (cover by `r + 1` affines),
and a short exact sequence `0 → R → 𝒪(-m)^k → F → 0` (twisting is exact, being an equivalence of
categories) together with `Hᵖ(𝒪(d)) = 0` for `p > 0`, `d > -r - 1` gives
`Hᵖ(F(n)) ↪ Hᵖ⁺¹(R(n))`.
-/

universe v u

open CategoryTheory TopologicalSpace Opposite Limits MvPolynomial

/-! ## Generalities -/

namespace AlgebraicGeometry.CohomologyAux

variable {X : Scheme.{u}}

/-- The map on sections over `V` of a morphism of `𝒪_X`-modules, as a `Γ(X, V)`-linear map. -/
noncomputable def appLinearMap {M N : X.Modules} (φ : M ⟶ N) (V : X.Opens) :
    Γ(M, V) →ₗ[Γ(X, V)] Γ(N, V) where
  toFun := φ.app V
  map_add' := map_add _
  map_smul' := Scheme.Modules.Hom.app_smul φ

lemma appLinearMap_apply {M N : X.Modules} (φ : M ⟶ N) (V : X.Opens) (s : Γ(M, V)) :
    appLinearMap φ V s = φ.app V s :=
  rfl

/-- The sections of a finite biproduct are generated by the sections of the summands. -/
lemma finite_sections_biproduct {J : Type} [Finite J] (G : J → X.Modules) (V : X.Opens)
    (h : ∀ j, Module.Finite Γ(X, V) Γ(G j, V)) : Module.Finite Γ(X, V) Γ(⨁ G, V) := by
  have := Fintype.ofFinite J
  let f : (∀ j, Γ(G j, V)) →ₗ[Γ(X, V)] Γ(⨁ G, V) :=
    ∑ j, appLinearMap (biproduct.ι G j) V ∘ₗ LinearMap.proj j
  refine Module.Finite.of_surjective f fun s ↦ ⟨fun j ↦ (biproduct.π G j).app V s, ?_⟩
  let ev : (⨁ G ⟶ ⨁ G) →+ Γ(⨁ G, V) :=
    { toFun := fun φ ↦ φ.app V s, map_zero' := rfl, map_add' := fun _ _ ↦ rfl }
  have h := congrArg ev (biproduct.total (f := G))
  rw [map_sum] at h
  refine (LinearMap.sum_apply _ _ _).trans (Eq.trans ?_ h)
  rfl

variable (X) in
/-- The free `𝒪_X`-module `𝒪_X^k`, as a biproduct. -/
noncomputable abbrev unitBiproduct (k : ℕ) : X.Modules :=
  ⨁ fun _ : Fin k ↦ unitModule X

instance isQuasicoherent_unitBiproduct (k : ℕ) : (unitBiproduct X k).IsQuasicoherent :=
  (SheafOfModules.isQuasicoherent X.ringCatSheaf).prop_of_iso
    ((Sigma.whiskerEquiv (f := fun _ : ULift.{u} (Fin k) ↦ unitModule X)
      (g := fun _ : Fin k ↦ unitModule X) Equiv.ulift fun _ ↦ Iso.refl _) ≪≫
      (biproduct.isoCoproduct fun _ : Fin k ↦ unitModule X).symm)
    (inferInstanceAs
      (SheafOfModules.free (R := X.ringCatSheaf) (ULift.{u} (Fin k))).IsQuasicoherent)

lemma finite_sections_unitBiproduct (k : ℕ) (V : X.Opens) :
    Module.Finite Γ(X, V) Γ(unitBiproduct X k, V) :=
  finite_sections_biproduct _ V fun _ ↦ Module.Finite.self Γ(X, V)

/-- The kernel sequence of an epimorphism is short exact. -/
lemma shortExact_kernelSequence {M N : X.Modules} (π : M ⟶ N) [Epi π] :
    (ShortComplex.kernelSequence π).ShortExact where
  exact := ShortComplex.kernelSequence_exact π
  mono_f := by change Mono (kernel.ι π); infer_instance
  epi_g := by change Epi π; infer_instance

end AlgebraicGeometry.CohomologyAux

namespace AlgebraicGeometry.Scheme.LineBundle

variable {X : Scheme.{u}} (L : X.LineBundle) (n : ℤ)

lemma twistMap_add {M N : X.Modules} (φ ψ : M ⟶ N) :
    L.twistMap n (φ + ψ) = L.twistMap n φ + L.twistMap n ψ :=
  Scheme.Modules.hom_ext _ _ fun _ ↦ by ext s; rfl

instance : (twistFunctor X L n).Additive where
  map_add := L.twistMap_add n _ _

/-- **Twisting is exact**: it maps short exact sequences to short exact sequences. -/
lemma shortExact_map_twistFunctor {S : ShortComplex X.Modules} (hS : S.ShortExact) :
    (S.map (twistFunctor X L n)).ShortExact :=
  hS.map_of_exact _

/-- Twisting commutes with finite biproducts. -/
noncomputable def twistBiproductIso {J : Type} [Fintype J] (G : J → X.Modules) :
    L.twist (⨁ G) n ≅ ⨁ fun j ↦ L.twist (G j) n :=
  (twistFunctor X L n).mapBiproduct G

/-- The twist `𝒪_X ⊗ L^{⊗d}` of the structure sheaf is `L^{⊗d}` itself (definitionally). -/
lemma twist_unit_eq (d : ℤ) : L.twist (CohomologyAux.unitModule X) d = L.toModules d :=
  rfl

end AlgebraicGeometry.Scheme.LineBundle

namespace AlgebraicGeometry.projectiveSpace

attribute [local instance] MvPolynomial.gradedAlgebra

/-! ## Noetherian properties -/

section Noetherian

variable {σ : Type v} {A : Type u} [CommRing A]

lemma surjective_algebraMap_gradeZero :
    Function.Surjective (algebraMap A (homogeneousSubmodule σ A 0)) := by
  rintro ⟨p, hp⟩
  have hp' := hp
  rw [homogeneousSubmodule_zero, Submodule.mem_one] at hp'
  obtain ⟨a, rfl⟩ := hp'
  exact ⟨a, rfl⟩

instance isNoetherianRing_gradeZero [IsNoetherianRing A] :
    IsNoetherianRing (homogeneousSubmodule σ A 0) :=
  isNoetherianRing_of_surjective A _ (algebraMap A _) surjective_algebraMap_gradeZero

instance finiteType_gradeZero [Finite σ] :
    Algebra.FiniteType (homogeneousSubmodule σ A 0) (MvPolynomial σ A) := by
  classical
  have := Fintype.ofFinite σ
  refine ⟨⟨Finset.univ.image X, ?_⟩⟩
  rw [Finset.coe_image, Finset.coe_univ, Set.image_univ]
  exact adjoin_range_X σ A

/-- For `A` noetherian, the rings `Γ(D₊(xᵢ), 𝒪) = A[xⱼ/xᵢ]` are noetherian. -/
instance isNoetherianRing_topStd [Finite σ] [IsNoetherianRing A] (i : σ) :
    IsNoetherianRing Γ(Proj (homogeneousSubmodule σ A), topStd σ A i) := by
  classical
  have hf := prodX_mem (A := A) ({i} : Finset σ)
  have := HomogeneousLocalization.Away.finiteType _ _ hf
  have := Algebra.FiniteType.isNoetherianRing (homogeneousSubmodule σ A 0)
    (HomogeneousLocalization.Away (homogeneousSubmodule σ A) (prodX σ A {i}))
  have e := (Proj.basicOpenIsoAway (homogeneousSubmodule σ A) (prodX σ A {i}) hf
    (Finset.singleton_nonempty i).card_pos).commRingCatIsoToRingEquiv
  change IsNoetherianRing Γ(Proj (homogeneousSubmodule σ A), ⊤ ⊓ stdCover σ A i)
  rw [top_inf_stdCover]
  exact isNoetherianRing_of_ringEquiv _ e

end Noetherian

/-! ## Modules with finitely generated sections on the standard cover -/

variable {σ : Type v} {A : Type u} [CommRing A] [Fintype σ] [DecidableEq σ] [Nonempty σ]

variable (σ A) in
/-- A quasi-coherent module on `Proj A[xᵢ]` whose sections over each standard affine `D₊(xᵢ)` are
finitely generated. For `A` noetherian these are exactly the coherent modules (EGA I 1.5.1); the
class used in Serre's theorems (EGA III 2.2.1). -/
structure IsStdFinite (F : (Proj (homogeneousSubmodule σ A)).Modules) : Prop where
  isQuasicoherent : F.IsQuasicoherent
  finite (i : σ) :
    Module.Finite Γ(Proj (homogeneousSubmodule σ A), topStd σ A i) Γ(F, topStd σ A i)

namespace IsStdFinite

variable {F G : (Proj (homogeneousSubmodule σ A)).Modules}

omit [Fintype σ] [DecidableEq σ] [Nonempty σ] in
lemma of_iso (hF : IsStdFinite σ A F) (e : F ≅ G) : IsStdFinite σ A G where
  isQuasicoherent :=
    (SheafOfModules.isQuasicoherent (Proj (homogeneousSubmodule σ A)).ringCatSheaf).prop_of_iso e
      hF.isQuasicoherent
  finite i := by
    have := hF.finite i
    refine Module.Finite.of_surjective (CohomologyAux.appLinearMap e.hom (topStd σ A i))
      fun s ↦ ⟨e.inv.app _ s, ?_⟩
    rw [CohomologyAux.appLinearMap_apply, ← ConcreteCategory.comp_apply,
      ← Scheme.Modules.Hom.comp_app, e.inv_hom_id]
    rfl

omit [Fintype σ] [DecidableEq σ] [Nonempty σ] in
/-- Twists of modules in the class stay in the class. -/
lemma twist (hF : IsStdFinite σ A F) (n : ℤ) :
    IsStdFinite σ A ((twistingBundle σ A).twist F n) where
  isQuasicoherent := by
    have := hF.isQuasicoherent
    infer_instance
  finite i := by
    have := hF.finite i
    exact Module.Finite.equiv ((twistingBundle σ A).twistEquiv (M := F) (n := n) (idx σ A i)
      (inf_le_right : topStd σ A i ≤ (twistingBundle σ A).U _)).symm

omit [Fintype σ] [DecidableEq σ] [Nonempty σ] in
lemma unitBiproduct (k : ℕ) :
    IsStdFinite σ A (CohomologyAux.unitBiproduct (Proj (homogeneousSubmodule σ A)) k) where
  isQuasicoherent := inferInstance
  finite _ := CohomologyAux.finite_sections_unitBiproduct k _

omit [Fintype σ] [DecidableEq σ] [Nonempty σ] in
/-- **Coherence of kernels** (EGA I 1.5.1 for noetherian schemes): in a short exact sequence
`0 → R → E → F → 0` with `E` and `F` in the class, `R` is in the class, `A` being noetherian. -/
lemma of_shortExact [Finite σ] [IsNoetherianRing A]
    {S : ShortComplex (Proj (homogeneousSubmodule σ A)).Modules} (hS : S.ShortExact)
    (h₂ : IsStdFinite σ A S.X₂) (h₃ : IsStdFinite σ A S.X₃) :
    IsStdFinite σ A S.X₁ where
  isQuasicoherent := by
    have := h₂.isQuasicoherent
    have := h₃.isQuasicoherent
    exact CohomologyAux.isQuasicoherent_X₁_of_shortExact hS
  finite i := by
    have := h₂.finite i
    have : _root_.IsNoetherian Γ(Proj (homogeneousSubmodule σ A), topStd σ A i)
        Γ(S.X₂, topStd σ A i) := isNoetherian_of_isNoetherianRing_of_finite _ _
    exact Module.Finite.of_injective (CohomologyAux.appLinearMap S.f (topStd σ A i))
      (CohomologyAux.app_injective_of_shortExact hS _)

end IsStdFinite

omit [Fintype σ] [DecidableEq σ] [Nonempty σ] in
lemma iSup_topStd : ⨆ i, topStd σ A i = ⊤ := by
  simp only [topStd, top_inf_eq]
  exact iSup_stdCover σ A

omit [Fintype σ] [DecidableEq σ] [Nonempty σ] in
/-- **Every module of the class is a quotient of some `𝒪(-m)^k`** (EGA III 2.2.1 (i);
Hartshorne II.5.18): there is an epimorphism `(𝒪^k)(-m) ⟶ F`. -/
theorem exists_epi_twist [Finite σ] {F : (Proj (homogeneousSubmodule σ A)).Modules}
    (hF : IsStdFinite σ A F) :
    ∃ (m k : ℕ) (π : (twistingBundle σ A).twist
      (CohomologyAux.unitBiproduct (Proj (homogeneousSubmodule σ A)) k) (-(m : ℤ)) ⟶ F), Epi π := by
  have := hF.isQuasicoherent
  obtain ⟨m, hm⟩ := exists_generating_twist_sections F hF.finite
  obtain ⟨J, _, g, hg⟩ := hm m le_rfl
  let L := twistingBundle σ A
  let k := Fintype.card J
  let g' : Fin k → Γ(L.twist F m, ⊤) := g ∘ (Fintype.equivFin J).symm
  have hφ : Epi (biproduct.desc fun j ↦ CohomologyAux.homOfSection (L.twist F m) (g' j)) := by
    refine CohomologyAux.epi_biproduct_desc_homOfSection (L.twist F m) g' (topStd σ A)
      iSup_topStd isAffineOpen_topStd fun i ↦ ?_
    rw [← hg i]
    congr 1
    exact (Fintype.equivFin J).symm.surjective.range_comp
      (fun j ↦ (L.twist F m).presheaf.map (homOfLE le_top : topStd σ A i ⟶ ⊤).op (g j))
  refine ⟨m, k, L.twistMap (-(m : ℤ)) (biproduct.desc fun j ↦
    CohomologyAux.homOfSection (L.twist F m) (g' j)) ≫ (L.twistTwistIso F m (-(m : ℤ))).hom ≫
      eqToHom (congrArg (L.twist F) (add_neg_cancel (m : ℤ))) ≫ (L.twistZeroIso F).inv, ?_⟩
  have : Epi (L.twistMap (-(m : ℤ)) (biproduct.desc fun j ↦
      CohomologyAux.homOfSection (L.twist F m) (g' j))) :=
    (Scheme.LineBundle.twistFunctor _ L (-(m : ℤ))).map_epi _
  infer_instance

/-! ## Serre's vanishing theorem -/

section Vanishing

variable {A : Type u} [CommRing A] {r : ℕ}

/-- `Hᵖ((𝒪^k)(d)) = 0` for `p > 0` and `d > -r - 1` on `ℙʳ_A`. -/
lemma H_twist_unitBiproduct_subsingleton (k q : ℕ) {d : ℤ} (hd : -((r : ℤ) + 1) < d) :
    Subsingleton (((twistingBundle (Fin (r + 1)) A).twist
      (CohomologyAux.unitBiproduct (Proj (homogeneousSubmodule (Fin (r + 1)) A)) k) d).H
        (q + 1)) := by
  let L := twistingBundle (Fin (r + 1)) A
  have h := Scheme.Modules.subsingleton_H'_biproduct (n := q + 1) (U := ⊤)
    (fun _ : Fin k ↦ L.twist (CohomologyAux.unitModule _) d)
    fun _ ↦ H_twist_subsingleton A r q d (Or.inr hd)
  exact Scheme.Modules.subsingleton_H'_of_iso (L.twistBiproductIso d _).symm

/-- **Serre's vanishing theorem**, induction step form: for `q + j ≥ r`, every `F` of the class
has `H^{q+1}(ℙʳ_A, F(n)) = 0` for `n ≫ 0`. -/
theorem exists_H_twist_subsingleton_aux [IsNoetherianRing A] :
    ∀ (j q : ℕ), r ≤ q + j → ∀ F : (Proj (homogeneousSubmodule (Fin (r + 1)) A)).Modules,
      IsStdFinite (Fin (r + 1)) A F → ∃ n₀ : ℤ, ∀ n ≥ n₀,
        Subsingleton (((twistingBundle (Fin (r + 1)) A).twist F n).H (q + 1))
  | 0, q, hq, F, hF => ⟨0, fun n _ ↦
      @H_subsingleton_of_lt (CommRingCat.of A) r ((twistingBundle _ A).twist F n)
        (hF.twist n).isQuasicoherent _ (by omega)⟩
  | j + 1, q, hq, F, hF => by
      let L := twistingBundle (Fin (r + 1)) A
      obtain ⟨m, k, π, hπ⟩ := exists_epi_twist hF
      let S := ShortComplex.kernelSequence π
      have hS : S.ShortExact := CohomologyAux.shortExact_kernelSequence π
      have hR : IsStdFinite (Fin (r + 1)) A S.X₁ :=
        IsStdFinite.of_shortExact hS ((IsStdFinite.unitBiproduct k).twist _) hF
      obtain ⟨n₁, hn₁⟩ := exists_H_twist_subsingleton_aux j (q + 1) (by omega) S.X₁ hR
      refine ⟨max n₁ ((m : ℤ) - r), fun n hn ↦ ?_⟩
      have hSn := L.shortExact_map_twistFunctor n hS
      have hE0 := H_twist_unitBiproduct_subsingleton (A := A) (r := r) k q
        (d := -(m : ℤ) + n) (by have := le_of_max_le_right hn; omega)
      have hE : Subsingleton
          ((S.map (Scheme.LineBundle.twistFunctor _ L n)).X₂.H' (q + 1) ⊤) :=
        Scheme.Modules.subsingleton_H'_of_iso (L.twistTwistIso _ (-(m : ℤ)) n).symm
      have hR' : Subsingleton
          ((S.map (Scheme.LineBundle.twistFunctor _ L n)).X₁.H' (q + 1 + 1) ⊤) :=
        hn₁ n (le_of_max_le_left hn)
      refine ⟨fun x y ↦ ?_⟩
      have hx : ∀ z : (S.map (Scheme.LineBundle.twistFunctor _ L n)).X₃.H' (q + 1) ⊤,
          z = 0 := by
        intro z
        obtain ⟨w, hw⟩ := (Scheme.Modules.H'.exact_map_δ hSn (q + 1) ⊤ z).mp
          (@Subsingleton.elim _ hR' _ _)
        rw [← hw, @Subsingleton.elim _ hE w 0, map_zero]
      exact (hx x).trans (hx y).symm

/-- **Serre's vanishing theorem** (EGA III 2.2.1 (ii); Hartshorne III.5.2 (b); Serre, FAC §66):
let `A` be noetherian and `F` a quasi-coherent module on `ℙʳ_A` with finitely generated sections
over the `D₊(xᵢ)` (e.g. a coherent module). Then there is `n₀` such that `Hᵖ(ℙʳ_A, F(n)) = 0` for
all `p > 0` and `n ≥ n₀`. -/
theorem exists_H_twist_subsingleton [IsNoetherianRing A]
    {F : (Proj (homogeneousSubmodule (Fin (r + 1)) A)).Modules}
    (hF : IsStdFinite (Fin (r + 1)) A F) :
    ∃ n₀ : ℤ, ∀ n ≥ n₀, ∀ p : ℕ,
      Subsingleton (((twistingBundle (Fin (r + 1)) A).twist F n).H (p + 1)) := by
  have key : ∀ Q : ℕ, ∃ n₀ : ℤ, ∀ n ≥ n₀, ∀ p < Q,
      Subsingleton (((twistingBundle (Fin (r + 1)) A).twist F n).H (p + 1)) := by
    intro Q
    induction Q with
    | zero => exact ⟨0, fun _ _ _ hp ↦ absurd hp (Nat.not_lt_zero _)⟩
    | succ Q ih =>
      obtain ⟨n₁, hn₁⟩ := ih
      obtain ⟨n₂, hn₂⟩ := exists_H_twist_subsingleton_aux (r - Q) Q (by omega) F hF
      refine ⟨max n₁ n₂, fun n hn p hp ↦ ?_⟩
      rcases Nat.lt_succ_iff_lt_or_eq.mp hp with hp | rfl
      · exact hn₁ n (le_of_max_le_left hn) p hp
      · exact hn₂ n (le_of_max_le_right hn)
  obtain ⟨n₀, hn₀⟩ := key r
  refine ⟨n₀, fun n hn p ↦ ?_⟩
  by_cases hp : p < r
  · exact hn₀ n hn p hp
  · exact @H_subsingleton_of_lt (CommRingCat.of A) r ((twistingBundle _ A).twist F n)
      (hF.twist n).isQuasicoherent _ (by omega)

end Vanishing

end AlgebraicGeometry.projectiveSpace
