/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.Foundations.Projective.BertiniField
import SGA.Foundations.Fields.GeometricallyIntegral
import Mathlib.FieldTheory.RatFunc.AsPolynomial
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
import Mathlib.RingTheory.Artinian.Module
import SGA.Foundations.Dimension.FiniteType

/-!
# The Bertini field lemma

Let `k` be an algebraically closed field, `L ⊇ k` a field, `x, y ∈ L` algebraically independent
over `k`, and `s` an indeterminate. Then the field `K₀ = k(s, x + s y)` is algebraically closed
in `L(s)` (`Bertini.mem_of_isAlgebraic`). Geometrically: the generic member `x + s y = z` of the
pencil of hyperplane sections through `x = y = 0` of a variety with function field `L` is
geometrically irreducible over `k(s, z)` (the Matsusaka–Zariski form of Bertini's theorem, used
in SGA 1 X.2.10). The statement holds in every characteristic.

The proof compares two generic points (Jouanolou). Let `A = L ⊗_k L`, a domain because `k` is
algebraically closed, `N` its fraction field, `a = x ⊗ 1 − 1 ⊗ x`, `b = y ⊗ 1 − 1 ⊗ y` and
`s₀ = −a/b ∈ N`. The two embeddings `L → N` extend to `ι₁, ι₂ : L(s) → N` with `s ↦ s₀`; they agree
on `K₀` because `a + b s₀ = 0`, so they define `Ψ : L(s) ⊗_{K₀} L(s) → N`.

* `Bertini.dvd_of_eval₂_eq_zero`: since `a` is a nonzerodivisor modulo `b`
  (`Bertini.mem_span_of_mul_mem`), the kernel of `A[X] → N`, `X ↦ s₀`, is generated by `a + b X`;
* hence `ι₁`, `ι₂` and `Ψ` are injective (`Bertini.injective_tensorHom`): every element of
  `L(s) ⊗_{K₀} L(s)` is a fraction `φ(P) / φ(Q)` with `φ : A[X] → L(s) ⊗_{K₀} L(s)`, `X ↦ s ⊗ 1`,
  which kills `a + b X`;
* so `L(s) ⊗_{K₀} L(s)` is a domain, and for `E = K₀(α)` finite over `K₀` inside `L(s)`, the
  finite-dimensional domain `E ⊗_{K₀} E` is a field: the multiplication map `E ⊗_{K₀} E → E` is
  then injective, so `[E : K₀]² = [E : K₀]` and `α ∈ K₀`.

## References

* [J.-P. Jouanolou, *Théorèmes de Bertini et applications*, §6]
* [M. Fried, M. Jarden, *Field Arithmetic*, §10.5]
-/

open Polynomial TensorProduct

namespace Bertini

section Kernel

variable {A N : Type*} [CommRing A] [Field N] (j : A →+* N)
  {a b : A} (hab : ∀ c, a * c ∈ Ideal.span {b} → c ∈ Ideal.span {b})

include hab in
lemma mem_span_of_pow_mul_mem (n : ℕ) {c : A} (h : (-a) ^ n * c ∈ Ideal.span {b}) :
    c ∈ Ideal.span {b} := by
  induction n with
  | zero => simpa using h
  | succ n ih =>
    refine ih (hab _ ?_)
    rw [pow_succ', mul_assoc, neg_mul] at h
    simpa using (Ideal.span {b}).neg_mem h

/-- Homogenization of the evaluation at `t` with `b t = −a`:
`bⁿ P(t) = ∑_{i ≤ n} pᵢ (−a)ⁱ bⁿ⁻ⁱ` for `deg P ≤ n`. -/
lemma pow_mul_eval₂_eq {t : N} (ht : j a + j b * t = 0) (P : A[X]) {n : ℕ}
    (hP : P.natDegree ≤ n) :
    j b ^ n * P.eval₂ j t =
      j (∑ i ∈ Finset.range (n + 1), P.coeff i * (-a) ^ i * b ^ (n - i)) := by
  rw [eval₂_eq_sum_range' j (Nat.lt_succ_of_le hP), Finset.mul_sum, map_sum]
  refine Finset.sum_congr rfl fun i hi ↦ ?_
  have hin : i ≤ n := Nat.lt_succ_iff.mp (Finset.mem_range.mp hi)
  have hbt : j b * t = j (-a) := by rw [map_neg]; exact eq_neg_of_add_eq_zero_right ht
  rw [map_mul, map_mul, map_pow, map_pow, ← hbt, ← pow_mul_pow_sub (j b) hin]
  ring

include hab in
/-- **The kernel of `A[X] → N`, `X ↦ t`, is `(b X + a)`**, when `j : A → N` is injective,
`b ≠ 0`, `j a + j b t = 0` and `a` is a nonzerodivisor modulo `b`. -/
theorem dvd_of_eval₂_eq_zero (hj : Function.Injective j) {t : N} (ht : j a + j b * t = 0)
    (P : A[X]) (hP : P.eval₂ j t = 0) : C b * X + C a ∣ P := by
  obtain ⟨n, hn⟩ : ∃ n, P.natDegree ≤ n := ⟨_, le_rfl⟩
  induction n generalizing P with
  | zero =>
    rw [eq_C_of_natDegree_le_zero hn, eval₂_C] at hP
    rw [eq_C_of_natDegree_le_zero hn, (map_eq_zero_iff j hj).mp hP, C_0]
    exact dvd_zero _
  | succ n ih =>
    -- the leading coefficient lies in `(b)`
    have hsum := pow_mul_eval₂_eq j ht P hn
    rw [hP, mul_zero, eq_comm, map_eq_zero_iff j hj, Finset.sum_range_succ,
      Nat.sub_self, pow_zero, mul_one] at hsum
    have hrest : ∑ i ∈ Finset.range (n + 1), P.coeff i * (-a) ^ i * b ^ (n + 1 - i) ∈
        Ideal.span {b} := by
      refine Ideal.sum_mem _ fun i hi ↦ ?_
      have hin : n + 1 - i = (n - i) + 1 := by
        have := Finset.mem_range.mp hi
        omega
      rw [hin, pow_succ]
      exact Ideal.mul_mem_left _ _ (Ideal.mul_mem_left _ _ (Ideal.mem_span_singleton_self b))
    have hlead : (-a) ^ (n + 1) * P.coeff (n + 1) ∈ Ideal.span {b} := by
      have : P.coeff (n + 1) * (-a) ^ (n + 1) =
          -∑ i ∈ Finset.range (n + 1), P.coeff i * (-a) ^ i * b ^ (n + 1 - i) :=
        eq_neg_of_add_eq_zero_right hsum
      rw [mul_comm, this]
      exact (Ideal.span {b}).neg_mem hrest
    obtain ⟨q, hq⟩ := Ideal.mem_span_singleton'.mp (mem_span_of_pow_mul_mem hab _ hlead)
    -- subtract `q Xⁿ (b X + a)`
    set P' := P - C q * X ^ n * (C b * X + C a) with hP'
    have hP'deg : P'.natDegree ≤ n := by
      rw [natDegree_le_iff_coeff_eq_zero]
      intro m hm
      have e : C q * X ^ n * (C b * X + C a) = C (q * b) * X ^ (n + 1) + C (q * a) * X ^ n := by
        simp only [C_mul, pow_succ]
        ring
      have hmn : m ≠ n := Nat.ne_of_gt hm
      rw [hP', e, coeff_sub, coeff_add, coeff_C_mul_X_pow, coeff_C_mul_X_pow]
      simp only [hmn, ↓reduceIte, add_zero]
      rcases Nat.lt_or_ge (n + 1) m with h | h
      · have hmn' : m ≠ n + 1 := (Nat.ne_of_lt h).symm
        simp only [hmn', ↓reduceIte, coeff_eq_zero_of_natDegree_lt (hn.trans_lt h), sub_zero]
      · have hm' : m = n + 1 := le_antisymm h hm
        subst hm'
        simp [hq]
    have hP'eval : P'.eval₂ j t = 0 := by
      simp only [hP', eval₂_sub, hP, eval₂_mul, eval₂_add, eval₂_C, eval₂_X, eval₂_X_pow]
      rw [show j b * t + j a = 0 by rw [add_comm]; exact ht]
      ring
    have := ih P' hP'eval hP'deg
    have e : P = P' + C q * X ^ n * (C b * X + C a) := by rw [hP', sub_add_cancel]
    rw [e]
    exact dvd_add this (dvd_mul_left _ _)

include hab in
/-- A polynomial with unit leading coefficient does not vanish at `t` (with `j a + j b t = 0`),
unless it is `0`, when `b ≠ 0` is not a unit. -/
theorem eq_zero_of_eval₂_eq_zero [IsDomain A] (hj : Function.Injective j) (hb : b ≠ 0)
    (hbu : ¬IsUnit b) {t : N} (ht : j a + j b * t = 0) {P : A[X]} (hP : P.eval₂ j t = 0)
    (hu : IsUnit P.leadingCoeff) : P = 0 := by
  obtain ⟨R, hR⟩ := dvd_of_eval₂_eq_zero j hab hj ht P hP
  by_contra hP0
  have hR0 : R ≠ 0 := by rintro rfl; rw [mul_zero] at hR; exact hP0 hR
  rw [hR, leadingCoeff_mul, leadingCoeff_linear hb] at hu
  exact hbu (isUnit_of_mul_isUnit_left hu)

end Kernel

/-- If `M ⊗_K M` is a domain, `K` is algebraically closed in `M`: for `α` algebraic over `K`, the
finite-dimensional domain `E ⊗_K E` (`E = K(α)`) is a field, so the multiplication map
`E ⊗_K E → E` is injective and `[E : K]² ≤ [E : K]`. -/
theorem mem_of_isAlgebraic_of_isDomain {K M : Type*} [Field K] [Field M] [Algebra K M]
    [IsDomain (M ⊗[K] M)] {α : M} (hα : IsAlgebraic K α) : α ∈ (⊥ : IntermediateField K M) := by
  set E := IntermediateField.adjoin K {α}
  have : FiniteDimensional K E := IntermediateField.adjoin.finiteDimensional hα.isIntegral
  let ιE : E ⊗[K] E →ₐ[K] M ⊗[K] M := Algebra.TensorProduct.map E.val E.val
  have hιE : Function.Injective ιE :=
    TensorProduct.map_injective_of_flat_flat E.val.toLinearMap E.val.toLinearMap
      E.val.injective E.val.injective
  have : IsDomain (E ⊗[K] E) := hιE.isDomain ιE
  have : IsArtinianRing (E ⊗[K] E) := IsArtinianRing.of_finite K _
  have hF : IsField (E ⊗[K] E) := IsArtinianRing.isField_of_isDomain _
  let μ : E ⊗[K] E →ₐ[K] E := Algebra.TensorProduct.lmul' K
  have hμ : Function.Injective μ := by
    rw [injective_iff_map_eq_zero]
    intro w hw
    by_contra hw0
    obtain ⟨w', hw'⟩ := hF.mul_inv_cancel hw0
    have := congrArg μ hw'
    rw [map_mul, hw, zero_mul, map_one] at this
    exact zero_ne_one this
  have hle := LinearMap.finrank_le_finrank_of_injective (f := μ.toLinearMap) hμ
  rw [Module.finrank_tensorProduct] at hle
  have hpos : 0 < Module.finrank K E := Module.finrank_pos
  have h1 : Module.finrank K E = 1 := by nlinarith
  rw [IntermediateField.finrank_eq_one_iff] at h1
  have hαE : α ∈ E := IntermediateField.mem_adjoin_simple_self K α
  rwa [h1] at hαE

section FieldLemma

attribute [local instance] Algebra.TensorProduct.isDomain_of_isAlgClosed

variable (k : Type*) [Field k] {L : Type*} [Field L] [Algebra k L]

/-- The element `z = x + s y` of `L(s)` (`s = RatFunc.X`). -/
noncomputable def pencil (x y : L) : RatFunc L :=
  RatFunc.C x + RatFunc.X * RatFunc.C y

/-- The field `K₀ = k(s, x + s y) ⊆ L(s)`. -/
noncomputable abbrev pencilField (x y : L) : IntermediateField k (RatFunc L) :=
  IntermediateField.adjoin k {RatFunc.X, pencil x y}

variable [IsAlgClosed k]

/-- The "slope" `s₀ = −a / b ∈ Frac (L ⊗_k L)` of the line through the two generic points, with
`a = x ⊗ 1 − 1 ⊗ x` and `b = y ⊗ 1 − 1 ⊗ y`. -/
noncomputable def genericSlope (x y : L) : FractionRing (L ⊗[k] L) :=
  -algebraMap (L ⊗[k] L) (FractionRing (L ⊗[k] L)) (x ⊗ₜ 1 - 1 ⊗ₜ x) /
    algebraMap (L ⊗[k] L) (FractionRing (L ⊗[k] L)) (y ⊗ₜ 1 - 1 ⊗ₜ y)

variable {k} {x y : L} (hxy : AlgebraicIndependent k ![x, y])

include hxy in
lemma genericSlope_spec :
    algebraMap (L ⊗[k] L) (FractionRing (L ⊗[k] L)) (x ⊗ₜ 1 - 1 ⊗ₜ x) +
      algebraMap (L ⊗[k] L) _ (y ⊗ₜ 1 - 1 ⊗ₜ y) * genericSlope k x y = 0 := by
  have hb : algebraMap (L ⊗[k] L) (FractionRing (L ⊗[k] L)) (y ⊗ₜ 1 - 1 ⊗ₜ y) ≠ 0 :=
    (map_ne_zero_iff _ (IsFractionRing.injective _ _)).mpr (tmul_one_sub_one_tmul_ne_zero hxy)
  rw [genericSlope, mul_div_cancel₀ _ hb, add_neg_cancel]

omit [IsAlgClosed k] in
/-- `b = y ⊗ 1 − 1 ⊗ y` is not a unit: it lies in the kernel of the multiplication map. -/
lemma not_isUnit_tmul_one_sub_one_tmul (y : L) : ¬IsUnit (y ⊗ₜ[k] (1 : L) - 1 ⊗ₜ y) := by
  intro h
  have := h.map (Algebra.TensorProduct.lmul' k : L ⊗[k] L →ₐ[k] L)
  simp at this

include hxy in
/-- The evaluation `L[s] → Frac (L ⊗_k L)`, `s ↦ s₀`, through an embedding `L → L ⊗_k L` (one of the
two factors), is injective. -/
lemma injective_eval₂_genericSlope (incl : L →+* L ⊗[k] L) (hincl : Function.Injective incl) :
    Function.Injective (eval₂RingHom ((algebraMap (L ⊗[k] L) (FractionRing (L ⊗[k] L))).comp incl)
      (genericSlope k x y)) := by
  rw [injective_iff_map_eq_zero]
  intro P hP
  by_contra hP0
  have h1 : (P.map incl).eval₂ (algebraMap _ (FractionRing (L ⊗[k] L))) (genericSlope k x y) =
      0 := by
    rwa [eval₂_map]
  have hu : IsUnit (P.map incl).leadingCoeff := by
    rw [leadingCoeff_map_of_injective hincl]
    exact (isUnit_iff_ne_zero.mpr (leadingCoeff_ne_zero.mpr hP0)).map incl
  have h0 := eq_zero_of_eval₂_eq_zero (algebraMap (L ⊗[k] L) (FractionRing (L ⊗[k] L)))
    (fun c ↦ mem_span_of_mul_mem hxy) (IsFractionRing.injective _ _)
    (tmul_one_sub_one_tmul_ne_zero hxy) (not_isUnit_tmul_one_sub_one_tmul y)
    (genericSlope_spec hxy) h1 hu
  exact hP0 (Polynomial.map_injective incl hincl (by rw [h0, Polynomial.map_zero]))

/-- The left factor `L → L ⊗_k L`. -/
noncomputable abbrev inclLeft : L →+* L ⊗[k] L :=
  (Algebra.TensorProduct.includeLeft : L →ₐ[k] L ⊗[k] L).toRingHom

/-- The right factor `L → L ⊗_k L`. -/
noncomputable abbrev inclRight : L →+* L ⊗[k] L :=
  (Algebra.TensorProduct.includeRight : L →ₐ[k] L ⊗[k] L).toRingHom

omit [IsAlgClosed k] in
lemma inclLeft_injective : Function.Injective (inclLeft : L →+* L ⊗[k] L) :=
  Algebra.TensorProduct.includeLeft_injective (S := k) (algebraMap k L).injective

omit [IsAlgClosed k] in
lemma inclRight_injective : Function.Injective (inclRight : L →+* L ⊗[k] L) :=
  Algebra.TensorProduct.includeRight_injective (algebraMap k L).injective

/-- The embedding `ι₁ : L(s) → Frac (L ⊗_k L)`: `L` through the left factor, `s ↦ s₀`. -/
noncomputable def leftEmbedding : RatFunc L →+* FractionRing (L ⊗[k] L) :=
  IsFractionRing.lift (injective_eval₂_genericSlope hxy _ inclLeft_injective)

/-- The embedding `ι₂ : L(s) → Frac (L ⊗_k L)`: `L` through the right factor, `s ↦ s₀`. -/
noncomputable def rightEmbedding : RatFunc L →+* FractionRing (L ⊗[k] L) :=
  IsFractionRing.lift (injective_eval₂_genericSlope hxy _ inclRight_injective)

lemma leftEmbedding_C (l : L) :
    leftEmbedding hxy (RatFunc.C l) = algebraMap (L ⊗[k] L) _ (l ⊗ₜ 1) := by
  rw [← RatFunc.algebraMap_C, leftEmbedding, IsFractionRing.lift_algebraMap]
  simp

lemma rightEmbedding_C (l : L) :
    rightEmbedding hxy (RatFunc.C l) = algebraMap (L ⊗[k] L) _ (1 ⊗ₜ l) := by
  rw [← RatFunc.algebraMap_C, rightEmbedding, IsFractionRing.lift_algebraMap]
  simp

lemma leftEmbedding_X : leftEmbedding hxy RatFunc.X = genericSlope k x y := by
  rw [← RatFunc.algebraMap_X, leftEmbedding, IsFractionRing.lift_algebraMap]
  simp

lemma rightEmbedding_X : rightEmbedding hxy RatFunc.X = genericSlope k x y := by
  rw [← RatFunc.algebraMap_X, rightEmbedding, IsFractionRing.lift_algebraMap]
  simp

/-- `ι₁` and `ι₂` agree on `K₀ = k(s, x + s y)`, because `a + b s₀ = 0`. -/
lemma leftEmbedding_eq_rightEmbedding {q : RatFunc L} (hq : q ∈ pencilField k x y) :
    leftEmbedding hxy q = rightEmbedding hxy q := by
  have h : (pencilField k x y).toSubfield ≤
      RingHom.eqLocusField (leftEmbedding hxy) (rightEmbedding hxy) := by
    rw [IntermediateField.adjoin_toSubfield, Subfield.closure_le]
    rintro _ (⟨r, rfl⟩ | h)
    · change leftEmbedding hxy _ = rightEmbedding hxy _
      rw [IsScalarTower.algebraMap_apply k L (RatFunc L), RatFunc.algebraMap_eq_C,
        leftEmbedding_C, rightEmbedding_C, Algebra.TensorProduct.tmul_one_eq_one_tmul]
    · rcases h with rfl | h
      · change leftEmbedding hxy _ = rightEmbedding hxy _
        rw [leftEmbedding_X, rightEmbedding_X]
      · rw [Set.mem_singleton_iff] at h
        subst h
        change leftEmbedding hxy _ = rightEmbedding hxy _
        have e := genericSlope_spec hxy
        rw [map_sub, map_sub] at e
        simp only [pencil, map_add, map_mul, leftEmbedding_C, rightEmbedding_C, leftEmbedding_X,
          rightEmbedding_X]
        linear_combination e
  exact h hq

section Tensor

variable (K₀ : IntermediateField k (RatFunc L))

omit [IsAlgClosed k] in
/-- `L ⊗_k L → L(s) ⊗_{K₀} L(s)`. -/
noncomputable def tensorMap : L ⊗[k] L →+* RatFunc L ⊗[K₀] RatFunc L :=
  (Algebra.TensorProduct.productMap
    ((Algebra.TensorProduct.includeLeft (S := k)).comp (IsScalarTower.toAlgHom k L (RatFunc L)))
    (((Algebra.TensorProduct.includeRight : RatFunc L →ₐ[K₀] _).restrictScalars k).comp
      (IsScalarTower.toAlgHom k L (RatFunc L)))).toRingHom

omit [IsAlgClosed k] in
lemma tensorMap_tmul (l m : L) : tensorMap K₀ (l ⊗ₜ m) = RatFunc.C l ⊗ₜ RatFunc.C m := by
  simp [tensorMap, Algebra.TensorProduct.tmul_mul_tmul]

/-- `φ : (L ⊗_k L)[X] → L(s) ⊗_{K₀} L(s)`, `X ↦ s ⊗ 1`. -/
noncomputable def tensorPoly : (L ⊗[k] L)[X] →+* RatFunc L ⊗[K₀] RatFunc L :=
  eval₂RingHom (tensorMap K₀) (RatFunc.X ⊗ₜ 1)

omit [IsAlgClosed k] in
lemma tensorPoly_map_inclLeft (p : L[X]) :
    tensorPoly K₀ (p.map inclLeft) = algebraMap L[X] (RatFunc L) p ⊗ₜ 1 := by
  have e : (tensorMap K₀).comp inclLeft =
      Algebra.TensorProduct.includeLeftRingHom.comp RatFunc.C := by
    ext l
    simp [tensorMap_tmul]
  rw [tensorPoly, coe_eval₂RingHom, eval₂_map, e, ← RatFunc.aeval_X_left_eq_algebraMap,
    aeval_def, RatFunc.algebraMap_eq_C]
  change _ = Algebra.TensorProduct.includeLeftRingHom (eval₂ RatFunc.C RatFunc.X p)
  rw [hom_eval₂]
  rfl

omit [IsAlgClosed k] in
lemma tensorPoly_map_inclRight (hX : RatFunc.X ∈ K₀) (p : L[X]) :
    tensorPoly K₀ (p.map inclRight) = 1 ⊗ₜ algebraMap L[X] (RatFunc L) p := by
  have e : (tensorMap K₀).comp inclRight =
      (Algebra.TensorProduct.includeRight : RatFunc L →ₐ[K₀] _).toRingHom.comp RatFunc.C := by
    ext l
    simp [tensorMap_tmul]
  have hX' : ((RatFunc.X : RatFunc L) ⊗ₜ[K₀] (1 : RatFunc L)) = 1 ⊗ₜ (RatFunc.X : RatFunc L) := by
    have := Algebra.TensorProduct.tmul_one_eq_one_tmul (R := K₀) (A := RatFunc L)
      (B := RatFunc L) ⟨_, hX⟩
    exact this
  rw [tensorPoly, coe_eval₂RingHom, eval₂_map, e, hX', ← RatFunc.aeval_X_left_eq_algebraMap,
    aeval_def, RatFunc.algebraMap_eq_C]
  change _ = (Algebra.TensorProduct.includeRight : RatFunc L →ₐ[K₀] _).toRingHom
    (eval₂ RatFunc.C RatFunc.X p)
  rw [hom_eval₂]
  rfl

omit [IsAlgClosed k] in
/-- Every element of `L(s) ⊗_{K₀} L(s)` is a fraction `φ(P) / φ(Q)` (when `s ∈ K₀`). -/
lemma exists_mul_tensorPoly_eq (hX : RatFunc.X ∈ K₀) (w : RatFunc L ⊗[K₀] RatFunc L) :
    ∃ P Q : (L ⊗[k] L)[X], IsUnit (tensorPoly K₀ Q) ∧ w * tensorPoly K₀ Q = tensorPoly K₀ P := by
  let good : RatFunc L ⊗[K₀] RatFunc L → Prop := fun w ↦
    ∃ P Q : (L ⊗[k] L)[X], IsUnit (tensorPoly K₀ Q) ∧ w * tensorPoly K₀ Q = tensorPoly K₀ P
  have hmul (w w' : RatFunc L ⊗[K₀] RatFunc L) (h : good w) (h' : good w') : good (w * w') := by
    obtain ⟨P, Q, hQ, e⟩ := h
    obtain ⟨P', Q', hQ', e'⟩ := h'
    refine ⟨P * P', Q * Q', by rw [map_mul]; exact hQ.mul hQ', ?_⟩
    rw [map_mul, map_mul, ← e, ← e']
    ring
  have hfrac (m : RatFunc L) : ∃ p q : L[X], algebraMap L[X] (RatFunc L) q ≠ 0 ∧
      m * algebraMap L[X] (RatFunc L) q = algebraMap L[X] (RatFunc L) p := by
    obtain ⟨p, q, hq, rfl⟩ := IsFractionRing.div_surjective (A := L[X]) m
    have hq' := IsFractionRing.to_map_ne_zero_of_mem_nonZeroDivisors (K := RatFunc L) hq
    exact ⟨p, q, hq', div_mul_cancel₀ _ hq'⟩
  induction w using TensorProduct.induction_on with
  | zero => exact ⟨0, 1, by rw [map_one]; exact isUnit_one, by rw [zero_mul, map_zero]⟩
  | add w w' h h' =>
    obtain ⟨P, Q, hQ, e⟩ := h
    obtain ⟨P', Q', hQ', e'⟩ := h'
    refine ⟨P * Q' + P' * Q, Q * Q', by rw [map_mul]; exact hQ.mul hQ', ?_⟩
    rw [map_add, map_mul, map_mul, map_mul, ← e, ← e']
    ring
  | tmul m m' =>
    have e : m ⊗ₜ[K₀] m' = (m ⊗ₜ 1) * (1 ⊗ₜ m') := by
      rw [Algebra.TensorProduct.tmul_mul_tmul, mul_one, one_mul]
    rw [e]
    refine hmul _ _ ?_ ?_
    · obtain ⟨p, q, hq, h⟩ := hfrac m
      refine ⟨p.map inclLeft, q.map inclLeft, ?_, ?_⟩
      · rw [tensorPoly_map_inclLeft]
        exact (isUnit_iff_ne_zero.mpr hq).map Algebra.TensorProduct.includeLeftRingHom
      · rw [tensorPoly_map_inclLeft, tensorPoly_map_inclLeft, Algebra.TensorProduct.tmul_mul_tmul,
          mul_one, h]
    · obtain ⟨p, q, hq, h⟩ := hfrac m'
      refine ⟨p.map inclRight, q.map inclRight, ?_, ?_⟩
      · rw [tensorPoly_map_inclRight K₀ hX]
        exact (isUnit_iff_ne_zero.mpr hq).map
          (Algebra.TensorProduct.includeRight : RatFunc L →ₐ[K₀] _)
      · rw [tensorPoly_map_inclRight K₀ hX, tensorPoly_map_inclRight K₀ hX,
          Algebra.TensorProduct.tmul_mul_tmul, mul_one, h]

omit [IsAlgClosed k] in
/-- `φ` kills `b X + a` (with `a = x ⊗ 1 − 1 ⊗ x`, `b = y ⊗ 1 − 1 ⊗ y`) when `s, x + s y ∈ K₀`. -/
lemma tensorPoly_eq_zero (hX : RatFunc.X ∈ K₀) (hz : pencil x y ∈ K₀) :
    tensorPoly K₀ (C (y ⊗ₜ[k] 1 - 1 ⊗ₜ y) * X + C (x ⊗ₜ[k] 1 - 1 ⊗ₜ x)) = 0 := by
  have hX' : ((RatFunc.X : RatFunc L) ⊗ₜ[K₀] (1 : RatFunc L)) = 1 ⊗ₜ RatFunc.X :=
    Algebra.TensorProduct.tmul_one_eq_one_tmul (R := K₀) (A := RatFunc L)
      (B := RatFunc L) ⟨_, hX⟩
  have hz' : (pencil x y ⊗ₜ[K₀] (1 : RatFunc L)) = 1 ⊗ₜ pencil x y :=
    Algebra.TensorProduct.tmul_one_eq_one_tmul (R := K₀) (A := RatFunc L)
      (B := RatFunc L) ⟨_, hz⟩
  rw [tensorPoly, coe_eval₂RingHom, eval₂_add, eval₂_mul, eval₂_C, eval₂_C, eval₂_X, map_sub,
    map_sub, tensorMap_tmul, tensorMap_tmul, tensorMap_tmul, tensorMap_tmul, map_one]
  have e3 : (1 ⊗ₜ[K₀] RatFunc.C y) * ((RatFunc.X : RatFunc L) ⊗ₜ[K₀] 1) =
      1 ⊗ₜ (RatFunc.C y * RatFunc.X) := by
    rw [hX', Algebra.TensorProduct.tmul_mul_tmul, one_mul]
  rw [sub_mul, e3, Algebra.TensorProduct.tmul_mul_tmul, mul_one]
  have e4 : pencil x y ⊗ₜ[K₀] (1 : RatFunc L) - 1 ⊗ₜ pencil x y = 0 := by rw [hz', sub_self]
  rw [← e4, pencil, add_tmul, tmul_add, mul_comm (RatFunc.X : RatFunc L) (RatFunc.C y)]
  abel

end Tensor

include hxy in
/-- **The Bertini field lemma** (Matsusaka–Zariski): let `k` be algebraically closed, `L ⊇ k` a
field and `x, y ∈ L` algebraically independent over `k`. Then `K₀ = k(s, x + s y)` is
algebraically closed in `L(s)`: every element of `L(s)` algebraic over `K₀` lies in `K₀`. -/
theorem mem_of_isAlgebraic {α : RatFunc L} (hα : IsAlgebraic (pencilField k x y) α) :
    α ∈ pencilField k x y := by
  set K₀ := pencilField k x y
  let N := FractionRing (L ⊗[k] L)
  let j := algebraMap (L ⊗[k] L) N
  let a : L ⊗[k] L := x ⊗ₜ 1 - 1 ⊗ₜ x
  let b : L ⊗[k] L := y ⊗ₜ 1 - 1 ⊗ₜ y
  have hX : RatFunc.X ∈ K₀ := IntermediateField.subset_adjoin _ _ (Set.mem_insert _ _)
  have hz : pencil x y ∈ K₀ :=
    IntermediateField.subset_adjoin _ _ (Set.mem_insert_of_mem _ rfl)
  -- the map `Ψ : L(s) ⊗_{K₀} L(s) → N`
  let ι₁ := leftEmbedding hxy
  let ι₂ := rightEmbedding hxy
  let _ : Algebra K₀ N := (ι₁.comp (algebraMap K₀ (RatFunc L))).toAlgebra
  let ι₁' : RatFunc L →ₐ[K₀] N := { ι₁ with commutes' := fun _ ↦ rfl }
  let ι₂' : RatFunc L →ₐ[K₀] N :=
    { ι₂ with commutes' := fun q ↦ (leftEmbedding_eq_rightEmbedding hxy q.2).symm }
  let Ψ := Algebra.TensorProduct.productMap ι₁' ι₂'
  -- `Ψ ∘ φ` is the evaluation at `s₀`
  have hΨm (w : L ⊗[k] L) : Ψ (tensorMap K₀ w) = j w := by
    induction w using TensorProduct.induction_on with
    | zero => simp
    | add w w' h h' => rw [map_add, map_add, h, h', map_add]
    | tmul l m =>
      rw [tensorMap_tmul, Algebra.TensorProduct.productMap_apply_tmul]
      change leftEmbedding hxy (RatFunc.C l) * rightEmbedding hxy (RatFunc.C m) = _
      rw [leftEmbedding_C, rightEmbedding_C, ← map_mul, Algebra.TensorProduct.tmul_mul_tmul,
        mul_one, one_mul]
  have hΨφ (P : (L ⊗[k] L)[X]) : Ψ (tensorPoly K₀ P) = P.eval₂ j (genericSlope k x y) := by
    rw [tensorPoly, coe_eval₂RingHom]
    change Ψ.toRingHom (eval₂ (tensorMap K₀) (RatFunc.X ⊗ₜ 1) P) = _
    rw [hom_eval₂]
    have e1 : Ψ.toRingHom.comp (tensorMap K₀) = j := RingHom.ext hΨm
    have e2 : Ψ.toRingHom ((RatFunc.X : RatFunc L) ⊗ₜ[K₀] 1) = genericSlope k x y := by
      change ι₁ RatFunc.X * ι₂ 1 = _
      rw [map_one, mul_one]
      exact leftEmbedding_X hxy
    rw [e1, e2]
  have hφ0 := tensorPoly_eq_zero K₀ hX hz
  -- `Ψ` is injective
  have hΨ : Function.Injective Ψ := by
    rw [injective_iff_map_eq_zero]
    intro w hw
    obtain ⟨P, Q, hQ, hPQ⟩ := exists_mul_tensorPoly_eq K₀ hX w
    have hP : P.eval₂ j (genericSlope k x y) = 0 := by
      rw [← hΨφ, ← hPQ, map_mul, hw, zero_mul]
    obtain ⟨R, hR⟩ := dvd_of_eval₂_eq_zero j (fun c ↦ mem_span_of_mul_mem hxy)
      (IsFractionRing.injective _ _) (genericSlope_spec hxy) P hP
    have hφP : tensorPoly K₀ P = 0 := by rw [hR, map_mul, hφ0, zero_mul]
    rw [hφP] at hPQ
    exact hQ.mul_left_eq_zero.mp hPQ
  have : IsDomain (RatFunc L ⊗[K₀] RatFunc L) := hΨ.isDomain Ψ
  obtain ⟨q, rfl⟩ := IntermediateField.mem_bot.mp (mem_of_isAlgebraic_of_isDomain hα)
  exact q.2

end FieldLemma

section Embedding

variable {k : Type*} [Field k] {L : Type*} [Field L] [Algebra k L] {x y : L}

variable (k) in
/-- `k[S, Z] → L(s)`, `S ↦ s`, `Z ↦ x + s y`. -/
noncomputable def pencilPoly (x y : L) : MvPolynomial (Fin 2) k →ₐ[k] RatFunc L :=
  MvPolynomial.aeval ![RatFunc.X, pencil x y]

/-- `S` and `x + S y` are algebraically independent over `k` when `x`, `y` are: the map
`k[S, Z] → L(S)` factors through `k[A, B][S]`, `Z ↦ A + S B`, which has the retraction
`S ↦ S`, `A ↦ Z`, `B ↦ 0`. -/
lemma injective_pencilPoly (hxy : AlgebraicIndependent k ![x, y]) :
    Function.Injective (pencilPoly k x y) := by
  let σ : MvPolynomial (Fin 2) k →ₐ[k] Polynomial (MvPolynomial (Fin 2) k) :=
    MvPolynomial.aeval ![Polynomial.X, Polynomial.C (MvPolynomial.X 0) +
      Polynomial.X * Polynomial.C (MvPolynomial.X 1)]
  let ρ : Polynomial (MvPolynomial (Fin 2) k) →ₐ[k] MvPolynomial (Fin 2) k :=
    (Polynomial.aeval (R := MvPolynomial (Fin 2) k) (MvPolynomial.X 0)).restrictScalars k |>.comp
      (Polynomial.mapAlgHom (MvPolynomial.aeval ![MvPolynomial.X 1, 0]))
  have hρσ : ρ.comp σ = AlgHom.id k (MvPolynomial (Fin 2) k) := by
    refine MvPolynomial.algHom_ext fun i ↦ ?_
    fin_cases i
    · simp [ρ, σ]
    · simp [ρ, σ, MvPolynomial.aeval_X]
  have hσ : Function.Injective σ := Function.LeftInverse.injective (g := ρ) fun p ↦
    congrArg (fun φ : MvPolynomial (Fin 2) k →ₐ[k] MvPolynomial (Fin 2) k ↦ φ p) hρσ
  let ev : MvPolynomial (Fin 2) k →+* L := (MvPolynomial.aeval ![x, y]).toRingHom
  have hev : Function.Injective ev := algebraicIndependent_iff_injective_aeval.mp hxy
  have hfac (p : MvPolynomial (Fin 2) k) : pencilPoly k x y p =
      algebraMap L[X] (RatFunc L) ((σ p).map ev) := by
    have : (pencilPoly k x y).toRingHom =
        (algebraMap L[X] (RatFunc L)).comp ((Polynomial.mapRingHom ev).comp σ.toRingHom) := by
      refine MvPolynomial.ringHom_ext (fun c ↦ ?_) (fun i ↦ ?_)
      · have e1 : σ (MvPolynomial.C c) = Polynomial.C (MvPolynomial.C c) := by
          rw [← MvPolynomial.algebraMap_eq, AlgHom.commutes, Polynomial.algebraMap_apply,
            MvPolynomial.algebraMap_eq]
        simp only [AlgHom.toRingHom_eq_coe, RingHom.coe_coe, RingHom.coe_comp,
          Function.comp_apply, e1, Polynomial.coe_mapRingHom, Polynomial.map_C]
        rw [RatFunc.algebraMap_C]
        simp [pencilPoly, ev, RatFunc.algebraMap_eq_C,
          IsScalarTower.algebraMap_apply k L (RatFunc L)]
      · fin_cases i
        · simp [pencilPoly, σ, ev]
        · simp [pencilPoly, σ, ev, pencil, Polynomial.map_add]
          ring
    exact congrArg (fun φ : MvPolynomial (Fin 2) k →+* RatFunc L ↦ φ p) this
  intro p q hpq
  rw [hfac, hfac] at hpq
  exact hσ (Polynomial.map_injective ev hev (RatFunc.algebraMap_injective L hpq))

variable (hxy : AlgebraicIndependent k ![x, y])

/-- The embedding `κ : k(S, Z) → L(s)`, `S ↦ s`, `Z ↦ x + s y`, onto `k(s, x + s y)`. -/
noncomputable def pencilEmbedding : FractionRing (MvPolynomial (Fin 2) k) →ₐ[k] RatFunc L :=
  IsFractionRing.liftAlgHom (injective_pencilPoly hxy)

lemma pencilEmbedding_algebraMap (p : MvPolynomial (Fin 2) k) :
    pencilEmbedding hxy (algebraMap _ _ p) = pencilPoly k x y p := by
  rw [pencilEmbedding, IsFractionRing.liftAlgHom_apply, IsFractionRing.lift_algebraMap]
  rfl

lemma pencilPoly_mem (p : MvPolynomial (Fin 2) k) : pencilPoly k x y p ∈ pencilField k x y := by
  induction p using MvPolynomial.induction_on with
  | C a => simp [pencilPoly, (pencilField k x y).algebraMap_mem a]
  | add p q hp hq => rw [map_add]; exact add_mem hp hq
  | mul_X p i hp =>
    rw [map_mul]
    refine mul_mem hp ?_
    fin_cases i
    · simpa [pencilPoly] using IntermediateField.subset_adjoin k _ (Set.mem_insert _ _)
    · simpa [pencilPoly] using
        IntermediateField.subset_adjoin k _ (Set.mem_insert_of_mem _ (Set.mem_singleton _))

lemma pencilEmbedding_mem (q : FractionRing (MvPolynomial (Fin 2) k)) :
    pencilEmbedding hxy q ∈ pencilField k x y := by
  obtain ⟨a, b, -, rfl⟩ := IsFractionRing.div_surjective (A := MvPolynomial (Fin 2) k) q
  rw [map_div₀, pencilEmbedding_algebraMap, pencilEmbedding_algebraMap]
  exact div_mem (pencilPoly_mem a) (pencilPoly_mem b)

lemma pencilField_le_fieldRange : pencilField k x y ≤ (pencilEmbedding hxy).fieldRange := by
  rw [IntermediateField.adjoin_le_iff]
  rintro _ (rfl | h)
  · refine ⟨algebraMap (MvPolynomial (Fin 2) k) _ (MvPolynomial.X 0), ?_⟩
    change pencilEmbedding hxy _ = _
    rw [pencilEmbedding_algebraMap]
    simp [pencilPoly]
  · rw [Set.mem_singleton_iff] at h
    subst h
    refine ⟨algebraMap (MvPolynomial (Fin 2) k) _ (MvPolynomial.X 1), ?_⟩
    change pencilEmbedding hxy _ = _
    rw [pencilEmbedding_algebraMap]
    simp [pencilPoly]

/-- **The Bertini field lemma, with `K₀ = k(S, Z)`**: let `k` be algebraically closed and `x, y ∈ L`
algebraically independent over `k`. Make `L(s)` a `k(S, Z)`-algebra by `S ↦ s`, `Z ↦ x + s y`
(`pencilEmbedding`). Every element of `L(s)` algebraic over `k(S, Z)` lies in its image. -/
theorem mem_range_pencilEmbedding [IsAlgClosed k] {θ : RatFunc L}
    (hθ : letI := (pencilEmbedding hxy).toRingHom.toAlgebra;
      IsAlgebraic (FractionRing (MvPolynomial (Fin 2) k)) θ) :
    θ ∈ Set.range (pencilEmbedding hxy) := by
  let K₀ := FractionRing (MvPolynomial (Fin 2) k)
  let S := pencilField k x y
  let _ : Algebra K₀ (RatFunc L) := (pencilEmbedding hxy).toRingHom.toAlgebra
  let κ' : K₀ →+* S := (pencilEmbedding hxy).toRingHom.codRestrict S.toSubalgebra
    (pencilEmbedding_mem hxy)
  let _ : Algebra K₀ S := κ'.toAlgebra
  have : IsScalarTower K₀ S (RatFunc L) := .of_algebraMap_eq fun _ ↦ rfl
  have hθS : IsAlgebraic S θ := hθ.extendScalars κ'.injective
  obtain ⟨q, hq⟩ := pencilField_le_fieldRange hxy (mem_of_isAlgebraic hxy hθS)
  exact ⟨q, hq⟩

end Embedding

section Trdeg

universe u

variable {k L : Type u} [Field k] [Field L] [Algebra k L] {x y : L}
  (hxy : AlgebraicIndependent k ![x, y])

/-- **Transcendence degree of the generic hyperplane section**: `trdeg_{k(S, Z)} L(s) + 1 =
trdeg_k L`, for `L(s)` a `k(S, Z)`-algebra through `pencilEmbedding` (`S ↦ s`, `Z ↦ x + s y`). -/
theorem trdeg_pencilEmbedding_add_one :
    letI := (pencilEmbedding hxy).toRingHom.toAlgebra
    Algebra.trdeg (FractionRing (MvPolynomial (Fin 2) k)) (RatFunc L) + 1 = Algebra.trdeg k L := by
  let K₀ := FractionRing (MvPolynomial (Fin 2) k)
  let _ : Algebra K₀ (RatFunc L) := (pencilEmbedding hxy).toRingHom.toAlgebra
  have : IsScalarTower k K₀ (RatFunc L) :=
    .of_algebraMap_eq fun r ↦ ((pencilEmbedding hxy).commutes r).symm
  have : FaithfulSMul K₀ (RatFunc L) :=
    (faithfulSMul_iff_algebraMap_injective _ _).mpr (pencilEmbedding hxy).injective
  -- `trdeg_k K₀ = 2`
  have h1 : Algebra.trdeg k K₀ = 2 := by
    rw [Algebra.FiniteType.trdeg_fractionRing k, MvPolynomial.trdeg_of_isDomain]
    simp
  -- `trdeg_L L(s) = 1`
  have h2 : Algebra.trdeg L (RatFunc L) = 1 := by
    have : Algebra.IsAlgebraic L[X] (RatFunc L) :=
      IsLocalization.isAlgebraic _ (nonZeroDivisors L[X])
    have h := lift_trdeg_add_eq L L[X] (RatFunc L)
    rw [trdeg_eq_zero (R := L[X]) (A := RatFunc L), Cardinal.lift_zero, add_zero,
      Cardinal.lift_id, Cardinal.lift_id, Polynomial.trdeg_of_isDomain] at h
    exact h.symm
  have h3 := trdeg_add_eq k L (A := RatFunc L)
  have h4 := trdeg_add_eq k K₀ (A := RatFunc L)
  rw [h2] at h3
  rw [h1, ← h3] at h4
  rw [← Cardinal.add_one_inj, add_assoc, one_add_one_eq_two, add_comm _ 2]
  exact h4

end Trdeg

end Bertini
