/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.Foundations.Projective.PlaneModel
import Mathlib.Algebra.MvPolynomial.NoZeroDivisors
import Mathlib.Algebra.MvPolynomial.Funext
import Mathlib.Algebra.Polynomial.Bivariate

/-!
# The equation of a plane curve

Let `k` be an infinite field, `k ⊆ K` and `x, y ∈ K` such that the relations between `x` and `y`
are generated by one polynomial `f ∈ k[s][t]`: `ker (k[s][t] → K, s ↦ x, t ↦ y) = (f)` (e.g. a
plane model of a function field of transcendence degree `1`,
`Field.exists_planeModel_of_trdeg_eq_one`).
Then the homogeneous prime `𝔭 = PlaneCurve.ideal k x y ⊆ k[X₀, X₁, X₂]` of the plane curve through
`(1 : x : y)` is principal, generated by the homogenization `F` of `f`
(`AlgebraicGeometry.PlaneCurve.toIdeal_ideal_eq_span`): the plane curve
`AlgebraicGeometry.planeCurve k x y` is the hypersurface `Proj (k[X₀, X₁, X₂] ⧸ (F))`. The
coefficients of `F` are those of `f`: homogenization commutes with maps of coefficients
(`PlaneCurve.map_homog`).

Tools:

* `PlaneCurve.dehom : k[X₀, X₁, X₂] → k[X₀', X₁']`, `P ↦ P(1, X₀', X₁')`;
* `PlaneCurve.homog n p = ∑_{j ≤ n} X₀^{n-j} p_j(X₁, X₂)` (`p_j` the homogeneous components of
  `p`), homogeneous of degree `n` (`isHomogeneous_homog`), with `dehom (homog n p) = p` when
  `deg p ≤ n` (`dehom_homog`);
* a homogeneous polynomial over an infinite field is determined by its dehomogenization
  (`eq_of_dehom_eq`).

## References

* [R. Hartshorne, *Algebraic Geometry*, I.2 and Exercise I.2.9][Hartshorne]
-/

universe u

open MvPolynomial

namespace AlgebraicGeometry.PlaneCurve

section Homogenization

variable {k : Type u} [Field k]

/-- Dehomogenization with respect to `X₀`: `P ↦ P(1, X₀', X₁')`. -/
noncomputable def dehom : MvPolynomial (Fin 3) k →ₐ[k] MvPolynomial (Fin 2) k :=
  aeval (Fin.cons 1 X)

/-- Homogenization to degree `n`: `∑_{j ≤ n} X₀^{n-j} p_j(X₁, X₂)`, where `p_j` is the homogeneous
component of degree `j` of `p`. -/
noncomputable def homog (n : ℕ) (p : MvPolynomial (Fin 2) k) : MvPolynomial (Fin 3) k :=
  ∑ j ∈ Finset.range (n + 1), X 0 ^ (n - j) * rename Fin.succ (homogeneousComponent j p)

lemma isHomogeneous_homog (n : ℕ) (p : MvPolynomial (Fin 2) k) :
    (homog n p).IsHomogeneous n := by
  refine IsHomogeneous.sum _ _ _ fun j hj ↦ ?_
  have hjn : j ≤ n := Nat.lt_succ_iff.mp (Finset.mem_range.mp hj)
  have h1 : (X 0 ^ (n - j) : MvPolynomial (Fin 3) k).IsHomogeneous (n - j) :=
    isHomogeneous_X_pow _ _
  have h2 : (rename Fin.succ (homogeneousComponent j p)).IsHomogeneous j :=
    (homogeneousComponent_isHomogeneous j p).rename_isHomogeneous
  simpa [Nat.sub_add_cancel hjn] using h1.mul h2

lemma dehom_rename_succ (q : MvPolynomial (Fin 2) k) : dehom (rename Fin.succ q) = q := by
  rw [dehom, aeval_rename]
  have : (Fin.cons 1 X : Fin 3 → MvPolynomial (Fin 2) k) ∘ Fin.succ = X := by
    ext1 i
    simp
  rw [this, aeval_X_left_apply]

lemma dehom_X_zero : dehom (X 0 : MvPolynomial (Fin 3) k) = 1 := by
  simp [dehom]

lemma dehom_homog {n : ℕ} {p : MvPolynomial (Fin 2) k} (hp : p.totalDegree ≤ n) :
    dehom (homog n p) = p := by
  have h1 (j : ℕ) : dehom ((X 0 : MvPolynomial (Fin 3) k) ^ (n - j) *
      rename Fin.succ (homogeneousComponent j p)) = homogeneousComponent j p := by
    rw [map_mul, map_pow, dehom_X_zero, one_pow, one_mul, dehom_rename_succ]
  rw [homog, map_sum, Finset.sum_congr rfl (fun j _ ↦ h1 j)]
  conv_rhs => rw [← sum_homogeneousComponent p]
  symm
  refine Finset.sum_subset (Finset.range_subset_range.mpr (Nat.succ_le_succ hp))
    fun j _ hj ↦ homogeneousComponent_eq_zero _ _ ?_
  rw [Finset.mem_range, not_lt] at hj
  omega

/-- Evaluating a homogeneous polynomial of degree `n` at `c • v` gives `cⁿ` times its value at
`v`. -/
lemma eval_smul_of_isHomogeneous {σ : Type*} {Q : MvPolynomial σ k} {n : ℕ}
    (hQ : Q.IsHomogeneous n) (c : k) (v : σ → k) :
    eval (c • v) Q = c ^ n * eval v Q := by
  conv_lhs => rw [Q.as_sum]
  conv_rhs => rw [Q.as_sum]
  rw [map_sum, map_sum, Finset.mul_sum]
  refine Finset.sum_congr rfl fun d hd ↦ ?_
  have hdeg : d.degree = n := by
    rw [Finsupp.degree_eq_weight_one]
    exact hQ (mem_support_iff.mp hd)
  have hsum : d.degree = ∑ i ∈ d.support, d i := rfl
  simp only [eval_monomial, Finsupp.prod, Pi.smul_apply, smul_eq_mul, mul_pow,
    Finset.prod_mul_distrib, Finset.prod_pow_eq_pow_sum]
  rw [← hsum, hdeg]
  ring

/-- Over an infinite field, a homogeneous polynomial in `X₀, X₁, X₂` whose dehomogenization
vanishes is zero. -/
lemma eq_zero_of_dehom_eq_zero [Infinite k] {Q : MvPolynomial (Fin 3) k} {n : ℕ}
    (hQ : Q.IsHomogeneous n) (h : dehom Q = 0) : Q = 0 := by
  have hX : (X 0 : MvPolynomial (Fin 3) k) * Q = 0 := by
    refine MvPolynomial.funext fun v ↦ ?_
    rw [map_zero, map_mul, eval_X]
    by_cases hv : v 0 = 0
    · rw [hv, zero_mul]
    · have hv' : v = v 0 • Fin.cons 1 (fun i ↦ (v 0)⁻¹ * v i.succ) := by
        ext i
        refine Fin.cases ?_ (fun i ↦ ?_) i
        · simp
        · simp [← mul_assoc, mul_inv_cancel₀ hv]
      have h0 : eval (Fin.cons 1 (fun i ↦ (v 0)⁻¹ * v i.succ) : Fin 3 → k) Q = 0 := by
        have e := congrArg (aeval (R := k) fun i ↦ (v 0)⁻¹ * v i.succ) h
        rw [map_zero, dehom, ← AlgHom.comp_apply, comp_aeval] at e
        rw [← coe_aeval_eq_eval, ← e]
        refine congrArg (fun g ↦ aeval g Q) (funext fun i ↦ ?_)
        refine Fin.cases ?_ (fun i ↦ ?_) i <;> simp
      rw [hv', eval_smul_of_isHomogeneous hQ, h0, mul_zero, mul_zero]
  exact (mul_eq_zero.mp hX).resolve_left (X_ne_zero 0)

/-- Over an infinite field, two homogeneous polynomials of the same degree in `X₀, X₁, X₂` with
the same dehomogenization are equal. -/
lemma eq_of_dehom_eq [Infinite k] {Q Q' : MvPolynomial (Fin 3) k} {n : ℕ}
    (hQ : Q.IsHomogeneous n) (hQ' : Q'.IsHomogeneous n) (h : dehom Q = dehom Q') : Q = Q' :=
  sub_eq_zero.mp (eq_zero_of_dehom_eq_zero (hQ.sub hQ') (by rw [map_sub, h, sub_self]))

lemma map_homogeneousComponent {k' : Type*} [Field k'] (φ : k →+* k') (j : ℕ)
    (p : MvPolynomial (Fin 2) k) :
    map φ (homogeneousComponent j p) = homogeneousComponent j (map φ p) := by
  ext d
  rw [coeff_map, coeff_homogeneousComponent, coeff_homogeneousComponent, coeff_map]
  split_ifs <;> simp

/-- Homogenization commutes with maps of coefficients: the coefficients of `homog n p` are
those of `p`. -/
lemma map_homog {k' : Type*} [Field k'] (φ : k →+* k') (n : ℕ) (p : MvPolynomial (Fin 2) k) :
    map φ (homog n p) = homog n (map φ p) := by
  simp only [homog, map_sum, map_mul, map_pow, map_X, map_rename, map_homogeneousComponent]

/-- Dehomogenization does not raise the total degree. -/
lemma totalDegree_dehom_le (P : MvPolynomial (Fin 3) k) :
    (dehom P).totalDegree ≤ P.totalDegree := by
  conv_lhs => rw [P.as_sum]
  rw [map_sum]
  refine (totalDegree_finsetSum _ _).trans (Finset.sup_le fun d hd ↦ ?_)
  refine le_trans ?_ (le_totalDegree hd)
  rw [dehom, aeval_monomial, Finsupp.prod]
  refine (totalDegree_mul _ _).trans ?_
  rw [algebraMap_eq, totalDegree_C, zero_add]
  refine (totalDegree_finsetProd _ _).trans ?_
  change _ ≤ ∑ i ∈ d.support, d i
  refine Finset.sum_le_sum fun i _ ↦ (totalDegree_pow _ _).trans ?_
  refine (Nat.mul_le_mul_left _ ?_).trans (mul_one _).le
  refine Fin.cases ?_ (fun i ↦ ?_) i
  · simp
  · simp [totalDegree_X]

end Homogenization

section Equation

variable (k : Type u) [Field k] {K : Type u} [Field K] [Algebra k K] (x y : K)

/-- Evaluation at `(x, y)` through `k[s][t] ≃ k[X₀', X₁']`
(`Polynomial.Bivariate.equivMvPolynomial`, `s ↦ X₀'`, `t ↦ X₁'`). -/
lemma aeval_equivMvPolynomial (f : Polynomial (Polynomial k)) :
    aeval ![x, y] (Polynomial.Bivariate.equivMvPolynomial k f) =
      Polynomial.eval₂RingHom (Polynomial.aeval x).toRingHom y f := by
  have h : ((aeval ![x, y]).comp (Polynomial.Bivariate.equivMvPolynomial k).toAlgHom).toRingHom =
      Polynomial.eval₂RingHom (Polynomial.aeval x).toRingHom y := by
    refine Polynomial.ringHom_ext (fun r ↦ ?_) ?_
    · induction r using Polynomial.induction_on' with
      | add p q hp hq => simp only [map_add, hp, hq]
      | monomial n a =>
        rw [← Polynomial.C_mul_X_pow_eq_monomial]
        simp [Polynomial.eval₂_pow]
    · simp
  exact congrArg (fun φ : Polynomial (Polynomial k) →+* K ↦ φ f) h

lemma aeval_coords_eq_aeval_dehom (P : MvPolynomial (Fin 3) k) :
    aeval (coords x y) P = aeval ![x, y] (dehom P) := by
  rw [dehom, ← AlgHom.comp_apply, comp_aeval]
  refine congrArg (fun g ↦ aeval g P) (funext fun i ↦ ?_)
  refine Fin.cases ?_ (fun i ↦ ?_) i
  · simp [coords]
  · rw [Fin.cons_succ]
    fin_cases i <;> simp [coords]

/-- **The plane curve is a hypersurface**: if the relations between `x` and `y` are generated by
`f ∈ k[s][t]` (`k` infinite), the homogeneous prime ideal of the plane curve through `(1 : x : y)`
is generated by the homogenization `F = homog d f` of `f` (`d` its total degree), a homogeneous
polynomial of degree `d` with `F(1, s, t) = f` (`isHomogeneous_homog`, `dehom_homog`). -/
theorem toIdeal_ideal_eq_span [Infinite k] {f : Polynomial (Polynomial k)}
    (hf : RingHom.ker (Polynomial.eval₂RingHom (Polynomial.aeval x).toRingHom y) =
      Ideal.span {f}) :
    (ideal k x y).toIdeal = Ideal.span {homog
      (Polynomial.Bivariate.equivMvPolynomial k f).totalDegree
      (Polynomial.Bivariate.equivMvPolynomial k f)} := by
  set e := Polynomial.Bivariate.equivMvPolynomial k
  set g := e f
  set d := g.totalDegree
  set G := homog d g
  have hG : G.IsHomogeneous d := isHomogeneous_homog d g
  have hdG : dehom G = g := dehom_homog le_rfl
  -- the relations between `x` and `y` in `k[X₀', X₁']`
  have hker (P : MvPolynomial (Fin 2) k) (hP : aeval ![x, y] P = 0) : g ∣ P := by
    have hmem : e.symm P ∈
        RingHom.ker (Polynomial.eval₂RingHom (Polynomial.aeval x).toRingHom y) := by
      rw [RingHom.mem_ker, ← aeval_equivMvPolynomial, AlgEquiv.apply_symm_apply]
      exact hP
    rw [hf, Ideal.mem_span_singleton] at hmem
    obtain ⟨h, hh⟩ := hmem
    exact ⟨e h, by rw [← e.apply_symm_apply P, hh, map_mul]⟩
  have hg : aeval ![x, y] g = 0 := by
    rw [aeval_equivMvPolynomial, ← RingHom.mem_ker, hf]
    exact Ideal.mem_span_singleton_self f
  refine le_antisymm (fun P hP ↦ ?_) ?_
  · rw [← sum_homogeneousComponent P]
    refine Ideal.sum_mem _ fun e _ ↦ ?_
    have hPe : homogeneousComponent e P ∈ (ideal k x y).toIdeal := by
      have := (ideal k x y).isHomogeneous e hP
      change (decomposition.decompose' P e : MvPolynomial (Fin 3) k) ∈ _ at this
      rwa [decomposition.decompose'_apply] at this
    set Q := homogeneousComponent e P
    have hQ : Q.IsHomogeneous e := homogeneousComponent_isHomogeneous e P
    have h0 : aeval ![x, y] (dehom Q) = 0 := by
      rw [← aeval_coords_eq_aeval_dehom]
      exact aeval_coords_eq_zero_of_mem k x y hPe
    obtain ⟨h, hh⟩ := hker _ h0
    by_cases hQ0 : dehom Q = 0
    · rw [eq_zero_of_dehom_eq_zero hQ hQ0]
      exact zero_mem _
    have hg0 : g ≠ 0 := by rintro hg0; rw [hg0, zero_mul] at hh; exact hQ0 hh
    have hh0 : h ≠ 0 := by rintro hh0; rw [hh0, mul_zero] at hh; exact hQ0 hh
    have hdeg : d + h.totalDegree ≤ e := by
      rw [← totalDegree_mul_of_isDomain hg0 hh0, ← hh]
      exact (totalDegree_dehom_le Q).trans hQ.totalDegree_le
    have hGH : (G * homog (e - d) h).IsHomogeneous e := by
      have := hG.mul (isHomogeneous_homog (e - d) h)
      rwa [Nat.add_sub_cancel' (le_of_add_le_left hdeg)] at this
    have hQGH : Q = G * homog (e - d) h := by
      refine eq_of_dehom_eq hQ hGH ?_
      rw [map_mul, hdG, dehom_homog (by omega), hh]
    rw [hQGH]
    exact Ideal.mul_mem_right _ _ (Ideal.mem_span_singleton_self G)
  · rw [Ideal.span_le, Set.singleton_subset_iff]
    change G ∈ (ideal k x y).toIdeal
    rw [toIdeal_ideal, RingHom.mem_ker, homogeneousEval_of_isHomogeneous k x y hG,
      aeval_coords_eq_aeval_dehom, hdG, hg, map_zero, mul_zero]

end Equation

end AlgebraicGeometry.PlaneCurve
