/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.Foundations.Projective.GradedQuotient
import SGA.Foundations.Projective.ProjBaseChange
import SGA.Foundations.Projective.RelativeProj
import SGA.Foundations.Projective.ProjectiveSpace
import Mathlib.RingTheory.TensorProduct.Quotient
import Mathlib.RingTheory.TensorProduct.MvPolynomial
import Mathlib.RingTheory.Polynomial.UniqueFactorization
import Mathlib.Algebra.MvPolynomial.Nilpotent
import Mathlib.Algebra.MvPolynomial.NoZeroDivisors

/-!
# Projective hypersurfaces and their base change

For a commutative ring `R` and a homogeneous polynomial `G ∈ R[xᵢ : i ∈ σ]` of degree `d`, the
projective hypersurface `V₊(G) = Proj (R[xᵢ] ⧸ (G))` (`AlgebraicGeometry.projHypersurface`).
Its formation commutes with base change: for an `R`-algebra `R'`,
`R' ⊗_R (R[xᵢ] ⧸ (G)) ≅ R'[xᵢ] ⧸ (G')` as graded `R'`-algebras, `G'` the image of `G`
(`ProjHypersurface.baseChangeEquiv`, `ProjHypersurface.baseChangeProjIso`), so with
`Proj.isPullback_map_baseChange` the fibres of `V₊(G) ⟶ Spec R` are the hypersurfaces `V₊(G')`.

We also prove a lifting criterion for primality: if `R` is local with residue field `k`
(through `φ : R → k`), and the reduction `F = φ(G)` is a prime element of `k[xᵢ]` of the same
total degree as `G`, then `G` is prime in `R[xᵢ]` (`ProjHypersurface.prime_of_prime_map`,
`R` a unique factorization domain). This is how the lift of a plane curve to the Witt vectors
stays integral.

## References

* [EGA II, 2.8.10] (base change of `Proj`)
* [R. Hartshorne, *Algebraic Geometry*, I.2 and II.7]
-/

universe u

open CategoryTheory MvPolynomial TensorProduct AlgebraicGeometry ProjectiveSpace

noncomputable section

namespace AlgebraicGeometry.ProjHypersurface

section Ideal

variable {σ R : Type u} [CommRing R]

/-- The homogeneous ideal `(G)` of `R[xᵢ : i ∈ σ]` generated by a homogeneous polynomial `G`. -/
def ideal (G : MvPolynomial σ R) {d : ℕ} (hG : G.IsHomogeneous d) :
    HomogeneousIdeal (grading σ R) where
  toSubmodule := Ideal.span {G}
  is_homogeneous' := Ideal.homogeneous_span _ _ fun _ h ↦ ⟨d, by
    rw [Set.mem_singleton_iff.mp h]; exact mem_grading.mpr hG⟩

@[simp]
lemma toIdeal_ideal (G : MvPolynomial σ R) {d : ℕ} (hG : G.IsHomogeneous d) :
    (ideal G hG).toIdeal = Ideal.span {G} :=
  rfl

/-- The image of a homogeneous polynomial under a map of coefficients is homogeneous. -/
lemma isHomogeneous_map {S : Type*} [CommRing S] (φ : R →+* S) {G : MvPolynomial σ R} {d : ℕ}
    (hG : G.IsHomogeneous d) : (map φ G).IsHomogeneous d := fun m hm ↦
  hG fun h ↦ hm (by rw [coeff_map, h, map_zero])

/-- Mapping the coefficients does not increase the total degree. -/
lemma totalDegree_map_le {S : Type*} [CommRing S] (φ : R →+* S) (G : MvPolynomial σ R) :
    (map φ G).totalDegree ≤ G.totalDegree :=
  Finset.sup_mono (support_map_subset φ G)

/-- **Primality lifts along a local homomorphism to the residue field**: let `R` be a local
unique factorization domain, `φ : R → k` a homomorphism onto a field with kernel the maximal
ideal, and `G ∈ R[xᵢ]` such that `φ(G)` is prime in `k[xᵢ]` and has the same total degree as
`G`. Then `G` is prime. -/
theorem prime_of_prime_map [IsDomain R] [IsLocalRing R] [UniqueFactorizationMonoid R]
    {k : Type*} [Field k] (φ : R →+* k) (hker : RingHom.ker φ = IsLocalRing.maximalIdeal R)
    {G : MvPolynomial σ R} (hF : Prime (map φ G))
    (hdeg : (map φ G).totalDegree = G.totalDegree) : Prime G := by
  rw [← UniqueFactorizationMonoid.irreducible_iff_prime]
  have hG0 : G ≠ 0 := by rintro rfl; exact hF.ne_zero (by simp)
  have key (a b : MvPolynomial σ R) (hab : G = a * b) (ha : IsUnit (map φ a)) : IsUnit a := by
    have ha0 : a ≠ 0 := by rintro rfl; rw [zero_mul] at hab; exact hG0 hab
    have hb0 : b ≠ 0 := by rintro rfl; rw [mul_zero] at hab; exact hG0 hab
    have hmap : map φ G = map φ a * map φ b := by rw [hab, map_mul]
    have hFa : map φ a ≠ 0 := by intro h; rw [h, zero_mul] at hmap; exact hF.ne_zero hmap
    have hFb : map φ b ≠ 0 := by intro h; rw [h, mul_zero] at hmap; exact hF.ne_zero hmap
    have hdG : G.totalDegree = a.totalDegree + b.totalDegree := by
      rw [hab, totalDegree_mul_of_isDomain ha0 hb0]
    have hdF : (map φ G).totalDegree = (map φ a).totalDegree + (map φ b).totalDegree := by
      rw [hmap, totalDegree_mul_of_isDomain hFa hFb]
    obtain ⟨c, hc, hac⟩ := (isUnit_iff_eq_C_of_isReduced).mp ha
    have hFa0 : (map φ a).totalDegree = 0 := by rw [hac, totalDegree_C]
    have hb := totalDegree_map_le φ b
    have ha0' : a.totalDegree = 0 := by omega
    obtain ⟨r, rfl⟩ : ∃ r, a = C r := ⟨_, totalDegree_eq_zero_iff_eq_C.mp ha0'⟩
    rw [map_C] at hac
    have hr : φ r ≠ 0 := by
      intro h; rw [h] at hac; exact hc.ne_zero (C_injective σ k hac).symm
    have : r ∉ IsLocalRing.maximalIdeal R := by rwa [← hker, RingHom.mem_ker]
    exact (IsLocalRing.notMem_maximalIdeal.mp this).map C
  refine ⟨fun hGu ↦ hF.not_isUnit (hGu.map (map φ)), fun a b hab ↦ ?_⟩
  rcases hF.irreducible.isUnit_or_isUnit (show map φ G = map φ a * map φ b by
    rw [hab, map_mul]) with h | h
  · exact Or.inl (key a b hab h)
  · exact Or.inr (key b a (by rw [hab, mul_comm]) h)

end Ideal

section BaseChange

variable {σ R : Type u} [CommRing R] (R' : Type u) [CommRing R'] [Algebra R R']
  (G : MvPolynomial σ R) {d : ℕ} (hG : G.IsHomogeneous d)

/-- **Base change of a hypersurface ring**: `R' ⊗_R (R[xᵢ] ⧸ (G)) ≅ R'[xᵢ] ⧸ (G')`, where `G'` is
the image of `G` in `R'[xᵢ]`. -/
def baseChangeEquiv :
    R' ⊗[R] (MvPolynomial σ R ⧸ (ideal G hG).toIdeal) ≃ₐ[R']
      MvPolynomial σ R' ⧸
        (ideal (map (algebraMap R R') G) (isHomogeneous_map (algebraMap R R') hG)).toIdeal :=
  (Algebra.TensorProduct.tensorQuotientEquiv R' (MvPolynomial σ R) R' (ideal G hG).toIdeal).trans
    (Ideal.quotientEquivAlg _ _ (algebraTensorAlgEquiv R R') (by
      rw [toIdeal_ideal, toIdeal_ideal, Ideal.map_span, Ideal.map_span, Set.image_singleton,
        Set.image_singleton]
      refine congrArg (fun x ↦ Ideal.span {x}) ?_
      change _ = algebraTensorAlgEquiv R R' (1 ⊗ₜ G)
      rw [algebraTensorAlgEquiv_tmul, one_smul]))

lemma baseChangeEquiv_tmul (a : R') (P : MvPolynomial σ R) :
    baseChangeEquiv R' G hG (a ⊗ₜ Ideal.Quotient.mk _ P) =
      a • Ideal.Quotient.mk _ (map (algebraMap R R') P) := by
  change Ideal.Quotient.mk _ (algebraTensorAlgEquiv R R' (a ⊗ₜ P)) = _
  rw [algebraTensorAlgEquiv_tmul]
  exact map_smul (Ideal.Quotient.mkₐ R' _) a _

lemma baseChangeEquiv_symm_mk_monomial (m : σ →₀ ℕ) (c : R') :
    (baseChangeEquiv R' G hG).symm (Ideal.Quotient.mk _ (monomial m c)) =
      c ⊗ₜ Ideal.Quotient.mk _ (monomial m 1) := by
  rw [AlgEquiv.symm_apply_eq, baseChangeEquiv_tmul, map_monomial, map_one]
  change Ideal.Quotient.mkₐ R' _ (monomial m c) = c • Ideal.Quotient.mkₐ R' _ (monomial m 1)
  rw [← map_smul, smul_monomial, smul_eq_mul, mul_one]

/-- The grading of `R' ⊗_R (R[xᵢ] ⧸ (G))` (base change of the grading of `R[xᵢ] ⧸ (G)`). -/
abbrev baseChangeGrading (i : ℕ) :
    Submodule R' (R' ⊗[R] (MvPolynomial σ R ⧸ (ideal G hG).toIdeal)) :=
  ((ideal G hG).quotientGrading i).baseChange R'

lemma baseChangeEquiv_mem {i : ℕ} {x : R' ⊗[R] (MvPolynomial σ R ⧸ (ideal G hG).toIdeal)}
    (hx : x ∈ baseChangeGrading R' G hG i) :
    baseChangeEquiv R' G hG x ∈
      (ideal (map (algebraMap R R') G) (isHomogeneous_map (algebraMap R R') hG)).quotientGrading i
    := by
  obtain ⟨t, rfl⟩ := hx
  induction t using TensorProduct.induction_on with
  | zero =>
    simp only [map_zero]
    exact zero_mem _
  | tmul a z =>
    obtain ⟨_, P, hP, rfl⟩ := z
    rw [LinearMap.baseChange_tmul, Submodule.subtype_apply]
    change baseChangeEquiv R' G hG (a ⊗ₜ Ideal.Quotient.mk _ P) ∈ _
    rw [baseChangeEquiv_tmul]
    exact Submodule.smul_mem _ a (HomogeneousIdeal.mk_mem_quotientGrading
      (mem_grading.mpr (isHomogeneous_map (algebraMap R R') (mem_grading.mp hP))))
  | add t₁ t₂ h₁ h₂ =>
    simp only [map_add]
    exact add_mem h₁ h₂

lemma baseChangeEquiv_symm_mem {i : ℕ} {x : MvPolynomial σ R' ⧸
      (ideal (map (algebraMap R R') G) (isHomogeneous_map (algebraMap R R') hG)).toIdeal}
    (hx : x ∈ (ideal (map (algebraMap R R') G)
      (isHomogeneous_map (algebraMap R R') hG)).quotientGrading i) :
    (baseChangeEquiv R' G hG).symm x ∈ baseChangeGrading R' G hG i := by
  obtain ⟨Q, hQ, rfl⟩ := hx
  have hQ' : Q.IsHomogeneous i := mem_grading.mp hQ
  change (baseChangeEquiv R' G hG).symm (Ideal.Quotient.mk _ Q) ∈ _
  rw [Q.as_sum, map_sum, map_sum]
  refine Submodule.sum_mem _ fun m hm ↦ ?_
  rw [baseChangeEquiv_symm_mk_monomial]
  refine Submodule.tmul_mem_baseChange_of_mem _ (HomogeneousIdeal.mk_mem_quotientGrading ?_)
  rw [mem_grading]
  have := hQ' (mem_support_iff.mp hm)
  exact isHomogeneous_monomial _ (by rwa [Finsupp.degree_eq_weight_one])

/-- `R' ⊗_R (R[xᵢ] ⧸ (G)) → R'[xᵢ] ⧸ (G')` as a graded ring homomorphism. -/
def baseChangeGradedHom :
    baseChangeGrading R' G hG →+*ᵍ
      (ideal (map (algebraMap R R') G) (isHomogeneous_map (algebraMap R R') hG)).quotientGrading
    where
  toRingHom := (baseChangeEquiv R' G hG).toRingHom
  map_mem hx := baseChangeEquiv_mem R' G hG hx

end BaseChange

section Scheme

variable {σ R : Type u} [CommRing R]

/-- The projective hypersurface `V₊(G) = Proj (R[xᵢ : i ∈ σ] ⧸ (G))` of a homogeneous
polynomial `G`, with structure morphism `Proj.toSpecBase _ : V₊(G) ⟶ Spec R`. -/
abbrev _root_.AlgebraicGeometry.projHypersurface (G : MvPolynomial σ R) {d : ℕ}
    (hG : G.IsHomogeneous d) : Scheme.{u} :=
  Proj (ideal G hG).quotientGrading

variable (R' : Type u) [CommRing R'] [Algebra R R'] (G : MvPolynomial σ R) {d : ℕ}
  (hG : G.IsHomogeneous d)

/-- `V₊(G') ≅ Proj (R' ⊗_R (R[xᵢ] ⧸ (G)))` (`Proj` of the graded isomorphism
`baseChangeEquiv`). -/
def baseChangeProjIso :
    projHypersurface (map (algebraMap R R') G) (isHomogeneous_map (algebraMap R R') hG) ≅
      Proj (baseChangeGrading R' G hG) :=
  have := Proj.isIso_map_of_bijective (baseChangeGradedHom R' G hG)
    (baseChangeEquiv R' G hG).bijective
    (Proj.irrelevant_le_map_of_surjective _ (baseChangeEquiv R' G hG).bijective)
  asIso (Proj.map (baseChangeGradedHom R' G hG)
    (Proj.irrelevant_le_map_of_surjective _ (baseChangeEquiv R' G hG).bijective))

lemma baseChangeProjIso_hom_toSpecBase :
    (baseChangeProjIso R' G hG).hom ≫ Proj.toSpecBase (baseChangeGrading R' G hG) =
      Proj.toSpecBase _ := by
  rw [baseChangeProjIso, asIso_hom, Proj.map_toSpecBase (RingHom.id R'), CommRingCat.ofHom_id,
    Spec.map_id, Category.comp_id]
  intro r
  exact (baseChangeEquiv R' G hG).commutes r

/-- **The fibres of a hypersurface**: `V₊(G') = V₊(G) ×_{Spec R} Spec R'`
(EGA II 2.8.10 and `baseChangeEquiv`). -/
lemma isPullback_baseChange :
    IsPullback ((baseChangeProjIso R' G hG).hom ≫
        Proj.map (Proj.baseChangeGradedHom R' (ideal G hG).quotientGrading)
          (Proj.irrelevant_baseChange_le _))
      (Proj.toSpecBase _) (Proj.toSpecBase _) (Spec.map (CommRingCat.ofHom (algebraMap R R'))) := by
  refine (Proj.isPullback_map_baseChange (R' := R') (ideal G hG).quotientGrading).of_iso
    (baseChangeProjIso R' G hG).symm (Iso.refl _) (Iso.refl _) (Iso.refl _) ?_ ?_ ?_ ?_
  · rw [Iso.symm_hom, Iso.inv_hom_id_assoc, Iso.refl_hom, Category.comp_id]
  · rw [Iso.refl_hom, Category.comp_id, Iso.symm_hom, Iso.eq_inv_comp,
      baseChangeProjIso_hom_toSpecBase]
  · rw [Iso.refl_hom, Iso.refl_hom, Category.comp_id, Category.id_comp]
  · rw [Iso.refl_hom, Iso.refl_hom, Category.comp_id, Category.id_comp]

end Scheme


end AlgebraicGeometry.ProjHypersurface
