/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import Mathlib.AlgebraicGeometry.AffineSpace
import Mathlib.AlgebraicGeometry.ProjectiveSpectrum.Functor
import Mathlib.RingTheory.MvPolynomial.Ideal
import SGA.Foundations.Projective.Dehomogenization

/-!
# Projective space over an affine scheme

For a ring `R`, the projective space `ℙ(σ; Spec R)` is `Proj R[xᵢ : i ∈ σ]` (EGA II 4.1.1): the
square formed by `Proj R[σ] ⟶ Proj ℤ[σ]` (induced by `ℤ → R`) and `Proj R[σ] ⟶ Spec R` is
cartesian. This is checked on the standard affine charts `D₊(xᵢ)`, using that
`R[σ]_(xᵢ) = R ⊗ ℤ[σ]_(xᵢ)` (dehomogenization).

## Main results

- `AlgebraicGeometry.ProjectiveSpace.isPullback_proj`: the cartesian square.
- `AlgebraicGeometry.ProjectiveSpace.isoProj`: `Proj R[σ] ≅ ℙ(σ; Spec R)`, compatible with the
  projections to `Spec R` and to `Proj ℤ[σ]`, and with the standard open subsets `D₊(xᵢ)`.
- `AlgebraicGeometry.ProjectiveSpace.projFinIso`: `Proj k[x₀, …, x_r] ≅ ℙ(Fin (r + 1); Spec k)`
  (index type lifted to the universe of `k`), relating the projective space of SGA 1 XI.
- `AlgebraicGeometry.ProjectiveSpace.basicOpenIsoAffineSpace`, `ProjectiveSpace.affineSpaceι`:
  `D₊(xᵢ) ≅ 𝔸(σ ∖ {i}; S)` for any base `S` (EGA II 2.3.1).

Since `grading σ R` is by definition `MvPolynomial.homogeneousSubmodule σ R` with the grading
`MvPolynomial.gradedAlgebra`, `Proj (grading σ R)` is definitionally the scheme
`Proj (homogeneousSubmodule σ R)` used elsewhere (e.g. SGA 1 XI and the cohomology of projective
space).
-/

universe u

open CategoryTheory Limits MvPolynomial HomogeneousLocalization

namespace AlgebraicGeometry.ProjectiveSpace

section irrelevant

variable (σ : Type*) (R : Type*) [CommRing R]

lemma X_mem_irrelevant (j : σ) :
    (X j : MvPolynomial σ R) ∈ (HomogeneousIdeal.irrelevant (grading σ R)).toIdeal := by
  rw [HomogeneousIdeal.mem_iff, HomogeneousIdeal.mem_irrelevant_iff, GradedRing.proj_apply,
    DirectSum.decompose_of_mem_ne _ (X_mem_grading j) one_ne_zero]

/-- The irrelevant ideal of `R[σ]` is generated by the variables. -/
lemma irrelevant_le_span_X :
    (HomogeneousIdeal.irrelevant (grading σ R)).toIdeal ≤ Ideal.span (Set.range X) := by
  intro p hp
  rw [HomogeneousIdeal.mem_iff, HomogeneousIdeal.mem_irrelevant_iff, GradedRing.proj_apply] at hp
  have h0 : coeff 0 p = 0 := by
    have : (DirectSum.decompose (grading σ R) p 0 : MvPolynomial σ R) =
        homogeneousComponent 0 p := decomposition.decompose'_apply p 0
    rw [hp, homogeneousComponent_zero, eq_comm, C_eq_zero] at this
    exact this
  rw [← Set.image_univ, mem_ideal_span_X_image]
  intro m hm
  by_contra! H
  have : m = 0 := Finsupp.ext fun j ↦ H j (Set.mem_univ j)
  exact (mem_support_iff.mp hm) (this ▸ h0)

end irrelevant

variable (σ R : Type u) [CommRing R]

variable {σ R} in
lemma irrelevant_le_map {R' : Type u} [CommRing R'] (φ : R →+* R') :
    HomogeneousIdeal.irrelevant (grading σ R') ≤
      (HomogeneousIdeal.irrelevant (grading σ R)).map (gradingMap σ φ) := by
  rw [← toIdeal_le_toIdeal_iff]
  refine (irrelevant_le_span_X σ R').trans (Ideal.span_le.mpr ?_)
  rintro _ ⟨j, rfl⟩
  rw [← map_X_eq j φ]
  exact Ideal.mem_map_of_mem _ (X_mem_irrelevant σ R j)

/-- The structure morphism `Proj R[σ] ⟶ Spec R`. -/
noncomputable def projToSpec : Proj (grading σ R) ⟶ Spec (.of R) :=
  Proj.toSpecZero _ ≫ Spec.map (CommRingCat.ofHom (algebraMap R (grading σ R 0)))

/-- The ring homomorphism `ℤ → R`. -/
noncomputable def intCast : ULift.{u} ℤ →+* R :=
  (Int.castRingHom R).comp ULift.ringEquiv.toRingHom

/-- The morphism `Proj R[σ] ⟶ Proj ℤ[σ]` induced by `ℤ → R`. -/
noncomputable def projToProjInt : Proj (grading σ R) ⟶ Proj (grading σ (ULift.{u} ℤ)) :=
  Proj.map (gradingMap σ (intCast R)) (irrelevant_le_map _)

variable {σ R}

@[reassoc]
lemma awayι_projToSpec {t : MvPolynomial σ R} (ht : t ∈ grading σ R 1) :
    Proj.awayι _ t ht one_pos ≫ projToSpec σ R = Spec.map (CommRingCat.ofHom (awayC t)) := by
  rw [projToSpec, Proj.awayι_toSpecZero_assoc, ← Spec.map_comp]
  rfl

set_option backward.isDefEq.respectTransparency.types false in
/-- EGA II 4.1.1: `Proj R[σ]` is the base change of `Proj ℤ[σ]` to `Spec R`. -/
theorem isPullback_proj :
    IsPullback (projToProjInt σ R) (projToSpec σ R) (terminal.from _) (terminal.from _) := by
  let 𝒰 := (Proj.affineOpenCoverOfIrrelevantLESpan (grading σ (ULift.{u} ℤ)) X
    (fun i ↦ X_mem_grading i) (fun _ ↦ one_pos) (irrelevant_le_span_X σ _)).openCover
  refine Scheme.isPullback_of_openCover _ _ _ _ 𝒰 fun i' ↦ ?_
  let i : σ := i'
  let φ := gradingMap σ (intCast R)
  have P1 : IsPullback (Spec.map (CommRingCat.ofHom (Away.map φ (X i))))
      (Proj.awayι _ (φ (X i)) (φ.2 (X_mem_grading i)) one_pos)
      (Proj.awayι _ (X i) (X_mem_grading i) one_pos) (projToProjInt σ R) :=
    IsOpenImmersion.isPullback _ _ _ _ (Proj.awayι_comp_map _ _ _ _ _)
      (by rw [Proj.opensRange_awayι, Proj.opensRange_awayι]; rfl)
  have := isIso_of_isTerminal specULiftZIsTerminal terminalIsTerminal (terminal.from _)
  have Q0 := isPullback_SpecMap_of_isPushout _ _ _ _ (isPushout_away i (intCast R))
  have Q : IsPullback (Spec.map (CommRingCat.ofHom (Away.map φ (X i))))
      (Proj.awayι _ (φ (X i)) (φ.2 (X_mem_grading i)) one_pos ≫ projToSpec σ R)
      (Proj.awayι _ (X i) (X_mem_grading i) one_pos ≫ terminal.from _)
      (terminal.from (Spec (.of R))) :=
    Q0.of_iso (Iso.refl _) (Iso.refl _) (Iso.refl _) (asIso (terminal.from _)) (by simp [φ])
      (by rw [Iso.refl_hom, Iso.refl_hom, Category.comp_id, Category.id_comp]
          exact (awayι_projToSpec _).symm) (terminal.hom_ext _ _) (terminal.hom_ext _ _)
  refine Q.of_iso P1.flip.isoPullback (Iso.refl _) (Iso.refl _) (Iso.refl _) ?_ ?_
    (terminal.hom_ext _ _) (by simp)
  · exact (Category.comp_id _).trans (IsPullback.isoPullback_hom_snd P1.flip).symm
  · exact (Category.comp_id _).trans
      ((congrArg (· ≫ projToSpec σ R) (IsPullback.isoPullback_hom_fst P1.flip)).symm.trans
        (Category.assoc _ _ _))

variable (σ R)

/-- EGA II 4.1.1: `Proj R[σ] ≅ ℙ(σ; Spec R)`. -/
noncomputable def isoProj : Proj (grading σ R) ≅ ℙ(σ; Spec (.of R)) :=
  (isPullback_proj (σ := σ) (R := R)).flip.isoPullback

@[reassoc (attr := simp)]
lemma isoProj_hom_over :
    (isoProj σ R).hom ≫ ℙ(σ; Spec (.of R)) ↘ Spec (.of R) = projToSpec σ R :=
  IsPullback.isoPullback_hom_fst _

@[reassoc (attr := simp)]
lemma isoProj_hom_toProj : (isoProj σ R).hom ≫ toProj σ _ = projToProjInt σ R :=
  IsPullback.isoPullback_hom_snd _

variable {σ}

/-- `isoProj` identifies the standard open subsets `D₊(xᵢ)`. -/
lemma isoProj_hom_preimage_basicOpen (i : σ) :
    (isoProj σ R).hom ⁻¹ᵁ basicOpen _ i = Proj.basicOpen (grading σ R) (X i) := by
  rw [basicOpen, ← Scheme.Hom.comp_preimage, isoProj_hom_toProj, projToProjInt,
    Proj.map_preimage_basicOpen]
  exact congrArg _ (map_X_eq i _)

section rename

variable {σ σ' : Type*} {R : Type*} [CommRing R]

/-- The graded ring homomorphism `R[σ] → R[σ']` induced by `e : σ → σ'`. -/
noncomputable def gradingRename (e : σ → σ') : grading σ R →+*ᵍ grading σ' R where
  toRingHom := (rename e).toRingHom
  map_mem hx := mem_grading.mpr ((mem_grading.mp hx).rename_isHomogeneous)

@[simp]
lemma gradingRename_apply (e : σ → σ') (p : MvPolynomial σ R) :
    gradingRename e p = rename e p :=
  rfl

lemma irrelevant_le_map_rename (e : σ ≃ σ') :
    HomogeneousIdeal.irrelevant (grading σ' R) ≤
      (HomogeneousIdeal.irrelevant (grading σ R)).map (gradingRename (R := R) e) := by
  rw [← toIdeal_le_toIdeal_iff]
  refine (irrelevant_le_span_X σ' R).trans (Ideal.span_le.mpr ?_)
  rintro _ ⟨j, rfl⟩
  rw [show (X j : MvPolynomial σ' R) = gradingRename e (X (e.symm j)) by simp]
  exact Ideal.mem_map_of_mem _ (X_mem_irrelevant σ R _)

lemma gradingRename_comp (e : σ ≃ σ') :
    (gradingRename (R := R) e.symm).comp (gradingRename e) = GradedRingHom.id _ :=
  GradedRingHom.ext fun p ↦ by simp [rename_rename]

end rename

section renameIso

variable {σ : Type} {σ' R : Type u} [CommRing R]

set_option backward.isDefEq.respectTransparency false in
/-- A bijection `σ ≃ σ'` induces `Proj R[σ] ≅ Proj R[σ']` (for `σ` a small type, e.g.
`Fin (n + 1)`, and `σ'` in the universe of `R`). -/
noncomputable def projRenameIso (e : σ ≃ σ') : Proj (grading σ R) ≅ Proj (grading σ' R) where
  hom := Proj.map (gradingRename e.symm) (irrelevant_le_map_rename e.symm)
  inv := Proj.map (gradingRename e) (irrelevant_le_map_rename e)
  hom_inv_id := by
    rw [← Proj.map_comp (gradingRename e) (gradingRename e.symm) (irrelevant_le_map_rename e)
      (irrelevant_le_map_rename e.symm)]
    convert Proj.map_id (𝒜 := grading σ R) using 2
    exact gradingRename_comp e
  inv_hom_id := by
    rw [← Proj.map_comp (gradingRename e.symm) (gradingRename e)
      (irrelevant_le_map_rename e.symm) (irrelevant_le_map_rename e)]
    convert Proj.map_id (𝒜 := grading σ' R) using 2
    exact gradingRename_comp e.symm

end renameIso

/-- EGA II 4.1.1: `ℙʳ_k = Proj k[x₀, …, x_r]` is `ℙ(Fin (r + 1); Spec k)` (up to lifting the index
type to the universe of `k`). Note that `Proj (grading (Fin (r + 1)) k)` is by definition
`Proj (MvPolynomial.homogeneousSubmodule (Fin (r + 1)) k)`, the projective space of SGA 1 XI. -/
noncomputable def projFinIso (k : Type u) [CommRing k] (r : ℕ) :
    Proj (grading (Fin (r + 1)) k) ≅ ℙ(ULift.{u} (Fin (r + 1)); Spec (.of k)) :=
  projRenameIso Equiv.ulift.symm ≪≫ isoProj (ULift.{u} (Fin (r + 1))) k

section affineSpace

variable (S : Scheme.{u})

set_option backward.isDefEq.respectTransparency.types false in
/-- EGA II 2.3.1: the standard open subset `D₊(xᵢ)` of `ℙ(σ; S)` is the affine space over `S`
with coordinates `xⱼ / xᵢ`, `j ≠ i`. -/
lemma isPullback_basicOpen_affineSpace (i : σ) :
    IsPullback ((basicOpen S i).ι ≫ ℙ(σ; S) ↘ S)
      (toProj σ S ∣_ Proj.basicOpen (grading σ (ULift.{u} ℤ)) (X i) ≫
        (Proj.basicOpenIsoSpec _ (X i) (X_mem_grading i) one_pos).hom ≫
          Spec.map (CommRingCat.ofHom (awayEquiv i rfl).symm.toRingHom))
      (terminal.from S) (terminal.from (Spec (.of (MvPolynomial {j // j ≠ i} (ULift.{u} ℤ))))) :=
  (isPullback_basicOpen S i).flip.of_iso (Iso.refl _) (Iso.refl _)
    (Proj.basicOpenIsoSpec _ (X i) (X_mem_grading i) one_pos ≪≫
      Scheme.Spec.mapIso (awayEquiv i rfl).toCommRingCatIso.op.symm) (Iso.refl _)
    (by simp only [Iso.refl_hom, Category.comp_id]; rfl)
    (by simp; rfl) (by simp) (terminal.hom_ext _ _)

/-- EGA II 2.3.1: `D₊(xᵢ) ≅ 𝔸(σ ∖ {i}; S)`. -/
noncomputable def basicOpenIsoAffineSpace (i : σ) :
    (basicOpen S i).toScheme ≅ 𝔸({j // j ≠ i}; S) :=
  (isPullback_basicOpen_affineSpace S i).isoPullback

@[reassoc (attr := simp)]
lemma basicOpenIsoAffineSpace_hom_over (i : σ) :
    (basicOpenIsoAffineSpace S i).hom ≫ 𝔸({j // j ≠ i}; S) ↘ S =
      (basicOpen S i).ι ≫ ℙ(σ; S) ↘ S :=
  IsPullback.isoPullback_hom_fst _

/-- The open immersion `𝔸(σ ∖ {i}; S) ⟶ ℙ(σ; S)` onto `D₊(xᵢ)`. -/
noncomputable def affineSpaceι (i : σ) : 𝔸({j // j ≠ i}; S) ⟶ ℙ(σ; S) :=
  (basicOpenIsoAffineSpace S i).inv ≫ (basicOpen S i).ι

instance (i : σ) : IsOpenImmersion (affineSpaceι S i) :=
  IsOpenImmersion.comp _ _

@[reassoc (attr := simp)]
lemma affineSpaceι_over (i : σ) :
    affineSpaceι S i ≫ ℙ(σ; S) ↘ S = 𝔸({j // j ≠ i}; S) ↘ S := by
  change ((basicOpenIsoAffineSpace S i).inv ≫ (basicOpen S i).ι) ≫ _ = _
  rw [Category.assoc, Iso.inv_comp_eq, basicOpenIsoAffineSpace_hom_over]

lemma opensRange_affineSpaceι (i : σ) : (affineSpaceι S i).opensRange = basicOpen S i := by
  change ((basicOpenIsoAffineSpace S i).inv ≫ (basicOpen S i).ι).opensRange = _
  rw [Scheme.Hom.opensRange_comp_of_isIso, Scheme.Opens.opensRange_ι]

end affineSpace

end AlgebraicGeometry.ProjectiveSpace
