/-
Copyright (c) 2026 SGAenglishpluslean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SGAenglishpluslean contributors
-/
import Mathlib.AlgebraicGeometry.Morphisms.Finite
import Mathlib.AlgebraicGeometry.Noetherian
import Mathlib.AlgebraicGeometry.Sites.SmallAffineZariski

/-!
# Gluing finite subalgebras of a quasi-coherent integral algebra

Let `P` be a presheaf of rings on a scheme `Y` with a morphism `α : 𝒪_Y ⟶ P` which is
"quasi-coherent" over the affine opens (`P(D(r)) = P(U)[1/r]` for `U` affine) and integral over
`𝒪_Y`. Given a finite cover of `Y` by open subsets `Uₖ` and subrings `Bₖ ⊆ P(Uₖ)` containing the
image of `Γ(Y, Uₖ)`, we define the subpresheaf `𝔅 = glob U B` of sections of `P` which, on every
affine open `W ⊆ Uₖ`, lie in the subring generated by `Bₖ` and `Γ(Y, W)`
(`loc`). When `Y` is noetherian it is again quasi-coherent over the affine opens
(`exists_pow_mul_mem_glob`, `coequifibered_globι`), so it glues to a `Y`-scheme with
`Scheme.AffineZariskiSite.relativeGluingData`, finite over `Y` as soon as the `Bₖ` are finite
(`glob_le`, `isFinite_toBase_of_cover`). It coincides with `P` after inverting any section `c` of
`P(Uₖ)` lying in the radical of the ideals generated by finitely many "good" elements of the `Bₖ'`
(`exists_pow_mul_mem_glob_of_radical`). This is the extension of coherent subsheaves of
EGA I 9.4.7, in the form needed for VIII.6.4.

The algebraic input is `exists_pow_mul_mem_of_mem_radical`: if `A` is integral over a subring
`B`, `A_b = B_b` for finitely many `b ∈ B` and `c` lies in the radical of `(b)A`, then `A_c = B_c`.
-/

universe u

open CategoryTheory Opposite TopologicalSpace AlgebraicGeometry

namespace SGA.SGA1.ExposeVIII

section Radical

set_option backward.isDefEq.respectTransparency false in
/-- Let `A` be integral over `R`, `B` an `R`-subalgebra of `A`, and `s` a finite subset of `B` such
that every element of `A` times a power of `b ∈ s` lies in `B` (i.e. `A_b = B_b`). If `c` lies in
the radical of the ideal of `A` generated by `s`, then every element of `A` times a power of `c`
lies in `B`. -/
theorem exists_pow_mul_mem_of_mem_radical {R A : Type*} [CommRing R] [CommRing A] [Algebra R A]
    [Algebra.IsIntegral R A] (B : Subalgebra R A) (s : Finset A) (hsB : ∀ b ∈ s, b ∈ B)
    (hs : ∀ b ∈ s, ∀ a : A, ∃ n, b ^ n * a ∈ B) {c : A}
    (hc : c ∈ (Ideal.span (s : Set A)).radical) (a : A) : ∃ N, ∀ n, N ≤ n → c ^ n * a ∈ B := by
  classical
  obtain ⟨K, hK⟩ := hc
  obtain ⟨d, -, hd⟩ := Submodule.mem_span_finset.mp hK
  -- the finite subalgebra `C` generated by `c`, `a`, `s` and the coefficients `d b`
  let T : Finset A := insert c (insert a (s ∪ s.image d))
  let C := Algebra.adjoin R (T : Set A)
  obtain ⟨E, hE⟩ := fg_adjoin_of_finite T.finite_toSet fun x _ ↦
    Algebra.IsIntegral.isIntegral (R := R) x
  have hTC {x : A} (hx : x ∈ T) : x ∈ C := Algebra.subset_adjoin hx
  -- a uniform exponent `P` with `b ^ P * C ⊆ B`
  let n : A → A → ℕ := fun b e ↦ if hb : b ∈ s then (hs b hb e).choose else 0
  let P := ∑ b ∈ s, ∑ e ∈ E, n b e
  have hP (b) (hb : b ∈ s) (e) (he : e ∈ E) : b ^ P * e ∈ B := by
    have hn : b ^ n b e * e ∈ B := by
      simp only [n, hb, ↓reduceDIte]
      exact (hs b hb e).choose_spec
    have hle : n b e ≤ P :=
      (Finset.single_le_sum (fun e _ ↦ Nat.zero_le (n b e)) he).trans
        (Finset.single_le_sum (fun b _ ↦ Nat.zero_le (∑ e ∈ E, n b e)) hb)
    rw [← Nat.sub_add_cancel hle, pow_add, mul_assoc]
    exact B.mul_mem (B.pow_mem (hsB b hb) _) hn
  have hPC (b) (hb : b ∈ s) (x) (hx : x ∈ C) : b ^ P * x ∈ B := by
    have hx' : x ∈ Submodule.span R (E : Set A) := by rw [hE]; exact hx
    clear hx
    induction hx' using Submodule.span_induction with
    | mem e he => exact hP b hb e he
    | zero => simp
    | add x y _ _ hx hy => rw [mul_add]; exact B.add_mem hx hy
    | smul r x _ hx => rw [mul_smul_comm]; exact B.smul_mem hx r
  -- in the ring `C`: `c ^ K = ∑ d b * b`, so a power of `c` lies in the ideal of the `b ^ (P + 1)`
  have hdT (b : A) (hb : b ∈ s) : d b ∈ T :=
    Finset.mem_insert_of_mem (Finset.mem_insert_of_mem
      (Finset.mem_union_right _ (Finset.mem_image_of_mem d hb)))
  have hsT (b : A) (hb : b ∈ s) : b ∈ T :=
    Finset.mem_insert_of_mem (Finset.mem_insert_of_mem (Finset.mem_union_left _ hb))
  let f : s → C := fun b ↦ ⟨d b * b, C.mul_mem (hTC (hdT b b.2)) (hTC (hsT b b.2))⟩
  have hsum : ((∑ i, f i : C) : A) = c ^ K := by
    rw [← hd, ← Finset.sum_coe_sort s]
    simp [f]
  have hmem := Ideal.sum_pow_mem_span_pow (Finset.univ : Finset s) f P
  rw [← Finset.coe_image] at hmem
  obtain ⟨g, -, hg⟩ := Submodule.mem_span_finset.mp hmem
  have ha : a ∈ C := hTC (by simp [T])
  have hcC : c ∈ C := hTC (by simp [T])
  have key (y) (hy : y ∈ C) : ∀ x ∈ Finset.univ.image (fun i ↦ f i ^ (P + 1)),
      ((g x * x : C) : A) * y ∈ B := by
    intro x hx
    obtain ⟨i, -, rfl⟩ := Finset.mem_image.mp hx
    have e : ((g (f i ^ (P + 1)) * f i ^ (P + 1) : C) : A) * y =
        (i : A) ^ P * ((g (f i ^ (P + 1)) : A) * d i ^ (P + 1) * i * y) := by
      simp only [Subalgebra.coe_mul, Subalgebra.coe_pow, f]
      ring
    rw [e]
    exact hPC i i.2 _ (C.mul_mem (C.mul_mem (C.mul_mem (g _).2
      (C.pow_mem (hTC (hdT i i.2)) _)) (hTC (hsT i i.2))) hy)
  refine ⟨K * ((Finset.univ : Finset s).card * P + 1), fun n hn ↦ ?_⟩
  have e : c ^ (K * ((Finset.univ : Finset s).card * P + 1)) * (c ^ (n - K *
      ((Finset.univ : Finset s).card * P + 1)) * a) =
      ∑ x ∈ Finset.univ.image (fun i ↦ f i ^ (P + 1)),
        ((g x * x : C) : A) * (c ^ (n - K * ((Finset.univ : Finset s).card * P + 1)) * a) := by
    rw [← Finset.sum_mul, pow_mul, ← hsum, ← SubmonoidClass.coe_pow, ← hg,
      AddSubmonoidClass.coe_finsetSum]
    simp only [smul_eq_mul]
  rw [← Nat.add_sub_cancel' hn, pow_add, mul_assoc, e]
  exact sum_mem (key _ (C.mul_mem (C.pow_mem hcC _) ha))

end Radical

/-- A criterion for a restriction of a ring homomorphism between subrings to be a localization
away from an element. -/
lemma isLocalization_away_restrict {A A' : Type*} [CommRing A] [CommRing A'] (φ : A →+* A')
    (R : Subring A) (R' : Subring A') (hφ : ∀ x ∈ R, φ x ∈ R') {t : A} (ht : t ∈ R)
    (hunit : ∃ u ∈ R', φ t * u = 1)
    (hsurj : ∀ z ∈ R', ∃ (m : ℕ) (a : A), a ∈ R ∧ z * φ t ^ m = φ a)
    (heq : ∀ a ∈ R, ∀ b ∈ R, φ a = φ b → ∃ m, t ^ m * a = t ^ m * b) :
    letI := (φ.restrict R R' hφ).toAlgebra
    IsLocalization.Away (⟨t, ht⟩ : R) R' := by
  let _ := (φ.restrict R R' hφ).toAlgebra
  obtain ⟨u, hu, e⟩ := hunit
  refine IsLocalization.Away.mk _ (IsUnit.of_mul_eq_one ⟨u, hu⟩ (Subtype.ext e))
    (fun z ↦ ?_) (fun a b hab ↦ ?_)
  · obtain ⟨m, a, ha, e⟩ := hsurj z.1 z.2
    exact ⟨m, ⟨a, ha⟩, Subtype.ext e⟩
  · obtain ⟨m, hm⟩ := heq a.1 a.2 b.1 b.2 (congrArg Subtype.val hab)
    exact ⟨m, Subtype.ext hm⟩

set_option backward.isDefEq.respectTransparency.types false in
/-- The scheme glued from a quasi-coherent algebra `F` over the affine opens of `Y` is finite over
`Y` as soon as `F` is finite over a covering family of affine opens. -/
theorem isFinite_toBase_of_cover {Y : Scheme.{u}} {F : Y.AffineZariskiSiteᵒᵖ ⥤ CommRingCat.{u}}
    {β : (Scheme.AffineZariskiSite.toOpensFunctor Y).op ⋙ Y.presheaf ⟶ F} (H : β.Coequifibered)
    {K : Type*} (W : K → Y.AffineZariskiSite) (hcov : ⨆ k, (W k).1 = ⊤)
    (hfin : ∀ k, (β.app (op (W k))).hom.Finite) :
    IsFinite (Scheme.AffineZariskiSite.relativeGluingData H).toBase := by
  let d := Scheme.AffineZariskiSite.relativeGluingData H
  refine IsZariskiLocalAtTarget.of_iSup_eq_top (fun k ↦ (W k).1) hcov fun k ↦ ?_
  have h₁ := d.isPullback_natTrans_ι_toBase (W k)
  have h₂ := isPullback_morphismRestrict d.toBase (W k).1
  have : IsIso ((Scheme.AffineZariskiSite.restrictIsoSpec Y).inv.app (W k)) :=
    (inferInstance : IsIso ((Scheme.AffineZariskiSite.restrictIsoSpec Y).app (W k)).inv)
  have hP : IsFinite (d.natTrans.app (W k)) := by
    change IsFinite (Spec.map (β.app (op (W k))) ≫
      (Scheme.AffineZariskiSite.restrictIsoSpec Y).inv.app (W k))
    rw [MorphismProperty.cancel_right_of_respectsIso @IsFinite]
    exact (IsFinite.SpecMap_iff _).mpr (hfin k)
  refine (MorphismProperty.arrow_mk_iso_iff @IsFinite
    (Arrow.isoMk (h₁.isoIsPullback _ _ h₂) (Iso.refl _) ?_)).mp hP
  simp only [Iso.refl_hom, Category.comp_id]
  exact IsPullback.isoIsPullback_hom_fst _ _ h₁ h₂

section Presheaf

variable {Y : Scheme.{u}} (P : Y.Opensᵒᵖ ⥤ CommRingCat.{u}) (α : Y.presheaf ⟶ P)

/-- Restriction of sections of a presheaf of rings on `Y`. -/
noncomputable abbrev res {U V : Y.Opens} (h : V ≤ U) : P.obj (op U) →+* P.obj (op V) :=
  (P.map (homOfLE h).op).hom

variable {P}

@[simp]
lemma res_res {U V W : Y.Opens} (h : V ≤ U) (h' : W ≤ V) (x : P.obj (op U)) :
    res P h' (res P h x) = res P (h'.trans h) x := by
  rw [res, res, res, ← CommRingCat.comp_apply, ← P.map_comp]
  rfl

@[simp]
lemma res_self {U : Y.Opens} (h : U ≤ U) (x : P.obj (op U)) : res P h x = x := by
  rw [res, show homOfLE h = 𝟙 U from rfl, op_id, P.map_id]
  rfl

@[simp]
lemma res_app {U V : Y.Opens} (h : V ≤ U) (r : Γ(Y, U)) :
    res P h (α.app (op U) r) = α.app (op V) (Y.presheaf.map (homOfLE h).op r) := by
  rw [res, ← CommRingCat.comp_apply, ← α.naturality]
  rfl

/-- For `W ⊆ U`, the subring of `P(W)` generated by the restrictions of the elements of a subring
`B` of `P(U)` and the image of `Γ(Y, W)`: the sections of the subsheaf generated by `B` if `W` is
affine. -/
def loc {U : Y.Opens} (B : Subring (P.obj (op U))) {W : Y.Opens} (hW : W ≤ U) :
    Subring (P.obj (op W)) :=
  Subring.closure (res P hW '' B ∪ Set.range (α.app (op W)))

variable {α}

lemma res_mem_loc {U W : Y.Opens} {B : Subring (P.obj (op U))} (hW : W ≤ U) {b : P.obj (op U)}
    (hb : b ∈ B) : res P hW b ∈ loc α B hW :=
  Subring.subset_closure (Or.inl ⟨b, hb, rfl⟩)

lemma app_mem_loc {U W : Y.Opens} {B : Subring (P.obj (op U))} (hW : W ≤ U) (r : Γ(Y, W)) :
    α.app (op W) r ∈ loc α B hW :=
  Subring.subset_closure (Or.inr ⟨r, rfl⟩)

lemma loc_res {U W W' : Y.Opens} {B : Subring (P.obj (op U))} (hW : W ≤ U) (h' : W' ≤ W)
    {x : P.obj (op W)} (hx : x ∈ loc α B hW) : res P h' x ∈ loc α B (h'.trans hW) := by
  have : (loc α B hW).map (res P h') ≤ loc α B (h'.trans hW) := by
    rw [loc, RingHom.map_closure]
    refine Subring.closure_le.mpr ?_
    rintro _ ⟨_, ⟨b, hb, rfl⟩ | ⟨r, rfl⟩, rfl⟩
    · rw [res_res]
      exact res_mem_loc _ hb
    · rw [res_app]
      exact app_mem_loc _ _
  exact this ⟨x, hx, rfl⟩

lemma loc_le {U : Y.Opens} {B : Subring (P.obj (op U))} (hB : ∀ r, α.app (op U) r ∈ B) :
    loc α B (le_refl U) ≤ B := by
  refine Subring.closure_le.mpr ?_
  rintro _ (⟨b, hb, rfl⟩ | ⟨r, rfl⟩)
  · rw [SetLike.mem_coe, res_self]
    exact hb
  · exact hB r

lemma isUnit_res_app_basicOpen {W : Y.Opens} (h : Γ(Y, W)) :
    IsUnit (res P (Y.basicOpen_le h) (α.app (op W) h)) := by
  rw [res_app]
  exact (Y.toRingedSpace.isUnit_res_basicOpen h).map _

set_option backward.isDefEq.respectTransparency false in
/-- Sections of `loc B` over a basic open `D(h)` of an affine `W` are fractions of sections over
`W` with denominator a power of `h`. -/
lemma exists_pow_mul_mem_loc {U W : Y.Opens} {B : Subring (P.obj (op U))} (hW : W ≤ U)
    (hWa : IsAffineOpen W) (h : Γ(Y, W)) {x : P.obj (op (Y.basicOpen h))}
    (hx : x ∈ loc α B ((Y.basicOpen_le h).trans hW)) :
    ∃ n, ∃ y ∈ loc α B hW,
      res P (Y.basicOpen_le h) y = res P (Y.basicOpen_le h) (α.app (op W) h) ^ n * x := by
  induction hx using Subring.closure_induction with
  | mem x hx =>
    rcases hx with ⟨b, hb, rfl⟩ | ⟨s, rfl⟩
    · exact ⟨0, res P hW b, res_mem_loc _ hb, by rw [res_res, pow_zero, one_mul]⟩
    · have := hWa.isLocalization_basicOpen h
      obtain ⟨⟨s', _, n, rfl⟩, e⟩ := IsLocalization.surj (Submonoid.powers h) s
      refine ⟨n, α.app (op W) s', app_mem_loc _ _, ?_⟩
      have e' : Y.presheaf.map (homOfLE (Y.basicOpen_le h)).op s' =
          s * Y.presheaf.map (homOfLE (Y.basicOpen_le h)).op (h ^ n) := e.symm
      rw [res_app, res_app, e', map_mul, map_pow, map_pow, mul_comm]
  | zero => exact ⟨0, 0, zero_mem _, by rw [map_zero, mul_zero]⟩
  | one => exact ⟨0, 1, one_mem _, by rw [map_one, pow_zero, one_mul]⟩
  | add x y _ _ hx hy =>
    obtain ⟨n₁, y₁, hy₁, e₁⟩ := hx
    obtain ⟨n₂, y₂, hy₂, e₂⟩ := hy
    refine ⟨n₁ + n₂, α.app (op W) h ^ n₂ * y₁ + α.app (op W) h ^ n₁ * y₂,
      add_mem (mul_mem (pow_mem (app_mem_loc _ _) _) hy₁)
        (mul_mem (pow_mem (app_mem_loc _ _) _) hy₂), ?_⟩
    rw [map_add, map_mul, map_mul, map_pow, map_pow, e₁, e₂]
    ring
  | neg x _ hx =>
    obtain ⟨n, y, hy, e⟩ := hx
    exact ⟨n, -y, neg_mem hy, by rw [map_neg, e, mul_neg]⟩
  | mul x y _ _ hx hy =>
    obtain ⟨n₁, y₁, hy₁, e₁⟩ := hx
    obtain ⟨n₂, y₂, hy₂, e₂⟩ := hy
    refine ⟨n₁ + n₂, y₁ * y₂, mul_mem hy₁ hy₂, ?_⟩
    rw [map_mul, e₁, e₂]
    ring

variable (hloc₁ : ∀ (W : Y.Opens), IsAffineOpen W → ∀ (h : Γ(Y, W)) (a b : P.obj (op W)),
  res P (Y.basicOpen_le h) a = res P (Y.basicOpen_le h) b →
    ∃ m, α.app (op W) h ^ m * a = α.app (op W) h ^ m * b)

include hloc₁ in
/-- Membership in `loc B` over an affine `W` is local on `W`: it may be checked on the basic open
subsets of a covering. -/
lemma mem_loc_of_span_eq_top {U W : Y.Opens} {B : Subring (P.obj (op U))} (hW : W ≤ U)
    (hWa : IsAffineOpen W) (t : Finset Γ(Y, W)) (ht : Ideal.span (t : Set Γ(Y, W)) = ⊤)
    {x : P.obj (op W)}
    (hx : ∀ h ∈ t, res P (Y.basicOpen_le h) x ∈ loc α B ((Y.basicOpen_le h).trans hW)) :
    x ∈ loc α B hW := by
  classical
  have H (h) (hh : h ∈ t) : ∃ N, α.app (op W) h ^ N * x ∈ loc α B hW := by
    obtain ⟨n, y, hy, e⟩ := exists_pow_mul_mem_loc hW hWa h (hx h hh)
    rw [← map_pow, ← map_mul] at e
    obtain ⟨m, hm⟩ := hloc₁ W hWa h _ _ e
    refine ⟨m + n, ?_⟩
    rw [pow_add, mul_assoc, ← hm]
    exact mul_mem (pow_mem (app_mem_loc _ _) _) hy
  choose! N hN using H
  let M := ∑ h ∈ t, N h
  have hM (h) (hh : h ∈ t) : α.app (op W) h ^ M * x ∈ loc α B hW := by
    have hle : N h ≤ M := Finset.single_le_sum (fun h _ ↦ Nat.zero_le (N h)) hh
    rw [← Nat.sub_add_cancel hle, pow_add, mul_assoc]
    exact mul_mem (pow_mem (app_mem_loc _ _) _) (hN h hh)
  have ht' := Ideal.span_pow_eq_top _ ht M
  rw [← Finset.coe_image, Ideal.eq_top_iff_one] at ht'
  obtain ⟨c, -, hc⟩ := Submodule.mem_span_finset.mp ht'
  have e : x = ∑ g ∈ t.image (fun h ↦ h ^ M), α.app (op W) (c g) * (α.app (op W) g * x) := by
    calc x = α.app (op W) 1 * x := by rw [map_one, one_mul]
      _ = _ := by
        rw [← hc, map_sum, Finset.sum_mul]
        refine Finset.sum_congr rfl fun g _ ↦ ?_
        rw [smul_eq_mul, map_mul, mul_assoc]
  rw [e]
  refine sum_mem fun g hg ↦ ?_
  obtain ⟨h, hh, rfl⟩ := Finset.mem_image.mp hg
  rw [map_pow]
  exact mul_mem (app_mem_loc _ _) (hM h hh)

include hloc₁ in
/-- If a section of `P` over `V` lies in `loc B` on the members of a family of opens, it lies in
`loc B` on every affine open covered by the family. -/
lemma res_mem_loc_of_cover {U V : Y.Opens} {B : Subring (P.obj (op U))} {ι : Type*}
    (Wl : ι → Y.Opens) (hWl : ∀ l, Wl l ≤ V) (hWU : ∀ l, Wl l ≤ U) {x : P.obj (op V)}
    (hx : ∀ l, res P (hWl l) x ∈ loc α B (hWU l)) {W : Y.Opens} (hWa : IsAffineOpen W)
    (h₁ : W ≤ V) (h₂ : W ≤ U) (hcov : W ≤ ⨆ l, Wl l) : res P h₁ x ∈ loc α B h₂ := by
  classical
  have H (y : W) : ∃ (g : Γ(Y, W)) (l : ι), Y.basicOpen g ≤ Wl l ∧ (y : Y) ∈ Y.basicOpen g := by
    obtain ⟨l, hl⟩ := Opens.mem_iSup.mp (hcov y.2)
    obtain ⟨g, hg, hyg⟩ := hWa.exists_basicOpen_le ⟨y, hl⟩ y.2
    exact ⟨g, l, hg, hyg⟩
  choose g l hgl hyg using H
  obtain ⟨t, ht⟩ := hWa.isCompact.elim_finite_subcover (fun y : W ↦ (Y.basicOpen (g y) : Set Y))
    (fun y ↦ (Y.basicOpen (g y)).isOpen) (fun y hy ↦ Set.mem_iUnion.mpr ⟨⟨y, hy⟩, hyg ⟨y, hy⟩⟩)
  refine mem_loc_of_span_eq_top hloc₁ h₂ hWa (t.image g) ?_ fun h hh ↦ ?_
  · rw [← hWa.self_le_iSup_basicOpen_iff]
    intro y hy
    obtain ⟨z, hz, hyz⟩ := Set.mem_iUnion₂.mp (ht hy)
    exact Opens.mem_iSup.mpr ⟨⟨g z, Finset.mem_coe.mpr (Finset.mem_image_of_mem g hz)⟩, hyz⟩
  · obtain ⟨z, -, rfl⟩ := Finset.mem_image.mp hh
    rw [res_res]
    have := loc_res (hWU (l z)) (hgl z) (hx (l z))
    rwa [res_res] at this

section Glob

variable (α) {K : Type*} (U : K → Y.Opens) (B : ∀ k, Subring (P.obj (op (U k))))

/-- The sections of `P` over `V` which, on every affine open `W ⊆ V ∩ Uₖ`, lie in the subring
`loc Bₖ` generated by `Bₖ` and `Γ(Y, W)`. -/
noncomputable def glob (V : Y.Opens) : Subring (P.obj (op V)) :=
  ⨅ (k : K) (W : Y.Opens) (_ : IsAffineOpen W) (h₁ : W ≤ V) (h₂ : W ≤ U k),
    (loc α (B k) h₂).comap (res P h₁)

variable {α U B}

lemma mem_glob_iff {V : Y.Opens} {x : P.obj (op V)} :
    x ∈ glob α U B V ↔ ∀ k (W : Y.Opens), IsAffineOpen W → ∀ (h₁ : W ≤ V) (h₂ : W ≤ U k),
      res P h₁ x ∈ loc α (B k) h₂ := by
  simp only [glob, Subring.mem_iInf, Subring.mem_comap]

lemma res_mem_glob {V V' : Y.Opens} (h : V' ≤ V) {x : P.obj (op V)} (hx : x ∈ glob α U B V) :
    res P h x ∈ glob α U B V' := by
  rw [mem_glob_iff] at hx ⊢
  intro k W hW h₁ h₂
  rw [res_res]
  exact hx k W hW _ h₂

lemma app_mem_glob {V : Y.Opens} (r : Γ(Y, V)) : α.app (op V) r ∈ glob α U B V := by
  rw [mem_glob_iff]
  intro k W _ h₁ h₂
  rw [res_app]
  exact app_mem_loc _ _

lemma glob_le (k : K) (hB : ∀ r, α.app (op (U k)) r ∈ B k) (hU : IsAffineOpen (U k)) :
    glob α U B (U k) ≤ B k := fun x hx ↦
  loc_le hB (by simpa using mem_glob_iff.mp hx k (U k) hU le_rfl le_rfl)

end Glob

/-- In a noetherian scheme, the intersection of an affine open `V` with an open `O` is covered by
finitely many basic open subsets of `V` contained in `O`. -/
lemma exists_finset_basicOpen_le [NoetherianSpace Y] {V : Y.Opens} (hV : IsAffineOpen V)
    (O : Y.Opens) : ∃ t : Finset Γ(Y, V), (∀ g ∈ t, Y.basicOpen g ≤ O) ∧
      V ⊓ O ≤ ⨆ g ∈ t, Y.basicOpen g := by
  classical
  have H (y : ↥(V ⊓ O)) : ∃ g : Γ(Y, V), Y.basicOpen g ≤ O ∧ (y : Y) ∈ Y.basicOpen g :=
    hV.exists_basicOpen_le ⟨y, y.2.2⟩ y.2.1
  choose g hgO hyg using H
  obtain ⟨t, ht⟩ := (NoetherianSpace.isCompact ((V ⊓ O : Y.Opens) : Set Y)).elim_finite_subcover
    (fun y : ↥(V ⊓ O) ↦ (Y.basicOpen (g y) : Set Y)) (fun y ↦ (Y.basicOpen (g y)).isOpen)
    (fun y hy ↦ Set.mem_iUnion.mpr ⟨⟨y, hy⟩, hyg ⟨y, hy⟩⟩)
  refine ⟨t.image g, fun h hh ↦ ?_, fun y hy ↦ ?_⟩
  · obtain ⟨z, -, rfl⟩ := Finset.mem_image.mp hh
    exact hgO z
  · obtain ⟨z, hz, hyz⟩ := Set.mem_iUnion₂.mp (ht hy)
    exact Opens.mem_iSup.mpr ⟨g z, Opens.mem_iSup.mpr ⟨Finset.mem_image_of_mem g hz, hyz⟩⟩

/-- In a noetherian scheme, the intersection of two affine opens `V` and `V'` is covered by
finitely many opens which are basic open subsets of both `V` and `V'`. -/
lemma exists_finset_basicOpen_le_basicOpen [NoetherianSpace Y] {V V' : Y.Opens}
    (hV : IsAffineOpen V) (hV' : IsAffineOpen V') :
    ∃ t : Finset Γ(Y, V), (∀ g ∈ t, Y.basicOpen g ≤ V' ∧
      ∃ t' : Γ(Y, V'), Y.basicOpen t' = Y.basicOpen g) ∧ V ⊓ V' ≤ ⨆ g ∈ t, Y.basicOpen g := by
  classical
  have H (y : ↥(V ⊓ V')) : ∃ g : Γ(Y, V), (Y.basicOpen g ≤ V' ∧
      ∃ t' : Γ(Y, V'), Y.basicOpen t' = Y.basicOpen g) ∧ (y : Y) ∈ Y.basicOpen g := by
    obtain ⟨g₀, hg₀, hyg₀⟩ := hV.exists_basicOpen_le ⟨y, y.2.2⟩ y.2.1
    obtain ⟨t', ht', hyt'⟩ := hV'.exists_basicOpen_le ⟨y, hyg₀⟩ y.2.2
    obtain ⟨g, hg⟩ := hV.basicOpen_basicOpen_is_basicOpen g₀
      (Y.presheaf.map (homOfLE hg₀).op t')
    have e : Y.basicOpen g = Y.basicOpen t' := by
      rw [hg, Scheme.basicOpen_res, inf_eq_right.mpr ht']
    refine ⟨g, ⟨?_, t', e.symm⟩, ?_⟩
    · rw [e]
      exact Y.basicOpen_le t'
    · rw [e]
      exact hyt'
  choose g hg hyg using H
  obtain ⟨t, ht⟩ := (NoetherianSpace.isCompact ((V ⊓ V' : Y.Opens) : Set Y)).elim_finite_subcover
    (fun y : ↥(V ⊓ V') ↦ (Y.basicOpen (g y) : Set Y)) (fun y ↦ (Y.basicOpen (g y)).isOpen)
    (fun y hy ↦ Set.mem_iUnion.mpr ⟨⟨y, hy⟩, hyg ⟨y, hy⟩⟩)
  refine ⟨t.image g, fun h hh ↦ ?_, fun y hy ↦ ?_⟩
  · obtain ⟨z, -, rfl⟩ := Finset.mem_image.mp hh
    exact hg z
  · obtain ⟨z, hz, hyz⟩ := Set.mem_iUnion₂.mp (ht hy)
    exact Opens.mem_iSup.mpr ⟨g z, Opens.mem_iSup.mpr ⟨Finset.mem_image_of_mem g hz, hyz⟩⟩

section Noetherian

variable [NoetherianSpace Y] {K : Type*} [Finite K] {U : K → Y.Opens}
  {B : ∀ k, Subring (P.obj (op (U k)))}

include hloc₁ in
set_option backward.isDefEq.respectTransparency false in
/-- `glob U B` is quasi-coherent over the affine opens: a section over a basic open `D(r)` of an
affine `V` becomes a section over `V` after multiplication by a power of `r`. -/
theorem exists_pow_mul_mem_glob {V : Y.Opens} (hV : IsAffineOpen V) (r : Γ(Y, V))
    {x : P.obj (op (Y.basicOpen r))} (hx : x ∈ glob α U B (Y.basicOpen r)) {a : P.obj (op V)}
    {m : ℕ} (hxa : x * res P (Y.basicOpen_le r) (α.app (op V) r) ^ m =
      res P (Y.basicOpen_le r) a) :
    ∃ N, α.app (op V) r ^ N * a ∈ glob α U B V := by
  classical
  have := Fintype.ofFinite K
  choose t ht htcov using fun k ↦ exists_finset_basicOpen_le hV (U k)
  have H (k) (g) (hg : g ∈ t k) : ∃ N,
      res P (Y.basicOpen_le g) (α.app (op V) r ^ N * a) ∈ loc α (B k) (ht k g hg) := by
    have hWa : IsAffineOpen (Y.basicOpen g) := hV.basicOpen g
    let h : Γ(Y, Y.basicOpen g) := Y.presheaf.map (homOfLE (Y.basicOpen_le g)).op r
    have hαh : α.app (op (Y.basicOpen g)) h = res P (Y.basicOpen_le g) (α.app (op V) r) :=
      (res_app α _ r).symm
    have hDh : Y.basicOpen h ≤ Y.basicOpen r := by
      rw [Scheme.basicOpen_res]
      exact inf_le_right
    have hx' := mem_glob_iff.mp hx k (Y.basicOpen h) (hWa.basicOpen h) hDh
      ((Y.basicOpen_le h).trans (ht k g hg))
    obtain ⟨n, y, hy, e⟩ := exists_pow_mul_mem_loc (ht k g hg) hWa h hx'
    have e₂ : res P hDh x * res P (Y.basicOpen_le h) (α.app (op (Y.basicOpen g)) h) ^ m =
        res P (Y.basicOpen_le h) (res P (Y.basicOpen_le g) a) := by
      have := congrArg (res P hDh) hxa
      rw [map_mul, map_pow, res_res, res_res] at this
      rw [hαh, res_res, res_res]
      exact this
    have e₃ : res P (Y.basicOpen_le h) (y * α.app (op (Y.basicOpen g)) h ^ m) =
        res P (Y.basicOpen_le h)
          (α.app (op (Y.basicOpen g)) h ^ n * res P (Y.basicOpen_le g) a) := by
      rw [map_mul, map_pow, e, map_mul, map_pow, ← e₂]
      ring
    obtain ⟨t', ht'⟩ := hloc₁ _ hWa h _ _ e₃
    refine ⟨t' + n, ?_⟩
    have e₄ : res P (Y.basicOpen_le g) (α.app (op V) r ^ (t' + n) * a) =
        α.app (op (Y.basicOpen g)) h ^ t' * (y * α.app (op (Y.basicOpen g)) h ^ m) := by
      rw [ht', map_mul, map_pow, ← hαh]
      ring
    rw [e₄]
    exact mul_mem (pow_mem (app_mem_loc _ _) _) (mul_mem hy (pow_mem (app_mem_loc _ _) _))
  choose! N hN using H
  let M := ∑ k, ∑ g ∈ t k, N k g
  refine ⟨M, mem_glob_iff.mpr fun k W hWa h₁ h₂ ↦ ?_⟩
  refine res_mem_loc_of_cover hloc₁ (fun g : t k ↦ Y.basicOpen (g : Γ(Y, V)))
    (fun g ↦ Y.basicOpen_le _) (fun g ↦ ht k g g.2) (fun g ↦ ?_) hWa h₁ h₂ ?_
  · have hle : N k g ≤ M := (Finset.single_le_sum (fun g _ ↦ Nat.zero_le (N k g)) g.2).trans
      (Finset.single_le_sum (fun k _ ↦ Nat.zero_le (∑ g ∈ t k, N k g)) (Finset.mem_univ k))
    rw [← Nat.sub_add_cancel hle, pow_add, mul_assoc, map_mul]
    exact mul_mem (by rw [map_pow, res_app]; exact pow_mem (app_mem_loc _ _) _) (hN k g g.2)
  · intro y hy
    obtain ⟨g, hg⟩ := Opens.mem_iSup.mp (htcov k ⟨h₁ hy, h₂ hy⟩)
    obtain ⟨hgt, hyg⟩ := Opens.mem_iSup.mp hg
    exact Opens.mem_iSup.mpr ⟨⟨g, hgt⟩, hyg⟩

variable (hloc₂ : ∀ (W : Y.Opens), IsAffineOpen W → ∀ (h : Γ(Y, W))
  (z : P.obj (op (Y.basicOpen h))), ∃ (m : ℕ) (a : P.obj (op W)),
    z * res P (Y.basicOpen_le h) (α.app (op W) h) ^ m = res P (Y.basicOpen_le h) a)

include hloc₁ hloc₂ in
set_option backward.isDefEq.respectTransparency false in
/-- Let `P` be integral over `𝒪_Y`, `Uₖ` affine, and let `Sₖ ⊆ Bₖ` be finite sets with
`P(Uₖ)_s = (Bₖ)_s` for `s ∈ Sₖ`. If a section `c` of `P` over `Uₖ` lies, over every basic open
`D(g) ⊆ Uₖ` of some `Uₖ'`, in the radical of the ideal generated by `Sₖ'`, then
`P(Uₖ)_c = (glob U B)(Uₖ)_c`. -/
theorem exists_pow_mul_mem_glob_of_radical
    (hint : ∀ W : Y.Opens, IsAffineOpen W → (α.app (op W)).hom.IsIntegral)
    (hU : ∀ k, IsAffineOpen (U k)) (S : ∀ k, Finset (P.obj (op (U k))))
    (hSB : ∀ k, ∀ s ∈ S k, s ∈ B k) (hS : ∀ k, ∀ s ∈ S k, ∀ a, ∃ n, s ^ n * a ∈ B k)
    (k : K) {c : P.obj (op (U k))}
    (hc : ∀ k' (g : Γ(Y, U k')) (hg : Y.basicOpen g ≤ U k),
      (∃ t : Γ(Y, U k), Y.basicOpen t = Y.basicOpen g) → res P hg c ∈
        (Ideal.span (res P (Y.basicOpen_le g) '' (S k' : Set (P.obj (op (U k')))))).radical)
    (a : P.obj (op (U k))) : ∃ N, ∀ n, N ≤ n → c ^ n * a ∈ glob α U B (U k) := by
  classical
  have := Fintype.ofFinite K
  choose t ht' htcov using fun k' ↦ exists_finset_basicOpen_le_basicOpen (hU k') (hU k)
  have ht (k') (g) (hg : g ∈ t k') : Y.basicOpen g ≤ U k := (ht' k' g hg).1
  have H (k') (g) (hg : g ∈ t k') : ∃ N, ∀ n, N ≤ n →
      res P (ht k' g hg) (c ^ n * a) ∈ loc α (B k') (Y.basicOpen_le g) := by
    have hWa : IsAffineOpen (Y.basicOpen g) := (hU k').basicOpen g
    let _ : Algebra Γ(Y, Y.basicOpen g) (P.obj (op (Y.basicOpen g))) :=
      (α.app (op (Y.basicOpen g))).hom.toAlgebra
    have : Algebra.IsIntegral Γ(Y, Y.basicOpen g) (P.obj (op (Y.basicOpen g))) :=
      ⟨hint _ hWa⟩
    let B' : Subalgebra Γ(Y, Y.basicOpen g) (P.obj (op (Y.basicOpen g))) :=
      { loc α (B k') (Y.basicOpen_le g) with algebraMap_mem' := fun r ↦ app_mem_loc _ r }
    have hc' := hc k' g (ht k' g hg) (ht' k' g hg).2
    rw [← Finset.coe_image] at hc'
    have h₁ : ∀ b ∈ (S k').image (res P (Y.basicOpen_le g)), b ∈ B' := by
      intro b hb
      obtain ⟨s, hs, rfl⟩ := Finset.mem_image.mp hb
      exact res_mem_loc _ (hSB k' s hs)
    have h₂ : ∀ b ∈ (S k').image (res P (Y.basicOpen_le g)), ∀ z, ∃ n, b ^ n * z ∈ B' := by
      intro b hb z
      obtain ⟨s, hs, rfl⟩ := Finset.mem_image.mp hb
      obtain ⟨m, a'', e⟩ := hloc₂ (U k') (hU k') g z
      obtain ⟨n, hn⟩ := hS k' s hs a''
      obtain ⟨v, hv⟩ : IsUnit (Y.presheaf.map (homOfLE (Y.basicOpen_le g)).op g) :=
        Y.toRingedSpace.isUnit_res_basicOpen g
      have hres : res P (Y.basicOpen_le g) (α.app (op (U k')) g) =
          α.app (op (Y.basicOpen g)) (v : Γ(Y, Y.basicOpen g)) := by
        rw [res_app, hv]
      rw [hres] at e
      have hz : z = res P (Y.basicOpen_le g) a'' * α.app (op (Y.basicOpen g))
          ((v⁻¹ : (Γ(Y, Y.basicOpen g))ˣ) : Γ(Y, Y.basicOpen g)) ^ m := by
        rw [← e, mul_assoc, ← mul_pow, ← map_mul, Units.mul_inv, map_one, one_pow, mul_one]
      refine ⟨n, ?_⟩
      rw [hz, ← mul_assoc, ← map_pow, ← map_mul]
      exact mul_mem (res_mem_loc _ hn) (pow_mem (app_mem_loc _ _) _)
    obtain ⟨N, hN⟩ := exists_pow_mul_mem_of_mem_radical B'
      ((S k').image (res P (Y.basicOpen_le g))) h₁ h₂ hc' (res P (ht k' g hg) a)
    refine ⟨N, fun n hn ↦ ?_⟩
    rw [map_mul, map_pow]
    exact hN n hn
  choose! N hN using H
  let M := ∑ k', ∑ g ∈ t k', N k' g
  refine ⟨M, fun n hn ↦ mem_glob_iff.mpr fun k' W hWa h₁ h₂ ↦ ?_⟩
  refine res_mem_loc_of_cover hloc₁ (fun g : t k' ↦ Y.basicOpen (g : Γ(Y, U k')))
    (fun g ↦ ht k' g g.2) (fun g ↦ Y.basicOpen_le _) (fun g ↦ ?_) hWa h₁ h₂ ?_
  · refine hN k' g g.2 n (le_trans ?_ hn)
    exact (Finset.single_le_sum (fun g _ ↦ Nat.zero_le (N k' g)) g.2).trans
      (Finset.single_le_sum (fun k' _ ↦ Nat.zero_le (∑ g ∈ t k', N k' g)) (Finset.mem_univ k'))
  · intro y hy
    obtain ⟨g, hg⟩ := Opens.mem_iSup.mp (htcov k' ⟨h₂ hy, h₁ hy⟩)
    obtain ⟨hgt, hyg⟩ := Opens.mem_iSup.mp hg
    exact Opens.mem_iSup.mpr ⟨⟨g, hgt⟩, hyg⟩

section Functor

variable (α U B)

/-- The presheaf of rings `W ↦ (glob U B)(W)` on the affine opens of `Y`. -/
noncomputable def globFunctor : Y.AffineZariskiSiteᵒᵖ ⥤ CommRingCat.{u} where
  obj W := CommRingCat.of (glob α U B W.unop.1)
  map {W W'} i := CommRingCat.ofHom ((res P (Scheme.AffineZariskiSite.toOpens_mono
    (leOfHom i.unop))).restrict (glob α U B W.unop.1) (glob α U B W'.unop.1)
      fun _ hx ↦ res_mem_glob _ hx)
  map_id W := by
    ext x
    exact res_self _ _
  map_comp i j := by
    ext x
    exact (res_res _ _ _).symm

/-- The structure morphism `𝒪_Y ⟶ glob U B` on the affine opens. -/
noncomputable def globι : (Scheme.AffineZariskiSite.toOpensFunctor Y).op ⋙ Y.presheaf ⟶
    globFunctor α U B where
  app W := CommRingCat.ofHom ((α.app (op W.unop.1)).hom.codRestrict _ fun r ↦ app_mem_glob r)
  naturality W W' i := by
    ext r
    exact Subtype.ext (res_app α _ r).symm

/-- The inclusion of `glob U B` into `P` on the affine opens. -/
noncomputable def globToP : globFunctor α U B ⟶
    (Scheme.AffineZariskiSite.toOpensFunctor Y).op ⋙ P where
  app W := CommRingCat.ofHom (glob α U B W.unop.1).subtype
  naturality W W' i := by
    ext x
    rfl

omit [NoetherianSpace Y] [Finite K] in
lemma globι_globToP : globι α U B ≫ globToP α U B =
    Functor.whiskerLeft (Scheme.AffineZariskiSite.toOpensFunctor Y).op α := by
  ext W r
  rfl

include hloc₁ hloc₂ in
/-- `glob U B` is a "quasi-coherent `𝒪_Y`-algebra" over the affine opens: its sections over a
basic open `D(r)` of an affine `W` are the localization of its sections over `W`. -/
theorem coequifibered_globι : (globι α U B).Coequifibered := by
  rw [Scheme.AffineZariskiSite.coequifibered_iff_forall_isLocalizationAway]
  intro W r
  obtain ⟨v, hv⟩ : IsUnit (Y.presheaf.map (homOfLE (Y.basicOpen_le r)).op r) :=
    Y.toRingedSpace.isUnit_res_basicOpen r
  have hvα : res P (Y.basicOpen_le r) (α.app (op W.1) r) =
      α.app (op (Y.basicOpen r)) (v : Γ(Y, Y.basicOpen r)) := by
    rw [res_app, hv]
  refine isLocalization_away_restrict (res P (Y.basicOpen_le r)) (glob α U B W.1)
    (glob α U B (Y.basicOpen r)) (fun _ hx ↦ res_mem_glob _ hx) (app_mem_glob r)
    ⟨α.app (op (Y.basicOpen r)) ((v⁻¹ : (Γ(Y, Y.basicOpen r))ˣ) : Γ(Y, Y.basicOpen r)),
      app_mem_glob _, by rw [hvα, ← map_mul, Units.mul_inv, map_one]⟩ (fun z hz ↦ ?_)
    (fun a _ b _ e ↦ hloc₁ W.1 W.2 r a b e)
  obtain ⟨m, a, e⟩ := hloc₂ W.1 W.2 r z
  obtain ⟨N, hN⟩ := exists_pow_mul_mem_glob hloc₁ W.2 r hz e
  refine ⟨N + m, _, hN, ?_⟩
  rw [pow_add, ← mul_assoc, mul_comm z, mul_assoc, e, map_mul, map_pow]

end Functor

end Noetherian

end Presheaf


end SGA.SGA1.ExposeVIII
