/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.SGA1.ExposeVIII.FiniteDescent
import SGA.SGA1.ExposeVIII.FiniteSubalgebraGluing

/-!
# SGA 1, Exposé VIII, 6.4: a quasi-finite separated morphism is an open subscheme of a finite one

Let `f : X ⟶ Y` be quasi-finite and separated, with `Y` noetherian. By Zariski's Main Theorem
(mathlib), `X` is an open subscheme of the normalization `N` of `Y` in `X`, which is integral over
`Y`: `N` is glued from the `Spec A(U)`, `A(U)` the integral closure of `Γ(Y, U)` in `Γ(X, f⁻¹(U))`
(`U` affine). Over each member `Uₖ` of a finite affine covering, VIII.6.4 over an affine base gives
a finite subalgebra `Bₖ ⊆ A(Uₖ)` with `A(Uₖ)_s = (Bₖ)_s` for finitely many `s` whose non-vanishing
loci cover `X ∩ N_{Uₖ}` (`exists_goodSubalgebra`). The subalgebras `Bₖ` glue to a finite
quasi-coherent subalgebra `𝔅` of `A` (`SGA.SGA1.ExposeVIII.glob`, EGA I 9.4.7), and `X` is open in
the finite `Y`-scheme `Z = Spec 𝔅` (`exists_isOpenImmersion_isFinite_of_isNoetherian`): since the
`D(s)` over different `Uₖ` all lie over `X`, each such `s` lies, locally, in the radical of the
ideal generated by the good elements of any other `Bₖ'` (`mem_radical_of_basicOpen_le_normOpen`),
hence `A(Uₖ)_s = 𝔅(Uₖ)_s`, and `X ⟶ Spec A ⟶ Spec 𝔅` is an open immersion on each chart
`Spec A(Uₖ)_s` and injective. This proves `QuasiFiniteOpenInFiniteStatement`
(`quasiFiniteOpenInFiniteStatement`).
-/

universe u

open CategoryTheory CategoryTheory.Limits AlgebraicGeometry TopologicalSpace Opposite

namespace SGA.SGA1.ExposeVIII

section Algebra

variable {A : Type*} [CommRing A] (G : Subring A) {s : A}
  (hs : ∀ a, ∃ N, ∀ n, N ≤ n → s ^ n * a ∈ G)
include hs

/-- If `G ⊆ A` is a subring with `sⁿ a ∈ G` for every `a ∈ A` and all large `n`, then `A_s` is a
localization of `G` away from an element of `G` (a power of `s`). -/
lemma exists_isLocalization_away_of_forall_pow_mul_mem :
    ∃ c : G, letI := ((algebraMap A (Localization.Away s)).comp G.subtype).toAlgebra
      IsLocalization.Away c (Localization.Away s) := by
  obtain ⟨N, hN⟩ := hs 1
  have hc : s ^ (N + 1) ∈ G := by simpa using hN (N + 1) (Nat.le_succ N)
  let _ := ((algebraMap A (Localization.Away s)).comp G.subtype).toAlgebra
  have halg (x : G) : algebraMap G (Localization.Away s) x =
      algebraMap A (Localization.Away s) x := rfl
  have hpow (m : ℕ) : algebraMap G (Localization.Away s) ⟨_, hc⟩ ^ m =
      algebraMap A (Localization.Away s) s ^ ((N + 1) * m) := by
    rw [halg, map_pow, pow_mul]
  refine ⟨⟨_, hc⟩, IsLocalization.Away.mk _ ?_ (fun z ↦ ?_) (fun a b e ↦ ?_)⟩
  · rw [← pow_one (algebraMap G _ _), hpow]
    exact (IsLocalization.Away.algebraMap_isUnit s).pow _
  · obtain ⟨n, a, e⟩ := IsLocalization.Away.surj s z
    obtain ⟨Na, hNa⟩ := hs a
    have hle : n + Na ≤ (N + 1) * (n + Na) := Nat.le_mul_of_pos_left _ (Nat.succ_pos N)
    refine ⟨n + Na, ⟨s ^ ((N + 1) * (n + Na) - n) * a, hNa _ (by omega)⟩, ?_⟩
    rw [hpow, halg]
    change _ = algebraMap A (Localization.Away s) (s ^ ((N + 1) * (n + Na) - n) * a)
    have hk : (N + 1) * (n + Na) = n + ((N + 1) * (n + Na) - n) := by omega
    rw [hk, pow_add, ← mul_assoc, e, map_mul, map_pow, mul_comm, Nat.add_sub_cancel_left]
  · obtain ⟨n, hn⟩ := IsLocalization.Away.exists_of_eq s e
    refine ⟨n, Subtype.ext ?_⟩
    change (s ^ (N + 1)) ^ n * (a : A) = (s ^ (N + 1)) ^ n * (b : A)
    have hn' : s ^ n * (a : A) = s ^ n * (b : A) := hn
    rw [← pow_mul, add_mul, one_mul, pow_add, mul_assoc, hn', ← mul_assoc]

/-- If `G ⊆ A` is a subring with `sⁿ a ∈ G` for every `a ∈ A` and all large `n`, then two primes
of `A` not containing `s` with the same trace on `G` coincide. -/
lemma eq_of_comap_eq_of_forall_pow_mul_mem (P₁ P₂ : PrimeSpectrum A) (h₁ : s ∉ P₁.asIdeal)
    (h : PrimeSpectrum.comap G.subtype P₁ = PrimeSpectrum.comap G.subtype P₂) : P₁ = P₂ := by
  have hmem (x : A) (hx : x ∈ G) : x ∈ P₁.asIdeal ↔ x ∈ P₂.asIdeal := by
    have := congrArg (fun Q : PrimeSpectrum G ↦ (⟨x, hx⟩ : G) ∈ Q.asIdeal) h
    simpa using this
  obtain ⟨N, hN⟩ := hs 1
  have hG : s ^ (N + 1) ∈ G := by simpa using hN (N + 1) (Nat.le_succ N)
  have h₂ : s ∉ P₂.asIdeal := fun hs₂ ↦ h₁ (P₁.2.mem_of_pow_mem _
    ((hmem _ hG).mpr (Ideal.pow_mem_of_mem _ hs₂ _ (Nat.succ_pos N))))
  ext a
  obtain ⟨Na, hNa⟩ := hs a
  have := hmem _ (hNa Na le_rfl)
  constructor
  · intro ha
    exact (P₂.2.mem_or_mem (this.mp (P₁.asIdeal.mul_mem_left _ ha))).resolve_left
      fun h' ↦ h₂ (P₂.2.mem_of_pow_mem _ h')
  · intro ha
    exact (P₁.2.mem_or_mem (this.mpr (P₂.asIdeal.mul_mem_left _ ha))).resolve_left
      fun h' ↦ h₁ (P₁.2.mem_of_pow_mem _ h')

end Algebra

variable {X Y : Scheme.{u}} (f : X ⟶ Y)

section Normalization

variable [QuasiCompact f] [QuasiSeparated f]

set_option backward.isDefEq.respectTransparency false in
lemma normalizationDiagram_isLocalizationAway (W : Y.Opens) (hW : IsAffineOpen W)
    (h : Γ(Y, W)) :
    letI := (res f.normalizationDiagram (Y.basicOpen_le h)).toAlgebra
    IsLocalization.Away (f.normalizationDiagramMap.app (op W) h)
      (f.normalizationDiagram.obj (op (Y.basicOpen h))) :=
  Scheme.AffineZariskiSite.coequifibered_iff_forall_isLocalizationAway.mp
    f.coequifibered_normalizationDiagramMap ⟨W, hW⟩ h

lemma normalization_hloc₁ (W : Y.Opens) (hW : IsAffineOpen W) (h : Γ(Y, W))
    (a b : f.normalizationDiagram.obj (op W))
    (e : res f.normalizationDiagram (Y.basicOpen_le h) a =
      res f.normalizationDiagram (Y.basicOpen_le h) b) :
    ∃ m, f.normalizationDiagramMap.app (op W) h ^ m * a =
      f.normalizationDiagramMap.app (op W) h ^ m * b := by
  let _ := (res f.normalizationDiagram (Y.basicOpen_le h)).toAlgebra
  have := normalizationDiagram_isLocalizationAway f W hW h
  obtain ⟨⟨_, m, rfl⟩, hm⟩ := IsLocalization.exists_of_eq
    (M := Submonoid.powers (f.normalizationDiagramMap.app (op W) h)) e
  exact ⟨m, hm⟩

lemma normalization_hloc₂ (W : Y.Opens) (hW : IsAffineOpen W) (h : Γ(Y, W))
    (z : f.normalizationDiagram.obj (op (Y.basicOpen h))) :
    ∃ (m : ℕ) (a : f.normalizationDiagram.obj (op W)),
      z * res f.normalizationDiagram (Y.basicOpen_le h)
        (f.normalizationDiagramMap.app (op W) h) ^ m =
        res f.normalizationDiagram (Y.basicOpen_le h) a := by
  let _ := (res f.normalizationDiagram (Y.basicOpen_le h)).toAlgebra
  have := normalizationDiagram_isLocalizationAway f W hW h
  obtain ⟨⟨a, _, m, rfl⟩, e⟩ := IsLocalization.surj
    (Submonoid.powers (f.normalizationDiagramMap.app (op W) h)) z
  refine ⟨m, a, ?_⟩
  rw [← map_pow]
  exact e

omit [QuasiCompact f] [QuasiSeparated f] in
lemma normalization_hint (W : Y.Opens) :
    (f.normalizationDiagramMap.app (op W)).hom.IsIntegral := by
  let := (f.app W).hom.toAlgebra
  change (algebraMap Γ(Y, W) (integralClosure Γ(Y, W) Γ(X, f ⁻¹ᵁ W))).IsIntegral
  exact algebraMap_isIntegral_iff.mpr inferInstance

variable [LocallyOfFiniteType f] [LocallyQuasiFinite f] [IsSeparated f]

/-- The open subset of the chart `Spec A(U)` of the normalization lying over `X`. -/
noncomputable abbrev normOpen (U : Y.affineOpens) :
    (Spec (f.normalizationDiagram.obj (op U.1))).Opens :=
  f.normalizationOpenCover.f U ⁻¹ᵁ f.toNormalization.opensRange

omit [LocallyOfFiniteType f] [LocallyQuasiFinite f] [IsSeparated f] in
/-- A point of `X` over an affine open `U` of `Y` lies in the image of the chart `Spec A(U)`. -/
lemma exists_normalizationOpenCover_eq (U : Y.affineOpens) {x : X} (hx : f x ∈ U.1) :
    ∃ P, f.normalizationOpenCover.f U P = f.toNormalization x := by
  have : f.toNormalization x ∈ f.fromNormalization ⁻¹ᵁ U.1 := by
    change f.fromNormalization (f.toNormalization x) ∈ U.1
    rw [← Scheme.Hom.comp_apply, f.toNormalization_fromNormalization]
    exact hx
  rw [f.fromNormalization_preimage U] at this
  exact this

omit [LocallyOfFiniteType f] [LocallyQuasiFinite f] [IsSeparated f] in
set_option backward.isDefEq.respectTransparency false in
/-- The charts of the normalization are compatible with restriction to basic opens. -/
lemma normalizationOpenCover_map_apply {U W : Y.affineOpens} (h : W.1 ≤ U.1) (t : Γ(Y, U.1))
    (ht : Y.basicOpen t = W.1) (Q : Spec (f.normalizationDiagram.obj (op W.1))) :
    f.normalizationOpenCover.f U (Spec.map (f.normalizationDiagram.map (homOfLE h).op) Q) =
      f.normalizationOpenCover.f W Q := by
  have e : Spec.map (f.normalizationDiagram.map (homOfLE h).op) ≫
      f.normalizationOpenCover.f U = f.normalizationOpenCover.f W :=
    colimit.w f.normalizationGlueData.functor
      (@homOfLE Y.AffineZariskiSite _ W U ⟨t, ht⟩)
  rw [← e]
  rfl

/-- If the basic open `D(s)` of the chart `Spec A(U)` lies over `X`, then so does its image in
the normalization. -/
lemma range_subset_of_basicOpen_le_normOpen (U : Y.affineOpens)
    {s : f.normalizationDiagram.obj (op U.1)} (hs : PrimeSpectrum.basicOpen s ≤ normOpen f U) :
    Set.range (Spec.map (CommRingCat.ofHom (algebraMap (f.normalizationDiagram.obj (op U.1))
      (Localization.Away s))) ≫ f.normalizationOpenCover.f U) ⊆ Set.range f.toNormalization := by
  rintro _ ⟨Q, rfl⟩
  have hQ : Spec.map (CommRingCat.ofHom (algebraMap (f.normalizationDiagram.obj (op U.1))
      (Localization.Away s))) Q ∈
      PrimeSpectrum.basicOpen s := by
    have := PrimeSpectrum.localization_away_comap_range (Localization.Away s) s
    change _ ∈ SetLike.coe (PrimeSpectrum.basicOpen s)
    rw [← this]
    exact ⟨Q, rfl⟩
  exact hs hQ

set_option backward.isDefEq.respectTransparency false in
/-- The key compatibility for gluing (EGA I 9.4.7): if the basic open `D(c)` of `Spec A(U)` lies
over `X` and the `D(s)`, `s ∈ S`, cover the part of `Spec A(V)` over `X`, then over every
`D(g) ⊆ U ∩ V` basic in both, `c` lies in the radical of the ideal generated by `S`. -/
lemma mem_radical_of_basicOpen_le_normOpen (U V : Y.affineOpens)
    {c : f.normalizationDiagram.obj (op U.1)} (hc : PrimeSpectrum.basicOpen c ≤ normOpen f U)
    (S : Finset (f.normalizationDiagram.obj (op V.1)))
    (hS : normOpen f V ≤ ⨆ s ∈ S, PrimeSpectrum.basicOpen s) (g : Γ(Y, V.1))
    (hg : Y.basicOpen g ≤ U.1) (ht : ∃ t : Γ(Y, U.1), Y.basicOpen t = Y.basicOpen g) :
    res f.normalizationDiagram hg c ∈
      (Ideal.span (res f.normalizationDiagram (Y.basicOpen_le g) '' (S : Set _))).radical := by
  obtain ⟨t, ht⟩ := ht
  rw [Ideal.radical_eq_sInf, Ideal.mem_sInf]
  rintro J ⟨hJ, hJp⟩
  by_contra hcJ
  let W : Y.affineOpens := ⟨Y.basicOpen g, V.2.basicOpen g⟩
  let Q : Spec (f.normalizationDiagram.obj (op W.1)) := ⟨J, hJp⟩
  have h₁ := normalizationOpenCover_map_apply f (U := U) (W := W) hg t ht Q
  have h₂ := normalizationOpenCover_map_apply f (U := V) (W := W) (Y.basicOpen_le g) g rfl Q
  have hU : Spec.map (f.normalizationDiagram.map (homOfLE hg).op) Q ∈ normOpen f U := hc hcJ
  have hV : Spec.map (f.normalizationDiagram.map (homOfLE (Y.basicOpen_le g)).op) Q ∈
      normOpen f V := by
    change f.normalizationOpenCover.f V _ ∈ f.toNormalization.opensRange
    rw [h₂, ← h₁]
    exact hU
  obtain ⟨s, hs⟩ := Opens.mem_iSup.mp (hS hV)
  obtain ⟨hsS, hs⟩ := Opens.mem_iSup.mp hs
  exact hs (hJ (Ideal.subset_span ⟨s, hsS, rfl⟩))

set_option backward.isDefEq.respectTransparency false in
/-- VIII.6.4 over an affine open `U` of `Y`, in the form needed for gluing: a finite subalgebra
`B` of `A(U)` and finitely many `s ∈ B` with `A(U)_s = B_s`, whose non-vanishing loci `D(s)` are
contained in, and cover, the part of `Spec A(U)` lying over `X`. -/
theorem exists_goodSubalgebra (U : Y.affineOpens) :
    letI := (f.normalizationDiagramMap.app (op U.1)).hom.toAlgebra
    ∃ (B : Subalgebra Γ(Y, U.1) (f.normalizationDiagram.obj (op U.1)))
      (S : Finset (f.normalizationDiagram.obj (op U.1))),
      Module.Finite Γ(Y, U.1) B ∧ (∀ s ∈ S, s ∈ B) ∧ (∀ s ∈ S, ∀ a, ∃ n, s ^ n * a ∈ B) ∧
      (∀ s ∈ S, PrimeSpectrum.basicOpen s ≤ normOpen f U) ∧
      normOpen f U ≤ ⨆ s ∈ S, PrimeSpectrum.basicOpen s := by
  classical
  let _ := (f.normalizationDiagramMap.app (op U.1)).hom.toAlgebra
  let A := f.normalizationDiagram.obj (op U.1)
  let χ := f.normalizationOpenCover.f U
  have : Algebra.IsIntegral Γ(Y, U.1) A := ⟨normalization_hint f U.1⟩
  -- the part of `Spec A` over `X` is quasi-compact
  have hOc : IsCompact (normOpen f U : Set (Spec A)) := by
    let _ := (f.app U.1).hom.toAlgebra
    let e : (f ⁻¹ᵁ U.1).toScheme ⟶ Spec A := (f ⁻¹ᵁ U.1).toSpecΓ ≫ Spec.map
      (CommRingCat.ofHom (integralClosure Γ(Y, U.1) Γ(X, f ⁻¹ᵁ U.1)).val.toRingHom)
    have he : (f ⁻¹ᵁ U.1).ι ≫ f.toNormalization = e ≫ χ := f.ι_toNormalization U
    have hrange : (normOpen f U : Set (Spec A)) = Set.range e := by
      ext P
      constructor
      · rintro ⟨x, hx⟩
        have hxU : f x ∈ U.1 := by
          have h1 : f x = f.fromNormalization (f.toNormalization x) :=
            (congrArg (fun φ : X ⟶ Y ↦ φ x) f.toNormalization_fromNormalization).symm
          have h2 : f.fromNormalization (χ P) = U.2.fromSpec (Spec.map
              (f.normalizationDiagramMap.app (op U.1)) P) :=
            congrArg (fun φ ↦ φ P) (f.ι_fromNormalization U)
          have h4 : f x = U.2.fromSpec (Spec.map
              (f.normalizationDiagramMap.app (op U.1)) P) :=
            h1.trans ((congrArg f.fromNormalization hx).trans h2)
          rw [h4]
          exact U.2.range_fromSpec.subset ⟨_, rfl⟩
        refine ⟨⟨x, hxU⟩, χ.isOpenEmbedding.injective ?_⟩
        have h3 := congrArg (fun φ ↦ φ (⟨x, hxU⟩ : f ⁻¹ᵁ U.1)) he
        exact h3.symm.trans hx
      · rintro ⟨y, rfl⟩
        exact ⟨(f ⁻¹ᵁ U.1).ι y, congrArg (fun φ ↦ φ y) he⟩
    have : CompactSpace (f ⁻¹ᵁ U.1) :=
      isCompact_iff_compactSpace.mp (f.isCompact_preimage U.2.isCompact)
    rw [hrange]
    exact isCompact_range e.continuous
  -- a finite covering by basic opens
  have H (P : normOpen f U) : ∃ s : A, (P : Spec A) ∈ PrimeSpectrum.basicOpen s ∧
      PrimeSpectrum.basicOpen s ≤ normOpen f U := by
    obtain ⟨_, ⟨s, rfl⟩, hPs, hsO⟩ :=
      Opens.isBasis_iff_nbhd.mp PrimeSpectrum.isBasis_basic_opens P.2
    exact ⟨s, hPs, hsO⟩
  choose sf hsf hsfO using H
  obtain ⟨t, ht⟩ := hOc.elim_finite_subcover (fun P : normOpen f U ↦
    SetLike.coe (PrimeSpectrum.basicOpen (sf P))) (fun P ↦ (PrimeSpectrum.basicOpen (sf P)).2)
    (fun P hP ↦ Set.mem_iUnion.mpr ⟨⟨P, hP⟩, hsf ⟨P, hP⟩⟩)
  let S := t.image sf
  have hSO (s) (hs : s ∈ S) : PrimeSpectrum.basicOpen s ≤ normOpen f U := by
    obtain ⟨P, -, rfl⟩ := Finset.mem_image.mp hs
    exact hsfO P
  have hOS : normOpen f U ≤ ⨆ s ∈ S, PrimeSpectrum.basicOpen s := by
    intro P hP
    obtain ⟨Q, hQ, hPQ⟩ := Set.mem_iUnion₂.mp (ht hP)
    exact Opens.mem_iSup.mpr ⟨sf Q, Opens.mem_iSup.mpr ⟨Finset.mem_image_of_mem sf hQ, hPQ⟩⟩
  -- the localizations `A_s`, `s ∈ S`, are of finite type over `Γ(Y, U)`
  have hL (s) (hs : s ∈ S) : Algebra.FiniteType Γ(Y, U.1) (Localization.Away s) := by
    let ι' := Spec.map (CommRingCat.ofHom (algebraMap A (Localization.Away s)))
    have hr : Set.range (ι' ≫ χ) ⊆ Set.range f.toNormalization :=
      range_subset_of_basicOpen_le_normOpen f U (hSO s hs)
    let ℓ := IsOpenImmersion.lift f.toNormalization (ι' ≫ χ) hr
    have hℓ : ℓ ≫ f.toNormalization = ι' ≫ χ := IsOpenImmersion.lift_fac _ _ _
    have : LocallyOfFiniteType ℓ := by
      have : LocallyOfFiniteType (ℓ ≫ f.toNormalization) := by
        rw [hℓ]
        infer_instance
      exact locallyOfFiniteType_of_comp ℓ f.toNormalization
    have h2 : Spec.map (CommRingCat.ofHom (algebraMap Γ(Y, U.1) (Localization.Away s))) ≫
        U.2.fromSpec = ℓ ≫ f := by
      rw [← f.toNormalization_fromNormalization, reassoc_of% hℓ, f.ι_fromNormalization,
        ← Spec.map_comp_assoc]
      congr 2
    have : LocallyOfFiniteType (Spec.map (CommRingCat.ofHom
        (algebraMap Γ(Y, U.1) (Localization.Away s)))) := by
      have : LocallyOfFiniteType (Spec.map (CommRingCat.ofHom
          (algebraMap Γ(Y, U.1) (Localization.Away s))) ≫ U.2.fromSpec) := by
        rw [h2]
        infer_instance
      exact locallyOfFiniteType_of_comp _ U.2.fromSpec
    exact RingHom.finiteType_algebraMap.mp
      ((HasRingHomProperty.Spec_iff (P := @LocallyOfFiniteType)).mp this)
  obtain ⟨B', hfin, hs', hloc⟩ :=
    exists_finite_subalgebra_isLocalization S (fun b ↦ Localization.Away b) hL
  refine ⟨B', S, hfin, hs', fun s hs a ↦ ?_, hSO, hOS⟩
  have := hloc s hs
  obtain ⟨⟨x, _, n, rfl⟩, e⟩ := IsLocalization.surj
    (Submonoid.powers (⟨s, hs' s hs⟩ : B')) (algebraMap A (Localization.Away s) a)
  have e' : algebraMap A (Localization.Away s) (a * s ^ n) =
      algebraMap A (Localization.Away s) x := by
    change algebraMap A (Localization.Away s) a * algebraMap A (Localization.Away s)
      ((⟨s, hs' s hs⟩ ^ n : B') : A) = algebraMap A (Localization.Away s) (x : A) at e
    rw [SubmonoidClass.coe_pow] at e
    rw [map_mul]
    exact e
  obtain ⟨⟨_, m, rfl⟩, hm⟩ := IsLocalization.exists_of_eq (M := Submonoid.powers s) e'
  refine ⟨m + n, ?_⟩
  have : s ^ (m + n) * a = s ^ m * (x : A) := by
    rw [← hm]
    ring
  rw [this]
  exact B'.mul_mem (B'.pow_mem (hs' s hs) m) x.2

end Normalization

/-- The diagram of a relative gluing datum over the affine opens is locally directed (so that it
has a colimit). -/
instance isLocallyDirected_relativeGluingData {F : Y.AffineZariskiSiteᵒᵖ ⥤ CommRingCat.{u}}
    {β : (Scheme.AffineZariskiSite.toOpensFunctor Y).op ⋙ Y.presheaf ⟶ F} (H : β.Coequifibered) :
    ((Scheme.AffineZariskiSite.relativeGluingData H).functor ⋙ Scheme.forget).IsLocallyDirected :=
  Scheme.Cover.RelativeGluingData.instIsLocallyDirectedI₀CompFunctorForgetOfIsThin ..

set_option backward.isDefEq.respectTransparency.types false in
/-- For the scheme glued from a quasi-coherent algebra `β : 𝒪_Y ⟶ F`, the structure morphism on
the chart over an affine open `V` is `Spec (β V)` followed by `Spec Γ(Y, V) ≅ V ⊆ Y`. -/
lemma ι_toBase_relativeGluingData {F : Y.AffineZariskiSiteᵒᵖ ⥤ CommRingCat.{u}}
    {β : (Scheme.AffineZariskiSite.toOpensFunctor Y).op ⋙ Y.presheaf ⟶ F} (H : β.Coequifibered)
    (V : Y.AffineZariskiSite) :
    colimit.ι (Scheme.AffineZariskiSite.relativeGluingData H).functor V ≫
      (Scheme.AffineZariskiSite.relativeGluingData H).toBase =
      Spec.map (β.app (op V)) ≫ V.2.fromSpec :=
  colimit.ι_desc _ _

set_option backward.isDefEq.respectTransparency false in
/-- **SGA 1 VIII 6.4.** Let `f : X ⟶ Y` be quasi-finite (of finite type with finite fibres) and
separated, with `Y` noetherian. Then `f` factors as an open immersion `X ⟶ Z` followed by a finite
morphism `Z ⟶ Y`.

`Z` is `Spec` of the quasi-coherent subalgebra `𝔅 = glob U B` of the normalization algebra `A`
of `Y` in `X`, glued (EGA I 9.4.7) from finite subalgebras `Bₖ ⊆ A(Uₖ)` chosen over a finite
affine covering `(Uₖ)` of `Y` by VIII.6.4 over an affine base; `X ⟶ Z` is
`X ⟶ Spec A ⟶ Spec 𝔅`. -/
theorem exists_isOpenImmersion_isFinite_of_isNoetherian [IsNoetherian Y]
    [LocallyOfFiniteType f] [QuasiCompact f] [LocallyQuasiFinite f] [IsSeparated f] :
    ∃ (Z : Scheme.{u}) (i : X ⟶ Z) (p : Z ⟶ Y), IsOpenImmersion i ∧ IsFinite p ∧ i ≫ p = f := by
  classical
  -- a finite covering of `Y` by affine opens `Uₖ`
  obtain ⟨s, hs⟩ := isCompact_univ.elim_finite_subcover (fun U : Y.affineOpens ↦ (U.1 : Set Y))
    (fun U ↦ U.1.2) fun y _ ↦ Set.mem_iUnion.mpr
      (Opens.mem_iSup.mp ((iSup_affineOpens_eq_top Y).ge (Set.mem_univ y)))
  let W : s → Y.AffineZariskiSite := fun k ↦ k.1
  let U : s → Y.Opens := fun k ↦ k.1.1
  have hU (k : s) : IsAffineOpen (U k) := k.1.2
  have hcov (y : Y) : ∃ k : s, y ∈ U k := by
    obtain ⟨V, hV, hy⟩ := Set.mem_iUnion₂.mp (hs (Set.mem_univ y))
    exact ⟨⟨V, hV⟩, hy⟩
  -- VIII.6.4 over each `Uₖ`
  choose B S hBfin hSB hS hSO hOS using fun k : s ↦ exists_goodSubalgebra f k.1
  let Bs (k : s) : Subring (f.normalizationDiagram.obj (op (U k))) :=
    letI := (f.normalizationDiagramMap.app (op (U k))).hom.toAlgebra
    (B k).toSubring
  -- the glued subalgebra `𝔅 = glob U B` of the normalization algebra, and `Z = Spec 𝔅`
  let α := f.normalizationDiagramMap
  have H := coequifibered_globι α (normalization_hloc₁ f) U Bs (normalization_hloc₂ f)
  let d := Scheme.AffineZariskiSite.relativeGluingData H
  have hglob (k : s) (s₀) (hs₀ : s₀ ∈ S k) (a) :
      ∃ N, ∀ n, N ≤ n → s₀ ^ n * a ∈ glob α U Bs (U k) :=
    exists_pow_mul_mem_glob_of_radical (normalization_hloc₁ f) (normalization_hloc₂ f)
      (fun W _ ↦ normalization_hint f W) hU S hSB hS k (fun k' g hg ht ↦
        mem_radical_of_basicOpen_le_normOpen f k.1 k'.1 (hSO k s₀ hs₀) (S k') (hOS k') g hg ht) a
  -- `Z` is finite over `Y`
  have hfin (k : s) : ((globι α U Bs).app (op (W k))).hom.Finite := by
    let _ : Algebra Γ(Y, U k) (f.normalizationDiagram.obj (op (U k))) :=
      (α.app (op (U k))).hom.toAlgebra
    let _ : Algebra Γ(Y, U k) ((globFunctor α U Bs).obj (op (W k))) :=
      ((globι α U Bs).app (op (W k))).hom.toAlgebra
    have := hBfin k
    have : IsNoetherianRing Γ(Y, U k) := IsLocallyNoetherian.component_noetherian k.1
    have hle := glob_le (α := α) (U := U) (B := Bs) k (fun r ↦ (B k).algebraMap_mem r) (hU k)
    let e : (globFunctor α U Bs).obj (op (W k)) →ₗ[Γ(Y, U k)] B k :=
      { toFun := fun x ↦ ⟨x.1, hle x.2⟩, map_add' := fun _ _ ↦ rfl, map_smul' := fun _ _ ↦ rfl }
    have hG : Module.Finite Γ(Y, U k) ((globFunctor α U Bs).obj (op (W k))) := by
      refine Module.Finite.of_injective e fun x y h ↦ ?_
      have h' : (e x).1 = (e y).1 := congrArg Subtype.val h
      exact Subtype.ext h'
    exact hG
  have hp : IsFinite d.toBase := isFinite_toBase_of_cover H W
    (eq_top_iff.mpr fun y _ ↦ Opens.mem_iSup.mpr (hcov y)) hfin
  -- the morphism `ψ : Spec A ⟶ Spec 𝔅`
  let ψ : f.normalization ⟶ d.glued :=
    colimMap (Functor.whiskerRight (NatTrans.rightOp (globToP α U Bs)) Scheme.Spec)
  have hχψ (V : Y.affineOpens) : f.normalizationOpenCover.f V ≫ ψ =
      Spec.map ((globToP α U Bs).app (op V)) ≫ colimit.ι d.functor V :=
    ι_colimMap _ _
  have hψp : ψ ≫ d.toBase = f.fromNormalization := by
    refine f.normalizationOpenCover.hom_ext _ _ fun V ↦ ?_
    rw [reassoc_of% (hχψ V), ι_toBase_relativeGluingData, f.ι_fromNormalization,
      ← Spec.map_comp_assoc, ← NatTrans.comp_app, globι_globToP]
    rfl
  have hfac : (f.toNormalization ≫ ψ) ≫ d.toBase = f := by
    rw [Category.assoc, hψp, f.toNormalization_fromNormalization]
  refine ⟨d.glued, f.toNormalization ≫ ψ, d.toBase, ?_, hp, hfac⟩
  -- every point of `X` lies in a chart `D(s₀) ⊆ Spec A(Uₖ)` with `s₀ ∈ Sₖ`
  have hchart (x : X) : ∃ (k : s) (P : Spec (f.normalizationDiagram.obj (op (U k)))) (s₀ : _),
      s₀ ∈ S k ∧ P ∈ PrimeSpectrum.basicOpen s₀ ∧
        f.normalizationOpenCover.f k.1 P = f.toNormalization x ∧ f x ∈ U k := by
    obtain ⟨k, hk⟩ := hcov (f x)
    obtain ⟨P, hP⟩ := exists_normalizationOpenCover_eq f k.1 hk
    have hPO : P ∈ normOpen f k.1 := ⟨x, hP.symm⟩
    obtain ⟨s₀, hs₀⟩ := Opens.mem_iSup.mp (hOS k hPO)
    obtain ⟨hs₀S, hPs₀⟩ := Opens.mem_iSup.mp hs₀
    exact ⟨k, P, s₀, hs₀S, hPs₀, hP, hk⟩
  have hψapply (k : s) (P : Spec (f.normalizationDiagram.obj (op (U k)))) :
      ψ (f.normalizationOpenCover.f k.1 P) =
        colimit.ι d.functor (W k) (Spec.map ((globToP α U Bs).app (op (W k))) P) := by
    rw [← Scheme.Hom.comp_apply, hχψ]
    rfl
  refine IsOpenImmersion.of_forall_source_exists _ ?_ fun x ↦ ?_
  · -- injectivity
    intro x₁ x₂ e
    obtain ⟨k, P₁, s₁, hs₁, hP₁s, hP₁, hk⟩ := hchart x₁
    have hx₂ : f x₂ ∈ U k := by
      have h1 : f x₂ = f x₁ := by
        have := congrArg (fun z ↦ d.toBase z) e
        simp only [← Scheme.Hom.comp_apply, hfac] at this
        exact this.symm
      rw [h1]
      exact hk
    obtain ⟨P₂, hP₂⟩ := exists_normalizationOpenCover_eq f k.1 hx₂
    have h12 : P₁ = P₂ := by
      refine eq_of_comap_eq_of_forall_pow_mul_mem _ (hglob k s₁ hs₁) P₁ P₂ hP₁s ?_
      apply (colimit.ι d.functor (W k)).isOpenEmbedding.injective
      have e' : ψ (f.toNormalization x₁) = ψ (f.toNormalization x₂) := e
      rw [← hP₁, ← hP₂, hψapply, hψapply] at e'
      exact e'
    apply f.toNormalization.isOpenEmbedding.injective
    rw [← hP₁, ← hP₂, h12]
  · -- the charts `Spec A(Uₖ)_{s₀} ⟶ X`
    obtain ⟨k, P₀, s₀, hs₀, hP₀s, hP₀, -⟩ := hchart x
    let A := f.normalizationDiagram.obj (op (U k))
    let L := Localization.Away s₀
    let ι' := Spec.map (CommRingCat.ofHom (algebraMap A L))
    let χ := f.normalizationOpenCover.f k.1
    let ℓ := IsOpenImmersion.lift f.toNormalization (ι' ≫ χ)
      (range_subset_of_basicOpen_le_normOpen f k.1 (hSO k s₀ hs₀))
    have hℓ : ℓ ≫ f.toNormalization = ι' ≫ χ := IsOpenImmersion.lift_fac _ _ _
    have : IsOpenImmersion ℓ := by
      have : IsOpenImmersion (ℓ ≫ f.toNormalization) := by
        rw [hℓ]
        infer_instance
      exact IsOpenImmersion.of_comp ℓ f.toNormalization
    refine ⟨Spec (CommRingCat.of L), ℓ, this, ?_, ?_⟩
    · have hr : P₀ ∈ Set.range (PrimeSpectrum.comap (algebraMap A L)) := by
        rw [PrimeSpectrum.localization_away_comap_range L s₀]
        exact hP₀s
      obtain ⟨Q, hQ⟩ := hr
      refine ⟨Q, f.toNormalization.isOpenEmbedding.injective ?_⟩
      rw [← Scheme.Hom.comp_apply, hℓ, Scheme.Hom.comp_apply]
      change χ (PrimeSpectrum.comap (algebraMap A L) Q) = _
      rw [hQ, hP₀]
    · obtain ⟨c, hc⟩ := exists_isLocalization_away_of_forall_pow_mul_mem _ (hglob k s₀ hs₀)
      let _ := ((algebraMap A L).comp (glob α U Bs (U k)).subtype).toAlgebra
      have e : ℓ ≫ f.toNormalization ≫ ψ = Spec.map (CommRingCat.ofHom
          (algebraMap (glob α U Bs (U k)) L)) ≫ colimit.ι d.functor (W k) := by
        rw [reassoc_of% hℓ, hχψ, ← Spec.map_comp_assoc]
        rfl
      rw [e]
      have := IsOpenImmersion.of_isLocalization (S := L) c
      infer_instance

/-- **SGA 1 VIII 6.4**: `QuasiFiniteOpenInFiniteStatement` holds. -/
theorem quasiFiniteOpenInFiniteStatement : QuasiFiniteOpenInFiniteStatement.{u} :=
  fun _ _ f _ _ _ _ _ ↦ exists_isOpenImmersion_isFinite_of_isNoetherian f

end SGA.SGA1.ExposeVIII
