/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import Mathlib.RingTheory.TensorProduct.IncludeLeftSubRight
import SGA.SGA1.ExposeVIII.ModuleDescentIso

/-!
# SGA 1, Exposé VIII, VIII.1.7–1.9: descent of sections, sub-Modules and closed subschemes

Affine case, `S = Spec A` and `S' = Spec B` with `B` faithfully flat over `A`:

* VIII.1.7 (descent of sections) is VIII.1.5 applied to the module `G`, see
  `range_mk_eq_eqLocus`; for `G = A` it is mathlib's `Algebra.IsEffective.of_faithfullyFlat`.
* VIII.1.8 (descent of quotient Modules): `exists_baseChange_eq_iff_span_eq`, stated for
  sub-Modules, which correspond bijectively to quotient Modules.
* VIII.1.9 (descent of closed subschemes): `exists_ideal_map_eq_iff`.

Both are deduced from a general statement: a submodule of a module with descent datum which is
stable under the descent datum is generated by its invariants
(`ModuleDescentDatum.eq_span_inf_invariants`), obtained by restricting the descent datum and
applying VIII.1.6. The general statements over preschemes are in
`SGA.SGA1.ExposeVIII.QuasiCoherentDescent`.
-/

universe u v w

open TensorProduct

namespace SGA.SGA1.ExposeVIII

variable {A : Type u} {B : Type v} [CommRing A] [CommRing B] [Algebra A B]

namespace ModuleDescentDatum

variable {N : Type w} [AddCommGroup N] [Module A N] [Module B N] [IsScalarTower A B N]
  (D : ModuleDescentDatum A B N) (P : Submodule B N)

/-- The inclusion `B ⊗_A P → B ⊗_A N` of a `B`-submodule. -/
noncomputable abbrev baseChangeSubtype : B ⊗[A] P →ₗ[B] B ⊗[A] N :=
  (P.subtype.restrictScalars A).baseChange B

/-- A submodule `P` is stable under the descent datum if `θ (P) ⊆ B ⊗_A P`. -/
def IsStable : Prop :=
  ∀ y ∈ P, D.coaction y ∈ LinearMap.range (baseChangeSubtype P)

variable {D P}

lemma baseChangeSubtype_injective [Module.Flat A B] :
    Function.Injective (baseChangeSubtype (A := A) (B := B) P) :=
  Module.Flat.lTensor_preserves_injective_linearMap _ P.injective_subtype

/-- The coaction induced on a stable submodule, for flat `A → B`. -/
noncomputable def restrictCoaction [Module.Flat A B] (hP : D.IsStable P) : P →ₗ[B] B ⊗[A] P :=
  (LinearEquiv.ofInjective _ baseChangeSubtype_injective).symm.toLinearMap ∘ₗ
    LinearMap.codRestrict (LinearMap.range (baseChangeSubtype P)) (D.coaction ∘ₗ P.subtype)
      fun y ↦ hP y y.2

lemma baseChangeSubtype_restrictCoaction [Module.Flat A B] (hP : D.IsStable P) (y : P) :
    baseChangeSubtype P (restrictCoaction hP y) = D.coaction y := by
  simp only [restrictCoaction, LinearMap.comp_apply, LinearEquiv.coe_coe]
  rw [← LinearEquiv.ofInjective_apply (h := baseChangeSubtype_injective),
    LinearEquiv.apply_symm_apply]
  rfl

omit [Module B N] [IsScalarTower A B N] in
lemma lTensor_mk_comp_subtype (Q : Submodule A N) (z : B ⊗[A] Q) :
    (Q.subtype.lTensor B).lTensor B ((TensorProduct.mk A B Q 1).lTensor B z) =
      (TensorProduct.mk A B N 1).lTensor B (Q.subtype.lTensor B z) := by
  rw [← LinearMap.lTensor_comp_apply, ← LinearMap.lTensor_comp_apply]
  rfl

lemma coe_act_eq (z : B ⊗[A] P) :
    ((LinearMap.liftBaseChange B (LinearMap.id : P →ₗ[A] P) z : P) : N) =
      LinearMap.liftBaseChange B LinearMap.id (baseChangeSubtype P z) := by
  induction z with
  | zero => simp
  | add x y hx hy => simp only [map_add, Submodule.coe_add, hx, hy]
  | tmul b x => simp

/-- The descent datum induced on a stable submodule, for flat `A → B`. -/
noncomputable def restrict [Module.Flat A B] (hP : D.IsStable P) : ModuleDescentDatum A B P where
  coaction := restrictCoaction hP
  counit y := by
    apply Subtype.val_injective
    rw [coe_act_eq, baseChangeSubtype_restrictCoaction, D.counit]
  coassoc y := by
    have hinj : Function.Injective
        (((baseChangeSubtype (A := A) (B := B) P).restrictScalars A).lTensor B) :=
      Module.Flat.lTensor_preserves_injective_linearMap _ baseChangeSubtype_injective
    apply hinj
    rw [← LinearMap.lTensor_comp_apply, ← LinearMap.lTensor_comp_apply]
    have h₁ : ((baseChangeSubtype P).restrictScalars A) ∘ₗ ((restrictCoaction hP).restrictScalars A)
        = (D.coaction.restrictScalars A) ∘ₗ (P.subtype.restrictScalars A) := by
      ext y
      exact baseChangeSubtype_restrictCoaction hP y
    have h₂ : ((baseChangeSubtype P).restrictScalars A) ∘ₗ (TensorProduct.mk A B P 1)
        = (TensorProduct.mk A B N 1) ∘ₗ (P.subtype.restrictScalars A) := by
      ext y
      rfl
    have h₃ : (P.subtype.restrictScalars A).lTensor B (restrictCoaction hP y) = D.coaction y :=
      baseChangeSubtype_restrictCoaction hP y
    rw [h₁, h₂, LinearMap.lTensor_comp_apply, LinearMap.lTensor_comp_apply, h₃, D.coassoc]

lemma mem_invariants_restrict [Module.Flat A B] (hP : D.IsStable P) (y : P) :
    y ∈ (D.restrict hP).invariants ↔ (y : N) ∈ D.invariants := by
  rw [mem_invariants, mem_invariants, ← (baseChangeSubtype_injective (A := A) (B := B)).eq_iff]
  change baseChangeSubtype P (restrictCoaction hP y) = _ ↔ _
  rw [baseChangeSubtype_restrictCoaction]
  rfl

/-- Descent of sub-objects: for flat `A → B`, a `B`-submodule `P` of a module with descent datum
which is stable under the descent datum is generated by its invariants. -/
theorem eq_span_inf_invariants [Module.Flat A B] (hP : D.IsStable P) :
    P = Submodule.span B ((P.restrictScalars A ⊓ D.invariants : Submodule A N) : Set N) := by
  refine le_antisymm (fun y hy ↦ ?_) (Submodule.span_le.2 fun x hx ↦ hx.1)
  obtain ⟨z, hz⟩ := (D.restrict hP).descentMap_bijective.2 ⟨y, hy⟩
  have hy' : y = ((D.restrict hP).descentMap z : N) := by rw [hz]
  subst hy'
  clear hz hy
  induction z with
  | zero => simp
  | add x y hx hy => rw [map_add, Submodule.coe_add]; exact add_mem hx hy
  | tmul b x =>
    rw [descentMap_tmul, Submodule.coe_smul]
    refine Submodule.smul_mem _ b (Submodule.subset_span ⟨(x : P).2, ?_⟩)
    exact (mem_invariants_restrict hP x).1 x.2

/-- A stable submodule is stable under `lTensorSMul`. -/
lemma lTensorSMul_mem_range (c : B) {w : B ⊗[A] N}
    (hw : w ∈ LinearMap.range (baseChangeSubtype P)) :
    lTensorSMul A B N c w ∈ LinearMap.range (baseChangeSubtype P) := by
  obtain ⟨z, rfl⟩ := hw
  refine ⟨lTensorSMul A B P c z, ?_⟩
  induction z with
  | zero => simp
  | add x y hx hy => simp only [map_add, hx, hy]
  | tmul b x => rfl

end ModuleDescentDatum

section Submodule

variable {M : Type w} [AddCommGroup M] [Module A M]

lemma assoc_smul_tmul (b c : B) (w : (B ⊗[A] B) ⊗[A] M) :
    TensorProduct.assoc A B B M ((b ⊗ₜ[A] c) • w) =
      b • lTensorSMul A B (B ⊗[A] M) c (TensorProduct.assoc A B B M w) := by
  induction w with
  | zero => simp
  | add x y hx hy => simp only [smul_add, map_add, hx, hy]
  | tmul x m =>
    induction x with
    | zero => simp
    | add x y hx hy => simp only [add_tmul, smul_add, map_add, hx, hy]
    | tmul b' c' => simp [smul_tmul']

/-- The `C`-submodule generated by the image of `B ⊗_A P` under an `A`-algebra map `B → C` is
`C ⊗_A P`. -/
lemma span_rTensor_image_baseChange {C : Type*} [CommRing C] [Algebra A C] (f : B →ₐ[A] C)
    (P : Submodule A M) :
    Submodule.span C (f.toLinearMap.rTensor M '' P.baseChange B) = P.baseChange C := by
  apply le_antisymm
  · rw [Submodule.span_le]
    rintro _ ⟨y, ⟨z, rfl⟩, rfl⟩
    induction z with
    | zero => simp
    | add x y hx hy => rw [map_add, map_add]; exact add_mem hx hy
    | tmul b p => exact Submodule.tmul_mem_baseChange_of_mem _ p.2
  · rw [Submodule.baseChange_eq_span, Submodule.span_le]
    rintro _ ⟨p, hp, rfl⟩
    refine Submodule.subset_span ⟨1 ⊗ₜ p, Submodule.tmul_mem_baseChange_of_mem _ hp, ?_⟩
    simp

variable (A B) in
/-- The `B ⊗_A B`-submodule of `(B ⊗_A B) ⊗_A M ≅ B ⊗_A (B ⊗_A M)` corresponding to
`B ⊗_A P'`, for a `B`-submodule `P'` of `B ⊗_A M`. -/
noncomputable def assocPreimageSubmodule (P' : Submodule B (B ⊗[A] M)) :
    Submodule (B ⊗[A] B) ((B ⊗[A] B) ⊗[A] M) where
  carrier := {w | TensorProduct.assoc A B B M w ∈
    LinearMap.range (ModuleDescentDatum.baseChangeSubtype P')}
  add_mem' {x y} hx hy := by
    change TensorProduct.assoc A B B M (x + y) ∈
      LinearMap.range (ModuleDescentDatum.baseChangeSubtype P')
    rw [map_add]
    exact add_mem hx hy
  zero_mem' := by
    change TensorProduct.assoc A B B M 0 ∈
      LinearMap.range (ModuleDescentDatum.baseChangeSubtype P')
    rw [map_zero]
    exact zero_mem _
  smul_mem' x w hw := by
    change TensorProduct.assoc A B B M w ∈
      LinearMap.range (ModuleDescentDatum.baseChangeSubtype P') at hw
    change TensorProduct.assoc A B B M (x • w) ∈
      LinearMap.range (ModuleDescentDatum.baseChangeSubtype P')
    induction x with
    | zero => simp only [zero_smul, map_zero]; exact zero_mem _
    | add x y hx hy => rw [add_smul, map_add]; exact add_mem hx hy
    | tmul b c =>
      rw [assoc_smul_tmul]
      exact Submodule.smul_mem _ b (ModuleDescentDatum.lTensorSMul_mem_range c hw)

/-- VIII.1.8 (affine case, stated for sub-Modules, which correspond bijectively to quotient
Modules): for a faithfully flat `A`-algebra `B` and an `A`-module `M`, a `B`-submodule `P'` of
`B ⊗_A M` comes from a submodule of `M` if and only if its two inverse images on
`Spec (B ⊗_A B)` coincide, i.e. the `B ⊗_A B`-submodules of `(B ⊗_A B) ⊗_A M` generated by
its images under the two projections are equal. The submodule of `M` is unique
(`Submodule.baseChange_injective`). -/
theorem exists_baseChange_eq_iff_span_eq [Module.FaithfullyFlat A B]
    (P' : Submodule B (B ⊗[A] M)) :
    (∃ P : Submodule A M, P.baseChange B = P') ↔
      Submodule.span (B ⊗[A] B) (rTensorIncludeLeft A B M '' P') =
        Submodule.span (B ⊗[A] B) (rTensorIncludeRight A B M '' P') := by
  constructor
  · rintro ⟨P, rfl⟩
    exact (span_rTensor_image_baseChange _ P).trans (span_rTensor_image_baseChange _ P).symm
  · intro h
    have hP : (ModuleDescentDatum.canonical A B M).IsStable P' := by
      intro y hy
      have : rTensorIncludeLeft A B M y ∈
          Submodule.span (B ⊗[A] B) (rTensorIncludeRight A B M '' P') :=
        h ▸ Submodule.subset_span ⟨y, hy, rfl⟩
      have hle : Submodule.span (B ⊗[A] B) (rTensorIncludeRight A B M '' P') ≤
          assocPreimageSubmodule A B P' := by
        rw [Submodule.span_le]
        rintro _ ⟨y', hy', rfl⟩
        change TensorProduct.assoc A B B M (rTensorIncludeRight A B M y') ∈
          LinearMap.range (ModuleDescentDatum.baseChangeSubtype P')
        rw [assoc_rTensorIncludeRight]
        exact ⟨1 ⊗ₜ ⟨y', hy'⟩, rfl⟩
      have h' : TensorProduct.assoc A B B M (rTensorIncludeLeft A B M y) ∈
          LinearMap.range (ModuleDescentDatum.baseChangeSubtype P') := hle this
      rwa [assoc_rTensorIncludeLeft] at h'
    refine ⟨P'.restrictScalars A |>.comap (TensorProduct.mk A B M 1), ?_⟩
    conv_rhs => rw [ModuleDescentDatum.eq_span_inf_invariants hP, ← range_mk_eq_invariants]
    rw [Submodule.baseChange_eq_span]
    congr 1
    ext y
    simp only [Submodule.map_coe, Submodule.comap_coe, Set.mem_image, Set.mem_preimage,
      SetLike.mem_coe, Submodule.coe_inf, Submodule.coe_restrictScalars, Set.mem_inter_iff,
      LinearMap.mem_range]
    constructor
    · rintro ⟨m, hm, rfl⟩
      exact ⟨hm, m, rfl⟩
    · rintro ⟨hy, m, rfl⟩
      exact ⟨m, hy, rfl⟩

end Submodule

section Ideal

variable (A B) in
/-- The canonical descent datum on `B` itself, `θ b = b ⊗ 1` (the case `M = A` of
`ModuleDescentDatum.canonical`). -/
noncomputable def ModuleDescentDatum.self : ModuleDescentDatum A B B where
  coaction := tmulOne A B B
  counit b := by simp
  coassoc b := by simp

lemma mem_invariants_self_iff [Module.FaithfullyFlat A B] (b : B) :
    b ∈ (ModuleDescentDatum.self A B).invariants ↔ b ∈ Set.range (algebraMap A B) := by
  have := (Algebra.IsEffective.of_faithfullyFlat A B) b
  rw [Algebra.TensorProduct.includeLeftSubRight_apply, sub_eq_zero] at this
  exact this

lemma tmul_smul_eq_smul_lTensorSMul (b c : B) (w : B ⊗[A] B) :
    (b ⊗ₜ[A] c) • w = b • lTensorSMul A B B c w := by
  induction w with
  | zero => simp
  | add x y hx hy => simp only [smul_add, map_add, hx, hy]
  | tmul x i => simp [smul_tmul']

variable (A B) in
/-- `B ⊗_A I'` as an ideal of `B ⊗_A B`. -/
noncomputable def baseChangeIdeal (I' : Ideal B) : Ideal (B ⊗[A] B) where
  carrier := LinearMap.range (ModuleDescentDatum.baseChangeSubtype (A := A) I')
  add_mem' := add_mem
  zero_mem' := zero_mem _
  smul_mem' x w hw := by
    induction x with
    | zero => rw [zero_smul]; exact zero_mem _
    | add x y hx hy => rw [add_smul]; exact add_mem hx hy
    | tmul b c =>
      rw [tmul_smul_eq_smul_lTensorSMul]
      exact Submodule.smul_mem _ b (ModuleDescentDatum.lTensorSMul_mem_range c hw)

/-- VIII.1.9 (affine case): for a faithfully flat `A`-algebra `B`, a closed subscheme of
`Spec B`, given by an ideal `I'`, comes from a closed subscheme of `Spec A` if and only if its
two inverse images on `Spec (B ⊗_A B)` coincide. The ideal of `A` is unique
(`Ideal.map_injective_of_faithfullyFlat`). -/
theorem exists_ideal_map_eq_iff [Module.FaithfullyFlat A B] (I' : Ideal B) :
    (∃ I : Ideal A, I.map (algebraMap A B) = I') ↔
      I'.map (Algebra.TensorProduct.includeLeft (R := A) (S := A) (A := B) (B := B)) =
        I'.map (Algebra.TensorProduct.includeRight (R := A) (A := B) (B := B)) := by
  constructor
  · rintro ⟨I, rfl⟩
    have key (f : B →ₐ[A] B ⊗[A] B) :
        (I.map (algebraMap A B)).map f = I.map (algebraMap A (B ⊗[A] B)) := by
      change (I.map (algebraMap A B)).map (f : B →+* B ⊗[A] B) = _
      rw [Ideal.map_map, AlgHom.comp_algebraMap]
    rw [key, key]
  · intro h
    have hP : (ModuleDescentDatum.self A B).IsStable I' := by
      intro y hy
      have h₁ : Algebra.TensorProduct.includeLeft (R := A) (S := A) (A := B) (B := B) y ∈
          I'.map (Algebra.TensorProduct.includeRight (R := A) (A := B) (B := B)) :=
        h ▸ Ideal.mem_map_of_mem _ hy
      have h₂ : I'.map (Algebra.TensorProduct.includeRight (R := A) (A := B) (B := B)) ≤
          baseChangeIdeal A B I' := by
        rw [Ideal.map_le_iff_le_comap]
        intro i hi
        exact ⟨1 ⊗ₜ ⟨i, hi⟩, rfl⟩
      exact h₂ h₁
    refine ⟨I'.comap (algebraMap A B), ?_⟩
    have := ModuleDescentDatum.eq_span_inf_invariants hP
    rw [Ideal.map]
    conv_rhs => rw [this]
    congr 1
    ext b
    simp only [Set.mem_image, Submodule.coe_inf, Submodule.coe_restrictScalars, Set.mem_inter_iff,
      SetLike.mem_coe, mem_invariants_self_iff, Ideal.mem_comap]
    constructor
    · rintro ⟨a, ha, rfl⟩
      exact ⟨ha, a, rfl⟩
    · rintro ⟨hb, a, rfl⟩
      exact ⟨a, hb, rfl⟩

end Ideal

end SGA.SGA1.ExposeVIII
