/-
Copyright (c) 2026 SGAenglishpluslean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SGAenglishpluslean contributors
-/
import SGA.SGA2.ExposeIV.HomOrthogonalLength
import Mathlib.RingTheory.Nakayama

/-!
# Actual single generation and the residue quotient

A finite module over a local ring is generated by one actual element if
and only if its quotient by the maximal ideal has length at most one.
The reverse implication uses the actual Nakayama surjectivity theorem.
The zero module is included, with generator zero.
-/

noncomputable section

universe u

open CategoryTheory Limits Opposite

namespace SGA.SGA2.ExposeIV

variable {R : Type u} [CommRing R]
variable (M : Type u) [AddCommGroup M] [Module R M]

/-- Monogenic means a single actual generator, with zero allowed. -/
def ModuleMonogenic : Prop := ∃ x : M, Submodule.span R {x} = ⊤

/-- The definition is equivalent to surjectivity of the original scalar map. -/
theorem moduleMonogenic_iff_surjective :
    ModuleMonogenic (R := R) M ↔
      ∃ x : M, Function.Surjective (LinearMap.toSpanSingleton R M x) := by
  simp only [ModuleMonogenic, LinearMap.span_singleton_eq_range, LinearMap.range_eq_top]

/-- Every module of length zero or one is generated by one actual element. -/
theorem moduleMonogenic_of_length_le_one (hlen : Module.length R M ≤ 1) :
    ModuleMonogenic (R := R) M := by
  by_cases hz : Module.length R M = 0
  · have := Module.length_eq_zero_iff.mp hz
    refine ⟨0, ?_⟩
    ext x
    simp [Subsingleton.elim x 0]
  · have h1 : Module.length R M = 1 :=
      le_antisymm hlen (Order.one_le_iff_ne_zero.mpr hz)
    have : IsSimpleModule R M := Module.length_eq_one_iff.mp h1
    have := IsSimpleModule.nontrivial R M
    obtain ⟨x, hx⟩ := exists_ne (0 : M)
    exact ⟨x, IsSimpleModule.span_singleton_eq_top R hx⟩

/-- A monogenic module annihilated by a maximal ideal is a quotient of the
actual residue field, hence has length at most one. -/
theorem length_le_one_of_moduleMonogenic_of_maximal_annihilator
    (m : Ideal R) (hm : m.IsMaximal) (hAnn : m ≤ Module.annihilator R M)
    (hgen : ModuleMonogenic (R := R) M) : Module.length R M ≤ 1 := by
  obtain ⟨x, hx⟩ := (moduleMonogenic_iff_surjective M).mp hgen
  let f : R ⧸ m →ₗ[R] M := m.liftQ (LinearMap.toSpanSingleton R M x) (by
    intro r hr
    exact Module.mem_annihilator.mp (hAnn hr) x)
  have hf : Function.Surjective f := by
    intro y
    obtain ⟨r, hr⟩ := hx y
    exact ⟨Ideal.Quotient.mk m r, hr⟩
  have : IsSimpleModule R (R ⧸ m) :=
    isSimpleModule_iff_quot_maximal.mpr ⟨m, hm, ⟨LinearEquiv.refl R _⟩⟩
  simpa only [Module.length_eq_one R (R ⧸ m)] using Module.length_le_of_surjective f hf

/-- For modules killed by a maximal ideal, length at most one is precisely
actual single generation, not a substitute definition of cyclicity. -/
theorem moduleMonogenic_iff_length_le_one_of_maximal_annihilator
    (m : Ideal R) (hm : m.IsMaximal) (hAnn : m ≤ Module.annihilator R M) :
    ModuleMonogenic (R := R) M ↔ Module.length R M ≤ 1 :=
  ⟨length_le_one_of_moduleMonogenic_of_maximal_annihilator M m hm hAnn,
    moduleMonogenic_of_length_le_one M⟩

variable [IsLocalRing R] [Module.Finite R M]

/-- Actual generators of the residue quotient lift to actual generators of
the finite original module, by Nakayama's lemma. -/
theorem moduleMonogenic_iff_residue_quotient_monogenic :
    ModuleMonogenic (R := R) M ↔
      ModuleMonogenic (R := R)
        (M ⧸ (IsLocalRing.maximalIdeal R • (⊤ : Submodule R M))) := by
  let m := IsLocalRing.maximalIdeal R
  let N : Submodule R M := m • ⊤
  rw [moduleMonogenic_iff_surjective, moduleMonogenic_iff_surjective]
  constructor
  · rintro ⟨x, hx⟩
    refine ⟨N.mkQ x, ?_⟩
    intro y
    obtain ⟨z, rfl⟩ := N.mkQ_surjective y
    obtain ⟨r, hr⟩ := hx z
    refine ⟨r, ?_⟩
    change r • x = z at hr
    change r • N.mkQ x = N.mkQ z
    rw [← N.mkQ.map_smul, hr]
  · rintro ⟨y, hy⟩
    obtain ⟨x, rfl⟩ := N.mkQ_surjective y
    refine ⟨x, LinearMap.surjective_of_surjective_comp_mkQ
      (LinearMap.toSpanSingleton R M x) m (IsLocalRing.maximalIdeal_le_jacobson ⊥) ?_⟩
    have heq : N.mkQ.comp (LinearMap.toSpanSingleton R M x) =
        LinearMap.toSpanSingleton R (M ⧸ N) (N.mkQ x) := by
      apply LinearMap.ext
      intro r
      exact N.mkQ.map_smul r x
    change Function.Surjective (N.mkQ.comp (LinearMap.toSpanSingleton R M x))
    rw [heq]
    exact hy

/-- The source's monogenic criterion is proved for its literal meaning:
there exists one element whose span is the entire module. -/
theorem moduleMonogenic_iff_residue_length_le_one :
    ModuleMonogenic (R := R) M ↔
      Module.length R (M ⧸ (IsLocalRing.maximalIdeal R • (⊤ : Submodule R M))) ≤ 1 := by
  rw [moduleMonogenic_iff_residue_quotient_monogenic]
  apply moduleMonogenic_iff_length_le_one_of_maximal_annihilator
    _ (IsLocalRing.maximalIdeal R) inferInstance
  exact (Module.isTorsionBySet_iff_subset_annihilator R _).mp
    (Module.isTorsionBySet_quotient_ideal_smul M (IsLocalRing.maximalIdeal R))

end SGA.SGA2.ExposeIV
