/-
Copyright (c) 2026 SGAenglishpluslean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SGAenglishpluslean contributors
-/
import Mathlib.RingTheory.MvPowerSeries.Basic
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.LinearAlgebra.StdBasis
import Mathlib.LinearAlgebra.Isomorphisms
import Mathlib.LinearAlgebra.Dimension.Finite

/-!
# The monomial basis of a coordinate-power quotient

For an actual multivariate power series ring over a field, the quotient by
the powers of its coordinate variables has the basis of monomial classes
whose exponents lie in the corresponding finite box. The proof identifies
the kernel of bounded-coefficient extraction with the actual generated
ideal. No positivity of the number of variables or of the power is assumed.
-/

noncomputable section
universe u

namespace SGA.SGA2.ExposeIV

variable (K : Type u) [Field K]

/-- Exponents strictly below `r` in each of the `d` coordinates. In
particular the zero-variable box has one element, even when `r = 0`. -/
def PowerSeriesPowerBox (d r : ℕ) :=
  {a : Fin d →₀ ℕ // ∀ i, a i < r}

instance powerSeriesPowerBox_fintype (d r : ℕ) : Fintype (PowerSeriesPowerBox d r) :=
  Fintype.ofInjective (fun a : PowerSeriesPowerBox d r =>
    fun i : Fin d => (⟨a.val i, a.property i⟩ : Fin r)) (by
      intro a b h
      apply Subtype.ext
      ext i
      exact congrArg Fin.val (congrFun h i))

/-- The exponent box is the actual finite product of the intervals
`{0, …, r-1}`. The empty product remains a singleton when `r = 0`. -/
def powerSeriesPowerBoxEquivPi (d r : ℕ) :
    PowerSeriesPowerBox d r ≃ (Fin d → Fin r) where
  toFun a i := ⟨a.val i, a.property i⟩
  invFun a := ⟨Finsupp.equivFunOnFinite.symm (fun i => (a i).val), fun i => (a i).isLt⟩
  left_inv a := by apply Subtype.ext; ext i; rfl
  right_inv a := by ext i; rfl

@[simp]
theorem powerSeriesPowerBox_card (d r : ℕ) :
    Fintype.card (PowerSeriesPowerBox d r) = r ^ d := by
  rw [Fintype.card_congr (powerSeriesPowerBoxEquivPi d r)]
  simp

/-- The ideal generated by the actual coordinate powers `X_i^r`. -/
def powerSeriesCoordinatePowerIdeal (d r : ℕ) : Ideal (MvPowerSeries (Fin d) K) :=
  Ideal.span (Set.range (fun i : Fin d => (MvPowerSeries.X i : MvPowerSeries (Fin d) K) ^ r))

/-- With no variables there are no generators, including at power zero. -/
@[simp]
theorem powerSeriesCoordinatePowerIdeal_zero_variables (r : ℕ) :
    powerSeriesCoordinatePowerIdeal K 0 r = ⊥ := by
  simp [powerSeriesCoordinatePowerIdeal]

/-- If a coordinate exists, its zeroth power generates the unit ideal. -/
theorem powerSeriesCoordinatePowerIdeal_zero_power (d : ℕ) (hd : 0 < d) :
    powerSeriesCoordinatePowerIdeal K d 0 = ⊤ := by
  refine Ideal.eq_top_of_isUnit_mem _ ?_ isUnit_one
  exact Ideal.subset_span ⟨⟨0, hd⟩, by simp⟩

/-- Power series with all coefficients in the finite box equal to zero
form an actual ideal. -/
def powerSeriesBoxVanishingIdeal (d r : ℕ) : Ideal (MvPowerSeries (Fin d) K) where
  carrier := {f | ∀ a : Fin d →₀ ℕ, (∀ i, a i < r) → MvPowerSeries.coeff a f = 0}
  zero_mem' := by simp
  add_mem' := by
    intro f g hf hg a ha
    rw [map_add, hf a ha, hg a ha, add_zero]
  smul_mem' := by
    intro f g hg a ha
    change MvPowerSeries.coeff a (f * g) = 0
    rw [MvPowerSeries.coeff_mul]
    apply Finset.sum_eq_zero
    rintro ⟨b, c⟩ hbc
    have hc : ∀ i, c i < r := by
      intro i
      have he := congrArg (fun a : Fin d →₀ ℕ => a i) (Finset.mem_antidiagonal.mp hbc)
      simp only [Finsupp.add_apply] at he
      have := ha i
      omega
    rw [hg c hc, mul_zero]

theorem powerSeriesCoordinatePowerIdeal_le_boxVanishing (d r : ℕ) :
    powerSeriesCoordinatePowerIdeal K d r ≤ powerSeriesBoxVanishingIdeal K d r := by
  apply Ideal.span_le.mpr
  rintro _ ⟨i, rfl⟩
  intro a ha
  exact MvPowerSeries.X_pow_dvd_iff.mp (dvd_refl _) a (ha i)

/-- Split the coefficients outside the box according to a chosen
coordinate whose exponent is too large. This is an actual power series,
not a formal infinite sum in the generated ideal. -/
def powerSeriesOutsideBoxPart (d r : ℕ) (f : MvPowerSeries (Fin d) K) (i : Fin d) :
    MvPowerSeries (Fin d) K := fun a =>
  if h : ∃ j : Fin d, r ≤ a j then
    if Classical.choose h = i then MvPowerSeries.coeff a f else 0
  else 0

/-- Each part is divisible by the corresponding actual coordinate power. -/
theorem powerSeriesOutsideBoxPart_dvd (d r : ℕ) (f : MvPowerSeries (Fin d) K)
    (i : Fin d) :
    (MvPowerSeries.X i : MvPowerSeries (Fin d) K) ^ r ∣
      powerSeriesOutsideBoxPart K d r f i := by
  apply MvPowerSeries.X_pow_dvd_iff.mpr
  intro a ha
  change (if h : ∃ j : Fin d, r ≤ a j then
    if Classical.choose h = i then MvPowerSeries.coeff a f else 0 else 0) = 0
  split_ifs with h hi
  · have hh := Classical.choose_spec h
    rw [hi] at hh
    omega
  · rfl
  · rfl

/-- A series with vanishing box coefficients is the finite sum of the
parts divisible by coordinate powers. This includes the empty-variable case. -/
theorem powerSeries_sum_outsideBoxParts (d r : ℕ) (f : MvPowerSeries (Fin d) K)
    (hf : f ∈ powerSeriesBoxVanishingIdeal K d r) :
    (∑ i : Fin d, powerSeriesOutsideBoxPart K d r f i) = f := by
  classical
  ext a
  rw [map_sum]
  by_cases h : ∃ j : Fin d, r ≤ a j
  · simp [powerSeriesOutsideBoxPart, MvPowerSeries.coeff_apply, h]
  · have ha : ∀ i, a i < r := by
      intro i
      by_contra hi
      exact h ⟨i, Nat.le_of_not_gt hi⟩
    simp [powerSeriesOutsideBoxPart, MvPowerSeries.coeff_apply, h, hf a ha]

/-- The coefficient vanishing criterion is exactly membership in the
original ideal generated by the coordinate powers. -/
theorem powerSeriesCoordinatePowerIdeal_eq_boxVanishing (d r : ℕ) :
    powerSeriesCoordinatePowerIdeal K d r = powerSeriesBoxVanishingIdeal K d r := by
  apply le_antisymm (powerSeriesCoordinatePowerIdeal_le_boxVanishing K d r)
  intro f hf
  rw [← powerSeries_sum_outsideBoxParts K d r f hf]
  apply (powerSeriesCoordinatePowerIdeal K d r).sum_mem
  intro i hi
  obtain ⟨g, hg⟩ := powerSeriesOutsideBoxPart_dvd K d r f i
  rw [hg]
  exact Ideal.mul_mem_right _ _ (Ideal.subset_span ⟨i, rfl⟩)

/-- Extract the actual coefficients at all exponents in the finite box. -/
def powerSeriesBoxCoefficients (d r : ℕ) :
    MvPowerSeries (Fin d) K →ₗ[K] (PowerSeriesPowerBox d r → K) where
  toFun f a := MvPowerSeries.coeff a.val f
  map_add' f g := by ext a; exact map_add (MvPowerSeries.coeff a.val) f g
  map_smul' c f := by ext a; exact (MvPowerSeries.coeff a.val).map_smul c f

@[simp]
theorem powerSeriesBoxCoefficients_apply (d r : ℕ) (f : MvPowerSeries (Fin d) K)
    (a : PowerSeriesPowerBox d r) :
    powerSeriesBoxCoefficients K d r f a = MvPowerSeries.coeff a.val f := rfl

theorem powerSeriesBoxCoefficients_surjective (d r : ℕ) :
    Function.Surjective (powerSeriesBoxCoefficients K d r) := by
  classical
  intro c
  refine ⟨fun a => if h : ∀ i, a i < r then c ⟨a, h⟩ else 0, ?_⟩
  ext a
  simp [powerSeriesBoxCoefficients, MvPowerSeries.coeff_apply, a.property]
  rfl

theorem powerSeriesBoxCoefficients_ker (d r : ℕ) :
    LinearMap.ker (powerSeriesBoxCoefficients K d r) =
      (powerSeriesCoordinatePowerIdeal K d r).restrictScalars K := by
  rw [powerSeriesCoordinatePowerIdeal_eq_boxVanishing]
  ext f
  rw [LinearMap.mem_ker, funext_iff]
  change (∀ a : PowerSeriesPowerBox d r, MvPowerSeries.coeff a.val f = 0) ↔
    ∀ a : Fin d →₀ ℕ, (∀ i, a i < r) → MvPowerSeries.coeff a f = 0
  exact ⟨fun h a ha => h ⟨a, ha⟩, fun h a => h a.val a.property⟩

/-- The actual coordinate-power quotient is identified with its actual
bounded coefficients. This is an isomorphism of the original `K`-modules. -/
def powerSeriesPowerQuotientEquiv (d r : ℕ) :
    (MvPowerSeries (Fin d) K ⧸ powerSeriesCoordinatePowerIdeal K d r) ≃ₗ[K]
      (PowerSeriesPowerBox d r → K) :=
  (Submodule.quotEquivOfEq _ _ (powerSeriesBoxCoefficients_ker K d r).symm).trans
    ((powerSeriesBoxCoefficients K d r).quotKerEquivOfSurjective
      (powerSeriesBoxCoefficients_surjective K d r))

/-- The quotient comparison is literally coefficient extraction on a
representative, not a chosen vector-space isomorphism. -/
@[simp]
theorem powerSeriesPowerQuotientEquiv_apply_mk (d r : ℕ)
    (f : MvPowerSeries (Fin d) K) (a : PowerSeriesPowerBox d r) :
    powerSeriesPowerQuotientEquiv K d r
      (Ideal.Quotient.mk (powerSeriesCoordinatePowerIdeal K d r) f) a =
        MvPowerSeries.coeff a.val f := rfl

/-- The desired actual `K`-basis of the quotient, obtained from its
coefficient isomorphism. The next theorem identifies every vector with
the original monomial class. -/
def powerSeriesPowerQuotientBasis (d r : ℕ) :
    Module.Basis (PowerSeriesPowerBox d r) K
      (MvPowerSeries (Fin d) K ⧸ powerSeriesCoordinatePowerIdeal K d r) :=
  (Pi.basisFun K (PowerSeriesPowerBox d r)).map (powerSeriesPowerQuotientEquiv K d r).symm

/-- Every basis vector is exactly the class of its bounded monomial. -/
theorem powerSeriesPowerQuotientBasis_apply (d r : ℕ) (a : PowerSeriesPowerBox d r) :
    powerSeriesPowerQuotientBasis K d r a =
      Ideal.Quotient.mk (powerSeriesCoordinatePowerIdeal K d r)
        (MvPowerSeries.monomial a.val (1 : K)) := by
  classical
  apply (powerSeriesPowerQuotientEquiv K d r).injective
  ext b
  simp only [powerSeriesPowerQuotientBasis, Module.Basis.map_apply,
    LinearEquiv.apply_symm_apply, Pi.basisFun_apply,
    powerSeriesPowerQuotientEquiv_apply_mk, MvPowerSeries.coeff_monomial]
  by_cases h : a = b
  · subst b
    simp
  · have hab : a.val ≠ b.val := fun hh => h (Subtype.ext hh)
    simp [Ne.symm h, Ne.symm hab]

/-- Equivalently, the basis consists of the literal products of coordinate
powers, as written in Exposé IV.5.5. -/
theorem powerSeriesPowerQuotientBasis_apply_prod (d r : ℕ) (a : PowerSeriesPowerBox d r) :
    powerSeriesPowerQuotientBasis K d r a =
      Ideal.Quotient.mk (powerSeriesCoordinatePowerIdeal K d r)
        (∏ i : Fin d, (MvPowerSeries.X i : MvPowerSeries (Fin d) K) ^ a.val i) := by
  rw [powerSeriesPowerQuotientBasis_apply, MvPowerSeries.monomial_one_eq,
    Finsupp.prod_fintype _ _ (fun _ => pow_zero _)]

/-- The coordinates in the actual monomial basis are the corresponding
coefficients of any representative series. -/
@[simp]
theorem powerSeriesPowerQuotientBasis_repr_mk (d r : ℕ)
    (f : MvPowerSeries (Fin d) K) (a : PowerSeriesPowerBox d r) :
    (powerSeriesPowerQuotientBasis K d r).repr
      (Ideal.Quotient.mk (powerSeriesCoordinatePowerIdeal K d r) f) a =
        MvPowerSeries.coeff a.val f := by
  simp [powerSeriesPowerQuotientBasis]

instance powerSeriesPowerQuotient_finite (d r : ℕ) :
    Module.Finite K (MvPowerSeries (Fin d) K ⧸ powerSeriesCoordinatePowerIdeal K d r) :=
  Module.Finite.of_basis (powerSeriesPowerQuotientBasis K d r)

/-- The quotient has dimension `r^d`. This includes dimension one when
`d=0` (even for `r=0`), and dimension zero when `r=0<d`. -/
theorem powerSeriesPowerQuotient_finrank (d r : ℕ) :
    Module.finrank K (MvPowerSeries (Fin d) K ⧸ powerSeriesCoordinatePowerIdeal K d r) =
      r ^ d := by
  rw [Module.finrank_eq_card_basis (powerSeriesPowerQuotientBasis K d r),
    powerSeriesPowerBox_card]

end SGA.SGA2.ExposeIV
