/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.Foundations.Limits.PropertiesLimitProper
import SGA.Foundations.Limits.PropertiesLimitSurjective
import SGA.Foundations.Limits.SpreadingOutSubfield
import SGA.Foundations.Limits.FibrePropertiesDescent

/-!
# Proper schemes over a field are defined over a small subfield

EGA IV 8.8.2 (ii) and 8.10.5 (xii) for the field `K = colim_s ℤ(s)`, the filtered union of its
subfields generated by finite subsets `s` (`Scheme.SpreadingOutSubfield.schemeDiagram`, a diagram
of noetherian affine schemes):

* `AlgebraicGeometry.Scheme.exists_isPullback_subfieldClosure_of_isProper`: a proper `K`-scheme
  `X` is `X₀ ×_{K₀} K` for a proper scheme `X₀` over the subfield `K₀ = ℤ(s) ⊆ K` generated by a
  finite subset `s` of `K`.
* `AlgebraicGeometry.Scheme.exists_isPullback_of_isAlgClosed_countable_of_isProper`: if `K` is
  algebraically closed, `X` is moreover the base change of a proper scheme over a countable
  algebraically closed subfield `k₀ ⊆ K`. In characteristic `0`, `k₀` embeds into `ℂ`.
* `AlgebraicGeometry.Scheme.exists_isPullback_subfieldClosure_of_limitDescends`,
  `Scheme.exists_isPullback_of_isAlgClosed_countable_of_limitDescends`: the same for finitely many
  properties at once, each descending along limits (`Scheme.LimitDescendsStatement`: proper,
  smooth, étale, finite, affine, separated, surjective, open or closed immersion, ...).

Geometric connectedness of the model needs no descent argument: if `X ⟶ Spec K` is geometrically
connected, so is every model `X₀ ⟶ Spec K₀` (`GeometricallyConnected.of_isPullback`, since
`Spec K ⟶ Spec K₀` is surjective).

## References

* [EGA IV₃, 8.8.2, 8.10.5][EGA4]
* [Stacks Project, Tag 01ZM](https://stacks.math.columbia.edu/tag/01ZM),
  [Tag 081F](https://stacks.math.columbia.edu/tag/081F)
-/

universe u

open CategoryTheory Limits

namespace AlgebraicGeometry

open Scheme.SpreadingOutSubfield

instance (K : Type u) [Field K] (F : (FGSubfield K)ᵒᵖ) : IsNoetherian ((schemeDiagram K).obj F) :=
  inferInstanceAs (IsNoetherian (Spec (CommRingCat.of F.unop.1)))

set_option backward.isDefEq.respectTransparency false in
/-- EGA IV 8.8.2 (ii) and 8.10.5 (xii) over a field: a proper `K`-scheme is the base change of a
proper scheme over the subfield `ℤ(s) ⊆ K` generated by a finite subset `s`. -/
theorem Scheme.exists_isPullback_subfieldClosure_of_isProper (K : Type u) [Field K]
    {X : Scheme.{u}} (q : X ⟶ Spec (.of K)) [IsProper q] :
    ∃ (s : Finset K) (X₀ : Scheme.{u}) (q₀ : X₀ ⟶ Spec (.of (Subfield.closure (s : Set K))))
      (e : X ⟶ X₀), IsProper q₀ ∧
        IsPullback e q q₀
          (Spec.map (CommRingCat.ofHom (Subfield.closure (s : Set K)).subtype)) := by
  have : LocallyOfFinitePresentation q := inferInstance
  let c := Scheme.Spec.mapCone (cocone K).op
  have hc : IsLimit c := isLimitSpecCone K
  obtain ⟨j, Xj, qj, e, _, _, _, h⟩ :=
    Scheme.exists_isPullback_of_isLimit_of_locallyOfFinitePresentation (E := schemeDiagram K)
      hc q
  have : IsProper (q : X ⟶ c.pt) := ‹IsProper q›
  obtain ⟨k, g, hk⟩ := Scheme.limitDescends_isProper_of_isNoetherian hc qj h
  let M₀ : Scheme.LimitModel c q j := { obj := Xj, hom := qj, proj := e, isPullback := h }
  let M := M₀.lower g
  have hM : IsPullback M.proj q M.hom (c.π.app k) := M.isPullback
  obtain ⟨⟨F, s, rfl⟩⟩ := k
  exact ⟨s, M.obj, M.hom, M.proj, hk, hM⟩

set_option backward.isDefEq.respectTransparency false in
/-- A proper scheme over an algebraically closed field `K` is the base change of a proper scheme
over a countable algebraically closed subfield `k₀ ⊆ K` (the algebraic closure in `K` of the
subfield of `Scheme.exists_isPullback_subfieldClosure_of_isProper`). -/
theorem Scheme.exists_isPullback_of_isAlgClosed_countable_of_isProper (K : Type u) [Field K]
    [IsAlgClosed K] {X : Scheme.{u}} (q : X ⟶ Spec (.of K)) [IsProper q] :
    ∃ (k₀ : Subfield K) (X₀ : Scheme.{u}) (q₀ : X₀ ⟶ Spec (.of k₀)) (e : X ⟶ X₀),
      IsAlgClosed k₀ ∧ Countable k₀ ∧ IsProper q₀ ∧
        IsPullback e q q₀ (Spec.map (CommRingCat.ofHom k₀.subtype)) := by
  obtain ⟨s, X₀, q₀, e, hq₀, h⟩ := Scheme.exists_isPullback_subfieldClosure_of_isProper K q
  obtain ⟨k₀, hFk, hk₀, hk₀c⟩ := Subfield.exists_isAlgClosed_countable_closure_le K s
  obtain ⟨e', h'⟩ := Scheme.exists_isPullback_subfield_of_le hFk h
  exact ⟨k₀, _, _, e', hk₀, hk₀c, MorphismProperty.pullback_snd _ _ hq₀, h'⟩

set_option backward.isDefEq.respectTransparency false in
/-- EGA IV 8.8.2 (ii) and 8.10.5 over a field, for finitely many properties at once: let `X` be a
`K`-scheme of finite type and quasi-separated whose structure morphism has the properties `P i`,
each stable under base change and descending along limits (`Scheme.LimitDescendsStatement`; for
example proper, smooth, étale, finite, separated, surjective, affine). Then `X` is the base change
of a scheme of finite type and quasi-separated over the subfield `ℤ(s) ⊆ K` generated by a finite
subset `s`, whose structure morphism has all the `P i`.

The stability hypothesis `hP'` is explicit because instance synthesis does not see through a
family written `![@IsProper, @Smooth]`. For `P := ![@IsProper, @Smooth]` (typed as
`Fin 2 → MorphismProperty Scheme`) pass
`Fin.forall_fin_two.mpr ⟨inferInstanceAs (IsStableUnderBaseChange @IsProper), inferInstanceAs …⟩`,
`Fin.forall_fin_two.mpr ⟨Scheme.properLimitStatement, Scheme.limitDescends_smooth⟩` and
`Fin.forall_fin_two.mpr ⟨‹IsProper q›, ‹Smooth q›⟩`. -/
theorem Scheme.exists_isPullback_subfieldClosure_of_limitDescends (K : Type u) [Field K]
    {X : Scheme.{u}} (q : X ⟶ Spec (.of K)) [LocallyOfFiniteType q] [QuasiCompact q]
    [QuasiSeparated q] {n : ℕ} (P : Fin n → MorphismProperty Scheme.{u})
    (hP' : ∀ i, (P i).IsStableUnderBaseChange)
    (hP : ∀ i, Scheme.LimitDescendsStatement.{u} (P i)) (hq : ∀ i, P i q) :
    ∃ (s : Finset K) (X₀ : Scheme.{u}) (q₀ : X₀ ⟶ Spec (.of (Subfield.closure (s : Set K))))
      (e : X ⟶ X₀), LocallyOfFiniteType q₀ ∧ QuasiCompact q₀ ∧ QuasiSeparated q₀ ∧
        (∀ i, P i q₀) ∧ IsPullback e q q₀
          (Spec.map (CommRingCat.ofHom (Subfield.closure (s : Set K)).subtype)) := by
  classical
  have := hP'
  have : LocallyOfFinitePresentation q := inferInstance
  let c := Scheme.Spec.mapCone (cocone K).op
  have hc : IsLimit c := isLimitSpecCone K
  obtain ⟨j, Xj, qj, e, _, _, _, h⟩ :=
    Scheme.exists_isPullback_of_isLimit_of_locallyOfFinitePresentation (E := schemeDiagram K)
      hc q
  have key (i : Fin n) := hP i (schemeDiagram K) c hc qj e q h (hq i)
  choose k g hg using key
  obtain ⟨m, φ, hφ⟩ := IsCofiltered.inf_exists (insert j (Finset.univ.image k))
    (Finset.univ.image fun i : Fin n ↦
      (⟨k i, j, by simp, by simp, g i⟩ : Σ' (X Y : (FGSubfield K)ᵒᵖ)
        (_ : X ∈ insert j (Finset.univ.image k)) (_ : Y ∈ insert j (Finset.univ.image k)),
          X ⟶ Y))
  let g₀ : m ⟶ j := φ (by simp)
  let M₀ : Scheme.LimitModel c q j := { obj := Xj, hom := qj, proj := e, isPullback := h }
  let M := M₀.lower g₀
  have hM (i : Fin n) : P i M.hom := by
    have ht : φ (X := k i) (by simp) ≫ g i = g₀ :=
      hφ (by simp) (by simp) (Finset.mem_image_of_mem _ (Finset.mem_univ i))
    have := Scheme.pullback_snd_comp_of_isStableUnderBaseChange qj
      ((schemeDiagram K).map (φ (X := k i) (by simp))) ((schemeDiagram K).map (g i)) (hg i)
    rw [← Functor.map_comp, ht] at this
    exact this
  obtain ⟨⟨F, s, rfl⟩⟩ := m
  exact ⟨s, M.obj, M.hom, M.proj, inferInstance, inferInstance, inferInstance, hM, M.isPullback⟩

set_option backward.isDefEq.respectTransparency false in
/-- `Scheme.exists_isPullback_subfieldClosure_of_limitDescends` over an algebraically closed field
`K`: the model can be taken over a countable algebraically closed subfield `k₀ ⊆ K`. The hypotheses
are those of `Scheme.exists_isPullback_subfieldClosure_of_limitDescends` (see there for how to
supply `hP'` for a family `![@IsProper, @Smooth]`). -/
theorem Scheme.exists_isPullback_of_isAlgClosed_countable_of_limitDescends (K : Type u) [Field K]
    [IsAlgClosed K] {X : Scheme.{u}} (q : X ⟶ Spec (.of K)) [LocallyOfFiniteType q]
    [QuasiCompact q] [QuasiSeparated q] {n : ℕ} (P : Fin n → MorphismProperty Scheme.{u})
    (hP' : ∀ i, (P i).IsStableUnderBaseChange)
    (hP : ∀ i, Scheme.LimitDescendsStatement.{u} (P i)) (hq : ∀ i, P i q) :
    ∃ (k₀ : Subfield K) (X₀ : Scheme.{u}) (q₀ : X₀ ⟶ Spec (.of k₀)) (e : X ⟶ X₀),
      IsAlgClosed k₀ ∧ Countable k₀ ∧ LocallyOfFiniteType q₀ ∧ QuasiCompact q₀ ∧
        QuasiSeparated q₀ ∧ (∀ i, P i q₀) ∧
          IsPullback e q q₀ (Spec.map (CommRingCat.ofHom k₀.subtype)) := by
  obtain ⟨s, X₀, q₀, e, _, _, _, hq₀, h⟩ :=
    Scheme.exists_isPullback_subfieldClosure_of_limitDescends K q P hP' hP hq
  have := hP'
  obtain ⟨k₀, hFk, hk₀, hk₀c⟩ := Subfield.exists_isAlgClosed_countable_closure_le K s
  obtain ⟨e', h'⟩ := Scheme.exists_isPullback_subfield_of_le hFk h
  exact ⟨k₀, _, _, e', hk₀, hk₀c, inferInstance, inferInstance, inferInstance,
    fun i ↦ MorphismProperty.pullback_snd _ _ (hq₀ i), h'⟩

end AlgebraicGeometry
