/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.Foundations.Limits.PropertiesLimitLocal

/-!
# Closed immersions and isomorphisms over a limit descend to a finite level

Let `c.pt = lim E i` be the limit of a cofiltered diagram of quasi-compact and quasi-separated
schemes with affine transition maps, `X_j ⟶ E j` of finite presentation and `X ⟶ c.pt` its base
change.

* `AlgebraicGeometry.Scheme.limitDescends_isClosedImmersion` (EGA IV 8.10.5 (iv)): if `X ⟶ c.pt` is
  a closed immersion, so is `X_j ×_{E j} E k ⟶ E k` for some `k`. Affine case: `X_k` becomes
  affine at some level (Stacks 01Z6), and the finitely many generators of `Γ(X_k)` over `Γ(E k)`
  come from `Γ(E l)` at some level `l` because `Γ(c.pt) ⟶ Γ(X)` is surjective; the general case
  by `Scheme.limitDescends_of_affine`.
* `AlgebraicGeometry.Scheme.limitDescends_isIso` (EGA IV 8.10.5 (i), 8.8.2.5): isomorphisms
  descend, from EGA IV 8.8.2 (i) (`Scheme.exists_iso_of_isPullback`).
* `CommRingCat.IsPushout.subring_eq_top`: the cocone point of a pushout of commutative rings is
  generated by the images of the two maps.

## References

* [EGA IV₃, 8.8.2, 8.10.5][EGA4]
* [Stacks Project, Tag 01Z6](https://stacks.math.columbia.edu/tag/01Z6)
-/

universe u

open CategoryTheory Limits

namespace CommRingCat

/-- The cocone point of a pushout of commutative rings is generated as a ring by the images of
the two maps: a subring containing both images is everything. -/
lemma IsPushout.subring_eq_top {R A B P : CommRingCat.{u}} {f : R ⟶ A} {g : R ⟶ B}
    {inl : A ⟶ P} {inr : B ⟶ P} (h : IsPushout f g inl inr) (T : Subring P)
    (hl : ∀ a, inl a ∈ T) (hr : ∀ b, inr b ∈ T) : T = ⊤ := by
  let il : A ⟶ CommRingCat.of T := CommRingCat.ofHom (inl.hom.codRestrict T hl)
  let ir : B ⟶ CommRingCat.of T := CommRingCat.ofHom (inr.hom.codRestrict T hr)
  have hw : f ≫ il = g ≫ ir := by
    ext x
    change (f ≫ inl) x = (g ≫ inr) x
    rw [h.w]
  have hid : h.desc il ir hw ≫ CommRingCat.ofHom T.subtype = 𝟙 P := by
    apply h.hom_ext
    · rw [h.inl_desc_assoc]
      ext x
      rfl
    · rw [h.inr_desc_assoc]
      ext x
      rfl
  rw [eq_top_iff]
  intro x _
  have : (h.desc il ir hw ≫ CommRingCat.ofHom T.subtype) x = x := by rw [hid]; rfl
  rw [← this]
  exact (h.desc il ir hw x).2

end CommRingCat

namespace AlgebraicGeometry

/-- `X ×_S T'` along `a ≫ b` is the base change of `X ×_S T` along `a`, as arrows over `T'`. -/
noncomputable def Scheme.pullbackSndCompArrowIso {X S T T' : Scheme.{u}} (q : X ⟶ S)
    (a : T' ⟶ T) (b : T ⟶ S) :
    Arrow.mk (pullback.snd q (a ≫ b)) ≅ Arrow.mk (pullback.snd (pullback.snd q b) a) :=
  Arrow.isoMk ((IsPullback.of_right' (IsPullback.of_hasPullback q (a ≫ b))
    (IsPullback.of_hasPullback q b)).isoIsPullback _ _ (IsPullback.of_hasPullback _ _))
    (Iso.refl _) (by simp)

/-- Transport of a property of `pullback.snd q g` along an equality `g = g'`. -/
lemma Scheme.of_pullback_snd_eq {P : MorphismProperty Scheme.{u}} {X S T : Scheme.{u}}
    {q : X ⟶ S} {g g' : T ⟶ S} (h : g = g') (hP : P (pullback.snd q g)) :
    P (pullback.snd q g') := by
  subst h
  exact hP

set_option backward.isDefEq.respectTransparency false in
/-- EGA IV 8.10.5 (iv), affine case: closed immersions descend along limits of affine schemes. -/
theorem Scheme.limitDescendsAffine_isClosedImmersion :
    Scheme.LimitDescendsAffineStatement.{u} @IsClosedImmersion := by
  intro I _ _ E _ _ c hc j X Xj qj _ _ _ e q h hq
  classical
  have : IsAffine c.pt := Scheme.isAffine_of_isLimit c hc
  have : IsAffine X := isAffine_of_isAffineHom q
  have := Scheme.compactSpace_baseChangeDiagram (E := E) qj
  have := Scheme.quasiSeparatedSpace_baseChangeDiagram (E := E) qj
  have : IsAffine (Scheme.baseChangeCone h).pt := ‹IsAffine X›
  -- the model becomes affine at some level `k₀`
  obtain ⟨k₀, hk₀⟩ := Scheme.exists_isAffine_of_isLimit (Scheme.baseChangeDiagram E qj)
    (Scheme.baseChangeCone h) (Scheme.isLimitBaseChangeCone hc h)
  let qk := pullback.snd qj (E.map k₀.hom)
  let pk := (Scheme.baseChangeCone h).π.app k₀
  have hk : IsPullback pk q qk (c.π.app k₀.left) := Scheme.isPullback_baseChangeCone h k₀
  have : IsAffine (pullback qj (E.map k₀.hom)) := hk₀
  suffices H : ∃ l : Over k₀.left, IsClosedImmersion (pullback.snd qk (E.map l.hom)) by
    obtain ⟨l, hl⟩ := H
    refine ⟨l.left, l.hom ≫ k₀.hom, ?_⟩
    have h' := (MorphismProperty.arrow_mk_iso_iff @IsClosedImmersion
      (Scheme.pullbackSndCompArrowIso qj (E.map l.hom) (E.map k₀.hom))).mpr hl
    exact Scheme.of_pullback_snd_eq (E.map_comp l.hom k₀.hom).symm h'
  let D := Scheme.baseChangeDiagram E qk
  let C := Scheme.baseChangeCone hk
  have hC := Scheme.isLimitBaseChangeCone hc hk
  have := Scheme.compactSpace_baseChangeDiagram (E := E) qk
  have hsurj := (IsClosedImmersion.isAffine_surjective_of_isAffine q).2
  -- transition maps of `D`
  have hDfst {l l' : Over k₀.left} (φ : l' ⟶ l) :
      D.map φ ≫ pullback.fst qk (E.map l.hom) = pullback.fst qk (E.map l'.hom) := by
    simp [D, pullback.map]
  have hDsnd {l l' : Over k₀.left} (φ : l' ⟶ l) :
      D.map φ ≫ pullback.snd qk (E.map l.hom) = pullback.snd qk (E.map l'.hom) ≫ E.map φ.left := by
    simp [D, pullback.map]
  -- every section of `X_{k₀}` comes from the base at some level, and then at every lower level
  have claim (b : Γ(pullback qj (E.map k₀.hom), ⊤)) : ∃ l : Over k₀.left,
      ∀ (l' : Over k₀.left) (_ : l' ⟶ l), (pullback.fst qk (E.map l'.hom)).appTop b ∈
        (pullback.snd qk (E.map l'.hom)).appTop.hom.range := by
    obtain ⟨a, ha⟩ := hsurj (pk.appTop b)
    obtain ⟨i, t, rfl⟩ := exists_appTop_π_eq_of_isLimit E c hc a
    let l₀ : Over k₀.left := Over.mk (IsCofiltered.minToLeft k₀.left i)
    let ρ : l₀.left ⟶ i := IsCofiltered.minToRight k₀.left i
    let t' := (E.map ρ).appTop t
    let s := (pullback.fst qk (E.map l₀.hom)).appTop b - (pullback.snd qk (E.map l₀.hom)).appTop t'
    have hs : (C.π.app l₀).appTop s = 0 := by
      have e1 : C.π.app l₀ ≫ pullback.fst qk (E.map l₀.hom) = pk := by simp [C]
      have e2a : C.π.app l₀ ≫ pullback.snd qk (E.map l₀.hom) = q ≫ c.π.app l₀.left := by
        simp [C]
      have e2 : C.π.app l₀ ≫ pullback.snd qk (E.map l₀.hom) ≫ E.map ρ = q ≫ c.π.app i := by
        rw [reassoc_of% e2a, Cone.w]
      have e1' : (C.π.app l₀).appTop ((pullback.fst qk (E.map l₀.hom)).appTop b) = pk.appTop b :=
        congrArg (fun φ ↦ φ.appTop b) e1
      have e2' : (C.π.app l₀).appTop
          ((pullback.snd qk (E.map l₀.hom)).appTop ((E.map ρ).appTop t)) =
            q.appTop ((c.π.app i).appTop t) :=
        congrArg (fun φ ↦ φ.appTop t) e2
      change (C.π.app l₀).appTop ((pullback.fst qk (E.map l₀.hom)).appTop b -
        (pullback.snd qk (E.map l₀.hom)).appTop ((E.map ρ).appTop t)) = 0
      rw [map_sub, e1', e2', ha, sub_self]
    obtain ⟨l, f, hf⟩ := exists_appTop_map_eq_zero_of_isLimit D C hC s hs
    refine ⟨l, fun l' φ ↦ ⟨(E.map (φ ≫ f).left).appTop t', ?_⟩⟩
    have hf' : (D.map (φ ≫ f)).appTop s = 0 := by
      rw [D.map_comp, Scheme.Hom.comp_appTop, CommRingCat.comp_apply, hf, map_zero]
    have e3 : (D.map (φ ≫ f)).appTop ((pullback.fst qk (E.map l₀.hom)).appTop b) =
        (pullback.fst qk (E.map l'.hom)).appTop b :=
      congrArg (fun F ↦ F.appTop b) (hDfst (φ ≫ f))
    have e4 : (D.map (φ ≫ f)).appTop ((pullback.snd qk (E.map l₀.hom)).appTop t') =
        (pullback.snd qk (E.map l'.hom)).appTop ((E.map (φ ≫ f).left).appTop t') :=
      congrArg (fun F ↦ F.appTop t') (hDsnd (φ ≫ f))
    have hf'' : (D.map (φ ≫ f)).appTop ((pullback.fst qk (E.map l₀.hom)).appTop b) -
        (D.map (φ ≫ f)).appTop ((pullback.snd qk (E.map l₀.hom)).appTop t') = 0 := by
      rw [← map_sub]
      exact hf'
    rw [e3, e4] at hf''
    exact (sub_eq_zero.mp hf'').symm
  -- finitely many generators
  have hft : qk.appTop.hom.FiniteType :=
    RingHom.FiniteType.of_finitePresentation qk.finitePresentation_appTop
  let := qk.appTop.hom.toAlgebra
  obtain ⟨S, hS⟩ := (show Algebra.FiniteType Γ(E.obj k₀.left, ⊤)
    Γ(pullback qj (E.map k₀.hom), ⊤) from hft).out
  choose L hL using claim
  obtain ⟨m, fm⟩ := IsCofiltered.inf_objs_exists (S.image L)
  replace fm (b : S) : m ⟶ L b := (@fm (L b) (Finset.mem_image_of_mem L b.2)).some
  refine ⟨m, IsClosedImmersion.of_surjective_of_isAffine _ fun y ↦ ?_⟩
  -- the global sections of `X_m` are generated by those of `X_{k₀}` and of `E m`
  have hpo := isPushout_appTop_of_isPullback (IsPullback.of_hasPullback qk (E.map m.hom))
  let T := (pullback.snd qk (E.map m.hom)).appTop.hom.range
  suffices hT : T = ⊤ by
    have : y ∈ T := hT ▸ Subring.mem_top y
    exact this
  refine CommRingCat.IsPushout.subring_eq_top hpo T (fun b ↦ ?_) (fun a ↦ ⟨a, rfl⟩)
  -- the preimage of `T` in `Γ(X_{k₀})` contains `Γ(E k₀)` and the generators
  let T' := T.comap (pullback.fst qk (E.map m.hom)).appTop.hom
  have hT' : T' = ⊤ := by
    rw [eq_top_iff]
    have hS' : Subring.closure (Set.range (algebraMap Γ(E.obj k₀.left, ⊤)
        Γ(pullback qj (E.map k₀.hom), ⊤)) ∪ (S : Set _)) = ⊤ := by
      rw [← Algebra.adjoin_eq_ring_closure, hS]
      rfl
    rw [← hS', Subring.closure_le]
    rintro x (⟨a, rfl⟩ | hx)
    · refine ⟨(E.map m.hom).appTop a, ?_⟩
      have := congrArg (fun φ ↦ φ a) hpo.w
      simpa [RingHom.algebraMap_toAlgebra] using this.symm
    · exact hL x m (fm ⟨x, hx⟩)
  have : b ∈ T' := hT' ▸ Subring.mem_top b
  exact this

/-- EGA IV 8.10.5 (iv): closed immersions descend along limits of cofiltered diagrams of
quasi-compact and quasi-separated schemes with affine transition maps. -/
theorem Scheme.limitDescends_isClosedImmersion :
    Scheme.LimitDescendsStatement.{u} @IsClosedImmersion :=
  Scheme.limitDescends_of_affine Scheme.limitDescendsAffine_isClosedImmersion

end AlgebraicGeometry

namespace AlgebraicGeometry

set_option backward.isDefEq.respectTransparency false in
/-- EGA IV 8.10.5 (i): isomorphisms descend along limits of cofiltered diagrams of quasi-compact
and quasi-separated schemes with affine transition maps (from EGA IV 8.8.2 (i),
`Scheme.exists_iso_of_isPullback`). -/
theorem Scheme.limitDescends_isIso :
    Scheme.LimitDescendsStatement.{u} (MorphismProperty.isomorphisms Scheme.{u}) := by
  intro I _ _ E _ _ _ c hc j X Xj qj _ _ _ e q h hq
  have : IsIso q := hq
  have h₂ : IsPullback (q ≫ c.π.app j) q (𝟙 (E.obj j)) (c.π.app j) :=
    IsPullback.of_vert_isIso ⟨by simp⟩
  obtain ⟨k, θ, hθ, -⟩ := Scheme.exists_iso_of_isPullback hc h h₂
  refine ⟨k.left, k.hom, ?_⟩
  change IsIso (pullback.snd qj (E.map k.hom))
  rw [← hθ]
  infer_instance

end AlgebraicGeometry
