/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import Mathlib.Algebra.AlgebraicCard
import Mathlib.FieldTheory.AlgebraicClosure
import Mathlib.SetTheory.Cardinal.Subfield
import SGA.Foundations.Limits.SpreadingOutGluing

/-!
# Spreading out schemes over a subfield

EGA IV 8.8.2 (ii) for the field `K = colim_s ℤ(s)`, the filtered union of its subfields generated
by finite subsets `s`:

* `AlgebraicGeometry.Scheme.spreadingOutSubfieldStatement`: a `K`-scheme `X` of finite type and
  quasi-separated (quasi-compact, quasi-separated, locally of finite type) is `X₀ ×_{K₀} K` for a
  scheme `X₀` of finite type and quasi-separated over the subfield `K₀ = ℤ(s) ⊆ K` generated by a
  finite subset `s` of `K`.
* `AlgebraicGeometry.Scheme.exists_isPullback_of_isAlgClosed_countable`: if `K` is algebraically
  closed, `X` is moreover defined over a countable algebraically closed subfield `k₀ ⊆ K` (the
  relative algebraic closure of `ℤ(s)` in `K`, `Subfield.exists_isAlgClosed_countable_closure_le`;
  the base change of a model to a larger subfield is `Scheme.exists_isPullback_subfield_of_le`).

Models with properties (proper, smooth, ...) are in
`SGA.Foundations.Limits.PropertiesLimitSubfield`.

## References

* [EGA IV₃, 8.8.2][EGA4]
* [Stacks Project, Tag 01ZM](https://stacks.math.columbia.edu/tag/01ZM)
-/

universe u

open CategoryTheory Limits Cardinal

/-- In an algebraically closed field `K`, the subfield generated by a finite set `s` is contained in
a countable algebraically closed subfield: the algebraic closure of `ℤ(s)` in `K`. -/
theorem Subfield.exists_isAlgClosed_countable_closure_le (K : Type u) [Field K] [IsAlgClosed K]
    (s : Finset K) :
    ∃ k₀ : Subfield K, Subfield.closure (s : Set K) ≤ k₀ ∧ IsAlgClosed k₀ ∧ Countable k₀ := by
  let F := Subfield.closure (s : Set K)
  let k₀ : Subfield K := (algebraicClosure F K).toSubfield
  have hFk : F ≤ k₀ := fun x hx ↦ (algebraicClosure F K).algebraMap_mem ⟨x, hx⟩
  have hk₀ : IsAlgClosed k₀ := IsAlgClosure.isAlgClosed (R := F) (K := algebraicClosure F K)
  have hF : Countable F := by
    rw [← Cardinal.mk_le_aleph0_iff]
    refine (Subfield.cardinalMk_closure_le_max _).trans (max_le ?_ le_rfl)
    exact Cardinal.mk_le_aleph0_iff.mpr (s.finite_toSet.countable.to_subtype)
  have hk₀c : Countable k₀ := by
    rw [← Cardinal.mk_le_aleph0_iff]
    have : #k₀ ≤ #{x : K // IsAlgebraic F x} :=
      Cardinal.mk_le_mk_of_subset fun x hx ↦ mem_algebraicClosure_iff.mp hx
    refine this.trans ((Algebraic.cardinalMk_le_max F K).trans (max_le ?_ le_rfl))
    exact Cardinal.mk_le_aleph0_iff.mpr hF
  exact ⟨k₀, hFk, hk₀, hk₀c⟩

namespace AlgebraicGeometry

namespace Scheme.SpreadingOutSubfield

variable (K : Type u) [Field K]

/-- The subfields of `K` generated by a finite subset, ordered by inclusion. -/
abbrev FGSubfield : Type u := {F : Subfield K // ∃ s : Finset K, F = Subfield.closure (s : Set K)}

instance : IsDirectedOrder (FGSubfield K) where
  directed F G := by
    classical
    obtain ⟨F, s, rfl⟩ := F
    obtain ⟨G, t, rfl⟩ := G
    refine ⟨⟨Subfield.closure ((s ∪ t : Finset K) : Set K), s ∪ t, rfl⟩, ?_, ?_⟩
    · exact Subfield.closure_mono (by simp)
    · exact Subfield.closure_mono (by simp)

instance : Nonempty (FGSubfield K) := ⟨⟨Subfield.closure ((∅ : Finset K) : Set K), ∅, rfl⟩⟩

/-- The diagram `F ↦ F` of the finitely generated subfields of `K`. -/
@[simps]
noncomputable abbrev diagram : FGSubfield K ⥤ CommRingCat.{u} where
  obj F := .of F.1
  map f := CommRingCat.ofHom (Subfield.inclusion (leOfHom f))

/-- The cocone of the inclusions `F ⟶ K`. -/
@[simps]
noncomputable abbrev cocone : Cocone (diagram K) where
  pt := .of K
  ι := { app F := CommRingCat.ofHom F.1.subtype }

/-- A field is the filtered colimit of its finitely generated subfields. -/
noncomputable def isColimitCocone : IsColimit (cocone K) := by
  have : ReflectsColimit (diagram K) (CategoryTheory.forget CommRingCat.{u}) :=
    reflectsColimit_of_reflectsIsomorphisms _ _
  refine isColimitOfReflects (CategoryTheory.forget CommRingCat.{u})
    (Types.FilteredColimit.isColimitOf _ _ (fun (x : K) ↦ ?_)
    fun (i j : FGSubfield K) xi xj hij ↦ ?_)
  · classical
    exact ⟨⟨Subfield.closure (({x} : Finset K) : Set K), {x}, rfl⟩,
      ⟨x, Subfield.subset_closure (by simp)⟩, rfl⟩
  · obtain ⟨m, him, hjm⟩ := exists_ge_ge i j
    exact ⟨m, homOfLE him, homOfLE hjm, Subtype.ext hij⟩

/-- The diagram `F ↦ Spec F` of schemes. -/
noncomputable abbrev schemeDiagram : (FGSubfield K)ᵒᵖ ⥤ Scheme.{u} :=
  (diagram K).op ⋙ Scheme.Spec

/-- `Spec K` is the limit of the `Spec F`. -/
noncomputable def isLimitSpecCone : IsLimit (Scheme.Spec.mapCone (cocone K).op) :=
  isLimitOfPreserves Scheme.Spec (isColimitCocone K).op

instance (F : (FGSubfield K)ᵒᵖ) : IsAffine ((schemeDiagram K).obj F) :=
  inferInstanceAs (IsAffine (Spec _))

instance {F G : (FGSubfield K)ᵒᵖ} (f : F ⟶ G) : IsAffineHom ((schemeDiagram K).map f) :=
  isAffineHom_of_isAffine _

end Scheme.SpreadingOutSubfield

open Scheme.SpreadingOutSubfield

set_option backward.isDefEq.respectTransparency false in
/-- EGA IV 8.8.2 (ii) over a field: a `K`-scheme of finite type and quasi-separated (`q`
locally of finite type, quasi-compact and quasi-separated) is the base change of a scheme of
finite type and quasi-separated over the subfield `ℤ(s) ⊆ K` generated by a finite subset `s`. -/
theorem Scheme.exists_isPullback_subfieldClosure (K : Type u) [Field K] {X : Scheme.{u}}
    (q : X ⟶ Spec (.of K)) [LocallyOfFiniteType q] [QuasiCompact q] [QuasiSeparated q] :
    ∃ (s : Finset K) (X₀ : Scheme.{u}) (q₀ : X₀ ⟶ Spec (.of (Subfield.closure (s : Set K))))
      (e : X ⟶ X₀), LocallyOfFiniteType q₀ ∧ QuasiCompact q₀ ∧ QuasiSeparated q₀ ∧
        IsPullback e q q₀
          (Spec.map (CommRingCat.ofHom (Subfield.closure (s : Set K)).subtype)) := by
  have : LocallyOfFinitePresentation q := inferInstance
  obtain ⟨⟨⟨F, s, rfl⟩⟩, Xj, qj, e, _, hqc, hqs, h⟩ :=
    Scheme.exists_isPullback_of_isLimit_of_locallyOfFinitePresentation
      (E := schemeDiagram K) (c := Scheme.Spec.mapCone (cocone K).op) (isLimitSpecCone K) q
  exact ⟨s, Xj, qj, e, inferInstance, hqc, hqs, h⟩

set_option backward.isDefEq.respectTransparency false in
/-- Base change of a model over a subfield `F ⊆ K` to a larger subfield `F ⊆ k₀ ⊆ K`: if
`X = X₀ ×_F K`, then `X = (X₀ ×_F k₀) ×_{k₀} K`. -/
theorem Scheme.exists_isPullback_subfield_of_le {K : Type u} [Field K] {F k₀ : Subfield K}
    (hFk : F ≤ k₀) {X X₀ : Scheme.{u}} {q : X ⟶ Spec (.of K)} {q₀ : X₀ ⟶ Spec (.of F)}
    {e : X ⟶ X₀} (h : IsPullback e q q₀ (Spec.map (CommRingCat.ofHom F.subtype))) :
    ∃ e' : X ⟶ pullback q₀ (Spec.map (CommRingCat.ofHom (Subfield.inclusion hFk))),
      IsPullback e' q (pullback.snd q₀ (Spec.map (CommRingCat.ofHom (Subfield.inclusion hFk))))
        (Spec.map (CommRingCat.ofHom k₀.subtype)) := by
  have hj : Spec.map (CommRingCat.ofHom F.subtype) =
      Spec.map (CommRingCat.ofHom k₀.subtype) ≫
        Spec.map (CommRingCat.ofHom (Subfield.inclusion hFk)) := by
    rw [← Spec.map_comp]
    rfl
  rw [hj] at h
  exact ⟨_, IsPullback.of_right' h (IsPullback.of_hasPullback q₀ _)⟩

set_option backward.isDefEq.respectTransparency false in
/-- A scheme of finite type and quasi-separated over an algebraically closed field `K` is the base
change of a scheme of finite type and quasi-separated over a countable algebraically closed
subfield `k₀ ⊆ K`: the algebraic closure in `K` of the subfield `ℤ(s)` of
`Scheme.exists_isPullback_subfieldClosure`. -/
theorem Scheme.exists_isPullback_of_isAlgClosed_countable (K : Type u) [Field K] [IsAlgClosed K]
    {X : Scheme.{u}} (q : X ⟶ Spec (.of K)) [LocallyOfFiniteType q] [QuasiCompact q]
    [QuasiSeparated q] :
    ∃ (k₀ : Subfield K) (X₀ : Scheme.{u}) (q₀ : X₀ ⟶ Spec (.of k₀)) (e : X ⟶ X₀),
      IsAlgClosed k₀ ∧ Countable k₀ ∧ LocallyOfFiniteType q₀ ∧ QuasiCompact q₀ ∧
        QuasiSeparated q₀ ∧ IsPullback e q q₀ (Spec.map (CommRingCat.ofHom k₀.subtype)) := by
  obtain ⟨s, X₀, q₀, e, h₁, h₂, h₃, h⟩ := Scheme.exists_isPullback_subfieldClosure K q
  obtain ⟨k₀, hFk, hk₀, hk₀c⟩ := Subfield.exists_isAlgClosed_countable_closure_le K s
  obtain ⟨e', h'⟩ := Scheme.exists_isPullback_subfield_of_le hFk h
  exact ⟨k₀, _, _, e', hk₀, hk₀c, inferInstance, inferInstance, inferInstance, h'⟩

/-- `Scheme.SpreadingOutSubfieldStatement` holds. -/
theorem Scheme.spreadingOutSubfieldStatement : Scheme.SpreadingOutSubfieldStatement.{u} :=
  fun K _ _ q _ _ _ ↦ Scheme.exists_isPullback_subfieldClosure K q

end AlgebraicGeometry
