/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.SGA1.ExposeV.NormalBase

/-!
# SGA 1, Exposé V, §8: the kernel of `π₁(Spec K) → π₁(Spec R)` for a normal base

V.8.2: let `R` be a noetherian normal domain with fraction field `K`, and `Ω` a separably closed
extension of `K`. Identify `π₁(Spec K)` with the Galois group of the separable closure `K̄` of `K`
in `Ω` (V.8.1). Then the kernel of `π₁(Spec K) → π₁(Spec R)` is the subgroup fixing the
compositum of the finite subextensions of `K̄/K` unramified over `R`
(`genericPointMapKernelStatement_holds`).

The proof is the one of SGA: an element `σ` is in the kernel iff it acts trivially on the
geometric points `A → K̄` of all étale coverings `Spec A` of `Spec R`
(`genericPointMap_symm_eq_one_iff`), i.e. iff it fixes the fields generated by their images; by
I.10.3 and I.10.6 (`SGA.SGA1.ExposeI.finite_etale_integralClosure`,
`SGA.SGA1.ExposeI.integralClosure_eq_adjoin_of_etale`) these fields are exactly the finite
extensions of `K` in `K̄` unramified over `R`.
-/

universe u

open CategoryTheory Limits CommAlgCat PreGaloisCategory TensorProduct Opposite

namespace SGA.SGA1.ExposeV

section Action

variable (K : Type u) [Field K] (Ω : Type u) [Field Ω] [IsSepClosed Ω] [Algebra K Ω]

/-- V.8.1: the element of `π₁(Spec K, a)` corresponding to `σ ∈ Gal(K̄/K)` acts on the geometric
points `B → Ω` by composition with `σ` (they take values in `K̄`). -/
lemma fundamentalGroupContinuousMulEquivGal_symm_hom_app (σ : Gal(separableClosure K Ω/K))
    (B : (FiniteEtale.{u} K)ᵒᵖ) (y : (fiberFunctor K Ω).obj B) :
    fiberToAlgHom K Ω (((fundamentalGroupContinuousMulEquivGal K Ω).symm σ).hom.app B y) =
      (separableClosure K Ω).val.comp (σ.toAlgHom.comp ((fiberToAlgHom K Ω y).codRestrict
        (separableClosure K Ω).toSubalgebra (algHom_apply_mem_separableClosure K Ω _))) := by
  set τ := (fundamentalGroupContinuousMulEquivGal K Ω).symm σ
  let E₀ := (fiberFunctor K Ω).leftUnitor ≪≫ (fiberFunctorSepClosureIso K Ω).symm
  have h : autMap (𝟭 _) E₀ τ = galContinuousMulEquivAut K (separableClosure K Ω) σ := by
    have h1 : (galContinuousMulEquivAut K (separableClosure K Ω)).symm (autMap (𝟭 _) E₀ τ) = σ :=
      (fundamentalGroupContinuousMulEquivGal K Ω).apply_symm_apply σ
    rw [← h1, ContinuousMulEquiv.apply_symm_apply]
  have h2 := congrArg (fun ρ : Aut (fiberFunctor K (separableClosure K Ω)) ↦ ρ.hom.app B) h
  simp only [autMap_hom_app] at h2
  have h3 : τ.hom.app B = E₀.hom.app B ≫
      (galContinuousMulEquivAut K (separableClosure K Ω) σ).hom.app B ≫ E₀.inv.app B := by
    rw [← h2]
    simp
  rw [h3]
  rfl

end Action

section Kernel

variable (R : Type u) [CommRing R] (K : Type u) [Field K] [Algebra R K] (Ω : Type u) [Field Ω]
  [Algebra K Ω] [Algebra R Ω] [IsScalarTower R K Ω]

/-- V.8.2 (proof): an element of `π₁(Spec K)` maps to `1` in `π₁(Spec R)` iff it acts trivially
on the fibers of all base changes `K ⊗_R A` of étale coverings `A` of `R`. -/
lemma genericPointMap_eq_one_iff (τ : fundamentalGroup K Ω) :
    genericPointMap R K Ω τ = 1 ↔
      ∀ A : FiniteEtale.{u} R, τ.hom.app ((FiniteEtale.baseChange R K).op.obj (op A)) = 𝟙 _ := by
  let e := FiniteEtale.fiberIsoBaseChangeFiber.{u} R Ω K
  constructor
  · intro h A
    have h1 := congrArg (fun ρ : fundamentalGroup R Ω ↦ ρ.hom.app (op A)) h
    simp only [genericPointMap, autMap_hom_app, Iso.symm_inv, Iso.symm_hom] at h1
    have h1' : (Iso.hom (1 : fundamentalGroup R Ω)).app (op A) = 𝟙 _ := rfl
    rw [h1'] at h1
    have h2 : τ.hom.app ((FiniteEtale.baseChange R K).op.obj (op A)) =
        e.inv.app (op A) ≫ (e.hom.app (op A) ≫
          τ.hom.app ((FiniteEtale.baseChange R K).op.obj (op A)) ≫ e.inv.app (op A)) ≫
            e.hom.app (op A) := by
      simp
    rw [h2, h1]
    simp
  · intro h
    apply Iso.ext
    refine NatTrans.ext (funext fun A ↦ ?_)
    change e.hom.app A ≫ τ.hom.app ((FiniteEtale.baseChange R K).op.obj A) ≫ e.inv.app A = 𝟙 _
    rw [h A.unop]
    simp

variable [IsSepClosed Ω]

/-- V.8.2 (proof): `σ ∈ Gal(K̄/K)` maps to `1` in `π₁(Spec R)` iff it fixes the values of all the
geometric points `K ⊗_R A → Ω` of the base changes of étale coverings `A` of `R`. -/
lemma genericPointMap_symm_eq_one_iff (σ : Gal(separableClosure K Ω/K)) :
    genericPointMap R K Ω ((fundamentalGroupContinuousMulEquivGal K Ω).symm σ) = 1 ↔
      ∀ (A : FiniteEtale.{u} R) (y : K ⊗[R] A →ₐ[K] Ω) (z : K ⊗[R] A),
        σ ⟨y z, algHom_apply_mem_separableClosure K Ω y z⟩ =
          ⟨y z, algHom_apply_mem_separableClosure K Ω y z⟩ := by
  rw [genericPointMap_eq_one_iff]
  refine forall_congr' fun A ↦ ?_
  constructor
  · intro h y z
    have h3 := fundamentalGroupContinuousMulEquivGal_symm_hom_app K Ω σ
      ((FiniteEtale.baseChange R K).op.obj (op A)) y
    rw [h] at h3
    have h4 := congrArg (fun f : K ⊗[R] A →ₐ[K] Ω ↦ f z) h3
    exact Subtype.ext h4.symm
  · intro h
    ext y : 1
    refine (fundamentalGroupContinuousMulEquivGal_symm_hom_app K Ω σ _ y).trans ?_
    ext z
    exact congrArg Subtype.val (h y z)

end Kernel

section Unramified

variable (R : Type u) [CommRing R] [IsDomain R] [IsIntegrallyClosed R] (Ω : Type u) [Field Ω]
  [IsSepClosed Ω] [Algebra (FractionRing R) Ω] [Algebra R Ω]
  [IsScalarTower R (FractionRing R) Ω]

local notation "K" => FractionRing R
local notation "Ksep" => separableClosure (FractionRing R) Ω

omit [IsSepClosed Ω] in
/-- I.10.6 applied to a geometric point: for an étale covering `A` of `Spec R` and a `K`-algebra
map `y : K ⊗_R A → Ω`, the subfield of `K̄` generated over `K` by the image of `A` is a finite
extension of `K` unramified over `R`. -/
lemma exists_unramified_of_algHom (A : FiniteEtale.{u} R) (y : K ⊗[R] A →ₐ[K] Ω) :
    ∃ L : IntermediateField K Ksep, (FiniteDimensional K L ∧ SGA.SGA1.ExposeI.IsUnramifiedOver R L)
      ∧ ∀ a : A, (⟨y (1 ⊗ₜ a), algHom_apply_mem_separableClosure K Ω y _⟩ : Ksep) ∈ L := by
  let y' : K ⊗[R] A →ₐ[K] Ksep :=
    y.codRestrict (separableClosure K Ω).toSubalgebra (algHom_apply_mem_separableClosure K Ω y)
  let f : A → Ksep := fun a ↦ y' (1 ⊗ₜ a)
  let L : IntermediateField K Ksep := IntermediateField.adjoin K (Set.range f)
  have hf (a : A) : f a ∈ L := IntermediateField.subset_adjoin K _ ⟨a, rfl⟩
  have hLsub : L.toSubalgebra = Algebra.adjoin K (Set.range f) :=
    IntermediateField.adjoin_toSubalgebra _
  refine ⟨L, ⟨?_, ?_⟩, hf⟩
  · have hle : Subalgebra.toSubmodule L.toSubalgebra ≤ LinearMap.range y'.toLinearMap := by
      rw [hLsub]
      intro w hw
      refine (Algebra.adjoin_le (S := y'.range) ?_) hw
      rintro _ ⟨a, rfl⟩
      exact ⟨1 ⊗ₜ a, rfl⟩
    have := Submodule.finiteDimensional_of_le hle
    exact this
  · let ι : A →ₐ[R] L :=
      { toFun := fun a ↦ ⟨f a, hf a⟩
        map_one' := Subtype.ext (show y' (1 ⊗ₜ 1) = 1 by
          rw [← Algebra.TensorProduct.one_def, map_one])
        map_mul' := fun a b ↦ Subtype.ext (show y' (1 ⊗ₜ (a * b)) = y' (1 ⊗ₜ a) * y' (1 ⊗ₜ b) by
          rw [← map_mul, Algebra.TensorProduct.tmul_mul_tmul, one_mul])
        map_zero' := Subtype.ext (show y' (1 ⊗ₜ 0) = 0 by rw [TensorProduct.tmul_zero, map_zero])
        map_add' := fun a b ↦ Subtype.ext (show y' (1 ⊗ₜ (a + b)) = y' (1 ⊗ₜ a) + y' (1 ⊗ₜ b) by
          rw [TensorProduct.tmul_add, map_add])
        commutes' := fun r ↦ by
          apply Subtype.ext
          apply Subtype.ext
          change y (1 ⊗ₜ algebraMap R A r) = _
          rw [← Algebra.TensorProduct.algebraMap_apply', ← AlgHom.restrictScalars_apply R,
            AlgHom.commutes]
          rfl }
    have hι : Algebra.adjoin K (Set.range ι) = ⊤ := by
      apply Subalgebra.map_injective (f := L.val) L.val.injective
      rw [AlgHom.map_adjoin, Algebra.map_top, IntermediateField.range_val, hLsub]
      congr 1
      ext w
      simp [ι]
    exact (SGA.SGA1.ExposeI.integralClosure_eq_adjoin_of_etale R R A K L ι hι).2

omit [IsSepClosed Ω] in
/-- I.10.3 applied to a geometric point: a finite extension `L` of `K` in `K̄` unramified over `R`
is the fraction field of the étale covering `integralClosure R L` of `Spec R`, so an automorphism
of `K̄/K` fixing the image of the geometric point `integralClosure R L → L ⊆ Ω` fixes `L`. -/
lemma exists_algHom_of_unramified [IsNoetherianRing R] (L : IntermediateField K Ksep)
    [FiniteDimensional K L] (hL : SGA.SGA1.ExposeI.IsUnramifiedOver R L) :
    ∃ (A : FiniteEtale.{u} R) (y : K ⊗[R] A →ₐ[K] Ω), ∀ σ : Gal(Ksep/K),
      (∀ a : A, σ ⟨y (1 ⊗ₜ a), algHom_apply_mem_separableClosure K Ω y _⟩ =
        ⟨y (1 ⊗ₜ a), algHom_apply_mem_separableClosure K Ω y _⟩) → σ ∈ L.fixingSubgroup := by
  have : Algebra.IsSeparable K L := Algebra.isSeparable_tower_bot_of_isSeparable K L Ksep
  obtain ⟨hfin, het, hfr⟩ := SGA.SGA1.ExposeI.finite_etale_integralClosure R L hL
  let B := integralClosure R L
  let A : FiniteEtale.{u} R := FiniteEtale.of R B
  let x : B →ₐ[R] Ω := (((separableClosure K Ω).val.comp L.val).restrictScalars R).comp B.val
  let y : K ⊗[R] A →ₐ[K] Ω :=
    Algebra.TensorProduct.lift (Algebra.ofId K Ω) x fun _ _ ↦ Commute.all _ _
  refine ⟨A, y, fun σ h ↦ ?_⟩
  have hx (b : B) : σ ((algebraMap B L b : L) : Ksep) = ((algebraMap B L b : L) : Ksep) := by
    have e : (⟨y (1 ⊗ₜ b), algHom_apply_mem_separableClosure K Ω y _⟩ : Ksep) =
        ((algebraMap B L b : L) : Ksep) := by
      apply Subtype.ext
      simp [y, x]
      rfl
    have := h b
    rwa [e] at this
  rw [IntermediateField.mem_fixingSubgroup_iff]
  intro l hl
  obtain ⟨a, b, -, hab⟩ := IsFractionRing.div_surjective (A := B) (⟨l, hl⟩ : L)
  have hl' : l = ((algebraMap B L a : L) : Ksep) / ((algebraMap B L b : L) : Ksep) := by
    rw [← IntermediateField.coe_div, hab]
  rw [hl', map_div₀, hx a, hx b]

/-- The subgroup fixing a compositum is the intersection of the subgroups fixing the fields. -/
lemma mem_fixingSubgroup_biSup_iff {F E : Type*} [Field F] [Field E] [Algebra F E]
    (P : IntermediateField F E → Prop) (σ : Gal(E/F)) :
    σ ∈ (⨆ (L : IntermediateField F E) (_ : P L), L).fixingSubgroup ↔
      ∀ L, P L → σ ∈ L.fixingSubgroup := by
  simp_rw [← Subgroup.zpowers_le, ← IntermediateField.le_iff_le]
  exact iSup₂_le_iff

variable [IsNoetherianRing R]

/-- V.8.2 (second assertion): for a noetherian normal domain `R` with fraction field `K` and a
separably closed extension `Ω` of `K`, the kernel of `π₁(Spec K) → π₁(Spec R)`, where
`π₁(Spec K)` is identified with the Galois group of the separable closure `K̄` of `K` in `Ω`
(V.8.1), is the subgroup fixing the compositum of the finite subextensions of `K̄/K` unramified
over `R`. -/
theorem ker_genericPointMap_comp_eq :
    ((genericPointMap R K Ω).comp
        (fundamentalGroupContinuousMulEquivGal K Ω).symm.toMonoidHom).ker =
      (⨆ (L : IntermediateField K Ksep)
        (_ : FiniteDimensional K L ∧ SGA.SGA1.ExposeI.IsUnramifiedOver R L), L).fixingSubgroup := by
  ext σ
  rw [mem_fixingSubgroup_biSup_iff, MonoidHom.mem_ker]
  change genericPointMap R K Ω ((fundamentalGroupContinuousMulEquivGal K Ω).symm σ) = 1 ↔ _
  rw [genericPointMap_symm_eq_one_iff]
  constructor
  · rintro hQ L ⟨hfd, hur⟩
    obtain ⟨A, y, hy⟩ := exists_algHom_of_unramified R Ω L hur
    exact hy σ fun a ↦ hQ A y (1 ⊗ₜ a)
  · intro h A y
    obtain ⟨L, hP, hmem⟩ := exists_unramified_of_algHom R Ω A y
    have hσ := (IntermediateField.mem_fixingSubgroup_iff _ _).mp (h L hP)
    let ys : K ⊗[R] A →ₐ[K] Ksep :=
      y.codRestrict (separableClosure K Ω).toSubalgebra (algHom_apply_mem_separableClosure K Ω y)
    have key (z : K ⊗[R] A) : σ (ys z) = ys z := by
      induction z using TensorProduct.induction_on with
      | zero => rw [map_zero, map_zero]
      | tmul k a =>
        have hk : k ⊗ₜ[R] a = algebraMap K (K ⊗[R] A) k * (1 ⊗ₜ a) := by
          rw [Algebra.TensorProduct.algebraMap_apply, Algebra.TensorProduct.tmul_mul_tmul,
            mul_one, one_mul]
          rfl
        have e : ys (k ⊗ₜ a) = algebraMap K Ksep k * ys (1 ⊗ₜ a) := by
          rw [hk, map_mul, AlgHom.commutes]
        rw [e, map_mul, AlgEquiv.commutes]
        congr 1
        exact hσ _ (hmem a)
      | add z w hz hw => rw [map_add, map_add, hz, hw]
    exact key

/-- V.8.2 (second assertion), as the statement `genericPointMapKernelStatement`. -/
theorem genericPointMapKernelStatement_holds : genericPointMapKernelStatement.{u} :=
  fun R _ _ _ _ Ω _ _ _ _ _ ↦ ker_genericPointMap_comp_eq R Ω

end Unramified

end SGA.SGA1.ExposeV
