/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.SGA1.ExposeV.FiniteEtaleAlgebra
import SGA.SGA1.ExposeV.FiniteQuotientBaseChange

/-!
# SGA 1, Exposé V, V.3.4 over an arbitrary affine base

Let `A` be a finite étale algebra over an arbitrary ring `R` and `G` a finite group acting on `A`
by `R`-algebra automorphisms. Then `A^G` is finite étale over `R`
(`finite_etale_fixedPoints_of_finite_etale`); this is V.3.4 for `Y = Spec R`, without SGA's
noetherian hypothesis and without assuming `Spec R` connected (the connected case is
`finite_etale_fixedPoints`).

* Split case (`finite_etale_iInf_equalizer`): for finitely many `T`-algebra endomorphisms `ψ_j`
  of `ι → T`, the coefficients `ψ_j(e_i)_k` are idempotents, and the products
  `ε_σ = ∏ ψ_j(e_{σ j k})_k` form a complete family of orthogonal idempotents of `T` over which
  each `ψ_j` is precomposition with `σ j`. The joint fixed points are then the image of an
  explicit map from a split algebra, with kernel generated by an idempotent.
* Constant rank: `A` is split by a faithfully flat finite étale algebra (Lenstra, mathlib), and
  invariants commute with flat base change (`fixedBaseChangeEquiv`).
* General case: the rank of `A` is locally constant, and finite étale is local on `Spec R`.
-/

universe u

open TensorProduct

namespace SGA.SGA1.ExposeV

section SplitFixed

variable {T : Type*} [CommRing T] {ι J : Type*} [DecidableEq ι] (ψ : J → ((ι → T) →ₐ[T] (ι → T)))

/-- The coefficient `ψ_j(e_i)_k` of an endomorphism of the split algebra `ι → T`. -/
def splitCoeff (j : J) (i k : ι) : T := ψ j (Pi.single i 1) k

lemma isIdempotentElem_splitCoeff (j : J) (i k : ι) : IsIdempotentElem (splitCoeff ψ j i k) := by
  have : IsIdempotentElem (Pi.single i 1 : ι → T) := by
    simp [IsIdempotentElem, ← Pi.single_mul]
  exact congr_fun (this.map (ψ j)) k

lemma splitCoeff_mul_splitCoeff {j : J} {i i' : ι} (h : i ≠ i') (k : ι) :
    splitCoeff ψ j i k * splitCoeff ψ j i' k = 0 := by
  have : (Pi.single i 1 : ι → T) * Pi.single i' 1 = 0 := by
    ext a
    by_cases ha : a = i
    · subst ha; simp [h]
    · simp [ha]
  have := congr_fun (congr_arg (ψ j) this) k
  rwa [map_mul, map_zero] at this

variable [Fintype ι]

lemma sum_splitCoeff (j : J) (k : ι) : ∑ i, splitCoeff ψ j i k = 1 := by
  have := congr_fun (map_one (ψ j)) k
  rw [← Finset.univ_sum_single (1 : ι → T)] at this
  simpa [splitCoeff, map_sum] using this

lemma apply_eq_sum_splitCoeff (j : J) (f : ι → T) (k : ι) :
    ψ j f k = ∑ i, f i * splitCoeff ψ j i k := by
  conv_lhs => rw [← Finset.univ_sum_single f]
  have : ∀ i, (Pi.single i (f i) : ι → T) = f i • Pi.single i 1 := fun i ↦ by
    rw [← Pi.single_smul, smul_eq_mul, mul_one]
  simp only [this, map_sum, map_smul, Finset.sum_apply, Pi.smul_apply, smul_eq_mul, splitCoeff]

variable [Fintype J] [DecidableEq J]

/-- The idempotent of the locus where every `ψ j` is precomposition with `σ j`. -/
def splitIdem (σ : J → ι → ι) : T := ∏ j, ∏ k, splitCoeff ψ j (σ j k) k

omit [DecidableEq J] in
lemma isIdempotentElem_splitIdem (σ : J → ι → ι) : IsIdempotentElem (splitIdem ψ σ) :=
  Finset.prod_induction _ _ (fun _ _ ha hb ↦ ha.mul hb) .one fun j _ ↦
    Finset.prod_induction _ _ (fun _ _ ha hb ↦ ha.mul hb) .one fun k _ ↦
      isIdempotentElem_splitCoeff ψ j _ k

omit [DecidableEq J] in
lemma splitIdem_mul_splitCoeff (σ : J → ι → ι) (j : J) (i k : ι) :
    splitIdem ψ σ * splitCoeff ψ j i k = if σ j k = i then splitIdem ψ σ else 0 := by
  classical
  have hfac : splitIdem ψ σ = splitCoeff ψ j (σ j k) k * splitIdem ψ σ := by
    unfold splitIdem
    rw [← Finset.mul_prod_erase _ _ (Finset.mem_univ j),
      ← Finset.mul_prod_erase _ _ (Finset.mem_univ k)]
    rw [← mul_assoc, ← mul_assoc, (isIdempotentElem_splitCoeff ψ j _ k).eq]
  split_ifs with h
  · rw [← h, hfac, mul_assoc, mul_comm _ (splitCoeff ψ j (σ j k) k), ← mul_assoc,
      (isIdempotentElem_splitCoeff ψ j _ k).eq, ← hfac]
  · rw [hfac, mul_right_comm, splitCoeff_mul_splitCoeff ψ h, zero_mul]

omit [DecidableEq J] in
lemma splitIdem_mul_apply (σ : J → ι → ι) (j : J) (f : ι → T) (k : ι) :
    splitIdem ψ σ * ψ j f k = splitIdem ψ σ * f (σ j k) := by
  classical
  rw [apply_eq_sum_splitCoeff, Finset.mul_sum]
  simp_rw [mul_left_comm (splitIdem ψ σ), splitIdem_mul_splitCoeff]
  simp [mul_comm]

omit [DecidableEq J] in
lemma splitIdem_mul_splitIdem {σ σ' : J → ι → ι} (h : σ ≠ σ') :
    splitIdem ψ σ * splitIdem ψ σ' = 0 := by
  classical
  obtain ⟨j, k, hjk⟩ : ∃ j k, σ j k ≠ σ' j k := by
    by_contra! H
    exact h (funext fun j ↦ funext fun k ↦ H j k)
  have hfac : splitIdem ψ σ' = splitCoeff ψ j (σ' j k) k * splitIdem ψ σ' := by
    unfold splitIdem
    rw [← Finset.mul_prod_erase _ _ (Finset.mem_univ j),
      ← Finset.mul_prod_erase _ _ (Finset.mem_univ k)]
    rw [← mul_assoc, ← mul_assoc, (isIdempotentElem_splitCoeff ψ j _ k).eq]
  rw [hfac, ← mul_assoc, splitIdem_mul_splitCoeff]
  simp [hjk]

lemma sum_splitIdem : ∑ σ : J → ι → ι, splitIdem ψ σ = 1 := by
  have h1 : ∏ j, ∏ k, ∑ i, splitCoeff ψ j i k = 1 := by
    simp [sum_splitCoeff]
  rw [← h1]
  simp_rw [Finset.prod_univ_sum, Fintype.piFinset_univ]
  rfl

/-- The relation `a ~ σ j a` on `ι`; on the locus of `splitIdem ψ σ`, the joint fixed points of
the `ψ j` are the functions constant on its classes. -/
def splitRel (σ : J → ι → ι) (a b : ι) : Prop := ∃ j, σ j a = b

/-- The index set of the split algebra `(Σ σ, ι/σ) → T` mapping onto the fixed points. -/
abbrev SplitIndex (ι J : Type*) : Type _ := Σ σ : J → ι → ι, Quot (splitRel σ)

omit [DecidableEq J] in
lemma splitIdem_mul_eq_of_eqvGen {σ : J → ι → ι} {f : ι → T}
    (hf : ∀ j a, splitIdem ψ σ * f (σ j a) = splitIdem ψ σ * f a) {a b : ι}
    (h : Relation.EqvGen (splitRel σ) a b) : splitIdem ψ σ * f a = splitIdem ψ σ * f b := by
  induction h with
  | rel a b hab => obtain ⟨j, rfl⟩ := hab; exact (hf j a).symm
  | refl => rfl
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ih₁ ih₂ => exact ih₁.trans ih₂

/-- The map `(Σ σ, ι/σ → T) → (ι → T)`, `h ↦ (a ↦ ∑ σ, ε_σ h(σ, [a]))`, whose image is the
algebra of joint fixed points of the `ψ j`. -/
noncomputable def splitFixedMap : (SplitIndex ι J → T) →ₐ[T] (ι → T) where
  toFun h a := ∑ σ, splitIdem ψ σ * h ⟨σ, Quot.mk _ a⟩
  map_one' := by
    funext a
    simp [sum_splitIdem]
  map_mul' h h' := by
    funext a
    simp only [Pi.mul_apply]
    rw [Finset.sum_mul_sum]
    refine Finset.sum_congr rfl fun σ _ ↦ ?_
    rw [Finset.sum_eq_single σ]
    · rw [mul_mul_mul_comm, (isIdempotentElem_splitIdem ψ σ).eq]
    · intro σ' _ hσ'
      rw [mul_mul_mul_comm, splitIdem_mul_splitIdem ψ (Ne.symm hσ'), zero_mul]
    · simp
  map_zero' := by funext a; simp
  map_add' h h' := by funext a; simp [mul_add, Finset.sum_add_distrib]
  commutes' t := by
    funext a
    simp [← Finset.sum_mul, sum_splitIdem]

lemma splitFixedMap_apply (h : SplitIndex ι J → T) (a : ι) :
    splitFixedMap ψ h a = ∑ σ, splitIdem ψ σ * h ⟨σ, Quot.mk _ a⟩ := rfl

lemma splitIdem_mul_splitFixedMap (σ : J → ι → ι) (h : SplitIndex ι J → T) (a : ι) :
    splitIdem ψ σ * splitFixedMap ψ h a = splitIdem ψ σ * h ⟨σ, Quot.mk _ a⟩ := by
  rw [splitFixedMap_apply, Finset.mul_sum, Finset.sum_eq_single σ]
  · rw [← mul_assoc, (isIdempotentElem_splitIdem ψ σ).eq]
  · intro σ' _ hσ'
    rw [← mul_assoc, splitIdem_mul_splitIdem ψ (Ne.symm hσ'), zero_mul]
  · simp

omit [DecidableEq J] in
lemma eq_of_forall_splitIdem_mul_eq {f f' : ι → T}
    (h : ∀ σ a, splitIdem ψ σ * f a = splitIdem ψ σ * f' a) : f = f' := by
  classical
  funext a
  rw [← one_mul (f a), ← one_mul (f' a), ← sum_splitIdem ψ, Finset.sum_mul, Finset.sum_mul]
  exact Finset.sum_congr rfl fun σ _ ↦ h σ a

/-- The joint fixed points of the `ψ j` are the image of `splitFixedMap`. -/
lemma range_splitFixedMap :
    (splitFixedMap ψ).range = ⨅ j, AlgHom.equalizer (ψ j) (AlgHom.id T _) := by
  ext f
  simp only [AlgHom.mem_range, Algebra.mem_iInf, AlgHom.mem_equalizer, AlgHom.coe_id, id_eq]
  constructor
  · rintro ⟨h, rfl⟩ j
    refine eq_of_forall_splitIdem_mul_eq ψ fun σ k ↦ ?_
    rw [splitIdem_mul_apply, splitIdem_mul_splitFixedMap, splitIdem_mul_splitFixedMap]
    congr 3
    exact (Quot.sound ⟨j, rfl⟩).symm
  · intro hf
    have hf' : ∀ σ j a, splitIdem ψ σ * f (σ j a) = splitIdem ψ σ * f a := fun σ j a ↦ by
      rw [← splitIdem_mul_apply, hf j]
    refine ⟨fun x ↦ f (Quot.out x.2), eq_of_forall_splitIdem_mul_eq ψ fun σ a ↦ ?_⟩
    rw [splitIdem_mul_splitFixedMap]
    exact splitIdem_mul_eq_of_eqvGen ψ (hf' σ) (Quot.eqvGen_exact (Quot.out_eq _))

/-- The idempotent `(σ, c) ↦ 1 - ε_σ` generating the kernel of `splitFixedMap`. -/
noncomputable def splitKerIdem : SplitIndex ι J → T := fun x ↦ 1 - splitIdem ψ x.1

omit [DecidableEq J] in
lemma isIdempotentElem_splitKerIdem : IsIdempotentElem (splitKerIdem ψ) := by
  funext x
  exact (isIdempotentElem_splitIdem ψ x.1).one_sub

lemma ker_splitFixedMap : RingHom.ker (splitFixedMap ψ) = Ideal.span {splitKerIdem ψ} := by
  ext h
  rw [RingHom.mem_ker, Ideal.mem_span_singleton']
  constructor
  · intro hh
    refine ⟨h, funext fun ⟨σ, c⟩ ↦ ?_⟩
    obtain ⟨a, rfl⟩ := Quot.exists_rep c
    have h3 : splitIdem ψ σ * h ⟨σ, Quot.mk _ a⟩ = 0 := by
      rw [← splitIdem_mul_splitFixedMap]
      have := congr_fun hh a
      rw [this, Pi.zero_apply, mul_zero]
    change h ⟨σ, _⟩ * (1 - splitIdem ψ σ) = h ⟨σ, _⟩
    rw [mul_sub, mul_one, mul_comm, h3, sub_zero]
  · rintro ⟨x, rfl⟩
    refine eq_of_forall_splitIdem_mul_eq ψ fun σ a ↦ ?_
    change splitIdem ψ σ * splitFixedMap ψ (x * splitKerIdem ψ) a = splitIdem ψ σ * 0
    rw [splitIdem_mul_splitFixedMap, mul_zero]
    change splitIdem ψ σ * (x _ * (1 - splitIdem ψ σ)) = 0
    rw [mul_sub, mul_one, mul_sub, ← mul_assoc, mul_comm (splitIdem ψ σ) (x _), mul_assoc,
      (isIdempotentElem_splitIdem ψ σ).eq, sub_self]

end SplitFixed

/-- The joint fixed points of finitely many `T`-algebra endomorphisms `ψ j` of a split algebra
`ι → T` (`T` any ring) form a finite étale `T`-algebra. -/
theorem finite_etale_iInf_equalizer {T : Type*} [CommRing T] {ι J : Type*} [Finite ι] [Finite J]
    (ψ : J → ((ι → T) →ₐ[T] (ι → T))) :
    Module.Finite T (⨅ j, AlgHom.equalizer (ψ j) (AlgHom.id T _) : Subalgebra T (ι → T)) ∧
      Algebra.Etale T (⨅ j, AlgHom.equalizer (ψ j) (AlgHom.id T _) : Subalgebra T (ι → T)) := by
  classical
  have := Fintype.ofFinite ι
  have := Fintype.ofFinite J
  have hE := isIdempotentElem_splitKerIdem ψ
  have hker : RingHom.ker (splitFixedMap ψ) = Ideal.span {1 - (1 - splitKerIdem ψ)} := by
    rw [ker_splitFixedMap, sub_sub_cancel]
  obtain ⟨h₁, h₂⟩ := finite_etale_quotient_one_sub (R := T) (T := SplitIndex ι J → T) hE.one_sub
  let e : ((SplitIndex ι J → T) ⧸ Ideal.span {1 - (1 - splitKerIdem ψ)}) ≃ₐ[T]
      (⨅ j, AlgHom.equalizer (ψ j) (AlgHom.id T _) : Subalgebra T (ι → T)) :=
    (Ideal.quotientEquivAlgOfEq T hker.symm).trans
      ((Ideal.quotientKerEquivRange (splitFixedMap ψ)).trans
        (Subalgebra.equivOfEq _ _ (range_splitFixedMap ψ)))
  exact ⟨Module.Finite.equiv e.toLinearEquiv, .of_equiv e⟩

section FixedPoints

variable {R A : Type*} [CommRing R] [CommRing A] [Algebra R A] (G : Type*) [Group G] [Finite G]
  [MulSemiringAction G A] [SMulCommClass G R A]

/-- If `A` becomes split after a faithfully flat change of base `R → T`, the invariants `A^G`
are finite étale over `R`: over `T` they are the joint fixed points of finitely many
endomorphisms of a split algebra (`finite_etale_iInf_equalizer`), and invariants commute with
flat base change. -/
theorem finite_etale_fixedPoints_of_isFiniteSplit (T : Type*) [CommRing T] [Algebra R T]
    [Module.FaithfullyFlat R T] [Algebra.IsFiniteSplit T (T ⊗[R] A)] :
    Module.Finite R (FixedPoints.subalgebra R A G) ∧
      Algebra.Etale R (FixedPoints.subalgebra R A G) := by
  classical
  have : Fintype G := Fintype.ofFinite G
  obtain ⟨n, ⟨e⟩⟩ := Algebra.IsFiniteSplit.nonempty_algEquiv_fun T (T ⊗[R] A)
  let ψ : G → ((Fin n → T) →ₐ[T] (Fin n → T)) := fun g ↦
    (e.toAlgHom.comp (baseChangeSMul R A G T g)).comp e.symm.toAlgHom
  obtain ⟨h₁, h₂⟩ := finite_etale_iInf_equalizer ψ
  let Φ := fixedBaseChangeMap R A G T
  have hrange : Φ.range.map e.toAlgHom = ⨅ g, AlgHom.equalizer (ψ g) (AlgHom.id T _) := by
    ext y
    simp only [Subalgebra.mem_map, Algebra.mem_iInf, AlgHom.mem_equalizer, AlgHom.coe_id, id_eq]
    constructor
    · rintro ⟨x, hx, rfl⟩ g
      rw [mem_range_fixedBaseChangeMap] at hx
      simp [ψ, hx g]
    · intro h
      refine ⟨e.symm y, (mem_range_fixedBaseChangeMap R A G T _).mpr fun g ↦ ?_, by simp⟩
      apply e.injective
      simpa [ψ] using h g
  let EE : T ⊗[R] FixedPoints.subalgebra R A G ≃ₐ[T]
      (⨅ g, AlgHom.equalizer (ψ g) (AlgHom.id T _) : Subalgebra T (Fin n → T)) :=
    (AlgEquiv.ofInjective Φ (fixedBaseChangeMap_injective R A G T)).trans <|
      (Subalgebra.equivMapOfInjective _ e.toAlgHom e.injective).trans
        (Subalgebra.equivOfEq _ _ hrange)
  have : Module.Finite T (T ⊗[R] FixedPoints.subalgebra R A G) :=
    Module.Finite.equiv EE.symm.toLinearEquiv
  have : Algebra.Etale T (T ⊗[R] FixedPoints.subalgebra R A G) := .of_equiv EE.symm
  exact ⟨.of_finite_tensorProduct_of_faithfullyFlat T,
    .of_etale_tensorProduct_of_faithfullyFlat T⟩

/-- V.3.4 for a finite étale algebra of constant rank over an arbitrary ring. -/
theorem finite_etale_fixedPoints_of_rankAtStalk_eq {R A : Type u} [CommRing R] [CommRing A]
    [Algebra R A] [Module.Finite R A] [Algebra.Etale R A] [MulSemiringAction G A]
    [SMulCommClass G R A] {n : ℕ} (hn : Module.rankAtStalk (R := R) A = n) :
    Module.Finite R (FixedPoints.subalgebra R A G) ∧
      Algebra.Etale R (FixedPoints.subalgebra R A G) := by
  obtain ⟨T, _, _, _, _, _, _⟩ := Algebra.IsFiniteSplit.exists_tensorProduct_of_etale hn
  exact finite_etale_fixedPoints_of_isFiniteSplit G T

/-- The invariants of `R' ⊗ A` under the action through `A` are `R' ⊗ A^G` when `R'` is flat. -/
noncomputable def fixedBaseChangeEquiv {R A : Type*} [CommRing R] [CommRing A] [Algebra R A]
    [MulSemiringAction G A] [SMulCommClass G R A] (R' : Type*) [CommRing R'] [Algebra R R']
    [Module.Flat R R'] :
    letI := tensorAction (B := R) (A := A) R' G
    letI := tensorAction_smulCommClass (B := R) (A := A) R' G
    R' ⊗[R] FixedPoints.subalgebra R A G ≃ₐ[R'] FixedPoints.subalgebra R' (R' ⊗[R] A) G :=
  letI := tensorAction (B := R) (A := A) R' G
  letI := tensorAction_smulCommClass (B := R) (A := A) R' G
  (AlgEquiv.ofInjective _ (fixedBaseChangeMap_injective R A G R')).trans
    (Subalgebra.equivOfEq _ _ (by
      ext x
      rw [mem_range_fixedBaseChangeMap]
      rfl))

/-- V.3.4 over an affine base: if `A` is a finite étale `R`-algebra (`R` arbitrary) and `G` a
finite group acting by `R`-algebra automorphisms, then `A^G` is finite étale over `R`. The rank
of `A` is locally constant; on a basic open where it is constant, `A` is split by a faithfully
flat finite étale algebra (Lenstra), and the invariants are computed there
(`finite_etale_fixedPoints_of_isFiniteSplit`). -/
theorem finite_etale_fixedPoints_of_finite_etale {R A : Type u} [CommRing R] [CommRing A]
    [Algebra R A] [Module.Finite R A] [Algebra.Etale R A] [MulSemiringAction G A]
    [SMulCommClass G R A] :
    Module.Finite R (FixedPoints.subalgebra R A G) ∧
      Algebra.Etale R (FixedPoints.subalgebra R A G) := by
  let B := FixedPoints.subalgebra R A G
  suffices (algebraMap R B).Finite ∧ (algebraMap R B).Etale by
    exact ⟨RingHom.finite_algebraMap.mp this.1, RingHom.etale_algebraMap.mp this.2⟩
  have hP : RingHom.RespectsIso fun {R S : Type u} [CommRing R] [CommRing S] (f : R →+* S) ↦
      f.Finite ∧ f.Etale :=
    ⟨fun f e h ↦ ⟨RingHom.finite_respectsIso.1 f e h.1, RingHom.Etale.respectsIso.1 f e h.2⟩,
      fun f e h ↦ ⟨RingHom.finite_respectsIso.2 f e h.1, RingHom.Etale.respectsIso.2 f e h.2⟩⟩
  have : Module.FinitePresentation R A := finitePresentation_of_finite_etale
  let s : Set R := {r | ∃ n : ℕ, ∀ p ∈ PrimeSpectrum.basicOpen r,
    Module.rankAtStalk (R := R) A p = n}
  have hs : Ideal.span s = ⊤ := by
    by_contra h
    obtain ⟨m, hm, hle⟩ := Ideal.exists_le_maximal _ h
    let p : PrimeSpectrum R := ⟨m, hm.isPrime⟩
    have hopen : IsOpen {q : PrimeSpectrum R | Module.rankAtStalk (R := R) A q =
        Module.rankAtStalk (R := R) A p} :=
      Module.isLocallyConstant_rankAtStalk.isOpen_fiber _
    obtain ⟨_, ⟨r, rfl⟩, hpr, hrU⟩ :=
      PrimeSpectrum.isTopologicalBasis_basic_opens.exists_subset_of_mem_open
        (show p ∈ {q : PrimeSpectrum R | Module.rankAtStalk (R := R) A q =
          Module.rankAtStalk (R := R) A p} from rfl) hopen
    exact hpr (hle (Ideal.subset_span ⟨_, fun q hq ↦ hrU hq⟩))
  refine (RingHom.finite_ofLocalizationSpan.and RingHom.Etale.ofLocalizationSpan).ofIsLocalization
    hP _ s hs fun ⟨r, n, hn⟩ ↦ ?_
  let Rᵣ := Localization.Away r
  refine ⟨Rᵣ, B ⊗[R] Rᵣ, inferInstance, inferInstance, inferInstance, inferInstance,
    inferInstance, IsLocalization.Away.tensor r Rᵣ,
    (Algebra.TensorProduct.includeRight : Rᵣ →ₐ[R] B ⊗[R] Rᵣ).toRingHom, ?_, ?_⟩
  · ext x
    simp [IsScalarTower.algebraMap_apply R B (B ⊗[R] Rᵣ)]
  -- the rank of `Rᵣ ⊗ A` is constant
  let _ := tensorAction (B := R) (A := A) Rᵣ G
  have := tensorAction_smulCommClass (B := R) (A := A) Rᵣ G
  have hn' : Module.rankAtStalk (R := Rᵣ) (Rᵣ ⊗[R] A) = n := by
    ext q
    rw [Module.rankAtStalk_baseChange]
    apply hn
    have hq : PrimeSpectrum.comap (algebraMap R Rᵣ) q ∈
        Set.range (PrimeSpectrum.comap (algebraMap R Rᵣ)) := ⟨q, rfl⟩
    rwa [PrimeSpectrum.localization_away_comap_range Rᵣ r] at hq
  obtain ⟨h₁, h₂⟩ := finite_etale_fixedPoints_of_rankAtStalk_eq G hn'
  let e := fixedBaseChangeEquiv G (R := R) (A := A) Rᵣ
  have : Module.Finite Rᵣ (Rᵣ ⊗[R] B) := Module.Finite.equiv e.symm.toLinearEquiv
  have : Algebra.Etale Rᵣ (Rᵣ ⊗[R] B) := .of_equiv e.symm
  have hc : (Algebra.TensorProduct.includeRight : Rᵣ →ₐ[R] B ⊗[R] Rᵣ).toRingHom =
      (Algebra.TensorProduct.comm R Rᵣ B).toRingEquiv.toRingHom.comp
        (algebraMap Rᵣ (Rᵣ ⊗[R] B)) := by
    ext x
    simp
  rw [hc]
  exact hP.1 _ _ ⟨RingHom.finite_algebraMap.mpr inferInstance,
    RingHom.etale_algebraMap.mpr inferInstance⟩

end FixedPoints

end SGA.SGA1.ExposeV
