/-
Copyright (c) 2026 SGAenglishpluslean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SGAenglishpluslean contributors
-/
import SGA.SGA1.ExposeV.QuotientEtale

/-!
# SGA 1, Exposé V, V.1.3 (iii): the residue extensions of a quotient are normal

For `p : X ⟶ Y` as in V.1.3 (`G` finite acting on the right, `p` affine and invariant with
`𝒪_Y = p_*(𝒪_X)^G`), with `X` not necessarily affine, the residue extension `κ(x)/κ(p x)` is
normal (quasi-Galois) (`normal_residueFieldMap`). The affine case is mathlib's
`Ideal.IsFractionRing.normal` (`normal_residueField`); the surjectivity of
`G_d(x) → Aut(κ(x)/κ(y))` is `exists_fromSpecResidueField_comp_eq`.

Along the way: the residue extensions of an integral morphism are integral
(`isIntegral_residueFieldMap`).
-/

universe u

open CategoryTheory Limits AlgebraicGeometry Opposite

namespace SGA.SGA1.ExposeV

section Normal

variable {X Y : Scheme.{u}}

set_option backward.isDefEq.respectTransparency false in
/-- For an integral morphism `f`, the residue extensions `κ(x)/κ(f x)` are integral (hence
algebraic): `κ(x)` is generated by the values at `x` of sections over `f⁻¹ U`, `U` affine, which
are integral over `Γ(Y, U)`. -/
theorem isIntegral_residueFieldMap (f : X ⟶ Y) [IsIntegralHom f] (x : X) :
    letI := (f.residueFieldMap x).hom.toAlgebra
    Algebra.IsIntegral (Y.residueField (f x)) (X.residueField x) := by
  let := (f.residueFieldMap x).hom.toAlgebra
  obtain ⟨U, hU, hxU⟩ := exists_isAffineOpen_mem (f x)
  have hV : IsAffineOpen (f ⁻¹ᵁ U) := hU.preimage f
  have hx : x ∈ f ⁻¹ᵁ U := hxU
  let := X.presheaf.algebra_section_stalk ⟨x, hx⟩
  have := hV.isLocalization_stalk ⟨x, hx⟩
  let := (f.app U).hom.toAlgebra
  have hr : ∀ a : Γ(X, f ⁻¹ᵁ U), _root_.IsIntegral (Y.residueField (f x))
      (X.residue x (algebraMap Γ(X, f ⁻¹ᵁ U) (X.presheaf.stalk x) a)) := by
    intro a
    refine _root_.IsIntegral.map_of_comp_eq (Y.evaluation U (f x) hxU).hom
      ((X.residue x).hom.comp
        (algebraMap Γ(X, f ⁻¹ᵁ U) (X.presheaf.stalk x))) ?_ (f.isIntegral_app U hU a)
    ext b
    exact Scheme.evaluation_naturality_apply f x hxU b
  refine ⟨fun l ↦ ?_⟩
  obtain ⟨t, rfl⟩ := X.residue_surjective x l
  obtain ⟨⟨a, s⟩, rfl⟩ := IsLocalization.mk'_surjective
    (hV.primeIdealOf ⟨x, hx⟩).asIdeal.primeCompl t
  have hs : X.residue x (algebraMap Γ(X, f ⁻¹ᵁ U) (X.presheaf.stalk x) s) ≠ 0 :=
    ((IsLocalization.map_units (X.presheaf.stalk x) s).map (X.residue x).hom).ne_zero
  have he : X.residue x (IsLocalization.mk' (X.presheaf.stalk x) a s) =
      X.residue x (algebraMap _ (X.presheaf.stalk x) a) *
        (X.residue x (algebraMap _ (X.presheaf.stalk x) (s : Γ(X, f ⁻¹ᵁ U))))⁻¹ := by
    rw [eq_mul_inv_iff_mul_eq₀ hs, ← map_mul, IsLocalization.mk'_spec]
  rw [he]
  exact (hr a).mul (hr s).inv

/-- A field extension `L/K` is normal as soon as every `K`-embedding of `L` into an algebraic
closure `Ω` of `L` has the same image as the canonical one. -/
lemma normal_of_forall_algHom_mem_range {K L : Type u} [Field K] [Field L] [Algebra K L]
    [Algebra.IsAlgebraic K L]
    (h : ∀ τ : L →ₐ[K] AlgebraicClosure L, ∀ l, ∃ l', τ l = algebraMap L _ l') : Normal K L := by
  let ι := IsScalarTower.toAlgHom K L (AlgebraicClosure L)
  have : Normal K ι.fieldRange := by
    refine IntermediateField.normal_iff_forall_fieldRange_le.mpr fun σ ↦ ?_
    rintro _ ⟨z, rfl⟩
    obtain ⟨l, hl⟩ := ι.equivFieldRange.surjective z
    obtain ⟨l', hl'⟩ := h (σ.comp ι.equivFieldRange.toAlgHom) l
    refine ⟨l', ?_⟩
    rw [← hl]
    exact hl'.symm
  exact Normal.of_algEquiv ι.equivFieldRange.symm

variable {G : Type*} [Group G] {T : G → (X ⟶ X)} (hT : IsRightAction T) {p : X ⟶ Y}
  (hTp : ∀ g, T g ≫ p = p)

set_option backward.isDefEq.respectTransparency false in
include hT in
/-- V.1.3 (iii), first half, for any `p` as in V.1.3 (`X` not necessarily affine): the residue
extension `κ(x)/κ(p x)` is normal (quasi-Galois). It is algebraic since `p` is integral, and every
`κ(p x)`-embedding `τ` of `κ(x)` into an algebraic closure `Ω` of `κ(x)` differs from the
canonical one by an automorphism of `κ(x)` induced by some `g ∈ G_d(x)`: the two points
`Spec Ω ⟶ X` have the same image in `Y`, hence are conjugate (`exists_comp_eq_of_comp_eq`). -/
theorem normal_residueFieldMap [IsAffineHom p] [Finite G]
    (hsec : ∀ U, SectionsAreInvariant T p hTp U) (x : X) :
    letI := (p.residueFieldMap x).hom.toAlgebra
    Normal (Y.residueField (p x)) (X.residueField x) := by
  let := (p.residueFieldMap x).hom.toAlgebra
  have : IsIntegralHom p := isIntegralHom_of_sectionsAreInvariant hT fun U _ ↦ hsec U
  have : Algebra.IsIntegral (Y.residueField (p x)) (X.residueField x) :=
    isIntegral_residueFieldMap p x
  refine normal_of_forall_algHom_mem_range fun τ l ↦ ?_
  let Ω := AlgebraicClosure (X.residueField x)
  let ιh : X.residueField x ⟶ CommRingCat.of Ω :=
    CommRingCat.ofHom (algebraMap (X.residueField x : Type u) Ω)
  let τh : X.residueField x ⟶ CommRingCat.of Ω := CommRingCat.ofHom τ.toRingHom
  let a : Spec (.of Ω) ⟶ X := Spec.map ιh ≫ X.fromSpecResidueField x
  let b : Spec (.of Ω) ⟶ X := Spec.map τh ≫ X.fromSpecResidueField x
  have hφ : p.residueFieldMap x ≫ ιh = p.residueFieldMap x ≫ τh := by
    ext k
    change algebraMap (X.residueField x : Type u) Ω (algebraMap (Y.residueField (p x)) _ k) =
      τ (algebraMap (Y.residueField (p x)) _ k)
    rw [τ.commutes, ← IsScalarTower.algebraMap_apply]
  have hab : a ≫ p = b ≫ p := by
    simp only [a, b, Category.assoc, ← Scheme.Hom.SpecMap_residueFieldMap_fromSpecResidueField,
      ← Spec.map_comp_assoc, hφ]
  obtain ⟨g, hg⟩ := exists_comp_eq_of_comp_eq hT hTp hsec a b hab
  have hx : T g x = x := by
    have := congr($(hg) (IsLocalRing.closedPoint Ω))
    simpa [a, b] using this
  let σ₀ : X.residueField x ⟶ X.residueField x :=
    (X.residueFieldCongr hx.symm).hom ≫ (T g).residueFieldMap x
  have hσ₀ : X.fromSpecResidueField x ≫ T g = Spec.map σ₀ ≫ X.fromSpecResidueField x := by
    rw [Spec.map_comp, Category.assoc, Scheme.residueFieldCongr_fromSpecResidueField hx.symm,
      Scheme.Hom.SpecMap_residueFieldMap_fromSpecResidueField]
  have hτ : σ₀ ≫ ιh = τh := by
    have e : Spec.map (σ₀ ≫ ιh) ≫ X.fromSpecResidueField x =
        Spec.map τh ≫ X.fromSpecResidueField x := by
      rw [Spec.map_comp, Category.assoc, ← hσ₀]
      exact hg
    exact Spec.map_injective ((cancel_mono _).mp e)
  exact ⟨σ₀ l, congr($(hτ).hom l).symm⟩

end Normal

end SGA.SGA1.ExposeV
