/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import Mathlib.Algebra.Group.MinimalAxioms
import SGA.Foundations.Fields.GeometricallyConnected
import SGA.SGA1.ExposeX.ProperOverField
import SGA.SGA1.ExposeXI.AbelianVarietyMulN
import SGA.SGA1.ExposeXI.ProjectiveSpace
import SGA.SGA1.ExposeXI.TateModule

/-!
# SGA 1, Exposé XI.2: a pointed connected étale covering of an abelian variety is one

XI.2, before XI.2.1: "every principal covering of `A` with commutative structure group `G`,
pointed over the origin of `A`, is endowed in a unique way with a structure of algebraic group
admitting the marked point as origin, and such that `A' → A` is a homomorphism of algebraic
groups. In particular, if `A'` is connected, it is also an abelian variety, isogenous to `A`."

We prove the connected case (`existsUnique_grpObj_coveringOver`): for an abelian variety `A`
over an algebraically closed field `k`, a connected étale covering `p : A' ⟶ A` and a `k`-point
`0'` of `A'` over the origin, there is a unique group-scheme structure on `A'` with origin `0'`
for which `p` is a homomorphism. `A'` is then an abelian variety (proper, smooth, connected,
hence commutative), and `p` is an isogeny: finite and surjective
(`isFinite_coveringHom`, `surjective_coveringHom`). (A connected étale covering of `A` is
principal with commutative group, `π₁(A)` being commutative; the disconnected principal
coverings, i.e. SGA's `Ext(A, G) ≅ H¹(A, G)`, are not treated.)

The proof follows SGA's argument through the lifting criterion, without Serre's theorem on
extensions:

* the multiplication `A' ×ₖ A' ⟶ A ×ₖ A ⟶ A` lifts through `p`, sending `(0', 0')` to `0'`
  (`exists_mul_lift`): by the Künneth formula X.1.7, `π₁(A' ×ₖ A')` is generated by the images of
  the two axes `A' ⟶ A' ×ₖ A'`, on which the composite is `p`;
* the inverse `A' ⟶ A ⟶ A` lifts as well (`exists_inv_lift`), since `ι_*` is inversion on
  `π₁(A)` (`pointedMap_inv`) and `p_* π₁(A')` is a subgroup;
* the group axioms hold because two morphisms from a connected scheme to `A'` which agree after
  `p` and at one point are equal (`coveringHom_ext`), and the products of `k`-schemes involved
  are connected (`connectedSpace_tensor`, from registry row A6:
  `AlgebraicGeometry.connectedSpace_pullback_of_isAlgClosed_of_connectedSpace`). The group object
  is built with mathlib's `GrpObj.ofRepresentableBy` from the induced group structures on the sets
  `S ⟶ A'`.

SGA's next remark is that every isogeny `A' ⟶ A` is a quotient of some `n_A`. What is proved
here, for these coverings: the lift `g : A ⟶ A'` of some `n_A` given by Serre–Lang is a
homomorphism with `g ≫ p = n_A` (`exists_isMonHom_comp_eq_mulN`). Since `p` is finite and
surjective, `g` is surjective (i.e. `A'` is the quotient `A / ker g`) exactly when `n_A` is:
`surjective_of_comp_eq_mulN` (in `AbelianVarietyIsogeny`) for one direction, the surjectivity of
`p` for the other. So SGA's remark is proved when the multiplications `n_A` are surjective
(`exists_surjective_isMonHom_comp_eq_mulN`), in particular in characteristic `0`
(`exists_surjective_isMonHom_comp_eq_mulN_of_charZero`, from `mulNIsogeny_of_ne_zero`). In
characteristic `p > 0` the `n` given by Serre–Lang may be divisible by `p`, and the surjectivity
of `p_A` is the open case of `MulNIsogenyStatement`.
-/

universe u

open CategoryTheory Limits AlgebraicGeometry MonoidalCategory CartesianMonoidalCategory MonObj
  PreGaloisCategory

namespace SGA.SGA1.ExposeXI

section Generalities

variable {k : Type u} [Field k] [IsAlgClosed k]

/-- The product of two connected `k`-schemes is connected, `k` being algebraically closed: the
form in `Over (Spec k)` of
`AlgebraicGeometry.connectedSpace_pullback_of_isAlgClosed_of_connectedSpace` (registry row A6). -/
lemma connectedSpace_tensor (X Z : Over (Spec (.of k))) [ConnectedSpace X.left]
    [ConnectedSpace Z.left] : ConnectedSpace (X ⊗ Z).left :=
  connectedSpace_pullback_of_isAlgClosed_of_connectedSpace X.hom Z.hom

end Generalities

section HSpace

variable {k : Type u} [Field k] [IsAlgClosed k]

/-- XI.2: on a group scheme `A` (proper, connected and reduced over `k`), the inverse induces
`σ ↦ σ⁻¹` on `π₁(A, 0)`: `x ↦ x · ι(x)` is constant (`pointedMap_lift_comp_mul`). -/
theorem pointedMap_inv (A : Over (Spec (.of k))) [GrpObj A] [IsProper A.hom] [IsReduced A.left]
    [ConnectedSpace A.left] (h : (η[A].left : Spec (.of k) ⟶ A.left) ≫ ι[A].left = η[A].left)
    (σ : ExposeV.etaleFundamentalGroup k (η[A].left : Spec (.of k) ⟶ A.left)) :
    pointedMap k ι[A].left _ _ h σ = σ⁻¹ := by
  have he : (η[A].left : Spec (.of k) ⟶ A.left) ≫ A.hom = 𝟙 _ := Over.w η[A]
  have hm₁ : pullback.lift (𝟙 A.left) (A.hom ≫ η[A].left) (by simp [he]) ≫ μ[A].left =
      𝟙 A.left := by
    have h := congrArg CommaMorphism.left (lift_comp_one_right (𝟙 A) (toUnit A))
    simp only [Over.comp_left, Over.lift_left, Over.id_left, Over.toUnit_left] at h
    exact h
  have hm₂ : pullback.lift (A.hom ≫ η[A].left) (𝟙 A.left) (by simp [he]) ≫ μ[A].left =
      𝟙 A.left := by
    have h := congrArg CommaMorphism.left (lift_comp_one_left (toUnit A) (𝟙 A))
    simp only [Over.comp_left, Over.lift_left, Over.id_left, Over.toUnit_left] at h
    exact h
  have hc := mul_comm_of_monObj A
  have hr : pullback.lift (𝟙 A.left) ι[A].left (by simp) ≫ μ[A].left = A.hom ≫ η[A].left := by
    have h := congrArg CommaMorphism.left (GrpObj.right_inv A)
    simp only [Over.comp_left, Over.lift_left, Over.id_left, Over.toUnit_left] at h
    exact h
  have key := pointedMap_lift_comp_mul A.hom _ he μ[A].left hm₁ hm₂ (𝟙 A.left) ι[A].left (by simp)
    (Category.comp_id _) h (by
      rw [hr, ← Category.assoc, he]
      exact Category.id_comp _) σ
  rw [pointedMap_of_eq k hr _ _ _ (by
      rw [← Category.assoc, he]
      exact Category.id_comp _),
    pointedMap_comp_eq_one k A.hom _ _ _ _ hc σ, pointedMap_id _ _ hc] at key
  exact (eq_inv_of_mul_eq_one_right key.symm)

end HSpace

section Covering

variable {k : Type u} [Field k] (A : Over (Spec (.of k))) (Y : ExposeV.FEt A.left)

/-- An étale covering `Y` of `A`, as a `k`-scheme. -/
noncomputable abbrev coveringOver : Over (Spec (.of k)) := Over.mk (Y.hom ≫ A.hom)

/-- The covering map `Y ⟶ A`, as a morphism of `k`-schemes. -/
noncomputable abbrev coveringHom : coveringOver A Y ⟶ A := Over.homMk Y.hom rfl

instance : IsFinite (coveringHom A Y).left := Y.prop.1

instance : Etale (coveringHom A Y).left := Y.prop.2

instance [IsProper A.hom] : IsProper (coveringOver A Y).hom := by
  have : IsFinite (Y.hom : Y.left ⟶ A.left) := Y.prop.1
  exact inferInstanceAs (IsProper (Y.hom ≫ A.hom))

instance [Smooth A.hom] : Smooth (coveringOver A Y).hom := by
  have : Etale (Y.hom : Y.left ⟶ A.left) := Y.prop.2
  exact inferInstanceAs (Smooth (Y.hom ≫ A.hom))

/-- XI.2: the covering map is finite. -/
theorem isFinite_coveringHom : IsFinite (coveringHom A Y).left := inferInstance

/-- XI.2: the covering map of a connected (indeed nonempty) étale covering is surjective. -/
theorem surjective_coveringHom [ConnectedSpace A.left] [Nonempty Y.left] :
    Surjective (coveringHom A Y).left :=
  have : Nonempty (coveringOver A Y).left := ‹Nonempty Y.left›
  ⟨ProjectiveSpace.surjective_of_isFinite_of_etale _⟩

variable {A Y}

/-- Two morphisms from a connected `k`-scheme `Z` to the covering which agree after the covering
map and at one point are equal. -/
lemma coveringHom_ext {Z : Over (Spec (.of k))} [ConnectedSpace Z.left]
    {f g : Z ⟶ coveringOver A Y} (h : f ≫ coveringHom A Y = g ≫ coveringHom A Y)
    (z : 𝟙_ (Over (Spec (.of k))) ⟶ Z) (hz : z ≫ f = z ≫ g) : f = g := by
  have : Etale (Y.hom : Y.left ⟶ A.left) := Y.prop.2
  have : IsFinite (Y.hom : Y.left ⟶ A.left) := Y.prop.1
  have : Nonempty (𝟙_ (Over (Spec (.of k)))).left := inferInstanceAs (Nonempty (Spec (.of k)))
  ext
  exact ExposeX.eq_of_comp_eq_of_connectedSpace Y.hom (congrArg CommaMorphism.left h) z.left
    (congrArg CommaMorphism.left hz)

variable [MonObj A] (o : Spec (.of k) ⟶ Y.left) (ho : o ≫ Y.hom = unitSection A)

/-- The marked point `0'` of the covering, as a point of the `k`-scheme. -/
noncomputable abbrev coveringUnit : 𝟙_ (Over (Spec (.of k))) ⟶ coveringOver A Y :=
  Over.homMk o (by
    change o ≫ Y.hom ≫ A.hom = 𝟙 _
    rw [← Category.assoc, ho]
    exact Over.w η[A])

include ho in
lemma coveringUnit_comp_coveringHom : coveringUnit o ho ≫ coveringHom A Y = η[A] := by
  ext
  exact ho

end Covering

section Lifts

variable {k : Type u} [Field k] [IsAlgClosed k] {A : Over (Spec (.of k))} [GrpObj A]
  [IsProper A.hom] [Smooth A.hom] [ConnectedSpace A.left] {Y : ExposeV.FEt A.left}
  [ConnectedSpace Y.left] (o : Spec (.of k) ⟶ Y.left) (ho : o ≫ Y.hom = unitSection A)
include ho

omit [ConnectedSpace Y.left] in
/-- `π₁` of an étale covering of `A`, at a point over the origin, is commutative: it embeds into
`π₁(A, 0)` (V.7). -/
lemma mul_comm_fundamentalGroup_covering (a b : ExposeV.etaleFundamentalGroup k o) :
    a * b = b * a := by
  have : IsReduced A.left := ExposeII.isReduced_of_smooth_of_isReduced A.hom
  have hinj : Function.Injective (pointedMap k Y.hom o (unitSection A) ho) := by
    rw [pointedMap_eq]
    exact (fundamentalGroupCongr ho).injective.comp
      (ExposeV.etaleFundamentalGroup.injective_map_and_range_eq_stabilizer k Y.hom Y.prop o).1
  apply hinj
  rw [map_mul, map_mul]
  exact mul_comm_of_monObj A _ _

omit [IsProper A.hom] [Smooth A.hom] [ConnectedSpace A.left] in
/-- The covering map fixes the marked point: `p_*` maps `π₁(A', 0')` into the stabilizer of
`0'` in the fibre of `p` at the origin. -/
lemma pointedMap_coveringHom_smul (a : ExposeV.etaleFundamentalGroup k o) :
    pointedMap k Y.hom o (unitSection A) ho a • fiberMk Y o ho = fiberMk Y o ho :=
  have : ConnectedSpace ((𝟭 Scheme).obj Y.left) := ‹ConnectedSpace Y.left›
  pointedMap_smul_eq_of_lift Y.hom o _ ho Y _ (𝟙 _) (Category.id_comp _)
    (by rw [Category.comp_id, fiberPoint_fiberMk]) a

/-- XI.2: the multiplication of `A` lifts to the covering: there is `m : A' ⊗ A' ⟶ A'` over
`(p ⊗ p) ≫ μ` with `m(0', 0') = 0'`. By X.1.7, `π₁(A' ×ₖ A')` is generated by the images of the
axes `x ↦ (x, 0')` and `x ↦ (0', x)`, on which `(p ⊗ p) ≫ μ` is `p`. -/
theorem exists_mul_lift :
    ∃ m : coveringOver A Y ⊗ coveringOver A Y ⟶ coveringOver A Y,
      m ≫ coveringHom A Y = (coveringHom A Y ⊗ₘ coveringHom A Y) ≫ μ[A] ∧
      lift (coveringUnit o ho) (coveringUnit o ho) ≫ m = coveringUnit o ho := by
  have : IsReduced A.left := ExposeII.isReduced_of_smooth_of_isReduced A.hom
  set A' := coveringOver A Y
  set p := coveringHom A Y
  set e' := coveringUnit o ho
  have : IsReduced A'.left := ExposeII.isReduced_of_smooth_of_isReduced A'.hom
  have : IsLocallyNoetherian A'.left := LocallyOfFiniteType.isLocallyNoetherian A'.hom
  have : ConnectedSpace A'.left := ‹ConnectedSpace Y.left›
  have : ConnectedSpace (A' ⊗ A').left := connectedSpace_tensor A' A'
  have hc' := mul_comm_fundamentalGroup_covering o ho
  have hcA := mul_comm_of_monObj A
  have hep : e' ≫ p = η[A] := coveringUnit_comp_coveringHom o ho
  have heu : e' ≫ toUnit A' = 𝟙 _ := toUnit_unique _ _
  let u : A' ⊗ A' ⟶ A := (p ⊗ₘ p) ≫ μ[A]
  let t : Spec (.of k) ⟶ (A' ⊗ A').left := (lift e' e').left
  have hu0 : lift e' e' ≫ u = η[A] := by
    have := lift_comp_one_right η[A] (𝟙 _)
    rw [Category.id_comp] at this
    rw [← Category.assoc, lift_map, hep, this]
  have h : t ≫ u.left = unitSection A := congrArg CommaMorphism.left hu0
  let y := fiberMk Y o ho
  -- the two axes `x ↦ (x, 0')` and `x ↦ (0', x)`
  let I₁ : A' ⟶ A' ⊗ A' := lift (𝟙 A') (toUnit A' ≫ e')
  let I₂ : A' ⟶ A' ⊗ A' := lift (toUnit A' ≫ e') (𝟙 A')
  have hI₁ : o ≫ I₁.left = t := by
    have : e' ≫ I₁ = lift e' e' := by
      rw [comp_lift, Category.comp_id, ← Category.assoc, heu, Category.id_comp]
    exact congrArg CommaMorphism.left this
  have hI₂ : o ≫ I₂.left = t := by
    have : e' ≫ I₂ = lift e' e' := by
      rw [comp_lift, Category.comp_id, ← Category.assoc, heu, Category.id_comp]
    exact congrArg CommaMorphism.left this
  have hI₁u : I₁.left ≫ u.left = Y.hom := by
    have : I₁ ≫ u = p := by
      rw [← Category.assoc, lift_map, Category.id_comp, Category.assoc, hep]
      exact lift_comp_one_right p (toUnit A')
    exact congrArg CommaMorphism.left this
  have hI₂u : I₂.left ≫ u.left = Y.hom := by
    have : I₂ ≫ u = p := by
      rw [← Category.assoc, lift_map, Category.id_comp, Category.assoc, hep]
      exact lift_comp_one_left (toUnit A') p
    exact congrArg CommaMorphism.left this
  have hcf : t ≫ pullback.fst A'.hom A'.hom = o := congrArg CommaMorphism.left (lift_fst e' e')
  have hcs : t ≫ pullback.snd A'.hom A'.hom = o := congrArg CommaMorphism.left (lift_snd e' e')
  have hI₁f : I₁.left ≫ pullback.fst A'.hom A'.hom = 𝟙 _ :=
    congrArg CommaMorphism.left (lift_fst (𝟙 A') (toUnit A' ≫ e'))
  have hI₁s : I₁.left ≫ pullback.snd A'.hom A'.hom = A'.hom ≫ o :=
    congrArg CommaMorphism.left (lift_snd (𝟙 A') (toUnit A' ≫ e'))
  have hI₂f : I₂.left ≫ pullback.fst A'.hom A'.hom = A'.hom ≫ o :=
    congrArg CommaMorphism.left (lift_fst (toUnit A' ≫ e') (𝟙 A'))
  have hI₂s : I₂.left ≫ pullback.snd A'.hom A'.hom = 𝟙 _ :=
    congrArg CommaMorphism.left (lift_snd (toUnit A' ≫ e') (𝟙 A'))
  have hoo : o ≫ A'.hom ≫ o = o := by
    rw [← Category.assoc]
    have : o ≫ A'.hom = 𝟙 _ := e'.w
    rw [this]
    exact Category.id_comp _
  -- by X.1.7, an element of `π₁(A' ×ₖ A')` is determined by its two projections
  have hinj (τ τ' : ExposeV.etaleFundamentalGroup k t)
      (h₁ : pointedMap k (pullback.fst A'.hom A'.hom) t o hcf τ =
        pointedMap k (pullback.fst A'.hom A'.hom) t o hcf τ')
      (h₂ : pointedMap k (pullback.snd A'.hom A'.hom) t o hcs τ =
        pointedMap k (pullback.snd A'.hom A'.hom) t o hcs τ') : τ = τ' := by
    have hΦ := ExposeX.bijective_map_prod A'.hom A'.hom t (by
      rw [← Category.assoc, hcs]
      exact e'.w)
    rw [pointedMap_eq] at h₁ h₂
    apply hΦ.1
    simp only [MonoidHom.comp_apply, MulEquiv.coe_toMonoidHom, EmbeddingLike.apply_eq_iff_eq]
      at h₁ h₂
    simp only [MonoidHom.prod_apply, h₁, h₂]
  have hconst (x : ExposeV.etaleFundamentalGroup k o) :
      pointedMap k (A'.hom ≫ o) o o hoo x = 1 :=
    pointedMap_comp_eq_one k A'.hom o o o hoo hc' x
  have hy (σ : ExposeV.etaleFundamentalGroup k t) :
      pointedMap k u.left t (unitSection A) h σ • y = y := by
    set a := pointedMap k (pullback.fst A'.hom A'.hom) t o hcf σ
    set b := pointedMap k (pullback.snd A'.hom A'.hom) t o hcs σ
    have hσ : σ = pointedMap k I₁.left o t hI₁ a * pointedMap k I₂.left o t hI₂ b := by
      apply hinj
      · rw [map_mul, pointedMap_pointedMap I₁.left _ o t o hI₁ hcf (by rw [hI₁f, Category.comp_id])
          hc', pointedMap_pointedMap I₂.left _ o t o hI₂ hcf (by rw [hI₂f, hoo]) hc',
          pointedMap_of_eq k hI₁f o o _ (Category.comp_id o), pointedMap_of_eq k hI₂f o o _ hoo,
          pointedMap_id (T := A'.left) o _ hc', hconst, _root_.mul_one]
      · rw [map_mul, pointedMap_pointedMap I₁.left _ o t o hI₁ hcs (by rw [hI₁s, hoo]) hc',
          pointedMap_pointedMap I₂.left _ o t o hI₂ hcs (by rw [hI₂s, Category.comp_id]) hc',
          pointedMap_of_eq k hI₁s o o _ hoo, pointedMap_of_eq k hI₂s o o _ (Category.comp_id o),
          pointedMap_id (T := A'.left) o _ hc', hconst, _root_.one_mul]
    rw [hσ, map_mul,
      pointedMap_pointedMap I₁.left u.left o t _ hI₁ h (by rw [hI₁u, ho]) hcA,
      pointedMap_pointedMap I₂.left u.left o t _ hI₂ h (by rw [hI₂u, ho]) hcA,
      pointedMap_of_eq k hI₁u o _ _ ho, pointedMap_of_eq k hI₂u o _ _ ho, mul_smul,
      pointedMap_coveringHom_smul o ho, pointedMap_coveringHom_smul o ho]
  obtain ⟨g, hg, hg0⟩ := exists_lift_of_forall_smul_eq_of_apply u.left t _ h Y y hy
  refine ⟨Over.homMk g (by
      change g ≫ Y.hom ≫ A.hom = _
      rw [← Category.assoc, hg]
      exact Over.w u), ?_, ?_⟩
  · ext
    exact hg
  · ext
    exact hg0.trans (fiberPoint_fiberMk _ _ _)

/-- XI.2: the inverse of `A` lifts to the covering: there is `i : A' ⟶ A'` over `p ≫ ι` with
`i(0') = 0'`, since `ι_*` is inversion on `π₁(A, 0)` (`pointedMap_inv`) and `p_* π₁(A', 0')` is
a subgroup. -/
theorem exists_inv_lift :
    ∃ i : coveringOver A Y ⟶ coveringOver A Y,
      i ≫ coveringHom A Y = coveringHom A Y ≫ ι[A] ∧ coveringUnit o ho ≫ i = coveringUnit o ho := by
  have : IsReduced A.left := ExposeII.isReduced_of_smooth_of_isReduced A.hom
  have hcA := mul_comm_of_monObj A
  have hι0 : unitSection A ≫ ι[A].left = unitSection A :=
    congrArg CommaMorphism.left (GrpObj.one_inv (G := A))
  have h : o ≫ Y.hom ≫ ι[A].left = unitSection A := by rw [← Category.assoc, ho, hι0]
  have hy (σ : ExposeV.etaleFundamentalGroup k o) :
      pointedMap k (Y.hom ≫ ι[A].left) o _ h σ • fiberMk Y o ho = fiberMk Y o ho := by
    rw [← pointedMap_pointedMap Y.hom ι[A].left o _ _ ho hι0 h hcA, pointedMap_inv A hι0,
      inv_smul_eq_iff]
    exact (pointedMap_coveringHom_smul o ho σ).symm
  have : ConnectedSpace ((𝟭 Scheme).obj Y.left) := ‹ConnectedSpace Y.left›
  obtain ⟨g, hg, hg0⟩ := exists_lift_of_forall_smul_eq_of_apply _ o _ h Y _ hy
  refine ⟨Over.homMk g (by
      change g ≫ Y.hom ≫ A.hom = Y.hom ≫ A.hom
      rw [← Category.assoc, hg, Category.assoc]
      congr 1
      exact Over.w ι[A]), ?_, ?_⟩
  · ext
    exact hg
  · ext
    exact hg0.trans (fiberPoint_fiberMk _ _ _)

end Lifts

section Group

variable {k : Type u} [Field k] [IsAlgClosed k] {A : Over (Spec (.of k))} [GrpObj A]
  [IsProper A.hom] [Smooth A.hom] [ConnectedSpace A.left] {Y : ExposeV.FEt A.left}
  [ConnectedSpace Y.left] {o : Spec (.of k) ⟶ Y.left} {ho : o ≫ Y.hom = unitSection A}
  {m : coveringOver A Y ⊗ coveringOver A Y ⟶ coveringOver A Y}
  {i : coveringOver A Y ⟶ coveringOver A Y}
  (hm : m ≫ coveringHom A Y = (coveringHom A Y ⊗ₘ coveringHom A Y) ≫ μ[A])
  (hm0 : lift (coveringUnit o ho) (coveringUnit o ho) ≫ m = coveringUnit o ho)
  (hi : i ≫ coveringHom A Y = coveringHom A Y ≫ ι[A])
  (hi0 : coveringUnit o ho ≫ i = coveringUnit o ho)

omit [IsAlgClosed k] [IsProper A.hom] [Smooth A.hom] [ConnectedSpace A.left]
  [ConnectedSpace Y.left] in
include hm in
/-- `m` lifts the multiplication: `p ∘ m(f, g) = p(f) · p(g)` in the group `S ⟶ A`. -/
lemma lift_comp_comp_coveringHom {S : Over (Spec (.of k))} (f g : S ⟶ coveringOver A Y) :
    (lift f g ≫ m) ≫ coveringHom A Y = (f ≫ coveringHom A Y) * (g ≫ coveringHom A Y) := by
  rw [Category.assoc, hm, ← Category.assoc, lift_map, Hom.mul_def]

omit [GrpObj A] [IsProper A.hom] [Smooth A.hom] [ConnectedSpace A.left] in
/-- The connectedness facts used for the group axioms. -/
private lemma connectedSpace_covering_tensor :
    ConnectedSpace (coveringOver A Y ⊗ coveringOver A Y).left ∧
      ConnectedSpace ((coveringOver A Y ⊗ coveringOver A Y) ⊗ coveringOver A Y).left := by
  have : ConnectedSpace (coveringOver A Y).left := ‹ConnectedSpace Y.left›
  have h₁ := connectedSpace_tensor (coveringOver A Y) (coveringOver A Y)
  refine ⟨h₁, ?_⟩
  have : ConnectedSpace (coveringOver A Y ⊗ (coveringOver A Y ⊗ coveringOver A Y)).left :=
    connectedSpace_tensor _ _
  exact (Scheme.homeoOfIso ((Over.forget _).mapIso
    (α_ (coveringOver A Y) (coveringOver A Y) (coveringOver A Y)))).connectedSpace_iff.mpr this

variable (m) in
/-- `(x, y, z) ↦ m(m(x, y), z)`. -/
private noncomputable abbrev mulLeft :
    (coveringOver A Y ⊗ coveringOver A Y) ⊗ coveringOver A Y ⟶ coveringOver A Y :=
  lift (lift (fst _ _ ≫ fst _ _) (fst _ _ ≫ snd _ _) ≫ m) (snd _ _) ≫ m

variable (m) in
/-- `(x, y, z) ↦ m(x, m(y, z))`. -/
private noncomputable abbrev mulRight :
    (coveringOver A Y ⊗ coveringOver A Y) ⊗ coveringOver A Y ⟶ coveringOver A Y :=
  lift (fst _ _ ≫ fst _ _) (lift (fst _ _ ≫ snd _ _) (snd _ _) ≫ m) ≫ m

omit [IsProper A.hom] [Smooth A.hom] [ConnectedSpace A.left] in
include hm hm0 in
/-- Associativity of `m` on the universal triple: both sides lift `p(x) p(y) p(z)` and agree at
`(0', 0', 0')`. -/
private lemma mulLeft_eq_mulRight : mulLeft m = mulRight m := by
  have := (connectedSpace_covering_tensor (A := A) (Y := Y)).2
  refine coveringHom_ext ?_
    (lift (lift (coveringUnit o ho) (coveringUnit o ho)) (coveringUnit o ho)) ?_
  · rw [lift_comp_comp_coveringHom hm, lift_comp_comp_coveringHom hm,
      lift_comp_comp_coveringHom hm, lift_comp_comp_coveringHom hm, _root_.mul_assoc]
  · simp [comp_lift_assoc, hm0]

omit [IsAlgClosed k] [IsProper A.hom] [Smooth A.hom] [ConnectedSpace A.left] in
include hm hm0 in
/-- The left unit law for `m`, on the universal element. -/
private lemma one_mul_univ :
    lift (toUnit (coveringOver A Y) ≫ coveringUnit o ho) (𝟙 _) ≫ m = 𝟙 (coveringOver A Y) := by
  have : ConnectedSpace (coveringOver A Y).left := ‹ConnectedSpace Y.left›
  refine coveringHom_ext ?_ (coveringUnit o ho) ?_
  · rw [lift_comp_comp_coveringHom hm, Category.assoc, coveringUnit_comp_coveringHom o ho,
      ← Hom.one_def, _root_.one_mul]
  · simp [comp_lift_assoc, hm0]

omit [IsAlgClosed k] [IsProper A.hom] [Smooth A.hom] [ConnectedSpace A.left] in
include hm hm0 hi hi0 in
/-- The left inverse law for `m` and `i`, on the universal element. -/
private lemma inv_mul_univ :
    lift i (𝟙 _) ≫ m = toUnit (coveringOver A Y) ≫ coveringUnit o ho := by
  have : ConnectedSpace (coveringOver A Y).left := ‹ConnectedSpace Y.left›
  refine coveringHom_ext ?_ (coveringUnit o ho) ?_
  · rw [lift_comp_comp_coveringHom hm, hi, Category.id_comp, ← Hom.inv_def, inv_mul_cancel,
      Category.assoc, coveringUnit_comp_coveringHom o ho, ← Hom.one_def]
  · simp [comp_lift_assoc, hm0, hi0]

include hm hm0 hi hi0 in
/-- The group structure on `S ⟶ A'` induced by `m`, `i` and `0'`. -/
noncomputable abbrev coveringHomGroup (S : Over (Spec (.of k))) :
    Group (S ⟶ coveringOver A Y) :=
  letI : Mul (S ⟶ coveringOver A Y) := ⟨fun f g ↦ lift f g ≫ m⟩
  letI : One (S ⟶ coveringOver A Y) := ⟨toUnit S ≫ coveringUnit o ho⟩
  letI : Inv (S ⟶ coveringOver A Y) := ⟨fun f ↦ f ≫ i⟩
  Group.ofLeftAxioms
    (fun f g h ↦ by
      change lift (lift f g ≫ m) h ≫ m = lift f (lift g h ≫ m) ≫ m
      have e₁ : lift (lift f g ≫ m) h ≫ m = lift (lift f g) h ≫ mulLeft m := by
        simp [comp_lift_assoc]
      have e₂ : lift f (lift g h ≫ m) ≫ m = lift (lift f g) h ≫ mulRight m := by
        simp [comp_lift_assoc]
      rw [e₁, e₂, mulLeft_eq_mulRight hm hm0])
    (fun f ↦ by
      change lift (toUnit S ≫ coveringUnit o ho) f ≫ m = f
      have e : lift (toUnit S ≫ coveringUnit o ho) f ≫ m =
          f ≫ lift (toUnit (coveringOver A Y) ≫ coveringUnit o ho) (𝟙 _) ≫ m := by
        simp [comp_lift_assoc]
      rw [e, one_mul_univ hm hm0, Category.comp_id])
    (fun f ↦ by
      change lift (f ≫ i) f ≫ m = toUnit S ≫ coveringUnit o ho
      have e : lift (f ≫ i) f ≫ m = f ≫ lift i (𝟙 _) ≫ m := by
        simp [comp_lift_assoc]
      rw [e, inv_mul_univ hm hm0 hi hi0, ← Category.assoc, comp_toUnit])

include hm hm0 hi hi0 in
/-- The functor `S ↦ (S ⟶ A')`, with the group structures `coveringHomGroup`. -/
noncomputable def coveringGrpFunctor : (Over (Spec (.of k)))ᵒᵖ ⥤ GrpCat.{u} where
  obj S :=
    letI := coveringHomGroup hm hm0 hi hi0 S.unop
    GrpCat.of (S.unop ⟶ coveringOver A Y)
  map {S T} f :=
    letI := coveringHomGroup hm hm0 hi hi0 S.unop
    letI := coveringHomGroup hm hm0 hi hi0 T.unop
    GrpCat.ofHom
    { toFun x := f.unop ≫ x
      map_one' := by
        change f.unop ≫ toUnit _ ≫ coveringUnit o ho = toUnit _ ≫ coveringUnit o ho
        rw [← Category.assoc, comp_toUnit]
      map_mul' x y := by
        change f.unop ≫ lift x y ≫ m = lift (f.unop ≫ x) (f.unop ≫ y) ≫ m
        rw [comp_lift_assoc] }
  map_id S := GrpCat.ext fun x ↦ Category.id_comp x
  map_comp f g := GrpCat.ext fun x ↦ Category.assoc _ _ x

/-- `A'` represents `coveringGrpFunctor`, tautologically. -/
noncomputable def coveringRepresentableBy :
    (coveringGrpFunctor hm hm0 hi hi0 ⋙ forget GrpCat).RepresentableBy (coveringOver A Y) where
  homEquiv := Equiv.refl _
  homEquiv_comp _ _ := rfl

/-- The group-scheme structure on `A'` given by the lifts `m` and `i`. -/
noncomputable abbrev coveringGrpObj : GrpObj (coveringOver A Y) :=
  GrpObj.ofRepresentableBy _ _ (coveringRepresentableBy hm hm0 hi hi0)

omit [IsProper A.hom] [Smooth A.hom] [ConnectedSpace A.left] in
lemma coveringGrpObj_one : (coveringGrpObj hm hm0 hi hi0).one = coveringUnit o ho := by
  change toUnit (𝟙_ _) ≫ coveringUnit o ho = coveringUnit o ho
  rw [toUnit_unique (toUnit _) (𝟙 _), Category.id_comp]

omit [IsProper A.hom] [Smooth A.hom] [ConnectedSpace A.left] in
lemma coveringGrpObj_mul : (coveringGrpObj hm hm0 hi hi0).mul = m := by
  change lift (fst _ _) (snd _ _) ≫ m = m
  rw [lift_fst_snd, Category.id_comp]

omit [IsProper A.hom] [Smooth A.hom] [ConnectedSpace A.left] in
lemma isMonHom_coveringHom :
    @IsMonHom _ _ _ _ _ (coveringGrpObj hm hm0 hi hi0).toMonObj _ (coveringHom A Y) := by
  let _ := coveringGrpObj hm hm0 hi hi0
  exact
    { one_hom := by
        rw [coveringGrpObj_one hm hm0 hi hi0]
        exact coveringUnit_comp_coveringHom o ho
      mul_hom := by
        rw [coveringGrpObj_mul hm hm0 hi hi0]
        exact hm }

end Group

section Main

variable {k : Type u} [Field k] [IsAlgClosed k] {A : Over (Spec (.of k))} [GrpObj A]
  [IsProper A.hom] [Smooth A.hom] [ConnectedSpace A.left] {Y : ExposeV.FEt A.left}
  [ConnectedSpace Y.left]

/-- XI.2 (the connected case of SGA's statement on principal coverings): let `A` be an abelian
variety over an algebraically closed field `k`, `p : A' ⟶ A` a connected étale covering and `0'`
a `k`-point of `A'` over the origin. Then `A'` carries a unique group-scheme structure with
origin `0'` for which `p` is a homomorphism. With it, `A'` is an abelian variety (proper, smooth
and connected, hence commutative by `isCommMonObj_of_smooth`) and `p` is an isogeny: finite and
surjective (`isFinite_coveringHom`, `surjective_coveringHom`). -/
theorem existsUnique_grpObj_coveringOver (o : Spec (.of k) ⟶ Y.left)
    (ho : o ≫ Y.hom = unitSection A) :
    ∃! G : GrpObj (coveringOver A Y), G.one = coveringUnit o ho ∧
      @IsMonHom _ _ _ _ _ G.toMonObj _ (coveringHom A Y) := by
  obtain ⟨m, hm, hm0⟩ := exists_mul_lift o ho
  obtain ⟨i, hi, hi0⟩ := exists_inv_lift o ho
  refine ⟨coveringGrpObj hm hm0 hi hi0,
    ⟨coveringGrpObj_one hm hm0 hi hi0, isMonHom_coveringHom hm hm0 hi hi0⟩,
    fun G ⟨hG1, hGp⟩ ↦ GrpObj.ext _ _ (MonObj.ext _ _ ?_)⟩
  rw [coveringGrpObj_mul hm hm0 hi hi0]
  -- `G`'s multiplication is a lift of `(p ⊗ p) ≫ μ` sending `(0', 0')` to `0'`
  have := (connectedSpace_covering_tensor (A := A) (Y := Y)).1
  refine coveringHom_ext ?_ (lift (coveringUnit o ho) (coveringUnit o ho)) ?_
  · rw [hm]
    let _ := G
    exact IsMonHom.mul_hom (coveringHom A Y)
  · rw [hm0]
    let _ := G
    have h := lift_comp_one_right (coveringUnit o ho) (𝟙 (𝟙_ (Over (Spec (.of k)))))
    rw [Category.id_comp, hG1] at h
    exact h

omit [ConnectedSpace Y.left] in
/-- XI.2, towards "every isogeny `A' ⟶ A` is a quotient of an isogeny `n_A`", for the étale
coverings: with any group-scheme structure on `A'` as in `existsUnique_grpObj_coveringOver`, the
lift `g : A ⟶ A'` of some `n_A` given by Serre–Lang (`exists_mulNLifts`) with `g(0) = 0'` is a
homomorphism with `g ≫ p = n_A`. (Both `g ∘ μ` and `μ' ∘ (g × g)` lift `n_A ∘ μ` and agree at
`(0, 0)`.)

This does not say that `g` is surjective, which is what "`A'` is a quotient of `A` by `ker g`"
means. Since `p` is surjective, `g` is surjective iff `n_A = g ≫ p` is
(`surjective_of_comp_eq_mulN` for `⇐`); see `exists_surjective_isMonHom_comp_eq_mulN` and, in
characteristic `0`, `exists_surjective_isMonHom_comp_eq_mulN_of_charZero`. In characteristic
`p > 0` the `n` given here may be divisible by `p`, and `p_A` surjective is the open case of
`MulNIsogenyStatement`. -/
theorem exists_isMonHom_comp_eq_mulN (o : Spec (.of k) ⟶ Y.left)
    (ho : o ≫ Y.hom = unitSection A) (G : GrpObj (coveringOver A Y))
    (hG1 : G.one = coveringUnit o ho)
    (hGp : @IsMonHom _ _ _ _ _ G.toMonObj _ (coveringHom A Y)) :
    ∃ n : ℕ, 0 < n ∧ ∃ g : A ⟶ coveringOver A Y,
      @IsMonHom _ _ _ _ _ _ G.toMonObj g ∧ g ≫ coveringHom A Y = mulN A n := by
  let _ := G
  have : IsReduced A.left := ExposeII.isReduced_of_smooth_of_isReduced A.hom
  have := isCommMonObj_of_smooth A
  obtain ⟨n, hn, hlift⟩ := exists_mulNLifts A Y
  obtain ⟨g, hg, hg0⟩ := hlift (fiberMk Y o ho)
  rw [fiberPoint_fiberMk] at hg0
  let g' : A ⟶ coveringOver A Y := Over.homMk g (by
    change g ≫ Y.hom ≫ A.hom = A.hom
    rw [← Category.assoc, hg]
    exact Over.w (mulN A n))
  have hg'p : g' ≫ coveringHom A Y = mulN A n := by
    ext
    exact hg
  have hg'0 : η[A] ≫ g' = coveringUnit o ho := by
    ext
    exact hg0
  refine ⟨n, hn, g', ⟨?_, ?_⟩, hg'p⟩
  · rw [hg'0, ← hG1]
  · have : ConnectedSpace (A ⊗ A).left := connectedSpace_tensor A A
    refine coveringHom_ext ?_ (lift η[A] η[A]) ?_
    · rw [Category.assoc, hg'p, Category.assoc, IsMonHom.mul_hom (coveringHom A Y),
        ← Category.assoc, tensorHom_comp_tensorHom, hg'p]
      exact IsMonHom.mul_hom (mulN A n)
    · have h₁ := lift_comp_one_right η[A] (𝟙 (𝟙_ (Over (Spec (.of k)))))
      have h₂ := lift_comp_one_right η[coveringOver A Y] (𝟙 (𝟙_ (Over (Spec (.of k)))))
      rw [Category.id_comp] at h₁ h₂
      rw [← Category.assoc, h₁, hg'0, ← Category.assoc, lift_map, hg'0, ← hG1, h₂]

/-- XI.2: "every isogeny `A' ⟶ A` is a quotient of an isogeny `n_A`", for the connected étale
coverings, assuming that the multiplications `n_A` are surjective (SGA's cited fact
`MulNIsogenyStatement` gives this). With any group-scheme structure on `A'` as in
`existsUnique_grpObj_coveringOver`, there are `n > 0` and a surjective homomorphism
`g : A ⟶ A'` with `g ≫ p = n_A` (`exists_isMonHom_comp_eq_mulN`, `surjective_of_comp_eq_mulN`). -/
theorem exists_surjective_isMonHom_comp_eq_mulN
    (hsurj : ∀ n : ℕ, 0 < n → Surjective (mulN A n).left) (o : Spec (.of k) ⟶ Y.left)
    (ho : o ≫ Y.hom = unitSection A) (G : GrpObj (coveringOver A Y))
    (hG1 : G.one = coveringUnit o ho)
    (hGp : @IsMonHom _ _ _ _ _ G.toMonObj _ (coveringHom A Y)) :
    ∃ n : ℕ, 0 < n ∧ ∃ g : A ⟶ coveringOver A Y,
      @IsMonHom _ _ _ _ _ _ G.toMonObj g ∧ g ≫ coveringHom A Y = mulN A n ∧
        Surjective g.left := by
  obtain ⟨n, hn, g, hgm, hg⟩ := exists_isMonHom_comp_eq_mulN o ho G hG1 hGp
  have := hsurj n hn
  have : IsFinite (Y.hom : Y.left ⟶ A.left) := Y.prop.1
  have : Etale (Y.hom : Y.left ⟶ A.left) := Y.prop.2
  have : ConnectedSpace ((𝟭 Scheme).obj Y.left) := ‹ConnectedSpace Y.left›
  exact ⟨n, hn, g, hgm, hg,
    surjective_of_comp_eq_mulN A Y.hom g.left (congrArg CommaMorphism.left hg)⟩

/-- XI.2 in characteristic `0`: "every isogeny `A' ⟶ A` is a quotient of an isogeny `n_A`", for
the connected étale coverings: `exists_surjective_isMonHom_comp_eq_mulN`, the multiplications
`n_A` being surjective for `n` invertible in `k` (`mulNIsogeny_of_ne_zero`). -/
theorem exists_surjective_isMonHom_comp_eq_mulN_of_charZero [CharZero k]
    (o : Spec (.of k) ⟶ Y.left) (ho : o ≫ Y.hom = unitSection A) (G : GrpObj (coveringOver A Y))
    (hG1 : G.one = coveringUnit o ho)
    (hGp : @IsMonHom _ _ _ _ _ G.toMonObj _ (coveringHom A Y)) :
    ∃ n : ℕ, 0 < n ∧ ∃ g : A ⟶ coveringOver A Y,
      @IsMonHom _ _ _ _ _ _ G.toMonObj g ∧ g ≫ coveringHom A Y = mulN A n ∧
        Surjective g.left := by
  have := isCommMonObj_of_smooth A
  exact exists_surjective_isMonHom_comp_eq_mulN
    (fun n hn ↦ (mulNIsogeny_of_ne_zero A (Nat.cast_ne_zero.mpr hn.ne')).2) o ho G hG1 hGp

end Main

end SGA.SGA1.ExposeXI
