/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.SGA1.ExposeXI.HodgeLefschetzAlgebra

/-!
# Unirationality descends to a large enough subfield (XI.1.4, Lefschetz principle)

The algebra behind the spreading-out half of the Lefschetz principle for XI.1.4: a unirational
parametrization is defined over a subfield generated by finitely many elements. Let `F ⊆ K` be
fields, `A` an `F`-algebra of finite type, `B = K ⊗_F A` with fraction field `L` unirational over
`K`. Then there is a finite set `S ⊆ K` such that for every tower of fields `F → E → K` with `S`
in the image of `E`, the fraction field of `E ⊗_F A` is unirational over `E`
(`exists_finset_isUnirational_of_isPushout`).

The proof: write the parametrization as `τ : L ↪ K(σ)`, `K(σ)` finite over `L`. The images of
finitely many generators of `A` are fractions of polynomials with finitely many coefficients, and
the integral equations of the variables of `K(σ)` over `L` have finitely many coefficients, each
a fraction of elements of `K ⊗_F A` involving finitely many elements of `K`. Once `E` contains all
of these, `τ` maps `E ⊗_F A` into `E(σ) ⊆ K(σ)` and the variables are integral over the fraction
field of `E ⊗_F A`.

* `HodgeLefschetz.mem_range_ratFuncMap_of_coeffs`: a fraction of polynomials with coefficients in
  `E` lies in `E(σ)`;
* `HodgeLefschetz.exists_finset_mem_adjoin`: every element of `K ⊗_F A` lies in the
  `F`-subalgebra generated by `A` and finitely many elements of `K`;
* `exists_finset_isUnirational_of_isPushout`: the main result.

## References

* [EGA IV₃, 8.8.2] (spreading out over a filtered union of subrings), for the shape of the
  argument.
-/

universe u

open TensorProduct

namespace SGA.SGA1.ExposeXI

namespace HodgeLefschetz

section Coefficients

variable {K : Type u} [Field K] (σ : Type u)

/-- A fraction of polynomials whose coefficients lie in a subfield `E ⊆ K` lies in the image of
`E(σ) → K(σ)`. -/
theorem mem_range_ratFuncMap_of_coeffs (E : Type u) [Field E] [Algebra E K]
    (p q : MvPolynomial σ K) (hp : (p.coeffs : Set K) ⊆ Set.range (algebraMap E K))
    (hq : (q.coeffs : Set K) ⊆ Set.range (algebraMap E K)) :
    algebraMap _ (FractionRing (MvPolynomial σ K)) p /
        algebraMap (MvPolynomial σ K) (FractionRing (MvPolynomial σ K)) q ∈
      Set.range (ratFuncMap E K σ) := by
  obtain ⟨p', rfl⟩ := MvPolynomial.mem_range_map_iff_coeffs_subset.mpr hp
  obtain ⟨q', rfl⟩ := MvPolynomial.mem_range_map_iff_coeffs_subset.mpr hq
  refine ⟨algebraMap _ _ p' / algebraMap (MvPolynomial σ E) _ q', ?_⟩
  rw [map_div₀, ratFuncMap_algebraMap, ratFuncMap_algebraMap]
  simp [polyToRatFunc, MvPolynomial.mapAlgHom_apply]

end Coefficients

section Pushout

variable {F K A B : Type u} [Field F] [Field K] [Algebra F K] [CommRing A] [Algebra F A]
  [CommRing B] [Algebra F B] [Algebra A B] [Algebra K B] [IsScalarTower F A B]
  [IsScalarTower F K B] [Algebra.IsPushout F K A B]

variable (A) in
/-- Every element of `B = K ⊗_F A` lies in the `F`-subalgebra generated by the image of `A` and
finitely many elements of `K`. -/
theorem exists_finset_mem_adjoin (b : B) :
    ∃ T : Finset K, b ∈ Algebra.adjoin F (Set.range (algebraMap A B) ∪ algebraMap K B '' T) := by
  classical
  obtain ⟨z, rfl⟩ := (Algebra.IsPushout.equiv F K A B).surjective b
  induction z using TensorProduct.induction_on with
  | zero => exact ⟨∅, by simp⟩
  | tmul c a =>
    refine ⟨{c}, ?_⟩
    rw [Algebra.IsPushout.equiv_tmul]
    exact Subalgebra.mul_mem _ (Algebra.subset_adjoin (Or.inr ⟨c, by simp, rfl⟩))
      (Algebra.subset_adjoin (Or.inl ⟨a, rfl⟩))
  | add z₁ z₂ h₁ h₂ =>
    obtain ⟨T₁, hT₁⟩ := h₁
    obtain ⟨T₂, hT₂⟩ := h₂
    refine ⟨T₁ ∪ T₂, ?_⟩
    rw [map_add]
    have hle (T T' : Finset K) (h : T ⊆ T') :
        Algebra.adjoin F (Set.range (algebraMap A B) ∪ algebraMap K B '' T) ≤
          Algebra.adjoin F (Set.range (algebraMap A B) ∪ algebraMap K B '' T') :=
      Algebra.adjoin_mono (Set.union_subset_union_right _ (Set.image_mono (by simpa using h)))
    exact add_mem (hle _ _ Finset.subset_union_left hT₁) (hle _ _ Finset.subset_union_right hT₂)

end Pushout


section Descent

variable {F K A B : Type u} [Field F] [Field K] [Algebra F K] [CommRing A] [Algebra F A]
  [CommRing B] [Algebra F B] [Algebra A B] [Algebra K B] [IsScalarTower F A B]
  [IsScalarTower F K B]
  (E : Type u) [Field E] [Algebra F E] [Algebra E K] [IsScalarTower F E K]
  (BE : Type u) [CommRing BE] [Algebra F BE] [Algebra A BE]
  [Algebra E BE] [IsScalarTower F A BE] [IsScalarTower F E BE] [Algebra.IsPushout F E A BE]

variable (F K A B) in
/-- The canonical map `E ⊗_F A → K ⊗_F A` for a tower of fields `F ⊆ E ⊆ K`. -/
noncomputable def pushoutMap : BE →ₐ[F] B :=
  Algebra.pushoutDesc BE ((IsScalarTower.toAlgHom F K B).comp (IsScalarTower.toAlgHom F E K))
    (IsScalarTower.toAlgHom F A B) fun _ _ ↦ mul_comm _ _

@[simp]
theorem pushoutMap_algebraMap_left (e : E) :
    pushoutMap F K A B E BE (algebraMap E BE e) = algebraMap K B (algebraMap E K e) :=
  Algebra.pushoutDesc_left BE _ _ _ e

@[simp]
theorem pushoutMap_algebraMap_right (a : A) :
    pushoutMap F K A B E BE (algebraMap A BE a) = algebraMap A B a :=
  Algebra.pushoutDesc_right BE _ _ _ a

/-- `E ⊗_F A → K ⊗_F A` is injective (`A` is flat over the field `F`). -/
theorem pushoutMap_injective [Algebra.IsPushout F K A B] :
    Function.Injective (pushoutMap F K A B E BE) := by
  have h : ⇑(pushoutMap F K A B E BE) ∘ ⇑(Algebra.IsPushout.equiv F E A BE) =
      ⇑(Algebra.IsPushout.equiv F K A B) ∘
        ⇑((IsScalarTower.toAlgHom F E K).toLinearMap.rTensor A) := by
    funext z
    induction z using TensorProduct.induction_on with
    | zero => simp
    | tmul e a =>
      simp only [Function.comp_apply, Algebra.IsPushout.equiv_tmul, map_mul,
        pushoutMap_algebraMap_left, pushoutMap_algebraMap_right, LinearMap.rTensor_tmul,
        AlgHom.toLinearMap_apply]
      rfl
    | add z₁ z₂ h₁ h₂ => simp only [Function.comp_apply, map_add] at h₁ h₂ ⊢; rw [h₁, h₂]
  have hinj : Function.Injective (⇑(Algebra.IsPushout.equiv F K A B) ∘
      ⇑((IsScalarTower.toAlgHom F E K).toLinearMap.rTensor A)) :=
    (Algebra.IsPushout.equiv F K A B).injective.comp
      (Module.Flat.rTensor_preserves_injective_linearMap _ (algebraMap E K).injective)
  rw [← h] at hinj
  exact hinj.of_comp_right (Algebra.IsPushout.equiv F E A BE).surjective

/-- `E ⊗_F A` is generated as an `F`-algebra by the images of `A` and of `E`. -/
theorem adjoin_range_union_range_eq_top :
    Algebra.adjoin F (Set.range (algebraMap A BE) ∪ Set.range (algebraMap E BE)) = ⊤ := by
  rw [eq_top_iff]
  rintro b -
  obtain ⟨z, rfl⟩ := (Algebra.IsPushout.equiv F E A BE).surjective b
  induction z using TensorProduct.induction_on with
  | zero => simp
  | tmul e a =>
    rw [Algebra.IsPushout.equiv_tmul]
    exact Subalgebra.mul_mem _ (Algebra.subset_adjoin (Or.inr ⟨e, rfl⟩))
      (Algebra.subset_adjoin (Or.inl ⟨a, rfl⟩))
  | add z₁ z₂ h₁ h₂ => rw [map_add]; exact add_mem h₁ h₂

end Descent

end HodgeLefschetz

open HodgeLefschetz

section Main

variable {F K A B L : Type u} [Field F] [Field K] [Algebra F K] [CommRing A] [Algebra F A]
  [Algebra.FiniteType F A] [CommRing B] [Algebra F B] [Algebra A B] [Algebra K B]
  [IsScalarTower F A B] [IsScalarTower F K B] [Algebra.IsPushout F K A B]
  [Field L] [Algebra B L] [IsFractionRing B L] [Algebra K L] [IsScalarTower K B L]

variable (A B) in
include A B in
/-- **A unirational parametrization is defined over a finitely generated subfield**: let `F ⊆ K`
be fields, `A` an `F`-algebra of finite type and `B = K ⊗_F A` (an `Algebra.IsPushout`) with
fraction field `L` (so `B` is a domain), `L` essentially of finite type over `K`. If `L` is
unirational over `K`, there is a finite set `S ⊆ K` such that for every tower of fields
`F → E → K` with `S` in the image of `E` (e.g. an intermediate field containing `S`), the fraction
field `L_E` of `B_E = E ⊗_F A` is unirational over `E`. -/
theorem exists_finset_isUnirational_of_isPushout [Algebra.EssFiniteType K L]
    (h : IsUnirational K L) :
    ∃ S : Finset K, ∀ (E : Type u) [Field E] [Algebra F E] [Algebra E K] [IsScalarTower F E K],
      (S : Set K) ⊆ Set.range (algebraMap E K) →
      ∀ (BE LE : Type u) [CommRing BE] [Algebra F BE] [Algebra A BE] [Algebra E BE]
        [IsScalarTower F A BE] [IsScalarTower F E BE] [Algebra.IsPushout F E A BE] [Field LE]
        [Algebra BE LE] [IsFractionRing BE LE] [Algebra E LE] [IsScalarTower E BE LE],
        IsUnirational E LE := by
  classical
  obtain ⟨σ, _, τ, hfin⟩ := exists_algHom_fractionRing_of_isUnirational h
  have := Fintype.ofFinite σ
  let Kσ := FractionRing (MvPolynomial σ K)
  -- generators of `A` and their images, as fractions of polynomials
  obtain ⟨y, hy⟩ := Algebra.FiniteType.out (R := F) (A := A)
  have hfrac (a : A) : ∃ p q : MvPolynomial σ K, τ (algebraMap B L (algebraMap A B a)) =
      algebraMap _ Kσ p / algebraMap (MvPolynomial σ K) Kσ q := by
    obtain ⟨p, q, -, e⟩ := IsFractionRing.div_surjective (A := MvPolynomial σ K)
      (τ (algebraMap B L (algebraMap A B a)))
    exact ⟨p, q, e.symm⟩
  choose p q hpq using hfrac
  -- integral equations of the variables over `L`
  let _ : Algebra L Kσ := τ.toRingHom.toAlgebra
  have hint (i : σ) : IsIntegral L (algebraMap (MvPolynomial σ K) Kσ (MvPolynomial.X i)) := by
    have : Module.Finite L Kσ := hfin
    exact Algebra.IsIntegral.isIntegral _
  choose P hPm hP using hint
  -- the coefficients as fractions of elements of `B`
  have hcoef (c : L) : ∃ u v : B, c = algebraMap B L u / algebraMap B L v := by
    obtain ⟨u, v, -, e⟩ := IsFractionRing.div_surjective (A := B) c
    exact ⟨u, v, e.symm⟩
  choose u v huv using hcoef
  choose T hT using exists_finset_mem_adjoin (F := F) (K := K) A (B := B)
  -- the finite set
  let S : Finset K := y.biUnion (fun a ↦ (p a).coeffs ∪ (q a).coeffs) ∪
    Finset.univ.biUnion fun i : σ ↦ (Finset.range ((P i).natDegree + 1)).biUnion
      fun n ↦ T (u ((P i).coeff n)) ∪ T (v ((P i).coeff n))
  refine ⟨S, fun E _ _ _ _ hE BE LE _ _ _ _ _ _ _ _ _ _ _ _ ↦ ?_⟩
  have hSE {x : K} (hx : x ∈ S) : x ∈ Set.range (algebraMap E K) := hE hx
  let Eσ := FractionRing (MvPolynomial σ E)
  let φ := pushoutMap F K A B E BE
  have hφ : Function.Injective φ := pushoutMap_injective E BE
  let ι : Eσ →+* Kσ := (ratFuncMap E K σ : Eσ →+* Kσ)
  have hι : Function.Injective ι := (ratFuncMap E K σ).injective
  have hιC (e : E) : ι (algebraMap E Eσ e) = algebraMap K Kσ (algebraMap E K e) := by
    simp only [ι, AlgHom.coe_toRingHom, AlgHom.commutes]
    exact IsScalarTower.algebraMap_apply E K Kσ e
  -- `g : B_E → K(σ)` lands in `E(σ)`
  let g : BE →+* Kσ := (τ : L →+* Kσ).comp ((algebraMap B L).comp (φ : BE →+* B))
  have hgE (e : E) : g (algebraMap E BE e) = algebraMap K Kσ (algebraMap E K e) := by
    simp only [g, φ, RingHom.coe_comp, Function.comp_apply, AlgHom.coe_toRingHom,
      pushoutMap_algebraMap_left, ← IsScalarTower.algebraMap_apply, AlgHom.commutes]
    rfl
  have hgA (a : A) : g (algebraMap A BE a) ∈ ι.range := by
    have hya : a ∈ Algebra.adjoin F (y : Set A) := hy ▸ Algebra.mem_top
    induction hya using Algebra.adjoin_induction with
    | mem a ha =>
      have := mem_range_ratFuncMap_of_coeffs σ E (p a) (q a)
        (fun x hx ↦ hSE (Finset.mem_union_left _ (Finset.mem_biUnion.mpr
          ⟨a, ha, Finset.mem_union_left _ hx⟩)))
        (fun x hx ↦ hSE (Finset.mem_union_left _ (Finset.mem_biUnion.mpr
          ⟨a, ha, Finset.mem_union_right _ hx⟩)))
      obtain ⟨z, hz⟩ := this
      refine ⟨z, ?_⟩
      simp only [g, φ, ι, RingHom.coe_comp, Function.comp_apply, AlgHom.coe_toRingHom,
        pushoutMap_algebraMap_right, hpq, hz]
      rfl
    | algebraMap r =>
      rw [← IsScalarTower.algebraMap_apply, IsScalarTower.algebraMap_apply F E BE, hgE]
      exact ⟨algebraMap E Eσ (algebraMap F E r), hιC _⟩
    | add a b _ _ ha hb => rw [map_add, map_add]; exact add_mem ha hb
    | mul a b _ _ ha hb => rw [map_mul, map_mul]; exact mul_mem ha hb
  have hg (b : BE) : g b ∈ ι.range := by
    have hb : b ∈ Algebra.adjoin F (Set.range (algebraMap A BE) ∪ Set.range (algebraMap E BE)) :=
      (adjoin_range_union_range_eq_top (F := F) (A := A) E BE) ▸ Algebra.mem_top
    induction hb using Algebra.adjoin_induction with
    | mem b hb =>
      rcases hb with ⟨a, rfl⟩ | ⟨e, rfl⟩
      · exact hgA a
      · exact ⟨algebraMap E Eσ e, (hιC e).trans (hgE e).symm⟩
    | algebraMap r =>
      rw [IsScalarTower.algebraMap_apply F E BE, hgE]
      exact ⟨algebraMap E Eσ (algebraMap F E r), hιC _⟩
    | add a b _ _ ha hb => rw [map_add]; exact add_mem ha hb
    | mul a b _ _ ha hb => rw [map_mul]; exact mul_mem ha hb
  -- `θ : B_E → E(σ)` with `ι ∘ θ = g`
  let θ : BE →+* Eσ :=
    (RingEquiv.ofLeftInverse (Function.leftInverse_invFun hι)).symm.toRingHom.comp
      (g.codRestrict ι.range hg)
  have hθ (b : BE) : ι (θ b) = g b := by
    simp only [θ, RingHom.coe_comp, Function.comp_apply, RingEquiv.toRingHom_eq_coe,
      RingEquiv.coe_toRingHom, RingEquiv.ofLeftInverse_symm_apply, RingHom.codRestrict_apply]
    exact Function.invFun_eq (hg b)
  have hg_inj : Function.Injective g :=
    τ.injective.comp ((IsFractionRing.injective B L).comp hφ)
  have hθ_inj : Function.Injective θ := fun b b' hbb' ↦
    hg_inj (by rw [← hθ, ← hθ, hbb'])
  -- `ψ : L_E → E(σ)` and `χ : L_E → L`
  let ψ : LE →+* Eσ := IsFractionRing.lift hθ_inj
  have hψ (b : BE) : ψ (algebraMap BE LE b) = θ b := IsFractionRing.lift_algebraMap _ _
  have hχ_inj : Function.Injective ((algebraMap B L).comp (φ : BE →+* B)) :=
    (IsFractionRing.injective B L).comp hφ
  let χ : LE →+* L := IsFractionRing.lift hχ_inj
  have hχ (b : BE) : χ (algebraMap BE LE b) = algebraMap B L (φ b) :=
    IsFractionRing.lift_algebraMap _ _
  have hιψ : ι.comp ψ = (τ : L →+* Kσ).comp χ := by
    refine IsLocalization.ringHom_ext (nonZeroDivisors BE) (RingHom.ext fun b ↦ ?_)
    simp only [RingHom.coe_comp, Function.comp_apply, hψ, hθ, hχ]
    rfl
  have hψE (e : E) : ψ (algebraMap E LE e) = algebraMap E Eσ e := by
    apply hι
    rw [IsScalarTower.algebraMap_apply E BE LE, hψ, hθ, hgE, hιC]
  -- the integral equations of the variables descend to `L_E`
  let _ : Algebra LE Eσ := ψ.toAlgebra
  let Xσ : σ → Eσ := fun i ↦ algebraMap (MvPolynomial σ E) Eσ (MvPolynomial.X i)
  have hιX (i : σ) : ι (Xσ i) = algebraMap (MvPolynomial σ K) Kσ (MvPolynomial.X i) := by
    exact (ratFuncMap_algebraMap E K σ (MvPolynomial.X i)).trans (polyToRatFunc_X E K σ i)
  have hrangeφ (b : B) (hb : (T b : Set K) ⊆ Set.range (algebraMap E K)) : b ∈ φ.range := by
    refine Algebra.adjoin_le ?_ (hT b)
    rintro _ (⟨a, rfl⟩ | ⟨t, ht, rfl⟩)
    · exact ⟨algebraMap A BE a, pushoutMap_algebraMap_right ..⟩
    · obtain ⟨t', rfl⟩ := hb ht
      exact ⟨algebraMap E BE t', pushoutMap_algebraMap_left ..⟩
  have hTsub (i : σ) (n : ℕ) (hn : n ≤ (P i).natDegree) :
      (T (u ((P i).coeff n)) : Set K) ⊆ Set.range (algebraMap E K) ∧
        (T (v ((P i).coeff n)) : Set K) ⊆ Set.range (algebraMap E K) := by
    have hmem {x : K} (hx : x ∈ T (u ((P i).coeff n)) ∪ T (v ((P i).coeff n))) :
        x ∈ Set.range (algebraMap E K) :=
      hE (Finset.mem_union_right _ (Finset.mem_biUnion.mpr ⟨i, Finset.mem_univ _,
        Finset.mem_biUnion.mpr ⟨n, Finset.mem_range.mpr (Nat.lt_succ_of_le hn), hx⟩⟩))
    exact ⟨fun x hx ↦ hmem (Finset.mem_union_left _ hx),
      fun x hx ↦ hmem (Finset.mem_union_right _ hx)⟩
  have hlift (i : σ) : P i ∈ Polynomial.lifts χ := by
    rw [Polynomial.lifts_iff_coeff_lifts]
    intro n
    by_cases hn : n ≤ (P i).natDegree
    · obtain ⟨hu, hv⟩ := hTsub i n hn
      obtain ⟨u', hu'⟩ := hrangeφ _ hu
      obtain ⟨v', hv'⟩ := hrangeφ _ hv
      refine ⟨algebraMap BE LE u' / algebraMap BE LE v', ?_⟩
      rw [map_div₀, hχ, hχ]
      rw [show φ u' = u ((P i).coeff n) from hu', show φ v' = v ((P i).coeff n) from hv']
      exact (huv _).symm
    · rw [Polynomial.coeff_eq_zero_of_natDegree_lt (not_le.mp hn)]
      exact ⟨0, map_zero _⟩
  have hintE (i : σ) : IsIntegral LE (Xσ i) := by
    obtain ⟨P', hP'map, -, hP'm⟩ :=
      Polynomial.lifts_and_natDegree_eq_and_monic (hlift i) (hPm i)
    refine ⟨P', hP'm, hι ?_⟩
    rw [map_zero, Polynomial.hom_eval₂]
    have e1 : ι.comp (algebraMap LE Eσ) = (τ : L →+* Kσ).comp χ := hιψ
    rw [e1, ← Polynomial.eval₂_map, hP'map, hιX]
    exact hP i
  -- `E(σ)` is generated over `L_E` by the variables, hence finite over `L_E`
  let SX : Set Eσ := Set.range Xσ
  have hEtop : IntermediateField.adjoin LE SX = ⊤ := by
    have h := eq_top_of_algebraMap_mem E σ (IntermediateField.adjoin LE SX).toSubfield
      (fun c ↦ by
        have : algebraMap E Eσ c = algebraMap LE Eσ (algebraMap E LE c) := (hψE c).symm
        rw [this]
        exact IntermediateField.algebraMap_mem _ _)
      (fun i ↦ IntermediateField.subset_adjoin LE _ ⟨i, rfl⟩)
    refine eq_top_iff.mpr fun z _ ↦ ?_
    have hz : z ∈ (IntermediateField.adjoin LE SX).toSubfield := h ▸ Subfield.mem_top z
    exact hz
  have hSX : FiniteDimensional LE (IntermediateField.adjoin LE SX) :=
    IntermediateField.finiteDimensional_adjoin fun _ ⟨i, hi⟩ ↦ hi ▸ hintE i
  rw [hEtop] at hSX
  have hfin' : FiniteDimensional LE Eσ :=
    LinearEquiv.finiteDimensional (IntermediateField.topEquiv (F := LE) (E := Eσ)).toLinearEquiv
  -- conclusion
  refine ⟨Eσ, inferInstance, ψ.toAlgebra, hfin', ?_⟩
  have e : (ψ.comp (algebraMap E LE)).toAlgebra = (inferInstance : Algebra E Eσ) :=
    Algebra.algebra_ext _ _ fun c ↦ hψE c
  change @IsPurelyTranscendental E Eσ _ _ (ψ.comp (algebraMap E LE)).toAlgebra
  rw [e]
  exact isPurelyTranscendental_fractionRing E σ

end Main

end SGA.SGA1.ExposeXI
