/-
Copyright (c) 2026 SGAenglishpluslean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SGAenglishpluslean contributors
-/
import SGA.SGA1.ExposeVIII.AffineHomDescent
import SGA.SGA1.ExposeXI.AffineSheaves

/-!
# SGA 1, Exposé XI.4: representability of fpqc sheaves by descent of affine schemes

SGA uses VIII.2.1 (faithfully flat quasi-compact morphisms are effective descent morphisms for
affine schemes) to show that objects defined locally for the fpqc topology, such as the
associated bundles of XI.4 and the torsors of footnote 296, are representable when they are
locally represented by affine schemes. We formalize this for fpqc sheaves `F` on the category
of `S`-schemes.

* `RepresentsOver F f u`: for a morphism `f : X ⟶ V` of `S`-schemes, the section `u ∈ F(X)`
  represents the restriction of `F` to `S`-schemes over `V`.
* `RepresentsOver.descend`: if `g : S' ⟶ V` is faithfully flat and quasi-compact and the
  restriction of `F` to `S`-schemes over `S'` is represented by `X'` affine over `S'`, then the
  restriction of `F` to `S`-schemes over `V` is represented by some `X` affine over `V`, with
  `X' ≅ X ×_V S'`. The proof builds the descent datum on `X'` given by the representability,
  applies VIII.2.1 (`DescentDatum.isEffective_of_isAffineHom`), and descends the universal
  section along the faithfully flat `X' ⟶ X`.
-/

universe u

open CategoryTheory Limits Opposite AlgebraicGeometry MorphismProperty

namespace SGA.SGA1.ExposeXI

variable {S : Scheme.{u}}

section Represents

variable (F : (Over S)ᵒᵖ ⥤ Type u)

/-- The section `u ∈ F(X)`, for a morphism `f : X ⟶ V` of `S`-schemes, represents the
restriction of `F` to `S`-schemes over `V`: for every `S`-scheme `Z` with a morphism
`t : Z ⟶ V`, the `V`-morphisms `Z ⟶ X` correspond to the sections of `F` over `Z` by
`φ ↦ φ^* u`. -/
def RepresentsOver {V X : Over S} (f : X ⟶ V) (u : F.obj (op X)) : Prop :=
  ∀ ⦃Z : Over S⦄ (t : Z ⟶ V),
    Function.Bijective fun φ : {φ : Z ⟶ X // φ ≫ f = t} ↦ F.map φ.1.op u

variable {F}

namespace RepresentsOver

variable {V X : Over S} {f : X ⟶ V} {u : F.obj (op X)} (h : RepresentsOver F f u)
include h

lemma ext {Z : Over S} {φ ψ : Z ⟶ X} (e : φ ≫ f = ψ ≫ f)
    (e' : F.map φ.op u = F.map ψ.op u) : φ = ψ :=
  congrArg Subtype.val (@(h (φ ≫ f)).1 ⟨φ, rfl⟩ ⟨ψ, e.symm⟩ e')

lemma exists_eq {Z : Over S} (t : Z ⟶ V) (s : F.obj (op Z)) :
    ∃ φ : Z ⟶ X, φ ≫ f = t ∧ F.map φ.op u = s := by
  obtain ⟨⟨φ, hφ⟩, hs⟩ := (h t).2 s
  exact ⟨φ, hφ, hs⟩

end RepresentsOver

lemma map_comp_op_apply {A B C : Over S} (φ : A ⟶ B) (ψ : B ⟶ C) (x : F.obj (op C)) :
    F.map (φ ≫ ψ).op x = F.map φ.op (F.map ψ.op x) := by
  rw [op_comp, Functor.map_comp_apply]

/-- The sieve generated by a faithfully flat quasi-compact morphism is an fpqc covering. -/
lemma generate_singleton_mem_fpqc {T Y : Over S} (g : T ⟶ Y) [Flat g.left] [Surjective g.left]
    [QuasiCompact g.left] : Sieve.generate (Presieve.singleton g) ∈ fpqc S Y := by
  rw [GrothendieckTopology.mem_over_iff]
  refine GrothendieckTopology.superset_covering _ ?_ (Precoverage.generate_mem_toGrothendieck
    (Scheme.Hom.singleton_mem_fpqcPrecoverage g.left))
  rintro W w ⟨_, c, _, ⟨⟩, rfl⟩
  rw [Sieve.overEquiv_iff]
  exact ⟨T, CategoryTheory.Over.homMk c (by simp), g, Presieve.singleton.mk, rfl⟩

variable (hF : Presieve.IsSheaf (fpqc S) F)
include hF

/-- An fpqc sheaf is separated for a faithfully flat quasi-compact morphism. -/
lemma eq_of_map_eq_of_fpqc {T Y : Over S} (g : T ⟶ Y) [Flat g.left] [Surjective g.left]
    [QuasiCompact g.left] {y₁ y₂ : F.obj (op Y)} (e : F.map g.op y₁ = F.map g.op y₂) :
    y₁ = y₂ :=
  (hF _ (generate_singleton_mem_fpqc g)).isSeparatedFor.ext fun _ _ ⟨_, c, _, ⟨⟩, hc⟩ ↦ by
    rw [← hc, map_comp_op_apply, map_comp_op_apply, e]

set_option backward.isDefEq.respectTransparency.types false in
/-- XI.4 (VIII.2.1 for representable sheaves): let `g : S' ⟶ V` be a faithfully flat
quasi-compact morphism of `S`-schemes. If the restriction of an fpqc sheaf `F` to `S`-schemes
over `S'` is represented by an `S'`-scheme `X'` affine over `S'`, then the restriction of `F` to
`S`-schemes over `V` is represented by an `S`-scheme `X` affine over `V`, and `X' = X ×_V S'`. -/
theorem RepresentsOver.descend {V S' X' : Over S} (g : S' ⟶ V) [Surjective g.left]
    [Flat g.left] [QuasiCompact g.left] {a : X' ⟶ S'} [IsAffineHom a.left]
    {u' : F.obj (op X')} (h : RepresentsOver F a u') :
    ∃ (X : Over S) (f : X ⟶ V) (u : F.obj (op X)) (k : X' ⟶ X), IsAffineHom f.left ∧
      RepresentsOver F f u ∧ IsPullback k.left a.left f.left g.left ∧ F.map k.op u = u' := by
  -- The descent datum `q₁, q₂ : X'' ⇉ X'` over `S' ×_V S' ⇉ S'`.
  let p₁ := pullback.fst g.left g.left
  let p₂ := pullback.snd g.left g.left
  let X'' := pullback a.left p₁
  let q₁ : X'' ⟶ X'.left := pullback.fst a.left p₁
  let b : X'' ⟶ pullback g.left g.left := pullback.snd a.left p₁
  have hga : g.left ≫ V.hom = S'.hom := Over.w g
  have haS : a.left ≫ S'.hom = X'.hom := Over.w a
  have hq₁b : q₁ ≫ a.left = b ≫ p₁ := pullback.condition
  have hp : p₁ ≫ g.left = p₂ ≫ g.left := pullback.condition
  have hb' : b ≫ p₂ ≫ S'.hom = q₁ ≫ a.left ≫ S'.hom := by
    rw [← hga, ← reassoc_of% hp, reassoc_of% hq₁b]
  have hb : (b ≫ p₂) ≫ S'.hom = q₁ ≫ X'.hom := by
    rw [Category.assoc, hb', haS]
  let X''ₒ : Over S := Over.mk (q₁ ≫ X'.hom)
  let q₁ₒ : X''ₒ ⟶ X' := CategoryTheory.Over.homMk q₁ rfl
  obtain ⟨q₂ₒ, hq₂a, hq₂u⟩ := h.exists_eq (CategoryTheory.Over.homMk (U := X''ₒ) (b ≫ p₂) hb) (F.map q₁ₒ.op u')
  let q₂ : X'' ⟶ X'.left := q₂ₒ.left
  have hq₂ : q₂ ≫ a.left = b ≫ p₂ := by
    simpa using congrArg CommaMorphism.left hq₂a
  -- Two morphisms to `X'` over `S'` with the same inverse image of `u'` agree.
  have uniq : ∀ {T : Scheme.{u}} (z : T ⟶ S) (x y : T ⟶ X'.left) (hx : x ≫ X'.hom = z)
      (hy : y ≫ X'.hom = z), x ≫ a.left = y ≫ a.left →
      F.map (CategoryTheory.Over.homMk (U := Over.mk z) (V := X') x hx).op u' =
        F.map (CategoryTheory.Over.homMk (U := Over.mk z) (V := X') y hy).op u' → x = y :=
    fun z x y hx hy e e' ↦ congrArg CommaMorphism.left
      (h.ext (Over.OverMorphism.ext (by simpa using e)) e')
  -- The inverse images of `u'` by `q₁` and `q₂` agree.
  have key : ∀ {T : Scheme.{u}} (z : T ⟶ S) (r : T ⟶ X'') (h₁ : (r ≫ q₁) ≫ X'.hom = z)
      (h₂ : (r ≫ q₂) ≫ X'.hom = z),
      F.map (CategoryTheory.Over.homMk (U := Over.mk z) (V := X') (r ≫ q₂) h₂).op u' =
        F.map (CategoryTheory.Over.homMk (U := Over.mk z) (V := X') (r ≫ q₁) h₁).op u' := by
    intro T z r h₁ h₂
    have hr : r ≫ X''ₒ.hom = (Over.mk z).hom := by
      change r ≫ q₁ ≫ X'.hom = z
      rw [← h₁, Category.assoc]
    have e₂ : CategoryTheory.Over.homMk (U := Over.mk z) (V := X') (r ≫ q₂) h₂ =
        CategoryTheory.Over.homMk (U := Over.mk z) (V := X''ₒ) r hr ≫ q₂ₒ := by
      ext; simp [q₂]
    have e₁ : CategoryTheory.Over.homMk (U := Over.mk z) (V := X') (r ≫ q₁) h₁ =
        CategoryTheory.Over.homMk (U := Over.mk z) (V := X''ₒ) r hr ≫ q₁ₒ := by
      ext; simp [q₁ₒ]
    rw [e₂, e₁, map_comp_op_apply, map_comp_op_apply, hq₂u]
  -- `q₂` is characterized by these two properties.
  have char : ∀ {T : Scheme.{u}} (z : T ⟶ S) (r : T ⟶ X'') (y : T ⟶ X'.left)
      (h₁ : (r ≫ q₁) ≫ X'.hom = z) (hy : y ≫ X'.hom = z), y ≫ a.left = r ≫ b ≫ p₂ →
      F.map (CategoryTheory.Over.homMk (U := Over.mk z) (V := X') y hy).op u' =
        F.map (CategoryTheory.Over.homMk (U := Over.mk z) (V := X') (r ≫ q₁) h₁).op u' → r ≫ q₂ = y := by
    intro T z r y h₁ hy e e'
    have h₂ : (r ≫ q₂) ≫ X'.hom = z := by
      rw [← h₁, ← haS]
      simp only [Category.assoc]
      rw [reassoc_of% hq₂, hb']
    exact uniq z _ _ h₂ hy (by rw [Category.assoc, hq₂, e]) ((key z r h₁ h₂).trans e'.symm)
  -- The universal property of the square `q₂, b` (so `q₂` is a base change of `a` along `p₂`).
  have hlift : ∀ {T : Scheme.{u}} (x : T ⟶ X'.left) (c : T ⟶ pullback g.left g.left),
      x ≫ a.left = c ≫ p₂ → ∃ r : T ⟶ X'', r ≫ q₂ = x ∧ r ≫ b = c ∧
        ∀ r' : T ⟶ X'', r' ≫ q₂ = x → r' ≫ b = c → r' = r := by
    intro T x c e
    have hc : (c ≫ p₁) ≫ S'.hom = x ≫ X'.hom := by
      rw [← haS, ← hga]
      simp only [Category.assoc]
      rw [reassoc_of% hp, reassoc_of% e]
    obtain ⟨y, hya, hyu⟩ := h.exists_eq (CategoryTheory.Over.homMk (U := Over.mk (x ≫ X'.hom)) (c ≫ p₁) hc)
      (F.map (CategoryTheory.Over.homMk (U := Over.mk (x ≫ X'.hom)) (V := X') x rfl).op u')
    have hya' : y.left ≫ a.left = c ≫ p₁ := by simpa using congrArg CommaMorphism.left hya
    have hy : y.left ≫ X'.hom = x ≫ X'.hom := Over.w y
    have hy₀ : CategoryTheory.Over.homMk (U := Over.mk (x ≫ X'.hom)) (V := X') y.left hy = y := by ext; rfl
    let r := pullback.lift y.left c hya'
    have hr₁ : r ≫ q₁ = y.left := pullback.lift_fst _ _ _
    have hr₂ : r ≫ b = c := pullback.lift_snd _ _ _
    refine ⟨r, ?_, hr₂, fun r' h₂ hb₂ ↦ ?_⟩
    · have hy' : CategoryTheory.Over.homMk (U := Over.mk (x ≫ X'.hom)) (V := X') (r ≫ q₁)
          (by rw [hr₁, hy]; rfl) = y := by ext; simp [hr₁]
      exact char (x ≫ X'.hom) r x (by rw [hr₁, hy]) rfl (by rw [reassoc_of% hr₂, e])
        (by rw [hy', hyu])
    · have h₁ : (r' ≫ q₁) ≫ X'.hom = x ≫ X'.hom := by
        rw [← hc, ← haS]
        simp only [Category.assoc]
        rw [reassoc_of% hq₁b, reassoc_of% hb₂]
      have h₂' : (r' ≫ q₂) ≫ X'.hom = x ≫ X'.hom := by rw [h₂]
      have e₁ : r' ≫ q₁ = y.left := by
        refine uniq (x ≫ X'.hom) _ _ h₁ hy (by rw [Category.assoc, hq₁b, reassoc_of% hb₂, hya'])
          ?_
        rw [← key (x ≫ X'.hom) r' h₁ h₂', hy₀, hyu]
        congr 2
        ext
        simp [h₂]
      exact pullback.hom_ext (e₁.trans hr₁.symm) (hb₂.trans hr₂.symm)
  have isPullback₂ : IsPullback q₂ b a.left p₂ :=
    IsPullback.of_isLimit (c := PullbackCone.mk q₂ b hq₂) (PullbackCone.IsLimit.mk hq₂
      (fun s ↦ (hlift s.fst s.snd s.condition).choose)
      (fun s ↦ (hlift s.fst s.snd s.condition).choose_spec.1)
      (fun s ↦ (hlift s.fst s.snd s.condition).choose_spec.2.1)
      (fun s m h₁ h₂ ↦ (hlift s.fst s.snd s.condition).choose_spec.2.2 m h₁ h₂))
  have refl : ∀ ⦃T : Scheme.{u}⦄ (x : T ⟶ X'.left), ∃ r : T ⟶ X'', r ≫ q₁ = x ∧ r ≫ q₂ = x := by
    intro T x
    let r := pullback.lift (f := a.left) (g := p₁) x (x ≫ a.left ≫ pullback.diagonal g.left)
      (by simp [p₁])
    have hr₁ : r ≫ q₁ = x := pullback.lift_fst _ _ _
    have hr₂ : r ≫ b = x ≫ a.left ≫ pullback.diagonal g.left := pullback.lift_snd _ _ _
    refine ⟨r, hr₁, char (x ≫ X'.hom) r x (by rw [hr₁]) rfl (by rw [reassoc_of% hr₂]; simp [p₂]) ?_⟩
    congr 2
    ext
    simp [hr₁]
  have trans : ∀ ⦃T : Scheme.{u}⦄ (r r' : T ⟶ X''), r ≫ q₂ = r' ≫ q₁ →
      ∃ r'' : T ⟶ X'', r'' ≫ q₁ = r ≫ q₁ ∧ r'' ≫ q₂ = r' ≫ q₂ := by
    intro T r r' e
    have hc : (r ≫ b ≫ p₁) ≫ g.left = (r' ≫ b ≫ p₂) ≫ g.left := by
      simp only [Category.assoc]
      rw [hp, ← reassoc_of% hq₂, reassoc_of% e, reassoc_of% hq₁b, hp, reassoc_of% hq₂]
    let c := pullback.lift _ _ hc
    let r'' := pullback.lift (f := a.left) (g := p₁) (r ≫ q₁) c (by
      rw [Category.assoc, hq₁b]
      exact (pullback.lift_fst _ _ _).symm)
    have hr₁ : r'' ≫ q₁ = r ≫ q₁ := pullback.lift_fst _ _ _
    have hr₂ : r'' ≫ b = c := pullback.lift_snd _ _ _
    have hq₁₂ : q₂ ≫ X'.hom = q₁ ≫ X'.hom := by rw [← haS, reassoc_of% hq₂, hb']
    have hz₁ : (r' ≫ q₁) ≫ X'.hom = (r ≫ q₁) ≫ X'.hom := by
      rw [← e, Category.assoc, Category.assoc, hq₁₂]
    have hz₂ : (r' ≫ q₂) ≫ X'.hom = (r ≫ q₁) ≫ X'.hom := by
      rw [Category.assoc, hq₁₂, ← Category.assoc, hz₁]
    have hz₃ : (r ≫ q₂) ≫ X'.hom = (r ≫ q₁) ≫ X'.hom := by
      rw [Category.assoc, hq₁₂, Category.assoc]
    refine ⟨r'', hr₁, char ((r ≫ q₁) ≫ X'.hom) r'' (r' ≫ q₂) (by rw [hr₁]) hz₂ ?_ ?_⟩
    · rw [Category.assoc, hq₂, reassoc_of% hr₂]
      exact (pullback.lift_snd _ _ _).symm
    · rw [key _ r' hz₁ hz₂]
      have e₁ : CategoryTheory.Over.homMk (U := Over.mk ((r ≫ q₁) ≫ X'.hom)) (V := X') (r' ≫ q₁) hz₁ =
          CategoryTheory.Over.homMk (r ≫ q₂) hz₃ := by ext; exact e.symm
      have e₂ : CategoryTheory.Over.homMk (U := Over.mk ((r ≫ q₁) ≫ X'.hom)) (V := X') (r'' ≫ q₁)
          (by rw [hr₁]; rfl) = CategoryTheory.Over.homMk (r ≫ q₁) rfl := by ext; exact hr₁
      rw [e₁, key _ r rfl hz₃, e₂]
  -- VIII.2.1: the descent datum is effective.
  let D : ExposeVIII.DescentDatum g.left :=
    { X' := X'.left, a := a.left, X'' := X'', b := b, q₁ := q₁, q₂ := q₂,
      isPullback₁ := IsPullback.of_hasPullback a.left p₁, isPullback₂ := isPullback₂,
      refl := refl,
      symm := ExposeVIII.symm_of_refl_of_trans (IsPullback.of_hasPullback a.left p₁) isPullback₂
        refl trans,
      trans := trans }
  have : IsAffineHom D.a := ‹IsAffineHom a.left›
  obtain ⟨X₀, f₀, k₀, hpb, hk⟩ := D.isEffective_of_isAffineHom
  have hq : IsPullback q₁ q₂ k₀ k₀ := D.isPullback_q₁_q₂ hpb hk
  have hk₀f : k₀ ≫ f₀ = a.left ≫ g.left := hpb.w
  have hfpqc : (@Surjective ⊓ @Flat ⊓ @QuasiCompact : MorphismProperty Scheme.{u}) k₀ :=
    MorphismProperty.of_isPullback hpb.flip ⟨⟨‹_›, ‹_›⟩, ‹_›⟩
  have : Surjective k₀ := hfpqc.1.1
  have : Flat k₀ := hfpqc.1.2
  have : QuasiCompact k₀ := hfpqc.2
  have haff : IsAffineHom f₀ := of_isPullback_of_descendsAlong (P := @IsAffineHom)
    (Q := @Surjective ⊓ @Flat ⊓ @QuasiCompact) hpb.flip ⟨⟨‹_›, ‹_›⟩, ‹_›⟩ ‹IsAffineHom a.left›
  let X : Over S := Over.mk (f₀ ≫ V.hom)
  let f : X ⟶ V := CategoryTheory.Over.homMk f₀ rfl
  let k : X' ⟶ X := CategoryTheory.Over.homMk k₀ (by
    change k₀ ≫ f₀ ≫ V.hom = X'.hom
    rw [reassoc_of% hk₀f, hga, haS])
  have : Surjective k.left := ‹Surjective k₀›
  have : Flat k.left := ‹Flat k₀›
  have : QuasiCompact k.left := ‹QuasiCompact k₀›
  -- The universal section descends to `X`.
  obtain ⟨u, hu⟩ := exists_descend_of_fpqc hF k u' fun Z φ ψ e ↦ by
    have e' : φ.left ≫ k₀ = ψ.left ≫ k₀ := by simpa [k] using congrArg CommaMorphism.left e
    let r := hq.lift φ.left ψ.left e'
    have hr : r ≫ X''ₒ.hom = Z.hom := by
      change r ≫ q₁ ≫ X'.hom = Z.hom
      rw [hq.lift_fst_assoc, Over.w φ]
    have e₁ : φ = CategoryTheory.Over.homMk r hr ≫ q₁ₒ := by ext; simp [q₁ₒ, r]
    have e₂ : ψ = CategoryTheory.Over.homMk r hr ≫ q₂ₒ := by
      ext
      exact (hq.lift_snd φ.left ψ.left e').symm
    rw [e₁, e₂, map_comp_op_apply, map_comp_op_apply, hq₂u]
  have hX'k : ∀ {T : Scheme.{u}} (y : T ⟶ X'.left), y ≫ X'.hom = (y ≫ k₀) ≫ X.hom := by
    intro T y
    rw [Category.assoc]
    exact congrArg (y ≫ ·) (Over.w k).symm
  -- Injectivity.
  have hinj : ∀ ⦃Z : Over S⦄ (φ ψ : Z ⟶ X), φ ≫ f = ψ ≫ f →
      F.map φ.op u = F.map ψ.op u → φ = ψ := by
    intro Z φ ψ e e'
    have ef : φ.left ≫ f₀ = ψ.left ≫ f₀ := by simpa [f] using congrArg CommaMorphism.left e
    let π := pullback.fst (φ.left ≫ f₀) g.left
    let t' := pullback.snd (φ.left ≫ f₀) g.left
    have hπ : (@Surjective ⊓ @Flat ⊓ @QuasiCompact : MorphismProperty Scheme.{u}) π :=
      MorphismProperty.pullback_fst _ _ ⟨⟨‹_›, ‹_›⟩, ‹_›⟩
    have : Surjective π := hπ.1.1
    have : Flat π := hπ.1.2
    have : QuasiCompact π := hπ.2
    have hφ : (π ≫ φ.left) ≫ f₀ = t' ≫ g.left := by
      rw [Category.assoc]
      exact pullback.condition
    have hψ : (π ≫ ψ.left) ≫ f₀ = t' ≫ g.left := by
      rw [Category.assoc, ← ef]
      exact pullback.condition
    let φ' := hpb.lift (π ≫ φ.left) t' hφ
    let ψ' := hpb.lift (π ≫ ψ.left) t' hψ
    have hφZ : φ' ≫ X'.hom = π ≫ Z.hom := by
      rw [hX'k, hpb.lift_fst, Category.assoc, Over.w φ]
    have hψZ : ψ' ≫ X'.hom = π ≫ Z.hom := by
      rw [hX'k, hpb.lift_fst, Category.assoc, Over.w ψ]
    let πₒ : Over.mk (π ≫ Z.hom) ⟶ Z := CategoryTheory.Over.homMk π rfl
    have hφk : CategoryTheory.Over.homMk (U := Over.mk (π ≫ Z.hom)) (V := X') φ' hφZ ≫ k = πₒ ≫ φ := by
      ext
      exact hpb.lift_fst _ _ _
    have hψk : CategoryTheory.Over.homMk (U := Over.mk (π ≫ Z.hom)) (V := X') ψ' hψZ ≫ k = πₒ ≫ ψ := by
      ext
      exact hpb.lift_fst _ _ _
    have hφψ : φ' = ψ' := uniq (π ≫ Z.hom) φ' ψ' hφZ hψZ
      (by rw [hpb.lift_snd, hpb.lift_snd]) (by
        rw [← hu, ← map_comp_op_apply, ← map_comp_op_apply, hφk, hψk, map_comp_op_apply,
          map_comp_op_apply, e'])
    ext
    rw [← cancel_epi π, ← hpb.lift_fst (π ≫ φ.left) t' hφ, ← hpb.lift_fst (π ≫ ψ.left) t' hψ]
    exact congrArg (· ≫ k₀) hφψ
  refine ⟨X, f, u, k, haff, ?_, hpb, hu⟩
  intro Z t
  refine ⟨fun φ ψ e ↦ Subtype.ext (hinj φ.1 ψ.1 (φ.2.trans ψ.2.symm) e), fun s ↦ ?_⟩
  -- Surjectivity.
  let π := pullback.fst t.left g.left
  let t' := pullback.snd t.left g.left
  have hπ : (@Surjective ⊓ @Flat ⊓ @QuasiCompact : MorphismProperty Scheme.{u}) π :=
    MorphismProperty.pullback_fst _ _ ⟨⟨‹_›, ‹_›⟩, ‹_›⟩
  have : Surjective π := hπ.1.1
  have : Flat π := hπ.1.2
  have : QuasiCompact π := hπ.2
  let Z' : Over S := Over.mk (π ≫ Z.hom)
  let πₒ : Z' ⟶ Z := CategoryTheory.Over.homMk π rfl
  have : Surjective πₒ.left := ‹Surjective π›
  have : Flat πₒ.left := ‹Flat π›
  have : QuasiCompact πₒ.left := ‹QuasiCompact π›
  have hπt : π ≫ t.left = t' ≫ g.left := pullback.condition
  have ht' : t' ≫ S'.hom = Z'.hom := by
    change t' ≫ S'.hom = π ≫ Z.hom
    rw [← hga, ← reassoc_of% hπt, Over.w t]
  obtain ⟨x, hxa, hxu⟩ := h.exists_eq (CategoryTheory.Over.homMk (U := Z') t' ht') (F.map πₒ.op s)
  have hxa' : x.left ≫ a.left = t' := by simpa using congrArg CommaMorphism.left hxa
  obtain ⟨y, hydef⟩ : ∃ y, x.left ≫ k₀ = y := ⟨_, rfl⟩
  have hy : y ≫ f₀ = π ≫ t.left := by
    rw [← hydef, Category.assoc, hk₀f, reassoc_of% hxa', hπt]
  have hyX : y ≫ X.hom = π ≫ Z.hom := by
    rw [← hydef, ← hX'k]
    exact Over.w x
  have hdesc : ∀ {T : Scheme.{u}} (α β : T ⟶ Z'.left), α ≫ π = β ≫ π → α ≫ y = β ≫ y := by
    intro T α β e
    have hα : (α ≫ y) ≫ X.hom = α ≫ π ≫ Z.hom := by rw [Category.assoc, hyX]
    have hβ : (β ≫ y) ≫ X.hom = α ≫ π ≫ Z.hom := by rw [Category.assoc, hyX, reassoc_of% e]
    have hα' : α ≫ Z'.hom = α ≫ π ≫ Z.hom := rfl
    have hβ' : β ≫ Z'.hom = α ≫ π ≫ Z.hom := by
      change β ≫ π ≫ Z.hom = _
      rw [reassoc_of% e]
    have eα : CategoryTheory.Over.homMk (U := Over.mk (α ≫ π ≫ Z.hom)) (V := X) (α ≫ y) hα =
        CategoryTheory.Over.homMk (U := Over.mk (α ≫ π ≫ Z.hom)) (V := Z') α hα' ≫ x ≫ k := by
      ext; simp [← hydef, k]
    have eβ : CategoryTheory.Over.homMk (U := Over.mk (α ≫ π ≫ Z.hom)) (V := X) (β ≫ y) hβ =
        CategoryTheory.Over.homMk (U := Over.mk (α ≫ π ≫ Z.hom)) (V := Z') β hβ' ≫ x ≫ k := by
      ext; simp [← hydef, k]
    have eπ : CategoryTheory.Over.homMk (U := Over.mk (α ≫ π ≫ Z.hom)) (V := Z') α hα' ≫ πₒ =
        CategoryTheory.Over.homMk (U := Over.mk (α ≫ π ≫ Z.hom)) (V := Z') β hβ' ≫ πₒ := by
      ext; exact e
    have hf : CategoryTheory.Over.homMk (U := Over.mk (α ≫ π ≫ Z.hom)) (V := X) (α ≫ y) hα ≫ f =
        CategoryTheory.Over.homMk (U := Over.mk (α ≫ π ≫ Z.hom)) (V := X) (β ≫ y) hβ ≫ f := by
      ext
      change (α ≫ y) ≫ f₀ = (β ≫ y) ≫ f₀
      rw [Category.assoc, Category.assoc, hy, reassoc_of% e]
    have hu' : F.map (CategoryTheory.Over.homMk (U := Over.mk (α ≫ π ≫ Z.hom)) (V := X)
        (α ≫ y) hα).op u = F.map (CategoryTheory.Over.homMk (U := Over.mk (α ≫ π ≫ Z.hom))
        (V := X) (β ≫ y) hβ).op u := by
      rw [eα, eβ, map_comp_op_apply, map_comp_op_apply, map_comp_op_apply, map_comp_op_apply, hu,
        hxu, ← map_comp_op_apply, ← map_comp_op_apply, eπ]
    exact congrArg CommaMorphism.left (hinj _ _ hf hu')
  let φ₀ := EffectiveEpi.desc π y hdesc
  have hφ₀ : π ≫ φ₀ = y := EffectiveEpi.fac π y hdesc
  have hφ₀f : φ₀ ≫ f₀ = t.left := by rw [← cancel_epi π, reassoc_of% hφ₀, hy]
  let φ : Z ⟶ X := CategoryTheory.Over.homMk φ₀ (by
    change φ₀ ≫ f₀ ≫ V.hom = Z.hom
    rw [reassoc_of% hφ₀f, Over.w t])
  refine ⟨⟨φ, by ext; exact hφ₀f⟩, ?_⟩
  apply eq_of_map_eq_of_fpqc hF πₒ
  have hπφ : πₒ ≫ φ = x ≫ k := by ext; exact hφ₀.trans hydef.symm
  change F.map πₒ.op (F.map φ.op u) = _
  rw [← map_comp_op_apply, hπφ, map_comp_op_apply, hu, hxu]

end Represents

section Representable

variable {F : (Over S)ᵒᵖ ⥤ Type u}

open MonoidalCategory CartesianMonoidalCategory in
/-- A representation over the final `S`-scheme `S` is a representation of `F`. -/
noncomputable def RepresentsOver.representableBy {X : Over S} {f : X ⟶ 𝟙_ (Over S)}
    {u : F.obj (op X)} (h : RepresentsOver F f u) : F.RepresentableBy X where
  homEquiv {Z} := Equiv.ofBijective (fun φ ↦ F.map φ.op u)
    ⟨fun _ _ e ↦ h.ext (toUnit_unique _ _) e,
      fun s ↦ (h.exists_eq (toUnit Z) s).imp fun _ hφ ↦ hφ.2⟩
  homEquiv_comp g φ := map_comp_op_apply g φ u

end Representable

section Torsor

open MonoidalCategory CartesianMonoidalCategory MonObj

variable {G : Over S} [GrpObj G] (T : Torsor (fpqc S) (yonedaGrpObj G))

/-- A section `p` of a `G`-torsor `T` over `S'` identifies `T` over `S'` with `G ×_S S'`: the
section `pr₁ • pr₂^* p` of `T` over `G ×_S S'` represents `T` on `S'`-schemes. -/
theorem representsOver_smul {S' : Over S} (p : T.obj.obj (op S')) :
    RepresentsOver T.obj (snd G S') (T.smul (op (G ⊗ S')) (fst G S') (T.obj.map (snd G S').op p)) := by
  intro Z t
  have key : ∀ φ : Z ⟶ G ⊗ S', T.obj.map φ.op (T.smul (op (G ⊗ S')) (fst G S')
      (T.obj.map (snd G S').op p)) = T.smul (op Z) (φ ≫ fst G S') (T.obj.map (φ ≫ snd G S').op p) := by
    intro φ
    refine (T.map_smul φ.op _ _).trans ?_
    rw [map_comp_op_apply]
    rfl
  constructor
  · rintro ⟨φ, hφ⟩ ⟨ψ, hψ⟩ e
    change T.obj.map φ.op _ = T.obj.map ψ.op _ at e
    rw [key, key, hφ, hψ] at e
    exact Subtype.ext (CartesianMonoidalCategory.hom_ext _ _ (T.smul_left_injective _ e)
      (hφ.trans hψ.symm))
  · intro s
    obtain ⟨c, hc⟩ := (T.existsUnique_smul' (T.obj.map t.op p) s).exists
    refine ⟨⟨lift c t, lift_snd _ _⟩, ?_⟩
    change T.obj.map (lift c t).op _ = s
    rw [key]
    have e₂ : lift c t ≫ snd G S' = t := lift_snd c t
    rw [e₂]
    exact (congrArg (fun x : Z ⟶ G ↦ T.smul (op Z) x (T.obj.map t.op p)) (lift_fst c t)).trans hc

variable {T} {X : Over S} (e : T.obj.RepresentableBy X)

/-- The action of `G` on an `S`-scheme `X` representing a `G`-torsor `T`: the morphism
`G ×_S X ⟶ X` corresponding to the section `pr₁ • pr₂^* x` of `T`, where `x` is the universal
section over `X`. -/
noncomputable def torsorSMul : G ⊗ X ⟶ X :=
  e.homEquiv.symm (T.smul (op (G ⊗ X)) (fst G X) (e.homEquiv (snd G X)))

lemma homEquiv_lift_torsorSMul {Z : Over S} (m : Z ⟶ G) (x : Z ⟶ X) :
    e.homEquiv (lift m x ≫ torsorSMul e) = T.smul (op Z) m (e.homEquiv x) := by
  rw [e.homEquiv_comp, torsorSMul, Equiv.apply_symm_apply]
  refine (T.map_smul (lift m x).op _ _).trans ?_
  rw [← e.homEquiv_comp, lift_snd]
  exact congrArg (fun y : Z ⟶ G ↦ T.smul (op Z) y (e.homEquiv x)) (lift_fst m x)

/-- The action of `G` on an `S`-scheme representing a `G`-torsor. -/
@[instance_reducible]
noncomputable def modObjOfRepresentableBy : ModObj G X where
  smul := torsorSMul e
  one_smul := by
    change η[G] ▷ X ≫ torsorSMul e = (λ_ X).hom
    have h₁ : η[G] ▷ X = lift (fst _ _ ≫ η[G]) (snd _ _) := by ext <;> simp
    apply e.homEquiv.injective
    rw [h₁, homEquiv_lift_torsorSMul, leftUnitor_hom]
    have h₂ : fst (𝟙_ (Over S)) X ≫ η[G] = 1 := by
      rw [Hom.one_def]
      exact congrArg (· ≫ η[G]) (toUnit_unique _ _)
    exact (congrArg (fun y : 𝟙_ (Over S) ⊗ X ⟶ G ↦ T.smul (op _) y (e.homEquiv (snd _ _))) h₂).trans
      (T.one_smul _ _)
  mul_smul := by
    change μ[G] ▷ X ≫ torsorSMul e = (α_ G G X).hom ≫ G ◁ torsorSMul e ≫ torsorSMul e
    have h₁ : μ[G] ▷ X = lift (fst _ _ ≫ μ[G]) (snd _ _) := by ext <;> simp
    have h₂ : (α_ G G X).hom ≫ G ◁ torsorSMul e =
        lift (fst _ _ ≫ fst _ _) (lift (fst _ _ ≫ snd _ _) (snd _ _) ≫ torsorSMul e) := by
      refine CartesianMonoidalCategory.hom_ext _ _ (by simp) ?_
      simp only [Category.assoc, whiskerLeft_snd, lift_snd]
      rw [← Category.assoc]
      congr 1
      exact CartesianMonoidalCategory.hom_ext _ _ (by simp) (by simp)
    have h₃ : fst (G ⊗ G) X ≫ μ[G] = (fst _ _ ≫ fst _ _) * (fst _ _ ≫ snd _ _) := by
      rw [Hom.mul_def, ← comp_lift, lift_fst_snd, Category.comp_id]
    apply e.homEquiv.injective
    rw [h₁, reassoc_of% h₂, homEquiv_lift_torsorSMul, homEquiv_lift_torsorSMul,
      homEquiv_lift_torsorSMul]
    exact (congrArg (fun y : (G ⊗ G) ⊗ X ⟶ G ↦ T.smul (op _) y (e.homEquiv (snd _ _))) h₃).trans
      (T.mul_smul _ _ _ _)


end Torsor

section Gluing

variable {F : (Over S)ᵒᵖ ⥤ Type u}

/-- A jointly surjective family of open immersions of `S`-schemes generates an fpqc covering
sieve. -/
lemma generate_ofArrows_mem_fpqc {Y : Over S} {ι : Type u} {Z : ι → Over S} (p : ∀ i, Z i ⟶ Y)
    [∀ i, IsOpenImmersion (p i).left] (hp : ∀ y : Y.left, ∃ i z, (p i).left z = y) :
    Sieve.generate (Presieve.ofArrows Z p) ∈ fpqc S Y := by
  rw [GrothendieckTopology.mem_over_iff]
  let 𝒰 : Y.left.OpenCover :=
    Scheme.Cover.mkOfCovers ι (fun i ↦ (Z i).left) (fun i ↦ (p i).left) hp
  refine mem_fpqcTopology_of_openCover _ 𝒰 (fun i ↦ 𝒰.X i) (fun i ↦ 𝟙 _)
    (fun i ↦ ⟨⟨inferInstance, inferInstance⟩, inferInstance⟩) fun i ↦ ?_
  rw [Sieve.overEquiv_iff]
  refine ⟨Z i, CategoryTheory.Over.homMk (𝟙 _) ?_, p i, Presieve.ofArrows.mk (Y := Z) (f := p) i, ?_⟩
  · change 𝟙 _ ≫ (Z i).hom = (𝟙 _ ≫ (p i).left) ≫ Y.hom
    rw [Category.id_comp, Category.id_comp, Over.w (p i)]
  · ext
    change 𝟙 _ ≫ (p i).left = 𝟙 _ ≫ (p i).left
    rfl

variable (hF : Presieve.IsSheaf (fpqc S) F)
include hF

/-- An fpqc sheaf is separated for a jointly surjective family of open immersions. -/
lemma eq_of_forall_map_eq_of_isOpenImmersion {Y : Over S} {ι : Type u} {Z : ι → Over S}
    (p : ∀ i, Z i ⟶ Y) [∀ i, IsOpenImmersion (p i).left]
    (hp : ∀ y : Y.left, ∃ i z, (p i).left z = y) {y₁ y₂ : F.obj (op Y)}
    (h : ∀ i, F.map (p i).op y₁ = F.map (p i).op y₂) : y₁ = y₂ :=
  (hF _ (generate_ofArrows_mem_fpqc p hp)).isSeparatedFor.ext <| by
    rintro _ _ ⟨_, c, _, ⟨i⟩, hc⟩
    rw [← hc, map_comp_op_apply, map_comp_op_apply, h]

/-- Compatible sections of an fpqc sheaf over a jointly surjective family of open immersions
glue. -/
lemma exists_glue_of_isOpenImmersion {Y : Over S} {ι : Type u} {Z : ι → Over S}
    (p : ∀ i, Z i ⟶ Y) [∀ i, IsOpenImmersion (p i).left]
    (hp : ∀ y : Y.left, ∃ i z, (p i).left z = y) (x : ∀ i, F.obj (op (Z i)))
    (hx : Presieve.Arrows.Compatible F p x) : ∃ t : F.obj (op Y), ∀ i, F.map (p i).op t = x i := by
  have hsh := (Presieve.isSheafFor_iff_generate _).2 (hF _ (generate_ofArrows_mem_fpqc p hp))
  rw [Presieve.isSheafFor_arrows_iff] at hsh
  obtain ⟨t, ht, -⟩ := hsh x hx
  exact ⟨t, ht⟩

end Gluing

section Restriction

variable {F : (Over S)ᵒᵖ ⥤ Type u}

/-- If `(f, u)` and `(g, v)` represent `F` over `V` and `W`, a morphism `τ` of the representing
schemes over `ι : V ⟶ W` with `τ^* v = u` makes the square `τ, f, g, ι` cartesian. -/
theorem RepresentsOver.isPullback {V W X Y : Over S} {f : X ⟶ V} {g : Y ⟶ W}
    {u : F.obj (op X)} {v : F.obj (op Y)} (hf : RepresentsOver F f u)
    (hg : RepresentsOver F g v) (ι : V ⟶ W) (τ : X ⟶ Y) (hτ : τ ≫ g = f ≫ ι)
    (hu : F.map τ.op v = u) : IsPullback τ.left f.left g.left ι.left := by
  have hτ' : τ.left ≫ g.left = f.left ≫ ι.left := by
    simpa using congrArg CommaMorphism.left hτ
  have H : ∀ {T : Scheme.{u}} (α : T ⟶ Y.left) (β : T ⟶ V.left), α ≫ g.left = β ≫ ι.left →
      ∃ γ : T ⟶ X.left, γ ≫ τ.left = α ∧ γ ≫ f.left = β ∧
        ∀ γ' : T ⟶ X.left, γ' ≫ τ.left = α → γ' ≫ f.left = β → γ' = γ := by
    intro T α β e
    have hα : α ≫ Y.hom = (Over.mk (β ≫ V.hom)).hom := by
      change α ≫ Y.hom = β ≫ V.hom
      rw [← Over.w g, reassoc_of% e, Over.w ι]
    let αₒ : Over.mk (β ≫ V.hom) ⟶ Y := CategoryTheory.Over.homMk α hα
    let βₒ : Over.mk (β ≫ V.hom) ⟶ V := CategoryTheory.Over.homMk β rfl
    obtain ⟨c, hcf, hcu⟩ := hf.exists_eq βₒ (F.map αₒ.op v)
    have hcf' : c.left ≫ f.left = β := congrArg CommaMorphism.left hcf
    have hcτ : c ≫ τ = αₒ := hg.ext (by
        ext
        simp only [Over.comp_left, Category.assoc, hτ', reassoc_of% hcf', αₒ,
          CategoryTheory.Over.homMk_left, e])
      (by rw [map_comp_op_apply, hu, hcu])
    refine ⟨c.left, congrArg CommaMorphism.left hcτ, hcf', fun γ' h₁ h₂ ↦ ?_⟩
    have hγ' : γ' ≫ X.hom = (Over.mk (β ≫ V.hom)).hom := by
      change γ' ≫ X.hom = β ≫ V.hom
      rw [← Over.w f, reassoc_of% h₂]
    let γₒ : Over.mk (β ≫ V.hom) ⟶ X := CategoryTheory.Over.homMk γ' hγ'
    have hγτ : γₒ ≫ τ = αₒ := by ext; exact h₁
    have : γₒ = c := hf.ext (by ext; exact h₂.trans hcf'.symm) (by
      rw [hcu, ← hu, ← map_comp_op_apply, hγτ])
    exact congrArg CommaMorphism.left this
  exact IsPullback.of_isLimit (c := PullbackCone.mk _ _ hτ') (PullbackCone.IsLimit.mk hτ'
    (fun s ↦ (H s.fst s.snd s.condition).choose)
    (fun s ↦ (H s.fst s.snd s.condition).choose_spec.1)
    (fun s ↦ (H s.fst s.snd s.condition).choose_spec.2.1)
    (fun s m h₁ h₂ ↦ (H s.fst s.snd s.condition).choose_spec.2.2 m h₁ h₂))

variable {V V' X : Over S} {f : X ⟶ V} (ι : V' ⟶ V)

/-- The base change `X ×_V V'` of `f : X ⟶ V` along `ι : V' ⟶ V`, as an `S`-scheme. -/
noncomputable abbrev pullbackOver : Over S := Over.mk (pullback.snd f.left ι.left ≫ V'.hom)

/-- The projection `X ×_V V' ⟶ V'`. -/
noncomputable abbrev pullbackOverSnd : pullbackOver (f := f) ι ⟶ V' :=
  CategoryTheory.Over.homMk (pullback.snd f.left ι.left) rfl

/-- The projection `X ×_V V' ⟶ X`. -/
noncomputable abbrev pullbackOverFst : pullbackOver (f := f) ι ⟶ X :=
  CategoryTheory.Over.homMk (pullback.fst f.left ι.left) (by
    change pullback.fst f.left ι.left ≫ X.hom = pullback.snd f.left ι.left ≫ V'.hom
    rw [← Over.w f, pullback.condition_assoc, Over.w ι])

/-- Representability over `V` restricts to representability over `V'`, for any `ι : V' ⟶ V`,
by `X ×_V V'`. -/
theorem RepresentsOver.pullback {u : F.obj (op X)} (h : RepresentsOver F f u) :
    RepresentsOver F (pullbackOverSnd (f := f) ι) (F.map (pullbackOverFst (f := f) ι).op u) := by
  intro Z t
  have hpr : ∀ φ' : Z ⟶ pullbackOver (f := f) ι, φ' ≫ pullbackOverSnd ι = t →
      (φ' ≫ pullbackOverFst ι) ≫ f = t ≫ ι := by
    intro φ' e
    ext
    have e' : φ'.left ≫ pullback.snd f.left ι.left = t.left := by
      simpa using congrArg CommaMorphism.left e
    simp only [Over.comp_left, Category.assoc, CategoryTheory.Over.homMk_left]
    rw [pullback.condition, reassoc_of% e']
  constructor
  · rintro ⟨φ₁, h₁⟩ ⟨φ₂, h₂⟩ e
    change F.map φ₁.op (F.map _ u) = F.map φ₂.op (F.map _ u) at e
    rw [← map_comp_op_apply, ← map_comp_op_apply] at e
    have := h.ext ((hpr φ₁ h₁).trans (hpr φ₂ h₂).symm) e
    apply Subtype.ext
    ext
    apply pullback.hom_ext
    · simpa using congrArg CommaMorphism.left this
    · simpa using (congrArg CommaMorphism.left h₁).trans (congrArg CommaMorphism.left h₂).symm
  · intro s
    obtain ⟨φ, hφf, hφu⟩ := h.exists_eq (t ≫ ι) s
    have e : φ.left ≫ f.left = t.left ≫ ι.left := by simpa using congrArg CommaMorphism.left hφf
    let φ' : Z ⟶ pullbackOver (f := f) ι := CategoryTheory.Over.homMk (pullback.lift _ _ e) (by
      change pullback.lift _ _ e ≫ pullback.snd f.left ι.left ≫ V'.hom = Z.hom
      rw [pullback.lift_snd_assoc, Over.w t])
    have hφ' : φ' ≫ pullbackOverFst ι = φ := by ext; exact pullback.lift_fst _ _ _
    refine ⟨⟨φ', by ext; exact pullback.lift_snd _ _ _⟩, ?_⟩
    change F.map φ'.op (F.map _ u) = s
    rw [← map_comp_op_apply, hφ', hφu]

set_option backward.isDefEq.respectTransparency.types false in
instance [IsAffineHom f.left] : IsAffineHom (pullbackOverSnd (f := f) ι).left :=
  MorphismProperty.pullback_snd (P := @IsAffineHom) _ _ ‹_›

end Restriction

section ZariskiGluing

variable {F : (Over S)ᵒᵖ ⥤ Type u}

/-- A section `u ∈ F(X)` such that `φ ↦ φ^* u` is bijective for every `S`-scheme `Z` gives a
representation of `F` by `X`. -/
noncomputable def representableByOfBijective {X : Over S} (u : F.obj (op X))
    (h : ∀ Z : Over S, Function.Bijective fun φ : Z ⟶ X ↦ F.map φ.op u) : F.RepresentableBy X where
  homEquiv {Z} := Equiv.ofBijective _ (h Z)
  homEquiv_comp g φ := map_comp_op_apply g φ u

variable (F) in
/-- `F` is represented over the open subset `V` of `S` by an `S`-scheme affine over `V`. -/
def IsAffinelyRepresentedOn (V : S.Opens) : Prop :=
  ∃ (X : Over S) (f : X ⟶ Over.mk V.ι) (u : F.obj (op X)), IsAffineHom f.left ∧
    RepresentsOver F f u

lemma IsAffinelyRepresentedOn.mono {V W : S.Opens} (hle : W ≤ V)
    (h : IsAffinelyRepresentedOn F V) : IsAffinelyRepresentedOn F W := by
  obtain ⟨X, f, u, _, hf⟩ := h
  let ι : Over.mk W.ι ⟶ Over.mk V.ι := CategoryTheory.Over.homMk (S.homOfLE hle) (S.homOfLE_ι _)
  exact ⟨_, pullbackOverSnd (f := f) ι, _, inferInstance, hf.pullback ι⟩

set_option backward.isDefEq.respectTransparency.types false in
/-- Zariski gluing of representing schemes: if every point of `S` has an open neighbourhood over
which the fpqc sheaf `F` is represented by an `S`-scheme affine over it, then `F` is represented
by an `S`-scheme affine over `S`. The representing schemes are glued along the open cover of `S`
by all such open subsets (`Scheme.Cover.RelativeGluingData`). -/
theorem exists_representableBy_of_isAffinelyRepresentedOn (hF : Presieve.IsSheaf (fpqc S) F)
    (H : ∀ x : S, ∃ V : S.Opens, x ∈ V ∧ IsAffinelyRepresentedOn F V) :
    ∃ X : Over S, IsAffineHom X.hom ∧ Nonempty (F.RepresentableBy X) := by
  let I := {V : S.Opens // IsAffinelyRepresentedOn F V}
  have hcov : TopologicalSpace.IsOpenCover (fun i : I ↦ i.1) := by
    refine top_le_iff.mp fun x _ ↦ ?_
    obtain ⟨V, hx, hV⟩ := H x
    exact TopologicalSpace.Opens.mem_iSup.mpr ⟨⟨V, hV⟩, hx⟩
  choose X f u haff hrep using fun i : I ↦ i.2
  let 𝒰 : S.OpenCover := S.openCoverOfIsOpenCover (fun i : I ↦ i.1) hcov
  let _ : Preorder 𝒰.I₀ := inferInstanceAs (Preorder I)
  have hle : ∀ {i j : 𝒰.I₀}, i ≤ j ↔ (𝒰.f i).opensRange ≤ (𝒰.f j).opensRange := by
    intro i j
    change i.1 ≤ j.1 ↔ i.1.ι.opensRange ≤ j.1.ι.opensRange
    simp
  have hbasis : TopologicalSpace.Opens.IsBasis
      (Set.range fun i : 𝒰.I₀ ↦ (𝒰.f i).opensRange) := by
    rw [TopologicalSpace.Opens.isBasis_iff_nbhd]
    intro U x hx
    obtain ⟨V, hxV, hV⟩ := H x
    refine ⟨V ⊓ U, ⟨⟨V ⊓ U, hV.mono inf_le_left⟩, ?_⟩, ⟨hxV, hx⟩, inf_le_right⟩
    change (V ⊓ U).ι.opensRange = V ⊓ U
    simp
  let _ := Scheme.Cover.LocallyDirected.ofIsBasisOpensRange hle hbasis
  -- The transition maps `X i ⟶ X j` for `i ≤ j`.
  let ιo : ∀ i j : I, i ≤ j → (Over.mk i.1.ι ⟶ Over.mk j.1.ι) := fun i j h ↦
    CategoryTheory.Over.homMk (S.homOfLE h) (S.homOfLE_ι _)
  have hιo_id : ∀ i : I, ιo i i le_rfl = 𝟙 _ := fun i ↦ by ext; simp [ιo]
  have hιo_comp : ∀ (i j k : I) (h₁ : i ≤ j) (h₂ : j ≤ k),
      ιo i j h₁ ≫ ιo j k h₂ = ιo i k (h₁.trans h₂) := fun i j k h₁ h₂ ↦ by ext; simp [ιo]
  choose τ hτf hτu using fun (i j : I) (h : i ≤ j) ↦ (hrep j).exists_eq (f i ≫ ιo i j h) (u i)
  have τ_id : ∀ i : I, τ i i le_rfl = 𝟙 _ := fun i ↦ (hrep i).ext
    (by rw [hτf, hιo_id, Category.comp_id, Category.id_comp]) (by simp [hτu])
  have τ_comp : ∀ (i j k : I) (h₁ : i ≤ j) (h₂ : j ≤ k),
      τ i k (h₁.trans h₂) = τ i j h₁ ≫ τ j k h₂ := fun i j k h₁ h₂ ↦ (hrep k).ext
    (by rw [hτf, Category.assoc, hτf, reassoc_of% hτf, hιo_comp])
    (by rw [hτu, map_comp_op_apply, hτu, hτu])
  have hτf' : ∀ (i j : I) (h : i ≤ j), (τ i j h).left ≫ (f j).left = (f i).left ≫ S.homOfLE h :=
    fun i j h ↦ congrArg CommaMorphism.left (hτf i j h)
  have htrans : ∀ {i j : 𝒰.I₀} (h : i ⟶ j), 𝒰.trans h = S.homOfLE (leOfHom h) := by
    intro i j h
    rw [← cancel_mono (𝒰.f j), 𝒰.trans_map]
    exact (S.homOfLE_ι _).symm
  let Φ : 𝒰.I₀ ⥤ Scheme.{u} :=
    { obj i := (X i).left
      map {i j} h := (τ i j (leOfHom h)).left
      map_id i := by rw [τ_id]; rfl
      map_comp {i j k} h₁ h₂ := by rw [← Over.comp_left, ← τ_comp] }
  let α : Φ ⟶ 𝒰.functorOfLocallyDirected :=
    { app i := (f i).left
      naturality {i j} h := by
        change (τ i j _).left ≫ (f j).left = (f i).left ≫ 𝒰.trans h
        rw [htrans]
        exact hτf' i j _ }
  have hα : α.Equifibered := by
    intro i j h
    change IsPullback (τ i j _).left (f i).left (f j).left (𝒰.trans h)
    rw [htrans]
    exact (hrep i).isPullback (hrep j) (ιo i j _) (τ i j _) (hτf i j _) (hτu i j _)
  let d : 𝒰.RelativeGluingData := ⟨Φ, α, hα⟩
  have : ∀ {i j : 𝒰.I₀} (h : i ⟶ j), IsOpenImmersion (d.functor.map h) := fun h ↦
    MorphismProperty.of_isPullback (hα h).flip (inferInstanceAs (IsOpenImmersion (𝒰.trans h)))
  have : Quiver.IsThin 𝒰.I₀ := inferInstance
  have : Small.{u} 𝒰.I₀ := inferInstance
  have : (d.functor ⋙ Scheme.forget).IsLocallyDirected :=
    Scheme.isLocallyDirected_of_equifibered_of_injective d.natTrans d.equifibered
      fun h ↦ (d.functor.map h).isOpenEmbedding.injective
  -- The glued scheme.
  let XX : Over S := Over.mk d.toBase
  have hι : ∀ i : I, colimit.ι d.functor i ≫ d.toBase = (X i).hom := fun i ↦ by
    rw [d.ι_toBase]
    exact Over.w (f i)
  let ιX : ∀ i : I, X i ⟶ XX := fun i ↦ CategoryTheory.Over.homMk (colimit.ι d.functor i) (hι i)
  have hιτ : ∀ (i j : I) (h : i ≤ j), τ i j h ≫ ιX j = ιX i := fun i j h ↦ by
    ext
    exact colimit.w d.functor (homOfLE h)
  have hpb : ∀ i : I, IsPullback (f i).left (colimit.ι d.functor i) i.1.ι d.toBase :=
    d.isPullback_natTrans_ι_toBase
  have : ∀ i : I, IsOpenImmersion (ιX i).left := fun i ↦
    inferInstanceAs (IsOpenImmersion (colimit.ι d.functor i))
  have hsurj : ∀ x : XX.left, ∃ i z, (ιX i).left z = x :=
    fun x ↦ Scheme.IsLocallyDirected.ι_jointly_surjective d.functor x
  -- The universal section.
  obtain ⟨uu, huu⟩ := exists_glue_of_isOpenImmersion hF ιX hsurj u fun i j Z a b hab ↦ by
    have hab' : a.left ≫ colimit.ι d.functor i = b.left ≫ colimit.ι d.functor j :=
      congrArg CommaMorphism.left hab
    have hZi : a.left ≫ (f i).left ≫ i.1.ι = Z.hom :=
      (congrArg (a.left ≫ ·) (Over.w (f i))).trans (Over.w a)
    have hZj : b.left ≫ (f j).left ≫ j.1.ι = Z.hom :=
      (congrArg (b.left ≫ ·) (Over.w (f j))).trans (Over.w b)
    let k : I := ⟨i.1 ⊓ j.1, i.2.mono inf_le_left⟩
    have hki : k ≤ i := show i.1 ⊓ j.1 ≤ i.1 from inf_le_left
    have hkj : k ≤ j := show i.1 ⊓ j.1 ≤ j.1 from inf_le_right
    have hrange : Set.range Z.hom ⊆ Set.range k.1.ι := by
      rintro _ ⟨z, rfl⟩
      rw [Scheme.Opens.range_ι]
      refine ⟨?_, ?_⟩
      · rw [← hZi, Scheme.Hom.comp_apply, Scheme.Hom.comp_apply]
        exact ((f i).left (a.left z)).2
      · rw [← hZj, Scheme.Hom.comp_apply, Scheme.Hom.comp_apply]
        exact ((f j).left (b.left z)).2
    let zk : Z.left ⟶ k.1 := IsOpenImmersion.lift k.1.ι Z.hom hrange
    have hzk : zk ≫ k.1.ι = Z.hom := IsOpenImmersion.lift_fac _ _ _
    let tk : Z ⟶ Over.mk k.1.ι := CategoryTheory.Over.homMk zk hzk
    obtain ⟨c, hcf, hcu⟩ := (hrep k).exists_eq tk (F.map a.op (u i))
    have hcf' : c.left ≫ (f k).left = zk := congrArg CommaMorphism.left hcf
    have hca : c ≫ τ k i hki = a := (hrep i).ext (by
        ext
        change c.left ≫ (τ k i hki).left ≫ (f i).left = a.left ≫ (f i).left
        rw [hτf', reassoc_of% hcf', ← cancel_mono i.1.ι, Category.assoc, S.homOfLE_ι, hzk,
          Category.assoc, hZi])
      (by rw [map_comp_op_apply, hτu, hcu])
    have hcb : c ≫ τ k j hkj = b := by
      ext
      rw [← cancel_mono (colimit.ι d.functor j)]
      change c.left ≫ (τ k j hkj ≫ ιX j).left = b.left ≫ colimit.ι d.functor j
      rw [← hab', hιτ, ← hca, ← hιτ k i hki]
      rfl
    rw [← hca, ← hcb, map_comp_op_apply, map_comp_op_apply, hτu, hτu]
  -- Restriction of an `S`-scheme `Z` to the inverse images of the `i`.
  have hZcov : ∀ Z : Over S, TopologicalSpace.IsOpenCover (fun i : I ↦ Z.hom ⁻¹ᵁ i.1) :=
    fun Z ↦ by
      change ⨆ i : I, Z.hom ⁻¹ᵁ i.1 = ⊤
      rw [← Scheme.Hom.preimage_iSup, show ⨆ i : I, i.1 = ⊤ from hcov, Scheme.Hom.preimage_top]
  let Zi : Over S → I → Over S := fun Z i ↦ Over.mk ((Z.hom ⁻¹ᵁ i.1).ι ≫ Z.hom)
  let jZ : ∀ (Z : Over S) (i : I), Zi Z i ⟶ Z := fun Z i ↦
    CategoryTheory.Over.homMk (Z.hom ⁻¹ᵁ i.1).ι rfl
  let tZ : ∀ (Z : Over S) (i : I), Zi Z i ⟶ Over.mk i.1.ι := fun Z i ↦
    CategoryTheory.Over.homMk (Z.hom ∣_ i.1) (morphismRestrict_ι _ _)
  have : ∀ (Z : Over S) (i : I), IsOpenImmersion (jZ Z i).left := fun Z i ↦
    inferInstanceAs (IsOpenImmersion (Z.hom ⁻¹ᵁ i.1).ι)
  have hjZ : ∀ (Z : Over S) (z : Z.left), ∃ i w, (jZ Z i).left w = z := fun Z z ↦ by
    obtain ⟨i, hi⟩ := TopologicalSpace.Opens.mem_iSup.mp
      ((show ⨆ i : I, i.1 = ⊤ from hcov).ge (Set.mem_univ (Z.hom z)))
    exact ⟨i, ⟨z, hi⟩, rfl⟩
  -- A morphism `Z ⟶ X` restricts to morphisms `Zᵢ ⟶ Xᵢ` over `i`.
  have hres : ∀ (Z : Over S) (φ : Z ⟶ XX) (i : I),
      ∃ φi : Zi Z i ⟶ X i, φi ≫ f i = tZ Z i ∧ φi ≫ ιX i = jZ Z i ≫ φ := by
    intro Z φ i
    have w : (Z.hom ∣_ i.1) ≫ i.1.ι = ((Z.hom ⁻¹ᵁ i.1).ι ≫ φ.left) ≫ d.toBase := by
      rw [morphismRestrict_ι, Category.assoc]
      exact congrArg ((Z.hom ⁻¹ᵁ i.1).ι ≫ ·) (Over.w φ).symm
    let l := (hpb i).lift (Z.hom ∣_ i.1) ((Z.hom ⁻¹ᵁ i.1).ι ≫ φ.left) w
    have hl₁ : l ≫ (f i).left = Z.hom ∣_ i.1 := (hpb i).lift_fst _ _ _
    have hl₂ : l ≫ colimit.ι d.functor i = (Z.hom ⁻¹ᵁ i.1).ι ≫ φ.left := (hpb i).lift_snd _ _ _
    refine ⟨CategoryTheory.Over.homMk l ?_, ?_, ?_⟩
    · change l ≫ (X i).hom = (Z.hom ⁻¹ᵁ i.1).ι ≫ Z.hom
      rw [← Over.w (f i), reassoc_of% hl₁]
      exact morphismRestrict_ι _ _
    · ext; exact hl₁
    · ext; exact hl₂
  -- Injectivity.
  have hinj : ∀ ⦃Z : Over S⦄ (φ ψ : Z ⟶ XX), F.map φ.op uu = F.map ψ.op uu → φ = ψ := by
    intro Z φ ψ e
    ext
    refine Scheme.Cover.hom_ext (Z.left.openCoverOfIsOpenCover _ (hZcov Z)) _ _ fun i ↦ ?_
    obtain ⟨φi, hφf, hφι⟩ := hres Z φ i
    obtain ⟨ψi, hψf, hψι⟩ := hres Z ψ i
    have : φi = ψi := (hrep i).ext (hφf.trans hψf.symm) (by
      rw [← huu, ← map_comp_op_apply, ← map_comp_op_apply, hφι, hψι, map_comp_op_apply,
        map_comp_op_apply, e])
    have := congrArg CommaMorphism.left ((hφι.symm.trans (this ▸ rfl)).trans hψι)
    exact this
  -- Surjectivity.
  have hsurj' : ∀ (Z : Over S) (s : F.obj (op Z)), ∃ φ : Z ⟶ XX, F.map φ.op uu = s := by
    intro Z s
    choose φi hφf hφu using fun i : I ↦ (hrep i).exists_eq (tZ Z i) (F.map (jZ Z i).op s)
    let 𝒵 := Z.left.openCoverOfIsOpenCover _ (hZcov Z)
    let g : ∀ i : I, 𝒵.X i ⟶ XX.left := fun i ↦ (φi i).left ≫ colimit.ι d.functor i
    have hg : ∀ i : I, g i ≫ XX.hom = (Z.hom ⁻¹ᵁ i.1).ι ≫ Z.hom := fun i ↦ by
      change (φi i).left ≫ colimit.ι d.functor i ≫ d.toBase = _
      rw [hι]
      exact Over.w (φi i)
    have hcompat : ∀ i j : I, pullback.fst (𝒵.f i) (𝒵.f j) ≫ g i =
        pullback.snd (𝒵.f i) (𝒵.f j) ≫ g j := by
      intro i j
      let W : Over S := Over.mk (pullback.fst (𝒵.f i) (𝒵.f j) ≫ (Z.hom ⁻¹ᵁ i.1).ι ≫ Z.hom)
      let p₁ : W ⟶ Zi Z i := CategoryTheory.Over.homMk (pullback.fst (𝒵.f i) (𝒵.f j)) rfl
      let p₂ : W ⟶ Zi Z j := CategoryTheory.Over.homMk (pullback.snd (𝒵.f i) (𝒵.f j)) (by
        change pullback.snd (𝒵.f i) (𝒵.f j) ≫ (Z.hom ⁻¹ᵁ j.1).ι ≫ Z.hom = _
        exact pullback.condition_assoc (f := 𝒵.f i) (g := 𝒵.f j) _ |>.symm)
      have hp : p₁ ≫ jZ Z i = p₂ ≫ jZ Z j := by
        ext
        exact pullback.condition
      have := hinj (p₁ ≫ φi i ≫ ιX i) (p₂ ≫ φi j ≫ ιX j) (by
        rw [map_comp_op_apply, map_comp_op_apply, huu, hφu, map_comp_op_apply,
          map_comp_op_apply, huu, hφu, ← map_comp_op_apply, ← map_comp_op_apply, hp])
      exact congrArg CommaMorphism.left this
    let φ₀ : Z.left ⟶ XX.left := 𝒵.glueMorphisms g hcompat
    have hφ₀ : ∀ i : I, (Z.hom ⁻¹ᵁ i.1).ι ≫ φ₀ = g i := fun i ↦
      Scheme.Cover.ι_glueMorphisms 𝒵 g hcompat i
    let φ : Z ⟶ XX := CategoryTheory.Over.homMk φ₀ (by
      refine Scheme.Cover.hom_ext 𝒵 _ _ fun i ↦ ?_
      change (Z.hom ⁻¹ᵁ i.1).ι ≫ φ₀ ≫ XX.hom = (Z.hom ⁻¹ᵁ i.1).ι ≫ Z.hom
      rw [reassoc_of% (hφ₀ i)]
      exact hg i)
    refine ⟨φ, eq_of_forall_map_eq_of_isOpenImmersion hF (jZ Z) (hjZ Z) fun i ↦ ?_⟩
    have hjφ : jZ Z i ≫ φ = φi i ≫ ιX i := by
      ext
      exact hφ₀ i
    rw [← map_comp_op_apply, hjφ, map_comp_op_apply, huu, hφu]
  -- Affineness.
  have haffX : IsAffineHom XX.hom := by
    refine IsZariskiLocalAtTarget.of_openCover 𝒰 fun i ↦ ?_
    change IsAffineHom (pullback.snd d.toBase i.1.ι)
    rw [← (hpb i).flip.isoPullback_inv_snd]
    infer_instance
  exact ⟨XX, haffX, ⟨representableByOfBijective uu fun Z ↦
    ⟨fun φ ψ e ↦ hinj φ ψ e, fun s ↦ hsurj' Z s⟩⟩⟩

end ZariskiGluing

end SGA.SGA1.ExposeXI
