/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.SGA1.ExposeIII.CurveLiftCharts
import SGA.Foundations.Formal.AmpleLift
import SGA.Foundations.Cohomology.FormalAlgebraization

/-!
# SGA 1, Exposé III, 7.4: lifting a curve with a morphism to `ℙ¹`, level by level

Let `A` be a noetherian ring and `I ⊆ A` an ideal, `Aₙ = A / I^{n+1}`. Let `X₀` be a smooth
`A₀`-scheme which is the union of two affine opens `U₀`, `U₁` with affine intersection, with
`t ∈ Γ(U₀)`, `s ∈ Γ(U₁)`, `t s = 1` on `U₀ ∩ U₁`, `D(t) ⊆ U₁`, `D(s) ⊆ U₀` (a morphism
`X₀ ⟶ ℙ¹` with `U₀`, `U₁` the inverse images of the standard charts), such that
`Γ(U₀ ∩ U₁) = t Γ(U₁) + s Γ(U₀)` (`CurveLift.Base`; this is `H¹(X₀, g^* 𝒪(2)) = 0` for the
morphism `g = (1 : t) : X₀ ⟶ ℙ¹`). We construct smooth lifts `Xₙ` of `X₀` over `Aₙ`, with
`Xₙ = Xₙ₊₁ ×_{Aₙ₊₁} Aₙ`, together with lifts of `U₀`, `U₁`, `t`, `s` (`CurveLift.Stage`,
`CurveLift.Stage.exists_succ`): the lift of the scheme is III.6.7 for two charts
(`exists_smooth_lift_of_sup_eq_top_preimage`), and the lift of `t`, `s` is
`AmpleLift.exists_lift_mul_eq_one` (deformation of the morphism `X₀ ⟶ ℙ¹`, not in SGA).

## Relation to SGA 1 III.7.4

SGA proves III.7.4 by lifting `X₀` formally (III.6.10, the obstructions lie in `H²` of coherent
sheaves on a curve), lifting an ample line bundle (III.7.1, `H²(X₀, 𝒪) = 0`) and algebraizing the
formal curve inside the formal completion of `ℙⁿ_A` by Grothendieck's existence theorem (III.7.2).
This formalization replaces the ample line bundle by a **finite flat morphism `X₀ ⟶ ℙ¹`**: the
lifts `Xₙ` come with lifted morphisms `Xₙ ⟶ ℙ¹_{Aₙ}` (this file), which form a finite flat cover
of the formal completion of `ℙ¹_A` (`SGA.SGA1.ExposeIII.CurveLiftSystem`,
`SGA.SGA1.ExposeIII.CurveLiftFinite`, `SGA.SGA1.ExposeIII.CurveLiftFlat`); it is algebraized by the
existence theorem for locally free sheaves (`CohomologyAux.exists_finite_flat_of_formalFiniteFlat`)
instead of the one for coherent sheaves on `ℙⁿ_A`. The algebraization is smooth by
`SGA.SGA1.ExposeIII.CurveLiftSmooth` and `SGA.SGA1.ExposeIII.CurveLiftAssembly`; the level `0`
data come from a finite flat morphism `X₀ ⟶ ℙ¹` (`SGA.SGA1.ExposeIII.CurveLiftBase`), which exists
for every smooth proper curve (`SGA.SGA1.ExposeIII.CurveLiftCurve`). The result is
`SGA.SGA1.ExposeIII.smoothProperCurveLiftStatement`.

## References

* [SGA 1, III.6.7, III.7.1–III.7.4][SGA1].
-/

universe u

open CategoryTheory Limits AlgebraicGeometry

namespace SGA.SGA1.ExposeIII

section BaseChange

set_option backward.isDefEq.respectTransparency false in
/-- **Affine base change on an affine open** (variant of
`CohomologyAux.app_surjective_ker_of_isPullback` for an affine open `V ≤ p⁻¹ U`): for a cartesian
square `P = Y ×_X X'` with `i : X' ⟶ X` surjective on sections over the affine open `U`, `i⁻¹ U`
affine, and `V ≤ p⁻¹ U` affine, `Γ(Y, V) → Γ(P, j⁻¹ V)` is surjective with kernel generated by the
kernel of `i`. -/
theorem app_surjective_ker_of_isPullback_le {P Y X' X : Scheme.{u}} {j : P ⟶ Y} {s : P ⟶ X'}
    {p : Y ⟶ X} {i : X' ⟶ X} (H : IsPullback j s p i) {U : X.Opens} (hU : IsAffineOpen U)
    {V : Y.Opens} (hV : IsAffineOpen V) (hVU : V ≤ p ⁻¹ᵁ U) (hiU : IsAffineOpen (i ⁻¹ᵁ U))
    (hi : Function.Surjective (i.app U)) :
    Function.Surjective (j.app V) ∧
      RingHom.ker (j.app V).hom = (RingHom.ker (i.app U).hom).map (p.appLE U V hVU).hom := by
  have hUY : j ⁻¹ᵁ V = j ⁻¹ᵁ V ⊓ s ⁻¹ᵁ i ⁻¹ᵁ U := by
    refine (inf_eq_left.mpr ?_).symm
    rw [← Scheme.Hom.comp_preimage, ← H.w, Scheme.Hom.comp_preimage]
    exact j.preimage_mono hVU
  have hiso := isIso_pushoutSection_of_isAffineOpen H (US := U) (UT := i ⁻¹ᵁ U) (UX := V)
    le_rfl hVU hUY hU hiU hV
  rw [isIso_pushoutSection_iff] at hiso
  have hi' : Function.Surjective (i.appLE U (i ⁻¹ᵁ U) le_rfl) := by
    rwa [← Scheme.Hom.app_eq_appLE]
  obtain ⟨hker, hsurj⟩ := CohomologyAux.ker_inl_of_isPushout_surjective hiso hi'
  rw [Scheme.Hom.app_eq_appLE, Scheme.Hom.app_eq_appLE]
  exact ⟨hsurj, hker⟩

/-- For a surjective ring map `φ` whose kernel is nilpotent, the closed immersion `Spec φ` has a
nilpotent ideal. -/
lemma isNilpotent_ker_specMap {R S : CommRingCat.{u}} (φ : R ⟶ S) (n : ℕ)
    (hn : RingHom.ker φ.hom ^ n = ⊥) : IsNilpotent (Spec.map φ).ker := by
  refine ⟨n, Scheme.IdealSheafData.ext_of_isAffine ?_⟩
  rw [Scheme.IdealSheafData.ideal_pow, Pi.pow_apply, Scheme.Hom.ker_apply]
  change RingHom.ker (Spec.map φ).appTop.hom ^ n = ⊥
  have hnat := Scheme.ΓSpecIso_naturality φ
  have hle : (RingHom.ker (Spec.map φ).appTop.hom).map (Scheme.ΓSpecIso R).hom.hom ≤
      RingHom.ker φ.hom := by
    rw [Ideal.map_le_iff_le_comap]
    intro x hx
    rw [Ideal.mem_comap, RingHom.mem_ker]
    have hx' := congrArg (fun g ↦ g.hom x) hnat
    simp only [CommRingCat.hom_comp, RingHom.coe_comp, Function.comp_apply] at hx'
    rw [← hx', RingHom.mem_ker.mp hx, map_zero]
  rw [eq_bot_iff]
  intro x hx
  have h1 : (Scheme.ΓSpecIso R).hom.hom x ∈ RingHom.ker φ.hom ^ n := by
    have := Ideal.mem_map_of_mem (Scheme.ΓSpecIso R).hom.hom hx
    rw [Ideal.map_pow] at this
    exact Ideal.pow_right_mono hle n this
  rw [hn, Ideal.mem_bot] at h1
  rw [Ideal.mem_bot]
  exact (map_eq_zero_iff _ (Scheme.ΓSpecIso R).commRingCatIsoToRingEquiv.injective).mp h1

/-- The kernel of `Γ(Spec B, ⊤) → Γ(Spec C, ⊤)` for `ψ : B → C`. -/
lemma ker_specMap_appTop {B C : CommRingCat.{u}} (ψ : B ⟶ C) :
    RingHom.ker (Spec.map ψ).appTop.hom = (RingHom.ker ψ.hom).map (Scheme.ΓSpecIso B).inv.hom := by
  have hnat := Scheme.ΓSpecIso_naturality ψ
  ext x
  rw [RingHom.mem_ker, show (Scheme.ΓSpecIso B).inv.hom =
    ((Scheme.ΓSpecIso B).commRingCatIsoToRingEquiv.symm : B →+* Γ(Spec B, ⊤)) from rfl,
    Ideal.map_comap_of_equiv, Ideal.mem_comap, RingEquiv.symm_symm, RingHom.mem_ker]
  have hx := congrArg (fun g ↦ g.hom x) hnat
  simp only [CommRingCat.hom_comp, RingHom.coe_comp, Function.comp_apply] at hx
  change _ ↔ ψ.hom ((Scheme.ΓSpecIso B).hom.hom x) = 0
  rw [← hx]
  constructor
  · intro h'
    rw [h', map_zero]
  · intro h'
    apply (Scheme.ΓSpecIso C).commRingCatIsoToRingEquiv.injective
    rw [map_zero]
    exact h'

/-- **Affine base change along `Spec C ⟶ Spec B`** on an affine open `V` of `X'`, for a cartesian
square `X = X' ×_{Spec B} Spec C` with `ψ : B → C` surjective: `Γ(X', V) → Γ(X, k⁻¹ V)` is
surjective with kernel generated by `ker ψ`. -/
lemma appLE_surjective_ker_of_isPullback_specMap {X X' : Scheme.{u}} {B C : CommRingCat.{u}}
    (ψ : B ⟶ C) (hψ : Function.Surjective ψ) {k : X ⟶ X'} {f : X ⟶ Spec C} {f' : X' ⟶ Spec B}
    (H : IsPullback k f f' (Spec.map ψ)) {V : X'.Opens} (hV : IsAffineOpen V) {W : X.Opens}
    (hW : k ⁻¹ᵁ V = W) :
    Function.Surjective (k.appLE V W hW.ge) ∧ RingHom.ker (k.appLE V W hW.ge).hom =
      (RingHom.ker ψ.hom).map ((f'.appLE ⊤ V le_top).hom.comp (Scheme.ΓSpecIso B).inv.hom) := by
  have hsurj : Function.Surjective ((Spec.map ψ).app ⊤) := by
    have hnat := Scheme.ΓSpecIso_naturality ψ
    intro y
    obtain ⟨b, hb⟩ := hψ ((Scheme.ΓSpecIso C).hom y)
    refine ⟨(Scheme.ΓSpecIso B).inv b, ?_⟩
    apply (Scheme.ΓSpecIso C).commRingCatIsoToRingEquiv.injective
    have hx := congrArg (fun g ↦ g.hom ((Scheme.ΓSpecIso B).inv b)) hnat
    simp only [CommRingCat.hom_comp, RingHom.coe_comp, Function.comp_apply,
      Iso.inv_hom_id_apply] at hx
    exact hx.trans hb
  obtain ⟨h1, h2⟩ := app_surjective_ker_of_isPullback_le H (isAffineOpen_top _) hV le_top
    (by simpa using isAffineOpen_top (Spec C)) hsurj
  obtain ⟨h3, h4⟩ := CohomologyAux.appLE_surjective_ker_of_eq k V hW.symm hW.ge
  refine ⟨h3.mpr h1, ?_⟩
  rw [h4, h2]
  change (RingHom.ker (Spec.map ψ).appTop.hom).map _ = _
  rw [ker_specMap_appTop, Ideal.map_map]

end BaseChange

namespace CurveLift

variable {A : Type u} [CommRing A] (I : Ideal A)

/-- The ring `Aₙ = A / I^{n+1}`. -/
abbrev Q (n : ℕ) : CommRingCat.{u} := .of (A ⧸ I ^ (n + 1))

/-- The closed immersion `Spec Aₙ ⟶ Spec Aₙ₊₁`. -/
noncomputable def π (n : ℕ) : Spec (Q I n) ⟶ Spec (Q I (n + 1)) :=
  Spec.map (CommRingCat.ofHom
    (Ideal.Quotient.factor (Ideal.pow_le_pow_right (Nat.le_succ (n + 1)))))

/-- The closed immersion `Spec A₀ ⟶ Spec Aₙ`. -/
noncomputable def ρ (n : ℕ) : Spec (Q I 0) ⟶ Spec (Q I n) :=
  Spec.map (CommRingCat.ofHom
    (Ideal.Quotient.factor (Ideal.pow_le_pow_right (by omega : 0 + 1 ≤ n + 1))))

lemma ρ_zero : ρ I 0 = 𝟙 _ := by
  rw [ρ, Ideal.Quotient.factor_eq]
  exact Spec.map_id _

lemma ρ_comp_π (n : ℕ) : ρ I n ≫ π I n = ρ I (n + 1) := by
  rw [ρ, π, ρ, ← Spec.map_comp, ← CommRingCat.ofHom_comp, Ideal.Quotient.factor_comp]

/-- The ring homomorphism `A → Γ(X, ⊤)` of a scheme over `Spec Aₙ`. -/
noncomputable def cA {n : ℕ} {X : Scheme.{u}} (f : X ⟶ Spec (Q I n)) : A →+* Γ(X, ⊤) :=
  f.appTop.hom.comp ((Scheme.ΓSpecIso (Q I n)).inv.hom.comp (Ideal.Quotient.mk _))

/-- The level `0` data: a smooth `A₀`-scheme `X₀ = U₀ ∪ U₁` (affine charts with affine
intersection), with `t ∈ Γ(U₀)`, `s ∈ Γ(U₁)`, `t s = 1` on `U₀ ∩ U₁`, `D(t) ⊆ U₁`, `D(s) ⊆ U₀`,
and `Γ(U₀ ∩ U₁) = t Γ(U₁) + s Γ(U₀)`. -/
structure Base where
  /-- The scheme `X₀`. -/
  X : Scheme.{u}
  /-- The structure morphism. -/
  f : X ⟶ Spec (Q I 0)
  smooth : Smooth f
  /-- The first chart. -/
  U₀ : X.Opens
  /-- The second chart. -/
  U₁ : X.Opens
  isAffineOpen_U₀ : IsAffineOpen U₀
  isAffineOpen_U₁ : IsAffineOpen U₁
  isAffineOpen_inf : IsAffineOpen (U₀ ⊓ U₁)
  sup_eq_top : U₀ ⊔ U₁ = ⊤
  /-- The coordinate on `U₀`. -/
  t : Γ(X, U₀)
  /-- The coordinate on `U₁`. -/
  s : Γ(X, U₁)
  mul_eq_one : X.presheaf.map (homOfLE inf_le_left : U₀ ⊓ U₁ ⟶ U₀).op t *
    X.presheaf.map (homOfLE inf_le_right : U₀ ⊓ U₁ ⟶ U₁).op s = 1
  basicOpen_t_le : X.basicOpen t ≤ U₁
  basicOpen_s_le : X.basicOpen s ≤ U₀
  /-- `H¹(X₀, g^* 𝒪(2)) = 0` for the morphism `g = (1 : t)`, in Čech form. -/
  H1 : ∀ w : Γ(X, U₀ ⊓ U₁), ∃ (r : Γ(X, U₀)) (v : Γ(X, U₁)),
    w = X.presheaf.map (homOfLE inf_le_left : U₀ ⊓ U₁ ⟶ U₀).op t *
        X.presheaf.map (homOfLE inf_le_right : U₀ ⊓ U₁ ⟶ U₁).op v +
      X.presheaf.map (homOfLE inf_le_right : U₀ ⊓ U₁ ⟶ U₁).op s *
        X.presheaf.map (homOfLE inf_le_left : U₀ ⊓ U₁ ⟶ U₀).op r

variable {I} (B : Base I)

/-- A lift of the level `0` data over `Aₙ`. -/
structure Stage (n : ℕ) where
  /-- The scheme `Xₙ`. -/
  X : Scheme.{u}
  /-- The structure morphism. -/
  f : X ⟶ Spec (Q I n)
  smooth : Smooth f
  /-- The first chart. -/
  U₀ : X.Opens
  /-- The second chart. -/
  U₁ : X.Opens
  isAffineOpen_U₀ : IsAffineOpen U₀
  isAffineOpen_U₁ : IsAffineOpen U₁
  isAffineOpen_inf : IsAffineOpen (U₀ ⊓ U₁)
  sup_eq_top : U₀ ⊔ U₁ = ⊤
  /-- The coordinate on `U₀`. -/
  t : Γ(X, U₀)
  /-- The coordinate on `U₁`. -/
  s : Γ(X, U₁)
  mul_eq_one : X.presheaf.map (homOfLE inf_le_left : U₀ ⊓ U₁ ⟶ U₀).op t *
    X.presheaf.map (homOfLE inf_le_right : U₀ ⊓ U₁ ⟶ U₁).op s = 1
  basicOpen_t_le : X.basicOpen t ≤ U₁
  basicOpen_s_le : X.basicOpen s ≤ U₀
  /-- The closed immersion `X₀ ⟶ Xₙ`. -/
  i : B.X ⟶ X
  isPullback : IsPullback i B.f f (ρ I n)
  preimage_U₀ : i ⁻¹ᵁ U₀ = B.U₀
  preimage_U₁ : i ⁻¹ᵁ U₁ = B.U₁
  t_eq : i.appLE U₀ B.U₀ preimage_U₀.ge t = B.t
  s_eq : i.appLE U₁ B.U₁ preimage_U₁.ge s = B.s

set_option backward.isDefEq.respectTransparency false in
/-- The level `0` stage. -/
noncomputable def Stage.zero : Stage B 0 where
  X := B.X
  f := B.f
  smooth := B.smooth
  U₀ := B.U₀
  U₁ := B.U₁
  isAffineOpen_U₀ := B.isAffineOpen_U₀
  isAffineOpen_U₁ := B.isAffineOpen_U₁
  isAffineOpen_inf := B.isAffineOpen_inf
  sup_eq_top := B.sup_eq_top
  t := B.t
  s := B.s
  mul_eq_one := B.mul_eq_one
  basicOpen_t_le := B.basicOpen_t_le
  basicOpen_s_le := B.basicOpen_s_le
  i := 𝟙 _
  isPullback := by
    rw [ρ_zero]
    exact IsPullback.of_horiz_isIso ⟨by simp⟩
  preimage_U₀ := rfl
  preimage_U₁ := rfl
  t_eq := by
    simp only [Scheme.Hom.appLE, Scheme.Hom.id_app, Category.id_comp]
    exact CategoryTheory.Functor.map_id_apply _ _ _
  s_eq := by
    simp only [Scheme.Hom.appLE, Scheme.Hom.id_app, Category.id_comp]
    exact CategoryTheory.Functor.map_id_apply _ _ _

omit [CommRing A] in
lemma le_of_preimage_le {X Y : Scheme.{u}} (k : X ⟶ Y) (hk : Function.Surjective k)
    {U V : Y.Opens} (h : k ⁻¹ᵁ U ≤ k ⁻¹ᵁ V) : U ≤ V := by
  intro x hx
  obtain ⟨y, rfl⟩ := hk x
  exact h hx

/-- The `A`-algebra structure on the sections over an open of a scheme over `Spec Aₙ`. -/
noncomputable abbrev cV {n : ℕ} {X : Scheme.{u}} (f : X ⟶ Spec (Q I n)) (V : X.Opens) :
    A →+* Γ(X, V) :=
  (f.appLE ⊤ V (by simp)).hom.comp ((Scheme.ΓSpecIso (Q I n)).inv.hom.comp
    (Ideal.Quotient.mk _))

lemma res_cV {n : ℕ} {X : Scheme.{u}} (f : X ⟶ Spec (Q I n)) {V W : X.Opens} (h : W ≤ V)
    (a : A) : X.presheaf.map (homOfLE h).op (cV f V a) = cV f W a := by
  have := congrArg (fun g ↦ g.hom ((Scheme.ΓSpecIso (Q I n)).inv.hom (Ideal.Quotient.mk _ a)))
    (Scheme.Hom.appLE_map f (U := ⊤) (V := V) (V' := W) (by simp) (homOfLE h).op)
  exact this

lemma ker_factor_pow {m k : ℕ} (H : I ^ m ≤ I ^ k) :
    RingHom.ker (Ideal.Quotient.factor H : A ⧸ I ^ m →+* A ⧸ I ^ k) =
      (I ^ k).map (Ideal.Quotient.mk (I ^ m)) :=
  Ideal.Quotient.factor_ker _

/-- **The lifting step** (SGA 1 III.6.7 for a scheme covered by two affine charts, together with
the lifting of the morphism to `ℙ¹` given by the coordinates `t`, `s`, whose obstruction lies in
`H¹(X₀, g^* T_{ℙ¹})` and vanishes by the condition `Base.H1`; the latter is not in SGA, which
lifts an ample line bundle instead, III.7.1): for `A` noetherian, a stage over `Aₙ` lifts to a
stage over `Aₙ₊₁`, with `Xₙ = Xₙ₊₁ ×_{Aₙ₊₁} Aₙ`, compatibly with the charts and the coordinates. -/
theorem Stage.exists_succ [IsNoetherianRing A] {n : ℕ} (S : Stage B n) :
    ∃ (S' : Stage B (n + 1)) (k : S.X ⟶ S'.X) (h₀ : k ⁻¹ᵁ S'.U₀ = S.U₀)
      (h₁ : k ⁻¹ᵁ S'.U₁ = S.U₁), IsPullback k S.f S'.f (π I n) ∧ S.i ≫ k = S'.i ∧
        k.appLE S'.U₀ S.U₀ h₀.ge S'.t = S.t ∧ k.appLE S'.U₁ S.U₁ h₁.ge S'.s = S.s := by
  have hsurjπ : Function.Surjective (Ideal.Quotient.factor
      (Ideal.pow_le_pow_right (Nat.le_succ (n + 1))) : A ⧸ I ^ (n + 1 + 1) →+* A ⧸ I ^ (n + 1)) :=
    Ideal.Quotient.factor_surjective _
  have : IsClosedImmersion (π I n) := IsClosedImmersion.spec_of_surjective _ hsurjπ
  have hnil : IsNilpotent (π I n).ker := by
    refine isNilpotent_ker_specMap _ 2 ?_
    rw [CommRingCat.hom_ofHom, ker_factor_pow, ← Ideal.map_pow, ← pow_mul, eq_bot_iff,
      Ideal.map_le_iff_le_comap]
    intro x hx
    rw [Ideal.mem_comap, Ideal.mem_bot, Ideal.Quotient.eq_zero_iff_mem]
    exact Ideal.pow_le_pow_right (by omega) hx
  have := S.smooth
  obtain ⟨X', f', hsm, k, hk, V₀, V₁, hV₀, hV₁, hVW, hVsup, hpre₀, hpre₁⟩ :=
    exists_smooth_lift_of_sup_eq_top_preimage (π I n) hnil S.f S.U₀ S.U₁ S.isAffineOpen_U₀
      S.isAffineOpen_U₁ S.isAffineOpen_inf S.sup_eq_top
  have hi' : IsPullback (S.i ≫ k) B.f f' (ρ I (n + 1)) := by
    rw [← ρ_comp_π]
    exact S.isPullback.paste_horiz hk
  have hpreW : k ⁻¹ᵁ (V₀ ⊓ V₁) = S.U₀ ⊓ S.U₁ := by
    rw [Scheme.Hom.preimage_inf, hpre₀, hpre₁]
  have hipre₀ : (S.i ≫ k) ⁻¹ᵁ V₀ = B.U₀ := by
    rw [Scheme.Hom.comp_preimage, hpre₀, S.preimage_U₀]
  have hipre₁ : (S.i ≫ k) ⁻¹ᵁ V₁ = B.U₁ := by
    rw [Scheme.Hom.comp_preimage, hpre₁, S.preimage_U₁]
  have hipreW : (S.i ≫ k) ⁻¹ᵁ (V₀ ⊓ V₁) = B.U₀ ⊓ B.U₁ := by
    rw [Scheme.Hom.preimage_inf, hipre₀, hipre₁]
  -- the reductions on the charts
  have hρsurj : Function.Surjective (Ideal.Quotient.factor
      (Ideal.pow_le_pow_right (by omega : 0 + 1 ≤ n + 1 + 1)) :
        A ⧸ I ^ (n + 1 + 1) →+* A ⧸ I ^ (0 + 1)) :=
    Ideal.Quotient.factor_surjective _
  obtain ⟨hπR, hkR⟩ := appLE_surjective_ker_of_isPullback_specMap _ hsurjπ hk hV₀ hpre₀
  obtain ⟨hπS, hkS⟩ := appLE_surjective_ker_of_isPullback_specMap _ hsurjπ hk hV₁ hpre₁
  obtain ⟨-, hkT⟩ := appLE_surjective_ker_of_isPullback_specMap _ hsurjπ hk hVW hpreW
  obtain ⟨hψR, -⟩ := appLE_surjective_ker_of_isPullback_specMap _ hρsurj hi' hV₀ hipre₀
  obtain ⟨hψS, -⟩ := appLE_surjective_ker_of_isPullback_specMap _ hρsurj hi' hV₁ hipre₁
  obtain ⟨-, hk₀T⟩ := appLE_surjective_ker_of_isPullback_specMap _ hρsurj hi' hVW hipreW
  -- the `A`-algebras of sections over the charts of `X'`
  let : Algebra A Γ(X', V₀) := (cV f' V₀).toAlgebra
  let : Algebra A Γ(X', V₁) := (cV f' V₁).toAlgebra
  let : Algebra A Γ(X', V₀ ⊓ V₁) := (cV f' (V₀ ⊓ V₁)).toAlgebra
  let ρ' : Γ(X', V₀) →ₐ[A] Γ(X', V₀ ⊓ V₁) :=
    { (X'.presheaf.map (homOfLE inf_le_left : V₀ ⊓ V₁ ⟶ V₀).op).hom with
      commutes' := fun a ↦ res_cV f' inf_le_left a }
  let σ' : Γ(X', V₁) →ₐ[A] Γ(X', V₀ ⊓ V₁) :=
    { (X'.presheaf.map (homOfLE inf_le_right : V₀ ⊓ V₁ ⟶ V₁).op).hom with
      commutes' := fun a ↦ res_cV f' inf_le_right a }
  obtain ⟨t', s', ht', hs', hts'⟩ := AmpleLift.exists_lift_mul_eq_one (I ^ (n + 1)) I
    (Λ := A) (T' := Γ(X', V₀ ⊓ V₁))
    (by
      intro x hx
      rw [RingHom.mem_ker]
      change cV f' (V₀ ⊓ V₁) x = 0
      simp only [cV, RingHom.coe_comp, Function.comp_apply]
      rw [(Ideal.Quotient.eq_zero_iff_mem).mpr ((Ideal.pow_le_pow_right
        (by omega : n + 1 + 1 ≤ n + 1 + (n + 1))) (by rw [← pow_add] at hx; exact hx)),
        map_zero, map_zero])
    (by
      intro x hx
      rw [RingHom.mem_ker]
      change cV f' (V₀ ⊓ V₁) x = 0
      simp only [cV, RingHom.coe_comp, Function.comp_apply]
      rw [(Ideal.Quotient.eq_zero_iff_mem).mpr (by rw [← pow_succ] at hx; exact hx), map_zero,
        map_zero])
    ρ' σ' (k.appLE V₀ S.U₀ hpre₀.ge).hom (k.appLE V₁ S.U₁ hpre₁.ge).hom
    (k.appLE (V₀ ⊓ V₁) (S.U₀ ⊓ S.U₁) hpreW.ge).hom
    (S.X.presheaf.map (homOfLE inf_le_left : S.U₀ ⊓ S.U₁ ⟶ S.U₀).op).hom
    (S.X.presheaf.map (homOfLE inf_le_right : S.U₀ ⊓ S.U₁ ⟶ S.U₁).op).hom
    hπR hπS
    (fun x ↦ by
      change (X'.presheaf.map _ ≫ k.appLE _ _ _) x = (k.appLE _ _ _ ≫ S.X.presheaf.map _) x
      rw [Scheme.Hom.map_appLE, Scheme.Hom.appLE_map])
    (fun x ↦ by
      change (X'.presheaf.map _ ≫ k.appLE _ _ _) x = (k.appLE _ _ _ ≫ S.X.presheaf.map _) x
      rw [Scheme.Hom.map_appLE, Scheme.Hom.appLE_map])
    (by rw [hkR, CommRingCat.hom_ofHom, ker_factor_pow, Ideal.map_map]; rfl)
    (by rw [hkS, CommRingCat.hom_ofHom, ker_factor_pow, Ideal.map_map]; rfl)
    (by rw [hkT, CommRingCat.hom_ofHom, ker_factor_pow, Ideal.map_map]; rfl)
    (S.i.appLE S.U₀ B.U₀ S.preimage_U₀.ge).hom (S.i.appLE S.U₁ B.U₁ S.preimage_U₁.ge).hom
    ((S.i ≫ k).appLE (V₀ ⊓ V₁) (B.U₀ ⊓ B.U₁) hipreW.ge).hom
    (B.X.presheaf.map (homOfLE inf_le_left : B.U₀ ⊓ B.U₁ ⟶ B.U₀).op).hom
    (B.X.presheaf.map (homOfLE inf_le_right : B.U₀ ⊓ B.U₁ ⟶ B.U₁).op).hom
    (by
      convert hψR using 1
      ext x
      change (k.appLE _ _ _ ≫ S.i.appLE _ _ _) x = _
      rw [Scheme.Hom.appLE_comp_appLE])
    (by
      convert hψS using 1
      ext x
      change (k.appLE _ _ _ ≫ S.i.appLE _ _ _) x = _
      rw [Scheme.Hom.appLE_comp_appLE])
    (fun x ↦ by
      change (X'.presheaf.map _ ≫ (S.i ≫ k).appLE _ _ _) x =
        (k.appLE _ _ _ ≫ S.i.appLE _ _ _ ≫ B.X.presheaf.map _) x
      rw [Scheme.Hom.map_appLE, Scheme.Hom.appLE_map, Scheme.Hom.appLE_comp_appLE])
    (fun x ↦ by
      change (X'.presheaf.map _ ≫ (S.i ≫ k).appLE _ _ _) x =
        (k.appLE _ _ _ ≫ S.i.appLE _ _ _ ≫ B.X.presheaf.map _) x
      rw [Scheme.Hom.map_appLE, Scheme.Hom.appLE_map, Scheme.Hom.appLE_comp_appLE])
    (by
      rw [hk₀T, CommRingCat.hom_ofHom, ker_factor_pow, Ideal.map_map, zero_add, pow_one]
      rfl)
    S.t S.s S.mul_eq_one
    (fun w₀ ↦ by
      obtain ⟨r, v, hw⟩ := B.H1 w₀
      refine ⟨r, v, ?_⟩
      rw [S.t_eq, S.s_eq]
      exact hw)
  -- the new stage
  have hπs : Function.Surjective (π I n) := surjective_of_isNilpotent_ker _ hnil
  have hks : Function.Surjective k :=
    (MorphismProperty.of_isPullback (P := @Surjective) hk.flip ⟨hπs⟩).surj
  have hbo (V V' : X'.Opens) (W W' : S.X.Opens) (hV : k ⁻¹ᵁ V = W) (hV' : k ⁻¹ᵁ V' = W')
      (r : Γ(X', V)) (hr : S.X.basicOpen (k.appLE V W hV.ge r) ≤ W') : X'.basicOpen r ≤ V' := by
    refine le_of_preimage_le k hks ?_
    rw [hV']
    refine le_trans ?_ hr
    rw [Scheme.basicOpen_appLE]
    exact le_inf ((k.preimage_mono (X'.basicOpen_le r)).trans hV.le) le_rfl
  refine ⟨{
    X := X', f := f', smooth := hsm, U₀ := V₀, U₁ := V₁, isAffineOpen_U₀ := hV₀,
    isAffineOpen_U₁ := hV₁, isAffineOpen_inf := hVW, sup_eq_top := hVsup, t := t', s := s',
    mul_eq_one := hts',
    basicOpen_t_le := hbo V₀ V₁ S.U₀ S.U₁ hpre₀ hpre₁ t' (by
      change S.X.basicOpen ((k.appLE V₀ S.U₀ hpre₀.ge).hom t') ≤ _
      rw [ht']
      exact S.basicOpen_t_le),
    basicOpen_s_le := hbo V₁ V₀ S.U₁ S.U₀ hpre₁ hpre₀ s' (by
      change S.X.basicOpen ((k.appLE V₁ S.U₁ hpre₁.ge).hom s') ≤ _
      rw [hs']
      exact S.basicOpen_s_le),
    i := S.i ≫ k, isPullback := hi', preimage_U₀ := hipre₀, preimage_U₁ := hipre₁,
    t_eq := ?_, s_eq := ?_ }, k, hpre₀, hpre₁, hk, rfl, ht', hs'⟩
  · rw [← Scheme.Hom.appLE_comp_appLE _ _ _ S.U₀ _ hpre₀.ge S.preimage_U₀.ge]
    change (S.i.appLE S.U₀ B.U₀ _).hom ((k.appLE V₀ S.U₀ hpre₀.ge).hom t') = B.t
    rw [ht', S.t_eq]
  · rw [← Scheme.Hom.appLE_comp_appLE _ _ _ S.U₁ _ hpre₁.ge S.preimage_U₁.ge]
    change (S.i.appLE S.U₁ B.U₁ _).hom ((k.appLE V₁ S.U₁ hpre₁.ge).hom s') = B.s
    rw [hs', S.s_eq]

end CurveLift

end SGA.SGA1.ExposeIII
