/-
Copyright (c) 2026 SGAenglishpluslean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SGAenglishpluslean contributors
-/
import SGA.SGA1.ExposeIII.FormalIsomorphism
import Mathlib.RingTheory.Derivation.ToSquareZero
import Mathlib.RingTheory.Flat.EquationalCriterion

/-!
# SGA 1, Exposé III, 5.8: uniqueness of the extension of isomorphisms

Proposition III.5.8 ends: the extension `𝔜 ≅ 𝔛` of `Y₀ ≅ X₀` is unique if
`H⁰(X₀, 𝔤_{X₀/k}) = 0`. The argument is that of III.5.1: two extensions of the same morphism
along a square-zero thickening differ by a section of `𝒢 = ℋom(g₀^* Ω, 𝒥)`
(`eq_of_subsingleton_derivation`), and by III.5.6, since the ideal `𝒥 = 𝔪ⁿ⁺¹ 𝒪 / 𝔪ⁿ⁺² 𝒪` is
`gr^{n+1}(A) ⊗ 𝒪_{Y₀}` with `gr^{n+1}(A)` free over `k` (and `Y` flat),
`H⁰(𝒢) = H⁰(𝒢₀) ⊗ gr^{n+1}(A)` vanishes with `H⁰(𝒢₀) = H⁰(𝔤)`
(`subsingleton_derivation_map_of_flat`).
-/

universe u

open AlgebraicGeometry CategoryTheory CategoryTheory.Limits

namespace SGA.SGA1.ExposeIII

section Rings

/-- III.5.1, uniqueness, for rings: two `R`-algebra maps `C → B` which agree modulo a
square-zero ideal `J` differ by an `R`-derivation `C → J` (for the `C`-module structure given by
`ψ`); if there is no nonzero such derivation, they are equal. -/
theorem eq_of_subsingleton_derivation {R C B : Type*} [CommRing R] [CommRing C] [CommRing B]
    [Algebra R C] [Algebra R B] {J : Ideal B} (hJ : J ^ 2 = ⊥) (ψ ψ' : C →ₐ[R] B)
    (h : ∀ c, ψ' c - ψ c ∈ J)
    (hD : letI := ψ.toRingHom.toAlgebra; Subsingleton (Derivation R C J)) : ψ' = ψ := by
  let := ψ.toRingHom.toAlgebra
  have : IsScalarTower R C B := .of_algebraMap_eq fun r ↦ (ψ.commutes r).symm
  have e : (Ideal.Quotient.mkₐ R J).comp ψ' = IsScalarTower.toAlgHom R C (B ⧸ J) := by
    ext c
    simp only [AlgHom.comp_apply, Ideal.Quotient.mkₐ_eq_mk, IsScalarTower.coe_toAlgHom']
    exact Ideal.Quotient.eq.mpr (h c)
  ext c
  have := congrArg (fun D ↦ (D c : B))
    (Subsingleton.elim (derivationToSquareZeroOfLift J hJ ψ' e) 0)
  simp only [derivationToSquareZeroOfLift_apply, Derivation.zero_apply, ZeroMemClass.coe_zero,
    sub_eq_zero] at this
  exact this

variable {R C B : Type u} [CommRing R] [CommRing C] [CommRing B] [Algebra R C] [Algebra R B]
  [Algebra C B] (m I : Ideal R) {d : ℕ} (e : Fin d → R)

/-- Elements of `I B`, for `I` generated by `e₁, …, e_d`, are sums `∑ eᵢ bᵢ`. -/
lemma exists_eq_sum_of_mem_map (hI : I = Ideal.span (Set.range e)) {x : B}
    (hx : x ∈ I.map (algebraMap R B)) : ∃ b : Fin d → B, x = ∑ i, algebraMap R B (e i) * b i := by
  rw [hI, Ideal.map_span, ← Set.range_comp] at hx
  obtain ⟨b, hb⟩ := (Submodule.mem_span_range_iff_exists_fun B).mp hx
  exact ⟨b, by rw [← hb]; simp [smul_eq_mul, mul_comm]⟩

include e in
/-- The coefficients `bᵢ` in `∑ eᵢ bᵢ` are unique modulo `𝔪 B`, if `B` is flat and the `eᵢ` are
linearly independent modulo `𝔪` (i.e. `I = gr` is free over `R / 𝔪` with basis `(eᵢ)`). -/
lemma sub_mem_of_sum_eq [Module.Flat R B]
    (he : ∀ a : Fin d → R, ∑ i, a i * e i = 0 → ∀ i, a i ∈ m) {b b' : Fin d → B}
    (h : ∑ i, algebraMap R B (e i) * b i = ∑ i, algebraMap R B (e i) * b' i) (i : Fin d) :
    b i - b' i ∈ m.map (algebraMap R B) := by
  have h' : ∑ i, e i • (b i - b' i) = 0 := by
    simp only [Algebra.smul_def, mul_sub, Finset.sum_sub_distrib, h, sub_self]
  obtain ⟨k, a, y, hxy, ha⟩ := Module.Flat.isTrivialRelation_of_sum_smul_eq_zero h'
  have hi : b i - b' i = ∑ l, a i l • y l := hxy i
  rw [hi]
  refine Ideal.sum_mem _ fun l _ ↦ ?_
  rw [Algebra.smul_def]
  refine Ideal.mul_mem_right _ _ (Ideal.mem_map_of_mem _ ?_)
  exact he (fun i ↦ a i l) (by simpa [mul_comm] using ha l) i

/-- III.5.6 for `H⁰`, on affine charts: let `B` be a flat `R`-algebra, `I ⊆ R` an ideal with
`I 𝔪 = 0` which is free over `R / 𝔪` with basis `e₁, …, e_d` (for `R = A / 𝔪ⁿ⁺²` and
`I = 𝔪ⁿ⁺¹ / 𝔪ⁿ⁺²`: `gr^{n+1}(A)` is free over `k`), and `C → B` an `R`-algebra map. If there is
no nonzero `R`-derivation `C → B / 𝔪 B`, there is no nonzero `R`-derivation `C → I B`: indeed
`I B = I ⊗_R B = ⊕ᵢ eᵢ (B / 𝔪 B)`, and each coordinate of a derivation `C → I B` is a derivation
`C → B / 𝔪 B`. -/
theorem subsingleton_derivation_map_of_flat [Module.Flat R B] (hIm : I * m = ⊥)
    (hI : I = Ideal.span (Set.range e)) (he : ∀ a : Fin d → R, ∑ i, a i * e i = 0 → ∀ i, a i ∈ m)
    (h : Subsingleton (Derivation R C (B ⧸ m.map (algebraMap R B)))) :
    Subsingleton (Derivation R C (I.map (algebraMap R B))) := by
  set J := I.map (algebraMap R B)
  set mB := m.map (algebraMap R B)
  have hrep (x : J) := exists_eq_sum_of_mem_map I e hI x.2
  choose b hb using hrep
  have hb_eq (x : J) (b' : Fin d → B) (h' : (x : B) = ∑ i, algebraMap R B (e i) * b' i) (i) :
      Ideal.Quotient.mk mB (b x i) = Ideal.Quotient.mk mB (b' i) :=
    Ideal.Quotient.eq.mpr (sub_mem_of_sum_eq m e he ((hb x).symm.trans h') i)
  suffices H : ∀ D : Derivation R C J, D = 0 from ⟨fun D D' ↦ by rw [H D, H D']⟩
  intro D
  have key (i : Fin d) (c : C) : b (D c) i ∈ mB := by
    let Di : Derivation R C (B ⧸ mB) := Derivation.mk'
      { toFun := fun c ↦ Ideal.Quotient.mk mB (b (D c) i)
        map_add' := fun c c' ↦ by
          rw [hb_eq (D (c + c')) (b (D c) + b (D c')) (by
            rw [D.map_add, Submodule.coe_add, hb (D c), hb (D c'), ← Finset.sum_add_distrib]
            simp [mul_add]) i]
          simp
        map_smul' := fun r c ↦ by
          rw [hb_eq (D (r • c)) (fun j ↦ algebraMap R B r * b (D c) j) (by
            rw [D.map_smul, Submodule.coe_smul_of_tower, hb (D c), Finset.smul_sum]
            simp [Algebra.smul_def, mul_left_comm]) i]
          simp [Algebra.smul_def] }
      fun c c' ↦ by
        change Ideal.Quotient.mk mB (b (D (c * c')) i) =
          c • Ideal.Quotient.mk mB (b (D c') i) + c' • Ideal.Quotient.mk mB (b (D c) i)
        rw [hb_eq (D (c * c')) (fun j ↦ algebraMap C B c * b (D c') j +
            algebraMap C B c' * b (D c) j) (by
          rw [D.leibniz, Submodule.coe_add, Submodule.coe_smul_of_tower,
            Submodule.coe_smul_of_tower, hb (D c'), hb (D c), Finset.smul_sum, Finset.smul_sum,
            ← Finset.sum_add_distrib]
          simp [Algebra.smul_def, mul_add, mul_left_comm]) i]
        simp [Algebra.smul_def]
    have := congrArg (fun D ↦ D c) (Subsingleton.elim Di 0)
    exact Ideal.Quotient.eq_zero_iff_mem.mp this
  ext c
  rw [hb (D c)]
  refine (Finset.sum_eq_zero fun i _ ↦ ?_).trans (by simp)
  have hmem : algebraMap R B (e i) * b (D c) i ∈ J * mB :=
    Ideal.mul_mem_mul (Ideal.mem_map_of_mem _ (hI ▸ Ideal.subset_span ⟨i, rfl⟩)) (key i c)
  rwa [← Ideal.map_mul, hIm, Ideal.map_bot, Ideal.mem_bot] at hmem

omit [Algebra C B] in
/-- Reduction of `H⁰(𝒢₀)` to `H⁰(X₀, 𝔤_{X₀/S₀})`, on affine charts: let `π_R : R → R₀`,
`π_C : C → C₀` be surjective, with `ker π_C ⊆ (ker π_R) C` (for `C₀ = C ⊗_R R₀`), let
`ψ : C → B` be an `R`-algebra map and `θ : B → C₀` a surjection with kernel `(ker π_R) B` and
`θ ∘ ψ = π_C` (for `B ⊗_R R₀ ≅ C₀`, the reduction of `ψ` being an isomorphism). If `C₀` has no
nonzero `R₀`-derivation into itself, then there is no nonzero `R`-derivation `C → B / (ker π_R) B`.
-/
theorem subsingleton_derivation_quotient_of_surjective {R₀ C₀ : Type*} [CommRing R₀]
    [CommRing C₀] [Algebra R₀ C₀] (πR : R →+* R₀) (hπR : Function.Surjective πR)
    (πC : C →+* C₀) (hπC : Function.Surjective πC)
    (hkerC : RingHom.ker πC ≤ (RingHom.ker πR).map (algebraMap R C))
    (hπ : ∀ r, πC (algebraMap R C r) = algebraMap R₀ C₀ (πR r))
    (ψ : C →ₐ[R] B) (θ : B →+* C₀) (hθ : Function.Surjective θ)
    (hkerθ : RingHom.ker θ = (RingHom.ker πR).map (algebraMap R B)) (hθψ : ∀ c, θ (ψ c) = πC c)
    (h : Subsingleton (Derivation R₀ C₀ C₀)) :
    letI := ψ.toRingHom.toAlgebra
    Subsingleton (Derivation R C (B ⧸ (RingHom.ker πR).map (algebraMap R B))) := by
  let := ψ.toRingHom.toAlgebra
  set mB := (RingHom.ker πR).map (algebraMap R B)
  let θ' : B ⧸ mB ≃+* C₀ := (Ideal.quotEquivOfEq hkerθ.symm).trans
    (RingHom.quotientKerEquivOfSurjective hθ)
  have hθ' (b : B) : θ' (Ideal.Quotient.mk mB b) = θ b := rfl
  have hθR (r : R) : θ (algebraMap R B r) = algebraMap R₀ C₀ (πR r) := by
    rw [← ψ.commutes, hθψ, hπ]
  suffices H : ∀ D : Derivation R C (B ⧸ mB), D = 0 from ⟨fun D D' ↦ by rw [H D, H D']⟩
  intro D
  -- `D` vanishes on `(ker π_R) C`, hence on `ker π_C`
  have hvan : ∀ x ∈ (RingHom.ker πR).map (algebraMap R C), D x = 0 := by
    let K : Ideal C :=
      { carrier := {x | D x = 0 ∧ ψ x ∈ mB}
        add_mem' := fun hx hy ↦ ⟨by rw [D.map_add, hx.1, hy.1, add_zero],
          by rw [map_add]; exact add_mem hx.2 hy.2⟩
        zero_mem' := ⟨D.map_zero, by rw [map_zero]; exact zero_mem _⟩
        smul_mem' := fun c x hx ↦ ⟨by
          rw [smul_eq_mul, D.leibniz, hx.1, smul_zero, zero_add, Algebra.smul_def,
            ← Ideal.Quotient.mk_algebraMap, Ideal.Quotient.eq_zero_iff_mem.mpr
            (show algebraMap C B x ∈ mB from hx.2), zero_mul],
          by rw [smul_eq_mul, map_mul]; exact Ideal.mul_mem_left _ _ hx.2⟩ }
    have hle : (RingHom.ker πR).map (algebraMap R C) ≤ K :=
      Ideal.map_le_iff_le_comap.mpr fun r hr ↦ ⟨D.map_algebraMap r, by
        rw [ψ.commutes]; exact Ideal.mem_map_of_mem _ hr⟩
    exact fun x hx ↦ (hle hx).1
  have hD (c c' : C) (hc : πC c = πC c') : D c = D c' := by
    rw [← sub_eq_zero, ← D.map_sub]
    exact hvan _ (hkerC (by rw [RingHom.mem_ker, map_sub, hc, sub_self]))
  -- the induced derivation of `C₀`
  let lift : C₀ → C := Function.surjInv hπC
  have hlift (y : C₀) : πC (lift y) = y := Function.surjInv_eq hπC y
  have hF (c : C) : θ' (D (lift (πC c))) = θ' (D c) := by rw [hD _ _ (hlift _)]
  let F : Derivation R₀ C₀ C₀ := Derivation.mk'
    { toFun := fun y ↦ θ' (D (lift y))
      map_add' := fun y y' ↦ by
        obtain ⟨c, rfl⟩ := hπC y
        obtain ⟨c', rfl⟩ := hπC y'
        rw [← map_add, hF, hF, hF, D.map_add, map_add]
      map_smul' := fun r₀ y ↦ by
        obtain ⟨r, rfl⟩ := hπR r₀
        obtain ⟨c, rfl⟩ := hπC y
        have : πR r • πC c = πC (r • c) := by
          rw [Algebra.smul_def, ← hπ, ← map_mul, ← Algebra.smul_def]
        simp only [RingHom.id_apply]
        rw [this, hF, hF, D.map_smul, Algebra.smul_def, Algebra.smul_def, map_mul,
          ← Ideal.Quotient.mk_algebraMap, hθ', hθR] }
    fun y y' ↦ by
      obtain ⟨c, rfl⟩ := hπC y
      obtain ⟨c', rfl⟩ := hπC y'
      change θ' (D (lift (πC c * πC c'))) =
        πC c • θ' (D (lift (πC c'))) + πC c' • θ' (D (lift (πC c)))
      rw [← map_mul, hF, hF, hF, D.leibniz, map_add, Algebra.smul_def, Algebra.smul_def,
        map_mul, map_mul, ← Ideal.Quotient.mk_algebraMap, ← Ideal.Quotient.mk_algebraMap,
        hθ', hθ']
      simp only [smul_eq_mul]
      rw [show algebraMap C B c = ψ c from rfl, show algebraMap C B c' = ψ c' from rfl, hθψ, hθψ]
  have hF0 : F = 0 := Subsingleton.elim _ _
  ext c
  have := congrArg (fun D : Derivation R₀ C₀ C₀ ↦ D (πC c)) hF0
  simp only [Derivation.zero_apply] at this
  change θ' (D (lift (πC c))) = 0 at this
  rw [hF, map_eq_zero_iff _ θ'.injective] at this
  rw [this, Derivation.zero_apply]

end Rings

section Schemes

/-- The composite `Z₀ → Zₙ` of a sequence of morphisms `Zₙ → Zₙ₊₁`. -/
def seqComp {Z : ℕ → Scheme.{u}} (t : ∀ n, Z n ⟶ Z (n + 1)) : ∀ n, Z 0 ⟶ Z n
  | 0 => 𝟙 _
  | n + 1 => seqComp t n ≫ t n

@[simp]
lemma seqComp_zero {Z : ℕ → Scheme.{u}} (t : ∀ n, Z n ⟶ Z (n + 1)) : seqComp t 0 = 𝟙 _ := rfl

lemma seqComp_succ {Z : ℕ → Scheme.{u}} (t : ∀ n, Z n ⟶ Z (n + 1)) (n : ℕ) :
    seqComp t (n + 1) = seqComp t n ≫ t n := rfl

lemma isPullback_seqComp {S X : ℕ → Scheme.{u}} {s : ∀ n, S n ⟶ S (n + 1)}
    {iX : ∀ n, X n ⟶ X (n + 1)} {p : ∀ n, X n ⟶ S n}
    (hX : ∀ n, IsPullback (iX n) (p n) (p (n + 1)) (s n)) :
    ∀ n, IsPullback (seqComp iX n) (p 0) (p n) (seqComp s n)
  | 0 => IsPullback.id_horiz (p 0)
  | n + 1 => (isPullback_seqComp hX n).paste_horiz (hX n)

lemma isClosedImmersion_seqComp {S : ℕ → Scheme.{u}} (s : ∀ n, S n ⟶ S (n + 1))
    [∀ n, IsClosedImmersion (s n)] : ∀ n, IsClosedImmersion (seqComp s n)
  | 0 => inferInstanceAs (IsClosedImmersion (𝟙 _))
  | n + 1 => by
    have := isClosedImmersion_seqComp s n
    exact inferInstanceAs (IsClosedImmersion (seqComp s n ≫ s n))

lemma seqComp_comp_eq {X Y : ℕ → Scheme.{u}} {iX : ∀ n, X n ⟶ X (n + 1)}
    {iY : ∀ n, Y n ⟶ Y (n + 1)} (e : ∀ n, Y n ⟶ X n)
    (he : ∀ n, iY n ≫ e (n + 1) = e n ≫ iX n) :
    ∀ n, seqComp iY n ≫ e n = e 0 ≫ seqComp iX n
  | 0 => by simp
  | n + 1 => by
    rw [seqComp_succ, seqComp_succ, Category.assoc, he, ← Category.assoc,
      seqComp_comp_eq e he n, Category.assoc]

/-- The kernel of `Γ(X, ⊤) → Γ(X₀, ⊤)` for a base change `X₀ = X ×_Y Y₀` of affine schemes along a
closed immersion is the extension of the kernel of `Γ(Y, ⊤) → Γ(Y₀, ⊤)`. -/
lemma ker_appTop_eq_map_of_isPullback {X Y X₀ Y₀ : Scheme.{u}} {f : X ⟶ Y} {i : Y₀ ⟶ Y}
    {iX : X₀ ⟶ X} {fX : X₀ ⟶ Y₀} (hX : IsPullback iX fX f i) [IsClosedImmersion i] [IsAffine Y]
    [IsAffine X] :
    RingHom.ker iX.appTop.hom = (RingHom.ker i.appTop.hom).map f.appTop.hom := by
  obtain ⟨-, hker⟩ := surjective_appLE_and_ker_eq_map hX (isAffineOpen_top Y)
    (isAffineOpen_top X) le_top
  change RingHom.ker (iX.app ⊤).hom = (RingHom.ker (i.app ⊤).hom).map (f.app ⊤).hom
  rw [Scheme.Hom.app_eq_appLE, Scheme.Hom.app_eq_appLE, hker, Scheme.Hom.app_eq_appLE]
  rfl

lemma surjective_appTop_of_isClosedImmersion {X Y : Scheme.{u}} (i : X ⟶ Y)
    [IsClosedImmersion i] [IsAffine Y] : Function.Surjective i.appTop := by
  have := i.app_surjective ⊤ (isAffineOpen_top Y)
  exact this

set_option backward.isDefEq.respectTransparency false in
/-- III.5.8, uniqueness, for an affine formal scheme `𝔜`: with the notation of
`exists_isoSeq_of_isAffine`, assume `Y` flat over `S` and `gr^{n+1} = ker(Γ(Sₙ₊₁) → Γ(Sₙ))` free
over `Γ(S₀)` (with a basis `(eᵢ)`, and killed by `ker(Γ(Sₙ₊₁) → Γ(S₀))`), as in III.5.6 (in
III.5.8, `Sₙ = Spec (A ⧸ 𝔪ⁿ⁺¹)` and `gr^{n+1} = 𝔪ⁿ⁺¹ / 𝔪ⁿ⁺²` is a `k`-vector space). If
`H⁰(X₀, 𝔤_{X₀/S₀}) = 0`, i.e. the affine `X₀` has no nonzero `Γ(S₀)`-derivation, then two
compatible systems of isomorphisms `Yₙ ≅ Xₙ` over `Sₙ` which agree on `Y₀` are equal. -/
theorem isoSeq_eq_of_isAffine {S : ℕ → Scheme.{u}} (s : ∀ n, S n ⟶ S (n + 1))
    [∀ n, IsAffine (S n)] [∀ n, IsClosedImmersion (s n)]
    (hs : ∀ n, RingHom.ker (s n).appTop.hom ^ 2 = ⊥)
    (hgr : ∀ n, ∃ (d : ℕ) (e : Fin d → Γ(S (n + 1), ⊤)),
      RingHom.ker (s n).appTop.hom = Ideal.span (Set.range e) ∧
      RingHom.ker (s n).appTop.hom * RingHom.ker (seqComp s (n + 1)).appTop.hom = ⊥ ∧
      ∀ a : Fin d → Γ(S (n + 1), ⊤), ∑ i, a i * e i = 0 →
        ∀ i, a i ∈ RingHom.ker (seqComp s (n + 1)).appTop.hom)
    {X Y : ℕ → Scheme.{u}} (p : ∀ n, X n ⟶ S n) (q : ∀ n, Y n ⟶ S n)
    (iX : ∀ n, X n ⟶ X (n + 1)) (iY : ∀ n, Y n ⟶ Y (n + 1))
    (hX : ∀ n, IsPullback (iX n) (p n) (p (n + 1)) (s n))
    (hY : ∀ n, IsPullback (iY n) (q n) (q (n + 1)) (s n))
    [∀ n, Flat (q n)] [∀ n, IsAffine (Y n)]
    (hX₀ : letI := (p 0).appTop.hom.toAlgebra
      Subsingleton (Derivation Γ(S 0, ⊤) Γ(X 0, ⊤) Γ(X 0, ⊤)))
    (e e' : ∀ n, Y n ≅ X n) (he : ∀ n, (e n).hom ≫ p n = q n)
    (he' : ∀ n, (e' n).hom ≫ p n = q n)
    (hec : ∀ n, iY n ≫ (e (n + 1)).hom = (e n).hom ≫ iX n)
    (hec' : ∀ n, iY n ≫ (e' (n + 1)).hom = (e' n).hom ≫ iX n) (h₀ : e 0 = e' 0) :
    e = e' := by
  funext n
  induction n with
  | zero => exact h₀
  | succ n ih =>
  have : IsAffine (X (n + 1)) := .of_isIso (e (n + 1)).inv
  have : IsAffine (X 0) := .of_isIso (e 0).inv
  have := isClosedImmersion_seqComp s (n + 1)
  obtain ⟨d, fam, hI, hIm, hfam⟩ := hgr n
  -- the rings
  let R := Γ(S (n + 1), ⊤)
  let C := Γ(X (n + 1), ⊤)
  let B := Γ(Y (n + 1), ⊤)
  let : Algebra R C := (p (n + 1)).appTop.hom.toAlgebra
  let : Algebra R B := (q (n + 1)).appTop.hom.toAlgebra
  have hcomm (φ : Y (n + 1) ≅ X (n + 1)) (hφ : φ.hom ≫ p (n + 1) = q (n + 1)) (r : R) :
      φ.hom.appTop (algebraMap R C r) = algebraMap R B r := by
    change ((p (n + 1)).appTop ≫ φ.hom.appTop) r = (q (n + 1)).appTop r
    rw [← Scheme.Hom.comp_appTop, hφ]
  let ψ : C →ₐ[R] B := { (e (n + 1)).hom.appTop.hom with commutes' := hcomm _ (he _) }
  let ψ' : C →ₐ[R] B := { (e' (n + 1)).hom.appTop.hom with commutes' := hcomm _ (he' _) }
  have : Module.Flat R B :=
    (HasRingHomProperty.iff_of_isAffine (P := @Flat)).mp (inferInstance : Flat (q (n + 1)))
  -- the ideal of `Yₙ` in `Yₙ₊₁`
  have hJ := ker_appTop_eq_map_of_isPullback (hY n)
  -- the reduction to `S₀`
  let πR := (seqComp s (n + 1)).appTop.hom
  have hYc := isPullback_seqComp hY (n + 1)
  have hXc := isPullback_seqComp hX (n + 1)
  have hecc := seqComp_comp_eq (fun n ↦ (e n).hom) hec (n + 1)
  let : Algebra Γ(S 0, ⊤) Γ(X 0, ⊤) := (p 0).appTop.hom.toAlgebra
  have hsub₀ := subsingleton_derivation_quotient_of_surjective (R := R) (C := C) (B := B)
    πR (surjective_appTop_of_isClosedImmersion _) (seqComp iX (n + 1)).appTop.hom
    (by
      have : IsClosedImmersion (seqComp iX (n + 1)) :=
        MorphismProperty.of_isPullback hXc.flip inferInstance
      exact surjective_appTop_of_isClosedImmersion _)
    (ker_appTop_eq_map_of_isPullback hXc).le
    (fun r ↦ by
      change ((p (n + 1)).appTop ≫ (seqComp iX (n + 1)).appTop) r =
        ((seqComp s (n + 1)).appTop ≫ (p 0).appTop) r
      rw [← Scheme.Hom.comp_appTop, ← Scheme.Hom.comp_appTop, hXc.w])
    ψ ((e 0).inv.appTop.hom.comp (seqComp iY (n + 1)).appTop.hom)
    (by
      have : IsClosedImmersion (seqComp iY (n + 1)) :=
        MorphismProperty.of_isPullback hYc.flip inferInstance
      have h₁ : Function.Surjective (seqComp iY (n + 1)).appTop.hom :=
        surjective_appTop_of_isClosedImmersion (seqComp iY (n + 1))
      have h₂ : Function.Surjective (e 0).inv.appTop.hom :=
        (ConcreteCategory.bijective_of_isIso (e 0).inv.appTop).2
      exact h₂.comp h₁)
    (by
      rw [RingHom.ker_comp_of_injective _ (ConcreteCategory.bijective_of_isIso (e 0).inv.appTop).1]
      exact ker_appTop_eq_map_of_isPullback hYc)
    (fun c ↦ by
      have h : (e (n + 1)).hom.appTop ≫ (seqComp iY (n + 1)).appTop ≫ (e 0).inv.appTop =
          (seqComp iX (n + 1)).appTop := by
        rw [← Category.assoc, ← Scheme.Hom.comp_appTop, hecc, Scheme.Hom.comp_appTop,
          Category.assoc, ← Scheme.Hom.comp_appTop, Iso.inv_hom_id, Scheme.Hom.id_appTop,
          Category.comp_id]
      have h' := congrArg (fun φ ↦ φ.hom c) h
      simp only [CommRingCat.hom_comp, RingHom.comp_apply] at h'
      exact h')
    hX₀
  let := ψ.toRingHom.toAlgebra
  have hsub := subsingleton_derivation_map_of_flat (C := C) (B := B) (RingHom.ker πR)
    (RingHom.ker (s n).appTop.hom) fam hIm hI hfam hsub₀
  have hJ2 : RingHom.ker (iY n).appTop.hom ^ 2 = ⊥ := ker_appTop_sq_of_isPullback (hY n) (hs n)
  have hdiff (c : C) : ψ' c - ψ c ∈ RingHom.ker (iY n).appTop.hom := by
    rw [RingHom.mem_ker, map_sub, sub_eq_zero]
    change ((e' (n + 1)).hom.appTop ≫ (iY n).appTop) c = ((e (n + 1)).hom.appTop ≫ (iY n).appTop) c
    rw [← Scheme.Hom.comp_appTop, ← Scheme.Hom.comp_appTop, hec, hec', ih]
  have hD : Subsingleton (Derivation R C (RingHom.ker (iY n).appTop.hom)) := hJ ▸ hsub
  have hψ := eq_of_subsingleton_derivation hJ2 ψ ψ' hdiff hD
  have happ : (e' (n + 1)).hom.appTop = (e (n + 1)).hom.appTop := by
    ext c
    exact congrArg (fun φ : C →ₐ[R] B ↦ φ c) hψ
  exact (Iso.ext (ext_of_isAffine happ)).symm

end Schemes

end SGA.SGA1.ExposeIII
