/-
Copyright (c) 2026 SGAenglishpluslean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SGAenglishpluslean contributors
-/
import SGA.Foundations.HenselianLifting
import Mathlib.Algebra.Colimit.DirectLimit
import Mathlib.RingTheory.Flat.EquationalCriterion
import Mathlib.RingTheory.Flat.Localization
import Mathlib.RingTheory.Smooth.Flat
import Mathlib.RingTheory.Unramified.LocalRing

/-!
# Henselization and strict henselization of a local ring

Let `R` be a ring and `K` a field with a ring map `R → K`, i.e. a `K`-point `Spec K → Spec R`. A
*pointed étale neighbourhood* of this point is an étale `R`-algebra `S` with an `R`-algebra map
`S → K`. By the local structure of étale algebras (Stacks 00UE) the standard étale ones,
`S = R[X, 1/g]/(f)` with `f` monic and `f'` invertible in `S`, are cofinal; a point of such an `S`
is a root `x ∈ K` of `f` with `g(x) ≠ 0`. We index neighbourhoods by such pairs
(`IsLocalRing.EtaleNbhd R K`), so that the index type lives in the universe of `R`.

For a neighbourhood `N` let `N.Stalk` be the local ring of `S` at the kernel of `S → K`. Maps of
pointed local rings `N.Stalk → N'.Stalk` are unique when they exist (two maps from an unramified
algebra into a local ring that agree on the residue field coincide), so neighbourhoods form a
directed preorder and the local rings form a directed system. Its colimit is

* `IsLocalRing.StrictHenselization R K`: for `K` separably closed, the strict henselization of the
  local ring of `R` at the image of the point, with respect to the separable closure of its residue
  field in `K` (Stacks, Section 04GN and 0BSK; EGA IV 18.8). Its properties are proved below for
  `R` local and `R → K` local; see also `SGA.Foundations.StrictHenselization`;
* `IsLocalRing.Henselization R := StrictHenselization R (ResidueField R)` for `R` local: the
  henselization (Stacks, Section 04GN; EGA IV 18.6).

## Main results

For any `K`:
* `StrictHenselization.henselianLocalRing`: the colimit is a henselian local ring;
* `StrictHenselization.pointHom`, `ker_pointHom`: its residue field embeds into `K`;
* `StrictHenselization.flat`: it is flat over `R` (a filtered colimit of flat algebras);
* `StrictHenselization.liftEquiv`: for a henselian local `R`-algebra `A`, the maps to `A` are the
  maps to the residue field of `A`.

For `R` local and `R → K` local:
* `StrictHenselization.map_maximalIdeal`: the maximal ideal is generated by that of `R`;
* `R → StrictHenselization R K` is local and faithfully flat (`StrictHenselization.faithfullyFlat`);
* `StrictHenselization.liftEquivResidueField`: universal property, maps to a henselian local
  `R`-algebra `A` correspond to maps of residue fields.

For the henselization:
* `Henselization.residueFieldEquiv`: its residue field is that of `R`;
* `Henselization.lift`, `Henselization.algHom_ext`: it is initial among henselian local rings
  under `R` (with local structure map).

That the (strict) henselization of a noetherian local ring is noetherian (Stacks 06LJ) is proved
in `SGA.Foundations.HenselizationNoetherian` (`IsLocalRing.StrictHenselization.isNoetherianRing`).
-/

universe u

open Polynomial IsLocalRing TensorProduct

noncomputable section

namespace IsLocalRing

variable (R : Type u) [CommRing R] (K : Type u) [Field K] [Algebra R K]

/-- A pointed standard étale neighbourhood of the `K`-point `Spec K → Spec R`. -/
structure EtaleNbhd where
  /-- The standard étale pair `(f, g)`: the neighbourhood is `Spec R[X, 1/g]/(f)`. -/
  pair : StandardEtalePair R
  /-- The `K`-point of the neighbourhood: a root of `f` in `K` at which `g` does not vanish. -/
  point : K
  hasMap : pair.HasMap point

namespace EtaleNbhd

variable {R K} (N : EtaleNbhd R K)

/-- The `K`-point of a neighbourhood, as an `R`-algebra map. -/
def toField : N.pair.Ring →ₐ[R] K := N.pair.lift N.point N.hasMap

@[simp]
lemma toField_X : N.toField N.pair.X = N.point := N.pair.lift_X _ _

/-- The prime ideal of the neighbourhood at its point. -/
def prime : Ideal N.pair.Ring := RingHom.ker N.toField

instance : N.prime.IsPrime := RingHom.ker_isPrime _

lemma mem_prime {s : N.pair.Ring} : s ∈ N.prime ↔ N.toField s = 0 := RingHom.mem_ker

/-- The local ring of the neighbourhood at its point. -/
abbrev Stalk : Type u := Localization.AtPrime N.prime

/-- The `K`-point of a neighbourhood, as an `R`-algebra map from its local ring. -/
def pointHom : N.Stalk →ₐ[R] K :=
  IsLocalization.liftAlgHom (M := N.prime.primeCompl) (f := N.toField) fun s ↦
    isUnit_iff_ne_zero.mpr fun h ↦ s.2 (N.mem_prime.mpr h)

@[simp]
lemma pointHom_algebraMap (s : N.pair.Ring) :
    N.pointHom (algebraMap N.pair.Ring N.Stalk s) = N.toField s :=
  IsLocalization.lift_eq _ _

lemma pointHom_comp_algebraMap :
    N.pointHom.comp (IsScalarTower.toAlgHom R N.pair.Ring N.Stalk) = N.toField := by
  ext; simp

lemma pointHom_eq_zero_iff (x : N.Stalk) : N.pointHom x = 0 ↔ x ∈ maximalIdeal N.Stalk := by
  constructor
  · intro h
    by_contra hx
    have : IsUnit (N.pointHom x) := ((mem_maximalIdeal x).not.mp hx |> not_not.mp).map _
    exact this.ne_zero h
  · intro hx
    rw [← Localization.AtPrime.map_eq_maximalIdeal] at hx
    have : Ideal.map (algebraMap N.pair.Ring N.Stalk) N.prime ≤ RingHom.ker N.pointHom := by
      rw [Ideal.map_le_iff_le_comap]
      intro s hs
      simpa [Ideal.mem_comap, RingHom.mem_ker, N.mem_prime] using hs
    exact this hx

lemma ker_pointHom : RingHom.ker N.pointHom = maximalIdeal N.Stalk :=
  Ideal.ext N.pointHom_eq_zero_iff

lemma isUnit_iff_pointHom_ne_zero (x : N.Stalk) : IsUnit x ↔ N.pointHom x ≠ 0 := by
  rw [ne_eq, pointHom_eq_zero_iff, mem_maximalIdeal, mem_nonunits_iff, not_not]

instance [IsLocalHom (algebraMap R K)] : IsLocalHom (algebraMap R N.Stalk) where
  map_nonunit r hr := by
    rw [isUnit_iff_pointHom_ne_zero, AlgHom.commutes] at hr
    exact isUnit_of_map_unit (algebraMap R K) r (isUnit_iff_ne_zero.mpr hr)

lemma pointHom_eq_iff (x y : N.Stalk) :
    N.pointHom x = N.pointHom y ↔ residue N.Stalk x = residue N.Stalk y := by
  rw [← sub_eq_zero, ← map_sub, pointHom_eq_zero_iff, ← sub_eq_zero, ← map_sub,
    residue_eq_zero_iff]

/-- Two `R`-algebra maps from the local ring of a neighbourhood to a local ring `A` which agree
on the residue field of `A` are equal. -/
lemma algHom_ext {A : Type*} [CommRing A] [IsLocalRing A] [Algebra R A]
    {φ ψ : N.Stalk →ₐ[R] A} (h : ∀ x, residue A (φ x) = residue A (ψ x)) : φ = ψ :=
  Algebra.FormallyUnramified.algHom_ext_of_residue h

/-- Two `R`-algebra maps from a neighbourhood to a local ring `A` which agree on the residue
field of `A` are equal. -/
lemma algHom_ext' {A : Type*} [CommRing A] [IsLocalRing A] [Algebra R A]
    {φ ψ : N.pair.Ring →ₐ[R] A} (h : ∀ x, residue A (φ x) = residue A (ψ x)) : φ = ψ :=
  Algebra.FormallyUnramified.algHom_ext_of_residue h

/-- Neighbourhoods are preordered by the existence of a morphism of pointed local rings; such a
morphism is unique (`EtaleNbhd.hom_ext`). -/
instance : Preorder (EtaleNbhd R K) where
  le N N' := ∃ φ : N.Stalk →ₐ[R] N'.Stalk, N'.pointHom.comp φ = N.pointHom
  le_refl N := ⟨AlgHom.id R _, AlgHom.comp_id _⟩
  le_trans := fun _ _ _ ⟨φ, hφ⟩ ⟨ψ, hψ⟩ ↦ ⟨ψ.comp φ, by rw [← AlgHom.comp_assoc, hψ, hφ]⟩

lemma le_def {N N' : EtaleNbhd R K} :
    N ≤ N' ↔ ∃ φ : N.Stalk →ₐ[R] N'.Stalk, N'.pointHom.comp φ = N.pointHom := Iff.rfl

lemma hom_ext {N N' : EtaleNbhd R K} {φ ψ : N.Stalk →ₐ[R] N'.Stalk}
    (hφ : N'.pointHom.comp φ = N.pointHom) (hψ : N'.pointHom.comp ψ = N.pointHom) : φ = ψ :=
  algHom_ext _ fun x ↦ by
    rw [← pointHom_eq_iff, ← AlgHom.comp_apply, hφ, ← AlgHom.comp_apply, hψ]

/-- The transition map between the local rings of two comparable neighbourhoods. -/
def transition (N N' : EtaleNbhd R K) (h : N ≤ N') : N.Stalk →ₐ[R] N'.Stalk := h.choose

@[simp]
lemma pointHom_comp_transition {N N' : EtaleNbhd R K} (h : N ≤ N') :
    N'.pointHom.comp (transition N N' h) = N.pointHom := h.choose_spec

@[simp]
lemma pointHom_transition {N N' : EtaleNbhd R K} (h : N ≤ N') (x : N.Stalk) :
    N'.pointHom (transition N N' h x) = N.pointHom x :=
  DFunLike.congr_fun (pointHom_comp_transition h) x

lemma transition_eq {N N' : EtaleNbhd R K} (h : N ≤ N') (φ : N.Stalk →ₐ[R] N'.Stalk)
    (hφ : N'.pointHom.comp φ = N.pointHom) : transition N N' h = φ :=
  hom_ext (pointHom_comp_transition h) hφ

instance : DirectedSystem (fun N : EtaleNbhd R K ↦ N.Stalk) (transition · · ·) where
  map_self N x := by
    rw [transition_eq le_rfl (AlgHom.id R _) (AlgHom.comp_id _)]
    rfl
  map_map {N₃ N₂ N₁} h₁₂ h₂₃ x := by
    rw [transition_eq (h₁₂.trans h₂₃) ((transition N₂ N₃ h₂₃).comp (transition N₁ N₂ h₁₂))
      (by rw [← AlgHom.comp_assoc, pointHom_comp_transition, pointHom_comp_transition])]
    rfl

lemma transition_comp_algebraMap {N N' : EtaleNbhd R K} (h : N ≤ N')
    (ψ : N.pair.Ring →ₐ[R] N'.Stalk) (hψ : N'.pointHom.comp ψ = N.toField) :
    (transition N N' h).comp (IsScalarTower.toAlgHom R N.pair.Ring N.Stalk) = ψ :=
  algHom_ext' _ fun s ↦ by
    rw [← pointHom_eq_iff, ← AlgHom.comp_apply N'.pointHom ψ, hψ]
    simp

/-- A map of pointed algebras from a neighbourhood to the local ring of another neighbourhood
compares them. -/
lemma le_of_algHom {N N' : EtaleNbhd R K} (ψ : N.pair.Ring →ₐ[R] N'.Stalk)
    (hψ : N'.pointHom.comp ψ = N.toField) : N ≤ N' := by
  have hunit (s : N.prime.primeCompl) : IsUnit (ψ s) := by
    rw [isUnit_iff_pointHom_ne_zero, ← AlgHom.comp_apply, hψ, ne_eq, ← N.mem_prime]
    exact s.2
  refine ⟨IsLocalization.liftAlgHom (M := N.prime.primeCompl) hunit, ?_⟩
  apply IsLocalization.algHom_ext N.prime.primeCompl
  refine AlgHom.ext fun s ↦ ?_
  change N'.pointHom (IsLocalization.liftAlgHom hunit (algebraMap N.pair.Ring N.Stalk s)) =
    N.pointHom (algebraMap N.pair.Ring N.Stalk s)
  rw [IsLocalization.liftAlgHom_apply, IsLocalization.lift_eq, pointHom_algebraMap, ← hψ]
  rfl

/-- Every étale `R`-algebra with a `K`-point maps to a pointed standard étale neighbourhood
(Stacks 00UE, local structure of étale algebras). -/
theorem exists_algHom_of_etale {T : Type*} [CommRing T] [Algebra R T] [Algebra.Etale R T]
    (τ : T →ₐ[R] K) : ∃ (N : EtaleNbhd R K) (φ : T →ₐ[R] N.pair.Ring), N.toField.comp φ = τ := by
  let Q := RingHom.ker τ
  have : Q.IsPrime := RingHom.ker_isPrime _
  obtain ⟨t, htQ, ht⟩ := Algebra.IsEtaleAt.exists_isStandardEtale (R := R) Q
  have hτt : IsUnit (τ t) := isUnit_iff_ne_zero.mpr fun h ↦ htQ (RingHom.mem_ker.mpr h)
  let τt : Localization.Away t →ₐ[R] K := IsLocalization.Away.liftAlgHom t hτt
  obtain ⟨P⟩ := ht.nonempty_standardEtalePresentation
  let N : EtaleNbhd R K := ⟨P.P, τt P.x, P.hasMap.map τt⟩
  refine ⟨N, P.equivRing.toAlgHom.comp (IsScalarTower.toAlgHom R T (Localization.Away t)), ?_⟩
  have key : N.toField.comp P.equivRing.toAlgHom = τt := P.hom_ext (by
    change N.toField (P.equivRing P.x) = _
    rw [P.equivRing_x]
    exact N.toField_X)
  refine AlgHom.ext fun s ↦ ?_
  have := DFunLike.congr_fun key (algebraMap T (Localization.Away t) s)
  simpa [τt] using this

instance : IsDirectedOrder (EtaleNbhd R K) where
  directed N₁ N₂ := by
    let T := N₁.pair.Ring ⊗[R] N₂.pair.Ring
    have : Algebra.Etale R T := Algebra.Etale.comp R N₁.pair.Ring T
    obtain ⟨N, φ, hφ⟩ := exists_algHom_of_etale
      (Algebra.TensorProduct.lift N₁.toField N₂.toField fun _ _ ↦ .all _ _)
    refine ⟨N, le_of_algHom ((IsScalarTower.toAlgHom R _ N.Stalk).comp
      (φ.comp Algebra.TensorProduct.includeLeft)) ?_, le_of_algHom ((IsScalarTower.toAlgHom R _
      N.Stalk).comp (φ.comp Algebra.TensorProduct.includeRight)) ?_⟩
    · refine AlgHom.ext fun s ↦ ?_
      have := DFunLike.congr_fun hφ (s ⊗ₜ 1)
      simpa using this
    · refine AlgHom.ext fun s ↦ ?_
      have := DFunLike.congr_fun hφ (1 ⊗ₜ s)
      simpa using this

/-- The local ring of a neighbourhood has the lifting property with respect to henselian local
rings: an `R`-algebra map to the residue field of a henselian local ring `A` lifts uniquely to
`A` (Stacks 04GG). -/
theorem existsUnique_lift {A : Type*} [CommRing A] [HenselianLocalRing A] [Algebra R A]
    (τ : N.Stalk →ₐ[R] ResidueField A) :
    ∃! φ : N.Stalk →ₐ[R] A, (IsScalarTower.toAlgHom R A (ResidueField A)).comp φ = τ := by
  obtain ⟨φ₀, hφ₀⟩ := HenselianLocalRing.exists_algHom_lift
    (τ.comp (IsScalarTower.toAlgHom R N.pair.Ring N.Stalk))
  have hφ₀' (s : N.pair.Ring) : residue A (φ₀ s) = τ (algebraMap N.pair.Ring N.Stalk s) := by
    simpa using DFunLike.congr_fun hφ₀ s
  have hunit (s : N.prime.primeCompl) : IsUnit (φ₀ s) := by
    rw [← residue_ne_zero_iff_isUnit, hφ₀']
    exact ((IsLocalization.map_units N.Stalk s).map τ).ne_zero
  have hres : (IsScalarTower.toAlgHom R A (ResidueField A)).comp
      (IsLocalization.liftAlgHom (M := N.prime.primeCompl) hunit) = τ := by
    apply IsLocalization.algHom_ext N.prime.primeCompl
    refine AlgHom.ext fun s ↦ ?_
    change algebraMap A (ResidueField A) (IsLocalization.liftAlgHom hunit
      (algebraMap N.pair.Ring N.Stalk s)) = τ (algebraMap N.pair.Ring N.Stalk s)
    rw [IsLocalization.liftAlgHom_apply, IsLocalization.lift_eq]
    exact hφ₀' s
  refine ⟨_, hres, fun φ hφ ↦ algHom_ext _ fun x ↦ ?_⟩
  have h₁ := DFunLike.congr_fun hφ x
  have h₂ := DFunLike.congr_fun hres x
  simp only [AlgHom.comp_apply, IsScalarTower.coe_toAlgHom', ResidueField.algebraMap_eq] at h₁ h₂
  rw [h₁, h₂]

/-- The trivial neighbourhood `Spec R[X]/(X)` with the point `0`. -/
def trivial : EtaleNbhd R K :=
  ⟨⟨X, monic_X, 1, 1, 0, 0, by simp⟩, 0, by simp [StandardEtalePair.HasMap]⟩

instance : Nonempty (EtaleNbhd R K) := ⟨trivial⟩

end EtaleNbhd

/-- The colimit of the local rings of the pointed étale neighbourhoods of the `K`-point
`Spec K → Spec R`: the *strict henselization* of `R` with respect to `K` (Stacks, Section 04GN
and 0BSK; EGA IV 18.8). When `K` is separably closed this is the strict henselization of the
local ring of `R` at the image of the point, with respect to the separable closure of its residue
field in `K`; when `K` is the residue field of the local ring `R`, it is the henselization of `R`
(`IsLocalRing.Henselization`). -/
def StrictHenselization : Type u :=
  DirectLimit (fun N : EtaleNbhd R K ↦ N.Stalk) EtaleNbhd.transition

namespace StrictHenselization

variable {R K}

instance : CommRing (StrictHenselization R K) :=
  inferInstanceAs (CommRing (DirectLimit (fun N : EtaleNbhd R K ↦ N.Stalk) _))

instance : Algebra R (StrictHenselization R K) :=
  inferInstanceAs (Algebra R (DirectLimit (fun N : EtaleNbhd R K ↦ N.Stalk) _))

/-- The canonical map from the local ring of a neighbourhood to the colimit. -/
def of (N : EtaleNbhd R K) : N.Stalk →ₐ[R] StrictHenselization R K :=
  DirectLimit.Algebra.of _ EtaleNbhd.transition N

@[simp]
lemma of_transition {N N' : EtaleNbhd R K} (h : N ≤ N') (x : N.Stalk) :
    of N' (EtaleNbhd.transition N N' h x) = of N x :=
  DirectLimit.Algebra.of_f h x

lemma of_comp_transition {N N' : EtaleNbhd R K} (h : N ≤ N') :
    (of N').comp (EtaleNbhd.transition N N' h) = of N :=
  AlgHom.ext (of_transition h)

lemma exists_of (z : StrictHenselization R K) : ∃ N x, of N x = z := by
  obtain ⟨N, x, rfl⟩ := DirectLimit.exists_eq_mk _ z
  exact ⟨N, x, rfl⟩

@[elab_as_elim]
lemma induction_on {C : StrictHenselization R K → Prop} (z : StrictHenselization R K)
    (h : ∀ N x, C (of N x)) : C z := by
  obtain ⟨N, x, rfl⟩ := exists_of z
  exact h N x

lemma of_eq_of_iff {N : EtaleNbhd R K} (x y : N.Stalk) :
    of N x = of N y ↔ ∃ N' h, EtaleNbhd.transition N N' h x = EtaleNbhd.transition N N' h y := by
  change (⟦⟨N, x⟩⟧ : DirectLimit _ _) = ⟦⟨N, y⟩⟧ ↔ _
  rw [Quotient.eq]
  constructor
  · rintro ⟨N', h₁, h₂, e⟩
    exact ⟨N', h₁, e⟩
  · rintro ⟨N', h, e⟩
    exact ⟨N', h, h, e⟩

lemma of_eq_zero_iff {N : EtaleNbhd R K} (x : N.Stalk) :
    of N x = 0 ↔ ∃ N' h, EtaleNbhd.transition N N' h x = 0 := by
  rw [← map_zero (of N), of_eq_of_iff]
  simp

/-- Maps out of the colimit. -/
def lift {A : Type*} [CommRing A] [Algebra R A] (φ : ∀ N : EtaleNbhd R K, N.Stalk →ₐ[R] A)
    (hφ : ∀ N N' (h : N ≤ N') x, φ N' (EtaleNbhd.transition N N' h x) = φ N x) :
    StrictHenselization R K →ₐ[R] A :=
  DirectLimit.Algebra.lift _ EtaleNbhd.transition A φ hφ

@[simp]
lemma lift_of {A : Type*} [CommRing A] [Algebra R A] (φ : ∀ N : EtaleNbhd R K, N.Stalk →ₐ[R] A)
    (hφ) (N : EtaleNbhd R K) (x : N.Stalk) : lift φ hφ (of N x) = φ N x := rfl

@[ext]
lemma algHom_ext {A : Type*} [CommRing A] [Algebra R A] {φ ψ : StrictHenselization R K →ₐ[R] A}
    (h : ∀ N, φ.comp (of N) = ψ.comp (of N)) : φ = ψ :=
  DirectLimit.Algebra.hom_ext (P := A) h

/-- The `K`-point of the strict henselization. -/
def pointHom : StrictHenselization R K →ₐ[R] K :=
  lift (fun N ↦ N.pointHom) fun _ _ h x ↦ EtaleNbhd.pointHom_transition h x

@[simp]
lemma pointHom_of (N : EtaleNbhd R K) (x : N.Stalk) : pointHom (of N x) = N.pointHom x := rfl

lemma isUnit_iff_pointHom_ne_zero (z : StrictHenselization R K) :
    IsUnit z ↔ pointHom z ≠ 0 := by
  refine ⟨fun h ↦ (h.map pointHom).ne_zero, fun h ↦ ?_⟩
  obtain ⟨N, x, rfl⟩ := exists_of z
  rw [pointHom_of, ← EtaleNbhd.isUnit_iff_pointHom_ne_zero] at h
  exact h.map _

instance : Nontrivial (StrictHenselization R K) :=
  pointHom.domain_nontrivial

instance : IsLocalRing (StrictHenselization R K) where
  isUnit_or_isUnit_of_add_one {a b} hab := by
    simp only [isUnit_iff_pointHom_ne_zero]
    by_contra! h
    have := congrArg pointHom hab
    rw [map_add, h.1, h.2, add_zero, map_one] at this
    exact zero_ne_one this

lemma pointHom_eq_zero_iff (z : StrictHenselization R K) :
    pointHom z = 0 ↔ z ∈ maximalIdeal (StrictHenselization R K) := by
  rw [mem_maximalIdeal, mem_nonunits_iff, isUnit_iff_pointHom_ne_zero, not_not]

lemma ker_pointHom : RingHom.ker (pointHom : StrictHenselization R K →ₐ[R] K) =
    maximalIdeal (StrictHenselization R K) :=
  Ideal.ext pointHom_eq_zero_iff

instance (N : EtaleNbhd R K) : IsLocalHom (of N) where
  map_nonunit x hx := by
    rw [isUnit_iff_pointHom_ne_zero, pointHom_of] at hx
    rwa [EtaleNbhd.isUnit_iff_pointHom_ne_zero]

instance [IsLocalHom (algebraMap R K)] : IsLocalHom (algebraMap R (StrictHenselization R K)) where
  map_nonunit r hr := by
    rw [isUnit_iff_pointHom_ne_zero, AlgHom.commutes] at hr
    exact isUnit_of_map_unit (algebraMap R K) r (isUnit_iff_ne_zero.mpr hr)

/-- Finitely many elements of the colimit come from the local ring of a single neighbourhood. -/
lemma exists_of_finite {ι : Type*} [Finite ι] (z : ι → StrictHenselization R K) :
    ∃ (N : EtaleNbhd R K) (x : ι → N.Stalk), ∀ i, of N (x i) = z i := by
  classical
  have := Fintype.ofFinite ι
  choose N x hx using fun i ↦ exists_of (z i)
  obtain ⟨M, hM⟩ := (Finset.univ.image N).exists_le
  have hle (i : ι) : N i ≤ M := hM _ (Finset.mem_image_of_mem _ (Finset.mem_univ i))
  exact ⟨M, fun i ↦ EtaleNbhd.transition _ _ (hle i) (x i), fun i ↦ by simp [hx]⟩

/-- Finitely many elements of the colimit come from a single neighbourhood (not only from its
local ring). -/
lemma exists_of_algebraMap {ι : Type*} [Finite ι] (z : ι → StrictHenselization R K) :
    ∃ (N : EtaleNbhd R K) (y : ι → N.pair.Ring),
      ∀ i, of N (algebraMap N.pair.Ring N.Stalk (y i)) = z i := by
  classical
  have := Fintype.ofFinite ι
  obtain ⟨N, x, hx⟩ := exists_of_finite z
  choose a s hs using fun i ↦ IsLocalization.exists_mk'_eq N.prime.primeCompl (x i)
  let t : N.pair.Ring := ∏ i, (s i : N.pair.Ring)
  have ht : t ∈ N.prime.primeCompl := by
    simpa [t] using (∏ i, s i).2
  have hτt : IsUnit (N.toField t) :=
    isUnit_iff_ne_zero.mpr fun h ↦ ht (N.mem_prime.mpr h)
  let T := Localization.Away t
  obtain ⟨N', φ, hφ⟩ := EtaleNbhd.exists_algHom_of_etale (IsLocalization.Away.liftAlgHom
    (S := T) t hτt)
  let ψ : N.pair.Ring →ₐ[R] N'.Stalk := (IsScalarTower.toAlgHom R _ N'.Stalk).comp
    (φ.comp (IsScalarTower.toAlgHom R N.pair.Ring T))
  have hψ : N'.pointHom.comp ψ = N.toField := by
    refine AlgHom.ext fun r ↦ ?_
    have := DFunLike.congr_fun hφ (algebraMap N.pair.Ring T r)
    simp only [AlgHom.comp_apply, IsLocalization.Away.coe_liftAlgHom,
      IsLocalization.Away.lift_eq] at this
    simp [ψ, this]
  have hle : N ≤ N' := EtaleNbhd.le_of_algHom ψ hψ
  have htr := EtaleNbhd.transition_comp_algebraMap hle ψ hψ
  have hsT (i : ι) : IsUnit (algebraMap N.pair.Ring T (s i)) :=
    isUnit_of_dvd_unit (map_dvd _ (Finset.dvd_prod_of_mem (fun i ↦ (s i : N.pair.Ring))
      (Finset.mem_univ i))) (IsLocalization.Away.algebraMap_isUnit t)
  refine ⟨N', fun i ↦ φ (algebraMap _ T (a i) * ↑(hsT i).unit⁻¹), fun i ↦ ?_⟩
  rw [← hx i, ← of_transition hle, ← hs i]
  congr 1
  have hψs : IsUnit (ψ (s i)) := (hsT i).map ((IsScalarTower.toAlgHom R _ N'.Stalk).comp φ)
  apply hψs.mul_right_cancel
  have e₁ : EtaleNbhd.transition N N' hle (IsLocalization.mk' N.Stalk (a i) (s i)) * ψ (s i) =
      ψ (a i) := by
    rw [← htr, AlgHom.comp_apply, AlgHom.comp_apply, ← map_mul]
    congr 1
    exact IsLocalization.mk'_spec _ _ _
  rw [e₁]
  simp only [ψ, AlgHom.comp_apply, IsScalarTower.coe_toAlgHom', ← map_mul]
  congr 2
  rw [mul_assoc, IsUnit.val_inv_mul, mul_one]

/-- The points of the strict henselization with values in étale `R`-algebras are the `K`-points:
for `B` étale over `R`, composition with the point is a bijection
`(B →ₐ[R] StrictHenselization R K) ≃ (B →ₐ[R] K)`. Geometrically, the fibre at the point
`Spec K → Spec R` of an étale `R`-scheme `Spec B` is the set of its sections over
`Spec (StrictHenselization R K)`; this is the relation between the strict henselization and the
fibre functors of the étale site (`AlgebraicGeometry.Scheme.pointSmallEtale`). -/
def algHomEquivPoint (B : Type*) [CommRing B] [Algebra R B] [Algebra.Etale R B] :
    (B →ₐ[R] StrictHenselization R K) ≃ (B →ₐ[R] K) :=
  Equiv.ofBijective (fun φ ↦ pointHom.comp φ) <| by
    refine ⟨fun φ ψ h ↦ Algebra.FormallyUnramified.algHom_ext_of_residue fun b ↦ ?_,
      fun τ ↦ ?_⟩
    · rw [← sub_eq_zero, ← map_sub, residue_eq_zero_iff, ← pointHom_eq_zero_iff, map_sub,
        sub_eq_zero]
      exact DFunLike.congr_fun h b
    · obtain ⟨N, φ, hφ⟩ := EtaleNbhd.exists_algHom_of_etale τ
      refine ⟨(of N).comp ((IsScalarTower.toAlgHom R N.pair.Ring N.Stalk).comp φ), ?_⟩
      rw [← hφ]
      ext b
      simp

@[simp]
lemma algHomEquivPoint_apply (B : Type*) [CommRing B] [Algebra R B] [Algebra.Etale R B]
    (φ : B →ₐ[R] StrictHenselization R K) (b : B) :
    algHomEquivPoint B φ b = pointHom (φ b) := rfl

section IsLocalRing

variable [IsLocalRing R] [IsLocalHom (algebraMap R K)]

/-- The maximal ideal of the strict henselization is generated by the maximal ideal of `R`
(Stacks, Section 04GN; EGA IV 18.6). -/
theorem map_maximalIdeal :
    (maximalIdeal R).map (algebraMap R (StrictHenselization R K)) =
      maximalIdeal (StrictHenselization R K) := by
  apply le_antisymm
  · rw [Ideal.map_le_iff_le_comap]
    intro r hr
    exact (mem_maximalIdeal _).mpr fun hu ↦ hr (isUnit_of_map_unit _ r hu)
  · intro z hz
    obtain ⟨N, x, rfl⟩ := exists_of z
    have hx : x ∈ maximalIdeal N.Stalk := by
      rwa [← EtaleNbhd.pointHom_eq_zero_iff, ← pointHom_of, pointHom_eq_zero_iff]
    rw [← Algebra.FormallyUnramified.map_maximalIdeal (R := R)] at hx
    have hle : (maximalIdeal R).map (algebraMap R N.Stalk) ≤
        ((maximalIdeal R).map (algebraMap R (StrictHenselization R K))).comap (of N) := by
      rw [Ideal.map_le_iff_le_comap]
      intro r hr
      rw [Ideal.mem_comap, Ideal.mem_comap, AlgHom.commutes]
      exact Ideal.mem_map_of_mem _ hr
    exact hle hx

end IsLocalRing

/-- The strict henselization is flat over `R` (Stacks, Section 04GN): it is a filtered colimit of
flat `R`-algebras. -/
instance flat : Module.Flat R (StrictHenselization R K) := by
  refine Module.Flat.of_forall_isTrivialRelation fun {l f x} hfx ↦ ?_
  obtain ⟨N, y, hy⟩ := exists_of_finite x
  have h0 : of N (∑ i, f i • y i) = 0 := by
    simp [map_sum, hy, hfx]
  obtain ⟨N', h, h'⟩ := (of_eq_zero_iff _).mp h0
  have hrel : ∑ i, f i • EtaleNbhd.transition N N' h (y i) = 0 := by
    simpa [map_sum] using h'
  obtain ⟨k, a, z, hz, ha⟩ := Module.Flat.isTrivialRelation_of_sum_smul_eq_zero hrel
  refine ⟨k, a, fun j ↦ of N' (z j), fun i ↦ ?_, ha⟩
  rw [← hy i, ← of_transition h, show EtaleNbhd.transition N N' h (y i) = _ from hz i, map_sum]
  simp

/-- The strict henselization is a henselian local ring (Stacks, Section 04GN): a monic
polynomial with a simple root modulo the maximal ideal comes from a neighbourhood `N`, and adjoining
the root to `N` gives a standard étale algebra over `N`, hence a larger neighbourhood, in which the
root exists. -/
instance henselianLocalRing : HenselianLocalRing (StrictHenselization R K) where
  is_henselian f hf a₀ h₁ h₂ := by
    classical
    obtain ⟨N, y, hy⟩ := exists_of_algebraMap
      (fun i : Option (Fin f.natDegree) ↦ i.elim a₀ fun j ↦ f.coeff j)
    let ι : N.pair.Ring →ₐ[R] StrictHenselization R K :=
      (of N).comp (IsScalarTower.toAlgHom R N.pair.Ring N.Stalk)
    have hι (s : N.pair.Ring) : ι s = of N (algebraMap N.pair.Ring N.Stalk s) := rfl
    have hιpt (s : N.pair.Ring) : pointHom (ι s) = N.toField s := by
      rw [hι, pointHom_of, EtaleNbhd.pointHom_algebraMap]
    let F : N.pair.Ring[X] := X ^ f.natDegree + ∑ j : Fin f.natDegree, C (y (some j)) * X ^ (j : ℕ)
    have hF : F.Monic := monic_X_pow_add (degree_sum_fin_lt _)
    have hFf : F.map (ι : N.pair.Ring →+* StrictHenselization R K) = f := by
      conv_rhs => rw [hf.as_sum, ← Fin.sum_univ_eq_sum_range]
      simp only [F, Polynomial.map_add, Polynomial.map_pow, Polynomial.map_X, Polynomial.map_sum,
        Polynomial.map_mul, Polynomial.map_C]
      congr 1
      refine Finset.sum_congr rfl fun j _ ↦ ?_
      congr 2
      exact hy (some j)
    have ha₀ : ι (y none) = a₀ := hy none
    -- the standard étale algebra over the neighbourhood obtained by adjoining a root of `F`
    let Q : StandardEtalePair N.pair.Ring := ⟨F, hF, derivative F, 1, 0, 1, by ring⟩
    let : Algebra N.pair.Ring K := N.toField.toAlgebra
    have : IsScalarTower R N.pair.Ring K :=
      IsScalarTower.of_algebraMap_eq' N.toField.comp_algebraMap.symm
    let : Algebra R Q.Ring := ((algebraMap N.pair.Ring Q.Ring).comp (algebraMap R _)).toAlgebra
    have : IsScalarTower R N.pair.Ring Q.Ring := IsScalarTower.of_algebraMap_eq' rfl
    have : Algebra.Etale R Q.Ring := Algebra.Etale.comp R N.pair.Ring Q.Ring
    have heval (p : N.pair.Ring[X]) :
        aeval (N.toField (y none)) p = pointHom ((p.map (ι : N.pair.Ring →+* _)).eval a₀) := by
      rw [← ha₀, eval_map]
      change aeval _ p =
        pointHom (eval₂ (ι : N.pair.Ring →+* StrictHenselization R K)
          ((ι : N.pair.Ring →+* StrictHenselization R K) (y none)) p)
      rw [eval₂_hom, RingHom.coe_coe, hιpt, aeval_def]
      exact eval₂_hom (N.toField : N.pair.Ring →+* K) (y none)
    have hx : Q.HasMap (N.toField (y none)) := by
      refine ⟨?_, ?_⟩
      · change aeval (N.toField (y none)) F = 0
        rw [heval, hFf, pointHom_eq_zero_iff]
        exact h₁
      · change IsUnit (aeval (N.toField (y none)) (derivative F))
        rw [heval, ← derivative_map, hFf, isUnit_iff_ne_zero, ← isUnit_iff_pointHom_ne_zero]
        exact h₂
    let τ : Q.Ring →ₐ[R] K := (Q.lift _ hx).restrictScalars R
    obtain ⟨N', φ, hφ⟩ := EtaleNbhd.exists_algHom_of_etale τ
    let ψ : N.pair.Ring →ₐ[R] N'.Stalk := (IsScalarTower.toAlgHom R _ N'.Stalk).comp
      (φ.comp (IsScalarTower.toAlgHom R N.pair.Ring Q.Ring))
    have hψ : N'.pointHom.comp ψ = N.toField := by
      refine AlgHom.ext fun s ↦ ?_
      have := DFunLike.congr_fun hφ (algebraMap N.pair.Ring Q.Ring s)
      simp only [AlgHom.comp_apply, τ, AlgHom.restrictScalars_apply, AlgHom.commutes] at this
      simpa [ψ, RingHom.algebraMap_toAlgebra] using this
    have hle : N ≤ N' := EtaleNbhd.le_of_algHom ψ hψ
    let θ : Q.Ring →ₐ[R] StrictHenselization R K :=
      (of N').comp ((IsScalarTower.toAlgHom R _ N'.Stalk).comp φ)
    have hθ : (θ : Q.Ring →+* _).comp (algebraMap N.pair.Ring Q.Ring) =
        (ι : N.pair.Ring →+* StrictHenselization R K) := by
      have := EtaleNbhd.transition_comp_algebraMap hle ψ hψ
      refine RingHom.ext fun s ↦ ?_
      have h := DFunLike.congr_fun this s
      simp only [AlgHom.comp_apply, IsScalarTower.coe_toAlgHom'] at h
      simp only [RingHom.coe_comp, RingHom.coe_coe, Function.comp_apply, hι]
      rw [← of_transition hle, h]
      rfl
    refine ⟨θ Q.X, ?_, ?_⟩
    · change eval (θ Q.X) f = 0
      rw [← hFf, eval_map, ← hθ]
      change eval₂ ((θ : Q.Ring →+* StrictHenselization R K).comp (algebraMap _ _))
        ((θ : Q.Ring →+* StrictHenselization R K) Q.X) F = 0
      rw [← hom_eval₂, ← aeval_def]
      change θ (aeval Q.X Q.f) = 0
      rw [StandardEtalePair.hasMap_X.1, map_zero]
    · rw [← pointHom_eq_zero_iff, map_sub, sub_eq_zero, ← ha₀, hιpt]
      have := DFunLike.congr_fun hφ Q.X
      simp only [AlgHom.comp_apply, τ, AlgHom.restrictScalars_apply,
        StandardEtalePair.lift_X] at this
      simp [θ, this]

section Local

variable [IsLocalRing R] [IsLocalHom (algebraMap R K)] {B : Type*} [CommRing B] [IsLocalRing B]
  [Algebra R B] [IsLocalHom (algebraMap R B)]

/-- Every `R`-algebra map from the strict henselization to a local `R`-algebra (with local
structure map) is local, because the maximal ideal is generated by that of `R`. -/
lemma isLocalHom_algHom (φ : StrictHenselization R K →ₐ[R] B) : IsLocalHom φ := by
  have hle : maximalIdeal (StrictHenselization R K) ≤ (maximalIdeal B).comap φ := by
    rw [← map_maximalIdeal, Ideal.map_le_iff_le_comap]
    intro r hr
    rw [Ideal.mem_comap, Ideal.mem_comap, AlgHom.commutes]
    exact (mem_maximalIdeal _).mpr fun hu ↦ hr (isUnit_of_map_unit _ r hu)
  refine ⟨fun z hz ↦ ?_⟩
  by_contra h
  exact (mem_maximalIdeal _).mp (hle ((mem_maximalIdeal z).mpr h)) hz

/-- Every `R`-algebra map from the strict henselization to the residue field of a local
`R`-algebra `B` (with local structure map) kills the maximal ideal. -/
lemma algHom_residueField_eq_zero (τ : StrictHenselization R K →ₐ[R] ResidueField B)
    {z : StrictHenselization R K} (hz : z ∈ maximalIdeal (StrictHenselization R K)) : τ z = 0 := by
  rw [← map_maximalIdeal] at hz
  have hle : (maximalIdeal R).map (algebraMap R (StrictHenselization R K)) ≤ RingHom.ker τ := by
    rw [Ideal.map_le_iff_le_comap]
    intro r hr
    rw [Ideal.mem_comap, RingHom.mem_ker, AlgHom.commutes, IsScalarTower.algebraMap_apply R B,
      ResidueField.algebraMap_eq, residue_eq_zero_iff]
    exact (mem_maximalIdeal _).mpr fun hu ↦ hr (isUnit_of_map_unit _ r hu)
  exact hle hz

end Local

section FaithfullyFlat

variable [IsLocalRing R] [IsLocalHom (algebraMap R K)]

/-- The strict henselization is faithfully flat over `R`. -/
instance faithfullyFlat : Module.FaithfullyFlat R (StrictHenselization R K) :=
  .of_flat_of_isLocalHom

lemma algebraMap_injective : Function.Injective (algebraMap R (StrictHenselization R K)) :=
  FaithfulSMul.algebraMap_injective _ _

end FaithfullyFlat

/-- The residue field of the strict henselization, embedded into `K` by the point. -/
def residueFieldHom : ResidueField (StrictHenselization R K) →ₐ[R] K :=
  Ideal.Quotient.liftₐ _ pointHom fun z hz ↦ (pointHom_eq_zero_iff z).mpr hz

@[simp]
lemma residueFieldHom_residue (z : StrictHenselization R K) :
    residueFieldHom (residue _ z) = pointHom z := rfl

lemma residueFieldHom_injective :
    Function.Injective (residueFieldHom : ResidueField (StrictHenselization R K) →ₐ[R] K) :=
  RingHom.injective (residueFieldHom : _ →ₐ[R] K).toRingHom

lemma range_residueFieldHom :
    Set.range (residueFieldHom : ResidueField (StrictHenselization R K) →ₐ[R] K) =
      Set.range (pointHom : StrictHenselization R K →ₐ[R] K) := by
  ext y
  constructor
  · rintro ⟨z, rfl⟩
    obtain ⟨z, rfl⟩ := residue_surjective z
    exact ⟨z, rfl⟩
  · rintro ⟨z, rfl⟩
    exact ⟨residue _ z, rfl⟩

section UniversalProperty

variable {A : Type*} [CommRing A] [HenselianLocalRing A] [Algebra R A]

/-- Existence and uniqueness of lifts: every `R`-algebra map from the strict henselization to the
residue field of a henselian local `R`-algebra `A` lifts uniquely to `A`. -/
theorem existsUnique_lift (τ : StrictHenselization R K →ₐ[R] ResidueField A) :
    ∃! φ : StrictHenselization R K →ₐ[R] A,
      (IsScalarTower.toAlgHom R A (ResidueField A)).comp φ = τ := by
  choose φ hφ hφu using fun N : EtaleNbhd R K ↦ N.existsUnique_lift (τ.comp (of N))
  beta_reduce at hφ hφu
  have compat (N N' : EtaleNbhd R K) (h : N ≤ N') :
      (φ N').comp (EtaleNbhd.transition N N' h) = φ N := hφu N _ (by
    rw [← AlgHom.comp_assoc, hφ, AlgHom.comp_assoc, of_comp_transition])
  refine ⟨lift φ fun N N' h x ↦ DFunLike.congr_fun (compat N N' h) x, ?_, fun ψ hψ ↦ ?_⟩
  · ext N : 1
    rw [AlgHom.comp_assoc]
    exact hφ N
  · beta_reduce at hψ
    ext N : 1
    refine (hφu N _ ?_).trans rfl
    rw [← AlgHom.comp_assoc, hψ]

/-- The universal property of the strict henselization, in the form of Stacks 04GG: for a
henselian local `R`-algebra `A`, reduction modulo the maximal ideal of `A` is a bijection
`(StrictHenselization R K →ₐ[R] A) ≃ (StrictHenselization R K →ₐ[R] κ(A))`. -/
def liftEquiv : (StrictHenselization R K →ₐ[R] A) ≃
    (StrictHenselization R K →ₐ[R] ResidueField A) :=
  Equiv.ofBijective (fun φ ↦ (IsScalarTower.toAlgHom R A (ResidueField A)).comp φ)
    ⟨fun _ _ h ↦ (existsUnique_lift _).unique h rfl, fun τ ↦ (existsUnique_lift τ).exists⟩

@[simp]
lemma residue_liftEquiv_symm_apply (τ : StrictHenselization R K →ₐ[R] ResidueField A)
    (z : StrictHenselization R K) : residue A (liftEquiv.symm τ z) = τ z :=
  DFunLike.congr_fun (liftEquiv.apply_symm_apply τ) z

variable [IsLocalRing R] [IsLocalHom (algebraMap R K)] [IsLocalHom (algebraMap R A)]

/-- The universal property of the strict henselization (Stacks, Section 04GN; EGA IV 18.6, 18.8):
for a henselian local ring `A` with a local homomorphism `R → A`, the `R`-algebra maps from the
strict henselization to `A` correspond to the `R`-algebra maps between the residue fields. -/
def liftEquivResidueField : (StrictHenselization R K →ₐ[R] A) ≃
    (ResidueField (StrictHenselization R K) →ₐ[R] ResidueField A) :=
  liftEquiv.trans
    { toFun τ := Ideal.Quotient.liftₐ _ τ fun _ ↦ algHom_residueField_eq_zero τ
      invFun σ := σ.comp (Ideal.Quotient.mkₐ R _)
      left_inv _ := rfl
      right_inv _ := Ideal.Quotient.algHom_ext _ rfl }

lemma liftEquivResidueField_apply_residue (φ : StrictHenselization R K →ₐ[R] A)
    (z : StrictHenselization R K) :
    liftEquivResidueField φ (residue _ z) = residue A (φ z) := rfl

end UniversalProperty

end StrictHenselization

instance ResidueField.isLocalHom_algebraMap (R : Type*) [CommRing R] [IsLocalRing R] :
    IsLocalHom (algebraMap R (ResidueField R)) :=
  inferInstanceAs (IsLocalHom (residue R))

/-- The henselization of a local ring `R` (Stacks, Section 04GN; EGA IV 18.6): the colimit of the
local rings of the étale neighbourhoods of the closed point of `Spec R` with trivial residue field
extension, i.e. the strict henselization of `R` with respect to its residue field. It is a
henselian local ring (`StrictHenselization.henselianLocalRing`), faithfully flat over `R`, with
maximal ideal generated by that of `R` (`StrictHenselization.map_maximalIdeal`) and residue field
that of `R` (`Henselization.residueFieldEquiv`); it is initial among henselian local `R`-algebras
(`Henselization.lift`, `Henselization.algHom_ext`). -/
abbrev Henselization (R : Type u) [CommRing R] [IsLocalRing R] : Type u :=
  StrictHenselization R (ResidueField R)

namespace Henselization

variable {R : Type u} [CommRing R] [IsLocalRing R]

open StrictHenselization

lemma pointHom_surjective :
    Function.Surjective (pointHom : Henselization R →ₐ[R] ResidueField R) := fun y ↦ by
  obtain ⟨r, rfl⟩ := residue_surjective y
  exact ⟨algebraMap R _ r, by rw [AlgHom.commutes]; rfl⟩

/-- The residue field of the henselization is the residue field of `R`. -/
def residueFieldEquiv : ResidueField (Henselization R) ≃ₐ[R] ResidueField R :=
  AlgEquiv.ofBijective residueFieldHom ⟨residueFieldHom_injective, fun y ↦ by
    obtain ⟨z, rfl⟩ := pointHom_surjective y
    exact ⟨residue _ z, rfl⟩⟩

lemma residue_algebraMap_surjective :
    Function.Surjective ((residue (Henselization R)).comp (algebraMap R (Henselization R))) := by
  intro z
  obtain ⟨r, hr⟩ := residue_surjective (residueFieldEquiv z)
  refine ⟨r, residueFieldEquiv.injective ?_⟩
  rw [← hr, RingHom.comp_apply, ← ResidueField.algebraMap_eq, ← IsScalarTower.algebraMap_apply,
    AlgEquiv.commutes]
  rfl

instance {B : Type*} [Semiring B] [Algebra R B] :
    Subsingleton (ResidueField (Henselization R) →ₐ[R] B) where
  allEq σ σ' := AlgHom.ext fun z ↦ by
    obtain ⟨r, rfl⟩ := residue_algebraMap_surjective z
    simp only [RingHom.comp_apply, ← ResidueField.algebraMap_eq, ← IsScalarTower.algebraMap_apply,
      AlgHom.commutes]

variable {A : Type*} [CommRing A] [HenselianLocalRing A] [Algebra R A]
  [IsLocalHom (algebraMap R A)]

/-- The universal property of the henselization (Stacks, Section 04GN; EGA IV 18.6): the
`R`-algebra map to a henselian local ring `A` with a local homomorphism `R → A`. -/
def lift : Henselization R →ₐ[R] A :=
  liftEquivResidueField.symm
    (((Algebra.ofId (ResidueField R) (ResidueField A)).restrictScalars R).comp
      residueFieldEquiv.toAlgHom)

/-- The universal property of the henselization, uniqueness: there is at most one `R`-algebra
map from the henselization to a henselian local ring `A` with a local homomorphism `R → A`. -/
instance : Subsingleton (Henselization R →ₐ[R] A) where
  allEq _ _ := liftEquivResidueField.injective (Subsingleton.elim _ _)

lemma algHom_ext (φ ψ : Henselization R →ₐ[R] A) : φ = ψ := Subsingleton.elim φ ψ


instance : IsLocalHom (lift : Henselization R →ₐ[R] A) := isLocalHom_algHom _

omit [HenselianLocalRing A] [IsLocalHom (algebraMap R A)] in
/-- Every `R`-algebra map from the henselization to a local `R`-algebra with local structure map
is local. -/
lemma isLocalHom_of_algHom {B : Type*} [CommRing B] [IsLocalRing B] [Algebra R B]
    [IsLocalHom (algebraMap R B)] (φ : Henselization R →ₐ[R] B) : IsLocalHom φ :=
  isLocalHom_algHom φ

end Henselization

namespace Henselization

/-- A henselian local ring is its own henselization. -/
def algEquivOfHenselian (R : Type u) [CommRing R] [HenselianLocalRing R] :
    Henselization R ≃ₐ[R] R :=
  haveI : IsLocalHom (algebraMap R R) := inferInstanceAs (IsLocalHom (RingHom.id R))
  AlgEquiv.ofAlgHom lift (Algebra.ofId R (Henselization R))
    (AlgHom.ext fun r ↦ by simp) (algHom_ext _ _)

variable {R : Type u} [CommRing R] [IsLocalRing R]

/-- Functoriality of the henselization: a local homomorphism `R → S` of local rings induces a
local homomorphism `Rʰ → Sʰ` (EGA IV 18.6). -/
def map {S : Type u} [CommRing S] [IsLocalRing S] (f : R →+* S) [IsLocalHom f] :
    Henselization R →+* Henselization S :=
  letI : Algebra R (Henselization S) := ((algebraMap S (Henselization S)).comp f).toAlgebra
  haveI : IsLocalHom (algebraMap R (Henselization S)) :=
    inferInstanceAs (IsLocalHom ((algebraMap S (Henselization S)).comp f))
  (lift : Henselization R →ₐ[R] Henselization S).toRingHom

lemma map_algebraMap {S : Type u} [CommRing S] [IsLocalRing S] (f : R →+* S) [IsLocalHom f]
    (r : R) : map f (algebraMap R (Henselization R) r) = algebraMap S (Henselization S) (f r) :=
  letI : Algebra R (Henselization S) := ((algebraMap S (Henselization S)).comp f).toAlgebra
  haveI : IsLocalHom (algebraMap R (Henselization S)) :=
    inferInstanceAs (IsLocalHom ((algebraMap S (Henselization S)).comp f))
  (lift : Henselization R →ₐ[R] Henselization S).commutes r

instance {S : Type u} [CommRing S] [IsLocalRing S] (f : R →+* S) [IsLocalHom f] :
    IsLocalHom (map f) :=
  letI : Algebra R (Henselization S) := ((algebraMap S (Henselization S)).comp f).toAlgebra
  haveI : IsLocalHom (algebraMap R (Henselization S)) :=
    inferInstanceAs (IsLocalHom ((algebraMap S (Henselization S)).comp f))
  ⟨fun x hx ↦ (StrictHenselization.isLocalHom_algHom
    (lift : Henselization R →ₐ[R] Henselization S)).map_nonunit x hx⟩

/-- Stacks 06LJ: the henselization of a noetherian local ring is noetherian. Proved as
`IsLocalRing.Henselization.isNoetherianStatement` in `SGA.Foundations.HenselizationNoetherian`. -/
def IsNoetherianStatement : Prop :=
  ∀ (R : Type u) [CommRing R] [IsLocalRing R] [IsNoetherianRing R],
    IsNoetherianRing (Henselization R)

end Henselization

end IsLocalRing

end
