/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import Mathlib.RingTheory.Henselian
import Mathlib.RingTheory.Etale.StandardEtale
import Mathlib.RingTheory.Unramified.LocalStructure

/-!
# Lifting points of étale algebras to henselian local rings

Let `R` be a ring, `S` an étale `R`-algebra and `A` a henselian local ring which is an
`R`-algebra. Every `R`-algebra map `S → κ(A)` to the residue field of `A` lifts uniquely to an
`R`-algebra map `S → A` (Stacks 04GG; EGA IV 18.5). Uniqueness holds for any local
ring `A` and any unramified `S` (the diagonal of an unramified algebra is cut out by an
idempotent); existence uses the local structure of étale algebras (`S` is standard étale around
the kernel of `S → κ(A)`) and the definition of a henselian local ring.

## Main results

* `Algebra.FormallyUnramified.algHom_ext_of_sub_mem_jacobson`: two maps from an unramified
  algebra which agree modulo an ideal contained in the Jacobson radical are equal.
* `Algebra.FormallyUnramified.algHom_ext_of_residue`: the same for maps to a local ring which
  agree on the residue field.
* `HenselianLocalRing.exists_algHom_lift`: existence of lifts.
* `HenselianLocalRing.algHomEquivResidueField`: the bijection
  `(S →ₐ[R] A) ≃ (S →ₐ[R] ResidueField A)`.
-/

open Polynomial IsLocalRing TensorProduct

/-- An idempotent element in the Jacobson radical is zero. -/
lemma IsIdempotentElem.eq_zero_of_mem_jacobson {C : Type*} [CommRing C] {x : C}
    (hx : IsIdempotentElem x) (hj : x ∈ Ideal.jacobson ⊥) : x = 0 := by
  rw [Ideal.mem_jacobson_bot] at hj
  have hu : IsUnit (x * (-1) + 1) := hj (-1)
  have : x * (x * (-1) + 1) = 0 := by
    rw [mul_add, ← mul_assoc, hx.eq]
    ring
  exact hu.mul_left_eq_zero.mp this

namespace Algebra.FormallyUnramified

variable {R S C : Type*} [CommRing R] [CommRing S] [CommRing C] [Algebra R S] [Algebra R C]

/-- Two `R`-algebra maps from an unramified `R`-algebra `S` (formally unramified and essentially
of finite type) to `C` which agree modulo an ideal contained in the Jacobson radical of `C` are
equal. The kernel of the multiplication `S ⊗[R] S → S` is generated by an idempotent. -/
theorem algHom_ext_of_sub_mem_jacobson [FormallyUnramified R S] [EssFiniteType R S]
    {J : Ideal C} (hJ : J ≤ Ideal.jacobson ⊥) {f g : S →ₐ[R] C} (h : ∀ s, f s - g s ∈ J) :
    f = g := by
  obtain ⟨e, he, hsp⟩ : ∃ e, IsIdempotentElem e ∧ KaehlerDifferential.ideal R S = S ⊗[R] S ∙ e :=
    (Ideal.isIdempotentElem_iff_of_fg _ (KaehlerDifferential.ideal_fg R S)).mp <|
      (Ideal.cotangent_subsingleton_iff _).mp <| inferInstanceAs <| Subsingleton Ω[S⁄R]
  let φ : S ⊗[R] S →ₐ[R] C := Algebra.TensorProduct.lift f g fun _ _ ↦ Commute.all _ _
  have hφ (s : S) : φ ((1 : S) ⊗ₜ[R] s - s ⊗ₜ[R] (1 : S)) = -(f s - g s) := by
    simp [φ]
  have hI : KaehlerDifferential.ideal R S ≤ J.comap φ := by
    rw [← KaehlerDifferential.span_range_eq_ideal, Ideal.span_le]
    rintro _ ⟨s, rfl⟩
    rw [SetLike.mem_coe, Ideal.mem_comap, hφ]
    exact J.neg_mem (h s)
  have heI : e ∈ KaehlerDifferential.ideal R S := by
    rw [hsp]
    exact Submodule.mem_span_singleton_self e
  have he0 : φ e = 0 := (he.map φ).eq_zero_of_mem_jacobson (hJ (hI heI))
  ext s
  have hmem : (1 : S) ⊗ₜ[R] s - s ⊗ₜ[R] (1 : S) ∈ KaehlerDifferential.ideal R S :=
    KaehlerDifferential.one_smul_sub_smul_one_mem_ideal R s
  rw [hsp] at hmem
  obtain ⟨r, hr⟩ := Submodule.mem_span_singleton.mp hmem
  have := congrArg φ hr
  rw [smul_eq_mul, map_mul, he0, mul_zero, hφ, zero_eq_neg, sub_eq_zero] at this
  exact this

/-- Two `R`-algebra maps from an unramified `R`-algebra to a local ring `C` which induce the same
map to the residue field of `C` are equal. -/
theorem algHom_ext_of_residue [FormallyUnramified R S] [EssFiniteType R S] [IsLocalRing C]
    {f g : S →ₐ[R] C} (h : ∀ s, residue C (f s) = residue C (g s)) : f = g :=
  algHom_ext_of_sub_mem_jacobson (maximalIdeal_le_jacobson ⊥) fun s ↦ by
    rw [← residue_eq_zero_iff, map_sub, h, sub_self]

end Algebra.FormallyUnramified

namespace HenselianLocalRing

variable {R S A : Type*} [CommRing R] [CommRing S] [CommRing A] [Algebra R S] [Algebra R A]

lemma residue_aeval [IsLocalRing A] (p : R[X]) (a : A) :
    residue A (aeval a p) = aeval (residue A a) p :=
  (aeval_algHom_apply (IsScalarTower.toAlgHom R A (ResidueField A)) a p).symm

variable [HenselianLocalRing A]

/-- Lifting a point of a standard étale algebra: if `P` is a standard étale pair over `R` and
`y₀` is a point of `P` with values in the residue field of a henselian local `R`-algebra `A`,
then `y₀` lifts to a point of `P` with values in `A`. -/
theorem exists_hasMap_lift (P : StandardEtalePair R) {y₀ : ResidueField A} (hy₀ : P.HasMap y₀) :
    ∃ y : A, P.HasMap y ∧ residue A y = y₀ := by
  obtain ⟨a₀, rfl⟩ := residue_surjective y₀
  have hunit (b : A) : IsUnit b ↔ residue A b ≠ 0 := (residue_ne_zero_iff_isUnit b).symm
  have h₁ : (P.f.map (algebraMap R A)).eval a₀ ∈ maximalIdeal A := by
    rw [eval_map_algebraMap, ← residue_eq_zero_iff, residue_aeval]
    exact hy₀.1
  have h₂ : IsUnit ((P.f.map (algebraMap R A)).derivative.eval a₀) := by
    rw [derivative_map, eval_map_algebraMap, hunit, residue_aeval]
    exact hy₀.isUnit_derivative_f.ne_zero
  obtain ⟨a, ha, hmem⟩ :=
    HenselianLocalRing.is_henselian _ (P.monic_f.map (algebraMap R A)) a₀ h₁ h₂
  have hres : residue A a = residue A a₀ := by
    rw [← sub_eq_zero, ← map_sub, residue_eq_zero_iff]
    exact hmem
  refine ⟨a, ⟨?_, ?_⟩, hres⟩
  · rw [← eval_map_algebraMap]
    exact ha
  · rw [hunit, residue_aeval, hres]
    exact hy₀.2.ne_zero

/-- Stacks 04GG, existence: an `R`-algebra map `S → κ(A)` from an étale `R`-algebra `S` to
the residue field of a henselian local `R`-algebra `A` lifts to an `R`-algebra map `S → A`.
The algebra `S` is standard étale around the kernel of `S → κ(A)` and a simple root of a monic
polynomial lifts to `A`. -/
theorem exists_algHom_lift [Algebra.Etale R S] (τ : S →ₐ[R] ResidueField A) :
    ∃ φ : S →ₐ[R] A, (IsScalarTower.toAlgHom R A (ResidueField A)).comp φ = τ := by
  let Q := RingHom.ker τ
  have : Q.IsPrime := RingHom.ker_isPrime _
  obtain ⟨t, htQ, ht⟩ := Algebra.IsEtaleAt.exists_isStandardEtale (R := R) Q
  have hτt : IsUnit (τ t) := isUnit_iff_ne_zero.mpr fun h ↦ htQ (RingHom.mem_ker.mpr h)
  let τt : Localization.Away t →ₐ[R] ResidueField A := IsLocalization.Away.liftAlgHom t hτt
  have hτt_comp : τt.comp (IsScalarTower.toAlgHom R S (Localization.Away t)) = τ := by
    ext s
    simp [τt]
  obtain ⟨P⟩ := ht.nonempty_standardEtalePresentation
  obtain ⟨y, hy, hyres⟩ := exists_hasMap_lift P.P (P.hasMap.map τt)
  refine ⟨((P.lift y hy).comp P.equivRing.toAlgHom).comp
    (IsScalarTower.toAlgHom R S (Localization.Away t)), ?_⟩
  have key : (IsScalarTower.toAlgHom R A (ResidueField A)).comp (P.lift y hy) =
      τt.comp P.equivRing.symm.toAlgHom := by
    apply P.P.hom_ext
    simp [hyres]
  rw [← hτt_comp]
  ext s
  have := congrArg (fun F ↦ F (P.equivRing (algebraMap S (Localization.Away t) s))) key
  simpa using this

variable (R S A) in
/-- Stacks 04GG: for `S` étale over `R` and `A` a henselian local `R`-algebra, reduction
modulo the maximal ideal of `A` is a bijection `(S →ₐ[R] A) ≃ (S →ₐ[R] κ(A))`. -/
noncomputable def algHomEquivResidueField [Algebra.Etale R S] :
    (S →ₐ[R] A) ≃ (S →ₐ[R] ResidueField A) :=
  Equiv.ofBijective (fun φ ↦ (IsScalarTower.toAlgHom R A (ResidueField A)).comp φ) <| by
    refine ⟨fun φ ψ h ↦ ?_, fun τ ↦ exists_algHom_lift τ⟩
    exact Algebra.FormallyUnramified.algHom_ext_of_residue fun s ↦ DFunLike.congr_fun h s

@[simp]
lemma algHomEquivResidueField_apply [Algebra.Etale R S] (φ : S →ₐ[R] A) (s : S) :
    algHomEquivResidueField R S A φ s = residue A (φ s) := rfl

@[simp]
lemma residue_algHomEquivResidueField_symm_apply [Algebra.Etale R S]
    (τ : S →ₐ[R] ResidueField A) (s : S) :
    residue A ((algHomEquivResidueField R S A).symm τ s) = τ s :=
  DFunLike.congr_fun ((algHomEquivResidueField R S A).apply_symm_apply τ) s

end HenselianLocalRing
