/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import Mathlib.AlgebraicGeometry.Morphisms.UniversallyInjective
import Mathlib.RingTheory.Kaehler.Basic
import Mathlib.RingTheory.Smooth.NoetherianDescent
import SGA.Foundations.Formal.EtaleLift

/-!
# Noetherian approximation of finite radicial algebras and étale algebras

EGA IV 8 (limit methods) in the form needed for the topological invariance of the étale site
(SGA 1 IX.4.10) over an arbitrary base.

* `Algebra.exists_finite_model_of_isNilpotent`: let `A'` be a finite, finitely presented
  `A`-algebra such that the kernels of `A → A'` and of the multiplication `A' ⊗_A A' → A'` are nil
  (i.e. `Spec A' → Spec A` is surjective and radicial). Then `A' = A ⊗_{A₀} A'₀` for a finitely
  generated subring `A₀ ⊆ A` and a finite, finitely presented `A₀`-algebra `A'₀` with the same
  properties; moreover any given finite subset of `A'` comes from `A'₀`. The model is mathlib's
  `Algebra.Presentation.ModelOfHasCoeffs`; finiteness, the nil kernels and the prescribed elements
  are obtained by also putting the coefficients of explicit polynomial witnesses into `A₀`.
* `Algebra.Presentation.ker_aeval_tensor_le`: the kernel of `R[X ⊔ X] → S ⊗_R S` is generated by
  the relations of `S` in each set of variables.
* `Algebra.Etale.exists_model_of_subset_range`: an étale `A'`-algebra descends to any
  `A'₀ → A'` whose image contains the coefficients of a submersive presentation (Stacks 00U2 (8)),
  using the lifting of étale algebras along surjections (`SGA.Foundations.Formal.EtaleLift`).
* `AlgebraicGeometry.universallyInjective_specMap_iff`,
  `AlgebraicGeometry.surjective_specMap_of_isIntegral`,
  `AlgebraicGeometry.isNilpotent_of_algebraMap_eq_zero_of_surjective`: the ring-theoretic meaning
  of radicial and surjective morphisms of affine schemes.
-/

universe u

open CategoryTheory Limits MorphismProperty TensorProduct

open MvPolynomial in
set_option backward.isDefEq.respectTransparency false in
/-- For a presentation `S = R[X]/(fⱼ)`, the kernel of `R[X ⊔ X] → S ⊗[R] S`
(`X_{inl i} ↦ xᵢ ⊗ 1`, `X_{inr i} ↦ 1 ⊗ xᵢ`) is generated by the relations in each set of
variables. -/
theorem Algebra.Presentation.ker_aeval_tensor_le {R S ι σ : Type*} [CommRing R] [CommRing S]
    [Algebra R S] (P : Algebra.Presentation R S ι σ) :
    RingHom.ker (aeval (Sum.elim (fun i ↦ P.val i ⊗ₜ[R] (1 : S))
        (fun i ↦ (1 : S) ⊗ₜ[R] P.val i)) : MvPolynomial (ι ⊕ ι) R →ₐ[R] S ⊗[R] S) ≤
      Ideal.span (Set.range (fun j ↦ rename Sum.inl (P.relation j)) ∪
        Set.range (fun j ↦ rename Sum.inr (P.relation j))) := by
  set J := Ideal.span (Set.range (fun j ↦ rename Sum.inl (P.relation j)) ∪
    Set.range (fun j ↦ rename Sum.inr (P.relation j)))
  have hker (f : ι → ι ⊕ ι) (hf : ∀ j, rename f (P.relation j) ∈ J) :
      ∀ p ∈ P.ker, ((Ideal.Quotient.mkₐ R J).comp (rename f)) p = 0 := by
    intro p hp
    rw [← P.span_range_relation_eq_ker] at hp
    induction hp using Submodule.span_induction with
    | mem x hx =>
      obtain ⟨j, rfl⟩ := hx
      simpa [Ideal.Quotient.eq_zero_iff_mem] using hf j
    | zero => simp
    | add x y _ _ hx hy => rw [map_add, hx, hy, add_zero]
    | smul a x _ hx => rw [smul_eq_mul, map_mul, hx, mul_zero]
  let ψ (f : ι → ι ⊕ ι) (hf : ∀ j, rename f (P.relation j) ∈ J) :
      S →ₐ[R] MvPolynomial (ι ⊕ ι) R ⧸ J :=
    (Ideal.Quotient.liftₐ P.ker ((Ideal.Quotient.mkₐ R J).comp (rename f)) (hker f hf)).comp
      (P.quotientEquiv.symm.restrictScalars R).toAlgHom
  have hψ (f) (hf) (p : MvPolynomial ι R) :
      ψ f hf (aeval P.val p) = Ideal.Quotient.mk J (rename f p) := by
    have : aeval P.val p = P.quotientEquiv (Ideal.Quotient.mk P.ker p) := by
      rw [Algebra.Presentation.quotientEquiv_mk, Algebra.Generators.algebraMap_apply]
    simp only [ψ, AlgHom.coe_comp, Function.comp_apply, this]
    simp only [AlgEquiv.coe_toAlgHom, AlgEquiv.coe_restrictScalars, AlgEquiv.symm_apply_apply,
      Ideal.Quotient.liftₐ_apply, Ideal.Quotient.lift_mk, AlgHom.coe_toRingHom,
      AlgHom.coe_comp, Function.comp_apply, Ideal.Quotient.mkₐ_eq_mk]
  have hl : ∀ j, rename Sum.inl (P.relation j) ∈ J :=
    fun j ↦ Ideal.subset_span (Or.inl ⟨j, rfl⟩)
  have hr : ∀ j, rename Sum.inr (P.relation j) ∈ J :=
    fun j ↦ Ideal.subset_span (Or.inr ⟨j, rfl⟩)
  let Ψ : S ⊗[R] S →ₐ[R] MvPolynomial (ι ⊕ ι) R ⧸ J :=
    Algebra.TensorProduct.lift (ψ Sum.inl hl) (ψ Sum.inr hr) fun _ _ ↦ Commute.all _ _
  have hΨ : Ψ.comp (aeval (Sum.elim (fun i ↦ P.val i ⊗ₜ[R] (1 : S))
      (fun i ↦ (1 : S) ⊗ₜ[R] P.val i))) = Ideal.Quotient.mkₐ R J := by
    ext i
    rcases i with i | i
    · simp only [AlgHom.coe_comp, Function.comp_apply, aeval_X, Sum.elim_inl, Ψ,
        Algebra.TensorProduct.lift_tmul, map_one, mul_one, Ideal.Quotient.mkₐ_eq_mk]
      rw [← aeval_X (R := R) P.val i, hψ Sum.inl hl, rename_X]
    · simp only [AlgHom.coe_comp, Function.comp_apply, aeval_X, Sum.elim_inr, Ψ,
        Algebra.TensorProduct.lift_tmul, map_one, one_mul, Ideal.Quotient.mkₐ_eq_mk]
      rw [← aeval_X (R := R) P.val i, hψ Sum.inr hr, rename_X]
  intro p hp
  have := congr($hΨ p)
  simp only [AlgHom.coe_comp, Function.comp_apply, RingHom.mem_ker.mp hp, map_zero,
    Ideal.Quotient.mkₐ_eq_mk] at this
  exact Ideal.Quotient.eq_zero_iff_mem.mp this.symm

open MvPolynomial in
/-- If `S` is generated by the `xᵢ` over `R`, the kernel of the multiplication `S ⊗[R] S → S` is
generated by the `xᵢ ⊗ 1 - 1 ⊗ xᵢ`. -/
theorem KaehlerDifferential.ideal_le_span_of_adjoin_eq_top {R S ι : Type*} [CommRing R]
    [CommRing S]
    [Algebra R S] (x : ι → S) (hx : Algebra.adjoin R (Set.range x) = ⊤) :
    KaehlerDifferential.ideal R S ≤
      Ideal.span (Set.range fun i ↦ x i ⊗ₜ[R] (1 : S) - 1 ⊗ₜ x i) := by
  set K := Ideal.span (Set.range fun i ↦ x i ⊗ₜ[R] (1 : S) - 1 ⊗ₜ x i)
  rw [← KaehlerDifferential.span_range_eq_ideal, Ideal.span_le]
  rintro _ ⟨y, rfl⟩
  have hy : y ∈ Algebra.adjoin R (Set.range x) := hx ▸ trivial
  induction hy using Algebra.adjoin_induction with
  | mem y hy =>
    obtain ⟨i, rfl⟩ := hy
    have : (1 : S) ⊗ₜ[R] x i - x i ⊗ₜ 1 = -(x i ⊗ₜ[R] (1 : S) - 1 ⊗ₜ x i) := by ring
    beta_reduce
    change _ ∈ K
    rw [this]
    exact K.neg_mem (Ideal.subset_span ⟨i, rfl⟩)
  | algebraMap a =>
    beta_reduce
    change _ ∈ K
    rw [← Algebra.TensorProduct.tmul_one_eq_one_tmul, sub_self]
    exact K.zero_mem
  | add y z _ _ hy hz =>
    beta_reduce at hy hz ⊢
    change _ ∈ K
    rw [TensorProduct.tmul_add, TensorProduct.add_tmul]
    convert K.add_mem hy hz using 1
    ring
  | mul y z _ _ hy hz =>
    have : (1 : S) ⊗ₜ[R] (y * z) - (y * z) ⊗ₜ 1 =
        (1 ⊗ₜ y) * (1 ⊗ₜ z - z ⊗ₜ 1) + (1 ⊗ₜ y - y ⊗ₜ 1) * (z ⊗ₜ (1 : S)) := by
      simp only [mul_sub, sub_mul, Algebra.TensorProduct.tmul_mul_tmul, one_mul, mul_one]
      ring
    beta_reduce at hy hz ⊢
    change _ ∈ K
    rw [this]
    exact K.add_mem (K.mul_mem_left _ hz) (K.mul_mem_right _ hy)

open MvPolynomial in
/-- If `(X_{inl i} - X_{inr i})ᴺ` is a combination of the relations `fⱼ(X_{inl})`, `fⱼ(X_{inr})`
satisfied by the `xᵢ`, then `(xᵢ ⊗ 1 - 1 ⊗ xᵢ)ᴺ = 0`. -/
theorem Algebra.TensorProduct.pow_sub_tmul_eq_zero {R S ι σ : Type*} [CommRing R] [CommRing S]
    [Algebra R S]
    [Fintype σ] (x : ι → S) (rel : σ → MvPolynomial ι R) (hrel : ∀ j, aeval x (rel j) = 0)
    (i : ι) (N : ℕ) (d : σ ⊕ σ → MvPolynomial (ι ⊕ ι) R)
    (h : (X (Sum.inl i) - X (Sum.inr i) : MvPolynomial (ι ⊕ ι) R) ^ N =
      ∑ k, d k * Sum.elim (fun j ↦ rename Sum.inl (rel j)) (fun j ↦ rename Sum.inr (rel j)) k) :
    (x i ⊗ₜ[R] (1 : S) - 1 ⊗ₜ x i) ^ N = 0 := by
  let Φ : MvPolynomial (ι ⊕ ι) R →ₐ[R] S ⊗[R] S :=
    aeval (Sum.elim (fun i ↦ x i ⊗ₜ[R] (1 : S)) (fun i ↦ (1 : S) ⊗ₜ x i))
  have hl : Φ.comp (rename Sum.inl) =
      (Algebra.TensorProduct.includeLeft (R := R) (S := R) (A := S) (B := S)).comp (aeval x) := by
    apply MvPolynomial.algHom_ext
    intro j
    simp [Φ]
  have hr : Φ.comp (rename Sum.inr) =
      (Algebra.TensorProduct.includeRight (R := R) (A := S) (B := S)).comp (aeval x) := by
    apply MvPolynomial.algHom_ext
    intro j
    simp [Φ]
  have := congr_arg Φ h
  rw [map_pow, map_sub, map_sum] at this
  simp only [Φ, aeval_X, Sum.elim_inl, Sum.elim_inr] at this
  rw [this]
  refine Finset.sum_eq_zero fun k _ ↦ ?_
  rcases k with k | k
  · have : Φ (rename Sum.inl (rel k)) = 0 := by
      rw [← AlgHom.comp_apply, hl, AlgHom.comp_apply, hrel, map_zero]
    simp only [Sum.elim_inl]
    rw [map_mul, show aeval _ (rename Sum.inl (rel k)) = Φ (rename Sum.inl (rel k)) from rfl, this,
      mul_zero]
  · have : Φ (rename Sum.inr (rel k)) = 0 := by
      rw [← AlgHom.comp_apply, hr, AlgHom.comp_apply, hrel, map_zero]
    simp only [Sum.elim_inr]
    rw [map_mul, show aeval _ (rename Sum.inr (rel k)) = Φ (rename Sum.inr (rel k)) from rfl, this,
      mul_zero]

open MvPolynomial in
set_option backward.isDefEq.respectTransparency false in
/-- EGA IV 8, noetherian approximation of a finite, finitely presented, radicial algebra with
nil kernel: let `A'` be a finite and finitely presented `A`-algebra such that the kernel of
`A → A'` and the kernel of the multiplication `A' ⊗_A A' → A'` are nil, and `T ⊆ A'` finite. There
are a finitely generated subring `A₀ ⊆ A` and a finite, finitely presented `A₀`-algebra `A'₀` with
the same two properties such that `A' = A ⊗_{A₀} A'₀` and `T` lies in the image of `A'₀`. -/
theorem Algebra.exists_finite_model_of_isNilpotent {A A' : Type u} [CommRing A] [CommRing A']
    [Algebra A A']
    [Module.Finite A A'] [Algebra.FinitePresentation A A']
    (hsurj : ∀ a : A, algebraMap A A' a = 0 → IsNilpotent a)
    (hrad : ∀ x ∈ KaehlerDifferential.ideal A A', IsNilpotent x) (T : Set A') (hT : T.Finite) :
    ∃ (A₀ : Subalgebra ℤ A) (A'₀ : Type u) (_ : CommRing A'₀) (_ : Algebra A₀ A'₀),
      A₀.FG ∧ Module.Finite A₀ A'₀ ∧ Algebra.FinitePresentation A₀ A'₀ ∧
      (∀ a : A₀, algebraMap A₀ A'₀ a = 0 → IsNilpotent a) ∧
      (∀ x ∈ KaehlerDifferential.ideal A₀ A'₀, IsNilpotent x) ∧
      ∃ e : A ⊗[A₀] A'₀ ≃ₐ[A] A', T ⊆ Set.range fun y : A'₀ ↦ e (1 ⊗ₜ y) := by
  classical
  let P := Algebra.Presentation.ofFinitePresentation A A'
  -- integral equations of the generators
  have hint (i) : ∃ p : Polynomial A, p.Monic ∧ Polynomial.aeval (P.val i) p = 0 :=
    Algebra.IsIntegral.isIntegral (P.val i)
  choose p hpm hp using hint
  have hq (i) : Polynomial.aeval (X i : MvPolynomial _ A) (p i) ∈
      Ideal.span (Set.range P.relation) := by
    rw [P.span_range_relation_eq_ker, Algebra.Generators.ker_eq_ker_aeval_val, RingHom.mem_ker,
      ← Polynomial.aeval_algHom_apply, aeval_X, hp]
  choose c hc using fun i ↦ Ideal.mem_span_range_iff_exists_fun.mp (hq i)
  -- nilpotence of `xᵢ ⊗ 1 - 1 ⊗ xᵢ`, as an identity of polynomials
  have hδ (i) : ∃ N : ℕ, (P.val i ⊗ₜ[A] (1 : A') - 1 ⊗ₜ P.val i) ^ N = 0 :=
    hrad _ (by simp [RingHom.mem_ker])
  choose N hN using hδ
  let relJ : _ ⊕ _ → MvPolynomial (_ ⊕ _) A :=
    Sum.elim (fun j ↦ rename Sum.inl (P.relation j)) (fun j ↦ rename Sum.inr (P.relation j))
  have hD (i) : ((X (Sum.inl i) - X (Sum.inr i) : MvPolynomial (_ ⊕ _) A) ^ N i) ∈
      Ideal.span (Set.range relJ) := by
    rw [Set.Sum.elim_range]
    apply P.ker_aeval_tensor_le
    simp [RingHom.mem_ker, hN]
  choose d hd using fun i ↦ Ideal.mem_span_range_iff_exists_fun.mp (hD i)
  -- polynomials representing the elements of `T`
  let r : A' → MvPolynomial _ A := P.σ
  -- the coefficients needed
  let S₀ : Set A := P.coeffs ∪ (⋃ i, Set.range fun n : Fin ((p i).natDegree + 1) ↦ (p i).coeff n) ∪
    (⋃ i, ⋃ j, ((c i j).coeffs : Set A)) ∪ (⋃ i, ⋃ k, ((d i k).coeffs : Set A)) ∪
    (⋃ t ∈ T, ((r t).coeffs : Set A))
  have hS₀ : S₀.Finite := by
    refine ((((P.finite_coeffs.union ?_).union ?_).union ?_).union ?_)
    · exact Set.finite_iUnion fun i ↦ Set.finite_range _
    · exact Set.finite_iUnion fun i ↦ Set.finite_iUnion fun j ↦ Finset.finite_toSet _
    · exact Set.finite_iUnion fun i ↦ Set.finite_iUnion fun k ↦ Finset.finite_toSet _
    · exact hT.biUnion fun t _ ↦ Finset.finite_toSet _
  let A₀ : Subalgebra ℤ A := Algebra.adjoin ℤ S₀
  have hA₀ : A₀.FG := ⟨hS₀.toFinset, by simp [A₀]⟩
  have hmem {x : A} (hx : x ∈ S₀) : x ∈ Set.range (algebraMap A₀ A) :=
    ⟨⟨x, Algebra.subset_adjoin hx⟩, rfl⟩
  have hlift {κ : Type} (x : MvPolynomial κ A) (hx : (x.coeffs : Set A) ⊆ S₀) :
      ∃ x₀ : MvPolynomial κ A₀, map (algebraMap A₀ A) x₀ = x :=
    mem_range_map_iff_coeffs_subset.mpr fun a ha ↦ hmem (hx ha)
  have hinj {κ : Type} : Function.Injective (map (algebraMap A₀ A) : MvPolynomial κ A₀ → _) :=
    map_injective _ Subtype.val_injective
  have : P.HasCoeffs A₀ := ⟨fun a ha ↦ hmem (Or.inl (Or.inl (Or.inl (Or.inl ha))))⟩
  let A'₀ := P.ModelOfHasCoeffs A₀
  let rel₀ := P.relationOfHasCoeffs A₀
  let x₀ (i) : A'₀ := Ideal.Quotient.mk _ (X i)
  have hmk (q : MvPolynomial _ A₀) : aeval x₀ q = Ideal.Quotient.mk _ q := by
    have := congr($(comp_aeval (R := A₀) (fun i ↦ (X i : MvPolynomial _ A₀))
      (Ideal.Quotient.mkₐ A₀ (Ideal.span (Set.range rel₀)))) q)
    simpa [aeval_X_left_apply] using this.symm
  have hadj : Algebra.adjoin A₀ (Set.range x₀) = ⊤ := by
    have h1 := congr_arg (Subalgebra.map (Ideal.Quotient.mkₐ A₀ (Ideal.span (Set.range rel₀))))
      (MvPolynomial.adjoin_range_X (R := A₀)
        (σ := Fin (Algebra.Presentation.ofFinitePresentationVars A A')))
    rw [AlgHom.map_adjoin, Algebra.map_top,
      (AlgHom.range_eq_top _).mpr (Ideal.Quotient.mkₐ_surjective _ _), ← Set.range_comp] at h1
    exact h1
  -- `A'₀` is finite over `A₀`
  have hfin : Module.Finite A₀ A'₀ := by
    have hx₀ (i) : IsIntegral A₀ (x₀ i) := by
      obtain ⟨p₀, hp₀, -, hp₀m⟩ := Polynomial.lifts_and_natDegree_eq_and_monic
        ((Polynomial.lifts_iff_coeff_lifts _).mpr fun n ↦ by
          by_cases hn : n ≤ (p i).natDegree
          · exact hmem (Or.inl (Or.inl (Or.inl (Or.inr (Set.mem_iUnion.mpr
              ⟨i, ⟨⟨n, Nat.lt_succ_of_le hn⟩, rfl⟩⟩)))))
          · rw [Polynomial.coeff_eq_zero_of_natDegree_lt (not_le.mp hn)]
            exact ⟨0, map_zero _⟩) (hpm i)
      have hc₀ (j) : ∃ c₀ : MvPolynomial _ A₀, map (algebraMap A₀ A) c₀ = c i j :=
        hlift _ fun a ha ↦ Or.inl (Or.inl (Or.inr (Set.mem_iUnion₂.mpr ⟨i, j, ha⟩)))
      choose c₀ hc₀ using hc₀
      refine ⟨p₀, hp₀m, ?_⟩
      have h : Polynomial.aeval (X i : MvPolynomial _ A₀) p₀ = ∑ j, c₀ j * rel₀ j := by
        apply hinj
        rw [map_sum]
        simp_rw [map_mul, hc₀, rel₀, P.map_relationOfHasCoeffs]
        rw [hc i, Polynomial.aeval_def, Polynomial.aeval_def, Polynomial.hom_eval₂, ← hp₀,
          Polynomial.eval₂_map, map_X]
        congr 1
        ext a
        simp
      have : x₀ i = Ideal.Quotient.mkₐ A₀ (Ideal.span (Set.range rel₀)) (X i) := rfl
      rw [← Polynomial.aeval_def, this, Polynomial.aeval_algHom_apply, h, map_sum]
      refine Finset.sum_eq_zero fun j _ ↦ ?_
      rw [map_mul, Ideal.Quotient.mkₐ_eq_mk,
        Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.subset_span (Set.mem_range_self j)), mul_zero]
    have : Algebra.IsIntegral A₀ A'₀ := ⟨fun y ↦ by
      have hy : y ∈ Algebra.adjoin A₀ (Set.range x₀) := hadj ▸ trivial
      exact (Algebra.adjoin_le (S := integralClosure A₀ A'₀)
        (by rintro _ ⟨i, rfl⟩; exact hx₀ i)) hy⟩
    exact Algebra.IsIntegral.finite
  let e := P.tensorModelOfHasCoeffsEquiv A₀
  -- the kernel of `A₀ → A'₀` is nil
  have hsurj₀ (a : A₀) (ha : algebraMap A₀ A'₀ a = 0) : IsNilpotent a := by
    have h1 : e ((1 : A) ⊗ₜ algebraMap A₀ A'₀ a) = algebraMap A A' a := by
      rw [← Algebra.TensorProduct.tmul_one_eq_one_tmul]
      exact e.commutes (algebraMap A₀ A a)
    obtain ⟨n, hn⟩ := hsurj a (by rw [← h1, ha, TensorProduct.tmul_zero, map_zero])
    exact ⟨n, Subtype.val_injective (by simpa using hn)⟩
  -- the kernel of the multiplication of `A'₀` is nil
  have hδ₀ (i) : IsNilpotent (x₀ i ⊗ₜ[A₀] (1 : A'₀) - 1 ⊗ₜ x₀ i) := by
    have hd₀ (k) : ∃ d₀ : MvPolynomial _ A₀, map (algebraMap A₀ A) d₀ = d i k :=
      hlift _ fun a ha ↦ Or.inl (Or.inr (Set.mem_iUnion₂.mpr ⟨i, k, ha⟩))
    choose d₀ hd₀ using hd₀
    refine ⟨N i, Algebra.TensorProduct.pow_sub_tmul_eq_zero x₀ rel₀ (fun j ↦ ?_) i (N i) d₀ ?_⟩
    · rw [hmk, Ideal.Quotient.eq_zero_iff_mem]
      exact Ideal.subset_span (Set.mem_range_self j)
    · apply hinj
      simp only [map_pow, map_sub, map_X, map_sum]
      rw [← hd i]
      refine Finset.sum_congr rfl fun k _ ↦ ?_
      rw [map_mul, hd₀]
      congr 1
      rcases k with k | k <;> simp [relJ, map_rename, rel₀, P.map_relationOfHasCoeffs]
  have hrad₀ (x) (hx : x ∈ KaehlerDifferential.ideal A₀ A'₀) : IsNilpotent x := by
    have hnil : Ideal.span (Set.range fun i ↦ x₀ i ⊗ₜ[A₀] (1 : A'₀) - 1 ⊗ₜ x₀ i) ≤
        nilradical _ := Ideal.span_le.mpr fun _ ⟨i, hi⟩ ↦ hi ▸ hδ₀ i
    exact hnil (KaehlerDifferential.ideal_le_span_of_adjoin_eq_top x₀ hadj hx)
  refine ⟨A₀, A'₀, inferInstance, inferInstance, hA₀, hfin, inferInstance, hsurj₀, hrad₀, e, ?_⟩
  intro t ht
  obtain ⟨r₀, hr₀⟩ := hlift (r t) fun a ha ↦ Or.inr (Set.mem_biUnion ht ha)
  refine ⟨Ideal.Quotient.mk _ r₀, ?_⟩
  beta_reduce
  rw [← P.tensorModelOfHasCoeffsEquiv_symm_tmul A₀ r₀, AlgEquiv.apply_symm_apply,
    ← MvPolynomial.aeval_map_algebraMap A, hr₀]
  exact P.aeval_val_σ t

set_option backward.isDefEq.respectTransparency false in
/-- EGA IV 8.8.2, 17.7.8: an étale `A'`-algebra `B'` descends to any `A'₀ → A'` whose image
contains a certain finite subset of `A'`: `B' = A' ⊗_{A'₀} C` with `C` étale over `A'₀`. -/
theorem Algebra.Etale.exists_model_of_subset_range {A' B' : Type u} [CommRing A'] [CommRing B']
    [Algebra A' B']
    [Algebra.Etale A' B'] :
    ∃ T : Set A', T.Finite ∧ ∀ (A'₀ : Type u) [CommRing A'₀] [Algebra A'₀ A'],
      T ⊆ Set.range (algebraMap A'₀ A') →
        ∃ (C : Type u) (_ : CommRing C) (_ : Algebra A'₀ C), Algebra.Etale A'₀ C ∧
          Nonempty (A' ⊗[A'₀] C ≃ₐ[A'] B') := by
  obtain ⟨ι, σ, _, _, Q, hQ⟩ :=
    (Algebra.Etale.iff_isStandardSmoothOfRelativeDimension_zero.mp ‹_›).out
  refine ⟨Q.coeffs, Q.finite_coeffs, fun A'₀ _ _ hT ↦ ?_⟩
  let R₀ : Subalgebra A'₀ A' := ⊥
  have : Q.HasCoeffs R₀ := ⟨fun c hc ↦ by
    obtain ⟨y, hy⟩ := hT hc
    exact ⟨algebraMap A'₀ R₀ y, hy⟩⟩
  let M := Q.toPresentation.ModelOfHasCoeffs R₀
  have : Algebra.Etale R₀ M :=
    Algebra.Etale.iff_isStandardSmoothOfRelativeDimension_zero.mpr
      ⟨⟨_, _, _, inferInstance, Q.ofHasCoeffs R₀, hQ⟩⟩
  have hS : Function.Surjective (algebraMap A'₀ R₀) := by
    rintro ⟨y, hy⟩
    obtain ⟨z, rfl⟩ := Algebra.mem_bot.mp hy
    exact ⟨z, rfl⟩
  obtain ⟨C, _, _, hC, ⟨eC⟩⟩ := Algebra.Etale.exists_etale_tensor_equiv hS M
  refine ⟨C, inferInstance, inferInstance, hC, ⟨?_⟩⟩
  exact (Algebra.TensorProduct.cancelBaseChange A'₀ R₀ A' A' C).symm.trans
    ((Algebra.TensorProduct.congr AlgEquiv.refl eC).trans
      (Q.toPresentation.tensorModelOfHasCoeffsEquiv R₀))

namespace AlgebraicGeometry

section RingCriteria

variable {R S : Type u} [CommRing R] [CommRing S] [Algebra R S]

/-- The kernel of `R → S` is nil if `Spec S → Spec R` is surjective. -/
lemma isNilpotent_of_algebraMap_eq_zero_of_surjective
    (h : Surjective (Spec.map (CommRingCat.ofHom (algebraMap R S)))) (a : R)
    (ha : algebraMap R S a = 0) : IsNilpotent a := by
  rw [nilpotent_iff_mem_prime]
  intro J hJ
  obtain ⟨q, hq⟩ := (Spec.map (CommRingCat.ofHom (algebraMap R S))).surjective ⟨J, hJ⟩
  have : a ∈ (PrimeSpectrum.comap (algebraMap R S) q).asIdeal := by
    change algebraMap R S a ∈ q.asIdeal
    rw [ha]; exact q.asIdeal.zero_mem
  rw [show PrimeSpectrum.comap (algebraMap R S) q = ⟨J, hJ⟩ from hq] at this
  exact this

/-- An integral `R`-algebra `S` such that the kernel of `R → S` is nil has surjective spectrum
map (lying over). -/
lemma surjective_specMap_of_isIntegral [Algebra.IsIntegral R S]
    (h : ∀ a : R, algebraMap R S a = 0 → IsNilpotent a) :
    Surjective (Spec.map (CommRingCat.ofHom (algebraMap R S))) := by
  refine ⟨fun p ↦ ?_⟩
  have : (p : PrimeSpectrum R).asIdeal.IsPrime := PrimeSpectrum.isPrime (R := R) p
  obtain ⟨Q, -, hQ, hQp⟩ := Ideal.exists_ideal_over_prime_of_isIntegral (S := S) p.asIdeal ⊥
    (fun a ha ↦ by
      have : algebraMap R S a = 0 := by simpa using ha
      exact (nilpotent_iff_mem_prime.mp (h a this)) _ p.isPrime)
  exact ⟨⟨Q, hQ⟩, PrimeSpectrum.ext hQp⟩

/-- `Spec S → Spec R` is universally injective iff the kernel of `S ⊗[R] S → S` is nil. -/
lemma universallyInjective_specMap_iff :
    UniversallyInjective (Spec.map (CommRingCat.ofHom (algebraMap R S))) ↔
      ∀ x ∈ KaehlerDifferential.ideal R S, IsNilpotent x := by
  rw [UniversallyInjective.iff_diagonal, diagonal_SpecMap, surjective_iff]
  simp only [Scheme.Hom.comp_base, TopCat.coe_comp]
  rw [show (⇑(pullbackSpecIso R S S).inv) = ⇑(pullbackSpecIso R S S).inv.homeomorph from rfl,
    EquivLike.comp_surjective]
  change Function.Surjective (PrimeSpectrum.comap _) ↔ _
  rw [← Set.range_eq_univ, range_comap_of_surjective _ _
    (fun s ↦ ⟨s ⊗ₜ[R] (1 : S), by simp⟩), PrimeSpectrum.zeroLocus_eq_univ_iff]
  exact ⟨fun h x hx ↦ mem_nilradical.mp (h hx), fun h x hx ↦ mem_nilradical.mpr (h x hx)⟩

end RingCriteria

end AlgebraicGeometry
