/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.Foundations.Pro.TopologicallyFG
import SGA.SGA1.ExposeV.MultiGalois
import SGA.SGA1.ExposeV.QuotientComponents
import SGA.SGA1.ExposeV.EtaleCoveringAutomorphisms
import SGA.SGA1.ExposeV.QuotientHasQuotients
import SGA.SGA1.ExposeXIII.AffineLineFundamentalGroup


/-!
# SGA 1, Exposé IX, 5.2: topological finite generation of `π₁` by descent

IX.5.2 says: if `g : S' ⟶ S` is an effective descent morphism for étale coverings, `S` is
connected, `S'` and `S'' = S' ×_S S'` have finitely many connected components and the fundamental
groups of the connected components of `S'` are topologically finitely generated, then so is
`π₁(S)`. SGA derives it from the presentation IX.5.1. We prove it for `S` noetherian and `g`
proper surjective (`isTopologicallyFG_etaleFundamentalGroup_of_isProper_of_surjective`; `S'` and
`S''` then have finitely many connected components automatically), and for a finite
jointly surjective family of proper morphisms from connected schemes
(`isTopologicallyFG_etaleFundamentalGroup_of_family`), the form used in the proof of X.2.9 (Chow
cover and normalization of the irreducible components), with a direct argument that needs neither
IX.5.1 nor descent (of `g` it uses universal closedness and surjectivity, and finite type and
quasi-compactness to make `S'`, `S' ×_S S'` and the `X ×_S S'_i` noetherian, so that they have
finitely many connected components):

* by the uniform criterion for profinite groups
  (`CategoryTheory.PreGaloisCategory.exists_finset_card_le_dense_closure_aut_of_forall_isGalois`),
  it suffices to bound, uniformly in the Galois covering `X` of `S`, the number of generators of
  `Γ = Aut X`;
* `Γ` acts on the graph whose vertices are the connected components of the `X ×_S S'_i` and whose
  edges come from the points of `X ×_S (S'_i ×_S S'_j)`; the graph is connected because
  `∐ X ×_S S'_i ⟶ X` is closed and surjective and `X` is connected;
* the stabilizer of a vertex is a quotient of `π₁(S'_i)` (`exists_stabilizer_le_closure`), the
  vertices over `S'_i` and the edges over a connected component of `S'_i ×_S S'_j` form single
  `Γ`-orbits (`exists_smul_mem_connectedComponent`), and a group acting on a connected graph is
  generated by the stabilizers of representatives of the vertex orbits together with two elements
  per edge orbit (`DescentFiniteGeneration.eq_top_of_adj`).

This gives at most `∑ᵢ dᵢ + 2 ∑_{i,j} #π₀(S'_i ×_S S'_j)` generators for every Galois group
(`exists_card_le_closure_eq_top`), where `dᵢ` generators suffice for `π₁(S'_i)`.

The presentation IX.5.1 itself and IX.5.3 (finite presentation) are not formalized. For IX.5.4
(pinching), the consequence "`π₁(S')` is topologically finitely generated as soon as `π₁(S)` is"
is `SGA.SGA1.ExposeIX.isTopologicallyFG_etaleFundamentalGroup_of_pinching`
(`SGA.SGA1.ExposeIX.Pinching`).
-/

universe u

open CategoryTheory CategoryTheory.Limits AlgebraicGeometry PreGaloisCategory

namespace SGA.SGA1.ExposeIX

section Graph

/-- A group acting on the vertices of a connected graph is generated by any subgroup `K` which
contains the stabilizers of a set `R` of representatives of distinct orbits of vertices and,
for every edge, elements carrying two vertices of `R` to the ends of a translate of that
edge. (Bass–Serre style generation of a group by vertex stabilizers and edge elements.) -/
theorem DescentFiniteGeneration.eq_top_of_adj {Γ V : Type*} [Group Γ] [MulAction Γ V]
    (Adj : V → V → Prop)
    (hconn : ∀ W : Set V, W.Nonempty → (∀ v w, Adj v w → (v ∈ W ↔ w ∈ W)) → ∀ v, v ∈ W)
    (R : Set V) (hR : ∀ r ∈ R, ∀ r' ∈ R, ∀ γ : Γ, γ • r = r' → r = r') (hRne : R.Nonempty)
    (K : Subgroup Γ) (hstab : ∀ r ∈ R, MulAction.stabilizer Γ r ≤ K)
    (hadj : ∀ v w, Adj v w → ∃ γ : Γ, ∃ a ∈ K, ∃ b ∈ K, ∃ r ∈ R, ∃ r' ∈ R,
      v = γ • a • r ∧ w = γ • b • r') :
    K = ⊤ := by
  let W : Set V := {v | ∃ k ∈ K, ∃ r ∈ R, v = k • r}
  -- if `δ • r₀ = k • r` with `k ∈ K`, then `r₀ = r` and `δ ∈ K`
  have key : ∀ δ : Γ, ∀ k ∈ K, ∀ r₀ ∈ R, ∀ r ∈ R, δ • r₀ = k • r → δ ∈ K := by
    intro δ k hk r₀ hr₀ r hr h
    have h' : (k⁻¹ * δ) • r₀ = r := by rw [mul_smul, h, inv_smul_smul]
    obtain rfl := hR r₀ hr₀ r hr _ h'
    have : k⁻¹ * δ ∈ K := hstab r₀ hr₀ h'
    have hδ : δ = k * (k⁻¹ * δ) := by group
    rw [hδ]
    exact K.mul_mem hk this
  have hW : ∀ v w, Adj v w → (v ∈ W ↔ w ∈ W) := by
    intro v w hvw
    obtain ⟨γ, a, ha, b, hb, r, hr, r', hr', rfl, rfl⟩ := hadj v w hvw
    constructor
    · rintro ⟨k, hk, r₀, hr₀, h⟩
      have : γ * a ∈ K := key _ k hk r hr r₀ hr₀ (by rw [mul_smul]; exact h)
      have hγ : γ ∈ K := by simpa using K.mul_mem this (K.inv_mem ha)
      exact ⟨γ * b, K.mul_mem hγ hb, r', hr', by rw [mul_smul]⟩
    · rintro ⟨k, hk, r₀, hr₀, h⟩
      have : γ * b ∈ K := key _ k hk r' hr' r₀ hr₀ (by rw [mul_smul]; exact h)
      have hγ : γ ∈ K := by simpa using K.mul_mem this (K.inv_mem hb)
      exact ⟨γ * a, K.mul_mem hγ ha, r, hr, by rw [mul_smul]⟩
  obtain ⟨r₀, hr₀⟩ := hRne
  have hall := hconn W ⟨r₀, 1, K.one_mem, r₀, hr₀, (one_smul _ _).symm⟩ hW
  refine eq_top_iff.mpr fun δ _ ↦ ?_
  obtain ⟨k, hk, r, hr, h⟩ := hall (δ • r₀)
  exact key δ k hk r₀ hr₀ r hr h

end Graph

namespace DescentFiniteGeneration

open ExposeV

section Action

variable {S T : Scheme.{u}} (q : T ⟶ S) (X : FEt S)

/-- The action of the automorphism group of an étale covering `X` of `S` on the points of its
base change `X ×_S T`. -/
@[reducible] noncomputable def pullbackAction :
    MulAction (Aut X) ((FEt.pullback q).obj X).left where
  smul γ y := ((FEt.pullback q).map γ.hom).left y
  one_smul y := by
    change ((FEt.pullback q).map (𝟙 X)).left y = y
    rw [CategoryTheory.Functor.map_id]
    rfl
  mul_smul γ δ y := by
    change ((FEt.pullback q).map (δ.hom ≫ γ.hom)).left y = _
    rw [CategoryTheory.Functor.map_comp]
    rfl

attribute [local instance] pullbackAction

lemma smul_def (γ : Aut X) (y : ((FEt.pullback q).obj X).left) :
    γ • y = ((FEt.pullback q).map γ.hom).left y :=
  rfl

lemma continuous_smul_left (γ : Aut X) :
    Continuous fun y : ((FEt.pullback q).obj X).left ↦ γ • y :=
  ((FEt.pullback q).map γ.hom).left.continuous

lemma pullback_map_left_fst {X Y : FEt S} (φ : X ⟶ Y) :
    ((FEt.pullback q).map φ).left ≫ pullback.fst Y.hom q = pullback.fst X.hom q ≫ φ.left := by
  simp only [FEt.pullback, MorphismProperty.Over.pullback_map_left]
  exact pullback.lift_fst _ _ _

lemma pullback_map_left_snd {X Y : FEt S} (φ : X ⟶ Y) :
    ((FEt.pullback q).map φ).left ≫ pullback.snd Y.hom q = pullback.snd X.hom q := by
  simp only [FEt.pullback, MorphismProperty.Over.pullback_map_left]
  exact pullback.lift_snd _ _ _

/-- The induced action on the connected components of `X ×_S T`. -/
@[reducible] noncomputable def componentsAction :
    MulAction (Aut X) (ConnectedComponents ((FEt.pullback q).obj X).left) where
  smul γ c := (continuous_smul_left q X γ).connectedComponentsMap c
  one_smul c := by
    obtain ⟨y, rfl⟩ := ConnectedComponents.surjective_coe c
    change (continuous_smul_left q X 1).connectedComponentsMap (.mk y) = .mk y
    rw [Continuous.connectedComponentsMap_mk, one_smul]
  mul_smul γ δ c := by
    obtain ⟨y, rfl⟩ := ConnectedComponents.surjective_coe c
    change (continuous_smul_left q X (γ * δ)).connectedComponentsMap (.mk y) =
      (continuous_smul_left q X γ).connectedComponentsMap
        ((continuous_smul_left q X δ).connectedComponentsMap (.mk y))
    simp only [Continuous.connectedComponentsMap_mk, mul_smul]

attribute [local instance] componentsAction

lemma smul_mk (γ : Aut X) (y : ((FEt.pullback q).obj X).left) :
    γ • (ConnectedComponents.mk y) = ConnectedComponents.mk (γ • y) :=
  Continuous.connectedComponentsMap_mk _ y

end Action

section Points

variable {S : Scheme.{u}} {Ω : Type u} [Field Ω]

/-- The geometric point `x` of `X`, as an element of the fibre at `x ≫ X.toBase`. -/
noncomputable def toFiber (X : FEt S) (x : Spec (.of Ω) ⟶ X.left) :
    (FEt.fiber Ω (x ≫ X.toBase)).obj X :=
  (FEt.fiberEquiv Ω _ X).symm (Over.homMk x rfl)

lemma fiberEquiv_toFiber_left (X : FEt S) (x : Spec (.of Ω) ⟶ X.left) :
    (FEt.fiberEquiv Ω _ X (toFiber X x)).left = x := by
  rw [toFiber, Equiv.apply_symm_apply]
  rfl

variable [ConnectedSpace S] [IsSepClosed Ω]

/-- Two geometric points of a Galois covering over the same geometric point of the base differ by
an automorphism of the covering. -/
lemma exists_aut_comp_eq (X : FEt S) [IsGalois X] (x x' : Spec (.of Ω) ⟶ X.left)
    (h : x ≫ X.toBase = x' ≫ X.toBase) : ∃ γ : Aut X, x ≫ γ.hom.left = x' := by
  let a : (FEt.fiber Ω (x ≫ X.toBase)).obj X := toFiber X x
  let a' : (FEt.fiber Ω (x ≫ X.toBase)).obj X :=
    (FEt.fiberEquiv Ω _ X).symm (Over.homMk x' h.symm)
  obtain ⟨γ, hγ⟩ := MulAction.exists_smul_eq (Aut X) a a'
  refine ⟨γ, ?_⟩
  have := FEt.fiberEquiv_map_left Ω γ.hom a
  change (FEt.fiber Ω (x ≫ X.toBase)).map γ.hom a = a' at hγ
  rw [hγ, fiberEquiv_toFiber_left] at this
  have ha' : (FEt.fiberEquiv Ω _ X a').left = x' := by
    simp only [a', Equiv.apply_symm_apply]
    rfl
  exact this.symm.trans ha'

/-- Two automorphisms of a connected covering which agree at one geometric point are equal. -/
lemma aut_eq_of_comp_eq (X : FEt S) [IsConnected X] (x : Spec (.of Ω) ⟶ X.left) (γ δ : Aut X)
    (h : x ≫ γ.hom.left = x ≫ δ.hom.left) : γ = δ := by
  refine evaluation_aut_injective_of_isConnected (FEt.fiber Ω (x ≫ X.toBase)) X (toFiber X x) ?_
  apply FEt.fiber_ext Ω
  change (FEt.fiberEquiv Ω _ X ((FEt.fiber Ω (x ≫ X.toBase)).map γ.hom (toFiber X x))).left =
    (FEt.fiberEquiv Ω _ X ((FEt.fiber Ω (x ≫ X.toBase)).map δ.hom (toFiber X x))).left
  rw [FEt.fiberEquiv_map_left, FEt.fiberEquiv_map_left, fiberEquiv_toFiber_left]
  exact h

end Points

section Transitive

variable {S T : Scheme.{u}} (q : T ⟶ S) (X : FEt S)

attribute [local instance] pullbackAction

/-- A morphism into `X ×_S T` is moved by `φ` as its projection to `X` is. -/
lemma comp_map_left_eq {W : Scheme.{u}} (y y' : W ⟶ ((FEt.pullback q).obj X).left) (φ : X ⟶ X)
    (hsnd : y ≫ pullback.snd X.hom q = y' ≫ pullback.snd X.hom q)
    (hfst : y ≫ pullback.fst X.hom q ≫ φ.left = y' ≫ pullback.fst X.hom q) :
    y ≫ ((FEt.pullback q).map φ).left = y' := by
  apply pullback.hom_ext
  · exact (Category.assoc y ((FEt.pullback q).map φ).left (pullback.fst X.hom q)).trans
      ((congrArg (y ≫ ·) (pullback_map_left_fst q φ)).trans hfst)
  · exact (Category.assoc y ((FEt.pullback q).map φ).left (pullback.snd X.hom q)).trans
      ((congrArg (y ≫ ·) (pullback_map_left_snd q φ)).trans hsnd)

variable [ConnectedSpace S] [IsLocallyNoetherian T]

/-- Let `X` be a Galois covering of a connected scheme `S` and `T ⟶ S` with `T` locally
noetherian. Two points of `X ×_S T` lying over the same connected component of `T` are carried
into the same connected component by an automorphism of `X`: the automorphism group of `X` acts
transitively on the connected components of `X ×_S T` over each connected component of `T`. -/
theorem exists_smul_mem_connectedComponent [IsGalois X] (z z' : ((FEt.pullback q).obj X).left)
    (h : connectedComponent (((FEt.pullback q).obj X).toBase z) =
      connectedComponent (((FEt.pullback q).obj X).toBase z')) :
    ∃ γ : Aut X, γ • z ∈ connectedComponent z' := by
  let Z := (FEt.pullback q).obj X
  have : IsFinite Z.toBase := Z.prop.1
  have : Etale Z.toBase := Z.prop.2
  have : IsLocallyNoetherian Z.left := LocallyOfFiniteType.isLocallyNoetherian Z.toBase
  let A := connectedComponent z
  have hA : IsClopen A := ExposeV.isClopen_connectedComponent_of_isLocallyNoetherian z
  have himA : IsClopen (Z.toBase '' A) :=
    ⟨FEt.isClosedMap Z _ hA.isClosed, FEt.isOpenMap Z _ hA.isOpen⟩
  have hsub : connectedComponent (Z.toBase z) ⊆ Z.toBase '' A :=
    himA.connectedComponent_subset ⟨z, mem_connectedComponent, rfl⟩
  obtain ⟨a, haA, ha⟩ : Z.toBase z' ∈ Z.toBase '' A := hsub (h ▸ mem_connectedComponent)
  let t := ExposeV.geometricPointAt T (Z.toBase z')
  have ht : t (IsLocalRing.closedPoint _) = Z.toBase z' :=
    Scheme.fromSpecResidueField_apply (Z.toBase z') _
  obtain ⟨ab, hab, habpt⟩ := ExposeV.exists_geometricPoint_lift Z.toBase t a (ha.trans ht.symm)
  obtain ⟨zb', hzb', hzb'pt⟩ := ExposeV.exists_geometricPoint_lift Z.toBase t z' ht.symm
  have e1 (w : Spec (.of (AlgebraicClosure (T.residueField (Z.toBase z')))) ⟶ Z.left) :
      (w ≫ pullback.fst X.hom q) ≫ X.toBase = (w ≫ Z.toBase) ≫ q :=
    (Category.assoc _ _ _).trans ((congrArg (w ≫ ·) pullback.condition).trans
      (Category.assoc _ _ _).symm)
  have hx : (ab ≫ pullback.fst X.hom q) ≫ X.toBase =
      (zb' ≫ pullback.fst X.hom q) ≫ X.toBase := by
    rw [e1, e1, hab, hzb']
  obtain ⟨γ, hγ⟩ := exists_aut_comp_eq X _ _ hx
  have habz : ab ≫ ((FEt.pullback q).map γ.hom).left = zb' :=
    comp_map_left_eq q X ab zb' γ.hom (hab.trans hzb'.symm) ((Category.assoc _ _ _).symm.trans hγ)
  have hγa : γ • a = z' := by
    rw [smul_def, ← habpt]
    exact (congrArg (fun f ↦ f (IsLocalRing.closedPoint _)) habz).trans hzb'pt
  refine ⟨γ, ?_⟩
  have hconn : _root_.IsPreconnected ((fun y ↦ γ • y) '' A) :=
    isPreconnected_connectedComponent.image _ (continuous_smul_left q X γ).continuousOn
  exact hconn.subset_connectedComponent ⟨a, haA, hγa⟩ ⟨z, mem_connectedComponent, rfl⟩

end Transitive

section Vertex

variable {S T : Scheme.{u}} (q : T ⟶ S) (X : FEt S)

attribute [local instance] pullbackAction componentsAction

lemma mem_connectedComponent_of_mem_stabilizer {y₀ : ((FEt.pullback q).obj X).left} {σ : Aut X}
    (hσ : σ ∈ MulAction.stabilizer (Aut X) (ConnectedComponents.mk y₀))
    {y : ((FEt.pullback q).obj X).left} (hy : y ∈ connectedComponent y₀) :
    σ • y ∈ connectedComponent y₀ := by
  rw [MulAction.mem_stabilizer_iff] at hσ
  have h1 : ConnectedComponents.mk y = ConnectedComponents.mk y₀ :=
    ConnectedComponents.coe_eq_coe'.mpr hy
  have h2 : ConnectedComponents.mk (σ • y) = ConnectedComponents.mk y₀ := by
    rw [← smul_mk, h1, hσ]
  exact ConnectedComponents.coe_eq_coe'.mp h2

variable [ConnectedSpace S] [ConnectedSpace T] [IsLocallyNoetherian T]

/-- **Vertex groups.** Let `X` be a Galois covering of the connected scheme `S`, `q : T ⟶ S` with
`T` connected and locally noetherian, and suppose `π₁(T, s₀)` is topologically generated by a
finite set `s`. Then the stabilizer in `Aut X` of a connected component of `X ×_S T` is contained
in a subgroup generated by at most `#s` elements (it is a quotient of `π₁(T, s₀)`). -/
theorem exists_stabilizer_le_closure [IsGalois X] {Ω : Type u} [Field Ω] [IsSepClosed Ω]
    (s₀ : Spec (.of Ω) ⟶ T) {s : Finset (ExposeV.etaleFundamentalGroup Ω s₀)}
    (hs : Dense (Subgroup.closure (s : Set (ExposeV.etaleFundamentalGroup Ω s₀)) :
      Set (ExposeV.etaleFundamentalGroup Ω s₀)))
    (y₀ : ((FEt.pullback q).obj X).left) :
    ∃ t : Finset (Aut X), t.card ≤ s.card ∧
      MulAction.stabilizer (Aut X) (ConnectedComponents.mk y₀) ≤ Subgroup.closure (t : Set _) := by
  classical
  let Z := (FEt.pullback q).obj X
  let F := FEt.fiber Ω s₀
  let F' := FEt.fiber Ω (s₀ ≫ q)
  let e : (FEt.pullback q ⋙ F).obj X ≅ F'.obj X := (FEt.pullbackFiberIso Ω q s₀).app X
  have he (φ : X ⟶ X) (a : F.obj Z) :
      e.hom (F.map ((FEt.pullback q).map φ) a) = F'.map φ (e.hom a) :=
    NatTrans.naturality_apply (FEt.pullbackFiberIso Ω q s₀).hom φ a
  -- the action of `Aut X` on `F(Z)`, transported from `F'(X)`
  let act (γ : Aut X) (a : F.obj Z) : F.obj Z := F.map ((FEt.pullback q).map γ.hom) a
  have hact (γ : Aut X) (a : F.obj Z) : e.hom (act γ a) = γ • e.hom a := he γ.hom a
  have act_mul (γ δ : Aut X) (a : F.obj Z) : act (γ * δ) a = act γ (act δ a) := by
    apply (FintypeCat.equivEquivIso.symm e).injective
    change e.hom _ = e.hom _
    rw [hact, hact, hact, mul_smul]
  have act_inj (a : F.obj Z) (γ δ : Aut X) (h : act γ a = act δ a) : γ = δ := by
    have h' : γ • e.hom a = δ • e.hom a := by rw [← hact, ← hact, h]
    exact evaluation_aut_injective_of_isConnected F' X (e.hom a) h'
  have act_trans (a b : F.obj Z) : ∃ γ : Aut X, act γ a = b := by
    obtain ⟨γ, hγ⟩ := MulAction.exists_smul_eq (Aut X) (e.hom a) (e.hom b)
    refine ⟨γ, (FintypeCat.equivEquivIso.symm e).injective ?_⟩
    change e.hom _ = e.hom _
    rw [hact, hγ]
  have act_comm (p : Aut F) (γ : Aut X) (a : F.obj Z) : p • act γ a = act γ (p • a) :=
    mulAction_naturality F p _ a
  have act_one (a : F.obj Z) : act 1 a = a := by
    apply (FintypeCat.equivEquivIso.symm e).injective
    change e.hom _ = e.hom _
    rw [hact, one_smul]
  -- the connected component `C` of `y₀`, as an étale covering of `T`
  have : IsFinite Z.toBase := Z.prop.1
  have : IsLocallyNoetherian Z.left := LocallyOfFiniteType.isLocallyNoetherian Z.toBase
  have hC := ExposeV.isClopen_connectedComponent_of_isLocallyNoetherian y₀
  let U : Z.left.Opens := ⟨connectedComponent y₀, hC.isOpen⟩
  let Cfet := FEt.restrict Z U hC.isClosed
  let ι : Cfet ⟶ Z := FEt.restrictι Z U hC.isClosed
  have : ConnectedSpace Cfet.left :=
    isConnected_iff_connectedSpace.mp isConnected_connectedComponent
  have : IsConnected Cfet := FEt.isConnected_of_connectedSpace Cfet
  obtain ⟨b₀⟩ := nonempty_fiber_of_isConnected F Cfet
  let a₀ : F.obj Z := F.map ι b₀
  -- the generators
  choose γ_ hγ_ using fun p : Aut F ↦ act_trans a₀ (p • a₀)
  refine ⟨s.image γ_, Finset.card_image_le, fun σ hσ ↦ ?_⟩
  let K := Subgroup.closure ((s.image γ_ : Finset (Aut X)) : Set (Aut X))
  have hK : ∀ p ∈ Subgroup.closure (s : Set (Aut F)), ∃ γ ∈ K, act γ a₀ = p • a₀ := by
    intro p hp
    induction hp using Subgroup.closure_induction with
    | mem p hp => exact ⟨γ_ p, Subgroup.subset_closure (Finset.mem_image_of_mem _ hp), hγ_ p⟩
    | one => exact ⟨1, K.one_mem, by rw [act_one, one_smul]⟩
    | mul p₁ p₂ _ _ h₁ h₂ =>
      obtain ⟨γ₁, hγ₁, e₁⟩ := h₁
      obtain ⟨γ₂, hγ₂, e₂⟩ := h₂
      refine ⟨γ₂ * γ₁, K.mul_mem hγ₂ hγ₁, ?_⟩
      rw [act_mul, e₁, ← act_comm, e₂, mul_smul]
    | inv p _ h =>
      obtain ⟨γ, hγ, e₁⟩ := h
      refine ⟨γ⁻¹, K.inv_mem hγ, ?_⟩
      have h1 : act γ (p⁻¹ • a₀) = a₀ := by rw [← act_comm, e₁, inv_smul_smul]
      calc act γ⁻¹ a₀ = act γ⁻¹ (act γ (p⁻¹ • a₀)) := by rw [h1]
        _ = p⁻¹ • a₀ := by rw [← act_mul, inv_mul_cancel, act_one]
  -- `σ` maps `C` into itself, hence restricts to an endomorphism `r` of `C`
  have hσC (y) (hy : y ∈ connectedComponent y₀) : σ • y ∈ connectedComponent y₀ :=
    mem_connectedComponent_of_mem_stabilizer q X hσ hy
  have hrange : Set.range (U.ι ≫ ((FEt.pullback q).map σ.hom).left) ⊆ Set.range U.ι := by
    rintro _ ⟨x, rfl⟩
    rw [Scheme.Opens.range_ι]
    exact hσC _ x.2
  let r₀ : U.toScheme ⟶ U.toScheme :=
    IsOpenImmersion.lift U.ι (U.ι ≫ ((FEt.pullback q).map σ.hom).left) hrange
  have hr₀ : r₀ ≫ U.ι = U.ι ≫ ((FEt.pullback q).map σ.hom).left := IsOpenImmersion.lift_fac _ _ _
  have hw : ((FEt.pullback q).map σ.hom).left ≫ Z.toBase = Z.toBase :=
    MorphismProperty.Over.w ((FEt.pullback q).map σ.hom)
  let r : Cfet ⟶ Cfet := MorphismProperty.Over.homMk r₀ (by
    change r₀ ≫ U.ι ≫ Z.toBase = U.ι ≫ Z.toBase
    rw [reassoc_of% hr₀, hw])
  have hrι : r ≫ ι = ι ≫ (FEt.pullback q).map σ.hom :=
    MorphismProperty.Over.Hom.ext hr₀
  have hσa₀ : act σ a₀ = F.map ι (F.map r b₀) := by
    change F.map ((FEt.pullback q).map σ.hom) (F.map ι b₀) = F.map ι (F.map r b₀)
    rw [← FintypeCat.comp_apply, ← F.map_comp, ← hrι, F.map_comp, FintypeCat.comp_apply]
  obtain ⟨p, hp⟩ := MulAction.exists_smul_eq (Aut F) b₀ (F.map r b₀)
  have hpa : p • a₀ = act σ a₀ := by
    rw [hσa₀, ← hp]
    exact mulAction_naturality F p ι b₀
  -- approximate `p` by an element of the dense subgroup generated by `s`
  have hopen : IsOpen {p' : Aut F | p' • a₀ = p • a₀} :=
    (continuous_id.smul continuous_const).isOpen_preimage _ (isOpen_discrete {p • a₀})
  obtain ⟨p', hp'mem, hp'⟩ := hs.exists_mem_open hopen ⟨p, rfl⟩
  obtain ⟨γ, hγK, hγ⟩ := hK p' hp'mem
  have : σ = γ := act_inj a₀ σ γ (by rw [hγ, show p' • a₀ = p • a₀ from hp', hpa])
  exact this ▸ hγK

end Vertex

section Edges

variable {S : Scheme.{u}} {ι : Type*} {S' : ι → Scheme.{u}} (g : ∀ i, S' i ⟶ S) (X : FEt S)

/-- The scheme `S'_i ×_S S'_j`. -/
noncomputable abbrev edgeBase (i j : ι) : Scheme.{u} := pullback (g i) (g j)

/-- The structure morphism `S'_i ×_S S'_j ⟶ S`. -/
noncomputable abbrev edgeMap (i j : ι) : pullback (g i) (g j) ⟶ S :=
  pullback.fst (g i) (g j) ≫ g i

/-- The first projection `X ×_S (S'_i ×_S S'_j) ⟶ X ×_S S'_i`. -/
noncomputable def edgeFst (i j : ι) :
    ((FEt.pullback (edgeMap g i j)).obj X).left ⟶ ((FEt.pullback (g i)).obj X).left :=
  pullback.lift (pullback.fst X.hom (edgeMap g i j))
    (pullback.snd X.hom (edgeMap g i j) ≫ pullback.fst (g i) (g j))
    ((pullback.condition).trans (Category.assoc _ _ _).symm)

/-- The second projection `X ×_S (S'_i ×_S S'_j) ⟶ X ×_S S'_j`. -/
noncomputable def edgeSnd (i j : ι) :
    ((FEt.pullback (edgeMap g i j)).obj X).left ⟶ ((FEt.pullback (g j)).obj X).left :=
  pullback.lift (pullback.fst X.hom (edgeMap g i j))
    (pullback.snd X.hom (edgeMap g i j) ≫ pullback.snd (g i) (g j))
    ((pullback.condition).trans ((congrArg (_ ≫ ·) pullback.condition).trans
      (Category.assoc _ _ _).symm))

attribute [local instance] pullbackAction

lemma edgeFst_comp_fst (i j : ι) :
    edgeFst g X i j ≫ pullback.fst X.hom (g i) = pullback.fst X.hom (edgeMap g i j) :=
  pullback.lift_fst _ _ _

lemma edgeSnd_comp_fst (i j : ι) :
    edgeSnd g X i j ≫ pullback.fst X.hom (g j) = pullback.fst X.hom (edgeMap g i j) :=
  pullback.lift_fst _ _ _

set_option backward.isDefEq.respectTransparency false in
lemma map_left_comp_edgeFst (i j : ι) (φ : X ⟶ X) :
    ((FEt.pullback (edgeMap g i j)).map φ).left ≫ edgeFst g X i j =
      edgeFst g X i j ≫ ((FEt.pullback (g i)).map φ).left := by
  apply pullback.hom_ext
  · refine (Category.assoc _ _ _).trans ?_
    refine ((congrArg (_ ≫ ·) (edgeFst_comp_fst g X i j)).trans
      (pullback_map_left_fst (edgeMap g i j) φ)).trans ?_
    refine Eq.trans ?_ (Category.assoc _ _ _).symm
    rw [pullback_map_left_fst, ← Category.assoc, edgeFst_comp_fst]
  · have hfs : edgeFst g X i j ≫ pullback.snd X.hom (g i) =
        pullback.snd X.hom (edgeMap g i j) ≫ pullback.fst (g i) (g j) := pullback.lift_snd _ _ _
    calc (((FEt.pullback (edgeMap g i j)).map φ).left ≫ edgeFst g X i j) ≫
          pullback.snd X.hom (g i)
        _ = ((FEt.pullback (edgeMap g i j)).map φ).left ≫
            (pullback.snd X.hom (edgeMap g i j) ≫ pullback.fst (g i) (g j)) :=
          (Category.assoc _ _ _).trans (congrArg (_ ≫ ·) hfs)
        _ = pullback.snd X.hom (edgeMap g i j) ≫ pullback.fst (g i) (g j) :=
          (Category.assoc _ _ _).symm.trans
            (congrArg (· ≫ pullback.fst (g i) (g j)) (pullback_map_left_snd _ φ))
        _ = edgeFst g X i j ≫ (((FEt.pullback (g i)).map φ).left ≫ pullback.snd X.hom (g i)) :=
          hfs.symm.trans (congrArg (_ ≫ ·) (pullback_map_left_snd _ φ).symm)
        _ = _ := (Category.assoc _ _ _).symm

set_option backward.isDefEq.respectTransparency false in
lemma map_left_comp_edgeSnd (i j : ι) (φ : X ⟶ X) :
    ((FEt.pullback (edgeMap g i j)).map φ).left ≫ edgeSnd g X i j =
      edgeSnd g X i j ≫ ((FEt.pullback (g j)).map φ).left := by
  apply pullback.hom_ext
  · refine (Category.assoc _ _ _).trans ?_
    refine ((congrArg (_ ≫ ·) (edgeSnd_comp_fst g X i j)).trans
      (pullback_map_left_fst (edgeMap g i j) φ)).trans ?_
    refine Eq.trans ?_ (Category.assoc _ _ _).symm
    rw [pullback_map_left_fst, ← Category.assoc, edgeSnd_comp_fst]
  · have hfs : edgeSnd g X i j ≫ pullback.snd X.hom (g j) =
        pullback.snd X.hom (edgeMap g i j) ≫ pullback.snd (g i) (g j) := pullback.lift_snd _ _ _
    calc (((FEt.pullback (edgeMap g i j)).map φ).left ≫ edgeSnd g X i j) ≫
          pullback.snd X.hom (g j)
        _ = ((FEt.pullback (edgeMap g i j)).map φ).left ≫
            (pullback.snd X.hom (edgeMap g i j) ≫ pullback.snd (g i) (g j)) :=
          (Category.assoc _ _ _).trans (congrArg (_ ≫ ·) hfs)
        _ = pullback.snd X.hom (edgeMap g i j) ≫ pullback.snd (g i) (g j) :=
          (Category.assoc _ _ _).symm.trans
            (congrArg (· ≫ pullback.snd (g i) (g j)) (pullback_map_left_snd _ φ))
        _ = edgeSnd g X i j ≫ (((FEt.pullback (g j)).map φ).left ≫ pullback.snd X.hom (g j)) :=
          hfs.symm.trans (congrArg (_ ≫ ·) (pullback_map_left_snd _ φ).symm)
        _ = _ := (Category.assoc _ _ _).symm

set_option backward.isDefEq.respectTransparency false in
lemma edgeFst_smul (i j : ι) (γ : Aut X) (z : ((FEt.pullback (edgeMap g i j)).obj X).left) :
    edgeFst g X i j (γ • z) = γ • edgeFst g X i j z := by
  rw [smul_def, smul_def, ← Scheme.Hom.comp_apply, map_left_comp_edgeFst, Scheme.Hom.comp_apply]

set_option backward.isDefEq.respectTransparency false in
lemma edgeSnd_smul (i j : ι) (γ : Aut X) (z : ((FEt.pullback (edgeMap g i j)).obj X).left) :
    edgeSnd g X i j (γ • z) = γ • edgeSnd g X i j z := by
  rw [smul_def, smul_def, ← Scheme.Hom.comp_apply, map_left_comp_edgeSnd, Scheme.Hom.comp_apply]

set_option backward.isDefEq.respectTransparency false in
/-- Two points of `X ×_S S'_i` and `X ×_S S'_j` with the same image in `X` come from a point of
`X ×_S (S'_i ×_S S'_j)`. -/
lemma exists_edgeFst_edgeSnd {i j : ι} (y : ((FEt.pullback (g i)).obj X).left)
    (y' : ((FEt.pullback (g j)).obj X).left)
    (h : pullback.fst X.hom (g i) y = pullback.fst X.hom (g j) y') :
    ∃ z, edgeFst g X i j z = y ∧ edgeSnd g X i j z = y' := by
  let fi : ((FEt.pullback (g i)).obj X).left ⟶ X.left := pullback.fst X.hom (g i)
  let fj : ((FEt.pullback (g j)).obj X).left ⟶ X.left := pullback.fst X.hom (g j)
  obtain ⟨p, hp₁, hp₂⟩ := Scheme.Pullback.exists_preimage_pullback (f := fi) (g := fj) y y' h
  have ci : pullback.snd X.hom (g i) ≫ g i = fi ≫ X.hom := pullback.condition.symm
  have cj : pullback.snd X.hom (g j) ≫ g j = fj ≫ X.hom := pullback.condition.symm
  have c₁ : (pullback.fst fi fj ≫ pullback.snd X.hom (g i)) ≫ g i =
      (pullback.snd fi fj ≫ pullback.snd X.hom (g j)) ≫ g j :=
    calc _ = (pullback.fst fi fj ≫ fi) ≫ X.hom :=
          (Category.assoc _ _ _).trans ((congrArg (_ ≫ ·) ci).trans (Category.assoc _ _ _).symm)
      _ = (pullback.snd fi fj ≫ fj) ≫ X.hom := congrArg (· ≫ X.hom) pullback.condition
      _ = _ := (Category.assoc _ _ _).trans ((congrArg (_ ≫ ·) cj.symm).trans
          (Category.assoc _ _ _).symm)
  let w : pullback fi fj ⟶ pullback (g i) (g j) := pullback.lift _ _ c₁
  have hw₁ : w ≫ pullback.fst (g i) (g j) = pullback.fst fi fj ≫ pullback.snd X.hom (g i) :=
    pullback.lift_fst _ _ _
  have hw₂ : w ≫ pullback.snd (g i) (g j) = pullback.snd fi fj ≫ pullback.snd X.hom (g j) :=
    pullback.lift_snd _ _ _
  have c₂ : (pullback.fst fi fj ≫ fi) ≫ X.hom = w ≫ edgeMap g i j :=
    calc _ = (pullback.fst fi fj ≫ pullback.snd X.hom (g i)) ≫ g i :=
          (Category.assoc _ _ _).trans ((congrArg (_ ≫ ·) ci.symm).trans
            (Category.assoc _ _ _).symm)
      _ = (w ≫ pullback.fst (g i) (g j)) ≫ g i := congrArg (· ≫ g i) hw₁.symm
      _ = _ := Category.assoc _ _ _
  let ψ : pullback fi fj ⟶ pullback X.hom (edgeMap g i j) := pullback.lift _ w c₂
  have hψf : ψ ≫ pullback.fst X.hom (edgeMap g i j) = pullback.fst fi fj ≫ fi :=
    pullback.lift_fst _ _ _
  have hψs : ψ ≫ pullback.snd X.hom (edgeMap g i j) = w := pullback.lift_snd _ _ _
  have hfs : edgeFst g X i j ≫ pullback.snd X.hom (g i) =
      pullback.snd X.hom (edgeMap g i j) ≫ pullback.fst (g i) (g j) := pullback.lift_snd _ _ _
  have hss : edgeSnd g X i j ≫ pullback.snd X.hom (g j) =
      pullback.snd X.hom (edgeMap g i j) ≫ pullback.snd (g i) (g j) := pullback.lift_snd _ _ _
  have hψ₁ : ψ ≫ edgeFst g X i j = pullback.fst fi fj := by
    apply pullback.hom_ext
    · exact (Category.assoc _ _ _).trans ((congrArg (ψ ≫ ·) (edgeFst_comp_fst g X i j)).trans hψf)
    · exact (Category.assoc _ _ _).trans ((congrArg (ψ ≫ ·) hfs).trans
        ((Category.assoc _ _ _).symm.trans ((congrArg (· ≫ _) hψs).trans hw₁)))
  have hψ₂ : ψ ≫ edgeSnd g X i j = pullback.snd fi fj := by
    apply pullback.hom_ext
    · exact (Category.assoc _ _ _).trans ((congrArg (ψ ≫ ·) (edgeSnd_comp_fst g X i j)).trans
        (hψf.trans pullback.condition))
    · exact (Category.assoc _ _ _).trans ((congrArg (ψ ≫ ·) hss).trans
        ((Category.assoc _ _ _).symm.trans ((congrArg (· ≫ _) hψs).trans hw₂)))
  refine ⟨ψ p, ?_, ?_⟩
  · exact (congrArg (fun f ↦ f p) hψ₁).trans hp₁
  · exact (congrArg (fun f ↦ f p) hψ₂).trans hp₂

end Edges

section Main

/-- A scheme of finite type over a noetherian scheme by a quasi-compact morphism is noetherian. -/
private lemma isNoetherian_of_quasiCompact {X Y : Scheme.{u}} (f : X ⟶ Y) [IsNoetherian Y]
    [QuasiCompact f] [LocallyOfFiniteType f] : IsNoetherian X :=
  have := LocallyOfFiniteType.isLocallyNoetherian f
  have := QuasiCompact.compactSpace_of_compactSpace f
  { }

private lemma mk_eq_mk_of_mk_eq {α β : Type*} [TopologicalSpace α] [TopologicalSpace β] {f : α → β}
    (hf : Continuous f) {a b : α} (h : ConnectedComponents.mk a = ConnectedComponents.mk b) :
    ConnectedComponents.mk (f a) = ConnectedComponents.mk (f b) := by
  rw [← hf.connectedComponentsMap_mk, ← hf.connectedComponentsMap_mk, h]

variable {S : Scheme.{u}} [IsNoetherian S] [ConnectedSpace S] {ι : Type*} [Fintype ι]
  {S' : ι → Scheme.{u}} (g : ∀ i, S' i ⟶ S) [∀ i, IsProper (g i)] [∀ i, ConnectedSpace (S' i)]

attribute [local instance] pullbackAction componentsAction

/-- **IX.5.2 for one Galois covering.** Let `g_i : S'_i ⟶ S` (`i ∈ I` finite) be proper morphisms
of connected schemes, jointly surjective onto the connected noetherian scheme `S`, and suppose
`π₁(S'_i, s_i)` is topologically generated by a finite set `gens i`. Then the automorphism group
of every Galois covering of `S` is generated by at most
`∑ᵢ #(gens i) + 2 ∑_{i,j} #π₀(S'_i ×_S S'_j)` elements. -/
theorem exists_card_le_closure_eq_top (hg : ∀ s : S, ∃ i, s ∈ Set.range (g i))
    {Ω : ι → Type u} [∀ i, Field (Ω i)] [∀ i, IsSepClosed (Ω i)]
    (s₀ : ∀ i, Spec (.of (Ω i)) ⟶ S' i)
    (gens : ∀ i, Finset (ExposeV.etaleFundamentalGroup (Ω i) (s₀ i)))
    (hgens : ∀ i, Dense (Subgroup.closure
      (gens i : Set (ExposeV.etaleFundamentalGroup (Ω i) (s₀ i))) :
        Set (ExposeV.etaleFundamentalGroup (Ω i) (s₀ i))))
    (X : FEt S) [IsGalois X] :
    ∃ t : Finset (Aut X), t.card ≤ ∑ i, (gens i).card +
      2 * ∑ ij : ι × ι, Nat.card (ConnectedComponents (edgeBase g ij.1 ij.2)) ∧
      Subgroup.closure (t : Set (Aut X)) = ⊤ := by
  classical
  have hS' (i : ι) : IsNoetherian (S' i) := isNoetherian_of_quasiCompact (g i)
  have hXi (i : ι) : IsNoetherian ((FEt.pullback (g i)).obj X).left := by
    have : IsFinite ((FEt.pullback (g i)).obj X).toBase := ((FEt.pullback (g i)).obj X).prop.1
    exact isNoetherian_of_quasiCompact ((FEt.pullback (g i)).obj X).toBase
  have hS'' (ij : ι × ι) : IsNoetherian (edgeBase g ij.1 ij.2) :=
    isNoetherian_of_quasiCompact (pullback.fst (g ij.1) (g ij.2))
  have hfinV (i : ι) : Finite (ConnectedComponents ((FEt.pullback (g i)).obj X).left) :=
    ExposeV.finite_connectedComponents_of_noetherianSpace _
  have hfinE (ij : ι × ι) : Fintype (ConnectedComponents (edgeBase g ij.1 ij.2)) :=
    have := ExposeV.finite_connectedComponents_of_noetherianSpace (edgeBase g ij.1 ij.2)
    Fintype.ofFinite _
  have : ConnectedSpace X.left := FEt.connectedSpace_of_isConnected X
  -- a point of each `X ×_S S'_i`
  have hne (i : ι) : Nonempty ((FEt.pullback (g i)).obj X).left := by
    obtain ⟨s'⟩ : Nonempty (S' i) := inferInstance
    obtain ⟨x, hx⟩ : g i s' ∈ Set.range X.toBase := by
      rw [FEt.range_eq_univ X]
      trivial
    obtain ⟨y, hy, -⟩ := Scheme.Pullback.exists_preimage_pullback (f := X.hom) (g := g i) x s' hx
    exact ⟨y⟩
  let y (i : ι) : ((FEt.pullback (g i)).obj X).left := Classical.choice (hne i)
  -- the vertex groups
  choose t ht_card ht_stab using fun i ↦
    exists_stabilizer_le_closure (g i) X (s₀ i) (hgens i) (y i)
  -- the edge elements
  have hE (e : Σ ij : ι × ι, ConnectedComponents (edgeBase g ij.1 ij.2)) :
      ∃ αβ : Aut X × Aut X, ∀ z : ((FEt.pullback (edgeMap g e.1.1 e.1.2)).obj X).left,
        ConnectedComponents.mk (((FEt.pullback (edgeMap g e.1.1 e.1.2)).obj X).toBase z) = e.2 →
        ∃ γ : Aut X, ConnectedComponents.mk (edgeFst g X e.1.1 e.1.2 z) =
            γ • αβ.1 • ConnectedComponents.mk (y e.1.1) ∧
          ConnectedComponents.mk (edgeSnd g X e.1.1 e.1.2 z) =
            γ • αβ.2 • ConnectedComponents.mk (y e.1.2) := by
    obtain ⟨⟨i, j⟩, T⟩ := e
    by_cases h : ∃ z₀ : ((FEt.pullback (edgeMap g i j)).obj X).left,
      ConnectedComponents.mk (((FEt.pullback (edgeMap g i j)).obj X).toBase z₀) = T
    swap
    · exact ⟨(1, 1), fun z hz ↦ (h ⟨z, hz⟩).elim⟩
    obtain ⟨z₀, hz₀⟩ := h
    have hvert {k : ι} (w : ((FEt.pullback (g k)).obj X).left) :
        ∃ α : Aut X, ConnectedComponents.mk w = α • ConnectedComponents.mk (y k) := by
      obtain ⟨α, hα⟩ := exists_smul_mem_connectedComponent (g k) X (y k) w (by
        rw [PreconnectedSpace.connectedComponent_eq_univ,
          PreconnectedSpace.connectedComponent_eq_univ])
      exact ⟨α, by rw [smul_mk]; exact (ConnectedComponents.coe_eq_coe'.mpr hα).symm⟩
    obtain ⟨α, hα⟩ := hvert (edgeFst g X i j z₀)
    obtain ⟨β, hβ⟩ := hvert (edgeSnd g X i j z₀)
    refine ⟨(α, β), fun z hz ↦ ?_⟩
    obtain ⟨γ, hγ⟩ := exists_smul_mem_connectedComponent (edgeMap g i j) X z₀ z
      (ConnectedComponents.coe_eq_coe.mp (hz₀.trans hz.symm))
    have hγ' : ConnectedComponents.mk (γ • z₀) = ConnectedComponents.mk z :=
      ConnectedComponents.coe_eq_coe'.mpr hγ
    refine ⟨γ, ?_, ?_⟩
    · rw [← mk_eq_mk_of_mk_eq (edgeFst g X i j).continuous hγ', edgeFst_smul, ← smul_mk, hα]
    · rw [← mk_eq_mk_of_mk_eq (edgeSnd g X i j).continuous hγ', edgeSnd_smul, ← smul_mk, hβ]
  choose αβ hαβ using hE
  let E := Σ ij : ι × ι, ConnectedComponents (edgeBase g ij.1 ij.2)
  let T : Finset (Aut X) := Finset.univ.biUnion t ∪ Finset.univ.image (fun e : E ↦ (αβ e).1) ∪
    Finset.univ.image (fun e : E ↦ (αβ e).2)
  have hcardE : Fintype.card E =
      ∑ ij : ι × ι, Nat.card (ConnectedComponents (edgeBase g ij.1 ij.2)) := by
    rw [Fintype.card_sigma]
    exact Finset.sum_congr rfl fun ij _ ↦ Nat.card_eq_fintype_card.symm
  refine ⟨T, ?_, ?_⟩
  · have h1 : (Finset.univ.biUnion t).card ≤ ∑ i, (gens i).card :=
      Finset.card_biUnion_le.trans (Finset.sum_le_sum fun i _ ↦ ht_card i)
    have h2 : (Finset.univ.image (fun e : E ↦ (αβ e).1)).card ≤ Fintype.card E :=
      Finset.card_image_le.trans_eq Finset.card_univ
    have h3 : (Finset.univ.image (fun e : E ↦ (αβ e).2)).card ≤ Fintype.card E :=
      Finset.card_image_le.trans_eq Finset.card_univ
    calc T.card ≤ (Finset.univ.biUnion t).card + (Finset.univ.image (fun e : E ↦ (αβ e).1)).card +
          (Finset.univ.image (fun e : E ↦ (αβ e).2)).card :=
        (Finset.card_union_le _ _).trans (Nat.add_le_add_right (Finset.card_union_le _ _) _)
      _ ≤ ∑ i, (gens i).card + Fintype.card E + Fintype.card E := by gcongr
      _ = _ := by rw [hcardE]; ring
  let K := Subgroup.closure (T : Set (Aut X))
  have hTK {γ : Aut X} (h : γ ∈ T) : γ ∈ K := Subgroup.subset_closure h
  let V := Σ i, ConnectedComponents ((FEt.pullback (g i)).obj X).left
  let _ : MulAction (Aut X) V :=
    { smul := fun γ v ↦ ⟨v.1, γ • v.2⟩
      one_smul := fun v ↦ by
        change (⟨v.1, (1 : Aut X) • v.2⟩ : V) = v
        rw [one_smul]
      mul_smul := fun γ δ v ↦ by
        change (⟨v.1, (γ * δ) • v.2⟩ : V) = ⟨v.1, γ • δ • v.2⟩
        rw [mul_smul] }
  have hsmul (γ : Aut X) (i : ι) (c : ConnectedComponents ((FEt.pullback (g i)).obj X).left) :
      γ • (⟨i, c⟩ : V) = ⟨i, γ • c⟩ := rfl
  let Adj : V → V → Prop := fun v w ↦ ∃ z : ((FEt.pullback (edgeMap g v.1 w.1)).obj X).left,
    ConnectedComponents.mk (edgeFst g X v.1 w.1 z) = v.2 ∧
      ConnectedComponents.mk (edgeSnd g X v.1 w.1 z) = w.2
  let R : Set V := Set.range fun i ↦ (⟨i, ConnectedComponents.mk (y i)⟩ : V)
  refine DescentFiniteGeneration.eq_top_of_adj (V := V) Adj ?_ R ?_ ?_ K ?_ ?_
  · -- the graph is connected, because `∐ X ×_S S'_i ⟶ X` is closed and surjective
    intro W hWne hW
    by_contra hcon
    obtain ⟨v₀, hv₀⟩ := not_forall.mp hcon
    let f (i : ι) : ((FEt.pullback (g i)).obj X).left → X.left := pullback.fst X.hom (g i)
    have hfc (i : ι) : IsClosedMap (f i) := (pullback.fst X.hom (g i)).isClosedMap
    let comp (v : V) : Set ((FEt.pullback (g v.1)).obj X).left :=
      {y | ConnectedComponents.mk y = v.2}
    have hcomp (v : V) : IsClosed (comp v) ∧ (comp v).Nonempty := by
      obtain ⟨y₁, hy₁⟩ := ConnectedComponents.surjective_coe v.2
      have : comp v = connectedComponent y₁ := by
        ext y
        change ConnectedComponents.mk y = v.2 ↔ _
        rw [← hy₁, ConnectedComponents.coe_eq_coe']
      rw [this]
      exact ⟨isClosed_connectedComponent, ⟨y₁, mem_connectedComponent⟩⟩
    let Y₁ : Set X.left := ⋃ v ∈ W, f v.1 '' comp v
    let Y₂ : Set X.left := ⋃ v ∈ Wᶜ, f v.1 '' comp v
    have hY₁ : IsClosed Y₁ := (Set.toFinite W).isClosed_biUnion fun v _ ↦ hfc v.1 _ (hcomp v).1
    have hY₂ : IsClosed Y₂ := (Set.toFinite _).isClosed_biUnion fun v _ ↦ hfc v.1 _ (hcomp v).1
    have hcover (x : X.left) : x ∈ Y₁ ∨ x ∈ Y₂ := by
      obtain ⟨i, s', hs'⟩ := hg (X.toBase x)
      obtain ⟨y', hy', -⟩ :=
        Scheme.Pullback.exists_preimage_pullback (f := X.hom) (g := g i) x s' hs'.symm
      let v : V := ⟨i, ConnectedComponents.mk y'⟩
      by_cases hv : v ∈ W
      · exact Or.inl (Set.mem_biUnion hv ⟨y', rfl, hy'⟩)
      · exact Or.inr (Set.mem_biUnion (s := Wᶜ) hv ⟨y', rfl, hy'⟩)
    have hdisj (x : X.left) (h₁ : x ∈ Y₁) (h₂ : x ∈ Y₂) : False := by
      obtain ⟨v, hv, y₁, hy₁, rfl⟩ := Set.mem_iUnion₂.mp h₁
      obtain ⟨w, hw, y₂, hy₂, hxy⟩ := Set.mem_iUnion₂.mp h₂
      obtain ⟨z, hz₁, hz₂⟩ := exists_edgeFst_edgeSnd g X y₁ y₂ hxy.symm
      have hadj : Adj v w := ⟨z, by rw [hz₁]; exact hy₁, by rw [hz₂]; exact hy₂⟩
      exact hw ((hW v w hadj).mp hv)
    have hclopen : IsClopen Y₁ := by
      refine ⟨hY₁, ?_⟩
      have : Y₁ᶜ = Y₂ := by
        ext x
        exact ⟨fun h ↦ (hcover x).resolve_left h, fun h h' ↦ hdisj x h' h⟩
      rw [← isClosed_compl_iff, this]
      exact hY₂
    rcases isClopen_iff.mp hclopen with h | h
    · obtain ⟨w, hw⟩ := hWne
      obtain ⟨yw, hyw⟩ := (hcomp w).2
      have : f w.1 yw ∈ Y₁ := Set.mem_biUnion hw ⟨yw, hyw, rfl⟩
      rw [h] at this
      exact this
    · obtain ⟨yv, hyv⟩ := (hcomp v₀).2
      exact hdisj (f v₀.1 yv) (h ▸ trivial) (Set.mem_biUnion (s := Wᶜ) hv₀ ⟨yv, hyv, rfl⟩)
  · rintro _ ⟨i, rfl⟩ _ ⟨i', rfl⟩ γ h
    rw [hsmul] at h
    obtain rfl : i = i' := congrArg Sigma.fst h
    rfl
  · obtain ⟨s⟩ : Nonempty S := inferInstance
    obtain ⟨i, -⟩ := hg s
    exact ⟨_, ⟨i, rfl⟩⟩
  · rintro _ ⟨i, rfl⟩ γ hγ
    have hγ' : γ • ConnectedComponents.mk (y i) = ConnectedComponents.mk (y i) := by
      have h := (MulAction.mem_stabilizer_iff.mp hγ)
      rw [hsmul] at h
      exact eq_of_heq (Sigma.mk.inj_iff.mp h).2
    refine Subgroup.closure_mono ?_ (ht_stab i (MulAction.mem_stabilizer_iff.mpr hγ'))
    intro δ hδ
    exact Finset.mem_union_left _ (Finset.mem_union_left _
      (Finset.mem_biUnion.mpr ⟨i, Finset.mem_univ _, hδ⟩))
  · rintro ⟨i, c⟩ ⟨j, c'⟩ ⟨z, hz₁, hz₂⟩
    let e : E := ⟨(i, j), ConnectedComponents.mk (((FEt.pullback (edgeMap g i j)).obj X).toBase z)⟩
    obtain ⟨γ, h₁, h₂⟩ := hαβ e z rfl
    refine ⟨γ, (αβ e).1, hTK (Finset.mem_union_left _ (Finset.mem_union_right _
      (Finset.mem_image_of_mem _ (Finset.mem_univ e)))), (αβ e).2,
      hTK (Finset.mem_union_right _ (Finset.mem_image_of_mem _ (Finset.mem_univ e))),
      _, ⟨i, rfl⟩, _, ⟨j, rfl⟩, ?_, ?_⟩
    · exact congrArg (Sigma.mk (β := fun i ↦ ConnectedComponents ((FEt.pullback (g i)).obj X).left)
        i) (hz₁.symm.trans h₁)
    · exact congrArg (Sigma.mk (β := fun i ↦ ConnectedComponents ((FEt.pullback (g i)).obj X).left)
        j) (hz₂.symm.trans h₂)

end Main

end DescentFiniteGeneration

section Family

open ExposeV DescentFiniteGeneration

variable {S : Scheme.{u}} [IsNoetherian S] [ConnectedSpace S] {ι : Type*} [Finite ι]
  {S' : ι → Scheme.{u}} (g : ∀ i, S' i ⟶ S) [∀ i, IsProper (g i)] [∀ i, ConnectedSpace (S' i)]

/-- **IX.5.2** (finite generation), for a finite family: let `S` be a connected noetherian scheme
and `g_i : S'_i ⟶ S` (`i` in a finite set) proper morphisms from connected schemes, jointly
surjective. If each `π₁(S'_i)` is topologically finitely generated (at some geometric point),
then `π₁(S, s)` is topologically finitely generated at every geometric point `s`.

SGA has a single effective descent morphism `g : S' ⟶ S` for étale coverings, with `S'` and
`S' ×_S S'` having finitely many connected components. Here `S` is noetherian and `S'` is the
disjoint union of finitely many connected `S'_i`, the `g_i` proper and jointly surjective
(descent is not used; the morphism form is
`isTopologicallyFG_etaleFundamentalGroup_of_isProper_of_surjective`). -/
theorem isTopologicallyFG_etaleFundamentalGroup_of_family
    (hg : ∀ s : S, ∃ i, s ∈ Set.range (g i))
    (hfg : ∀ i, ∃ (Ω : Type u) (_ : Field Ω) (_ : IsSepClosed Ω) (s : Spec (.of Ω) ⟶ S' i),
      ExposeXIII.IsTopologicallyFG (ExposeV.etaleFundamentalGroup Ω s))
    (Ω : Type u) [Field Ω] [IsSepClosed Ω] (s : Spec (.of Ω) ⟶ S) :
    ExposeXIII.IsTopologicallyFG (ExposeV.etaleFundamentalGroup Ω s) := by
  let _ : Fintype ι := Fintype.ofFinite ι
  choose Ωi _ _ s₀ hs using hfg
  choose gens hgens using hs
  obtain ⟨t, -, ht⟩ := exists_finset_card_le_dense_closure_aut_of_forall_isGalois
    (FEt.fiber Ω s) _ fun X _ ↦ exists_card_le_closure_eq_top g hg s₀ gens hgens X
  exact ⟨t, ht⟩

end Family

section Morphism

open ExposeV DescentFiniteGeneration

variable {S S' : Scheme.{u}} [IsNoetherian S] [ConnectedSpace S] (g : S' ⟶ S) [IsProper g]
  [Surjective g]

include g in
/-- **IX.5.2** (finite generation), for proper surjective morphisms: let `S` be a connected
noetherian scheme and `g : S' ⟶ S` proper and surjective. If the fundamental group of every
connected component of `S'` (i.e. of every connected open and closed subscheme) is topologically
finitely generated, so is the fundamental group of `S`, at every geometric point.

SGA assumes instead that `g` is an effective descent morphism for étale coverings and that `S'`
and `S' ×_S S'` have finitely many connected components. Here `S` is noetherian and `g` is proper
and surjective (such a `g` is an effective descent morphism, IX.4.12, but descent is not used:
the proof uses that `g` is universally closed and surjective, and of finite type and
quasi-compact so that `S'`, `S' ×_S S'` and the `X ×_S S'` are noetherian). -/
theorem isTopologicallyFG_etaleFundamentalGroup_of_isProper_of_surjective
    (hfg : ∀ U : S'.Opens, IsClopen (U : Set S') → ConnectedSpace U →
      ∃ (Ω : Type u) (_ : Field Ω) (_ : IsSepClosed Ω) (s : Spec (.of Ω) ⟶ U),
        ExposeXIII.IsTopologicallyFG (ExposeV.etaleFundamentalGroup Ω s))
    (Ω : Type u) [Field Ω] [IsSepClosed Ω] (s : Spec (.of Ω) ⟶ S) :
    ExposeXIII.IsTopologicallyFG (ExposeV.etaleFundamentalGroup Ω s) := by
  have : IsNoetherian S' := isNoetherian_of_quasiCompact g
  have := ExposeV.finite_connectedComponents_of_noetherianSpace S'
  let U := ExposeV.connectedComponentOpens S'
  have hU (c : ConnectedComponents S') : IsClosedImmersion (U c).ι := by
    refine IsClosedImmersion.of_isPreimmersion _ ?_
    rw [Scheme.Opens.range_ι]
    exact (isClopen_discrete {c}).isClosed.preimage ConnectedComponents.continuous_coe
  have (c : ConnectedComponents S') : IsProper ((U c).ι ≫ g) := by
    have := hU c
    infer_instance
  refine isTopologicallyFG_etaleFundamentalGroup_of_family (fun c ↦ (U c).ι ≫ g) (fun x ↦ ?_)
    (fun c ↦ hfg (U c) ((isClopen_discrete {c}).preimage ConnectedComponents.continuous_coe)
      inferInstance) Ω s
  obtain ⟨x', rfl⟩ := g.surjective x
  exact ⟨ConnectedComponents.mk x', ⟨x', rfl⟩, rfl⟩

end Morphism

end SGA.SGA1.ExposeIX
