/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.SGA1.ExposeIX.ConnectedFibres
import SGA.SGA1.ExposeIX.GaloisFunctors
import SGA.SGA1.ExposeIX.TopologicalInvariance
import SGA.SGA1.ExposeIX.NilImmersion

/-!
# SGA 1, Exposé IX, §5: descent and the fundamental group

IX.5 computes `π₁(S)` from `π₁(S')`, `π₁(S'')`, `π₁(S''')` when `g : S' ⟶ S` is an effective descent
morphism for étale coverings. We formalize the Galois-categorical form: a truncated diagram
`C' ⇉ C'' ⇶ C'''` (`DescentDiagram`) with its category of descent data and the comparison functor
from `C`, and fibre functors at a point of `S'` and its diagonal images (`DiagonalPoint`). The main
result is IX.5.6, i.e. IX.5.1 when `S'` and `S''` are connected: the kernel of `π₁(S') → π₁(S)` is
the closed normal subgroup generated by the `p₁*(g) p₂*(g)⁻¹` (`ker_autMap_eq_relations`) and
`π₁(S) ≅ π₁(S')/N` (`quotientRelationsEquiv`). Its instance for schemes is in
`FiniteEtaleDescentDiagram`.

Scheme-level consequences proved here: surjectivity of `π₁(S') → π₁(S)` for universally submersive
`g` with geometrically connected fibres, and the topological invariance of `π₁` (remark after
IX.5.3): `π₁(S') ≅ π₁(S)` for `g` finite, radicial, surjective and of finite presentation (IX.4.10,
`bijective_etaleFundamentalGroup_map_of_isFinite`) and for nil-immersions (IX.1.7,
`bijective_etaleFundamentalGroup_map_of_isClosedImmersion`); the étale coverings are handled by
the descent of finiteness along universally closed surjective morphisms
(`isFinite_of_isFinite_pullback`). They are first proved for any Galois
structures and fibre functors, then for the fundamental groups of Exposé V at geometric points
(`surjective_etaleFundamentalGroup_map`, `full_etalePullback`,
`bijective_etaleFundamentalGroup_map_iff`), where the Galois structures are those of V.7. The
presentation
IX.5.1 for disconnected `S'`, `S''` and IX.5.3–IX.5.5, IX.5.7 need profinite presentations and are
not formalized; for IX.5.8 only the group-theoretic translation (`ker_autMap_eq_iff_of_family`) is.
-/

universe v₁ v₂ v₃ v₄ u₁ u₂ u₃ u₄ w u

namespace SGA.SGA1.ExposeIX

open CategoryTheory CategoryTheory.Functor CategoryTheory.Limits PreGaloisCategory

/-- The truncated diagram `C' ⇉ C'' ⇶ C'''` of IX.5 (*): the inverse image functors along the two
projections `S'' = S' ×_S S' ⇉ S'` and the three projections `S''' ⇶ S''`, with the canonical
isomorphisms `p₂₁^* p₁^* ≅ p₃₁^* p₁^*`, `p₂₁^* p₂^* ≅ p₃₂^* p₁^*`, `p₃₁^* p₂^* ≅ p₃₂^* p₂^*`
(the three composites are the inverse images along the three projections `S''' → S'`). -/
structure DescentDiagram (C' : Type u₂) [Category.{v₂} C'] (C'' : Type u₃) [Category.{v₃} C'']
    (C''' : Type u₄) [Category.{v₄} C'''] where
  /-- the inverse image `p₁^*` along the first projection `S'' → S'` -/
  p₁ : C' ⥤ C''
  /-- the inverse image `p₂^*` along the second projection `S'' → S'` -/
  p₂ : C' ⥤ C''
  /-- the inverse image along the projection of `S'''` onto its factors `1, 2` -/
  p₂₁ : C'' ⥤ C'''
  /-- the inverse image along the projection of `S'''` onto its factors `2, 3` -/
  p₃₂ : C'' ⥤ C'''
  /-- the inverse image along the projection of `S'''` onto its factors `1, 3` -/
  p₃₁ : C'' ⥤ C'''
  /-- both sides are the inverse image along the first projection `S''' → S'` -/
  e₁ : p₁ ⋙ p₂₁ ≅ p₁ ⋙ p₃₁
  /-- both sides are the inverse image along the second projection `S''' → S'` -/
  e₂ : p₂ ⋙ p₂₁ ≅ p₁ ⋙ p₃₂
  /-- both sides are the inverse image along the third projection `S''' → S'` -/
  e₃ : p₂ ⋙ p₃₁ ≅ p₂ ⋙ p₃₂

namespace DescentDiagram

variable {C : Type u₁} [Category.{v₁} C] {C' : Type u₂} [Category.{v₂} C']
  {C'' : Type u₃} [Category.{v₃} C''] {C''' : Type u₄} [Category.{v₄} C''']
  (D : DescentDiagram C' C'' C''')

/-- The cocycle condition `p₃₁^* φ = p₃₂^* φ ∘ p₂₁^* φ` on a gluing datum `φ : p₁^* Y ≅ p₂^* Y`. -/
def IsCocycle {Y : C'} (φ : D.p₁.obj Y ≅ D.p₂.obj Y) : Prop :=
  D.p₂₁.map φ.hom ≫ D.e₂.hom.app Y ≫ D.p₃₂.map φ.hom =
    D.e₁.hom.app Y ≫ D.p₃₁.map φ.hom ≫ D.e₃.hom.app Y

/-- An object of `C'` with a descent datum. -/
structure Datum where
  /-- the underlying object -/
  obj : C'
  /-- the gluing datum -/
  φ : D.p₁.obj obj ≅ D.p₂.obj obj
  cocycle : D.IsCocycle φ

/-- Morphisms of objects with descent data. -/
@[ext]
structure Datum.Hom (X Y : D.Datum) where
  /-- the underlying morphism -/
  hom : X.obj ⟶ Y.obj
  comm : D.p₁.map hom ≫ Y.φ.hom = X.φ.hom ≫ D.p₂.map hom

attribute [reassoc] Datum.Hom.comm

instance Datum.category : Category D.Datum where
  Hom := Datum.Hom D
  id X := ⟨𝟙 _, by simp⟩
  comp f g := ⟨f.hom ≫ g.hom, by simp [Datum.Hom.comm, Datum.Hom.comm_assoc]⟩

@[simp]
lemma Datum.id_hom (X : D.Datum) : Datum.Hom.hom (𝟙 X) = 𝟙 X.obj := rfl

@[simp]
lemma Datum.comp_hom {X Y Z : D.Datum} (f : X ⟶ Y) (g : Y ⟶ Z) :
    Datum.Hom.hom (f ≫ g) = f.hom ≫ g.hom := rfl

/-- The forgetful functor from objects with descent data. -/
@[simps]
def Datum.forget : D.Datum ⥤ C' where
  obj X := X.obj
  map f := f.hom

/-- The comparison functor `C ⥤ D.Datum`, `X ↦ (H X, ε_X)`, given the canonical descent data
`ε : H ⋙ p₁ ≅ H ⋙ p₂` on the inverse images. `g : S' → S` is a descent (resp. effective descent)
morphism when this functor is fully faithful (resp. an equivalence). -/
@[simps]
def comparison (H : C ⥤ C') (ε : H ⋙ D.p₁ ≅ H ⋙ D.p₂) (hε : ∀ X, D.IsCocycle (ε.app X)) :
    C ⥤ D.Datum where
  obj X := ⟨H.obj X, ε.app X, hε X⟩
  map f := ⟨H.map f, ε.hom.naturality f⟩

variable (F' : C' ⥤ FintypeCat.{w}) (F'' : C'' ⥤ FintypeCat.{w}) (F''' : C''' ⥤ FintypeCat.{w})

/-- Fibre functors at a geometric point `s'` of `S'` and at its images under the diagonals
`S' → S''` and `S' → S'''`, together with the identifications of fibres coming from
`pᵢ ∘ Δ = id`. With these choices the "classes of paths" of IX.5 are trivial. -/
structure DiagonalPoint where
  /-- `F'' ∘ p₁^* ≅ F'` -/
  d₁ : D.p₁ ⋙ F'' ≅ F'
  /-- `F'' ∘ p₂^* ≅ F'` -/
  d₂ : D.p₂ ⋙ F'' ≅ F'
  /-- `F''' ∘ p₂₁^* ≅ F''` -/
  d₂₁ : D.p₂₁ ⋙ F''' ≅ F''
  /-- `F''' ∘ p₃₂^* ≅ F''` -/
  d₃₂ : D.p₃₂ ⋙ F''' ≅ F''
  /-- `F''' ∘ p₃₁^* ≅ F''` -/
  d₃₁ : D.p₃₁ ⋙ F''' ≅ F''
  comm₁ (Y : C') : F'''.map (D.e₁.hom.app Y) ≫ d₃₁.hom.app (D.p₁.obj Y) ≫ d₁.hom.app Y =
    d₂₁.hom.app (D.p₁.obj Y) ≫ d₁.hom.app Y
  comm₂ (Y : C') : F'''.map (D.e₂.hom.app Y) ≫ d₃₂.hom.app (D.p₁.obj Y) ≫ d₁.hom.app Y =
    d₂₁.hom.app (D.p₂.obj Y) ≫ d₂.hom.app Y
  comm₃ (Y : C') : F'''.map (D.e₃.hom.app Y) ≫ d₃₂.hom.app (D.p₂.obj Y) ≫ d₂.hom.app Y =
    d₃₁.hom.app (D.p₂.obj Y) ≫ d₂.hom.app Y

namespace DiagonalPoint

attribute [reassoc] comm₁ comm₂ comm₃

variable {D F' F'' F'''} (P : D.DiagonalPoint F' F'' F''')

/-- The homomorphism `p₁* : π₁(S'', Δ s') → π₁(S', s')`. -/
def q₁ : Aut F'' →* Aut F' :=
  P.d₁.conjAut.toMonoidHom.comp (autMap D.p₁ F'')

/-- The homomorphism `p₂* : π₁(S'', Δ s') → π₁(S', s')`. -/
def q₂ : Aut F'' →* Aut F' :=
  P.d₂.conjAut.toMonoidHom.comp (autMap D.p₂ F'')

lemma q₁_hom_app (g : Aut F'') (Y : C') :
    (P.q₁ g).hom.app Y = P.d₁.inv.app Y ≫ g.hom.app (D.p₁.obj Y) ≫ P.d₁.hom.app Y := by
  simp [q₁, Iso.conjAut_hom, Iso.conj_apply]

lemma q₂_hom_app (g : Aut F'') (Y : C') :
    (P.q₂ g).hom.app Y = P.d₂.inv.app Y ≫ g.hom.app (D.p₂.obj Y) ≫ P.d₂.hom.app Y := by
  simp [q₂, Iso.conjAut_hom, Iso.conj_apply]

lemma q₁_smul (g : Aut F'') {Y : C'} (z : F''.obj (D.p₁.obj Y)) :
    P.q₁ g • P.d₁.hom.app Y z = P.d₁.hom.app Y (g • z) := by
  change (P.q₁ g).hom.app Y (P.d₁.hom.app Y z) = _
  simp [q₁_hom_app, mulAction_def]

lemma q₂_smul (g : Aut F'') {Y : C'} (z : F''.obj (D.p₂.obj Y)) :
    P.q₂ g • P.d₂.hom.app Y z = P.d₂.hom.app Y (g • z) := by
  change (P.q₂ g).hom.app Y (P.d₂.hom.app Y z) = _
  simp [q₂_hom_app, mulAction_def]

section cocycle

variable [GaloisCategory C''] [FiberFunctor F''] [F'''.Faithful]

/-- If `p₁*` and `p₂*` act in the same way on the fibre of `Y`, the identification
`F''(p₁^* Y) ≅ F' Y ≅ F''(p₂^* Y)` at the diagonal point lifts to a descent datum on `Y`. -/
lemma exists_isCocycle (Y : C')
    (hY : ∀ (g : Aut F'') (y : F'.obj Y), P.q₁ g • y = P.q₂ g • y) :
    ∃ φ : D.p₁.obj Y ≅ D.p₂.obj Y,
      D.IsCocycle φ ∧ F''.map φ.hom ≫ P.d₂.hom.app Y = P.d₁.hom.app Y := by
  let ψ : F''.obj (D.p₁.obj Y) ⟶ F''.obj (D.p₂.obj Y) := P.d₁.hom.app Y ≫ P.d₂.inv.app Y
  have hψ (g : Aut F'') (z : F''.obj (D.p₁.obj Y)) : ψ (g • z) = g • ψ z := by
    apply (FintypeCat.equivEquivIso.symm (P.d₂.app Y)).injective
    change P.d₂.hom.app Y (P.d₂.inv.app Y (P.d₁.hom.app Y (g • z))) =
      P.d₂.hom.app Y (g • P.d₂.inv.app Y (P.d₁.hom.app Y z))
    rw [← q₂_smul, ← q₁_smul]
    simp [hY]
  let ψA : (functorToAction F'').obj (D.p₁.obj Y) ⟶ (functorToAction F'').obj (D.p₂.obj Y) :=
    ⟨ψ, fun g ↦ by
      ext z
      exact hψ g z⟩
  obtain ⟨φ₀, hφ₀⟩ := (functorToAction F'').map_surjective ψA
  have h1 : F''.map φ₀ = ψ := congrArg Action.Hom.hom hφ₀
  have : IsIso (F''.map φ₀) := by
    rw [h1]
    infer_instance
  have : IsIso φ₀ := isIso_of_reflects_iso φ₀ F''
  have h2 : F''.map φ₀ ≫ P.d₂.hom.app Y = P.d₁.hom.app Y := by simp [h1, ψ]
  have n₂₁ := P.d₂₁.hom.naturality φ₀
  have n₃₂ := P.d₃₂.hom.naturality φ₀
  have n₃₁ := P.d₃₁.hom.naturality φ₀
  simp only [Functor.comp_map] at n₂₁ n₃₂ n₃₁
  refine ⟨asIso φ₀, ?_, h2⟩
  apply F'''.map_injective
  rw [← cancel_mono (P.d₃₂.hom.app (D.p₂.obj Y) ≫ P.d₂.hom.app Y)]
  simp only [asIso_hom, Functor.map_comp, Category.assoc]
  rw [reassoc_of% n₃₂, h2, P.comm₂, reassoc_of% n₂₁, h2, P.comm₃, reassoc_of% n₃₁, h2,
    P.comm₁]

end cocycle

/-- The closed normal subgroup of `π₁(S', s')` generated by the elements `p₁*(g) p₂*(g)⁻¹`,
`g ∈ π₁(S'', Δ s')`. -/
def relations : Subgroup (Aut F') :=
  (Subgroup.normalClosure (Set.range fun g : Aut F'' ↦ P.q₁ g * (P.q₂ g)⁻¹)).topologicalClosure

instance relations_normal : P.relations.Normal :=
  Subgroup.is_normal_topologicalClosure _

lemma isClosed_relations : IsClosed (P.relations : Set (Aut F')) :=
  Subgroup.isClosed_topologicalClosure _

/-- `relations` acts trivially on `F' Y` exactly when `p₁*` and `p₂*` act in the same way. -/
lemma forall_mem_relations_smul_eq_iff (Y : C') :
    (∀ σ ∈ P.relations, ∀ y : F'.obj Y, σ • y = y) ↔
      ∀ (g : Aut F'') (y : F'.obj Y), P.q₁ g • y = P.q₂ g • y := by
  rw [relations, forall_mem_normalClosure_smul_eq_iff]
  refine ⟨fun h g y ↦ ?_, fun h σ ⟨g, hg⟩ y ↦ ?_⟩
  · simpa [mul_smul] using h _ ⟨g, rfl⟩ (P.q₂ g • y)
  · rw [← hg, mul_smul, h, smul_inv_smul]

variable {C : Type u₁} [Category.{v₁} C] (H : C ⥤ C') (ε : H ⋙ D.p₁ ≅ H ⋙ D.p₂)
  (hε : ∀ X, D.IsCocycle (ε.app X))

/-- At the diagonal point, the canonical descent datum `ε` of an inverse image is the
identity of fibres. -/
def IsTrivialOn : Prop :=
  ∀ X : C, F''.map (ε.hom.app X) ≫ P.d₂.hom.app (H.obj X) = P.d₁.hom.app (H.obj X)

variable {H ε}

lemma q₁_mul_inv_mem_ker (hPε : P.IsTrivialOn H ε) (g : Aut F'') :
    P.q₁ g * (P.q₂ g)⁻¹ ∈ (autMap H F').ker := by
  rw [MonoidHom.mem_ker, map_mul, _root_.map_inv, mul_inv_eq_one]
  ext X : 3
  have h := hPε X
  have h' : P.d₁.inv.app (H.obj X) = P.d₂.inv.app (H.obj X) ≫ F''.map (ε.inv.app X) := by
    rw [← cancel_epi (P.d₁.hom.app (H.obj X)), Iso.hom_inv_id_app, ← h, Category.assoc,
      Iso.hom_inv_id_app_assoc, ← F''.map_comp, Iso.hom_inv_id_app, F''.map_id]
    rfl
  have hn := g.hom.naturality (ε.inv.app X)
  simp only [autMap_hom_app, q₁_hom_app, q₂_hom_app]
  rw [h', ← h, Category.assoc, reassoc_of% hn]
  simp [← F''.map_comp_assoc]

lemma relations_le_ker (hPε : P.IsTrivialOn H ε) : P.relations ≤ (autMap H F').ker := by
  refine Subgroup.topologicalClosure_minimal _ (Subgroup.normalClosure_le_normal ?_) ?_
  · rintro _ ⟨g, rfl⟩
    exact P.q₁_mul_inv_mem_ker hPε g
  · rw [MonoidHom.coe_ker]
    exact isClosed_singleton.preimage (continuous_autMap H F')

variable [GaloisCategory C] [GaloisCategory C'] [GaloisCategory C''] [FiberFunctor F']
  [FiberFunctor F''] [F'''.Faithful] [FiberFunctor (H ⋙ F')]

omit [GaloisCategory C] [FiberFunctor (H ⋙ F')] in
/-- IX.5.6, the kernel (abstract form): if `g : S' → S` is an effective descent morphism for étale
coverings and `S''` is connected, the kernel of `π₁(S', s') → π₁(S, s)` is the closed normal
subgroup generated by the `p₁*(g'') p₂*(g'')⁻¹`, `g'' ∈ π₁(S'', Δ s')`. Only essential surjectivity
of the comparison functor (effectiveness of descent data) is used. -/
theorem ker_autMap_eq_relations (hPε : P.IsTrivialOn H ε) [(D.comparison H ε hε).EssSurj] :
    (autMap H F').ker = P.relations := by
  refine ker_autMap_eq H F' P.relations P.isClosed_relations fun Y ↦ ⟨fun hY σ hσ y ↦ ?_, ?_⟩
  · exact smul_eq_of_mem_essImage H F' hY (P.relations_le_ker hPε hσ) y
  · rw [forall_mem_relations_smul_eq_iff]
    intro hY
    obtain ⟨φ, hφ, -⟩ := P.exists_isCocycle Y hY
    obtain ⟨X, ⟨e⟩⟩ := Functor.EssSurj.mem_essImage (D.comparison H ε hε) ⟨Y, φ, hφ⟩
    exact ⟨X, ⟨(Datum.forget D).mapIso e⟩⟩

omit [GaloisCategory C] [GaloisCategory C'] [FiberFunctor F'] [F'''.Faithful]
  [FiberFunctor (H ⋙ F')] in
/-- At the diagonal point every morphism between inverse images is compatible with the canonical
descent data (the argument of IX.3.4, with `S''` connected). Hence `H` is full as soon as `g` is a
descent morphism. -/
lemma full_of_full_comparison (hPε : P.IsTrivialOn H ε) [(D.comparison H ε hε).Full] :
    H.Full where
  map_surjective {X Y} f := by
    have hf : D.p₁.map f ≫ ε.hom.app Y = ε.hom.app X ≫ D.p₂.map f := by
      apply F''.map_injective
      rw [← cancel_mono (P.d₂.hom.app (H.obj Y))]
      have n₁ := P.d₁.hom.naturality f
      have n₂ := P.d₂.hom.naturality f
      simp only [Functor.comp_map] at n₁ n₂
      rw [Functor.map_comp, Functor.map_comp, Category.assoc, Category.assoc, hPε Y, n₁, n₂,
        reassoc_of% (hPε X)]
    obtain ⟨g, hg⟩ := (D.comparison H ε hε).map_surjective (X := X) (Y := Y) ⟨f, hf⟩
    exact ⟨g, congrArg Datum.Hom.hom hg⟩

/-- IX.5.6 (abstract form): if `g : S' → S` is an effective descent morphism for étale coverings
and `S'`, `S''` are connected, then `π₁(S, s)` is the quotient of `π₁(S', s')` by the closed normal
subgroup generated by the `p₁*(g'') p₂*(g'')⁻¹`, i.e. the cokernel of `p₁*, p₂*` in the category of
profinite groups. -/
noncomputable def quotientRelationsEquiv (hPε : P.IsTrivialOn H ε)
    [(D.comparison H ε hε).IsEquivalence] : Aut F' ⧸ P.relations ≃ₜ* Aut (H ⋙ F') :=
  have := P.full_of_full_comparison hε hPε
  have := preservesIsConnected_of_full H F'
  quotientEquivOfKerEq H F' (surjective_of_preservesIsConnected H F') _
    (P.ker_autMap_eq_relations hε hPε)

omit [F'''.Faithful] in
/-- IX.5.2 when `S'` and `S''` are connected: if `g` is a descent morphism and `π₁(S')` is
topologically finitely generated, so is `π₁(S)`. The general case (finitely many components)
needs the presentation IX.5.1, which is not formalized. -/
theorem exists_finite_topologicalClosure_eq_top (hPε : P.IsTrivialOn H ε)
    [(D.comparison H ε hε).Full] {s : Set (Aut F')} (hs : s.Finite)
    (h : (Subgroup.closure s).topologicalClosure = ⊤) :
    ∃ t : Set (Aut (H ⋙ F')), t.Finite ∧ (Subgroup.closure t).topologicalClosure = ⊤ :=
  have := P.full_of_full_comparison hε hPε
  have := preservesIsConnected_of_full H F'
  SGA.SGA1.ExposeIX.exists_finite_topologicalClosure_eq_top H F'
    (surjective_of_preservesIsConnected H F') hs h

end DiagonalPoint

end DescentDiagram

section schemes

open AlgebraicGeometry

local notation "FEt" => (SGA.SGA1.ExposeV.finiteEtaleHom : MorphismProperty Scheme)

variable {S S' : Scheme.{u}} (g : S' ⟶ S)

/-- IX.5.6, surjectivity: if `g` is universally submersive with geometrically connected fibres,
then `π₁(S', s') → π₁(S, s)` is surjective. Here the fundamental groups are the automorphism groups
of any fibre functors `F'` on the finite étale coverings of `S'` and `F' ∘ g^*` on those of `S`
(the categories of étale coverings are Galois categories by V.7 as soon as they have a fibre
functor); for the fibre functors at geometric points see `surjective_etaleFundamentalGroup_map`. -/
theorem surjective_autMap_pullback
    (hg : (topologically Topology.IsQuotientMap).universally g) [GeometricallyConnected g]
    (F' : MorphismProperty.Over FEt ⊤ S' ⥤ FintypeCat.{w}) [FiberFunctor F']
    [FiberFunctor (MorphismProperty.Over.pullback FEt ⊤ g ⋙ F')] :
    Function.Surjective (autMap (MorphismProperty.Over.pullback FEt ⊤ g) F') :=
  have := SGA.SGA1.ExposeV.galoisCategory_of_fiberFunctor F'
  have := SGA.SGA1.ExposeV.galoisCategory_of_fiberFunctor
    (MorphismProperty.Over.pullback FEt ⊤ g ⋙ F')
  have := preservesIsConnected_pullback g hg
  surjective_of_preservesIsConnected _ F'

/-- IX.5.6, in its proof: under the hypotheses of IX.5.6, the inverse image `g^*` of finite étale
coverings is full (the second assertion of IX.3.4 for finite étale coverings); here it is deduced
from the surjectivity by V.6.9. -/
theorem full_pullback
    (hg : (topologically Topology.IsQuotientMap).universally g) [GeometricallyConnected g]
    (F' : MorphismProperty.Over FEt ⊤ S' ⥤ FintypeCat.{w}) [FiberFunctor F']
    [FiberFunctor (MorphismProperty.Over.pullback FEt ⊤ g ⋙ F')] :
    (MorphismProperty.Over.pullback FEt ⊤ g).Full :=
  have := SGA.SGA1.ExposeV.galoisCategory_of_fiberFunctor F'
  have := SGA.SGA1.ExposeV.galoisCategory_of_fiberFunctor
    (MorphismProperty.Over.pullback FEt ⊤ g ⋙ F')
  full_of_surjective _ F' (surjective_autMap_pullback g hg F')

/-- Remark after IX.5.3 (`π₁` is a topological invariant): for a universal homeomorphism `g`, for
instance a finite radicial surjective morphism, `π₁(S') → π₁(S)` is bijective if and only if every
finite étale covering of `S'` comes from one of `S`; the latter is the essential surjectivity in
IX.4.10. The surjectivity is automatic (`surjective_autMap_pullback`). -/
theorem bijective_autMap_pullback_iff (hg : (topologically IsHomeomorph).universally g)
    (F' : MorphismProperty.Over FEt ⊤ S' ⥤ FintypeCat.{w}) [FiberFunctor F']
    [FiberFunctor (MorphismProperty.Over.pullback FEt ⊤ g ⋙ F')] :
    Function.Bijective (autMap (MorphismProperty.Over.pullback FEt ⊤ g) F') ↔
      (MorphismProperty.Over.pullback FEt ⊤ g).EssSurj := by
  have := SGA.SGA1.ExposeV.galoisCategory_of_fiberFunctor F'
  have := SGA.SGA1.ExposeV.galoisCategory_of_fiberFunctor
    (MorphismProperty.Over.pullback FEt ⊤ g ⋙ F')
  have := preservesIsConnected_pullback_of_universally_isHomeomorph g hg
  rw [bijective_autMap_iff]
  refine ⟨fun _ ↦ inferInstance, fun _ ↦ ?_⟩
  have := full_of_surjective _ F'
    (surjective_of_preservesIsConnected (MorphismProperty.Over.pullback FEt ⊤ g) F')
  have := faithful_of_fiberFunctor (MorphismProperty.Over.pullback FEt ⊤ g) F'
  exact { }

/-- The homomorphism `π₁(H)` of Exposé V (`SGA.SGA1.ExposeV.autMap`) is `autMap H F` followed by
the conjugation by the isomorphism of fibre functors. -/
lemma autMap_eq_conjAut_comp {C : Type u₁} [Category.{v₁} C] {C' : Type u₂} [Category.{v₂} C']
    (H : C ⥤ C') {F : C' ⥤ FintypeCat.{w}} {F' : C ⥤ FintypeCat.{w}} (e : H ⋙ F ≅ F') :
    SGA.SGA1.ExposeV.autMap H e = e.conjAut.toMonoidHom.comp (autMap H F) := by
  ext σ : 1
  apply Iso.ext
  rfl

variable [ConnectedSpace S]

/-- IX.5.6, surjectivity, for the fundamental groups of Exposé V: if `g : S' ⟶ S` is universally
submersive with geometrically connected fibres and `S` is connected, then for every geometric
point `s'` of `S'`, `π₁(S', s') → π₁(S, g(s'))` is surjective. -/
theorem surjective_etaleFundamentalGroup_map
    (hg : (topologically Topology.IsQuotientMap).universally g) [GeometricallyConnected g]
    (Ω : Type u) [Field Ω] [IsSepClosed Ω] (s' : Spec (.of Ω) ⟶ S') :
    Function.Surjective (SGA.SGA1.ExposeV.etaleFundamentalGroup.map Ω g s') :=
  have := connectedSpace_of_universally_isQuotientMap g hg
  have : PreservesIsConnected (SGA.SGA1.ExposeV.FEt.pullback g) :=
    preservesIsConnected_pullback g hg
  SGA.SGA1.ExposeV.autMap_surjective _ _ fun _ _ ↦ PreservesIsConnected.preserves

/-- IX.5.6, in its proof (IX.3.4 for étale coverings): under the hypotheses of IX.5.6, the
inverse image functor on étale coverings is full. -/
theorem full_etalePullback
    (hg : (topologically Topology.IsQuotientMap).universally g) [GeometricallyConnected g] :
    (SGA.SGA1.ExposeV.FEt.pullback g).Full := by
  have := connectedSpace_of_universally_isQuotientMap g hg
  have : PreservesIsConnected (SGA.SGA1.ExposeV.FEt.pullback g) :=
    preservesIsConnected_pullback g hg
  obtain ⟨x⟩ : Nonempty S' := inferInstance
  let s' := SGA.SGA1.ExposeV.geometricPointAt S' x
  have : FiberFunctor (SGA.SGA1.ExposeV.FEt.pullback g ⋙ SGA.SGA1.ExposeV.FEt.fiber _ s') :=
    SGA.SGA1.ExposeV.fiberFunctor_of_iso (SGA.SGA1.ExposeV.FEt.pullbackFiberIso _ g s').symm
  exact full_of_surjective _ (SGA.SGA1.ExposeV.FEt.fiber _ s')
    (surjective_of_preservesIsConnected _ _)

/-- Remark after IX.5.3 (`π₁` is a topological invariant), for the fundamental groups of
Exposé V: for a universal homeomorphism `g` onto a connected scheme and a geometric point `s'`
of `S'`, `π₁(S', s') → π₁(S, g(s'))` is bijective if and only if every étale covering of `S'`
comes from one of `S` (the essential surjectivity in IX.4.10). -/
theorem bijective_etaleFundamentalGroup_map_iff (hg : (topologically IsHomeomorph).universally g)
    (Ω : Type u) [Field Ω] [IsSepClosed Ω] (s' : Spec (.of Ω) ⟶ S') :
    Function.Bijective (SGA.SGA1.ExposeV.etaleFundamentalGroup.map Ω g s') ↔
      (SGA.SGA1.ExposeV.FEt.pullback g).EssSurj := by
  have := geometricallyConnected_of_universally_isHomeomorph g hg
  have hq := universally_isQuotientMap_of_universally_isHomeomorph g hg
  have := connectedSpace_of_universally_isQuotientMap g hq
  have : FiberFunctor (SGA.SGA1.ExposeV.FEt.pullback g ⋙ SGA.SGA1.ExposeV.FEt.fiber Ω s') :=
    SGA.SGA1.ExposeV.fiberFunctor_of_iso (SGA.SGA1.ExposeV.FEt.pullbackFiberIso Ω g s').symm
  have := full_etalePullback g hq
  have := faithful_of_fiberFunctor (SGA.SGA1.ExposeV.FEt.pullback g)
    (SGA.SGA1.ExposeV.FEt.fiber Ω s')
  rw [SGA.SGA1.ExposeV.etaleFundamentalGroup.map, autMap_eq_conjAut_comp, MonoidHom.coe_comp,
    MulEquiv.coe_toMonoidHom, Function.Bijective.of_comp_iff' (MulEquiv.bijective _),
    bijective_autMap_iff]
  exact ⟨fun _ ↦ inferInstance, fun _ ↦ { }⟩

section Invariance

/-! ### Topological invariance of the fundamental group

An étale morphism whose base change along a universally closed surjective morphism is finite is
itself finite (`isFinite_of_isFinite_pullback`): separatedness and universal closedness descend,
and a proper quasi-finite morphism is finite. Hence IX.4.10 and IX.1.7, which are about étale
schemes, give the corresponding statements for étale coverings (`essSurj_fetPullback_of_*`), and
the fundamental group is invariant under finite radicial surjective morphisms of finite
presentation and under nil-immersions (`bijective_etaleFundamentalGroup_map_of_isFinite`,
`bijective_etaleFundamentalGroup_map_of_isClosedImmersion`), as remarked after IX.5.3. -/

variable {X : Scheme.{u}}

omit [ConnectedSpace S] in
/-- Separatedness descends along universally closed surjective morphisms: the base change of the
diagonal of `p` along such a morphism is (up to isomorphism) the diagonal of the base change. -/
lemma isSeparated_of_isSeparated_pullback (p : X ⟶ S) [UniversallyClosed g] [Surjective g]
    [IsSeparated (pullback.fst g p)] : IsSeparated p := by
  let M := ((Over.pullback g).map (Over.homMk (pullback.diagonal p) :
    Over.mk p ⟶ Over.mk (pullback.snd p p ≫ p))).left
  have hM : IsClosedImmersion M := by
    have h := diagonal_pullback_fst g p
    have hM' : M = (pullbackSymmetry g p).inv ≫ pullback.diagonal (pullback.fst g p) ≫
        (diagonalObjPullbackFstIso g p).hom := by
      rw [h]
      simp [M]
    rw [hM']
    infer_instance
  have hcomm : pullback.fst p g ≫ pullback.diagonal p =
      M ≫ pullback.fst (pullback.snd p p ≫ p) g := by
    simp only [M, Over.pullback_map_left]
    exact (pullback.lift_fst _ _ _).symm
  have : UniversallyClosed (pullback.fst p g ≫ pullback.diagonal p) := by
    rw [hcomm]
    infer_instance
  have : UniversallyClosed (pullback.diagonal p) :=
    UniversallyClosed.of_comp_surjective (pullback.fst p g) (pullback.diagonal p)
  exact ⟨IsClosedImmersion.of_isPreimmersion _ (pullback.diagonal p).isClosedMap.isClosed_range⟩

omit [ConnectedSpace S] in
/-- A locally quasi-finite morphism locally of finite type (for instance an étale morphism) whose
base change along a universally closed surjective morphism is finite is finite. -/
lemma isFinite_of_isFinite_pullback (p : X ⟶ S) [LocallyOfFiniteType p] [LocallyQuasiFinite p]
    [UniversallyClosed g] [Surjective g] [IsFinite (pullback.fst g p)] : IsFinite p := by
  have := isSeparated_of_isSeparated_pullback g p
  have : UniversallyClosed (pullback.snd g p ≫ p) := by
    rw [← pullback.condition]
    infer_instance
  have : UniversallyClosed p := UniversallyClosed.of_comp_surjective (pullback.snd g p) p
  have : IsProper p := ⟨⟩
  exact IsFinite.of_isProper_of_locallyQuasiFinite p

omit [ConnectedSpace S] in
/-- An étale covering of `S'` which is the base change of an étale `S`-scheme along a universally
closed surjective `g` is the base change of an étale covering of `S`. -/
lemma mem_essImage_fetPullback_of_etale [UniversallyClosed g] [Surjective g]
    (Y' : MorphismProperty.Over FEt ⊤ S') (p : X ⟶ S) [Etale p] (e : pullback p g ≅ Y'.left)
    (he : e.hom ≫ Y'.hom = pullback.snd p g) :
    (MorphismProperty.Over.pullback FEt ⊤ g).essImage Y' := by
  have : IsFinite Y'.hom := Y'.prop.1
  have : IsFinite (pullback.snd p g) := by
    rw [← he]
    infer_instance
  have : IsFinite (pullback.fst g p) := by
    rw [← pullbackSymmetry_hom_comp_snd]
    infer_instance
  have : IsFinite p := isFinite_of_isFinite_pullback g p
  exact ⟨MorphismProperty.Over.mk ⊤ p ⟨inferInstance, inferInstance⟩,
    ⟨MorphismProperty.Over.isoMk e he⟩⟩

-- `@Etale` as a morphism property needs this option (as in IX.4.10).
set_option backward.isDefEq.respectTransparency.types false in
omit [ConnectedSpace S] in
/-- IX.4.10 for étale coverings: for `g : S' ⟶ S` finite, radicial, surjective and of finite
presentation, every étale covering of `S'` comes from an étale covering of `S`. -/
theorem essSurj_fetPullback_of_isFinite [IsFinite g] [UniversallyInjective g] [Surjective g]
    [LocallyOfFinitePresentation g] : (MorphismProperty.Over.pullback FEt ⊤ g).EssSurj where
  mem_essImage Y' := by
    have := essSurj_pullback_etale_of_isFinite g
    obtain ⟨Xe, ⟨e⟩⟩ := Functor.EssSurj.mem_essImage
      (MorphismProperty.Over.pullback @Etale ⊤ g) (MorphismProperty.Over.mk ⊤ Y'.hom Y'.prop.2)
    have : Etale Xe.hom := Xe.prop
    exact mem_essImage_fetPullback_of_etale g Y' Xe.hom
      ⟨e.hom.left, e.inv.left, congrArg (fun φ ↦ φ.left) e.hom_inv_id,
        congrArg (fun φ ↦ φ.left) e.inv_hom_id⟩
      (MorphismProperty.Over.w e.hom)

-- `@Etale` as a morphism property needs this option (as in IX.4.10).
set_option backward.isDefEq.respectTransparency.types false in
omit [ConnectedSpace S] in
/-- IX.1.7 for étale coverings: for a nil-immersion `i : S₀ ⟶ S` (a surjective closed
immersion), every étale covering of `S₀` comes from an étale covering of `S`. -/
theorem essSurj_fetPullback_of_isClosedImmersion [IsClosedImmersion g] [Surjective g] :
    (MorphismProperty.Over.pullback FEt ⊤ g).EssSurj where
  mem_essImage Y' := by
    have := essSurj_pullback_etale_of_isClosedImmersion g
    obtain ⟨Xe, ⟨e⟩⟩ := Functor.EssSurj.mem_essImage
      (MorphismProperty.Over.pullback @Etale ⊤ g) (MorphismProperty.Over.mk ⊤ Y'.hom Y'.prop.2)
    have : Etale Xe.hom := Xe.prop
    exact mem_essImage_fetPullback_of_etale g Y' Xe.hom
      ⟨e.hom.left, e.inv.left, congrArg (fun φ ↦ φ.left) e.hom_inv_id,
        congrArg (fun φ ↦ φ.left) e.inv_hom_id⟩
      (MorphismProperty.Over.w e.hom)

/-- Remark after IX.5.3 (topological invariance of `π₁`, IX.4.10): for `g : S' ⟶ S` finite,
radicial, surjective and of finite presentation onto a connected scheme, `π₁(S', s') → π₁(S, g(s'))`
is bijective for every geometric point `s'` of `S'`. -/
theorem bijective_etaleFundamentalGroup_map_of_isFinite [IsFinite g] [UniversallyInjective g]
    [Surjective g] [LocallyOfFinitePresentation g] (Ω : Type u) [Field Ω] [IsSepClosed Ω]
    (s' : Spec (.of Ω) ⟶ S') :
    Function.Bijective (SGA.SGA1.ExposeV.etaleFundamentalGroup.map Ω g s') :=
  (bijective_etaleFundamentalGroup_map_iff g (universally_isHomeomorph_of_universallyClosed g) Ω
    s').mpr (essSurj_fetPullback_of_isFinite g)

/-- IX.1.7 ("fundamental groups do not change on dividing out by the nilpotent elements"): for a
surjective closed immersion `i : S₀ ⟶ S` onto a connected scheme, `π₁(S₀, s₀) → π₁(S, i(s₀))` is
bijective for every geometric point `s₀` of `S₀`. -/
theorem bijective_etaleFundamentalGroup_map_of_isClosedImmersion [IsClosedImmersion g]
    [Surjective g] (Ω : Type u) [Field Ω] [IsSepClosed Ω] (s' : Spec (.of Ω) ⟶ S') :
    Function.Bijective (SGA.SGA1.ExposeV.etaleFundamentalGroup.map Ω g s') :=
  (bijective_etaleFundamentalGroup_map_iff g (universally_isHomeomorph_of_universallyClosed g) Ω
    s').mpr (essSurj_fetPullback_of_isClosedImmersion g)

end Invariance

end schemes

end SGA.SGA1.ExposeIX
