/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.SGA1.ExposeIX.FiniteEtaleEffectiveDescent
import SGA.SGA1.ExposeV.MultiGalois
import SGA.SGA1.ExposeX.BaseChangeAlgClosed
import SGA.Foundations.Pro.TopologicallyFG
import SGA.SGA1.ExposeXIII.AffineLineFundamentalGroup
import SGA.SGA1.ExposeX.GaloisFunctors

/-!
# SGA 1, Exposé IX, 5.4: pinching, consequence on finite generation

IX.5.4 describes the effect of a "pinching" `g : S' ⟶ S` (a finite morphism which is a universal
homeomorphism away from a discrete set `T ⊆ S`, e.g. the normalization of a curve) on the
fundamental group: `π₁(S)` is generated by `π₁(S')` and free generators, one for each extra
geometric point over `T`. SGA's proof (left to the reader) is the intrinsic form: the étale
coverings of `S` are the étale coverings of `S'` with, over each point of `T`, a transitive system
of bijections between the fibres at the points above it.

We prove a consequence of IX.5.4 (`isTopologicallyFG_etaleFundamentalGroup_of_pinching`):
**`π₁(S')` is topologically finitely generated as soon as `π₁(S)` is**, through a continuous
surjection `π₁(S) ↠ π₁(S')` built in the proof (not stated as a separate theorem). SGA does not use
IX.5.4 for X.2.9: its proof rests on Chow's lemma, IX.5.2, X.2.6 (for the curve case) and X.2.10.
In this formalization the result is a step of a planned, unfinished route to the curve case of
X.2.9 in characteristic `p` (`SGA.SGA1.ExposeIX.PinchingCurve`); no proof of X.2.9 in this
repository uses it. SGA's hypotheses
(`g` finite of finite presentation, `T ⊆ S` discrete, `n(s) = 1` geometric point in the fibre
over each `s ∉ T`) are replaced by the following ones: `g` proper and surjective, `S` locally
noetherian, `S'` connected, everything over a separably closed field `k` (`τ : S ⟶ Spec k`);
the points of `S'' = S' ×_S S'` off the diagonal form a finite set of closed points, each carrying
a `k`-point; and `S''' = S'' ×_{S'} S''` has finitely many connected components, each carrying a
`k`-point. For the normalization of a proper curve over an algebraically closed field these hold
(`SGA.SGA1.ExposeIX.PinchingCurve`), the points off the diagonal lying over the finitely many
points where `g` is not an isomorphism.

The construction:
* `S''` is the disjoint union of the (open) range of the diagonal and of the points `z` off it
  (`opensFamily`);
* on the diagonal part, `p₁^*` and `p₂^*` agree, through IX.1.7 for the surjective closed immersion
  `S' ⟶ U_Δ` (`diagIso`); on `{z}`, whose étale coverings are trivial (`full_fiber`), the two
  inverse images are identified through chosen isomorphisms of fibre functors ("paths") from a
  base point `c₀` to `p₁(z)` and `p₂(z)` (`pointIso`);
* these glue (V.9, `FEt.equivPiOfDisjoint`) to a natural isomorphism `p₁^* ≅ p₂^*` (`gluingIso`),
  which is given on fibres at every `k`-point by the transport along the paths
  (`gluingFiber_eq`), hence satisfies the cocycle condition (`isCocycle_gluingIso`, checked on
  fibres at `k`-points of the components of `S'''`, `hom_ext_of_fiber`);
* by IX.4.12 (`isEquivalence_fetComparison_of_isProper`) every étale covering of `S'` descends:
  this gives a section `pinchFunctor` of `g^*` which preserves connectedness, hence (V.6.9) a
  continuous surjection `π₁(S) ↠ π₁(S')`.

The rest of IX.5.4 (the description of `π₁(S)` by `π₁(S')` and free generators) is not
formalized; the direction
"`π₁(S')` t.f.g. ⇒ `π₁(S)` t.f.g." is IX.5.2 (`isTopologicallyFG_etaleFundamentalGroup_of_family`).
-/

universe u

open CategoryTheory CategoryTheory.Limits AlgebraicGeometry PreGaloisCategory

namespace SGA.SGA1.ExposeIX

namespace Pinching

section KPoints

variable {k : Type u} [Field k] {T : Scheme.{u}}

/-- A morphism `Spec k ⟶ T` through the residue field of a point `x`. -/
lemma exists_eq_spec_map_comp_fromSpecResidueField (t : Spec (.of k) ⟶ T) :
    ∃ φ : T.residueField (t (IsLocalRing.closedPoint k)) ⟶ .of k,
      t = Spec.map φ ≫ T.fromSpecResidueField (t (IsLocalRing.closedPoint k)) :=
  ⟨_, (Scheme.descResidueField_stalkClosedPointTo_fromSpecResidueField k T t).symm⟩

/-- Two `k`-points of a `k`-scheme with the same underlying point are equal (`k` any field; for
`k` algebraically closed and `T` locally of finite type this is also mathlib's
`AlgebraicGeometry.ext_of_apply_closedPoint_eq`). -/
lemma eq_of_comp_eq_id (τ : T ⟶ Spec (.of k)) {t₁ t₂ : Spec (.of k) ⟶ T}
    (h₁ : t₁ ≫ τ = 𝟙 _) (h₂ : t₂ ≫ τ = 𝟙 _)
    (h : t₁ (IsLocalRing.closedPoint k) = t₂ (IsLocalRing.closedPoint k)) : t₁ = t₂ := by
  obtain ⟨φ₁, e₁⟩ := exists_eq_spec_map_comp_fromSpecResidueField t₁
  obtain ⟨φ₂', e₂'⟩ := exists_eq_spec_map_comp_fromSpecResidueField t₂
  let φ₂ := (T.residueFieldCongr h).hom ≫ φ₂'
  have e₂ : t₂ = Spec.map φ₂ ≫ T.fromSpecResidueField (t₁ (IsLocalRing.closedPoint k)) := by
    rw [e₂', Spec.map_comp, Category.assoc, Scheme.residueFieldCongr_fromSpecResidueField]
  let σ := Spec.preimage (T.fromSpecResidueField (t₁ (IsLocalRing.closedPoint k)) ≫ τ)
  have hσ (φ : T.residueField (t₁ (IsLocalRing.closedPoint k)) ⟶ .of k)
      (hφ : (Spec.map φ ≫ T.fromSpecResidueField (t₁ (IsLocalRing.closedPoint k))) ≫ τ = 𝟙 _) :
      σ ≫ φ = 𝟙 _ := by
    apply Spec.map_injective
    rw [Spec.map_comp, Spec.map_preimage, ← Category.assoc, hφ, Spec.map_id]
  have hs₁ := hσ φ₁ (e₁ ▸ h₁)
  have hs₂ := hσ φ₂ (e₂ ▸ h₂)
  have : φ₁ = φ₂ := by
    ext b
    have hb : σ (φ₁ b) = b := φ₁.hom.injective (by
      rw [← CommRingCat.comp_apply, hs₁, CommRingCat.id_apply])
    calc φ₁ b = φ₂ (σ (φ₁ b)) := by rw [← CommRingCat.comp_apply, hs₂, CommRingCat.id_apply]
      _ = φ₂ b := by rw [hb]
  rw [e₁, e₂, this]

end KPoints

section Full

variable {C : Type*} [Category C] [GaloisCategory C] (F : C ⥤ FintypeCat.{w}) [FiberFunctor F]

/-- A fibre functor with trivial automorphism group is full. -/
private lemma full_of_subsingleton_aut [Subsingleton (Aut F)] : F.Full where
  map_surjective {X Y} f := by
    let f' : (functorToAction F).obj X ⟶ (functorToAction F).obj Y :=
      { hom := f
        comm := fun σ ↦ by
          rw [Subsingleton.elim σ 1]
          rfl }
    obtain ⟨g, hg⟩ := (functorToAction F).map_surjective f'
    exact ⟨g, congrArg Action.Hom.hom hg⟩

variable {k : Type u} [Field k] [IsSepClosed k] {U : Scheme.{u}} [Subsingleton U]

omit [IsSepClosed k] in
/-- A one-point scheme with a `k`-point is connected. -/
private lemma connectedSpace_of_subsingleton (t : Spec (.of k) ⟶ U) : ConnectedSpace U :=
  { isPreconnected_univ := Set.subsingleton_of_subsingleton.isPreconnected
    toNonempty := ⟨t (IsLocalRing.closedPoint k)⟩ }

/-- On a scheme with a single point and a `k`-point `t`, `k` separably closed, the fundamental
group is trivial: `t` is a surjective closed immersion, and IX.1.7 applies. -/
lemma subsingleton_etaleFundamentalGroup (τ : U ⟶ Spec (.of k)) (t : Spec (.of k) ⟶ U)
    (ht : t ≫ τ = 𝟙 _) : Subsingleton (ExposeV.etaleFundamentalGroup k t) := by
  have := connectedSpace_of_subsingleton t
  have : IsClosedImmersion t := isClosedImmersion_of_comp_eq_id τ t ht
  have : Surjective t := ⟨fun _ ↦ ⟨IsLocalRing.closedPoint k, Subsingleton.elim _ _⟩⟩
  have hb := bijective_etaleFundamentalGroup_map_of_isClosedImmersion t k (𝟙 _)
  have : Subsingleton (ExposeV.etaleFundamentalGroup k (𝟙 _ ≫ t)) := hb.2.subsingleton
  rwa [Category.id_comp] at this

/-- On a scheme with a single point and a `k`-point `t`, `k` separably closed, the fibre functor
at `t` is full (and faithful): every étale covering is trivial. -/
lemma full_fiber (τ : U ⟶ Spec (.of k)) (t : Spec (.of k) ⟶ U) (ht : t ≫ τ = 𝟙 _) :
    (ExposeV.FEt.fiber k t).Full := by
  have := connectedSpace_of_subsingleton t
  have := subsingleton_etaleFundamentalGroup τ t ht
  exact full_of_subsingleton_aut _

end Full

section Decomposition

variable {S S' : Scheme.{u}} (g : S' ⟶ S) [IsSeparated g]

/-- The points of `S' ×_S S'` off the diagonal. -/
abbrev offDiag : Set ↥(pullback g g) := (Set.range (pullback.diagonal g))ᶜ

variable {g} (hZ : (offDiag g).Finite) (hZc : ∀ z ∈ offDiag g, IsClosed ({z} : Set ↥(pullback g g)))
include hZ hZc

omit [IsSeparated g] in
/-- A subset of the (finite, closed-pointed) off-diagonal set is closed. -/
private lemma isClosed_offDiag_diff (A : Set ↥(pullback g g)) : IsClosed (offDiag g \ A) := by
  rw [← Set.biUnion_of_singleton (offDiag g \ A)]
  exact (hZ.subset Set.sdiff_subset).isClosed_biUnion fun z hz ↦ hZc z hz.1

omit [IsSeparated g] in
/-- Under the finiteness hypotheses on the off-diagonal points, the diagonal of `S' ×_S S'` is
open. -/
lemma isOpen_range_diagonal : IsOpen (Set.range (pullback.diagonal g)) := by
  simpa using (isClosed_offDiag_diff hZ hZc ∅).isOpen_compl

/-- Under the finiteness hypotheses, each point off the diagonal of `S' ×_S S'` is open. -/
lemma isOpen_singleton_of_mem_offDiag {z : ↥(pullback g g)} (hz : z ∈ offDiag g) :
    IsOpen ({z} : Set ↥(pullback g g)) := by
  have : ({z} : Set ↥(pullback g g)) =
      (Set.range (pullback.diagonal g) ∪ (offDiag g \ {z}))ᶜ := by
    ext w
    constructor
    · rintro rfl (h | ⟨-, h⟩)
      · exact hz h
      · exact h rfl
    · intro hw
      by_contra hne
      by_cases h : w ∈ Set.range (pullback.diagonal g)
      · exact hw (Or.inl h)
      · exact hw (Or.inr ⟨h, hne⟩)
  rw [this]
  exact ((pullback.diagonal g).isClosedEmbedding.isClosed_range.union
    (isClosed_offDiag_diff hZ hZc {z})).isOpen_compl

/-- The decomposition of `S' ×_S S'` into the (open) diagonal and the points off it. -/
def opensFamily : Option (offDiag g) → (pullback g g).Opens
  | none => ⟨_, isOpen_range_diagonal hZ hZc⟩
  | some z => ⟨_, isOpen_singleton_of_mem_offDiag hZ hZc z.2⟩

lemma iSup_opensFamily : iSup (opensFamily hZ hZc) = ⊤ := by
  refine top_le_iff.mp fun w _ ↦ ?_
  rw [TopologicalSpace.Opens.mem_iSup]
  by_cases hw : w ∈ Set.range (pullback.diagonal g)
  · exact ⟨none, by simpa [opensFamily] using hw⟩
  · exact ⟨some ⟨w, hw⟩, by simp [opensFamily]⟩

lemma pairwise_disjoint_opensFamily :
    Pairwise (Function.onFun Disjoint (opensFamily hZ hZc)) := by
  rintro (_ | ⟨z⟩) (_ | ⟨z'⟩) h
  · exact (h rfl).elim
  · rw [Function.onFun, ← TopologicalSpace.Opens.coe_disjoint]
    exact Set.disjoint_singleton_right.mpr z'.2
  · rw [Function.onFun, ← TopologicalSpace.Opens.coe_disjoint]
    exact Set.disjoint_singleton_left.mpr z.2
  · rw [Function.onFun, ← TopologicalSpace.Opens.coe_disjoint]
    exact Set.disjoint_singleton.mpr fun h' ↦ h (congrArg some (Subtype.ext h'))

end Decomposition

section TriplePoints

open ExposeV

variable {A B B' T' : Scheme.{u}} (Ω : Type u) [Field Ω]

/-- The canonical isomorphism `a^* f^* ≅ a'^* f'^*` (for `a ≫ f = a' ≫ f'`) on fibres at a
geometric point. -/
lemma fiber_fetPullbackCompCongr (f : B ⟶ T') (a : A ⟶ B) (f' : B' ⟶ T') (a' : A ⟶ B')
    (h : a ≫ f = a' ≫ f') (s : Spec (.of Ω) ⟶ A) (Y : FEt T') :
    (FEt.fiber Ω s).map ((fetPullbackCompCongr f a f' a' h).hom.app Y) ≫
      (FEt.pullbackFiberIso Ω a' s).hom.app ((FEt.pullback f').obj Y) ≫
      (FEt.pullbackFiberIso Ω f' (s ≫ a')).hom.app Y ≫
      (FEt.fiberCongr Ω (by rw [Category.assoc, Category.assoc, h])).hom.app Y =
    (FEt.pullbackFiberIso Ω a s).hom.app ((FEt.pullback f).obj Y) ≫
      (FEt.pullbackFiberIso Ω f (s ≫ a)).hom.app Y := by
  refine FintypeCat.hom_ext _ _ fun x ↦ FEt.fiber_ext_point Ω ?_
  simp only [ConcreteCategory.comp_apply]
  rw [FEt.fiberPoint_fiberCongr, FEt.fiberPoint_pullbackFiberIso, FEt.fiberPoint_pullbackFiberIso,
    FEt.fiberPoint_pullbackFiberIso, FEt.fiberPoint_pullbackFiberIso, FEt.fiberPoint_map]
  exact assoc_eq_of_eq _ _ _ _ _ _ (fetPullbackCompCongr_hom_app_left_fetProj _ _ _ _ _ Y)

end TriplePoints

section Faithful

open ExposeV

variable {k : Type u} [Field k] [IsSepClosed k] {T : Scheme.{u}} [Finite (ConnectedComponents T)]

/-- On a scheme with finitely many connected components, morphisms of étale coverings are
determined by their fibres at one geometric point of each connected component. -/
lemma hom_ext_of_fiber (P : ConnectedComponents T → (Spec (.of k) ⟶ T))
    (hP : ∀ c, ConnectedComponents.mk (P c (IsLocalRing.closedPoint k)) = c) {A B : FEt T}
    {f₁ f₂ : A ⟶ B} (h : ∀ c, (FEt.fiber k (P c)).map f₁ = (FEt.fiber k (P c)).map f₂) :
    f₁ = f₂ := by
  have := FEt.restrictFamily_faithful (iSup_connectedComponentOpens T)
  apply (FEt.restrictFamily (connectedComponentOpens T)).map_injective
  funext c
  let ι := (connectedComponentOpens T c).ι
  let s' : Spec (.of k) ⟶ (connectedComponentOpens T c :) :=
    IsOpenImmersion.lift ι (P c) (by
      rw [Scheme.Opens.range_ι]
      rintro _ ⟨x, rfl⟩
      have : x = IsLocalRing.closedPoint k := Subsingleton.elim (α := PrimeSpectrum k) _ _
      subst this
      exact hP c)
  have hs' : s' ≫ ι = P c := IsOpenImmersion.lift_fac _ _ _
  let ε : FEt.pullback ι ⋙ FEt.fiber k s' ≅ FEt.fiber k (P c) :=
    FEt.pullbackFiberIso k ι s' ≪≫ FEt.fiberCongr k hs'
  apply (FEt.fiber k s').map_injective
  have h₁ := ε.hom.naturality f₁
  have h₂ := ε.hom.naturality f₂
  change (FEt.pullback ι ⋙ FEt.fiber k s').map f₁ = (FEt.pullback ι ⋙ FEt.fiber k s').map f₂
  rw [← cancel_mono (ε.hom.app B), h₁, h₂, h c]

end Faithful

section Construction

open ExposeV

local notation "FEtP" => (SGA.SGA1.ExposeV.finiteEtaleHom : MorphismProperty Scheme)
local notation "pb" => MorphismProperty.Over.pullback FEtP ⊤

variable {k : Type u} [Field k] {S S' : Scheme.{u}} {g : S' ⟶ S} [IsSeparated g]
  (hZ : (offDiag g).Finite) (hZc : ∀ z ∈ offDiag g, IsClosed ({z} : Set ↥(pullback g g)))

/-- The diagonal `S' ⟶ S' ×_S S'`, as a morphism to its (open) range. -/
noncomputable def diagLift : S' ⟶ (opensFamily hZ hZc none :) :=
  IsOpenImmersion.lift (opensFamily hZ hZc none).ι (pullback.diagonal g) (by
    rw [Scheme.Opens.range_ι]; exact subset_rfl)

@[reassoc (attr := simp)]
lemma diagLift_ι : diagLift hZ hZc ≫ (opensFamily hZ hZc none).ι = pullback.diagonal g :=
  IsOpenImmersion.lift_fac _ _ _

instance : IsClosedImmersion (diagLift hZ hZc) := by
  have : IsClosedImmersion (diagLift hZ hZc ≫ (opensFamily hZ hZc none).ι) := by
    rw [diagLift_ι]; infer_instance
  exact IsClosedImmersion.of_comp _ (opensFamily hZ hZc none).ι

instance : Surjective (diagLift hZ hZc) := by
  refine ⟨fun w ↦ ?_⟩
  obtain ⟨x, hx⟩ : w.1 ∈ Set.range (pullback.diagonal g) := by
    simpa [opensFamily] using w.2
  refine ⟨x, Subtype.ext ?_⟩
  rw [← hx, ← diagLift_ι hZ hZc, Scheme.Hom.comp_apply]
  rfl

/-- On the diagonal part, the two inverse images agree: the canonical isomorphism, through the
equivalence of IX.1.7 along the surjective closed immersion `S' ⟶ U_Δ`. -/
noncomputable def diagIso :
    pb (pullback.fst g g) ⋙ pb (opensFamily hZ hZc none).ι ≅
      pb (pullback.snd g g) ⋙ pb (opensFamily hZ hZc none).ι :=
  have := ExposeX.FEt.isEquivalence_pullback_of_isClosedImmersion (diagLift hZ hZc)
  ((Functor.FullyFaithful.ofFullyFaithful (FEt.pullback (diagLift hZ hZc))).whiskeringRight
    (FEt S')).preimageIso
      (Functor.associator _ _ _ ≪≫
        Functor.isoWhiskerLeft _ (MorphismProperty.Over.pullbackComp _ _).symm ≪≫
        fetPullbackCompCongr _ _ _ _ (by simp) ≪≫
        Functor.isoWhiskerLeft _ (MorphismProperty.Over.pullbackComp _ _) ≪≫
        (Functor.associator _ _ _).symm)

variable (τ : S ⟶ Spec (.of k))
  (hZk : ∀ z ∈ offDiag g, ∃ t : Spec (.of k) ⟶ pullback g g,
    t ≫ pullback.fst g g ≫ g ≫ τ = 𝟙 _ ∧ t (IsLocalRing.closedPoint k) = z)

omit [IsSeparated g] in
/-- A `k`-point at a point `z` off the diagonal. -/
noncomputable def offPoint (z : offDiag g) : Spec (.of k) ⟶ pullback g g :=
  (hZk z z.2).choose

omit [IsSeparated g] in
lemma offPoint_comp (z : offDiag g) :
    offPoint τ hZk z ≫ pullback.fst g g ≫ g ≫ τ = 𝟙 _ :=
  (hZk z z.2).choose_spec.1

omit [IsSeparated g] in
lemma offPoint_apply (z : offDiag g) :
    offPoint τ hZk z (IsLocalRing.closedPoint k) = z :=
  (hZk z z.2).choose_spec.2

/-- The `k`-point at `z`, as a point of the open subscheme `{z}`. -/
noncomputable def offPointLift (z : offDiag g) :
    Spec (.of k) ⟶ (opensFamily hZ hZc (some z) :) :=
  IsOpenImmersion.lift (opensFamily hZ hZc (some z)).ι (offPoint τ hZk z) (by
    rw [Scheme.Opens.range_ι]
    rintro _ ⟨x, rfl⟩
    have : x = IsLocalRing.closedPoint k := Subsingleton.elim (α := PrimeSpectrum k) _ _
    subst this
    simp [opensFamily, offPoint_apply])

@[reassoc (attr := simp)]
lemma offPointLift_ι (z : offDiag g) :
    offPointLift hZ hZc τ hZk z ≫ (opensFamily hZ hZc (some z)).ι = offPoint τ hZk z :=
  IsOpenImmersion.lift_fac _ _ _

instance (z : offDiag g) : Subsingleton (opensFamily hZ hZc (some z) :) :=
  ⟨fun a b ↦ Subtype.ext ((a.2 : a.1 ∈ ({z.1} : Set _)).trans (b.2 : b.1 ∈ ({z.1} : Set _)).symm)⟩

variable [IsSepClosed k] [ConnectedSpace S'] (c₀ : Spec (.of k) ⟶ S')

/-- A chosen path (isomorphism of fibre functors) from the base point `c₀` to `c`. -/
noncomputable def path (c : Spec (.of k) ⟶ S') : FEt.fiber k c₀ ≅ FEt.fiber k c :=
  Classical.choice (etalePaths.nonempty k k c₀ c)

/-- The fibre at `z` of an inverse image along a projection `p : S' ×_S S' ⟶ S'`. -/
noncomputable def fibIso (p : pullback g g ⟶ S') (z : offDiag g) :
    (pb p ⋙ pb (opensFamily hZ hZc (some z)).ι) ⋙ FEt.fiber k (offPointLift hZ hZc τ hZk z) ≅
      FEt.fiber k (offPoint τ hZk z ≫ p) :=
  Functor.associator _ _ _ ≪≫ Functor.isoWhiskerLeft _ (FEt.pullbackFiberIso k _ _) ≪≫
    FEt.pullbackFiberIso k _ _ ≪≫ FEt.fiberCongr k (by rw [offPointLift_ι])

/-- On the component `{z}`, the gluing isomorphism is given on fibres by the chosen paths. -/
noncomputable def pointIso (z : offDiag g) :
    pb (pullback.fst g g) ⋙ pb (opensFamily hZ hZc (some z)).ι ≅
      pb (pullback.snd g g) ⋙ pb (opensFamily hZ hZc (some z)).ι :=
  have := connectedSpace_of_subsingleton (offPointLift hZ hZc τ hZk z)
  have := full_fiber ((opensFamily hZ hZc (some z)).ι ≫ pullback.fst g g ≫ g ≫ τ)
    (offPointLift hZ hZc τ hZk z) (by simp [offPoint_comp])
  ((Functor.FullyFaithful.ofFullyFaithful
    (FEt.fiber k (offPointLift hZ hZc τ hZk z))).whiskeringRight (FEt S')).preimageIso
      (fibIso hZ hZc τ hZk _ z ≪≫ (path c₀ _).symm ≪≫ path c₀ _ ≪≫
        (fibIso hZ hZc τ hZk _ z).symm)

/-- The gluing isomorphism on each member of the decomposition. -/
noncomputable def compIso : ∀ i : Option (offDiag g),
    pb (pullback.fst g g) ⋙ pb (opensFamily hZ hZc i).ι ≅
      pb (pullback.snd g g) ⋙ pb (opensFamily hZ hZc i).ι
  | none => diagIso hZ hZc
  | some z => pointIso hZ hZc τ hZk c₀ z

/-- The gluing isomorphism `p₁^* ≅ p₂^*` of functors `FEt S' ⥤ FEt (S' ×_S S')`: canonical on
the diagonal, given by the chosen paths at the points off the diagonal. -/
noncomputable def piIso :
    pb (pullback.fst g g) ⋙ FEt.restrictFamily (opensFamily hZ hZc) ≅
      pb (pullback.snd g g) ⋙ FEt.restrictFamily (opensFamily hZ hZc) :=
  NatIso.pi' fun i ↦ compIso hZ hZc τ hZk c₀ i

/-- The gluing isomorphism `p₁^* ≅ p₂^*` of functors `FEt S' ⥤ FEt (S' ×_S S')`: canonical on
the diagonal, given by the chosen paths at the points off the diagonal. -/
noncomputable def gluingIso : pb (pullback.fst g g) ≅ pb (pullback.snd g g) :=
  have := FEt.restrictFamily_faithful (iSup_opensFamily hZ hZc)
  have := FEt.restrictFamily_full (iSup_opensFamily hZ hZc) (pairwise_disjoint_opensFamily hZ hZc)
  ((Functor.FullyFaithful.ofFullyFaithful
    (FEt.restrictFamily (opensFamily hZ hZc))).whiskeringRight (FEt S')).preimageIso
      (piIso hZ hZc τ hZk c₀)

/-- The restriction of the gluing isomorphism to a member of the decomposition. -/
lemma gluingIso_restrict (i : Option (offDiag g)) (Y : FEt S') :
    (FEt.pullback (opensFamily hZ hZc i).ι).map ((gluingIso hZ hZc τ hZk c₀).hom.app Y) =
      (compIso hZ hZc τ hZk c₀ i).hom.app Y := by
  have := FEt.restrictFamily_faithful (iSup_opensFamily hZ hZc)
  have := FEt.restrictFamily_full (iSup_opensFamily hZ hZc) (pairwise_disjoint_opensFamily hZ hZc)
  have h : (FEt.restrictFamily (opensFamily hZ hZc)).map
      ((gluingIso hZ hZc τ hZk c₀).hom.app Y) = (piIso hZ hZc τ hZk c₀).hom.app Y :=
    (Functor.FullyFaithful.ofFullyFaithful _).map_preimage _
  exact congrFun h i

/-- The fibre at a geometric point `t` of `S' ×_S S'` of the gluing isomorphism, as an isomorphism
between the fibre functors of `S'` at `t ≫ p₁` and `t ≫ p₂`. -/
noncomputable def gluingFiber (t : Spec (.of k) ⟶ pullback g g) :
    FEt.fiber k (t ≫ pullback.fst g g) ≅ FEt.fiber k (t ≫ pullback.snd g g) :=
  (FEt.pullbackFiberIso k _ t).symm ≪≫
    Functor.isoWhiskerRight (gluingIso hZ hZc τ hZk c₀) (FEt.fiber k t) ≪≫
    FEt.pullbackFiberIso k _ t

omit [IsSepClosed k] in
/-- `pullbackFiberIso` commutes with `fiberCongr`. -/
private lemma pullbackFiberIso_fiberCongr {T T' : Scheme.{u}} (p : T ⟶ T')
    {t₁ t₂ : Spec (.of k) ⟶ T} (h : t₁ = t₂) (h' : t₁ ≫ p = t₂ ≫ p) (Y : FEt T') :
    (FEt.pullbackFiberIso k p t₁).hom.app Y ≫ (FEt.fiberCongr k h').hom.app Y =
      (FEt.fiberCongr k h).hom.app ((FEt.pullback p).obj Y) ≫
        (FEt.pullbackFiberIso k p t₂).hom.app Y := by
  subst h
  simp [FEt.fiberCongr]

/-- The gluing isomorphism at the chosen `k`-point of a point off the diagonal is given by the
chosen paths. -/
lemma gluingFiber_offPoint (z : offDiag g) (Y : FEt S') :
    (gluingFiber hZ hZc τ hZk c₀ (offPoint τ hZk z)).hom.app Y =
      (path c₀ _).inv.app Y ≫ (path c₀ _).hom.app Y := by
  set t' := offPointLift hZ hZc τ hZk z
  have hι := offPointLift_ι hZ hZc τ hZk z
  -- the fibre at `offPoint z` through the open subscheme `{z}`
  let ε : FEt.pullback (opensFamily hZ hZc (some z)).ι ⋙ FEt.fiber k t' ≅
      FEt.fiber k (offPoint τ hZk z) :=
    FEt.pullbackFiberIso k _ t' ≪≫ FEt.fiberCongr k hι
  have hnat := ε.hom.naturality ((gluingIso hZ hZc τ hZk c₀).hom.app Y)
  have hres := gluingIso_restrict hZ hZc τ hZk c₀ (some z) Y
  have := connectedSpace_of_subsingleton t'
  have := full_fiber ((opensFamily hZ hZc (some z)).ι ≫ pullback.fst g g ≫ g ≫ τ) t'
    (by simp [t', offPoint_comp])
  have hpre : (FEt.fiber k t').map ((pointIso hZ hZc τ hZk c₀ z).hom.app Y) =
      (fibIso hZ hZc τ hZk (pullback.fst g g) z ≪≫ (path c₀ _).symm ≪≫ path c₀ _ ≪≫
        (fibIso hZ hZc τ hZk (pullback.snd g g) z).symm).hom.app Y := by
    have h := ((Functor.FullyFaithful.ofFullyFaithful (FEt.fiber k t')).whiskeringRight
      (FEt S')).map_preimage (fibIso hZ hZc τ hZk (pullback.fst g g) z ≪≫ (path c₀ _).symm ≪≫
        path c₀ _ ≪≫ (fibIso hZ hZc τ hZk (pullback.snd g g) z).symm).hom
    exact congrArg (fun α ↦ NatTrans.app α Y) h
  have key : (FEt.fiber k (offPoint τ hZk z)).map ((gluingIso hZ hZc τ hZk c₀).hom.app Y) =
      ε.inv.app _ ≫ (FEt.fiber k t').map ((pointIso hZ hZc τ hZk c₀ z).hom.app Y) ≫
        ε.hom.app _ := by
    rw [← Iso.app_inv, Iso.eq_inv_comp, Iso.app_hom, ← hnat, Functor.comp_map, hres]
    rfl
  have hC (p : pullback g g ⟶ S') :
      (fibIso hZ hZc τ hZk p z).hom.app Y =
        ε.hom.app ((FEt.pullback p).obj Y) ≫ (FEt.pullbackFiberIso k p _).hom.app Y := by
    simp only [fibIso, ε, Iso.trans_hom, NatTrans.comp_app, Functor.associator_hom_app,
      Functor.isoWhiskerLeft_hom, Functor.whiskerLeft_app, Category.id_comp, Category.assoc]
    rw [pullbackFiberIso_fiberCongr p hι]
  simp only [gluingFiber, Iso.trans_hom, Iso.symm_hom, NatTrans.comp_app,
    Functor.isoWhiskerRight_hom, Functor.whiskerRight_app, key, hpre, hC, Category.assoc]
  simp only [Iso.inv_hom_id_app_assoc]
  rw [← hC, Iso.inv_hom_id_app, Category.comp_id]

/-- Over the diagonal the gluing isomorphism is the identity: for `w` a morphism to `p₁^* Y` above
the diagonal, `w ≫ φ ≫ pr = w ≫ pr`. -/
lemma gluingIso_left_diag (Y : FEt S') {W : Scheme.{u}}
    (w : W ⟶ ((FEt.pullback (pullback.fst g g)).obj Y).left) (c : W ⟶ S')
    (hw : w ≫ ((FEt.pullback (pullback.fst g g)).obj Y).hom = c ≫ pullback.diagonal g) :
    w ≫ ((gluingIso hZ hZc τ hZk c₀).hom.app Y).left ≫ fetProj (pullback.snd g g) Y =
      w ≫ fetProj (pullback.fst g g) Y := by
  set δ' := diagLift hZ hZc
  set ι := (opensFamily hZ hZc none).ι
  have hδ : δ' ≫ ι = pullback.diagonal g := diagLift_ι hZ hZc
  let w₁ : W ⟶ ((FEt.pullback ι).obj ((FEt.pullback (pullback.fst g g)).obj Y)).left :=
    pullback.lift w (c ≫ δ') (by rw [Category.assoc, hδ, ← hw])
  let w₂ : W ⟶ ((FEt.pullback δ').obj
      ((FEt.pullback ι).obj ((FEt.pullback (pullback.fst g g)).obj Y))).left :=
    pullback.lift w₁ c (pullback.lift_snd _ _ _)
  have hw₂ : w = w₂ ≫ fetProj δ' _ ≫ fetProj ι _ := by
    simp only [w₂, w₁, fetProj]
    erw [pullback.lift_fst_assoc, pullback.lift_fst]
  have hres := gluingIso_restrict hZ hZc τ hZk c₀ none Y
  have := ExposeX.FEt.isEquivalence_pullback_of_isClosedImmersion δ'
  let canon : (FEt.pullback (pullback.fst g g) ⋙ FEt.pullback ι) ⋙ FEt.pullback δ' ≅
      (FEt.pullback (pullback.snd g g) ⋙ FEt.pullback ι) ⋙ FEt.pullback δ' :=
    Functor.associator _ _ _ ≪≫
        Functor.isoWhiskerLeft _ (MorphismProperty.Over.pullbackComp δ' ι).symm ≪≫
        fetPullbackCompCongr (pullback.fst g g) (δ' ≫ ι) (pullback.snd g g) (δ' ≫ ι)
          (by simp [hδ]) ≪≫
        Functor.isoWhiskerLeft _ (MorphismProperty.Over.pullbackComp δ' ι) ≪≫
        (Functor.associator _ _ _).symm
  have hpre : (FEt.pullback δ').map ((diagIso hZ hZc).hom.app Y) = canon.hom.app Y := by
    have h := ((Functor.FullyFaithful.ofFullyFaithful
      (FEt.pullback δ')).whiskeringRight (FEt S')).map_preimage canon.hom
    exact congrArg (fun α ↦ NatTrans.app α Y) h
  rw [hw₂]
  simp only [Category.assoc]
  rw [← fetPullback_map_left_fetProj_assoc ι, ← fetPullback_map_left_fetProj_assoc δ', hres]
  change w₂ ≫ ((FEt.pullback δ').map ((diagIso hZ hZc).hom.app Y)).left ≫ _ = _
  rw [hpre]
  simp only [canon, Iso.trans_hom, Iso.symm_hom, NatTrans.comp_app, Functor.associator_hom_app,
    Functor.associator_inv_app, Functor.isoWhiskerLeft_hom, Functor.whiskerLeft_app,
    Category.id_comp, Category.comp_id, MorphismProperty.Comma.comp_left, Category.assoc]
  rw [pullbackComp_hom_app_left_fetProj_assoc, fetPullbackCompCongr_hom_app_left_fetProj,
    pullbackComp_inv_app_left_fetProj_assoc]

/-- At a geometric point of the diagonal, the gluing isomorphism is the identity on fibres. -/
lemma gluingFiber_diag (c : Spec (.of k) ⟶ S') (Y : FEt S') :
    (gluingFiber hZ hZc τ hZk c₀ (c ≫ pullback.diagonal g)).hom.app Y =
      (FEt.fiberCongr k (by simp)).hom.app Y := by
  ext x
  apply FEt.fiber_ext_point k
  set y : (FEt.fiber k (c ≫ pullback.diagonal g)).obj ((FEt.pullback (pullback.fst g g)).obj Y) :=
    (FEt.pullbackFiberIso k (pullback.fst g g) (c ≫ pullback.diagonal g)).inv.app Y x
  have hy : FEt.fiberPoint k y ≫ fetProj (pullback.fst g g) Y = FEt.fiberPoint k x := by
    rw [← FEt.fiberPoint_pullbackFiberIso]
    simp [y]
  simp only [gluingFiber, Iso.trans_hom, Iso.symm_hom, NatTrans.comp_app,
    Functor.isoWhiskerRight_hom, Functor.whiskerRight_app, ConcreteCategory.comp_apply]
  rw [FEt.fiberPoint_pullbackFiberIso, FEt.fiberPoint_map, FEt.fiberPoint_fiberCongr]
  have hD := gluingIso_left_diag hZ hZc τ hZk c₀ Y (FEt.fiberPoint k y) c
    (FEt.fiberPoint_comp k y)
  rw [Category.assoc]
  exact hD.trans hy

/-- `fiberCongr` is the transport along the chosen paths. -/
private lemma fiberCongr_eq_path {a b : Spec (.of k) ⟶ S'} (h : a = b) (Y : FEt S') :
    (FEt.fiberCongr k h).hom.app Y = (path c₀ a).inv.app Y ≫ (path c₀ b).hom.app Y := by
  subst h
  simp [FEt.fiberCongr]

/-- **The gluing isomorphism on fibres**: at every `k`-point `t` of `S' ×_S S'`, the fibre map of
the gluing isomorphism is the transport along the chosen paths, from `t ≫ p₁` to `t ≫ p₂`. -/
theorem gluingFiber_eq (t : Spec (.of k) ⟶ pullback g g)
    (ht : t ≫ pullback.fst g g ≫ g ≫ τ = 𝟙 _) (Y : FEt S') :
    (gluingFiber hZ hZc τ hZk c₀ t).hom.app Y =
      (path c₀ (t ≫ pullback.fst g g)).inv.app Y ≫ (path c₀ (t ≫ pullback.snd g g)).hom.app Y := by
  by_cases hmem : t (IsLocalRing.closedPoint k) ∈ Set.range (pullback.diagonal g)
  · obtain ⟨x, hx⟩ := hmem
    have ht' : t = (t ≫ pullback.fst g g) ≫ pullback.diagonal g := by
      refine eq_of_comp_eq_id (pullback.fst g g ≫ g ≫ τ) ht ?_ ?_
      · simp only [Category.assoc, pullback.diagonal_fst_assoc]
        simpa only [Category.assoc] using ht
      · have e : ((t ≫ pullback.fst g g) ≫ pullback.diagonal g) (IsLocalRing.closedPoint k) =
            pullback.diagonal g (pullback.fst g g (t (IsLocalRing.closedPoint k))) := rfl
        rw [e, ← hx]
        have e' : pullback.fst g g (pullback.diagonal g x) = x := by
          rw [← Scheme.Hom.comp_apply, pullback.diagonal_fst]; rfl
        rw [e']
    have key (c : Spec (.of k) ⟶ S') :
        (gluingFiber hZ hZc τ hZk c₀ (c ≫ pullback.diagonal g)).hom.app Y =
          (path c₀ ((c ≫ pullback.diagonal g) ≫ pullback.fst g g)).inv.app Y ≫
            (path c₀ ((c ≫ pullback.diagonal g) ≫ pullback.snd g g)).hom.app Y := by
      rw [gluingFiber_diag, fiberCongr_eq_path]
    rw [ht'] at ht ⊢
    exact key _
  · have ht' : t = offPoint τ hZk ⟨_, hmem⟩ :=
      eq_of_comp_eq_id (pullback.fst g g ≫ g ≫ τ) ht (offPoint_comp τ hZk _)
        (offPoint_apply τ hZk ⟨_, hmem⟩).symm
    rw [ht']
    exact gluingFiber_offPoint hZ hZc τ hZk c₀ _ Y

/-- The fibre of the inverse image of the gluing isomorphism along `q : T ⟶ S' ×_S S'`. -/
lemma fiber_map_pullback_gluingIso {T : Scheme.{u}} (q : T ⟶ pullback g g)
    (s : Spec (.of k) ⟶ T) (Y : FEt S') :
    (FEt.fiber k s).map ((FEt.pullback q).map ((gluingIso hZ hZc τ hZk c₀).hom.app Y)) =
      (FEt.pullbackFiberIso k q s).hom.app _ ≫ (FEt.pullbackFiberIso k _ (s ≫ q)).hom.app Y ≫
        (gluingFiber hZ hZc τ hZk c₀ (s ≫ q)).hom.app Y ≫
        (FEt.pullbackFiberIso k _ (s ≫ q)).inv.app Y ≫ (FEt.pullbackFiberIso k q s).inv.app _ := by
  have hn := (FEt.pullbackFiberIso k q s).hom.naturality ((gluingIso hZ hZc τ hZk c₀).hom.app Y)
  simp only [gluingFiber, Iso.trans_hom, Iso.symm_hom, NatTrans.comp_app,
    Functor.isoWhiskerRight_hom, Functor.whiskerRight_app, Category.assoc,
    Iso.hom_inv_id_app_assoc]
  rw [← Category.assoc, ← hn, Category.assoc, Iso.hom_inv_id_app, Category.comp_id]
  rfl

/-- **The cocycle condition on fibres**, for three maps `q₂₁, q₃₂, q₃₁ : T ⟶ S' ×_S S'` satisfying
the relations of the three projections of `S'''`, at a `k`-point `s` of `T`. -/
lemma fiber_cocycle {T : Scheme.{u}} (q₂₁ q₃₂ q₃₁ : T ⟶ pullback g g)
    (h₁ : q₂₁ ≫ pullback.fst g g = q₃₁ ≫ pullback.fst g g)
    (h₂ : q₂₁ ≫ pullback.snd g g = q₃₂ ≫ pullback.fst g g)
    (h₃ : q₃₁ ≫ pullback.snd g g = q₃₂ ≫ pullback.snd g g)
    (s : Spec (.of k) ⟶ T) (hs : s ≫ q₂₁ ≫ pullback.fst g g ≫ g ≫ τ = 𝟙 _) (Y : FEt S') :
    (FEt.fiber k s).map ((FEt.pullback q₂₁).map ((gluingIso hZ hZc τ hZk c₀).hom.app Y) ≫
      (fetPullbackCompCongr _ _ _ _ h₂).hom.app Y ≫
      (FEt.pullback q₃₂).map ((gluingIso hZ hZc τ hZk c₀).hom.app Y)) =
    (FEt.fiber k s).map ((fetPullbackCompCongr _ _ _ _ h₁).hom.app Y ≫
      (FEt.pullback q₃₁).map ((gluingIso hZ hZc τ hZk c₀).hom.app Y) ≫
      (fetPullbackCompCongr _ _ _ _ h₃).hom.app Y) := by
  have k₂₁ : (s ≫ q₂₁) ≫ pullback.fst g g ≫ g ≫ τ = 𝟙 _ := by simpa only [Category.assoc] using hs
  have k₃₁ : (s ≫ q₃₁) ≫ pullback.fst g g ≫ g ≫ τ = 𝟙 _ := by
    rw [Category.assoc, ← Category.assoc q₃₁, ← h₁]; simpa only [Category.assoc] using hs
  have k₃₂ : (s ≫ q₃₂) ≫ pullback.fst g g ≫ g ≫ τ = 𝟙 _ := by
    rw [Category.assoc, ← Category.assoc q₃₂, ← h₂, Category.assoc, ← Category.assoc _ g,
      ← pullback.condition]; simpa only [Category.assoc] using hs
  have e₁ := fiber_fetPullbackCompCongr k _ _ _ _ h₁ s Y
  have e₂ := fiber_fetPullbackCompCongr k _ _ _ _ h₂ s Y
  have e₃ := fiber_fetPullbackCompCongr k _ _ _ _ h₃ s Y
  rw [fiberCongr_eq_path c₀] at e₁ e₂ e₃
  have e₁' := congrArg (· ≫ (path c₀ ((s ≫ q₂₁) ≫ pullback.fst g g)).inv.app Y ≫
    (path c₀ ((s ≫ q₃₁) ≫ pullback.fst g g)).hom.app Y) e₁
  have e₂' := congrArg (· ≫ (path c₀ ((s ≫ q₂₁) ≫ pullback.snd g g)).inv.app Y ≫
    (path c₀ ((s ≫ q₃₂) ≫ pullback.fst g g)).hom.app Y) e₂
  have e₃' := congrArg (· ≫ (path c₀ ((s ≫ q₃₁) ≫ pullback.snd g g)).inv.app Y ≫
    (path c₀ ((s ≫ q₃₂) ≫ pullback.snd g g)).hom.app Y) e₃
  simp only [Category.assoc, Iso.hom_inv_id_app_assoc,
    Iso.inv_hom_id_app, Category.comp_id] at e₁' e₂' e₃'
  have e₃'' : (FEt.pullbackFiberIso k (pullback.snd g g) (s ≫ q₃₁)).inv.app Y ≫
      (FEt.pullbackFiberIso k q₃₁ s).inv.app ((FEt.pullback (pullback.snd g g)).obj Y) ≫
      (FEt.fiber k s).map ((fetPullbackCompCongr _ _ _ _ h₃).hom.app Y) =
      (path c₀ ((s ≫ q₃₁) ≫ pullback.snd g g)).inv.app Y ≫
      (path c₀ ((s ≫ q₃₂) ≫ pullback.snd g g)).hom.app Y ≫
      (FEt.pullbackFiberIso k (pullback.snd g g) (s ≫ q₃₂)).inv.app Y ≫
      (FEt.pullbackFiberIso k q₃₂ s).inv.app ((FEt.pullback (pullback.snd g g)).obj Y) := by
    rw [← cancel_mono ((FEt.pullbackFiberIso k q₃₂ s).hom.app _),
      ← cancel_mono ((FEt.pullbackFiberIso k _ (s ≫ q₃₂)).hom.app Y)]
    simp only [Category.assoc, Iso.inv_hom_id_app, e₃', Iso.inv_hom_id_app_assoc]
    erw [Category.id_comp, Iso.inv_hom_id_app]
    exact (Category.comp_id _).symm
  simp only [Functor.map_comp, fiber_map_pullback_gluingIso, gluingFiber_eq _ _ _ _ _ _ k₂₁,
    gluingFiber_eq _ _ _ _ _ _ k₃₁, gluingFiber_eq _ _ _ _ _ _ k₃₂, Category.assoc,
    reassoc_of% e₁', reassoc_of% e₂', Iso.hom_inv_id_app_assoc, Iso.inv_hom_id_app_assoc, e₃'']

omit [IsSeparated g] [ConnectedSpace S'] in
/-- `p₃₁` followed by the first projection. -/
private lemma tripleProj₃₁_fst :
    tripleProj₃₁ g ≫ pullback.fst g g = tripleProj₂₁ g ≫ pullback.fst g g :=
  pullback.lift_fst _ _ _

omit [IsSeparated g] [ConnectedSpace S'] in
/-- `p₃₁` followed by the second projection. -/
private lemma tripleProj₃₁_snd :
    tripleProj₃₁ g ≫ pullback.snd g g = tripleProj₃₂ g ≫ pullback.snd g g :=
  pullback.lift_snd _ _ _

variable [Finite (ConnectedComponents ↥(pullback (pullback.snd g g) (pullback.fst g g)))]
  (P₃ : ConnectedComponents ↥(pullback (pullback.snd g g) (pullback.fst g g)) →
    (Spec (.of k) ⟶ pullback (pullback.snd g g) (pullback.fst g g)))
  (hP₃ : ∀ c, ConnectedComponents.mk (P₃ c (IsLocalRing.closedPoint k)) = c)
  (hP₃k : ∀ c, P₃ c ≫ tripleProj₂₁ g ≫ pullback.fst g g ≫ g ≫ τ = 𝟙 _)

include P₃ hP₃ hP₃k in
/-- **The cocycle condition** for the gluing isomorphism. -/
theorem isCocycle_gluingIso (Y : FEt S') :
    (fetDescentDiagram g).IsCocycle ((gluingIso hZ hZc τ hZk c₀).app Y) :=
  hom_ext_of_fiber P₃ hP₃ fun c ↦ fiber_cocycle hZ hZc τ hZk c₀ (tripleProj₂₁ g)
    (tripleProj₃₂ g) (tripleProj₃₁ g) (tripleProj₃₁_fst (g := g)).symm pullback.condition
    (tripleProj₃₁_snd (g := g)) (P₃ c) (hP₃k c) Y

/-- The étale coverings of `S'`, with the gluing isomorphism as descent datum. -/
noncomputable def sectionDatum : FEt S' ⥤ (fetDescentDiagram g).Datum where
  obj Y := ⟨Y, (gluingIso hZ hZc τ hZk c₀).app Y, isCocycle_gluingIso hZ hZc τ hZk c₀ P₃ hP₃ hP₃k Y⟩
  map f := ⟨f, (gluingIso hZ hZc τ hZk c₀).hom.naturality f⟩

end Construction

section Pinch

open ExposeV

variable {k : Type u} [Field k] [IsSepClosed k] {S S' : Scheme.{u}} {g : S' ⟶ S}
  [IsLocallyNoetherian S] [IsProper g] [Surjective g]
  (hZ : (offDiag g).Finite) (hZc : ∀ z ∈ offDiag g, IsClosed ({z} : Set ↥(pullback g g)))
  (τ : S ⟶ Spec (.of k))
  (hZk : ∀ z ∈ offDiag g, ∃ t : Spec (.of k) ⟶ pullback g g,
    t ≫ pullback.fst g g ≫ g ≫ τ = 𝟙 _ ∧ t (IsLocalRing.closedPoint k) = z)
  [ConnectedSpace S'] (c₀ : Spec (.of k) ⟶ S')
  [Finite (ConnectedComponents ↥(pullback (pullback.snd g g) (pullback.fst g g)))]
  (P₃ : ConnectedComponents ↥(pullback (pullback.snd g g) (pullback.fst g g)) →
    (Spec (.of k) ⟶ pullback (pullback.snd g g) (pullback.fst g g)))
  (hP₃ : ∀ c, ConnectedComponents.mk (P₃ c (IsLocalRing.closedPoint k)) = c)
  (hP₃k : ∀ c, P₃ c ≫ tripleProj₂₁ g ≫ pullback.fst g g ≫ g ≫ τ = 𝟙 _)

local notation "pb" => MorphismProperty.Over.pullback
  (SGA.SGA1.ExposeV.finiteEtaleHom : MorphismProperty Scheme) ⊤

/-- The pinching functor of IX.5.4 (under the hypotheses of this section, which replace SGA's,
see the module docstring): the functor `FEt S' ⥤ FEt S` obtained by descending every étale
covering of `S'` along `g` with the gluing descent datum (IX.4.12). -/
noncomputable def pinchFunctor : FEt S' ⥤ FEt S :=
  have := isEquivalence_fetComparison_of_isProper g
  sectionDatum hZ hZc τ hZk c₀ P₃ hP₃ hP₃k ⋙ (fetComparison g).asEquivalence.inverse

/-- The pinching functor is a section of the inverse image along `g`. -/
noncomputable def pinchFunctorIso :
    pinchFunctor hZ hZc τ hZk c₀ P₃ hP₃ hP₃k ⋙ FEt.pullback g ≅ 𝟭 (FEt S') :=
  have := isEquivalence_fetComparison_of_isProper g
  have e : (fetComparison g).asEquivalence.inverse ⋙ FEt.pullback g ≅
      DescentDiagram.Datum.forget (fetDescentDiagram g) :=
    (Functor.associator (fetComparison g).asEquivalence.inverse (fetComparison g)
        (DescentDiagram.Datum.forget (fetDescentDiagram g))).symm ≪≫
      Functor.isoWhiskerRight (fetComparison g).asEquivalence.counitIso _ ≪≫ Functor.leftUnitor _
  Functor.associator _ _ _ ≪≫ Functor.isoWhiskerLeft (sectionDatum hZ hZc τ hZk c₀ P₃ hP₃ hP₃k) e

/-- The pinching functor sends connected coverings to connected coverings. -/
lemma isConnected_pinchFunctor_obj (Y : FEt S') [IsConnected Y] :
    IsConnected ((pinchFunctor hZ hZc τ hZk c₀ P₃ hP₃ hP₃k).obj Y) := by
  rw [FEt.isConnected_iff_connectedSpace]
  set X := (pinchFunctor hZ hZc τ hZk c₀ P₃ hP₃ hP₃k).obj Y
  have : ConnectedSpace Y.left := FEt.connectedSpace_of_isConnected Y
  have e := ((pinchFunctorIso hZ hZc τ hZk c₀ P₃ hP₃ hP₃k).app Y)
  have hc : ConnectedSpace ((FEt.pullback g).obj X).left :=
    (Homeomorph.connectedSpace_iff ((MorphismProperty.Over.forget _ _ _ ⋙
      Over.forget _).mapIso e).hom.homeomorph).mpr (show ConnectedSpace Y.left from inferInstance)
  have : ConnectedSpace ↥(pullback X.hom g) := hc
  exact (pullback.fst X.hom g).surjective.connectedSpace (pullback.fst X.hom g).continuous

include hZ hZc τ hZk P₃ hP₃ hP₃k in
/-- **IX.5.4, consequence**: if `π₁(S)` is topologically finitely generated, so is `π₁(S')`.
The proof makes `π₁(S')` a continuous quotient of `π₁(S)`: the pinching functor, a section of
`g^*`, preserves connectedness (V.6.9, `ExposeX.autWhiskerLeft_surjective_of_isConnected`).

SGA's hypotheses (`g` finite of finite presentation, `T ⊆ S` discrete, `n(s) = 1` geometric point
in the fibre over each `s ∉ T`) are replaced by the following ones: `g : S' ⟶ S` proper and
surjective, `S` locally noetherian, `S'` connected; a separably closed field `k` with
`τ : S ⟶ Spec k`; the points of `S' ×_S S'` off the diagonal are finitely many (`hZ`) closed
points (`hZc`), each the image of a `k`-point over `τ` (`hZk`); and
`S''' = (S' ×_S S') ×_{S'} (S' ×_S S')` has finitely many connected components, each containing
the image of a `k`-point over `τ` (`P₃`, `hP₃`, `hP₃k`). The base point `c₀` of `S'` is a
`k`-point. -/
theorem _root_.SGA.SGA1.ExposeIX.isTopologicallyFG_etaleFundamentalGroup_of_pinching
    (h : ExposeXIII.IsTopologicallyFG (etaleFundamentalGroup k (c₀ ≫ g)))
    (Ω : Type u) [Field Ω] [IsSepClosed Ω] (s' : Spec (.of Ω) ⟶ S') :
    ExposeXIII.IsTopologicallyFG (etaleFundamentalGroup Ω s') := by
  have : ConnectedSpace S := g.surjective.connectedSpace g.continuous
  let H := pinchFunctor hZ hZc τ hZk c₀ P₃ hP₃ hP₃k
  let e : H ⋙ FEt.fiber k (c₀ ≫ g) ≅ FEt.fiber k c₀ :=
    Functor.isoWhiskerLeft H (FEt.pullbackFiberIso k g c₀).symm ≪≫
      (Functor.associator _ _ _).symm ≪≫
      Functor.isoWhiskerRight (pinchFunctorIso hZ hZc τ hZk c₀ P₃ hP₃ hP₃k) _ ≪≫
      Functor.leftUnitor _
  have hsurj := ExposeX.autWhiskerLeft_surjective_of_isConnected H e
    (fun Y _ ↦ isConnected_pinchFunctor_obj hZ hZc τ hZk c₀ P₃ hP₃ hP₃k Y)
  have hfg : ExposeXIII.IsTopologicallyFG (etaleFundamentalGroup k c₀) :=
    h.of_surjective (ExposeX.autWhiskerLeft H e) (ExposeX.continuous_autWhiskerLeft H e) hsurj
  obtain ⟨φ⟩ := etaleFundamentalGroup.nonempty_continuousMulEquiv k Ω c₀ s'
  exact hfg.of_surjective φ.toMulEquiv.toMonoidHom φ.continuous φ.surjective

end Pinch

end Pinching

end SGA.SGA1.ExposeIX

