/-
Copyright (c) 2026 SGAenglishpluslean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SGAenglishpluslean contributors
-/
import SGA.SGA1.ExposeIX.ProperDescentLocal

/-!
# SGA 1, Exposé IX, 6.11 over a locally noetherian base

Let `f : X ⟶ S` be proper with geometrically connected fibres, `S` locally noetherian. The kernel
of `π₁(X) → π₁(S)` is the closed normal subgroup generated by the images of the `π₁(X̄_s)`
(IX.6.11). By the abstract criterion `ker_eq_iff_forall_isCompletelyDecomposed` this amounts to:
an étale covering of `X` comes from `S` iff its inverse images on all geometric fibres `X̄_s` are
completely decomposed. This follows from IX.6.8 (`mem_essImage_iff_forall_isGeometricallyTrivial`)
and IX.6.2 for the fibres `X_s` over `κ(s)`: we compare the geometric fibre `X̄_s` of `f` with the
geometric fibre of `X_s ⟶ Spec κ(s)` at the point of `Spec κ(s)`, to which IX.6.2
(`isGeometricallyTrivial_iff_isCompletelyDecomposed_of_artinian`) applies.
-/

universe u w

open CategoryTheory Limits AlgebraicGeometry MorphismProperty PreGaloisCategory

namespace SGA.SGA1.ExposeIX

local notation "FEt" => (SGA.SGA1.ExposeV.finiteEtaleHom : MorphismProperty Scheme)
local notation "pb" => MorphismProperty.Over.pullback FEt ⊤

section CompletelyDecomposed

variable {C : Type*} [Category C] {D : Type*} [Category D]

lemma IsCompletelyDecomposed.of_iso [PreGaloisCategory C] {Z Z' : C} (e : Z ≅ Z')
    (h : IsCompletelyDecomposed Z) : IsCompletelyDecomposed Z' := by
  obtain ⟨n, ⟨e'⟩⟩ := h
  exact ⟨n, ⟨e.symm ≪≫ e'⟩⟩

/-- V.6.4: a functor of Galois categories compatible with fibre functors sends completely
decomposed objects to completely decomposed objects. -/
lemma isCompletelyDecomposed_map [GaloisCategory C] [GaloisCategory D] (H : C ⥤ D)
    (F' : D ⥤ FintypeCat.{w}) [FiberFunctor F'] [FiberFunctor (H ⋙ F')] {Z : C}
    (hZ : IsCompletelyDecomposed Z) : IsCompletelyDecomposed (H.obj Z) := by
  rw [isCompletelyDecomposed_iff (H ⋙ F')] at hZ
  rw [isCompletelyDecomposed_iff F']
  intro σ y
  exact hZ (autMap H F' σ) y

/-- The inverse image of a completely decomposed étale covering along a morphism of connected
schemes is completely decomposed. -/
lemma isCompletelyDecomposed_pullback {A B : Scheme.{u}} (φ : B ⟶ A) [ConnectedSpace A]
    [ConnectedSpace B] {Z : MorphismProperty.Over FEt ⊤ A} (hZ : IsCompletelyDecomposed Z) :
    IsCompletelyDecomposed ((pb φ).obj Z) := by
  obtain ⟨x⟩ : Nonempty B := inferInstance
  let b := SGA.SGA1.ExposeV.geometricPointAt B x
  have : FiberFunctor (pb φ ⋙ SGA.SGA1.ExposeV.FEt.fiber _ b) :=
    SGA.SGA1.ExposeV.fiberFunctor_of_iso (SGA.SGA1.ExposeV.FEt.pullbackFiberIso _ φ b).symm
  exact isCompletelyDecomposed_map (pb φ) (SGA.SGA1.ExposeV.FEt.fiber _ b) hZ

end CompletelyDecomposed

section Comparison

variable {X S : Scheme.{u}} (f : X ⟶ S) (s : S)

/-- The point of `Spec κ(s)`. -/
noncomputable abbrev residuePt : Spec (S.residueField s) := IsLocalRing.closedPoint _

/-- The residue field of `Spec κ(s)` at its point receives `κ(s)`. -/
noncomputable abbrev residuePtMap : S.residueField s ⟶ (Spec (S.residueField s)).residueField
    (residuePt s) :=
  Spec.preimage ((Spec (S.residueField s)).fromSpecResidueField (residuePt s))

/-- An embedding of algebraic closures over `κ(s) → κ(s₀)`, `s₀` the point of `Spec κ(s)`. -/
noncomputable def algClosureResidueMap : CommRingCat.of (AlgebraicClosure (S.residueField s)) ⟶
    CommRingCat.of (AlgebraicClosure ((Spec (S.residueField s)).residueField (residuePt s))) :=
  letI : Algebra (S.residueField s)
      (AlgebraicClosure ((Spec (S.residueField s)).residueField (residuePt s))) :=
    ((algebraMap ((Spec (S.residueField s)).residueField (residuePt s))
      (AlgebraicClosure ((Spec (S.residueField s)).residueField (residuePt s)))).comp
        (residuePtMap s).hom).toAlgebra
  CommRingCat.ofHom (IsAlgClosed.lift (R := S.residueField s)).toRingHom

lemma algClosureResidueMap_comp :
    CommRingCat.ofHom (algebraMap (S.residueField s) (AlgebraicClosure (S.residueField s))) ≫
        algClosureResidueMap s =
      residuePtMap s ≫ CommRingCat.ofHom (algebraMap
        ((Spec (S.residueField s)).residueField (residuePt s))
        (AlgebraicClosure ((Spec (S.residueField s)).residueField (residuePt s)))) := by
  let _ : Algebra (S.residueField s)
      (AlgebraicClosure ((Spec (S.residueField s)).residueField (residuePt s))) :=
    ((algebraMap ((Spec (S.residueField s)).residueField (residuePt s))
      (AlgebraicClosure ((Spec (S.residueField s)).residueField (residuePt s)))).comp
        (residuePtMap s).hom).toAlgebra
  ext x
  exact (IsAlgClosed.lift (R := S.residueField s)
    (S := AlgebraicClosure (S.residueField s))).commutes x

set_option backward.isDefEq.respectTransparency false in
/-- The comparison `X̄'_{s₀} ⟶ X̄_s` of the geometric fibre of `X_s ⟶ Spec κ(s)` at the point
`s₀` of `Spec κ(s)` with the geometric fibre of `f` at `s`, over `X`. -/
noncomputable def geometricFiberComparison :
    geometricFiber (f.fiberToSpecResidueField s) (residuePt s) ⟶ geometricFiber f s :=
  pullback.lift (pullback.fst _ _ ≫ (f.fiberToSpecResidueField s).fiberι (residuePt s))
    (pullback.snd _ _ ≫ Spec.map (algClosureResidueMap s)) (by
      rw [Category.assoc, Scheme.Hom.fiber_fac, pullback.condition_assoc, Category.assoc,
        ← Spec.map_comp, algClosureResidueMap_comp, Spec.map_comp, Spec.map_preimage])

set_option backward.isDefEq.respectTransparency false in
lemma geometricFiberComparison_comp :
    geometricFiberComparison f s ≫ geometricFiberι f s =
      geometricFiberι (f.fiberToSpecResidueField s) (residuePt s) ≫ f.fiberι s := by
  unfold geometricFiberComparison geometricFiberι
  rw [pullback.lift_fst_assoc, Category.assoc]

end Comparison

section GeometricFibres

variable {X S : Scheme.{u}} (f : X ⟶ S)

set_option backward.isDefEq.respectTransparency false in
/-- IX.6.2, (ii) ⇒ (i), for the fibre `X_s` of a proper `f` with geometrically connected fibres: if
the inverse image of `Y` on the geometric fibre `X̄_s` is completely decomposed, then `Y` is
geometrically trivial on `X_s`. -/
theorem isGeometricallyTrivial_of_isCompletelyDecomposed [IsProper f] [GeometricallyConnected f]
    (s : S) (Y : MorphismProperty.Over FEt ⊤ X)
    (hY : IsCompletelyDecomposed ((pb (geometricFiberι f s)).obj Y)) :
    IsGeometricallyTrivial (f.fiberToSpecResidueField s) ((pb (f.fiberι s)).obj Y) := by
  let g := f.fiberToSpecResidueField s
  let s₀ := residuePt s
  have : IsProper g := MorphismProperty.pullback_snd _ _ inferInstance
  have : IsProper (g.fiberToSpecResidueField s₀) := MorphismProperty.pullback_snd _ _ inferInstance
  have : QuasiSeparatedSpace (g.fiber s₀) :=
    quasiSeparatedSpace_of_quasiSeparated (g.fiberToSpecResidueField s₀)
  have hg : GeometricallyConnected (g.fiberToSpecResidueField s₀) := inferInstance
  have hA : ∃ A : CommRingCat.{u}, IsArtinianRing A ∧ IsLocalRing A ∧
      Nonempty (Spec (S.residueField s) ≅ Spec A) :=
    ⟨S.residueField s, inferInstance, inferInstance, ⟨Iso.refl _⟩⟩
  have := connectedSpace_geometricFiber g s₀ hg
  have := connectedSpace_geometricFiber f s inferInstance
  obtain ⟨x⟩ : Nonempty (geometricFiber g s₀) := inferInstance
  let b := SGA.SGA1.ExposeV.geometricPointAt _ x
  let ι := geometricFiberι g s₀
  let F'' := SGA.SGA1.ExposeV.FEt.fiber _ b
  have : FiberFunctor (pb ι ⋙ F'') :=
    SGA.SGA1.ExposeV.fiberFunctor_of_iso (SGA.SGA1.ExposeV.FEt.pullbackFiberIso _ ι b).symm
  have : FiberFunctor (pb g ⋙ pb ι ⋙ F'') :=
    SGA.SGA1.ExposeV.fiberFunctor_of_iso (Functor.isoWhiskerLeft (pb g)
      (SGA.SGA1.ExposeV.FEt.pullbackFiberIso _ ι b) ≪≫
        SGA.SGA1.ExposeV.FEt.pullbackFiberIso _ g (b ≫ ι)).symm
  rw [isGeometricallyTrivial_iff_isCompletelyDecomposed_of_artinian g s₀ hA hg F'']
  let φ := geometricFiberComparison f s
  let e : (pb ι).obj ((pb (f.fiberι s)).obj Y) ≅ (pb φ).obj ((pb (geometricFiberι f s)).obj Y) :=
    ((MorphismProperty.Over.pullbackComp ι (f.fiberι s)).app Y).symm ≪≫
      (MorphismProperty.Over.pullbackCongr (geometricFiberComparison_comp f s).symm).app Y ≪≫
        (MorphismProperty.Over.pullbackComp φ (geometricFiberι f s)).app Y
  exact (isCompletelyDecomposed_pullback φ hY).of_iso e.symm

/-- IX.6.2, (i) ⇔ (ii), for the fibres of a proper `f` with geometrically connected fibres: `Y` is
geometrically trivial on `X_s` iff its inverse image on the geometric fibre `X̄_s` is completely
decomposed. -/
theorem isGeometricallyTrivial_iff_isCompletelyDecomposed_geometricFiber [IsProper f]
    [GeometricallyConnected f] (s : S) (Y : MorphismProperty.Over FEt ⊤ X) :
    IsGeometricallyTrivial (f.fiberToSpecResidueField s) ((pb (f.fiberι s)).obj Y) ↔
      IsCompletelyDecomposed ((pb (geometricFiberι f s)).obj Y) := by
  refine ⟨fun ⟨Z, ⟨e⟩⟩ ↦ ?_, isGeometricallyTrivial_of_isCompletelyDecomposed f s Y⟩
  have := connectedSpace_geometricFiber f s inferInstance
  let ω := Spec.map (CommRingCat.ofHom (algebraMap (S.residueField s)
    (AlgebraicClosure (S.residueField s))))
  let p : geometricFiber f s ⟶ f.fiber s := pullback.fst _ _
  let q : geometricFiber f s ⟶ Spec (.of (AlgebraicClosure (S.residueField s))) :=
    pullback.snd _ _
  have w : p ≫ f.fiberToSpecResidueField s = q ≫ ω := pullback.condition
  -- `Z ⊗ κ(s)‾` is completely decomposed (V.8), hence so is its inverse image on `X̄_s`
  have hZ : IsCompletelyDecomposed ((pb ω).obj Z) :=
    SGA.SGA1.ExposeV.FEt.exists_iso_sigma_terminal _ _
  let e' : (pb q).obj ((pb ω).obj Z) ≅ (pb (geometricFiberι f s)).obj Y :=
    ((MorphismProperty.Over.pullbackComp q ω).app Z).symm ≪≫
      ((MorphismProperty.Over.pullbackCongr w).app Z).symm ≪≫
        (MorphismProperty.Over.pullbackComp p (f.fiberToSpecResidueField s)).app Z ≪≫
          (pb p).mapIso e ≪≫ ((MorphismProperty.Over.pullbackComp p (f.fiberι s)).app Y).symm
  exact (isCompletelyDecomposed_pullback q hZ).of_iso e'

/-- **IX.6.11 over a locally noetherian base** (the conclusion of `GeometricFibresStatement`, the
hypotheses of finite presentation and connectedness of `X` not being needed): for `f : X ⟶ S`
proper and surjective with geometrically connected fibres, `S` locally noetherian, the kernel of
`π₁(X) → π₁(S)` is the closed normal subgroup generated by the images of the `π₁(X̄_s) → π₁(X)`,
`s ∈ S` (for any classes of paths `d s`). By `ker_eq_iff_forall_isCompletelyDecomposed` this is
IX.6.8 (`mem_essImage_iff_forall_isGeometricallyTrivial`) combined with IX.6.2 on the fibres
(`isGeometricallyTrivial_iff_isCompletelyDecomposed_geometricFiber`). -/
theorem ker_autMap_eq_geometricFibres_of_isLocallyNoetherian [IsLocallyNoetherian S] [IsProper f]
    [Surjective f] [GeometricallyConnected f]
    (F' : MorphismProperty.Over FEt ⊤ X ⥤ FintypeCat.{u}) [FiberFunctor F']
    [FiberFunctor (pb f ⋙ F')]
    (G : ∀ s, MorphismProperty.Over FEt ⊤ (geometricFiber f s) ⥤ FintypeCat.{u})
    [∀ s, FiberFunctor (G s)] (d : ∀ s, pb (geometricFiberι f s) ⋙ G s ≅ F') :
    (autMap (pb f) F').ker =
      (Subgroup.normalClosure (⋃ s, Set.range (pathMap F'
        (fun s ↦ pb (geometricFiberι f s)) G d s))).topologicalClosure := by
  have := SGA.SGA1.ExposeV.galoisCategory_of_fiberFunctor F'
  have := SGA.SGA1.ExposeV.galoisCategory_of_fiberFunctor (pb f ⋙ F')
  have (s : S) := SGA.SGA1.ExposeV.galoisCategory_of_fiberFunctor (G s)
  refine (ker_eq_iff_forall_isCompletelyDecomposed (pb f) F' (fun s ↦ pb (geometricFiberι f s)) G d
    (surjective_autMap_of_isProper f F')).mpr fun Y ↦ ?_
  simp only [← isGeometricallyTrivial_iff_isCompletelyDecomposed_geometricFiber f]
  exact mem_essImage_iff_forall_isGeometricallyTrivial f Y

end GeometricFibres

end SGA.SGA1.ExposeIX
