/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import Mathlib.Algebra.MvPolynomial.Funext
import Mathlib.Algebra.MvPolynomial.Monad
import Mathlib.Order.BooleanSubalgebra
import Mathlib.RingTheory.MvPolynomial.Basic
import Mathlib.Topology.Algebra.Polynomial
import Mathlib.Topology.Algebra.MvPolynomial
import Mathlib.Topology.Order.IntermediateValue
import Mathlib.Analysis.SpecialFunctions.Pow.Real

/-!
# Semialgebraic sets

A subset of `ℝ^ι` is *semialgebraic* if it is a finite Boolean combination of sets
`{x | 0 < p(x)}`, `p` a real polynomial in the coordinates (`IsSemialgebraic`). The semialgebraic
subsets of `ℝ^ι` form a Boolean subalgebra of `Set (ι → ℝ)` (`semialgebraicSets`), which contains
the zero sets and the sign conditions of polynomials and is stable under preimages by polynomial
maps (`IsSemialgebraic.preimage_polynomialMap`).

This is the first file of a library of semialgebraic geometry (Tarski–Seidenberg, cylindrical
decomposition, curve selection, Łojasiewicz inequality) aimed at the local conic structure of
real and complex algebraic sets.

## References

* [J. Bochnak, M. Coste, M.-F. Roy, *Real Algebraic Geometry*, §2.1][BCR]
-/

open Set MvPolynomial

variable {ι κ : Type*}

/-- The Boolean algebra of *semialgebraic* subsets of `ℝ^ι`: the Boolean subalgebra of
`Set (ι → ℝ)` generated by the sets `{x | 0 < p(x)}`, `p` a real polynomial. -/
def semialgebraicSets (ι : Type*) : BooleanSubalgebra (Set (ι → ℝ)) :=
  BooleanSubalgebra.closure (range fun p : MvPolynomial ι ℝ ↦ {x | 0 < eval x p})

/-- A subset of `ℝ^ι` is *semialgebraic* if it is a finite Boolean combination of sets
`{x | 0 < p(x)}`, `p` a real polynomial. -/
def IsSemialgebraic (S : Set (ι → ℝ)) : Prop := S ∈ semialgebraicSets ι

namespace IsSemialgebraic

variable {S T : Set (ι → ℝ)}

protected lemma pos (p : MvPolynomial ι ℝ) : IsSemialgebraic {x : ι → ℝ | 0 < eval x p} :=
  BooleanSubalgebra.subset_closure ⟨p, rfl⟩

protected lemma empty : IsSemialgebraic (∅ : Set (ι → ℝ)) :=
  BooleanSubalgebra.bot_mem (L := semialgebraicSets ι)

protected lemma univ : IsSemialgebraic (univ : Set (ι → ℝ)) :=
  BooleanSubalgebra.top_mem (L := semialgebraicSets ι)

protected lemma union (hS : IsSemialgebraic S) (hT : IsSemialgebraic T) :
    IsSemialgebraic (S ∪ T) :=
  BooleanSubalgebra.sup_mem hS hT

protected lemma inter (hS : IsSemialgebraic S) (hT : IsSemialgebraic T) :
    IsSemialgebraic (S ∩ T) :=
  BooleanSubalgebra.inf_mem hS hT

protected lemma compl (hS : IsSemialgebraic S) : IsSemialgebraic Sᶜ :=
  BooleanSubalgebra.compl_mem hS

@[simp] lemma compl_iff : IsSemialgebraic Sᶜ ↔ IsSemialgebraic S :=
  BooleanSubalgebra.compl_mem_iff

protected lemma diff (hS : IsSemialgebraic S) (hT : IsSemialgebraic T) :
    IsSemialgebraic (S \ T) :=
  BooleanSubalgebra.sdiff_mem hS hT

protected lemma biUnion {α : Type*} {s : Set α} (hs : s.Finite) {f : α → Set (ι → ℝ)}
    (hf : ∀ a ∈ s, IsSemialgebraic (f a)) : IsSemialgebraic (⋃ a ∈ s, f a) := by
  induction s, hs using Set.Finite.induction_on with
  | empty => simpa using IsSemialgebraic.empty
  | @insert a s _ _ ih =>
    rw [biUnion_insert]
    exact (hf a (mem_insert a s)).union (ih fun b hb ↦ hf b (mem_insert_of_mem a hb))

protected lemma biInter {α : Type*} {s : Set α} (hs : s.Finite) {f : α → Set (ι → ℝ)}
    (hf : ∀ a ∈ s, IsSemialgebraic (f a)) : IsSemialgebraic (⋂ a ∈ s, f a) := by
  rw [← compl_iff, compl_iInter₂]
  exact IsSemialgebraic.biUnion hs fun a ha ↦ (hf a ha).compl

protected lemma iUnion {α : Type*} [Finite α] {f : α → Set (ι → ℝ)}
    (hf : ∀ a, IsSemialgebraic (f a)) : IsSemialgebraic (⋃ a, f a) := by
  simpa using IsSemialgebraic.biUnion finite_univ fun a _ ↦ hf a

protected lemma iInter {α : Type*} [Finite α] {f : α → Set (ι → ℝ)}
    (hf : ∀ a, IsSemialgebraic (f a)) : IsSemialgebraic (⋂ a, f a) := by
  simpa using IsSemialgebraic.biInter finite_univ fun a _ ↦ hf a

protected lemma neg (p : MvPolynomial ι ℝ) : IsSemialgebraic {x : ι → ℝ | eval x p < 0} := by
  simpa using IsSemialgebraic.pos (-p)

protected lemma lt (p q : MvPolynomial ι ℝ) :
    IsSemialgebraic {x : ι → ℝ | eval x p < eval x q} := by
  simpa [sub_pos] using IsSemialgebraic.pos (q - p)

protected lemma le (p q : MvPolynomial ι ℝ) :
    IsSemialgebraic {x : ι → ℝ | eval x p ≤ eval x q} := by
  have : {x : ι → ℝ | eval x p ≤ eval x q} = {x | eval x q < eval x p}ᶜ := by
    ext; simp [not_lt]
  rw [this]
  exact (IsSemialgebraic.lt q p).compl

protected lemma eq (p q : MvPolynomial ι ℝ) :
    IsSemialgebraic {x : ι → ℝ | eval x p = eval x q} := by
  have : {x : ι → ℝ | eval x p = eval x q} =
      {x | eval x p ≤ eval x q} ∩ {x | eval x q ≤ eval x p} := by
    ext x; simp [le_antisymm_iff]
  rw [this]
  exact (IsSemialgebraic.le p q).inter (IsSemialgebraic.le q p)

protected lemma ne (p q : MvPolynomial ι ℝ) :
    IsSemialgebraic {x : ι → ℝ | eval x p ≠ eval x q} := by
  have : {x : ι → ℝ | eval x p ≠ eval x q} = {x | eval x p = eval x q}ᶜ := rfl
  rw [this]
  exact (IsSemialgebraic.eq p q).compl

/-- The zero set of a polynomial is semialgebraic. -/
protected lemma zero (p : MvPolynomial ι ℝ) : IsSemialgebraic {x : ι → ℝ | eval x p = 0} := by
  simpa using IsSemialgebraic.eq p 0

/-- The common zero set of finitely many polynomials is semialgebraic. -/
lemma zeroLocus {s : Set (MvPolynomial ι ℝ)} (hs : s.Finite) :
    IsSemialgebraic {x : ι → ℝ | ∀ p ∈ s, eval x p = 0} := by
  have : {x : ι → ℝ | ∀ p ∈ s, eval x p = 0} = ⋂ p ∈ s, {x | eval x p = 0} := by
    ext; simp
  rw [this]
  exact IsSemialgebraic.biInter hs fun p _ ↦ IsSemialgebraic.zero p

/-- Induction principle for semialgebraic sets. -/
@[elab_as_elim]
lemma induction {P : Set (ι → ℝ) → Prop} (pos : ∀ p : MvPolynomial ι ℝ,
      P {x | 0 < eval x p}) (empty : P ∅) (union : ∀ S T, P S → P T → P (S ∪ T))
    (compl : ∀ S, P S → P Sᶜ) {S : Set (ι → ℝ)} (hS : IsSemialgebraic S) : P S := by
  let L : BooleanSubalgebra (Set (ι → ℝ)) :=
    { carrier := {S | IsSemialgebraic S ∧ P S}
      supClosed' := fun S hS T hT ↦ ⟨hS.1.union hT.1, union S T hS.2 hT.2⟩
      infClosed' := fun S hS T hT ↦ ⟨hS.1.inter hT.1, by
        change P (S ∩ T)
        rw [← compl_compl (S ∩ T), compl_inter]
        exact compl _ (union _ _ (compl S hS.2) (compl T hT.2))⟩
      compl_mem' := fun {S} hS ↦ ⟨hS.1.compl, compl S hS.2⟩
      bot_mem' := ⟨IsSemialgebraic.empty, empty⟩ }
  have : semialgebraicSets ι ≤ L := by
    refine BooleanSubalgebra.closure_le.mpr ?_
    rintro _ ⟨p, rfl⟩
    exact ⟨IsSemialgebraic.pos p, pos p⟩
  exact (this hS).2

/-- The preimage of a semialgebraic set by a polynomial map is semialgebraic. -/
lemma preimage_polynomialMap (F : ι → MvPolynomial κ ℝ) (hS : IsSemialgebraic S) :
    IsSemialgebraic ((fun y : κ → ℝ ↦ fun i ↦ eval y (F i)) ⁻¹' S) := by
  refine IsSemialgebraic.induction (fun p ↦ ?_) IsSemialgebraic.empty
    (fun S T hS hT ↦ hS.union hT) (fun S hS ↦ hS.compl) hS
  · have : (fun y : κ → ℝ ↦ fun i ↦ eval y (F i)) ⁻¹' {x | 0 < eval x p} =
        {y | 0 < eval y (bind₁ F p)} := by
      ext y
      have : eval y (bind₁ F p) = eval (fun i ↦ eval y (F i)) p := eval₂Hom_bind₁ _ _ _ _
      simp [this]
    rw [this]
    exact IsSemialgebraic.pos _

/-- The preimage of a semialgebraic set by a change of coordinates `x ↦ x ∘ e` is
semialgebraic. -/
lemma preimage_comp (e : κ → ι) {T : Set (κ → ℝ)} (hT : IsSemialgebraic T) :
    IsSemialgebraic ((fun y : ι → ℝ ↦ y ∘ e) ⁻¹' T) := by
  simpa [Function.comp_def] using preimage_polynomialMap (fun k ↦ X (e k)) hT

end IsSemialgebraic
