/-
Copyright (c) 2026 SGAenglishpluslean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SGAenglishpluslean contributors
-/
import SGA.SGA1.ExposeXII.AnalyticAffine
import SGA.SGA1.ExposeI.Permanence

/-!
# SGA 1, Exposé XII, 2.1: comparison of the local rings of `X` and `X^an`

For `A = 𝕜[x]/(g)`, `X = Spec A` and `x ∈ X^an`, the local homomorphism
`𝒪_{X, φ(x)} → 𝒪_{X^an, x}` (`stalkComparison`) is faithfully flat (`SGA.Foundations.Analytic`)
and `𝔪_{X, φ(x)} 𝒪_{X^an, x} = 𝔪_{X^an, x}` (`map_maximalIdeal_stalkComparison`, from the jet
comparison in order `2` and Nakayama's lemma). Hence, for the local rings at `x`:

* XII.2.1 (viii): equal dimensions (`ringKrullDim_algStalk`);
* XII.2.1 (iv): `𝒪_{X, φ(x)}` is regular iff `𝒪_{X^an, x}` is (`isRegularLocalRing_algStalk_iff`);
* XII.2.1 (vi), (vii), one direction: normality and reducedness descend from `𝒪_{X^an, x}` to
  `𝒪_{X, φ(x)}` (`isIntegrallyClosed_algStalk`, `isReduced_algStalk`).

SGA also uses the converse directions (through the isomorphism of completions and the excellence of
`𝒪_{X, φ(x)}`, which mathlib does not have) and properties (ii), (iii), (v) (Cohen–Macaulay,
`(Sₙ)`, `(Rₙ)`).
-/

noncomputable section

open CategoryTheory AlgebraicGeometry AnalyticGeometry IsLocalRing

namespace SGA.SGA1.ExposeXII

namespace AffineAnalytification

variable {𝕜 : Type} [NontriviallyNormedField 𝕜] [CompleteSpace 𝕜] {n k : ℕ}
  (g : Fin k → MvPolynomial (Fin n) 𝕜) (x : (polynomialModel g).zeroSet)

lemma stalkGermHom_mem_maximalIdeal_iff (a : PresentedAlgebra g) :
    stalkGermHom g x a ∈ maximalIdeal ((analytification g).presheaf.stalk x) ↔
      a ∈ RingHom.ker (evalPoint x) := by
  obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective a
  rw [RingHom.mem_ker, evalPoint_mk, mem_maximalIdeal, mem_nonunits_iff]
  change ¬IsUnit ((analytification g).presheaf.Γgerm x (polynomialSection p)) ↔ _
  rw [isUnit_Γgerm_polynomialSection_iff, not_not]

/-- XII.2.1: the maximal ideal of `𝒪_{X^an, x}` is generated by the maximal ideal `𝔪ₓ` of `A`
(by the jet comparison in order `2` and Nakayama's lemma). -/
theorem map_stalkGermHom_ker_evalPoint :
    (RingHom.ker (evalPoint x)).map (stalkGermHom g x) =
      maximalIdeal ((analytification g).presheaf.stalk x) := by
  set N := maximalIdeal ((analytification g).presheaf.stalk x)
  refine le_antisymm (Ideal.map_le_iff_le_comap.mpr fun a ha ↦
    (stalkGermHom_mem_maximalIdeal_iff g x a).mpr ha) ?_
  have hfg : (N : Submodule _ _).FG := IsNoetherian.noetherian _
  refine Submodule.le_of_le_smul_of_le_jacobson_bot hfg (maximalIdeal_le_jacobson _) fun b hb ↦ ?_
  obtain ⟨a', ha'⟩ := (jetComparison g x 2).2 (Ideal.Quotient.mk _ b)
  obtain ⟨a, rfl⟩ := Ideal.Quotient.mk_surjective a'
  rw [Ideal.quotientMap_mk, Ideal.Quotient.eq, pow_two] at ha'
  have hga : stalkGermHom g x a ∈ N := by
    have := N.add_mem (Ideal.mul_le_left ha') hb
    rwa [sub_add_cancel] at this
  have ha : a ∈ RingHom.ker (evalPoint x) := (stalkGermHom_mem_maximalIdeal_iff g x a).mp hga
  have : b = stalkGermHom g x a - (stalkGermHom g x a - b) := by ring
  rw [this]
  exact Submodule.sub_mem_sup (Ideal.mem_map_of_mem _ ha) ha'

/-- The image `φ(x) ∈ Spec A` of `x`. -/
abbrev specPt : PrimeSpectrum (PresentedAlgebra g) := (toSpec g).base x

/-- The local ring `𝒪_{X, φ(x)}` of `X = Spec A` at the image of `x`. -/
abbrev algStalk : Type :=
  (Spec.structureSheaf (PresentedAlgebra g)).presheaf.stalk (specPt g x)

/-- The local homomorphism `𝒪_{X, φ(x)} → 𝒪_{X^an, x}`. -/
abbrev stalkComparison : algStalk g x →+* (analytification g).presheaf.stalk x :=
  ((toSpec g).stalkMap x).hom

instance : IsLocalRing (algStalk g x) :=
  (Spec.locallyRingedSpaceObj (CommRingCat.of (PresentedAlgebra g))).isLocalRing (specPt g x)

instance : IsLocalHom (stalkComparison g x) := (toSpec g).prop x

lemma stalkComparison_comp_algebraMap :
    (stalkComparison g x).comp (algebraMap (PresentedAlgebra g) (algStalk g x)) =
      stalkGermHom g x :=
  congrArg CommRingCat.Hom.hom (toStalk_stalkMap_toSpec (g := g) x)

instance : IsNoetherianRing (algStalk g x) :=
  IsLocalization.isNoetherianRing (specPt g x).asIdeal.primeCompl _ inferInstance

/-- XII.2.1: `𝔪_{X, φ(x)} 𝒪_{X^an, x} = 𝔪_{X^an, x}`. -/
theorem map_maximalIdeal_stalkComparison :
    (maximalIdeal (algStalk g x)).map (stalkComparison g x) =
      maximalIdeal ((analytification g).presheaf.stalk x) := by
  rw [← IsLocalization.AtPrime.map_eq_maximalIdeal (specPt g x).asIdeal (algStalk g x),
    Ideal.map_map, stalkComparison_comp_algebraMap, toSpec_base_asIdeal,
    map_stalkGermHom_ker_evalPoint]

section Consequences

/-- The `𝒪_{X, φ(x)}`-algebra structure of `𝒪_{X^an, x}`. -/
abbrev stalkAlgebra : Algebra (algStalk g x) ((analytification g).presheaf.stalk x) :=
  (stalkComparison g x).toAlgebra

attribute [local instance] stalkAlgebra

instance : Module.Flat (algStalk g x) ((analytification g).presheaf.stalk x) :=
  flat_stalkMap_toSpec g x

instance : Module.FaithfullyFlat (algStalk g x) ((analytification g).presheaf.stalk x) :=
  faithfullyFlat_stalkMap_toSpec g x

instance : IsLocalHom (algebraMap (algStalk g x) ((analytification g).presheaf.stalk x)) :=
  inferInstanceAs (IsLocalHom (stalkComparison g x))

/-- XII.2.1 (viii), local form: `𝒪_{X, φ(x)}` and `𝒪_{X^an, x}` have the same dimension. -/
theorem ringKrullDim_algStalk :
    ringKrullDim (algStalk g x) = ringKrullDim ((analytification g).presheaf.stalk x) :=
  ExposeI.ringKrullDim_eq_of_flat_of_map_maximalIdeal (map_maximalIdeal_stalkComparison g x)

/-- XII.2.1 (iv), local form: `𝒪_{X, φ(x)}` is regular if and only if `𝒪_{X^an, x}` is. -/
theorem isRegularLocalRing_algStalk_iff :
    IsRegularLocalRing (algStalk g x) ↔
      IsRegularLocalRing ((analytification g).presheaf.stalk x) :=
  ExposeI.isRegularLocalRing_iff_of_flat (map_maximalIdeal_stalkComparison g x)

/-- XII.2.1 (vi), local form, one direction: if `𝒪_{X^an, x}` is a normal domain, so is
`𝒪_{X, φ(x)}` (faithfully flat descent). The converse uses that `𝒪_{X, φ(x)}` is excellent. -/
theorem isIntegrallyClosed_algStalk [IsDomain ((analytification g).presheaf.stalk x)]
    [IsIntegrallyClosed ((analytification g).presheaf.stalk x)] :
    IsIntegrallyClosed (algStalk g x) :=
  have : IsDomain (algStalk g x) := isDomain_stalk_of_isDomain_stalk_analytification g x
  ExposeI.isIntegrallyClosed_of_faithfullyFlat (B := (analytification g).presheaf.stalk x)

/-- XII.2.1 (vii), local form, one direction: if `𝒪_{X^an, x}` is reduced, so is
`𝒪_{X, φ(x)}`. -/
theorem isReduced_algStalk [IsReduced ((analytification g).presheaf.stalk x)] :
    IsReduced (algStalk g x) :=
  isReduced_stalk_of_isReduced_stalk_analytification g x

end Consequences

end AffineAnalytification

end SGA.SGA1.ExposeXII
