/-
Copyright (c) 2026 SlopdeGeometrieAlgebrique contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: SlopdeGeometrieAlgebrique contributors
-/
import SGA.SGA1.ExposeXII.RiemannHigherPresentation

/-!
# The parameter algebras of presentation data

For `r ∈ A[X]` and degree bounds `κ = (k, n, N, D)`, the parameter algebra
`RiemannHigher.ParamAlg r κ` is the `A`-algebra of finite type generated by the coefficients of
`G` (monic of degree `k`), `P` (monic of degree `n` in `Y`, coefficients of degree `≤ D` in `X`),
and of the certificates `U, V, V', a, b` (degrees `≤ D`), subject to the identities
`V G + V' G' = 1`, `U r = G^N`, `a P + b ∂_Y P = G^N`. It carries the universal presentation
datum `RiemannHigher.ParamAlg.univ r κ`, and every presentation datum over `ℂ` (as an
`A`-algebra through a point `w` of `A`) is the specialization of the universal one at a point of
`ParamAlg r κ` over `w`, for suitable `κ` (`RiemannHigher.ParamAlg.exists_point`).

This is the parameter space `Q_κ` of the induction step of XII.5.1 in higher dimension
(`SGA.SGA1.ExposeXII.RiemannHigher`, step 1 (b)).
-/
noncomputable section

open Polynomial

namespace SGA.SGA1.ExposeXII.RiemannHigher

variable {A : Type} [CommRing A] [Algebra ℂ A] (r : A[X])

/-- Degree bounds `(k, n, N, D)` for presentation data. -/
abbrev Bounds : Type := ℕ × ℕ × ℕ × ℕ

namespace ParamAlg

/-- The variables: coefficients of `G`, `P`, `U`, `V`, `V'`, `a`, `b`. -/
abbrev Var (κ : Bounds) : Type :=
  Fin κ.1 ⊕ (Fin κ.2.1 × Fin (κ.2.2.2 + 1)) ⊕ Fin (κ.2.2.2 + 1) ⊕ Fin (κ.2.2.2 + 1) ⊕
    Fin (κ.2.2.2 + 1) ⊕ (Fin (κ.2.2.2 + 1) × Fin (κ.2.2.2 + 1)) ⊕
    (Fin (κ.2.2.2 + 1) × Fin (κ.2.2.2 + 1))

variable (κ : Bounds)

/-- The polynomial algebra on the variables. -/
abbrev Free : Type := MvPolynomial (Var κ) A

/-- The variable `v`, as an element of `Free`. -/
abbrev var (v : Var κ) : Free (A := A) κ := MvPolynomial.X v

/-- A polynomial in `X` of degree `≤ D` with coefficients given by `c`. -/
def poly {S : Type*} [CommRing S] (D : ℕ) (c : Fin (D + 1) → S) : S[X] :=
  ∑ j : Fin (D + 1), C (c j) * X ^ (j : ℕ)

/-- A polynomial in `X, Y` of degrees `≤ D` with coefficients given by `c`. -/
def poly₂ {S : Type*} [CommRing S] (D : ℕ) (c : Fin (D + 1) → Fin (D + 1) → S) : S[X][X] :=
  ∑ i : Fin (D + 1), C (poly D (c i)) * X ^ (i : ℕ)

/-- The universal `G`. -/
def uG {S : Type*} [CommRing S] (k : ℕ) (c : Fin k → S) : S[X] :=
  X ^ k + ∑ l : Fin k, C (c l) * X ^ (l : ℕ)

/-- The universal `P`. -/
def uP {S : Type*} [CommRing S] (n D : ℕ) (c : Fin n → Fin (D + 1) → S) : S[X][X] :=
  X ^ n + ∑ i : Fin n, C (poly D (c i)) * X ^ (i : ℕ)

lemma poly_map {S T : Type*} [CommRing S] [CommRing T] (f : S →+* T) (D : ℕ)
    (c : Fin (D + 1) → S) : (poly D c).map f = poly D (f ∘ c) := by
  simp [poly, Polynomial.map_sum]

lemma poly₂_map {S T : Type*} [CommRing S] [CommRing T] (f : S →+* T) (D : ℕ)
    (c : Fin (D + 1) → Fin (D + 1) → S) :
    (poly₂ D c).map (mapRingHom f) = poly₂ D fun i j ↦ f (c i j) := by
  simp only [poly₂, Polynomial.map_sum, Polynomial.map_mul, Polynomial.map_C, Polynomial.map_pow,
    Polynomial.map_X, coe_mapRingHom, poly_map]
  rfl

lemma uG_map {S T : Type*} [CommRing S] [CommRing T] (f : S →+* T) (k : ℕ) (c : Fin k → S) :
    (uG k c).map f = uG k (f ∘ c) := by
  simp [uG, Polynomial.map_sum]

lemma uP_map {S T : Type*} [CommRing S] [CommRing T] (f : S →+* T) (n D : ℕ)
    (c : Fin n → Fin (D + 1) → S) :
    (uP n D c).map (mapRingHom f) = uP n D fun i j ↦ f (c i j) := by
  simp only [uP, Polynomial.map_add, Polynomial.map_sum, Polynomial.map_mul, Polynomial.map_C,
    Polynomial.map_pow, Polynomial.map_X, coe_mapRingHom, poly_map]
  rfl

lemma monic_uG {S : Type*} [CommRing S] (k : ℕ) (c : Fin k → S) : (uG k c).Monic := by
  refine monic_X_pow_add ?_
  refine (degree_sum_le _ _).trans_lt ?_
  refine Finset.sup_lt_iff (WithBot.bot_lt_coe k) |>.mpr fun l _ ↦ ?_
  exact (degree_C_mul_X_pow_le _ _).trans_lt (WithBot.coe_lt_coe.mpr l.2)

lemma monic_uP {S : Type*} [CommRing S] (n D : ℕ) (c : Fin n → Fin (D + 1) → S) :
    (uP n D c).Monic := by
  refine monic_X_pow_add ?_
  refine (degree_sum_le _ _).trans_lt ?_
  refine Finset.sup_lt_iff (WithBot.bot_lt_coe n) |>.mpr fun i _ ↦ ?_
  exact (degree_C_mul_X_pow_le _ _).trans_lt (WithBot.coe_lt_coe.mpr i.2)



section Coeff

variable {S : Type*} [CommRing S]

lemma uG_coeff {p : S[X]} (hp : p.Monic) : uG p.natDegree (fun l ↦ p.coeff l) = p := by
  conv_rhs => rw [hp.as_sum]
  rw [uG, Finset.sum_range (fun i ↦ C (p.coeff i) * X ^ i)]

lemma poly_coeff (p : S[X]) {D : ℕ} (h : p.natDegree ≤ D) : poly D (fun j ↦ p.coeff j) = p := by
  conv_rhs => rw [as_sum_range_C_mul_X_pow' p (Nat.lt_succ_of_le h)]
  rw [poly, Finset.sum_range (fun j ↦ C (p.coeff j) * X ^ j)]

lemma uP_coeff {p : S[X][X]} (hp : p.Monic) {D : ℕ} (h : ∀ i, (p.coeff i).natDegree ≤ D) :
    uP p.natDegree D (fun i j ↦ (p.coeff i).coeff j) = p := by
  conv_rhs => rw [hp.as_sum]
  rw [uP, Finset.sum_range (fun i ↦ C (p.coeff i) * X ^ i)]
  simp_rw [poly_coeff _ (h _)]

lemma poly₂_coeff (p : S[X][X]) {D : ℕ} (h : p.natDegree ≤ D)
    (h' : ∀ i, (p.coeff i).natDegree ≤ D) : poly₂ D (fun i j ↦ (p.coeff i).coeff j) = p := by
  conv_rhs => rw [as_sum_range_C_mul_X_pow' p (Nat.lt_succ_of_le h)]
  rw [poly₂, Finset.sum_range (fun i ↦ C (p.coeff i) * X ^ i)]
  simp_rw [poly_coeff _ (h' _)]

lemma natDegree_coeff_le_sum (p : S[X][X]) (i : ℕ) :
    (p.coeff i).natDegree ≤ ∑ j ∈ Finset.range (p.natDegree + 1), (p.coeff j).natDegree := by
  by_cases hi : i ≤ p.natDegree
  · exact Finset.single_le_sum (f := fun j ↦ (p.coeff j).natDegree) (fun _ _ ↦ Nat.zero_le _)
      (Finset.mem_range.mpr (Nat.lt_succ_of_le hi))
  · rw [coeff_eq_zero_of_natDegree_lt (not_le.mp hi), natDegree_zero]
    exact Nat.zero_le _

end Coeff

section Universal

variable {κ}

/-- The coefficient variables of `G`. -/
abbrev cG (l : Fin κ.1) : Free (A := A) κ := var κ (.inl l)
/-- The coefficient variables of `P`. -/
abbrev cP (i : Fin κ.2.1) (j : Fin (κ.2.2.2 + 1)) : Free (A := A) κ := var κ (.inr (.inl (i, j)))
/-- The coefficient variables of `U`. -/
abbrev cU (j : Fin (κ.2.2.2 + 1)) : Free (A := A) κ := var κ (.inr (.inr (.inl j)))
/-- The coefficient variables of `V`. -/
abbrev cV (j : Fin (κ.2.2.2 + 1)) : Free (A := A) κ := var κ (.inr (.inr (.inr (.inl j))))
/-- The coefficient variables of `V'`. -/
abbrev cV' (j : Fin (κ.2.2.2 + 1)) : Free (A := A) κ :=
  var κ (.inr (.inr (.inr (.inr (.inl j)))))
/-- The coefficient variables of `a`. -/
abbrev ca (i j : Fin (κ.2.2.2 + 1)) : Free (A := A) κ :=
  var κ (.inr (.inr (.inr (.inr (.inr (.inl (i, j)))))))
/-- The coefficient variables of `b`. -/
abbrev cb (i j : Fin (κ.2.2.2 + 1)) : Free (A := A) κ :=
  var κ (.inr (.inr (.inr (.inr (.inr (.inr (i, j)))))))

variable (κ) in
/-- The first relation: `V G + V' G' - 1`. -/
def rel₁ : (Free (A := A) κ)[X] :=
  poly _ cV * uG _ cG + poly _ cV' * derivative (uG _ cG) - 1

variable (κ) in
/-- The second relation: `U r - G^N`. -/
def rel₂ : (Free (A := A) κ)[X] :=
  poly _ cU * r.map (algebraMap A (Free κ)) - uG _ cG ^ κ.2.2.1

variable (κ) in
/-- The third relation: `a P + b ∂_Y P - G^N`. -/
def rel₃ : (Free (A := A) κ)[X][X] :=
  poly₂ _ ca * uP _ _ cP + poly₂ _ cb * derivative (uP _ _ cP) - C (uG _ cG ^ κ.2.2.1)

variable (κ) in
/-- The ideal of relations. -/
def relIdeal : Ideal (Free (A := A) κ) :=
  Ideal.span (Set.range (fun i ↦ (rel₁ κ).coeff i) ∪ Set.range (fun i ↦ (rel₂ r κ).coeff i) ∪
    Set.range (fun ij : ℕ × ℕ ↦ ((rel₃ κ).coeff ij.1).coeff ij.2))

end Universal

end ParamAlg

/-- The parameter algebra `Q_κ` of presentation data with degree bounds `κ`. -/
abbrev ParamAlg (κ : Bounds) : Type := ParamAlg.Free (A := A) κ ⧸ ParamAlg.relIdeal r κ

namespace ParamAlg

variable (κ : Bounds)

/-- The quotient map onto the parameter algebra. -/
abbrev mk : Free (A := A) κ →ₐ[A] ParamAlg r κ := Ideal.Quotient.mkₐ A _

omit [Algebra ℂ A] in
lemma map_eq_zero_of_coeff_mem {p : (Free (A := A) κ)[X]} (h : ∀ i, p.coeff i ∈ relIdeal r κ) :
    p.map (mk r κ).toRingHom = 0 := by
  ext i
  rw [coeff_map, coeff_zero]
  exact Ideal.Quotient.eq_zero_iff_mem.mpr (h i)

omit [Algebra ℂ A] in
lemma map₂_eq_zero_of_coeff_mem {p : (Free (A := A) κ)[X][X]}
    (h : ∀ i j, (p.coeff i).coeff j ∈ relIdeal r κ) :
    p.map (mapRingHom (mk r κ).toRingHom) = 0 := by
  ext i j
  rw [coeff_map, coeff_zero, coe_mapRingHom, coeff_map, coeff_zero]
  exact Ideal.Quotient.eq_zero_iff_mem.mpr (h i j)

/-- The universal presentation datum over the parameter algebra. -/
def univ : PresData r (ParamAlg r κ) where
  N := κ.2.2.1
  G := (uG _ cG).map (mk r κ).toRingHom
  P := (uP _ _ cP).map (mapRingHom (mk r κ).toRingHom)
  U := (poly _ cU).map (mk r κ).toRingHom
  V := (poly _ cV).map (mk r κ).toRingHom
  V' := (poly _ cV').map (mk r κ).toRingHom
  a := (poly₂ _ ca).map (mapRingHom (mk r κ).toRingHom)
  b := (poly₂ _ cb).map (mapRingHom (mk r κ).toRingHom)
  monic_G := (monic_uG _ _).map _
  monic_P := (monic_uP _ _ _).map _
  sep_G := by
    have h := map_eq_zero_of_coeff_mem r κ (p := rel₁ κ) fun i ↦
      Ideal.subset_span (Or.inl (Or.inl ⟨i, rfl⟩))
    rw [rel₁, Polynomial.map_sub, sub_eq_zero, Polynomial.map_one, Polynomial.map_add,
      Polynomial.map_mul, Polynomial.map_mul, ← derivative_map] at h
    exact h
  sep_P := by
    have h := map₂_eq_zero_of_coeff_mem r κ (p := rel₃ κ) fun i j ↦
      Ideal.subset_span (Or.inr ⟨(i, j), rfl⟩)
    rw [rel₃, Polynomial.map_sub, sub_eq_zero, Polynomial.map_add, Polynomial.map_mul,
      Polynomial.map_mul, ← derivative_map, Polynomial.map_C, coe_mapRingHom,
      Polynomial.map_pow] at h
    exact h
  dvd_r := by
    have h := map_eq_zero_of_coeff_mem r κ (p := rel₂ r κ) fun i ↦
      Ideal.subset_span (Or.inl (Or.inr ⟨i, rfl⟩))
    rw [rel₂, Polynomial.map_sub, sub_eq_zero, Polynomial.map_mul, Polynomial.map_pow,
      Polynomial.map_map] at h
    rw [← h]
    congr 2

section Point

variable (w : Points ℂ A)

/-- **Every presentation datum over `ℂ` comes from the parameter algebra**: for a point `w` of `A`
and a presentation datum `D₀` over `ℂ` (an `A`-algebra through `w`), there are bounds `κ` and a
point `q` of `ParamAlg r κ` over `w` at which the universal datum specializes to `D₀`. -/
theorem exists_point (D₀ : letI := w.toRingHom.toAlgebra; PresData r ℂ) :
    letI := w.toRingHom.toAlgebra
    ∃ (κ : Bounds) (q : Points ℂ (ParamAlg r κ)), Points.proj A (ParamAlg r κ) q = w ∧
      (univ r κ).G.map q.toRingHom = D₀.G ∧
      (univ r κ).P.map (mapRingHom q.toRingHom) = D₀.P := by
  let := w.toRingHom.toAlgebra
  let k := D₀.G.natDegree
  let n := D₀.P.natDegree
  obtain ⟨Dd, hUd, hVd, hV'd, had, hbd, hPc, hac, hbc⟩ : ∃ Dd : ℕ, D₀.U.natDegree ≤ Dd ∧
      D₀.V.natDegree ≤ Dd ∧ D₀.V'.natDegree ≤ Dd ∧ D₀.a.natDegree ≤ Dd ∧ D₀.b.natDegree ≤ Dd ∧
      (∀ i, (D₀.P.coeff i).natDegree ≤ Dd) ∧ (∀ i, (D₀.a.coeff i).natDegree ≤ Dd) ∧
      (∀ i, (D₀.b.coeff i).natDegree ≤ Dd) :=
    ⟨D₀.U.natDegree + D₀.V.natDegree + D₀.V'.natDegree + D₀.a.natDegree + D₀.b.natDegree +
      ∑ j ∈ Finset.range (D₀.P.natDegree + 1), (D₀.P.coeff j).natDegree +
      ∑ j ∈ Finset.range (D₀.a.natDegree + 1), (D₀.a.coeff j).natDegree +
      ∑ j ∈ Finset.range (D₀.b.natDegree + 1), (D₀.b.coeff j).natDegree,
      by omega, by omega, by omega, by omega, by omega,
      fun i ↦ (natDegree_coeff_le_sum D₀.P i).trans (by omega),
      fun i ↦ (natDegree_coeff_le_sum D₀.a i).trans (by omega),
      fun i ↦ (natDegree_coeff_le_sum D₀.b i).trans (by omega)⟩
  let κ : Bounds := (k, n, D₀.N, Dd)
  let vals : Var κ → ℂ :=
    Sum.elim (fun l ↦ D₀.G.coeff l) <| Sum.elim (fun ij ↦ (D₀.P.coeff ij.1).coeff ij.2) <|
      Sum.elim (fun j ↦ D₀.U.coeff j) <| Sum.elim (fun j ↦ D₀.V.coeff j) <|
      Sum.elim (fun j ↦ D₀.V'.coeff j) <| Sum.elim (fun ij ↦ (D₀.a.coeff ij.1).coeff ij.2)
        (fun ij ↦ (D₀.b.coeff ij.1).coeff ij.2)
  let f : Free (A := A) κ →+* ℂ := MvPolynomial.eval₂Hom w.toRingHom vals
  have hf (v : Var κ) : f (MvPolynomial.X v) = vals v := MvPolynomial.eval₂Hom_X' _ _ _
  have hG : (uG _ (cG (κ := κ))).map f = D₀.G := by
    rw [uG_map]
    have : (⇑f ∘ cG (κ := κ)) = fun (l : Fin κ.1) ↦ D₀.G.coeff l := funext fun l ↦ hf _
    rw [this]
    exact uG_coeff D₀.monic_G
  have hP : (uP _ _ (cP (κ := κ))).map (mapRingHom f) = D₀.P := by
    rw [uP_map]
    have : (fun i j ↦ f (cP (κ := κ) i j)) = fun (i : Fin κ.2.1) (j : Fin (κ.2.2.2 + 1)) ↦ (D₀.P.coeff i).coeff j :=
      funext fun i ↦ funext fun j ↦ hf _
    rw [this]
    exact uP_coeff D₀.monic_P hPc
  have hU : (poly _ (cU (κ := κ))).map f = D₀.U := by
    rw [poly_map]
    have : (⇑f ∘ cU (κ := κ)) = fun (j : Fin (κ.2.2.2 + 1)) ↦ D₀.U.coeff j := funext fun j ↦ hf _
    rw [this]
    exact poly_coeff _ hUd
  have hV : (poly _ (cV (κ := κ))).map f = D₀.V := by
    rw [poly_map]
    have : (⇑f ∘ cV (κ := κ)) = fun (j : Fin (κ.2.2.2 + 1)) ↦ D₀.V.coeff j := funext fun j ↦ hf _
    rw [this]
    exact poly_coeff _ hVd
  have hV' : (poly _ (cV' (κ := κ))).map f = D₀.V' := by
    rw [poly_map]
    have : (⇑f ∘ cV' (κ := κ)) = fun (j : Fin (κ.2.2.2 + 1)) ↦ D₀.V'.coeff j := funext fun j ↦ hf _
    rw [this]
    exact poly_coeff _ hV'd
  have ha : (poly₂ _ (ca (κ := κ))).map (mapRingHom f) = D₀.a := by
    rw [poly₂_map]
    have : (fun i j ↦ f (ca (κ := κ) i j)) = fun (i j : Fin (κ.2.2.2 + 1)) ↦ (D₀.a.coeff i).coeff j :=
      funext fun i ↦ funext fun j ↦ hf _
    rw [this]
    exact poly₂_coeff _ had hac
  have hb : (poly₂ _ (cb (κ := κ))).map (mapRingHom f) = D₀.b := by
    rw [poly₂_map]
    have : (fun i j ↦ f (cb (κ := κ) i j)) = fun (i j : Fin (κ.2.2.2 + 1)) ↦ (D₀.b.coeff i).coeff j :=
      funext fun i ↦ funext fun j ↦ hf _
    rw [this]
    exact poly₂_coeff _ hbd hbc
  have hr : (r.map (algebraMap A (Free (A := A) κ))).map f = r.map (algebraMap A ℂ) := by
    rw [Polynomial.map_map]
    congr 1
    ext a
    exact MvPolynomial.eval₂Hom_C _ _ _
  have h₁ : (rel₁ κ).map f = 0 := by
    rw [rel₁, Polynomial.map_sub, Polynomial.map_add, Polynomial.map_mul, Polynomial.map_mul,
      ← derivative_map, hG, hV, hV', Polynomial.map_one, D₀.sep_G, sub_self]
  have h₂ : (rel₂ r κ).map f = 0 := by
    rw [rel₂, Polynomial.map_sub, Polynomial.map_mul, Polynomial.map_pow, hU, hr, hG, D₀.dvd_r,
      sub_self]
  have h₃ : (rel₃ κ).map (mapRingHom f) = 0 := by
    rw [rel₃, Polynomial.map_sub, Polynomial.map_add, Polynomial.map_mul, Polynomial.map_mul,
      ← derivative_map, hP, ha, hb, Polynomial.map_C, coe_mapRingHom, Polynomial.map_pow, hG,
      D₀.sep_P, sub_self]
  have hI : relIdeal r κ ≤ RingHom.ker f := by
    refine Ideal.span_le.mpr ?_
    rintro x ((⟨i, rfl⟩ | ⟨i, rfl⟩) | ⟨⟨i, j⟩, rfl⟩)
    · change f _ = 0
      rw [← coeff_map, h₁, coeff_zero]
    · change f _ = 0
      rw [← coeff_map, h₂, coeff_zero]
    · change f _ = 0
      rw [← coeff_map, ← coe_mapRingHom, ← coeff_map, h₃, coeff_zero, coeff_zero]
  let q₀ : ParamAlg r κ →+* ℂ := Ideal.Quotient.lift _ f hI
  have hq₀ (x : Free (A := A) κ) : q₀ (mk r κ x) = f x := Ideal.Quotient.lift_mk _ f hI
  let q : Points ℂ (ParamAlg r κ) := Points.ofAlgHom
    { q₀ with
      commutes' := fun c ↦ by
        change q₀ (algebraMap ℂ (ParamAlg r κ) c) = c
        rw [IsScalarTower.algebraMap_apply ℂ A (ParamAlg r κ),
          IsScalarTower.algebraMap_apply A (Free (A := A) κ) (ParamAlg r κ)]
        change q₀ (mk r κ _) = c
        rw [hq₀]
        change MvPolynomial.eval₂ _ _ (MvPolynomial.C _) = c
        rw [MvPolynomial.eval₂_C]
        exact w.commutes c }
  have hq : q.toRingHom.comp (mk r κ).toRingHom = f := RingHom.ext fun x ↦ hq₀ x
  refine ⟨κ, q, ?_, ?_, ?_⟩
  · ext a
    change q₀ (algebraMap A (ParamAlg r κ) a) = w a
    rw [IsScalarTower.algebraMap_apply A (Free (A := A) κ) (ParamAlg r κ)]
    change q₀ (mk r κ _) = w a
    rw [hq₀]
    exact MvPolynomial.eval₂_C _ _ _
  · change ((uG _ _).map _).map _ = _
    rw [Polynomial.map_map, hq, hG]
  · change ((uP _ _ _).map _).map _ = _
    rw [Polynomial.map_map, mapRingHom_comp, hq, hP]

end Point

end ParamAlg

end SGA.SGA1.ExposeXII.RiemannHigher
