name: TeX

on:
  push:
    branches: [main]
    paths:
      - "translation/**"
      - .github/workflows/tex.yml
  pull_request:
    branches: [main]
    paths:
      - "translation/**"
      - .github/workflows/tex.yml
  workflow_dispatch:

concurrency:
  group: tex-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  sga1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        expose: [I, II, III, VI]
    steps:
      - uses: actions/checkout@v5
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: SGA1-${{ matrix.expose }}.tex
          working_directory: translation/SGA1/Expose${{ matrix.expose }}
          latexmk_use_lualatex: false
      - uses: actions/upload-artifact@v4
        with:
          name: SGA1-Expose-${{ matrix.expose }}-EN
          path: translation/SGA1/Expose${{ matrix.expose }}/SGA1-${{ matrix.expose }}.pdf
